### ISSUE TITLE
DefaultDrmSession: DRM session error

### ISSUE THREAD

**Issue by Kolyall** [google/ExoPlayer#10006]
"com.google.android.exoplayer:extension-okhttp:2.16.1"
```
val client = OkHttpClient.Builder().build()

val okhttpDataSourceFactory = OkHttpDataSource.Factory(okHttpClient)

val okHttpDataSource = okhttpDataSourceFactory.createDataSource()`

val dashManifest = DashUtil.loadManifest(
                formatDataSource,
                dashManifestFileUrl
            )

val format = DashUtil.loadFormatWithDrmInitData(okHttpDataSource, dashManifest.getPeriod(0))

 val offlineLicenseHelper = OfflineLicenseHelper(
                drmSessionManager,
                /*eventDispatcher = */DrmSessionEventListener.EventDispatcher()
            )
            
             val offlineLicense = format?.let {
                offlineLicenseHelper.downloadLicense(format)
                    .also { bytes ->
                        val offlineLicenseString = String(bytes)
                        Log.d(TAG, "offlineLicense: $offlineLicenseString url: ${dashManifestFileUrl}")
                    }
            }
```
All works fine, but sometimes the error occurs:

```
2022-02-24 12:41:00.170 28319-28761/ E/DefaultDrmSession: DRM session error
      android.media.ResourceBusyException: Failed to open session
        at android.media.MediaDrm.openSession(Native Method)
        at android.media.MediaDrm.openSession(MediaDrm.java:941)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.openSession(FrameworkMediaDrm.java:177)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.openInternal(DefaultDrmSession.java:372)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:311)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:782)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:683)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:565)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:511)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.openBlockingKeyRequest(OfflineLicenseHelper.java:284)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.blockingKeyRequest(OfflineLicenseHelper.java:267)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.downloadLicense(OfflineLicenseHelper.java:194)
```

**Comment by Kolyall** [comment]
And sometimes:
```
 com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.ResourceBusyException: Failed to open session
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:540)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.openInternal(DefaultDrmSession.java:383)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:311)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:782)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:683)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:565)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:511)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.openBlockingKeyRequest(OfflineLicenseHelper.java:284)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.blockingKeyRequest(OfflineLicenseHelper.java:267)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.downloadLicense(OfflineLicenseHelper.java:194)
```

**Comment by icbaker** [comment]
`ResourceBusyException` suggests the device has reached its maximum number of concurrent DRM sessions. Are you trying to perform lots of DRM operations in parallel? 

This limit is different on different devices and is shared across all applications (similar to video/audio decoders). Some debugging ideas (in both cases you don't need to use the same `MediaDrm` instance that ExoPlayer is using, just construct your own using `new MediaDrm(C.WIDEVINE_UUID)` (assuming you're using widevine)):
* For a particular device you can query the limit using [`MediaDrm#getMaxSessionCount()`](https://developer.android.com/reference/android/media/MediaDrm#getMaxSessionCount()).
* You can also query the number of sessions when this exception is thrown by catching it and using [`MediaDrm#getOpenSessionCount()`](https://developer.android.com/reference/android/media/MediaDrm#getOpenSessionCount()).

I'm not sure there's really an ExoPlayer bug here - if the device has run out of DRM resources, there's not much we can do except propagate this exception back to the application.
