### ISSUE TITLE
Unable to access setUri method through Robolectric test runner

### ISSUE THREAD

**Issue by gsnayma01** [google/ExoPlayer#10018]
Hi,

I am using ExoPlayer for my media app in AOSP code and I have used PlayerView in my layout file.

I am trying to write the Unit tests for my app but when I run the robolectric tests it gives android.view.InflateException on  PlayerView.
I am using Android 11 and ExoPlayer 2.16.1

**Error :** 

```
 There was 1 failure:
RunMyMediaTest: 1) initComponentsTest(com.gs.mymedia.MainActivityTest)
RunMyMediaTest: android.view.InflateException: Binary XML file line #12: Binary XML file line #12: Error inflating class com.google.android.exoplayer2.ui.PlayerView
RunMyMediaTest: Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class com.google.android.exoplayer2.ui.PlayerView
RunMyMediaTest: Caused by: java.lang.reflect.InvocationTargetException
RunMyMediaTest:    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
RunMyMediaTest:    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
RunMyMediaTest:    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
RunMyMediaTest:    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createView(LayoutInflater.java:852)
RunMyMediaTest:    at android.view.LayoutInflater.createView(LayoutInflater.java)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:1004)
RunMyMediaTest:    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:959)
RunMyMediaTest:    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflate(LayoutInflater.java:1121)
RunMyMediaTest:    at android.view.LayoutInflater.rInflate(LayoutInflater.java)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflateChildren(LayoutInflater.java:1082)
RunMyMediaTest:    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:680)
RunMyMediaTest:    at android.view.LayoutInflater.inflate(LayoutInflater.java)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:532)
RunMyMediaTest:    at android.view.LayoutInflater.inflate(LayoutInflater.java)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:479)
RunMyMediaTest:    at android.view.LayoutInflater.inflate(LayoutInflater.java)
RunMyMediaTest:    at com.gs.mymedia.MainActivityTest.setUp(MainActivityTest.java:77)
RunMyMediaTest:    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
RunMyMediaTest:    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
RunMyMediaTest:    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
RunMyMediaTest:    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
RunMyMediaTest:    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
RunMyMediaTest:    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
RunMyMediaTest:    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
RunMyMediaTest:    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
RunMyMediaTest:    at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
RunMyMediaTest:    at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
RunMyMediaTest:    at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
RunMyMediaTest:    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
RunMyMediaTest:    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
RunMyMediaTest:    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
RunMyMediaTest:    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
RunMyMediaTest:    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
RunMyMediaTest:    at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
RunMyMediaTest:    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
RunMyMediaTest:    at org.junit.runners.Suite.runChild(Suite.java:128)
RunMyMediaTest:    at org.junit.runners.Suite.runChild(Suite.java:27)
RunMyMediaTest:    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
RunMyMediaTest:    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
RunMyMediaTest:    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
RunMyMediaTest:    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
RunMyMediaTest:    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
RunMyMediaTest:    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
RunMyMediaTest:    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
RunMyMediaTest:    at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
RunMyMediaTest:    at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
RunMyMediaTest:    at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
RunMyMediaTest:    at com.android.junitxml.JUnitXmlRunner.main(JUnitXmlRunner.java:98)
RunMyMediaTest: Caused by: java.lang.NoSuchMethodError: com.google.android.exoplayer2.MediaItem$Builder.setUri(Landroid/net/Uri;)Lcom/google/android/exoplayer2/MediaItem$Builder;
RunMyMediaTest:    at com.google.android.exoplayer2.Timeline$Window.<clinit>(Timeline.java:160)
RunMyMediaTest:    at com.google.android.exoplayer2.ui.PlayerControlView.<init>(PlayerControlView.java:410)
RunMyMediaTest:    at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:498)
RunMyMediaTest:    at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:318)
RunMyMediaTest:    ... 52 more
RunMyMediaTest:
RunMyMediaTest: FAILURES!!!
RunMyMediaTest: Tests run: 1,  Failures: 1
RunMyMediaTest:
```

#### build completed successfully (01:20 (mm:ss)) ####

```
@RunWith(RobolectricTestRunner.class)
public class MainActivityTest { 

    private Context mContext;

    private MainActivity mActivity;
    
    @Before
    public void setUp() throws NoSuchFieldException {
        MockitoAnnotations.initMocks(this);
        mContext = RuntimeEnvironment.application;
        mActivity = Robolectric.buildActivity(MainActivity.class).create().resume().get();
    }

    @Test
    public void initComponentsTest() {
        assertNotNull(mActivity);
    }

}
```

And here is my XML

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/root_container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center_horizontal|top"
    android:background="@color/activityBackground">

    <com.google.android.exoplayer2.ui.PlayerView
        android:id="@+id/player_view"
        app:use_controller="false"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:resize_mode="fill"/>

    </FrameLayout>
```

**Comment by marcbaechinger** [comment]
The error is thrown when static initialization of [`Timeline.EMPTY_MEDIA_ITEM`](https://github.com/google/ExoPlayer/blob/r2.16.1/library/common/src/main/java/com/google/android/exoplayer2/Timeline.java#L160) is attempted. 

I'm pretty sure this is something related to what Robolectric does. I remember we has to use @DoNotInstrument for some of our androidx unit tests to hinder Robolectric to instrument some classes which would have the result of these methods being replaced by private methods for shadowing.

I don't think you are running in the exact same problem but I think it may be similar. We were able to remove the `@DoNotInstrument` after upgrading Robolectric becasue this was more of a legacy behaviour we were seeing.

So I'd like to ask you to upgrade to the latest Robolectric version available and if this does not help let us know the version you are using and update the post here?

**Comment by gsnayma01** [comment]
Currently I am using Robolectric version 4.1

**Comment by gsnayma01** [comment]
I am using robolectric in AOSP code so I am yet to check with updated version of robolectric.

**Comment by ojw28** [comment]
Closing this because as per @marcbaechinger above, this is something to do with Robolectric rather than being a problem with ExoPlayer. There have been [over 70 issues filed on the Robolectric issue tracker about `NoSuchMethodError`](https://github.com/robolectric/robolectric/issues?q=is%3Aissue+is%3Aopen+NoSuchMethodError), so it seems to be a common problem that developers face when using it.
