### ISSUE TITLE
Crash on `MediaPeriodHolder` while doing track selection using `TrackSelectionOverrides.TrackSelectionOverride`

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#10017]
Hi,

I have a question about Exo 2.16.1.

I want to select a specific track from a `TrackGroup` so I use renderer index. Then i get the `TrackGroup`. 
Now to select a specific index, I use `selectedIndices` and passing it to `TrackSelectionOverrides.TrackSelectionOverride`

Then I call `parametersBuilder.setTrackSelectionOverrides(trackSelectionOverrides)` on `DefaultTrackSelector.ParametersBuilder` and finally I use `selector.setParameters(parametersBuilder)` on `DefaultTrackSelector`. Can see the code [here](https://github.com/kaltura/playkit-android/blob/3d94d8cc967257badd23b000bb4d256be591d6b0/playkit/src/main/java/com/kaltura/playkit/player/TrackSelectionHelper.java#L1590). 

This is changing a specific index in `TrackGroup`. Let's suppose I have 4 video renditions then i want to choose 1 rendition, i can do it in the above way.

Issue is that when i prepare another media then i get the followin exception,

``` java
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:612)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:84)
        at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:314)
        at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:259)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:193)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2209)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:505)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 

```
What I understood by this issue that when i prepare another media, internally previous overrides are retained and it tried applying it to the next media.
**So to resolve this,** I am clearing off the previous overrides by passing EMPTY , please check the code [here](https://github.com/kaltura/playkit-android/blob/3d94d8cc967257badd23b000bb4d256be591d6b0/playkit/src/main/java/com/kaltura/playkit/player/TrackSelectionHelper.java#L2062)

**NOTE:**  This question was raised a few week back in a bit different sense [here](https://github.com/google/ExoPlayer/issues/9984)

**Question**: My question is that I am on Exo 2.16.1, after clearing the previous overrides, i don't see any issue but is this the correct way of doing it in v2.16.1

Why I am emphasizing on v2.16.1 because in v2.17.0 I can see that there is some code change was done in this [commit](https://github.com/google/ExoPlayer/commit/8c90ba5db462ee0c1bfadd67a817092ee23af0eb) and now, I don't see any issue if I don't clear the overrides.

**Comment by ojw28** [comment]
As per the issue you reference, the playback failure you're seeing has been fixed in 2.17.

Clearing the overrides when preparing another piece of media probably does avoid the bug when using 2.16, although if you use ExoPlayer's playlist functionality then you may still hit the bug and have no easy way to avoid it. The best way to avoid the bug is to upgrade to a version that contains the fix.
