### ISSUE TITLE
Player fails to decode audio when using HE-AACv2 with HLS stream

### ISSUE THREAD

**Issue by sam-git2021** [google/ExoPlayer#10025]
The Issue:
-------------------------

I have some HLS streams which use HE-AACv2 (High-Efficiency AAC V2) as their audio codec.
When using ExoPlayer to play the content,
The audio is messed up and the video also interrupts a lot and loses many frames.
And I get this error:

```
 com.google.android.exoplayer2.demo E/MediaCodecAudioRenderer: Audio sink error
      com.google.android.exoplayer2.audio.AudioSink$UnexpectedDiscontinuityException: Unexpected audio track timestamp discontinuity: expected 1000001289467, got 1000001076134
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:981)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:703)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1881)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:997)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:498)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

I thought It's a device related issue, so I Enabled ffmpeg audio renderer to render the audio, I followed the ffmpeg extension guideline and enabled necessary decoders, including aac decoder.
Then I played the same stream, but got this error:

```
com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=0.93, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_DECODING_FAILED
      com.google.android.exoplayer2.ExoPlaybackException: FfmpegAudioRenderer error, index=5, format=Format(1/15, null, null, audio/mp4a-latm, mp4a.40.2, -1, uk, [-1, -1, -1.0], [1, 24000]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:574)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.ext.ffmpeg.FfmpegDecoderException: Unexpected decode error
        at com.google.android.exoplayer2.ext.ffmpeg.FfmpegAudioDecoder.createUnexpectedDecodeException(FfmpegAudioDecoder.java:95)
        at com.google.android.exoplayer2.ext.ffmpeg.FfmpegAudioDecoder.createUnexpectedDecodeException(FfmpegAudioDecoder.java:32)
        at com.google.android.exoplayer2.decoder.SimpleDecoder.decode(SimpleDecoder.java:242)
        at com.google.android.exoplayer2.decoder.SimpleDecoder.run(SimpleDecoder.java:202)
        at com.google.android.exoplayer2.decoder.SimpleDecoder.access$000(SimpleDecoder.java:29)
        at com.google.android.exoplayer2.decoder.SimpleDecoder$1.run(SimpleDecoder.java:73)
     Caused by: java.lang.IllegalArgumentException
        at java.nio.Buffer.limit(Buffer.java:290)
        at java.nio.ByteBuffer.limit(ByteBuffer.java:818)
        at com.google.android.exoplayer2.ext.ffmpeg.FfmpegAudioDecoder.decode(FfmpegAudioDecoder.java:139)
        at com.google.android.exoplayer2.ext.ffmpeg.FfmpegAudioDecoder.decode(FfmpegAudioDecoder.java:32)
        at com.google.android.exoplayer2.decoder.SimpleDecoder.decode(SimpleDecoder.java:238)
        at com.google.android.exoplayer2.decoder.SimpleDecoder.run(SimpleDecoder.java:202) 
        at com.google.android.exoplayer2.decoder.SimpleDecoder.access$000(SimpleDecoder.java:29) 
        at com.google.android.exoplayer2.decoder.SimpleDecoder$1.run(SimpleDecoder.java:73) 
    ]
```

Here is a TS file with same audio and video codec as the stream:
https://drive.google.com/file/d/1Z5UcA3XousnfQn9hoWA0YepowB8Akr7x/view?usp=sharing

 I was able to reproduce the same result in the `demo` app by adding this TS file to assets folder and to `media.exolist.json`.
try this to reproduce the issue:

```
{
        "name": "AAC_HE_V2 TS",
        "uri": "asset:///ts_output.ts"
}
```

**Comment by ojw28** [comment]
VLC on my Macbook plays the file with exactly the same type of audio corruption (although Chrome is able to play it successfully). Are you sure there isn't something wrong with the encoding of the file itself, given VLC and ExoPlayer both seem to exhibit similar issues playing it back?

**Comment by sam-git2021** [comment]
There are some other non-android devices which play the same stream, it was working fine.
That's why I thought This could be an issue from the player.
Now I believe the issue comes from the stream itself, but the non-android device somehow ignores it and plays the stream with no corruption.

Thanks for your time.
