### ISSUE TITLE
VerifyError on api < 19

### ISSUE THREAD

**Issue by barisahmet** [google/ExoPlayer#10022]
I have upgraded ExoPlayer version of my application. I was using **2.13.3** without problem. After I updated it to **2.17.0**, 90% of my users with Android 4.x.x versions can't use my application because it throws VerifyError. Mostly Samsung devices. I have read changelogs but couldn't find any related changes. It may be a bug.

MinApi : 16

Here is the full stacktrace: 

```
java.lang.VerifyError: android/support/v4/media/b
    at com.google.android.exoplayer2.util.Util.<clinit>(Util.java:141)
    at com.google.android.exoplayer2.ui.PlayerControlView.setTimeBarMinUpdateInterval(PlayerControlView.java:762)
    at com.google.android.exoplayer2.ui.PlayerControlView.<init>(PlayerControlView.java:400)
    at com.google.android.exoplayer2.ui.PlayerControlView.<init>(PlayerControlView.java:354)    at com.google.android.exoplayer2.ui.PlayerControlView.<init>(PlayerControlView.java:350)
    at java.lang.reflect.Constructor.constructNative(Constructor.java)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at android.view.LayoutInflater.createView(LayoutInflater.java:601)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:703)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:762)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:771)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
    at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
    at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
    at com.my.app.MainActivity.onCreate(MainActivity.java:769)
    at android.app.Activity.performCreate(Activity.java:5442)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
    at android.app.ActivityThread.access$800(ActivityThread.java:166)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5584)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
    at dalvik.system.NativeStart.main(NativeStart.java)
java.lang.reflect.InvocationTargetException: null
    at java.lang.reflect.Constructor.constructNative(Constructor.java)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at android.view.LayoutInflater.createView(LayoutInflater.java:601)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:703)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:762)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:771)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
    at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
    at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
    at com.my.app.MainActivity.onCreate(MainActivity.java:769)
    at android.app.Activity.performCreate(Activity.java:5442)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
    at android.app.ActivityThread.access$800(ActivityThread.java:166)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5584)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
    at dalvik.system.NativeStart.main(NativeStart.java)
android.view.InflateException: Binary XML file line #64: Error inflating class com.google.android.exoplayer2.ui.PlayerControlView
    at android.view.LayoutInflater.createView(LayoutInflater.java:627)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:703)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:762)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:771)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
    at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
    at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
    at com.my.app.MainActivity.onCreate(MainActivity.java:769)
    at android.app.Activity.performCreate(Activity.java:5442)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
    at android.app.ActivityThread.access$800(ActivityThread.java:166)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5584)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
    at dalvik.system.NativeStart.main(NativeStart.java)
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app/com.my.app.MainActivity}: android.view.InflateException: Binary XML file line #64: Error inflating class com.google.android.exoplayer2.ui.PlayerControlView
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
    at android.app.ActivityThread.access$800(ActivityThread.java:166)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5584)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
    at dalvik.system.NativeStart.main(NativeStart.java)
```

PlayerControlView part of main_activity.xml file:

```
<com.google.android.exoplayer2.ui.PlayerControlView
            android:id="@+id/main_player_exo"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:controller_layout_id="@layout/custom_exo_controls"
            app:repeat_toggle_modes="all|one|none"
            app:show_shuffle_button="true"
            app:show_timeout="0" />
```

custom_exo_controls.xml file:

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:tools="http://schemas.android.com/tools"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:layout_gravity="bottom"
              android:layoutDirection="ltr"
              android:background="#CC000000"
              android:orientation="vertical"
              tools:targetApi="28">

    <LinearLayout
        android:id="@+id/exo_title_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:paddingBottom="8dp"
        android:orientation="vertical"
        android:layout_below="@id/exo_seek_container">

        <TextView
            android:id="@+id/exo_title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textSize="15sp"
            android:textStyle="normal"
            android:paddingLeft="20dp"
            android:paddingRight="20dp"
            android:includeFontPadding="false"
            android:singleLine="true"
            android:ellipsize="middle"
            android:textColor="#FFBEBEBE" />
    </LinearLayout>

    <LinearLayout
        android:id="@+id/exo_seek_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="4dp"
        android:gravity="center_vertical"
        android:orientation="horizontal"
        android:layout_below="@id/exo_control_container">

        <TextView
            android:id="@id/exo_position"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textSize="14sp"
            android:textStyle="bold"
            android:paddingLeft="4dp"
            android:paddingRight="4dp"
            android:includeFontPadding="false"
            android:textColor="#FFBEBEBE" />

        <com.google.android.exoplayer2.ui.DefaultTimeBar
            android:id="@id/exo_progress"
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="26dp" />

        <TextView
            android:id="@id/exo_duration"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textSize="14sp"
            android:textStyle="bold"
            android:paddingLeft="4dp"
            android:paddingRight="4dp"
            android:includeFontPadding="false"
            android:textColor="#FFBEBEBE" />
    </LinearLayout>

    <LinearLayout
        android:id="@+id/exo_control_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:orientation="horizontal"
        android:layout_alignParentTop="true">

        <ImageButton
            android:id="@id/exo_prev"
            style="@style/ExoMediaButton.Previous" />

        <ImageButton
            android:id="@id/exo_shuffle"
            style="@style/ExoMediaButton" />

        <ImageButton
            android:id="@id/exo_repeat_toggle"
            style="@style/ExoMediaButton" />

        <ImageButton android:id="@id/exo_play"
                     style="@style/ExoMediaButton.Play"/>

        <ImageButton android:id="@id/exo_pause"
                     style="@style/ExoMediaButton.Pause"/>

        <ImageButton android:id="@id/exo_next"
                     style="@style/ExoMediaButton.Next"/>

    </LinearLayout>



    <TextView
        android:id="@+id/exo_hide"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textColor="@color/black"
        android:background="#33FFFFFF"
        android:padding="8dp"
        android:layout_alignParentTop="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true" />


</RelativeLayout>
```

**Comment by marcbaechinger** [comment]
I can not reproduce this with the demo app on on a Nexus 5 with API 19 (see below).

Can you try this with the [ExoPlayer demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main) on such a device and then when it crashes create a [bugreport](https://developer.android.com/studio/debug/bug-report) and upload here? 

If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #10022". Please also update this issue to indicate you’ve done this.


```
2022-03-03 15:18:56.734 I/ExoPlayerImpl: Init 428efc00 [AndroidXMedia3/1.0.0-alpha02] [hammerhead, Nexus 5, LGE, 19]
2022-03-03 15:18:56.904 D/EventLogger: playWhenReady [eventTime=0.00, mediaPos=0.00, window=0, true, USER_REQUEST]
2022-03-03 15:18:56.944 D/EventLogger: timeline [eventTime=0.04, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
2022-03-03 15:18:56.944 D/EventLogger:   period [?]
2022-03-03 15:18:56.944 D/EventLogger:   window [?, seekable=false, dynamic=true]
2022-03-03 15:18:56.944 D/EventLogger: ]
2022-03-03 15:18:56.944 D/EventLogger: mediaItem [eventTime=0.04, mediaPos=0.00, window=0, reason=PLAYLIST_CHANGED]
2022-03-03 15:18:56.954 D/EventLogger: state [eventTime=0.05, mediaPos=0.00, window=0, BUFFERING]
2022-03-03 15:18:57.004 D/EventLogger: loading [eventTime=0.10, mediaPos=0.00, window=0, period=0, true]
2022-03-03 15:18:57.054 D/EventLogger: surfaceSize [eventTime=0.15, mediaPos=0.00, window=0, period=0, 1080, 1701]
2022-03-03 15:18:57.364 D/EventLogger: timeline [eventTime=0.46, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
[...]
2022-03-03 15:18:58.614 D/EventLogger: videoSize [eventTime=1.72, mediaPos=0.00, window=0, period=0, 854, 380]
2022-03-03 15:18:58.624 D/EventLogger: renderedFirstFrame [eventTime=1.72, mediaPos=0.00, window=0, period=0, Surface(name=null)/@0x42817b08]
2022-03-03 15:18:58.644 D/EventLogger: state [eventTime=1.74, mediaPos=0.02, window=0, period=0, READY]
2022-03-03 15:18:58.654 D/EventLogger: isPlaying [eventTime=1.75, mediaPos=0.02, window=0, period=0, true]
```
