### ISSUE TITLE
Streaming shoutcast radio on android 4.1.2

### ISSUE THREAD

**Issue by kaltindas** [google/ExoPlayer#1003]
Hi, 

when i try to streaming following url, it doesnt work. 

http://77.223.136.16:9920/

i have tried it on lollipop and marshmallow devices, it works fine but on 4.1.2 galaxy tab it throws following error:

com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: -1

Please HELP me.. 

full stacktrace:

com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: -1
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: -1
            at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
            at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:136)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:733)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)

**Comment by ojw28** [comment]
Please try taking a look at these issues. It's almost certain one of them is what you need (probably the one about ICY Protocol):

https://github.com/google/ExoPlayer/issues?utf8=%E2%9C%93&q=Shoutcast

**Comment by atul14** [comment]
@kaltindas could you find a solution for this? If yes, please share

**Comment by kaltindas** [comment]
@atul14 

hii, the solution was easy for shoutcast.

first off all you have to replace "http" with "icy"

http://77.223.136.16:9920/
->
icy://77.223.136.16:9920/

and you have to register "ICY" protocoll in your Main Activity:

try {
            java.net.URL.setURLStreamHandlerFactory(new java.net.URLStreamHandlerFactory() {
                public java.net.URLStreamHandler createURLStreamHandler(String protocol) {
                    Log.e("ICY", "Asking for stream handler for protocol: '" + protocol + "'");
                    if ("icy".equals(protocol)) return new IcyURLStreamHandler();
                    return null;
                }
            });
        } catch (Throwable t) {
            Log.e("ICY", "Cannot set the ICY URLStreamHandler - maybe already set ? - " + t);
        }

**Comment by atul14** [comment]
@kaltindas Thanks.

This registration has to be done only once in a single app session?

And will this work for all Android versions or need to so special handling for some specific Android versions?

**Comment by kaltindas** [comment]
@atul14 
"This registration has to be done only once in a single app session?"

yes, i do register everytime on app start.  

"And will this work for all Android versions or need to so special handling for some specific Android versions?"

Min SDK for my App is 14 and i have tested this solution on API 14 and above.. it is working from 14 up to Marshmallow..
