### ISSUE TITLE
JIO Android STB : OutOfMemoryError for Exoplayer while content Playback

### ISSUE THREAD

**Issue by khushank** [google/ExoPlayer#10040]
### Issue Description
While Playing a DRM content on JIO Android TV STB , facing out of memory Error 
```
--------- beginning of crash
03-09 12:09:32.877  9651 10203 E AndroidRuntime: FATAL EXCEPTION: ExoPlayer:Playback
03-09 12:09:32.877  9651 10203 E AndroidRuntime: Process: com.jiotv.sonyliv, PID: 9651
03-09 12:09:32.877  9651 10203 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 25 byte allocation with 3992 free bytes and 3KB until OOM
03-09 12:09:32.877  9651 10203 E AndroidRuntime: 	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:96)
03-09 12:09:32.877  9651 10203 E AndroidRuntime: 	at android.media.MediaCodec.getBuffer(Native Method)
03-09 12:09:32.877  9651 10203 E AndroidRuntime: 	at android.media.MediaCodec.getOutputBuffer(MediaCodec.java:3048)
03-09 12:09:32.877  9651 10203 E AndroidRuntime: 	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.getOutputBuffer(SynchronousMediaCodecAdapter.java:133)
03-09 12:09:32.877  9651 10203 E AndroidRuntime: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1853)
03-09 12:09:32.877  9651 10203 E AndroidRuntime: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:823)
03-09 12:09:32.877  9651 10203 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
03-09 12:09:32.877  9651 10203 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
03-09 12:09:32.877  9651 10203 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
03-09 12:09:32.877  9651 10203 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
03-09 12:09:32.877  9651 10203 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

###  Reproduction steps

- Play the DRM protected content.
- Observe the crash.

###Device Details
- ExoPlayer version number : 2.15.1
- Android version : 7.0
- Android device : JIO STB Version : MCM 3000

Attaching the Full Bug report for this issue.
[bugreport-NBD92G-2022-03-09-12-17-41.zip](https://github.com/google/ExoPlayer/files/8213503/bugreport-NBD92G-2022-03-09-12-17-41.zip)

**Comment by ojw28** [comment]
The fact that the OutOfMemoryError occurs at the stack trace provided doesn't really tell you anything. The allocation being made is tiny, and the process has already consumed nearly all available heap space. This may have been done by ExoPlayer, or by something else entirely in your process.

You will most likely need to do some memory profiling to work out what's happening. [This documentation is a good place to start](https://developer.android.com/studio/profile/memory-profiler).
