### ISSUE TITLE
TimedValueQueue.java line 113 com.google.android.exoplayer2.util.TimedValueQueue.poll

### ISSUE THREAD

**Issue by lazarflorian** [google/ExoPlayer#10044]
We noticed several crashes in Firebase Crashlytics with the following stack trace:

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=4653149
       at com.google.android.exoplayer2.util.TimedValueQueue.poll(TimedValueQueue.java:113)
       at com.google.android.exoplayer2.util.TimedValueQueue.pollFloor(TimedValueQueue.java:82)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.updateOutputFormatForTime(MediaCodecRenderer.java:656)
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onProcessedTunneledBuffer(MediaCodecVideoRenderer.java:886)
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23.handleFrameRendered(MediaCodecVideoRenderer.java:1835)
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23.handleMessage(MediaCodecVideoRenderer.java:1819)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

Steps to reproduce: unknown
ADB bug report: cannot retrieve
Crashlytics log: 
[ssue_62d46943cb4a76defccd37051efcc24b_crash_session_6206F34D01030001199C47BD6EAF7A06_DNE_0_v2.log](https://github.com/google/ExoPlayer/files/8215271/ssue_62d46943cb4a76defccd37051efcc24b_crash_session_6206F34D01030001199C47BD6EAF7A06_DNE_0_v2.log)

URI and DRM: unknown

ExoPlayer version: 2.16.1, 2.12.1
Android version: 9
Android device: Technicolor UZX8020CHM (https://sites.google.com/view/droid-tv/pay-tv-provider/com-hem-tv-hub)

**Comment by ojw28** [comment]
Looking at the [source code for `TimedValueQueue` on 2.16.1](https://github.com/google/ExoPlayer/blob/r2.16.1/library/common/src/main/java/com/google/android/exoplayer2/util/TimedValueQueue.java#L113), I can't see any way that the index (`first`) used on L113 can end up being as per the stack trace:
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=4653149
```
`first` is only assigned in a couple of places in the class, either to `0` or to `first = (first + 1) % values.length;`, and it looks like `values.length == timestamps.length` since they're resized together. As far as I can see, this means `first` will always be less than the length of the array that it's indexing into. All public methods are synchronized, so I don't think there are possible race conditions here either.

The class in question is small, and so it's possible just to read the code and reason about it directly. If you have a concrete theory for what could be happening then please let us know. Else I think we'll put this down to being a weird device specific issue (e.g., memory corruption, or similar).
