### ISSUE TITLE
Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#10042]
I am getting firebase report with the following:
**Galaxy A6+**
```
Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b2dfd2b u0 com.application.service.LocalExoplayerDownloadService}
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2096)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7860)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Moto e6**
```
Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1a60cf u0 com.application.service.LocalExoplayerDownloadService}
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1915)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:215)
       at android.app.ActivityThread.main(ActivityThread.java:6939)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

**Huawai Y5 Lite**
```
Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1956)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:6861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

- ExoPlayer version number: 2.16.1
- Android version: From Android 8 to Android 11 so far
- Android device: Samsung Galaxy A6+, Motorola moto e6, HUAWEI Y5 lite

I'm using `DownloadService` class as specified in the doc https://exoplayer.dev/downloading-media.html and in https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoDownloadService.java

**LocalExoplayerDownloadService**
```kotlin
private const val JOB_ID = 7654
const val FOREGROUND_NOTIFICATION_ID = 6909
const val DOWNLOAD_NOTIFICATION_CHANNEL_ID = "download_channel"
private const val GROUP_KEY = "com.example.DOWNLOAD_SERVICE"
class LocalExoplayerDownloadService: DownloadService(
    FOREGROUND_NOTIFICATION_ID,
    DEFAULT_FOREGROUND_NOTIFICATION_UPDATE_INTERVAL,
    DOWNLOAD_NOTIFICATION_CHANNEL_ID,
    R.string.exo_download_notification_channel_name, R.string.exo_download_description
) {

    override fun getDownloadManager(): DownloadManager {
        val downloadNotificationHelper: DownloadNotificationHelper = DownloadUtil.getDownloadNotificationHelper(this)
        val downloadManager = DownloadUtil.getDownloadManager()
        downloadManager.addListener(TerminalStateNotificationHelper(this, downloadNotificationHelper)
        return downloadManager
    }

    override fun getScheduler(): PlatformScheduler? {
        return if (Util.SDK_INT >= 21) PlatformScheduler(this, JOB_ID) else null
    }

    override fun getForegroundNotification(
        downloads: MutableList<Download>,
        notMetRequirements: Int
    ): Notification {
       val nManager = NotificationManagerCompat.from(this)
       downloads.filter { it.state == Download.STATE_DOWNLOADING }.forEach {
              val notification = NotificationCompat.Builder(this, DOWNLOAD_NOTIFICATION_CHANNEL_ID)
                   .setSmallIcon(R.drawable.ic_download)
                   .setContentTitle(Util.fromUtf8Bytes(it.request.data))
                   .setProgress(100, it.percentDownloaded.roundToInt(), false)
                   .setOngoing(true)
                   .setGroup(GROUP_KEY)
                   .build()
               nManager.notify(it.request.id.toInt(), notification)
       }
       val title = if(realDownload.isNotEmpty())
            getTranslation(R.string.download_progress, realDownload.size)
        else
            getString(R.string.download_sync)
        return NotificationCompat.Builder(this, DownloadUtil.DOWNLOAD_NOTIFICATION_CHANNEL_ID)
            .setSmallIcon(R.drawable.ic_download)
            .setContentText(getString(R.string.download_current_download))
            .setContentTitle(title)
            .setContentIntent(downloadFragmentIntent)
            .setOngoing(true)
            .setShowWhen(false)
            .setGroup(GROUP_KEY)
            .setGroupSummary(true)
            .build()
}


class TerminalStateNotificationHelper(
    context: Context,
    private val notificationHelper: DownloadNotificationHelper,
) : DownloadManager.Listener {
    private val context: Context = context.applicationContext

    override fun onDownloadChanged(downloadManager: DownloadManager, download: Download, finalException: Exception?) {
        val notification: Notification? = when(download.state) {
            Download.STATE_COMPLETED -> {
                val videoPendingIntent = NavDeepLinkBuilder(context)
                    .setGraph(R.navigation.nav_graph)
                    .setDestination(R.id.videoDetails)
                    .setArguments(
                        VideoDetailsFragmentArgs.Builder(
                            download.request.id,
                            Util.fromUtf8Bytes(download.request.data)
                        ).build().toBundle()
                    )
                    .createPendingIntent()

                notificationHelper.buildDownloadCompletedNotification(
                    context,
                    R.drawable.ic_download,
                    videoPendingIntent, /* contentIntent= */
                    Util.fromUtf8Bytes(download.request.data)
                )
            }
            Download.STATE_FAILED -> {
                val removePendingIntent = PendingIntent.getBroadcast(context, REQUEST_CODE,
                    Intent(context, DownloadReceiver::class.java).apply {
                        action = DownloadService.ACTION_REMOVE_DOWNLOAD
                        putExtra(EXTRA_VIDEO_ID, download.request.id)
                    }, flags)
                notificationHelper.buildDownloadFailedNotification(
                    context,
                    R.drawable.ic_download,
                    removePendingIntent, /* contentIntent= */
                    Util.fromUtf8Bytes(download.request.data)
                )
            }
            else -> { null }
        }
        NotificationUtil.setNotification(context, download.request.id.toInt(), notification)
    }
}
```

**Manifest**
```
<application
....
  <service android:name="com.example.service.LocalExoplayerDownloadService" android:exported="false">
     <!-- This is needed for Scheduler -->
     <intent-filter>
         <action android:name="com.google.android.exoplayer.downloadService.action.RESTART"/>
         <category android:name="android.intent.category.DEFAULT"/>
     </intent-filter>
 </service>
 <service android:name="com.google.android.exoplayer2.scheduler.PlatformScheduler$PlatformSchedulerService"
     android:permission="android.permission.BIND_JOB_SERVICE"
     android:exported="true"/>
 <receiver android:name="com.example.receiver.DownloadReceiver" android:exported="false" />
</application>
```

In the hope of fixing this issue I even added this recently but I'm still getting crash report
```kotlin
class App: Application() {
       
       fun onCreate() {
              super.onCreate()
              startDownloadServices()
       }

       private fun startDownloadServices() {
        if (Build.VERSION.SDK_INT >= 26) {
            DownloadService.startForeground(this, LocalExoplayerDownloadService::class.java)
        } else {
            DownloadService.start(this, LocalExoplayerDownloadService::class.java)
        }
    }
}
```

**Comment by ojw28** [comment]
I don't really understand what notification `getForegroundNotification` is returning in your code, so that might be something to look at.

Either way, the easiest way for us to help with this would be for you to provide a simple demo app project (ideally as a GitHub repository) that we can use to reproduce the problem. I suspect there's something wrong in your application code somewhere, but without an easy way to reproduce it's hard to know exactly what.

**Comment by yoobi** [comment]
`getForegroundNotification` is showing only `Download` that have the `Download.STATE_DOWNLOADING` a bit like 
https://github.com/google/ExoPlayer/blob/f1b37bc547e7194354fe31e240afa8a8fb0b5c6c/library/core/src/main/java/com/google/android/exoplayer2/ui/DownloadNotificationHelper.java#L97

I can create a special repository for this but I couldn't reproduce the issue myself so it's kind of hard to determine if the new repository will have the same issue

**Comment by ojw28** [comment]
Isn't `getForegroundNotification` supposed to return a notification that will be used to transition the service into the foreground, rather than posting notifications directly? It can also post additional notifications directly if it wishes to do so, but it must always return one. I'm not hugely familiar with Kotlin, but I can't work out which notification your code is actually returning. I'm not sure how the code compiles.

**Comment by yoobi** [comment]
Oh damn you're totally right during copying I missed a portion of code, I'm updating

**Comment by ojw28** [comment]
The updated code looks more sensible!

I'm not sure what could be wrong, unfortunately. Using `DownloadService.startForeground` puts an extra into the intent that should cause the service to always call its own `startForeground` method, hence avoiding the crash. Is it possible you have code elsewhere in your app that also starts this service in the foreground, but creates the intent differently and in a way that doesn't cause the extra to be inserted? I think you'll probably have to debug this further on your side.

**Comment by yoobi** [comment]
Thank you for your thoughs, I'll triple-check that again and look for intent that could start the Service

**Comment by ojw28** [comment]
I don't think there's anything actionable for us here. Closing for now, but please let us know if you discover something. We'll also keep an eye out for other similar issues.

**Comment by yoobi** [comment]
Just giving some feedback, as said in the initial post I had this code at the startup of my application
```
class App: Application() {
       
       fun onCreate() {
              super.onCreate()
              startDownloadServices()
       }

       private fun startDownloadServices() {
        if (Build.VERSION.SDK_INT >= 26) {
            DownloadService.startForeground(this, LocalExoplayerDownloadService::class.java)
        } else {
            DownloadService.start(this, LocalExoplayerDownloadService::class.java)
        }
    }
}
```

after removing `startDownloadServices` I no longer have crash, it might be related to the 5 seconds delay to show a notification.
