### ISSUE TITLE
FileDataSource RandomAccessFile throw FileNotFoundException although the file url exsits

### ISSUE THREAD

**Issue by nickliwei1624** [google/ExoPlayer#10078]
Hi,

I have got one issue like below, please help to check and give some suggestion. Thank you.
1. Android Version
   Android Q, TV
2. Exoplayer Version
   2.9.0
3. reproduction steps
   a. Burn the Android Q image on TV set.
   b. mount streams server on path "/mnt/runtime/default/emulated/0/media".
   c. input "ls /mnt/runtime/default/emulated/0/media" to list the content of the path, to ensure it's ok.
   d. input "cp -r /mnt/sdcard/media/xxx.mkv /sdcard/Alarms/" to copy the mkv file to the "/sdcard/Alarms/".
   e. input "md5sum /mnt/sdcard/media/xxx.mkv" and "md5sum /sdcard/Alarms/xxx.mkv" to ensure the md5 values are the same, that is to say, the path of "/sdcard/Alarms/xxx.mkv" exists.
   f. input am start -a android.intent.action.MAIN -n com.google.android.exoplayer2.demo/.PlayerActivity -d "file:///sdcard/Alarms/xxx.mkv" to play the mkv file with Exoplayer.
4. Test Result
   The playing failed with FileNotFoundException in FileDataSource.open, like below. The issue can be reproduced with 10% probability.
```
============================================================
02-24 22:13:24.201 28740 28740 I PlayerActivity: ==onCreate success
02-24 22:13:24.204 28740 28740 I PlayerActivity: ==onStart
02-24 22:13:24.205 28740 28740 I PlayerActivity: initializePlayer contentUri:file:///sdcard/Alarms/3DMark_2003_In_8k_60Fps_Demo+AllTests_original.mkv contentType: 3
02-24 22:13:24.205 28740 28740 I PlayerActivity: initializePlayer intent:Intent { act=android.intent.action.MAIN dat=file:///sdcard/Alarms/3DMark_2003_In_8k_60Fps_Demo+AllTests_original.mkv flg=0x10000000 cmp=com.google.android.exoplayer2.demo/.PlayerActivity } action: android.intent.action.MAIN
02-24 22:13:24.267 28740 28740 I SimpleExoPlayer: SimpleExoPlayer+ renderers.length: 5
02-24 22:13:24.270 28740 28740 I ExoPlayerImpl: Init 7b1d52c [ExoPlayerLib/2.9.0] [wudangstick, STBAndroid wudangstick, Huanglong, 29]
02-24 22:13:24.294 28740 28740 I PlayerActivity: buildMediaSource type:3
02-24 22:13:24.295 28740 28740 I ExtractorMediaSource: buildMediaSource context:com.google.android.exoplayer2.demo.PlayerActivity@1b35bf5
02-24 22:13:24.297 28740 28740 I DefaultExtractorsFactory: ==DefaultExtractorsFactory ::com.google.android.exoplayer2.extractor.DefaultExtractorsFactory@3e0fd8a mContext:com.google.android.exoplayer2.demo.PlayerActivity@1b35bf5 uri:file:///sdcard/Alarms/3DMark_2003_In_8k_60Fps_Demo+AllTests_original.mkv
02-24 22:13:24.300 28740 28740 I PlayerActivity: build mediasource uri[0]: file:///sdcard/Alarms/3DMark_2003_In_8k_60Fps_Demo+AllTests_original.mkv
02-24 22:13:24.303 28740 28740 D EventLogger: state [0.01, 0.00, window=0, true, BUFFERING]
02-24 22:13:24.306 28740 29437 I MediaPeriodHolder: create MediaPeriodHolder 
02-24 22:13:24.306 28740 28740 I PlayerActivity: ==onResume
02-24 22:13:24.316 28740 29437 I DefaultExtractorsFactory: ==createExtractors this:com.google.android.exoplayer2.extractor.DefaultExtractorsFactory@3e0fd8a contextcom.google.android.exoplayer2.demo.PlayerActivity@1b35bf5
02-24 22:13:24.316 28740 29437 D UserInfo: android.media.MediaExtractor: false
02-24 22:13:24.316 28740 28740 D EventLogger: timelineChanged [0.03, 0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
02-24 22:13:24.317 28740 28740 D EventLogger:   period [?]
02-24 22:13:24.317 28740 28740 D EventLogger:   window [?, false, false]
02-24 22:13:24.317 28740 28740 D EventLogger: ]
02-24 22:13:24.337 28740 29437 I AdtsReader: AdtsReader language nullexposeId3 true
02-24 22:13:24.337 28740 28740 D EventLogger: surfaceSizeChanged [0.05, 0.00, window=0, 3840, 2160]
02-24 22:13:24.342 28740 29437 I DefaultTsPayloadReaderFactory: flags 0
02-24 22:13:24.343 28740 29437 I TsExtractor: mode 0
02-24 22:13:24.347 28740 28760 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
02-24 22:13:24.350 28740 29437 I ExtractorMediaPeriod: prepare
02-24 22:13:24.354 28740 29456 I ExtractorMediaPeriod: load():
02-24 22:13:24.359 28740 29456 I FileDataSource: open /sdcard/Alarms/3DMark_2003_In_8k_60Fps_Demo+AllTests_original.mkv
02-24 22:13:24.360 28740 29456 I FileDataSource: close
02-24 22:13:24.361 28740 29456 I ExtractorMediaPeriod: load():
02-24 22:13:24.362 28740 29456 I FileDataSource: open /sdcard/Alarms/3DMark_2003_In_8k_60Fps_Demo+AllTests_original.mkv
02-24 22:13:24.362 28740 29456 I FileDataSource: close
02-24 22:13:24.369  2649  2649 I hwservicemanager: getTransport: Cannot find entry android.hardware.graphics.mapper@3.0::IMapper/default in either framework or device manifest.
02-24 22:13:24.369 28740 28760 W Gralloc3: mapper 3.x is not supported
02-24 22:13:24.488  3324  3379 I ActivityTaskManager: Displayed com.google.android.exoplayer2.demo/.PlayerActivity: +28s769ms
02-24 22:13:24.492 28740 28740 D EventLogger: mediaPeriodCreated [0.20, 0.00, window=0, period=0]
02-24 22:13:24.492 28740 28740 D EventLogger: loading [0.20, 0.00, window=0, period=0, true]
02-24 22:13:24.498 28740 28740 E EventLogger: internalError [0.20, 0.00, window=0, period=0, loadError]
02-24 22:13:24.498 28740 28740 E EventLogger: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /sdcard/Alarms/3DMark_2003_In_8k_60Fps_Demo+AllTests_original.mkv: open failed: ENOENT (No such file or directory)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:82)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:249)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:475)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:304)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:923)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at java.lang.Thread.run(Thread.java:919)
02-24 22:13:24.498 28740 28740 E EventLogger: Caused by: java.io.FileNotFoundException: /sdcard/Alarms/3DMark_2003_In_8k_60Fps_Demo+AllTests_original.mkv: open failed: ENOENT (No such file or directory)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at libcore.io.IoBridge.open(IoBridge.java:496)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:74)
02-24 22:13:24.498 28740 28740 E EventLogger: 	... 9 more
02-24 22:13:24.498 28740 28740 E EventLogger: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at libcore.io.Linux.open(Native Method)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7267)
02-24 22:13:24.498 28740 28740 E EventLogger: 	at libcore.io.IoBridge.open(IoBridge.java:482)
02-24 22:13:24.498 28740 28740 E EventLogger: 	... 12 more
02-24 22:13:24.499 28740 28740 E EventLogger: internalError [0.21, 0.00, window=0, period=0, loadError]
02-24 22:13:24.499 28740 28740 E EventLogger: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /sdcard/Alarms/3DMark_2003_In_8k_60Fps_Demo+AllTests_original.mkv: open failed: ENOENT (No such file or directory)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:82)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:249)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:475)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:304)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:923)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at java.lang.Thread.run(Thread.java:919)
02-24 22:13:24.499 28740 28740 E EventLogger: Caused by: java.io.FileNotFoundException: /sdcard/Alarms/3DMark_2003_In_8k_60Fps_Demo+AllTests_original.mkv: open failed: ENOENT (No such file or directory)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at libcore.io.IoBridge.open(IoBridge.java:496)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:74)
02-24 22:13:24.499 28740 28740 E EventLogger: 	... 9 more
02-24 22:13:24.499 28740 28740 E EventLogger: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at libcore.io.Linux.open(Native Method)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7267)
02-24 22:13:24.499 28740 28740 E EventLogger: 	at libcore.io.IoBridge.open(IoBridge.java:482)
02-24 22:13:24.499 28740 28740 E EventLogger: 	... 12 more
===================================================================
```

**Comment by nickliwei1624** [comment]
I have checked the source code, it's RandomAccessFile throw FileDataSourceException, like below. the dataSpec.uri.getPath() is "/sdcard/Alarms/3DMark_2003_In_8k_60Fps_Demo+AllTests_original.mkv", which was ensured exists, but why RandomAccessFile would throw FileDataSourceException?
```
@Override
  public long open(DataSpec dataSpec) throws FileDataSourceException {
    try {
      // HUANGLONG add begin
      Log.i(TAG, "open " + dataSpec.uri.getPath());
      // HUANGLONG add end
      uri = dataSpec.uri;
      transferInitializing(dataSpec);
      file = new RandomAccessFile(dataSpec.uri.getPath(), "r");
      file.seek(dataSpec.position);
      bytesRemaining = dataSpec.length == C.LENGTH_UNSET ? file.length() - dataSpec.position
          : dataSpec.length;
      if (bytesRemaining < 0) {
        throw new EOFException();
      }
    } catch (IOException e) {
      throw new FileDataSourceException(e);
    }
    opened = true;
    transferStarted(dataSpec);

    return bytesRemaining;
  }
```

**Comment by ojw28** [comment]
This doesn't really sound like an ExoPlayer issue, since the same issue would presumably occur if you were to try and read the file directly with `RandomAccessFile` in your own code, without using ExoPlayer at all. I suggest you confirm that this is the case, and generalize your question to ask on StackOverflow (or to file as a standard Android issue: https://source.android.com/setup/contribute/report-bugs.

I suspect that the problem is something specific to the way you're mounting the streams server, but this doesn't fall within the scope of this issue tracker.
