### ISSUE TITLE
java.io.IOException: javax.crypto.BadPaddingException while trying to play encrypted content in Exoplayer (2.14.2).

### ISSUE THREAD

**Issue by gurmeetsingh90** [google/ExoPlayer#10074]
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.io.IOException: javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
        at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:133)
        at javax.crypto.CipherInputStream.read(CipherInputStream.java:249)
        at com.google.android.exoplayer2.source.hls.Aes128DataSource.read(Aes128DataSource.java:101)
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:92)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:283)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:159)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:141)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:150)

When reporting a bug:
-------------------------
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-MAP:URI="179603_c07a55_video_500.mp4?aka_me_pasthr=AAAAA_nfs&aka_media_format_type=hls&aka_sign=%2bw%2tWCJPsMG4%3d",BYTERANGE="800@0"
#EXT-X-I-FRAMES-ONLY
#EXT-X-KEY:METHOD=AES-128,URI="https://wwww.xyz/test/encrypted/stream_fmp4/serve.key?aka_me_session_id=AAAAAAAAAACCUx"
#EXTINF:10.000000,

- ExoPlayer version number   - 2.14.2
- Android version                 - all version 
- Android device

If there's something you don't want to post publicly, please submit the issue,
then email the link/bug report to dev.exoplayer@gmail.com using a subject in the
format "Issue #1234", where #1234 is your issue number (we don't reply to
emails).

**Comment by icbaker** [comment]
The error suggests your content is either encrypted incorrectly or you've misconfigured the HLS playlist with the wrong crypto algorithm or key info.

Do you have anything to indicate this is a bug in ExoPlayer?

**Comment by gurmeetsingh90** [comment]
Thanks, Google/Exoplayer for your reply,

Yes, the correct above issue was due to partially encrypted content.
Sorry for the late reply.


Thanks & Regards

*Gurmeet Singh*
*09711085915*
