### ISSUE TITLE
E/EventLogger: playerFailed [86.55]

### ISSUE THREAD

**Issue by abhiguru** [google/ExoPlayer#1008]
Trying to make sense of why the player keeps failing, I have played back hevc mpd before several times on the device without any issues but for some reason the video below causes repeated buffer and player failure. Any insight on what might be causing this ? 

HEVC MPD - http://video.vcu.tv/39626_3d44509789563ea63e18514faf71fdf9/39626.mpd

```
com.google.android.exoplayer.demo D/EventLogger: bandwidth [58.88, 741776, 54.37, 3192365]
com.google.android.exoplayer.demo E/EventLogger: internalError [58.88, loadError]
                                                 com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException
                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                                                     at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141)
                                                     at com.google.android.exoplayer.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61)
                                                     at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:388)
                                                     at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:256)
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:123)
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:132)
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:748)
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:177)
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.net.SocketTimeoutException
                                                     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
                                                     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                     at com.android.okio.Okio$2.read(Okio.java:113)
                                                     at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
                                                     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
                                                     at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                                                     at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141) 
                                                     at com.google.android.exoplayer.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61) 
                                                     at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:388) 
                                                     at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:256) 
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:123) 
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:132) 
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:748) 
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:177) 
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93) 
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165) 
                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                     at java.lang.Thread.run(Thread.java:818) 
com.google.android.exoplayer.demo D/EventLogger: bandwidth [67.13, 0, 8.09, 3192365]
com.google.android.exoplayer.demo E/EventLogger: internalError [67.13, loadError]
                                                 com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException
                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                                                     at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141)
                                                     at com.google.android.exoplayer.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61)
                                                     at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:388)
                                                     at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:256)
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:123)
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:132)
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:748)
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:177)
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.net.SocketTimeoutException
                                                     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
                                                     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                     at com.android.okio.Okio$2.read(Okio.java:113)
                                                     at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
                                                     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
                                                     at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                                                     at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141) 
                                                     at com.google.android.exoplayer.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61) 
                                                     at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:388) 
                                                     at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:256) 
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:123) 
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:132) 
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:748) 
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:177) 
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93) 
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165) 
                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                     at java.lang.Thread.run(Thread.java:818) 
com.google.android.exoplayer.demo D/EventLogger: bandwidth [76.36, 0, 8.10, 3192365]
com.google.android.exoplayer.demo E/EventLogger: internalError [76.37, loadError]
                                                 com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException
                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                                                     at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141)
                                                     at com.google.android.exoplayer.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61)
                                                     at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:388)
                                                     at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:256)
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:123)
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:132)
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:748)
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:177)
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.net.SocketTimeoutException
                                                     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
                                                     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                     at com.android.okio.Okio$2.read(Okio.java:113)
                                                     at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
                                                     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
                                                     at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                                                     at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141) 
                                                     at com.google.android.exoplayer.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61) 
                                                     at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:388) 
                                                     at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:256) 
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:123) 
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:132) 
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:748) 
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:177) 
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93) 
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165) 
                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                     at java.lang.Thread.run(Thread.java:818) 
com.google.android.exoplayer.demo D/EventLogger: bandwidth [86.54, 0, 8.10, 3192365]
com.google.android.exoplayer.demo E/EventLogger: internalError [86.55, loadError]
                                                 com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException
                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                                                     at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141)
                                                     at com.google.android.exoplayer.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61)
                                                     at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:388)
                                                     at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:256)
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:123)
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:132)
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:748)
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:177)
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.net.SocketTimeoutException
                                                     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
                                                     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                     at com.android.okio.Okio$2.read(Okio.java:113)
                                                     at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
                                                     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
                                                     at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                                                     at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141) 
                                                     at com.google.android.exoplayer.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61) 
                                                     at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:388) 
                                                     at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:256) 
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:123) 
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:132) 
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:748) 
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:177) 
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93) 
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165) 
                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                     at java.lang.Thread.run(Thread.java:818) 
com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal track renderer error.
                                                           com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException
                                                               at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
                                                               at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:141)
                                                               at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:438)
                                                               at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                               at android.os.Looper.loop(Looper.java:135)
                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
                                                               at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                            Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                                                               at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141)
                                                               at com.google.android.exoplayer.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61)
                                                               at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:388)
                                                               at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:256)
                                                               at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:123)
                                                               at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:132)
                                                               at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:748)
                                                               at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:177)
                                                               at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                               at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
                                                               at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                               at java.lang.Thread.run(Thread.java:818)
                                                            Caused by: java.net.SocketTimeoutException
                                                               at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
                                                               at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                               at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                               at com.android.okio.Okio$2.read(Okio.java:113)
                                                               at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
                                                               at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
                                                               at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                                                               at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141) 
                                                               at com.google.android.exoplayer.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61) 
                                                               at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:388) 
                                                               at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:256) 
                                                               at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:123) 
                                                               at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:132) 
                                                               at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:748) 
                                                               at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:177) 
                                                               at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93) 
                                                               at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165) 
                                                               at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                               at java.lang.Thread.run(Thread.java:818) 
? I/pv_hevcdec_api: pv_rkhevcdecoder_flush out
com.google.android.exoplayer.demo E/EventLogger: playerFailed [86.55]
                                                 com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException
                                                     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
                                                     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:141)
                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:438)
                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                  Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException
                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                                                     at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141)
                                                     at com.google.android.exoplayer.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61)
                                                     at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:388)
                                                     at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:256)
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:123)
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:132)
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:748)
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:177)
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.net.SocketTimeoutException
                                                     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
                                                     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                     at com.android.okio.Okio$2.read(Okio.java:113)
                                                     at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
                                                     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
                                                     at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                                                     at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141) 
                                                     at com.google.android.exoplayer.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61) 
                                                     at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:388) 
                                                     at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:256) 
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:123) 
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:132) 
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:748) 
                                                     at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:177) 
                                                     at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93) 
                                                     at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165) 
                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                     at java.lang.Thread.run(Thread.java:818) 
? I/vpu_mem_pool: pid 148, close_vpu_memory_pool:552: 
system_process W/AppOps: Bad call: specified package media under uid 1000 but it is really 1013
```

**Comment by ojw28** [comment]
Well, what would your interpretation of the log output you've pasted above be? You should be able to debug this yourself ;)...

**Comment by ojw28** [comment]
See: http://developer.android.com/reference/java/net/SocketTimeoutException.html

"This exception is thrown when a timeout expired on a socket read or accept operation."
