### ISSUE TITLE
Cache cannot be read in first app process for some older devices (Android 9-10) 

### ISSUE THREAD

**Issue by OneManMobile** [google/ExoPlayer#10090]
Hi

This is a bug that I believe should be reproducible given the setup information below.

So, the issue is that in the FIRST app process, when using ExoPlayer and a DownloadManager, there is a strange cache-read bug on some older devices. One of those devices is a Samsung S9, running Android 9. But also an older Nokia Android phone running Android 10 has the exact same bug.

The issue is in detail that you can download an HLS stream through the download manager, and it writes fine to cache. But if you try to construct a media item from a fully downloaded item like this, the playback fails:

`val mediaItem = downloadedItem.request.toMediaItem()`

**Given you are in the first app process on the mentioned older devices, exoplayer will throw an error if trying to play this item**. It is using the HlsMediaSource.Factory called DOWNLOADS_NAME_FORCE_CACHE from the configuration code below (in Koin).

The error is:

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
2022-03-18 11:22:59.246 17006-17286/xMUSIC:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:628)
2022-03-18 11:22:59.246 17006-17286/xMUSIC:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:604)
2022-03-18 11:22:59.246 17006-17286/xMUSIC:     at android.os.Handler.dispatchMessage(Handler.java:102)
2022-03-18 11:22:59.246 17006-17286/xMUSIC:     at android.os.Looper.loop(Looper.java:214)
2022-03-18 11:22:59.246 17006-17286/xMUSIC:     at android.os.HandlerThread.run(HandlerThread.java:65)
2022-03-18 11:22:59.246 17006-17286/xMUSIC: Caused by: java.io.IOException: DummyDataSource cannot be opened
2022-03-18 11:22:59.246 17006-17286/xMUSIC:     at com.google.android.exoplayer2.upstream.DummyDataSource.open(DummyDataSource.java:39)
2022-03-18 11:22:59.246 17006-17286/xMUSIC:     at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
2022-03-18 11:22:59.246 17006-17286/xMUSIC:     at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
2022-03-18 11:22:59.246 17006-17286/xMUSIC:     at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
2022-03-18 11:22:59.246 17006-17286/xMUSIC:     at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
2022-03-18 11:22:59.247 17006-17286/xMUSIC:     at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
2022-03-18 11:22:59.247 17006-17286/xMUSIC:     at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
2022-03-18 11:22:59.247 17006-17286/xMUSIC:     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
2022-03-18 11:22:59.247 17006-17286/xMUSIC:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-03-18 11:22:59.247 17006-17286/xMUSIC:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022-03-18 11:22:59.247 17006-17286/xMUSIC:     at java.lang.Thread.run(Thread.java:764)
```

So, just to repeat, if you RESTART THE APP PROCESS, then this cache issue goes away. Then everything written to cache is also read fine back. However, everything written to the cache within the first app process is still corrupt.

Below is the Koin setup of the different components. Thank you for the ExoPlayer library everyone, it is truly amazing overall.

```
    const val DOWNLOADS_NAME_CACHE_POOL = "cache_pool"
    const val DOWNLOADS_NAME_FORCE_CACHE = "force_cache"

    val module = module {

        single<DatabaseProvider>(named(DOWNLOADS_NAME_CACHE_POOL)) {
            MediaStorageDatabaseProvider(get(), "cache_index_storage")
        }
        
        single<Cache>(named(DOWNLOADS_NAME_CACHE_POOL)) {
            val context: Context = get()
            val directory = context.cacheDir
            val downloadContentDirectory = File(
                directory,
                "media-cache"
            )
            SimpleCache(
                downloadContentDirectory,
                LeastRecentlyUsedCacheEvictor(downloadContentDirectory.totalSpace),
                get<DatabaseProvider>(named(DOWNLOADS_NAME_CACHE_POOL))
            )
        }

        single<DataSource.Factory>(named(DOWNLOADS_NAME_CACHE_POOL)) {
            CacheDataSource.Factory()
                .setCache(get(named(DOWNLOADS_NAME_CACHE_POOL)))
                .setUpstreamDataSourceFactory(
                    DefaultHttpDataSource.Factory()
                )
        }

        single<HlsMediaSource.Factory>(named(DOWNLOADS_NAME_CACHE_POOL)) {
            val dataSourceFactory: DataSource.Factory = get(named(DOWNLOADS_NAME_CACHE_POOL))
            HlsMediaSource.Factory(
                dataSourceFactory,
            ).setAllowChunklessPreparation(true)
        }

        single<HlsMediaSource.Factory>(named(DOWNLOADS_NAME_FORCE_CACHE)) {
            val dataSourceFactory: DataSource.Factory = CacheDataSource.Factory()
                .setCache(get(named(DOWNLOADS_NAME_CACHE_POOL)))
                .setCacheWriteDataSinkFactory(null)

            HlsMediaSource.Factory(
                dataSourceFactory,
            ).setAllowChunklessPreparation(true)
        }
        
}
```

**Comment by ojw28** [comment]
My first guess would be that there's some component you should have a single instance of, where you actually have more than one instance. That's what most often causes this type of issue. I'm not really sure what the code above does, since I've never used Koin.

If I were you I'd (a) explore this possibility, and (b) see if the issue reproduces using our demo app running on the same device. If it does then you'll be able to provide more actionable reproduction steps for us. If it doesn't then that would point toward an issue in your code.

**Comment by OneManMobile** [comment]
Koin is a Service Locator Framework (light version dependency injection), and the "single<X>" means that it only creates one instance. I have not been able to log any double initialization of any of these components. They are all singletons.

Alternatively, I could have initialized it all in-order in a "Helper" class for the same result.

The reason I don't suspect the duplication of components is that the error does not occur on newer devices, only older ones. Newer devices can always read and write to cache on the first process it is only some older ones where any first-process cache writes are corrupted.

**Comment by ojw28** [comment]
Have you tried our demo app, and does the issue reproduce there?
