### ISSUE TITLE
Crash in android 6.0.1 Device

### ISSUE THREAD

**Issue by UtsavG93** [google/ExoPlayer#10095]
I am getting crash on Firebase Crashalytics

Fatal Exception: java.lang.RuntimeException: Unable to create service com.musicplayer.playermusic.services.MusicPlayerService: android.content.res.Resources$NotFoundException: Resource ID #0x1120015
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3883)
       at android.app.ActivityThread.access$2100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1909)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
       
       
       Caused by android.content.res.Resources$NotFoundException: Resource ID #0x1120015
       at android.content.res.Resources.getValue(Resources.java:2596)
       at android.content.res.Resources.getBoolean(Resources.java:2322)
       at android.media.AudioManager.<init>(AudioManager.java:877)
       at android.app.SystemServiceRegistry$7.createService(SystemServiceRegistry.java:314)
       at android.app.SystemServiceRegistry$7.createService(SystemServiceRegistry.java:311)
       at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:1262)
       at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:1215)
       at android.app.ContextImpl.getSystemService(ContextImpl.java:1511)
       at android.content.ContextWrapper.getSystemService(ContextWrapper.java:655)
       **at com.google.android.exoplayer2.C.generateAudioSessionIdV21(C.java:1081)**
       **at com.musicplayer.playermusic.services.MusicPlayerService.onCreate(MusicPlayerService.java:548)**
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3873)
       at android.app.ActivityThread.access$2100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1909)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
       
       
       
       in My MusicPlayerService.java onCreate()
      
       mAudioSessionId = C.generateAudioSessionIdV21(this); //here I am getting crash only in Samsung Galexy J7 android 6.0.1, only two users are getting this

**Comment by icbaker** [comment]
This doesn't look like an ExoPlayer issue, the crash is coming from deep within the platform and the [`Context.getSystemService(String)`](https://developer.android.com/reference/android/content/Context#getSystemService(java.lang.String)) method is clearly documented that:
1. [`Context.AUDIO_SERVICE`](https://developer.android.com/reference/android/content/Context#AUDIO_SERVICE) is a valid value to pass since API 1
2. Unrecognised services should result in `null` not a runtime exception: 
    > Note: When implementing this method, keep in mind that new services can be added on newer Android releases, so if you're looking for just the explicit names mentioned above, make sure to return null when you don't recognize the name — if you throw a [RuntimeException](https://developer.android.com/reference/java/lang/RuntimeException) exception instead, you're app might break on new Android releases.
   > ...
   > Returns the service or null if the name does not exist.
