### ISSUE TITLE
Cannot play mpg streams UnrecognizedInputFormatException

### ISSUE THREAD

**Issue by wazerstar** [google/ExoPlayer#10103]
Testing with

- ExoPlayer r2.17.1
- Android 11
- Nvidia Shield / Android Studio - Exoplayer demo app

```
2022-03-21 16:58:07.622 3573-3611/com.google.android.exoplayer2.demo I/exoplayer2.dem: Waiting for a blocking GC ProfileSaver
2022-03-21 16:58:14.903 3573-3573/com.google.android.exoplayer2.demo E/libc: Access denied finding property "vendor.display-size"
2022-03-21 16:58:14.912 3573-3573/com.google.android.exoplayer2.demo E/libc: Access denied finding property "vendor.display-size"
2022-03-21 16:58:14.946 3573-3573/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init 93136a3 [ExoPlayerLib/2.17.1] [generic_x86_arm, AOSP TV on x86, unknown, 30]
2022-03-21 16:58:14.981 3573-3573/com.google.android.exoplayer2.demo W/exoplayer2.dem: Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
2022-03-21 16:58:15.039 3573-3573/com.google.android.exoplayer2.demo D/EventLogger: playWhenReady [eventTime=0.00, mediaPos=0.00, window=0, true, USER_REQUEST]
2022-03-21 16:58:15.047 3573-3573/com.google.android.exoplayer2.demo D/EventLogger: timeline [eventTime=0.01, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
2022-03-21 16:58:15.047 3573-3573/com.google.android.exoplayer2.demo D/EventLogger:   period [?]
2022-03-21 16:58:15.047 3573-3573/com.google.android.exoplayer2.demo D/EventLogger:   window [?, seekable=false, dynamic=true]
2022-03-21 16:58:15.047 3573-3573/com.google.android.exoplayer2.demo D/EventLogger: ]
2022-03-21 16:58:15.047 3573-3573/com.google.android.exoplayer2.demo D/EventLogger: mediaItem [eventTime=0.01, mediaPos=0.00, window=0, reason=PLAYLIST_CHANGED]
2022-03-21 16:58:15.056 3573-3573/com.google.android.exoplayer2.demo D/EventLogger: state [eventTime=0.02, mediaPos=0.00, window=0, BUFFERING]
2022-03-21 16:58:15.142 3573-3573/com.google.android.exoplayer2.demo D/EventLogger: surfaceSize [eventTime=0.10, mediaPos=0.00, window=0, 1920, 1080]
2022-03-21 16:58:15.204 3573-3573/com.google.android.exoplayer2.demo D/EventLogger: loading [eventTime=0.17, mediaPos=0.00, window=0, period=0, true]
2022-03-21 16:58:15.204 3573-3573/com.google.android.exoplayer2.demo D/EventLogger: timeline [eventTime=0.17, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
2022-03-21 16:58:15.204 3573-3573/com.google.android.exoplayer2.demo D/EventLogger:   period [?]
2022-03-21 16:58:15.204 3573-3573/com.google.android.exoplayer2.demo D/EventLogger:   window [?, seekable=false, dynamic=false]
2022-03-21 16:58:15.204 3573-3573/com.google.android.exoplayer2.demo D/EventLogger: ]
2022-03-21 16:58:15.218 3573-3645/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (PsExtractor, FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1020)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2022-03-21 16:58:15.266 3573-3573/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=0.23, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (PsExtractor, FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1020)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
    ]
2022-03-21 16:58:15.267 3573-3573/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=0.23, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (PsExtractor, FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1020)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
    ]
2022-03-21 16:58:15.267 3573-3573/com.google.android.exoplayer2.demo D/EventLogger: loading [eventTime=0.23, mediaPos=0.00, window=0, period=0, false]
2022-03-21 16:58:15.268 3573-3573/com.google.android.exoplayer2.demo D/EventLogger: state [eventTime=0.23, mediaPos=0.00, window=0, period=0, IDLE]
```

Will sent further information to test with to email [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) when this ticket has been created.

**Comment by wazerstar** [comment]
I have now sent an email [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with m3u file to test with
