### ISSUE TITLE
Dash stream with BaseURL element after Period element fails to play

### ISSUE THREAD

**Issue by yukihiro-m-play** [google/ExoPlayer#10119]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

* Pixel3a running Android12

### Reproducible in the demo app?

Yes

### Reproduction steps

1.Play the attached media in the demo app.
A media is clear dash video include BaseUrl tag.

### Expected result

The media play successfully.

### Actual result

Playback failed and output error. 

```
2022-03-28 21:52:40.769 5969-5969/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=0.66, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:726)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:99)
```

### Media

[contents.zip](https://github.com/google/ExoPlayer/files/8362851/contents.zip)

Place the mp4 file in a different domain (https://another/clear/src/) from the mpd file.

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
I think the DASH spec defines a sequence of the elements that defines the order of the child elements as well. This would mean that the `BaseURL` element should appear before the `Period` element.

So as per title of your issue I think the issue is that the `BaseURL` in your manifest appears after the `Period` element.

Can you confirm it works when you put the `BaseURL` in the manifest according to the spec?

```
<xs:complexType name="MPDtype">
  <xs:sequence>
    <xs:element name="ProgramInformation" type="ProgramInformationType" minOccurs="0"
maxOccurs="unbounded"/>
    <xs:element name="BaseURL" type="BaseURLType" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="Location" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="Period" type="PeriodType" maxOccurs="unbounded"/>
    <xs:element name="Metrics" type="MetricsType" minOccurs="0" maxOccurs="unbounded"/>
    <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
...
```

**Comment by ojw28** [comment]
Agreed the DASH specification defines a specific ordering (and therefore the media is not spec compliant).
