### ISSUE TITLE
MediaCodecVideoRenderer error  video/avc, avc1.640033

### ISSUE THREAD

**Issue by feikai2012** [google/ExoPlayer#10123]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

vivo Y66L running Android 6.0.1

### Devices that do not reproduce the issue

mi 9 running android 11

### Reproducible in the demo app?

Yes

### Reproduction steps

Exoplayer Demo App for  build withDecoderExtensions Release

### Expected result

The media plays successfully

### Actual result
```
 playerFailed [eventTime=25.79, mediaPos=257.60, window=0, period=0, errorCode=ERROR_CODE_DECODER_INIT_FAILED
   p0.p: MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/avc, avc1.640033, -1, null, [3840, 2160, -1.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
       at p0.m1.handleMessage()
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)
   Caused by: n1.o$b: Decoder init failed: OMX.qcom.video.decoder.avc, Format(0, null, null, video/avc, avc1.640033, -1, null, [3840, 2160, -1.0], [-1, -1])
       at n1.o.I0()
       at n1.o.H0()
       at n1.o.M0()
       at com.google.android.exoplayer2.video.j.M0()
       at n1.o.U0()
       at n1.o.l()
       at p0.m1.p()
       ... 4 more
   Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
       at android.media.MediaCodec.native_configure(Native Method)
       at android.media.MediaCodec.configure(MediaCodec.java:1778)
       at n1.x$b.a()
       at n1.j.a()
       at n1.o.C0()
       ... 11 more
 ]
```
### Media

http://jhcache3.4008835316.com/jianghu/iqiyi/f01e99dc88773efe9941883d25b4f644.m3u8

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by feikai2012** [comment]
NoSupport [sizeAndRate.support, 3840x2160x-1.0] [OMX.google.h264.decoder, video/avc] [PD1621, vivo Y66, vivo, 23]

**Comment by marcbaechinger** [comment]
The device does not support the media with this resolution. 

```
[3840, 2160, -1.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
```

You need to transform the video to a lower resolution to make this work. I don't think that there is something we can do on our end.

I'm closing this issue. Please reopen when you think there is something wrong with the library.

**Comment by feikai2012** [comment]
I tested that IJKPLAYER can play with the same model. I hope that Exoplayer can support support compatibility

**Comment by feikai2012** [comment]
@marcbaechinger thanks
