### ISSUE TITLE
DRM_LICENSE_ACQUISITION_FAILED

### ISSUE THREAD

**Issue by narasimharao11** [google/ExoPlayer#10146]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

Oneplus 8T Android 11
IQOO Z6 5G Andrroid 12
Realme 8 and 9 versions

### Reproducible in the demo app?

Yes

### Reproduction steps

Hi Team,

We have recently updated the exoplayer version to 2.17.1 and we are facing issue with the live stream drm content for widevine streams.
We have hardcoded the stream url and license url in demo app and facing the same issue.

### Expected result

The media has to play succesfully without any issue.

### Actual result

We are getting playback failed error with  errorCode=ERROR_CODE_DRM_LICENSE_ACQUISITION_FAILED

E/EventLogger: playerFailed [eventTime=4.65, mediaPos=275.99, window=0, period=0, errorCode=ERROR_CODE_DRM_LICENSE_ACQUISITION_FAILED
      x0.p: Source error
        at x0.m1.G(Unknown Source:16)
        at x0.m1.handleMessage(Unknown Source:329)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:233)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: d1.o$a: d1.o0: g3.b0$e: Response code: 500
        at d1.g.u(Unknown Source:6)
        at d1.g.w(Unknown Source:15)
        at d1.g.v(Unknown Source:21)
        at d1.g.l(Unknown Source:0)
        at d1.g$e.handleMessage(Unknown Source:18)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: d1.o0: g3.b0$e: Response code: 500
        at d1.l0.c(Unknown Source:111)
        at d1.l0.a(Unknown Source:84)
        at d1.g$c.handleMessage(Unknown Source:21)
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: g3.b0$e: Response code: 500
        at g3.v.b(Unknown Source:257)
        at g3.n0.b(Unknown Source:12)
        at g3.o.a(Unknown Source:8)
        at g3.o.read(Unknown Source:7)
        at g3.o.read(Unknown Source:2)
        at i3.u0.j1(Unknown Source:9)
        at d1.l0.c(Unknown Source:47)
        at d1.l0.a(Unknown Source:84) 
        at d1.g$c.handleMessage(Unknown Source:21) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    ]

### Media

[bugreport-OnePlus8T_IND-RP1A.201005.001-2022-04-01-20-16-04.zip](https://github.com/google/ExoPlayer/files/8398832/bugreport-OnePlus8T_IND-RP1A.201005.001-2022-04-01-20-16-04.zip)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
The stack trace indicates that the license server is returning a 500 error. You should follow up with your DRM provider to understand why this is happening, as they will have access to the server logs which provide more information.

**Comment by icbaker** [comment]
Closing due to inactivity.
