### ISSUE TITLE
RTSP error not handled by Listener.onPlayerError, app crashes on invalid media

### ISSUE THREAD

**Issue by artroman** [google/ExoPlayer#10165]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

Any device, I think.
Reproduces on emulator with Android 11 (R) and Asus Tinkerboard with Android 7 (N).

### Reproducible in the demo app?

Not tested

### Reproduction steps

Start RTSP stream: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_175k.mov
Stream is missing some data because server was about to close starting this year, but URL is still accessible.

### Expected result

RTSP stream is missing some data, so playback should stop, ExoException should raise via onPlayerError(PlaybackException error) if listener is set

### Actual result

App crashes with error in log tagged by AndroidRuntime:
```
 FATAL EXCEPTION: ExoPlayer:Playback
 Process: *****, PID: 29242
 java.lang.IllegalArgumentException
 	at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
 	at com.google.android.exoplayer2.source.rtsp.RtspSessionTiming.parseTiming(RtspSessionTiming.java:66)
 	at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.onDescribeResponseReceived(RtspClient.java:683)
 	at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspResponse(RtspClient.java:598)
 	at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:507)
 	at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$com-google-android-exoplayer2-source-rtsp-RtspClient$MessageListener(RtspClient.java:500)
 	at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener$$ExternalSyntheticLambda0.run(Unknown Source:4)
 	at android.os.Handler.handleCallback(Handler.java:938)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:223)
 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

RtspSessionTiming.java:66 is 
```
      checkArgument(stopTimeMs > startTimeMs);
```
both values are set to 0.

### Media

rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_175k.mov

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by ojw28** [comment]
@claincly - Please take a look

**Comment by claincly** [comment]
I can't connect to the link provided via both VLC and ExoPlayer. A fix is on the way.
