### ISSUE TITLE
Error inflating class com.google.android.exoplayer2.ui.StyledPlayerView

### ISSUE THREAD

**Issue by dharmeshdhorajiya** [google/ExoPlayer#10180]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

* Redmi 8 Android 10
* KFMAWI Android 9
* A57  Android 6.0.1
* Redmi Note 4 6.0
See More Device Crashes from firebase. 
![Untitled](https://user-images.githubusercontent.com/30367192/163101901-43647197-7dd0-44a4-a3ff-aea6f8dad99a.png)
 

### Devices that do not reproduce the issue

* Oneplus 6T Android 11
*  Oneplus 7T Android 12

### Reproducible in the demo app?

Yes

### Reproduction steps

I found this issues from firebase Crashlytics dashboard.
I have try into my device there is no issues happening.

* I am using This are dependence.

    implementation 'com.google.android.exoplayer:exoplayer-core:2.17.1'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.17.1'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.17.1'

### Expected result

Play video successfully.

### Actual result

Fatal Exception: java.lang.RuntimeException: Unable to start activity android.view.InflateException: Binary XML file line #35: Binary XML file line #35: Error inflating class com.google.android.exoplayer2.ui.StyledPlayerView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2604)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2670)
       at android.app.ActivityThread.access$1100(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5845)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)

Caused by android.view.InflateException: Binary XML file line #35: Error inflating class com.google.android.exoplayer2.ui.StyledPlayerView
       at android.view.LayoutInflater.createView(LayoutInflater.java:649)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
       at com.vidbit.videoeditor.video.status.activity.MainActivity.onCreate(MainActivity.java:143)
       at android.app.Activity.performCreate(Activity.java:6340)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2670)
       at android.app.ActivityThread.access$1100(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5845)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)

### Media

Fatal Exception: java.lang.RuntimeException: Unable to start activity android.view.InflateException: Binary XML file line #35: Binary XML file line #35: Error inflating class com.google.android.exoplayer2.ui.StyledPlayerView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2604)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2670)
       at android.app.ActivityThread.access$1100(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5845)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)

Caused by android.view.InflateException: Binary XML file line #35: Error inflating class com.google.android.exoplayer2.ui.StyledPlayerView
       at android.view.LayoutInflater.createView(LayoutInflater.java:649)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
       at com.vidbit.videoeditor.video.status.activity.MainActivity.onCreate(MainActivity.java:143)
       at android.app.Activity.performCreate(Activity.java:6340)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2670)
       at android.app.ActivityThread.access$1100(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5845)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
> ### Reproducible in the demo app?
> Yes
> 
> ### Reproduction steps
> I found this issues from firebase Crashlytics dashboard. I have try into my device there is no issues happening.

It's unclear whether you're able to reproduce this issue in the demo app or not. Please clarify. If you are able to reproduce in the demo app, please provide a bug report taken with `adb bugreport` immediately after reproducing - please email it to dev.exoplayer@gmail.com using the subject `Issue #10180`. Please also update this issue to indicate you’ve done this.

----

The report as-is is not really actionable for us I'm afraid, as there's not enough information included to understand what might be going wrong.
