### ISSUE TITLE
Issue in Playing prefetching ADs Ima extension version 2.17.1 

### ISSUE THREAD

**Issue by nitin0331** [google/ExoPlayer#10186]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

Issue in Playing prefetching ADs using Ima extension version 2.17.1 though its playing fine with 2.10.5 version.

I have request and save ads in admanager and later on I will play those ads using saved admanager from the array list.

on version 2.10.5 its working perfectly fine and no issue with that but when i have updated my version to 2.17.1 I m getting below issue from second ads onward 

```
MessageQueue: Handler (android.os.Handler) {b90d4c8} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {b90d4c8} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:643)
        at android.os.Handler.sendMessageAtTime(Handler.java:612)
        at android.os.Handler.sendMessageDelayed(Handler.java:582)
        at android.os.Handler.sendMessage(Handler.java:519)
        at android.os.Message.sendToTarget(Message.java:416)
        at com.google.ads.interactivemedia.v3.internal.cl.a(IMASDK:1)
        at com.google.ads.interactivemedia.v3.internal.gg.j(IMASDK:1)
        at com.google.ads.interactivemedia.v3.internal.fw.s(IMASDK:5)
        at com.google.ads.interactivemedia.v3.internal.hk.M(IMASDK:9)
        at com.google.ads.interactivemedia.v3.internal.ajr.loadAd(IMASDK:11)
        at com.google.ads.interactivemedia.v3.internal.aiu.f(IMASDK:11)
        at com.google.ads.interactivemedia.v3.internal.ain.r(IMASDK:3)
        at com.google.ads.interactivemedia.v3.internal.ain.k(IMASDK:115)
        at com.google.ads.interactivemedia.v3.internal.ait.f(IMASDK:5)
        at com.google.ads.interactivemedia.v3.internal.aiq.shouldOverrideUrlLoading(IMASDK:2)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
        at org.chromium.base.compat.ApiHelperForN.shouldOverrideUrlLoading(chromium-AmazonWebView.apk-stable-60308632)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-AmazonWebView.apk-stable-60308632:14)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6194)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
```

### Devices that do not reproduce the issue

Firetv 4k 

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. request ads from server 
2. save ads on ArrayList<AdsManager>  
3. retrieve Ads one by one from the arraylist and called init on it 
4. once Ads loaded call the admanager.start() on it

### Expected result

Multiple ad should play one after the another as I have saved all the ad request response in an Arraylist of AdManager 

### Actual result

After first ad play its throwing exception after Its called start on the next admanager  from the ArrayList

```
MessageQueue: Handler (android.os.Handler) {b90d4c8} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {b90d4c8} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:643)
        at android.os.Handler.sendMessageAtTime(Handler.java:612)
        at android.os.Handler.sendMessageDelayed(Handler.java:582)
        at android.os.Handler.sendMessage(Handler.java:519)
        at android.os.Message.sendToTarget(Message.java:416)
        at com.google.ads.interactivemedia.v3.internal.cl.a(IMASDK:1)
        at com.google.ads.interactivemedia.v3.internal.gg.j(IMASDK:1)
        at com.google.ads.interactivemedia.v3.internal.fw.s(IMASDK:5)
        at com.google.ads.interactivemedia.v3.internal.hk.M(IMASDK:9)
        at com.google.ads.interactivemedia.v3.internal.ajr.loadAd(IMASDK:11)
        at com.google.ads.interactivemedia.v3.internal.aiu.f(IMASDK:11)
        at com.google.ads.interactivemedia.v3.internal.ain.r(IMASDK:3)
        at com.google.ads.interactivemedia.v3.internal.ain.k(IMASDK:115)
        at com.google.ads.interactivemedia.v3.internal.ait.f(IMASDK:5)
        at com.google.ads.interactivemedia.v3.internal.aiq.shouldOverrideUrlLoading(IMASDK:2)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
        at org.chromium.base.compat.ApiHelperForN.shouldOverrideUrlLoading(chromium-AmazonWebView.apk-stable-60308632)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-AmazonWebView.apk-stable-60308632:14)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6194)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
```

### Media

Not applicable

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
From the stack trace I think the exception happens without any ExoPlayer library or extension classes being involved.

It's a bit unclear to me how you are using the IMA extension. I think you should not be required to load ads in an `ArrayList`, call methods on the `AdsManager` and the like. From what you describe it looks like you are using ExoPlayer to play ads in a custom way.

I'd recommend to integrate your adtag as described in the [Developer Guide](https://exoplayer.dev/ad-insertion.html). Quickest way to try this out is probably to add your media and the ad tag to the [demo app](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/assets/media.exolist.json#L277) and then deploy the demo app.
