### ISSUE TITLE
Error while playing live

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#1018]
Hi,

I'm getting this error while playing the live stream for a long time. How can we solve this?

```
E/ExoPlayerImplInternal( 2085): Internal track renderer error.
E/ExoPlayerImplInternal( 2085): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.ParserException: java.nio.BufferOverflowException
E/ExoPlayerImplInternal( 2085):     at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:455)
E/ExoPlayerImplInternal( 2085):     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
E/ExoPlayerImplInternal( 2085):     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
E/ExoPlayerImplInternal( 2085):     at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 2085):     at android.os.Looper.loop(Looper.java:136)
E/ExoPlayerImplInternal( 2085):     at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 2085):     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/ExoPlayerImplInternal( 2085): Caused by: com.google.android.exoplayer.ParserException: java.nio.BufferOverflowException
E/ExoPlayerImplInternal( 2085):     at com.google.android.exoplayer.chunk.parser.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:229)
E/ExoPlayerImplInternal( 2085):     at com.google.android.exoplayer.chunk.ContainerMediaChunk.read(ContainerMediaChunk.java:134)
E/ExoPlayerImplInternal( 2085):     at com.google.android.exoplayer.chunk.ChunkSampleSource.readData(ChunkSampleSource.java:359)
E/ExoPlayerImplInternal( 2085):     at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:531)
E/ExoPlayerImplInternal( 2085):     at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:449)
E/ExoPlayerImplInternal( 2085):     ... 6 more
E/ExoPlayerImplInternal( 2085): Caused by: java.nio.BufferOverflowException
E/ExoPlayerImplInternal( 2085):     at java.nio.Buffer.checkPutBounds(Buffer.java:189)
E/ExoPlayerImplInternal( 2085):     at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:307)
E/ExoPlayerImplInternal( 2085):     at com.google.android.exoplayer.upstream.DataSourceStream.read(DataSourceStream.java:185)
E/ExoPlayerImplInternal( 2085):     at com.google.android.exoplayer.upstream.DataSourceStream.read(DataSourceStream.java:149)
E/ExoPlayerImplInternal( 2085):     at com.google.android.exoplayer.chunk.parser.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:787)
E/ExoPlayerImplInternal( 2085):     at com.google.android.exoplayer.chunk.parser.mp4.FragmentedMp4Extractor.readOrSkipSample(FragmentedMp4Extractor.java:741)
E/ExoPlayerImplInternal( 2085):     at com.google.android.exoplayer.chunk.parser.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:223)
E/ExoPlayerImplInternal( 2085):     ... 10 more
```

Regards,
Randeep

**Comment by andrewlewis** [comment]
Please provide additional information as described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html). How long is 'a long time'?

**Comment by randeeppr** [comment]
@andrewlewis 
It was around 5-7 minutes. It happened when I stopped a livestream and start another stream immediately.  I'll try to reproduce this and update you with more details.

Regards,
Randeep

**Comment by ojw28** [comment]
Closing due to lack of information.
