### ISSUE TITLE
decoderInitializationError on some devices

### ISSUE THREAD

**Issue by wanglg** [google/ExoPlayer#1019]
12-02 20:10:13.898 3056-3056/com.google.android.exoplayer.demo E/EventLogger: internalError [1.64, decoderInitializationError]
                                                                              com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: AACDecoder, MediaFormat(2, audio/mp4a-latm, -1, 1162, -1, -1, -1, -1.0, 2, 44100, und, 221078000, false, -1, -1)
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:346)
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:709)
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:470)
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:451)
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                  at android.os.Looper.loop(Looper.java:193)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                               Caused by: java.io.IOException: Failed to allocate component instance
                                                                                  at android.media.MediaCodec.native_setup(Native Method)
                                                                                  at android.media.MediaCodec.<init>(MediaCodec.java:213)
                                                                                  at android.media.MediaCodec.createByCodecName(MediaCodec.java:207)
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:331)
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:709) 
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:470) 
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:451) 
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                  at android.os.Looper.loop(Looper.java:193) 
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
12-02 20:10:13.899 3056-7271/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                        com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: AACDecoder, MediaFormat(2, audio/mp4a-latm, -1, 1162, -1, -1, -1, -1.0, 2, 44100, und, 221078000, false, -1, -1)
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:359)
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:346)
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:709)
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:470)
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:451)
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                            at android.os.Looper.loop(Looper.java:193)
                                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                         Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: AACDecoder, MediaFormat(2, audio/mp4a-latm, -1, 1162, -1, -1, -1, -1.0, 2, 44100, und, 221078000, false, -1, -1)
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:346) 
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:709) 
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:470) 
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:451) 
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                            at android.os.Looper.loop(Looper.java:193) 
                                                                                            at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                                                         Caused by: java.io.IOException: Failed to allocate component instance
                                                                                            at android.media.MediaCodec.native_setup(Native Method)
                                                                                            at android.media.MediaCodec.<init>(MediaCodec.java:213)
                                                                                            at android.media.MediaCodec.createByCodecName(MediaCodec.java:207)
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:331)
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:709) 
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:470) 
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:451) 
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                            at android.os.Looper.loop(Looper.java:193) 
                                                                                            at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by ojw28** [comment]
This is fixed in the dev branch, by https://github.com/google/ExoPlayer/commit/b64986ce8275dc3c723bb15bf9f00a808ab19b16.
