### ISSUE TITLE
InstantiationError on 2.17.X

### ISSUE THREAD

**Issue by MilleJanos** [google/ExoPlayer#10218]
I'm experiencing crashes when starting DASH playback starting from version 2.17.0. Check the exception below.

Looks like ```com.google.android.exoplayer2.ext.ffmpeg.FfmpegLibrary``` class tries to create a new instance of ```com.google.android.exoplayer2.util.LibraryLoader``` class, but ```LibraryLoader``` became abstract starting from 2.17.0.
I don't have any issues on exoplayer 2.16.1.
Am I doing something wrong? Is there an updated version of ```FfmpegLibrary```?

### I'm using the following dependencies:
com.google.android.exoplayer:exoplayer-core:2.17.1
com.google.android.exoplayer:exoplayer-dash:2.17.1
com.google.android.exoplayer:exoplayer-hls:2.17.1
com.google.android.exoplayer:exoplayer-core:2.17.1
com.google.android.exoplayer:exoplayer-ui:2.17.1

### Crash message:
```    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: ExoPlayer:Playback
    Process: com.myapp.develop, PID: 10859
    java.lang.InstantiationError: com.google.android.exoplayer2.util.LibraryLoader
        at com.google.android.exoplayer2.ext.ffmpeg.FfmpegLibrary.<clinit>(FfmpegLibrary.java:37)
        at com.google.android.exoplayer2.ext.ffmpeg.FfmpegLibrary.isAvailable(FfmpegLibrary.java:59)
        at com.google.android.exoplayer2.ext.ffmpeg.FfmpegAudioRenderer.supportsFormatInternal(FfmpegAudioRenderer.java:97)
        at com.google.android.exoplayer2.audio.DecoderAudioRenderer.supportsFormat(DecoderAudioRenderer.java:231)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:509)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:376)
        at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:238)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:186)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2249)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:518)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)```

**Comment by marcbaechinger** [comment]
> Is there an updated version of FfmpegLibrary?

It appears to me that this should work if you have updated the Ffmpeg extension to 2.17.1 accordingly:

https://github.com/google/ExoPlayer/blob/r2.17.1/extensions/ffmpeg/src/main/java/com/google/android/exoplayer2/ext/ffmpeg/FfmpegLibrary.java#L36

Can you double check whether this is the case and if not keep the version of the extension in sync with the other dependencies and try again?

**Comment by MilleJanos** [comment]
There is an `ffmpeg` related `.aar` file which targets `"com.google.android.exoplayer2.ext.ffmpeg"` where the class files are located inside `classes.jar`. Do I have to manually update each file from the link you sent? Or it is possible to make this `.aar` file update automatically to the 2.17.1 version?
(Updated comment)

**Comment by marcbaechinger** [comment]
I think you got that `aar` file from building the extension yourself. I don't know of another way of integrating the extension than described in the [`README`](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg#build-instructions-linux-macos).

**Comment by MilleJanos** [comment]
Okay. I re-built the `aar` file manually and now the stream works with 2.17.1
Thank you very-very much for the help!
