### ISSUE TITLE
Divided by zero problem

### ISSUE THREAD

**Issue by Appes** [google/ExoPlayer#1021]
Hi, if i want to play some mp3s I get this error. 

LoadTask: Unexpected exception loading stream
                                           java.lang.ArithmeticException: divide by zero
                                               at com.google.android.exoplayer.extractor.mp3.XingSeeker.getTimeUs(XingSeeker.java:139)
                                               at com.google.android.exoplayer.extractor.mp3.Mp3Extractor.readSample(Mp3Extractor.java:162)
                                               at com.google.android.exoplayer.extractor.mp3.Mp3Extractor.read(Mp3Extractor.java:152)
                                               at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:744)
                                               at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                               at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                               at java.lang.Thread.run(Thread.java:856)

Thanks, David

**Comment by Appes** [comment]
I resolve it. I had version 1.4.2 and update to 1.5.2. Everything is ok.
