### ISSUE TITLE
Randome Crash in AdTagLoader

### ISSUE THREAD

**Issue by TheSikh** [google/ExoPlayer#10221]
### ExoPlayer Version

2.16.1

### Devices that reproduce the issue

Xiomi Redmi 9A running android 10
Oppo A5 running android 8.1.0
Xiomi Redmi 7 running android 10
Xiomi Redmi note 9 Pro running android 10
Samsung Galaxy A10 running android 9
Xiomi Poco M2 running android 10
Vivo 1904 running android 9
Xiomi Redmi Y2 running android 9
Vivo 1820 running android 8.1.0
Oppo A1K running android 9
Samsung Galaxy S7 running android 8
Opposition CPH1909 running android 8.1.0

### Devices that do not reproduce the issue

Pixeel 4a running android 12 
OnePlus 7T running android 11
OnePlus 8T running android 11
Lenovo Tablet running android 10
Samsung Tab A series running android 10

### Reproducible in the demo app?

Not tested

### Reproduction steps

Player is randomly crashing while playing vast ads

### Expected result

Ads Should play successfully 

### Actual result

Playback crashes with below stack trace 
```
Fatal Exception: java.lang.NullPointerException
       at java.util.Objects.requireNonNull(Objects.java:203)
       at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:154)
       at com.google.android.exoplayer2.ext.ima.AdTagLoader.handlePlayerStateChanged(AdTagLoader.java:804)
       at com.google.android.exoplayer2.ext.ima.AdTagLoader.onPlaybackStateChanged(AdTagLoader.java:492)
       at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$19(ExoPlayerImpl.java:1335)
       at com.google.android.exoplayer2.ExoPlayerImpl.$r8$lambda$AB64kYhFun_tYwwYaOXrDXesNBw(ExoPlayerImpl.java)
       at com.google.android.exoplayer2.ExoPlayerImpl$$InternalSyntheticLambda$0$1d3756c78b6d6b7ece141d7c1e9a6465b69ea5798e59ea3803cb705ea4cacb60$10.invoke(ExoPlayerImpl.java:4)
       at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:261)
       at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:170)
       at com.google.android.exoplayer2.util.ListenerSet.$r8$lambda$NbKDn9xtItiyMgYZmjIx_Sv1FFQ(ListenerSet.java)
       at com.google.android.exoplayer2.util.ListenerSet$$InternalSyntheticLambda$1$4aa6d67c50ced20c53fd0cecd314136314e77eb5e787a34f9137864aa48c8e5a$0.run(ListenerSet.java:6)
       at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:191)
       at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1366)
       at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1202)
       at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1(ExoPlayerImpl.java:242)
       at com.google.android.exoplayer2.ExoPlayerImpl.$r8$lambda$nOBJYkeEQ2uz3sBKLToLWmzrgZk(ExoPlayerImpl.java)
       at com.google.android.exoplayer2.ExoPlayerImpl$$InternalSyntheticLambda$1$c21d15d1115b763b806454db59b3e976fd0126920652a5d519869fbd815a1094$0.run(ExoPlayerImpl.java:4)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:200)
       at android.app.ActivityThread.main(ActivityThread.java:6971)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

### Media

Not Applicable 

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
This issue is not actionable for us I'm afraid. 

Can you please add some more details along the lines of the form fields that you filled with 1Not applicable`. I think we would need at least a URI to an ad tag, reproduction steps on how we can reproduce the issue like for instance in the demo app. 

Without this information we will not be able to help you some further.
