### ISSUE TITLE
Can not play！

### ISSUE THREAD

**Issue by zhoushsong** [google/ExoPlayer#10236]
I have several video files. When I put them into the playlist, some programs can't be played during switching, but a single one can be played normally.  Different video formats

2022-05-03 17:46:38.708 2242-3638/com.google.android.exoplayer2.demo E/Surface: freeAllBuffers: 10 buffers were freed while being dequeued!
2022-05-03 17:46:39.256 2242-2242/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=97.82, mediaPos=79.60, window=8, period=8, errorCode=ERROR_CODE_TIMEOUT
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$release$5(ExoPlayerImpl.java:955)
        at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda18.invoke(Unknown Source:2)
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:281)
        at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
        at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
        at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
        at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:226)
        at com.google.android.exoplayer2.ExoPlayerImpl.release(ExoPlayerImpl.java:951)
        at com.google.android.exoplayer2.demo.PlayerActivity.releasePlayer(PlayerActivity.java:379)
        at com.google.android.exoplayer2.demo.PlayerActivity.onStop(PlayerActivity.java:185)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1476)
        at android.app.Activity.performStop(Activity.java:8209)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4848)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4827)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4901)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:233)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
     Caused by: com.google.android.exoplayer2.ExoTimeoutException: Player release timed out.
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$release$5(ExoPlayerImpl.java:954)
        at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda18.invoke(Unknown Source:2) 
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:281) 
        at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190) 
        at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6) 
        at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211) 
        at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:226) 
        at com.google.android.exoplayer2.ExoPlayerImpl.release(ExoPlayerImpl.java:951) 
        at com.google.android.exoplayer2.demo.PlayerActivity.releasePlayer(PlayerActivity.java:379) 
        at com.google.android.exoplayer2.demo.PlayerActivity.onStop(PlayerActivity.java:185) 
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1476) 
        at android.app.Activity.performStop(Activity.java:8209) 
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4848) 
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4827) 
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4901) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:233) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952) 
    ]
2022-05-03 17:46:40.246 2242-3641/com.google.android.exoplayer2.demo E/ACodec: [OMX.amlogic.avc.decoder.awesome2] ERROR(0x80001000)
2022-05-03 17:46:40.246 2242-3641/com.google.android.exoplayer2.demo E/ACodec: signalError(omxError 0x80001000, internalError -2147483648)
2022-05-03 17:46:40.247 2242-3638/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported err 0x80001000, actionCode 0, while in state 7
2022-05-03 17:46:40.247 2242-3638/com.google.android.exoplayer2.demo E/Surface: freeAllBuffers: 10 buffers were freed while being dequeued!
2022-05-03 17:46:40.249 2242-3477/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Disable failed.
      android.media.MediaCodec$CodecException: Error 0x80001000
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2298)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:166)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:864)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:857)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:710)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:561)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:186)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1671)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1411)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.releaseInternal(ExoPlayerImplInternal.java:1385)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:563)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-05-03 17:46:40.302 2242-3924/com.google.android.exoplayer2.demo E/FMQ: grantorIdx must be less than 3

**Comment by ojw28** [comment]
Since you're reporting a bug, please fill out the [bug template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml) including all of the requested information. Closing this one. Thanks!
