### ISSUE TITLE
How to play.m3u8 file in exoplayer？

### ISSUE THREAD

**Issue by tmi111** [google/ExoPlayer#10242]
How to play.m3u8 file in exoplayer？

**Comment by cbazalduaDev** [comment]
try to follow this link 
https://exoplayer.dev/hls.html

**Comment by tmi111** [comment]
Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: src.length=0 srcPos=0 dst.length=65536 dstPos=1 length=8
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:430)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=0 dst.length=65536 dstPos=1 length=8
        at java.lang.System.arraycopy(Native Method)
        at com.google.android.exoplayer2.util.ParsableByteArray.readBytes(ParsableByteArray.java:205)
        at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:193)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:585)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor$TrackBundle.outputSampleEncryptionData(FragmentedMp4Extractor.java:1766)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1361)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:339)
        at com.google.android.exoplayer2.source.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:67)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:462)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:432)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:388)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923)

**Comment by tmi111** [comment]
How did this error happen while playing.m3u8

**Comment by tmi111** [comment]
How did this error happen while playing.m3u8  


 Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: src.length=0 srcPos=0 dst.length=65536 dstPos=1 length=8
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:430)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)
 Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=0 dst.length=65536 dstPos=1 length=8
    at java.lang.System.arraycopy(Native Method)
    at com.google.android.exoplayer2.util.ParsableByteArray.readBytes(ParsableByteArray.java:205)
    at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:193)
    at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:585)
    at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor$TrackBundle.outputSampleEncryptionData(FragmentedMp4Extractor.java:1766)
    at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1361)
    at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:339)
    at com.google.android.exoplayer2.source.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:67)
    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:462)
    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:432)
    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:388)
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
    at java.lang.Thread.run(Thread.java:923)

**Comment by cbazalduaDev** [comment]
Ok let's see your code

**Comment by tmi111** [comment]
DataSource.Factory dataSourceFactory = new DefaultHttpDataSource.Factory();
// Create a HLS media source pointing to a playlist uri.
        HlsMediaSource hlsMediaSource =
                new HlsMediaSource.Factory(dataSourceFactory)
                        .createMediaSource(MediaItem.fromUri(url));
// Create a player instance.
// Set the media source to be played.
        mPlayer.setMediaSource(hlsMediaSource);
