### ISSUE TITLE
`</EventStream>` is not coming in `onMetadata` event

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#10256]
ExoPlayer : v2.17.1
Device: Any device

Duplication question: https://github.com/google/ExoPlayer/issues/9818 

I have the same question. I have a media having `</EventStream>` in `</Period>` tag but I don't receive it in the timed metadata`onMetadata(Metadata metadata)` event. In stead I get this info inside `onTimelineChanged(Timeline timeline, int reason)` in period object.

Is there any reason of not sending this `</EventStream>` in timed metadata ?

**Comment by icbaker** [comment]
Please provide a stream we can use to reproduce the issue. Please either post it here or send it to dev.exoplayer@gmail.com using the subject `Issue #10256`. Please also update this issue to indicate you’ve done this.

**Comment by GouravSna** [comment]
Hi @icbaker ,

I have shared the manifest over the email.

**Comment by icbaker** [comment]
I need to be able to play the media in order to reproduce the problem and investigate. This issue seems unlikely to be related to DRM, so you should be able to craft some media that reproduces the problem and the link lasts for a long time with no license duration concerns. Thanks!

**Comment by GouravSna** [comment]
Hi @icbaker , I have shared the playable media over the email. Please take a look. Please use India VPN for the playback.

-Thanks

**Comment by icbaker** [comment]
The `MPD` file provided over email has no `<EventStream>` tags (as referred to in the title of this issue), it only has `<InbandEventStream>`. Is that expected?

I also am unable to play it without error - after a short time of playback proceeding (without video visible) playback always fails with an exception like below. I'm VPN'd to India, without that I see 403 errors immediately when attempting playback. Is it possible your DRM server is detecting the VPN IP somehow and blocking it? Please consider my request above and provide a DRM-free feed that reproduces the issue. It doesn't seem like a good use of time to try and debug DRM issues on a non-DRM question.

```
2022-05-23 15:39:25.864 27685-27685/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=40.23, mediaPos=-31.32, window=0, period=0, errorCode=ERROR_CODE_DRM_LICENSE_ACQUISITION_FAILED
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:595)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: failed to connect to tv.media.jio.com/49.40.0.179 (port 443) from /100.120.132.142 (port 40794) after 8000ms
```
