### ISSUE TITLE
An error may occur during streaming playback

### ISSUE THREAD

**Issue by KazukiSugiyama107** [google/ExoPlayer#10301]
It doesn't happen every time, but when I play the streaming on a particular device, I get an error.
In some cases, you can play the same video file on the same device.
I think each device spec is related, but do you know when this error occurs?

- device: F-41A
- OS: Android 11

**Log**
```
05-25 16:35:38.454  9488  9553 E IPCThreadState: *** writeTransactionData:errorCheck() statusBuffer err=-74
05-25 16:35:38.475  9488 16767 E ACodec  : [OMX.qcom.video.decoder.avc.secure] ERROR(0x80001009)
05-25 16:35:38.475  9488 16767 E ACodec  : signalError(omxError 0x80001009, internalError -2147483648)
05-25 16:35:38.475  9488 16766 E MediaCodec: Codec reported err 0x80001009, actionCode 0, while in state 6
05-25 16:35:38.485  9488 16766 D SurfaceUtils: disconnecting from surface 0x707f435750, reason disconnectFromSurface
05-25 16:35:38.485  9488 16766 E Surface : freeAllBuffers: 2 buffers were freed while being dequeued!
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(video-avc1-3, null, null, video/avc, avc1.4D401F, 1000000, null, [1280, 720, 29.97003], [-1, -1]), rendererSupport=NO_UNSUPPORTED_DRM
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: 	at m.c.b.b.z.a(BaseRenderer.java:14)
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.a(MediaCodecRenderer.java:48)
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: 	at m.c.b.b.j0.b(ExoPlayerImplInternal.java:161)
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: 	at m.c.b.b.j0.handleMessage(ExoPlayerImplInternal.java:24)
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:223)
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:67)
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: Caused by: java.lang.IllegalStateException
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: 	at m.c.b.b.o1.r.a(SynchronousMediaCodecAdapter.java:1)
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.b(MediaCodecRenderer.java:14)
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.a(MediaCodecRenderer.java:35)
05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: 	... 5 more
05-25 16:35:38.523  9488 16739 D CCodecBufferChannel: [c2.android.aac.decoder#144] MediaCodec discarded an unknown buffer
05-25 16:35:38.524  9488 16739 I chatty  : uid=10274(jp.mgstage.player) identical 2 lines
05-25 16:35:38.524  9488 16739 D CCodecBufferChannel: [c2.android.aac.decoder#144] MediaCodec discarded an unknown buffer
05-25 16:35:38.553  9488 16739 I hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
05-25 16:35:38.592  9488 16767 E Surface : getSlotFromBufferLocked: unknown buffer: 0x6f6f495a10
05-25 16:35:38.593  9488 16767 W ACodec  : [OMX.qcom.video.decoder.avc.secure] can not return buffer 26 to native window
05-25 16:35:38.594  9488 16767 E Surface : getSlotFromBufferLocked: unknown buffer: 0x6f6f4a9240
05-25 16:35:38.594  9488 16767 W ACodec  : [OMX.qcom.video.decoder.avc.secure] can not return buffer 25 to native window
05-25 16:35:38.620  9488 16767 D SurfaceUtils: disconnecting from surface 0x707f435750, reason pushBlankBuffersToNativeWindow
05-25 16:35:38.620  9488 16767 E Surface : freeAllBuffers: 2 buffers were freed while being dequeued!
05-25 16:35:38.628  9488 16767 E SurfaceUtils: Failed to disconnect from surface 0x707f435750, err -19
05-25 16:35:38.628  9488 16767 E SurfaceUtils: error pushing blank frames: api_disconnect failed: No such device (19)
```

**Comment by christosts** [comment]
The error log says

> 05-25 16:35:38.518  9488 16503 E ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(video-avc1-3, null, null, video/avc, avc1.4D401F, 1000000, null, [1280, 720, 29.97003], [-1, -1]), rendererSupport=**NO_UNSUPPORTED_DRM**

The `NO_UNSUPPORTED_DRM` says  that most likely the device does not have the DRM capabilities to play this content. 

In the general case, we need a bug-report obtained from the device obtained right after the error happens and a link to the content to test ourselves to provide more assistance. Please consider sharing those. Note however, this seems to be a device-specific issue and we don't have access to the specific device, so we might not be able to provide more help anyway.

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by KazukiSugiyama107** [comment]
Thank you for answering.
We plan to update the installed ExoPlayer in the near future, so if you still get the same error after the update, we'll ask you another question.
This issue will be closed.
