### ISSUE TITLE
ExoPlayer FFmpeg extension error

### ISSUE THREAD

**Issue by SharyRajpoot** [google/ExoPlayer#10300]
### ExoPlayer Version

2.16.1

### Devices that reproduce the issue

None

### Devices that do not reproduce the issue

None

### Reproducible in the demo app?

Not tested

### Reproduction steps

None

### Expected result

ExoPlayer is not able to play some audio formats although the video is working fine without audio.
So I tried to build an ExoPlayer extension with FFmpeg. After building and putting it inside my app as .aar the app gets crashed and below is the error that is related to ffmpegLib.

### Actual result

Process: org.example.exoplayerdemo, PID: 3101
    java.lang.IncompatibleClassChangeError: com.google.android.exoplayer2.ext.ffmpeg.FfmpegLibrary$1
        at com.google.android.exoplayer2.ext.ffmpeg.FfmpegLibrary.<clinit>(FfmpegLibrary.java:35)
        at com.google.android.exoplayer2.ext.ffmpeg.FfmpegAudioRenderer.supportsFormatInternal(FfmpegAudioRenderer.java:93)
        at com.google.android.exoplayer2.audio.DecoderAudioRenderer.supportsFormat(DecoderAudioRenderer.java:221)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:492)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:359)
        at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:238)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:186)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2209)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:505)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:150)
        at android.os.HandlerThread.run(HandlerThread.java:61)

### Media

Not willing to share it here...

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by SharyRajpoot** [comment]
Got the issue...
It was something like I am using ExoPlayer 2.16.1 and its extension from the latest version build ...
So now when I have updated ExoPlayer to the latest version 2.17.1, the app runs successfully without any error and FFmpeg is also working perfectly...
