### ISSUE TITLE
ANR getCodec on Android 11 & 12

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#10306]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

69% Android 11
31% Android 12

### Devices that do not reproduce the issue

From Android 5.0 to Android 10

### Reproducible in the demo app?

No

### Reproduction steps

I couldn't reproduce the issue with my app nor the demo app

### Expected result

Shouldn't block main thread

### Actual result

```
ExoPlayer:Playback (native): tid=82 systid=16470 
#00 pc 0xc54a4 libc.so 
#01 pc 0x81db8 libc.so 
#02 pc 0x54a34 libbinder.so 
#03 pc 0x55a78 libbinder.so 
#04 pc 0x557e8 libbinder.so 
#05 pc 0x4e098 libbinder.so 
#06 pc 0x47c34 libmedia.so 
#07 pc 0x1364b0 libstagefright.so 
#08 pc 0x4d02c libmedia_jni.so 
#09 pc 0x4c41c libmedia_jni.so 
       at android.media.MediaCodecList.native_getCodecCount(MediaCodecList.java)
       at android.media.MediaCodecList.initCodecList(MediaCodecList.java:82)
       at android.media.MediaCodecList.<init>(MediaCodecList.java:172)
       at com.google.android.exoplayer2.mediacodec.MediaCodecUtil$MediaCodecListCompatV21.ensureMediaCodecInfosInitialized(MediaCodecUtil.java:1033)
       at com.google.android.exoplayer2.mediacodec.MediaCodecUtil$MediaCodecListCompatV21.getCodecCount(MediaCodecUtil.java:1003)
       at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:321)
       at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java:169)
       at com.google.android.exoplayer2.mediacodec.MediaCodecSelector$$InternalSyntheticLambda$1$294d267b7aafaf8414a7ebd3a1b4aadba77d4ea137193cab50bd2f3c70fd5f79$0.getDecoderInfos(MediaCodecSelector.java)
       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.getDecoderInfos(MediaCodecAudioRenderer.java:393)
       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.supportsFormat(MediaCodecAudioRenderer.java:305)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.supportsFormat(MediaCodecRenderer.java:445)
       at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:509)
       at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:376)
       at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:238)
       at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:186)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2249)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:518)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:254)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

```
main (blocked): tid=1 systid=16285 | waiting to lock <0x04254fec> (java.lang.Class<com.google.android.exoplayer2.mediacodec.MediaCodecUtil>) held by thread 82
       at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java)
       at com.google.android.exoplayer2.mediacodec.MediaCodecSelector$$InternalSyntheticLambda$1$294d267b7aafaf8414a7ebd3a1b4aadba77d4ea137193cab50bd2f3c70fd5f79$0.getDecoderInfos(MediaCodecSelector.java)
       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.getDecoderInfos(MediaCodecAudioRenderer.java:393)
       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.supportsFormat(MediaCodecAudioRenderer.java:305)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.supportsFormat(MediaCodecRenderer.java:445)
       at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:509)
       at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:376)
       at com.google.android.exoplayer2.offline.DownloadHelper.runTrackSelection(DownloadHelper.java:844)
       at com.google.android.exoplayer2.offline.DownloadHelper.onMediaPrepared(DownloadHelper.java:792)
       at com.google.android.exoplayer2.offline.DownloadHelper.access$200(DownloadHelper.java:92)
       at com.google.android.exoplayer2.offline.DownloadHelper$MediaPreparer.handleDownloadHelperCallbackMessage(DownloadHelper.java:1057)
       at com.google.android.exoplayer2.offline.DownloadHelper$MediaPreparer$$InternalSyntheticLambda$3$266abe9c357fb87a79d66f3013f00a0b1490a75aacb1d70a4af6bba70c00539d$0.handleMessage(DownloadHelper.java:26)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:254)
       at android.app.ActivityThread.main(ActivityThread.java:8203)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

### Media

My application only plays HLS video

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment]
This is an error reported from the platform, propagated through the player. There's not much the player can do to actually solve this. If the platform raises this error, it's likely in a bad state and the player won't be able to function.

May I ask: are the two stack traces reported at the same time (is the app initiating playback and download at the same time) or where they collected from different occasions?

edited: Some extra questions:
- are you seeing this error on specific vendors?
- did you observe these errors with a previous ExoPlayer version, if you were using one?

**Comment by yoobi** [comment]
Oh my bad if it's in the platform I'll report on the issuetracker.

1. The stacks are reported at the same time. My user can view a video and download it at the same time
2. I'm seeing this issue only on Android 11+
3. I can't tell you if this error exist in the previous exoPlayer as I'm getting it only recently and I've been on 1.17.1 for a while

**Comment by christosts** [comment]
Based on the two stack traces
- [fist stack trace] the player's internal thread (not the app main thread) is blocked on `MediaCodecUtil.getDecoderInfos()`, specifically trying to create a `MediaCodecList`. `MediaCodecList` this is a platform component and is needed in order to get information about available platform decoders.
- [second stack trace] the DownloadHelper running on the app thread also needs to query the platform for available decoders and is blocked on `MediaCodecUtil.getDecoderInfos()` too, causing the ANRs.

As I said, this looks like a platform issue. If the app is raising an ANR, it means that the player's thread (first stack trace) is likely to be blocked for over 5 seconds, causing the app main thread to ANR.

You report that you are seeing this 69% on Android 11 and 31% on Android 12. Are these errors from the same brand/model? If yes, you might have to reach the device vendor.

**Comment by yoobi** [comment]
To understand correctly, the second stack trace is causing an ANR because `MediaCodecUtil.getDecoderInfos()` is blocking it, so it has nothing to do with my own code ?

Below a screen of the multiple model getting the ANR
<img width="142" alt="Screenshot 2022-06-01 at 14 51 19" src="https://user-images.githubusercontent.com/17434735/171408600-f01b3693-206c-4dbb-a58f-b1eddd980395.png">

**Comment by christosts** [comment]
Apologies for the delayed reply.

> To understand correctly, the second stack trace is causing an ANR because `MediaCodecUtil.getDecoderInfos()` is blocking it, so it has nothing to do with my own code ?

That's my reading of the stack traces. I'd reach out to either the device vendors of the Android issue tracker.

**Comment by yoobi** [comment]
No worries. Thank you for your time.
