### ISSUE TITLE
CryptoException: Operation not supported - unable to play DRM protected contents on HUAWEI device

### ISSUE THREAD

**Issue by Bhupesh71** [google/ExoPlayer#10314]
### ExoPlayer Version

2.16.1

### Devices that reproduce the issue

On HUAWEI Nova 9
![Screenshot_20220602_192144_com android settings](https://user-images.githubusercontent.com/78247191/171647830-e5a89ca2-7481-444c-93a1-8030ea9d976f.jpg)

### Reproducible in the demo app?

Yes

### Reproduction steps

Playing any WIDEVINE protected content on ExoPlayer sample app

### Expected result

Playback should work fine.

### Actual result

Getting decoder initialisation failure when playing DRM protected contents. Below is the error stack trace collected from Exo-Player sample app.

```2022-06-02 19:33:07.825 8274-8391/com.google.android.exoplayer2.demo E/MediaCodecVideoRenderer: Video codec error
      com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.qti.avc.decoder.secure, Format(2, null, null, video/avc, avc1.4D401F, 1777315, null, [854, 380, 24.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1017)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1437)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:799)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:950)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:228)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.media.MediaCodec$CryptoException: Operation not supported in this configuration
        at android.media.MediaCodec.getBuffers(Native Method)
        at android.media.MediaCodec.cacheBuffers(MediaCodec.java:3797)
        at android.media.MediaCodec.start(MediaCodec.java:2237)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:58)
        at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:130)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1095)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1006)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1437) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:799) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:950) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:228) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2022-06-02 19:33:07.831 8274-8455/com.google.android.exoplayer2.demo I/MediaCodec: mediacodec kWhatReleaseCompleted end
2022-06-02 19:33:07.834 8274-8391/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.4D401F, 1777315, null, [854, 380, 24.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:228)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.qti.avc.decoder.secure, Format(2, null, null, video/avc, avc1.4D401F, 1777315, null, [854, 380, 24.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1017)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1437)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:799)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:950)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:228) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.media.MediaCodec$CryptoException: Operation not supported in this configuration
        at android.media.MediaCodec.getBuffers(Native Method)
        at android.media.MediaCodec.cacheBuffers(MediaCodec.java:3797)
        at android.media.MediaCodec.start(MediaCodec.java:2237)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:58)
        at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:130)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1095)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1006)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1437) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:799) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:950) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:228) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2022-06-02 19:33:07.835 8274-8391/com.google.android.exoplayer2.demo I/MediaCrypto-JNI: release
2022-06-02 19:33:07.835 8274-8391/com.google.android.exoplayer2.demo I/MediaCrypto-JNI: JCrypto Destroyed 0x74c9b362c0
2022-06-02 19:33:07.836 8274-8274/com.google.android.exoplayer2.demo D/EventLogger: videoDisabled [eventTime=3.20, mediaPos=0.00, window=0, period=0]
2022-06-02 19:33:07.838 8274-8274/com.google.android.exoplayer2.demo D/EventLogger: audioDisabled [eventTime=3.20, mediaPos=0.00, window=0, period=0]
2022-06-02 19:33:07.840 8274-8274/com.google.android.exoplayer2.demo D/EventLogger: drmSessionReleased [eventTime=3.21, mediaPos=0.00, window=0, period=0]
2022-06-02 19:33:07.849 8274-8456/com.google.android.exoplayer2.demo D/BufferPoolAccessor2.0: Destruction - bufferpool2 0x75207d4028 cached: 0/0M, 0/0% in use; allocs: 4, 0% recycled; transfers: 0, 0% unfetched
2022-06-02 19:33:07.850 8274-8456/com.google.android.exoplayer2.demo I/CryptoHal: CryptoHal Destroyed 0x74c9c2c480
2022-06-02 19:33:07.850 8274-8385/com.google.android.exoplayer2.demo E/BufferQueueProducer: [MediaCodec.release](id:205200000001,api:0,p:-1,c:8274) detachBuffer: BufferQueue has no connected producer
2022-06-02 19:33:07.861 8274-8391/com.google.android.exoplayer2.demo I/MediaDrm-JNI: MediaDrm_native drm release 0x7520892180
2022-06-02 19:33:07.861 8274-8391/com.google.android.exoplayer2.demo I/MediaDrm-JNI: MediaDrm_native drm disconnect
2022-06-02 19:33:07.861 8274-8391/com.google.android.exoplayer2.demo I/MediaDrm-JNI: MediaDrm_native destroyPlugin and clear
2022-06-02 19:33:07.865 8274-8391/com.google.android.exoplayer2.demo I/DrmHal: DrmHal Destroyed 0x75349e5000
2022-06-02 19:33:07.873 8274-8274/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=3.24, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_DECODER_INIT_FAILED
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.4D401F, 1777315, null, [854, 380, 24.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:228)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.qti.avc.decoder.secure, Format(2, null, null, video/avc, avc1.4D401F, 1777315, null, [854, 380, 24.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1017)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1437)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:799)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:950)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:228) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.media.MediaCodec$CryptoException: Operation not supported in this configuration
        at android.media.MediaCodec.getBuffers(Native Method)
        at android.media.MediaCodec.cacheBuffers(MediaCodec.java:3797)
        at android.media.MediaCodec.start(MediaCodec.java:2237)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:58)
        at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:130)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1095)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1006)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1437) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:799) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:950) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:228) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    ]```

**Comment by Bhupesh71** [comment]
In addition to the above info, device supports Widevine L1 security level, I am attaching DRM info and device specific info below.
![Screenshot_20220602_192202_com androidfung drminfo](https://user-images.githubusercontent.com/78247191/171648014-032b79ea-3345-4d6e-aa4e-756ab6a91ed0.jpg)
![Screenshot_20220602_192210_com androidfung drminfo](https://user-images.githubusercontent.com/78247191/171648028-ef45ff51-9e34-4f49-a21a-baed2eb26433.jpg)

**Comment by Bhupesh71** [comment]
Hi team, any update on this?

**Comment by rrfrias** [comment]
@Bhupesh71, can you share a bugreport with [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com)?

**Comment by Bhupesh71** [comment]
@rrfrias sent bugreport to dev.exoplayer@gmail.com

**Comment by rrfrias** [comment]
From the bugreport, it does appear to be an issue with the device. I would like to share the bugreport with Huawei to investigate furthur. Can you let me know if i have your permission? Also can you share repro steps include the specific video you tried to playback. I do not have a Huawei Nova 9 to test with and Huawei might not be very familiar with Exoplayer so precise steps will be helpful.

```
06-09 12:18:13.311 media 25257 25258 E WVCdm   : [crypto_session.cpp(1541):Decrypt] OEMCrypto_DecryptCENC failed: status = 28
06-09 12:18:13.311 media 25257 25258 E WVCdm   : Decrypt error in session sid2 during a sample without protected data: 178
06-09 12:18:13.311 10202 25173 25318 I CCodecBufferChannel: [c2.qti.avc.decoder.secure#761] decrypt failed: result=-2006
06-09 12:18:13.311 10202 25173 25318 W MediaCodec: Log queueSecureInputBuffer error: -2006
06-09 12:18:13.311 10202 25173 25318 E MediaCodec: queueCSDInputBuffer failed w/ error -2006
06-09 12:18:13.402 media 25257 25258 E WVCdm   : Decrypt error in session sid2 during a sample without protected data: 178
```

**Comment by rrfrias** [comment]
I have learned that we are limited in the assistance we can provide for Huawei devices. Sorry. You might want to contact Huawei directly if you need to investigate this furthur.

https://support.google.com/android/thread/29434011/answering-your-questions-on-huawei-devices-and-google-services?hl=en
