### ISSUE TITLE
 Large audio files in wav format are not supported, Unsupported WAV format type: 3

### ISSUE THREAD

**Issue by firsthubgit** [google/ExoPlayer#10334]
### ExoPlayer Version

2.16.1

### Devices that reproduce the issue

HuaWei P30 pro
Harmony OS2.0

### Reproducible in the demo app?

Yes

### Reproduction steps

download the file  and play it

https://drive.google.com/file/d/1SsuZVVhPGcN8cqxZtnwGkFj6y4tC0iW_/view?usp=sharing

### Expected result

can play it

### Actual result
```java
2022-06-13 22:06:13.668 19989-19989/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=0.14, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.ParserException: Unsupported WAV format type: 3
        at com.google.android.exoplayer2.extractor.wav.WavExtractor.readFormat(WavExtractor.java:199)
        at com.google.android.exoplayer2.extractor.wav.WavExtractor.read(WavExtractor.java:134)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
    ]
2022-06-13 22:06:13.668 19989-20432/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:628)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:598)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.ParserException: Unsupported WAV format type: 3
        at com.google.android.exoplayer2.extractor.wav.WavExtractor.readFormat(WavExtractor.java:199)
        at com.google.android.exoplayer2.extractor.wav.WavExtractor.read(WavExtractor.java:134)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
2022-06-13 22:06:13.676 19989-19989/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=0.14, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:628)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:598)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.ParserException: Unsupported WAV format type: 3
        at com.google.android.exoplayer2.extractor.wav.WavExtractor.readFormat(WavExtractor.java:199)
        at com.google.android.exoplayer2.extractor.wav.WavExtractor.read(WavExtractor.java:134)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at 
 com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
    ]
```

### Media

https://drive.google.com/file/d/1SsuZVVhPGcN8cqxZtnwGkFj6y4tC0iW_/view?usp=sharing

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by firsthubgit** [comment]
https://drive.google.com/file/d/1SsuZVVhPGcN8cqxZtnwGkFj6y4tC0iW_/view?usp=sharing
the song is very beautiful

**Comment by tonihei** [comment]
This file uses 64-bit float PCM data, which isn't supported by the Android platform. You can only play WAV files with integer PCM data in various bit configurations or 32-bit float PCM data.

**Comment by firsthubgit** [comment]
> This file uses 64-bit float PCM data, which isn't supported by the Android platform. You can only play WAV files with integer PCM data in various bit configurations or 32-bit float PCM data.

what should i do to use the ffmpeg to support the 64-bit float PCM data
