### ISSUE TITLE
Playback error: UnrecognizedInputFormatException

### ISSUE THREAD

**Issue by mis-kcn** [google/ExoPlayer#10348]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

- Android TV emulator running Android 9
- Custom STB Box

### Devices that do not reproduce the issue

None

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Play the attached media file

### Expected result

The media plays successfully

### Actual result

Playback crashes with this following stack trace:

```
E/ExoPlayerImplInternal( 8455): Playback error
E/ExoPlayerImplInternal( 8455):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 8455):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
E/ExoPlayerImplInternal( 8455):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
E/ExoPlayerImplInternal( 8455):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 8455):       at android.os.Looper.loop(Looper.java:193)
E/ExoPlayerImplInternal( 8455):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal( 8455):   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.
E/ExoPlayerImplInternal( 8455):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
E/ExoPlayerImplInternal( 8455):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1020)
E/ExoPlayerImplInternal( 8455):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal( 8455):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 8455):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 8455):       at java.lang.Thread.run(Thread.java:764)
```

### Media

I will email [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) after filling this issue.

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by mis-kcn** [comment]
I've sent the M3U8 URL and adb bugreport produced by zip file at dev.exoplayer@gmail.com

**Comment by mis-kcn** [comment]
Closing as the problem is not with the exoplayer, but with the url link.
