### ISSUE TITLE
 java.lang.NoSuchMethodError: No virtual method setParameters

### ISSUE THREAD

**Issue by droider91** [google/ExoPlayer#10380]
I am implementing exo player in my app's one module in an another module I have implemented brightcove player(As brightcove uses exoplayer internally).
I am getting this error from exo player
```
E/com.brightcove.player.event.EventEmitterImpl@b1bc2d5: processEvent() threw a throwable.
    java.lang.NoSuchMethodError: No virtual method setParameters(Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector$Parameters;)V in class Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector; or its super classes (declaration of 'com.google.android.exoplayer2.trackselection.DefaultTrackSelector' appears in /data/app/~~IcHQVEM5w4IXny6I30aQ9g==/com.test.demo-upkrdit2H5SqzTzsEzy8jw==/base.apk!classes2.dex)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.updateTrackSelectorPeakBitrate(ExoPlayerVideoDisplayComponent.java:2052)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.initializePlayer(ExoPlayerVideoDisplayComponent.java:1028)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.createPlayer(ExoPlayerVideoDisplayComponent.java:1015)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.openVideo(ExoPlayerVideoDisplayComponent.java:1086)
        at com.brightcove.player.display.VideoDisplayComponent.openCurrentVideoSource(VideoDisplayComponent.java:470)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent$ExoPlayerOnSetSourceListener.processEvent(ExoPlayerVideoDisplayComponent.java:1288)
        at com.brightcove.player.event.EventEmitterImpl.invokeListenersForEventType(EventEmitterImpl.java:458)
        at com.brightcove.player.event.EventEmitterImpl.invokeListenersForEvent(EventEmitterImpl.java:429)
        at com.brightcove.player.event.EventEmitterImpl.access$300(EventEmitterImpl.java:42)
        at com.brightcove.player.event.EventEmitterImpl$1.handleMessage(EventEmitterImpl.java:74)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:257)
        at android.app.ActivityThread.main(ActivityThread.java:8218)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
2022-06-24 10:48:46.138 31056-31056/com.test.demo E/com.brightcove.player.event.EventEmitterImpl@987c257: processEvent() threw a throwable.
    java.lang.NoSuchMethodError: No virtual method setParameters(Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector$Parameters;)V in class Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector; or its super classes (declaration of 'com.google.android.exoplayer2.trackselection.DefaultTrackSelector' appears in /data/app/~~IcHQVEM5w4IXny6I30aQ9g==/com.test.demo-upkrdit2H5SqzTzsEzy8jw==/base.apk!classes2.dex)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.updateTrackSelectorPeakBitrate(ExoPlayerVideoDisplayComponent.java:2052)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.initializePlayer(ExoPlayerVideoDisplayComponent.java:1028)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.createPlayer(ExoPlayerVideoDisplayComponent.java:1015)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.openVideo(ExoPlayerVideoDisplayComponent.java:1086)
        at com.brightcove.player.display.VideoDisplayComponent.openCurrentVideoSource(VideoDisplayComponent.java:470)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent$ExoPlayerOnSetSourceListener.processEvent(ExoPlayerVideoDisplayComponent.java:1288)
        at com.brightcove.player.event.EventEmitterImpl.invokeListenersForEventType(EventEmitterImpl.java:458)
        at com.brightcove.player.event.EventEmitterImpl.invokeListenersForEvent(EventEmitterImpl.java:429)
        at com.brightcove.player.event.EventEmitterImpl.access$300(EventEmitterImpl.java:42)
        at com.brightcove.player.event.EventEmitterImpl$1.handleMessage(EventEmitterImpl.java:74)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:257)
        at android.app.ActivityThread.main(ActivityThread.java:8218)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```

I added the multidex library also. and this is my proguard of main app

```
-keep public class * extends com.brightcove.player.display.ExoPlayerVideoDisplayComponent
-keep public class * extends com.google.android.exoplayer2.trackselection.TrackSelection
-keep public class * extends com.google.android.exoplayer2.trackselection.DefaultTrackSelector

-keep public class com.google.android.exoplayer2.**{*;}
-keep public class com.google.android.exoplayer2.trackselection.**{*;}
-keep public class com.brightcove.player.**{*;}
-keep  interface com.google.android.exoplayer2.**{*;}
-keep  interface com.brightcove.player.**{*;}
-keep  interface android.os.**{*;}

-keepclassmembers class ** {
    @com.google.android.exoplayer2.trackselection.DefaultTrackSelector$Parameters <methods>;
}


-keepclasseswithmembers class * {
    @com.brightcove.player.* <methods>;
}
-keepclasseswithmembers class * {
    @com.google.android.exoplayer2.trackselection* <methods>;
}
```

**Comment by tonihei** [comment]
Whenever `NoSuchMethodError` or similar problems come up, it's usually one of two things:
 1. A build problem where the build system uses incompatible intermediate files to building the apk. You can try to fix this (or exclude it as the reason) by fully cleaning your project in Android Studio ("Build -> Clean project") and also running "File -> Invalidate Caches". 
 2. An unintended version upgrade of another dependent library that also uses ExoPlayer. Based on your description, this is the likely reason. Gradle updates all ExoPlayer versions in the entire dependency tree to the same version and if you add one directly, the version brightcove is using is upgraded too and their code may no longer be compatible. You can check what gradle is doing by running `./gradlew yourAppGradleTarget:dependencies`.

**Comment by tonihei** [comment]
Closing due to inactivity.
