### ISSUE TITLE
MP4 Parser issue after update to 2.18.0

### ISSUE THREAD

**Issue by Tolriq** [google/ExoPlayer#10381]
### ExoPlayer Version

2.18.0

### Devices that reproduce the issue

All

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play the media that I'll send by mail after;

### Expected result

IT plays on 2.17.1 and previous versions

### Actual result

Parser error:

```
playerFailed [eventTime=9.03, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_IO_UNSPECIFIED
  com.google.android.exoplayer2.ExoPlaybackException: Source error
	  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
	  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:608)
	  at android.os.Handler.dispatchMessage(Handler.java:102)
	  at android.os.Looper.loopOnce(Looper.java:201)
	  at android.os.Looper.loop(Looper.java:288)
	  at android.os.HandlerThread.run(HandlerThread.java:67)
  Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: Top bit not zero: -44491104
	  at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:433)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	  at java.lang.Thread.run(Thread.java:920)
  Caused by: java.lang.IllegalStateException: Top bit not zero: -44491104
	  at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:371)
	  at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseEsdsFromParent(AtomParsers.java:1686)
	  at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseAudioSampleEntry(AtomParsers.java:1516)
	  at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:987)
	  at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:311)
	  at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:132)
	  at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:515)
	  at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:474)
	  at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:456)
	  at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:254)
	  at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
	  at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
	  at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
	  at java.lang.Thread.run(Thread.java:920) 
]
```

### Media

Will send by mail

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by Tolriq** [comment]
Did you get the file?

**Comment by rohitjoins** [comment]
Cannot access the file as it needs access to Google drive.

**Comment by Tolriq** [comment]
@rohitjoins I think I've fixed the perms to allow anyone. Else I'll put the file elsewhere.

**Comment by rohitjoins** [comment]
Was able to access the file and reproduce the issue on the demo app version 2.18.0. We're looking into this.

**Comment by rohitjoins** [comment]
A [fix](https://github.com/google/ExoPlayer/commit/9e10286b5ea624b8a7533e5fc452b19476589764) for this bug has been released in the dev-v2 branch.

**Comment by Tolriq** [comment]
@rohitjoins thanks. Do you have an eta for next release? I'm in beta with current version and just need to know if I should revert or wait for fix before release. No need for precise date.

**Comment by rohitjoins** [comment]
@Tolriq [release](https://github.com/google/ExoPlayer/releases/tag/r2.18.1) is done with the fix.
