### ISSUE TITLE
Missing CodecPrivate for codec A_OPUS

### ISSUE THREAD

**Issue by ec-siddhant** [google/ExoPlayer#10384]
I am getting this error on playing a .webm video

**Missing CodecPrivate for codec A_OPUS**

What does It mean, and can it be solved, there are no references on Intenet for this log, please help.

here is the whole log I am getting:

```
E/ExoPlayerImplInternal(10376): Playback error
E/ExoPlayerImplInternal(10376):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
E/ExoPlayerImplInternal(10376):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(10376):       at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal(10376):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(10376):   Caused by: com.google.android.exoplayer2.ParserException: Missing CodecPrivate for codec A_OPUS
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$Track.getCodecPrivate(MatroskaExtractor.java:2511)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$Track.initializeOutput(MatroskaExtractor.java:2084)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.endMasterElement(MatroskaExtractor.java:799)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$InnerEbmlProcessor.endMasterElement(MatroskaExtractor.java:1925)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.extractor.mkv.DefaultEbmlReader.read(DefaultEbmlReader.java:88)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.read(MatroskaExtractor.java:510)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(10376):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(10376):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(10376):       at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal(10376): Playback error
E/ExoPlayerImplInternal(10376):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
E/ExoPlayerImplInternal(10376):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(10376):       at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal(10376):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(10376):   Caused by: com.google.android.exoplayer2.ParserException: Missing CodecPrivate for codec A_OPUS
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$Track.getCodecPrivate(MatroskaExtractor.java:2511)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$Track.initializeOutput(MatroskaExtractor.java:2084)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.endMasterElement(MatroskaExtractor.java:799)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$InnerEbmlProcessor.endMasterElement(MatroskaExtractor.java:1925)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.extractor.mkv.DefaultEbmlReader.read(DefaultEbmlReader.java:88)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.read(MatroskaExtractor.java:510)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
E/ExoPlayerImplInternal(10376):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(10376):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(10376):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(10376):       at java.lang.Thread.run(Thread.java:919)
```

**Comment by rohitjoins** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can
be found [here](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml).
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.

**Comment by rohitjoins** [comment]
Hi @ec-siddhant,

Based on the [definition](https://wiki.xiph.org/MatroskaOpus) of `opus` codec in `Matroska` container, the `HeaderInfo` should contain `CodecPrivate` consisting of the `OpusHead` packet.

As this data is missing from your media file, we throw this error when parsing the file. You can inspect your media file using [`mkvinfo`](https://mkvtoolnix.download/doc/mkvinfo.html)
