### ISSUE TITLE
[Crash] NullPointerException - com.google.android.exoplayer2.util.Util.isTv(Util.java:2232)

### ISSUE THREAD

**Issue by raghav2945** [google/ExoPlayer#10392]
### ExoPlayer Version

2.15.1

### Devices that reproduce the issue

Multiple devices:

1. Samsung
2. Motorola
3. TECNO MOBILE

### Reproducible in the demo app?

Not tested

### Reproduction steps

Unknow. As this issue is not locally replicated. Issue has been reported over firebase and the count is high. 

### Expected result

No crash and media play as expected.

### Actual result

Crash reported over Firebase with below stack-trace

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
       at com.google.android.exoplayer2.util.Util.isTv(Util.java:2232)
       at com.google.android.exoplayer2.audio.AudioCapabilities.getCapabilities(AudioCapabilities.java:94)
       at com.google.android.exoplayer2.audio.AudioCapabilities.getCapabilities(AudioCapabilities.java:82)
       at com.google.android.exoplayer2.DefaultRenderersFactory.buildAudioSink(DefaultRenderersFactory.java:637)
       at com.google.android.exoplayer2.DefaultRenderersFactory.createRenderers(DefaultRenderersFactory.java:320)
       at com.google.android.exoplayer2.SimpleExoPlayer.<init>(SimpleExoPlayer.java:725)
       at com.google.android.exoplayer2.SimpleExoPlayer$Builder.build(SimpleExoPlayer.java:625)
       at com.audiomack.playback.Players.initExoPlayer(Players.kt:76)
       at com.audiomack.playback.Players.access$initExoPlayer(Players.kt:22)
       at com.audiomack.playback.Players$2.invokeSuspend(Players.kt:33)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### Media

Not applicable.
Application name & Google playstore link - [Audiomack](https://play.google.com/store/apps/details?id=com.audiomack&hl=en&gl=US)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by raghav2945** [comment]
This error is not always reported by Util. Other classes that report the same details include WakeLockManager, AudioFocusManager, AudioBecomingNoisyManager, and so on. However, the one below is common in all. 

> com.google.android.exoplayer2.SimpleExoPlayer.<init>(SimpleExoPlayer.java)

**Comment by raghav2945** [comment]
Is there any new update on this?

**Comment by icbaker** [comment]
The NPE is ultimately happening because `DefaultRenderersFactory.context` is null. There isn't enough information provided to know exactly where that value is coming from (i.e. which `DefaultRenderersFactory` constructor is used in your app), but I believe in all cases this `Context` value is provided from your app (e.g. via one of the `SimpleExoPlayer.Builder` constructors if you don't construct `DefaultRenderersFactory` yourself manually).

ExoPlayer uses package-level annotations to indicate that everything is non-null by default, and we explicitly annotate nullable properties with `@Nullable`. The `Context` parameters described above are not `@Nullable` so null should never be passed.

So I think this boils down to: Don't pass a null value to a non-null constructor parameter.
