### ISSUE TITLE
sending message to a Handler on a dead thread #426

### ISSUE THREAD

**Issue by mirwisek** [google/ExoPlayer#10416]
### ExoPlayer Version

2.18.0

### Devices that reproduce the issue

* Xiaomi Pocco F3 (Android 12)

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Create a `ViewPager2` with viewpager's `offscreenPageLimit >= 2`
2. The ViewPager adapter fragments should contain a single `StyledPlayerView`
3. For each ViewPager adapter item fragment, the ExoPlayer should be initialized and prepared in `onViewCreated`
4. Set `onResume` as follows:
 ```
player?.apply {
            seekTo(0)
// try calling play() if seekTo() does not trigger the error
            playWhenReady = true
        }
```
5. Set `onPause` as follows:
```
player?.apply {
// try calling stop() if seekTo() does not trigger the error
            playWhenReady = false
        }
```

### Expected result

The video should seek to 0 position and start playing

### Actual result

when scrolling forward the `viewPager` the media plays fine but when scrolling backward while calling `onResume` the error occurs

```
W/MessageQueue: Handler (android.os.Handler) {fb8358b} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {fb8358b} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:569)
        at android.os.Handler.enqueueMessage(Handler.java:778)
        at android.os.Handler.sendMessageAtTime(Handler.java:727)
        at android.os.Handler.sendMessageDelayed(Handler.java:697)
        at android.os.Handler.sendMessage(Handler.java:635)
        at android.os.Message.sendToTarget(Message.java:482)
        at com.google.android.exoplayer2.util.SystemHandlerWrapper$SystemMessage.sendToTarget(SystemHandlerWrapper.java:153)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.seekTo(ExoPlayerImplInternal.java:322)
        at com.google.android.exoplayer2.ExoPlayerImpl.seekTo(ExoPlayerImpl.java:827)
        at com.google.android.exoplayer2.BasePlayer.seekTo(BasePlayer.java:131)
```

### Media

Not applicable

### Intent (Scenario)

I'm creating a ViewPager that need to set `MediaSource` once during `onCreate` and I want the playback to start immediately at `onResume`. I have achieved this goal already but when I come back to the old fragment and `onResume` is called, I want the video to play from the start but during call to `seekTo(0)` triggers the error. I have tried without `seekTo(0)` the video continues fine from where it left off. The error only triggers with call to `seekTo()`

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment]
Can you please share a minimal project that reproduces this error so that we can test?
