### ISSUE TITLE
ExoPlayer in Android not load with M3U8 + QueryParameter(auth)

### ISSUE THREAD

**Issue by rabinansal** [google/ExoPlayer#10430]
I am using com.google.android.exoplayer2 and I had to load / streaming videos like

http://raax.xyz/SportsCornerGroup/playlist.m3u8?ch=star1in|User-Agent=SportsCornerGroup&Referer=https://noob4cast.com&cookie=SportsCornerGroup

 player is not loading this videos.

**Comment by marcbaechinger** [comment]
You need to provide a bit more info so we know what is going wrong exactly.

In the case of the URL above I do a 

```
curl --verbose "http://raax.xyz/SportsCornerGroup/playlist.m3u8?ch=star1in|User-Agent=SportsCornerGroup&Referer=https://noob4cast.com&cookie=SportsCornerGroup"
```

That gives a redirect that goes from http to https which ExoPlayer does not allow. See [DevGuide](https://exoplayer.dev/troubleshooting.html#why-do-some-streams-fail-with-http-response-code-301-or-302) also.

When I then copy the redirect URL manually and I do 

```
curl --verbose "https://raax.xyz/SportsCornerGroup/playlist.m3u8?ch=star1in|User-Agent=SportsCornerGroup&Referer=https://noob4cast.com&cookie=SportsCornerGroup"
```

i get a HTTP/200 but a blank page. 

This corresponds to the error message ` Input does not start with the #EXTM3U header.` that I get from ExoPlayer when I use the redirect URL directly:

```
E/ExoPlayerImplInternal: Playback error
      androidx.media3.exoplayer.ExoPlaybackException: Source error
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:639)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:609)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: androidx.media3.common.ParserException: Input does not start with the #EXTM3U header.
        at androidx.media3.exoplayer.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:262)
        at androidx.media3.exoplayer.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:69)
        at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:182)
        at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

It looks like you need to fix the URI to make that work.

**Comment by rabinansal** [comment]
This url work in mx player

**Comment by marcbaechinger** [comment]
Without more information from your side I can't really help you I'm afraid. 

I'm happy to help you towards solving this if this is possible (see comment above also). You could on your side, for instance, provide a stack track, or tell us what network stack you are using in your app. You could also relate your comment to the answer I was giving  to confirm/reject the hypothesis made there in absence of sufficient information there. That would be a) polite, b) helpful for yourself to get a quick solution and c) it would make sure we are not going to investigate things that are probably not even the cause of your problem.

I'm adding the needs-more-info label as an aide-mémoire.

**Comment by rabinansal** [comment]
The question is how to use URL with M3U8 + Query Parameter. Above link has no problem it working in mx player
For detailed question see this below links 
https://stackoverflow.com/questions/67412832/exoplayer-in-android-not-load-with-m3u8-queryparameterauth

**Comment by marcbaechinger** [comment]
```
User-Agent=SportsCornerGroup&Referer=https://noob4cast.com&cookie=SportsCornerGroup
```

In case the URL parameters above are not URL parameters but HTTP header, you may want to read [this section of the DevGuide on how you can set HTTP headers](https://exoplayer.dev/customization.html#customizing-server-interactions). 

It looks like when setting the above URI parameters as HTTP headers with curl

```
> user-agent: SportsCornerGroup
> Referer: https://noob4cast.com
> Cookie: SportsCornerGroup
```

then response is not an empty page but a HLS manifest.
