### ISSUE TITLE
CMAF Widevine CBCS feed issue not playing with Android 9

### ISSUE THREAD

**Issue by SamirG** [google/ExoPlayer#10462]
We are trying to play CMAF stream+CBCS+Widevine DRM with exoplayer sample app. it works fine with android 11 and above. We are seeing the issues with android 9 devices and emulator. 

Not sure if that is player issue or device specific issue. have provided the sample stream and bug report over email. One thing to note here , in same device google sample exoplayer feed with CBCS works fine.

### ExoPlayer Version

2.18.0

### Devices that reproduce the issue

- AVD Pixel 5 API 28
- Samsung SMJ701F , SDK level 28 , Widevine Security Level 1

### Devices that do not reproduce the issue

- AVD Pixel API 30
- Redmi Note 8 Pro - Android 11

### Reproducible in the demo app?

Yes

### Reproduction steps

play the stream provided over email

### Expected result

Media should play with video and audio

### Actual result

```
2022-07-21 11:48:40.040 13969-16485/com.google.android.exoplayer2.demo I/OMXClient: IOmx service obtained
2022-07-21 11:48:40.047 13969-16484/com.google.android.exoplayer2.demo D/SurfaceUtils: connecting to surface 0xc8fa4808, reason connectToSurface
2022-07-21 11:48:40.049 13969-16484/com.google.android.exoplayer2.demo I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 14304265
2022-07-21 11:48:40.049 13969-16484/com.google.android.exoplayer2.demo D/SurfaceUtils: disconnecting from surface 0xc8fa4808, reason connectToSurface(reconnect)
2022-07-21 11:48:40.050 13969-16484/com.google.android.exoplayer2.demo D/SurfaceUtils: connecting to surface 0xc8fa4808, reason connectToSurface(reconnect)
2022-07-21 11:48:40.056 13969-16485/com.google.android.exoplayer2.demo E/ACodec: [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
2022-07-21 11:48:40.065 13969-16485/com.google.android.exoplayer2.demo I/ACodec: codec does not support config priority (err -1010)
2022-07-21 11:48:40.108 13969-13969/com.google.android.exoplayer2.demo D/EventLogger: videoDecoderInitialized [eventTime=0.91, mediaPos=20.00, window=0, period=0, OMX.google.h264.decoder]
2022-07-21 11:48:40.109 13969-13969/com.google.android.exoplayer2.demo D/EventLogger: videoInputFormat [eventTime=0.91, mediaPos=20.00, window=0, period=0, id=video-stream-5_SD_DRM-1, mimeType=video/avc, bitrate=2000000, codecs=avc1.4D401E, drm=[widevine,cenc], res=720x576, fps=25.0, roleFlags=[main]]
2022-07-21 11:48:40.408 13969-13969/com.google.android.exoplayer2.demo D/EventLogger: drmKeysLoaded [eventTime=1.21, mediaPos=20.00, window=0, period=0]
2022-07-21 11:48:40.413 13969-16473/com.google.android.exoplayer2.demo E/MediaCodecVideoRenderer: Video codec error
      android.media.MediaCodec$CodecException: Error 0x80000000
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2608)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:149)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1358)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2022-07-21 11:48:40.415 13969-16473/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(video-stream-5_SD_DRM-1, null, null, video/avc, avc1.4D401E, 2000000, null, [720, 576, 25.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.google.h264.decoder
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1590)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2608)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:149)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1358)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
2022-07-21 11:48:40.420 13969-13969/com.google.android.exoplayer2.demo D/EventLogger: videoDisabled [eventTime=1.22, mediaPos=20.00, window=0, period=0]
2022-07-21 11:48:40.422 13969-13969/com.google.android.exoplayer2.demo D/EventLogger: audioDisabled [eventTime=1.22, mediaPos=20.00, window=0, period=0]
2022-07-21 11:48:40.446 13969-16484/com.google.android.exoplayer2.demo D/SurfaceUtils: disconnecting from surface 0xc8fa4808, reason disconnectFromSurface
2022-07-21 11:48:40.462 13969-13969/com.google.android.exoplayer2.demo D/EventLogger: videoDecoderReleased [eventTime=1.26, mediaPos=20.00, window=0, period=0, OMX.google.h264.decoder]
2022-07-21 11:48:40.486 13969-13969/com.google.android.exoplayer2.demo D/EventLogger: audioDecoderReleased [eventTime=1.29, mediaPos=20.00, window=0, period=0, OMX.google.aac.decoder]
2022-07-21 11:48:40.502 13969-16473/com.google.android.exoplayer2.demo W/MediaDrm: MediaDrm went away with unhandled events
2022-07-21 11:48:40.503 13969-16473/com.google.android.exoplayer2.demo W/MediaDrm: MediaDrm went away with unhandled events
2022-07-21 11:48:40.504 13969-13969/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=1.30, mediaPos=20.00, window=0, period=0, errorCode=ERROR_CODE_DECODING_FAILED
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(video-stream-5_SD_DRM-1, null, null, video/avc, avc1.4D401E, 2000000, null, [720, 576, 25.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.google.h264.decoder
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1590)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2608)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:149)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1358)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

### Media

Will be shared over email

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by ojw28** [comment]
@rrfrias - Would you be able to take a look at this? It's easy to reproduce using a `Pixel 5 API 28` emulator in Android Studio (I'd normally suggest not using an emulator, but given it plays Widevine's sample CBCS content fine it seems as good as anything for working out what the difference is).

Note that the failing media was provided via email (subject: `Issue #10462`).

**Comment by rrfrias** [comment]
The [encryption cipher mode](https://developer.android.com/reference/android/media/MediaCodec.CryptoInfo#mode) is specified twice, once in the license and a second time when [MediaCodec#queueSecureInputBuffer](https://developer.android.com/reference/android/media/MediaCodec#queueSecureInputBuffer(int,%20int,%20android.media.MediaCodec.CryptoInfo,%20long,%20int)) is called. Exoplayer specifies this in [MediaCodec.CryptoInfo](https://developer.android.com/reference/android/media/MediaCodec.CryptoInfo). If these are in conflict, the mode specified when frames are queued is the one used. Due to limitations in the secure crypto library, this is not possible for devices running android 9/P and earlier and the two values must be consistent otherwise an exception is thrown. This appears to be what is happening in the log you shared.

Can you check the encryption mode specified in your license/policy configuration at the license service. Please contact your Widevine partner engineer or https://www.widevine.com/contact for additional assistance. Let me know if you still see problems after this.

**Comment by SamirG** [comment]
thanks @rrfrias , As you mentioned.issue seems to be with  license delivered.
