### ISSUE TITLE
Pausing the video trigger an error

### ISSUE THREAD

**Issue by Joadar** [google/ExoPlayer#10485]
### ExoPlayer Version

2.16.1

### Devices that reproduce the issue

* Emulator Pixel 2 API 30 (We can always repeat this error in ExoPlayer 2.14.1, 2.16.1 and 2.18.1)
* Emulator Pixel 2XL API 30
* Emulator Nexus 6P API 30

We got a lot of errors reported on Mux with different devices/Android version since we migrate from 2.14.1 to 2.16.1. 
On our side we can always repeat it on emulator with API 30 (from 2.14.1 to 2.18.1) but users got it in all API versions.

Not all devices from a model specific receive on a specific Android version received the error though. There is others conditions we don't know.

We agree that testing on emulator is not so great, but what we don't understand is we can repeat it on our side with a specific API version and not another one.

### Devices that do not reproduce the issue

* Emulator Pixel 2 API 29
* Emulator Pixel 2XL API 31
* Pixel 4XL API 32
* Pixel 5a API 32

### Reproducible in the demo app?

Yes

### Reproduction steps

* Run the demo app
* Play any video
* Pause
* Wait 5 seconds
* An error is happening but it is possible to continue to play the video.

Users are reporting to us they can play the video and have the error triggered when they pause the video.

### Expected result

No error is triggered.

### Actual result

From Mux, we have this result (ExoPlayer 2.16.1):

`com.google.android.exoplayer2.video.MediaCodecVideoDecoderException - Decoder failed: OMX.qcom.video.decoder.avc.secure`

`com.google.android.exoplayer2.video.MediaCodecVideoDecoderException - Decoder failed: OMX.MS.AVC.Decoder`

`com.google.android.exoplayer2.video.MediaCodecVideoDecoderException - Decoder failed: OMX.MTK.VIDEO.DECODER.AVC`

From Firebase, we have this result (ExoPlayer 2.16.1):
```
Non-fatal Exception: com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(4, null, null, video/avc, avc1.64001F, 1415720, null, [1280, 720, 30.0], [-1, -1]), format_supported=YES
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:214)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

```
Non-fatal Exception: com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(8, null, null, audio/mp4a-latm, mp4a.40.2, 199988, und, [-1, -1, -1.0], [2, 48000]), format_supported=YES
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

On our machine running demo app, we have this result:
```
2022-07-29 10:11:13.196 5112-5969/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported err 0x80000000, actionCode 0, while in state 6
2022-07-29 10:11:13.989 5112-5191/com.google.android.exoplayer2.demo E/MediaCodecVideoRenderer: Video codec error
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:99)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1190)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-07-29 10:11:13.991 5112-5191/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(4, null, null, video/avc, avc1.64002A, 18316946, null, [1920, 856, 24.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.android.avc.decoder
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1590)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:99)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1190)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2022-07-29 10:11:13.992 5112-5191/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2298)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:166)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:877)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:870)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:710)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:561)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:186)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1651)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1392)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1355)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:582)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-07-29 10:11:14.007 5112-5112/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=128.26, mediaPos=8.79, window=0, period=0, errorCode=ERROR_CODE_DECODING_FAILED
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(4, null, null, video/avc, avc1.64002A, 18316946, null, [1920, 856, 24.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.android.avc.decoder
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1590)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:99)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1190)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    ]
```

With some investigation, on ExoPlayer 2.17.1, it seems to come from `ExoPlayerImplInternal.java` where we have `stopInternal()` called line 591 that leads to the `releaseCodec()` method on `MediaCodecVideoRenderer.java`.

### Media

Nothing different from demo app.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
I'm unable to reproduce the problem. I did the following:

1. Installed ExoPlayer 2.18.1 demo app on an Pixel 2 API 30 emulator created inside Android Studio 2021.3.1 Beta 4.
2. Played Misc -> Dizzy (MP4)
3. Paused playback after a few seconds
4. Waited 5 seconds

I saw no errors in logcat, and resuming playback worked as expected.

Is there something you're doing differently to this in order to be able to repro? Does it repro every time for you?

**Comment by Joadar** [comment]
Here are my steps:
- Open demo app (release-v2 branch)
- Clear Dash -> HD (MP4, H264)
- I have the following result (see video)
- Configuration:
-- Android Studio 2021.2.1 Patch 1
-- Emulator: Pixel 2 API 30, Android 11 Google Play | arm64

And yes, with this specific emulator (API 30), I can always reproduce the error, but not in other API. The configuration doesn't change with other API.

https://user-images.githubusercontent.com/3017042/182275352-5b819879-77f9-40c4-9fcf-cf269d992693.mov


I can't play as you do "Misc -> Dizzy (MP4)", I have the following error with the same emulator (but not with physical device Pixel 4XL API 32, I can play the cat video).

```
2022-08-02 10:01:06.815 30499-30499/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=0.44, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: ev: Exception in CronetUrlRequest: net::ERR_CONNECTION_RESET, ErrorCode=8, InternalErrorCode=-101, Retryable=true
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:545)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1005)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: ev: Exception in CronetUrlRequest: net::ERR_CONNECTION_RESET, ErrorCode=8, InternalErrorCode=-101, Retryable=true
        at org.chromium.net.impl.CronetUrlRequest.onError(:com.google.android.gms.dynamite_cronetdynamite@221820081@22.18.20 (150400-0):4)
    ]
2022-08-02 10:01:06.849 30499-30499/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=0.48, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: ev: Exception in CronetUrlRequest: net::ERR_CONNECTION_RESET, ErrorCode=8, InternalErrorCode=-101, Retryable=true
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:545)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1005)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: ev: Exception in CronetUrlRequest: net::ERR_CONNECTION_RESET, ErrorCode=8, InternalErrorCode=-101, Retryable=true
        at org.chromium.net.impl.CronetUrlRequest.onError(:com.google.android.gms.dynamite_cronetdynamite@221820081@22.18.20 (150400-0):4)
    ]
2022-08-02 10:01:07.891 30499-30499/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=1.52, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: ev: Exception in CronetUrlRequest: net::ERR_CONNECTION_RESET, ErrorCode=8, InternalErrorCode=-101, Retryable=true
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:545)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1005)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: ev: Exception in CronetUrlRequest: net::ERR_CONNECTION_RESET, ErrorCode=8, InternalErrorCode=-101, Retryable=true
        at org.chromium.net.impl.CronetUrlRequest.onError(:com.google.android.gms.dynamite_cronetdynamite@221820081@22.18.20 (150400-0):4)
    ]
2022-08-02 10:01:09.930 30499-30499/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=3.56, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: ev: Exception in CronetUrlRequest: net::ERR_CONNECTION_RESET, ErrorCode=8, InternalErrorCode=-101, Retryable=true
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:545)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1005)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: ev: Exception in CronetUrlRequest: net::ERR_CONNECTION_RESET, ErrorCode=8, InternalErrorCode=-101, Retryable=true
        at org.chromium.net.impl.CronetUrlRequest.onError(:com.google.android.gms.dynamite_cronetdynamite@221820081@22.18.20 (150400-0):4)
    ]
2022-08-02 10:01:09.934 30499-32336/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:604)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: ev: Exception in CronetUrlRequest: net::ERR_CONNECTION_RESET, ErrorCode=8, InternalErrorCode=-101, Retryable=true
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:545)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1005)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: ev: Exception in CronetUrlRequest: net::ERR_CONNECTION_RESET, ErrorCode=8, InternalErrorCode=-101, Retryable=true
        at org.chromium.net.impl.CronetUrlRequest.onError(:com.google.android.gms.dynamite_cronetdynamite@221820081@22.18.20 (150400-0):4)
2022-08-02 10:01:09.934 30499-30499/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=3.56, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_IO_NETWORK_CONNECTION_FAILED
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:604)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: ev: Exception in CronetUrlRequest: net::ERR_CONNECTION_RESET, ErrorCode=8, InternalErrorCode=-101, Retryable=true
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:545)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1005)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: ev: Exception in CronetUrlRequest: net::ERR_CONNECTION_RESET, ErrorCode=8, InternalErrorCode=-101, Retryable=true
        at org.chromium.net.impl.CronetUrlRequest.onError(:com.google.android.gms.dynamite_cronetdynamite@221820081@22.18.20 (150400-0):4)
    ]
```

**Comment by icbaker** [comment]
Thanks - the only difference I see (apart from the asset used, and I was also unable to repro with the DASH asset) is that I'm using an x86-based emulator and yours is ARM-based. From your screencast it looks like you're on MacOS, is that an ARM-powered machine? When I instantiate an ARM emulator on my x86 machine it warns me about performance impact. Unfortunately it then completely fails to start the ARM-based emulator (my x86 environment is a little unusual), so I can't verify if this is the cause of the difference.

If this is a pecularity of the ARM emulators then I don't think there's much actionable for the ExoPlayer library here (if you believe this is an emulator bug you can report it as described here: https://developer.android.com/studio/report-bugs.html#emulator-bugs)

Given that you're unable to reproduce the real-world issue on any real devices, is it possible that this emulator problem you've found is a slightly different issue to that captured by your error reporting?

**Comment by Joadar** [comment]
Okay thank you for your answer. It's running on a MacBook Pro M1.

It's just users reported to us the same issue on their side (different API and devices) and we were surprised that we could reproduce exactly the same thing.

We will report to Android Studio.

Thank you for your help!

**Comment by icbaker** [comment]
@Joadar OOI, did you file a bug against Android Studio? If so, would you be able to share the link here? Thanks!
