### ISSUE TITLE
Unable to play widevine protected video on Samsung Galaxy S4

### ISSUE THREAD

**Issue by PetrSklenicka** [google/ExoPlayer#1048]
Hello,
I am using Exoplayer (version 1.4.2) for playing widevine protected movies and it works fine with almost all devices. But I have a problem with my Samsung Galaxy S4 with Android version 5.0.1. If I am trying to play movie, I am getting this exception:

```
2-11 15:44:40.505 8213-9634/cz.company.player E/ExoPlayerImplInternal: Internal track renderer error.
                                                                    com.google.android.exoplayer.ExoPlaybackException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: DRM vendor-defined error: -2998
                                                                        at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:330)
                                                                        at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:739)
                                                                        at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:372)
                                                                        at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:511)
                                                                        at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:492)
                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                        at android.os.Looper.loop(Looper.java:145)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                     Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: DRM vendor-defined error: -2998
                                                                        at android.media.MediaDrm.getKeyRequest(Native Method)
                                                                        at com.google.android.exoplayer.drm.StreamingDrmSessionManager.postKeyRequest(StreamingDrmSessionManager.java:367)
                                                                        at com.google.android.exoplayer.drm.StreamingDrmSessionManager.openInternal(StreamingDrmSessionManager.java:319)
                                                                        at com.google.android.exoplayer.drm.StreamingDrmSessionManager.open(StreamingDrmSessionManager.java:289)

```

Also, I tried to play some video from PlayMovies application and it does not work too. I am getting very similar exception:

```
E/PlayMovies: WidevineMediaDrmWrapper.requestLicenseInternal:499 Unexpected error during license request
                                               THROWABLE:
                                               android.media.MediaDrm$MediaDrmStateException: Failed to get key request: DRM vendor-defined error: -2998
12-11 15:45:21.385 10872-11265/? E/ExoPlayerImplInternal: Internal track renderer error.
                                                          com.google.android.exoplayer.ExoPlaybackException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: DRM vendor-defined error: -2998
                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(SourceFile:335)
                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(SourceFile:750)
                                                              at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(SourceFile:372)
                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(SourceFile:520)
                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(SourceFile:498)
                                                              at com.google.android.videos.service.player.exo.VideoRenderer.doSomeWork(SourceFile:65)
                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(SourceFile:415)
                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(SourceFile:205)
                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                              at android.os.Looper.loop(Looper.java:145)
                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                              at com.google.android.exoplayer.util.PriorityHandlerThread.run(SourceFile:40)
                                                           Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: DRM vendor-defined error: -2998
                                                              at android.media.MediaDrm.getKeyRequest(Native Method)
                                                              at com.google.android.videos.service.drm.WidevineMediaDrmWrapper.requestLicenseInternal(SourceFile:478)
                                                              at com.google.android.videos.service.drm.WidevineMediaDrmWrapper.requestLicense(SourceFile:467)
                                                              at com.google.android.videos.service.player.exo.WidevineDrmSessionManager.onStreamingLicenseError(SourceFile:316)
                                                              at com.google.android.videos.service.player.exo.WidevineDrmSessionManager.access$1400(SourceFile:41)
                                                              at com.google.android.videos.service.player.exo.WidevineDrmSessionManager$StreamingLicenseCallback.onError(SourceFile:383)
                                                              at com.google.android.videos.service.async.ThreadingCallback$CallbackRunnable.run(SourceFile:134)
                                                              at com.google.android.videos.service.async.HandlerCallback.post(SourceFile:44)
                                                              at com.google.android.videos.service.async.ThreadingCallback.onError(SourceFile:48)
                                                              at com.google.android.videos.service.drm.WidevineMediaDrmWrapper.reportErrorToClient(SourceFile:577)
                                                              at com.google.android.videos.service.drm.WidevineMediaDrmWrapper.requestLicenseInternal(SourceFile:500)
                                                              at com.google.android.videos.service.drm.WidevineMediaDrmWrapper.requestLicense(SourceFile:467)
                                                              at com.google.android.videos.service.player.exo.WidevineDrmSessionManager.loadInitialLicense(SourceFile:183)
                                                              at com.google.android.videos.service.player.exo.WidevineDrmSessionManager.onOpened(SourceFile:171)
                                                              at com.google.android.videos.service.player.exo.WidevineDrmSessionManager.access$900(SourceFile:41)
                                                              at com.google.android.videos.service.player.exo.WidevineDrmSessionManager$OpenCallback.onResponse(SourceFile:350)
                                                              at com.google.android.videos.service.player.exo.WidevineDrmSessionManager$OpenCallback.onResponse(SourceFile:346)
                                                              at com.google.android.videos.service.async.ThreadingCallback$CallbackRunnable.run(SourceFile:132)
                                                              at com.google.android.videos.service.async.HandlerCallback.post(SourceFile:44)
                                                              at com.google.android.videos.service.async.ThreadingCallback.onResponse(SourceFile:41)
                                                              at com.google.android.videos.service.drm.WidevineMediaDrmWrapper.reportResponseToClient(SourceFile:567)
                                                              at com.google.android.videos.service.drm.WidevineMediaDrmWrapper.openInternal(SourceFile:305)
                                                              at com.google.android.videos.service.drm.WidevineMediaDrmWrapper.open(SourceFile:290)
                                                              at com.google.android.videos.service.player.exo.WidevineDrmSessionManager.open(SourceFile:153)
                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(SourceFile:330)
                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(SourceFile:750) 
                                                              at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(SourceFile:372) 
                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(SourceFile:520) 
                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(SourceFile:498) 
                                                              at com.google.android.videos.service.player.exo.VideoRenderer.doSomeWork(SourceFile:65) 
                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(SourceFile:415) 
                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(SourceFile:205) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                              at android.os.Looper.loop(Looper.java:145) 
                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
```

Is there any way how can I solve it? Thank you.

**Comment by PetrSklenicka** [comment]
I also tested a new version of Exoplayer (1.5.3) and I have the same problem.

**Comment by wvpaf** [comment]
Please provide full unfiltered with system messages log and an ADB bug report.

thanks,

**Comment by wvpaf** [comment]
@PetrSklenicka,  any updates? 
almost 3 months without a ADB Bugreport. Will monitor for a couple more weeks then will close.
