### ISSUE TITLE
EnableHdrEditing catch a exception

### ISSUE THREAD

**Issue by StephenGiant** [google/ExoPlayer#10525]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Sony Xperia5 || Android 12

### Devices that do not reproduce the issue

no

### Reproducible in the demo app?

Yes

### Reproduction steps

1、enable hdrediting
2、use gleffect
3、start transform processing
4、catch a exception 

### Expected result

get transformed video file

### Actual result

Caused by: java.lang.IllegalStateException
2022-08-16 10:47:08.704 25420-25596/com.google.android.exoplayer2.transformerdemo W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
2022-08-16 10:47:08.704 25420-25596/com.google.android.exoplayer2.transformerdemo W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
2022-08-16 10:47:08.704 25420-25596/com.google.android.exoplayer2.transformerdemo W/System.err:     at com.google.android.exoplayer2.transformer.DefaultCodec.maybeDequeueOutputBuffer(DefaultCodec.java:293)

### Media

a 1080p 10bit hdr video

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by andrewlewis** [comment]
`TransformationRequest.experimental_setEnableHdrEditing` is an experimental feature and isn't supported on most devices. For the case you describe it definitely won't be supported because it requires Android 13.
