### ISSUE TITLE
 Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference

### ISSUE THREAD

**Issue by vimal1695** [google/ExoPlayer#10580]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Galaxy A20s
Lenovo Tab P10

### Devices that do not reproduce the issue

Unable to reproduce the issue

### Reproducible in the demo app?

No

### Reproduction steps

Example
Unable to reproduce the crash

### Expected result

Media Play Successful without crash

### Actual result

Fatal Exception: java.lang.IllegalArgumentException: Bad stream type -1
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2441)
       at android.os.Parcel.createException(Parcel.java:2421)
       at android.os.Parcel.readException(Parcel.java:2404)
       at android.os.Parcel.readException(Parcel.java:2346)
       at android.media.IAudioService$Stub$Proxy.getDevicesForStream(IAudioService.java:6999)
       at android.media.MediaRouter.isAudioPathA2DPStatic(MediaRouter.java:3310)
       at android.media.MediaRouter.selectDefaultRouteStatic(MediaRouter.java:1172)
       at android.media.MediaRouter.removeRouteStatic(MediaRouter.java:1288)
       at android.media.MediaRouter.removeUserRoute(MediaRouter.java:1244)
       at androidx.mediarouter.media.MediaRouterJellybean.removeUserRoute(MediaRouterJellybean.java:1)
       at androidx.mediarouter.media.SystemMediaRouteProvider$JellybeanImpl.onSyncRouteRemoved(SystemMediaRouteProvider.java:6)
       at androidx.mediarouter.media.MediaRouter$GlobalMediaRouter$CallbackHandler.syncWithSystemProvider(MediaRouter.java:2)
       at androidx.mediarouter.media.MediaRouter$GlobalMediaRouter$CallbackHandler.handleMessage(MediaRouter.java:7)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by vimal1695** [comment]
Wrong crash report
