### ISSUE TITLE
How to play a live RTSP video stream

### ISSUE THREAD

**Issue by yangpengliao** [google/ExoPlayer#10589]
```
2022-09-06 17:18:35.076 24379-24407/com.jianguo.exoplayerdemo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:608)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.source.rtsp.RtspMediaSource$RtspPlaybackException: rtsp://111.1.24.140:554/pag://10.22.254.135:7302:33108100001320354299:0:MAIN:TCP/trackID=video?streamform=rtp
        at com.google.android.exoplayer2.source.rtsp.RtspMediaPeriod$InternalListener.onLoadError(RtspMediaPeriod.java:555)
        at com.google.android.exoplayer2.source.rtsp.RtspMediaPeriod$InternalListener.onLoadError(RtspMediaPeriod.java:479)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:489)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: com.google.android.exoplayer2.ParserException: RTP H264 packetization mode [0] not supported.
        at com.google.android.exoplayer2.source.rtsp.reader.RtpH264Reader.consume(RtpH264Reader.java:108)
        at com.google.android.exoplayer2.source.rtsp.RtpExtractor.read(RtpExtractor.java:178)
        at com.google.android.exoplayer2.source.rtsp.RtpDataLoadable.load(RtpDataLoadable.java:159)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

I can play it on VLC, but I can't play it on  ExoPlayer

**Comment by marcbaechinger** [comment]
I think the reason is what the stack trace says: `RTP H264 packetization mode [0] not supported`

**Comment by yangpengliao** [comment]
> I think the reason is what the stack trace says: `RTP H264 packetization mode [0] not supported`
I see, does this mean I can't play videos in this format?
