### ISSUE TITLE
Exoplayer having playback issues with certain url having mime-type: audio/mp4a-latm

### ISSUE THREAD

**Issue by vikaspAlgoworks** [google/ExoPlayer#10605]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

* Oneplus 8T Android 12 
* Android 12 Arm Emulator

### Reproducible in the demo app?

Reproducible in 2.17.1 as well as in the latest 2.18.1 

### Reproduction steps

1. Try to play the media with these urls:

Urls can be shared upon the request

### Expected result

The video should play perfectly.

### Actual result

The playback closes with source error as mentioned below
` Caused by: com.google.android.exoplayer2.source.hls.SampleQueueMappingException: Unable to bind a sample queue to TrackGroup with mime type audio/mp4a-latm.
        at com.google.android.exoplayer2.source.hls.HlsSampleStream.maybeThrowError(HlsSampleStream.java:62)
        at com.google.android.exoplayer2.BaseRenderer.maybeThrowStreamError(BaseRenderer.java:156)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1011)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)`

### Media

Urls can be shared upon the request

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by skfaisal93** [comment]
Please share your full code so that I can look into it

**Comment by vikaspAlgoworks** [comment]
Hi @skfaisal93, The issue is reproducible in the Exoplayer demo [2.18.1](https://github.com/google/ExoPlayer/tree/r2.18.1) as well. You can try out with this media files mentioned with the same.

**Comment by vikaspAlgoworks** [comment]
@christosts ,I have shared the media urls on email [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com). Please check the email.

**Comment by nikkysliv** [comment]
@tianyif Is there any fix provided for this issue ?
