### ISSUE TITLE
Error parsing segmented .vtt 

### ISSUE THREAD

**Issue by baboya** [google/ExoPlayer#1060]
Hi, 
For those who are very kind and willing to help me with this issue I will share the url so please let me know your email address.
Thanks, 

```
E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: java.io.EOFException
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:87)
            at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114)
            at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
12-14 22:21:41.034    2644-2644/com.bwm.cinematix E/EventLogger﹕ playerFailed [3.40]
    com.google.android.exoplayer.ExoPlaybackException: java.io.EOFException
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:87)
            at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114)
            at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
```

**Comment by ojw28** [comment]
We don't support WebVTT for HLS yet. Tracked by #151.

**Comment by baboya** [comment]
?
But I was able to parse a single .vtt file using the below code and it works fine. 
The issue is when parsing subtitle manifest file (for example, caption-en.m3u8)... 
I can get .vtt file to work if it's just ONE file. 

SingleSampleSource textSampleSource = new SingleSampleSource(sampleUri, textDataSource,
           MediaFormat.createTextFormat("1", "text/vtt", MediaFormat.NO_VALUE,
           TrackRenderer.MATCH_LONGEST_US, null));

Thanks,

**Comment by ojw28** [comment]
The ability to parse a single vtt file doesn't imply that we support segmented WebVTT described in a HLS media playlist. This is not something we support yet.

Also, if you're not doing this in the context of an HLS playback (i.e. video/audio also delivered using HLS) then this use case is really strange, and is likely something we will never properly support. If it is in the context of an HLS playback, we will be adding support as tracked by #151.
