### ISSUE TITLE
OOM in DefaultAllocator

### ISSUE THREAD

**Issue by richk** [google/ExoPlayer#1061]
Have been noticing this crash in production app after integrating with Exoplayer.
```
Fatal Exception: java.lang.OutOfMemoryError
       at com.google.android.exoplayer.upstream.DefaultAllocator.allocate(DefaultAllocator.java:79)
       at com.google.android.exoplayer.extractor.RollingSampleBuffer.prepareForAppend(RollingSampleBuffer.java:439)
       at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:409)
       at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:261)
       at com.google.android.exoplayer.extractor.ts.H264Reader.consume(H264Reader.java:102)

```

DefaultAllocator is being initialized with 64k as the value for argument

```
public DefaultAllocator(int individualAllocationSize) {
        this(individualAllocationSize, 0);
    }
```

Any recommendations on optimal size or factors/constraints to consider while choosing this number?

**Comment by ojw28** [comment]
An OutOfMemoryError tells you that your application has run out of memory, but does not tell you why. The point at which an OutOfMemoryError is thrown (i.e. the stack trace above) is often relatively meaningless. It may well be being thrown because some other part of your code is leaking or using an excessive amount of memory.

You should probably do some investigations around RAM usage of your application. [This guide](http://developer.android.com/tools/debugging/debugging-memory.html) may provide a good starting point. Depending on what OS version you're seeing the failure on, setting `android:largeHeap` to true in your manifest resolve the issue for you in the case that you simply need a bit more memory for your application to run.
