### ISSUE TITLE
HLS/CBCS Widevine DRM Playback problem

### ISSUE THREAD

**Issue by Ascii91** [google/ExoPlayer#10663]
We have a problem playing HLS/CBCS Widevine DRM on Android using the ExoPlayer library.
It works fine with Android 11 and above but we are seeing the issues with random Android devices Android OS <= 10. Also we can reproduce this issue on Android emulators.

We’ve tried forcing software decoding and selecting different stream profiles but it didn’t help. It looks like the problem is related to the Android OS version (Xiaomi with Android < 10 doesn’t work and with version 10 works fine). We’ve tried playing provided test streams from the ExoPlayer demo app and they are working on all supported devices. 
 “Error 0x80000000" from error logs appears to be a generic error.

### ExoPlayer Version

2.16.1

### Devices that reproduce the issue

Xiaomi Mi A2 (Android 8.1)
Xiaomi Mi A2 (Android 9.0)
Google Pixel XL (Android 10)
Sony Xperia XA1 (Android 7.1.1) 
Emulator AVD Pixel 5 API 28

### Devices that do not reproduce the issue

Google Pixel 4XL (Android 13)
Xiaomi Mi A2 (Android 10)
Samsung Galaxy A71 (Android 11)
Samsung Galaxy s8 (Android 9.0)
Emulator AVD Pixel 5 API 32

### Reproducible in the demo app?

Yes

### Reproduction steps

Play the stream provided.

### Expected result

Media should play with video and audio

### Actual result

Playback crashes with folowing stacktrace:

```
      android.media.MediaCodec$CodecException: Error 0x80000000
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2699)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:150)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1418)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:860)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-09-30 17:16:18.578 28519-28581/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.42C016, 1722000, null, [448, 200, -1.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc.secure
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1512)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:880)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2699)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:150)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1418)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:860)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
```

### Media

Stream url: 

https://demo.unified-streaming.com/k8s/features/no-handler-origin/multi-format-drm/master.m3u8

Licence server uri: 

https://cwip-shaka-proxy.appspot.com/no_auth

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by Ascii91** [comment]
Same issue : https://github.com/google/ExoPlayer/issues/10462
Problem resolved by updating licence configuration.
