### ISSUE TITLE
Failed to initialize decoder: OMX.TI.DUCATI1.VIDEO.DECODER

### ISSUE THREAD

**Issue by alekssunsss** [google/ExoPlayer#10665]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Kindle Fire HD (3rd Generation) 

### Devices that do not reproduce the issue

Samsung galaxy Tab E (Android 4.4), 
Samsung Galaxy A5 (Android 8), 
Amazon Fire HD 8 (10th Generation), 
Amazon Fire HD 10 (11th Generation), 
Samsung Galaxy Tab A7 Lite (Android 11)

### Reproducible in the demo app?

Not tested

### Reproduction steps

The issue reproduces every time when we are trying to play the video at the start of our application on device Kindle Fire HD (3rd Generation)

### Expected result

video file plays without issues

### Actual result

Playback error 

```
09-27 16:16:12.616  7757  8022 W MediaCodecRenderer: Failed to initialize decoder: OMX.TI.DUCATI1.VIDEO.DECODER

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:   java.lang.IllegalStateException: start failed

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:       at android.media.MediaCodec.start(Native Method)

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:58)

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:       at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:110)

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:877)

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:       at android.os.Handler.dispatchMessage(Handler.java:98)

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:       at android.os.Looper.loop(Looper.java:145)

09-27 16:16:12.616  7757  8022 W MediaCodecRenderer:       at android.os.HandlerThread.run(HandlerThread.java:61)

09-27 16:16:12.616  7757  8022 E dalvikvm: Could not find class 'android.media.MediaCodec$CodecException', referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException.getDiagnosticInfoV21

09-27 16:16:12.616  7757  8022 W dalvikvm: VFY: unable to resolve instanceof 216 (Landroid/media/MediaCodec$CodecException;) in Lcom/google/android/exoplayer2/mediacodec/MediaCodecRenderer$DecoderInitializationException;

09-27 16:16:12.616  7757  8022 D dalvikvm: VFY: replacing opcode 0x20 at 0x0000

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer: Video codec error

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:   com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.TI.DUCATI1.VIDEO.DECODER, Format(1, null, null, video/avc, avc1.4D4029, -1, null, [1920, 1080, 29.970032], [-1, -1])

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1030)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:877)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at android.os.Handler.dispatchMessage(Handler.java:98)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at android.os.Looper.loop(Looper.java:145)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at android.os.HandlerThread.run(HandlerThread.java:61)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:   Caused by: java.lang.IllegalStateException: start failed

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at android.media.MediaCodec.start(Native Method)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:58)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:110)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)

09-27 16:16:12.624  7757  8022 E MediaCodecVideoRenderer:       ... 10 more

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal: Playback error

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4029, -1, null, [1920, 1080, 29.970032], [-1, -1]), format_supported=YES

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:98)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:145)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:61)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.TI.DUCATI1.VIDEO.DECODER, Format(1, null, null, video/avc, avc1.4D4029, -1, null, [1920, 1080, 29.970032], [-1, -1])

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1030)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:877)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       ... 3 more

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:   Caused by: java.lang.IllegalStateException: start failed

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at android.media.MediaCodec.start(Native Method)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:58)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:110)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)

09-27 16:16:12.632  7757  8022 E ExoPlayerImplInternal:       ... 10 more

```

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
According the logs you provided, the MediaCodec on the device should support the media format you are trying to play (`format_supported=YES`). If codec initialization still fails, then this is a device-specific issue you'd need to report to Amazon.

**Comment by alekssunsss** [comment]
I`m sorry for additional question, but the same video plays well on the same device (Kindle Fire HD (3rd Generation) using another players (Prime photos and TotalCmd (Queue)). But when we try to play video using ExoPlayer sometimes we get error (Failed to initialize decoder: OMX.TI.DUCATI1.VIDEO.DECODER) or sometimes the video starts to play but FPS is very low (one frame per one second or maybe lower). 
The same issue reproduces using test application ExoPlayer demo app
Can you comment this addition information? Can we do something about it?
