### ISSUE TITLE
Unable to play HDPVR H264 encoded TS files from SageTV

### ISSUE THREAD

**Issue by stuckless** [google/ExoPlayer#1068]
I'm currently writing an AndroidTV app for SageTV and I started off using IJKPlayer, but I wanted to give ExoPlayer a try as well, since there are other advantages to ExoPlayer, in that I I can write my DataSource implementation which will be a requirement when communicating with SageTV.

To start, I pulled in the DemoPlayer and supporting files (ExtractorRenderBuilder, and EventLogger, etc).   To test, I'm serving up some files over HTTP using a python server that does support range requests.

When I play a .ts file, I get the following from the EventLogger
```
12-16 08:43:33.285 23623-23623/sagex.miniclient.android D/EventLogger: state [493,666.88, false, P]
12-16 08:43:33.344 23623-23623/sagex.miniclient.android D/EventLogger: state [493,666.94, true, P]
12-16 08:43:49.285 23623-23623/sagex.miniclient.android E/EventLogger: playerFailed [493,682.88]
                                                                       com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                                                                           at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
                                                                           at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                           at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                        Caused by: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                                                                           at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                           at java.lang.Thread.run(Thread.java:818)
                                                                        Caused by: java.lang.IllegalArgumentException
                                                                           at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                                                                           at com.google.android.exoplayer.util.ParsableByteArray.setPosition(ParsableByteArray.java:116)
                                                                           at com.google.android.exoplayer.util.ParsableByteArray.skipBytes(ParsableByteArray.java:127)
                                                                           at com.google.android.exoplayer.extractor.ts.TsExtractor$PmtReader.consume(TsExtractor.java:295)
                                                                           at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:153)
                                                                           at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:753)
                                                                           at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                           at java.lang.Thread.run(Thread.java:818) 
12-16 08:43:49.285 23623-23623/sagex.miniclient.android D/EventLogger: state [493,682.88, true, I]
12-16 08:45:16.783 23623-24919/sagex.miniclient.android D/EventLogger: state [493,770.41, false, I]
```

When I setup the player, I'm basically using my own activity and the player initialization is copied, pretty close from the sample you provide.

```
        ExtractorRendererBuilder rendererBuilder = new ExtractorRendererBuilder(context, "sagetv", Uri.parse("http://192.168.1.176:8000/TheBigBangTheory-TheFortificationImplementation-13289053-0.ts"));
        player = new DemoPlayer(rendererBuilder);
        EventLogger eventLogger = new EventLogger();
        player.setInternalErrorListener(eventLogger);
        player.setInfoListener(eventLogger);
        player.addListener(eventLogger);

        player.setBackgrounded(false);
        player.seekTo(0);
        player.prepare();

        // start playing
        player.setSurface(mSurface.getHolder().getSurface());
        player.setPlayWhenReady(true);
```

When I play a .mp4 file from that http server, I don't get any errors no the log, but also don'e get any audio or video.  Same for .mkv files.  

All the files play if I use VLC or ffplay from the command line and access the same urls.

I know the player works, because if I feed it the following URL, it will play
http://techslides.com/demos/sample-videos/small.mp4

There is almost no logging, so I have no idea what the player is doing.  I'm trying to figure out how I go about troubleshooting this.  For example, in the cases of mkv and mp4 files, I have no idea if it's actually reading the file, what codec it thinks it needs, etc.  The EventLogger basically logs almost nothing except for a couple of "state" events.

Thanks

**Comment by ojw28** [comment]
You'll need to provide links to the media that doesn't work, as opposed to the media that does work ;).

**Comment by stuckless** [comment]
How would you suggest I do that... My SageTV server is not a public server, but I'd be happy to share the files, there is a way that you can accept them :)

**Comment by stuckless** [comment]
Also, am I missing something with the logging?  Does the player have log setting that can be enabled to figure out what it's doing?

**Comment by stuckless** [comment]
Hopefully this is acceptable, but I've taken the first 10mb of the .ts file (equates to be about 5 seconds of video).

[sample.zip](https://github.com/google/ExoPlayer/files/64071/sample.zip)

**Comment by ojw28** [comment]
It appears the stream is invalid (it contains an invalid `program_info_length` in one of the program map tables defined in stream, which is many times longer than the whole program map section).

The mkv and/or mp4 issues will be different (although likely related to the media rather than the player). We'd need separate samples for those to diagnose the issues.

**Comment by stuckless** [comment]
for the .ts file, it plays in SageTV today (HD300 and desktop clients).  It also plays using mplayer, vlc, and ffplay, and it plays on my android devices using ijkplayer.  I get that the HDPVR is obviously producing an invalid stream, but, is there way to work around this, especially given that all these other players appear to do so.

As for the mp4/mkv files.  Is MKV supported (I thought I saw that mkv was not)?  Unfortunately I can't really share these files, since they are  large (and you'd need the entire file), and they are actual TV shows, which can't be shared.  That makes things tricky... which is why I've asked is there some way that I troubleshoot what is happening at a lower level (ie, enable some logging, etc).

Like, the ts files, these mkv and mp4 files also play in the android IJKPlayer (ffplay based)... so my guess is that while these files are not perfect, they are real world files that do play in other players.... I just need to figure out what I need to do to make the ExoPlayer read and play them.  I'm willing to do the leg work and troubleshoot... if i can figure out how to get some amount of logging out of the player, or, if you can intstruct me on how I might go about troubleshooting this.  I'm an app developer, but not a video developer, so I'm struggling here :)

Thanks,

**Comment by ojw28** [comment]
There is no exhaustive logging you can enable. MKV is supported, but there's a difference between the container (MKV) and the underlying streams that they contain (e.g. H264+AAC). It's most likely the case that the MP4/MKV files you're using contain audio streams for which Android does not provide decoders. If you're using Linux, you can get the details of the underlying streams using:

```
mediainfo your_file
```

on the command line. I think VLC also exposes information about the underlying streams in a menu somewhere. Could you dig that information out, and post it here? Thanks!

**Comment by stuckless** [comment]
Here's the MP4

```
General
Complete name                            : sample.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42
File size                                : 276 MiB
Duration                                 : 42mn 43s
Overall bit rate mode                    : Variable
Overall bit rate                         : 904 Kbps
Writing application                      : HandBrake rev0 2014050299

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 42mn 43s
Bit rate                                 : 810 Kbps
Width                                    : 720 pixels
Height                                   : 400 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 23.976 fps
Minimum frame rate                       : 23.974 fps
Maximum frame rate                       : 23.981 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.117
Stream size                              : 245 MiB (89%)
Writing library                          : x264 core 142 r2409 d6b4e63
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=abr / mbtree=1 / bitrate=810 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 42mn 43s
Bit rate mode                            : Variable
Bit rate                                 : 96.0 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 29.4 MiB (11%)
```

Here's the MKV

```
General
Unique ID                                : 49288362216249173148415993983295036954 (0x251497E08E6C7EE91563C7FAF3F01E1A)
Complete name                            : sample.mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 3.38 GiB
Duration                                 : 1h 4mn
Overall bit rate                         : 7 448 Kbps
Encoded date                             : UTC 2015-10-12 03:15:16
Writing application                      : mkvmerge v7.0.0 ('Where We Going') 64bit built on Jun 22 2014 08:19:39
Writing library                          : libebml v1.3.0 + libmatroska v1.4.1

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 5 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 1h 4mn
Bit rate                                 : 6 916 Kbps
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.313
Stream size                              : 3.14 GiB (93%)
Writing library                          : x264 core 148 r2597 e86f3a1
Encoding settings                        : cabac=1 / ref=5 / deblock=1:0:0 / analyse=0x3:0x113 / me=umh / subme=8 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=22 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=crf / mbtree=1 / crf=18.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 1h 4mn
Bit rate mode                            : Constant
Bit rate                                 : 384 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 178 MiB (5%)
Default                                  : Yes
Forced                                   : No
```

**Comment by ojw28** [comment]
- For the MKV sample, Android does not support AC-3 (see [here](http://developer.android.com/guide/appendix/media-formats.html) for a list of supported formats), which is why you don't hear any audio. Some AndroidTV devices do provide support, and on such devices you will get audio. We have a longer term plan to explicitly expose tracks that are not supported through the player, to indicate to the application that we know they're there but that we can't play them.
- I think the MP4 should play with both audio and video. Is there an issue with that sample, or not? Please test on the latest release or with the dev branch, since we fixed some issues relatively recently.

**Comment by stuckless** [comment]
In my testing, so far, none of these 3 files will play (ts,mp4,mkv)... but since the mp4 should play, I'll verify that the file is being served up correctly, etc.  I'll copy it to the device instead of playing it over http just to rule out the server is not sending it correctly.

For the TS file.. is there anything that I can do in the TS parser work around the issue?  Or is this happening at a much lower level?

**Comment by stuckless** [comment]
FYI... the mp4 copied to the device does play, so that's good news.  I just need to figure out why the HTTP stream for the same file doesn't play.  Likely the MKV (less the audio) would play as well.

So, really, it's just the TS file that I'd really like to figure out how to work around.

Thanks

**Comment by ojw28** [comment]
You can add the following code block immediately above the point in `TsExtractor.PmtReader.consume` to avoid the failure:

```
if (programInfoLength > sectionData.bytesLeft()) {
  Log.w(TAG, "Invalid programInfoLength: " + programInfoLength);
  return;
}
```

**Comment by stuckless** [comment]
Great news!  That fixed my issue, the TS file are now playing.  So, knowing this is sort of a hack to work around bad data in the TS stream... is this something that you going to add into the ExoPlayer, or, should I keep my own fork with this change?

Thanks again for the help.

**Comment by ojw28** [comment]
We wont be adding the workaround unless we see many (important) streams with the issue. See my rant near the bottom of https://github.com/google/ExoPlayer/pull/1064 for an explanation about why. Closing this issue, since it sounds like you're able to move forward at this point. Thanks!

**Comment by stuckless** [comment]
np... I'll maintain a separate fork with this change.  Thanks again for your help.

**Comment by ojw28** [comment]
@stuckless My mistake. The TS file is actually valid in this case. The reason for the playback failure is the one reported in issue #1001. In this case, we're treating a PID with value 0x1F as a PMT, which according to that issue is incorrect. That would imply the fix I suggested isn't really the correct one. Please follow #1001 to track delivery of a proper fix.

**Comment by ojw28** [comment]
The TS issue is fixed by the change ref'd above.

**Comment by stuckless** [comment]
Thanks!  One less thing for me to maintain in my application ;)
