### ISSUE TITLE
Ffmpeg extention thorws error on running in my app

### ISSUE THREAD

**Issue by ThreeMinutesFix** [google/ExoPlayer#10680]
I have build my arr file for FFMPEG extention support to support 5.1 audio on my app.
I use windows poweshell to generate  ffmepg files 
but when i run the app it thows some error

Error Logs

```
Superclass com.google.android.exoplayer2.util.LibraryLoader of com.google.android.exoplayer2.ext.ffmpeg.FfmpegLibrary$1 is declared final (declaration of 'com.google.android.exoplayer2.ext.ffmpeg.FfmpegLibrary$1' appears in /data/app/com.gospel.youtubedemo-fUObS54QMnrXEW3c9ybg4Q==/base.apk!classes4.dex)
        at com.google.android.exoplayer2.ext.ffmpeg.FfmpegLibrary.isAvailable(FfmpegLibrary.java:61)
        at com.google.android.exoplayer2.ext.ffmpeg.FfmpegAudioRenderer.supportsFormatInternal(FfmpegAudioRenderer.java:93)
        at com.google.android.exoplayer2.audio.DecoderAudioRenderer.supportsFormat(DecoderAudioRenderer.java:218)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:485)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:355)
        at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:238)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:186)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2202)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:501)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:225)
        at android.os.HandlerThread.run(HandlerThread.java:67)

```

my player initilization code:

```
` void initializePlayer(MediaSource mediaSource) {
        ExoTrackSelection.Factory videoTrackSelectionFactory = new
                AdaptiveTrackSelection.Factory();
        trackSelector = new
                DefaultTrackSelector(Player.this, videoTrackSelectionFactory);
        DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(this);
        renderersFactory.setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER);
        simpleExoPlayer = new SimpleExoPlayer.Builder(this, renderersFactory)
                .setTrackSelector(trackSelector)
                .setSeekForwardIncrementMs(10000)
                .setSeekBackIncrementMs(10000)
                .build();
        playerView.setPlayer(simpleExoPlayer);
        playerView.setKeepScreenOn(true);'
```

extention integration as arr file :    `implementation files('libs/extentions.aar')`
Thankyou

**Comment by tonihei** [comment]
> Superclass com.google.android.exoplayer2.util.LibraryLoader of com.google.android.exoplayer2.ext.ffmpeg.FfmpegLibrary$1 is declared final

That doesn't seem to make sense because `LibraryLoader` is (and never was) final. It's an abstract class in fact. 

Could it be that something in your build environment is going wrong? I'd suggest cleaning everything (caches in Android Studio, output files etc) and then rebuilding from scratch to see if it helps. If you think something is wrong in the library, please try to describe the reproduction steps in detail. We also don't have a Windows environment for testing, so we may not be able to help you with this part in case it's related.

**Comment by ThreeMinutesFix** [comment]
ok i am currently installing Linux ubuntu(virtual machine)   for this purpose. i want more info like i need to install android studio and gits etc in my vmachine ubuntu?

**Comment by ThreeMinutesFix** [comment]
> > Superclass com.google.android.exoplayer2.util.LibraryLoader of com.google.android.exoplayer2.ext.ffmpeg.FfmpegLibrary$1 is declared final
> 
> That doesn't seem to make sense because `LibraryLoader` is (and never was) final. It's an abstract class in fact.
> 
> Could it be that something in your build environment is going wrong? I'd suggest cleaning everything (caches in Android Studio, output files etc) and then rebuilding from scratch to see if it helps. If you think something is wrong in the library, please try to describe the reproduction steps in detail. We also don't have a Windows environment for testing, so we may not be able to help you with this part in case it's related.

yes i try this also in mean time of linux downloading.  i following this guide  [guide1](https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/README.md)
[guide2](https://captaindroid.com/how-to-integrate-exoplayer-ffmpeg-extension/)
