### ISSUE TITLE
Playback corrupted after midrolls (Device specific)

### ISSUE THREAD

**Issue by fpitters** [google/ExoPlayer#10699]
We have a device, LGE STB with Android 9, that fails to continue playing protected content after a midroll.
The decoder seems to enter a corrupted state when content is resumed. 
See the attached video:
https://user-images.githubusercontent.com/1129222/196462328-82d4d036-ca16-456d-a53e-7eda0ed8e9b6.mp4

We only reproduce this when using some particular profile/levels, so it wasn't reproducible with the Dash/Widevine samples included on Exoplayer Demo, but the following playlist seems to reproduce it consistently:
```
  {
    "name": "Allente issue",
    "samples": [
      {
        "name": "Ads use case: Widevine -> Clear -> Widevine",
        "playlist": [
          {
            "name": "Network sample",
            "drm_scheme": "widevine",
            "uri": "https://amssamples.streaming.mediaservices.windows.net/622b189f-ec39-43f2-93a2-201ac4e31ce1/BigBuckBunny.ism/manifest(format=mpd-time-csf)",
            "clip_end_position_ms": 8000
          },
          {
            "uri": "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8",
            "clip_end_position_ms": 3000
          },
          {
            "name": "Network sample",
            "drm_scheme": "widevine",
            "uri": "https://amssamples.streaming.mediaservices.windows.net/622b189f-ec39-43f2-93a2-201ac4e31ce1/BigBuckBunny.ism/manifest(format=mpd-time-csf)",
            "clip_end_position_ms": 30000
          }
        ]
      }
    ]
  },
```
On the logs we see:
```
10-18 11:51:00.448  1046  2946  9259 W SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x0005
10-18 11:51:00.448  1046  2946  9259 W SoftAAC2: AAC decoder returned error 0x0005, substituting silence

10-18 11:51:00.465 10039  8570  9201 E MediaCodecAudioRenderer: Audio sink error
10-18 11:51:00.465 10039  8570  9201 E MediaCodecAudioRenderer:   com.google.android.exoplayer2.audio.AudioSink$UnexpectedDiscontinuityException: Unexpected audio track timestamp discontinuity: expected 1000015852970, got 1000015342132
10-18 11:51:00.465 10039  8570  9201 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:998)
10-18 11:51:00.465 10039  8570  9201 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:703)
10-18 11:51:00.465 10039  8570  9201 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1894)
10-18 11:51:00.465 10039  8570  9201 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
10-18 11:51:00.465 10039  8570  9201 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
10-18 11:51:00.465 10039  8570  9201 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
10-18 11:51:00.465 10039  8570  9201 E MediaCodecAudioRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
10-18 11:51:00.465 10039  8570  9201 E MediaCodecAudioRenderer:       at android.os.Looper.loop(Looper.java:193)
10-18 11:51:00.465 10039  8570  9201 E MediaCodecAudioRenderer:       at android.os.HandlerThread.run(HandlerThread.java:65)
```
but our guess is that it's a consequence on the video decoder being broken.

We have tried playing with the flags in `DefaultMediaCodecAdapterFactory` (`forceEnableAsynchronous` and `experimentalSetSynchronizeCodecInteractionsWithQueueingEnabled`) and all the `MediaCodecRenderer` workarounds,just in case something rings :)
The only workaround we have found is using the Google decoder for the clear content (the ad) but it performs badly.

We understand this is a device specific issue and we are reaching the manufacturer with the information we got, but we are wondering:
- Have we missed any similar issue with a similar use case from this tracker?
- Any alternative workaround or attempts you think we could try?

Thank you for your time

**Comment by christosts** [comment]
@icbaker do you think this falls into any of our existing cases transitioning between secure and non-secure decoders?

**Comment by icbaker** [comment]
@fpitters What happens if you use `drm_session_for_clear_content` in your clear sample?

Concretely (note you also need to specify a DRM scheme):

```
{
    "name": "Allente issue",
    "samples": [
      {
        "name": "Ads use case: Widevine -> Clear -> Widevine",
        "playlist": [
          {
            "name": "Network sample",
            "drm_scheme": "widevine",
            "uri": "https://amssamples.streaming.mediaservices.windows.net/622b189f-ec39-43f2-93a2-201ac4e31ce1/BigBuckBunny.ism/manifest(format=mpd-time-csf)",
            "clip_end_position_ms": 8000
          },
          {
            "uri": "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8",
            "drm_scheme": "widevine",
            "drm_session_for_clear_content": true,
            "clip_end_position_ms": 3000
          },
          {
            "name": "Network sample",
            "drm_scheme": "widevine",
            "uri": "https://amssamples.streaming.mediaservices.windows.net/622b189f-ec39-43f2-93a2-201ac4e31ce1/BigBuckBunny.ism/manifest(format=mpd-time-csf)",
            "clip_end_position_ms": 30000
          }
        ]
      }
    ]
  },
```

**Comment by fpitters** [comment]
And yes! 
That solves the issue with the playlist and discovers a bug on my code on which `DefaultDrmSessionManager.setUseDrmSessionsForClearContent` wasn't being applied :disappointed: 
Sorry I've missed it and thank you very much for the help!
