### ISSUE TITLE
Chromecast with Google TV update to Android 12, play 4k 60fps get format_supported=NO_EXCEEDS_CAPABILITIES

### ISSUE THREAD

**Issue by how8570** [google/ExoPlayer#10708]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Device: Chromecast with Google TV (4k ver)
Android version: 12

probably relevant system info:
![image](https://user-images.githubusercontent.com/16633155/196842167-0ed4595d-508f-4fba-893f-894c7b9848b2.png)

### Devices that do not reproduce the issue

NVIDIA SHIELD
Chromecast with Google TV on Android 10

### Reproducible in the demo app?

Yes

### Reproduction steps

1. build demo app to the Android 12 CCwGTV(Chromecast with Google TV)
2.  just play video in demo app
    - 60fps DASH 
      - 4K (MP4, H264, Clear)

### Expected result

The media play  successfully.

### Actual result

Got this kind result

```
11:12:03.330  E  Playback error
                   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640033, 19375046, null, [3840, 2160, 60.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
                       at android.os.Handler.dispatchMessage(Handler.java:102)
                       at android.os.Looper.loopOnce(Looper.java:201)
                       at android.os.Looper.loop(Looper.java:288)
                       at android.os.HandlerThread.run(HandlerThread.java:67)
                   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.amlogic.avc.decoder.awesome2
                       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1590)
                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                       at android.os.Looper.loopOnce(Looper.java:201) 
                       at android.os.Looper.loop(Looper.java:288) 
                       at android.os.HandlerThread.run(HandlerThread.java:67) 
                   Caused by: android.media.MediaCodec$CodecException: Error 0x80001000
11:12:03.335  E  Disable failed.
                   java.lang.IllegalStateException
                       at android.media.MediaCodec.native_flush(Native Method)
                       at android.media.MediaCodec.flush(MediaCodec.java:2350)
                       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.flush(AsynchronousMediaCodecAdapter.java:228)
                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:877)
                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:870)
                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:710)
                       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:561)
                       at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:186)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1651)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1392)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1355)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:582)
                       at android.os.Handler.dispatchMessage(Handler.java:102)
                       at android.os.Looper.loopOnce(Looper.java:201)
                       at android.os.Looper.loop(Looper.java:288)
                       at android.os.HandlerThread.run(HandlerThread.java:67)
11:12:03.346  E  playerFailed [eventTime=0.75, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_DECODING_FAILED
                   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640033, 19375046, null, [3840, 2160, 60.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
                       at android.os.Handler.dispatchMessage(Handler.java:102)
                       at android.os.Looper.loopOnce(Looper.java:201)
                       at android.os.Looper.loop(Looper.java:288)
                       at android.os.HandlerThread.run(HandlerThread.java:67)
                   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.amlogic.avc.decoder.awesome2
                       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1590)
                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                       at android.os.Looper.loopOnce(Looper.java:201) 
                       at android.os.Looper.loop(Looper.java:288) 
                       at android.os.HandlerThread.run(HandlerThread.java:67) 
                   Caused by: android.media.MediaCodec$CodecException: Error 0x80001000
                 ]

```

### Media

demo app media
```
      {
        "name": "4K (MP4, H264, Clear)",
        "uri": "https://storage.googleapis.com/exoplayer-test-media-1/60fps/bbb-clear-2160/manifest.mpd"
      }
```

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

----
## Other Notes : 

I am taking `androidx.media3:media3-exoplayer:1.0.0-beta02`, it seem probiliy same as ExoPlayer 2.18.1 [got this info from here](https://developer.android.com/jetpack/androidx/releases/media3#1.0.0-beta02). 

I also tried pure ExoPlayer demo app and leave the error code here.
Playing on Android 10 is fine.
After update to Android 12, 4k capabilities lose, it quite wired?? 🤔

I guess it might the chromecast's update issue.
I also facing another bug is on CCwGTV Android 10, when i calling `exoPlayer.release()`, it seems that codec not really do the native codec release by OS, witch may cause oom crash.
If is, please let me know that, I can contact them in need.

**Comment by christosts** [comment]
I'm testing the content (H264, 4K, 60fps) on the same device on Android 10 (build `QTS1.220504.008.8726984`) and the video format is reported to exceed the device capabilities too.

> [X] Track:0, id=1, mimeType=video/avc, bitrate=19375046, codecs=avc1.640033, res=3840x2160, fps=60.0, supported=NO_EXCEEDS_CAPABILITIES

Video playback starts, there are many dropped frames, but no error [1]. The device cannot decode 4K at 60fps.

I upgraded the device to Android 12 and I can see the error. The codec still reports that H264 4K@60fps is beyond its capablities. The difference is that instead of choppy playback, the codec raises the error.

I'll forward this to the Chromecast team - thanks for reporting. 

[1] Note that in Android 10, the player is still communicating with MediaCodec in synchronous mode. Enabling [asynchronous queueing](https://exoplayer.dev/customization.html#enabling-asynchronous-buffer-queueing) does not improve much because the device cannot decode fast enough anyway.

**Comment by christosts** [comment]
[internal ref 254670010]

**Comment by how8570** [comment]
Dose there any update? (*´･д･)?

I understand that hardware issue probably hard to be fix.
I am curious about that will be fix or not? Or maybe a due date that can represent this issue won't be fix?

thx <(_ _)>

**Comment by christosts** [comment]
There is no update yet, and I will update this issue once we get one from the Chromecast team. 

For clarity, even before the upgrade to Android 12, the device did not report it could play 4K@60fps and playback was stuttering. Regardless of a potential fix, I think that your app should avoid playing such streams anyway, it you want to ensure smooth playback (my hypothesis is that even if there is a fix on the device, the fix would not make the device faster but at best bring the old behavior back)

**Comment by christosts** [comment]
I'm sharing an update from the Chromecast team: the decoder does fail, however this is in line with the spec since the stream is exceeding the decoder capabilities. 

On the player side, ExoPlayer knows that playing this stream might cause errors (see documentation of [FORMAT_EXCEEDS_CAPABILITIES](https://github.com/google/ExoPlayer/blob/ab4d37f499ba49bb3cac7938eb03ebf7133ccfe6/library/common/src/main/java/com/google/android/exoplayer2/C.java#L1309-L1319)) but goes ahead anyway in a best-effort manner since there are no other video tracks to choose. For example, if the file had another video track that was within the decoder capabilities, ExoPlayer would pick the other track.

You may be able to override the codec configuration and make playback work but still stuttering by customising `MediaCodecVideoRenderer` on your app. I can share more details if you want to go that path. However, my advice is that you should **not** play streams that exceed the decoder capabilities. Note that playback of AVC 4k@60fps was stuttering already on Android 10.

**Comment by how8570** [comment]
hum...? I am little confuse about this. 🤔 

So on the player side, player know that both version (Android 10, 12) of Chromecast are exceed the decoder capabilities.
But on the 12, device strongly refuse to decode media witch cause video won't be play?

---

> You may be able to override the codec configuration and make playback work but still stuttering by customising MediaCodecVideoRenderer on your app.

I am not sure how much effort to workaround this, i need take some time to survey this.
If necessary, I will contact again, THX

Thanks the infomation, I will take a look [FORMAT_EXCEEDS_CAPABILITIES](https://github.com/google/ExoPlayer/blob/ab4d37f499ba49bb3cac7938eb03ebf7133ccfe6/library/common/src/main/java/com/google/android/exoplayer2/C.java#L1309-L1319) and relevant source code.
