### ISSUE TITLE
Widevine DRM Dash Stream Key Rotation Play Error

### ISSUE THREAD

**Issue by leventyayla** [google/ExoPlayer#10724]
We use Widevine DRM with Dash streams and recently we enabled Key Rotation but i have tested these streams with exoplayer it gives me following error:

> playerFailed [eventTime=0.75, mediaPos=86383.99, window=0, period=0
                                                                                                      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4d401e, 1400000, null, [704, 396, 25.0], [-1, -1]), format_supported=YES
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                                          at android.os.Looper.loop(Looper.java:213)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: android.media.MediaCodec$CryptoException: Crypto key not available
                                                                                                          at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                                          at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2699)
                                                                                                          at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:75)
                                                                                                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1416)
                                                                                                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:859)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:103) 
                                                                                                          at android.os.Looper.loop(Looper.java:213) 
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67) 
                                                                                                    ]

We are creting DefaultDrmSessionManager like this:
`
DefaultDrmSessionManager.Builder()
                    .setUuidAndExoMediaDrmProvider(DRM_SCHEME, ExoMediaDrm.AppManagedProvider(mediaDrm!!))
                    .setKeyRequestParameters(null)
                    .setMultiSession(true)
                    .build(drmCallback)
`

ExoPlayer Version: 2.12.2

If we restart the stream on CDN side exoplayer plays content but when content key changed player gives this error. Could you help me about this situation?

**Comment by yoluquitas** [comment]
Hi, is there any update? 
I would like to know if Widevine Key rotation is supported by Exo Player.

Thanks in advance!

**Comment by icbaker** [comment]
Key rotation is supported: https://developer.android.com/guide/topics/media/exoplayer/drm#key_rotation

In order to help with your specific problem please send an `adb bugreport` taken after reproducing the problem to dev.exoplayer@gmail.com using the subject `Issue #10724`. Please also update this issue to indicate you’ve done this.

**Comment by yoluquitas** [comment]
> Key rotation is supported: https://developer.android.com/guide/topics/media/exoplayer/drm#key_rotation
> 
> In order to help with your specific problem please send an `adb bugreport` taken after reproducing the problem to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using the subject `Issue #10724`. Please also update this issue to indicate you’ve done this.

@icbaker thank you very much for your soon answer. There is not actual bug at this moment, my question was in order to confirm if key rotation is currently supported for Widevine.  

Regards!
