### ISSUE TITLE
AbstractMethodError crash and enableDexingArtifactTransform removal in AGP 8.0

### ISSUE THREAD

**Issue by wbonnefond** [google/ExoPlayer#10741]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

All devices

### Reproducible in the demo app?

Not tested

### Reproduction steps

Application fails with the following error:
```
13:33:05.588 Andr...ime  E  FATAL EXCEPTION: main
                            Process: com.onepeloton.callisto.dev, PID: 26905
                            java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.analytics.AnalyticsListener.onEvents(com.google.android.exoplayer2.Player, com.google.android.exoplayer2.analytics.AnalyticsListener$Events)"
                            	at com.google.android.exoplayer2.analytics.DefaultAnalyticsCollector.lambda$setPlayer$1$com-google-android-exoplayer2-analytics-DefaultAnalyticsCollector(DefaultAnalyticsCollector.java:120)
                            	at com.google.android.exoplayer2.analytics.DefaultAnalyticsCollector$$ExternalSyntheticLambda19.invoke(Unknown Source:6)
                            	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet.java:292)
                            	at com.google.android.exoplayer2.util.ListenerSet.handleMessage(ListenerSet.java:244)
                            	at com.google.android.exoplayer2.util.ListenerSet.$r8$lambda$eEvjP-IE0x3J2lRvKfFbbjRFRvc(Unknown Source:0)
                            	at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda0.handleMessage(Unknown Source:2)
                            	at android.os.Handler.dispatchMessage(Handler.java:102)
                            	at android.os.Looper.loopOnce(Looper.java:226)
                            	at android.os.Looper.loop(Looper.java:313)
                            	at android.app.ActivityThread.main(ActivityThread.java:8663)
                            	at java.lang.reflect.Method.invoke(Native Method)
                            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
                            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

The solution from other closed issues(#8254, #8224, #7927, #7349) is to use `android.enableDexingArtifactTransform=false` but this will be removed in the next major version of AGP. 

**Please advise a fix that does not require this flag.**

```
WARNING:The option setting 'android.enableDexingArtifactTransform=false' is deprecated.
The current default is 'true'.
It will be removed in version 8.0 of the Android Gradle plugin.
```

### Expected result

App does not crash

### Actual result

App crashes

### Media

N/A

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by michalvimn** [comment]
@marcbaechinger Any updates on this issue? With the AGP 8.0 being released now it's becoming a huge issue for us.

**Comment by icbaker** [comment]
To repeat what has been said in all the issues you linked: This is an issue with the way you build your app, not the ExoPlayer library. This is happening because desugaring + jetification is not operating correctly on the ExoPlayer code when **you** compile in order to make `default` methods work on older versions of Android.

> Any updates on this issue? With the AGP 8.0 being released now it's becoming a huge issue for us.

This flag has not been removed in AGP 8.0, we are using 8.0.1 in this project and I just added `android.enableDexingArtifactTransform=false` to our `gradle.properties` file as a test and it still works.

It sounds like the removal has been punted while a blocking issue related to `compileOnly` dependencies is resolved: https://issuetracker.google.com/225900051#comment5

It's not clear to me if you're encountering this issue due to `compileOnly` dependencies or for another reason. There's also a mention that it can cause problem with file dependencies in Gradle (https://issuetracker.google.com/225900051#comment1). The linked Gradle ticket has been closed without being fixed because they're apparently moving away from file dependencies.

I'm going to close this because a) the flag still exists and b) this is an issue with your build process, not ExoPlayer. If you need further support I suggest you ask the Android Gradle Plugin folks.
