### ISSUE TITLE
Error when to play mp4

### ISSUE THREAD

**Issue by qqli007** [google/ExoPlayer#1075]
Hello,I met a problem when to play one mp4 file.

the file path:
http://7xi8k7.com1.z0.glb.clouddn.com/125559181215fba916b92610.mp4

I play it on Mi note Android 4.4.4, the exoplayer version is 1.5.1, it still has error on 1.5.3

The error msg:
```
12-18 13:41:53.347 14732-26282/com.xunlei.fileexplorer E/LoadTask: Unexpected exception loading stream
                                                                   java.lang.IllegalStateException: Top bit not zero: -72
                                                                       at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:240)
                                                                       at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:196)
                                                                       at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:259)
                                                                       at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:229)
                                                                       at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:117)
                                                                       at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:745)
                                                                       at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:841)
```

Have any idea about it?

**Comment by andrewlewis** [comment]
The timestamp information in the stream's video track seems to be incorrect: the last sample_delta in the stts box has the value 0xFFFFFFB8, which would imply an incorrect (too large) duration for the final sample. Although the ISOBMFF specification technically permits the value, ExoPlayer throws an exception as it can't be represented using a positive 32-bit signed integer.

**Comment by ojw28** [comment]
Closing as a media error.
