### ISSUE TITLE
FFMpeg error with some flac files

### ISSUE THREAD

**Issue by Tolriq** [google/ExoPlayer#10760]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

All

### Devices that do not reproduce the issue

None

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play the file send by mail with the ffmpeg extension enabled.
Skip or wait until near the end of the file and see an error.

### Expected result

No error (And no error with default Android mediacodec)

### Actual result

```
ExoPlayerImplInternal - Playback error
                                                                               com.google.android.exoplayer2.ExoPlaybackException: FfmpegAudioRenderer error, index=0, format=Format(null, null, null, audio/flac, null, -1, null, [-1, -1, -1.0], [2, 48000]), format_supported=YES
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loopOnce(Looper.java:201)
                                                                                   at android.os.Looper.loop(Looper.java:288)
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                               Caused by: com.google.android.exoplayer2.ext.ffmpeg.FfmpegDecoderException: Unexpected decode error
                                                                                   at com.google.android.exoplayer2.ext.ffmpeg.FfmpegAudioDecoder.createUnexpectedDecodeException(FfmpegAudioDecoder.java:95)
                                                                                   at com.google.android.exoplayer2.ext.ffmpeg.FfmpegAudioDecoder.createUnexpectedDecodeException(FfmpegAudioDecoder.java:32)
                                                                                   at com.google.android.exoplayer2.decoder.SimpleDecoder.decode(SimpleDecoder.java:245)
                                                                                   at com.google.android.exoplayer2.decoder.SimpleDecoder.run(SimpleDecoder.java:202)
                                                                                   at com.google.android.exoplayer2.decoder.SimpleDecoder.access$000(SimpleDecoder.java:29)
                                                                                   at com.google.android.exoplayer2.decoder.SimpleDecoder$1.run(SimpleDecoder.java:73)
                                                                               Caused by: java.lang.IllegalArgumentException
                                                                                   at java.nio.Buffer.limit(Buffer.java:290)
                                                                                   at java.nio.ByteBuffer.limit(ByteBuffer.java:820)
                                                                                   at com.google.android.exoplayer2.ext.ffmpeg.FfmpegAudioDecoder.decode(FfmpegAudioDecoder.java:139)
                                                                                   at com.google.android.exoplayer2.ext.ffmpeg.FfmpegAudioDecoder.decode(FfmpegAudioDecoder.java:32)
                                                                                   at com.google.android.exoplayer2.decoder.SimpleDecoder.decode(SimpleDecoder.java:241)
                                                                                   at com.google.android.exoplayer2.decoder.SimpleDecoder.run(SimpleDecoder.java:202) 
                                                                                   at com.google.android.exoplayer2.decoder.SimpleDecoder.access$000(SimpleDecoder.java:29) 
                                                                                   at com.google.android.exoplayer2.decoder.SimpleDecoder$1.run(SimpleDecoder.java:73) 
```

### Media

Send by mail.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by Tolriq** [comment]
Doing some tests ffmpeg returns -1094995529 -> AVERROR_INVALIDDATA

If would be nice if the library detected those negative values and at least throw a better error message.

Now about the root issue, since those files does not give errors via other decoders would is make sense to handle invalid data at the end of the file and ignore it like some cases handled for mp3 ?

**Comment by Tolriq** [comment]
@rohitjoins I've checked again and it's actually already there : https://github.com/google/ExoPlayer/blob/dev-v2/extensions/ffmpeg/src/main/java/com/google/android/exoplayer2/ext/ffmpeg/FfmpegAudioDecoder.java#L114

The issue is at https://github.com/google/ExoPlayer/blob/dev-v2/extensions/ffmpeg/src/main/jni/ffmpeg_jni.cc#L286 the result is returned as raw ffmpeg value and not properly converted as https://github.com/google/ExoPlayer/blob/dev-v2/extensions/ffmpeg/src/main/jni/ffmpeg_jni.cc#L267

Edit: There's the same issue in other place in that decode function

**Comment by Tolriq** [comment]
Fix confirmed made a PR

https://github.com/google/ExoPlayer/pull/10762

**Comment by rohitjoins** [comment]
@Tolriq Thank you for sending the PR. I agree with the fix in the error message and will accept the PR soon. Overriding behaviour of ffmpeg to handle invalid data seems tricky and hard to maintain in the future. I believe we should mirror the ffmpeg extension when enabled.

**Comment by Tolriq** [comment]
@rohitjoins actually there's nothing more to do, the fix does return the proper code that is supported by the decoder and in the case of that file properly ignore the invalid data at the end of it.

So simple fix to greatly improve resilience of the ffmpeg extension.
