### ISSUE TITLE
Exoplayer can't play audio for HLS

### ISSUE THREAD

**Issue by himanshuthakkar2781** [google/ExoPlayer#10803]
ExoPlayer Version
2.18.1

Devices that reproduce the issue
All android devices

Devices that do not reproduce the issue
none

Reproducible in the demo app?
No
Downloaded file plays(as am using progressive media source).
But Hls file does not play.

Reproduction steps
After changing version to 2.18.1 from 2.11.3.
playing hls media source produces error below

E/LoadTask: Unexpected exception loading stream
      java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
        at com.google.android.exoplayer2.util.FileTypes.inferFileTypeFromResponseHeaders(FileTypes.java:126)
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.createExtractor(DefaultHlsExtractorFactory.java:106)
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.createExtractor(DefaultHlsExtractorFactory.java:48)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:513)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:468)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:437)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:394)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2022-11-21 19:38:07.455 6709-6968/com.gurumaa.amritvarsha E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:608)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:241)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:433)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
        at com.google.android.exoplayer2.util.FileTypes.inferFileTypeFromResponseHeaders(FileTypes.java:126)
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.createExtractor(DefaultHlsExtractorFactory.java:106)
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.createExtractor(DefaultHlsExtractorFactory.java:48)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:513)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:468)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:437)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:394)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

[AudioPlayerService.txt](https://github.com/google/ExoPlayer/files/10057555/AudioPlayerService.txt)
[streamdatasource.txt](https://github.com/google/ExoPlayer/files/10057567/streamdatasource.txt)

**Comment by tianyif** [comment]
Hi @himanshuthakkar2781,

In the attached implementation `StreamDataSource`, we noticed that you are returning a `null` object in method `getResponseHeaders()`, and when [`FileTypes`](https://github.com/google/ExoPlayer/blob/03569f9e6536e6c60cb585115d6d7352a4deab71/library/common/src/main/java/com/google/android/exoplayer2/util/FileTypes.java#L126) tries to access the value from a "null" map, the `NullPointerException` is thrown.

So you can fix your implementation to return a non-null map in `getResponseHeaders()`, or even simpler, you don't need to override that method since we have a [default implementation](https://github.com/google/ExoPlayer/blob/03569f9e6536e6c60cb585115d6d7352a4deab71/library/datasource/src/main/java/com/google/android/exoplayer2/upstream/DataSource.java#L92) which returns an empty map. What's more, you can extend the test class [`DataSourceContractTest`](https://github.com/google/ExoPlayer/blob/a9444c880230d2c2c79097e89259ce0b9f80b87d/testutils/src/main/java/com/google/android/exoplayer2/testutil/DataSourceContractTest.java) to test the compliance of your implementation.

Also, you can consider using [`ResolvingDataSource`](https://github.com/google/ExoPlayer/blob/a9444c880230d2c2c79097e89259ce0b9f80b87d/library/datasource/src/main/java/com/google/android/exoplayer2/upstream/ResolvingDataSource.java). You just need to implement the `Resolver`. It produces a resolved data spec which will be used in `upstreamDataSource`. This may help to simplify your implementation.

**Comment by himanshuthakkar2781** [comment]
Thanks a ton.....This has fixed my issue.
