### ISSUE TITLE
ArrayIndexOutOfBoundsException on AdPlaybackState.java

### ISSUE THREAD

**Issue by kaan-celen** [google/ExoPlayer#10817]
### ExoPlayer Version

2.16.0

### Devices that reproduce the issue

Samsung
Huawei
Motorola
Amazon
Lenovo
Oppo
Google
Xiaomi
Sony

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play a video with ads

### Expected result

App play ads

### Actual result

App close itself

### Media

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at com.google.android.exoplayer2.source.ads.AdPlaybackState.getAdGroup(AdPlaybackState.java:485)
       at com.google.android.exoplayer2.Timeline$Period.getAdGroupTimeUs(Timeline.java:728)
       at com.google.android.exoplayer2.analytics.PlaybackStatsListener.findBestEventTime(PlaybackStatsListener.java:322)
       at com.google.android.exoplayer2.analytics.PlaybackStatsListener.onEvents(PlaybackStatsListener.java:247)
       at com.google.android.exoplayer2.analytics.AnalyticsCollector.lambda$setPlayer$1$AnalyticsCollector(AnalyticsCollector.java:142)
       at com.google.android.exoplayer2.analytics.-$$Lambda$AnalyticsCollector$uX7qombvbhfllBfrArZ4fy72Fso.invoke(-.java:6)
       at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet.java:272)
       at com.google.android.exoplayer2.util.ListenerSet.handleMessage(ListenerSet.java:224)
       at com.google.android.exoplayer2.util.ListenerSet.handleMessage(ListenerSet.java)
       at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$gt28PMFfhLXGfIVY4v7eP9kmalg.handleMessage(-.java:2)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loopOnce(Looper.java:223)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:7942)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
Has someone observing this issue ever found a reliable way to reproduce? Just playing an ad with an attached `PlaybackStatsListener` doesn't cause this to happen automatically.

**Comment by tonihei** [comment]
I'll de-duplicate this one against the newer one in https://github.com/androidx/media/issues/743.
