### ISSUE TITLE
IMA extension: catch WebView exceptions

### ISSUE THREAD

**Issue by MBakhshi96** [google/ExoPlayer#10829]
### ExoPlayer Version

2.15.1

### Devices that reproduce the issue

All devices which does not have WebView or disabled it

### Reproducible in the demo app?

Yes

### Reproduction steps

Play samples with ads using ima extension

### Expected result

When WebView is not available, we expect player to skip the ads, since WebView is only needed for playing ads and not the actual video.

### Actual result

Playback crashed with the exception `android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed`

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by MBakhshi96** [comment]
It would be better to catch WebView related exceptions and prevent player from crashing. It was not possible to catch this exception when building MediaItem and adding adTagUri.

**Comment by marcbaechinger** [comment]
On what devices does this happen? I would guess that an Android device goes through CTS tests that verify that `WebView` is installed [1]. So it would be interesting to know the devices which do fail providing this. 

Given we test with Android devices that pass CTS, we probably can't easily repro. So a full stack trace would be helpful to understand better from where this is coming. I doubt we need to catch that but without a stack trace it seems difficult to make this issue actionable if we device to go down that route.

[1] https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/tools/cts_config/README.md?pli=1

**Comment by MBakhshi96** [comment]
This mostly happens on some Android box devices. I suspect they might not have gone through CTS tests. Also this can happen if the user has disabled WebView, so you can reproduce it by disabling WebView. I know that not too many users may try to disable WebView, but handling it gracefully can result in a better UX.

I'm also pasting the stack trace
```
android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
        at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:435)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
        at android.webkit.WebView.getFactory(WebView.java:2551)
        at android.webkit.WebView.ensureProviderCreated(WebView.java:2545)
        at android.webkit.WebView.setOverScrollMode(WebView.java:2613)
        at android.view.View.<init>(View.java:5060)
        at android.view.View.<init>(View.java:5201)
        at android.view.ViewGroup.<init>(ViewGroup.java:675)
        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
        at android.webkit.WebView.<init>(WebView.java:410)
        at android.webkit.WebView.<init>(WebView.java:353)
        at android.webkit.WebView.<init>(WebView.java:336)
        at android.webkit.WebView.<init>(WebView.java:323)
        at android.webkit.WebView.<init>(WebView.java:313)
        at com.google.ads.interactivemedia.v3.internal.ed.<init>(IMASDK:23)
        at com.google.ads.interactivemedia.v3.internal.cu.<init>(IMASDK:1)
        at com.google.ads.interactivemedia.v3.api.ImaSdkFactory.createAdsLoader(IMASDK:6)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader$DefaultImaFactory.createAdsLoader(ImaAdsLoader.java:756)
        at com.google.android.exoplayer2.ext.ima.AdTagLoader.requestAds(AdTagLoader.java:530)
        at com.google.android.exoplayer2.ext.ima.AdTagLoader.<init>(AdTagLoader.java:266)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.requestAds(ImaAdsLoader.java:451)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.start(ImaAdsLoader.java:539)
        at com.google.android.exoplayer2.source.ads.AdsMediaSource.lambda$prepareSourceInternal$0$AdsMediaSource(AdsMediaSource.java:190)
        at com.google.android.exoplayer2.source.ads.-$$Lambda$AdsMediaSource$1-m7XF1umsWz9SdpDX3nvldjhmE.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
     Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
        at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:339)
        at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:402)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252) 
        at android.webkit.WebView.getFactory(WebView.java:2551) 
        at android.webkit.WebView.ensureProviderCreated(WebView.java:2545) 
        at android.webkit.WebView.setOverScrollMode(WebView.java:2613) 
        at android.view.View.<init>(View.java:5060) 
        at android.view.View.<init>(View.java:5201) 
        at android.view.ViewGroup.<init>(ViewGroup.java:675) 
        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56) 
        at android.webkit.WebView.<init>(WebView.java:410) 
        at android.webkit.WebView.<init>(WebView.java:353) 
        at android.webkit.WebView.<init>(WebView.java:336) 
        at android.webkit.WebView.<init>(WebView.java:323) 
        at android.webkit.WebView.<init>(WebView.java:313) 
        at com.google.ads.interactivemedia.v3.internal.ed.<init>(IMASDK:23) 
        at com.google.ads.interactivemedia.v3.internal.cu.<init>(IMASDK:1) 
        at com.google.ads.interactivemedia.v3.api.ImaSdkFactory.createAdsLoader(IMASDK:6) 
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader$DefaultImaFactory.createAdsLoader(ImaAdsLoader.java:756) 
        at com.google.android.exoplayer2.ext.ima.AdTagLoader.requestAds(AdTagLoader.java:530) 
        at com.google.android.exoplayer2.ext.ima.AdTagLoader.<init>(AdTagLoader.java:266) 
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.requestAds(ImaAdsLoader.java:451) 
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.start(ImaAdsLoader.java:539) 
        at com.google.android.exoplayer2.source.ads.AdsMediaSource.lambda$prepareSourceInternal$0$AdsMediaSource(AdsMediaSource.java:190) 
        at com.google.android.exoplayer2.source.ads.-$$Lambda$AdsMediaSource$1-m7XF1umsWz9SdpDX3nvldjhmE.run(Unknown Source:4) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 
```

**Comment by marcbaechinger** [comment]
Yeah, supporting devices going not through CTS is difficult because they are actually not real Android devices without that. However, I see that does not help you. 

IMA using a WebView under the hood is more an implementation detail that we should not care about. Ideally this would be taken into account from IMA side and just do nothing in such cases. I can file an internal bug for this, but I guess what I will hear is that on devices not having passed CTS it's not expected to work. I'll report back what I hear from there.

> but handling it gracefully can result in a better UX

Yeah, totally. The best UX would result in apps not trying to load ads if there is no webview. This would minimize startup time by not starting the SDK at all. So an app can test for `getPackageManager().hasSystemFeature(PackageManager.FEATURE_WEBVIEW)` and then create the `MediaItem` with or without the `AdsConfiguration` according to the availability of the webview. This is the most efficient solution I think as it doesn't even try to load the webview that is not available.

**Comment by marcbaechinger** [comment]
Internal bug ref: b/261432339
