### ISSUE TITLE
Can not play the HLS DAI stream which encrypted by AES-128 (SSAI)

### ISSUE THREAD

**Issue by 247az** [google/ExoPlayer#10862]
I tested this issue on version 2.17.1, no problem. But after updating ExoPlayer to version 2.18.0 or above, then playback cannot start. And the request to the license server is also absent.

Player setup:
```
 adsLoader = ImaAdsLoader.Builder(context.applicationContext)
            .setDebugModeEnabled(BuildConfig.DEBUG)
            .setAdEventListener { event ->
                adEventListener?.onAdEvent(event)
            }
            .setAdErrorListener { error ->
                adErrorListener?.onAdError(error)
            }
            .setImaSdkSettings(imaSdkSettings).build()
        val adsMediaSourceFactory = DefaultMediaSourceFactory(dataSourceFactory)
            .setLocalAdInsertionComponents( { adsLoader }, playerView)

// Create a server side ad insertion AdsLoader
        daiAdsLoader = ImaServerSideAdInsertionMediaSource.AdsLoader.Builder(context, playerView)
            .setAdEventListener { event ->
                adEventListener?.onAdEvent(event)
            }
            .setAdErrorListener { error ->
                adErrorListener?.onAdError(error)
            }
            .setImaSdkSettings(imaSdkSettings).build()
        // MediaSource.Factory to create the ad sources for the current player.
        daiAdsLoader?.let {
            val daiAdsMediaSourceFactory = ImaServerSideAdInsertionMediaSource.Factory(it, adsMediaSourceFactory)
            adsMediaSourceFactory.setServerSideAdInsertionMediaSourceFactory(daiAdsMediaSourceFactory)
        }

        playerBuilder.setMediaSourceFactory(adsMediaSourceFactory)
```
createServerSideAdInsertionMediaItemBuilder() method.
```
private fun createServerSideAdInsertionMediaItemBuilder(): MediaItem.Builder? {
         httpDataSourceFactory.setDefaultRequestProperties(requestHeaders)

        // Build an IMA SSAI media item to prepare the player with.
        val ssaiLiveUri = ImaServerSideAdInsertionUriBuilder()
            .setAssetKey(assetKey)
            .setFormat(C.CONTENT_TYPE_HLS)
            .build()

        // Create the MediaItem to play, specifying the stream URI.
        return MediaItem.Builder().setUri(ssaiLiveUri)
    }
```

We use `requestHeaders` for the request to the license server.
```
httpDataSourceFactory.setDefaultRequestProperties(requestHeaders)
```

Note that, there are no problems on 2.17.1 version

On 2.17.1
Has request to the license server: https://qaplg02east.keydelivery.japaneast.media.azure.net/?kid=d54fb5c8-513e-4340-a936-a45f818997de

On 2.18.0 or above
No request to the license server: https://qaplg02east.keydelivery.japaneast.media.azure.net/?kid=d54fb5c8-513e-4340-a936-a45f818997de
--> So the video or audio fragment can not be downloaded.

There aren't any errors thrown from the ExoPlayer side, but if you look at the event log it looks a bit strange. With a `period [?]`.

Event log:
```
EventLogger: timeline [eventTime=156.27, mediaPos=8778.77, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
EventLogger:   period [?]
EventLogger:   window [8932.92, seekable=true, dynamic=true]
EventLogger: ]
```

### ExoPlayer Version

2.18.0 - 2.18.2

### Devices that reproduce the issue

Any devices

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play a SSAI content (Play the HLS DAI stream which encrypted by AES-128)

For example: 
```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-DISCONTINUITY-SEQUENCE:0
#EXT-X-I-FRAMES-ONLY

#EXT-X-KEY:METHOD=AES-128,URI="https://qaplg02east.keydelivery.japaneast.media.azure.net/?kid=d54fb5c8-513e-4340-a936-a45f818997de",IV=0X79D4C126D68BB73240DF2B5292ED2EC0
#EXT-X-PROGRAM-DATE-TIME:2022-12-07T05:31:07Z
#EXTINF:2.002000,no-desc
https://qartvnplg-hls02-east.akamaized.net/09bad558-a9ca-44d0-9350-f0655eedd77b/4f9e1815-629d-4797-912d-d08909eb25e6.ism/QualityLevels(200000)/KeyFrames(video=20020000,format=m3u8-aapl,encryption=cbc)
#EXTINF:2.002000,no-desc
https://qartvnplg-hls02-east.akamaized.net/09bad558-a9ca-44d0-9350-f0655eedd77b/4f9e1815-629d-4797-912d-d08909eb25e6.ism/QualityLevels(200000)/KeyFrames(video=40040000,format=m3u8-aapl,encryption=cbc)
#EXTINF:2.002000,no-desc
https://qartvnplg-hls02-east.akamaized.net/09bad558-a9ca-44d0-9350-f0655eedd77b/4f9e1815-629d-4797-912d-d08909eb25e6.ism/QualityLevels(200000)/KeyFrames(video=60060000,format=m3u8-aapl,encryption=cbc)
#EXTINF:2.002000,no-desc
https://qartvnplg-hls02-east.akamaized.net/09bad558-a9ca-44d0-9350-f0655eedd77b/4f9e1815-629d-4797-912d-d08909eb25e6.ism/QualityLevels(200000)/KeyFrames(video=80080000,format=m3u8-aapl,encryption=cbc)
#EXTINF:2.002000,no-desc
....

```

### Expected result

Can play the HLS DAI stream which encrypted by AES-128 (SSAI) without problems

### Actual result

Can not play the HLS DAI stream which encrypted by AES-128 (SSAI) 

### Media

Play the HLS DAI stream which encrypted by AES-128 (SSAI)

master.m3u8
```
#EXTM3U
#EXT-X-VERSION:4

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="comment",LANGUAGE="en",URI="https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/8397dbf6f5275d2c2e5c2ccb97fc92a6/bandwidth/000.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="no_comment",LANGUAGE="en",DEFAULT=YES,URI="https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/c2fec07d74cff68e829756591de604a2/bandwidth/000.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=416944,RESOLUTION=320x180,CODECS="avc1.4d400d",URI="https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/3b6b972edfa49e18c040c772e9edc3d5/bandwidth/416944.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=621344,RESOLUTION=480x270,CODECS="avc1.4d4015",URI="https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/d9d4e21b01042049647515421f1684bf/bandwidth/621344.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=927911,RESOLUTION=480x270,CODECS="avc1.4d4015",URI="https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/828ae3bf7aa9a12139bd3331cd8338c9/bandwidth/927911.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=1234544,RESOLUTION=640x360,CODECS="avc1.4d401e",URI="https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/40ce50f237f4f35dde8f0e5418c2e9de/bandwidth/1234544.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=2869744,RESOLUTION=960x540,CODECS="avc1.4d401f",URI="https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/c863c4529550391e57a1ba71ac35a889/bandwidth/2869744.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=4300544,RESOLUTION=1280x720,CODECS="avc1.4d401f",URI="https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/e8aa31dfd075656ad17e2c6499a7d595/bandwidth/4300544.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=6344544,RESOLUTION=1920x1080,CODECS="avc1.4d4028",URI="https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/c9fc492e9546140c7246932450685201/bandwidth/6344544.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=416944,RESOLUTION=320x180,CODECS="avc1.4d400d,mp4a.40.2",AUDIO="audio"
https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/2c00fd17a3911cbd27c9328a6f9b94aa/bandwidth/416944.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=621344,RESOLUTION=480x270,CODECS="avc1.4d4015,mp4a.40.2",AUDIO="audio"
https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/60a211d0900691a31e4804b07974512b/bandwidth/621344.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=927911,RESOLUTION=480x270,CODECS="avc1.4d4015,mp4a.40.2",AUDIO="audio"
https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/56f05553b386644e973b2edf97691292/bandwidth/927911.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1234544,RESOLUTION=640x360,CODECS="avc1.4d401e,mp4a.40.2",AUDIO="audio"
https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/005e8314a59288941742dfec28a99db6/bandwidth/1234544.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2869744,RESOLUTION=960x540,CODECS="avc1.4d401f,mp4a.40.2",AUDIO="audio"
https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/5da73a79d09d08bb811051fce3a23954/bandwidth/2869744.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=4300544,RESOLUTION=1280x720,CODECS="avc1.4d401f,mp4a.40.2",AUDIO="audio"
https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/367d506b8ca0c5c4488322519c241108/bandwidth/4300544.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=6344544,RESOLUTION=1920x1080,CODECS="avc1.4d4028,mp4a.40.2",AUDIO="audio"
https://dai.google.com/linear/hls/pb/event/JqpG8XXcQGiqyPDrUWAaWw/stream/5c753129-3f43-443e-bf57-25ce555730ff:TPE/variant/6a1085862b9293770cedd59bd6213e29/bandwidth/6344544.m3u8

```

416944.m3u8: 
```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-DISCONTINUITY-SEQUENCE:0
#EXT-X-I-FRAMES-ONLY

#EXT-X-KEY:METHOD=AES-128,URI="https://qaplg02east.keydelivery.japaneast.media.azure.net/?kid=d54fb5c8-513e-4340-a936-a45f818997de",IV=0X79D4C126D68BB73240DF2B5292ED2EC0
#EXT-X-PROGRAM-DATE-TIME:2022-12-07T05:31:07Z
#EXTINF:2.002000,no-desc
https://qartvnplg-hls02-east.akamaized.net/09bad558-a9ca-44d0-9350-f0655eedd77b/4f9e1815-629d-4797-912d-d08909eb25e6.ism/QualityLevels(200000)/KeyFrames(video=20020000,format=m3u8-aapl,encryption=cbc)
#EXTINF:2.002000,no-desc
https://qartvnplg-hls02-east.akamaized.net/09bad558-a9ca-44d0-9350-f0655eedd77b/4f9e1815-629d-4797-912d-d08909eb25e6.ism/QualityLevels(200000)/KeyFrames(video=40040000,format=m3u8-aapl,encryption=cbc)
#EXTINF:2.002000,no-desc
https://qartvnplg-hls02-east.akamaized.net/09bad558-a9ca-44d0-9350-f0655eedd77b/4f9e1815-629d-4797-912d-d08909eb25e6.ism/QualityLevels(200000)/KeyFrames(video=60060000,format=m3u8-aapl,encryption=cbc)
#EXTINF:2.002000,no-desc
https://qartvnplg-hls02-east.akamaized.net/09bad558-a9ca-44d0-9350-f0655eedd77b/4f9e1815-629d-4797-912d-d08909eb25e6.ism/QualityLevels(200000)/KeyFrames(video=80080000,format=m3u8-aapl,encryption=cbc)
#EXTINF:2.002000,no-desc
....

```

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by devno44** [comment]
@marcbaechinger @microkatz 
I can reproduce this. 
If you set this `dai-sr` ad parameter to `ServerSideAdInsertionMediaSource`, this will happen, I don't understand why. You can reproduce it on ExoPlayer's sample app if you set this `dai-sr` ad parameter.
https://support.google.com/admanager/answer/7320898?hl=en
For example: `dai-sr=0:2500000`

**Comment by marcbaechinger** [comment]
> I can reproduce this. If you set this dai-sr ad parameter to ServerSideAdInsertionMediaSource, this will happen,

@devno44 Sorry, what are the `this` in the sentence above?

The issue is about AES-128 not working with the `ImaServerSideInsertedAdsMediaSource`. You say this is reproducable with the demo app, but the demo app does not have an encrypted stream I think.

So to both, @devno44  and @247az (sorry for my late response also):  If this is about AES-128 streams not working, can you provide me with a `assetKey` for an encrypted HLS live stream? Is this still happening with the current version?

> if you look at the event log it looks a bit strange. With a period [?].

That means that the duration of the period is unknown which is normal and expected for live streams that have no end.

**Comment by devno44** [comment]
@marcbaechinger 
> I can reproduce this.
> If you set this dai-sr ad parameter to ServerSideAdInsertionMediaSource, this will happen, I don't understand why. You can > reproduce it on ExoPlayer's sample app if you set this dai-sr ad parameter.
> https://support.google.com/admanager/answer/7320898?hl=en
> For example: dai-sr=0:2500000

As I said above, I think it doesn't depend on it's AES-128 streams or not.Which is because you set an ad tag parameter named `dai-sr`. If you set it up, you won't be able to play it.
You can completely reproduce it in the demo app if you set `dai-sr` to `adTagParameters`.

You can use this `assetKey` to reproduce it.
```
{
        "name": "HLS Live: Big Buck Bunny (mid), 3 ads [10/10/10s]",
        "uri": "ssai://dai.google.com/?assetKey=qmB0Lc10QTy7ZnSraUPIKA&adTagParameters=%3Fdai-sr%3D0%253A5000000&format=2&adsId=3"
      }
```

Stream can be played if you not set `adTagParameters=%3Fdai-sr%3D0%253A5000000`
```
{
        "name": "HLS Live: Big Buck Bunny (mid), 3 ads [10/10/10s]",
        "uri": "ssai://dai.google.com/?assetKey=qmB0Lc10QTy7ZnSraUPIKA&format=2&adsId=3"
      }
```

**Comment by marcbaechinger** [comment]
When I play `HLS Live: Big Buck Bunny (mid)` with the URL above with the given parameter I get a completely different playlist pointing to different servers. When I follow the playlist structure with curl then I soon get:

```
 HTTP/2 503 
< server: AkamaiGHost
< mime-version: 1.0
< content-type: text/html
< content-length: 268
```

This corresponds to what I get when trying to play the stream URI directly without the IMA extension:

```
2023-03-08 16:08:03.435 13902-13902 EventLogger             androidx.media3.demo.main            E  internalError [eventTime=7.45, mediaPos=0.00, window=0, period=0, loadError
androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 503
  at androidx.media3.datasource.cronet.CronetDataSource.open(CronetDataSource.java:628)
  at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:272)
  at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:798)
  at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:611)
  at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
  at androidx.media3.exoplayer.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:495)
  at androidx.media3.exoplayer.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:468)
  at androidx.media3.exoplayer.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:437)
  at androidx.media3.exoplayer.hls.HlsMediaChunk.load(HlsMediaChunk.java:394)
  at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:414)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:919)
]
```

My understanding is that in normal cases, the DAI service gets an HLS playlist for the content stream from the customer and stitches in the ad segments. Whether or not different bandwidth variants can be delivered, which is what setting the `dai-sr` parameter implies, depends on the content provider. 

From this, in general I don't think that the problem with setting that parameters breaks the ExoPlayer DAi extension, but it breaks the stream that is delivered by the SDK. I don't know how to validate what and which bandwidth requests by this parameter are valid but if the delivered stream can't be played, the DAI extension can't fix this.

What makes you expect that this parameter can be set to a random stream? If you have a stream for which you know setting this parameter gives you a working stream and this stream does not work with the ExoPlayer DAI extension than I would be super interested to get such a stream.

The same is true for an AES encripted test stream.  I'd very glad to have such a stream for testing to see why this fails to play.

**Comment by devno44** [comment]
@marcbaechinger 
Thank you,
Maybe the stream url I gave you was closed, and I need to recreate it. Sorry it can't last more than 8 hours.
```
HTTP/2 503 
< server: AkamaiGHost
< mime-version: 1.0
< content-type: text/html
< content-length: 268
```

And why I think it's `ImaServerSideInsertedAdsMediaSource`'s problem is because when I do it the way below, I can still set up `dai-sr` parameter. I don't know what the difference is.

```
adsLoader = sdkFactory.createAdsLoader(context, imaSdkSettings, displayContainer)
```
```
 adsLoader?.requestStream(buildStreamRequest())
```
```
private fun buildStreamRequest(): StreamRequest? {
        return sdkFactory.createLiveStreamRequest(assetKey, "").also { req ->
            req.format = format
            adTagParameters?.let { req.adTagParameters = it }
        }
    }
```
And use the stream url from this

```
private fun createVideoStreamPlayer(): VideoStreamPlayer {
        return object : VideoStreamPlayer {
            override fun loadUrl(url: String?, subtitles: List<HashMap<String?, String?>?>?) {
                ===> Use the url from this callback
            }
        ....
}
```

**Comment by marcbaechinger** [comment]
Ok, thanks for clarifying. If you want to post a new stream I can try to be quick enough before it expires.

**Comment by devno44** [comment]
@marcbaechinger 
Thank you.
Sorry, But can you tell me what time is good for you? because I can't start a stream without knowing the exact time you can use it.
Maybe our time is different.
