### ISSUE TITLE
Missing CodecPrivate for codec V_MPEG4/ISO/AVC

### ISSUE THREAD

**Issue by sysmind** [google/ExoPlayer#10861]
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

Infinix android 11

### Reproducible in the demo app?

Yes

### Reproduction steps

E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:637)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:607)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:268)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     **Caused by: com.google.android.exoplayer2.ParserException: Missing CodecPrivate for codec V_MPEG4/ISO/AVC**
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$Track.getCodecPrivate(MatroskaExtractor.java:2548)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$Track.initializeOutput(MatroskaExtractor.java:2074)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.endMasterElement(MatroskaExtractor.java:812)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$InnerEbmlProcessor.endMasterElement(MatroskaExtractor.java:1947)
        at com.google.android.exoplayer2.extractor.mkv.DefaultEbmlReader.read(DefaultEbmlReader.java:88)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.read(MatroskaExtractor.java:512)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1039)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)

And here is my code -

  player = new ExoPlayer.Builder(Objects.requireNonNull(getActivity())).build();
        simpleExoPlayerView.setPlayer(player);
        MediaItem mediaItem = MediaItem.fromUri(videoUri);
        player.setMediaItem(mediaItem);
        player.prepare();
        player.play();

### Expected result

Video will play

### Actual result

Video not playing

### Media

https://cdnmedia-fm.melpapp.com/7a14c9d8-c99a-42d6-8a55-cc02395ee339/0d53@screencapture.webm?sessionid=7zoijdm41s00

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by rohitjoins** [comment]
Hi @sysmind,

Based on the [codec specs](https://www.matroska.org/technical/codec_specs.html) for Matroska, each encoding supported for storage in Matroska MUST have a defined Initialization. The Initialization MUST describe the storage of data necessary to initialize the decoder, which MUST be stored within the `CodecPrivate` Element defined [here](https://www.matroska.org/technical/elements.html).

Now for codec `V_MPEG4/ISO/AVC`, the `CodecPrivate` element should contain `AVCDecoderConfigurationRecord` structure which is missing as seen by inspecting the file using [`mkvinfo`](https://mkvtoolnix.download/doc/mkvinfo.html).

```
+ EBML head
|+ EBML version: 1
|+ EBML read version: 1
|+ Maximum EBML ID length: 4
|+ Maximum EBML size length: 8
|+ Document type: matroska
|+ Document type version: 4
|+ Document type read version: 2
+ Segment: size unknown
|+ Segment information
| + Timestamp scale: 1000000
| + Multiplexing application: Chrome
| + Writing application: Chrome
|+ Tracks
| + Track
|  + Track number: 1 (track ID for mkvmerge & mkvextract: 0)
|  + Track UID: 36983872468098380
|  + Track type: video
|  + Codec ID: V_MPEG4/ISO/AVC
|  + Video track
|   + Pixel width: 1920
|   + Pixel height: 1080
|+ Cluster
```

Closing this issue as bad media.

Note: webm comprises a subset of the Matroska multimedia container format.
