### ISSUE TITLE
Some subtitles tracks stop playing after upgrade to 2.18.2 from 2.18.1

### ISSUE THREAD

**Issue by DarkAnakin** [google/ExoPlayer#10867]
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

Pixel 4a 
Fire Stick Max

### Devices that do not reproduce the issue

None

### Reproducible in the demo app?

Not tested

### Reproduction steps

none

### Expected result

play subtitle track

### Actual result

`at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:621)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loop(Looper.java:193)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:65)
                                                                                                      Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
                                                                                                          at com.google.android.exoplayer2.text.ttml.TtmlSubtitle.getEventTime(TtmlSubtitle.java:62)
                                                                                                          at com.google.android.exoplayer2.text.SubtitleOutputBuffer.getEventTime(SubtitleOutputBuffer.java:53)
                                                                                                          at com.google.android.exoplayer2.text.TextRenderer.getCurrentEventTimeUs(TextRenderer.java:426)
                                                                                                          at com.google.android.exoplayer2.text.TextRenderer.render(TextRenderer.java:259)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:994)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:495)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                          at android.os.Looper.loop(Looper.java:193) 
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:65) `

### Media

none

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
Thanks for reporting, based on the stack trace I think this is the same underlying issue I fixed in https://github.com/google/ExoPlayer/commit/5f6fde4d2a90d78a8d58430c88d7dc12849fe163 - so I'm going to close this and the fix will be included in the next release.

**Comment by jmvillagra** [comment]
Thank you @icbaker Do you have an approximately idea when the next release will be out? 
We're also facing this problem when users change subtitles track in the player, it's quite a blocker issue.

**Comment by icbaker** [comment]
We don't yet have a planned date for the next release I'm afraid.

> We're also facing this problem when users change subtitles track in the player, it's quite a blocker issue.

Is this an adaptive stream with subtitles referenced from the manifest (e.g. DASH or HLS) or have you sideloaded subtitles (i.e. via `MediaItem.SubtitleConfiguration`) (or is it a progressive container like MP4 with multiple subtitle files muxed into the same file as audio and video tracks)?

**Comment by jmvillagra** [comment]
DASH Stream with references subtitles
`    <AdaptationSet id="3" mimeType="application/mp4" contentType="text" lang="en" codecs="stpp">
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="alternate"/>
      <SegmentTemplate media="..." presentationTimeOffset="0" timescale="1000" initialization="....">
        <SegmentTimeline>
          <S t="1671099265600" d="1600" r="9"/>
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation id="10" bandwidth="100"/>
    </AdaptationSet>`

**Comment by jmvillagra** [comment]
After more testing, we can reproduce the issue at anytime subtitles are enabled and not only when activating / deactivating them. So we cannot release this version to the public without breaking completely subtitles. Any updates on possible release dates for 2.18.3? 
This fix should have a bigger priority than minor.
