### ISSUE TITLE
ExoPlayer doesn't play some videos on some devices.

### ISSUE THREAD

**Issue by juliangerhards** [google/ExoPlayer#10876]
The video stays black, no sound, no image, no crash. It does show the length of the video tho!
On simulator it runs but has weird artifacts.

Device: SAMSUNG GALAXY S10 LIGHT

It's an MP4 video which was cropped and resized with FFMPEG (X264).

Version:
``implementation 'com.google.android.exoplayer:exoplayer:2.18.2'``

My code:
```kotlin
@Composable
fun VideoView(videoUri: String, height: Float) {
    val context = LocalContext.current

    val exoPlayer = ExoPlayer.Builder(context)
            .build()
            .also { exoPlayer ->

                val mediaItem = MediaItem.Builder()
                        .setMimeType("video/mp4")
                        .setUri(videoUri)
                        .build()

                exoPlayer.setMediaItem(mediaItem)
                exoPlayer.prepare()
            }

    val lifecycleOwner = rememberUpdatedState(LocalLifecycleOwner.current)

    DisposableEffect(
            AndroidView(factory = {
                StyledPlayerView(context).apply {
                    player = exoPlayer
                }
            }, modifier = Modifier.height(height.dp))
    ) {
        val observer = LifecycleEventObserver { owner, event ->
            when (event) {
                Lifecycle.Event.ON_PAUSE -> {
                    exoPlayer.pause()
                }
                Lifecycle.Event.ON_RESUME -> {
                    exoPlayer.play()
                }
                else -> {}
            }
        }
        val lifecycle = lifecycleOwner.value.lifecycle
        lifecycle.addObserver(observer)

        onDispose {
            exoPlayer.release()
            lifecycle.removeObserver(observer)
        }
    }
}
```

I had to cut a lot out because of the limit. The part i think is the most interesting:
```
E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
E/ACodec: [OMX.qcom.video.decoder.avc] ERROR(0x80001009)
E/ACodec: signalError(omxError 0x80001009, internalError -2147483648)
E/MediaCodec: Codec reported err 0x80001001/-2147479551 (Unknown error 2147479551), actionCode 0, while in state 6/STARTED
E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
D/SurfaceUtils: disconnecting from surface 0xb400007c2fcb1010, reason disconnectFromSurface
E/Surface: freeAllBuffers: 4 buffers were freed while being dequeued!
E/MediaCodec: Codec reported err 0x80001009/-2147479543 (Unknown error 2147479543), actionCode 0, while in state 0/UNINITIALIZED
E/MediaCodec: Codec reported err 0x80001001/-2147479551 (Unknown error 2147479551), actionCode 0, while in state 0/UNINITIALIZED
E/MediaCodecVideoRenderer: Video codec error
      android.media.MediaCodec$CodecException: Error 0x80001001
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.6E001F, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [r5q, SM-G770F, samsung, 33]
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.6E001F, video/avc] [c2.android.avc.decoder, video/avc] [r5q, SM-G770F, samsung, 33]
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.6E001F, -1, null, [800, 602, 29.997414], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:571)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1629)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:994)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:495)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.media.MediaCodec$CodecException: Error 0x80001001
E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2388)
        at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.flush(AsynchronousMediaCodecAdapter.java:228)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:877)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:870)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:710)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:608)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:186)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1655)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1396)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1359)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:587)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by microkatz** [comment]
Hi! It appears that the mediatype is not supported by the available decoders. As there is not other tracks or options to play, it seems Exoplayer tries anyway but it was correct and could not play it correctly.

In your shared log trace:
MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.6E001F, -1, null, [800, 602, 29.997414], [-1, -1]), **format_supported=NO_EXCEEDS_CAPABILITIES**

It may be that the profile or level are unsupported or that your cropping invalidated the mediatype. Some formats require resolutions that are divisible by 4/8. The 602 in your format res seems odd.

Feel free to re-open if you have additional questions or if you choose to send the media content along for us to test further. You can send the content to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). If you do so, please also update this issue to
indicate you've done this.

**Comment by AndersonCodeArt** [comment]
I have a similar problem here, how do I end it?

MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640034, -1, null, [2156, 4312, 29.999216], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
