### ISSUE TITLE
SurfaceView.updateSurface causes the thread check to fail if the ExoPlayer instance is managed from a thread other than main

### ISSUE THREAD

**Issue by stoyicker** [google/ExoPlayer#10880]
### ExoPlayer Version

2.14.2

### Devices that reproduce the issue

All.

### Devices that do not reproduce the issue

None.

### Reproducible in the demo app?

No

### Reproduction steps

1. Checkout MWE [here](https://github.com/stoyicker/mwe-exoplayer-surfaceviewwrongthread/tree/1ef3c119bf460485c3b2e884157c21d240e7a476).
2. Run the app.

### Expected result

The video plays successfully.

### Actual result

The video visuals fail to render. See longs for "wrong thread" issue and how it traces to SurfaceView.

Note that it seems to be a slightly different form https://github.com/google/ExoPlayer/issues/9005

It is a strong requirement for me to use a custom thread as it has to use a specific ThreadGroup and be confined to certain parts of the codebase.

I've opened it as a bug, but I'm not even sure it is - is there an intended way to work with this? If so, what is it?

### Media

https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tianyif** [comment]
Hi @stoyicker,

From the received bug report we are seeing

```
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: Exception configuring surface
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: java.lang.IllegalStateException: Player is accessed on the wrong thread.
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: Current thread: 'main'
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: Expected thread: 'ExoPlayerThread'
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:2041)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at com.google.android.exoplayer2.SimpleExoPlayer.getCurrentTimeline(SimpleExoPlayer.java:1681)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:863)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:912)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateReadingMediaPeriodEventTime(AnalyticsCollector.java:920)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at com.google.android.exoplayer2.analytics.AnalyticsCollector.onSurfaceSizeChanged(AnalyticsCollector.java:492)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at com.google.android.exoplayer2.SimpleExoPlayer.maybeNotifySurfaceSizeChanged(SimpleExoPlayer.java:1975)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at com.google.android.exoplayer2.SimpleExoPlayer.access$4100(SimpleExoPlayer.java:92)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at com.google.android.exoplayer2.SimpleExoPlayer$ComponentListener.surfaceChanged(SimpleExoPlayer.java:2285)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.view.SurfaceView.updateSurface(SurfaceView.java:1196)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.view.SurfaceView.lambda$new$0$SurfaceView(SurfaceView.java:175)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.view.SurfaceView$$ExternalSyntheticLambda2.onPreDraw(Unknown Source:2)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3300)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8658)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.view.Choreographer.doFrame(Choreographer.java:780)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.os.Handler.handleCallback(Handler.java:938)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.os.Looper.loopOnce(Looper.java:201)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.os.Looper.loop(Looper.java:288)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at java.lang.reflect.Method.invoke(Native Method)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-21 15:33:17.257 10149  5989  5989 E SurfaceView: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
looks like the issue is similar to https://github.com/google/ExoPlayer/issues/9005, that the `SurfaceHolder` callbacks are called on the main thread, but `SimpleExoPlayer.getCurrentTimeline()` is expected to be called on your `ExoPlayerThread`. As suggested in https://exoplayer.dev/hello-world.html#a-note-on-threading, the `ExoPlayer` instances must be accessed from a single application thread.

If it is a requirement for you to use the `ExoPlayer` on a custom thread, could you please try if this [workaround](https://github.com/google/ExoPlayer/issues/9005#issuecomment-856094027) works for you?

**Comment by stoyicker** [comment]
Hi again and happy new year!

Apologies for the late reply, I've been on vacation. I can confirm that something like the workaround works for my use case, but I am working on a library and it will compromise the relevant part of my API in a way that I'd rather avoid.

Given that as per the "A note on threading" link you refer to my MWE _should_ work given that it doesn't use either the IMA or UI extensions and that the offending access to ExoPlayer on the wrong thread is an unfortunate limitation from Android that I can't really do much about from my end, would you be willing to consider a contribution to incorporate the logic for wrapping the callback passed to `setSurfaceHolder` in a solution based on the workaround if Exo's looper is not the main one into ExoPlayer?

**Comment by tianyif** [comment]
@stoyicker Happy new year!

Sorry for the confusion first. The "A note on threading" link doesn't mean that your case has to enforce the `ExoPlayer` on main thread, it just explains the `ExoPlayer` should be access from a single thread, except for the IMA or UI extensions which have more requirement on the main thread. For `setVideoSurfaceView`, we have the [documentation](https://github.com/google/ExoPlayer/blob/release-v2/library/common/src/main/java/com/google/android/exoplayer2/Player.java#L2431-L2432) that the thread that calls the `SurfaceHolder.Callback` methods must be the thread associated with `getApplicationLooper()` (sorry again that I should have mentioned this one as well in the last message). The same applies to `setVideoSurfaceHolder`  and `setVideoTextureView` methods as well.

Yes, we would like to consider a contribution for this. The reason why we haven't done ourselves is that the surface methods need to be handled synchronously. For example, `surfaceDestroyed()` needs to remove the Surface from the MediaCodec before the callback returns. That is to say, we have to block the callbacks called on main thread until the player thread completed the actual work. Then given that we don't have full control on the player thread (eg. the app may have blocked the player thread), there is a risk to create deadlock, depending on what other things the app is doing on the main and player thread.

I'm marking this as an enhancement, but this is a non-trivial change and we haven't implemented yet.

**Comment by stoyicker** [comment]
Apologies on me, should definitely have thought about reading the javadoc for the methods that the issue resolves around.

Anyway, I see the complexity regarding the possibility of a deadlock. I'll see if I can think of something to avoid it. Thanks for the help!
