### ISSUE TITLE
App Fc [AbstractMethodError]

### ISSUE THREAD

**Issue by otangid** [google/ExoPlayer#10916]
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

Redmi note 8
Android 10

### Reproducible in the demo app?

Not tested

### Reproduction steps

Listener in service

### Expected result

App not fc

### Actual result

Build version: 1.0 
Build date: 2023-01-11 20:46:50 
Current date: 2023-01-11 20:47:19 
Device: Xiaomi Redmi Note 8 
 
Stack trace:  
java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$Listener.onTimelineChanged(com.google.android.exoplayer2.Timeline, int)"
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$12(ExoPlayerImpl.java:1874)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda14.invoke(Unknown Source:6)
	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:282)
	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
	at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1966)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1794)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1$com-google-android-exoplayer2-ExoPlayerImpl(ExoPlayerImpl.java:312)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda5.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment]
Similar issues, with solutions, have been reported in #8227, #7927, #6738 amd #6372. Can you please go through them and see which one fits your project?
