### ISSUE TITLE
How to get the url of the currently playing ts file?

### ISSUE THREAD

**Issue by jinlinupup** [google/ExoPlayer#10927]
```
Authentication error encountered during playback：
com.google.android.exoplayer2.ExoPlaybackException: Source error
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:628)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:219)
    at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
    at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:382)
    at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
    at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
    at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
    at com.google.android.exoplayer2.source.hls.Aes128DataSource.open(Aes128DataSource.java:93)
    at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:483)
    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:457)
    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:432)
    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:388)
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:929)
```
How to get the url of the currently playing ts file?

**Comment by rohitjoins** [comment]
Hi @jinlinupup,

To get the url of the current playing media file, you can define an instance of [`AnalyticsListener`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/AnalyticsListener.html) which overrides the method [`onLoadStarted`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/AnalyticsListener.html#onLoadStarted(com.google.android.exoplayer2.analytics.AnalyticsListener.EventTime,com.google.android.exoplayer2.source.LoadEventInfo,com.google.android.exoplayer2.source.MediaLoadData)) and then call [`player.addAnalyticsListener`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlayer.html#addAnalyticsListener(com.google.android.exoplayer2.analytics.AnalyticsListener)) on the `ExoPlayer` instance of the player.

You'll receive a callback to your overridden method whenever we start loading a media. Adding an example code snippet to demonstrate the same.

```
player.addAnalyticsListener(new AnalyticsListener() {
  @Override
  public void onLoadStarted(EventTime eventTime, LoadEventInfo loadEventInfo,
      MediaLoadData mediaLoadData) {
    String uriString = loadEventInfo.uri.toString(); // media url
    AnalyticsListener.super.onLoadStarted(eventTime, loadEventInfo, mediaLoadData);
  }
});
```
