### ISSUE TITLE
Fragment scrolling error

### ISSUE THREAD

**Issue by Dacao404** [google/ExoPlayer#10924]
```
023-01-13 12:33:22.994 307-23297/? E/C2RKMpiDec: failed to find output buffer
2023-01-13 12:33:22.994 22492-23295/com.example.zhuoyuadvert E/MediaCodec: Codec reported err 0xe, actionCode 0, while in state 6/STARTED
2023-01-13 12:33:22.996 22492-23295/com.example.zhuoyuadvert E/BufferQueueProducer: [SurfaceTexture-1-22492-6](id:57dc00000018,api:0,p:-1,c:22492) cancelBuffer: BufferQueue has no connected producer
2023-01-13 12:33:22.996 22492-23295/com.example.zhuoyuadvert E/BufferQueueProducer: [SurfaceTexture-1-22492-6](id:57dc00000018,api:0,p:-1,c:22492) cancelBuffer: BufferQueue has no connected producer
2023-01-13 12:33:22.996 22492-23295/com.example.zhuoyuadvert E/BufferQueueProducer: [SurfaceTexture-1-22492-6](id:57dc00000018,api:0,p:-1,c:22492) cancelBuffer: BufferQueue has no connected producer
2023-01-13 12:33:22.996 22492-23295/com.example.zhuoyuadvert E/BufferQueueProducer: [SurfaceTexture-1-22492-6](id:57dc00000018,api:0,p:-1,c:22492) cancelBuffer: BufferQueue has no connected producer
2023-01-13 12:33:22.996 22492-23295/com.example.zhuoyuadvert E/BufferQueueProducer: [SurfaceTexture-1-22492-6](id:57dc00000018,api:0,p:-1,c:22492) cancelBuffer: BufferQueue has no connected producer
2023-01-13 12:33:22.996 22492-23295/com.example.zhuoyuadvert E/BufferQueueProducer: [SurfaceTexture-1-22492-6](id:57dc00000018,api:0,p:-1,c:22492) cancelBuffer: BufferQueue has no connected producer
2023-01-13 12:33:22.996 22492-23295/com.example.zhuoyuadvert E/BufferQueueProducer: [SurfaceTexture-1-22492-6](id:57dc00000018,api:0,p:-1,c:22492) cancelBuffer: BufferQueue has no connected producer
2023-01-13 12:33:23.001 22492-23293/com.example.zhuoyuadvert E/ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(1, null, null, video/avc, null, -1, null, [720, 1280, 25.0], [-1, -1]), rendererSupport=YES
    com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:732)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2938)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1048)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:719)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2023-01-13 12:33:23.003 22492-23293/com.example.zhuoyuadvert E/ExoPlayerImplInternal: Disable failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2350)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:773)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.flushOrReleaseCodec(MediaCodecVideoRenderer.java:724)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:634)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:569)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:168)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1136)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:891)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:382)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2023-01-13 12:33:23.010 22492-22628/com.example.zhuoyuadvert E/BufferQueueProducer: [SurfaceTexture-1-22492-6](id:57dc00000018,api:0,p:-1,c:22492) cancelBuffer: BufferQueue has no connected producer
2023-01-13 12:33:23.011 22492-23293/com.example.zhuoyuadvert E/ExoPlayerImplInternal: Reset failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2300)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:668)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:714)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onReset(MediaCodecRenderer.java:641)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onReset(MediaCodecVideoRenderer.java:578)
        at com.google.android.exoplayer2.BaseRenderer.reset(BaseRenderer.java:175)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:900)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:382)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2023-01-13 12:33:23.021 22492-22628/com.example.zhuoyuadvert E/BufferQueueProducer: [SurfaceTexture-1-22492-6](id:57dc00000018,api:0,p:-1,c:22492) detachBuffer: BufferQueue has been abandoned
```

**Comment by christosts** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml).

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com with subject "Issue #10924" and update this issue to indicate you've done this.
