### ISSUE TITLE
Transforming HLS Live to MP4 Fails

### ISSUE THREAD

**Issue by dev-onetv** [google/ExoPlayer#10943]
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

It happens in all different devices and Android Version that we tested

### Reproducible in the demo app?

Yes

### Reproduction steps

1. modify `demos/transformer/build.gradle` and add the following line at line 83:
```
implementation project(modulePrefix + 'library-hls'),
```
2. Add an example HLS Live Stream URL to the Transformer Demo.
 a) add the following HLS Live Stream URL at  aline 91:
  ```
  "https://dh4wkqcyy8768.cloudfront.net/live_500.m3u8",
  ```
b) Add the title for the above URL at line 107:
  ```
  "Test Record Live Stream - OneTV",
  ```
Here is a link to our fork of the main repo with the changes: https://github.com/dev-onetv/ExoPlayer/commits/release-v2

Now build and run the demo-transformer app using Android Studio, and transforming the added URL.

The first 1-2 minutes of Live Stream video is saved as MP4, but then it fails.

### Expected result

Our use case to be able to record live stream and the Transformer seems to be ideal for this use case. Thus, we can avoid using FFMEG which takes a large size to record from HLS live Stream.

It appears that Transformer fails because the player speed is higher and when it reaches the end of Live Play list, it fails.

We would be very grateful if you could kindly let us now how we can probably reduces the transform speed and how to gracefully stop the transformation after the desired time, thus the MP4 output file is correctly written and playable.

### Actual result

Transform after 1-2 minutes crashes with the following log:

```
I/MPEG4Writer: MOOV atom was written to the file
D/MPEG4Writer: release()
D/MPEG4Writer: ftruncate mPreAllocateFileEndOffset:6957350 mOffset:6950200 mMdatEndOffset:6938606 diff:7150
D/MPEG4Writer: MP4WtrCtrlHlpLooper stopped
D/MPEG4Writer: Top 5 write durations(microseconds): #1:2620 #2:2697 #3:2912 #4:3245 #5:3305
D/MPEG4Writer: reset()
D/MPEG4Writer: Audio track stopping. Stop source
E/MPEG4Writer: Stop() called but track is not started or stopped
D/MPEG4Writer: Video track stopping. Stop source
E/MPEG4Writer: Stop() called but track is not started or stopped
D/CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10157; state: ENABLED
E/TransformerActivity: Transformation error
      com.google.android.exoplayer2.transformer.TransformationException: Muxer error
        at com.google.android.exoplayer2.transformer.MuxerWrapper.lambda$resetAbortTimer$0$com-google-android-exoplayer2-transformer-MuxerWrapper(MuxerWrapper.java:315)
        at com.google.android.exoplayer2.transformer.MuxerWrapper$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.IllegalStateException: No output sample written in the last 3000 milliseconds. Aborting transformation.
        at com.google.android.exoplayer2.transformer.MuxerWrapper.lambda$resetAbortTimer$0$com-google-android-exoplayer2-transformer-MuxerWrapper(MuxerWrapper.java:314)
        at com.google.android.exoplayer2.transformer.MuxerWrapper$$ExternalSyntheticLambda0.run(Unknown Source:4) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
``` 

### Media

Here is an example HLS Live Stream URL:  https://dh4wkqcyy8768.cloudfront.net/live_500.m3u8

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
That's an interesting one for @andrewlewis

**Comment by andrewlewis** [comment]
So far we haven't tried to support using live streams as input to Transformer so I will mark this as an enhancement.

For the muxer error "No output sample written in the last 3000 milliseconds.": we have a 'watchdog' timeout in case MediaCodec gets stuck during encoding to avoid blocking the transformation forever, and that is triggering because data wasn't processed by the pipeline for 3 seconds. This could be because of a live stream buffering for too long. We are tracking having a way to suppress this check when the upstream source is buffering ([internal: b/260601108]). In the mean time you can suppress this error by passing a custom `Muxer.Factory` to transformer where you pass `maxDelayBetweenSamplesMs = C.TIME_UNSET` when instantiating `DefaultMuxer.Factory`.

For the request to gracefully stop the transformation after a desired time, could you clarify whether the live stream you are supplying is ongoing or whether it ends? If it doesn't end, can you try supplying a clipping configuration on the input media item to transformer?

**Comment by dev-onetv** [comment]
Thank you very much for the information.

After passing a custom `Muxer.Factory` to transformer, I see that downloading from the HLS Live Stream continues without crash. Just for reference, I added the following line in the `createTransformer` method in `TransformerActivity` of demo app:
```
transformerBuilder.setMuxerFactory(new DefaultMuxer.Factory(C.TIME_UNSET));
```

The live steams that we are working with are ongoing and trimming duration is not known in advance in our use case. That is, as users watch the streams decide when to end the recording/download.

Looking at the code, it seems that to gracefully stop the recording, we need to call `onEnded()` method on `ComponentListener` object  of `Transformer` object. This method unfortunately is not being called if we call `transformer.cancel()`. The `Transformer` class is final and it is not clear to me how we can gracefully stop download at a desired time using precompiled library.

I would very much appreciate any suggestion on how to achieve this.

**Comment by dev-onetv** [comment]
@andrewlewis: I would be very grateful if you could share any progress on this issue.

**Comment by andrewlewis** [comment]
Apart from setting a clip end point when setting up Transformer, there isn't a way to end transformation before the source finishes currently, so similar to what I was saying above this isn't really officially supported.

I will try to suggest some ways of doing this with what we have now, but I haven't tried them and they may be fragile.
- I think when a transformation gets `Transformer.cancel()`ed we don't currently delete the output, so you could try canceling the transformation and seeing if the intermediate result output file looks okay for what you need.
- If that doesn't work, you could try injecting a custom muxer that delegates to the default muxer but also cleanly ends muxing based on the signal from the UI (and then ignores subsequent interaction from cancellation).
- As a more robust way of doing this if you depend on dev/main branch (rather than a release), you could inject a custom `AssetLoader` that wraps an `ExoPlayerAssetLoader` (I don't think these exist in the release version yet) but where you add in a method signaled from your UI where you end loading early. From the perspective of downstream components this looks like a stream that ends in the normal way so it is a relatively clean implementation.

**Comment by dev-onetv** [comment]
Thank you very much for the suggestions. 

- When using `Transformer.cancel()`, the output mp4 file is not properly written and it  has zero size.
- We tried injecting delegating muxer to the transformer, although this works and the output file in correctly written, we see crashes as the other resources are not released (we also tried calling `muxer.realse()` followed by `transformer.cancel()` but still crash was happening)
- Using AssetLoader seems like the best solution and we will try this solution soon from the dev branch.

Also, we are wondering if it would be possible to add `transformer.finish()` method to gracefully finish the transformation?

**Comment by dev-onetv** [comment]
Based on the latest code, if we want to use your third suggested solution, it appears that we need to inject a custom AssetLoader that wraps `DefaultAssetLoader`, which its factory is constructed as

```
DefaultAssetLoaderFactory defaultPlayerAssetLoaderFactory =
                new DefaultAssetLoaderFactory(context, new DefaultDecoderFactory(context, Clock.DEFAULT);
```

However, the problem is that `DefaultDecoderFactory` does not have public access. We would prefer not to customize the library (to make `DefaultDecoderFactory` public ourselves), so we can follow the updates.

We would be very grateful if you could kindly resolve this issue or if you could add `transformer.finish()` that would be ideal. Thanks again

**Comment by dev-onetv** [comment]
@andrewlewis: Using the latest code in the `dev-v2` branch, the MP4 file is now not empty anymore after calling the `transformer.cancle()` method. This resolves the issue for us, however you may want to look at the issue described in the previous comment.

As the issue is resolved for us, you can close this issue. Thank you  very much again for the support and all your efforts.
