### ISSUE TITLE
ServerSideAdInsertionMediaSource.SharedMediaPeriod sometimes crashes on seek.

### ISSUE THREAD

**Issue by zilinx** [google/ExoPlayer#10942]
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

Probably any device. I used Samsung Galaxy S10 (Android 12) and Google TV HD (Android 11) for development.

### Reproducible in the demo app?

Yes

### Reproduction steps

I have a multi-period DASH asset which maps the ad periods using `ServerSideAdInsertionMediaSource`.
1. start the stream
2. wait for the initial periods marked as ads to play
3. seek forward to hit the next ad break

The issue does not reproduce in 100% of cases, but hopping between start and a position after mid-rolls will eventually crash the player. 

### Expected result

The player doesn't crash. The active ad before the seek target is playing and once complete the content playback continues from the target seek position.

### Actual result

The player crashes with: 
```
playerFailed [eventTime=132.00, mediaPos=0.00, window=0, period=3, adGroup=0, ad=0, errorCode=ERROR_CODE_UNSPECIFIED
  com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:621)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loopOnce(Looper.java:226)
      at android.os.Looper.loop(Looper.java:313)
      at android.os.HandlerThread.run(HandlerThread.java:67)
  Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
      at com.google.android.exoplayer2.source.ads.ServerSideAdInsertionMediaSource$SharedMediaPeriod.onDownstreamFormatChanged(ServerSideAdInsertionMediaSource.java:910)
      at com.google.android.exoplayer2.source.ads.ServerSideAdInsertionMediaSource.onDownstreamFormatChanged(ServerSideAdInsertionMediaSource.java:535)
      at com.google.android.exoplayer2.source.MediaSourceEventListener$EventDispatcher.lambda$downstreamFormatChanged$5$com-google-android-exoplayer2-source-MediaSourceEventListener$EventDispatcher(MediaSourceEventListener.java:471)
      at com.google.android.exoplayer2.source.MediaSourceEventListener$EventDispatcher$$ExternalSyntheticLambda4.run(Unknown Source:6)
      at com.google.android.exoplayer2.util.Util.postOrRun(Util.java:604)
      at com.google.android.exoplayer2.source.MediaSourceEventListener$EventDispatcher.downstreamFormatChanged(MediaSourceEventListener.java:469)
      at com.google.android.exoplayer2.source.MediaSourceEventListener$EventDispatcher.downstreamFormatChanged(MediaSourceEventListener.java:454)
      at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.maybeNotifyPrimaryTrackFormatChanged(ChunkSampleStream.java:752)
      at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.maybeNotifyPrimaryTrackFormatChanged(ChunkSampleStream.java:744)
      at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.readData(ChunkSampleStream.java:390)
      at com.google.android.exoplayer2.source.ads.ServerSideAdInsertionMediaSource$SharedMediaPeriod.readData(ServerSideAdInsertionMediaSource.java:871)
      at com.google.android.exoplayer2.source.ads.ServerSideAdInsertionMediaSource$SampleStreamImpl.readData(ServerSideAdInsertionMediaSource.java:1230)
      at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:425)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:961)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:994)
      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:495)
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loopOnce(Looper.java:226) 
      at android.os.Looper.loop(Looper.java:313) 
      at android.os.HandlerThread.run(HandlerThread.java:67) 
```

The fix might be as simple as adding the condition to the if statement in `onDownstreamFormatChanged(
        MediaPeriodImpl, MediaLoadData)`, so that the operation doesn't execute if the length is invalid. Though this might be only healing the symptoms.  
```
if (streamIndex != C.INDEX_UNSET && mediaPeriod.hasNotifiedDownstreamFormatChange.length > streamIndex)
```

### Media

I will send a sample and a patch with my `ServerSideAdInsertionMediaSource` implementation by email. The samples are tagged for issue [10940](https://github.com/google/ExoPlayer/issues/10940)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
Thanks for reporting. I can repro this. We will look into this and evaluate.

**Comment by marcbaechinger** [comment]
Closing as this is fixed with [this commit](https://github.com/google/ExoPlayer/commit/f28a151acf136f6cef509b4a1e672e496aa43d6f).
