### ISSUE TITLE
After Proguard build my ExoPlayer stop playing videos 

### ISSUE THREAD

**Issue by Himanshu4003** [google/ExoPlayer#1097]
Here is my log cat after Apply Proguard it's stop working 

```Java
12-31 03:34:46.555 7109-7109/? E/LOG_TAG: Video Format Manifest LIst[]LIst Variants[com.google.android.exoplayer.hls.Variant@160e810]
12-31 03:34:46.561 7109-7109/? W/AudioCapabilities: Unsupported mime audio/x-ms-wma
12-31 03:34:46.565 7109-7109/? W/AudioCapabilities: Unsupported mime audio/vnd.rn-realaudio
12-31 03:34:46.569 7109-7109/? W/AudioCapabilities: Unsupported mime audio/mpeg-L2
12-31 03:34:46.573 7109-7109/? W/AudioCapabilities: Unsupported mime audio/ac3
12-31 03:34:46.574 7109-7109/? W/AudioCapabilities: Unsupported mime audio/x-ape
12-31 03:34:46.576 7109-7109/? W/AudioCapabilities: Unsupported mime audio/vnd.dts
12-31 03:34:46.576 7109-7109/? W/AudioCapabilities: Unsupported mime audio/x-pcm
12-31 03:34:46.577 7109-7109/? W/AudioCapabilities: Unsupported mime audio/ffmpeg
12-31 03:34:46.583 7109-7109/? W/VideoCapabilities: Unsupported mime video/mpeg2
12-31 03:34:46.585 7109-7109/? W/VideoCapabilities: Unsupported mime video/x-ms-wmv
12-31 03:34:46.588 7109-7109/? W/VideoCapabilities: Unsupported mime video/vnd.rn-realvideo
12-31 03:34:46.590 7109-7109/? W/VideoCapabilities: Unsupported mime video/vc1
12-31 03:34:46.592 7109-7109/? W/VideoCapabilities: Unsupported mime video/x-flv
12-31 03:34:46.592 7109-7109/? W/VideoCapabilities: Unsupported mime video/divx
12-31 03:34:46.595 7109-7109/? W/VideoCapabilities: Unsupported mime video/ffmpeg
12-31 03:34:46.607 7109-7109/? I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
12-31 03:34:46.609 7109-7109/? E/EventLogger: internalError [1.07, rendererInitError]
                                              java.lang.IllegalStateException: No variants selected.
                                                  at com.xxx.yy.player.HlsRendererBuilder$AsyncRendererBuilder.a(Unknown Source)
                                                  at com.google.android.exoplayer.util.ManifestFetcher$SingleFetchHelper.a(Unknown Source)
                                                  at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Unknown Source)
                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                  at android.os.Looper.loop(Looper.java:135)
                                                  at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
````
But without Proguard build it's working fine .

**Comment by ojw28** [comment]
What version of ExoPlayer are you using, and what's your Proguard configuration? Is it possible for you to reproduce the issue by applying your Proguard configuration to the ExoPlayer demo app, or not?

**Comment by Himanshu4003** [comment]
I am using Exo r1.5.3 as Gradle build .
''''java
java.lang.IllegalStateException: No variants selected.
1	at com.xx.yy player.HlsRendererBuilder$AsyncRendererBuilder.void onSingleManifest(com.google.android.exoplayer.hls.HlsPlaylist)(Unknown Source)
2 void onSingleManifest(java.lang.Object)
3	at com.xx.yy player.HlsRendererBuilder$AsyncRendererBuilder.void onSingleManifest(com.google.android.exoplayer.hls.HlsPlaylist)(Unknown Source)
4 void onSingleManifest(java.lang.Object)
5	at com.google.android.exoplayer.util.ManifestFetcher$SingleFetchHelper.void onLoadCompleted(com.google.android.exoplayer.upstream.Loader$Loadable)(Unknown Source)
6 void onLoadError(com.google.android.exoplayer.upstream.Loader$Loadable,java.io.IOException)
7	at com.google.android.exoplayer.upstream.Loader$LoadTask.void handleMessage(android.os.Message)(Unknown Source)
8	at android.os.Handler.dispatchMessage(Handler.java:102)
9	at android.os.Looper.loop(Looper.java:135)
10	at android.app.ActivityThread.main(ActivityThread.java:5254)
11	at java.lang.reflect.Method.invoke(Native Method)
12	at java.lang.reflect.Method.invoke(Method.java:372)
13	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
14	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
''''
It's seem to work fine with Real device Nexus 5 with Android 6.0.1 OS ,But i am getting above logs when i run same app on Genymotion Emulator with Android 5.1 and Same working fine with Genymotion Emulator 5.0 OS .

Do you have any idea why it's behave like this in my case ?

Here is my ProGuard :

```Java
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class * { *; }
-dontwarn javax.**
-dontwarn io.realm.**

-keepclasseswithmembers class * {
    @retrofit.http.* <methods>;
}


-dontwarn com.squareup.okhttp.**


-dontwarn rx.**


-dontwarn okio.**
-dontwarn com.digits.sdk.android.**

#Warning:com.fasterxml.jackson.databind.ext.DOMSerializer: can't find referenced class org.w3c.dom.bootstrap.DOMImplementationRegistry
-dontwarn com.fasterxml.jackson.databind.ext.**

#Warning:com.digits.sdk.android.DigitsAuthRequestQueue$1: can't find referenced method 'Result(java.lang.Object,retrofit.client.Response)' in program class com.twitter.sdk.android.core.Result

#Retrofit
-dontwarn retrofit.**
-keep class retrofit.** { *; }
-keepattributes Signature
-keepattributes Exceptions
-keepattributes *Annotation*
-keep class com.facebook.** {
   *;
}

-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**
-keep class com.splunk.** { *; }

-keep class com.fasterxml.jackson.databind.ObjectMapper {
    public <methods>;
    protected <methods>;
}
-keep class com.fasterxml.jackson.databind.ObjectWriter {
    public ** writeValueAsString(**);
}

-keepclassmembers class * implements android.os.Parcelable {
    static ** CREATOR;
}

-keep  class com.fasterxml.jackson.annotation.** {*;}
-keep  class com.fasterxml.jackson.core.** {*;}
-keep  class com.fasterxml.jackson.databind.** {*;}

-keepclassmembers public class * {
     @com.fasterxml.jackson.annotation.JsonCreator *;
}

-keep class com.xx.yy.model.** { *; }

-keep class com.xx.yy.player.**
-keepclassmembers class com.xx.yy.player.** {
    *;
 }

 # or more generally:
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
     **[] $VALUES;
     public *;
}

-keep class android.support.v7.widget.** { *; }
-keep interface android.support.v7.widget.** { *; }
-keep class android.support.v4.app.** { *; }
-keep interface android.support.v4.app.** { *; }


-assumenosideeffects class android.util.Log {
    public static boolean isLoggable(java.lang.String, int);
    public static int v(...);
    public static int i(...);
    public static int w(...);
    public static int d(...);
    public static int e(...);
}
#Warning:com.twitter.sdk.android.tweetui.BaseTweetView: can't find referenced class com.squareup.picasso.RequestCreator
#-keep com.twitter.sdk.android.tweetui.**
#retrofit_tb
-keep class retrofit_tb.** { *; }
-keepclasseswithmembers class * {
    @retrofit_tb.http.* <methods>;
}
-keep class com.twitter.sdk.android.core.** {*;}
```

**Comment by Himanshu4003** [comment]
I just verify Exo Player Demo working fine with Pro guard But Really issue happen when i put our hls url in Exo Player Demo it give below Error .

``` Java
01-05 05:04:21.655 5739-5739/? W/System.err: java.lang.IllegalStateException: No variants selected.
01-05 05:04:21.656 5739-5739/? W/System.err:     at com.google.android.exoplayer.demo.a.l.a(Unknown Source)
01-05 05:04:21.656 5739-5739/? W/System.err:     at com.google.android.exoplayer.j.q.a(Unknown Source)
01-05 05:04:21.656 5739-5739/? W/System.err:     at com.google.android.exoplayer.i.z.handleMessage(Unknown Source)
01-05 05:04:21.656 5739-5739/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-05 05:04:21.656 5739-5739/? W/System.err:     at android.os.Looper.loop(Looper.java:135)
01-05 05:04:21.656 5739-5739/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
01-05 05:04:21.656 5739-5739/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-05 05:04:21.656 5739-5739/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
01-05 05:04:21.656 5739-5739/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
01-05 05:04:21.656 5739-5739/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
01-05 05:04:21.688 5739-5757/? W/EGL_emulation: eglSurfaceAttrib not implemented
01-05 05:04:21.688 5739-5757/? W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xf3faeca0, error=EGL_SUCCESS
```` 
It's seem to fail only in Genymotion Emulator with Version 5.1 OS but working fine in Nexus 5 with M 6.0.1 OS .

**Comment by ojw28** [comment]
Are you sure the same thing doesn't happen when using your HLS URL on the Genymotion Emulator *without* proguard too? We've had quite a few issues that occur only on Genymotion Emulator and not on real devices; from which I conclude it doesn't do the best job of emulating when it comes to media.

**Comment by Himanshu4003** [comment]
No , It's happen without proguard as well . Also it only happen with Genymotion Emulator with Andorid 5.1  OS while it's working fine with Proguard and without Pro Guard on Genymotion Rmulator Andorid 5.0 . So it seem like it's issue with some specific Genymotion andorid version emulator .

**Comment by ojw28** [comment]
Most likely the Genymotion simulator just claim that it cannot support any of the variants available in the HLS playlist. You'd have to report the issue to Genymotion.

**Comment by faridfor** [comment]
I have this problem with Huawei P8 lite!
Hls works fine without proguard, but when i set minifyEnabled to true it cant play HLS links.
I've added these lines to my proguard file:

```
 -keepclasseswithmembernames,includedescriptorclasses class* {
     native <methods>;
 }
 -keep class com.google.android.exoplayer.** {*;}
``` 
everything works good on other phones.
here is the log:
`03-09 18:41:05.850 5828-5913/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                        com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
                                                                                            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(Unknown Source)
                                                                                            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(Unknown Source)
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(Unknown Source)
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(Unknown Source)
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(Unknown Source)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(Unknown Source)
                                                                                         Caused by: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
                                                                                            at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(Unknown Source)
                                                                                            at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(Unknown Source)
                                                                                            at com.google.android.exoplayer.MediaCodecUtil.maxH264DecodableFrameSize(Unknown Source)
                                                                                            at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.selectVideoFormats(Unknown Source)
                                                                                            at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.selectVideoFormatsForDefaultDisplay(Unknown Source)
                                                                                            at com.google.android.exoplayer.hls.DefaultHlsTrackSelector.selectTracks(Unknown Source)
                                                                                            at com.google.android.exoplayer.hls.HlsChunkSource.prepare(Unknown Source)
                                                                                            at com.google.android.exoplayer.hls.HlsSampleSource.prepare(Unknown Source)
                                                                                            at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(Unknown Source)
                                                                                            at com.google.android.exoplayer.TrackRenderer.prepare(Unknown Source)
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(Unknown Source) 
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(Unknown Source) 
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(Unknown Source) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                            at android.os.Looper.loop(Looper.java:135) 
                                                                                            at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(Unknown Source) 
                                                                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                                            at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:2150)
                                                                                            at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfoInternal(Unknown Source)
                                                                                            at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(Unknown Source) 
                                                                                            at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(Unknown Source) 
                                                                                            at com.google.android.exoplayer.MediaCodecUtil.maxH264DecodableFrameSize(Unknown Source) 
                                                                                            at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.selectVideoFormats(Unknown Source) 
                                                                                            at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.selectVideoFormatsForDefaultDisplay(Unknown Source) 
                                                                                            at com.google.android.exoplayer.hls.DefaultHlsTrackSelector.selectTracks(Unknown Source) 
                                                                                            at com.google.android.exoplayer.hls.HlsChunkSource.prepare(Unknown Source) 
                                                                                            at com.google.android.exoplayer.hls.HlsSampleSource.prepare(Unknown Source) 
                                                                                            at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(Unknown Source) 
                                                                                            at com.google.android.exoplayer.TrackRenderer.prepare(Unknown Source) 
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(Unknown Source) 
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(Unknown Source) 
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(Unknown Source) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                            at android.os.Looper.loop(Looper.java:135) 
                                                                                            at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(Unknown Source) 
`
