### ISSUE TITLE
NPE on handlePlayerStateChanged

### ISSUE THREAD

**Issue by FadillahMozhaiq** [google/ExoPlayer#10988]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

- Google TV
- Xiaomi  Mi TV
- Sharp TV
- TCL
- Changhong
- Etc

### Reproducible in the demo app?

Not tested

### Reproduction steps

Unknown

### Expected result

The media play successfully

### Actual result

```
> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:154)
       at com.google.android.exoplayer2.ext.ima.AdTagLoader.updateAdProgress(AdTagLoader.java:688)
       at com.google.android.exoplayer2.ext.ima.AdTagLoader.handlePlayerStateChanged(AdTagLoader.java:814)
       at com.google.android.exoplayer2.ext.ima.AdTagLoader.onPlaybackStateChanged(AdTagLoader.java:495)
       at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$22(ExoPlayerImpl.java:1916)
       at com.google.android.exoplayer2.ExoPlayerImpl$$InternalSyntheticLambda$1$b132fcb325c34ac563536ede08c2aa5e54dc24d459a99c4a20673c9aa7c8f376$10.invoke$bridge(ExoPlayerImpl.java:21)
       at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:281)
       at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
       at com.google.android.exoplayer2.util.ListenerSet$$InternalSyntheticLambda$2$84623593c2a26340561ccf78330ea2f1ed5a5ffef54877eb1edb03aa4d882c21$0.run(ListenerSet.java:23)
       at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
       at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1947)
       at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1774)
       at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1(ExoPlayerImpl.java:306)
       at com.google.android.exoplayer2.ExoPlayerImpl.$r8$lambda$nOBJYkeEQ2uz3sBKLToLWmzrgZk(ExoPlayerImpl.java:216)
       at com.google.android.exoplayer2.ExoPlayerImpl$$InternalSyntheticLambda$2$87dd1a18cfb37560c5082e49219a5ca1cfe58b4494399f2c707a90a0afa53990$0.run(ExoPlayerImpl.java:4)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
```
> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:154)
       at com.google.android.exoplayer2.ext.ima.AdTagLoader.handlePlayerStateChanged(AdTagLoader.java:807)
       at com.google.android.exoplayer2.ext.ima.AdTagLoader.onPlaybackStateChanged(AdTagLoader.java:495)
       at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$22(ExoPlayerImpl.java:1916)
       at com.google.android.exoplayer2.ExoPlayerImpl$$InternalSyntheticLambda$1$b132fcb325c34ac563536ede08c2aa5e54dc24d459a99c4a20673c9aa7c8f376$10.invoke$bridge(ExoPlayerImpl.java:21)
       at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:281)
       at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
       at com.google.android.exoplayer2.util.ListenerSet$$InternalSyntheticLambda$2$84623593c2a26340561ccf78330ea2f1ed5a5ffef54877eb1edb03aa4d882c21$0.run(ListenerSet.java:23)
       at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
       at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1947)
       at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1774)
       at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1(ExoPlayerImpl.java:306)
       at com.google.android.exoplayer2.ExoPlayerImpl.$r8$lambda$nOBJYkeEQ2uz3sBKLToLWmzrgZk(ExoPlayerImpl.java:216)
       at com.google.android.exoplayer2.ExoPlayerImpl$$InternalSyntheticLambda$2$87dd1a18cfb37560c5082e49219a5ca1cfe58b4494399f2c707a90a0afa53990$0.run(ExoPlayerImpl.java:4)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
### Media

Unknown

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by FadillahMozhaiq** [comment]
Maybe related with this issue #8290

**Comment by tonihei** [comment]
This looks impossible in the 2.17.1 code. Both stack traces originate in this `if`-block: [if (playingAd && imaAdState == IMA_AD_STATE_PLAYING)](https://github.com/google/ExoPlayer/blob/8129675b065bc98330ec775fb7a538c139793070/extensions/ima/src/main/java/com/google/android/exoplayer2/ext/ima/AdTagLoader.java#L804) in `AdTagLoader`, and the only places that set `imaAdState` to `IMA_AD_STATE_PLAYING` guarantee a non-null value of `imaAdMediaInfo` (the variable that is apparently null in your stack traces).

Do you have any background information on these crashes? Can you reproduce yourself for example? Or do you integrate with the IMA extension in a way which is different from https://exoplayer.dev/ad-insertion.html?

**Comment by FadillahMozhaiq** [comment]
We can't reproduce the issue and we have already integrate with the IMA extension follow [this](https://exoplayer.dev/ad-insertion.html) guideline

**Comment by tonihei** [comment]
In case you can obtain bugreports for the problem, it would also be helpful to see IMA debug logs, which can be enabled with `ImaAdsLoader.setDebugModeEnabled(true)`. Without any reproduction or detailed logs, I don't see a good way to debug this right now.
