### ISSUE TITLE
Unable to bind a sample queue to TrackGroup with mime type video/avc

### ISSUE THREAD

**Issue by thomas-coldwell** [google/ExoPlayer#10998]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

OnePlus 6

### Reproducible in the demo app?

No

### Reproduction steps

Hi I'm trying to configure a single ExoPlayer instance so that I can give it multiple HLS streams that are all in-sync and renderer out to separate Surfaces. I've followed the steps mentioned in [#2855](https://github.com/google/ExoPlayer/issues/2855) to configure this:
- Inject a custom `RenderersFactory` that creates a video renderer and an audio renderer for each of the sources. For the audio renderers I return null for the `getMediaClock` except for the first so the player has a single clock for playback
- Merge all of the sources using `MergingMediaSource()` to create a single source that can be passed to the player
- Inject a custom `TrackSelector` that then wires up each video and audio track to a corresponding renderer selection
- Send a message to each of the video renderers with a payload of the target surface each video should be rendered into

This works great with **different** HLS streams and I get a fully synchronised pair of videos. However, if I then use the same HLS stream for the two media sources I get the following error after preparing the player (before commencing playback):
```
2023-02-17 17:05:57.878  6034-21398 ExoPlayerImplInternal Playback error
com.google.android.exoplayer2.ExoPlaybackException: Source error
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:608)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:233)
    at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.source.hls.SampleQueueMappingException: Unable to bind a sample queue to TrackGroup with mime type video/avc.
    at com.google.android.exoplayer2.source.hls.HlsSampleStream.maybeThrowError(HlsSampleStream.java:62)
    at com.google.android.exoplayer2.BaseRenderer.maybeThrowStreamError(BaseRenderer.java:156)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1002)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:233) 
    at android.os.HandlerThread.run(HandlerThread.java:67) 
```
I've checked the stack trace here and it seems to trying to bind the same sample queue multiple times to different the 2 different video track groups.

### Expected result

Expected behaviour is the same as if I was using two different HLS streams - it should bind each of these to a separate sample queue and finish preparing without this exception

### Actual result

Actual result is documented in reproduction steps ⬆️

### Media

N/A

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by thomas-coldwell** [comment]
Also after searching around various issues this seemed like it could be relevant - maybe ExoPlayer is assigning the same ID somehow? But I'm not sure I fully understand the internal track selection logic here https://github.com/google/ExoPlayer/issues/10930#issuecomment-1413974276

**Comment by thomas-coldwell** [comment]
Nevermind, upgrading to 2.18.3 resolved this!
