### ISSUE TITLE
DefaultDrmSessionManager: null exception fetching crypto type

### ISSUE THREAD

**Issue by sixones** [google/ExoPlayer#11008]
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

- Fire TV devices (AFTMM, AFTSSS, AFTSS).
- Chromecast Google TV.
- Samsung Galaxy TAB A7 / Samsung Galaxy S20 / Samsung Galaxy S10+.
- Most common in Android 7, 9 and 5, occurs in all versions but a lot less common.

### Reproducible in the demo app?

No

### Reproduction steps

Unsure how to reproduce, it's being picked up by our crash reporting system.

### Expected result

Media plays successfully without any issues.

### Actual result

Playback crashes with a null exception;

```stacktrace
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:154)
       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.getCryptoType(DefaultDrmSessionManager.java:599)
       at com.google.android.exoplayer2.source.dash.DashMediaPeriod.buildPrimaryAndEmbeddedTrackGroupInfos(DashMediaPeriod.java:675)
       at com.google.android.exoplayer2.source.dash.DashMediaPeriod.buildTrackGroups(DashMediaPeriod.java:518)
       at com.google.android.exoplayer2.source.dash.DashMediaPeriod.<init>(DashMediaPeriod.java:153)
       at com.google.android.exoplayer2.source.dash.DashMediaSource.createPeriod(DashMediaSource.java:490)
```

### Media

It's a DASH stream with Widevine encryption, it's not restricted to a single stream though so I'm not sure it's applicable. 

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
This is occuring because `exoMediaDrm` is `null` here:
https://github.com/google/ExoPlayer/blob/a9444c880230d2c2c79097e89259ce0b9f80b87d/library/core/src/main/java/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.java#L599

This can only happen if the `DefaultDrmSessionManager` instance either hasn't been prepared (via `prepare()` method) before the call to `getCryptoType()`, or it has been already released (i.e. `release()` has been called as many times as `prepare()`).

How are you configuring DRM for your playback? Are you just using fields on `MediaItem` or are you also instantiating a `DefaultDrmSessionManager` manually anywhere?

Are you able to reliably reproduce the problem every time?

> It's a DASH stream with Widevine encryption, it's not restricted to a single stream though so I'm not sure it's applicable.

It doesn't happen for DASH + widevine playback for me in the demo app, so there is something different about your setup.

**Comment by sixones** [comment]
> Are you able to reliably reproduce the problem every time?

As I said I cannot reproduce and it only happens randomly, it's not seen by every user so it seems like a race condition inside ExoPlayer.

> How are you configuring DRM for your playback? Are you just using fields on MediaItem or are you also instantiating a DefaultDrmSessionManager manually anywhere?

We create a `DefaultDrmSessionManager` and then pass that to `DashMediaSource.Factory`, the `DashMediaSource` then calls `prepare` and `release` for us. We don't call `DefaultDrmSessionManager#prepare` ourselves.

**Comment by icbaker** [comment]
OK thanks for the extra info, I agree this sounds like a race condition somewhere - but I can't really see where.

I added some logging to the demo app to check what thread the `DefaultDrmSessionManager.prepare()`, `getCryptoType()` and `release()` methods are called on, and it was the playback thread in all cases. Given that, I can't really see how there would be a race here.

I tried to customise the demo app to match what you describe here:

> We create a `DefaultDrmSessionManager` and then pass that to `DashMediaSource.Factory`, the `DashMediaSource` then calls `prepare` and `release` for us. We don't call `DefaultDrmSessionManager#prepare` ourselves.

I ended up with this inside `PlayerActivity.createMediaSourceFactory` (I had to plumb the `MediaItem.DrmConfiguration` in). I then played the `Widevine DASH (MP4, H264) -> HD (cenc)` sample. Does this look like roughly what you're doing? If you're able to dump the equivalent config code from your project it might help me spot something that's a bit different.

```java
DefaultDrmSessionManager defaultDrmSessionManager =
    new DefaultDrmSessionManager.Builder()
        .build(
            new HttpMediaDrmCallback(
                drmConfiguration.licenseUri.toString(),
                DemoUtil.getHttpDataSourceFactory(/* context= */ this)));
return new DashMediaSource.Factory(dataSourceFactory)
    .setDrmSessionManagerProvider(mediaItem -> defaultDrmSessionManager);
```

---

One thought I had: Are you using a single `DefaultDrmSessionManager` instance between two different `ExoPlayer` instances? In that case the playback threads would be different, which could possibly cause issues.

**Comment by sixones** [comment]
> One thought I had: Are you using a single DefaultDrmSessionManager instance between two different ExoPlayer instances? In that case the playback threads would be different, which could possibly cause issues.

We always use one instance of the DrmSessionManager, and one instance of ExoPlayer. 

> Does this look like roughly what you're doing?

It's similar, though we build the DRM session like this; 
```
new DefaultDrmSessionManager.Builder()
        .setUuidAndExoMediaDrmProvider(C.WIDEVINE_UUID, FrameworkMediaDrm.DEFAULT_PROVIDER)
        .build(new DrmCallback(dataSourceFactory, callback));
```

The `DrmCallback` is a `MediaDrmCallback` where we have some custom code to calculate the license URL (only inside of `getDrmCallback`), which then return's a `HttpMediaDrmCallback`. 

Unsure if this would be of any help, but the stacktrace starts at `com.google.android.exoplayer2.source.ads.AdsMediaSource.maybeUpdateSourceInfo (AdsMediaSource.java:339)`, which then goes onto `refreshSourceInfo`. 

It is very odd, no matter what I try I can't reproduce even on an Amazon device where the crash is most popular. Do you have any suggestions on places I could add logs to see if I can get more information into Crashlytics?

**Comment by icbaker** [comment]
> Unsure if this would be of any help, but the stacktrace starts at `com.google.android.exoplayer2.source.ads.AdsMediaSource.maybeUpdateSourceInfo (AdsMediaSource.java:339)`, which then goes onto `refreshSourceInfo`.

Ah this is an interesting hint. Couple of questions:
* Are you using `DefaultMediaSourceFactory` in order to get local ad insertion support, or are you setting up `AdsMediaSource` more manually? If so, what does that manual setup look like?
* Are you using `ExoPlayer.Builder.setLooper` or `ExoPlayer.Builder.setPlaybackLooper` when building your player?

> Do you have any suggestions on places I could add logs to see if I can get more information into Crashlytics?

`DefaultDrmSessionManager.exoMediaDrm` only gets nulled out here:
https://github.com/google/ExoPlayer/blob/bc3537260b1df38b30100e67ac5e1ac592fb5f26/library/core/src/main/java/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.java#L806-L813

This is only called from two places: `release()` and `ReferenceCountListenerImpl.onReferenceCountDecremented()`. In both cases the `exoMediaDrm = null` line is only hit if `DefaultDrmSessionManager.prepareCallsCount == 0` (which should never happen until the final `release()` call). If you're [depending on ExoPlayer locally](https://github.com/google/ExoPlayer/blob/release-v2/README.md#locally) you could try adding logging for a couple of 'should never happen' cases:
* Whenever a `DefaultDrmSessionManager` method (except `prepare()`) is called with `prepareCallsCount <= 0`.
* Whenever `DefaultDrmSessionManager.maybeReleaseExoMediaDrm` or `DefaultDrmSessionManager.getCryptoType` are called on a thread that isn't the playback thread (you can check this programmatically by comparing to the thread backing `DefaultDrmSessionManager.playbackLooper`).

If you find either of these cases then it would be interesting to look at the stack trace to see where the problematic call is coming from. I'm unable to explain this problem unless there's multiple threads somehow involved...

**Comment by sixones** [comment]
> Are you using DefaultMediaSourceFactory in order to get local ad insertion support, or are you setting up AdsMediaSource more manually? If so, what does that manual setup look like?

We have our own setup for the `MediaSourceFactory`, that looks like this;

```java
public class AdsMediaSourceFactory implements MediaSourceFactory
{
  private final DataSource.Factory m_dataSourceFactory;
  private DrmSessionManagerProvider m_drmSessionManagerProvider;
  @Nullable private LoadErrorHandlingPolicy m_loadErrorHandlingPolicy;

  public AdsMediaSourceFactory(DataSource.Factory factory)
  {
    m_dataSourceFactory = factory;
  }

  @Override
  public MediaSourceFactory setDrmSessionManagerProvider(@Nullable DrmSessionManagerProvider drmSessionManagerProvider)
  {
    if (drmSessionManagerProvider != null)
      m_drmSessionManagerProvider = drmSessionManagerProvider;
    else
      m_drmSessionManagerProvider = new DefaultDrmSessionManagerProvider();

    return this;
  }

  @Override
  public MediaSourceFactory setLoadErrorHandlingPolicy(@Nullable LoadErrorHandlingPolicy loadErrorHandlingPolicy)
  {
    m_loadErrorHandlingPolicy = loadErrorHandlingPolicy;
    return this;
  }

  @Override @NonNull
  public MediaSource createMediaSource(MediaItem mediaItem)
  {
    Assertions.checkNotNull(mediaItem.playbackProperties);
    @C.ContentType
    int type = Util.inferContentTypeForUriAndMimeType(
        mediaItem.playbackProperties.uri, mediaItem.playbackProperties.mimeType);

    @Nullable MediaSourceFactory mediaSourceFactory = null;

    switch (type)
    {
      case C.TYPE_HLS:
        mediaSourceFactory = new HlsMediaSource.Factory(m_dataSourceFactory);
        break;
      case C.TYPE_DASH:
        mediaSourceFactory = new DashMediaSource.Factory(m_dataSourceFactory);
        break;
      case C.TYPE_OTHER:
        mediaSourceFactory = new ProgressiveMediaSource.Factory(m_dataSourceFactory);
        break;
      case C.TYPE_RTSP:
      case C.TYPE_SS:
      default:
        break;
    }

    if (mediaSourceFactory == null)
      throw new IllegalStateException("Unsupported type: " + type);

    if (m_loadErrorHandlingPolicy == null)
      m_loadErrorHandlingPolicy = new DefaultLoadErrorHandlingPolicy();

    return mediaSourceFactory
        .setDrmSessionManagerProvider(m_drmSessionManagerProvider)
        .setLoadErrorHandlingPolicy(m_loadErrorHandlingPolicy)
        .createMediaSource(mediaItem);
  }

  @Override @NonNull
  public int[] getSupportedTypes()
  {
    return new int[] { C.TYPE_HLS, C.TYPE_DASH, C.TYPE_OTHER };
  }
}
```

At some point we had more custom code so this was needed, but checking now I think we could switch to using `DefaultMediaSourceFactory` and remove our custom `AdsMediaSourceFactory` from our code base. 

We are using ExoPlayer locally, so I can see if we can add some logging - unless you think the problem is likely due to our custom `AdsMediaSourceFactory` above, in which case I will revert us to using `DefaultMediaSourceFactory` first and see if that solves the problem. 

> Are you using ExoPlayer.Builder.setLooper or ExoPlayer.Builder.setPlaybackLooper when building your player?

We use `ExoPlayer.Builder.setLooper` and put ExoPlayer on a background thread (with it's own looper).  Looking back at when the crash started, it might of been originated when we moved ExoPlayer off the main thread - though our Crashlytics instance had some problems which meant it's not 100% clear if this was the case.

**Comment by icbaker** [comment]
> > Are you using ExoPlayer.Builder.setLooper or ExoPlayer.Builder.setPlaybackLooper when building your player?
> 
> We use `ExoPlayer.Builder.setLooper` and put ExoPlayer on a background thread (with it's own looper). Looking back at when the crash started, it might of been originated when we moved ExoPlayer off the main thread - though our Crashlytics instance had some problems which meant it's not 100% clear if this was the case.

You cannot use a background thread if you are using ExoPlayer's IMA extension (not sure if you are): 
> Note that the IMA module only supports players that are accessed on the application's main thread.

https://github.com/google/ExoPlayer/tree/release-v2/extensions/ima#using-the-module

I suspect (unproven) that this is resulting in `DefaultDrmSessionManager` being accessed by more than one thread, resulting in the racy behaviour you're seeing.

**Comment by sixones** [comment]
> You cannot use a background thread if you are using ExoPlayer's IMA extension (not sure if you are):

We are not using IMA anymore due to the advert freezing bug, we have our own VAST implementation. 

> I suspect (unproven) that this is resulting in DefaultDrmSessionManager being accessed by more than one thread, resulting in the racy behaviour you're seeing.

From what I can tell, everything is always using the background thread that we specify rather than a random or main thread.

**Comment by icbaker** [comment]
I've added some additional logging to expose if `DefaultDrmSessionManager` is accessed on the wrong thread - some of this is included in 2.18.6 (though there were some false positives: https://github.com/androidx/media/issues/350). I wonder if you can tweak whatever crash/log analytics tools you're using to detect if these warnings are logged during the same playback you see `mediaDrm == null`?
