### ISSUE TITLE
Video 4096 *2160 is not Playing.

### ISSUE THREAD

**Issue by Manli123** [google/ExoPlayer#11015]
### ExoPlayer Version

2.18.3

### Devices that reproduce the issue

Android 8.1 vivo 1811
Android 11
Android 7.1.2 redmi  Y1

### Devices that do not reproduce the issue

Redmi 9 11 RP1A200720.011 MIUI Global 12.5.6

### Reproducible in the demo app?

Yes

### Reproduction steps

--------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------
Code:

   public void initilisePlayer()
    {
        DefaultRenderersFactory rf = new DefaultRenderersFactory(MainActivity.this)
                .setExtensionRendererMode(EXTENSION_RENDERER_MODE_PREFER).setMediaCodecSelector(
                        new MediaCodecSelector() {
                            @Override
                            public List<MediaCodecInfo> getDecoderInfos(String mimeType,
                                                                        boolean requiresSecureDecoder, boolean requiresTunnelingDecoder)
                                    throws MediaCodecUtil.DecoderQueryException {
                                List<MediaCodecInfo> decoderInfos = MediaCodecSelector.DEFAULT
                                        .getDecoderInfos(mimeType, requiresSecureDecoder, requiresTunnelingDecoder);
                                if (MimeTypes.VIDEO_H264.equals(mimeType)) {
                                    // copy the list because MediaCodecSelector.DEFAULT returns an unmodifiable list
                                    decoderInfos = new ArrayList<>(decoderInfos);
                                    Collections.reverse(decoderInfos);
                                }
                                return decoderInfos;
                            }
                        });

        // url of video which we are loading.
//      
       
     
        //sorry i can not share url.
//     

        DefaultLoadControl loadControl = new DefaultLoadControl
                .Builder()
                .setBufferDurationsMs(32*1024, 64*1024, 1024, 1024)
                .createDefaultLoadControl();

//        DataSource.Factory cacheDataSourceFactory =
//                new CacheDataSource.Factory()
//                        .setCache(com.axat.starbarn.model.SimpleMediaPlayer.getInstance(MainActivity.this))
//                        .setUpstreamDataSourceFactory(new DefaultHttpDataSource.Factory()
//                                .setUserAgent(MainActivity.this.getString(R.string.app_name)));

        exoPlayer = new ExoPlayer.Builder(MainActivity.this,rf).setLoadControl(loadControl).build();

//

        exoPlayer.addListener(new Player.Listener() {
            @Override
            public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                Player.Listener.super.onPlayerStateChanged(playWhenReady, playbackState);

            }

            @Override
            public void onMediaMetadataChanged(MediaMetadata mediaMetadata) {
                Player.Listener.super.onMediaMetadataChanged(mediaMetadata);
            }

            @Override
            public void onPlayerError(PlaybackException error) {
                Player.Listener.super.onPlayerError(error);
                Log.e("play_error",""+error.getMessage().toString()+""+error.errorCode);
//                    Toast.makeText(context, "Can't play this video", Toast.LENGTH_SHORT).show();
            }
        });

//
        exoPlayerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_ZOOM);
        exoPlayerView.setShutterBackgroundColor(Color.TRANSPARENT);
        exoPlayerView.setKeepContentOnPlayerReset(true);
        exoPlayer.seekTo(0);
        exoPlayer.setRepeatMode(Player.REPEAT_MODE_ONE);

        MediaSource mediaSource = new ProgressiveMediaSource.Factory(
                new CacheDataSource.Factory()
                        .setCache(com.axat.starbarn.model.SimpleMediaPlayer.getInstance(MainActivity.this))
                        .setUpstreamDataSourceFactory(new DefaultHttpDataSource.Factory()
                                .setUserAgent(MainActivity.this.getString(R.string.app_name)))
                        .setFlags(CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)
        ).createMediaSource(MediaItem.fromUri(videoURL));

        exoPlayer.setMediaSource(mediaSource,true);
        exoPlayerView.setPlayer(exoPlayer);
        exoPlayer.setPlayWhenReady(true);
        exoPlayer.prepare();
        exoPlayer.play();
    }

--------------
 private void releasePlayer() {
        exoPlayer.setPlayWhenReady(false);
        exoPlayer.stop();

        exoPlayer.release();
        exoPlayerView.clearAnimation();
        exoPlayerView.getPlayer().clearVideoSurface();
        exoPlayer=null;
        exoPlayerView.setPlayer(null);
    }
--------------------
 @Override
    protected void onResume() {
//        if (Build.VERSION.SDK_INT <= 23 || exoPlayer == null) {
//
//            Log.e("method","resume");
//
//            initilisePlayer();
//            if (exoPlayerView != null) {
//                exoPlayerView.onResume();
//            }
//        }
        initilisePlayer();
        super.onResume();
    }

    @Override
    protected void onPause() {

//        if (Build.VERSION.SDK_INT <= 23) {
//            Log.e("method","pause");
//            if (exoPlayerView != null) {
//                exoPlayerView.onPause();
//            }
//
//        }
        releasePlayer();
        super.onPause();
    }

### Expected result

Video play on all devices.

### Actual result

```
E/MediaCodecVideoRenderer: Video codec error
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2632)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:106)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1838)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1001)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:192)
        at android.os.HandlerThread.run(HandlerThread.java:65)
E/pos: 2
D/MediaCodecInfo: NoSupport [sizeAndRate.support, 4096x2160@25.0] [OMX.google.h264.decoder, video/avc] [1811, vivo 1811, vivo, 27]
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.640033, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [1811, vivo 1811, vivo, 27]
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640033, -1, null, [4096, 2160, 25.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:192)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.google.h264.decoder
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1629)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1001)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2632)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:106)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1838)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1001) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
I/MediaCodec: flush
E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2114)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:166)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:877)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:870)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:710)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:608)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:186)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1664)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1405)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1366)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:594)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:192)
        at android.os.HandlerThread.run(HandlerThread.java:65)
I/MediaCodec: release
I/MediaCodec: kWhatStop or kWhatRelease
I/ACodec: initiateShutdown kWhatReleaseCodecInstance
E/pos: 2
I/MediaCodec: ~MediaCodec
E/play_error: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640033, -1, null, [4096, 2160, 25.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES4003
E/pos: 2
```

### Media
https://thegoatappvideos.s3.us-east-2.amazonaws.com/post_video/productio.mp4

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
I think the device can not play this video.

```
E/play_error: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640033, -1, null, 
[4096, 2160, 25.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES4003
```

**Comment by Manli123** [comment]
okay Thank You

**Comment by mhbdev** [comment]
> I think the device can not play this video.
> 
> ```
> E/play_error: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640033, -1, null, 
> [4096, 2160, 25.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES4003
> ```

I checked it on a specific samsung device and the thing is codec is not really supported by the device itself cause videos with avc1.640033 encoding could not be played on the phones default video player but MX Player is supporting the video

**Comment by marcbaechinger** [comment]
I'm closing this as the given video exceeds the capabilities of the device as answered above.

**Comment by mhbdev** [comment]
> I'm closing this as the given video exceeds the capabilities of the device as answered above.

Yesterday, I have tried to open the same video with MxPlayer on Android, And I don't know how but the player can handle playing that kind of videos without considering device capalities.
