### ISSUE TITLE
Exoplayer - DRM contents(Mpeg Dash) issue

### ISSUE THREAD

**Issue by markshim1** [google/ExoPlayer#11049]
**ExoPlayer Version**
2.18.1

**Devices that reproduce the issue**
Recent Android devices

**Devices that do not reproduce the issue**
No response

**Reproducible in the demo app?**
No

**Reproduction steps**
Play DRM contents (multi period Dash)

**Expected result**
Media plays successfully without any issues.

**Actual result**
IllegalArgumentException

Some DRM(widevine) contents are not playing.
According to your docs, 
<img width="897" alt="image" src="https://user-images.githubusercontent.com/7144761/224139475-80edd265-36d1-4a88-a4a9-e83b676d254a.png">
**DefaultMediaSourceFactory** does not support sideloading subtitles for multi-period DASH.

Then is it way to resolve this issue?
Followings are drm contents I'm testing with.

- ExoPlayer version : 2.18.1

- Contents DRM Contents (WideVine)
- source url: `https://hls.ondemandkorea.com/kcp-content-ingest/processing/EP00013-The-Penthouse-2-70762578-2023-01-12-08-43-14.mp4/WideVine/bumper/kcp_master_1080p.mpd`
- drmtoday url : `https://lic.drmtoday.com/license-proxy-widevine/cenc/`
- merchant: `odkmedia`
- assetId : `662e4bd1c8f0c6c71d7c32819d806427af1cf08eb1eea1bb3c0dc3afe010eba1`
- variantId : `staging`
- userId : `7e2f9a23-e1b9-46c0-b804-d7d9760c3887`
- session id : `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX25hbWUiOiJvZGsiLCJlcGlzb2RlX2lkIjo4NDE1MjMsImVuY3J5cHRpb25faWQiOiI2NjJlNGJkMWM4ZjBjNmM3MWQ3YzMyODE5ZDgwNjQyN2FmMWNmMDhlYjFlZWExYmIzYzBkYzNhZmUwMTBlYmExIiwiZHJtX3Nlc3Npb24iOiI3ZTJmOWEyMy1lMWI5LTQ2YzAtYjgwNC1kN2Q5NzYwYzM4ODcifQ.AkvF7zP3TP35GhDNEZZstu11yJqliY_FQvvGSSMcu-Q`

**Error Message**
`11:54:02.259 LoadTask                 E  Unexpected exception handling load completed
                                           java.lang.IllegalArgumentException
                                               at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
                                               at com.google.android.exoplayer2.source.ads.AdsMediaSource.onChildSourceInfoRefreshed(AdsMediaSource.java:266)
                                               at com.google.android.exoplayer2.source.ads.AdsMediaSource.onChildSourceInfoRefreshed(AdsMediaSource.java:61)
                                               at com.google.android.exoplayer2.source.CompositeMediaSource.lambda$prepareChildSource$0$com-google-android-exoplayer2-source-CompositeMediaSource(CompositeMediaSource.java:115)
                                               at com.google.android.exoplayer2.source.CompositeMediaSource$$ExternalSyntheticLambda0.onSourceInfoRefreshed(Unknown Source:4)
                                               at com.google.android.exoplayer2.source.BaseMediaSource.refreshSourceInfo(BaseMediaSource.java:88)
                                               at com.google.android.exoplayer2.source.dash.DashMediaSource.processManifest(DashMediaSource.java:847)
                                               at com.google.android.exoplayer2.source.dash.DashMediaSource.onManifestLoadCompleted(DashMediaSource.java:624)
                                               at com.google.android.exoplayer2.source.dash.DashMediaSource$ManifestCallback.onLoadCompleted(DashMediaSource.java:1302)
                                               at com.google.android.exoplayer2.source.dash.DashMediaSource$ManifestCallback.onLoadCompleted(DashMediaSource.java:1297)
                                               at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:478)
                                               at android.os.Handler.dispatchMessage(Handler.java:106)
                                               at android.os.Looper.loopOnce(Looper.java:226)
                                               at android.os.Looper.loop(Looper.java:313)
                                               at android.os.HandlerThread.run(HandlerThread.java:67)
11:54:02.263 ExoPlayerImplInternal    E  Playback error
                                           com.google.android.exoplayer2.ExoPlaybackException: Source error
                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:608)
                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                               at android.os.Looper.loopOnce(Looper.java:226)
                                               at android.os.Looper.loop(Looper.java:313)
                                               at android.os.HandlerThread.run(HandlerThread.java:67)
                                           Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                                               at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:482)
                                               at android.os.Handler.dispatchMessage(Handler.java:106)
                                               at android.os.Looper.loopOnce(Looper.java:226) 
                                               at android.os.Looper.loop(Looper.java:313) 
                                               at android.os.HandlerThread.run(HandlerThread.java:67) 
                                           Caused by: java.lang.IllegalArgumentException
                                               at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
                                               at com.google.android.exoplayer2.source.ads.AdsMediaSource.onChildSourceInfoRefreshed(AdsMediaSource.java:266)
                                               at com.google.android.exoplayer2.source.ads.AdsMediaSource.onChildSourceInfoRefreshed(AdsMediaSource.java:61)
                                               at com.google.android.exoplayer2.source.CompositeMediaSource.lambda$prepareChildSource$0$com-google-android-exoplayer2-source-CompositeMediaSource(CompositeMediaSource.java:115)
                                               at com.google.android.exoplayer2.source.CompositeMediaSource$$ExternalSyntheticLambda0.onSourceInfoRefreshed(Unknown Source:4)
                                               at com.google.android.exoplayer2.source.BaseMediaSource.refreshSourceInfo(BaseMediaSource.java:88)
                                               at com.google.android.exoplayer2.source.dash.DashMediaSource.processManifest(DashMediaSource.java:847)
                                               at com.google.android.exoplayer2.source.dash.DashMediaSource.onManifestLoadCompleted(DashMediaSource.java:624)
                                               at com.google.android.exoplayer2.source.dash.DashMediaSource$ManifestCallback.onLoadCompleted(DashMediaSource.java:1302)
                                               at com.google.android.exoplayer2.source.dash.DashMediaSource$ManifestCallback.onLoadCompleted(DashMediaSource.java:1297)
                                               at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:478)
                                               at android.os.Handler.dispatchMessage(Handler.java:106) 
                                               at android.os.Looper.loopOnce(Looper.java:226) 
                                               at android.os.Looper.loop(Looper.java:313) 
                                               at android.os.HandlerThread.run(HandlerThread.java:67) `

**Comment by markshim1** [comment]
Any update on this?

**Comment by tonihei** [comment]
The reported exception has nothing to do with DRM or subtitles. The exception is thrown because your app attempts to use client-side ad insertion with a multi-period DASH stream. Client-side ad insertion is only supported with single-period media I'm afraid. See https://github.com/google/ExoPlayer/issues/3693
