### ISSUE TITLE
Audio Sink error

### ISSUE THREAD

**Issue by wishygupta** [google/ExoPlayer#11054]
On one of the HLS stream I am getting Audio Sink error from the time to time.

```
03-10 19:36:25.482  3049  3986 E MediaCodecAudioRenderer: Audio sink error
03-10 19:36:25.482  3049  3986 E MediaCodecAudioRenderer:   com.google.android.exoplayer2.audio.AudioSink$UnexpectedDiscontinuityException: Unexpected audio track timestamp discontinuity: expected 1005666327999, got 1005670294666
03-10 19:36:25.482  3049  3986 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:998)
03-10 19:36:25.482  3049  3986 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:703)
03-10 19:36:25.482  3049  3986 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1894)
03-10 19:36:25.482  3049  3986 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
03-10 19:36:25.482  3049  3986 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
03-10 19:36:25.482  3049  3986 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
03-10 19:36:25.482  3049  3986 E MediaCodecAudioRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
03-10 19:36:25.482  3049  3986 E MediaCodecAudioRenderer:       at android.os.Looper.loopOnce(Looper.java:201)
03-10 19:36:25.482  3049  3986 E MediaCodecAudioRenderer:       at android.os.Looper.loop(Looper.java:288)
03-10 19:36:25.482  3049  3986 E MediaCodecAudioRenderer:       at android.os.HandlerThread.run(HandlerThread.java:67)
```

What does it mean by ` Unexpected audio track timestamp discontinuity`.
Is it due to stream or missing somethink in exoplayer implementation?

**Comment by wishygupta** [comment]
This is the sample master manifest 

`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=158730,AVERAGE-BANDWIDTH=151800,CODECS="avc1.4d400c,mp4a.40.2",RESOLUTION=320x180,FRAME-RATE=25.000
master_180p.m3u8`

Could the codec be the issue in this?

**Comment by marcbaechinger** [comment]
> Is it due to stream or missing somethink in exoplayer implementation?

Can you send us an URI to the stream? It would enable us to look into your question.

Is this is a user visible issue or did you just find the stack trace in the logs?
