### ISSUE TITLE
ExoPlayer - Player is accessed on the wrong thread with RxJava2

### ISSUE THREAD

**Issue by hichemcesar24** [google/ExoPlayer#11060]
From past developers, I got a large library, which is built on the basis of ExoPlayer, which allows you to listen to audio books.

Everything worked fine until the library itself had to update the version of ExoPlayer to a newer one (this was very important)

In short: there is a small interface that has a ProgressBar showing how many seconds the audio has already been playing. Here is the code for this:

```
private lateinit var mExoPlayer : ExoPlayer

private val compositeDisposable = CompositeDisposable()
private val currentTrackProgress = MutableLiveData<Long>()

private var currentTrackProgressDisposable : Disposable? = null
private val playbackProgressObservable : Observable<Long> =
    Observable.interval(1, TimeUnit.MILLISECONDS).map {
        mExoPlayer.currentPosition
    }.observeOn(AndroidSchedulers.mainThread())

////////////////////// So many code here
////////////////////// Somewhere there is a call to the "createExoPlayer()" function

private fun createExoPlayer() {
    mExoPlayer = ExoPlayer.Builder(this).build()

    mExoPlayer.addListener(object : Player.Listener {

        override fun onIsPlayingChanged(isPlaying : Boolean) {
            if (isPlaying) {
                currentTrackProgressDisposable = playbackProgressObservable.subscribeBy(
                    onError = { error ->
                        Log.d("error", error.toString())
                    },
                    onNext = { progress ->
                        currentTrackProgress.value = progress
                    }
                )
                compositeDisposable.add(currentTrackProgressDisposable!!)
            }
        }
    })

    mExoPlayer.playWhenReady = true
}
```
Before updating ExoPlayer version, everything worked fine, but after updating to the latest version, an error began to appear in onError:

java.lang.IllegalStateException: Player is accessed on the wrong thread.
Current thread: 'RxComputationThreadPool-7'
Expected thread: 'main'

```
java.lang.IllegalStateException: Player is accessed on the wrong thread.
Current thread: 'RxComputationThreadPool-7'
Expected thread: 'main'
See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
     at com.google.android.exoplayer2.ExoPlayerImpl.verifyApplicationThread(ExoPlayerImpl.java:2668)
     at com.google.android.exoplayer2.ExoPlayerImpl.getCurrentPosition(ExoPlayerImpl.java:1058)
     at  xx.xx.xx.xxx.xxx..ExoBasePlayer.getCurrentPositionMs(Unknown Source:4)
     at  xx.xx.xx.xxx.xxx..AudioPlayer.getCurrentPosition(Unknown Source:2)
     at  xx.xx.xx.xxx.xxx..player.MediaSessionController.getCurrentPlaybackState(Unknown Source:2)
     at  xx.xx.xx.xxx.xxx..MediaSessionController.init$lambda-6(Unknown Source:82)
     at xx.xx.xx.xxx.xxx.MediaSessionController.$r8$lambda$VsMb3HHeQpuRrgGgnxPJqHRLzD8(Unknown Source:0)
     at xx.xxx.xx.xx.xx.xx.MediaSessionController$$ExternalSyntheticLambda4.apply(Unknown Source:4)
     at io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:111)
     at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
     at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111)
     at io.reactivex.internal.operators.observable.ObservableBufferTimed$BufferExactUnboundedObserver.accept(ObservableBufferTimed.java:213)
     at io.reactivex.internal.operators.observable.ObservableBufferTimed$BufferExactUnboundedObserver.accept(ObservableBufferTimed.java:81)
     at io.reactivex.internal.observers.QueueDrainObserver.fastPathEmit(QueueDrainObserver.java:69)
     at io.reactivex.internal.operators.observable.ObservableBufferTimed$BufferExactUnboundedObserver.run(ObservableBufferTimed.java:208)
     at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:38)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
     at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:308)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
     at java.lang.Thread.run(Thread.java:1012)
```

What could be the reason for this and how to fix it? After all, I didn’t even update the RxJava2 version, but only updated ExoPlayer

**Comment by marcbaechinger** [comment]
As explained on the page of the URL in the stack trace (https://exoplayer.dev/issues/player-accessed-on-wrong-thread) the player needs to be accessed on the same thread on which is has been created.

>  Somewhere there is a call to the "createExoPlayer()" function

Given the stack trace you posted, this `somewhere` is on another thread than this call:

```
at com.google.android.exoplayer2.ExoPlayerImpl.getCurrentPosition(ExoPlayerImpl.java:1058)
at  xx.xx.xx.xxx.xxx..ExoBasePlayer.getCurrentPositionMs(Unknown Source:4)
at  xx.xx.xx.xxx.xxx..AudioPlayer.getCurrentPosition(Unknown Source:2)
```

Put a break point in `createExoPlayer` and in `AudioPlayer.getCurrentPosition` and check the thread you are in. These are different threads. So you need to either create ExoPlayer on the same thread on which you later call your method, or, vice versa,  you do the call to `getCurrentPosition()` on the thread on which you created the player.

Please also consult the URL from the stack trace for more info: https://exoplayer.dev/issues/player-accessed-on-wrong-thread

**Comment by hichemcesar24** [comment]
Thanks It's work now
