### ISSUE TITLE
Failed to get key request

### ISSUE THREAD

**Issue by adaleydev** [google/ExoPlayer#11073]
Some of ours users are getting the error “Failed to get key request” when trying to download/stream Widevine content. This is an example of what we are seeing in user logs

    EXOPLAYER VERSION: 2.15.1 
    SDK:30 
    MODEL:ONEPLUS A6003
    com.google.android.exoplayer2.drm.DrmSession$DrmSessionException :: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error
	at com.google.android.exoplayer2.drm.DefaultDrmSession.t(DefaultDrmSession.java:2)
	at com.google.android.exoplayer2.drm.DefaultDrmSession.v(DefaultDrmSession.java:3)
	at com.google.android.exoplayer2.drm.DefaultDrmSession.C(DefaultDrmSession.java:4)
	at com.google.android.exoplayer2.drm.DefaultDrmSession.n(DefaultDrmSession.java:8)
	at com.google.android.exoplayer2.drm.DefaultDrmSession.a(DefaultDrmSession.java:9)
	at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.v(DefaultDrmSessionManager.java:5)
	at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.w(DefaultDrmSessionManager.java:1)
	at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.s(DefaultDrmSessionManager.java:17)
	at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.a(DefaultDrmSessionManager.java:3)
	at com.google.android.exoplayer2.drm.OfflineLicenseHelper.d(OfflineLicenseHelper.java:5)
	at com.google.android.exoplayer2.drm.OfflineLicenseHelper.b(OfflineLicenseHelper.java:2)
	at com.google.android.exoplayer2.drm.OfflineLicenseHelper.c(OfflineLicenseHelper.java:2)

Based on this ticket we found https://github.com/google/ExoPlayer/issues/8039,
we implemented a similar process to ‘force provision’ the device, but we are not sure if this will actually fix the issue and it invalidates the already downloaded Widevine content. We were hoping that a better solution is available. 

In our normal L1 flow, we check if the device is provisioned on startup and if it hasn’t we send the provisioning request. We do this to avoid the latency on the user’s first download or streaming attempt. We are considering removing this as a potential reason for error. Instead, we would rely on provision requests from Exoplayer at time of download/playback. We are not confident that this is the problem and it doesn’t fix the current user’s issues.

Is there any documentation around these errors? Are you aware of what could cause this failure and/or steps to resolve?

**Comment by rrfrias** [comment]
The stack trace does not contain sufficient information to identify the problem. A bugreport would help. If this is not possible and an android 9+ device, can you add some code to call [MediaDrm#getPropertyByteArray(“metrics”)](https://developer.android.com/reference/android/media/MediaDrm#getPropertyByteArray(java.lang.String)) and share the string with us. Mail dev.exoplayer@gmail.com with Issue #11073 in the subject line. 

You might also want to consider falling back to L3 if you see this problem repeatedly.

If you are seeing this on devices other than ONEPLUS A6003, do let us know.
