### ISSUE TITLE
Got error after updated to exoplayer 2.18.5

### ISSUE THREAD

**Issue by vqoley** [google/ExoPlayer#11081]
this code is from exoplayer 2.11.4:

```java
private void setSelectedSubtitle(com.google.android.exoplayer2.source.MediaSource mediaSource, String url) {
        MergingMediaSource mergedSource;
        if (url != null) {
            Uri subtitleUri = Uri.parse(url);

            Format subtitleFormat = Format.createTextSampleFormat(
                    null, // An identifier for the track. May be null.
                    MimeTypes.TEXT_VTT, // The mime type. Must be set correctly.
                    Format.NO_VALUE, // Selection flags for the track.
                    "en"); // The subtitle language. May be null.

            DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(PlayerActivity.this,
                    Util.getUserAgent(PlayerActivity.this, CLASS_NAME), new DefaultBandwidthMeter());


            com.google.android.exoplayer2.source.MediaSource subtitleSource = new SingleSampleMediaSource
                    .Factory(dataSourceFactory)
                    .createMediaSource(subtitleUri, subtitleFormat, C.TIME_UNSET);


            mergedSource = new MergingMediaSource(mediaSource, subtitleSource);
            player.prepare(mergedSource, false, false);
            player.setPlayWhenReady(true);
            //resumePlayer();

        } else {
            Toast.makeText(PlayerActivity.this, "there is no subtitle", Toast.LENGTH_SHORT).show();
        }
    }
```

when i update exoplayer to 2.18.5 and i modified code into this:

```java
private void setSelectedSubtitle(MediaSource mediaSource, String url) {
        MergingMediaSource mergedSource;
        if (url != null) {
            Uri subtitleUri = Uri.parse(url);

            Format subtitleFormat = new Format.Builder()
                    .setId(/* id= */ null)
                    .setLabel(/* label= */ null)
                    .setLanguage(/* language= */ "en")
                    .setSelectionFlags(/* selectionFlags= */ 0)
                    .setSampleMimeType(MimeTypes.TEXT_VTT)
                    .build();

            DataSource.Factory dataSourceFactory = new DefaultHttpDataSource.Factory();

            MediaItem.SubtitleConfiguration subtitleConfig = new MediaItem.SubtitleConfiguration.Builder(subtitleUri)
                    .setMimeType(MimeTypes.TEXT_VTT)
                    .setLanguage("en")
                    .build();

            MediaItem mediaItem = new MediaItem.Builder()
                    .setUri(url)
                    .setSubtitleConfigurations(Collections.singletonList(subtitleConfig))
                    .build();

            MediaSource subtitleSource = new ProgressiveMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(mediaItem);

            mergedSource = new MergingMediaSource(mediaSource, subtitleSource);
            DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(this)
                    .setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON);
            //player = new SimpleExoPlayer.Builder(this).build();
            //player = new SimpleExoPlayer.Builder(this).build();
           // player = (SimpleExoPlayer) new ExoPlayer.Builder(this).build();
            ExoPlayer player = new ExoPlayer.Builder(this).build();
            player.setMediaSource(mergedSource); //this line 475
            player.prepare();
            player.setPlayWhenReady(true);
        } else {
            Toast.makeText(this, "There is no subtitle", Toast.LENGTH_SHORT).show();
        }
    }
```

subtitle not working. when i select subtitle in player, that subtitle not showing and i got this error on logcat:

```
Access denied finding property "vendor.display-size"
eglMakeCurrent: 0xdfe5d8c0: ver 3 0 (tinfo 0xeb040e80)
Window handle Window{7c6745d u0 com.mana.magic/com.mana.magic.view.PlayerActivity} has no registered input channel
Playback error
  com.google.android.exoplayer2.ExoPlaybackException: Source error
	  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:614)
	  at android.os.Handler.dispatchMessage(Handler.java:103)
	  at android.os.Looper.loop(Looper.java:214)
	  at android.os.HandlerThread.run(HandlerThread.java:67)
  Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.
	  at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
	  at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1017)
	  at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	  at java.lang.Thread.run(Thread.java:919)
```

Anyone know what's wrong with this?

**Comment by icbaker** [comment]
You are trying to 'play' a subtitle file as the main piece of media, because `url` here points at your subtitle file, not your 'main' media:

```
MediaItem mediaItem = new MediaItem.Builder()
    .setUri(url)
    .setSubtitleConfigurations(Collections.singletonList(subtitleConfig))
    .build();
```

Try creating your `subtitleSource` using `SingleSampleMediaSource` in 2.18.5 like you are in 2.11.4. It's not clear to me why you switched to `ProgressiveMediaSource`. You are directly creating `MediaSource` instances, so you don't need to use `MediaItem` at all really. If you want to switch to using `MediaItem` then you should avoid manually creating any `MediaSource` instances yourself and let the player do it (with a custom factory if needed: https://exoplayer.dev/media-sources.html#customizing-media-source-creation)

**Comment by vqoley** [comment]
example i recreate by adding:

```
com.google.android.exoplayer2.source.MediaSource subtitleSource = new SingleSampleMediaSource
                    .Factory(dataSourceFactory)
                    .createMediaSource(subtitleUri, subtitleFormat, C.TIME_UNSET);

            mergedSource = new MergingMediaSource(mediaSource, subtitleSource);
            player.prepare(mergedSource, false, false);
            player.setPlayWhenReady(true);
```

on `createMediaSource` it said `Expected 2 arguments but found 3` . i confused on that. also `player.prepare(mergedSource, false, false)` is deprecated ('prepare(com.google.android.exoplayer2.source.MediaSource, boolean, boolean)' is deprecated ) so i change with `player.setMediaSource` but it want only 2 arguments instead 3 argument from old version code, thats mean i need remove on booleon on that right? so what's about `createMediaSource` it said `Expected 2 arguments but found 3` ?

**Comment by icbaker** [comment]
From the [release notes for 2.16.0](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2160-2021-11-04):
> Remove `SingleSampleMediaSource.createMediaSource(Uri, Format, long)`. Use `SingleSampleMediaSource.createMediaSource(MediaItem.Subtitle, long)` instead.

`MediaItem.Subtitle` has since been renamed `MediaItem.SubtitleConfiguration`.

The `resetState` boolean is not used by `prepare(MediaSource, boolean, boolean)`, so you can just drop that:
https://github.com/google/ExoPlayer/blob/0106f02a25a71321f9948f5aa6fefeb3008e21ca/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImpl.java#L551-L555

So try:

```java
MediaItem.SubtitleConfiguration subtitleConfig = new MediaItem.SubtitleConfiguration.Builder(subtitleUri)
    .setMimeType(MimeTypes.TEXT_VTT)
    .setLanguage("en")
    .build();
MediaSource subtitleSource = new SingleSampleMediaSource.Factory(dataSourceFactory)
    .createMediaSource(subtitleConfig, C.TIME_UNSET);

mergedSource = new MergingMediaSource(mediaSource, subtitleSource);
player.setMediaSource(mergedSource, false);
player.prepare();
player.setPlayWhenReady(true);
```

**Comment by vqoley** [comment]
Thank you. this is my latest code when recreate it.

```
private void setSelectedSubtitle(MediaSource mediaSource, String url) {
        MergingMediaSource mergedSource;
        if (url != null) {
            Uri subtitleUri = Uri.parse(url);

            Format subtitleFormat = new Format.Builder()
                    .setId(/* id= */ null)
                    .setLabel(/* label= */ null)
                    .setLanguage(/* language= */ "en")
                    .setSelectionFlags(/* selectionFlags= */ 0)
                    .setSampleMimeType(MimeTypes.TEXT_VTT)
                    .build();

            DataSource.Factory dataSourceFactory = new DefaultHttpDataSource.Factory();

            MediaItem.SubtitleConfiguration subtitleConfig = new MediaItem.SubtitleConfiguration.Builder(subtitleUri)
                    .setMimeType(MimeTypes.TEXT_VTT)
                    .setLanguage("en")
                    .build();
            MediaSource subtitleSource = new SingleSampleMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(subtitleConfig, C.TIME_UNSET);

            mergedSource = new MergingMediaSource(mediaSource, subtitleSource);
            player.setMediaSource(mergedSource, false); //error show here. line 490
            player.prepare();
            player.setPlayWhenReady(true);

        } else {
            Toast.makeText(this, "There is no subtitle", Toast.LENGTH_SHORT).show();
        }
    }
```

when i try choose subtitle from player, player stopped and got error,

```
FATAL EXCEPTION: main
Process: com.mana.magic, PID: 24690
 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.SimpleExoPlayer.setMediaSource(com.google.android.exoplayer2.source.MediaSource, boolean)' on a null object reference at com.mana.magic.view.PlayerActivity.setSelectedSubtitle(PlayerActivity.java:490)
```

error show at `player.setMediaSource(mergedSource, false);` . is that i miss something or i use wrong code from exoplayer 2.18.5 ?

**Comment by icbaker** [comment]
Closing because resolving `NullPointerException` errors due to uninitialized variables in your application is out of scope for this issue tracker.
