### ISSUE TITLE
Exoplayer throws IllegalStateException, moves to idle state and doesn't recover when a http request takes long time (>3 seconds) for HLS lives stream

### ISSUE THREAD

**Issue by shubhamkank** [google/ExoPlayer#11086]
Hi,

We are using Exoplayer version 2.9.6 for running an HLS-based live stream. We are seeing an issue where if an HTTP call for fetching a particular video segment takes more time (>2-3 seconds), the player is moving to IDLE state and never recovering automatically. Thus, causing the video to freeze for our end users. Looking for any inputs which can help resolve this issue.

Steps to reproduce:
* Intercept the HTTPS call for a particular video segment (which will be generated in the future) and variant. We are using Charles proxy (breakpoint settings feature) for the same.
* Return 200 responses after a manual delay of a few seconds

Log summary: 
1. index.m3u8 and segments till 8096.ts are fetched successfully for variant 
2. Since the request for 8100 is intercepted, the playback state changes to buffering
3. Player throws an Illegal state exception
4. Playback state changes to idle and doesn't recover at all

Detailed log:
```
2023-03-27 17:03:54.137 26679-31169 Response Received :     com.livestream.android                 D  Id : 125
                                                                                                    Method : GET
                                                                                                    Host : livestreampoc.akamaized.net
                                                                                                    StatusCode : 200
                                                                                                    Request Size : -1
                                                                                                    Response Size : 219
                                                                                                    Time Taken : 120
                                                                                                    Url : https://livestreampoc.akamaized.net/hls/live/2097897/8tsgca/1280/index.m3u8
                                                                                                    Request Body : null
                                                                                                    Response Body : okhttp3.internal.http.RealResponseBody@6c66572 
2023-03-27 17:03:55.085 26679-31168 Response Received :     com.livestream.android                 D  Id : 126
                                                                                                    Method : GET
                                                                                                    Host : livestreampoc.akamaized.net
                                                                                                    StatusCode : 200
                                                                                                    Request Size : -1
                                                                                                    Response Size : 263576
                                                                                                    Time Taken : 205
                                                                                                    Url : https://livestreampoc.akamaized.net/hls/live/2097897/8tsgca/1280/8096.ts
                                                                                                    Request Body : null
                                                                                                    Response Body : okhttp3.internal.http.RealResponseBody@29166be 
2023-03-27 17:03:55.656 26679-27291 CCodecBuffers           com.livestream.android                 D  [c2.android.aac.decoder#474:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
2023-03-27 17:03:56.059 26679-31170 BufferPoolAccessor2.0   com.livestream.android                 D  bufferpool2 0xb400007af7a0aba8 : 4(8388608 size) total buffers - 4(8388608 size) used buffers - 0/4 (recycle/alloc) - 5/804 (fetch/transfer)
2023-03-27 17:03:56.295 26679-31173 BufferPoolAccessor2.0   com.livestream.android                 D  bufferpool2 0xb400007af79ebf18 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 6/1166 (fetch/transfer)
2023-03-27 17:03:57.196 26679-31168 Response Received :     com.livestream.android                 D  Id : 127
                                                                                                    Method : GET
                                                                                                    Host : livestreampoc.akamaized.net
                                                                                                    StatusCode : 200
                                                                                                    Request Size : -1
                                                                                                    Response Size : 215260
                                                                                                    Time Taken : 289
                                                                                                    Url : https://livestreampoc.akamaized.net/hls/live/2097897/8tsgca/1280/8097.ts
                                                                                                    Request Body : null
                                                                                                    Response Body : okhttp3.internal.http.RealResponseBody@32c3704 
2023-03-27 17:03:57.306 26679-31169 Response Received :     com.livestream.android                 D  Id : 128
                                                                                                    Method : GET
                                                                                                    Host : livestreampoc.akamaized.net
                                                                                                    StatusCode : 200
                                                                                                    Request Size : -1
                                                                                                    Response Size : 219
                                                                                                    Time Taken : 164
                                                                                                    Url : https://livestreampoc.akamaized.net/hls/live/2097897/8tsgca/1280/index.m3u8
                                                                                                    Request Body : null
                                                                                                    Response Body : okhttp3.internal.http.RealResponseBody@3aed4ed 
2023-03-27 17:03:59.341 26679-31168 Response Received :     com.livestream.android                 D  Id : 129
                                                                                                    Method : GET
                                                                                                    Host : livestreampoc.akamaized.net
                                                                                                    StatusCode : 200
                                                                                                    Request Size : -1
                                                                                                    Response Size : 314524
                                                                                                    Time Taken : 437
                                                                                                    Url : https://livestreampoc.akamaized.net/hls/live/2097897/8tsgca/1280/8098.ts
                                                                                                    Request Body : null
                                                                                                    Response Body : okhttp3.internal.http.RealResponseBody@430d2e9 
2023-03-27 17:04:00.437 26679-31169 Response Received :     com.livestream.android                 D  Id : 130
                                                                                                    Method : GET
                                                                                                    Host : livestreampoc.akamaized.net
                                                                                                    StatusCode : 200
                                                                                                    Request Size : -1
                                                                                                    Response Size : 221
                                                                                                    Time Taken : 122
                                                                                                    Url : https://livestreampoc.akamaized.net/hls/live/2097897/8tsgca/1280/index.m3u8
                                                                                                    Request Body : null
                                                                                                    Response Body : okhttp3.internal.http.RealResponseBody@5bab4a5 
2023-03-27 17:04:01.278 26679-31168 Response Received :     com.livestream.android                 D  Id : 131
                                                                                                    Method : GET
                                                                                                    Host : livestreampoc.akamaized.net
                                                                                                    StatusCode : 200
                                                                                                    Request Size : -1
                                                                                                    Response Size : 257748
                                                                                                    Time Taken : 365
                                                                                                    Url : https://livestreampoc.akamaized.net/hls/live/2097897/8tsgca/1280/8099.ts
                                                                                                    Request Body : null
                                                                                                    Response Body : okhttp3.internal.http.RealResponseBody@946f621 
2023-03-27 17:04:01.460 26679-31170 BufferPoolAccessor2.0   com.livestream.android                 D  bufferpool2 0xb400007af7a0aba8 : 4(8388608 size) total buffers - 4(8388608 size) used buffers - 0/4 (recycle/alloc) - 5/966 (fetch/transfer)
2023-03-27 17:04:01.733 26679-31173 BufferPoolAccessor2.0   com.livestream.android                 D  bufferpool2 0xb400007af79ebf18 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 6/1400 (fetch/transfer)
2023-03-27 17:04:03.572 26679-31169 Response Received :     com.livestream.android                 D  Id : 133
                                                                                                    Method : GET
                                                                                                    Host : livestreampoc.akamaized.net
                                                                                                    StatusCode : 200
                                                                                                    Request Size : -1
                                                                                                    Response Size : 224
                                                                                                    Time Taken : 129
                                                                                                    Url : https://livestreampoc.akamaized.net/hls/live/2097897/8tsgca/1280/index.m3u8
                                                                                                    Request Body : null
                                                                                                    Response Body : okhttp3.internal.http.RealResponseBody@9274859 
2023-03-27 17:04:03.704 26679-26679 FkVideoAna...csListener com.livestream.android                 D  [main]  onPlayerStateChanged currentPlaybackPositionMs: 7816 totalBufferedDurationMs: 242 playWhenReady:true playbackState:2
2023-03-27 17:04:06.727 26679-31169 Response Received :     com.livestream.android                 D  Id : 134
                                                                                                    Method : GET
                                                                                                    Host : livestreampoc.akamaized.net
                                                                                                    StatusCode : 200
                                                                                                    Request Size : -1
                                                                                                    Response Size : 224
                                                                                                    Time Taken : 143
                                                                                                    Url : https://livestreampoc.akamaized.net/hls/live/2097897/8tsgca/1280/index.m3u8
                                                                                                    Request Body : null
                                                                                                    Response Body : okhttp3.internal.http.RealResponseBody@653a7b8 
2023-03-27 17:04:09.129 26679-27288 CCodec                  com.livestream.android                 W  previous call to queue exceeded timeout
2023-03-27 17:04:09.131 26679-31170 MediaCodec              com.livestream.android                 E  Codec reported err 0x80000000, actionCode 0, while in state 6
2023-03-27 17:04:09.133 26679-31170 SurfaceUtils            com.livestream.android                 D  disconnecting from surface 0xb400007b979a19e0, reason disconnectFromSurface
2023-03-27 17:04:09.134 26679-31170 CCodecBufferChannel     com.livestream.android                 D  [c2.android.avc.decoder#351] MediaCodec discarded an unknown buffer
2023-03-27 17:04:09.135 26679-31170 chatty                  com.livestream.android                 I  uid=10197(com.livestream.android) MediaCodec_loop identical 2 lines
2023-03-27 17:04:09.136 26679-31170 CCodecBufferChannel     com.livestream.android                 D  [c2.android.avc.decoder#351] MediaCodec discarded an unknown buffer
2023-03-27 17:04:09.142 26679-27269 ExoPlayerImplInternal   com.livestream.android                 E  Internal runtime error.
                                                                                                    java.lang.IllegalStateException
                                                                                                    	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                                                    	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
                                                                                                    	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1287)
                                                                                                    	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
                                                                                                    	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
                                                                                                    	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
2023-03-27 17:04:09.145 26679-27269 ExoPlayerImplInternal   com.livestream.android                 E  Stop failed.
                                                                                                    java.lang.IllegalStateException
                                                                                                    	at android.media.MediaCodec.native_stop(Native Method)
                                                                                                    	at android.media.MediaCodec.stop(MediaCodec.java:2251)
                                                                                                    	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:608)
                                                                                                    	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:508)
                                                                                                    	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:562)
                                                                                                    	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:377)
                                                                                                    	at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:153)
                                                                                                    	at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:976)
                                                                                                    	at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:764)
                                                                                                    	at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:735)
                                                                                                    	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:355)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
2023-03-27 17:04:09.145 26679-31171 hw-BpHwBinder           com.livestream.android                 I  onLastStrongRef automatically unlinking death recipients
2023-03-27 17:04:09.152 26679-31171 BufferPoolAccessor2.0   com.livestream.android                 D  bufferpool2 0xb400007af7a0aba8 : 0(0 size) total buffers - 0(0 size) used buffers - 0/4 (recycle/alloc) - 5/1021 (fetch/transfer)
2023-03-27 17:04:09.157   339-379   BufferQueueProducer     pid-339                              E  [SurfaceView - com.livestream.android/com.livestream.android.activity.HomeFragmentHolderActivity#0](id:153000001be,api:0,p:-1,c:339) detachBuffer: BufferQueue has no connected producer
2023-03-27 17:04:09.165 26679-31173 CCodecBufferChannel     com.livestream.android                 D  [c2.android.aac.decoder#474] MediaCodec discarded an unknown buffer
2023-03-27 17:04:09.167 26679-31173 chatty                  com.livestream.android                 I  uid=10197(com.livestream.android) MediaCodec_loop identical 6 lines
2023-03-27 17:04:09.167 26679-31173 CCodecBufferChannel     com.livestream.android                 D  [c2.android.aac.decoder#474] MediaCodec discarded an unknown buffer
2023-03-27 17:04:09.175 26679-26679 CrashLoggerUtils        com.livestream.android                 D  [main] [logCustomEvents] video_Health_event_dropped
2023-03-27 17:04:09.176 26679-31173 hw-BpHwBinder           com.livestream.android                 I  onLastStrongRef automatically unlinking death recipients
2023-03-27 17:04:09.177 26679-31173 BufferPoolAccessor2.0   com.livestream.android                 D  bufferpool2 0xb400007af79ebf18 : 0(0 size) total buffers - 0(0 size) used buffers - 1/7 (recycle/alloc) - 6/1484 (fetch/transfer)
2023-03-27 17:04:09.178 26679-26679 FkVideoAna...csListener com.livestream.android                 D  [main]  onPlayerStateChanged currentPlaybackPositionMs: 5825 totalBufferedDurationMs: 0 playWhenReady:true playbackState:1
2023-03-27 17:04:10.452 26679-31168 Response Received :     com.livestream.android                 D  Id : 132
                                                                                                    Method : GET
                                                                                                    Host : livestreampoc.akamaized.net
                                                                                                    StatusCode : 200
                                                                                                    Request Size : -1
                                                                                                    Response Size : 222968
                                                                                                    Time Taken : 7542
                                                                                                    Url : https://livestreampoc.akamaized.net/hls/live/2097897/8tsgca/1280/8100.ts
                                                                                                    Request Body : null
                                                                                                    Response Body : okhttp3.internal.http.RealResponseBody@42cdcf7 
2023-03-27 17:04:14.161 26679-27290 BufferPoolAccessor2.0   com.livestream.android                 D  bufferpool2 0xb400007af7a0aba8 : 0(0 size) total buffers - 0(0 size) used buffers - 0/4 (recycle/alloc) - 5/1021 (fetch/transfer)
2023-03-27 17:04:14.162 26679-27290 BufferPoolAccessor2.0   com.livestream.android                 D  evictor expired: 1, evicted: 1
2023-03-27 17:04:15.164 26679-27290 BufferPoolAccessor2.0   com.livestream.android                 D  bufferpool2 0xb400007af79ebf18 : 0(0 size) total buffers - 0(0 size) used buffers - 1/7 (recycle/alloc) - 6/1484 (fetch/transfer)
2023-03-27 17:04:15.164 26679-27290 BufferPoolAccessor2.0   com.livestream.android                 D  evictor expired: 1, evicted: 1
```

**Comment by shubhamkank** [comment]
@tianyif Can you please help here?

**Comment by tianyif** [comment]
Hi @shubhamkank,

Sorry for the delay! Could you please send me a sample stream url if you are still seeing this issue? The one `https://livestreampoc.akamaized.net/hls/live/2097897/8tsgca/1280/index.m3u8` in the log is no longer available. 

Thanks in advance!
