### ISSUE TITLE
GZip related errors when streaming (http) over certain carrier networks?

### ISSUE THREAD

**Issue by hansvdg** [google/ExoPlayer#1109]
Hi,

When opening a VOD m3u8 playlist we get the exception below on devices running android 6.0.1
On Android 6.0 the video plays fine.
Is this something that can be fixed in ExoPlayer or should we fix this on the streaming server side?

```
com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.io.IOException: ID1ID2: actual 0x00002345 != expected 0x00001f8b
                                                                        at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                                                                        at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141)
                                                                        at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:77)
                                                                        at java.io.InputStreamReader.read(InputStreamReader.java:233)
                                                                        at java.io.BufferedReader.fillBuf(BufferedReader.java:145)
                                                                        at java.io.BufferedReader.readLine(BufferedReader.java:397)
                                                                        at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:112)
                                                                        at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:37)
                                                                        at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93)
                                                                        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                        at java.lang.Thread.run(Thread.java:818)
                                                                     Caused by: java.io.IOException: ID1ID2: actual 0x00002345 != expected 0x00001f8b
                                                                        at com.android.okhttp.okio.GzipSource.checkEqual(GzipSource.java:205)
                                                                        at com.android.okhttp.okio.GzipSource.consumeHeader(GzipSource.java:120)
                                                                        at com.android.okhttp.okio.GzipSource.read(GzipSource.java:73)
                                                                        at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
                                                                        at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                                                                        at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                                                                        at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141) 
                                                                        at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:77) 
                                                                        at java.io.InputStreamReader.read(InputStreamReader.java:233) 
                                                                        at java.io.BufferedReader.fillBuf(BufferedReader.java:145) 
                                                                        at java.io.BufferedReader.readLine(BufferedReader.java:397) 
                                                                        at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:112) 
                                                                        at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:37) 
                                                                        at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93) 
                                                                        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by ojw28** [comment]
Please provide a sample stream. The failure is pretty deep in the network stack underneath of ExoPlayer. It could be a server or client side issue, I'm not sure just from looking at the stack trace.

**Comment by hansvdg** [comment]
We investigated a little further and now found that it works on wifi but not on 4G (Vodafone NL). We will try other providers to see if it is an isolated problem.

**Comment by ojw28** [comment]
If you're using http and have the ability to do so, it would also be an interesting exercise to try the same stream over https. Doing so will limit the ability of a man in the middle, for example a network provider, to modify the request/response. If this does turn out to be provider specific, then I'd take a wild guess from the stack trace that the provider is trying to compress the response, but is in some way not getting it quite right.

**Comment by ciribob** [comment]
We had the exact same issue on O2 and Vodafone UK with an HLS feed from Akami. Disabling GZIP here https://github.com/google/ExoPlayer/blob/r1.5.3/library/src/main/java/com/google/android/exoplayer/hls/HlsChunkSource.java#L534 solved the issue for us.

Unfortunately they are paid/protected feeds so I can't provide a link for testing.

**Comment by ciribob** [comment]
Further to this, it worked fine on EE (UK)

**Comment by ojw28** [comment]
So, to summarize, I think the conclusions so far are:

- There's some kind of bad interaction between the way ExoPlayer requests data and handles the responses, and certain carrier networks. The bad interaction appears to be related to the compression of the response.
- Disabling gzip as @ciribob describes is a workaround. Using https rather than http almost certainly also resolves the issue.

What's unclear is whether the bad interaction part is the carrier network doing something that's "flat out wrong" or whether it's doing something that's "a bit strange but technically valid". We should take a look at that and try and work out exactly what's going on.

**Comment by AquilesCanta** [comment]
I am not able to reproduce the bug on Vodafone UK, using an HLS feed. It does not mean anything, so I will keep trying. If you could provide something for me to work on, that would really help. The issue is that the GZip header (https://www.ietf.org/rfc/rfc1952.txt [Page 5]) is failing to include the fixed values ID1 ID2, so I would go for the "flat out wrong" hypothesis. If it works on Wifi, the man in the middle theory seems the most according. Can you try HTTPS and attempt to recreate?

**Comment by hansvdg** [comment]
We experience the issue on Vodafone NL, WiFi works fine. The content comes from an Akamai CDN which does not support HTTPS (at least not for the content we are trying to play). I have yet to test with GZIP compression off.
