### ISSUE TITLE
play live mp4 video exception

### ISSUE THREAD

**Issue by s894792409** [google/ExoPlayer#11125]
### Bug

An exception occurred while playing MP4, which only appeared on some videos, and this is a video that can be played normally using other methods.
exception:
 E/LoadTask: Unexpected exception loading stream
      java.lang.ArrayIndexOutOfBoundsException: length=157; index=157
        at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedByte(ParsableByteArray.java:233)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseVideoSampleEntry(AtomParsers.java:1203)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:949)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:308)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:130)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:483)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:442)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:424)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:242)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:624)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: length=157; index=157
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:430)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=157; index=157
        at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedByte(ParsableByteArray.java:233)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseVideoSampleEntry(AtomParsers.java:1203)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:949)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:308)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:130)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:483)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:442)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:424)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:242)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by s894792409** [comment]
https://user-images.githubusercontent.com/25165344/232726310-745e8643-4fc9-41c0-bcff-5ef0d73fafa9.mp4

this is exception mp4 video

**Comment by christosts** [comment]
@rohitjoins can you take a look?

**Comment by rohitjoins** [comment]
@s894792409,

Could you inform me about the version of the Exoplayer library that you're using so that I can understand the stack trace better?

**Comment by s894792409** [comment]
My used version is 'com.google.android.exoplayer:exoplayer:2.15.1'. My project only supports up to SDK30, so this is the latest version I can use

**Comment by s894792409** [comment]
My used View is 'com.google.android.exoplayer2.ui.PlayerView' 
code:
` 
                   Player player = playerView.getPlayer();
                    if (player == null) {
                        player = new SimpleExoPlayer.Builder(context)
                                .build();
                        playerView.setPlayer(player);
                    }
                    playerView.setControllerAutoShow(true);
//                    playerView.hideController();

                    String url = bean.getUrl();
                    MediaItem mediaItem = MediaItem.fromUri(url);

                    player.setMediaItem(mediaItem);
                    player.prepare();
`

**Comment by icbaker** [comment]
> My used version is 'com.google.android.exoplayer:exoplayer:2.15.1'. My project only supports up to SDK30, so this is the latest version I can use

I don't think there's any reason you can't increase your `compileSdkVersion` to the latest value (33). This is distinct from `targetSdkVersion` and `minSdkVersion`, and using the latest `compileSdkVersion` is "strongly recommended": https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd

I suggest you try reproducing your problem in the [demo app](https://exoplayer.dev/demo-application.html) at 2.15.1. If you're able to reproduce the problem then try again in the demo app at 2.18.6 (the latest version) - this will tell you if you're encountering a problem that's been fixed since 2.15.1 and you can then upgrade your app to use 2.18.6. If you find you're able to reproduce at 2.18.6 and a change is required in the library, then this change will only be available in a later version, so at that point you will need to upgrade your app anyway to pick up the fix.
