### ISSUE TITLE
Offline Playback of DRM content

### ISSUE THREAD

**Issue by Envitec** [google/ExoPlayer#11135]
There ar
![26a504f4-a7d3-4285-9661-6e50a68f027d](https://user-images.githubusercontent.com/39764252/234491511-e92938d6-cfb0-4aaa-b5cc-3148f9855f2d.png)
e several examples that shows use of ExoPlayer’s DownloadService class to download content.

Our use case is to download the files(s) (including .mpd, .mp4 (audio & video)) using backend gRPC services and modify ExoPlayer’s media source Uri to point to a folder on Android device with these files to play the content.

I am not able to get this going with several attempt to use file Uri instead of Http Uri. A typical exception I see is attached with this text.

Can you point me to any source which plays a downloaded content from a custom folder on the device and not use ExoPlayer’s Download service to cache the content?

**Comment by icbaker** [comment]
The screenshot provided is **incredibly** low resolution and hard to read. It would be much easier if you paste the stack trace here as text rather than any form of screenshot.

I **think** the root cause message is: `sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpUrlConnection`, being thrown from inside `DefaultHttpDataSource`.

I can't read any of the line numbers, but the only place in `DefaultHttpDataSource` we cast to `HttpUrlConnection` is here:
https://github.com/google/ExoPlayer/blob/cf49175f790dc4bbee85bb195c021ea40765d84b/library/datasource/src/main/java/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.java#L660-L662

I suspect what's happening is that you're passing a `file://` URI into `DefaultHttpDataSource`. This is not supported. If you want to read `file://` URIs then you should use [`FileDataSource`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/FileDataSource.html) or [`DefaultDataSource`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DefaultDataSource.html) (which will delegate `file://` URIs to `FileDataSource`).

**Comment by Envitec** [comment]
Sorry about that. Here is the trace in text format and the source code below. It is in C# / MAUI.

```
[DrmHalHidl] uuid=[edef8ba979d64ace a3c827dcd51d21ed] No supported hal instance found
[LoadTask] Unexpected exception loading stream
[LoadTask]   java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
[LoadTask]       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.openConnection(DefaultHttpDataSource.java:661)
[LoadTask]       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:619)
[LoadTask]       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:534)
[LoadTask]       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:376)
[LoadTask]       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
[LoadTask]       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
[LoadTask]       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
[LoadTask]       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
[LoadTask]       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
[LoadTask]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
[LoadTask]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
[LoadTask]       at java.lang.Thread.run(Thread.java:1012)
[ExoPlayerImplInternal] Playback error
[ExoPlayerImplInternal]   com.google.android.exoplayer2.ExoPlaybackException: Source error
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:637)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
[ExoPlayerImplInternal]       at android.os.Handler.dispatchMessage(Handler.java:102)
[ExoPlayerImplInternal]       at android.os.Looper.loopOnce(Looper.java:201)
[ExoPlayerImplInternal]       at android.os.Looper.loop(Looper.java:288)
[ExoPlayerImplInternal]       at android.os.HandlerThread.run(HandlerThread.java:67)
[ExoPlayerImplInternal]   Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:433)
[ExoPlayerImplInternal]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
[ExoPlayerImplInternal]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
[ExoPlayerImplInternal]       at java.lang.Thread.run(Thread.java:1012)
[ExoPlayerImplInternal]   Caused by: java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.openConnection(DefaultHttpDataSource.java:661)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:619)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:534)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:376)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
[ExoPlayerImplInternal]       ... 3 more
[DrmHalAidl] Failed to get vendor from drm plugin: -1010
[DrmHalAidl] Failed to get description from drm plugin: -1010
[0:] MediaManager: Error: Error codename: ERROR_CODE_IO_UNSPECIFIED, Error message: Source error
```

```
                protected void InitializeDrmPlayer(string videoUrl, string licenseUrl)
                {
                                var defaultHttpDataSourceFactory = new DefaultHttpDataSource.Factory().SetUserAgent(UserAgent)
                                                                                                                .SetTransferListener(new DefaultBandwidthMeter.Builder(mediaElementHandler.Context)
                                                                                                                .SetResetOnNetworkTypeChange(false).Build());

                                var mediaDataSourceFactory = new DefaultDataSource.Factory(mediaElementHandler.Context);

                                // DRM Callback & Session manager
                                var drmCallBack = new HttpMediaDrmCallback(licenseUrl, defaultHttpDataSourceFactory);
                                drmCallBack.SetKeyRequestProperty("X-AxDRM-Message", DrmToken);
                                var defaultDrmSessionManager = new DefaultDrmSessionManager.Builder().SetUuidAndExoMediaDrmProvider(C.WidevineUuid, FrameworkMediaDrm.DefaultProvider).Build(drmCallBack);

                                DefaultDashChunkSource.Factory dahsChunkSourceFactory;
                                var manifestDataSourceFactory = new DefaultHttpDataSource.Factory().SetUserAgent(UserAgent);


                                var headerDictionary = new Dictionary<string, string>();
                                headerDictionary.Add("X-AxDRM-Message", DrmToken);

                                Android.Net.Uri uriVideo = null;

                                if (PlayMode == 1) // 1 = Offline Playback
                                {
                                                uriVideo = Android.Net.Uri.FromFile(new Java.IO.File(videoUrl));
                                                dahsChunkSourceFactory = new DefaultDashChunkSource.Factory(mediaDataSourceFactory);
                                }
                                else
                                {
                                                uriVideo = Android.Net.Uri.Parse(videoUrl);
                                                dahsChunkSourceFactory = new DefaultDashChunkSource.Factory(defaultHttpDataSourceFactory);
                                }

                                var dashMediaSource = new DashMediaSource.Factory(dahsChunkSourceFactory, manifestDataSourceFactory)
                                                                                                                                //.SetDrmSessionManagerProvider((IDrmSessionManagerProvider)defaultDrmSessionManager)
                                                                                                                                .CreateMediaSource(new MediaItem.Builder().SetUri(uriVideo)
                                                                                                                                .SetDrmConfiguration(new MediaItem.DrmConfiguration.Builder(C.WidevineUuid)
                                                                                                                                .SetLicenseRequestHeaders(headerDictionary)
                                                                                                                                .SetLicenseUri(licenseUrl)
                                                                                                                                .Build())
                                                                                                                                .SetMimeType(MimeTypes.ApplicationMpd)
                                                                                                                                .SetTag(null)
                                                                                                                                .Build()
                                                                                                                                );

                                //_exoPlayer.SetMediaSource(dashMediaSource);
                                _exoPlayer.Prepare(dashMediaSource);
                                _exoPlayer.Play();
                                //mediaElement.Play();
                }
```

Thanks
Rajesh

**Comment by icbaker** [comment]
Based on the code you provided my diagnosis in https://github.com/google/ExoPlayer/issues/11135#issuecomment-1523306124 is correct. You're using `DefaultHttpDataSource` and passing it a `file://` URI. Please use a `DataSource` instance that supports `file://` URIs.
