### ISSUE TITLE
 ExoPlayer  play video error 

### ISSUE THREAD

**Issue by arwzhao** [google/ExoPlayer#11153]
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal: Playback error
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D402A, -1, null, [1280, 720, 25.0], [-1, -1]), format_supported=YES
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:223)
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.qti.avc.decoder
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1590)
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:       ... 3 more
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:   Caused by: java.lang.IllegalStateException
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:       at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:99)
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1190)
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
04-26 20:48:36.209  6206  8277 E ExoPlayerImplInternal:       ... 5 more
04-26 20:48:36.209  1624  2365 D Client  : clientCallBack!!  data:ClientCbData{code=4, serviceId=177, operationId=28, seqNr=111, opType=0, dataType=0, proc=0, payloadLen=0, payload=[]}
04-26 20:48:36.209  1624  2365 I Client  : clientCallBack: =MSG_SEND_SUC=
04-26 20:48:36.209  1624  2365 D IPCP Utils: byte2hex: data is NULL

**Comment by microkatz** [comment]
Hello @arwzhao,

Could you please provide the **complete** information as requested in the issue template. The issue template can
be found [here](https://github.com/androidx/media/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml).
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #11153". Please also update this issue to
indicate you've done this.

**Comment by tomake** [comment]
same issue with me

**Comment by microkatz** [comment]
Hello @tomake,

Could you please provide the complete information as requested in the issue template. The issue template can
be found [here](https://github.com/androidx/media/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to [android-media-github@google.com](mailto:android-media-github@google.com) using a subject in the format "Issue https://github.com/google/ExoPlayer/issues/11153". Please also update this issue to indicate you've done this.

**Comment by hoangchungk53qx1** [comment]
Realme C67 same issue with me
