### ISSUE TITLE
EXCEPTION: ExoPlayer:Playback

### ISSUE THREAD

**Issue by skyer518** [google/ExoPlayer#11156]
### Bug

implementation 'com.google.android.exoplayer:exoplayer-core:2.15.1'

```
 java.lang.IllegalAccessError: Illegal class access ('com.google.android.exoplayer2.video.MediaCodecVideoRenderer' attempting to access 'com.google.android.exoplayer2.RendererCapabilities$$Util') in attempt to invoke static method int com.google.android.exoplayer2.RendererCapabilities$$Util.create(int) (declaration of 'com.google.android.exoplayer2.video.MediaCodecVideoRenderer' appears in /data/app/com.sankuai.ng.cashier-1/base.apk:classes5.dex)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.supportsFormat(MediaCodecVideoRenderer.java:301)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.supportsFormat(MediaCodecRenderer.java:482)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:485)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:355)
        at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:238)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:186)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2202)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:501)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by marcbaechinger** [comment]
Thanks for you r report.

Hard to say what causes this. I can't imagine how this is a problem of the library because as far as I understand almost every playback with ExoPlayer is running trough this code path and we would be aware if this was a general issue. 

I recommend upgrading to another version which will probably also solve this problem. Without repro steps and the usual required info difficult to say what this is.

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #11156". Please also update this issue to indicate you’ve done this.
