### ISSUE TITLE
I can't play video after proguard

### ISSUE THREAD

**Issue by chenshuhong** [google/ExoPlayer#1115]
In 5.0 Android Verson ，it can‘t play video after progurad. The log is below 

```
Internal track renderer error.
                                                                     com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
                                                                         at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(Unknown Source)
                                                                         at com.google.android.exoplayer.TrackRenderer.prepare(Unknown Source)
                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(Unknown Source)
                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(Unknown Source)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                         at com.google.android.exoplayer.util.PriorityHandlerThread.run(Unknown Source)
                                                                      Caused by: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
                                                                         at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(Unknown Source)
                                                                         at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(Unknown Source)
                                                                         at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfo(Unknown Source)
                                                                         at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.handlesTrack(Unknown Source)
                                                                         at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(Unknown Source) 
                                                                         at com.google.android.exoplayer.TrackRenderer.prepare(Unknown Source) 
                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(Unknown Source) 
                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(Unknown Source) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                         at com.google.android.exoplayer.util.PriorityHandlerThread.run(Unknown Source) 
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                         at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:2150)
                                                                         at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfoInternal(Unknown Source)
                                                                         at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(Unknown Source) 
                                                                         at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(Unknown Source) 
                                                                         at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfo(Unknown Source) 
                                                                         at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.handlesTrack(Unknown Source) 
                                                                         at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(Unknown Source) 
                                                                         at com.google.android.exoplayer.TrackRenderer.prepare(Unknown Source) 
                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(Unknown Source) 
                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(Unknown Source) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                         at com.google.android.exoplayer.util.PriorityHandlerThread.run(Unknown Source) 
```

**Comment by chenshuhong** [comment]
How can I deal with it?

**Comment by ojw28** [comment]
Are you certain this is only after proguard? Last time this kind of issue was reported it turned out it occurred without proguard too. If it is only with proguard, you'll have to try playing around with your proguard configuration to see what causes it.

I'm not sure exactly what version of Android you're running, or on which device. The stack trace:

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                         at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:2150)
```

Doesn't match up with 5.0 source code (there's no call to `String.equals`) that [here](https://android.googlesource.com/platform/frameworks/base/+/android-5.0.2_r3/media/java/android/media/MediaCodecInfo.java#2150)

**Comment by ptran-gpfw** [comment]
@chenshuhong Can you give details on model and OS version?

@ojw28 My team has also observed this on [Huawei P8 Lite ALE-L23 ](http://pdadb.net/index.php?m=specs&id=7966&c=huawei_p8_lite_ale-l23_dual_sim_lte_huawei_alice).

I agree it is strange because there is no `String.equals` at that line in MediaCodecInfo. Is it possible OEM has modified code at there?

We can repro this 100%. And simply toggling `minifyEnabled` to false in build.gradle causes problem to go away.

**Comment by chenshuhong** [comment]
@ptran-gpfw ，my device is Huawei CHE-TL00H ,OS version 5.0.2

**Comment by ojw28** [comment]
I don't think it's possible for an OEM to have modified the code, no. Is it possible that the line numbers have changed because they're not being retained through your proguard step?

**Comment by ptran-gpfw** [comment]
Hi @ojw28,
So we've been examining our proguard rules and here's what we observed.

Using this proguard rule at the app-level causes the problem to go away:
`
-dontobfuscate
`

However, using `keep` on exoplayer does not fix the problem, ie
`
-keep class com.google.android.exoplayer.** { *; }
`

Note the only `-dont` flag that fixes this issue is `-dontobfuscate`. So shrinking and optimization is still occurring. Any hints on why obfuscation would cause an `String.equals` NPE in Android framework code (not ExoPlayer code) ?

**Comment by ptran-gpfw** [comment]
We are testing with two Huawei P8 Lite phones, one on 5.0.1 and one on 5.1. Only the phone on 5.0.1 exhibits this issue. This is not observed on 5.1 (or any other phone/os that we have in our QA lab).

We observe this issue with any MP4 played locally.

@ojw28 Would it be possible for you to test with Huawei P8 Lite running Android 5.0.1?

**Comment by ojw28** [comment]
Please can you provide a stack trace that at least has the line numbers retained. When every line says "Unknown Source" it's very difficult to work out what's going on. You should be able to retain line numbers, with:

```
-renamesourcefileattribute SourceFile
-keepattributes SourceFile,LineNumberTable
```

As per [this thread](http://stackoverflow.com/questions/10158849/android-proguard-return-line-number).

**Comment by ptran-gpfw** [comment]
Well this is strange.. when adding the proguard rules you suggested the problem goes away.

We narrowed it down and the problem is fixed when using this one proguard rule. 
`
-keepattributes SourceFile
`

We are going with this fix even though we're still not sure what the root cause is.
(I still maintain the belief that somehow OEM has modified MediaCodecInfo.java, perhaps some kind of reflection or stack-tracing functionality).

**Comment by ojw28** [comment]
MediaCodecInfo may be customized in the platform on this device (it most likely is given the stack trace). But your proguard config shouldn't make any difference to that class since it's not part of your apk.

The stack trace suggests that the value of `supportedType` passed to `getCapabilitiesForType` from `MediaCodecUtil.getMediaCodecInfoInternal` is probably null. However this should be impossible because the line above in `MediaCodecUtil.getMediaCodecInfoInternal` dereferences `supportedType`. If it were null, it should fail on that line.

All I can think of is that proguard is manipulates `MediaCodecUtil` in a way such that the resulting code then hits a bug in either dexopt or the vm on the affected devices. I have seen one other instance of this, where a proguard optimization generated code that was then subjected to an incorrect dead code elimination optimization. In that case the result was a seemingly impossible index out of bounds.

If the device has both Art and Dalvik then you could try switching in developer options. If it's a dexopt or vm thing then the issue would normally only affect one of them :).
