### ISSUE TITLE
SeekTo(MS) Not working

### ISSUE THREAD

**Issue by atiqmumtaz507** [google/ExoPlayer#11235]
### Bug

Hi I am using ExoPlayer latest version (2.18.7)

Here is my method which plays an Audio (Mp3) from this URL "https://sdn-global-audio-ais-cache.3qsdn.com/13088/files/23/06/28/8118761/19-3P8z6qhYjZ7fwVDBmNHt.mp3?awEpisodeId=8118761&awCollectionId=198&aisGetOriginalStream=true&listeningSessionID=64887fde721ac4c5_10627663_178__16beb84c1c0aaad493799cb1790991243df3e789"

    fun setCurrentPlayItemAndStartPlaying(item: PlayItem, seekTo: Int?): Boolean {
        try {
            item.progressiveUrlMp3?.let {
                if (isPlaying()) {
                    Timber.d("Player was playing an item. clearing the items.")
                    player.stop()
                    player.clearMediaItems()
                }

                Timber.d("Playing new item title %s URL %s seekTo %d", item.title, item.progressiveUrlMp3, seekTo)
                seekTo?.let { sektime ->
                    seekTimeInMS = sektime.toLong() * 1000
                }

                currentlyPlayingItem = item
                currentlyPlayingItem?.resetCheckPoints()
                setMediaItem(item, item.progressiveUrlMp3)
                player.prepare()
                player.seekTo(35000)
                player.addListener(this)
                startPlayService()
                resetTime()
                player.play()
                return true
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }

        return false
    }
    
    // This is how I set the URL to the player
    
    val dataSourceFactory: DataSource.Factory = DefaultDataSourceFactory(context, "ExoPlayer")
                val mediaSource: MediaSource = ProgressiveMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(MediaItem.fromUri(uriObj))
                player.setMediaSource(mediaSource)
                
                The problem is seek is not working at all.

**Comment by atiqmumtaz507** [comment]
@tianyif I get this Error

INFO:
 URL -> https://sdn-global-audio-ais-cache.3qsdn.com/12394/files/20/06/1522013/19-9H6yp8cDWv2thxXM3kLw.mp3?awEpisodeId=1522013&awCollectionId=200_264&aisGetOriginalStream=true
 
 This is how I set media item:
val  builder = MediaItem.ClippingConfiguration.Builder()
            .setStartPositionMs(20)
val clipConfig = builder.build()
        
        
 val mediaItem = MediaItem.Builder()
                .setUri(progressiveUrl)
                .setClippingConfiguration(clipConfig)
                .build()
 player.setMediaItem(mediaItem)
            
 Error: 
14:52:37.253  E  Playback error
                   com.google.android.exoplayer2.ExoPlaybackException: Source error
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:620)
                       at android.os.Handler.dispatchMessage(Handler.java:102)
                       at android.os.Looper.loopOnce(Looper.java:226)
                       at android.os.Looper.loop(Looper.java:313)
                       at android.os.HandlerThread.run(HandlerThread.java:67)
                   Caused by: com.google.android.exoplayer2.source.ClippingMediaSource$IllegalClippingException: Illegal clipping: not seekable to start
                       at com.google.android.exoplayer2.source.ClippingMediaSource$ClippingTimeline.<init>(ClippingMediaSource.java:306)
                       at com.google.android.exoplayer2.source.ClippingMediaSource.refreshClippedTimeline(ClippingMediaSource.java:267)
                       at com.google.android.exoplayer2.source.ClippingMediaSource.onChildSourceInfoRefreshed(ClippingMediaSource.java:233)
                       at com.google.android.exoplayer2.source.WrappingMediaSource.onChildSourceInfoRefreshed(WrappingMediaSource.java:130)
                       at com.google.android.exoplayer2.source.WrappingMediaSource.onChildSourceInfoRefreshed(WrappingMediaSource.java:46)
                       at com.google.android.exoplayer2.source.CompositeMediaSource.lambda$prepareChildSource$0$com-google-android-exoplayer2-source-CompositeMediaSource(CompositeMediaSource.java:115)
                       at com.google.android.exoplayer2.source.CompositeMediaSource$$ExternalSyntheticLambda0.onSourceInfoRefreshed(Unknown Source:4)
                       at com.google.android.exoplayer2.source.BaseMediaSource.refreshSourceInfo(BaseMediaSource.java:88)
                       at com.google.android.exoplayer2.source.ProgressiveMediaSource.notifySourceInfoRefreshed(ProgressiveMediaSource.java:374)
                       at com.google.android.exoplayer2.source.ProgressiveMediaSource.onSourceInfoRefreshed(ProgressiveMediaSource.java:337)
                       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.setSeekMap(ProgressiveMediaPeriod.java:739)
                       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.lambda$seekMap$1$com-google-android-exoplayer2-source-ProgressiveMediaPeriod(ProgressiveMediaPeriod.java:692)
                       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$$ExternalSyntheticLambda3.run(Unknown Source:4)
                       at android.os.Handler.handleCallback(Handler.java:942)
                       at android.os.Handler.dispatchMessage(Handler.java:99)
                       at android.os.Looper.loopOnce(Looper.java:226) 
                       at android.os.Looper.loop(Looper.java:313) 
                       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by atiqmumtaz507** [comment]
problem resolved as my player was not configured properly.Now my player is configured like this and it works

private fun createPlayer() {
        val dataSourceFactory = DefaultDataSourceFactory(context)
        val extractorsFactory = DefaultExtractorsFactory()
        extractorsFactory.setConstantBitrateSeekingAlwaysEnabled(false)
        extractorsFactory.setMp3ExtractorFlags(Mp3Extractor.FLAG_ENABLE_INDEX_SEEKING)
        val mediaSourceFactory = DefaultMediaSourceFactory(dataSourceFactory, extractorsFactory)

        val builder = ExoPlayer.Builder(context)
            .setMediaSourceFactory(mediaSourceFactory)
        player = builder.build()
    }
