### ISSUE TITLE
queueCSDInputBuffer failed w/ error -22 (DASH with PlayReady)

### ISSUE THREAD

**Issue by DavidMihola** [google/ExoPlayer#1124]
Hello,

when I try to play a DASH stream with PlayReady-DRM I get the following error:

    E/MediaCodec: queueCSDInputBuffer failed w/ error -22
    E/ExoPlayerImplInternal: Internal runtime error.
                         android.media.MediaCodec$CodecException: Error 0xffffffea
                             at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
                             at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:1048)
                             at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:569)
                             at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:503)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
                             at android.os.Handler.dispatchMessage(Handler.java:98)
                             at android.os.Looper.loop(Looper.java:135)
                             at android.os.HandlerThread.run(HandlerThread.java:61)
                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

Curiously, the same stream works fine when played with Widevine-DRM. Also, the error occurs even before the `executeKeyRequest` in my `PlayReadyDrmCallback` is called. (FWIW, when I do send the request, the response I receive seems OK...).

Is the error -22 even related to DRM at all or does the problem lies somewhere else?

Thanks for any help!

David

**Comment by ojw28** [comment]
Does the PlayReady sample in the demo app work correctly on whatever device you're testing on? What device is it that you're testing on, out of interest?

**Comment by DavidMihola** [comment]
You mean the Smooth Streaming example "Super speed (PlayReady)", right?

No, that doesn't work either, but with a rather different error message:

    ExoPlayerImplInternal: Internal track renderer error.
                       com.google.android.exoplayer.ExoPlaybackException: java.io.FileNotFoundException: http://playready.directtaps.net/pr/svc/rightsmanager.asmx
                           at com.google.android.exoplayer.MediaCodecTrackRenderer.shouldWaitForKeys(MediaCodecTrackRenderer.java:694)
                           at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:644)
                           at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:473)
                           at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                           at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                           at android.os.Handler.dispatchMessage(Handler.java:98)
                           at android.os.Looper.loop(Looper.java:135)
                           at android.os.HandlerThread.run(HandlerThread.java:61)
                           at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                        Caused by: java.io.FileNotFoundException: http://playready.directtaps.net/pr/svc/rightsmanager.asmx
                           at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:225)
                           at com.google.android.exoplayer.util.Util.executePost(Util.java:700)
                           at com.google.android.exoplayer.demo.SmoothStreamingTestMediaDrmCallback.executeKeyRequest(SmoothStreamingTestMediaDrmCallback.java:61)
                           at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostRequestHandler.handleMessage(StreamingDrmSessionManager.java:505)
                           at android.os.Handler.dispatchMessage(Handler.java:102)
                           at android.os.Looper.loop(Looper.java:135)
                           at android.os.HandlerThread.run(HandlerThread.java:61)
    EventLogger: internalError [2.95, drmSessionManagerError]
              java.io.FileNotFoundException: http://playready.directtaps.net/pr/svc/rightsmanager.asmx
                  at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:225)
                  at com.google.android.exoplayer.util.Util.executePost(Util.java:700)
                  at com.google.android.exoplayer.demo.SmoothStreamingTestMediaDrmCallback.executeKeyRequest(SmoothStreamingTestMediaDrmCallback.java:61)
                  at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostRequestHandler.handleMessage(StreamingDrmSessionManager.java:505)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:135)
                  at android.os.HandlerThread.run(HandlerThread.java:61)
    EventLogger: playerFailed [2.96]
              com.google.android.exoplayer.ExoPlaybackException: java.io.FileNotFoundException: http://playready.directtaps.net/pr/svc/rightsmanager.asmx
                  at com.google.android.exoplayer.MediaCodecTrackRenderer.shouldWaitForKeys(MediaCodecTrackRenderer.java:694)
                  at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:644)
                  at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:473)
                  at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                  at android.os.Handler.dispatchMessage(Handler.java:98)
                  at android.os.Looper.loop(Looper.java:135)
                  at android.os.HandlerThread.run(HandlerThread.java:61)
                  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
               Caused by: java.io.FileNotFoundException: http://playready.directtaps.net/pr/svc/rightsmanager.asmx
                  at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:225)
                  at com.google.android.exoplayer.util.Util.executePost(Util.java:700)
                  at com.google.android.exoplayer.demo.SmoothStreamingTestMediaDrmCallback.executeKeyRequest(SmoothStreamingTestMediaDrmCallback.java:61)
                  at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostRequestHandler.handleMessage(StreamingDrmSessionManager.java:505)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:135)
                   at android.os.HandlerThread.run(HandlerThread.java:61)

Also, it's a first generation Amazon Fire TV box (AFTB, "Bueller"), which does seem to support PlayReady - according to `MediaDrm.isCryptoSchemeSupported(StreamingDrmSessionManager.PLAYREADY_UUID)`. (In contrast, on my LG G2, the above streams fails because of "unsupported DRM scheme").

**Comment by ojw28** [comment]
- Do you have a (real) AndroidTV device to test with at all, such as Nexus Player, nVidia Shield TV box or one of the Sony TVs? We've seen compatibility issues with Fire TV devices where they haven't implemented Android APIs correctly. That's not to say that's definitely what's happening here, but it would be a good test to try on a device that we know does things properly.
- As for the demo app sample, could you give this another try? The error suggests to me that the server was down, but it seems to be working for me. It's possible that was a temporary issue? If you're still seeing the same error, it would be interesting to see what happens if you navigate to `http://playready.directtaps.net/pr/svc/rightsmanager.asmx` in a web browser.

**Comment by DavidMihola** [comment]
To answer your second question first:

I tried it again today and received the same error message - on the Fire TV. Meanwhile, on a Nexus Player (accessing the internet through the same access point) it works fine...

Which is also true for my own problem: While I still receive the error -22 on the Fire TV the stream plays without problems on the Nexus Player. Which is extremely frustrating because the Fire TV is the whole point of even implementing PlayReady at all, since it does not support Widevine Level 1 and thus cannot play HD streams with Widevine DRM...

I am afraid this means I'll really have to try VisualOn for DRM streams on Fire TV... I was so hoping to be able to use Exoplayer on all devices...

**Comment by ojw28** [comment]
I'd suggest you follow up with Amazon about this issue.

**Comment by DavidMihola** [comment]
@ojw28 Yes, I did contact Amazon, and their reply was basically: "Just use VisualOn."

:-(
