### ISSUE TITLE
HLS live stream works fine on Wifi, fails on 3G network

### ISSUE THREAD

**Issue by egemenhamutcu** [google/ExoPlayer#1126]
It fails on your Demo app. I put a URL in Sample[] HLS in Samples.java. It shows the URL in the list of SampleChooserActivity. When I tap it, it works fine on Wifi, but fails on 3G network giving the following error.

Stacktrace:

```
com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
                                                                                    at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
                                                                                    at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
                                                                                    at com.google.android.exoplayer.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:97)
                                                                                    at com.google.android.exoplayer.upstream.DataSourceInputStream.open(DataSourceInputStream.java:56)
                                                                                    at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:92)
                                                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                                    at java.lang.Thread.run(Thread.java:841)
```

I am trying to switch from Vitamio to Exoplayer. Vitamio hasn't got any issue like this. Any advices?

**Comment by ojw28** [comment]
That's just a networking error indicating the resource wasn't found, as described [here](https://en.wikipedia.org/wiki/HTTP_404). So it looks like a networking issue to me. ExoPlayer just uses the standard Android network stack, so it feels like this isn't an ExoPlayer issue.

**Comment by egemenhamutcu** [comment]
@ojw28 but the same source works like a charm in Vitamio bundle on both 3G and Wi-fi connection.

**Comment by ojw28** [comment]
I'm sorry, but a 404 is categorically a network error indicating the resource wasn't found. It's possible that the live stream you're attempting to play is missing various chunks and that a different player may, by chance, not select to try and play those chunks. In any case, you should look at the specific URL for which the 404 occurs, and see if your device is able to request that URL successfully in something like a regular browser.
