### ISSUE TITLE
EXoplayer throwing source Error when trying to play DRM content with ads

### ISSUE THREAD

**Issue by spuday90** [google/ExoPlayer#11288]
### Bug

Hi team,

We are facing issue with one of our partner content playback. We are trying to play drm content, its playing with out ads enabled.
But when we enable the ads its throwing the source error. We tried the same url in the exoplayer sample apps 2.18.1 adn 2.19.1
Same issue is observed. Please check the logs and suggest us whats wrong. Note any sample IMA adtag also same issue.

**Test Urls**
"uri": "https://vimtvdrm.sonyliv.com/DASH/8ac9ef8c2efb4eed80a7499850e9714a/1686119545/baseline-std-v4/1556784378_2018_Everyone_Is_A_Hero_tel_baseline-800300010.mpd?contentId=1000223489&cpCustomerId=2309090744418713702&deviceId=VIMTV-Server&partner=VIMTV&partnerId=1556784508&platform=ANDROID_PHONE&user-agent=Apache-HttpClient/4.5.5 (Java/1.8.0_362)&hdnea=exp=1694489763~acl=*~id=15567845082309090744418713702~hmac=092ece17b20b5178f013b83cf64f8476de6f6b839e49a688ba318a7337c93f66&sku_name=liv_mobilepack_vimtv_1m",

"drm_scheme": "widevine",

"drm_license_uri": "https://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=BwA2T1gfKbQAJDFhZWU2MmNiLTA2YzQtNDFmZC1iZjdkLWRhZDg2NWFlNWNmYwAAAIB39sEyLxlH4Z8rXqOGSerOtQRu8HY-LzVcJ_nH5AB5wU8RIK5K4xKCID_WlGWgNizS0n4fpR1JktVMt03EprF75mAgUl-UxZpOwnqZzqi8S9lSwQkfHYKiRb6qnCRmW-gwoaK9MgK6W9dJKwOAsY7SOuTGLWCWMxv0HctppYZSn2F4dUgZeTwTbQxHGuljAW1FiQNl",
        "ad_tag_uri": "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator="
        
        
        
**Error Logs:**

java.lang.IllegalArgumentException
                       at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
                       at com.google.android.exoplayer2.source.ads.AdsMediaSource.onChildSourceInfoRefreshed(AdsMediaSource.java:266)
                       at com.google.android.exoplayer2.source.ads.AdsMediaSource.onChildSourceInfoRefreshed(AdsMediaSource.java:61)
                       at com.google.android.exoplayer2.source.CompositeMediaSource.lambda$prepareChildSource$0$com-google-android-exoplayer2-source-CompositeMediaSource(CompositeMediaSource.java:115)
                       at com.google.android.exoplayer2.source.CompositeMediaSource$$ExternalSyntheticLambda0.onSourceInfoRefreshed(Unknown Source:4)
                       at com.google.android.exoplayer2.source.BaseMediaSource.refreshSourceInfo(BaseMediaSource.java:88)
                       at com.google.android.exoplayer2.source.dash.DashMediaSource.processManifest(DashMediaSource.java:847)
                       at com.google.android.exoplayer2.source.dash.DashMediaSource.onManifestLoadCompleted(DashMediaSource.java:624)
                       at com.google.android.exoplayer2.source.dash.DashMediaSource$ManifestCallback.onLoadCompleted(DashMediaSource.java:1302)
                       at com.google.android.exoplayer2.source.dash.DashMediaSource$ManifestCallback.onLoadCompleted(DashMediaSource.java:1297)
                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:478)
                       at android.os.Handler.dispatchMessage(Handler.java:106)
                       at android.os.Looper.loopOnce(Looper.java:210)
                       at android.os.Looper.loop(Looper.java:299)
                       at android.os.HandlerThread.run(HandlerThread.java:67)
                       
                       
                       
                       
com.google.android.exoplayer2.ExoPlaybackException: Source error
                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:608)
                     at android.os.Handler.dispatchMessage(Handler.java:102)
                     at android.os.Looper.loopOnce(Looper.java:210)
                     at android.os.Looper.loop(Looper.java:299)
                     at android.os.HandlerThread.run(HandlerThread.java:67)
                 Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:482)
                     at android.os.Handler.dispatchMessage(Handler.java:106)
                     at android.os.Looper.loopOnce(Looper.java:210)
                     at android.os.Looper.loop(Looper.java:299)
                     at android.os.HandlerThread.run(HandlerThread.java:67)
                 Caused by: java.lang.IllegalArgumentException

**Comment by oceanjules** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
