### ISSUE TITLE
Player crashes on Finishing Video

### ISSUE THREAD

**Issue by Amritpal33** [google/ExoPlayer#1131]
Hi,
   Exoplayer crashes with following logs:

```
01-11 19:25:07.655 32019-8915/com.jio.media.jod E/AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
01-11 19:25:07.655 32019-8915/com.jio.media.jod E/AndroidRuntime: Process: com.jio.media.jod, PID: 32019
01-11 19:25:07.655 32019-8915/com.jio.media.jod E/AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=497; index=497
01-11 19:25:07.655 32019-8915/com.jio.media.jod E/AndroidRuntime:     at com.google.android.exoplayer.dash.DashWrappingSegmentIndex.getTimeUs(DashWrappingSegmentIndex.java:51)
01-11 19:25:07.655 32019-8915/com.jio.media.jod E/AndroidRuntime:     at com.google.android.exoplayer.dash.DashChunkSource$RepresentationHolder.getSegmentStartTimeUs(DashChunkSource.java:918)
01-11 19:25:07.655 32019-8915/com.jio.media.jod E/AndroidRuntime:     at com.google.android.exoplayer.dash.DashChunkSource.newMediaChunk(DashChunkSource.java:680)
01-11 19:25:07.655 32019-8915/com.jio.media.jod E/AndroidRuntime:     at com.google.android.exoplayer.dash.DashChunkSource.getChunkOperation(DashChunkSource.java:483)
01-11 19:25:07.655 32019-8915/com.jio.media.jod E/AndroidRuntime:     at com.google.android.exoplayer.chunk.ChunkSampleSource.doChunkOperation(ChunkSampleSource.java:561)
01-11 19:25:07.655 32019-8915/com.jio.media.jod E/AndroidRuntime:     at com.google.android.exoplayer.chunk.ChunkSampleSource.updateLoadControl(ChunkSampleSource.java:435)
01-11 19:25:07.655 32019-8915/com.jio.media.jod E/AndroidRuntime:     at com.google.android.exoplayer.chunk.ChunkSampleSource.onLoadCompleted(ChunkSampleSource.java:361)
01-11 19:25:07.655 32019-8915/com.jio.media.jod E/AndroidRuntime:     at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
01-11 19:25:07.655 32019-8915/com.jio.media.jod E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-11 19:25:07.655 32019-8915/com.jio.media.jod E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
01-11 19:25:07.655 32019-8915/com.jio.media.jod E/AndroidRuntime:     at android.os.HandlerThread.run(HandlerThread.java:61)
01-11 19:25:07.655 32019-8915/com.jio.media.jod E/AndroidRuntime:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

Please suggest where is the issue.

**Comment by ojw28** [comment]
You'll have to provide more details, as listed [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html)

**Comment by ojw28** [comment]
Closing due to insufficient information.
