### ISSUE TITLE
Widevine drm content not playing on Android 7.1.2

### ISSUE THREAD

**Issue by raa-ju** [google/ExoPlayer#11312]
Hello,
I am facing a issue with drm protected video while playing. the log says
```

2023-10-16 15:45:58.973 4136-9782/? E/WVCdm: Decrypt error result in session sid38 during encrypted block: 176
2023-10-16 15:45:58.973 4136-9782/? E/WVCdm: WVCryptoPlugin::decrypt else E
2023-10-16 15:45:58.976 10187-10351/? E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/avc, avc1.4D401E, 2309363, null, [720, 480, 29.97], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:43)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.media.MediaCodec$CryptoException: Unknown Error
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2480)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SourceFile:3)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(SourceFile:75)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:18)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:15)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:25)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

how to resolve it ?

**Comment by tonihei** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues

There also isn't enough information to let us debug the issue. Please fill out the complete issue template (including the bugreport)
