### ISSUE TITLE
ExoPlayerImplInternal.waitUninterruptibly ANR

### ISSUE THREAD

**Issue by bookzhan** [google/ExoPlayer#11319]
### Bug

main (timed waiting):tid=1 systid=25461 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:442)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.waitUninterruptibly(ExoPlayerImplInternal.java:669)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.release(ExoPlayerImplInternal.java:436)
       at com.google.android.exoplayer2.ExoPlayerImpl.release(ExoPlayerImpl.java:989)

ExoPlayeVersion:2.18.6

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues

When filing a new issue please include the info requested by the issue template.
