### ISSUE TITLE
I am playing an mp3 file error, the mp3 file is normal, can be played in other software

### ISSUE THREAD

**Issue by yi1234** [google/ExoPlayer#11320]
Playback error
                                                                                                      com.google.android.exoplayer2.ExoPlaybackException: Source error
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:684)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:654)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loop(Looper.java:257)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: com.google.android.exoplayer2.ParserException: Expected block size: 4; got: 2{contentIsMalformed=true, dataType=1}
                                                                                                          at com.google.android.exoplayer2.extractor.wav.WavExtractor$PassthroughOutputWriter.<init>(WavExtractor.java:316)
                                                                                                          at com.google.android.exoplayer2.extractor.wav.WavExtractor.readFormat(WavExtractor.java:210)
                                                                                                          at com.google.android.exoplayer2.extractor.wav.WavExtractor.read(WavExtractor.java:142)
                                                                                                          at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:133)
                                                                                                          at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
                                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:420)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                          at java.lang.Thread.run(Thread.java:923)

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues

From the stack trace, ExoPlayer thinks your file is a .wav file not an MP3. If you open a new issue in the media3 repo please include the file so we can investigate.
