### ISSUE TITLE
Player video throw this exception:  InsufficientCapacityException: Buffer too small (58368 < 59408)

### ISSUE THREAD

**Issue by lingyfh** [google/ExoPlayer#11324]
### Bug

Hello, I encountered such a problem, which is very strange: When playing a video, the getCodecMaxInputSize of the video is calculated to be 58368, so the MaxInputSize of MediaCodec is set to 58368. However, the sample size calculated by sampleSizeBox.readNextSampleSize() is 59408. The capacity of the buffer obtained from buffer.data = codec.getInputBuffer(inputIndex); is also 58368, which caused the exception: Caused by: com.google.android.exoplayer2.decoder.DecoderInputBuffer$InsufficientCapacityException: Buffer too small (58368 < 59408)

on other normal device, codec.getInputBuffer(inputIndex) will return huge size.

devices: HUAWEI NOH-AN00
android: 12

video：
https://github.com/lingyfh/problem_resources/blob/main/problem_13011374225.mp4

**StackTrace:**

Caused by: com.google.android.exoplayer2.decoder.DecoderInputBuffer$InsufficientCapacityException: Buffer too small (58368 < 59408)
        at com.google.android.exoplayer2.decoder.DecoderInputBuffer.createReplacementByteBuffer(DecoderInputBuffer.java:251)
        at com.google.android.exoplayer2.decoder.DecoderInputBuffer.ensureSpaceForWrite(DecoderInputBuffer.java:192)
        at com.google.android.exoplayer2.source.SampleDataQueue.readSampleData(SampleDataQueue.java:292)
        at com.google.android.exoplayer2.source.SampleDataQueue.readToBuffer(SampleDataQueue.java:125)
        at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:422)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.readData(ProgressiveMediaPeriod.java:487)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$SampleStreamImpl.readData(ProgressiveMediaPeriod.java:952)
        at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:394)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1235)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:826)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:947)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:477)
        at android.os.Handler.dispatchMessage(Handler.java:113) 
        at android.os.Looper.loopOnce(Looper.java:205) 
        at android.os.Looper.loop(Looper.java:293) 
        at android.os.HandlerThread.run(HandlerThread.java:110)

**Comment by oceanjules** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues

When filing a new issue please include the info requested by the issue template.
