### ISSUE TITLE
Unable to play RTSP with KEYIFRAME method

### ISSUE THREAD

**Issue by folio3-naveedali** [google/ExoPlayer#11326]
### Bug

My link returns header
Public: DESCRIBE, PLAY, SETUP, TEARDOWN, KEYIFRAME, SET_PARAMETER, GET_PARAMETER

against KEYIFRAME it is throwing java.lang.IllegalArgumentException in android. 
Here is the exception logs generated by android studio
Caused by: java.lang.IllegalArgumentException
          at androidx.media3.exoplayer.rtsp.RtspMessageUtil.parseMethodString(RtspMessageUtil.java:286)
          at androidx.media3.exoplayer.rtsp.RtspMessageUtil.parsePublicHeader(RtspMessageUtil.java:389)
          at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.handleRtspResponse(RtspClient.java:618)
          at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:515) 
          at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$androidx-media3-exoplayer-rtsp-RtspClient$MessageListener(RtspClient.java:508) 
          at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener$$ExternalSyntheticLambda0.run(Unknown Source:4) 
          at android.os.Handler.handleCallback(Handler.java:942) 
          at android.os.Handler.dispatchMessage(Handler.java:99) 
          at android.os.Looper.loopOnce(Looper.java:226) 
          at android.os.Looper.loop(Looper.java:313) 
          at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by oceanjules** [comment]
Hi @folio3-naveedali,

From the following code and looking at the javadoc:
https://github.com/google/ExoPlayer/blob/5df25aefd9234f91716960430a4540baa8971315/library/rtsp/src/main/java/com/google/android/exoplayer2/source/rtsp/RtspMessageUtil.java#L381-L388

It looks like you can only use 11 `RtspRequest.Method` as defined here:

https://github.com/google/ExoPlayer/blob/5df25aefd9234f91716960430a4540baa8971315/library/rtsp/src/main/java/com/google/android/exoplayer2/source/rtsp/RtspRequest.java#L62-L78

If you look at the spec for methods, there doesn't seem to be one for KEYIFRAME: https://www.rfc-editor.org/rfc/rfc2326.html#page-29
