### ISSUE TITLE
unable to download video link with m3u8 file for android version 7 using media3 transformation

### ISSUE THREAD

**Issue by Kaleb09** [google/ExoPlayer#11342]
### Bug

i got the following error log when i try to make media transformation with m3u8 video link i used the demo app and added my own m3u8 video link and try to make the transformation but it failed the app works perfectly with android versions greater than 9 but it doesn't work for versions equalto and less than 9 i got the following error logs

Export error

```      
at com.google.android.exoplayer2.transformer.TransformerInternal.handleMessage(TransformerInternal.java:306)
at com.google.android.exoplayer2.transformer.TransformerInternal.$r8$lambda$wLcb-t1rNJBtxPBz3q3mAtv5x5M(TransformerInternal.java)
at com.google.android.exoplayer2.transformer.TransformerInternal$$ExternalSyntheticLambda3.handleMessage(D8$$SyntheticClass)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.IllegalStateException: Samples not in presentation order (133333 < 166666) unsupported on this API version
at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:107)
at com.google.android.exoplayer2.transformer.FrameworkMuxer.writeSampleData(FrameworkMuxer.java:176)
at com.google.android.exoplayer2.transformer.DefaultMuxer.writeSampleData(DefaultMuxer.java:97)
at com.google.android.exoplayer2.transformer.MuxerWrapper.writeSample(MuxerWrapper.java:243)
at com.google.android.exoplayer2.transformer.SamplePipeline.feedMuxer(SamplePipeline.java:125)
at com.google.android.exoplayer2.transformer.SamplePipeline.processData(SamplePipeline.java:73)
at com.google.android.exoplayer2.transformer.TransformerInternal.drainPipelinesInternal(TransformerInternal.java:327)
at com.google.android.exoplayer2.transformer.TransformerInternal.handaleMessage(TransformerInternal.java:292)
at com.google.android.exoplayer2.transformer.TransformerInternal.$r8$lambda$wLcb-t1rNJBtxPBz3q3mAtv5x5M(TransformerInternal.java) 
at com.google.android.exoplayer2.transformer.TransformerInternal$$ExternalSyntheticLambda3.handleMessage(D8$$SyntheticClass) 
at android.os.Handler.dispatchMessage(Handler.java:98) 
at android.os.Looper.loop(Looper.java:154) 
at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by marcbaechinger** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues
