### ISSUE TITLE
AV1 Seek Support Issue

### ISSUE THREAD

**Issue by jksaras** [google/ExoPlayer#11355]
When playing AV1 video in exoplayer 

1. Taking too much time when seeking 
2. When seeking near to end the video restarts. It gives an End of file exception 

 Playback error
                   com.google.android.exoplayer2.ExoPlaybackException: Source error
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:684)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:660)
                       at android.os.Handler.dispatchMessage(Handler.java:102)
                       at android.os.Looper.loop(Looper.java:246)
                       at android.os.HandlerThread.run(HandlerThread.java:67)
                   Caused by: java.io.EOFException
                       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:304)
                       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:115)
                       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:123)
                       at com.google.android.exoplayer2.extractor.mkv.DefaultEbmlReader.read(DefaultEbmlReader.java:157)
                       at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.read(MatroskaExtractor.java:520)
                       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:133)
                       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:420)
                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                       at java.lang.Thread.run(Thread.java:923)

**Comment by tonihei** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues

Please also provide the file if you want us to look into the issue as it's not possible to debug in detail without reproducing the issue first.
