### ISSUE TITLE
play error

### ISSUE THREAD

**Issue by 2038920059** [google/ExoPlayer#11381]
### This project is deprecated

- [X] I understand this project is deprecated, that I should file my issue in the [Media3 issue tracker](https://github.com/androidx/media/issues/new/choose) instead of here, and this issue will be closed with no response.

**Comment by 2038920059** [comment]
PlaybackException
                                                                                                    com.google.android.exoplayer2.ExoPlaybackException: Source error
                                                                                                    	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:684)
                                                                                                    	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:656)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                    	at android.os.Looper.loop(Looper.java:135)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                                    Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: failed to connect to cache.m.iqiyi.com/103.44.59.57 (port 80) after 8000ms
                                                                                                    	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:388)
                                                                                                    	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:269)
                                                                                                    	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:90)
                                                                                                    	at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:105)
                                                                                                    	at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:68)
                                                                                                    	at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:179)
                                                                                                    	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:420)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                    	at java.lang.Thread.run(Thread.java:818)
                                                                                                    Caused by: java.net.SocketTimeoutException: failed to connect to cache.m.iqiyi.com/103.44.59.57 (port 80) after 8000ms
                                                                                                    	at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
                                                                                                    	at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                                                    	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                                                    	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
                                                                                                    	at java.net.Socket.connect(Socket.java:882)
                                                                                                    	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
                                                                                                    	at com.android.okhttp.Connection.connect(Connection.java:152)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
                                                                                                    	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
                                                                                                    	at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
                                                                                                    	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:659)
                                                                                                    	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:540)
                                                                                                    	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:382)
                                                                                                    	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:269) 
                                                                                                    	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:90) 
                                                                                                    	at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:105) 
                                                                                                    	at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:68) 
                                                                                                    	at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:179) 
                                                                                                    	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:420) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                                    	at java.lang.Thread.run(Thread.java:818)

**Comment by xfy-c** [comment]
com.google.android.exoplayer2.ExoPlaybackException: Source error
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:684)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:656)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loop(Looper.java:193)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:65)
                                                                                                      Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.ConnectException: Failed to connect to user-images.githubusercontent.com/127.0.0.1:443
                                                                                                          at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:388)
                                                                                                          at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:60)
                                                                                                          at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:802)
                                                                                                          at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:615)
                                                                                                          at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:90)
                                                                                                          at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
                                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:420)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                          at java.lang.Thread.run(Thread.java:764)
                                                                                                      Caused by: java.net.ConnectException: Failed to connect to user-images.githubusercontent.com/127.0.0.1:443
                                                                                                          at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
                                                                                                          at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
                                                                                                          at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
                                                                                                          at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
                                                                                                          at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
                                                                                                          at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
                                                                                                          at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
                                                                                                          at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:507)
                                                                                                          at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:132)
                                                                                                          at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
                                                                                                          at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
                                                                                                          at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:659)
                                                                                                          at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:540)
                                                                                                          at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:382)
                                                                                                          at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:60) 
                                                                                                          at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:802) 
                                                                                                          at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:615) 
                                                                                                          at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:90) 
                                                                                                          at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013) 
                                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:420) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                          at java.lang.Thread.run(Thread.java:764)
