### ISSUE TITLE
Media decoder exception

### ISSUE THREAD

**Issue by VenkateshanR** [google/ExoPlayer#11401]
### This project is deprecated

- [ ] I understand this project is deprecated, that I should file my issue in the [Media3 issue tracker](https://github.com/androidx/media/issues/new/choose) instead of here, and this issue will be closed with no response.

**Comment by VenkateshanR** [comment]
Hi,
I am using exoplayer 2.11. videos are throwing Decoder exception.
Attaching log

`Renderer error: index=0, type=video, format=Format(video/avc1/4, null, null, video/avc, avc1.4D401E, 1093390, null, [640, 360, 25.0], [-1, -1]), rendererSupport=NO_UNSUPPORTED_DRM
  com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.mtk.avc.decoder.secure, Format(video/avc1/4, null, null, video/avc, avc1.4D401E, 1093390, null, [640, 360, 25.0], [-1, -1])
      at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:563)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1254)
      at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:756)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:814)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:712)
      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loopOnce(Looper.java:257)
      at android.os.Looper.loop(Looper.java:368)
      at android.os.HandlerThread.run(HandlerThread.java:67)
  Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.mtk.avc.decoder.secure, Format(video/avc1/4, null, null, video/avc, avc1.4D401E, 1093390, null, [640, 360, 25.0], [-1, -1])
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:867)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:561)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1254) 
      at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:756) 
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:814) 
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:712) 
      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loopOnce(Looper.java:257) 
      at android.os.Looper.loop(Looper.java:368) 
      at android.os.HandlerThread.run(HandlerThread.java:67) 
  Caused by: android.media.MediaCodec$CodecException: 
      at android.media.MediaCodec.native_start(Native Method)
      at android.media.MediaCodec.start(MediaCodec.java:2440)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:931)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:860)

> `

Once the error occurs, unable to play the video even after resume the app or reinstall app. only works after restarting the device.
Is there any way to stop this from happening? or when this error occur how do we modify properties in such way player can play the video file.
Device: Oneplus, Oppo, Realme
OS: Android 14 and 11

kindly help us to resolve this issue, we are loosing our customers

**Comment by rohitjoins** [comment]
The project is deprecated, please file your issue in the Media3 tracker as instructed.
