### ISSUE TITLE
Error playing video on Samsung Galaxy S6

### ISSUE THREAD

**Issue by abouda** [google/ExoPlayer#1166]
I get this error log when trying to play my stream with ExoPlayer. I also get the same error log with the ExoPlayer demo app.
I only get this on both Samsung Galaxy S6 and S6 edge (android 5.1.1). On all my other devices it works good.

````
D/OMX     ( 3009): SendBroadCasting VIDEO_PLAYBACK_START
I/SEC_AAC_DEC( 3009):  AudioSpecificConfig 0x 12 10
I/ACodec  (18320): can't find wfdsink-exynos-enable
I/OMX     ( 3009): width (320), height (142), fps (15)
E/OMXNodeInstance( 3009): getConfig(87:Exynos.avc.dec.secure, ConfigCommonOutputCrop(0x700000f)) ERROR: NotReady(0x80001010)
E/OMXNodeInstance( 3009): setParameter(87:Exynos.avc.dec.secure, ParamPortDefinition(0x2000001)) ERROR: BadParameter(0x80001005)
W/ACodec  (18320): [OMX.Exynos.avc.dec.secure] setting nBufferCountActual to 6 failed: -2147483648
E/OMXNodeInstance( 3009): setParameter(87:Exynos.avc.dec.secure, ParamPortDefinition(0x2000001)) ERROR: BadParameter(0x80001005)
W/ACodec  (18320): [OMX.Exynos.avc.dec.secure] setting nBufferCountActual to 5 failed: -2147483648
I/ACodec  (18320): [OMX.Exynos.avc.dec.secure] configureOutputBuffersFromNativeWindow setBufferCount : 4, minUndequeuedBuffers : 2
I/ACodec  (18320): [OMX.Exynos.avc.dec.secure] allocated meta buffer with ID 0xf02c6290 (pointer = 0x7fa908e000)
I/ACodec  (18320): [OMX.Exynos.avc.dec.secure] allocated meta buffer with ID 0xf02c69c0 (pointer = 0x7fa908e020)
I/ACodec  (18320): [OMX.Exynos.avc.dec.secure] allocated meta buffer with ID 0xef835920 (pointer = 0x7fa908e040)
I/ACodec  (18320): [OMX.Exynos.avc.dec.secure] allocated meta buffer with ID 0xef835560 (pointer = 0x7fa908e060)
I/ACodec  (18320): SECURE PLAYBACK START / send intent to dvfshelper
D/libexynosv4l2( 3009): try node: /dev/video6
D/libexynosv4l2( 3009): try node: /dev/video7
D/libexynosv4l2( 3009): try node: /dev/video8
I/libexynosv4l2( 3009): node found for device s5p-mfc-dec-secure: /dev/video8
D/EventLogger(18320): decoderInitialized [0.55, OMX.Exynos.avc.dec.secure]
W/Parcel  ( 3793): Attempt to read object from Parcel 0x7f956f18c8 at offset 276 that is not in the object list
I/System.out(18320): (HTTPLog)-Static: isSBSettingEnabled false
I/SEC_AAC_DEC( 3009):  AudioSpecificConfig 0x 12 10
D/CustomFrequencyManagerService( 3793): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 500000  uid : 1000  pid : 3793  pkgName : SCREEN_MIRROR_BOOSTER_1_0G@35
D/SSRM:a  ( 3793): DeviceInfo:: 000000000000
D/SSRM:a  ( 3793): SettingsAirViewInfo:: 000000000
I/ACodec  (18320): >>> getPortFormat 16, OMX.SEC.aac.dec
D/AudioPolicyManager( 3009): getDeviceForStrategy mLastPolicySelection device = 0
D/AudioPolicyManager( 3009): getDeviceForStrategy mLastPolicySelection device = 0
D/AudioPolicyManager( 3009): getDeviceForStrategy mLastPolicySelection device = 0
D/AudioPolicyManager( 3009): getDeviceForStrategy mLastPolicySelection device = 0
I/libexynosv4l2( 3009): open video device /dev/video8
I/ACodec  (18320): [OMX.Exynos.avc.dec.secure] Now Executing
E/wv_dash ( 3009): Trustlet did not send a valid return code: 0x6000
E/wv_dash ( 3009): tee_send_msg_general_cmd is failed.
E/wv_dash ( 3009): process drm decrypt CTR failed
E/WVCdm   ( 3009): Decrypt error result in session sid4 during unencrypted block: 1
E/MediaCodec(18320): queueCSDInputBuffer failed w/ error -2998
E/wv_dash ( 3009): Trustlet did not send a valid return code: 0x6000
E/wv_dash ( 3009): tee_send_msg_general_cmd is failed.
E/wv_dash ( 3009): process drm decrypt CTR failed
E/WVCdm   ( 3009): Decrypt error result in session sid4 during unencrypted block: 1
E/MediaCodec(18320): queueCSDInputBuffer failed w/ error -2998
E/ExoPlayerImplInternal(18320): Internal runtime error.
E/ExoPlayerImplInternal(18320): android.media.MediaCodec$CryptoException: Unknown Error
E/ExoPlayerImplInternal(18320): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/ExoPlayerImplInternal(18320): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
E/ExoPlayerImplInternal(18320): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:816)
E/ExoPlayerImplInternal(18320): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:472)
E/ExoPlayerImplInternal(18320): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
E/ExoPlayerImplInternal(18320): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
E/ExoPlayerImplInternal(18320): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal(18320): 	at android.os.Looper.loop(Looper.java:145)
E/ExoPlayerImplInternal(18320): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal(18320): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/libcsc  ( 3009): csc_deinit:: unsupported csc_hw_type
V/WindowManager( 3793): Adding window Window{2adbaf52 u0 d0 Panel:com.google.android.exoplayer.demo/com.google.android.exoplayer.demo.PlayerActivity} at 6 of 11 (after Window{7b7adee u0 d0 com.google.android.exoplayer.demo/com.google.android.exoplayer.demo.PlayerActivity})
D/MultiWindowConverter( 3793): dismissGuide() : Before attaching the guide view, mForceDismissGuide : false
D/InputDispatcher( 3793): Focus left window: 18320
D/InputDispatcher( 3793): Focus entered window: 18320
D/PointerIcon( 3793): setMouseIconStyle1 pointerType: 1001 iconType:101 flag:0 pid:3793 uid:1000
D/PointerIcon( 3793): setMouseCustomIcon IconType is same.101
E/EventLogger(18320): playerFailed [0.58]
E/EventLogger(18320): com.google.android.exoplayer.ExoPlaybackException: android.media.MediaCodec$CryptoException: Unknown Error
E/EventLogger(18320): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
E/EventLogger(18320): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/EventLogger(18320): 	at android.os.Looper.loop(Looper.java:145)
E/EventLogger(18320): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/EventLogger(18320): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/EventLogger(18320): Caused by: android.media.MediaCodec$CryptoException: Unknown Error
E/EventLogger(18320): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/EventLogger(18320): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
E/EventLogger(18320): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:816)
E/EventLogger(18320): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:472)
E/EventLogger(18320): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
E/EventLogger(18320): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
E/EventLogger(18320): 	... 4 more
```

**Comment by casajavi** [comment]
I get a similar problem on both the Samsung Galaxy S6 and the S6 edge. The video playback will work fine four an indeterminate amount of time then this error will occur: 
```01-22 10:58:30.297 12215-12215/com.blim E/EventLogger: internalError [0.26, drmSessionManagerError]
                                                       android.media.MediaDrm$MediaDrmStateException: Failed to open session: General DRM error
                                                           at android.media.MediaDrm.openSession(Native Method)
                                                           at com.google.android.exoplayer.drm.StreamingDrmSessionManager.openInternal(StreamingDrmSessionManager.java:320)
                                                           at com.google.android.exoplayer.drm.StreamingDrmSessionManager.open(StreamingDrmSessionManager.java:293)
                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:310)
                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:723)
                                                           at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:328)
                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:484)
                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:467)
                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                           at android.os.Looper.loop(Looper.java:145)
                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
                                                           at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)```

After this I can no longer start up playback for any video at all including videos in other apps like Netflix. To fix it I have to restart the device. Its a very strange problem.

Have you had any luck with this?

**Comment by abouda** [comment]
I found out that both these devices are rooted. I don't know if this is related but the streaming works on other rooted devices.

**Comment by jimmytobin2425** [comment]
I restarted my S6 (5.1.1) and also had the oculus developer mode on. That worked for me

**Comment by AquilesCanta** [comment]
When filing new issues, please read the Issue Template and provide all useful information. Namely, the stream that produces the failure.
