### ISSUE TITLE
Internal track render error, playback HLS

### ISSUE THREAD

**Issue by crossle** [google/ExoPlayer#1180]
Nexus 5 Android 6.0.1, HLS live streaming
```
 ExoPlayerImplInternal  E  Internal track renderer error.
                         E  com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.BehindLiveWindowException
                         E      at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                         E      at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:438)
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                         E      at android.os.Handler.dispatchMessage(Handler.java:98)
                         E      at android.os.Looper.loop(Looper.java:148)
                         E      at android.os.HandlerThread.run(HandlerThread.java:61)
                         E      at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                         E  Caused by: com.google.android.exoplayer.BehindLiveWindowException
                         E      at com.google.android.exoplayer.hls.HlsChunkSource.getChunkOperation(HlsChunkSource.java:400)
                         E      at com.google.android.exoplayer.hls.HlsSampleSource.maybeStartLoading(HlsSampleSource.java:697)
                         E      at com.google.android.exoplayer.hls.HlsSampleSource.continueBuffering(HlsSampleSource.java:264)
                         E      at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:127)
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                         E      ... 5 more
        DownloadManager  I  DownloadQueueManager WorkerThread[Thread[Thread-41927,5,main]] trying to get a task..mWaitingThreadPoolQueue size：0
                         E  com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.BehindLiveWindowException
                         E      at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                         E      at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:438)
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                         E      at android.os.Handler.dispatchMessage(Handler.java:98)
                         E      at android.os.Looper.loop(Looper.java:148)
                         E      at android.os.HandlerThread.run(HandlerThread.java:61)
                         E      at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                         E  Caused by: com.google.android.exoplayer.BehindLiveWindowException
                         E      at com.google.android.exoplayer.hls.HlsChunkSource.getChunkOperation(HlsChunkSource.java:400)
                         E      at com.google.android.exoplayer.hls.HlsSampleSource.maybeStartLoading(HlsSampleSource.java:697)
                         E      at com.google.android.exoplayer.hls.HlsSampleSource.continueBuffering(HlsSampleSource.java:264)
                         E      at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:127)
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                         E      ... 5 more
         OMX-VDEC-1080P  I  omx_vdec::component_deinit() complete
                         I  Exit OMX vdec Destructor: fd=26
            EventLogger  E  playerFailed [45]
                         E  com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.BehindLiveWindowException
                         E      at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                         E      at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:438)
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                         E      at android.os.Handler.dispatchMessage(Handler.java:98)
                         E      at android.os.Looper.loop(Looper.java:148)
                         E      at android.os.HandlerThread.run(HandlerThread.java:61)
                         E      at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                         E  Caused by: com.google.android.exoplayer.BehindLiveWindowException
                         E      at com.google.android.exoplayer.hls.HlsChunkSource.getChunkOperation(HlsChunkSource.java:400)
                         E      at com.google.android.exoplayer.hls.HlsSampleSource.maybeStartLoading(HlsSampleSource.java:697)
                         E      at com.google.android.exoplayer.hls.HlsSampleSource.continueBuffering(HlsSampleSource.java:264)
                         E      at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:127)
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                         E      ... 5 more
```

**Comment by ojw28** [comment]
Please see https://github.com/google/ExoPlayer/issues/1074.
