### ISSUE TITLE
When playing Youtube dash videos from demo app, it fails to play

### ISSUE THREAD

**Issue by guygeva** [google/ExoPlayer#1191]
I saw this exception when trying to play the 2 youtube dash MP4 videos:

```
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: java.lang.NullPointerException
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.dash.DashChunkSource$RepresentationHolder.getSegmentNum(DashChunkSource.java:954)
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.dash.DashChunkSource.getChunkOperation(DashChunkSource.java:513)
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.chunk.ChunkSampleSource.doChunkOperation(ChunkSampleSource.java:563)
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.chunk.ChunkSampleSource.updateLoadControl(ChunkSampleSource.java:437)
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.chunk.ChunkSampleSource.restartFrom(ChunkSampleSource.java:411)
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.chunk.ChunkSampleSource.enable(ChunkSampleSource.java:194)
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.SampleSourceTrackRenderer.onEnabled(SampleSourceTrackRenderer.java:112)
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onEnabled(MediaCodecVideoTrackRenderer.java:233)
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.TrackRenderer.enable(TrackRenderer.java:160)
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:322)
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:272)
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:201)
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:136)
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
01-26 18:49:27.781 23858 24055 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by ojw28** [comment]
The stack trace above doesn't match the line numbers in any releases that we've done. What version of ExoPlayer are you using?

**Comment by guygeva** [comment]
I apologize, it seems like I did use the wrong version.
