### ISSUE TITLE
exoplayer issues with aac+ stream API 19 KitKat

### ISSUE THREAD

**Issue by alexistkd** [google/ExoPlayer#1211]
Hi i already created my app with exoplayer version r1.5.3 in android studio when i try API 23 or 20 the app plays the stream without issues, but if i go to API 19 i get this error:

```
01-30 12:01:36.063 3996-4269/com.streaming507.aacplayer E/ExoPlayerImplInternal: Internal track renderer error.
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://streaming507.com:9986
                                                                                     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
                                                                                     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                  Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://streaming507.com:9986
                                                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:202)
                                                                                     at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
                                                                                     at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:741)
                                                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                     at java.lang.Thread.run(Thread.java:841)
                                                                                  Caused by: java.net.ProtocolException: Unexpected status line: ICY 200 OK
                                                                                     at com.android.okhttp.internal.http.RawHeaders.setStatusLine(RawHeaders.java:108)
                                                                                     at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
                                                                                     at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
                                                                                     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
                                                                                     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
                                                                                     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
                                                                                     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
                                                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:199)
```

**Comment by alexistkd** [comment]
it shows                                                                                   

> Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://streaming507.com:9986

but my stream is up and playing musi

**Comment by andrewlewis** [comment]
`Unexpected status line: ICY 200 OK` looks similar to #890. Is this still reproducible if you use [OkHttpDataSource](https://github.com/google/ExoPlayer/blob/master/extensions/okhttp/src/main/java/com/google/android/exoplayer/ext/okhttp/OkHttpDataSource.java)?

**Comment by alexistkd** [comment]
What you mean im using android studio how i can use okhttpdatasource i load the exoplayer via gradle jcenter

**Comment by andrewlewis** [comment]
OkHttpDataSource is part of [an extension](https://github.com/google/ExoPlayer/tree/master/extensions/okhttp), not the core library, and it looks like it is not published to jCenter at the moment unfortunately. You could try checking out the source and using that instead as per [the instructions here](https://github.com/google/ExoPlayer#as-source).
