### ISSUE TITLE
okhttp implementation with exoplayer

### ISSUE THREAD

**Issue by alexistkd** [google/ExoPlayer#1215]
Hi i tried to implement okhttp in my app with exoplayer by using this code:

          ```
      Allocator allocator = new DefaultAllocator(BUFFER_SEGMENT_SIZE);
                String userAgent = Util.getUserAgent(context, "ExoPlayerDemo");
                OkHttpClient okHttpClient = new OkHttpClient();
              //DataSource dataSource = new DefaultUriDataSource(context, null, userAgent);
                DataSource dataSource = new DefaultUriDataSource(context, null,
                        new OkHttpDataSource(okHttpClient, userAgent, null, null));
                ExtractorSampleSource sampleSource = new ExtractorSampleSource(
                        uri, dataSource, allocator, BUFFER_SEGMENT_SIZE * BUFFER_SEGMENT_COUNT);
                //audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource);
                exoPlayer.prepare(audioRenderer);
                return true;
```
```
01-31 18:41:54.400 2337-2981/com.streaming507.aacplayer E/ExoPlayerImplInternal: Internal runtime error.
                                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.exoplayer.MediaClock com.google.android.exoplayer.TrackRenderer.getMediaClock()' on a null object reference
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:264)
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:201)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
01-31 18:41:54.400 2337-2981/com.streaming507.aacplayer E/ExoPlayerImplInternal: Stop failed.
                                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer.TrackRenderer.getState()' on a null object reference
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.ensureStopped(ExoPlayerImplInternal.java:655)
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.stopAndDisable(ExoPlayerImplInternal.java:559)
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:548)
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:525)
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:247)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
01-31 18:41:54.410 2337-2981/com.streaming507.aacplayer E/ExoPlayerImplInternal: Release failed.
                                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer.TrackRenderer.release()' on a null object reference
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.release(ExoPlayerImplInternal.java:574)
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:549)
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:525)
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:247)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```
how i can fix this?

thank you in advance

**Comment by b95505017** [comment]
Could you test my branch?
https://github.com/b95505017/ExoPlayer/tree/okhttp_http_data_source
I'm not sure if your error is related to OkHttp or not.

**Comment by alexistkd** [comment]
yeah with yours works, i just put this code:

```
         DataSource dataSource = new DefaultUriDataSource(context, null,
                        new OkHttpDataSource(okHttpClient, userAgent, null, null, CacheControl.FORCE_NETWORK));

                ExtractorSampleSource sampleSource = new ExtractorSampleSource(uri, dataSource, allocator,
                        BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);

               // audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource);

                MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource,
                        MediaCodecSelector.DEFAULT, null, true, null, null,
                        AudioCapabilities.getCapabilities(context), AudioManager.STREAM_MUSIC);

                exoPlayer.prepare(audioRenderer);
```

and works like a charm.

thank yo

**Comment by ojw28** [comment]
The error has nothing to do with okhttp. The fact you've commented out the line of code that instantiates audioRenderer means that you're passing a null renderer to the player, which isn't a valid thing to do.

**Comment by bmutinda** [comment]
Is it possible to stream RTMP with `OkHttpDataSource` because I have tried and I am always getting this

``` java
Unexpected exception loading stream
java.lang.IllegalArgumentException: url == null
at com.squareup.okhttp.Request$Builder.url(Request.java:141)
at com.myexampleapp.android.music.player.OkHttpDataSource.makeRequest(OkHttpDataSource.java:261)
at com.myexampleapp.android.music.player.OkHttpDataSource.open(OkHttpDataSource.java:149)
at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:824)
at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
```

This is how I am creating my renderers

``` java
private static final int BUFFER_SEGMENT_SIZE = 64 * 1024;
private static final int BUFFER_SEGMENT_COUNT = 256;    
..................................................................................................................

Allocator allocator = new DefaultAllocator(BUFFER_SEGMENT_SIZE);
Handler mainHandler = player.getMainHandler();

// Build the video and audio renderers.
DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter(player.getMainHandler(),
      null);
DataSource dataSource = new DefaultUriDataSource(context, bandwidthMeter,
      new OkHttpDataSource(getHttpClient(), userAgent, null, null, CacheControl.FORCE_NETWORK));
ExtractorSampleSource sampleSource = new ExtractorSampleSource(uri, dataSource, allocator,
      BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);
MediaCodecVideoTrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(context,
      sampleSource, MediaCodecSelector.DEFAULT, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT, 5000,
      mainHandler, player, 50);
MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource,
      MediaCodecSelector.DEFAULT, null, true, mainHandler, player,
      AudioCapabilities.getCapabilities(context), AudioManager.STREAM_MUSIC);
TrackRenderer textRenderer = new TextTrackRenderer(sampleSource, player,
      mainHandler.getLooper());
```
