### ISSUE TITLE
Can't run apk with exoplayer 1.5.4 by device android 4.4.2

### ISSUE THREAD

**Issue by longquangpham90** [google/ExoPlayer#1218]
Hi all! 

I dealt with on mobile application development and run into problems with the link stream wowaza when play applications. app with the following error message . drunk only error with android device versions below 5.0

```
02-02 11:16:17.911: E/ACodec(25614): registering GraphicBuffer 0 with OMX IL component failed: -2147483648
02-02 11:16:17.911: E/ACodec(25614): Failed to allocate output port buffers after port reconfiguration (error 0x80000000)
02-02 11:16:17.911: E/MediaCodec(25614): Codec reported an error. (omx error 0x80001001, internalError -2147483648)
02-02 11:16:17.921: E/ExoPlayerImplInternal(25614): Internal runtime error.
02-02 11:16:17.921: E/ExoPlayerImplInternal(25614): java.lang.IllegalStateException
02-02 11:16:17.921: E/ExoPlayerImplInternal(25614): 	at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
02-02 11:16:17.921: E/ExoPlayerImplInternal(25614): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:817)
02-02 11:16:17.921: E/ExoPlayerImplInternal(25614): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:485)
02-02 11:16:17.921: E/ExoPlayerImplInternal(25614): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
02-02 11:16:17.921: E/ExoPlayerImplInternal(25614): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
02-02 11:16:17.921: E/ExoPlayerImplInternal(25614): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
02-02 11:16:17.921: E/ExoPlayerImplInternal(25614): 	at android.os.Handler.dispatchMessage(Handler.java:98)
02-02 11:16:17.921: E/ExoPlayerImplInternal(25614): 	at android.os.Looper.loop(Looper.java:136)
02-02 11:16:17.921: E/ExoPlayerImplInternal(25614): 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-02 11:16:17.921: E/ExoPlayerImplInternal(25614): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
02-02 11:16:18.131: A/ACodec(25614): frameworks/av/media/libstagefright/ACodec.cpp:3874 CHECK(!keepComponentAllocated) failed.
02-02 11:16:18.131: A/libc(25614): Fatal signal 6 (SIGABRT) at 0x0000640e (code=-6), thread 26098 (CodecLooper)
```

**Comment by ojw28** [comment]
There's insufficient information here for us to do anything. Please read [this](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html) and file a new issue containing all of the information listed there.
