### ISSUE TITLE
MP4 over network

### ISSUE THREAD

**Issue by j-garin** [google/ExoPlayer#1230]
hi.

I'm trying to play an MP4 file from the internet. I use the demo app as the base for my classes.
Here's my RendererBuilder class's buildRenderers method:

```
@Override
  public void buildRenderers(Player player) {
      DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter(player.getMainHandler(), player);

      Allocator allocator = new DefaultAllocator(BUFFER_SEGMENT_SIZE);
      DataSource dataSource = new DefaultHttpDataSource(userAgent, null);
      ExtractorSampleSource videoSampleSource = new ExtractorSampleSource(
              Uri.parse("http://media.achievr.co.s3.amazonaws.com/achievrWelcome.mp4"),
              dataSource, allocator, VIDEO_BUFFER_SEGMENTS * BUFFER_SEGMENT_SIZE);

      MediaCodecVideoTrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(
              context, videoSampleSource,
              MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT);
      ExtractorSampleSource audioSampleSource = new ExtractorSampleSource(
              Uri.parse(url), dataSource, allocator, AUDIO_BUFFER_SEGMENTS * BUFFER_SEGMENT_SIZE);
      MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(
              audioSampleSource);

      TrackRenderer[] renderers = new TrackRenderer[Player.RENDERER_COUNT];
      renderers[Player.TYPE_VIDEO] = videoRenderer;
      renderers[Player.TYPE_AUDIO] = audioRenderer;
      player.onRenderers(renderers, bandwidthMeter);
  }
```

The sound plays fine, but i  keep getting these error messages:
Please give me some hints. Thank you.

```
java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference
    at com.android.okio.OkBuffer.write(OkBuffer.java:574)
    at com.android.okio.OkBuffer.read(OkBuffer.java:610)
    at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:53)
    at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
    at com.android.okhttp.internal.Util.skipAll(Util.java:227)
    at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:216)
    at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:468)
    at com.android.okio.RealBufferedSource.close(RealBufferedSource.java:198)
    at com.android.okio.RealBufferedSource$1.close(RealBufferedSource.java:181)
    at com.google.android.exoplayer.upstream.DefaultHttpDataSource.close(DefaultHttpDataSource.java:270)
    at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:762)
    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by ojw28** [comment]
There's something a little strange about your code. If you're just trying to play a single MP4, why do you have two sample sources. The first one being:

```
ExtractorSampleSource videoSampleSource = new ExtractorSampleSource(
              Uri.parse("http://media.achievr.co.s3.amazonaws.com/achievrWelcome.mp4"),
              dataSource, allocator, VIDEO_BUFFER_SEGMENTS * BUFFER_SEGMENT_SIZE);
```

and the second one being:

```
      ExtractorSampleSource audioSampleSource = new ExtractorSampleSource(
              Uri.parse(url), dataSource, allocator, AUDIO_BUFFER_SEGMENTS * BUFFER_SEGMENT_SIZE);
```

For playing an MP4 you should have a single sample source, that's used by both the audio and video renderers. There's an example [here](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/ExtractorRendererBuilder.java#L64). I'm somewhat confused as to why you don't use `ExtractorRendererBuilder` without modification; it should do what you need.

As a final point, the actual crash you're seeing is because both of your two sample sources are using the same `DataSource`. A `DataSource` can only be used by one thing at once, so if you really do need two sample sources, you should have two `DataSource`s as well.
