### ISSUE TITLE
[Help] Unable to stream some videos

### ISSUE THREAD

**Issue by alirezaaa** [google/ExoPlayer#1238]
Hi,

I wonder why no video player is able to play some videos which are located on my server. May I ask you help me to this problem please?

**Note:** Playing those videos has no problem while they're located on local.
**Note:** I tested them using `MediaPlayer` and `ExoPlayer` and they didn't work.
**Note:** Just one time `ExoPlayer` was able to play those videos!
**Note:** I changed the video codec using a software but it didn't work.

You can have the video [by clicking on this link](http://collectup.blob.core.windows.net/videos/b691c376-f7c1-4256-92f8-a00d30819089.mp4).

Currently `ExoPlayer` cannot play that video and gives following exceptions:

```
> com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://collectup.blob.core.windows.net/videos/b691c376-f7c1-4256-92f8-a00d30819089.mp4
>     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
>     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
>     at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
>     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
>     at android.os.Handler.dispatchMessage(Handler.java:98)
>     at android.os.Looper.loop(Looper.java:135)
>     at android.os.HandlerThread.run(HandlerThread.java:61)
>     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
>  Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://collectup.blob.core.windows.net/videos/b691c376-f7c1-4256-92f8-a00d30819089.mp4
>     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:202)
>     at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
>     at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:713)
>     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>     at java.lang.Thread.run(Thread.java:818)
>  Caused by: java.net.SocketTimeoutException
>     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
>     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
>     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
>     at com.android.okio.Okio$2.read(Okio.java:113)
>     at com.android.okio.RealBufferedSource.indexOf(RealBufferedSource.java:147)
>     at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:94)
>     at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
>     at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
>     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
>     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
>     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
>     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
>     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:199)
>     at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135) 
>     at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:713) 
>     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
>     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
>     at java.lang.Thread.run(Thread.java:818) 
```

**Comment by marcbaechinger** [comment]
When using the url you posted above the video plays fine. I see a firework drawing a latter into the sky. 
Hence this seems to be a network issue to me. Apparently connecting to the server failed.

**Comment by ojw28** [comment]
I was able to play the video successfully too, although playback takes a *long* time to start.

It looks like the root cause for the slow startup is that your server lacks support for range requests. The file contains an index at the end of the file that the player needs before it can start playback. Since your server doesn't support range requests, the only way that the player can get at the index is to download the whole file, which is why the playback takes such a long time to start. Similarly, when seeking, the best the player can do is download the whole file up to the seek point.

For media, you really need a server that supports range requests properly (i.e. the server should respond with a 206 response code and partial content, not a 200 response code).

**Comment by alirezaaa** [comment]
Thank you guys for helping me. I'm able to play that video since a few days ago and there is no problem with playing that video right now but another strange exception will be thrown that I only know its message not the whole exception. It says 'Top bit not zero'. note that this new exception will not throw for the mentioned video.
