### ISSUE TITLE
Decoder error

### ISSUE THREAD

**Issue by pratikpradhan** [google/ExoPlayer#1253]
We have observed that on android 4.1.2 devices exoplayer is not able to play mp4/hls. 
Is there any specific support problem?
Can you tell are we going to fix them?

Below is a stack trace of the error.

```
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): onDecoderInitializationError#Exoplayer
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, 56680, 1280, 720, 0, 1.0, -1, -1, null, 516434000, false, -1, -1)
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:361)
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:723)
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): 	at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:328)
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:484)
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:467)
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): 	at android.os.Looper.loop(Looper.java:137)
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): 	at android.os.HandlerThread.run(HandlerThread.java:60)
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): Caused by: java.lang.IllegalStateException
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): 	at android.media.MediaCodec.getBuffers(Native Method)
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): 	at android.media.MediaCodec.getOutputBuffers(MediaCodec.java:482)
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:359)
02-10 12:44:35.810 E/com.kpoint.android.kapsule.view.ui.media.VideoKapsuleMediaPlayer( 6017): 	... 10 more
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): Internal track renderer error.
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, 56680, 1280, 720, 0, 1.0, -1, -1, null, 516434000, false, -1, -1)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:375)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:361)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:723)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:328)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:484)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:467)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	at android.os.Looper.loop(Looper.java:137)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	at android.os.HandlerThread.run(HandlerThread.java:60)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, 56680, 1280, 720, 0, 1.0, -1, -1, null, 516434000, false, -1, -1)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	... 11 more
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): Caused by: java.lang.IllegalStateException
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	at android.media.MediaCodec.getBuffers(Native Method)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	at android.media.MediaCodec.getOutputBuffers(MediaCodec.java:482)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:359)
02-10 12:44:35.820 E/ExoPlayerImplInternal( 6017): 	... 10 more
```

**Comment by ojw28** [comment]
That doesn't look like an error that would affect all devices running 4.1.2. It looks device specific to me. Please provide more information, as described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html). In particular full bug reports are very useful, as is detailed information about exactly which devices are affected by the issue.
