### ISSUE TITLE
IllegalStateException on TV Sony Bravia 2015

### ISSUE THREAD

**Issue by wkarl** [google/ExoPlayer#1278]
Apparently Exoplayer cannot play two videos simultaneously.

MP4 streams will simply pause when another player instance starts playing which is totally fine for our use case. 

However, HLS streams crash on some devices, even if the stream was paused before starting the second video.

OS version: Android 5.1.1 API 22
Stack trace:
```
E/ExoPlayerImplInternal: Internal runtime error.
   java.lang.IllegalStateException
   at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
   at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:983)
   at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:545)
   at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:485)
   at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
   at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
   at android.os.Handler.dispatchMessage(Handler.java:98)
   at android.os.Looper.loop(Looper.java:135)
   at android.os.HandlerThread.run(HandlerThread.java:61)
   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
02-18 17:31:05.353 16916-16952/com.example.demo
 E/ExoPlayerImplInternal: Stop failed.
   java.lang.IllegalStateException
   at android.media.MediaCodec.native_stop(Native Method)
   at android.media.MediaCodec.stop(MediaCodec.java:628)
   at com.google.android.exoplayer.MediaCodecTrackRenderer.releaseCodec(MediaCodecTrackRenderer.java:441)
   at com.google.android.exoplayer.MediaCodecTrackRenderer.onDisabled(MediaCodecTrackRenderer.java:408)
   at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onDisabled(MediaCodecVideoTrackRenderer.java:289)
   at com.google.android.exoplayer.TrackRenderer.disable(TrackRenderer.java:231)
   at com.google.android.exoplayer.ExoPlayerImplInternal.stopAndDisable(ExoPlayerImplInternal.java:561)
   at com.google.android.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:548)
   at com.google.android.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:525)
   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:247)
   at android.os.Handler.dispatchMessage(Handler.java:98)
   at android.os.Looper.loop(Looper.java:135)
   at android.os.HandlerThread.run(HandlerThread.java:61)
   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by wkarl** [comment]
Update: Nexus Player seems to be affected too

**Comment by wkarl** [comment]
Probably not an exoplayer issue

**Comment by LexJaunt** [comment]
@wkarl did you ever succeed to solve this problem?

**Comment by wkarl** [comment]
Sony confirmed that this particular device only supports one MediaCodec instance so you really only have two choices (I don't think software decoding is a good alternative): you can avoid instantiating two at the same time or catch the exception on affected devices and recover from the error.

Starting from API 23 there is an API to check the maximum number of supported instances: http://developer.android.com/reference/android/media/MediaCodecInfo.CodecCapabilities.html#getMaxSupportedInstances%28%29

Below 23 you could check which device model the app is running on, no idea how many devices have this limitation though.
