### ISSUE TITLE
Exception in demo app playing DASH/Widevine samples, Samsung Galaxy Note 2

### ISSUE THREAD

**Issue by muton** [google/ExoPlayer#129]
Hi, I'm getting a video freeze/halt and exception after a few seconds of playback in the demo app (building from both the current master and dev branches) on a Galaxy Note 2 running Android 4.4.2. This is on the "HDCP required" and "Secure video path required" items. (It may be that the hardware doesn't support these, but in that case I wouldn't expect the videos to start?)  Logs below.

(In general, I'm seeing various problems running the demo with the devices I have access to, is the project at a stage where it should be working well on all/most Android 4.3+ phones and tablets or is there a list of known good devices? Should I report relatively small issues (skipping frames on bitrate switch), or is that too much like fine tuning at this point? Just trying to get a picture of whether we could sensibly use it for a commercial app. If there's a better place/person for that question, that would be great to know.)

```
11-07 20:36:36.831: D/dalvikvm(17003): GC_FOR_ALLOC freed 477K, 58% free 12094K/28656K, paused 34ms, total 34ms
11-07 20:36:37.386: D/dalvikvm(17003): GC_FOR_ALLOC freed 227K, 54% free 13312K/28656K, paused 39ms, total 39ms
11-07 20:36:38.551: E/EventLogger(17003): internalError [11.53, cryptoError]
11-07 20:36:38.551: E/EventLogger(17003): android.media.MediaCodec$CryptoException: Error decrypting data.
11-07 20:36:38.551: E/EventLogger(17003):   at android.media.MediaCodec.queueSecureInputBuffer(Native Method)
11-07 20:36:38.551: E/EventLogger(17003):   at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:573)
11-07 20:36:38.551: E/EventLogger(17003):   at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:405)
11-07 20:36:38.551: E/EventLogger(17003):   at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:397)
11-07 20:36:38.551: E/EventLogger(17003):   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
11-07 20:36:38.551: E/EventLogger(17003):   at android.os.Handler.dispatchMessage(Handler.java:98)
11-07 20:36:38.551: E/EventLogger(17003):   at android.os.Looper.loop(Looper.java:146)
11-07 20:36:38.551: E/EventLogger(17003):   at android.os.HandlerThread.run(HandlerThread.java:61)
11-07 20:36:38.551: E/EventLogger(17003):   at com.google.android.exoplayer.ExoPlayerImplInternal$1.run(ExoPlayerImplInternal.java:109)
11-07 20:36:38.551: E/ExoPlayerImplInternal(17003): Internal track renderer error.
11-07 20:36:38.551: E/ExoPlayerImplInternal(17003): com.google.android.exoplayer.ExoPlaybackException: android.media.MediaCodec$CryptoException: Error decrypting data.
11-07 20:36:38.551: E/ExoPlayerImplInternal(17003):     at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:581)
11-07 20:36:38.551: E/ExoPlayerImplInternal(17003):     at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:405)
11-07 20:36:38.551: E/ExoPlayerImplInternal(17003):     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:397)
11-07 20:36:38.551: E/ExoPlayerImplInternal(17003):     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
11-07 20:36:38.551: E/ExoPlayerImplInternal(17003):     at android.os.Handler.dispatchMessage(Handler.java:98)
11-07 20:36:38.551: E/ExoPlayerImplInternal(17003):     at android.os.Looper.loop(Looper.java:146)
11-07 20:36:38.551: E/ExoPlayerImplInternal(17003):     at android.os.HandlerThread.run(HandlerThread.java:61)
11-07 20:36:38.551: E/ExoPlayerImplInternal(17003):     at com.google.android.exoplayer.ExoPlayerImplInternal$1.run(ExoPlayerImplInternal.java:109)
11-07 20:36:38.551: E/ExoPlayerImplInternal(17003): Caused by: android.media.MediaCodec$CryptoException: Error decrypting data.
11-07 20:36:38.551: E/ExoPlayerImplInternal(17003):     at android.media.MediaCodec.queueSecureInputBuffer(Native Method)
11-07 20:36:38.551: E/ExoPlayerImplInternal(17003):     at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:573)
11-07 20:36:38.551: E/ExoPlayerImplInternal(17003):     ... 7 more
11-07 20:36:38.551: I/ACodec(17003): [OMX.SEC.avc.dec] Now Executing->Idle
11-07 20:36:38.571: I/ACodec(17003): [OMX.SEC.avc.dec] Now Idle->Loaded
11-07 20:36:38.571: I/ACodec(17003): [OMX.SEC.avc.dec] Now Loaded
11-07 20:36:38.581: E/EventLogger(17003): playerFailed [11.56]
11-07 20:36:38.581: E/EventLogger(17003): com.google.android.exoplayer.ExoPlaybackException: android.media.MediaCodec$CryptoException: Error decrypting data.
11-07 20:36:38.581: E/EventLogger(17003):   at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:581)
11-07 20:36:38.581: E/EventLogger(17003):   at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:405)
11-07 20:36:38.581: E/EventLogger(17003):   at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:397)
11-07 20:36:38.581: E/EventLogger(17003):   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
11-07 20:36:38.581: E/EventLogger(17003):   at android.os.Handler.dispatchMessage(Handler.java:98)
11-07 20:36:38.581: E/EventLogger(17003):   at android.os.Looper.loop(Looper.java:146)
11-07 20:36:38.581: E/EventLogger(17003):   at android.os.HandlerThread.run(HandlerThread.java:61)
11-07 20:36:38.581: E/EventLogger(17003):   at com.google.android.exoplayer.ExoPlayerImplInternal$1.run(ExoPlayerImplInternal.java:109)
11-07 20:36:38.581: E/EventLogger(17003): Caused by: android.media.MediaCodec$CryptoException: Error decrypting data.
11-07 20:36:38.581: E/EventLogger(17003):   at android.media.MediaCodec.queueSecureInputBuffer(Native Method)
11-07 20:36:38.581: E/EventLogger(17003):   at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:573)
11-07 20:36:38.581: E/EventLogger(17003):   ... 7 more
11-07 20:36:38.581: I/ACodec(17003):  [OMX.SEC.avc.dec] Now uninitialized
11-07 20:36:38.586: I/ACodec(17003): [OMX.SEC.aac.dec] Now Executing->Idle
11-07 20:36:38.596: I/ACodec(17003): [OMX.SEC.aac.dec] Now Idle->Loaded
11-07 20:36:38.596: I/ACodec(17003): [OMX.SEC.aac.dec] Now Loaded
11-07 20:36:38.596: I/ACodec(17003):  [OMX.SEC.aac.dec] Now uninitialized
```

**Comment by almoghzn** [comment]
Hi ojw28,

I'm looking for solution to my issue (Issue #1116), 
By searching similar posts, I found this one.

You wrote: "The first 5-10 seconds of the streams may be unencrypted (this is common as a way of allowing playback to start in parallel with the keys being requested)"

I debugged a lot the logic of ExoPlayer, and my findings are:
- ALL of my content is encrypted.
- My content packed using Bento4.
- From the first sample I get: sampleHolder.isEncrypted() = true (in "MediaCodecTrackRenderer"."feedInputBuffer")
- Also from the first fragment I see that the flags indicate that the content is encrypted:
"sampleFlags" = C.SAMPLE_FLAG_ENCRYPTED in: "FragmentedMp4Extractor"."readSample".

When I performed the same tests on ExoPlayer's contents like:
"WV: HDCP required", "WV: Secure video path required", etc...
I found that the first 8 seconds (or so) are NOT encrypted. i.e.:
sampleHolder.isEncrypted() = false

Therefore the media of ExoPlayer starts playing immediately while my media stacked.

What is the solution to my problem?

Also, How can I create dash which is DRM encrypted BUT the first ~8 seconds aren't?
