### ISSUE TITLE
Error when playing a second video

### ISSUE THREAD

**Issue by ov-sondeos** [google/ExoPlayer#1301]
I have an application using Exoplayer with Widevine Dash. It opens the first video without problems but when opening the second video is fails (most of the times). And also the third time and further. When trying to play the first opened video again it doesn't work. The only way to make it work again is to restart the application.
The error that it throws is this one:

02-23 12:32:10.671  29640-29640/com.snd.qubitTV E/EventLogger﹕ playerFailed [0.52]
    com.google.android.exoplayer.ExoPlaybackException: android.media.MediaCodec$CryptoException: Unknown Error
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:145)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: android.media.MediaCodec$CryptoException: Unknown Error
            at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
            at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:824)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:484)
            at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:145)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 

I attach one of the .mpd as example.
[mpd.txt](https://github.com/google/ExoPlayer/files/142862/mpd.txt)

Thank you!

**Comment by ojw28** [comment]
Closing because information as requested in the issue template is missing. Please file a new issue with complete information, thanks.
