### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException during MOV playback

### ISSUE THREAD

**Issue by ened** [google/ExoPlayer#1315]
Playback of `Big Buck Bunny.mov` fails due to `java.lang.ArrayIndexOutOfBoundsException`.

This works in the DEMO app - however due to the encoding of the movie on my end, the playback in a integrated Exo Player fails.

Version is from git: 396a19f20cd24bf959ec09914fd898576d1f9f1a (dev branch).

I emailed the link to the G-Drive download to dev.exoplayer@gmail.com, along with the `adb bugreport` output, right after the crash occurred.

```
java.lang.ArrayIndexOutOfBoundsException: src.length=8192 srcPos=-8 dst.length=8192 dstPos=0 length=8
    at java.lang.System.arraycopy(Native Method)
    at com.google.android.exoplayer.extractor.DefaultExtractorInput.updatePeekBuffer(DefaultExtractorInput.java:214)
    at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFromPeekBuffer(DefaultExtractorInput.java:184)
    at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:93)
    at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:104)
    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:228)
    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:124)
    at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:739)
    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:848)
```

**Comment by ojw28** [comment]
Here's another mp4 parsing failure. `srcPos=-8 dst.length=8192 dstPos=0 length=8` looks suspicious ;).

**Comment by AquilesCanta** [comment]
The QuickTime format has a very peculiar format for the udta atom(not present in the MP4 format). A fix/workaround will be available for this soon. Thanks for the issue!

**Comment by dgreenhalgh** [comment]
@AquilesCanta Thanks for following up on the issue so quickly. 

We also ran into this issue - do you have a workaround until the fix makes it in?

**Comment by AquilesCanta** [comment]
@dgreenhalgh, If you are 100% sure that this bug is affecting you,  @andrewlewis suggested, one quick workaround would be to remove TYPE_udta and TYPE_meta from the shouldParseContainerAtom and shouldParseLeafAtom methods in the Mp4Extractor class.

The fix will very likely be available next week in the dev branch.

**Comment by dgreenhalgh** [comment]
@AquilesCanta Thanks! This workaround works for us. Looking forward to the official release.
