### ISSUE TITLE
Facing DRM vendor-defined error: -2902 issues in Nexus 5 

### ISSUE THREAD

**Issue by Amritpal33** [google/ExoPlayer#1316]
I am using Exoplayer version 1.5.6 in my application having DASH based Streaming with Widevine. It is working properly for most of my devices however for one of the Nexus5 device gives the following 

Even the Sample Application(Widevine DASH Policy Tests) is giving the same error in this device.

Exception:

```
02-26 16:50:40.034 17633-17633/com.jio.media.ondemand E/EventLogger: playerFailed [1.60]
                                                                     com.google.android.exoplayer.ExoPlaybackException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.shouldWaitForKeys(MediaCodecTrackRenderer.java:715)
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:649)
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:492)
                                                                         at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                         at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                      Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
                                                                         at android.media.MediaDrm.provideKeyResponse(Native Method)
                                                                         at com.google.android.exoplayer.drm.StreamingDrmSessionManager.onKeyResponse(StreamingDrmSessionManager.java:392)
                                                                         at com.google.android.exoplayer.drm.StreamingDrmSessionManager.access$800(StreamingDrmSessionManager.java:47)
                                                                         at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostResponseHandler.handleMessage(StreamingDrmSessionManager.java:483)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148) 
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                         at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

The Current OS version is 6.0.1. Just wanted to understand what and where exactly is the issue.

**Comment by AquilesCanta** [comment]
I will try this with Widevine DASH Policy Tests sample, but if you could also provide a sample to reproduce this to dev.exoplayer@gmail.com, that would be good.

**Comment by jefftinker** [comment]
See #1468
