### ISSUE TITLE
LibopusAudioTrackRenderer fails with 8 channel audio track

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#1317]
ExoPlayer: v1.5.5

I was recently investigating how well the `LibopusAudioTrackRenderer` worked and testing it with a number of sample files on different devices. I have found that when I attempt to play a specific 8 channel video, ExoPlayer fails. I have then tested this same file on a device which can handle the video via the `MediaCodecAudioTrackRenderer` where it worked fine. Here is the error i'm seeing in the logcat:

```
02-26 13:00:40.794   250  5092 D NvOsDebugPrintf: TVMR: RefreshRate = 60.000000 
02-26 13:00:40.794   250  5092 D NvOsDebugPrintf: TVMR: cbBeginSequence: 985: BeginSequence  1920x1088, bVPR = 0, fFrameRate = 23.975986
02-26 13:00:40.794   250  5092 D NvOsDebugPrintf: TVMR: LowCorner Frequency = 180000 
02-26 13:00:40.794   250  5092 D NvOsDebugPrintf: TVMR: cbBeginSequence: 1360: DecodeBuffers = 5, pnvsi->eCodec = 4, codec = 0 
02-26 13:00:40.798   250  5092 D NvOsDebugPrintf: TVMR: cbBeginSequence: 1419: Display Resolution : (1920x1080) 
02-26 13:00:40.798   250  5092 D NvOsDebugPrintf: TVMR: cbBeginSequence: 1420: Display Aspect Ratio : (1920x1080) 
02-26 13:00:40.798   250  5092 D NvOsDebugPrintf: TVMR: cbBeginSequence: 1460: ColorFormat : 5 
02-26 13:00:40.798   250  5092 D NvOsDebugPrintf: TVMR: cbBeginSequence:1471 ColorSpace = NvColorSpace_YCbCr709
02-26 13:00:40.798   250  5092 D NvOsDebugPrintf: TVMR: cbBeginSequence: 1600: SurfaceLayout = 3
02-26 13:00:40.798   250  5092 D NvOsDebugPrintf: TVMR: cbBeginSequence: 1674: NumOfSurfaces = 9, InteraceStream = 0, InterlaceEnabled = 0, bSecure = 0, MVC = 0 Semiplanar = 1, bReinit = 1, BitDepthForSurface = 8 LumaBitDepth = 8, ChromaBitDepth = 8, ChromaFormat = 5
02-26 13:00:40.798   250  5092 D NvOsDebugPrintf: Allocating new output: 1920x1088 (x 11), ThumbnailMode = 0
02-26 13:00:40.807  3667  5089 D SurfaceUtils: set up nativeWindow 0x20551f4210 for 1920x1088, color 0x146, rotation 0, usage 0x2b00
02-26 13:00:40.807   250   659 E OMXNodeInstance: setParameter(5f:Nvidia.h264.decode, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
02-26 13:00:40.807  3667  5089 W ACodec  : [OMX.Nvidia.h264.decode] setting nBufferCountActual to 15 failed: -1010
02-26 13:00:40.807   250  3430 E OMXNodeInstance: setParameter(5f:Nvidia.h264.decode, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
02-26 13:00:40.807  3667  5089 W ACodec  : [OMX.Nvidia.h264.decode] setting nBufferCountActual to 14 failed: -1010
02-26 13:00:40.835   250  3348 I NvAudioPolicyManager: getOutputForAttr() device 0x400, samplingRate 48000, format 1, channelMask 63f, flags 0
02-26 13:00:40.835   250  3348 I AudioFlinger: openOutput(), module 1 Device 400, SamplingRate 48000, Format 0x000001, Channels 63f, flags 9
02-26 13:00:40.836   250  3348 I AudioFlinger: AudioStreamOut::open(), mHalFormatIsLinearPcm = 1
02-26 13:00:40.836   250  3348 I AudioFlinger: HAL output buffer size 256 frames, normal sink buffer size 256 frames
02-26 13:00:40.837   250  5140 I AudioFlinger: AudioFlinger's thread 0x48279000 ready to run
02-26 13:00:40.838   250  3348 W AudioFlinger: moveEffectChain_l() effect chain for session 0 not on source thread 0x48360000
02-26 13:00:40.842  3667  5010 E android.media.AudioTrack: AudioTrack.write() called with invalid size (10368) value
02-26 13:00:40.843  3667  5010 E ExoPlayerImplInternal: Internal track renderer error.
02-26 13:00:40.843  3667  5010 E ExoPlayerImplInternal: com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.audio.AudioTrack$WriteException: AudioTrack write failed: -2
02-26 13:00:40.843  3667  5010 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.ext.opus.LibopusAudioTrackRenderer.doSomeWork(LibopusAudioTrackRenderer.java:201)
02-26 13:00:40.843  3667  5010 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
02-26 13:00:40.843  3667  5010 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
02-26 13:00:40.843  3667  5010 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
02-26 13:00:40.843  3667  5010 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-26 13:00:40.843  3667  5010 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:148)
02-26 13:00:40.843  3667  5010 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-26 13:00:40.843  3667  5010 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
02-26 13:00:40.843  3667  5010 E ExoPlayerImplInternal: Caused by: com.google.android.exoplayer.audio.AudioTrack$WriteException: AudioTrack write failed: -2
02-26 13:00:40.843  3667  5010 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.audio.AudioTrack.handleBuffer(AudioTrack.java:635)
02-26 13:00:40.843  3667  5010 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.ext.opus.LibopusAudioTrackRenderer.renderBuffer(LibopusAudioTrackRenderer.java:242)
02-26 13:00:40.843  3667  5010 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.ext.opus.LibopusAudioTrackRenderer.doSomeWork(LibopusAudioTrackRenderer.java:194)
02-26 13:00:40.843  3667  5010 E ExoPlayerImplInternal: 	... 7 more
02-26 13:00:40.848   250  5094 D NvOsDebugPrintf: TVMR: TVMRFrameStatusReporting: 5772: Closing TVMR Frame Status Thread -------------
02-26 13:00:40.849   250  5095 D NvOsDebugPrintf: TVMR: TVMRVPRFloorSizeSettingThread: 5590: Closing TVMRVPRFloorSizeSettingThread -------------
02-26 13:00:40.849   250  5093 D NvOsDebugPrintf: TVMR: TVMRFrameDelivery: 5622: Closing TVMR Frame Delivery Thread -------------
02-26 13:00:40.852   250  5090 D NvOsDebugPrintf: TVMR: NvMMLiteTVMRDecBlockClose: 7420: Done
```

Here is the media information associated with the sample file (i'll send a link to the sample file via email):
```
General
Unique ID : 67812056853284594150663291395325434414 (0x33042088DDECB05DAFA6D11AC8CA1A2E)
Complete name : /Users/ian/Downloads/mkv_1920x1080_24.9mbps_h264_8bit_23.976fps_opus-8ch_[68361e663b].mkv
Format : Matroska
Format version : Version 4 / Version 2
File size : 182 MiB
Duration : 1mn 1s
Overall bit rate : 24.9 Mbps
Writing application : Lavf56.40.101
Writing library : Lavf56.40.101 / Lavf56.40.101

Video
ID : 1
Format : AVC
Format/Info : Advanced Video Codec
Format profile : High@L4.1
Format settings, CABAC : Yes
Format settings, ReFrames : 4 frames
Codec ID : V_MPEG4/ISO/AVC
Duration : 1mn 1s
Width : 1 920 pixels
Height : 1 080 pixels
Display aspect ratio : 16:9
Frame rate mode : Constant
Frame rate : 23.976 fps
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Progressive
Language : English
Default : Yes
Forced : No
DURATION : 00:01:01.186000000

Audio
ID : 2
Format : Opus
Codec ID : A_OPUS
Duration : 1mn 1s
Channel(s) : 8 channels
Channel positions : Front: L C R, Side: L R, Rear: L R, LFE
Sampling rate : 48.0 KHz
Bit depth : 32 bits
Compression mode : Lossy
Delay relative to video : 2ms
Writing library : Lavc56.60.100 libopus
Language : English
Default : Yes
Forced : No
DURATION : 00:01:01.071000000

Menu
00:00:00.000 : :02:23:59.631
```

The error occurs when using `LibopusAudioTrackRenderer` on my Nexus 6P and my Nvidia Shield (which is connected to an AVR that can handle 8 channels).

**Comment by vigneshvg** [comment]
i have played back 8 channel audio streams with libopus renderer successfully in the past. can you please share the file with me and i will take a look?

**Comment by IanDBird** [comment]
I emailed the link to both @ojw28 and then the dev.exoplayer@gmail.com address. The issue should be reproducible with that link.

**Comment by vigneshvg** [comment]
@ojw28 could you please forward it to me? thanks!

**Comment by andrewlewis** [comment]
@vigneshvg I've forwarded it. Thanks for taking a look.
