### ISSUE TITLE
Unexpected exception loading stream : java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by desaibhavesh92** [google/ExoPlayer#1320]
E/LoadTask: Unexpected exception loading stream
                                                                       java.lang.ArithmeticException: divide by zero
                                                                           at com.google.android.exoplayer.util.Util.scaleLargeTimestamp(Util.java:474)
                                                                           at com.google.android.exoplayer.dash.mpd.SegmentBase.getPresentationTimeOffsetUs(SegmentBase.java:63)
                                                                           at com.google.android.exoplayer.dash.mpd.Representation.<init>(Representation.java:105)
                                                                           at com.google.android.exoplayer.dash.mpd.Representation.<init>(Representation.java:29)
                                                                           at com.google.android.exoplayer.dash.mpd.Representation$MultiSegmentRepresentation.<init>(Representation.java:239)
                                                                           at com.google.android.exoplayer.dash.mpd.Representation.newInstance(Representation.java:89)
                                                                           at com.google.android.exoplayer.dash.mpd.Representation.newInstance(Representation.java:70)
                                                                           at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.buildRepresentation(MediaPresentationDescriptionParser.java:420)
                                                                           at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseRepresentation(MediaPresentationDescriptionParser.java:408)
                                                                           at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseAdaptationSet(MediaPresentationDescriptionParser.java:258)
                                                                           at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parsePeriod(MediaPresentationDescriptionParser.java:206)
                                                                           at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseMediaPresentationDescription(MediaPresentationDescriptionParser.java:137)
                                                                           at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:101)
                                                                           at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:57)
                                                                           at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93)
                                                                           at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                           at java.lang.Thread.run(Thread.java:841)
E/EventLogger: internalError [6.89, rendererInitError]
                                                                          com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected ArithmeticException: divide by zero
                                                                              at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                              at java.lang.Thread.run(Thread.java:841)
                                                                           Caused by: java.lang.ArithmeticException: divide by zero
                                                                              at com.google.android.exoplayer.util.Util.scaleLargeTimestamp(Util.java:474)
                                                                              at com.google.android.exoplayer.dash.mpd.SegmentBase.getPresentationTimeOffsetUs(SegmentBase.java:63)
                                                                              at com.google.android.exoplayer.dash.mpd.Representation.<init>(Representation.java:105)
                                                                              at com.google.android.exoplayer.dash.mpd.Representation.<init>(Representation.java:29)
                                                                              at com.google.android.exoplayer.dash.mpd.Representation$MultiSegmentRepresentation.<init>(Representation.java:239)
                                                                              at com.google.android.exoplayer.dash.mpd.Representation.newInstance(Representation.java:89)
                                                                              at com.google.android.exoplayer.dash.mpd.Representation.newInstance(Representation.java:70)
                                                                              at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.buildRepresentation(MediaPresentationDescriptionParser.java:420)
                                                                              at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseRepresentation(MediaPresentationDescriptionParser.java:408)
                                                                              at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseAdaptationSet(MediaPresentationDescriptionParser.java:258)
                                                                              at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parsePeriod(MediaPresentationDescriptionParser.java:206)
                                                                              at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseMediaPresentationDescription(MediaPresentationDescriptionParser.java:137)
                                                                              at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:101)
                                                                              at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:57)
                                                                              at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93)
                                                                              at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390) 
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:234) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                                                                              at java.lang.Thread.run(Thread.java:841) 
E/EventLogger: playerFailed [6.95]
                                                                          com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected ArithmeticException: divide by zero
                                                                              at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                              at java.lang.Thread.run(Thread.java:841)
                                                                           Caused by: java.lang.ArithmeticException: divide by zero
                                                                              at com.google.android.exoplayer.util.Util.scaleLargeTimestamp(Util.java:474)
                                                                              at com.google.android.exoplayer.dash.mpd.SegmentBase.getPresentationTimeOffsetUs(SegmentBase.java:63)
                                                                              at com.google.android.exoplayer.dash.mpd.Representation.<init>(Representation.java:105)
                                                                              at com.google.android.exoplayer.dash.mpd.Representation.<init>(Representation.java:29)
                                                                              at com.google.android.exoplayer.dash.mpd.Representation$MultiSegmentRepresentation.<init>(Representation.java:239)
                                                                              at com.google.android.exoplayer.dash.mpd.Representation.newInstance(Representation.java:89)
                                                                              at com.google.android.exoplayer.dash.mpd.Representation.newInstance(Representation.java:70)
                                                                              at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.buildRepresentation(MediaPresentationDescriptionParser.java:420)
                                                                              at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseRepresentation(MediaPresentationDescriptionParser.java:408)
                                                                              at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseAdaptationSet(MediaPresentationDescriptionParser.java:258)
                                                                              at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parsePeriod(MediaPresentationDescriptionParser.java:206)
                                                                              at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseMediaPresentationDescription(MediaPresentationDescriptionParser.java:137)
                                                                              at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:101)
                                                                              at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:57)
                                                                              at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93)
                                                                              at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390) 
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:234) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                                                                              at java.lang.Thread.run(Thread.java:841)

**Comment by AquilesCanta** [comment]
As stated in the issue template, please provide content to reproduce the issue. It is impossible for us to work with the stack trace alone.

**Comment by desaibhavesh92** [comment]
Solved... There is problem in stream, i changed the setting for camera and now its working, mainly issues on different quality of video stream. e.g. 1080p.
