### ISSUE TITLE
Error on playing local mpeg files 

### ISSUE THREAD

**Issue by hoseinit** [google/ExoPlayer#1323]
Hi
I have made Demo app play my local .mpeg files. but when it comes to play files more than 30Mb size it crashes.please advise.

`02-28 15:01:15.533 3469-3527/? E/ACodec: [OMX.ffmpeg.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
02-28 15:01:15.533 3469-3527/? E/OMXNodeInstance: getConfig(1:ffmpeg.h264.decoder, ConfigCommonOutputCrop(0x700000f)) ERROR: Undefined(0x80001001)
02-28 15:01:15.551 3469-3531/? E/SoftMP3: mp3 decoder returned error 1
02-28 15:01:15.552 3469-3530/? E/ACodec: [OMX.google.mp3.decoder] ERROR(0x80001001)
02-28 15:01:15.552 3469-3530/? E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
02-28 15:01:15.552 3469-3530/? E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
02-28 15:01:15.557 3469-3522/? E/ExoPlayerImplInternal: Internal runtime error.
                                                        java.lang.IllegalStateException
                                                            at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                            at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:861)
                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:491)
                                                            at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                            at android.os.Looper.loop(Looper.java:135)
                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
02-28 15:01:15.579 3469-3522/? E/ExoPlayerImplInternal: Stop failed.
                                                        java.lang.IllegalStateException
                                                            at android.media.MediaCodec.native_stop(Native Method)
                                                            at android.media.MediaCodec.stop(MediaCodec.java:628)
                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.releaseCodec(MediaCodecTrackRenderer.java:448)
                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.onDisabled(MediaCodecTrackRenderer.java:413)
                                                            at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.onDisabled(MediaCodecAudioTrackRenderer.java:303)
                                                            at com.google.android.exoplayer.TrackRenderer.disable(TrackRenderer.java:231)
                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.stopAndDisable(ExoPlayerImplInternal.java:561)
                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:548)
                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:525)
                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:247)
                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                            at android.os.Looper.loop(Looper.java:135)
                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
02-28 15:01:15.682 3469-3469/? E/EventLogger: playerFailed [0.31]
                                              com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
                                                  at android.os.Handler.dispatchMessage(Handler.java:98)
                                                  at android.os.Looper.loop(Looper.java:135)
                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                               Caused by: java.lang.IllegalStateException
                                                  at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                  at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:861)
                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:491)
                                                  at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                  at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                  at android.os.Looper.loop(Looper.java:135) 
                                                  at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
`

**Comment by AquilesCanta** [comment]
As stated in the issue template, please provide content to reproduce the issue. It is impossible for us to work with the stack trace alone.

**Comment by hoseinit** [comment]
Hi,
I get a video file from user like:

`Intent pickMedia = new Intent(Intent.ACTION_GET_CONTENT);
pickMedia.setType("video/*");
startActivityForResult(pickMedia, 12345);`

then I Call the PlayerActivity from demo project as below:
`                Uri selectedVideoLocation = data.getData();

                Intent mpdIntent = new Intent(this, PlayerActivity.class)
                        .setData(selectedVideoLocation)
                        .putExtra(PlayerActivity.CONTENT_TYPE_EXTRA, Util.TYPE_OTHER);
                startActivity(mpdIntent);`

it works for small-sized videos but not for large ones.
thank you @AquilesCanta

**Comment by AquilesCanta** [comment]
@hoseinit, please provide a URL. I need whatever you are using as "selectedVideoLocation".

**Comment by hoseinit** [comment]
@AquilesCanta as you can see above I get a media (video) file from user's sdcard and it's not an Online content.

**Comment by AquilesCanta** [comment]
I am sorry, but we need a specific media file to check this. We will not be able to guess which format container you are working with, or which device this is. Exoplayer certainly plays files bigger that 30 MB, so I don't think that is a significant metric.

To sum up, to help you we need to be able to reproduce the problem ourselves, so we need the media sample and the device, if the file is not enough. I assure you, I cannot solve the problem with the provided information.

**Comment by hoseinit** [comment]
I will reopen the issue with more details later @AquilesCanta
