### ISSUE TITLE
HLS VOD Stream from Wowza wont play

### ISSUE THREAD

**Issue by dvpthien** [google/ExoPlayer#1325]
Hi, I am using the latest version to work from wowza server, the stream work well on VLC player.

This is stream: http://52.34.86.42:1935/karaoke/Ai_Kho_Vi_Ai.Que_Van.smil/playlist.m3u8
This is error log:

```
18047-18267 W: Unrecognized profile/level 0/0 for video/mpeg2
18047-18267 W: Unrecognized profile/level 0/2 for video/mpeg2
18047-18267 W: Unrecognized profile/level 0/3 for video/mpeg2
18047-18267 I: Unsupported profile 4 for video/mp4v-es
18047-18077 W: eglSurfaceAttrib not implemented
18047-18077 W: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa25ff2a0, error=EGL_SUCCESS
18047-18077 E: getSlotFromBufferLocked: unknown buffer: 0xabea8190
18047-18077 W: eglSurfaceAttrib not implemented
18047-18077 W: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa1f652c0, error=EGL_SUCCESS
18047-18047 E: internalError [28.03, loadError]
               com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.ProtocolException: unexpected end of stream
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                   at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:140)
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240)
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
                   at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:127)
                   at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
                   at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:115)
                   at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                   at java.lang.Thread.run(Thread.java:818)
                Caused by: java.net.ProtocolException: unexpected end of stream
                   at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:421)
                   at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
                   at com.android.okhttp.internal.http.HttpEngine$2.read(HttpEngine.java:942)
                   at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                   at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:140) 
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240) 
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67) 
                   at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:127) 
                   at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240) 
                   at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:115) 
                   at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                   at java.lang.Thread.run(Thread.java:818) 
18047-18047 E: internalError [124.30, loadError]
               com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.ProtocolException: unexpected end of stream
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                   at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:140)
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240)
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
                   at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:127)
                   at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
                   at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:115)
                   at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                   at java.lang.Thread.run(Thread.java:818)
                Caused by: java.net.ProtocolException: unexpected end of stream
                   at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:421)
                   at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                   at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:140) 
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240) 
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67) 
                   at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:127) 
                   at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240) 
                   at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:115) 
                   at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                   at java.lang.Thread.run(Thread.java:818) 
18047-18047 E: internalError [154.98, loadError]
               com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.ProtocolException: unexpected end of stream
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                   at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:140)
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240)
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
                   at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:127)
                   at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
                   at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:115)
                   at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                   at java.lang.Thread.run(Thread.java:818)
                Caused by: java.net.ProtocolException: unexpected end of stream
                   at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:421)
                   at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                   at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:140) 
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240) 
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67) 
                   at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:127) 
                   at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240) 
                   at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:115) 
                   at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                   at java.lang.Thread.run(Thread.java:818) 
18047-18047 E: internalError [215.40, loadError]
               com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.ProtocolException: unexpected end of stream
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                   at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:140)
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240)
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
                   at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:127)
                   at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
                   at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:115)
                   at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                   at java.lang.Thread.run(Thread.java:818)
                Caused by: java.net.ProtocolException: unexpected end of stream
                   at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:421)
                   at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                   at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:140) 
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240) 
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67) 
                   at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:127) 
                   at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240) 
                   at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:115) 
                   at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                   at java.lang.Thread.run(Thread.java:818) 
18047-18267 E: Internal track renderer error.
               com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.ProtocolException: unexpected end of stream
                   at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                   at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                   at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
                   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                   at android.os.Handler.dispatchMessage(Handler.java:98)
                   at android.os.Looper.loop(Looper.java:148)
                   at android.os.HandlerThread.run(HandlerThread.java:61)
                   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.ProtocolException: unexpected end of stream
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                   at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:140)
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240)
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
                   at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:127)
                   at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
                   at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:115)
                   at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                   at java.lang.Thread.run(Thread.java:818)
                Caused by: java.net.ProtocolException: unexpected end of stream
                   at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:421)
                   at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                   at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:140) 
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240) 
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67) 
                   at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:127) 
                   at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240) 
                   at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:115) 
                   at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                   at java.lang.Thread.run(Thread.java:818) 
18047-18047 E: playerFailed [215.42]
               com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.ProtocolException: unexpected end of stream
                   at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                   at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                   at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
                   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                   at android.os.Handler.dispatchMessage(Handler.java:98)
                   at android.os.Looper.loop(Looper.java:148)
                   at android.os.HandlerThread.run(HandlerThread.java:61)
                   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.ProtocolException: unexpected end of stream
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                   at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:140)
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240)
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
                   at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:127)
                   at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
                   at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:115)
                   at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                   at java.lang.Thread.run(Thread.java:818)
                Caused by: java.net.ProtocolException: unexpected end of stream
                   at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:421)
                   at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                   at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                   at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:140) 
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240) 
                   at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67) 
                   at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:127) 
                   at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240) 
                   at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:115) 
                   at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                   at java.lang.Thread.run(Thread.java:818) 
18047-18047 D: state [215.42, true, I]
```

**Comment by AquilesCanta** [comment]
Have you worked around the fact that the transport stream do not contain audio stream packets somehow? Because it will not play otherwise. One quick way to see whether this is the problem is to comment out the [https://github.com/google/ExoPlayer/blob/b228ccd8d27f66f63e1c7c9983a5002efa43a4b5/library/src/main/java/com/google/android/exoplayer/extractor/ts/TsExtractor.java#L343](TS_STREAM_TYPE_AAC) branch to avoid the AdtsReader from being created. If it plays after that, then there is your issue: the stream is malformed. Please let me know if this solves your issue.

**Comment by ojw28** [comment]
As per the end of https://github.com/google/ExoPlayer/issues/1056, `java.net.ProtocolException: unexpected end of stream` usually indicates an implementation error on the server side. Specifically:

> I think this is indicative of a server providing a Content-Length value in a response header that does not match the length of the response body (the body turns out to be shorter). If my understand is correct, that kind of behavior is invalid from the server.
