### ISSUE TITLE
Error playing local mp4 recorded on LG G4

### ISSUE THREAD

**Issue by RaduPrescura** [google/ExoPlayer#1326]
Noticed an exception being thrown when trying to play videos recorded on the LG G4. 
I tried the same video in the demo application and the result is the same.  Trying to play a video recorded on Nexus 5 works on the G4, but the video recorded on the G4 does not play on either Nexus 5 or G4. 

Devices: LG G4 (LG-H815) - Android 6.0, Nexus 5 - Android 6.0
Exoplayer version: 1.5.6
Video recorded on the G4: https://www.dropbox.com/s/txoxro4jjiueq9z/20160301_155039.mp4?dl=0

Stack trace: 

```
03-01 16:27:55.449 30258-9912/com.google.android.exoplayer.demo E/LoadTask: Unexpected exception loading stream
                                                                            java.lang.IllegalArgumentException
                                                                                at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                                                                                at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:254)
                                                                                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:298)
                                                                                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:239)
                                                                                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:124)
                                                                                at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:732)
                                                                                at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                at java.lang.Thread.run(Thread.java:818)
03-01 16:27:55.456 30258-9912/com.google.android.exoplayer.demo E/LoadTask: Unexpected exception loading stream
                                                                            java.lang.IllegalArgumentException
                                                                                at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                                                                                at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:254)
                                                                                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:298)
                                                                                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:239)
                                                                                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:124)
                                                                                at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:732)
                                                                                at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                at java.lang.Thread.run(Thread.java:818)
03-01 16:27:56.469 30258-9912/com.google.android.exoplayer.demo E/LoadTask: Unexpected exception loading stream
                                                                            java.lang.IllegalArgumentException
                                                                                at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                                                                                at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:254)
                                                                                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:298)
                                                                                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:239)
                                                                                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:124)
                                                                                at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:732)
                                                                                at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                at java.lang.Thread.run(Thread.java:818)
03-01 16:27:58.482 30258-9912/com.google.android.exoplayer.demo E/LoadTask: Unexpected exception loading stream
                                                                            java.lang.IllegalArgumentException
                                                                                at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                                                                                at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:254)
                                                                                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:298)
                                                                                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:239)
                                                                                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:124)
                                                                                at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:732)
                                                                                at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                at java.lang.Thread.run(Thread.java:818)
03-01 16:27:58.487 30258-9909/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                         com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                                                                                             at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                                                                                             at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
                                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                          Caused by: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                                                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                                          Caused by: java.lang.IllegalArgumentException
                                                                                             at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                                                                                             at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:254)
                                                                                             at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:298)
                                                                                             at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:239)
                                                                                             at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:124)
                                                                                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:732)
                                                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                             at java.lang.Thread.run(Thread.java:818) 
03-01 16:27:58.530 30258-30258/com.google.android.exoplayer.demo E/EventLogger: playerFailed [3.12]
                                                                                com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                 Caused by: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                                                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                    at java.lang.Thread.run(Thread.java:818)
                                                                                 Caused by: java.lang.IllegalArgumentException
                                                                                    at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                                                                                    at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:254)
                                                                                    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:298)
                                                                                    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:239)
                                                                                    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:124)
                                                                                    at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:732)
                                                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                    at java.lang.Thread.run(Thread.java:818) 
```

**Comment by AquilesCanta** [comment]
Sorry for the delay! Feel free to ping me if I take too long to respond an issue (there were a few similar bugs available that were waiting for the fix to be pushed. I thought this one was one of them). This is a confirmed bug. Takes place in a specification gray ground. A fix will be available soon, at which point I will close. Thanks for the report.
