### ISSUE TITLE
Mp4Extractor - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by DBradyIE** [google/ExoPlayer#1336]
Pretty self explanatory. Url is below. Nexus 5 - 6.0.1 Security patch 1st Feb 2016

Url: https://cdn.streamable.com/video/mp4/g6l4_1.mp4

I/ExoPlayerImpl: Init 1.5.6
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es

E/AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler

java.lang.ArrayIndexOutOfBoundsException: length=163; index=-1
	at com.google.android.exoplayer.extractor.b.j.b(Mp4Extractor.java:153)
	at com.google.android.exoplayer.extractor.ExtractorSampleSource.d(ExtractorSampleSource.java:615)
	at com.google.android.exoplayer.extractor.ExtractorSampleSource.g(ExtractorSampleSource.java:602)
	at com.google.android.exoplayer.extractor.ExtractorSampleSource.c(ExtractorSampleSource.java:539)
	at com.google.android.exoplayer.extractor.ExtractorSampleSource.b(ExtractorSampleSource.java:487)
	at com.google.android.exoplayer.upstream.o.handleMessage(Loader.java:240)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
	at com.google.android.exoplayer.util.t.run(PriorityHandlerThread.java:40)

**Comment by tao1** [comment]
Following report is not very valueable as I cannot provide test data, but it fails on release 1.5.6, and is also an ArrayIndexOutOfBounds related to Mp4Extractor:
03-07 14:41:25.323  30274-30429/fr.bouyguestelecom.tv.vod W/AudioCapabilities﹕ Unsupported mime audio/mpeg-L2
03-07 14:41:25.324  30274-30429/fr.bouyguestelecom.tv.vod W/AudioCapabilities﹕ Unsupported mime audio/x-ms-wma
03-07 14:41:25.325  30274-30429/fr.bouyguestelecom.tv.vod W/VideoCapabilities﹕ Unsupported mime video/wvc1
03-07 14:41:25.325  30274-30429/fr.bouyguestelecom.tv.vod W/VideoCapabilities﹕ Unsupported mime video/x-ms-wmv
03-07 14:41:25.326  30274-30429/fr.bouyguestelecom.tv.vod W/VideoCapabilities﹕ Unsupported mime video/mjpeg
03-07 14:41:25.330  30274-30429/fr.bouyguestelecom.tv.vod W/VideoCapabilities﹕ Unrecognized level 0 for video/x-vnd.on2.vp8
03-07 14:41:25.337  30274-30429/fr.bouyguestelecom.tv.vod W/VideoCapabilities﹕ Unrecognized profile/level 0/0 for video/mpeg2
03-07 14:41:25.337  30274-30429/fr.bouyguestelecom.tv.vod W/VideoCapabilities﹕ Unrecognized profile/level 0/2 for video/mpeg2
03-07 14:41:25.337  30274-30429/fr.bouyguestelecom.tv.vod W/VideoCapabilities﹕ Unrecognized profile/level 0/3 for video/mpeg2
03-07 14:41:25.355  30274-30429/fr.bouyguestelecom.tv.vod I/VideoCapabilities﹕ Unsupported profile 4 for video/mp4v-es
java.lang.ArrayIndexOutOfBoundsException: src.length=8192 srcPos=-8 dst.length=8192 dstPos=0 length=8
            at java.lang.System.arraycopy(Native Method)
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.updatePeekBuffer(DefaultExtractorInput.java:214)
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFromPeekBuffer(DefaultExtractorInput.java:184)
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:93)
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:104)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:228)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:124)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:732)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)

**Comment by AquilesCanta** [comment]
I think this last message (by @tao1) is not related to this bug, but rather #1315. Also, with less likelihood, could be #1308. I am currently working on this issue.

**Comment by AquilesCanta** [comment]
@DBradyIE, unfortunately the provided media sample includes a single edit list which doesn't include any sync samples. This is currently not supported (mentioned [here](https://github.com/google/ExoPlayer/blob/267a870509bb85e2cff839ea162ae5b7c85933aa/library/src/main/java/com/google/android/exoplayer/extractor/mp4/AtomParsers.java#L261)). This could change in the future, but not for now. Better error reporting will be included in the next release. If you control the file encoding, this is easily fixable.
