### ISSUE TITLE
Non-crashing NullPointerException & IllegalStateException 

### ISSUE THREAD

**Issue by subinkrishna** [google/ExoPlayer#1348]
I keep getting the following exceptions when I use MP4s with an external VTT. Though I see these exceptions, playback is uninterrupted and everything works as expected. Unfortunately I am not allowed to share the video/vtt URLs. I am using Moto X Second Gen running 6.0.

```
E/LoadTask: Unexpected exception loading stream
   java.lang.IllegalStateException: Unbalanced enter/exit
       at com.android.okhttp.okio.AsyncTimeout.enter(AsyncTimeout.java:62)
       at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:209)
       at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:418)
       at com.android.okhttp.internal.Util.skipAll(Util.java:176)
       at com.android.okhttp.internal.Util.discard(Util.java:158)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:435)
       at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:374)
       at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:362)
       at com.google.android.exoplayer.upstream.DefaultHttpDataSource.close(DefaultHttpDataSource.java:270)
       at com.google.android.exoplayer.upstream.DefaultUriDataSource.close(DefaultUriDataSource.java:152)
       at com.google.android.exoplayer.SingleSampleSource.load(SingleSampleSource.java:257)
       at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
E/LoadTask: Unexpected exception loading stream
   java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[], int, int)' on a null object reference
       at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
       at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
       at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:140)
       at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240)
       at com.google.android.exoplayer.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:56)
       at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:388)
       at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:256)
       at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:390)
       at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:129)
       at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:732)
       at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

My code is identical to that of in `ExtractorRendererBuilder` except for `TextRenderer`. Which is as follows:

```java
SingleSampleSource textSampleSource = new SingleSampleSource(
        subtitleUri,
        dataSource,
        MediaFormat.createTextFormat(
                "",
                MimeTypes.TEXT_VTT,
                MediaFormat.NO_VALUE,
                TrackRenderer.MATCH_LONGEST_US,
                "en"));

textRenderer = new TextTrackRenderer(
        textSampleSource,
        this,
        mainHandler.getLooper());
```

**Comment by ojw28** [comment]
You're probably reusing the same dataSource instance for multiple
renderers. This is invalid; you should be using a separate instance for
each one. Does that help?

**Comment by subinkrishna** [comment]
Yes, it works! Thanks for the help.
