### ISSUE TITLE
Decoder init failed: OMX.SEC.AVC.Decoder

### ISSUE THREAD

**Issue by FunnyDevs** [google/ExoPlayer#1352]
Hi! I 'm using exoplayer with a textureview. I found this error on some videos (on some smartphones) only when i apply a trasformation matrix.
this is the log

```
03-10 02:49:48.378 1814-4189/com.videotest.exoplayer E/ACodec: [OMX.SEC.AVC.Decoder] storeMetaDataInBuffers failed w/ err -2147483648
03-10 02:49:48.398 1814-4189/com.videotest.exoplayer E/ACodec: [OMX.SEC.AVC.Decoder] ERROR(0x80001000)
03-10 02:49:48.398 1814-4188/com.videotest.exoplayer E/MediaCodec: Codec reported an error. (omx error 0x80001000, internalError -2147483648)
03-10 02:49:48.398 1814-4090/com.videotest.exoplayer E/dalvikvm: Could not find class 'android.media.MediaCodec$CodecException', referenced from method com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException.getDiagnosticInfoV21
03-10 02:49:48.398 1814-4090/com.videotest.exoplayer W/dalvikvm: VFY: unable to resolve instanceof 227 (Landroid/media/MediaCodec$CodecException;) in Lcom/google/android/exoplayer/MediaCodecTrackRenderer$DecoderInitializationException;
03-10 02:49:48.403 1814-4090/com.videotest.exoplayer D/dalvikvm: VFY: replacing opcode 0x20 at 0x0000
03-10 02:49:48.418 1814-4090/com.videotest.exoplayer E/ExoPlayerImplInternal: Internal track renderer error.
			 com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.SEC.AVC.Decoder, MediaFormat(video/avc, -1, 204, 360, 1.0, -1, -1, 3434000, -1, -1)
				 at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:387)
				 at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
				 at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:739)
				 at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:372)
				 at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:511)
				 at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:492)
				 at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
				 at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
				 at android.os.Handler.dispatchMessage(Handler.java:98)
				 at android.os.Looper.loop(Looper.java:136)
				 at android.os.HandlerThread.run(HandlerThread.java:61)
				 at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
			  Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.SEC.AVC.Decoder, MediaFormat(video/avc, -1, 204, 360, 1.0, -1, -1, 3434000, -1, -1)
				 at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374) 
				 at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:739) 
				 at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:372) 
				 at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:511) 
				 at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:492) 
				 at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417) 
				 at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205) 
				 at android.os.Handler.dispatchMessage(Handler.java:98) 
				 at android.os.Looper.loop(Looper.java:136) 
				 at android.os.HandlerThread.run(HandlerThread.java:61) 
				 at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
			  Caused by: java.lang.IllegalStateException
				 at android.media.MediaCodec.getBuffers(Native Method)
				 at android.media.MediaCodec.getInputBuffers(MediaCodec.java:542)
				 at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:371)
				 at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:739) 
				 at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:372) 
				 at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:511) 
				 at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:492) 
				 at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417) 
				 at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205) 
				 at android.os.Handler.dispatchMessage(Handler.java:98) 
				 at android.os.Looper.loop(Looper.java:136) 
				 at android.os.HandlerThread.run(HandlerThread.java:61) 
				 at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

**Comment by ojw28** [comment]
The issue template asks for more information than is provided here. For example, it states that you should provide a full bugreport and not just a snippet of logcat output. Please file a new issue with complete information.
