### ISSUE TITLE
Attempt to read from field 'java.util.HashMap com.google.android.exoplayer.dash.DashChunkSource$PeriodHolder.representationHolders' on a null object reference

### ISSUE THREAD

**Issue by hyurtseven81** [google/ExoPlayer#1364]
Not always but almost every live stream play, player crashes and it gives nullpointer exception

`java.lang.NullPointerException: Attempt to read from field 'java.util.HashMap com.google.android.exoplayer.dash.DashChunkSource$PeriodHolder.representationHolders' on a null object reference
	at com.google.android.exoplayer.dash.DashChunkSource.getChunkOperation(DashChunkSource.java:463)
	at com.google.android.exoplayer.chunk.ChunkSampleSource.doChunkOperation(ChunkSampleSource.java:561)
	at com.google.android.exoplayer.chunk.ChunkSampleSource.updateLoadControl(ChunkSampleSource.java:435)
	at com.google.android.exoplayer.chunk.ChunkSampleSource.onLoadCompleted(ChunkSampleSource.java:361)
	at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)
	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)`

**Comment by AquilesCanta** [comment]
Unfortunately, to be able to help you, as a starting point, we need information to recreate the error ourselves. Please read the ISSUE_TEMPLATE provided in the root directory of the project. Other important point is that you haven't provide crucial information, like the ExoPlayer version you are using.
