### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 181, size is 181

### ISSUE THREAD

**Issue by hyurtseven81** [google/ExoPlayer#1365]
On mpd live stream sometimes player gives index error

java.lang.IndexOutOfBoundsException: Invalid index 181, size is 181
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at com.google.android.exoplayer.dash.mpd.SegmentBase$MultiSegmentBase.getSegmentTimeUs(SegmentBase.java:193)
	at com.google.android.exoplayer.dash.mpd.Representation$MultiSegmentRepresentation.getTimeUs(Representation.java:267)
	at com.google.android.exoplayer.dash.DashChunkSource$RepresentationHolder.getSegmentStartTimeUs(DashChunkSource.java:925)
	at com.google.android.exoplayer.dash.DashChunkSource.newMediaChunk(DashChunkSource.java:688)
	at com.google.android.exoplayer.dash.DashChunkSource.getChunkOperation(DashChunkSource.java:490)
	at com.google.android.exoplayer.chunk.ChunkSampleSource.doChunkOperation(ChunkSampleSource.java:561)
	at com.google.android.exoplayer.chunk.ChunkSampleSource.updateLoadControl(ChunkSampleSource.java:435)
	at com.google.android.exoplayer.chunk.ChunkSampleSource.onLoadCompleted(ChunkSampleSource.java:361)
	at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)
	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by ojw28** [comment]
The issue template pretty clearly requests substantially more information than is provided here (in particular, it *specifically* states not to just copy a small amount of logcat output). Closing this issue and the other one filed. Please file issues with complete information if you wish us to take a look.

**Comment by hyurtseven81** [comment]
I'm sorry, i will be more clear, when i prepare all information i will reopen this issue with regarding information.

Thanks for your explanation.

**Comment by hyurtseven81** [comment]
I updated the issue description and title and i'm attaching the logcat logs

[IndexOutOfBoundsException.txt](https://github.com/google/ExoPlayer/files/171582/IndexOutOfBoundsException.txt)
[NullObjectReference.txt](https://github.com/google/ExoPlayer/files/171583/NullObjectReference.txt)

**Comment by hyurtseven81** [comment]
i can't reopen therefore i'm adding a new one
