### ISSUE TITLE
H.264 Main Profile level 3.0 encoded HLS not working 

### ISSUE THREAD

**Issue by neo17** [google/ExoPlayer#1378]
Question: Can exoplayer play H.264 Main Profile Level 3.0: avc1.77.30?

My manifest is similar: 

`#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1681000,RESOLUTION=768x432,CODECS="avc1.77.30, mp4a.40.2"
http://***/***,1500k,600k,800k,2500k,400k,200k,1000k,.mp4.csmil/index_0_av.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=749000,RESOLUTION=480x270,CODECS="avc1.77.30, mp4a.40.2"
http://***/***,1500k,600k,800k,2500k,400k,200k,1000k,.mp4.csmil/index_1_av.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=956000,RESOLUTION=640x360,CODECS="avc1.77.30, mp4a.40.2"
http://***/***,1500k,600k,800k,2500k,400k,200k,1000k,.mp4.csmil/index_2_av.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2717000,RESOLUTION=1024x576,CODECS="avc1.77.30, mp4a.40.2"
http://***/***,1500k,600k,800k,2500k,400k,200k,1000k,.mp4.csmil/index_3_av.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=478000,RESOLUTION=320x180,CODECS="avc1.77.30, mp4a.40.2"
http://***/***,1500k,600k,800k,2500k,400k,200k,1000k,.mp4.csmil/index_4_av.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=266000,RESOLUTION=320x180,CODECS="avc1.77.30, mp4a.40.2"
http://***/***,1500k,600k,800k,2500k,400k,200k,1000k,.mp4.csmil/index_5_av.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1163000,RESOLUTION=640x360,CODECS="avc1.77.30, mp4a.40.2"
http://***/***,1500k,600k,800k,2500k,400k,200k,1000k,.mp4.csmil/index_6_av.m3u8
`

- H.264 Main Profile level 3.0 encoded HLS not working 
- Demo app if i try to play my m3u8 i can reproduce the error. I tried the current version of Exoplayer and also r 1.5.0
- ExoPlayer Version: 1.5.6
- Reproducible: Nexus 5, Galaxy s6, Nexus 9 etc
- `E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor, PsExtractor) could read the stream.
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                 Caused by: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor, PsExtractor) could read the stream.
                                                                                    at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:794)
                                                                                    at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:725)
                                                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                    at java.lang.Thread.run(Thread.java:818)`

**Comment by andrewlewis** [comment]
Based on the logging, it looks like the renderers were built using ExtractorRendererBuilder. The error is output because ExtractorSampleSource does not read m3u8 files.

HlsRendererBuilder shows how to build renderers for playing an HLS stream. If you are adding the URL in Samples.java, use Util.TYPE_HLS like [these samples](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/Samples.java#L213).

Regarding H.264 Main profile: before Android M, the Android CDD only required support for Baseline profile, so you can't rely on this format being supported in general (though it may work fine on many devices). The [M CDD](https://static.googleusercontent.com/media/source.android.com/en//compatibility/6.0/android-6.0-cdd.pdf) does require Main profile level 3.1, though.

**Comment by neo17** [comment]
Sorry my mistake for the log. Actually on Android M (Nexus 5) looks working ok. Lower than Android M no guarantee that it will work, the only log you get is: 
`E/EventLogger: internalError [0.18, rendererInitError]`
and this is understandable. 

Thank you for the clarification.
