### ISSUE TITLE
HLS Playlist parser throws integer parse exception on large byte ranges 

### ISSUE THREAD

**Issue by jhowens89** [google/ExoPlayer#1387]
When parsing playlists of large videos, an exception is thrown when a byte range offset is reached that is greater than a 32 bit integer. This occurs upon first loading the playlist.

```
03-22 13:08:15.611  17414-25338/? E/LoadTask﹕ Unexpected exception loading stream
    java.lang.NumberFormatException: Invalid int: "2148607444"
            at java.lang.Integer.invalidInt(Integer.java:138)
            at java.lang.Integer.parse(Integer.java:413)
            at java.lang.Integer.parseInt(Integer.java:367)
            at java.lang.Integer.parseInt(Integer.java:334)
            at com.google.android.exoplayer.hls.HlsPlaylistParser.parseMediaPlaylist(HlsPlaylistParser.java:256)
            at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:129)
            at net.entangledmedia.younity.presentation.view.video.CustomHlsChunkSource$MediaPlaylistChunk.consume(CustomHlsChunkSource.java:679)
            at com.google.android.exoplayer.chunk.DataChunk.load(DataChunk.java:97)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

[playlist.m3u8](https://paste.ee/p/9QV7z)

Exoplayer version currently being used: r1.5.3 
Device and android version is irrelevant.

Why is exoplayer using integers? The only place I see this value being used it is immediately cast to a long in DataSpec's constructor.

**Comment by ojw28** [comment]
Thanks for this. We'll push a fix tomorrow.
