### ISSUE TITLE
internalError [327.87, loadError]

### ISSUE THREAD

**Issue by Jedashford** [google/ExoPlayer#1392]
Version:
compile 'com.google.android.exoplayer:exoplayer:r1.5.6'

We're getting this on an hls stream. I've asked before, but it was indicated this could be a server issue. My question is: How can I see which hls segments are coming through? How can I get networking details on these segments? Such as headers? We have tens of thousands of people watching weekly on here and we're plagued with constant freezing. The video does continue after 10-15seconds after freezing.

```
03-23 10:53:24.064 18577-18577/com.vidangel E/EventLogger: internalError [327.87, loadError]
                                                           com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: timeout
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(SourceFile:260)
                                                               at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(SourceFile:140)
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(SourceFile:77)
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(SourceFile:70)
                                                               at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:99)
                                                               at javax.crypto.CipherInputStream.read(CipherInputStream.java:155)
                                                               at vl.read(SourceFile:101)
                                                               at com.google.android.exoplayer.extractor.DefaultExtractorInput.a(SourceFile:240)
                                                               at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(SourceFile:67)
                                                               at com.google.android.exoplayer.extractor.ts.TsExtractor.read(SourceFile:127)
                                                               at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(SourceFile:240)
                                                               at com.google.android.exoplayer.hls.TsChunk.load(SourceFile:115)
                                                               at ww.run(SourceFile:209)
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                               at java.lang.Thread.run(Thread.java:818)
                                                            Caused by: java.net.SocketTimeoutException: timeout
                                                               at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:207)
                                                               at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
                                                               at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
                                                               at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
                                                               at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:418)
                                                               at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.a(SourceFile:552)
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(SourceFile:258)
                                                               at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(SourceFile:140) 
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(SourceFile:77) 
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(SourceFile:70) 
                                                               at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:99) 
                                                               at javax.crypto.CipherInputStream.read(CipherInputStream.java:155) 
                                                               at vl.read(SourceFile:101) 
                                                               at com.google.android.exoplayer.extractor.DefaultExtractorInput.a(SourceFile:240) 
                                                               at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(SourceFile:67) 
                                                               at com.google.android.exoplayer.extractor.ts.TsExtractor.read(SourceFile:127) 
                                                               at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(SourceFile:240) 
                                                               at com.google.android.exoplayer.hls.TsChunk.load(SourceFile:115) 
                                                               at ww.run(SourceFile:209) 
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                               at java.lang.Thread.run(Thread.java:818) 
```

**Comment by Jedashford** [comment]
Could this be failing to get clips from the server? If so, how can I get access to networking data? I'd love to see the clips failing, why they are failing. We also stream from the Roku and notice the Roku pulls in 20-30+ clips ahead, which prevent many of the buffering issues for our customers. We also have the ability on our web HTML HLS player to pull in as many clips as we want. Any way we can set the length or number of clips we can buffer ahead here in ExoPlayer? This may fix our problems.

**Comment by ojw28** [comment]
This is a `HttpDataSourceException` being printed by an event logger, which is in your own code. `HttpDataSourceException` contains a `dataSpec` that includes information such as the failing request Uri. So you could try looking at that.

ExoPlayer does already buffer head (by a sufficient margin given anything approaching reasonable server performance). You can further increase the buffer size by changing the `BUFFER_SEGMENTS` constants in `HlsRendererBuilder`, if you wish to do so.

**Comment by Jedashford** [comment]
@ojw28 thanks for your support. I'll head into the details. Without your support, we'd be stuck on our Android platform without any good HLS support.
