### ISSUE TITLE
Play two audio tracks at once along with a video 

### ISSUE THREAD

**Issue by srikanth569** [google/ExoPlayer#1420]
I am still trying to Grasp the basics of ExoPlayer so forgive me if this is a silly question. 

Is it possible to add an additional audio track to a video which already has audio and play the three tracks together. 

Something like this : 

        MediaCodecVideoTrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(
                this, sampleSource, MediaCodecSelector.DEFAULT, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT);
        MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(
                sampleSource, MediaCodecSelector.DEFAULT);
        MediaCodecAudioTrackRenderer audioRenderer2 = new MediaCodecAudioTrackRenderer(
                sampleSource, MediaCodecSelector.DEFAULT);

        player = ExoPlayer.Factory.newInstance(3);

        player.prepare(videoRenderer, audioRenderer,audioRenderer2);

This leads to an internal state exception, though.

So can this be done and if so how can this be achieved ? 

An example of this behaviour is the youtube app which lets you add a music track to a  local video file 

![april 5 2016 90639 pm pdt](https://cloud.githubusercontent.com/assets/1894939/14337826/2f4ca5ca-fc26-11e5-9889-5e7f075cb550.png)

**Comment by andrewlewis** [comment]
What is the exception you are referring to? If it relates to having two media clocks, you could try subclassing MediaCodecAudioTrackRenderer, overriding getMediaClock to return null and using this new class as a replacement for one of your audio track renderers. The other audio track renderer, which is still a MediaCodecAudioTrackRenderer, will be the player's media clock. If the exception is something else, please provide a stack trace.

**Comment by srikanth569** [comment]
@andrewlewis 
I was seeing Seeing the error which related to having two media clocks and did exactly what you suggested. That took care of the media clock error but results in an error else where. 

I am able to play the Video and Audio separately but get the following error : 

```
04-10 13:43:31.025 14469-16955/com.srikanth.exoplayerexample E/LoadTask: Unexpected exception loading stream
                                                                         java.lang.IllegalStateException
                                                                             at com.google.android.exoplayer.util.Assertions.checkState(Assertions.java:66)
                                                                             at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:118)
                                                                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:720)
                                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)
04-10 13:43:31.027 14469-16955/com.srikanth.exoplayerexample E/LoadTask: Unexpected exception loading stream
                                                                         java.lang.IllegalStateException
                                                                             at com.google.android.exoplayer.util.Assertions.checkState(Assertions.java:66)
                                                                             at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:118)
                                                                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:720)
                                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)
04-10 13:43:31.047 14469-14510/com.srikanth.exoplayerexample E/Surface: getSlotFromBufferLocked: unknown buffer: 0xba134f18
04-10 13:43:32.035 14469-16955/com.srikanth.exoplayerexample E/LoadTask: Unexpected exception loading stream
                                                                         java.lang.IllegalStateException
                                                                             at com.google.android.exoplayer.util.Assertions.checkState(Assertions.java:66)
                                                                             at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:118)
                                                                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:720)
                                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)
04-10 13:43:34.045 14469-16955/com.srikanth.exoplayerexample E/LoadTask: Unexpected exception loading stream
                                                                         java.lang.IllegalStateException
                                                                             at com.google.android.exoplayer.util.Assertions.checkState(Assertions.java:66)
                                                                             at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:118)
                                                                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:720)
                                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)
04-10 13:43:34.046 14469-16954/com.srikanth.exoplayerexample E/LoadTask: Unexpected exception loading stream
                                                                         java.lang.NullPointerException: Attempt to invoke interface method 'int com.google.android.exoplayer.upstream.UriDataSource.read(byte[], int, int)' on a null object reference
                                                                             at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:140)
                                                                             at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240)
                                                                             at com.google.android.exoplayer.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:130)
                                                                             at com.google.android.exoplayer.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:110)
                                                                             at com.google.android.exoplayer.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:120)
                                                                             at com.google.android.exoplayer.extractor.webm.Sniffer.sniff(Sniffer.java:52)
                                                                             at com.google.android.exoplayer.extractor.webm.WebmExtractor.sniff(WebmExtractor.java:258)
                                                                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:784)
                                                                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:725)
                                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)
04-10 13:43:34.056 14469-16952/com.srikanth.exoplayerexample E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                      com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected NullPointerException: Attempt to invoke interface method 'int com.google.android.exoplayer.upstream.UriDataSource.read(byte[], int, int)' on a null object reference
                                                                                          at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                                                                                          at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                                                                                          at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
                                                                                          at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                          at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                       Caused by: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected NullPointerException: Attempt to invoke interface method 'int com.google.android.exoplayer.upstream.UriDataSource.read(byte[], int, int)' on a null object reference
                                                                                          at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int com.google.android.exoplayer.upstream.UriDataSource.read(byte[], int, int)' on a null object reference
                                                                                          at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:140)
                                                                                          at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240)
                                                                                          at com.google.android.exoplayer.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:130)
                                                                                          at com.google.android.exoplayer.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:110)
                                                                                          at com.google.android.exoplayer.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:120)
                                                                                          at com.google.android.exoplayer.extractor.webm.Sniffer.sniff(Sniffer.java:52)
                                                                                          at com.google.android.exoplayer.extractor.webm.WebmExtractor.sniff(WebmExtractor.java:258)
                                                                                          at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:784)
                                                                                          at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:725)
                                                                                          at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                          at java.lang.Thread.run(Thread.java:818) 
```

**Comment by andrewlewis** [comment]
If you look at the source of the failing assertion, it is caused by calling open on an already open data source. Do you have two SampleSources using the same DataSource? Please post the code that builds the sources and renderers.

**Comment by srikanth569** [comment]
Actually that was the case, I used an extra DataSource and that solved the issue. 
Thank you Andrew. 
For anyone that came here, the following is the solution that worked for me. 

`  //   private static final int BUFFER_SEGMENT_SIZE = 64 * 1024;
        //   private static final int BUFFER_SEGMENT_COUNT = 256;


        videoFrame = (AspectRatioFrameLayout) findViewById(R.id.video_frame);
        surfaceView = (SurfaceView) findViewById(R.id.surface_view);


        Uri uri = Uri.parse(getAVideoUri());
        Uri audioUri = Uri.parse(getAudioUri());


        Allocator allocator = new DefaultAllocator(BUFFER_SEGMENT_SIZE);

        DataSource dataSource = new DefaultUriDataSource(this, null, getUserAgent(this, "ExoPlayerExample"));
        DataSource audioDataSource = new DefaultUriDataSource(this, null, getUserAgent(this, "ExoPlayerExample"));

        ExtractorSampleSource sampleSource = new ExtractorSampleSource(
                uri, dataSource, allocator, BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);

        ExtractorSampleSource audioSample = new ExtractorSampleSource(
                audioUri, audioDataSource, allocator, BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);


        MediaCodecVideoTrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(
                this, sampleSource, MediaCodecSelector.DEFAULT, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT);
        MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(
                sampleSource, MediaCodecSelector.DEFAULT);
        MediaCodecAudioTrackRendererWithNoMediaClock secondAudioRenderer = new MediaCodecAudioTrackRendererWithNoMediaClock(
                audioSample, MediaCodecSelector.DEFAULT);
        player = ExoPlayer.Factory.newInstance(3);

        player.prepare(videoRenderer, audioRenderer, secondAudioRenderer);
        player.sendMessage(videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, surfaceView.getHolder().getSurface());
        player.setPlayWhenReady(true);`
