### ISSUE TITLE
com.google.android.exoplayer.demo E/MediaDrm-JNI: Illegal state exception: Failed to handle key response: DRM vendor-defined error

### ISSUE THREAD

**Issue by tiger1990** [google/ExoPlayer#1432]
Please search the existing issues before filing a new one, including issues that are closed. When filing a new issue please include all of the following, unless you're certain that they're not useful for the particular issue being reported.

- A description of the issue.
- Steps describing how the issue can be reproduced, ideally in the ExoPlayer demo app.
- A link to content that reproduces the issue. If you don't wish to post it publicly, please submit the issue, then email the link to dev.exoplayer@gmail.com including the issue number in the subject line.
- The version of ExoPlayer being used.
- The device(s) and version(s) of Android on which the issue can be reproduced, and how easily it reproduces. If possible, please test on multiple devices and Android versions.
- A bug report taken from the device just after the issue occurs, attached as a file. A bug report can be captured using "adb bugreport". Output from "adb logcat" or a log snippet is not sufficient.

**Comment by tiger1990** [comment]
I have found these logs : I was trying to play widevine sample given in exoplayer 
Got this issue in Nexus 5 and Lennovo 

com.google.android.exoplayer.demo E/MediaDrm-JNI: Illegal state exception: Failed to handle key response: DRM vendor-defined error: -2902 (-2902)
04-06 13:26:43.085 14713-14713/com.google.android.exoplayer.demo E/EventLogger: internalError [2.60, drmSessionManagerError]
                                                                                android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
                                                                                    at android.media.MediaDrm.provideKeyResponse(Native Method)
                                                                                    at com.google.android.exoplayer.drm.StreamingDrmSessionManager.onKeyResponse(StreamingDrmSessionManager.java:392)
                                                                                    at com.google.android.exoplayer.drm.StreamingDrmSessionManager.access$800(StreamingDrmSessionManager.java:45)
                                                                                    at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostResponseHandler.handleMessage(StreamingDrmSessionManager.java:482)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
04-06 13:26:43.092 14713-15537/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                          com.google.android.exoplayer.ExoPlaybackException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.shouldWaitForKeys(MediaCodecTrackRenderer.java:680)
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:630)
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:459)
                                                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                              at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                           Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
                                                                                              at android.media.MediaDrm.provideKeyResponse(Native Method)
                                                                                              at com.google.android.exoplayer.drm.StreamingDrmSessionManager.onKeyResponse(StreamingDrmSessionManager.java:392)
                                                                                              at com.google.android.exoplayer.drm.StreamingDrmSessionManager.access$800(StreamingDrmSessionManager.java:45)
                                                                                              at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostResponseHandler.handleMessage(StreamingDrmSessionManager.java:482)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                              at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
04-06 13:26:43.104 14713-14713/com.google.android.exoplayer.demo E/EventLogger: playerFailed [2.62]
                                                                                com.google.android.exoplayer.ExoPlaybackException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.shouldWaitForKeys(MediaCodecTrackRenderer.java:680)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:630)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:459)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                 Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
                                                                                    at android.media.MediaDrm.provideKeyResponse(Native Method)
                                                                                    at com.google.android.exoplayer.drm.StreamingDrmSessionManager.onKeyResponse(StreamingDrmSessionManager.java:392)
                                                                                    at com.google.android.exoplayer.drm.StreamingDrmSessionManager.access$800(StreamingDrmSessionManager.java:45)
                                                                                    at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostResponseHandler.handleMessage(StreamingDrmSessionManager.java:482)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
04-06 13:26:43.104 14713-14713/com.google.android.exoplayer.demo D/EventLogger: droppedFrames [2.62, 2]
04-06 13:26:43.138 14713-15587/com.google.android.exoplayer.demo D/SurfaceUtils: set up nativeWindow 0xaebbb208 for 1x1, color 0x2, rotation 0, usage 0x930
04-06 13:26:44.216 14713-14713/com.google.android.exoplayer.demo D/EventLogger: state [3.73, true, I]​

**Comment by ojw28** [comment]
If you want us to look at your issue, please provide the information requested in the issue template. The issue as it stands ignores every single bullet point, including the last one that explicitly states: **Output from "adb logcat" or a log snippet is not sufficient.**. Please file a new issue containing complete information.

**Comment by tiger1990** [comment]
**Description:** I have installed the sample app given in exoplayer, I tried to play a widevine sample on given below device(Configuration are mentioned below). And got the above log.
(Error Log :  com.google.android.exoplayer.demo E/MediaDrm-JNI: Illegal state exception: Failed to handle key response: DRM vendor-defined error: -2902 (-2902)
04-06 13:26:43.085 14713-14713/com.google.android.exoplayer.demo E/EventLogger: internalError [2.60, drmSessionManagerError])
# Brief log is given above

**Configuration Of Device On Which Getting This Error:**
Below are the configuration of Nexus Device On Which i am getting this error:
Model : Nexus 5
Android Version: 6.0.1
BaseBand Version: M8974A-2.0.50.2.28
Kernel Version 
3.4.0-gbaedb01
android-build@vped10.mtv.corp.google.com#1
Sat Jan 16 01:19:53 UTC 2016
Build Number: MMB29V

I have tried this sample on multiple android devices.
Some of the devices giving me this error.
eg. Htc, Lyf, Lenovo 
You can easily reproduce this error on the above mention configuration of Nexus 5.
