### ISSUE TITLE
Not Playing m3u8 wrapped mp3

### ISSUE THREAD

**Issue by sujitkjha** [google/ExoPlayer#1436]
I'm using exomedia built over exoplayer, while playing m3u8 wrapped mp4 play correctly but playing mp3 wrapped will give error,

Please help I have tried to find the solution all around but nothing till now. Please see the error log

```
04-12 11:38:13.365 16820-16820/com.newitventure.bindass W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
04-12 11:38:13.385 16820-16820/com.newitventure.bindass W/VideoCapabilities: Unsupported mime video/x-ms-wmv
04-12 11:38:13.385 16820-16820/com.newitventure.bindass W/AudioCapabilities: Unsupported mime audio/qcelp
04-12 11:38:13.385 16820-16820/com.newitventure.bindass W/AudioCapabilities: Unsupported mime audio/x-ms-wma
04-12 11:38:13.385 16820-16820/com.newitventure.bindass W/AudioCapabilities: Unsupported mime audio/qcelp
04-12 11:38:13.385 16820-16820/com.newitventure.bindass W/VideoCapabilities: Unsupported mime video/x-ms-wmv
04-12 11:38:13.425 16820-16820/com.newitventure.bindass I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
04-12 11:38:13.485 16820-17267/com.newitventure.bindass D/libc: [NET] android_getaddrinfofornet+,hn 15(0x3230322e313636),sn(),hints(known),family 0,flags 4
04-12 11:38:13.485 16820-17267/com.newitventure.bindass D/libc: [NET] android_getaddrinfofornet-, SUCCESS
04-12 11:38:13.625 16820-17267/com.newitventure.bindass D/libc: [NET] android_getaddrinfofornet+,hn 15(0x3230322e313636),sn(),hints(known),family 0,flags 4
04-12 11:38:13.625 16820-17267/com.newitventure.bindass D/libc: [NET] android_getaddrinfofornet-, SUCCESS
04-12 11:38:13.875 16820-17267/com.newitventure.bindass D/libc: [NET] android_getaddrinfofornet+,hn 15(0x3230322e313636),sn(),hints(known),family 0,flags 4
04-12 11:38:13.875 16820-17267/com.newitventure.bindass D/libc: [NET] android_getaddrinfofornet-, SUCCESS
04-12 11:38:14.945 16820-17267/com.newitventure.bindass D/libc: [NET] android_getaddrinfofornet+,hn 15(0x3230322e313636),sn(),hints(known),family 0,flags 4
04-12 11:38:14.945 16820-17267/com.newitventure.bindass D/libc: [NET] android_getaddrinfofornet-, SUCCESS
04-12 11:38:16.975 16820-17267/com.newitventure.bindass D/libc: [NET] android_getaddrinfofornet+,hn 15(0x3230322e313636),sn(),hints(known),family 0,flags 4
04-12 11:38:16.975 16820-17267/com.newitventure.bindass D/libc: [NET] android_getaddrinfofornet-, SUCCESS
04-12 11:38:17.005 16820-17263/com.newitventure.bindass E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                 com.google.android.exoplayer.ExoPlaybackException: java.io.EOFException
                                                                                     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                                                                                     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:155)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                  Caused by: java.io.EOFException
                                                                                     at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:245)
                                                                                     at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
                                                                                     at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:127)
                                                                                     at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
                                                                                     at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:115)
                                                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                     at java.lang.Thread.run(Thread.java:818)
04-12 11:38:17.025 16820-16820/com.newitventure.bindass D/EMPlaylistService: Retrying audio playback.  Retry count: 1
```

**Comment by andrewlewis** [comment]
Please could you provide a URL to sample media that reproduces this error when played in the ExoPlayer demo app?

**Comment by sujitkjha** [comment]
For Mp3 link is ---http://202.166.193.113:8081/music/JeenaJeena.mp3/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9NC8xMi8yMDE2IDc6NDM6NDkgQU0maGFzaF92YWx1ZT1lM0t6MEV4S3NWSHVxdVZwTTR4NlVRPT0mdmFsaWRtaW51dGVzPTUwMDA=

For mp4 link is --http://nettv.truestreamz.com:8081/nettvmovies/mobile/nep/PUNTEPARADE.mp4/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9NC8xMi8yMDE2IDc6NDM6NDkgQU0maGFzaF92YWx1ZT1lM0t6MEV4S3NWSHVxdVZwTTR4NlVRPT0mdmFsaWRtaW51dGVzPTUwMDA= @andrewlewis

**Comment by andrewlewis** [comment]
For the MP3 case, could you try using .mp3 as the chunk file extension instead of .ts? The chunks seem to play correctly when using Mp3Extractor (see [HlsChunkSource](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/hls/HlsChunkSource.java#L492)).

**Comment by huzaifa0024** [comment]
http://mjmobil.azurewebsites.net/Pages/Play/Media/858_1_3117.m3u8
EOF exception when i try to play this track.
Can anyone please tell me whats causing it.

**Comment by andrewlewis** [comment]
The media segment URIs have a last path segment of ".aspx". This isn't recognized so we default to treating them as MPEG TSs rather than MP3s, which means their contents are parsed incorrectly.

The easiest fix for now is to make the media segments end ".mp3". At some point we may determine which extractor to use based on the contents of the segments (like how ExtractorSampleSource's sniffs the container).

By the way, it looks like you might be using Azure to generate the streams. If so, we'd advise using DASH or Smooth Streaming instead of HLS, in which case you won't encounter this problem.
