### ISSUE TITLE
Cannot play mp3 that has meta data as thumbnail 

### ISSUE THREAD

**Issue by vsay01** [google/ExoPlayer#1445]
I used the ExoMedia repository that is a wrapper of the ExoPlayer itself and the issue seems to point to ExoPlayer as described in the log below.

ExoMedia version: 2.5.5
Device OS version: 6.0
Devide Manufacturer: Moto
Device Name: G

**Reproduction Steps**

Play song mp3 whose meta data has thumbnail

**Expected Result**

song play

**Actual Result**

Error as following:

```
ExoPlayerImplInternal: Internal track renderer error.
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor, PsExtractor) could read the stream.
                                                                                        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                                                                                        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                     Caused by: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor, PsExtractor) could read the stream.
                                                                                        at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:794)
                                                                                        at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:725)
                                                                                        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                        at java.lang.Thread.run(Thread.java:818)
```
**Noted:**
I removed the meta thumbnail from the mp3 file, and it can play well.

**Comment by AquilesCanta** [comment]
Can you please provide media to reproduce this issue? You can either post it here or send it to dev.exoplayer@gmail.com and then post here so that I look for it.

**Comment by daividssilverio** [comment]
I sent you an .mp3 that doesn't work

**Comment by AquilesCanta** [comment]
Hi, thanks to the invaluable help of @andrewlewis, we have come to the conclusion that the software you are using to add the thumbnail is faulty. Long story short, the file has an invalid prefix of ~55KB which is a copy of the real ID3 info (that contains the thumbnail). If you remove this prefix, you will get an MP3 file that contains the thumbnail and is playable. Due to this error, the length of the first ID3 header ends up being too far away from the first MP3 frame header, and so the MP3 sniffer gives up before finding it.

By the way, if you could add some information regarding how you added the thumbnail, that would be great.

**Comment by vsay01** [comment]
@AquilesCanta Thank for the information
@daividssilverio thank for the given music file..
