### ISSUE TITLE
BehindLiveWindowException for Wowza-generated DASH-stream

### ISSUE THREAD

**Issue by perchrh** [google/ExoPlayer#1450]
Immediate stream playback failure occurs when loading certain DASH streams. 
The stack trace is shown below.

Reproduce by loading the stream in ExoPlayer demo app. 
ExoPlayer 1.5.6 and 1.5.7 has this issue, possibly other versions. 
The issue is not device nor Android-version specific. 
The issue may be related to mpd-parsing, as the same stream works with a different style of manifest. The working stream has a SegmentTemplate style manifest, and the failing stream has a SegmentList type manifest. 

A test stream that reproduces this issue, as well as the other stream mentioned, have been sent to dev.exoplayer@gmail.com.

<pre><code>
E/ExoPlayerImplInternal: Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.BehindLiveWindowException
        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
        at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:441)
        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:211)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.BehindLiveWindowException
        at com.google.android.exoplayer.dash.DashChunkSource$RepresentationHolder.updateRepresentation(DashChunkSource.java:923)
        at com.google.android.exoplayer.dash.DashChunkSource$PeriodHolder.updatePeriod(DashChunkSource.java:1023)
        at com.google.android.exoplayer.dash.DashChunkSource.processManifest(DashChunkSource.java:767)
        at com.google.android.exoplayer.dash.DashChunkSource.continueBuffering(DashChunkSource.java:335)
        at com.google.android.exoplayer.chunk.ChunkSampleSource.continueBuffering(ChunkSampleSource.java:220)
        at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:127)
        at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:211) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
</code></pre>

**Comment by ojw28** [comment]
Hm. I managed to hack around and make this style of mpd work, but I'm not clear on whether the mpd is in violation of the DASH spec, or whether ExoPlayer is. The DASH spec is quite nuanced/complicated/non-intuitive when it comes to assigning start times and durations to segments in this kind of manifest, so it'll take a bit of thought.

As an aside, you should probably use the templated style of manifest regardless, since they're generally more concise.

**Comment by ojw28** [comment]
Marking as bug for now, although this is really pending further investigation.

**Comment by perchrh** [comment]
Turns out that this stream also does not play in Chrome (v49), with the Dash Reference Client. 
http://dashif.org/reference/players/javascript/v2.1.0/samples/dash-if-reference-player/index.html
That points towards the manifest being invalid. 

(I didn't think of checking the stream with the Reference Client at first.)

The error from the reference player is:
<pre><code>
Cannot read property 'presentationStartTime' of undefined
</code>
</pre>

**Comment by ojw28** [comment]
Closing for now, since it'll take us quite a long time to figure it out vs. what the spec defines. Please re-open if the combination of Wowza + DashIF determine it to be valid. Given Wowza seem to have issues with compatibility in other areas too, I'm suspecting it's invalid.

**Comment by peyoh** [comment]
Hello,
this timeline causes the error. 

```
        <SegmentTemplate timescale="90000" initialization="edash-video-1080.mp4" media="edash-video-1080-$Number$.mp4" startNumber="2427">
          <SegmentTimeline>
            <S t="8817032752" d="900000" r="4320"/>
            <S t="4118878160" d="900000" r="75"/>
          </SegmentTimeline>
        </SegmentTemplate>
```
