### ISSUE TITLE
BufferDrained on switching to background

### ISSUE THREAD

**Issue by frakc** [google/ExoPlayer#1454]
When I switch application from foreground to background I get following error
```java
E/BufferQueue: [unnamed-29079-0] queueBuffer: BufferQueue has been abandoned!
E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
E/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] BaseState::onOutputBufferDrained returning error -19
E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -19)
E/ExoPlayerImplInternal: Internal runtime error.
                         java.lang.IllegalStateException
                             at android.media.MediaCodec.releaseOutputBuffer(Native Method)
                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.renderOutputBuffer(MediaCodecVideoTrackRenderer.java:480)
                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.processOutputBuffer(MediaCodecVideoTrackRenderer.java:446)
                             at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:914)
                             at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:512)
                             at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                             at android.os.Handler.dispatchMessage(Handler.java:98)
                             at android.os.Looper.loop(Looper.java:146)
                             at android.os.HandlerThread.run(HandlerThread.java:61)
                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
I/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] Now Executing->Idle
E/EventLogger: playerFailed [9.17]
               com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
                   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
                   at android.os.Handler.dispatchMessage(Handler.java:98)
                   at android.os.Looper.loop(Looper.java:146)
                   at android.os.HandlerThread.run(HandlerThread.java:61)
                   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                Caused by: java.lang.IllegalStateException
                   at android.media.MediaCodec.releaseOutputBuffer(Native Method)
                   at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.renderOutputBuffer(MediaCodecVideoTrackRenderer.java:480)
                   at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.processOutputBuffer(MediaCodecVideoTrackRenderer.java:446)
                   at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:914)
                   at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:512)
                   at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                   at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
                   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                   at android.os.Looper.loop(Looper.java:146) 
                   at android.os.HandlerThread.run(HandlerThread.java:61) 
                   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```
If i select             `player.setSelectedTrack(DemoPlayer.TYPE_VIDEO, -1);` , then i dont have this error. Unfortunatly its only help if it was set before `onPaused called`

**Comment by ojw28** [comment]
You're most likely trying to access surface after it's been destroyed. The ExoPlayer demo app does not suffer from these problems. I suggest you look at how it works. Specifically, look at how `PlayerActivity` implements `SurfaceHolder.Callback`, to ensure that the player doesn't try and use a surface after `surfaceDestroyed` is invoked.

**Comment by neo17** [comment]
I have a similar but not the same issue. Here is my log: 

`04-20 12:42:26.266 183-200/? E/Parcel: dup() failed in Parcel::read, i is 0, fds[i] is -1, fd_count is 1, error: Bad file descriptor
04-20 12:42:26.267 183-200/? E/BufferQueueProducer: [de.rtl2apps.you.buildtest/de.rtl2apps.you.activities.HomeActivity] queueBuffer: fence is NULL
04-20 12:42:26.267 11278-11429/? E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22`

In my case i can reproduce this only sometimes if I release the player, destory the surface and then recreate the player and the surface. If i do this at the begining it works, but after several times it gives me this error and the queueBuffer is blocked resulting in the screen being totally blocked and not redrawing anymore. 
Is it the same that I'm trying to access an destroyed surface? 

Thanks

**Comment by volser** [comment]
I have the same issue. My log:

```
E/BufferQueue: [unnamed-2053-10] queueBuffer: BufferQueue has been abandoned!
E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -19)
E/ExoPlayerImplInternal: Internal runtime error.
                                                                        java.lang.IllegalStateException
                                                                            at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:889)
                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:512)
                                                                            at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
W/BufferQueue: [unnamed-2053-10] cancelBuffer: BufferQueue has been abandoned!
```

**Comment by saurabhkpatel** [comment]
@frakc : i have the same issue, how did you solve this? Can you please help me?
