### ISSUE TITLE
m3u8 : InvalidResponseCodeException

### ISSUE THREAD

**Issue by brucetoo** [google/ExoPlayer#1459]
- A description of the issue.
  ```java
 
                                                                                com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:275)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                 Caused by: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
                                                                                    at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
                                                                                    at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
                                                                                    at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:107)
                                                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                    at java.lang.Thread.run(Thread.java:818) 

 ```
- A link to content that reproduces the issue can find in this url,
just use the value of key “m3u8”  [m3u8 list](http://192.168.229.152:7701/live/live_list?gametype=3)
- The version of ExoPlayer is newest.
- The device(s) (Nexus 5x)and version(6.0.1) of Android may happen everywhere

I just test my m3u8 url and it work fine in VLC media player

**Comment by andrewlewis** [comment]
ExtractorSampleSource does not read m3u8 files, which is why the exception is thrown.

The URL seems to be on your private network, but you probably need to use an HlsSampleSource instead, as in [HlsRendererBuilder](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/HlsRendererBuilder.java).

**Comment by brdn** [comment]
hi @andrewlewis ,
for mp3 url i have no problem, but i with this way i can't hear any of hls stream. how can i use hlssamplesource for my app? (i'm not a developer)

`        protected Boolean doInBackground(final String... args) {

            try {
                Uri uri;

                if (station.getRadiourl().endsWith(".m3u")) {
                    uri = Uri.parse(Parser.parse(station.getRadiourl()));
                }
            else {
                    uri = Uri.parse(station.getRadiourl());
                }

                Allocator allocator = new DefaultAllocator(BUFFER_SEGMENT_SIZE);
                String userAgent = Util.getUserAgent(context, "ExoPlayerDemo");
                OkHttpClient okHttpClient = new OkHttpClient();
                //DataSource dataSource = new DefaultUriDataSource(context, null, userAgent);

                DataSource dataSource = new DefaultUriDataSource(context, null,
                        new OkHttpDataSource(okHttpClient, userAgent, null, null, CacheControl.FORCE_NETWORK));

                ExtractorSampleSource sampleSource = new ExtractorSampleSource(uri, dataSource, allocator,
                        BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);

                // audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource);

                MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource,
                        MediaCodecSelector.DEFAULT, null, true, null, null,
                        AudioCapabilities.getCapabilities(context), AudioManager.STREAM_MUSIC);

                exoPlayer.prepare(audioRenderer);

                return true;

            } catch (IllegalArgumentException e1) {

            } catch (IllegalStateException e1) {

            } catch (SecurityException e1) {

            }
            return false;
        }`

and Parser.Java
`public class Parser {

    public static String parse(String urlM3u) {

        String ligne = null;

        try {
            URL urlPage = new URL(urlM3u);
            HttpURLConnection connection = (HttpURLConnection) urlPage.openConnection();
            InputStream inputStream = connection.getInputStream();
            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream));

            StringBuffer stringBuffer = new StringBuffer();

            while ((ligne = bufferedReader.readLine()) != null) {
                if (ligne.contains("http")) {
                    connection.disconnect();
                    bufferedReader.close();
                    inputStream.close();
                    return ligne;
                }
                stringBuffer.append(ligne);
            }

            connection.disconnect();
            bufferedReader.close();
            inputStream.close();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }
}`

**Comment by brucetoo** [comment]
I ony change the Demo project in ```PlayerActivity``` 
And 

```
   case Util.TYPE_HLS:
        return new HlsRendererBuilder(this, userAgent, "http://cgi.v.cc.163.com/redirect/video/600111.m3u8?secret=17fb308fe7");
```

**Comment by andrewlewis** [comment]
@brdn I suggest using the demo app as a starting point, and making sure you can play your streams there. If not, please file a new issue and include the information requested in the template. We can only address issues that relate directly to ExoPlayer on this issue tracker I'm afraid.

@brucetoo The chunks are being fetched with a base URI before redirection. I will take a look at fixing this.

**Comment by brdn** [comment]
ok will open a new issue
Thank you

**Comment by ojw28** [comment]
Fixed in dev.
