### ISSUE TITLE
Handling onRenderersError and ExoPlayer.Listener errors

### ISSUE THREAD

**Issue by j-t-h** [google/ExoPlayer#1463]
My ExoPlayer wrapper class implements ExoPlayer.Listener and my Activity also implements this ExoPlayer.Listener. 

On the 
`public void onError(Exception e)` 

of the activity, what instances of Exceptions should I try to reset and play the stream again? Only instances of ExoPlaybackException?

Also is the best way to retry
`playerNeedsPrepare = true;`
 `preparePlayer(true);`

Thanks.

**Comment by ojw28** [comment]
`ExoPlayer.Listener` doesn't define an `onError(Exception e)` method, it defines ` onPlayerError(ExoPlaybackException)`, so I'm a little unsure as to what question you're asking.

In general though, `onPlayerError(ExoPlaybackException)` will only be called for errors where the player has failed to recover internally, or doesn't think that it will be able to. So you shouldn't retry automatically in any case when this method is invoked. It's more appropriate to display a retry button to the user, to allow them to retry manually if they wish to do so.

**Comment by j-t-h** [comment]
Sorry for the confusion. I have my activity that extends the ExoPlayer.Listener.

Reading early posts about the BehindLiveWindowException, although you stated that the source of the stream should be addressed, it was also said that retrying was the next best solution.

In the activity that contains the ExoPlayer object, my listener

`@Override`
`public void onError(Exception e) {`

I have 

`else if (e instanceof ExoPlaybackException && e.getCause() instanceof BehindLiveWindowException)` `{`
          `    _playerNeedsPrepare = true;`
            `    preparePlayer(true);`
       `}`

Is this acceptable or should I be doing something else?

Here are some examples of the other exceptions I am seeing

Non-fatal Exception: com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
       at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
       at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
Caused by java.lang.IllegalStateException
       at android.media.MediaCodec.queueInputBuffer(MediaCodec.java)
       at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:672)
       at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:492)
       at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
       at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
       at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
       at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

Non-fatal Exception: com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException: Buffer too small (176640 < 176699)
       at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
       at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
Caused by java.lang.IllegalStateException: Buffer too small (176640 < 176699)
       at com.google.android.exoplayer.SampleHolder.createReplacementBuffer(SampleHolder.java:148)
       at com.google.android.exoplayer.SampleHolder.ensureSpaceForWrite(SampleHolder.java:100)
       at com.google.android.exoplayer.extractor.RollingSampleBuffer.readSample(RollingSampleBuffer.java:189)
       at com.google.android.exoplayer.extractor.DefaultTrackOutput.getSample(DefaultTrackOutput.java:142)
       at com.google.android.exoplayer.hls.HlsExtractorWrapper.getSample(HlsExtractorWrapper.java:201)
       at com.google.android.exoplayer.hls.HlsSampleSource.readData(HlsSampleSource.java:338)
       at com.google.android.exoplayer.SampleSourceTrackRenderer.readSource(SampleSourceTrackRenderer.java:209)
       at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:588)
       at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:492)
       at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
       at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
       at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
       at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by ojw28** [comment]
- It can make sense to automatically retry for `BehindLiveWindowException` in the case that you know it's likely to occur with the source media due to the live window being too small. You'd probably want to put some kind of limit on it though; something like only allowing the automatic retry once every 30 seconds or something, so as to make sure you don't end up in an infinite cycle of retrying where the source media is completely broken.
- The last of the stack traces you posted (buffer too small) is definitely not a recoverable exception. It's a bug where the decoder input buffer isn't large enough. Attempting to play the same piece of media again will result in exactly the same failure. You should file a separate issue for that, containing all information requested in the issue template (including a full bug report).
- The first of the stack traces you posted should not really be considered recoverable. If that's happening mid-playback, it might be a device issue or an issue with the source media. It's not possible to tell with the information provided.
