### ISSUE TITLE
HLS from Wowza wont play - Index out of bounds

### ISSUE THREAD

**Issue by Marcin666** [google/ExoPlayer#1464]
Hi,
I try to implement Exo in my app. When i try to use any of my m3u8 sources by just changing paths in demo app - it shows only:

```
04-22 21:10:08.965 589-676/system_process W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client due to mismatching sample rate (48000 vs 44100)
04-22 21:10:08.965 242-395/? D/AudioFlinger: start(4100), calling pid 589 session 35
04-22 21:10:08.965 242-395/? D/AudioFlinger: ? => ACTIVE (4100) on thread 0x5ebac0
04-22 21:10:08.975 13452-13452/com.google.android.exoplayer.demo D/EventLogger: state [10.06, true, P]
04-22 21:10:09.135 13452-13575/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                          java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                                              at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                              at java.util.ArrayList.get(ArrayList.java:308)
                                                                                              at com.google.android.exoplayer.hls.HlsChunkSource.selectTrack(HlsChunkSource.java:349)
                                                                                              at com.google.android.exoplayer.hls.HlsChunkSource.prepare(HlsChunkSource.java:256)
                                                                                              at com.google.android.exoplayer.hls.HlsSampleSource.prepare(HlsSampleSource.java:149)
                                                                                              at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(SampleSourceTrackRenderer.java:54)
                                                                                              at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:110)
                                                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:273)
                                                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:264)
                                                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:201)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                              at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
04-22 21:10:09.155 13452-13452/com.google.android.exoplayer.demo E/EventLogger: playerFailed [10.24]
                                                                                com.google.android.exoplayer.ExoPlaybackException: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                 Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                                    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                    at java.util.ArrayList.get(ArrayList.java:308)
                                                                                    at com.google.android.exoplayer.hls.HlsChunkSource.selectTrack(HlsChunkSource.java:349)
                                                                                    at com.google.android.exoplayer.hls.HlsChunkSource.prepare(HlsChunkSource.java:256)
                                                                                    at com.google.android.exoplayer.hls.HlsSampleSource.prepare(HlsSampleSource.java:149)
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(SampleSourceTrackRenderer.java:54)
                                                                                    at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:110)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:273)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:264)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:201)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                    at android.os.Looper.loop(Looper.java:136) 
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
04-22 21:10:09.155 13452-13452/com.google.android.exoplayer.demo D/EventLogger: state [10.24, true, I]
```

Of couse nothing plays.
Demo of HLS: 
http://hls8.webcamera.pl/babki_dvr/babki_dvr.stream/playlist.m3u8
http://hls8.webcamera.pl/rakoniewice_cam_e1c271/rakoniewice_cam_e1c271.stream/playlist.m3u8

Those path works in VLC, Samsung Smart TV, Android native webView <video> tag and many more. What is wrong with Exo?

**Comment by Marcin666** [comment]
Some update.This error happens n Sony Xperia Mini Pro with Cyanogen mod Android 4.4.4. Doesnt happen on Honor 7 with Android 5.1.  Xperia Z with Android 5.1 also plays fine.

**Comment by mindcollapse** [comment]
I have the same problem with DemoPlayer with latest 1.5.7 version, it happens on that stream http://144.76.3.3:1935/live/bvntv_aac/playlist.m3u8

**Comment by ojw28** [comment]
The HLS playlists you've linked to only contain 720p and 1080p streams. HD resolutions are beyond the capabilities of low end (or older) devices. It's also a massive waste of bandwidth and battery to be streaming HD video to devices that have low resolution screens. The Sony Xperia Mini Pro has a screen resolution of 320x480, so sending it 720p is sending it 6 times as many pixels as the physical display can display.

The video isn't played because the device reports that its not capable to play it. The solution is to provide lower resolution variants in your HLS master playlist, so that one appropriate to the device can be selected for playback. ExoPlayer should also report a clearer error in this case, which is tracked by https://github.com/google/ExoPlayer/issues/1545.

**Comment by rajeshgoswami2025** [comment]
m3u8 link --https://res.cloudinary.com/db4xehbhz/video/upload/sp_hd/v1470669815/What_is_diabetes_-_Diabetes_UK_x2y8ys.m3u8

*_getting crash when playing video on genymotion marshmallow emulator  *_ 
when i am playing above url it is running smooth in marshmallow (one plus one device )
com.google.android.exoplayer.ExoPlaybackException: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:148)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at com.google.android.exoplayer.hls.HlsChunkSource.selectTrack(HlsChunkSource.java:392)
            at com.google.android.exoplayer.hls.HlsChunkSource.prepare(HlsChunkSource.java:299)
            at com.google.android.exoplayer.hls.HlsSampleSource.prepare(HlsSampleSource.java:149)
            at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(SampleSourceTrackRenderer.java:54)
            at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:110)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:273)
            at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:264)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:201)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:148)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by makvasic** [comment]
Hi,

I'm having the same problem as @Marcin666 but for me it's working normally on pre lollipop devices only.

Working: 
- TESLA Tablet 785 (4.2.2)
- S3 (4.4.2)

Not working:
- S4 (5.1)
- LG G3 (6.0),

which means that problem is not in low resolution screen in this case.

This is the [stream](http://148.251.85.99:1935/edutv/edutelevizija/playlist.m3u8) in question and MxPlayer plays it without any problems on all devices.

Any help is appreciated.

Thank you for your work and support.
Looking forward to Exo V2.

Cheers.

**Comment by AquilesCanta** [comment]
@rajeshgoswami2025 @makvasic , when you need to report a potential bug, please open a new issue. If you think the information in another issue is useful, just provide a link to it. Otherwise it is possible that it will get overlooked. Keep this in mind. 
On top of this:
@rajeshgoswami2025 : Unfortunately I cannot reproduce the issue in a device. Did you manage to achieve this? Emulators are not usually great for this. Please file a new issue with some more context (I will add some more related information below).
@makvasic : This usually happens because the declared resolution has an odd element. In this case, the manifest contains `RESOLUTION=1047x576`. As @ojw28 pointed out, it is the manifest that is malformed. The actual video is 720x576, so if you ignore that part of the manifest (or correct it, if you have access to the serving of the content), it will play correctly. 

I think both issues are related to renderer capabilities, that is why it is device dependent. I would suggest you start giving it a try to the version 2 that is a bit smarter in this aspect. If you still haven't solved your problems, please file a new issue.

**Comment by makvasic** [comment]
Thank you for the fast response.
I didn't open a new issue because I saw that @ojw28 is still in participant list but thanks for clarification, was wondering what was right way to go.

OK, the good thing is it's not API level dependent.
I tested other streams from @rajeshgoswami2025 and @Marcin666 and they all works without problems even on emulator (Nexus 6 API 23).

Thanks once again, cheers.
