### ISSUE TITLE
EOFException during playback of specific ogg file

### ISSUE THREAD

**Issue by zsmatyas** [google/ExoPlayer#1506]
Ogg sample throws and exception. Might be a problem with the content, but I cannot tell the cause at the moment. Other ogg files play correctly.

**CALLSTACK**
```
 java.io.EOFException
at com.google.android.exoplayer.extractor.ogg.OggUtil.populatePageHeader(OggUtil.java:108)
at com.google.android.exoplayer.extractor.ogg.OggReader.readGranuleOfLastPage(OggReader.java:119)
at com.google.android.exoplayer.extractor.ogg.OggVorbisExtractor.read(OggVorbisExtractor.java:118)
at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:836)
at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

**Repro steps:**
- Add sample to Samples.java:

`new Sample( "Short ogg file", "http://www.w3schools.com/tags/horse.ogg", Util.TYPE_OTHER),`
- attempt to play it

**Content:**
`http://www.w3schools.com/tags/horse.ogg`
**
The version of ExoPlayer being used:**
```
    android:versionCode="1507"
    android:versionName="1.5.7"
```

- Reproduced on all android devices I have, like Nexus 5x, Nexus player.

[bugreport.txt](https://github.com/google/ExoPlayer/files/252903/bugreport.txt)

**Comment by ojw28** [comment]
@marcbaechinger - Could you take a look at this?

- Where does the `-8000` come from in VorbisReader.read? Could this be made a named constant or could an inline comment be added for clarification?
- After seeking to `length-8000` readGranuleOfLastPage finds lots of page headers, but none for which the condition to exit the while loop is true. I think the file probably doesn't have "last page" flag set on the last page. It should be trivial to handle this case by breaking out of the loop if the input's position ends up being equal to its length after the body for the previous page has been skipped?

**Comment by marcbaechinger** [comment]
Yes, that's right. Seems to have no last page. I'll take a look. Thanks.

**Comment by marcbaechinger** [comment]
This is fixed in the dev branch. I tested with the horse sample. Thanks for reporting!

https://github.com/google/ExoPlayer/commit/45e9020c5a61e4baf99860911c76faa2b7d58476
