### ISSUE TITLE
ssl issue with the demo player

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#1514]
Hi,

We have enabled ssl on our widevine proxy. After that it is giving this error. Do we have to add CA certificate explicitly? Because other apps are working without issues with same certificate.
We are using ssl certificate from Godaddy. 

```
E/ExoPlayerImplInternal( 2112): com.google.android.exoplayer.ExoPlaybackException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal( 2112):         at com.google.android.exoplayer.MediaCodecTrackRenderer.shouldWaitForKeys(MediaCodecTrackRenderer.java:694)
E/ExoPlayerImplInternal( 2112):         at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:644)
E/ExoPlayerImplInternal( 2112):         at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:473)
E/ExoPlayerImplInternal( 2112):         at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
E/ExoPlayerImplInternal( 2112):         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
E/ExoPlayerImplInternal( 2112):         at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 2112):         at android.os.Looper.loop(Looper.java:136)
E/ExoPlayerImplInternal( 2112):         at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 2112):         at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/ExoPlayerImplInternal( 2112): Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal( 2112):         at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:410)
E/ExoPlayerImplInternal( 2112):         at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
E/ExoPlayerImplInternal( 2112):         at com.android.okhttp.Connection.connect(Connection.java:107)
E/ExoPlayerImplInternal( 2112):         at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
E/ExoPlayerImplInternal( 2112):         at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
E/ExoPlayerImplInternal( 2112):         at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
E/ExoPlayerImplInternal( 2112):         at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
E/ExoPlayerImplInternal( 2112):         at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
E/ExoPlayerImplInternal( 2112):         at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
E/ExoPlayerImplInternal( 2112):         at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:254)
E/ExoPlayerImplInternal( 2112):         at com.google.android.exoplayer.util.Util.executePost(Util.java:692)
E/ExoPlayerImplInternal( 2112):         at com.google.android.exoplayer.demo.WidevineTestMediaDrmCallback.executeKeyRequest(WidevineTestMediaDrmCallback.java:60)
E/ExoPlayerImplInternal( 2112):         at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostRequestHandler.handleMessage(StreamingDrmSessionManager.java:505)
E/ExoPlayerImplInternal( 2112):         at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 2112):         at android.os.Looper.loop(Looper.java:136)
E/ExoPlayerImplInternal( 2112):         at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 2112): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal( 2112):         at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:282)
E/ExoPlayerImplInternal( 2112):         at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:202)
E/ExoPlayerImplInternal( 2112):         at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:612)
E/ExoPlayerImplInternal( 2112):         at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/ExoPlayerImplInternal( 2112):         at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
E/ExoPlayerImplInternal( 2112):         ... 15 more
E/ExoPlayerImplInternal( 2112): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal( 2112):         ... 20 more
````

Please guide,

Regards,
Randeep

**Comment by ojw28** [comment]
Have you looked around for solutions to the exception ("Trust anchor for certification path not found")? It feels to me like something is wrong with your setup.
