### ISSUE TITLE
icecast mp3 streaming is not working in api level 19

### ISSUE THREAD

**Issue by jojoimteaj** [google/ExoPlayer#1527]
I'm trying to stream a mp3-radio-url ([http://streaming211.radionomy.com:80/Rey-de-Corazones](url)) using ExoPlayer Android 1.5.8 library. It is perfeclty playing/working in Android Api Level 16, 17, 18, 22 etc. ONLY not working in api level 19/Android 4.4 kitkat, I have tried both emulator and physical phone. I have also tried other radio urls, no luck!

This is my code :

```
private static final int BUFFER_SEGMENT_SIZE = 64 * 1024;
private static final int BUFFER_SEGMENT_COUNT = 256;
...
...
Allocator allocator = new DefaultAllocator(BUFFER_SEGMENT_SIZE);
String userAgent = Util.getUserAgent(context, "Exo Player Demo");
OkHttpClient okHttpClient = new OkHttpClient();

DataSource dataSource = new DefaultUriDataSource(context, null,
                    new OkHttpDataSource(okHttpClient, userAgent, null, null, CacheControl.FORCE_NETWORK));

ExtractorSampleSource sampleSource = new ExtractorSampleSource(uri, dataSource, allocator,
                    BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);

audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource,
                    MediaCodecSelector.DEFAULT, null, true, null, null,
                    AudioCapabilities.getCapabilities(context), AudioManager.STREAM_MUSIC);

exoPlayer.prepare(audioRenderer);
```

and this code is throwing Error :

```
com.revs.streamradio E/android.media.AudioTrack: getMinBufferSize(): error querying hardware
com.revs.streamradio E/AudioTrack-JNI: Error creating AudioTrack: Could not get AudioSystem frame count.
com.revs.streamradio E/android.media.AudioTrack: Error code -16 when initializing AudioTrack.
com.revs.streamradio E/ExoPlayerImplInternal: Internal track renderer error.
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 44100)
    at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:385)
    at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:915)
    at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:512)
    at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
    at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:136)
    at android.os.HandlerThread.run(HandlerThread.java:61)
    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
 Caused by: com.google.android.exoplayer.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 44100)
    at com.google.android.exoplayer.audio.AudioTrack.checkAudioTrackInitialized(AudioTrack.java:915)
    at com.google.android.exoplayer.audio.AudioTrack.initialize(AudioTrack.java:481)
    at com.google.android.exoplayer.audio.AudioTrack.initialize(AudioTrack.java:455)
    at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:379)
    at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:915) 
    at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:512) 
    at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
    at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434) 
    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
    at android.os.Handler.dispatchMessage(Handler.java:98) 
    at android.os.Looper.loop(Looper.java:136) 
    at android.os.HandlerThread.run(HandlerThread.java:61) 
    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

Anyone can tell me what's wrong here? Thanks! :+1:

**Comment by jojoimteaj** [comment]
@ojw28 Can you please help? stuck here for couple of days... sorry for the tag.

**Comment by ojw28** [comment]
It feels quite unlikely that you're seeing that exact error on both an emulator and a real device. Please attach separate bug reports for the emulator and the phones, taken using `adb bugreport`. Note that copy/pasting sections of log is not sufficient. Thanks!

**Comment by jojoimteaj** [comment]
@ojw28 Okay, I've attached `bug.txt` of emulator taken using `adb bugreport`. Real device is bit away from me now. I will upload whenever I get it in hand. Thanks.

[bug.txt](https://github.com/google/ExoPlayer/files/266107/bug.txt)

**Comment by ojw28** [comment]
It's the real device we're interested in (emulators often have spurious issues related to media playback), so we'll take a look once that bug report is provided.

**Comment by andrewlewis** [comment]
The stream plays fine for me on a Nexus 5 (build KTU84Q) running the demo app from the `dev` branch.

**Comment by ojw28** [comment]
Closing due to lack of information (i.e. a full bug report from a real device).
