### ISSUE TITLE
Unable to play HLS

### ISSUE THREAD

**Issue by PooriaFarhad** [google/ExoPlayer#1534]
Hello,

We are trying to play hls from this source:
http://hw1.vedas.ir/hls/mp4/3q1mj9DGTjEVZoA68fuc/smil:chunk.smil/playlist.m3u8
Bug report:
```
internalError [2.01, rendererInitError]
                                                           java.lang.IllegalStateException: No variants selected.
                                                               at ir.vedas.vedas.player.ExoPlayerHlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(ExoPlayerHlsRendererBuilder.java:82)
                                                               at ir.vedas.vedas.player.ExoPlayerHlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(ExoPlayerHlsRendererBuilder.java:46)
                                                               at com.google.android.exoplayer.util.ManifestFetcher$SingleFetchHelper.onLoadCompleted(ManifestFetcher.java:378)
                                                               at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:135)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
05-16 05:12:21.882 3651-3651/ir.vedas.vedas E/PlayerActivity: onError player : No variants selected.
05-16 05:12:21.882 3651-3651/ir.vedas.vedas E/EventLogger: playerFailed [2.01]
                                                           java.lang.IllegalStateException: No variants selected.
                                                               at ir.vedas.vedas.player.ExoPlayerHlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(TwExoPlayerHlsRendererBuilder.java:82)
                                                               at ir.vedas.vedas.player.ExoPlayerHlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(ExoPlayerHlsRendererBuilder.java:46)
                                                               at com.google.android.exoplayer.util.ManifestFetcher$SingleFetchHelper.onLoadCompleted(ManifestFetcher.java:378)
                                                               at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:135)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
[Full bug report](https://github.com/google/ExoPlayer/files/266164/bugreport.txt)
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es

**Comment by ojw28** [comment]
Please take a full bug report with `adb bugreport` and attach it to this issue.

**Comment by PooriaFarhad** [comment]
ok, It has been attached.
[FULL BUG REPORT](https://github.com/google/ExoPlayer/files/266164/bugreport.txt)

**Comment by ojw28** [comment]
The emulator you're attempting to run your app on claims that it can't play any of the variants (even the 480x270 one). Depending on whether the emulator is supposed to support video playback, this is either working as intended or a bug specific to that emulator. Please file an issue on whoever provides the emulator (AndroVM?).

Note that this issue is unlikely to reproduce on real Android devices. We recommend testing video playback on physical hardware.

**Comment by PooriaFarhad** [comment]
Unfortunately, it doesn't work on physical hardware too.
Please take a look at physical device (4.1.1) full report.
[bugreport (2).txt](https://github.com/google/ExoPlayer/files/266452/bugreport.2.txt)
 debug

**Comment by ojw28** [comment]
Do you see the issue on all devices, or just that one (and the emulator)? Could you also provide a working media link? The one at the top of this issue used to work, but is now returning 403 (FORBIDDEN). Thanks!

**Comment by PooriaFarhad** [comment]
It is working on android 4.2.2 (two physical hardware has been tested)
but not working on android 4.1.1 and Genymotion Emulator.

Source is available now:
http://hw1.vedas.ir/hls/mp4/2bJvTRGIzTLdO7XpD4jz/smil:chunk.smil/playlist.m3u8

What is your idea?

**Comment by ojw28** [comment]
Is it a single device not working on 4.1.1, or multiple devices running 4.1.1?

**Comment by ojw28** [comment]
Also, on the affected device, what value does `MediaCodecUtil.maxH264DecodableFrameSize` return?

**Comment by PooriaFarhad** [comment]
I do not have multiple device for 4.1.1.
You mean 4.1.1 physical device, it returns 101376.

**Comment by ojw28** [comment]
As a test only, does playback work properly if you hardcode `maxH264DecodableFrameSize` to return `384000` instead? The device's decoder is advertising a very low level of video support, which is why playback doesn't proceed correctly. It's likely a device specific issue; and is unlikely to be a widespread problem.

We could/should add a few sanity checks around maxH264DecodableFrameSize to guard against incorrect values. Specifically, we could check that the value we get is at least the frame size recorded by the device's camera, since there pretty much aren't devices that can't play back video recorded on the device!

**Comment by PooriaFarhad** [comment]
Is it a sustainable approach to add additional lower bitrate to the playlist? (for example 128kbps)

**Comment by ojw28** [comment]
It's resolution rather than bitrate that's the problem. If you were to go low enough then it would work, but it would provide a poor user experience. Instead, we should be doing more to correctly determine the true capability of the device. Please test having `maxH264DecodableFrameSize` return `384000` on the affected device.

**Comment by PooriaFarhad** [comment]
test result:

```
Internal track renderer error.
                                                                                          com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
```


so, What is the solution?

**Comment by ojw28** [comment]
Please can you provide more detailed information. The very top line of a stack trace isn't exactly useful. Please provide a full bug report taken just after the issue described above occurs.

**Comment by PooriaFarhad** [comment]
This is what we have changed in the MediaCodecUtil class:

public static int maxH264DecodableFrameSize() throws DecoderQueryException {
   /* if (maxH264DecodableFrameSize == -1) {
      int result = 0;
      DecoderInfo decoderInfo = getDecoderInfo(MimeTypes.VIDEO_H264, false);
      if (decoderInfo != null) {
        for (CodecProfileLevel profileLevel : decoderInfo.capabilities.profileLevels) {
          result = Math.max(avcLevelToMaxFrameSize(profileLevel.level), result);
        }
      }
      maxH264DecodableFrameSize = result;
    }*/
    return maxH264DecodableFrameSize = 384000;
  }

corresponding bug report can be accessed from here ([bugreport.txt](https://github.com/google/ExoPlayer/files/268694/bugreport.3.txt)
)

**Comment by ojw28** [comment]
Please take the bug report immediately after reproducing the issue (I would expect to see some relevant logging in the report if so - so either you didn't do this or something weird is happening capturing bug reports from this device). Either way, we really need the full stack trace of the "Internal track renderer error." issue you're seeing with this modification in place (either in a bug report or pasted here). That looks like a secondary issue, so the way forward here would be to fix the secondary issue, and then try again with the modification in place.

**Comment by ojw28** [comment]
Please pull the very latest `dev` branch, which will include the change ref'd above. Then modify `MediaCodecUtil` in the same way you have been doing (to return `384000` from `maxH264DecodableFrameSize`). Does playback then work correctly? Thanks!

**Comment by PooriaFarhad** [comment]
Yes! now it works correctly even with Genymotion.
so, Should we use it as a solution?

**Comment by ojw28** [comment]
You should definitely not use that as a general solution. It will restrict the ability to play higher quality streams unnecessarily on many devices. We'll have a think about what the long term fix should be.

**Comment by PooriaFarhad** [comment]
Thank you so much.
We have to release the app. What do you suggest for temporary solution?

**Comment by ojw28** [comment]
Can you please provide another working link (I'm guessing they're expiring). Or better, attach or paste a sample master playlist into this issue. Thanks.

**Comment by PooriaFarhad** [comment]
Available source:
http://hw1.vedas.ir/hls/mp4/yD0bHvb6hS4fLZKGTimO/smil:chunk.smil/playlist.m3u8

Thanks

**Comment by ojw28** [comment]
I would expect that source to play something (the 144p variant) even without making the test workaround. Is that quality new since the issue was originally filed?

**Comment by ojw28** [comment]
Note that the emulator is effectively irrelevant for the purposes of launching the app, since real users don't run apps in emulators. So it's really the physical device that we're interested in.

**Comment by PooriaFarhad** [comment]
Sorry, I just updated all the sources.
now check this please:
http://hw1.vedas.ir/hls/mp4/3q1mj9DGTjEVZoA68fuc/smil:chunk.smil/playlist.m3u8

**Comment by ojw28** [comment]
The change above should "fix" this issue by assuming that all devices are capable of playing back H264 videos whose total number of pixels don't exceed 172800 (480*360). This should allow the affected device to play the lowest quality variant that you're generating.

It would be further possible to add device specific workarounds to maxH264DecodableFrameSize conditional on Util.DEVICE, Util.SDK_INT and so on, which could enable them to play higher quality variants if we can verify that they really are capable of doing so. We probably wont do this unless we see significant demand and/or find a really popular device that would benefit from us doing this.
