### ISSUE TITLE
IllegalArgumentException in extractor.mp4.AtomParsers.parseStbl playing a video

### ISSUE THREAD

**Issue by fujunwei** [google/ExoPlayer#1559]
Most of video source is played finely except
`http://pcvideoyd.titan.mgtv.com/mp4/2016/zongyi/txdxqt_52216/62A9757A1712E4CBDF6DF9B8CC58F2DA_20160529_1_1_386.mp4?uuid=12d9555a04894080837b6563217cf3ed&t=574c3436&pno=1031&sign=c0ff64fb053c5ec0b1dc07bdb8147e4d&win=300&srgid=25009&urgid=632&srgids=25009&nid=25009&payload=usertoken%3dhit%3d0%5eruip%3d3227962430&rdur=21600&arange=900&limitrate=0&fid=62A9757A1712E4CBDF6DF9B8CC58F2DA&ver=0x03`

I am using the latest ExoPlayer.

The detail logs:
05-30 13:37:23.223 3415-3527/com.miui.networkassistant.deamon I/XiaomiFirewall: firewall pkgName:com.google.android.exoplayer.demo, result:0x0
05-30 13:37:23.503 27315-27578/com.google.android.exoplayer.demo E/LoadTask: Unexpected exception loading stream
                                                                             java.lang.IllegalArgumentException
                                                                                 at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                                                                                 at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:227)
                                                                                 at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:312)
                                                                                 at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:254)
                                                                                 at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:245)
                                                                                 at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:130)
                                                                                 at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:836)
                                                                                 at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                 at java.lang.Thread.run(Thread.java:841)
05-30 13:37:23.503 27315-27315/com.google.android.exoplayer.demo E/EventLogger: internalError [2.08, loadError]
                                                                                com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                                                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                    at java.lang.Thread.run(Thread.java:841)
                                                                                 Caused by: java.lang.IllegalArgumentException
                                                                                    at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                                                                                    at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:227)
                                                                                    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:312)
                                                                                    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:254)
                                                                                    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:245)
                                                                                    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:130)
                                                                                    at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:836)
                                                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                    at java.lang.Thread.run(Thread.java:841)

**Comment by AquilesCanta** [comment]
I get a 403. Can you fix this?

**Comment by fujunwei** [comment]
Thanks for your quick reply. The uri have expired, you can get the file from 
https://www.dropbox.com/s/074mc8naqlrxnd0/FE08D8DD76C824F0AAD83CC5A8064A35_20160529_1_1_386.mp4?dl=0

**Comment by AquilesCanta** [comment]
Just wondering, have you managed to play the file with another player? I haven't. I will look into it, but I have a feeling that it may be malformed.

**Comment by AquilesCanta** [comment]
Well, as a matter of fact the last URL you sent does not correspond to an mp4 file (I wasn't able to determine what it was either). Considering the stack trace you sent before, the dropbox.com url and the first one don't point to the same file. Please, open a new issue providing a correct media sample. If possible, make sure they don't expire. That way, the information exchange may become useful to third parties reading this thread.
