### ISSUE TITLE
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by iflytek-duan** [google/ExoPlayer#1564]
I encountered a problem in the following when playing video, how to fix it?
----
ErrorInfo：
com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://jiankang.openspeech.cn/resource/v1/2016/05/30/82daad29b46e4d07b76f616d33d2de1c.mp4
	at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193)
	at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
	at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:824)
	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
...
...
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by iflytek-duan** [comment]
@NoGirlFriendException

**Comment by ojw28** [comment]
This error is not ExoPlayer specific; it's an SSL failure in the network stack encountered when trying to open a connection to the server. I suggest you start your investigation [here](https://developer.android.com/training/articles/security-ssl.html#CommonProblems).

**Comment by iflytek-duan** [comment]
Thanks for your reply.
