### ISSUE TITLE
How to run playbacktests?

### ISSUE THREAD

**Issue by billyjoker** [google/ExoPlayer#1578]
I'd like tu run the run tests included in the module playbacktests

No playback tests could be run

I've got to execute the tests of the project with `gradlew connectedAndroidTest`, but the report shows 0 tests that were executed

Exoplayer 1.5.8

Moto X 2014. Android 5.1

Also, Flac test failed

What am i doing wrong?

**Flac failed:** 
![flascfailed](https://cloud.githubusercontent.com/assets/4301306/15865874/bb187138-2cdc-11e6-8a7d-c460c82a7775.jpg)

**playbacktests no tests:** 
![notests](https://cloud.githubusercontent.com/assets/4301306/15865879/c15973c6-2cdc-11e6-811b-930a38c2e6e2.jpg)

**Comment by ojw28** [comment]
Building the flac extension requires manual steps. Unless you need it, you should avoid building it. You can run the playback tests using:

```
./gradlew :playbacktests:installDebug
adb shell am instrument -w -r -e debug false com.google.android.exoplayer.playbacktests.test/android.test.InstrumentationTestRunner
```

**Comment by billyjoker** [comment]
`./gradlew :playbacktests:installDebug` was successfuly but

db shell am instrument -w -r -e debug false com.google.android.exoplayer.playbacktests.test/android.test.InstrumentationTestRunner

failed as follows: 

```
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.google.android.exoplayer.playbacktests.test/android.test.InstrumentationTestRunner}
INSTRUMENTATION_STATUS_CODE: -1
android.util.AndroidException: INSTRUMENTATION_FAILED: com.google.android.exoplayer.playbacktests.test/android.test.InstrumentationTestRunner
        at com.android.commands.am.Am.runInstrument(Am.java:981)
        at com.android.commands.am.Am.onRun(Am.java:319)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:98)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)

```

**Comment by billyjoker** [comment]
Ok i did run again fixin the path you said:

`adb shell am instrument -w -r -e debug false com.google.android.exoplayer.playbacktests/android.test.InstrumentationTestRunner`

I'm just now i'm running:

```
INSTRUMENTATION_STATUS: numtests=15
INSTRUMENTATION_STATUS: stream=
com.google.android.exoplayer.playbacktests.gts.DashTest:
INSTRUMENTATION_STATUS: id=InstrumentationTestRunner
INSTRUMENTATION_STATUS: test=test23FpsH264Fixed
INSTRUMENTATION_STATUS: class=com.google.android.exoplayer.playbacktests.gts.DashTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1
INSTRUMENTATION_STATUS: numtests=15
INSTRUMENTATION_STATUS: stream=.
INSTRUMENTATION_STATUS: id=InstrumentationTestRunner
INSTRUMENTATION_STATUS: test=test23FpsH264Fixed
INSTRUMENTATION_STATUS: class=com.google.android.exoplayer.playbacktests.gts.DashTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 0
INSTRUMENTATION_STATUS: numtests=15
INSTRUMENTATION_STATUS: stream=
INSTRUMENTATION_STATUS: id=InstrumentationTestRunner
INSTRUMENTATION_STATUS: test=test24FpsH264Fixed
INSTRUMENTATION_STATUS: class=com.google.android.exoplayer.playbacktests.gts.DashTest
INSTRUMENTATION_STATUS: current=2
INSTRUMENTATION_STATUS_CODE: 1
INSTRUMENTATION_STATUS: numtests=15
INSTRUMENTATION_STATUS: stream=.
INSTRUMENTATION_STATUS: id=InstrumentationTestRunner
INSTRUMENTATION_STATUS: test=test24FpsH264Fixed
INSTRUMENTATION_STATUS: class=com.google.android.exoplayer.playbacktests.gts.DashTest
INSTRUMENTATION_STATUS: current=2
INSTRUMENTATION_STATUS_CODE: 0
INSTRUMENTATION_STATUS: numtests=15
INSTRUMENTATION_STATUS: stream=
INSTRUMENTATION_STATUS: id=InstrumentationTestRunner
INSTRUMENTATION_STATUS: test=test29FpsH264Fixed
INSTRUMENTATION_STATUS: class=com.google.android.exoplayer.playbacktests.gts.DashTest
INSTRUMENTATION_STATUS: current=3
INSTRUMENTATION_STATUS_CODE: 1
INSTRUMENTATION_STATUS: numtests=15
INSTRUMENTATION_STATUS: stream=.
INSTRUMENTATION_STATUS: id=InstrumentationTestRunner
INSTRUMENTATION_STATUS: test=test29FpsH264Fixed
INSTRUMENTATION_STATUS: class=com.google.android.exoplayer.playbacktests.gts.DashTest
INSTRUMENTATION_STATUS: current=3
INSTRUMENTATION_STATUS_CODE: 0
INSTRUMENTATION_STATUS: numtests=15
INSTRUMENTATION_STATUS: stream=
INSTRUMENTATION_STATUS: id=InstrumentationTestRunner
INSTRUMENTATION_STATUS: test=testH264Adaptive
INSTRUMENTATION_STATUS: class=com.google.android.exoplayer.playbacktests.gts.DashTest
INSTRUMENTATION_STATUS: current=4
INSTRUMENTATION_STATUS_CODE: 1


```

**Comment by billyjoker** [comment]
And where could i see the file reports??

**Comment by ojw28** [comment]
I'm not really sure. I normally run them from Android Studio rather than the command line, which in general seems much easier!

**Comment by billyjoker** [comment]
Sure!! But i like the autogenerated html reports when i run unit tests

**Comment by ojw28** [comment]
I'm not sure you should expect an auto-generated file as output. The Android (documentation)[https://developer.android.com/studio/test/command-line.html] about running tests from the command lines just says:

> Your test results appear in STDOUT.

So if you're wanting the output as a file, you'll probably need to pipe STDOUT.
