### ISSUE TITLE
SmoothStreaming Playready Live stream crashes if audio/video elements change order

### ISSUE THREAD

**Issue by marcuz89** [google/ExoPlayer#1593]
Hi,
I've this blocking issue with a isml/Manifest for a live content (SmoothStreaming with Playready License), these are the logs starting with the demo app. The device that I use is with AndroidTV 5.1.1 platform.

```
W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 512*288, bits: 8(dither), vscaler:1
06-14 17:42:59.873 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:5),Stream(Used:14,Free:0),frameCount:20,delta=06,fps12.58,decode_stream start: 0, decoder status 5
06-14 17:43:00.873 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 512*288, bits: 8(dither), vscaler:1
06-14 17:43:00.873 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:4),Stream(Used:14,Free:0),frameCount:45,delta=25,fps17.53,decode_stream start: 0, decoder status 5
06-14 17:43:00.965 148-27151/? W/[33;1mAmp2@@[MODULE_VDEC:DDL_Callback():1744]:[0m: COMPVDEC:New Display Size 0x195000 Number 0x6 (1024 * 576),Reference Number 5,  Size: 120000, bit_depth=8
06-14 17:43:00.965 148-27151/? W/[33;1mAmp2@@[MODULE_VDEC:DDL_Callback():1825]:[0m: 0xeed4e000: width align to:1920, stride: 1920
06-14 17:43:00.965 148-27151/? W/[33;1mAmp2@@[MODULE_VDEC:DDL_Callback():1847]:[0m: COMPVDEC: resolution change on the fly count 0
06-14 17:43:00.967 26826-27148/? W/AHierarchicalStateMachine: Warning message AMessage(what = 'omx ', target = 1) = {
                                                                int32_t type = 0
                                                                int32_t node = 99
                                                                int32_t event = 2130706434
                                                                int32_t data1 = 1920
                                                                int32_t data2 = 1088
                                                              } unhandled in root state.
06-14 17:43:00.967 26826-27148/? W/AHierarchicalStateMachine: Warning message AMessage(what = 'omx ', target = 1) = {
                                                                int32_t type = 0
                                                                int32_t node = 99
                                                                int32_t event = 2130706439
                                                                int32_t data1 = 1920
                                                                int32_t data2 = 0
                                                              } unhandled in root state.
06-14 17:43:00.967 26826-27148/? W/AHierarchicalStateMachine: Warning message AMessage(what = 'omx ', target = 1) = {
                                                                int32_t type = 0
                                                                int32_t node = 99
                                                                int32_t event = 2130706438
                                                                int32_t data1 = 1088
                                                                int32_t data2 = 0
                                                              } unhandled in root state.
06-14 17:43:01.067 635-643/? W/BerlinAVS_VideoSourceContext: handleVideoScalingLocked, ignore, vrect (0 0 0 0)
06-14 17:43:01.873 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:01.873 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:5),Stream(Used:14,Free:0),frameCount:70,delta=25,fps19.66,decode_stream start: 0, decoder status 5
06-14 17:43:02.873 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:02.873 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:4),Stream(Used:14,Free:0),frameCount:95,delta=25,fps20.84,decode_stream start: 0, decoder status 5
06-14 17:43:03.873 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:03.873 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:5),Stream(Used:14,Free:0),frameCount:120,delta=25,fps21.60,decode_stream start: 0, decoder status 5
06-14 17:43:04.873 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:04.874 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:4),Stream(Used:14,Free:0),frameCount:145,delta=25,fps22.12,decode_stream start: 0, decoder status 5
06-14 17:43:05.874 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:05.874 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:5),Stream(Used:14,Free:0),frameCount:170,delta=25,fps22.50,decode_stream start: 0, decoder status 5
06-14 17:43:06.874 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:06.874 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:4),Stream(Used:14,Free:0),frameCount:195,delta=25,fps22.80,decode_stream start: 0, decoder status 5
06-14 17:43:07.391 148-207/? W/[33;1mAmp2@@[MODULE_DISPSRV:disp_output_info():285]:[0m: [Output] = 4Kx2KP60 YCbCr420 8Bit, HDMI HDCP2.2(1) => Connected
06-14 17:43:07.391 148-207/? W/[33;1mAmp2@@[MODULE_DISPSRV:disp_plane_info():257]:[0m: [MAIN plane]=(0,0,1024,576)->(0,0,3840,2160)/-/-
06-14 17:43:07.392 148-207/? W/[33;1mAmp2@@[MODULE_DISPSRV:disp_frame_info():233]:[0m: [MAIN frame]=(0,0,1920,1088)->(0,0,1920,1088)@YUV420SP/8bits/Pp:0/Fs:1
06-14 17:43:07.392 148-207/? W/[33;1mAmp2@@[MODULE_DISPSRV:disp_frame_info():233]:[0m: [PIP frame]=(0,0,0,0)->(0,0,0,0)@YUV422/0bits/Pp:0/Fs:0
06-14 17:43:07.392 148-207/? W/[33;1mAmp2@@[MODULE_DISPSRV:disp_plane_info():257]:[0m: [GFX0 plane]=(0,0,1920,1080)->(0,0,3840,2160)/-/-
06-14 17:43:07.392 148-207/? W/[33;1mAmp2@@[MODULE_DISPSRV:disp_frame_info():233]:[0m: [GFX0 frame]=(0,0,1920,1080)->(0,0,1920,1080)@ARGB32/8bits/Pp:0/Fs:0
06-14 17:43:07.874 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:07.874 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:5),Stream(Used:14,Free:0),frameCount:220,delta=25,fps23.03,decode_stream start: 0, decoder status 5
06-14 17:43:08.874 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:08.874 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:4),Stream(Used:14,Free:0),frameCount:245,delta=25,fps23.22,decode_stream start: 0, decoder status 5
06-14 17:43:10.874 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:10.874 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:4),Stream(Used:14,Free:0),frameCount:295,delta=25,fps23.50,decode_stream start: 0, decoder status 5
06-14 17:43:12.563 26826-27143/? E/LoadTask: Unexpected exception loading stream
                                             java.lang.IllegalStateException: Top bit not zero: -90291809
                                                 at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:292)
                                                 at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:763)
                                                 at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:182)
                                                 at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                 at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
                                                 at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                 at java.lang.Thread.run(Thread.java:818)
06-14 17:43:12.620 26826-27143/? E/LoadTask: Unexpected exception loading stream
                                             java.lang.IllegalStateException: Top bit not zero: -1751225774
                                                 at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:292)
                                                 at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:763)
                                                 at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:182)
                                                 at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                 at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
                                                 at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                 at java.lang.Thread.run(Thread.java:818)
06-14 17:43:12.620 26826-26826/? E/EventLogger: internalError [15.43, loadError]
                                                com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: Top bit not zero: -1751225774
                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                    at java.lang.Thread.run(Thread.java:818)
                                                 Caused by: java.lang.IllegalStateException: Top bit not zero: -1751225774
                                                    at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:292)
                                                    at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:763)
                                                    at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:182)
                                                    at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                    at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                    at java.lang.Thread.run(Thread.java:818) 
06-14 17:43:12.874 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:12.874 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:4),Stream(Used:14,Free:0),frameCount:345,delta=25,fps23.71,decode_stream start: 0, decoder status 5
06-14 17:43:15.725 148-207/? W/[33;1mAmp2@@[MODULE_DISPSRV:disp_plane_info():257]:[0m: [MAIN plane]=(0,0,1024,576)->(0,0,3840,2160)/-/-
06-14 17:43:15.725 148-207/? W/[33;1mAmp2@@[MODULE_DISPSRV:disp_frame_info():233]:[0m: [MAIN frame]=(0,0,1920,1088)->(0,0,1920,1088)@YUV420SP/8bits/Pp:0/Fs:1
06-14 17:43:15.725 148-207/? W/[33;1mAmp2@@[MODULE_DISPSRV:disp_frame_info():233]:[0m: [PIP frame]=(0,0,0,0)->(0,0,0,0)@YUV422/0bits/Pp:0/Fs:0
06-14 17:43:15.725 148-207/? W/[33;1mAmp2@@[MODULE_DISPSRV:disp_plane_info():257]:[0m: [GFX0 plane]=(0,0,1920,1080)->(0,0,3840,2160)/-/-
06-14 17:43:15.725 148-207/? W/[33;1mAmp2@@[MODULE_DISPSRV:disp_frame_info():233]:[0m: [GFX0 frame]=(0,0,1920,1080)->(0,0,1920,1080)@ARGB32/8bits/Pp:0/Fs:0
06-14 17:43:15.788 26826-27143/? E/LoadTask: Unexpected exception loading stream
                                             java.lang.IllegalStateException: Top bit not zero: -870374048
                                                 at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:292)
                                                 at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:763)
                                                 at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:182)
                                                 at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                 at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
                                                 at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                 at java.lang.Thread.run(Thread.java:818)
06-14 17:43:15.793 26826-26826/? E/EventLogger: internalError [18.60, loadError]
                                                com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: Top bit not zero: -870374048
                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                    at java.lang.Thread.run(Thread.java:818)
                                                 Caused by: java.lang.IllegalStateException: Top bit not zero: -870374048
                                                    at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:292)
                                                    at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:763)
                                                    at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:182)
                                                    at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                    at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                    at java.lang.Thread.run(Thread.java:818) 
06-14 17:43:15.874 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:15.874 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:5),Stream(Used:14,Free:0),frameCount:420,delta=25,fps23.93,decode_stream start: 0, decoder status 5
06-14 17:43:18.091 148-27166/? W/[33;1mAmp2@@[MODULE_ADEC:ADEC_CheckExecSleep():628]:[0m: ADEC Sleep, input[32 0 0x0][0 0 0x0], pcm[0 0 0x0 0x0][0 0 0x0 0x0], hdmi[D 0 0 0x0 0x0], spdif[D 0 0 0x0 0x0], es[0 0 0x0 0x0], EOS[(0 0), (0 0), 0, 0], DecErr[0/0 0], uiCurTime 515a1c, uiPreTime 515a1c, disc 0
06-14 17:43:18.849 26826-27143/? E/LoadTask: Unexpected exception loading stream
                                             java.lang.IllegalStateException: Top bit not zero: -1982918044
                                                 at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:292)
                                                 at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:763)
                                                 at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:182)
                                                 at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                 at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
                                                 at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                 at java.lang.Thread.run(Thread.java:818)
06-14 17:43:18.855 26826-26826/? E/EventLogger: internalError [21.67, loadError]
                                                com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: Top bit not zero: -1982918044
                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                    at java.lang.Thread.run(Thread.java:818)
                                                 Caused by: java.lang.IllegalStateException: Top bit not zero: -1982918044
                                                    at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:292)
                                                    at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:763)
                                                    at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:182)
                                                    at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                    at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                    at java.lang.Thread.run(Thread.java:818) 
06-14 17:43:18.875 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:19.875 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:19.875 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:5),Stream(Used:14,Free:0),frameCount:520,delta=25,fps24.13,decode_stream start: 0, decoder status 5
06-14 17:43:21.875 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:21.875 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:5),Stream(Used:14,Free:0),frameCount:570,delta=25,fps24.20,decode_stream start: 0, decoder status 5
06-14 17:43:22.875 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:22.875 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:4),Stream(Used:14,Free:0),frameCount:595,delta=25,fps24.23,decode_stream start: 0, decoder status 5
06-14 17:43:22.901 26826-27143/? E/LoadTask: Unexpected exception loading stream
                                             java.lang.IllegalStateException: Top bit not zero: -920745276
                                                 at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:292)
                                                 at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:763)
                                                 at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:182)
                                                 at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                 at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
                                                 at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                 at java.lang.Thread.run(Thread.java:818)
06-14 17:43:22.904 26826-26826/? E/EventLogger: internalError [25.72, loadError]
                                                com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: Top bit not zero: -920745276
                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                    at java.lang.Thread.run(Thread.java:818)
                                                 Caused by: java.lang.IllegalStateException: Top bit not zero: -920745276
                                                    at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:292)
                                                    at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:763)
                                                    at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:182)
                                                    at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                    at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                    at java.lang.Thread.run(Thread.java:818) 
06-14 17:43:24.875 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5930]:[0m: VDEC: 0xeed4e000,mediaType : h264, inputMode : frame-in, outputMode : SPUV,vpuId : V4G,resolution : 1024*576, bits: 8(dither), vscaler:1
06-14 17:43:24.875 148-27154/? W/[33;1mAmp2@@[MODULE_VDEC:VideoStatusProcess():5944]:[0m: BufferStatus: Display(Total:11,UsedByDecoder:3,FreeInVDEC:0),Reference(Total:5,Used:4),Stream(Used:14,Free:0),frameCount:645,delta=25,fps24.29,decode_stream start: 0, decoder status 5
```

**Comment by Micheledroid** [comment]
Hi,
we undestood which is the root cause of this blocking issue with a isml/Manifest for a live content (SmoothStreaming with Playready License), this is probably related to the parsing of the isml/manifest when a change occurs.

We have noticed something unusual in the parser of the manifest XML when a change occurs in the sequence of the TAGs for video and audio.
1.  If the manifest sequence for the tags video and audio keeps being the same during the video play: everything works fine
2.  If during the play a change occurs in the manifest sequence video and audio  then parser provides the error already attached to the ticket and the exoplayer crashes.

Info: 
-   The device used for the testing  is based on AndroidTV 5.1.1 platform
-   Other video-players (e.g. on iOS, Smart TVs) keep working with the same live video stream
-   Attached in the zip file XML with audio TAG first
-   Attached in the zip file XML with video TAG first
-   Log file in the bug report

Thanks for your support.

[manifest.zip](https://github.com/google/ExoPlayer/files/320995/manifest.zip)

**Comment by ojw28** [comment]
This is likely to be unrelated to PlayReady and related to your observation above, which is a failure to handle the audio and video elements changing order.

That said, it feels like a server that does this is really just asking for trouble. It should be trivially for a server to keep them in the same order, and it's likely that doing so will minimize the risk of client failures.

**Comment by ojw28** [comment]
I don't think we're going to be spending time on this. It appears to be an isolated case, and as above, the server can pretty easily keep a stable order in the manifest.
