### ISSUE TITLE
Dash + Widevine throws Failed to instantiate drm object on API 22 but not API 23.

### ISSUE THREAD

**Issue by rburnham52** [google/ExoPlayer#1616]
Hi,
So i've been trying to key a sample working for Dash + Widevine and i was able to get it to work on API 23, then i tried it on API 22 using the emulator and i'm getting the following error

```
> com.google.android.exoplayer.drm.UnsupportedDrmException: android.media.UnsupportedSchemeException: Failed to instantiate drm object.
>                                                                       at com.google.android.exoplayer.drm.StreamingDrmSessionManager.<init>(StreamingDrmSessionManager.java:182)
>                                                                       at com.google.android.exoplayer.drm.StreamingDrmSessionManager.newWidevineInstance(StreamingDrmSessionManager.java:126)
>                                                                       at com.google.android.libraries.mediaframework.exoplayerextensions.DashRendererBuilder$AsyncRendererBuilder.buildRenderers(DashRendererBuilder.java:213)
>                                                                       at com.google.android.libraries.mediaframework.exoplayerextensions.DashRendererBuilder$AsyncRendererBuilder.onSingleManifest(DashRendererBuilder.java:155)
>                                                                       at com.google.android.libraries.mediaframework.exoplayerextensions.DashRendererBuilder$AsyncRendererBuilder.onSingleManifest(DashRendererBuilder.java:110)
>                                                                       at com.google.android.exoplayer.util.ManifestFetcher$SingleFetchHelper.onLoadCompleted(ManifestFetcher.java:378)
>                                                                       at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
>                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                       at android.os.Looper.loop(Looper.java:136)
>                                                                       at android.app.ActivityThread.main(ActivityThread.java:5017)
>                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
>                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
>                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
>                                                                       at dalvik.system.NativeStart.main(Native Method)
>                                                                    Caused by: android.media.UnsupportedSchemeException: Failed to instantiate drm object.
>                                                                       at android.media.MediaDrm.native_setup(Native Method)
>                                                                       at android.media.MediaDrm.<init>(MediaDrm.java:163)
>                                                                       at com.google.android.exoplayer.drm.StreamingDrmSessionManager.<init>(StreamingDrmSessionManager.java:180)
>                                                                       at com.google.android.exoplayer.drm.StreamingDrmSessionManager.newWidevineInstance(StreamingDrmSessionManager.java:126) 
>                                                                       at com.google.android.libraries.mediaframework.exoplayerextensions.DashRendererBuilder$AsyncRendererBuilder.buildRenderers(DashRendererBuilder.java:213) 
>                                                                       at com.google.android.libraries.mediaframework.exoplayerextensions.DashRendererBuilder$AsyncRendererBuilder.onSingleManifest(DashRendererBuilder.java:155) 
>                                                                       at com.google.android.libraries.mediaframework.exoplayerextensions.DashRendererBuilder$AsyncRendererBuilder.onSingleManifest(DashRendererBuilder.java:110) 
>                                                                       at com.google.android.exoplayer.util.ManifestFetcher$SingleFetchHelper.onLoadCompleted(ManifestFetcher.java:378) 
>                                                                       at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245) 
>                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                       at android.os.Looper.loop(Looper.java:136) 
>                                                                       at android.app.ActivityThread.main(ActivityThread.java:5017) 
>                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
>                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
```

This was on exoplayer 1.5.7 but i just upgraded to 1.5.9 and tried it again. and the message is similar

```
> com.google.android.gms.unstable W/DG.WV: Widevine DRM not supported on this device
>                                                                       android.media.UnsupportedSchemeException: Failed to instantiate drm object.
>                                                                           at android.media.MediaDrm.native_setup(Native Method)
>                                                                           at android.media.MediaDrm.<init>(MediaDrm.java:180)
>                                                                           at mvf.a(SourceFile:121)
>                                                                           at msa.run(SourceFile:1094)
>                                                                           at jxo.run(SourceFile:438)
>                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>                                                                           at kby.run(SourceFile:17)
>                                                                           at java.lang.Thread.run(Thread.java:818)
```

I thought widevine + dash was supported back to api 16? i read that there is classic and modular widevine but both should be supported in api 22 right?

**Comment by ojw28** [comment]
Widevine is supported on API levels 18 and higher, as per the [supported formats](https://google.github.io/ExoPlayer/supported-formats.html) page. It's likely just an issue with the emulator; please try on a real device instead.
