### ISSUE TITLE
Widevine DASH contents does not playback normally.

### ISSUE THREAD

**Issue by Hongjae** [google/ExoPlayer#1634]
- All Widevine DASH contents does not playback normally. (Including clear contents)
  It stops about 10s after starting the contents.
  Suddenly, the same issue occurs on all devices.
  I think that it is a issue with the server.
- Exoplayer version is 1.5.3
- M OS / N OS
- Fail log
  06-27 19:49:56.929  5193  5193 E EventLogger: internalError [12.29, drmSessionManagerError]
  06-27 19:49:56.929  5193  5193 E EventLogger: java.io.FileNotFoundException: https://proxy.uat.widevine.com/proxy?video_id=&provider=widevine_test
  06-27 19:49:56.929  5193  5193 E EventLogger:   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:254)
  06-27 19:49:56.929  5193  5193 E EventLogger:   at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
  06-27 19:49:56.929  5193  5193 E EventLogger:   at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
  06-27 19:49:56.929  5193  5193 E EventLogger:   at com.google.android.exoplayer.util.Util.executePost(Util.java:700)
  06-27 19:49:56.929  5193  5193 E EventLogger:   at com.google.android.exoplayer.demo.WidevineTestMediaDrmCallback.executeKeyRequest(WidevineTestMediaDrmCallback.java:57)
  06-27 19:49:56.929  5193  5193 E EventLogger:   at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostRequestHandler.handleMessage(StreamingDrmSessionManager.java:505)
  06-27 19:49:56.929  5193  5193 E EventLogger:   at android.os.Handler.dispatchMessage(Handler.java:102)
  06-27 19:49:56.929  5193  5193 E EventLogger:   at android.os.Looper.loop(Looper.java:148)
  06-27 19:49:56.929  5193  5193 E EventLogger:   at android.os.HandlerThread.run(HandlerThread.java:61)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal: Internal track renderer error.
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal: com.google.android.exoplayer.ExoPlaybackException: java.io.FileNotFoundException: https://proxy.uat.widevine.com/proxy?video_id=&provider=widevine_test
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.shouldWaitForKeys(MediaCodecTrackRenderer.java:713)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:663)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at android.os.Handler.dispatchMessage(Handler.java:98)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at android.os.Looper.loop(Looper.java:148)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at android.os.HandlerThread.run(HandlerThread.java:61)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal: Caused by: java.io.FileNotFoundException: https://proxy.uat.widevine.com/proxy?video_id=&provider=widevine_test
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:254)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at com.google.android.exoplayer.util.Util.executePost(Util.java:700)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at com.google.android.exoplayer.demo.WidevineTestMediaDrmCallback.executeKeyRequest(WidevineTestMediaDrmCallback.java:57)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostRequestHandler.handleMessage(StreamingDrmSessionManager.java:505)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at android.os.Handler.dispatchMessage(Handler.java:102)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at android.os.Looper.loop(Looper.java:148)
  06-27 19:49:56.930  5193  5434 E ExoPlayerImplInternal:     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Hongjae** [comment]
Now, Widevine DASH contents does playback normally.
