### ISSUE TITLE
NoClassDefFoundError: java.lang.NoClassDefFoundError: android.media.AudioTimestamp 

### ISSUE THREAD

**Issue by tentkotta** [google/ExoPlayer#1635]
Please search the existing issues before filing a new one, including issues that
are closed. When filing a new issue please include all of the following, unless
you're certain that they're not useful for the particular issue being reported.
- ExoPlayer is using android.media.AudioTimestamp class whose API level is 19. Hence, Exoplayer running in devices with api level 17 are failing with NoClassDefFoundError. I expect Exoplayer lib to work with min api level 16 and above.
- Steps describing how the issue can be reproduced, ideally in the ExoPlayer
  demo app.
  Just use exoplayer in any device running in api level 17 or 16.
- A link to content that reproduces the issue. If you don't wish to post it
  publicly, please submit the issue, then email the link to
  dev.exoplayer@gmail.com including the issue number in the subject line.
- The version of ExoPlayer being used.
  r1.5.6 (As per code, the issue exists in r1.5.9 as well)
- The device(s) and version(s) of Android on which the issue can be reproduced,
  and how easily it reproduces. If possible, please test on multiple devices and
  Android versions.
  Any devices between API level 16 and 18
- A bug report taken from the device just after the issue occurs, attached as a
  file. A bug report can be captured using "adb bugreport". Output from "adb
  logcat" or a log snippet is not sufficient.

**Comment by andrewlewis** [comment]
AudioTimestamp is only used if the device is running >= API 19, so it is strange that you're seeing this error. Please send a full bug report captured with `adb bugreport` to dev.exoplayer@gmail.com.

**Comment by tentkotta** [comment]
I do not have bugreport as I got this error from "Crashes & ANRs" section in google play store developer console.

```
Attaching the exception stack-trace:
java.lang.NoClassDefFoundError: android.media.AudioTimestamp
    at com.google.android.exoplayer.audio.AudioTrack$AudioTrackUtil.<init>(AudioTrack.java:1282)
    at com.google.android.exoplayer.audio.AudioTrack.<init>(AudioTrack.java:305)
    at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.<init>(MediaCodecAudioTrackRenderer.java:190)
    at com.google.android.exoplayer.demo.player.HlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(HlsRendererBuilder.java:153)
    at com.google.android.exoplayer.demo.player.HlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(HlsRendererBuilder.java:91)
    at com.google.android.exoplayer.util.ManifestFetcher$SingleFetchHelper.onLoadCompleted(ManifestFetcher.java:378)
    at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:175)
    at android.app.ActivityThread.main(ActivityThread.java:5279)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
    at dalvik.system.NativeStart.main(Native Method)
```

This issue happens in the following devices:

Galaxy Tab2 10.1 (espresso10att) 
Galaxy S3 (m0) 
sugar-A10_A054 
Android TV G3 (eden) 
A1-830 (ducati) 
Galaxy Note 8.0 (kona3g) 
Android TV (cosmo) 
Galaxy Tab2 7.0 (espressowifi) 
Galaxy Tab3 Lite (goyawifi) 
Droid 4 (cdma_maserati) 
vision2_1 (vision2_1) 
Galaxy Tab2 10.1 (espresso10wifi) 
Galaxy Note 10.1 (p4notewifi)

**Comment by andrewlewis** [comment]
Which ExoPlayer version number does the stack trace correspond to?

**Comment by tentkotta** [comment]
I am using r1.5.6

**Comment by andrewlewis** [comment]
The stack trace mentions AudioTrack.java:1282, but that line doesn't exist in r1.5.6. Did you modify the code?

In [AudioTrack.java](https://github.com/google/ExoPlayer/blob/r1.5.6/library/src/main/java/com/google/android/exoplayer/audio/AudioTrack.java) we only use AudioTimestamp on devices where SDK_INT >= 19 (see [the check here](https://github.com/google/ExoPlayer/blob/r1.5.6/library/src/main/java/com/google/android/exoplayer/audio/AudioTrack.java#L259)). So I'm not sure how this is occurring if android.os.Build.VERSION.SDK_INT is set correctly.

To investigate further I think we need verified steps to reproduce this in the demo app, not just stack traces from your app from the developer console.

**Comment by aravinds03** [comment]
Yes, the code is modified. It is fixed in the code and also I upgraded the lib to 1.5.9

**Comment by tentkotta** [comment]
Yes, the code is modified. I reverted the code changes and  upgraded the lib to 1.5.9 to resolve this issue.
