### ISSUE TITLE
Issue with Pre-lollipop versions while streaming audio.

### ISSUE THREAD

**Issue by codered-sjy** [google/ExoPlayer#1651]
I am trying to play audio stream using Exoplayer in android. It works well in Lollipop & higher versions. But for pre-lollipop versions, Iam getting an exception. 

Internal track renderer error.
                                                                         com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: -1
                                                                             at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                                                                             at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:275)
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:137)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                          Caused by: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: -1
                                                                             at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
                                                                             at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
                                                                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:824)
                                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                             at java.lang.Thread.run(Thread.java:841)

**Comment by AquilesCanta** [comment]
Please see [#1003](https://github.com/google/ExoPlayer/issues/1003) and let me know if one of the referred issues provides some help, so I can close this one.

**Comment by AquilesCanta** [comment]
I found many related issues (particularly with icecast, though I don't know it this is the case here). Considering there is almost no information available for me to help you, I would suggest looking through older issues. If you cannot solve yours after this, open a fresh issue including all the information required in the issue template.

**Comment by bkoruznjak** [comment]
I have the somewhat the same issue. With the version r.2.1.1 and a jellybean device

E/ExoPlayerImplInternal: Source error.
                                                                                       com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: -1
                                                                                           at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                                           at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                           at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:618)
                                                                                           at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                                           at java.lang.Thread.run(Thread.java:838)


I tried many shoutcast streams and i keep getting this log
