### ISSUE TITLE
Failed playback video - DecoderInitializationException: Decoder init failed: OMX.MARVELL.AUDIO.AACDECODER

### ISSUE THREAD

**Issue by dongseok0** [google/ExoPlayer#1652]
Hi,
Video playback failed for on my customer's device. (JB)
The video file is encoded as AVC/AAC-LC  
Used content: https://1education.blob.core.windows.net/student3892/1466945644813fileVID_20160626_225315-converted.mp4  
Used ExoPlayer Version: 1.5.9
Full log:

```
E/ACodec: [OMX.MARVELL.AUDIO.AACDECODER] configureCodec returning error -1010
E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -1010)
E/ExoPlayerImplInternal: Internal track renderer error.
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.MARVELL.AUDIO.AACDECODER, MediaFormat(2, audio/mp4a-latm, -1, 858, -1, -1, -1, -1.0, 1, 8000, eng, 12448000, false, -1, -1, -1, -1, -1)
  at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:414)
  at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400)
  at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768)
  at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.onInputFormatChanged(MediaCodecAudioTrackRenderer.java:270)
  at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524)
  at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507)
  at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
  at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:137)
  at android.os.HandlerThread.run(HandlerThread.java:61)
  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.MARVELL.AUDIO.AACDECODER, MediaFormat(2, audio/mp4a-latm, -1, 858, -1, -1, -1, -1.0, 1, 8000, eng, 12448000, false, -1, -1, -1, -1, -1)
  at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400) 
  at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768) 
  at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.onInputFormatChanged(MediaCodecAudioTrackRenderer.java:270) 
  at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524) 
  at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507) 
  at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
  at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434) 
  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
  at android.os.Handler.dispatchMessage(Handler.java:95) 
  at android.os.Looper.loop(Looper.java:137) 
  at android.os.HandlerThread.run(HandlerThread.java:61) 
  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
Caused by: java.lang.IllegalStateException
  at android.media.MediaCodec.native_configure(Native Method)
  at android.media.MediaCodec.configure(MediaCodec.java:259)
  at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.configureCodec(MediaCodecAudioTrackRenderer.java:258)
  at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:389)
  at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768) 
  at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.onInputFormatChanged(MediaCodecAudioTrackRenderer.java:270) 
  at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524) 
  at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507) 
  at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
  at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434) 
  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
  at android.os.Handler.dispatchMessage(Handler.java:95) 
  at android.os.Looper.loop(Looper.java:137) 
  at android.os.HandlerThread.run(HandlerThread.java:61) 
  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

**Comment by andrewlewis** [comment]
Do you see the same failure on other devices or only this one?

Going on the assumption that it's device-specific, please could you let us know what the full build fingerprint is (output by `adb shell getprop ro.build.fingerprint`). If you have the device available please try adding another workaround like 1fa9b9235641916baf976b4246f06e86051ad641, but targeting the codec named `OMX.MARVELL.AUDIO.AACDECODER` and the relevant device name, then let us know if that resolves the issue. Thanks!

**Comment by dongseok0** [comment]
I got it work by applying workaround for that device.
https://github.com/dongseok0/ExoPlayer/commit/1f302c8c8a0fa2ed0eb3f9f3dbfa36a650e71c88  
Let me know if you want me to make PR to your repository.
Thanks!

**Comment by ojw28** [comment]
What actual device is this, and who's it made by? I can't seem to find any conclusive answer by searching for "xo4".

**Comment by ojw28** [comment]
We need more information to know that the workaround you've provided is the correct one. Please provide the fingerprint as mentioned by @andrewlewis above, and also a link to the device in question.

**Comment by ojw28** [comment]
We'll close this soon unless further information is provided. Thanks.
