### ISSUE TITLE
cookies issue in android

### ISSUE THREAD

**Issue by SagarRaiyani** [google/ExoPlayer#1666]
Hello,

I have use the exoPlayer for akamai video play and i have getting one issue. I have play video in player  but the player is not play video and after some times (Ex 40 to 50 sec) i retry button pressed the player is working good. so Please give me solution for this issue.

<--------------error log------------>
com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
                                                                                    at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
                                                                                    at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
                                                                                    at com.google.android.exoplayer.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:97)
                                                                                    at com.google.android.exoplayer.upstream.DataSourceInputStream.open(DataSourceInputStream.java:56)
                                                                                    at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:92)
                                                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                    at java.lang.Thread.run(Thread.java:818)

**Comment by andrewlewis** [comment]
The server is returning HTTP status code 403 (Forbidden). Please check the server is configured correctly. Does the stream play in other players?

**Comment by ojw28** [comment]
https://github.com/google/ExoPlayer/issues/625 may also be relevant.

**Comment by ojw28** [comment]
Closing due to inactivity.
