### ISSUE TITLE
The stss entry_count = 0 cause the ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by DaxiaK** [google/ExoPlayer#1681]
Hi , 
I have a plain mp4 can't be played in exoplayer , but it play in other player (even in Android gallery).
After I verified , its data is right but its atom of stss type seem having some error and the wrong stss will cause the ArrayIndexOutOfBoundsException.

If I make the stss is null , then the video can be played .
`ParsableByteArray stss =null;`

Is possible for fix it ? Thank you!

**Update**
**I find this stss issue is same as [issue 554](https://github.com/google/ExoPlayer/issues/554) , but it is stss not STSC now.**
**(The stss size is 12 + 4 , and entry_count = 0 )**

The video is: [error.mp4](https://mega.nz/#!pcZ02LyC!j-zeVbs0Lx8zl3E5at3aMoP_uHHLFrtPiucCzizZ2Uo)
The dump is (I think the wrong stss is in line 116):[error.txt](https://github.com/google/ExoPlayer/files/370628/error.txt)
The log is :

```
E/LoadTask: Unexpected exception loading stream
                                                                      java.lang.ArrayIndexOutOfBoundsException: length=16; index=16
                                                                          at com.google.android.exoplayer.util.ParsableByteArray.readInt(ParsableByteArray.java:229)
                                                                          at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:297)
                                                                          at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:150)
                                                                          at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:312)
                                                                          at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:254)
                                                                          at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:245)
                                                                          at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:130)
                                                                          at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:836)
                                                                          at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:841)
E/EventLogger: internalError [0.35, loadError]
                                                                         com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: length=16; index=16
                                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                             at java.lang.Thread.run(Thread.java:841)
                                                                          Caused by: java.lang.ArrayIndexOutOfBoundsException: length=16; index=16
                                                                             at com.google.android.exoplayer.util.ParsableByteArray.readInt(ParsableByteArray.java:229)
                                                                             at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:297)
                                                                             at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:150)
                                                                             at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:312)
                                                                             at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:254)
                                                                             at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:245)
                                                                             at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:130)
                                                                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:836)
                                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                             at java.lang.Thread.run(Thread.java:841) 
```

**Comment by AquilesCanta** [comment]
A fix will be available for both exoplayer versions in the next push.
