### ISSUE TITLE
Crash when fast forward video

### ISSUE THREAD

**Issue by sharkhuang** [google/ExoPlayer#1693]
2.2 develop branch.
User case: play several videos consecutive as playlist. customize media player to control moving forward or backward, which means customize seekto() function to find position cross the videos.  Crash happens when call seekTo(int sourceIndex, long positionMs) .

```
                                                                                java.lang.NullPointerException: Attempt to get length of null array
                                                                                    at com.google.android.exoplayer2.extractor.ExtractorSampleSource.getExtractedSamplesCount(ExtractorSampleSource.java:543)
                                                                                    at com.google.android.exoplayer2.extractor.ExtractorSampleSource.onLoadError(ExtractorSampleSource.java:428)
                                                                                    at com.google.android.exoplayer2.extractor.ExtractorSampleSource.onLoadError(ExtractorSampleSource.java:62)
                                                                                    at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:393)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                    at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by ojw28** [comment]
Please provide more information describing exactly how to reproduce this issue. Also, what specific version of the code are able to reproduce this with?

**Comment by sharkhuang** [comment]
@ojw28  update the description

**Comment by andrewlewis** [comment]
This should be fixed in `dev-v2`. There is still a known issue relating seeking and reuse of MediaPeriods which will likely be fixed in the next push. Thanks.
