### ISSUE TITLE
ExoPlayer sendinging message to a Handler on a dead thread

### ISSUE THREAD

**Issue by dobrusev** [google/ExoPlayer#1702]
Hello,
I use ExoPlayer with Cordova and when I'm switching between videos I see in logs that I'm trying to send something to a dead thread. Any ideas why this is happening? My app is based on the ExoPlayer test app. 

Thanks in advance!

`
test D/VideoPlugin.Notificator: {"type":"GET_CURRENT_POSITION","value":26447}

test D/ViewRootImpl: ViewPostImeInputStage processPointer 0
test D/ViewRootImpl: ViewPostImeInputStage processPointer 1
test W/BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 19536
test D/VideoPlugin.Notificator: {"type":"onStateChanged","value":{"playWhenReady":false,"state":4}}
test D/VideoPlugin.Notificator: {"type":"PLAY_WHEN_READY","value":false}
test D/VideoPlugin.Notificator: {"type":"STOP"}
test I/ACodec: [OMX.Exynos.avc.dec.secure] Now Executing->Idle
test D/SurfaceUtils: set up nativeWindow 0xbd7b8008 for 1x1, color 0x2, rotation 0, usage 0x930
test I/ACodec: [OMX.Exynos.avc.dec.secure] Now Idle->Loaded
test I/ACodec: [OMX.Exynos.avc.dec.secure] Now Loaded
test I/ACodec: SECURE PLAYBACK STOP / send intent to dvfshelper
test I/ACodec:  [OMX.Exynos.avc.dec.secure] Now kWhatShutdownCompleted event : 6915
test I/MediaCodec: Codec shutdown complete
test I/ACodec:  [OMX.Exynos.avc.dec.secure] Now uninitialized
test I/ACodec:  [] Now kWhatShutdownCompleted event : 6915
test I/MediaCodec: Codec shutdown complete
test I/ACodec: [OMX.SEC.aac.dec] Now Executing->Idle
test I/ACodec: [OMX.SEC.aac.dec] Now Idle->Loaded
test I/ACodec: [OMX.SEC.aac.dec] Now Loaded
test I/ACodec:  [OMX.SEC.aac.dec] Now kWhatShutdownCompleted event : 6915
test I/MediaCodec: Codec shutdown complete
test I/ACodec:  [OMX.SEC.aac.dec] Now uninitialized
test I/ACodec:  [] Now kWhatShutdownCompleted event : 6915
test I/MediaCodec: Codec shutdown complete
test W/MessageQueue: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {5fad3e} sending message to a Handler on a dead thread
                                                             java.lang.IllegalStateException: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {5fad3e} sending message to a Handler on a dead thread
                                                                 at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                 at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                 at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                 at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                 at android.os.Handler.sendEmptyMessageDelayed(Handler.java:534)
                                                                 at android.os.Handler.sendEmptyMessage(Handler.java:519)
                                                                 at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:212)
                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                 at java.lang.Thread.run(Thread.java:818)
test W/MessageQueue: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {b79d79f} sending message to a Handler on a dead thread
                                                             java.lang.IllegalStateException: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {b79d79f} sending message to a Handler on a dead thread
                                                                 at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                 at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                 at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                 at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                 at android.os.Handler.sendEmptyMessageDelayed(Handler.java:534)
                                                                 at android.os.Handler.sendEmptyMessage(Handler.java:519)
                                                                 at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:212)
                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                 at java.lang.Thread.run(Thread.java:818)
test D/ViewRootImpl: ViewPostImeInputStage processPointer 0
test D/ViewRootImpl: ViewPostImeInputStage processPointer 1
test W/BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 19536
test W/BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 19536
test D/ViewRootImpl: ViewPostImeInputStage processPointer 0
test D/ViewRootImpl: ViewPostImeInputStage processPointer 1
test D/ViewRootImpl: ViewPostImeInputStage processPointer 0
test D/ViewRootImpl: ViewPostImeInputStage processPointer 1
test W/BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 19536
test I/Choreographer: Skipped 52 frames!  The application may be doing too much work on its main thread.`

**Comment by andrewlewis** [comment]
See #426.
