### ISSUE TITLE
seekTo(index, position) throw IllegalStateException: Multiple renderer media clocks enabled.

### ISSUE THREAD

**Issue by mingchen** [google/ExoPlayer#1719]
**Code version:** 
dev-v2 commit 846f8e1

**Device:**
Nexus 5 / Android 6.0

Descrtiption:
For play list, when call `seekTo(index, position)` to skip to the begining of a video, for example, `seekTo(2, 0)`.  Player throw following exception

```
08-04 09:46:12.414 7582-9462 E/ExoPlayerImplInternal: Renderer error.
com.google.android.exoplayer2.ExoPlaybackException:
    at com.google.android.exoplayer2.ExoPlayerImplInternal$Timeline.enableRenderers(ExoPlayerImplInternal.java:969)
    at com.google.android.exoplayer2.ExoPlayerImplInternal$Timeline.setPlayingSource(ExoPlayerImplInternal.java:931)
    at com.google.android.exoplayer2.ExoPlayerImplInternal$Timeline.handleSourcePrepared(ExoPlayerImplInternal.java:736)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:251)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:148)
    at android.os.HandlerThread.run(HandlerThread.java:61)
    at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
 Caused by: java.lang.IllegalStateException: Multiple renderer media clocks enabled.
    at com.google.android.exoplayer2.ExoPlayerImplInternal$Timeline.enableRenderers(ExoPlayerImplInternal.java:969) 
    at com.google.android.exoplayer2.ExoPlayerImplInternal$Timeline.setPlayingSource(ExoPlayerImplInternal.java:931) 
    at com.google.android.exoplayer2.ExoPlayerImplInternal$Timeline.handleSourcePrepared(ExoPlayerImplInternal.java:736) 
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:251) 
    at android.os.Handler.dispatchMessage(Handler.java:98) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.os.HandlerThread.run(HandlerThread.java:61) 
    at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

**Reproduce:**

After playing, just call `seek(index, 0)` can easily reproduce this issue.

**Comment by andrewlewis** [comment]
This should be fixed in `dev-v2`. There is still a known issue relating seeking and reuse of MediaPeriods which will likely be fixed in the next push. Thanks.
