### ISSUE TITLE
Playing encrypted video, using custom DataSource

### ISSUE THREAD

**Issue by Joseph82** [google/ExoPlayer#1720]
I created a custom DataSource that is basically copied from ContentDataSource, but the InputStream is obtained in this way (inside the open() method):

```
File file = new File(dataSpec.uri.getPath());
clearInputStream = new CipherInputStream(new FileInputStream(file), mCipher);
```

When I try to play the file I obtain this error:

```
Unexpected exception loading stream
java.lang.IllegalStateException: Top bit not zero: -1195853062
at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:240)
at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:331)
at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:122)
at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:745)
at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

The video is MPEG-4 and is encoded with AES/ECB/PKCS5Padding.

More details about my implementation can be found here: http://stackoverflow.com/questions/38729220/reproducing-encrypted-video-using-exoplayer

NOTE: if I use the same DataSource file with a clear video, removing the CipherInputStream:

```
File file = new File(dataSpec.uri.getPath());
clearInputStream = new FileInputStream(file);
```

it works fine.

**Comment by ojw28** [comment]
The error is indicative of incorrect media data being fed into the extractor, which implies your custom DataSource isn't implemented correctly. Closing since this is not an issue with ExoPlayer itself.
