### ISSUE TITLE
Out of Memory Exception during playing movie in Exoplayer

### ISSUE THREAD

**Issue by sachinbhanot** [google/ExoPlayer#174]
Hi ,
I take a update today for exoplayer dev-hls Branch. And I am getting crash after 3 second video play.

11-27 20:18:43.785: I/ACodec(19352): [OMX.SEC.avc.dec] Now Executing
11-27 20:18:43.860: D/dalvikvm(19352): GC_FOR_ALLOC freed 6342K, 31% free 24532K/35108K, paused 26ms, total 26ms
11-27 20:18:43.960: D/dalvikvm(19352): GC_FOR_ALLOC freed 718K, 17% free 29214K/35108K, paused 29ms, total 29ms
11-27 20:18:43.975: D/EventLogger(19352): videoSizeChanged [640, 304, 1.0]
11-27 20:18:44.020: D/dalvikvm(19352): GC_FOR_ALLOC freed 3K, 16% free 32354K/38168K, paused 27ms, total 27ms
11-27 20:18:44.040: D/EventLogger(19352): state [0.68, true, R]
11-27 20:18:44.085: D/dalvikvm(19352): GC_FOR_ALLOC freed 2K, 14% free 37545K/43336K, paused 25ms, total 25ms
11-27 20:18:44.190: D/dalvikvm(19352): GC_FOR_ALLOC freed 820K, 12% free 44792K/50612K, paused 26ms, total 27ms
11-27 20:18:44.330: I/dalvikvm-heap(19352): Clamp target GC heap from 69.583MB to 64.000MB
11-27 20:18:44.330: D/dalvikvm(19352): GC_FOR_ALLOC freed 98K, 10% free 54086K/59860K, paused 29ms, total 29ms
11-27 20:18:44.435: I/dalvikvm-heap(19352): Clamp target GC heap from 75.091MB to 64.000MB
11-27 20:18:44.435: D/dalvikvm(19352): GC_FOR_ALLOC freed 97K, 9% free 59726K/65504K, paused 36ms, total 36ms
11-27 20:18:44.435: I/dalvikvm-heap(19352): Forcing collection of SoftReferences for 65552-byte allocation
11-27 20:18:44.475: I/dalvikvm-heap(19352): Clamp target GC heap from 75.083MB to 64.000MB
11-27 20:18:44.475: D/dalvikvm(19352): GC_BEFORE_OOM freed 74K, 9% free 59652K/65504K, paused 42ms, total 42ms
11-27 20:18:44.475: E/dalvikvm-heap(19352): Out of memory on a 65552-byte allocation.
11-27 20:18:44.475: I/dalvikvm(19352): "Loader:HLS" prio=5 tid=37 RUNNABLE
11-27 20:18:44.475: I/dalvikvm(19352):   | group="main" sCount=0 dsCount=0 obj=0x43630c98 self=0x621f82b0
11-27 20:18:44.475: I/dalvikvm(19352):   | sysTid=19474 nice=0 sched=0/0 cgrp=apps handle=1696367616
11-27 20:18:44.475: I/dalvikvm(19352):   | state=R schedstat=( 699007350 155348609 1888 ) utm=51 stm=18 core=3
11-27 20:18:44.475: I/dalvikvm(19352):   at com.google.android.exoplayer.hls.TsExtractor$Sample.<init>(TsExtractor.java:~1136)
11-27 20:18:44.475: I/dalvikvm(19352):   at com.google.android.exoplayer.hls.TsExtractor$SamplePool.get(TsExtractor.java:1107)
11-27 20:18:44.475: I/dalvikvm(19352):   at com.google.android.exoplayer.hls.TsExtractor$SampleQueue.getSample(TsExtractor.java:649)
11-27 20:18:44.475: I/dalvikvm(19352):   at com.google.android.exoplayer.hls.TsExtractor$SampleQueue.addSample(TsExtractor.java:662)
11-27 20:18:44.475: I/dalvikvm(19352):   at com.google.android.exoplayer.hls.TsExtractor$AdtsReader.readOneAacFrame(TsExtractor.java:1066)
11-27 20:18:44.480: I/dalvikvm(19352):   at com.google.android.exoplayer.hls.TsExtractor$AdtsReader.read(TsExtractor.java:1005)
11-27 20:18:44.480: I/dalvikvm(19352):   at com.google.android.exoplayer.hls.TsExtractor$PesReader.readPacketBody(TsExtractor.java:499)
11-27 20:18:44.480: I/dalvikvm(19352):   at com.google.android.exoplayer.hls.TsExtractor$PesReader.read(TsExtractor.java:443)
11-27 20:18:44.480: I/dalvikvm(19352):   at com.google.android.exoplayer.hls.TsExtractor.read(TsExtractor.java:275)
11-27 20:18:44.480: I/dalvikvm(19352):   at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:115)
11-27 20:18:44.480: I/dalvikvm(19352):   at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:206)
11-27 20:18:44.480: I/dalvikvm(19352):   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
11-27 20:18:44.480: I/dalvikvm(19352):   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-27 20:18:44.480: I/dalvikvm(19352):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-27 20:18:44.480: I/dalvikvm(19352):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-27 20:18:44.480: I/dalvikvm(19352):   at java.lang.Thread.run(Thread.java:841)
11-27 20:18:54.855: D/EventLogger(19352): state [11.49, true, B]
11-27 20:18:54.855: D/EventLogger(19352): droppedFrames [11.50, 1]
11-27 20:18:55.240: I/dalvikvm(19352): Jit: resizing JitTable from 4096 to 8192

**Comment by sachinbhanot** [comment]
Out of Memory issue is fixed if we play any stream in 10mb Bit rate ?
