### ISSUE TITLE
assert failed on BaseRenderer.replaceStream

### ISSUE THREAD

**Issue by mingchen** [google/ExoPlayer#1742]
**ExoPlayer version:**
dev-v2 f6fdcee9

**Device:**
Nexus 5

**OS:**
Android 6

**Description:**
When I use playlist to play a list of videos, sometime exoplayer's `onPlayerError()` get called, the type is TYPE_UNEXPECTED. before the `onPlayerError()`, exoplayer have following exception log:

```
 E/ExoPlayerImplInternal: Internal runtime error.
  java.lang.IllegalStateException
  at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:65)
  at com.google.android.exoplayer2.BaseRenderer.replaceStream(BaseRenderer.java:92)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1004)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:259)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at android.os.Looper.loop(Looper.java:148)
  at android.os.HandlerThread.run(HandlerThread.java:61)
  at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by ojw28** [comment]
I suspect this is fixed in the latest `dev-v2`. Please let us know if you still see the problem. Thanks!
