### ISSUE TITLE
Exoplayer demo-ext crashing (no more support on this lib ?)

### ISSUE THREAD

**Issue by NinoDLC** [google/ExoPlayer#1760]
Build the demo-ext on a G3 (for example). Click any Google Glass link. After buffering, it crashes. 

```
08-23 17:26:30.365 10641-11018/com.google.android.exoplayer.demo.ext E/art: No implementation found for long com.google.android.exoplayer.ext.vp9.VpxDecoder.vpxInit() (tried Java_com_google_android_exoplayer_ext_vp9_VpxDecoder_vpxInit and Java_com_google_android_exoplayer_ext_vp9_VpxDecoder_vpxInit__)
08-23 17:26:30.370 10641-11018/com.google.android.exoplayer.demo.ext E/AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
                                                                                       Process: com.google.android.exoplayer.demo.ext, PID: 10641
                                                                                       java.lang.UnsatisfiedLinkError: No implementation found for long com.google.android.exoplayer.ext.vp9.VpxDecoder.vpxInit() (tried Java_com_google_android_exoplayer_ext_vp9_VpxDecoder_vpxInit and Java_com_google_android_exoplayer_ext_vp9_VpxDecoder_vpxInit__)
                                                                                           at com.google.android.exoplayer.ext.vp9.VpxDecoder.vpxInit(Native Method)
                                                                                           at com.google.android.exoplayer.ext.vp9.VpxDecoder.<init>(VpxDecoder.java:74)
                                                                                           at com.google.android.exoplayer.ext.vp9.LibvpxVideoTrackRenderer.doSomeWork(LibvpxVideoTrackRenderer.java:221)
                                                                                           at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                           at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

Also, tremendous amount of link (over the internet) are broken because you no longer use a `master` branch. For exemple, follow any link in this guide : https://google.github.io/ExoPlayer/guide.html

Finally, your https://github.com/google/ExoPlayer/blob/release-v1/CONTRIBUTING.md is pointing to a broken URL : https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html

**Comment by ojw28** [comment]
- I've fixed the three broken links (CONTRIBUTING.md will remain broken on the dev branches for now, but we'll push fixes for those too in due course).
- As for your issue, did you build the extensions correctly? You need to build them all as per their instructions. For example the VP9 instructions [here](https://github.com/google/ExoPlayer/tree/release-v1/extensions/vp9).

**Comment by ojw28** [comment]
Closing due to lack of response. Please follow the build instructions for the extensions, as per the second bullet point in my previous reply. Thanks!
