### ISSUE TITLE
Can not play m3u8 with android APIv 18

### ISSUE THREAD

**Issue by davidarchi** [google/ExoPlayer#1770]
Hi.
I have tried to streamming m3u8 with the link 

"link"

by adding code in Sample.java:

`public static final Sample[] HLS = new Sample[] {
    new Sample("Apple master playlist",
        ""link", Util.TYPE_HLS),`

but this video cannot play with **Android APIv 18.**
It shown log like below:
`08-23 22:49:05.483 1603-1603/com.google.android.exoplayer.demo I/ExoPlayerImpl: Init 1.5.6
08-23 22:49:05.483 1603-1603/com.google.android.exoplayer.demo D/EventLogger: start [0]
08-23 22:49:05.483 1603-1603/com.google.android.exoplayer.demo D/EventLogger: state [0.00, false, P]
08-23 22:49:05.483 1603-1603/com.google.android.exoplayer.demo D/EventLogger: state [0.00, true, P]
08-23 22:49:05.525 1603-1603/com.google.android.exoplayer.demo W/EGL_emulation: eglSurfaceAttrib not implemented
08-23 22:49:05.593 1603-15011/com.google.android.exoplayer.demo D/dalvikvm: GC_FOR_ALLOC freed 976K, 35% free 8155K/12392K, paused 25ms, total 29ms
08-23 22:49:05.645 1603-15012/com.google.android.exoplayer.demo I/OMXClient: Using client-side OMX mux.
08-23 22:49:05.645 1603-15015/com.google.android.exoplayer.demo I/OMXClient: Using client-side OMX mux.
08-23 22:49:05.653 1603-15013/com.google.android.exoplayer.demo E/SoftAVC: Decoder failed: -2
08-23 22:49:05.653 1603-15012/com.google.android.exoplayer.demo E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
08-23 22:49:05.673 1603-15012/com.google.android.exoplayer.demo E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -2147483648)
08-23 22:49:05.673 1603-15004/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                         java.lang.IllegalStateException
                                                                                             at android.media.MediaCodec.dequeueInputBuffer(Native Method)
                                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:552)
                                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:493)
                                                                                             at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                             at android.os.Looper.loop(Looper.java:137)
                                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
08-23 22:49:05.687 1603-1603/com.google.android.exoplayer.demo D/EventLogger: state [0.20, true, B]
08-23 22:49:05.687 1603-1603/com.google.android.exoplayer.demo D/EventLogger: videoFormat [0.20, 0, 0]
08-23 22:49:05.687 1603-1603/com.google.android.exoplayer.demo D/EventLogger: decoderInitialized [0.20, OMX.google.h264.decoder]
08-23 22:49:05.687 1603-1603/com.google.android.exoplayer.demo D/EventLogger: decoderInitialized [0.20, OMX.google.aac.decoder]
08-23 22:49:05.693 1603-1603/com.google.android.exoplayer.demo E/EventLogger: playerFailed [0.21]
                                                                              com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:137)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                               Caused by: java.lang.IllegalStateException
                                                                                  at android.media.MediaCodec.dequeueInputBuffer(Native Method)
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:552)
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:493)
                                                                                  at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                  at android.os.Looper.loop(Looper.java:137) 
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
08-23 22:49:05.693 1603-1603/com.google.android.exoplayer.demo D/EventLogger: state [0.21, true, I]
08-23 22:49:05.744 1603-1603/com.google.android.exoplayer.demo W/EGL_emulation: eglSurfaceAttrib not implemented
`

**Note :** This video can work well in Android API 20.
Could you help me in that case ?

**Comment by ojw28** [comment]
Please provide a full bug report, as is explicitly requested in the issue template.

**Comment by davidarchi** [comment]
[log.txt](https://github.com/google/ExoPlayer/files/434327/log.txt)

Hi, I added log when reproduce this issue.
Thanks

**Comment by ojw28** [comment]
Please attach the output of "adb bugreport" rather than "adb logcat". Is this running on an emulator or a physical device?

**Comment by davidarchi** [comment]
[bugreport.txt](https://github.com/google/ExoPlayer/files/434366/bugreport.txt)
I attached again.
I tested it with emulator.
Thanks

**Comment by ojw28** [comment]
The emulator didn't do a good job of supporting video playback until pretty recent API levels. From your original post, it sounds as though it works properly once you get up to API level 20, although support probably becomes more robust the further you go beyond 20.

This is an issue with the emulator rather than with ExoPlayer. I don't think there are any plans to fix it for the older API levels, unfortunately. Playback is expected work correctly on real devices.

**Comment by davidarchi** [comment]
Thanks Ojw :D
