### ISSUE TITLE
Could not play HLS Streams in some emulators

### ISSUE THREAD

**Issue by visakhvj** [google/ExoPlayer#1771]
Hi,
I was trying to play HLS streams in some of the Android emulators like Leapdroid and bluestack.
But its not playing and got the following error log.

```
Could not find method android.media.MediaCodecInfo$CodecCapabilities.getVideoCapabilities, referenced from method com.google.android.exoplayer.MediaCodecUtil.getVideoCapabilitiesV21
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:04:17.656 I/dalvikvm(3556): Could not find method android.media.MediaCodecInfo$VideoCapabilities.areSizeAndRateSupported, referenced from method com.google.android.exoplayer.MediaCodecUtil.isSizeAndRateSupportedV21
08-23 22:07:39.184 D/leapdroid_hostime(717): UDP Client: Sending...RET_SET_CLIPBOARD_DATA_END:3556): Could not find method android.media.MediaCodecInfo$VideoCapabilities.isSizeSupported, referenced from method com.google.android.exoplayer.MediaCodecUtil.isSizeSupportedV21
```

**Comment by ojw28** [comment]
I don't think the log snippet you post is relevant (which is one of the reasons why our issue template explicitly requests a full bug report, not just a snippet).

That aside, this is likely an issue with the emulators rather than with ExoPlayer, so you should file issues on them rather than here. The official Android emulator does work well with ExoPlayer for recent API levels, I believe.

**Comment by visakhvj** [comment]
This is the full log of that exception. The issue is exist with the exo player demo app, when we run the APK of Bluestack or Leapdroid.

```
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://cdn3.viblast.com/streams/hls/airshow/playlist.m3u8
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:03:55.772 E/EventLogger(3556):    at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:03:55.772 E/EventLogger(3556):    at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:03:55.772 E/EventLogger(3556):    at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternbuflength = 511
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:03:55.772 E/EventLogger(3556):    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:03:55.772 E/EventLogger(3556):    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:03:55.772 E/EventLogger(3556): Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://cdn3.viblast.com/streams/hls/airshow/playlist.m3u8 buflength = 511
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:03:55.772 E/EventLogger(3556):    at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:202)
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:03:55.772 E/EventLogger(3556):    at com.google.android.exoplayer.upstream.DefaultUriDatabuflength = 511
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:03:55.772 E/EventLogger(3556):    at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:107)
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:03:55.772 E/EventLogger(3556):    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:03:55.772 E/EventLogger(3556):    at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:199)
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:04:12.500 I/URL     (3556): EXOPlayer video URL:https://yams-3-buflength = 511
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:04:12.500 I/EXOMediaPlayer(3556): Invoked the prepareplayer
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:04:12.500 I/ExoPlayerImpl(3556): Init 1.5.9
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:04:12.500 I/EXOMediaPlayer(3556): Invoked the listeners
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:04:12.500 I/EXOMediaPlayer(3556): Invoked the playbuflength = 511
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:04:17.656 I/dalvikvm(3556): Could not find method android.media.MediaCodecInfo$CodecCapabilities.getVideoCapabilities, referenced from method com.google.android.exoplayer.MediaCodecUtil.getVideoCapabilitiesV21
08-23 22:07:39.184 D/leapdroid_hostime(717): 08-23 22:04:17.656 I/dalvikvm(3556): Could not find method android.media.MediaCodecInfo$VideoCapabilities.areSizeAndRateSupported, referenced from method com.google.android.exoplayer.MediaCodecUtil.isSizeAndRateSupportedV21
08-23 22:07:39.184 D/leapdroid_hostime(717): UDP Client: Sending...RET_SET_CLIPBOARD_DATA_END:3556): Could not find method android.media.MediaCodecInfo$VideoCapabilities.isSizeSupported, referenced from method com.google.android.exoplayer.MediaCodecUtil.isSizeSupportedV21
```

**Comment by ojw28** [comment]
The relevant bit is:

```
Unable to connect to http://cdn3.viblast.com/streams/hls/airshow/playlist.m3u8
```

which suggests your app and/or the emulator doesn't have network connectivity (or else is broken in a way that causes ExoPlayer to experience a lack of network connectivity). This is an issue with your setup or the emulator, not with ExoPlayer.

**Comment by visakhvj** [comment]
But network connectivity is there with the emulator, and all other APIs are working fine. Only the problem occurred to EXO player.

**Comment by ojw28** [comment]
If you look at the DefaultHttpDataSource implementation, you'll see that all it does is call through to the platform network API (HttpURLConnection). In this case the platform network API is saying that it cannot connect, and DefaultHttpDataSource is then propagating that error up. So it's not even like it's something in the ExoPlayer layer that's failing.
