### ISSUE TITLE
HLS IllegalStateException only on some devices

### ISSUE THREAD

**Issue by makvasic** [google/ExoPlayer#1772]
Hi,

I am getting this error only on Samsung Galaxy S4 (5.1) among devices that I test on (TESLA Tablet 785 (4.2.2), S3 (4.4.2), LG G3 (6.0)).
If relevant, error is present on Nexus 4 (API 16) and Nexus 5X (API 22) emulators, for Nexus 6 (API 23) and Nexus 10 (API 23) emulators work fine.

```
08-24 07:44:31.206 2450-2830/com.google.android.exoplayer.demo E/SoftAVC: Decoder failed: -2
08-24 07:44:31.211 2450-2829/com.google.android.exoplayer.demo E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
08-24 07:44:31.211 2450-2829/com.google.android.exoplayer.demo E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
08-24 07:44:31.211 2450-2828/com.google.android.exoplayer.demo E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
08-24 07:44:31.213 2450-2799/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal runtime error.
        java.lang.IllegalStateException
            at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
            at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:983)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:591)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:530)
            at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

This issue is similar to #1383 which was discussed on #1385.

This is the [stream](http://148.251.85.99:1935/edutv/edutelevizija/playlist.m3u8) but in order to reproduce the bug some changes are needed as stated in #1464 by @AquilesCanta.
This is my workaround until source is fixed. 
(I replaced line 197 `width = Integer.parseInt(widthAndHeight[0]);` in `HlsPlaylistParser` of DemoApp with `width = 720;` or better just set `String resolutionString = null;` on line 192)

I should mention that behavior is the same for demo and demo-v2.

Here is the [bugreport](https://github.com/google/ExoPlayer/files/434251/bugreport.txt) and [full logcat](https://github.com/google/ExoPlayer/files/434275/logcat.txt).

**Comment by AquilesCanta** [comment]
Well... I can see three causes for this:
1. In older devices, the main profile might be unsupported. [This(#683)](https://github.com/google/ExoPlayer/issues/683) and [this(media format support)](https://developer.android.com/guide/appendix/media-formats.html) might be helpful.
2. The playlist is live. Does the issue reproduce instantly? If not, the encoding might be somehow sporadically changing so reproducing this might not be straightforward. I don't think this is too probable. If it always reproduces instantly, i'd go for the other two and ignore this one.
3. Emulators are not the ideal place to test video playback. For example, I was not able to reproduce this on a nexus5.

In version two, for playlist such as this one, in which there is only one entry, the resolution parsing will not be a problem as the width and height will be taken directly from the contents instead of the platylist.  Though this is still not available.

I will use this issue to track h264 profile support checks in version 2. This will not help you too much, but at least we will show a toast instead of throwing runtime error. I will write back once I add these checks, so you can try this on v2 and let me know the results.

**Comment by makvasic** [comment]
OK thanks.
It's definitely main profile because issue does reproduce instantly on both emulators and real device.

Just a thought about toast, isn't it better to throw meaningful exception so we can handle it ourselves?

Keep up good work, cheers.

**Comment by AquilesCanta** [comment]
Yes, the toast happens in the Demo app. No exception is thrown, though. You can have a look at the TrackSelector hierarchy to learn more about track support.

**Comment by AquilesCanta** [comment]
Well... The checks for AVC codecs have now been added to version 2. Please give it a try(once it gets pushed) and let me know if there are any issues.

**Comment by makvasic** [comment]
Nice,
 I just tested with latest version of demo-v2 (_commit 50527c0a7df296a78d0f6da096622d98cca03926_) and here're my findings:
For S3 and TESLA stream working normally and for others (S4, LG G3 and emulator Nexus 6 API 23) there is only audio with toast message.
![screenshot_1472715938_scaled](https://cloud.githubusercontent.com/assets/9867964/18161856/0bf639a6-7034-11e6-8280-a48a337afef1.png)
Hope this puts some light on the issue because there's no error thrown.
I suppose this means main profile of video codec is to blame, but do you have any suggestions or workarounds like in #1464?

**Comment by makvasic** [comment]
OK, actually behavior is the same as in #1464. Back then when I tested with v2 it was the same.
Again hard-coding video width value to 720 we come back to this issue.
So, it seems that 50527c0a7df296a78d0f6da096622d98cca03926 didn't bring any changes regarding #1464 :confused:

**Comment by AquilesCanta** [comment]
No, no. They are two different issues. #1464 declares an incorrect resolution(being the manifest resolution not supported), but the video is actually fine to play. This issue(#1772), on the other hand, refers to codecs that are not supported on the running device. There is no workaround for this, unfortunately, besides providing your own software decoder. Note that this is not a simple task.

In the near future, in HLS, for the first variant listed in the manifest we are going to use the actual resolution of the video, instead of the one listed in the playlist, so this workaround(#1464) won't be needed anymore. Just FYI. Can we close this issue now?

**Comment by makvasic** [comment]
Sorry on misunderstanding on #1464.
But as I said

> Again hard-coding video width value to 720 we come back to this issue.

which means #1772 is still present...
So, it seems that 50527c0a7df296a78d0f6da096622d98cca03926 didn't bring any changes regarding #1772 :)

```
09-01 10:16:08.226 1556-19558/com.google.android.exoplayer2.demo E/OMXNodeInstance: OMX_GetExtensionIndex failed
09-01 10:16:08.286 1556-19564/com.google.android.exoplayer2.demo E/OMXNodeInstance: OMX_GetExtensionIndex failed
09-01 10:16:08.296 1556-19562/com.google.android.exoplayer2.demo E/SoftAVC: Decoder failed: -2
09-01 10:16:08.306 1556-19558/com.google.android.exoplayer2.demo E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
09-01 10:16:08.306 1556-19558/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -2147483648)
09-01 10:16:08.306 1556-19548/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
        java.lang.IllegalStateException
            at android.media.MediaCodec.dequeueInputBuffer(Native Method)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:536)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:478)
            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:430)
            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
09-01 10:16:08.326 1556-1556/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [0.69]
        com.google.android.exoplayer2.ExoPlaybackException
            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
        Caused by: java.lang.IllegalStateException
            at android.media.MediaCodec.dequeueInputBuffer(Native Method)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:536)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:478)
            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:430)
            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
            at android.os.Handler.dispatchMessage(Handler.java:95) 
            at android.os.Looper.loop(Looper.java:137) 
            at android.os.HandlerThread.run(HandlerThread.java:60) 
            at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by AquilesCanta** [comment]
I thought you had said:

> For S3 and TESLA stream working normally and for others (S4, LG G3 and emulator Nexus 6 API 23) there is only audio with toast message.

When does the toast appear and when does the exception you pasted occur?

**Comment by makvasic** [comment]
Toast is for #1464 when manifest declares wrong resolution and we can forget about that.

Error is the same as stated in the first comment:

> I am getting this error only on Samsung Galaxy S4 (5.1) among devices that I test on (TESLA Tablet 785 (4.2.2), S3 (4.4.2), LG G3 (6.0)).
> If relevant, error is present on Nexus 4 (API 16) and Nexus 5X (API 22) emulators, for Nexus 6 (API 23) and Nexus 10 (API 23) emulators work fine.

We are talking about latest demo-v2. Sorry for the confusion.
In short 50527c0a7df296a78d0f6da096622d98cca03926 did not fix this issue (#1772).

**Comment by AquilesCanta** [comment]
This should finally be fixed in the next push.

**Comment by makvasic** [comment]
Hi,

I am on vacation until Wednesday, so I'll check the results when I come back.

Thanks.

**Comment by makvasic** [comment]
OK, I can confirm that this is fixed with release-v2 demo app.

Thanks for the support.
