### ISSUE TITLE
 java.lang.IllegalStateException: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {3eb3ac2b} sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by woniu0936** [google/ExoPlayer#1775]
W/MessageQueue: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {3eb3ac2b} sending message to a Handler on a dead thread
                                                                 java.lang.IllegalStateException: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {3eb3ac2b} sending message to a Handler on a dead thread
                                                                     at android.os.MessageQueue.enqueueMessage(MessageQueue.java:337)
                                                                     at android.os.Handler.enqueueMessage(Handler.java:707)
                                                                     at android.os.Handler.sendMessageAtTime(Handler.java:609)
                                                                     at android.os.Handler.sendMessageDelayed(Handler.java:579)
                                                                     at android.os.Handler.sendEmptyMessageDelayed(Handler.java:543)
                                                                     at android.os.Handler.sendEmptyMessage(Handler.java:528)
                                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:231)
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by woniu0936** [comment]
when i leave videoPlayerActivity，there always show the warn in log

**Comment by ojw28** [comment]
Please see https://github.com/google/ExoPlayer/issues/426. The key points being:
- The warning is harmless and can be safely ignored.
- The warning will go away in V2.
