### ISSUE TITLE
Exoplayer unable to stream certain AAC encoded audio with .m3u8

### ISSUE THREAD

**Issue by spark85** [google/ExoPlayer#178]
I'm porting an audio player project from Vitamio to ExoPlayer.  I've been able to get it working, except I have two audio sources that will not play.  There is no noticable difference between them and other samples that playback perfectly fine.  The issue is not sample length since very long running samples play as well.   Here are links to the sample file: 

http://s3.amazonaws.com/instarad_audio/20/208888/index.m3u8
http://s3.amazonaws.com/instarad_audio/20/208237/index.m3u8

Here is the error --> 

```
java.lang.IllegalStateException
        at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
        at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:720)
        at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:420)
        at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:398)
        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

11-27 17:50:05.423  28529-28571/com.google.android.exoplayer.demo E/OMXNodeInstance﹕ OMX_FreeBuffer for buffer h

I'm creating these samples as TYPE_HLS_MEDIA, either with AUDIO_AAC encoding or  VIDEO_H264. 

My best guess is that these samples were recorded with an unusuall sample rate, or they are somehow corrupt. 

All samples will be encoded as AAC streaming through .m3u8 format.  Are there other Renders/Encoders I should be looking at? 

Thank you, 
David

**Comment by martinbonnin** [comment]
Just for reference, I just came across the same issue with AAC main profile (object type 1). Apparently, it is not supported either: See https://github.com/mstorsjo/fdk-aac/blob/047376af8c47d45c78204112a7d1b873c93822bc/libMpegTPDec/src/tpdec_asc.cpp#L1318
