### ISSUE TITLE
SegmentBase ClassCastException when parsing DASH .mpd file

### ISSUE THREAD

**Issue by SLepUbIn** [google/ExoPlayer#1783]
Hi,

I got the following stacktrace when trying to parse a .mpd file:

```
Exception in thread "main" java.lang.ClassCastException: com.google.android.exoplayer.dash.mpd.SegmentBase$SingleSegmentBase cannot be cast to com.google.android.exoplayer.dash.mpd.SegmentBase$SegmentList
    at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseRepresentation(MediaPresentationDescriptionParser.java:398)
    at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseAdaptationSet(MediaPresentationDescriptionParser.java:261)
    at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parsePeriod(MediaPresentationDescriptionParser.java:209)
    at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseMediaPresentationDescription(MediaPresentationDescriptionParser.java:140)
    at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:104)
```

The playlist file is the following one : 
http://www-itec.uni-klu.ac.at/ftp/datasets/mmsys12/BigBuckBunny/MPDs/BigBuckBunnyNonSeg_4s_isoffmain_DIS_23009_1_v_2_1c2_2011_08_30.mpd
Seems like the first SegmentBase is causing a SingleSegmentBase to be instantiated and the subsequent SegmentList urls need to cast the SingleSegmentBase to a SegmentList.
Is this way of representing a media common ?
If so, is there a way to get around this ?
Thanks.

**Comment by ojw28** [comment]
I think the mpd file is invalid. It contains SegmentBase and SegmentList elements at the same depth in the manifest, but according to the DASH spec (ISO 23009-1):

> At each level at most one of the three, SegmentBase, SegmentTemplate and SegmentList shall be present.

So this is a violation of the DASH spec:

```
<SegmentBase>
  <Initialization sourceURL="bunny_4s_50kbit/bunny_50kbit_dashNonSeg.mp4" range="0-862"/>
</SegmentBase>
<SegmentList duration="4">
  <SegmentURL media="bunny_4s_50kbit/bunny_50kbit_dashNonSeg.mp4" mediaRange="863-22486"/>
  ....
```

A spec compliant manifest would only have the `SegmentList` element, probably like this:

```
<SegmentList duration="4">
  <Initialization sourceURL="bunny_4s_50kbit/bunny_50kbit_dashNonSeg.mp4" range="0-862"/>
  <SegmentURL media="bunny_4s_50kbit/bunny_50kbit_dashNonSeg.mp4" mediaRange="863-22486"/>
  ....
```

**Comment by SLepUbIn** [comment]
Ok, thank you very much, for your feedback
