### ISSUE TITLE
Emulator with lower API devices: Decoder failed and throws exception

### ISSUE THREAD

**Issue by hadifar** [google/ExoPlayer#1785]
The following exception happen when I run [this](http://www.sample-videos.com/video/mp4/480/big_buck_bunny_480p_10mb.mp4) URL in emulator with **Nexus 10** and **API 17**. ( not happen in Android 5.0)

Also one thing to mention: In demo app if I turned off video (with Video button in PlayerActivity) the sound play.

The video information based on MediaInfo:

Video: AVC, 1280*720 (16:9), 25.000 FPS
Audio: AAC, 48 kHz, 6Channels

```

08-29 19:17:52.772 430-657/E/SoftAVC: Decoder failed: -2
08-29 19:17:52.772 430-656/ E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
08-29 19:17:52.772 430-656/ E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -2147483648)
08-29 19:17:52.772 430-442/ E/ExoPlayerImplInternal: Internal runtime error.
                                                                        java.lang.IllegalStateException
                                                                            at android.media.MediaCodec.dequeueInputBuffer(Native Method)
                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:591)
                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:530)
                                                                            at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:137)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:60)
                                                                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
08-29 19:17:52.782 430-430/ir.apio.videoplayer E/EventLogger: playerFailed [19.57]
                                                              com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:244)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:137)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:60)
                                                                  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                               Caused by: java.lang.IllegalStateException
                                                                  at android.media.MediaCodec.dequeueInputBuffer(Native Method)
                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:591)
                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:530)
                                                                  at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                  at android.os.Looper.loop(Looper.java:137) 
                                                                  at android.os.HandlerThread.run(HandlerThread.java:60) 
                                                                  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

**Comment by ojw28** [comment]
The emulator does not properly support media applications unless running a system image with API level 23 or greater. This is a shortcoming of the emulator, not an ExoPlayer issue. Where possible, we recommend testing media applications on physical devices rather than emulators.
