### ISSUE TITLE
Internal track renderer error. 

### ISSUE THREAD

**Issue by YGStar** [google/ExoPlayer#1788]
ExoPlayer Demo version : 1.5.10

exoplayer demo app occured exception my mpd files.
i attach screen capture in debug mode when error occured.

![dash_error](https://cloud.githubusercontent.com/assets/18640101/18123496/19be2f16-6fa9-11e6-8d10-6b21f7596636.jpg)

```
Internal track renderer error.
  com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: src.length=8192 srcPos=-8 dst.length=8192 dstPos=0 length=8
      at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:262)
      at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:144)
      at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:439)
      at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
      at android.os.Handler.dispatchMessage(Handler.java:98)
      at android.os.Looper.loop(Looper.java:136)
      at android.os.HandlerThread.run(HandlerThread.java:61)
      at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
   Caused by: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: src.length=8192 srcPos=-8 dst.length=8192 dstPos=0 length=8
      at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:235)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
      at java.lang.Thread.run(Thread.java:841)
   Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=8192 srcPos=-8 dst.length=8192 dstPos=0 length=8
      at java.lang.System.arraycopy(Native Method)
      at com.google.android.exoplayer.extractor.DefaultExtractorInput.updatePeekBuffer(DefaultExtractorInput.java:213)
      at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFromPeekBuffer(DefaultExtractorInput.java:183)
      at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:92)
      at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:103)
      at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:285)
      at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:189)
      at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:92)
      at com.google.android.exoplayer.chunk.InitializationChunk.load(InitializationChunk.java:189)
      at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
      at java.lang.Thread.run(Thread.java:841) 
```

**Comment by AquilesCanta** [comment]
Make sure you provide all information required in the issue template. 

Please provide a link for us to reproduce the issue. Unfortunately, this is not enough. You can send them to dev.exoplayer@gmail.com if you don't want to post them here.

**Comment by ojw28** [comment]
The failure suggests your mp4 files are malformed. They appear to contain atoms/boxes that define their size incorrectly. As above, we'd need access to the content to tell you exactly what's wrong.

**Comment by YGStar** [comment]
[test.txt](https://github.com/google/ExoPlayer/files/448866/test.txt)

thanks to reply.
i met another exception.
"com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null"

but with dash.js in browser, played as well.

test mpd file attached.

**Comment by ojw28** [comment]
Providing the manifest without any of the underlying media segments is not useful to us, particularly given we believe the issue is in the underlying media segments. Please provide complete test content, meaning that we can take whatever link or files you attach and actually try and play them. Else we are unable to assist. Thanks!

**Comment by YGStar** [comment]
thanks. i solved problem.
test mpd file that i tested does not contains about audio segment info.
thanks to reply.
