### ISSUE TITLE
ArrayIndexOutOfBoundsException at HLS stream

### ISSUE THREAD

**Issue by AAkira** [google/ExoPlayer#1801]
Hi, 

I saw this isssue #1695. 
This problem persists in version 1.5.10.
It occurs when stream is live, I'm sorry I don't provide a stream url.

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-5
       at java.util.ArrayList.get(ArrayList.java:310)
       at java.util.Collections$UnmodifiableList.get(Collections.java:1054)
       at com.google.android.exoplayer.hls.HlsChunkSource.getLiveNextChunkSequenceNumber(HlsChunkSource.java:699)
       at com.google.android.exoplayer.hls.HlsChunkSource.getChunkOperation(HlsChunkSource.java:411)
       at com.google.android.exoplayer.hls.HlsSampleSource.maybeStartLoading(HlsSampleSource.java:711)
       at com.google.android.exoplayer.hls.HlsSampleSource.onLoadCompleted(HlsSampleSource.java:436)
       at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:258)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:224)
       at android.os.HandlerThread.run(HandlerThread.java:61)
       at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by ojw28** [comment]
Closing due to lack of useful information (a stream url).
