### ISSUE TITLE
Encrypted video producing compression artifacts in Exoplayer 1.5.10

### ISSUE THREAD

**Issue by mlondon1** [google/ExoPlayer#1813]
Hi,
We are seeing compression artifacts when playing common-encrypted Dash content using Widevine DRM in Exoplayer 1.5.10 on Samsung Tab2 (SM-T810) in Android 6.0.1.   When the video bit rate gets up to the 4.5 Mbps 1080p profile, the video gets distorted and discolored showing compression artifacts on and off indefinitely.  It exhibited the issue at 720p but to a much lower degree.   On other devices such as the HTC 10 and Nexus 6 drop frames instead.

On the Tab2 (SM-T810), the issue does not happen when playing unencrypted video (using the same source MP4s).

We can provide some of the sample premium video via email.

Here are some logs around the time of the issue, though not necessarily the cause

```
09-09 16:48:01.855 3558-12658/com.google.android.exoplayer.demo I/ACodec: [OMX.Exynos.avc.dec.secure] Now handling output port settings change
09-09 16:48:01.855 3558-12658/com.google.android.exoplayer.demo W/AHierarchicalStateMachine: Warning message AMessage(what = 'omxI') = {
                                                                                               int32_t type = 0
                                                                                               int32_t event = 3
                                                                                               int32_t data1 = 1
                                                                                               int32_t data2 = 117440527
                                                                                             } unhandled in root state.
09-09 16:48:02.190 3558-12658/com.google.android.exoplayer.demo D/SurfaceUtils: set up nativeWindow 0xadfba808 for 1920x1088, color 0x105, rotation 0, usage 0x806900
09-09 16:48:02.190 3558-12658/com.google.android.exoplayer.demo W/ACodec: [OMX.Exynos.avc.dec.secure] setting nBufferCountActual to 13 failed: -2147483648
09-09 16:48:02.195 3558-12658/com.google.android.exoplayer.demo I/ACodec: [OMX.Exynos.avc.dec.secure] configureOutputBuffersFromNativeWindow setBufferCount : 12, minUndequeuedBuffers : 3
09-09 16:48:02.205 3558-12658/com.google.android.exoplayer.demo I/ACodec: [OMX.Exynos.avc.dec.secure] Now Executing
09-09 16:48:02.275 3558-3558/com.google.android.exoplayer.demo D/EventLogger: videoSizeChanged [1920, 1080, 0, 1.0]
09-09 16:48:05.405 3558-11276/com.google.android.exoplayer.demo W/MessageQueue: Handler (com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostResponseHandler) {f8e69c4} sending message to a Handler on a dead thread
                                                                                java.lang.IllegalStateException: Handler (com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostResponseHandler) {f8e69c4} sending message to a Handler on a dead thread
                                                                                    at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                                    at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                                    at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                                    at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                                    at android.os.Handler.sendMessage(Handler.java:507)
                                                                                    at android.os.Message.sendToTarget(Message.java:416)
                                                                                    at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostRequestHandler.handleMessage(StreamingDrmSessionManager.java:557)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:158)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by mlondon1** [comment]
Hi, can someone from the Exoplayer team provide some assistance?  The folks at Widevine have reproduced this on the same device model.  

We also saw green screens and dropped frames on other devices such as the Nexus 6 and HTC 10.

**Comment by ojw28** [comment]
I think Widevine are the right people to help you with this. DRM is reasonably transparent to ExoPlayer. The encryption + packaging is done by the content provider and the decryption is done by the Widevine CDM. ExoPlayer is the layer in the middle, but we don't really do anything special for DRM aside from pipe the data to where it needs to go.

The nature of the issues you're seeing suggest a encoding/encryption/packaging issue to me. What tool are you using to package the media, and are you able to play it successfully elsewhere?

**Comment by ojw28** [comment]
@wvpaf - Are you able to provide some assistance here? Thanks!

**Comment by faltmark** [comment]
+Prashant who was working with the partner on this as well

**Comment by ojw28** [comment]
Following up off thread; thanks.

**Comment by mlondon1** [comment]
Exoplayer 2.0 apparently resolved this issue for us

**Comment by ojw28** [comment]
Closing as issue was resolved by updating to ExoPlayer V2. Thanks!
