### ISSUE TITLE
Mp4 playback problem

### ISSUE THREAD

**Issue by timonchev** [google/ExoPlayer#1850]
Hello, have a problems with different files from 360 camera.
Some files is playback with errors. File for example with error playback : https://s3.eu-central-1.amazonaws.com/3dreal/stitch.mp4

Nexus 5, Android 6.01. But have same error on other device also.
Log..

```
E/LoadTask: Unexpected exception loading stream
            java.lang.IllegalArgumentException
                at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:37)
                at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:253)
                at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:333)
                at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:272)
                at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:263)
                at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:143)
                at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:575)
                at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                at java.lang.Thread.run(Thread.java:818)
E/EventLogger: internalError [1.60, loadError]
               com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                   at java.lang.Thread.run(Thread.java:818)
                Caused by: java.lang.IllegalArgumentException
                   at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:37)
                   at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:253)
                   at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:333)
                   at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:272)
                   at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:263)
                   at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:143)
                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:575)
                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                   at java.lang.Thread.run(Thread.java:818) 
E/EventLogger: internalError [1.69, loadError]
               com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:562)
                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                   at java.lang.Thread.run(Thread.java:818)
                Caused by: com.google.android.exoplayer2.upstream.DataSourceException
                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:215)
                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:562) 
                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                   at java.lang.Thread.run(Thread.java:818) 
E/EventLogger: internalError [3.13, loadError]
               com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:562)
                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                   at java.lang.Thread.run(Thread.java:818)
                Caused by: com.google.android.exoplayer2.upstream.DataSourceException
                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:215)
                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:562) 
                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                   at java.lang.Thread.run(Thread.java:818) 
E/EventLogger: internalError [5.53, loadError]
               com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:562)
                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                   at java.lang.Thread.run(Thread.java:818)
                Caused by: com.google.android.exoplayer2.upstream.DataSourceException
                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:215)
                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:562) 
                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                   at java.lang.Thread.run(Thread.java:818) 
E/ExoPlayerImplInternal: Source error.
                         com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                             at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:562)
                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                             at java.lang.Thread.run(Thread.java:818)
                          Caused by: com.google.android.exoplayer2.upstream.DataSourceException
                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:215)
                             at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:562) 
                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                             at java.lang.Thread.run(Thread.java:818) 
E/EventLogger: playerFailed [5.55]
               com.google.android.exoplayer2.ExoPlaybackException
                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:310)
                   at android.os.Handler.dispatchMessage(Handler.java:98)
                   at android.os.Looper.loop(Looper.java:148)
                   at android.os.HandlerThread.run(HandlerThread.java:61)
                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:562)
                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                   at java.lang.Thread.run(Thread.java:818)
                Caused by: com.google.android.exoplayer2.upstream.DataSourceException
                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:215)
                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:562) 
                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                   at java.lang.Thread.run(Thread.java:818) 
```

**Comment by ojw28** [comment]
What version of ExoPlayer is this with? Please could you try with a recent version and report back (i.e. 1.5.11 or 2.0.0)?

**Comment by timonchev** [comment]
Tested with 1.5.9 and 1.5.11 with gvr-sdk. With 2.0.0 also same error..

**Comment by timonchev** [comment]
With gvr-sdk I have this error log:

```
09-23 09:23:25.937 22801-22892/ru.justbrains.vrrentals I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
09-23 09:23:25.943 22801-22892/ru.justbrains.vrrentals I/OpenGLRenderer: Initialized EGL, version 1.4
09-23 09:23:25.970 22801-22880/ru.justbrains.vrrentals W/art: Attempt to remove non-JNI local reference, dumping thread
09-23 09:23:25.977 22801-22880/ru.justbrains.vrrentals W/Adreno-ES20: <get_simple_queries:1544>: GL_INVALID_ENUM
09-23 09:23:26.902 22801-22893/ru.justbrains.vrrentals E/LoadTask: Unexpected exception loading stream
                                                                   java.lang.IllegalArgumentException
                                                                       at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                                                                       at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:242)
                                                                       at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:312)
                                                                       at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:254)
                                                                       at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:245)
                                                                       at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:130)
                                                                       at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:837)
                                                                       at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:224)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)
09-23 09:23:28.953 22801-22893/ru.justbrains.vrrentals E/LoadTask: Unexpected exception loading stream
                                                                   java.lang.IllegalArgumentException
                                                                       at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                                                                       at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:242)
                                                                       at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:312)
                                                                       at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:254)
                                                                       at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:245)
                                                                       at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:130)
                                                                       at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:837)
                                                                       at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:224)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)
09-23 09:23:28.971 22801-22879/ru.justbrains.vrrentals E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:275)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                 Caused by: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                                                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:237)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                    at java.lang.Thread.run(Thread.java:818)
                                                                                 Caused by: java.lang.IllegalArgumentException
                                                                                    at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                                                                                    at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:242)
                                                                                    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:312)
                                                                                    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:254)
                                                                                    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:245)
                                                                                    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:130)
                                                                                    at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:837)
                                                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:224)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                    at java.lang.Thread.run(Thread.java:818) 
09-23 09:23:28.974 22801-22801/ru.justbrains.vrrentals E/VrVideoPlayerInternal: 183410522.onPlayerError
                                                                                com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:275)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                 Caused by: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                                                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:237)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                    at java.lang.Thread.run(Thread.java:818)
                                                                                 Caused by: java.lang.IllegalArgumentException
                                                                                    at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                                                                                    at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:242)
                                                                                    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:312)
                                                                                    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:254)
                                                                                    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:245)
                                                                                    at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:130)
                                                                                    at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:837)
                                                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:224)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                    at java.lang.Thread.run(Thread.java:818) 
09-23 09:23:28.974 22801-22801/ru.justbrains.vrrentals E/ru.justbrains.vrrentals.HomeFragment$VrVideoListener: loadError com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
```

**Comment by timonchev** [comment]
Fo example, first file is playback good after converting, but second is original file no playback..

![2016-09-22 15 40 23](https://cloud.githubusercontent.com/assets/2788684/18779062/fc34c85e-817f-11e6-8704-6d3c2c3ff729.png)
![2016-09-22 15 40 33](https://cloud.githubusercontent.com/assets/2788684/18779063/fc5f7040-817f-11e6-9d1f-d9f2d39a1ec4.png)

**Comment by andrewlewis** [comment]
stitch.mp4 appears to be invalid: the number of video sample timestamps that can be derived from the `stts` box is different from the actual number of samples, so the player throws an error due when it asserts that the sample metadata is valid.

We might replace the assertion with a logged warning at some point, but the proper fix is to write the MP4 container correctly.

**Comment by timonchev** [comment]
If you can, pls do replace the assertion with a logged warning at some point. This video from SYVR360 app, I'll contact with app developers.
