### ISSUE TITLE
NullPointerException when disable text renderer in case of sideloaded track

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#1854]
ExoPlayer v2.
I do load dash source with side loaded vtt tracks in the way described in:
https://github.com/google/ExoPlayer/issues/1853
When I set text renderer disabled in the way:

```
mTrackSelector.setRendererDisabled(rendererIndex, true);
```

I do experience:

```
09-23 20:01:03.100 E: Internal runtime error.
                      java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.exoplayer2.Renderer.render(long, long)' on a null object reference
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:430)
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                          at android.os.Handler.dispatchMessage(Handler.java:98)
                          at android.os.Looper.loop(Looper.java:148)
                          at android.os.HandlerThread.run(HandlerThread.java:61)
                          at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

Meanwhile, disable audio renderer works well.
Please, let me know what kind of additional information you do need to process this issue.

**Comment by ojw28** [comment]
I think you're somehow managing to include a null entry in the array of `TrackRenderer` instances passed to `ExoPlayer.prepare`, which would be a bug in your application code. Either way it should be pretty easy to attach a debugger and work out why the player is trying to invoke a method on a null `TrackRenderer`.

**Comment by ChernyshovYuriy** [comment]
It is still reproducible with the latest ExoPlayer 2.0.1.
Steps to reproduce:
- Add side-loaded track.
- Try to disable it.
- Observe exception attached.

Could you re-open it?

Stack trace:

```
10-03 16:35:39.453 E: ExoPlayerEventLogger.onPlayerError(127)   playerFailed [18.45]
                      com.google.android.exoplayer2.ExoPlaybackException
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315)
                          at android.os.Handler.dispatchMessage(Handler.java:98)
                          at android.os.Looper.loop(Looper.java:148)
                          at android.os.HandlerThread.run(HandlerThread.java:61)
                          at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                       Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.exoplayer2.Renderer.setCurrentStreamIsFinal()' on a null object reference
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1001)
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:413)
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                          at android.os.Handler.dispatchMessage(Handler.java:98) 
                          at android.os.Looper.loop(Looper.java:148) 
                          at android.os.HandlerThread.run(HandlerThread.java:61) 
                          at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                        (QPServiceBinder-Thread)
10-03 16:35:39.455 D: ExoPlayerVstbImpl$ExoPlayerListener.onPlayerError(1580)   Caused by:NullPointerException  (QPServiceBinder-Thread)
10-03 16:35:39.465 E: Stop failed.
                      java.lang.NullPointerException: Attempt to invoke interface method 'int com.google.android.exoplayer2.Renderer.getState()' on a null object reference
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.ensureStopped(ExoPlayerImplInternal.java:663)
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:620)
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:599)
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:317)
                          at android.os.Handler.dispatchMessage(Handler.java:98)
                          at android.os.Looper.loop(Looper.java:148)
                          at android.os.HandlerThread.run(HandlerThread.java:61)
                          at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by ojw28** [comment]
We will push a fix for this tomorrow.

**Comment by ChernyshovYuriy** [comment]
Thanks guys!

**Comment by ChernyshovYuriy** [comment]
Just verified proposed solution. Working as designed and as desired :-)
Thanks guys!
