### ISSUE TITLE
IllegalStateException when jump to the third party sharing module

### ISSUE THREAD

**Issue by huyn** [google/ExoPlayer#1862]
It occurs when I play multiple videos and want to share these videos via a third party social app(like facebook), then the activity is moved to background,  I get these logs. And when the activity is moved to foreground, these videos can not be played any more. Maybe you guys should check it.

```
09-26 11:28:39.687 32156-16175/com.aube.phone E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
09-26 11:28:39.687 32156-16175/com.aube.phone E/ACodec: signalError(omxError 0x80001001, internalError -19)
09-26 11:28:39.687 32156-16173/com.aube.phone E/MediaCodec: Codec reported err 0xffffffed, actionCode 0, while in state 6
09-26 11:28:39.687 32156-15958/com.aube.phone E/ExoPlayerImplInternal: Internal runtime error.
                                                                       java.lang.IllegalStateException
                                                                           at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
                                                                           at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:986)
                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:591)
                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:529)
                                                                           at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                           at android.os.Looper.loop(Looper.java:159)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                           at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
09-26 11:28:39.707 32156-15952/com.aube.phone E/ExoPlayerImplInternal: Stop failed.
                                                                       java.lang.IllegalStateException
                                                                           at android.media.MediaCodec.native_stop(Native Method)
                                                                           at android.media.MediaCodec.stop(MediaCodec.java:631)
                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.releaseCodec(MediaCodecTrackRenderer.java:485)
                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.onDisabled(MediaCodecTrackRenderer.java:447)
                                                                           at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onDisabled(MediaCodecVideoTrackRenderer.java:289)
                                                                           at com.google.android.exoplayer.TrackRenderer.disable(TrackRenderer.java:231)
                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.ensureDisabled(ExoPlayerImplInternal.java:659)
                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.stopAndDisable(ExoPlayerImplInternal.java:560)
                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:549)
                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:526)
                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:245)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                           at android.os.Looper.loop(Looper.java:159)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                           at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by ojw28** [comment]
You're probably not detaching the `Surface` that the player is rendering to before it's destroyed. This results in the player trying to draw into a surface that's no longer valid, which may result in failure.

Please ensure you're listening to `surfaceDestroyed` and clearing the surface from the player in a blocking manner. You can refer to the V1 demo app for an example of this. In V2 `SimpleExoPlayer` manages this task for you, which makes things easier.
