### ISSUE TITLE
Crash after trying to play FLV on r2.0.1

### ISSUE THREAD

**Issue by mvasilchuk** [google/ExoPlayer#1899]
Got a crash after trying to play one flv stream on Nexus 7 (2013):

```
java.lang.NullPointerException: Attempt to read from null array
at com.google.android.exoplayer2.source.ExtractorMediaPeriod.configureRetry(ExtractorMediaPeriod.java:460)
at com.google.android.exoplayer2.source.ExtractorMediaPeriod.onLoadError(ExtractorMediaPeriod.java:352)
at com.google.android.exoplayer2.source.ExtractorMediaPeriod.onLoadError(ExtractorMediaPeriod.java:49)
 at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:359)
 at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
 at android.os.HandlerThread.run(HandlerThread.java:61)
at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

Example stream: http://webtv.net.ua:8080/stream.flv

This stream cannot be played by r1.5.11 either (got error "Audio format not supported: 2") but at least it doesn't crash.

**Comment by ojw28** [comment]
We'll fix the crash (thanks!), but we wont be adding support for streams of this type (FLV containing MP3 and H263). We would accept a high quality pull request to add support, if someone external feels like spending time on it. We only support FLV at all due to an external contribution, and that contribution only supported FLV containing AAC and H264.

**Comment by ojw28** [comment]
Fixed to the extent it's going to be fixed. Feel free to send a pull request to add MP3 / H263 support in FLV if you feel motivated enough to create one!
