### ISSUE TITLE
ArrayIndexOutOfBoundsException on HLS stream, ExoPlayer v2.x

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#1900]
I had searched for the same exception but didn't found with the same scenario and root point of exception.
Reproduced on application assembled from dev-v2 (hash 89c43807), as well as assembled from release-v2.
Steps:
- launch application and select HLS -> "Apple 16x9 basic stream"
- once started, select Text -> "unknown"
- observe:

```
10-05 14:59:29.197 E: playerFailed [5.63]
                      com.google.android.exoplayer2.ExoPlaybackException
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315)
                          at android.os.Handler.dispatchMessage(Handler.java:98)
                          at android.os.Looper.loop(Looper.java:148)
                          at android.os.HandlerThread.run(HandlerThread.java:61)
                          at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                       Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=3
                          at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.setTrackGroupEnabledState(HlsSampleStreamWrapper.java:611)
                          at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.selectTracks(HlsSampleStreamWrapper.java:183)
                          at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.selectTracks(HlsMediaPeriod.java:167)
                          at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.updatePeriodTrackSelection(ExoPlayerImplInternal.java:1263)
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.reselectTracksInternal(ExoPlayerImplInternal.java:704)
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:293)
                          at android.os.Handler.dispatchMessage(Handler.java:98) 
                          at android.os.Looper.loop(Looper.java:148) 
                          at android.os.HandlerThread.run(HandlerThread.java:61) 
                          at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

**Comment by AquilesCanta** [comment]
Yes, this is a bug. I will use this to keep track of this. Also there is a possibly related issue that dates from the v1 older versions reproducible thorugh the Apple master playlist advanced (TS) stream by alternating from text option 2 to 1.

**Comment by ojw28** [comment]
My fault.

**Comment by ojw28** [comment]
Note - A similar issue also affects `MergingMediaSource` in the case that two of the children being merged contain tracks of the same type, and if the track selection for a renderer is switched from a track belonging to one child to a track belonging to the other in a single selection step.

**Comment by ChernyshovYuriy** [comment]
Just verified proposed solution. Working as designed and as desired :-)
Thanks guys!
