### ISSUE TITLE
Exo Player Not Playing URL in Fire Tv Stick.

### ISSUE THREAD

**Issue by mohdabdullah1986** [google/ExoPlayer#1904]
http://pcappvod.nexg.tv/pcappvod/v/http20/9xm/Interview_With_Singer_Aman_Trikha_1200.mp4/playlist.m3u8

```
Error Log 
10-06 15:20:47.782 19205-19205/com.google.android.exoplayer2.demo E/EventLogger: internalError [26.64, loadError]
                                                                                 com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:267)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:128)
                                                                                     at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:247)
                                                                                     at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:56)
                                                                                     at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:170)
                                                                                     at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:180)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
                                                                                     at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:592)
                                                                                     at libcore.io.IoBridge.recvfrom(IoBridge.java:556)
                                                                                     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
                                                                                     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                                                     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                                     at com.android.okio.Okio$2.read(Okio.java:113)
                                                                                     at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
                                                                                     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:462)
                                                                                     at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:554)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:265)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:128) 
                                                                                     at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:247) 
                                                                                     at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:56) 
                                                                                     at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:170) 
                                                                                     at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:180) 
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                     at java.lang.Thread.run(Thread.java:818) 
                                                                                  Caused by: android.system.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
                                                                                     at libcore.io.Posix.recvfromBytes(Native Method)
                                                                                     at libcore.io.Posix.recvfrom(Posix.java:186)
                                                                                     at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
                                                                                     at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
                                                                                     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485) 
                                                                                     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37) 
                                                                                     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237) 
                                                                                     at com.android.okio.Okio$2.read(Okio.java:113) 
                                                                                     at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48) 
                                                                                     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:462) 
                                                                                     at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168) 
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:554) 
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:265) 
                                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:128) 
                                                                                     at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:247) 
                                                                                     at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:56) 
                                                                                     at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:170) 
                                                                                     at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:180) 
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                     at java.lang.Thread.run(Thread.java:818) 
10-06 15:20:47.812 19205-19205/com.google.android.exoplayer2.demo E/EventLogger: internalError [26.72, loadError]
10-06 15:20:48.002 19205-19205/com.google.android.exoplayer2.demo D/EventLogger: state [26.91, true, B]
10-06 15:20:48.812 19205-19205/com.google.android.exoplayer2.demo E/EventLogger: internalError [27.72, loadError]
10-06 15:20:50.812 19205-19205/com.google.android.exoplayer2.demo E/EventLogger: internalError [29.73, loadError]
10-06 15:20:50.812 19205-24976/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Source error.
10-06 15:20:50.822 19205-24976/com.google.android.exoplayer2.demo I/MediaCodecLogger:  com.google.android.exoplayer2.demo.SW.audio.mp4a.TotalAudioPlaybackTimeMs = 15580
10-06 15:20:50.822 19205-24976/com.google.android.exoplayer2.demo I/MediaCodecLogger: MediaCodecLogger:MMSW_Metrics5.2.1.1:com.google.android.exoplayer2.demo.SW.audio.mp4a.TotalAudioPlaybackTimeMs=15580;CT;1:NR
10-06 15:20:50.822 19205-24976/com.google.android.exoplayer2.demo I/MediaCodecLogger:  com.google.android.exoplayer2.demo.SW.audio.mp4a.StreamAvgBitrateInKbps = 48
10-06 15:20:50.822 19205-24976/com.google.android.exoplayer2.demo I/MediaCodecLogger: MediaCodecLogger:MMSW_Metrics5.2.1.1:com.google.android.exoplayer2.demo.SW.audio.mp4a.StreamAvgBitrateInKbps=48;CT;1:NR
10-06 15:20:50.832 19205-19205/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [29.74]
10-06 15:20:50.842 19205-19205/com.google.android.exoplayer2.demo D/EventLogger: audioDisabled [29.75]
10-06 15:20:50.842 19205-19205/com.google.android.exoplayer2.demo D/EventLogger: loading [false]
10-06 15:20:50.852 19205-19205/com.google.android.exoplayer2.demo D/EventLogger: state [29.77, true, I]
```

**Comment by ojw28** [comment]
The stack trace provided above is a network timeout, which is expected if you have a bad network. Since you haven't provided any of the information requested in the issue template, we wont be investigating further. Please provide complete information as requested in future issues.

Please also see the part of [this page](https://google.github.io/ExoPlayer/supported-devices.html) that refers to Fire OS. Thanks!

**Comment by mohdabdullah1986** [comment]
I have a very good internet connection.

The same url works on mobile (HTC and Redmi) however the same is not working on FireTV Stick Generation 1.

Let me know if this issue is coming due to hardware.
