### ISSUE TITLE
CryptoException on Samsung SM-T900 causing device reboot

### ISSUE THREAD

**Issue by mlondon1** [google/ExoPlayer#1913]
Device reboot after the following exception.

On a Samsung Galaxy Tab Pro 12.2 running Android 4.4.2, playing Widevine Dash content, after playing successfully in Exoplayer 2.0.2 for a few seconds, the following exception occurred resulting in a device crash.

```
10-07 15:46:17.850 2207-2850/? E/wv_dash: Trustlet did not send a valid return code: 0xd
10-07 15:46:17.850 2207-2850/? E/wv_dash: tee_send_msg_general_cmd is failed.
10-07 15:46:17.850 2207-2850/? E/wv_dash: process drm decrypt CTR failed
10-07 15:46:17.850 2207-2850/? E/WVCdm: Decrypt error result in session sid3 during encrypted block: 1
10-07 15:46:17.850 7321-7401/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Renderer error.
                                                                                         com.google.android.exoplayer2.ExoPlaybackException
                                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:660)
                                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:478)
                                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                             at android.os.Looper.loop(Looper.java:157)
                                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                             at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                          Caused by: android.media.MediaCodec$CryptoException: Error decrypting data.
                                                                                             at android.media.MediaCodec.queueSecureInputBuffer(Native Method)
                                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:651)
                                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:478) 
                                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265) 
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                             at android.os.Looper.loop(Looper.java:157) 
                                                                                             at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                             at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
10-07 15:46:17.860 7321-7321/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [29.13]
                                                                               com.google.android.exoplayer2.ExoPlaybackException
                                                                                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:660)
                                                                                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:478)
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:157)
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                Caused by: android.media.MediaCodec$CryptoException: Error decrypting data.
                                                                                   at android.media.MediaCodec.queueSecureInputBuffer(Native Method)
                                                                                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:651)
                                                                                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:478) 
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                   at android.os.Looper.loop(Looper.java:157) 
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by wvpaf** [comment]
@mlondon1  can you help provide a full ADB log? 

Other SS tablets have suffered from HDCP issues, which may cause the decrypt errors reported, and upgrading to L seem to fixed the other issue.

**Comment by ojw28** [comment]
Closing due to inactivity.
