### ISSUE TITLE
Can not play assets video in Android 7.0

### ISSUE THREAD

**Issue by niorgai** [google/ExoPlayer#1917]
I am using r2.0.2.
I put the file in assets dir, and create to Uri by call `Uri.parse("file:///android_asset/video_guide.mp4")`, It can play in Android 4.4, but it is not work on my nexus6, Android 7.0.

**Comment by ojw28** [comment]
I tried this by adding the following entry into `media.exolist.json` in the demo app:

```
      {
        "name": "Test",
        "uri": "file:///android_asset/video_guide.mp4"
      },
```

and also adding an asset of that name to the app, and it worked fine on 7.0.

Please try and reproduce using the demo app. If you cannot reproduce, this is likely some error in your application code. If you can, please provide clear reproduction steps and a full bugreport (captured with `adb bugreport` shortly after encountering the issue).

**Comment by niorgai** [comment]
I try it in demo app and it Toast `Media includes video tracks, but none are playable by this devices.`

Here is the execption stack.

``` Java

/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [5.75]
                                                                               com.google.android.exoplayer2.ExoPlaybackException
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                Caused by: java.lang.IllegalStateException
                                                                                   at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:79)
                                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod.startLoading(ExtractorMediaPeriod.java:423)
                                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod.continueLoading(ExtractorMediaPeriod.java:235)
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1081)
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.seekToPeriodPosition(ExoPlayerImplInternal.java:575)
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.seekToInternal(ExoPlayerImplInternal.java:513)
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:269)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                   at android.os.Looper.loop(Looper.java:154) 
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 

```

**Comment by ojw28** [comment]
Please can you read the [issue template](https://github.com/google/ExoPlayer/issues/new) (i.e. the default contents of the issue box) and provide all of the information requested? You're not providing sufficient information for us to help you.

**Comment by eneim** [comment]
@niorgai Did you grant the Read Storage Permission?

**Comment by niorgai** [comment]
@eneim yes.
@ojw28 sorry i can't catch the error info by `adb bugreport` right now, so i will close this issue now. when i find the error i will reopen it.
