### ISSUE TITLE
IllegalStateException playing MP4 with high resolution in some devices

### ISSUE THREAD

**Issue by lichangadd** [google/ExoPlayer#1946]
same problem as [https://github.com/google/ExoPlayer/issues/1806](url)
when I play a high resolution mp4 (1280x720),the stack:
`
10-14 11:47:14.437 15484-16050/com.google.android.exoplayer2.demo E/ACodec: [OMX.k3.video.decoder.avc] ERROR(0x80001009)
10-14 11:47:14.437 15484-16050/com.google.android.exoplayer2.demo E/ACodec: signalError(omxError 0x80001009, internalError -2147483648)
10-14 11:47:14.437 15484-16049/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported err 0x80001009, actionCode 0, while in state 6
10-14 11:47:14.457 15484-16038/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                           java.lang.IllegalStateException
                                                                                               at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                                               at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:850)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:477)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                               at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
`

But if I switch the videosource to a normal resolution video, all is well.
These are my test data:
http://7xqc8e.com1.z0.glb.clouddn.com/action_1_86169.mp4 (high resolution)
http://7xkrt9.dl1.z0.glb.clouddn.com/output.mp4 (low resolution)
TestDevice: Huawei P7

I had tried with r1.5.11 and r2.0.2's demo application

**Comment by lichangadd** [comment]
Solved，because the video with high resolution‘s codec version is 5.0 which some device not support

**Comment by rafa0809** [comment]
OMG
Is he saying that we can't play high resolution videos? When do you plan to get supported?
