### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by hardcattle** [google/ExoPlayer#1951]
java.lang.OutOfMemoryError
    at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
    at com.google.android.exoplayer2.extractor.DefaultTrackOutput.prepareForAppend(DefaultTrackOutput.java:557)
    at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:488)
    at com.google.android.exoplayer2.extractor.ts.H264Reader.consume(H264Reader.java:101)
    at com.google.android.exoplayer2.extractor.ts.TsExtractor$PesReader.consume(TsExtractor.java:587)
    at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:231)
    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:180)
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)

**Comment by ojw28** [comment]
Please stop filing issues that ignore the issue template (see also https://github.com/google/ExoPlayer/issues/1929). We will close all such issues without investigating.
