### ISSUE TITLE
java.lang.IllegalStateException when i seek offline encrypted video.

### ISSUE THREAD

**Issue by HungamaSurat** [google/ExoPlayer#1964]
I am trying to play encrypted file and decrypt at runtime and provide outputstream to exoplayer to play.

Steps:
-Launch the app
-Play video.
-Observe on Playing video and try to forward seek bar.

Below is full issue log.

[OMX.MTK.VIDEO.DECODER.AVC] ERROR(0x8000100b)
Codec: signalError(omxError 0x8000100b, internalError -2147483648)
MediaCodec: Codec reported err 0x8000100b, actionCode 0, while in state 6
ExoPlayerImplInternal: Internal runtime error.
                                                                                   java.lang.IllegalStateException
                                                                                       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                                       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
                                                                                       at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:890)
                                                                                       at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:512)
                                                                                       at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                                       at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
                                                                                       at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                       at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

```
                                                                               [ 10-19 18:32:37.635   158:18982 I/         ]
                                                                               [BWC INFO](18982): get_bwc_mm_property success

                                                                               [ 10-19 18:32:37.635   158:18982 I/         ]
                                                                               [BWC INFO](18982): BWC_SETTING::DumpInfo-------



                                                                               [ 10-19 18:32:37.635   158:18982 I/         ]
                                                                               [BWC INFO](18982):          sensor_size =      0 x      0


                                                                               [ 10-19 18:32:37.635   158:18982 I/         ]
                                                                               [BWC INFO](18982):              vr_size =      0 x      0


                                                                               [ 10-19 18:32:37.635   158:18982 I/         ]
                                                                               [BWC INFO](18982):            disp_size =      0 x      0


                                                                               [ 10-19 18:32:37.635   158:18982 I/         ]
                                                                               [BWC INFO](18982):              tv_size =      0 x      0


                                                                               [ 10-19 18:32:37.635   158:18982 I/         ]
                                                                               [BWC INFO](18982):                  fps =      0


                                                                               [ 10-19 18:32:37.635   158:18982 I/         ]
                                                                               [BWC INFO](18982):      venc_codec_type =      0


                                                                               [ 10-19 18:32:37.635   158:18982 I/         ]
                                                                               [BWC INFO](18982):      vdec_codec_type =      2


                                                                               [ 10-19 18:32:37.636   158:18982 I/         ]
                                                                               [BWC INFO](18982): ----------------------------



                                                                               [ 10-19 18:32:37.636   158:18982 I/         ]
                                                                               [BWC INFO](18982): Read DDR type string:LPDDR2


                                                                               [ 10-19 18:32:37.636   158:18982 I/         ]
                                                                               [BWC INFO](18982): DDR Type = 0


                                                                               [ 10-19 18:32:37.638   158:18982 I/         ]
                                                                               [BWC INFO](18982): smi_bw_ctrl_set: scen 2, turn off


                                                                               [ 10-19 18:32:37.638   158:18982 I/         ]
                                                                               [BWC INFO](18982): emi_bw_ctrl_set: CON_SCE_VP OFF
```

I got this issue on android one, samsung duos. it is not reproduced in nexus 5 and mi max.
Please

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
 
If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
