### ISSUE TITLE
Jellybean: PlaybackControlView + java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by irenecs** [google/ExoPlayer#1965]
```
Fatal Exception: java.lang.NoSuchMethodError: com.google.android.exoplayer2.ui.PlaybackControlView.isAttachedToWindow
       at com.google.android.exoplayer2.ui.PlaybackControlView.updatePlayPauseButton(PlaybackControlView.java:282)
       at com.google.android.exoplayer2.ui.PlaybackControlView.updateAll(PlaybackControlView.java:276)
       at com.google.android.exoplayer2.ui.PlaybackControlView.show(PlaybackControlView.java:235)
       at com.google.android.exoplayer2.ui.SimpleExoPlayerView.maybeShowController(SimpleExoPlayerView.java:293)
       at com.google.android.exoplayer2.ui.SimpleExoPlayerView.setPlayer(SimpleExoPlayerView.java:152)
       at com.smartboxtv.android.movistarmusic.exoplayer.ExoPlayerActivity.initializePlayer(ExoPlayerActivity.java:313)
       at com.smartboxtv.android.movistarmusic.exoplayer.ExoPlayerActivity.onResume(ExoPlayerActivity.java:210)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1193)
       at android.app.Activity.performResume(Activity.java:5200)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2952)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2994)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
       at android.app.ActivityThread.access$600(ActivityThread.java:162)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5400)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by ojw28** [comment]
Sorry about that. For some reason Android Studio isn't showing this as a lint error (`./gradlew library:lint` does). This issue affects devices running Jellybean. We'll push a fix shortly.

**Comment by ojw28** [comment]
This is fixed in the `dev-v2` branch by the change ref'd above. We'll push a r2.0.4 release sometime this week containing the fix.
