### ISSUE TITLE
OGG play failed for some files

### ISSUE THREAD

**Issue by WeaveStudios** [google/ExoPlayer#1976]
Some specific OGG files are not played. I have used R2.0.4 version with current DemoPlayer to play an OGG file, however, a EOF exception is thrown, as shown below. This is a built-in ringtone so there is no problem reproducing it by using other mechanisms, e.g., MediaPlayer.

```
10-20 15:59:52.847: E/EventLogger(5858): java.io.EOFException
10-20 15:59:52.847: E/EventLogger(5858):    at com.google.android.exoplayer2.extractor.ogg.DefaultOggSeeker.skipToNextPage(DefaultOggSeeker.java:243)
10-20 15:59:52.847: E/EventLogger(5858):    at com.google.android.exoplayer2.extractor.ogg.DefaultOggSeeker.readGranuleOfLastPage(DefaultOggSeeker.java:297)
10-20 15:59:52.847: E/EventLogger(5858):    at com.google.android.exoplayer2.extractor.ogg.DefaultOggSeeker.read(DefaultOggSeeker.java:86)
10-20 15:59:52.847: E/EventLogger(5858):    at com.google.android.exoplayer2.extractor.ogg.StreamReader.readPayload(StreamReader.java:157)
10-20 15:59:52.847: E/EventLogger(5858):    at com.google.android.exoplayer2.extractor.ogg.StreamReader.read(StreamReader.java:113)
10-20 15:59:52.847: E/EventLogger(5858):    at com.google.android.exoplayer2.extractor.ogg.OggExtractor.read(OggExtractor.java:97)
10-20 15:59:52.847: E/EventLogger(5858):    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:609)
10-20 15:59:52.847: E/EventLogger(5858):    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
10-20 15:59:52.847: E/EventLogger(5858):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
10-20 15:59:52.847: E/EventLogger(5858):    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
10-20 15:59:52.847: E/EventLogger(5858):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
10-20 15:59:52.847: E/EventLogger(5858):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
10-20 15:59:52.847: E/EventLogger(5858):    at java.lang.Thread.run(Thread.java:856)
```

It seems it's related to issue #1506, however this is ExoPlayer v2.

[bugreport.txt](https://github.com/google/ExoPlayer/files/542705/bugreport.txt)

**Comment by ojw28** [comment]
The fix for #1506 is in ExoPlayer V2 and the problematic sample provided in that issue plays correctly. You'll need to provide a problematic file to allow us to reproduce and debug further. Please can you provide one here, or email one to `dev.exoplayer@gmail.com` (updating this issue once sent, so we know to retrieve it). Thanks!

**Comment by WeaveStudios** [comment]
I have just sent you an email with the file. Let me know if you are experiencing the same behavior.

Thanks a lot for your time.

**Comment by ojw28** [comment]
Thanks. We're failing in the special case where the OGG file only contains a single page that's not a header. It's pretty easy to fix this; we'll push a fix soon.

**Comment by WeaveStudios** [comment]
Great! This was pretty fast.

**Comment by ojw28** [comment]
Fixed in `dev-v2`
