### ISSUE TITLE
Decoder init failed: CIPAMRNBDecoder

### ISSUE THREAD

**Issue by squm** [google/ExoPlayer#1986]
`compile 'com.google.android.exoplayer:exoplayer:r2.0.4'`

```
adb shell getprop ro.build.fingerprint`
> asus/WW_MeMO_Pad/K01A:4.4.2/KVT49L/WW_MeMO_Pad-11.2.3.34-20150302:user/release-keys
```

``````
D/EventLogger: state [0.35, true, B]
D/EventLogger: loading [true]
I/OMXClient: Using client-side OMX mux.
E/ACodec: [OMX.Intel.VideoDecoder.AVC] storeMetaDataInBuffers failed w/ err -2147483648
I/OMXClient: Using client-side OMX mux.
E/ACodec: Unable to instantiate decoder 'CIPAMRNBDecoder'.
E/MediaCodec: Codec reported an error. (omx error 0x80001003, internalError -2147483648)
E/ExoPlayerImplInternal: Renderer error.
                         com.google.android.exoplayer2.ExoPlaybackException
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:371)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:359)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748)
                             at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:219)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472)
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                             at android.os.Handler.dispatchMessage(Handler.java:98)
                             at android.os.Looper.loop(Looper.java:149)
                             at android.os.HandlerThread.run(HandlerThread.java:61)
                             at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                          Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: CIPAMRNBDecoder, Format(2, null, audio/3gpp, -1, , ```, [-1, -1, -1.0], [1, 8000])
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:359) 
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748) 
                             at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:219) 
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489) 
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472) 
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265) 
                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                             at android.os.Looper.loop(Looper.java:149) 
                             at android.os.HandlerThread.run(HandlerThread.java:61) 
                             at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                          Caused by: java.io.IOException: Failed to allocate component instance
                             at android.media.MediaCodec.native_setup(Native Method)
                             at android.media.MediaCodec.<init>(MediaCodec.java:210)
                             at android.media.MediaCodec.createByCodecName(MediaCodec.java:204)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:345)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748) 
                             at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:219) 
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489) 
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472) 
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265) 
                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                             at android.os.Looper.loop(Looper.java:149) 
                             at android.os.HandlerThread.run(HandlerThread.java:61) 
                             at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
E/EventLogger: playerFailed [1.03]
               com.google.android.exoplayer2.ExoPlaybackException
                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:371)
                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:359)
                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748)
                   at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:219)
                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489)
                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472)
                   at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                   at android.os.Handler.dispatchMessage(Handler.java:98)
                   at android.os.Looper.loop(Looper.java:149)
                   at android.os.HandlerThread.run(HandlerThread.java:61)
                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: CIPAMRNBDecoder, Format(2, null, audio/3gpp, -1, , ```, [-1, -1, -1.0], [1, 8000])
                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:359) 
                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748) 
                   at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:219) 
                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489) 
                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472) 
                   at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265) 
                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                   at android.os.Looper.loop(Looper.java:149) 
                   at android.os.HandlerThread.run(HandlerThread.java:61) 
                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                Caused by: java.io.IOException: Failed to allocate component instance
                   at android.media.MediaCodec.native_setup(Native Method)
                   at android.media.MediaCodec.<init>(MediaCodec.java:210)
                   at android.media.MediaCodec.createByCodecName(MediaCodec.java:204)
                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:345)
                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748) 
                   at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:219) 
                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489) 
                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472) 
                   at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265) 
                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                   at android.os.Looper.loop(Looper.java:149) 
                   at android.os.HandlerThread.run(HandlerThread.java:61) 
                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
D/EventLogger: videoDisabled [1.03]
D/EventLogger: audioDisabled [1.03]
D/EventLogger: loading [false]
``````

**Comment by ojw28** [comment]
Please try adding

```
|| "CIPAMRNBDecoder".equals(name)
```

to [MediaCodecUtil:225](https://github.com/google/ExoPlayer/blob/dev-v2/library/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecUtil.java#L225).

If that resolves the issue, we'll merge the fix. Thanks!

**Comment by squm** [comment]
can send you video/audio file if you want to test it
[decoder.mp4.zip](https://github.com/google/ExoPlayer/files/547573/decoder.mp4.zip)

**Comment by ojw28** [comment]
We don't have access to a device of this type, so you'll need to test and let us know yourself. Thanks.

**Comment by squm** [comment]
that needs from me modifying, building and testing from ExoPlayer source code, can't help with that

**Comment by ojw28** [comment]
It takes a couple of minutes at most to check out the ExoPlayer source code, modify it and test a sample using the demo app. It feels like this should be worth it if you want the bug fixed! Or at the very least, that this is not an unreasonable request.

**Comment by squm** [comment]
before
[http://vpaste.net/5r0yK](http://vpaste.net/5r0yK)

after
[http://vpaste.net/nbUFZ](http://vpaste.net/nbUFZ)

it has sound and a vide

while we are still here, can you tell how to fill window with `com.google.android.exoplayer2.ui.SimpleExoPlayerView`

full screen fill is missing

```
        AspectRatioFrameLayout.RESIZE_MODE_FIT
        AspectRatioFrameLayout.RESIZE_MODE_FIXED_HEIGHT
        AspectRatioFrameLayout.RESIZE_MODE_FIXED_WIDTH
```

**Comment by ojw28** [comment]
Thanks! So to clarify, the suggested workaround fixed the issue for you, correct (looks that way, just making sure)? If so we'll merge the fix.

`SimpleExoPlayerView` is deliberately designed to maintain the aspect ratio of the video. Do you want to deform (i.e. stretch) the video to fill the window, or do you want to keep the video aspect ratio unchanged but clip the edges?

**Comment by ojw28** [comment]
Fixed in `dev-v1` and `dev-v2`
