### ISSUE TITLE
Unsupported Service: captioning

### ISSUE THREAD

**Issue by PoulsQ** [google/ExoPlayer#1991]
Hi everyone,

I just follow this simple guide : https://google.github.io/ExoPlayer/guide.html

and I have a problem when I add my `com.google.android.exoplayer2.ui.SimpleExoPlayerView`, the Android Studio emulator shows me an exception and can't instanciate the view.

![exoplayer](https://cloud.githubusercontent.com/assets/4129609/19677912/df10ca9a-9a9b-11e6-90fa-889cbc553c8f.png)

Here is the excetpion code :
`java.lang.UnsupportedOperationException: Unsupported Service: captioning
    at com.android.layoutlib.bridge.android.BridgeContext.getSystemService(BridgeContext.java:602)
    at com.google.android.exoplayer2.ui.SubtitleView.getUserCaptionStyleV19(SubtitleView.java:260)
    at com.google.android.exoplayer2.ui.SubtitleView.setUserDefaultStyle(SubtitleView.java:186)
    at com.google.android.exoplayer2.ui.SimpleExoPlayerView.<init>(SimpleExoPlayerView.java:97)
    at com.google.android.exoplayer2.ui.SimpleExoPlayerView.<init>(SimpleExoPlayerView.java:61)
    at sun.reflect.GeneratedConstructorAccessor220.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:465)
    at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:172)
    at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:105)
    at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:186)
    at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:334)
    at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:345)
    at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:245)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
    at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
    at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
    at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
    at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
    at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
    at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
    at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
    at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
    at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
    at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
    at com.android.tools.idea.rendering.RenderTask.lambda$inflate$53(RenderTask.java:659)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
`

Am I missing something ? 
I'm using `compile 'com.google.android.exoplayer:exoplayer:r2.0.4'` and the error is still there with a  v16 <= SDK <= v24.

Could you help me on this ?

**Comment by andrewlewis** [comment]
I see the same error in the 'Design' view in Android Studio but I think it's safe to ignore -- the app runs fine. If you are seeing the error somewhere else, please clarify.

It looks like we can fix the error anyway by checking !isInEditMode() before accessing the captioning manager.

**Comment by PoulsQ** [comment]
In my case I see it in the "Preview" section when I'm editing my drawable layout in "Text" mode. So it shows a message all over the preview when I change anything in my XML code. :(
It's not a big deal because as you said, the app runs fine ! It's just an annoying little bug !

**Comment by andrewlewis** [comment]
We've fixed this by checking [View.isInEditMode()](https://developer.android.com/reference/android/view/View.html#isInEditMode%28%29). The patch will appear in `dev-v2` next time we push a set of changes. Thanks for reporting this!
