### ISSUE TITLE
[IllegalStateException - SDK v16] Can't read an MP4 from a particular URL

### ISSUE THREAD

**Issue by PoulsQ** [google/ExoPlayer#1997]
Hi guys,

Today I'm facing a strange issue, I can't read the video from here : 
https://icoprod.s3.amazonaws.com/scheduler/121-130-1477312544-14794964_1060335287399040_6271596638158979072_n.mp4

I'm using a SDK v16 (I have the same problem with a v19 or v22). At the time where I instanciate the exoplayer, I've got this exception :

```
E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)

E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6

E/ExoPlayerImplInternal: Internal runtime error.
 java.lang.IllegalStateException
     at android.media.MediaCodec.native_queueInputBuffer(Native Method)
     at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:831)
     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:653)
     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:478)
     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
     at android.os.Handler.dispatchMessage(Handler.java:98)
     at android.os.Looper.loop(Looper.java:135)
     at android.os.HandlerThread.run(HandlerThread.java:61)
     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

E/ExoPlayerImplInternal: Stop failed.
 java.lang.IllegalStateException
     at android.media.MediaCodec.native_stop(Native Method)
     at android.media.MediaCodec.stop(MediaCodec.java:628)
     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:441)
     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:396)
     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:275)
     at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:136)
     at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:631)
     at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:607)
     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:317)
     at android.os.Handler.dispatchMessage(Handler.java:98)
     at android.os.Looper.loop(Looper.java:135)
     at android.os.HandlerThread.run(HandlerThread.java:61)
     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

Is this a bug from the plugin ? Or a problem on my side ?

Here is my player implementation : 

```
// Create a default TrackSelector
Handler mainHandler = new Handler();
DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveVideoTrackSelection.Factory(bandwidthMeter);
TrackSelector trackSelector = new DefaultTrackSelector(mainHandler, videoTrackSelectionFactory);

// Create a default LoadControl
LoadControl loadControl = new DefaultLoadControl();

// Create the player
exoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);
exoPlayerView.setPlayer(exoPlayer);
exoPlayerView.setUseController(false);

// Produces DataSource instances through which media data is loaded.
DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(
        this,
        Util.getUserAgent(this, getResources().getString(R.string.app_name)),
        bandwidthMeter
);

// Produces Extractor instances for parsing the media data.
ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
// This is the MediaSource representing the media to be played.
MediaSource videoSource = new ExtractorMediaSource(Uri.parse(videoUrl), dataSourceFactory, extractorsFactory, null, null);
LoopingMediaSource loopingSource = new LoopingMediaSource(videoSource);
// Prepare the player with the source.
exoPlayer.prepare(loopingSource);
exoPlayer.setPlayWhenReady(play);
```

What do you think about ?

**Comment by ojw28** [comment]
If this is using an emulator, please see [here](https://google.github.io/ExoPlayer/faqs.html#does-exoplayer-support-emulators). If this is using a real device, please read the issue template and provide all of the requested information, since there's no enough here to debug the issue.

For what it's worth, the sample plays fine for me on Pixel and with a Virtual Device with configuration: Nexus 5X API 23.

**Comment by ghost** [comment]
i got the same problem. does you fixed it?

**Comment by PoulsQ** [comment]
Nope, not in my case ... I created a mediaplayer with native components : https://developer.android.com/guide/topics/media/mediaplayer.html

and now it's working perfectly !

**Comment by ojw28** [comment]
As above, please read the issue template and provide all of the requested information if you want us to look at this. Probably file a new issue at this point.
