### ISSUE TITLE
HLS Streams from Brightcove causes IllegalStateException

### ISSUE THREAD

**Issue by jeffdcamp** [google/ExoPlayer#200]
In using the dev-hls branch....

I don't know if the HLS stream that comes from Brightcove is different than other HLS streams, but when trying to play a URI from Brightcove we see 1-5 seconds of video then get a IllegalStateException.

If we remove the "Assertions.checkState(packetLength == 0);" from TsExtractor.java (line 432), then the video plays perfectly.

We have tried this (playing videos from Brightcove with that line removed) with lots of videos and they all play perfectly.  Should this line be removed?  Is it an invalid assertion?

Brightcove URI:
http://c.brightcove.com/services/mobile/streaming/index/master.m3u8?videoId=2893093382001

Code added to Demo Sample:
      new Sample("Test1", "uid:hls:bv",
              "http://c.brightcove.com/services/mobile/streaming/index/master.m3u8?videoId=2893093382001",
              DemoUtil.TYPE_HLS, false, false),

Full Exception:
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:428)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:398)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:218)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.IllegalStateException
            at com.google.android.exoplayer.util.Assertions.checkState(Assertions.java:66)
            at com.google.android.exoplayer.hls.TsExtractor$PesReader.read(TsExtractor.java:432)
            at com.google.android.exoplayer.hls.TsExtractor.read(TsExtractor.java:276)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:121)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:206)

**Comment by makk909** [comment]
@jeffdcamp I am facing the same issue of livestreaming being stopped after few seconds ranging from 6-8 seconds. Earlier it was even not buffering but after commenting the checkArgument() code in Assertion class, i was able to buffer but then it started stopping after 6-8 seconds.Do you have any idea about the same??
