### ISSUE TITLE
OutOfMemoryError due to audioTrackunderrun

### ISSUE THREAD

**Issue by mcse541** [google/ExoPlayer#2012]
While playing custom encrypted stream with widevine ,after some minutes of playback I get the following error.

Iam using Exoplayer library r2.0.0 in my project 

Tested on Nexus Player with version 7.0

```
10-28 12:20:13.987 5095-23858/com.package E/LoadTask: Unexpected error loading stream
                                                               java.lang.OutOfMemoryError: Failed to allocate a 164012 byte allocation with 87040 free bytes and 81KB until OOM
                                                                   at com.google.android.exoplayer2.extractor.DefaultTrackOutput$InfoQueue.commitSample(DefaultTrackOutput.java:869)
                                                                   at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleMetadata(DefaultTrackOutput.java:527)
                                                                   at com.google.android.exoplayer2.source.chunk.ChunkExtractorWrapper.sampleMetadata(ChunkExtractorWrapper.java:154)
                                                                   at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1006)
                                                                   at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:211)
                                                                   at com.google.android.exoplayer2.source.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:109)
                                                                   at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:115)
                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                   at java.lang.Thread.run(Thread.java:761)
10-28 12:20:14.026 5095-5095/com.package E/EventLogger: internalError [1256.13, audioTrackUnderrun [45312, 256, 436]]
10-28 12:20:14.120 5095-23790/com.package E/AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
                                                                     Process: com.package, PID: 5095
                                                                     java.lang.OutOfMemoryError: Failed to allocate a 164012 byte allocation with 87040 free bytes and 81KB until OOM
                                                                         at com.google.android.exoplayer2.extractor.DefaultTrackOutput$InfoQueue.commitSample(DefaultTrackOutput.java:869)
                                                                         at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleMetadata(DefaultTrackOutput.java:527)
                                                                         at com.google.android.exoplayer2.source.chunk.ChunkExtractorWrapper.sampleMetadata(ChunkExtractorWrapper.java:154)
                                                                         at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1006)
                                                                         at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:211)
                                                                         at com.google.android.exoplayer2.source.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:109)
                                                                         at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:115)
                                                                         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                         at java.lang.Thread.run(Thread.java:761)
10-28 12:20:14.147 5095-5095/com.package E/DRMPlayerActivity: OnPause
```

**Comment by ojw28** [comment]
We fixed a whole bunch of memory related issues in early 2.x releases. Please try with 2.0.4.

**Comment by mdtuyen** [comment]
I'm working with exoplayer 2.3.1. 

```
java.lang.OutOfMemoryError: 
  at com.google.android.exoplayer2.extractor.DefaultTrackOutput$InfoQueue.commitSample(ProGuard:900)
  at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleMetadata(ProGuard:548)
  at com.google.android.exoplayer2.extractor.ts.AdtsReader.b(ProGuard:336)
  at com.google.android.exoplayer2.extractor.ts.AdtsReader.consume(ProGuard:149)
  at com.google.android.exoplayer2.extractor.ts.PesReader.consume(ProGuard:132)
  at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(ProGuard:275)
  at com.google.android.exoplayer2.source.hls.HlsMediaChunk.b(ProGuard:264)
  at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(ProGuard:200)
  at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(ProGuard:295)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)
```
