### ISSUE TITLE
ExoDemo app doesn't play video at android 4.4.2

### ISSUE THREAD

**Issue by a-klimashevsky** [google/ExoPlayer#2036]
ExoDemo app doesn't play video at android 4.4.2

Player version: 2.0.4

Device: Samsung GT-I8160, android 4.4.2 (Gyanogenmode)

Steps to reproduce:

1) download https://drive.google.com/open?id=0ByD4juBaF_vWQWxTcXlPRWNaaWM
2) open with ExoDemo app

Result: Decoder init failed: OMX.ST.VFM.H264Dec

Log:

```
11-04 17:42:48.616 3181-4665/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Renderer error.
             com.google.android.exoplayer2.ExoPlaybackException
                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:371)
                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:359)
                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748)
                 at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324)
                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489)
                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472)
                 at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                 at android.os.Handler.dispatchMessage(Handler.java:98)
                 at android.os.Looper.loop(Looper.java:136)
                 at android.os.HandlerThread.run(HandlerThread.java:61)
                 at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
              Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.ST.VFM.H264Dec, Format(1, null, video/avc, -1, , null, [1280, 720, -1.0], [-1, -1])
                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:359) 
                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748) 
                 at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324) 
                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489) 
                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472) 
                 at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265) 
                 at android.os.Handler.dispatchMessage(Handler.java:98) 
                 at android.os.Looper.loop(Looper.java:136) 
                 at android.os.HandlerThread.run(HandlerThread.java:61) 
                 at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
              Caused by: java.lang.IllegalStateException
                 at android.media.MediaCodec.getBuffers(Native Method)
                 at android.media.MediaCodec.getInputBuffers(MediaCodec.java:542)
                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:356)
                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748) 
                 at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324) 
                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489) 
                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472) 
                 at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265) 
                 at android.os.Handler.dispatchMessage(Handler.java:98) 
                 at android.os.Looper.loop(Looper.java:136) 
                 at android.os.HandlerThread.run(HandlerThread.java:61) 
                 at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
11-04 17:42:48.756 3181-3181/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [2.57]
   com.google.android.exoplayer2.ExoPlaybackException
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:371)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:359)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748)
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)
       at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
    Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.ST.VFM.H264Dec, Format(1, null, video/avc, -1, , null, [1280, 720, -1.0], [-1, -1])
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:359) 
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748) 
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324) 
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489) 
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472) 
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265) 
       at android.os.Handler.dispatchMessage(Handler.java:98) 
       at android.os.Looper.loop(Looper.java:136) 
       at android.os.HandlerThread.run(HandlerThread.java:61) 
       at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
    Caused by: java.lang.IllegalStateException
       at android.media.MediaCodec.getBuffers(Native Method)
       at android.media.MediaCodec.getInputBuffers(MediaCodec.java:542)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:356)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748) 
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324) 
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489) 
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472) 
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265) 
       at android.os.Handler.dispatchMessage(Handler.java:98) 
       at android.os.Looper.loop(Looper.java:136) 
       at android.os.HandlerThread.run(HandlerThread.java:61) 
       at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

Some usefull tips:

1) ExoDemo play this video at android 5.0 and above and android 4.2
2) At different android emulators we have an issue that video format is not supported

**Comment by andrewlewis** [comment]
Could you clarify whether you saw the issue running on Cyanogenmod or stock Android? It looks like a platform bug rather than an issue with ExoPlayer.

See also the [FAQ about using ExoPlayer on emulators](https://google.github.io/ExoPlayer/faqs.html#does-exoplayer-support-emulators).

**Comment by a-klimashevsky** [comment]
I saw this issue at real device with Cyanogenmod.
I'm able to play this video using build-in gallery app. So its looks more like ExoPlayer bug

**Comment by ojw28** [comment]
The built in gallery app playing the video successfully doesn't say much about whether this is a platform bug or an ExoPlayer bug. The two may well use different decoders, exercise the underlying platform in different ways etc.

The failure (to instantiate a decoder) strongly suggests an issue with the version of Cyanogenmod that you're using rather than an issue in the ExoPlayer. If you can reproduce the issue with the official version of Android that the device shipped with then please let us know. Otherwise please report the issue to Cyanogenmod developers.
