### ISSUE TITLE
Not able to stream .pls and .m3u URL with ExoPlayer

### ISSUE THREAD

**Issue by chiragsidhiwala** [google/ExoPlayer#2051]
I would like to do live Audio streaming of few radio stations which contain .pls and .m3u URLs. After adding those URL in ExoPlayer Demo it's giving below error : 

com.google.android.exoplayer2.demo E/EventLogger: internalError [0.83, loadError]
                                                                                 com.google.android.exoplayer2.source.ExtractorMediaSource$UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:678)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:602)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                     at java.lang.Thread.run(Thread.java:761)
11-09 00:34:53.665 27133-27171/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Source error.
                                                                                           com.google.android.exoplayer2.source.ExtractorMediaSource$UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                               at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:678)
                                                                                               at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:602)
                                                                                               at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                               at java.lang.Thread.run(Thread.java:761)
11-09 00:34:53.667 27133-27133/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [0.85]
                                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:310)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                  Caused by: com.google.android.exoplayer2.source.ExtractorMediaSource$UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:678)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:602)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                     at java.lang.Thread.run(Thread.java:761)

I havve replaced URLs in media.exolist.json file added in assets folder in "HSL" section.
Below are sample URL which is not supporting : 
http://wmfe.iad.streamguys1.com/wmfe.m3u
http://wusf.usf.edu/wusf_radio.asx 
http://hd1.wusf.usf.edu:8000/listen.pls

Please help me to resolve this issue asap , as it's blocking my play store application.

**Comment by iNoles** [comment]
the biggest error is the "None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream."

**Comment by andrewlewis** [comment]
We don't currently support extracting URLs from these sort of playlist files; see also #1947. ExtractorMediaSource throws an exception because it doesn't recognize the file as a valid media container: MP3, Matroska, MP4, etc..

It should be fairly straightforward to request and parse the playlists in your app, then pass the contained media URLs to ExoPlayer.

Note: you can quickly verify that the contained URLs play using the ExoPlayer demo app, like this: `adb shell am start -a com.google.android.exoplayer.demo.action.VIEW -d "http://wmfe.iad.streamguys1.com:80/wmfe"`, where the URL comes from the `m3u` file linked above.

**Comment by amintabar** [comment]
Hi
I have same problem with exoplayer. i'm testing a lot of valid hls video url (exp 'http://content.jwplatform.com/manifests/vM7nH0Kl.m3u8') but all of them have same error like this. What's the problem? and how can i resolve it?!

**Comment by andrewlewis** [comment]
@amintabar If you're playing HLS streams, use HlsMediaSource (not ExtractorMediaSource).

**Comment by amintabar** [comment]
@andrewlewis Thanks, it's very helpful, and resolve my problem.
