### ISSUE TITLE
HLS with (very) large chunks: OutofMemory

### ISSUE THREAD

**Issue by jdprajapati** [google/ExoPlayer#2055]
Hi,

1) My local chunk is not playing longer, its size is 1.1GB.  its working fine while I am playing live stream but when I am using from local storage its crashed after few mins and throwing the exception of outofmemory.
FYI, I have set large heap true in manifest.

```
11-10 15:43:43.746 7691-8522/c.a.login E/LoadTask: Unexpected error loading stream
                                                   java.lang.OutOfMemoryError: Failed to allocate a 144016 byte allocation with 119936 free bytes and 117KB until OOM
                                                       at com.google.android.exoplayer.extractor.RollingSampleBuffer$InfoQueue.commitSample(RollingSampleBuffer.java:626)
                                                       at com.google.android.exoplayer.extractor.RollingSampleBuffer.commitSample(RollingSampleBuffer.java:429)
                                                       at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleMetadata(DefaultTrackOutput.java:266)
                                                       at com.google.android.exoplayer.extractor.ts.AdtsReader.readSample(AdtsReader.java:307)
                                                       at com.google.android.exoplayer.extractor.ts.AdtsReader.consume(AdtsReader.java:120)
                                                       at com.google.android.exoplayer.extractor.ts.TsExtractor$PesReader.consume(TsExtractor.java:643)
                                                       at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:220)
                                                       at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:238)
                                                       at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:116)
                                                       at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                       at java.lang.Thread.run(Thread.java:818)
```

2) Video showing green screen and audio is working fine, my stream is H265.

Can you please check this problem and give me the solution.

Thanks in advance.

**Comment by ojw28** [comment]
Please read the issue template and provide all of the requested information. We can't debug this with the information provided.

**Comment by jdprajapati** [comment]
I am playing HLS Stream from local storage (m3u8),

```
java.lang.OutOfMemoryError: Failed to allocate a 65548 byte allocation with 60240 free bytes and 58KB until OOM
at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
at com.google.android.exoplayer2.extractor.DefaultTrackOutput.prepareForAppend(DefaultTrackOutput.java:557)
at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:488)
at com.google.android.exoplayer2.extractor.ts.H264Reader.consume(H264Reader.java:108)
at com.google.android.exoplayer2.extractor.ts.TsExtractor$PesReader.consume(TsExtractor.java:634)
at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:242)
at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:180)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

I am not share the stream link with you , is it possible to we can skype/email so  i can show the problem in my system.

Thanks

**Comment by AquilesCanta** [comment]
We will almost surely need to reproduce the issue ourselves. If you cannot share the stream publicly, you can -as stated in the issue template- send it to dev.exoplayer@gmail.com. 

Just in case, if the chunk is too big, that could be the reason behind the error. If that's the case, try splitting it into smaller pieces or using a ExtractorMediaSource for the chunk directly. The stacktrace is not enough for us to figure out what the error is.

**Comment by jdprajapati** [comment]
Actually my chunk size 1GB, I can send you link in your email,

On Thu, Nov 10, 2016 at 11:07 PM, Santiago Seifert <notifications@github.com

**Comment by AquilesCanta** [comment]
I can confirm it's reproducible. I will look into it further later since it's most likely an unintended behavior. I would suggest using a shorter segment duration, if within your possibilities.

**Comment by jdprajapati** [comment]
Hi,

Thanks for replying,

The segment is not fixed, its randomly size set from server e.g. 1mb, 50mb,
1gb, 15gb per chunk.

So If possible then fix the outofmemory error.

Thanks

**Comment by ojw28** [comment]
There's no benefit to using HLS for your use case. Furthermore, your use case is not what HLS is designed for; Apple recommend 6 second chunk segments for HLS.

We're unlikely to fix this. I think you need to reconsider the approach you're taking. Why are you using HLS at all for this case? Why do you need an HLS playlist? Why don't you just play the underlying 1GB file directly using `ExtractorMediaSource`?

**Comment by jdprajapati** [comment]
Hi,
I have usedExtractorMediaSource with ts chunks file from local storage, its working fine but seekTo is not working ts files.
Please help me for this problem.

thanks

**Comment by andrewlewis** [comment]
I'm afraid we are unlikely to be able to help you play the media in its current form (definitely not in the near future). For HLS, we load chunks in full so they can't be too big. For MPEG-TS it's not feasible to support seeking (see #2061).

As an aside: even if we did load these 1 GB chunks in HlsMediaSource seeking would be very inefficient for most use cases, as we would need to read and discard samples from the start of the chunk up to the requested seek timestamp.

You will need to get streams in a different format, or implement your own MediaSource which constructs a time-to-byte mapping for these MPEG-TSs, but we don't have resources to provide guidance on this.
