### ISSUE TITLE
java.lang.OutOfMemoryError: with HLS stream

### ISSUE THREAD

**Issue by jdprajapati** [google/ExoPlayer#2057]
java.lang.OutOfMemoryError: Failed to allocate a 65548 byte allocation with 60240 free bytes and 58KB until OOM
                                                                                      at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
                                                                                      at com.google.android.exoplayer2.extractor.DefaultTrackOutput.prepareForAppend(DefaultTrackOutput.java:557)
                                                                                      at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:488)
                                                                                      at com.google.android.exoplayer2.extractor.ts.H264Reader.consume(H264Reader.java:108)
                                                                                      at com.google.android.exoplayer2.extractor.ts.TsExtractor$PesReader.consume(TsExtractor.java:634)
                                                                                      at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:242)
                                                                                      at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:180)
                                                                                      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                      at java.lang.Thread.run(Thread.java:818)

**Comment by AquilesCanta** [comment]
Please, see #2055.
