### ISSUE TITLE
EMAudioPlayer NoClassDefFound

### ISSUE THREAD

**Issue by Abbieben** [google/ExoPlayer#2062]
Please i just upgraded to the 2.0.4 version of your plugin, and i keep getting error for EMAudioPlayer it says no  
FATAL EXCEPTION: main
Process: net.novacio.villagesquare, PID: 18788  java.lang.NoClassDefFoundError: com.devbrackets.android.exomedia.core.exoplayer.EMExoPlayer
 at com.devbrackets.android.exomedia.core.audio.ExoMediaPlayer.<init>(ExoMediaPlayer.java:73)
 at com.devbrackets.android.exomedia.EMAudioPlayer.<init>(EMAudioPlayer.java:66)
 at com.devbrackets.android.exomedia.EMAudioPlayer.<init>(EMAudioPlayer.java:61)

Please is EMAudioPlayer no longer supported

**Comment by andrewlewis** [comment]
This is an issue for the ExoMedia project. EMAudioPlayer is not part of ExoPlayer.
