### ISSUE TITLE
ANR releasing player

### ISSUE THREAD

**Issue by gbhall** [google/ExoPlayer#2063]
Now and then I am getting an ANR when trying to call `.release()` on `ExoPlayer` in my fragment's `onPause()`.

Unsure of exact cause since it's infrequent but shouldn't be happening at all.

Using `r2.0.4`.

```
"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x74cca2a0 self=0xb4d76500
  | sysTid=8602 nice=0 cgrp=bg_non_interactive sched=0/0 handle=0xb6f76b34
  | state=S schedstat=( 24562497097 8964484440 45709 ) utm=2188 stm=268 core=0 HZ=100
  | stack=0xbe307000-0xbe309000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x0e6b2e4d> (a com.google.android.exoplayer2.ExoPlayerImplInternal)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.release(ExoPlayerImplInternal.java:216)
  - locked <0x0e6b2e4d> (a com.google.android.exoplayer2.ExoPlayerImplInternal)
  at com.google.android.exoplayer2.ExoPlayerImpl.release(ExoPlayerImpl.java:201)
  at XXX.releasePlayer(XXX.java:781)
  at XXX.onPause(XXX.java:255)
  at android.support.v4.app.Fragment.performPause(Fragment.java:2266)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1166)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1277)
  at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:2168)
  at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:234)
  at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:448)
  at android.app.Activity.performPause(Activity.java:6363)
  at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1311)
  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3367)
  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340)
  at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315)
  at android.app.ActivityThread.-wrap13(ActivityThread.java:-1)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by andrewlewis** [comment]
Please run `adb bugreport` just after seeing the ANR and attach the output to this issue, or email it to dev.exoplayer@gmail.com. Then we can investigate why the playback thread is blocking release. Thanks.

**Comment by gbhall** [comment]
Sent by email.

**Comment by ojw28** [comment]
- Is it intentional that you have 8 ExoPlayer instances at the same time? That looks a little suspicious to me.
- The ANR itself is likely caused by `"ExoPlayerImplInternal:Handler" prio=5 tid=39` which is blocked in `android.media.MediaCodec.native_stop`.

**Comment by gbhall** [comment]
Yes the 8 instances are intentional. Is that an issue?

**Comment by gbhall** [comment]
```
- waiting on <0x0e6b2e4d> (a com.google.android.exoplayer2.ExoPlayerImplInternal)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.release(ExoPlayerImplInternal.java:216)
```

 Line 216 contains `wait()` for `ExoPlayerImplInternal`

``` java
  public synchronized void release() {
    if (released) {
      return;
    }
    handler.sendEmptyMessage(MSG_RELEASE);
    while (!released) {
      try {
        wait();
      } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
      }
    }
    internalPlaybackThread.quit();
  }
```

**Comment by ojw28** [comment]
- Yes, it does. It's waiting for the playback thread to exit, which is blocked in `android.media.MediaCodec.native_stop` as per my previous reply. It looks like the call is hung in the platform.
- 8 instances seems pretty unusual. Most devices only have one or two hardware decoders available. Are you actually playing 8 pieces of media at once? What's the actual use case? It's difficult to say whether it's causing problems or not.

**Comment by gbhall** [comment]
The instances are loaded in seperate fragments within a viewpager. I only
play one video at a time when a fragment becomes visible.

**Comment by ojw28** [comment]
If I were you I'd make sure there's only ever a single instance, if you're only using playing one thing at once. It'll give you more confidence that there's no contention for decoders, memory etc. I'm not sure whether it will make the platform hang less likely (or get rid of it) though.

**Comment by gbhall** [comment]
Does `ExoPlayer`'s underlying architecture run on top of the same as `MediaPlayer`?

It seems that some people having an issue releasing MediaPlayer claimed that not calling `stop` helped them: https://code.google.com/p/android/issues/detail?id=959

The problem is this is a very hard issue to diagnose. It happens very infrequently.

I wonder if removing the call to `stop` would help. In my fragments `onPause` I essentially do:

``` java
            mExoPlayer.removeListener(mExoPlayerEventListener);
            mExoPlayer.stop();
            mExoPlayer.release();
            mExoPlayer = null;
```

Having a single instance I'm not even sure is feasible across multiple fragments. If I did somehow manage to have a single instance (shared in the activity or application?), as a user swipes, the next video in the viewpager must be immediately ready. The setup time to start playing a different video I think would be unfeasible theoretically and noticeable to the user.

**Comment by ojw28** [comment]
> Does ExoPlayer's underlying architecture run on top of the same as MediaPlayer?

"It depends". There's more than one `MediaPlayer` implementation, and device manufacturers may have made further modifications (including completely rewriting it) on their own devices. Generally speaking though, if you're running a relatively recent version of Android, and definitely if you're using a Nexus or Pixel device, then yes they both make use of the same decoders.

> It seems that some people having an issue releasing MediaPlayer claimed that not calling stop helped them: https://code.google.com/p/android/issues/detail?id=959

It looks to me like everyone in that thread except for one person is saying that removing stop didn't help.

> I wonder if removing the call to stop would help.

There's no real guarantee that `MediaPlayer` and `ExoPlayer` stop methods are doing the same thing thing with the underlying decoders. It's quite a big stretch to make this kind of inference. I doubt it'll help.

In my opinion there's probably not a huge amount you can do about this kind of issue. If it's very infrequent, you're probably best off not spending a whole amount of time looking into it.
