### ISSUE TITLE
ExoPlaybackException: java.io.EOFException after little play

### ISSUE THREAD

**Issue by sufyandeveloper** [google/ExoPlayer#2065]
I am working on live streaming using exoplayer in my application its successfully playing but its throw eof exception after playing i don't know how to solve this error please help what should i do. 

**This is my chunks.m3u8 file**

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:4
#EXT-X-ALLOW-CACHE:NO
#EXT-X-MEDIA-SEQUENCE:4386
#EXTINF:4,
file:///sdcard/download/ts/l_626655_24555301_4386.ts
#EXTINF:4,
file:///sdcard/download/ts/l_626655_24561301_4387.ts
#EXTINF:4,
file:///sdcard/download/ts/l_626655_24567301_4388.ts
#EXTINF:4,
file:///sdcard/download/ts/l_626655_24573301_4389.ts
```

**And this is my error** 
```
 E/ExoPlayerImplInternal: Internal track renderer error.
                                                                    com.

google.android.exoplayer.ExoPlaybackException: java.io.EOFException
                                                                        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SourceFile:263)
                                                                        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SourceFile:145)
                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(SourceFile:441)
                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(SourceFile:213)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                        at android.os.Looper.loop(Looper.java:194)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:60)
                                                                        at com.google.android.exoplayer.util.PriorityHandlerThread.run(SourceFile:40)
                                                                     Caused by: java.io.EOFException
                                                                        at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(SourceFile:245)
                                                                        at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(SourceFile:67)
                                                                        at com.google.android.exoplayer.extractor.ts.TsExtractor.read(SourceFile:133)
                                                                        at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(SourceFile:240)
                                                                        at com.google.android.exoplayer.hls.TsChunk.load(SourceFile:115)
                                                                        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(SourceFile:209)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                        at java.lang.Thread.run(Thread.java:838)
```

**Comment by AquilesCanta** [comment]
Could you please provide a link for us to reproduce ourselves? Also, is it possible for you to try your URL in v2 to see whether an error is thrown?

If you don't want to make the url public, please send it to dev.exoplayer@gmail.com

**Comment by ojw28** [comment]
Stream was provided by email.

**Comment by AquilesCanta** [comment]
Sorry for the delay on this. How long does the stream have to play for the error to occur? Have you tried the URL in V2?

**Comment by AquilesCanta** [comment]
I have been playing for some time now and did manage to reproduce the issue. But I also observed that the media sequence of the playlist gets reset to 0 from time to time. According to the spec, this is not allowed. I also suspect that in this process the server closes all connections, or some server related error occurs. If you find evidence pointing towards Exoplayer doing something wrong, please open a new issue. I suggest making sure the server is providing a stable stream. An easy way of doing this is tracking the state of the playlist with:

` wget -qO- <stream url>`
