### ISSUE TITLE
Unable to stream broadcastify api exoplayer version 2

### ISSUE THREAD

**Issue by atiwari600** [google/ExoPlayer#2086]
I am not able to stream a broadcastify url on exoplayer "r2.0.4"
Everytime I play the url player throws exception.

```
11-19 15:25:49.229 19567-19926/com.rebelappz.k9radiopro E/ExoPlayerImplInternal: Source error.
                                                                                 com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 401
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:596)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                     at java.lang.Thread.run(Thread.java:841)
11-19 15:25:49.229 19567-19567/com.rebelappz.k9radiopro W/System.err: com.google.android.exoplayer2.ExoPlaybackException
11-19 15:25:49.239 19567-19567/com.rebelappz.k9radiopro W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:310)
11-19 15:25:49.239 19567-19567/com.rebelappz.k9radiopro W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
11-19 15:25:49.239 19567-19567/com.rebelappz.k9radiopro W/System.err:     at android.os.Looper.loop(Looper.java:146)
11-19 15:25:49.239 19567-19567/com.rebelappz.k9radiopro W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
11-19 15:25:49.239 19567-19567/com.rebelappz.k9radiopro W/System.err:     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
11-19 15:25:49.239 19567-19567/com.rebelappz.k9radiopro W/System.err: Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 401
11-19 15:25:49.239 19567-19567/com.rebelappz.k9radiopro W/System.err:     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
11-19 15:25:49.239 19567-19567/com.rebelappz.k9radiopro W/System.err:     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:596)
11-19 15:25:49.239 19567-19567/com.rebelappz.k9radiopro W/System.err:     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
11-19 15:25:49.239 19567-19567/com.rebelappz.k9radiopro W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
11-19 15:25:49.239 19567-19567/com.rebelappz.k9radiopro W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-19 15:25:49.239 19567-19567/com.rebelappz.k9radiopro W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-19 15:25:49.239 19567-19567/com.rebelappz.k9radiopro W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-19 15:25:49.239 19567-19567/com.rebelappz.k9radiopro W/System.err:     at java.lang.Thread.run(Thread.java:841)
11-19 15:25:49.239 19567-19567/com.rebelappz.k9radiopro E/SongService: :::onPlayerError:::com.google.android.exoplayer2.ExoPlaybackException
```

It was working fine on exoplayer "r1.5.12" without any exception without any authentication.
Stream url : http://relay.broadcastify.com:80/il_chicago_police2

**Comment by ojw28** [comment]
I see the same error using r1.5.12 as well. It appears the server is rejecting the requests based on the User-Agent. I was able to play the stream successfully in both r1.5.12 and r2.0.4 by using a different User-Agent. Specifically in r2.0.4, by replacing [this line of code](https://github.com/google/ExoPlayer/blob/r2.0.4/demo/src/main/java/com/google/android/exoplayer2/demo/DemoApplication.java#L36) with:

```
userAgent = Util.getUserAgent(this, "ExoPlayerDemo").replace("ExoPlayerLib", "Blah");
```

I've no idea why the server would be configured this way. If it's not your server and you've released something that's sending it a significant amount of traffic, then it's possible they've crudely blocked your requests by returning 401 for all requests that have `ExoPlayerLib` in their User-Agent.

In any case, this isn't an ExoPlayer bug, so closing.

**Comment by atiwari600** [comment]
Thanks for the solution. Its works . I have used the User Agent which i have used for the exoplayer library r1.5.12 and it is working flawlessly. 

```
public static String getDefaultUserAgent() {
        StringBuilder result = new StringBuilder(64);
        result.append("Dalvik/");
        result.append(System.getProperty("java.vm.version")); // such as 1.1.0
        result.append(" (Linux; U; Android ");

        String version = Build.VERSION.RELEASE; // "1.0" or "3.4b5"
        result.append(version.length() > 0 ? version : "1.0");

        // add the model for the release build
        if ("REL".equals(Build.VERSION.CODENAME)) {
            String model = Build.MODEL;
            if (model.length() > 0) {
                result.append("; ");
                result.append(model);
            }
        }
        String id = Build.ID; // "MASTER" or "M4-rc20"
        if (id.length() > 0) {
            result.append(" Build/");
            result.append(id);
        }
        result.append(")");
        return result.toString();
    }
```

Thanks again!
