### ISSUE TITLE
Custom playlist playback failing

### ISSUE THREAD

**Issue by ascmartins** [google/ExoPlayer#2097]
I need to run a playlist of videos but I can't use the ConcatenatingMediaSource class as I may have more than 1000 in a playlist for a full day. So I built a custom class that worked for a previous version of ExoPlayer. The problem that I face now is that it only plays the first video and at the end status goes to IDLE or STOP. Any idea what can be causing the issue?

**Comment by ascmartins** [comment]
I need to run a playlist of videos but I can't use the ConcatenatingMediaSource class as I may have more than 1000 in a playlist for a full day. So I built a custom class that worked for a previous version of ExoPlayer. The problem that I face now is that it only plays the first video and at the end status goes to IDLE or STOP. Any idea what can be causing the issue?

**Comment by ojw28** [comment]
You'd need to provide at least a full bug report for us to help debug that. Probably you'll need to share your custom class somehow, or provide an equivalent class that we can test in the demo app to reproduce the issue.

**Comment by ascmartins** [comment]
Here is the full class I am using:
[AppendingMediaSource.java](https://github.com/ascmartins/mucodes/blob/master/AppendingMediaSource.java)
 I call the method `public void appendSource(String uriString, Context mContext)` a few seconds before video timeout, as I am using scheduled items. I am not sure of what version of Exoplayer I was using before but to avoid memory issues I had to update to r2.0.4. In the previous version the override method `public MediaPeriod createPeriod(int index, Allocator allocator, long positionUs)` was `public MediaPeriod createPeriod(int index, Callback callback, Allocator allocator, long positionUs)`.
Hope you can help me.

**Comment by ascmartins** [comment]
From debug I get this:
```
11-23 09:27:12.279 17061-23630/it.tailoradio.videomood E/ExoPlayerImplInternal: Internal runtime error.
                                                                                java.lang.IllegalStateException
                                                                                    at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:79)
                                                                                    at com.google.android.exoplayer2.BaseRenderer.replaceStream(BaseRenderer.java:92)
                                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1037)
                                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:414)
                                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                    at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
11-23 09:27:12.426 17061-23637/it.tailoradio.videomood I/omx_core: OMX_Deinit 96 gInitCount=0
11-23 09:27:12.427 17061-23681/it.tailoradio.videomood I/AudioTrack: ~AudioTrack, releasing session id from 17061 on behalf of 17061 mState/4
11-23 09:27:12.434 17061-17061/it.tailoradio.videomood D/VM_ACTIVITY: Player state changed: true, STATE_IDLE
```

**Comment by ascmartins** [comment]
The first implementation that worked for me was for ExoPlayer version 2.0.0. I wonder what is causing the IllegalStateException on my case.

**Comment by ascmartins** [comment]
Seems like the append MediaSource period is not appearing in the list on `updatePeriods(···)`. Any idea?

**Comment by ojw28** [comment]
Looking at your implementation, I'm not convinced that your approach is best suited to the problem you're trying to solve. Rather than requiring the application to proactively append child sources, I think you should instead just expose a timeline consisting of some arbitrarily large number of periods. Then when `createPeriod` is called for a period whose child source does not yet exist, you should ask the application to build you one. Conversely, when you're holding a child source whose periods have all been released, you should release it and null out any references you hold to it.

The suggested approach is basically the opposite of what you have now, with the source pulling data from the application rather than the application pushing data into the source. I think you'll find this approach works much better.

**Comment by ascmartins** [comment]
> The suggested approach is basically the opposite of what you have now, with the source pulling data from the application rather than the application pushing data into the source. I think you'll find this approach works much better.

How can I do this?

**Comment by ascmartins** [comment]
I found a way to use it as it is adding a single line of code to library in the [ExoPlayerImplInternal.java](https://github.com/google/ExoPlayer/blob/release-v2/library/src/main/java/com/google/android/exoplayer2/ExoPlayerImplInternal.java) just before line 1037. The line I added was:
`renderer.resetPosition(0);`

Thanks for all your help.
