### ISSUE TITLE
Internal ExoPlayer Exception Trying To Play DRM Content

### ISSUE THREAD

**Issue by aobeidah** [google/ExoPlayer#2104]
Unexpected exception loading stream

```
                                                         java.lang.IllegalStateException: Unexpected sample data in initialization chunk
                                                             at com.google.android.exoplayer.chunk.InitializationChunk.sampleData(InitializationChunk.java:154)
                                                             at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:137)
                                                             at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.appendSampleEncryptionData(FragmentedMp4Extractor.java:767)
                                                             at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:698)
                                                             at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:176)
                                                             at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                             at com.google.android.exoplayer.chunk.InitializationChunk.load(InitializationChunk.java:190)
                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                             at java.lang.Thread.run(Thread.java:818)
Unexpected exception loading stream
                                                         java.lang.IllegalStateException: Unexpected sample data in initialization chunk
                                                             at com.google.android.exoplayer.chunk.InitializationChunk.sampleData(InitializationChunk.java:154)
                                                             at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:137)
                                                             at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.appendSampleEncryptionData(FragmentedMp4Extractor.java:767)
                                                             at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:698)
                                                             at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:176)
                                                             at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                             at com.google.android.exoplayer.chunk.InitializationChunk.load(InitializationChunk.java:190)
                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                             at java.lang.Thread.run(Thread.java:818)
Internal track renderer error.
                                                                      com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: Unexpected sample data in initialization chunk
                                                                          at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
                                                                          at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:141)
                                                                          at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:438)
                                                                          at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                          at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                       Caused by: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: Unexpected sample data in initialization chunk
                                                                          at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                       Caused by: java.lang.IllegalStateException: Unexpected sample data in initialization chunk
                                                                          at com.google.android.exoplayer.chunk.InitializationChunk.sampleData(InitializationChunk.java:154)
                                                                          at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:137)
                                                                          at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.appendSampleEncryptionData(FragmentedMp4Extractor.java:767)
                                                                          at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:698)
                                                                          at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:176)
                                                                          at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
                                                                          at com.google.android.exoplayer.chunk.InitializationChunk.load(InitializationChunk.java:190)
                                                                          at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                          at java.lang.Thread.run(Thread.java:818) 
```

**Comment by ojw28** [comment]
It looks like the DASH stream you're trying to play is invalid. Since you've opted to ignore the issue template and not provide any of the requested information, we are unable to assist. Please file an issue including the requested information if you wish for us to investigate further. Thanks.
