### ISSUE TITLE
Out of memory when attempting to load webm from internal SD - MKV Sniff

### ISSUE THREAD

**Issue by TACIXAT** [google/ExoPlayer#2107]
I download a webm and write it to the internal SD. I then try to load it into exoplayer, following the code in the [guide](http://google.github.io/ExoPlayer/guide.html) pretty much exactly. Only thing I changed as the URI to point to the file. The MKV extractor appears to be attempting to allocate a 1.1 GB buffer. The target video is ~4 MB. 

Looking at the extractors, MKV appears to handle both MKV and webm?

Using Exoplayer 4.0.2. 

Nexus 5 emulator with 2 gb of ram. 

Android 7.1.1

```
E/LoadTask: Unexpected error loading stream
            java.lang.OutOfMemoryError: Failed to allocate a 1107296283 byte allocation with 4194304 free bytes and 505MB until OOM
                at java.util.Arrays.copyOf(Arrays.java:3256)
                at com.google.android.exoplayer2.extractor.DefaultExtractorInput.ensureSpaceForPeek(DefaultExtractorInput.java:179)
                at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:126)
                at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:142)
                at com.google.android.exoplayer2.extractor.mkv.Sniffer.sniff(Sniffer.java:81)
                at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.sniff(MatroskaExtractor.java:311)
                at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:667)
                at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:602)
                at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                at java.lang.Thread.run(Thread.java:761)
E/AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
                  Process: ooo.socialite.balance, PID: 11414
                  java.lang.OutOfMemoryError: Failed to allocate a 1107296283 byte allocation with 4194304 free bytes and 505MB until OOM
                      at java.util.Arrays.copyOf(Arrays.java:3256)
                      at com.google.android.exoplayer2.extractor.DefaultExtractorInput.ensureSpaceForPeek(DefaultExtractorInput.java:179)
                      at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:126)
                      at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:142)
                      at com.google.android.exoplayer2.extractor.mkv.Sniffer.sniff(Sniffer.java:81)
                      at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.sniff(MatroskaExtractor.java:311)
                      at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:667)
                      at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:602)
                      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                      at java.lang.Thread.run(Thread.java:761)
```

**Comment by ojw28** [comment]
This is almost certainly content specific. It's possible the content is malformed. Unless you provide us with sample content that reproduces the issue, as requested in the issue template, we can't investigate further.

**Comment by TACIXAT** [comment]
Bingo! I was packing the video into integers since Android endpoints doesn't support byte arrays, and I didn't want to use base64 due to the overhead. My decode loop was bad.
