### ISSUE TITLE
Decoder init failed: OMX.amlogic.avc.decoder.awesome

### ISSUE THREAD

**Issue by huongnv251291** [google/ExoPlayer#2116]
i got error when try play google ads video on minix neo x8h plus use android 4.4.
I start video when load ads sussces i pause it and play ads. But ads can't play and throw logerror,
it work normal on emulator tv android and some smartphone
Link ads : https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=
i use ads video mp4
ver exoplay : 1.5.12
Sorry my english not good
Log:
E/ACodec: Unable to instantiate decoder 'OMX.amlogic.avc.decoder.awesome'.
E/MediaCodec: Codec reported an error. (omx error 0x80001003, internalError -2147483648)
E/dalvikvm: Could not find class 'android.media.MediaCodec$CodecException', referenced from method com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException.getDiagnosticInfoV21
E/ExoPlayerImplInternal: Internal track renderer error.
                                                                     com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, MediaFormat(1, video/avc, -1, 13378, 1280, 720, 0, 1.0, -1, -1, null, 10000000, false, -1, -1, -1, -1, -1)
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:427)
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:413)
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:800)
                                                                         at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:540)
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:523)
                                                                         at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                         at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                      Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, MediaFormat(1, video/avc, -1, 13378, 1280, 720, 0, 1.0, -1, -1, null, 10000000, false, -1, -1, -1, -1, -1)
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:413) 
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:800) 
                                                                         at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333) 
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:540) 
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:523) 
                                                                         at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128) 
                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432) 
                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                         at android.os.Looper.loop(Looper.java:136) 
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                         at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                                      Caused by: java.io.IOException: Failed to allocate component instance
                                                                         at android.media.MediaCodec.native_setup(Native Method)
                                                                         at android.media.MediaCodec.<init>(MediaCodec.java:210)
                                                                         at android.media.MediaCodec.createByCodecName(MediaCodec.java:204)
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:399)
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:800) 
                                                                         at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333) 
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:540) 
                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:523) 
                                                                         at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128) 
                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432) 
                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                         at android.os.Looper.loop(Looper.java:136) 
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                         at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by huongnv251291** [comment]
i get error when try play google ads video on minix android 4.4.
I start video when load ads sussces i pause it and play ads. But ads can't play and throw logcat.
it work normal on emulator tv android and some smartphone
(omx error 0x80001003, internalError -2147483648)
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, MediaFormat.
Link ads :  https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=
ver exo : 1.5.12

**Comment by huongnv251291** [comment]
change media decoder  to OMX.google.h264.decoder and it work

**Comment by trulex** [comment]
Where did you change that?
