### ISSUE TITLE
E/ExoPlayerImplInternal: Renderer error.

### ISSUE THREAD

**Issue by longteng9** [google/ExoPlayer#2151]
```
 E/ExoPlayerImplInternal: Renderer error.
                                                                                    com.google.android.exoplayer2.ExoPlaybackException
                                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:301)
                                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:480)
                                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                        at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                     Caused by: java.lang.NullPointerException
                                                                                        at player.WidevineEpsMediaDrmCallback.postToLicenseProxy(WidevineEpsMediaDrmCallback.java:62)
                                                                                        at com.zeasn.hungama.player.WidevineEpsMediaDrmCallback.executeProvisionRequest(WidevineEpsMediaDrmCallback.java:108)
                                                                                        at com.google.android.exoplayer2.drm.StreamingDrmSessionManager$PostRequestHandler.handleMessage(StreamingDrmSessionManager.java:508)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
E/EventLogger: playerFailed [2.32]
                                                                          com.google.android.exoplayer2.ExoPlaybackException
                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:301)
                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:480)
                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                              at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                           Caused by: java.lang.NullPointerException
                                                                              at .player.WidevineEpsMediaDrmCallback.postToLicenseProxy(WidevineEpsMediaDrmCallback.java:62)
                                                                              at .player.WidevineEpsMediaDrmCallback.executeProvisionRequest(WidevineEpsMediaDrmCallback.java:108)
                                                                              at com.google.android.exoplayer2.drm.StreamingDrmSessionManager$PostRequestHandler.handleMessage(StreamingDrmSessionManager.java:508)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by longteng9** [comment]
I added the video DRM permissions when there was the following error

**Comment by andrewlewis** [comment]
As stated in the stack trace, the NullPointerException occurred in com.zeasn.hungama.player.WidevineEpsMediaDrmCallback on line 62 in postToLicenseProxy. This class is not part of ExoPlayer, so you'll need to debug your code and figure out what value is unexpectedly null.

**Comment by ojw28** [comment]
Closing since the failure is in application code, not ExoPlayer, as per the response above.
