### ISSUE TITLE
new Dev v2 Cannot Play http mp4(h265)?

### ISSUE THREAD

**Issue by qoo888** [google/ExoPlayer#2152]
Hello..
new Dev v2 Cannot Play http h265 mp4, but Release ver ( v2  v1 ) play h265 mp4 no problem.....   :( 
thank you..

```
12-05 14:12:37.608 25128-25128/? D/outPut: http://192.168.1.88:5000/mp4/1-27-20-6-_02-21-30.mp4
12-05 14:12:37.608 25128-25128/? I/Timeline: Timeline: Activity_launch_request time:54130609
12-05 14:12:37.736 25128-25128/? I/ExoPlayerImpl: Init 2.0.4 [natrium, MI 5s Plus, Xiaomi, 23]
12-05 14:12:37.738 25128-25128/? D/EventLogger: state [0.00, true, I]
12-05 14:12:37.738 25128-25128/? W/Bundle: Attempt to cast generated internal exception:
                                           java.lang.ClassCastException: java.lang.Character cannot be cast to java.lang.String
                                               at android.os.BaseBundle.getString(BaseBundle.java:923)
                                               at android.content.Intent.getStringExtra(Intent.java:5353)
                                               at com.e.myvideo.PlayerActivity.initializePlayer(PlayerActivity.java:332)
                                               at com.e.myvideo.PlayerActivity.onResume(PlayerActivity.java:193)
                                               at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
                                               at android.app.Activity.performResume(Activity.java:6408)
                                               at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3116)
                                               at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3158)
                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2497)
                                               at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                               at android.os.Looper.loop(Looper.java:148)
                                               at android.app.ActivityThread.main(ActivityThread.java:5458)
                                               at java.lang.reflect.Method.invoke(Native Method)
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
12-05 14:12:37.744 25128-25128/? D/ActivityThreadInjector: clearCachedDrawables.
12-05 14:12:37.770 25128-25128/? D/EventLogger: state [0.03, true, B]
12-05 14:12:37.770 25128-25128/? D/EventLogger: sourceInfo [periodCount=1, windowCount=1
12-05 14:12:37.770 25128-25128/? D/EventLogger:   period [?]
12-05 14:12:37.770 25128-25128/? D/EventLogger:   window [?, false, false]
12-05 14:12:37.770 25128-25128/? D/EventLogger: ]
12-05 14:12:37.770 25128-25128/? D/EventLogger: loading [true]
12-05 14:12:39.121 25128-27419/? E/LoadTask: Unexpected exception loading stream
                                             java.lang.StringIndexOutOfBoundsException: length=921898; regionStart=134; regionLength=-1
                                                 at java.lang.StringFactory.newStringFromBytes(StringFactory.java:69)
                                                 at com.google.android.exoplayer2.util.ParsableByteArray.readNullTerminatedString(ParsableByteArray.java:439)
                                                 at com.google.android.exoplayer2.extractor.mp4.MetadataUtil.parseTextAttribute(MetadataUtil.java:190)
                                                 at com.google.android.exoplayer2.extractor.mp4.MetadataUtil.parseIlstElement(MetadataUtil.java:130)
                                                 at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseIlst(AtomParsers.java:448)
                                                 at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseMetaAtom(AtomParsers.java:437)
                                                 at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseUdta(AtomParsers.java:422)
                                                 at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:318)
                                                 at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:273)
                                                 at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:264)
                                                 at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:144)
                                                 at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:628)
                                                 at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                 at java.lang.Thread.run(Thread.java:818)
12-05 14:12:39.123 25128-25128/? E/EventLogger: internalError [1.38, loadError]
                                                com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected StringIndexOutOfBoundsException: length=921898; regionStart=134; regionLength=-1
                                                    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                    at java.lang.Thread.run(Thread.java:818)
                                                 Caused by: java.lang.StringIndexOutOfBoundsException: length=921898; regionStart=134; regionLength=-1
                                                    at java.lang.StringFactory.newStringFromBytes(StringFactory.java:69)
                                                    at com.google.android.exoplayer2.util.ParsableByteArray.readNullTerminatedString(ParsableByteArray.java:439)
                                                    at com.google.android.exoplayer2.extractor.mp4.MetadataUtil.parseTextAttribute(MetadataUtil.java:190)
                                                    at com.google.android.exoplayer2.extractor.mp4.MetadataUtil.parseIlstElement(MetadataUtil.java:130)
                                                    at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseIlst(AtomParsers.java:448)
                                                    at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseMetaAtom(AtomParsers.java:437)
                                                    at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseUdta(AtomParsers.java:422)
                                                    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:318)
                                                    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:273)
                                                    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:264)
                                                    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:144)
                                                    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:628)
                                                    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)?
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)?
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)?
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)?
                                                    at java.lang.Thread.run(Thread.java:818)?
12-05 14:12:39.204 25128-25128/? E/EventLogger: internalError [1.47, loadError]
                                                java.io.EOFException
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:252)
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:76)
                                                    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:249)
                                                    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:144)
                                                    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:628)
                                                    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                    at java.lang.Thread.run(Thread.java:818)
12-05 14:12:40.291 25128-25128/? E/EventLogger: internalError [2.55, loadError]
                                                java.io.EOFException
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:252)
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:76)
                                                    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:249)
                                                    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:144)
                                                    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:628)
                                                    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                    at java.lang.Thread.run(Thread.java:818)
12-05 14:12:42.382 25128-25128/? E/EventLogger: internalError [4.64, loadError]
                                                java.io.EOFException
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:252)
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:76)
                                                    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:249)
                                                    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:144)
                                                    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:628)
                                                    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                    at java.lang.Thread.run(Thread.java:818)
12-05 14:12:42.385 25128-27418/? E/ExoPlayerImplInternal: Source error.
                                                          java.io.EOFException
                                                              at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:252)
                                                              at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
                                                              at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:76)
                                                              at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:249)
                                                              at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:144)
                                                              at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:628)
                                                              at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                              at java.lang.Thread.run(Thread.java:818)
12-05 14:12:42.386 25128-25128/? E/EventLogger: playerFailed [4.65]
                                                com.google.android.exoplayer2.ExoPlaybackException
                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                    at android.os.Looper.loop(Looper.java:148)
                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                    at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                 Caused by: java.io.EOFException
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:252)
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:76)
                                                    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:249)
                                                    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:144)
                                                    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:628)
                                                    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                    at java.lang.Thread.run(Thread.java:818)
12-05 14:12:42.393 25128-25128/? D/EventLogger: loading [false]
12-05 14:12:42.394 25128-25128/? D/EventLogger: state [4.66, true, I]
```

**Comment by andrewlewis** [comment]
Please provide the information requested in the issue template:

"- A link to content that reproduces the issue. If you don't wish to post it publicly, please submit the issue, then email the link to dev.exoplayer@gmail.com including the issue number in the subject line."

**Comment by qoo888** [comment]
Upload file for give you tests, thank you. :)

Test this h265.mp4 file work on release v2 and v1.


h265.mp4 1080p file 51 MB
https://srv07.bitsend.jp/download/c201bd3e3637224a5ebbaa70232075ab.html

use ver: 
dev-v2 at  2016-12-04

test device:
Xiaomi MI 5s Plus android 6  -----  fail play
nvidia shield android 6  -----  fail play

**Comment by ojw28** [comment]
This is an issue where we fail to correctly read a metadata string with length zero and no terminating NUL byte.

**Comment by ojw28** [comment]
Fixed in https://github.com/google/ExoPlayer/commit/9ea8b02.

**Comment by qoo888** [comment]
thank you
