### ISSUE TITLE
Unable to download Smooth Streaming chunk Exo 1.5.10

### ISSUE THREAD

**Issue by marcuz89** [google/ExoPlayer#2158]
Hi,
we are using exoplayer 1.5.10 in our app in AndroidTV device. 
In a particular manifest we have problems to download a chunk.
The player crashes after receiving the first 2.5MB of the chunk 57949600000. I think the offending chunk is downloaded only in part by the STB (or sent only in part by the server).

In particular we observe that:
- The problem is not systematic
- The player goes wrong when a particular chunk (Video = 57949600000) is downloaded with the highest profile (QualityLevels (7000000))
- The player is working properly when the same piece is downloaded with lower profiles (for example QualityLevels (3000000) or QualityLevels (3800000))

I think could be related with these issue:
https://github.com/google/ExoPlayer/issues/1333
https://github.com/google/ExoPlayer/issues/66
https://github.com/google/ExoPlayer/issues/652

These are the logs error:

```
12-05 13:47:41.349 21896-21896/my_app_id E/EventLogger: internalError [231.93, loadError]
                                                                                     com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: Top bit not zero: -1418831960
                                                                                         at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:235)
                                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                                      Caused by: java.lang.IllegalStateException: Top bit not zero: -1418831960
                                                                                         at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:299)
                                                                                         at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:930)
                                                                                         at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:195)
                                                                                         at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:92)
                                                                                         at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:164)
                                                                                         at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)�
                                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)�
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)�
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)�
                                                                                         at java.lang.Thread.run(Thread.java:818)�
12-05 13:47:41.422 21896-27454/my_app_id E/ExoPlayerImplInternal: Internal runtime error.
                                                                                               java.lang.ArrayIndexOutOfBoundsException: src.length=131072 srcPos=5230 dst.length=16 dstPos=0 length=118
                                                                                                   at java.lang.System.arraycopy(Native Method)
                                                                                                   at com.google.android.exoplayer.extractor.RollingSampleBuffer.readData(RollingSampleBuffer.java:304)
                                                                                                   at com.google.android.exoplayer.extractor.RollingSampleBuffer.readEncryptionData(RollingSampleBuffer.java:221)
                                                                                                   at com.google.android.exoplayer.extractor.RollingSampleBuffer.readSample(RollingSampleBuffer.java:186)
                                                                                                   at com.google.android.exoplayer.extractor.DefaultTrackOutput.getSample(DefaultTrackOutput.java:141)
                                                                                                   at com.google.android.exoplayer.chunk.ChunkSampleSource.readData(ChunkSampleSource.java:279)
                                                                                                   at com.google.android.exoplayer.SampleSourceTrackRenderer.readSource(SampleSourceTrackRenderer.java:208)
                                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:636)
                                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:529)
                                                                                                   at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                                                   at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                                                   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                                   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
12-05 13:47:41.430 21896-21896/my_app_id W/System.err: com.google.android.exoplayer.ExoPlaybackException: java.lang.ArrayIndexOutOfBoundsException: src.length=131072 srcPos=5230 dst.length=16 dstPos=0 length=118
12-05 13:47:41.430 21896-21896/my_app_id W/System.err:     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:244)
12-05 13:47:41.430 21896-21896/my_app_id W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
12-05 13:47:41.430 21896-21896/my_app_id W/System.err:     at android.os.Looper.loop(Looper.java:135)
12-05 13:47:41.430 21896-21896/my_app_id W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
12-05 13:47:41.430 21896-21896/my_app_id W/System.err:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
12-05 13:47:41.430 21896-21896/my_app_id W/System.err: Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=131072 srcPos=5230 dst.length=16 dstPos=0 length=118
12-05 13:47:41.430 21896-21896/my_app_id W/System.err:     at java.lang.System.arraycopy(Native Method)
12-05 13:47:41.430 21896-21896/my_app_id W/System.err:     at com.google.android.exoplayer.extractor.RollingSampleBuffer.readData(RollingSampleBuffer.java:304)
12-05 13:47:41.430 21896-21896/my_app_id W/System.err:     at com.google.android.exoplayer.extractor.RollingSampleBuffer.readEncryptionData(RollingSampleBuffer.java:221)
12-05 13:47:41.430 21896-21896/my_app_id W/System.err:     at com.google.android.exoplayer.extractor.RollingSampleBuffer.readSample(RollingSampleBuffer.java:186)
12-05 13:47:41.430 21896-21896/my_app_id W/System.err:     at com.google.android.exoplayer.extractor.DefaultTrackOutput.getSample(DefaultTrackOutput.java:141)
12-05 13:47:41.431 21896-21896/my_app_id W/System.err:     at com.google.android.exoplayer.chunk.ChunkSampleSource.readData(ChunkSampleSource.java:279)
12-05 13:47:41.431 21896-21896/my_app_id W/System.err:     at com.google.android.exoplayer.SampleSourceTrackRenderer.readSource(SampleSourceTrackRenderer.java:208)
12-05 13:47:41.431 21896-21896/my_app_id W/System.err:     at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:636)
12-05 13:47:41.431 21896-21896/my_app_id W/System.err:     at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:529)
12-05 13:47:41.431 21896-21896/my_app_id W/System.err:     at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
12-05 13:47:41.431 21896-21896/my_app_id W/System.err:     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
12-05 13:47:41.431 21896-21896/my_app_id W/System.err:     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
12-05 13:47:41.431 21896-21896/my_app_id W/System.err: 	... 4 more
12-05 13:47:41.431 21896-21896/my_app_id E/EventLogger: playerFailed [232.01]
                                                                                     com.google.android.exoplayer.ExoPlaybackException: java.lang.ArrayIndexOutOfBoundsException: src.length=131072 srcPos=5230 dst.length=16 dstPos=0 length=118
                                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:244)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                         at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                      Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=131072 srcPos=5230 dst.length=16 dstPos=0 length=118
                                                                                         at java.lang.System.arraycopy(Native Method)
                                                                                         at com.google.android.exoplayer.extractor.RollingSampleBuffer.readData(RollingSampleBuffer.java:304)
                                                                                         at com.google.android.exoplayer.extractor.RollingSampleBuffer.readEncryptionData(RollingSampleBuffer.java:221)
                                                                                         at com.google.android.exoplayer.extractor.RollingSampleBuffer.readSample(RollingSampleBuffer.java:186)
                                                                                         at com.google.android.exoplayer.extractor.DefaultTrackOutput.getSample(DefaultTrackOutput.java:141)
                                                                                         at com.google.android.exoplayer.chunk.ChunkSampleSource.readData(ChunkSampleSource.java:279)
                                                                                         at com.google.android.exoplayer.SampleSourceTrackRenderer.readSource(SampleSourceTrackRenderer.java:208)
                                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:636)
                                                                                         at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:529)
                                                                                         at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)�
                                                                                         at android.os.Looper.loop(Looper.java:135)�
                                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)�
                                                                                         at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)�
12-05 13:47:41.529 21896-27467/my_app_id E/LoadTask: Unexpected exception loading stream
                                                                                  java.lang.IllegalStateException: Top bit not zero: -69444500
                                                                                      at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:299)
                                                                                      at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:930)
                                                                                      at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:195)
                                                                                      at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:92)
                                                                                      at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:164)
                                                                                      at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                      at java.lang.Thread.run(Thread.java:818)
```

Thanks and BR,
Marco

**Comment by ojw28** [comment]
As far as I can tell, the chunk is just not encoded correctly. The chunk contains 125 samples. It looks like extraction fails at sample index 62 (i.e. the 63rd sample) because it doesn't start with a valid 4 byte NAL unit length.

**Comment by marcuz89** [comment]
Ok thank you very much, two questions.
1) Could you kindly explain me how to read from logs samples number and index?
2) Is it possible skipping chunks in an easy way when these exceptions occur in order to avoid the state idle of player?

**Comment by ojw28** [comment]
1. I added some logging to `FragmentedMp4Extractor`, attached the debugger, added some useful breakpoints etc. No magic was involved :).
1. Nope. The serving side should just not serve broken media under any circumstances.
