### ISSUE TITLE
Decoder init failed: OMX.Intel.VideoDecoder.AVC.secure

### ISSUE THREAD

**Issue by longteng9** [google/ExoPlayer#2165]
```
*E/ExoPlayerImplInternal: Renderer error.
                                                                            com.google.android.exoplayer2.ExoPlaybackException
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:377)
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:365)
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:755)
                                                                                at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324)
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:495)
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:478)
                                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                             Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Intel.VideoDecoder.AVC.secure, Format(video/1, null, video/avc, 554949, , null, [426, 240, 30.0], [-1, -1])
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:365)?
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:755)?
                                                                                at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324)?
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:495)?
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:478)?
                                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)?
                                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)?
                                                                                at android.os.Handler.dispatchMessage(Handler.java:98)?
                                                                                at android.os.Looper.loop(Looper.java:154)?
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)?
                                                                                at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)?
                                                                             Caused by: android.media.MediaCodec$CodecException: start failed
                                                                                at android.media.MediaCodec.native_start(Native Method)
                                                                                at android.media.MediaCodec.start(MediaCodec.java:1989)
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:356)
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:755)?
                                                                                at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324)?
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:495)?
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:478)?
                                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)?
                                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)?
                                                                                at android.os.Handler.dispatchMessage(Handler.java:98)?
                                                                                at android.os.Looper.loop(Looper.java:154)?
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)?
                                                                                at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)?
 E/EventLogger: playerFailed [2.99]
                                                                  com.google.android.exoplayer2.ExoPlaybackException
                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:377)
                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:365)
                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:755)
                                                                      at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324)
                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:495)
                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:478)
                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                      at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Intel.VideoDecoder.AVC.secure, Format(video/1, null, video/avc, 554949, , null, [426, 240, 30.0], [-1, -1])
                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:365)?
                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:755)?
                                                                      at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324)?
                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:495)?
                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:478)?
                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)?
                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)?
                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)?
                                                                      at android.os.Looper.loop(Looper.java:154)?
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)?
                                                                      at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)?
                                                                   Caused by: android.media.MediaCodec$CodecException: start failed
                                                                      at android.media.MediaCodec.native_start(Native Method)
                                                                      at android.media.MediaCodec.start(MediaCodec.java:1989)
                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:356)
                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:755)?
                                                                      at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324)?
                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:495)?
                                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:478)?
                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)?
                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)?
                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)?
                                                                      at android.os.Looper.loop(Looper.java:154)?
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)?
                                                                      at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)?
 E/ExoPlayerImplInternal: Stop failed.
                                                                            java.lang.IllegalStateException
                                                                                at android.media.MediaCodec.native_stop(Native Method)
                                                                                at android.media.MediaCodec.stop(MediaCodec.java:2005)
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:447)
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:402)
                                                                                at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:275)
                                                                                at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:136)
                                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:631)
                                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:607)
                                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by longteng9** [comment]
I tried a 174 solution but unfortunately there was no effect

**Comment by ojw28** [comment]
Closing because the issue lacks nearly all of the information requested in the issue template. We cannot investigate issues such as this one if you do not provide sufficient information.
