### ISSUE TITLE
NullPointerException in PlayerActivity onTimelineChanged

### ISSUE THREAD

**Issue by clhols** [google/ExoPlayer#2186]
When running the Demo app from the dev-2 branch and hitting the Retry button when the Timeline is dynamic, I get the following exception:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.exoplayer2.Timeline.isEmpty()' on a null object reference
                                                                                        at com.google.android.exoplayer2.demo.PlayerActivity.onTimelineChanged(PlayerActivity.java:430)
                                                                                        at com.google.android.exoplayer2.ExoPlayerImpl.prepare(ExoPlayerImpl.java:128)
                                                                                        at com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:494)
                                                                                        at com.google.android.exoplayer2.demo.PlayerActivity.initializePlayer(PlayerActivity.java:327)
                                                                                        at com.google.android.exoplayer2.demo.PlayerActivity.onClick(PlayerActivity.java:213)
```

**Comment by ojw28** [comment]
We'll push a fix for this tomorrow; thanks!
