### ISSUE TITLE
when play mp3 in background and lock screen  error happen

### ISSUE THREAD

**Issue by yanglichuan** [google/ExoPlayer#2188]
I have add wifylock and wakelock   but   after ten minutes   error happend  

```
/ExoPlayerImplInternal: Source error.
                                                                         com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://cdn.kaishuhezi.com/audio/story/M-3-01-20150408.mp3
                                                                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:195)
                                                                             at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:596)
                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                          Caused by: java.net.ConnectException: failed to connect to cdn.kaishuhezi.com/221.204.226.179 (port 80) after 8000ms: isConnected failed: ECONNREFUSED (Connection refused)
                                                                             at libcore.io.IoBridge.isConnected(IoBridge.java:238)
                                                                             at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
                                                                             at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                             at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                             at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
                                                                             at java.net.Socket.connect(Socket.java:882)
                                                                             at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
                                                                             at com.android.okhttp.Connection.connect(Connection.java:152)
                                                                             at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
                                                                             at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
                                                                             at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
                                                                             at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
                                                                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:427)
                                                                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:351)
                                                                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193)
                                                                             at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                                                                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:596) 
                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                             at java.lang.Thread.run(Thread.java:818) 
                                                                          Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
                                                                             at libcore.io.IoBridge.isConnected(IoBridge.java:223)
                                                                             at libcore.io.IoBridge.connectErrno(IoBridge.java:171) 
                                                                             at libcore.io.IoBridge.connect(IoBridge.java:122) 
                                                                             at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
                                                                             at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456) 
                                                                             at java.net.Socket.connect(Socket.java:882) 
                                                                             at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174) 
                                                                             at com.android.okhttp.Connection.connect(Connection.java:152) 
                                                                             at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276) 
                                                                             at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211) 
                                                                             at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382) 
                                                                             at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106) 
                                                                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:427) 
                                                                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:351) 
                                                                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193) 
                                                                             at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                                                                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:596) 
                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                             at java.lang.Thread.run(Thread.java:818) 
12-13 13:28:45.326 2521-2521/com.ks.kaishustory E/EventLogger: playerFailed [848.70]
                                                               com.google.android.exoplayer2.ExoPlaybackException
                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:310)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://cdn.kaishuhezi.com/audio/story/M-3-01-20150408.mp3
                                                                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:195)
                                                                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:596)
                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                   at java.lang.Thread.run(Thread.java:818)
                                                                Caused by: java.net.ConnectException: failed to connect to cdn.kaishuhezi.com/221.204.226.179 (port 80) after 8000ms: isConnected failed: ECONNREFUSED (Connection refused)
                                                                   at libcore.io.IoBridge.isConnected(IoBridge.java:238)
                                                                   at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
                                                                   at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                   at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                   at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
                                                                   at java.net.Socket.connect(Socket.java:882)
                                                                   at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
                                                                   at com.android.okhttp.Connection.connect(Connection.java:152)
                                                                   at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
                                                                   at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
                                                                   at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
                                                                   at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
                                                                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:427)
                                                                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:351)
                                                                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193)
                                                                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:596) 
                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                   at java.lang.Thread.run(Thread.java:818) 
                                                                Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
                                                                   at libcore.io.IoBridge.isConnected(IoBridge.java:223)
                                                                   at libcore.io.IoBridge.connectErrno(IoBridge.java:171) 
                                                                   at libcore.io.IoBridge.connect(IoBridge.java:122) 
                                                                   at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
                                                                   at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456) 
                                                                   at java.net.Socket.connect(Socket.java:882) 
                                                                   at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174) 
                                                                   at com.android.okhttp.Connection.connect(Connection.java:152) 
                                                                   at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276) 
                                                                   at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211) 
                                                                   at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382) 
                                                                   at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106) 
                                                                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:427) 
                                                                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:351) 
                                                                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193) 
                                                                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:596) 
                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                   at java.lang.Thread.run(Thread.java:818) 
```

**Comment by ojw28** [comment]
You should make sure you've acquired WiFi and wake locks to ensure playback whilst in the background (see https://github.com/google/ExoPlayer/issues/930). You'll also need to make sure you're running in a [foreground service](https://developer.android.com/guide/components/services.html#Foreground).
