### ISSUE TITLE
Live MPEG-DASH seeking issues

### ISSUE THREAD

**Issue by moacir69** [google/ExoPlayer#2206]
When playing a live MPEG-DASH content in ExoPlayer 2.1.0 demo application, it is not possible to properly perform a seek. The displayed current seek position never goes past the middle of the seek bar and if a seek is performed to the end, several server 404 errors like the following show up in the logs:

```
12-15 17:48:44.534 20187-20187/com.google.android.exoplayer2.demo E/EventLogger: internalError [3.17, loadError]
                                                                                 com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                     at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:114)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                     at java.lang.Thread.run(Thread.java:841)
```
In order to reproduce the issue, you just need to add a live MPEG-DASH content to the demo app samples, observe the behaviour of the seek bar and attempt to perform a seek to the end, in any device.
I can provide a sample content url by email.
Can you please investigate this issue?
Please, let me know if any further information is needed.
Kind regards,

Moacir

**Comment by ojw28** [comment]
We've got quite a few DASH live streams from multiple providers that we use for internal testing, and seeking is working correctly. It sounds more like a content issue to me. Please provide a test stream.

**Comment by ojw28** [comment]
Also, 404s when seeking near the end of the live window indicates media being advertised by the manifest before the chunks are actually available from the server (which is likely a violation of the DASH spec).

**Comment by moacir69** [comment]
Can you please provide an email address where I should send the test stream?
Warm regards,

Moacir

**Comment by andrewlewis** [comment]
@moacir69 dev.exoplayer@gmail.com

**Comment by moacir69** [comment]
Thank you,
I have just provided the url by email.
Kind regards,

Moacir

**Comment by ojw28** [comment]
The way this manifest is structured requires the client to be able to accurately synchronize against server time. This is normally achieved by the manifest including a `UTCTiming` element, however in this case the manifest does not include one. As a result, the best the client can do is assume that it's own clock is synchronized with the server, which is typically not correct.

The issues you're seeing are a result of the client and server clocks being slightly out of sync. This issue can be illustrated more obviously by changing the time on the client (i.e. mobile device) to be 1 hour ahead of the actual time. You'll find that playback is completely broken in this case.

The solution is for the manifest to include a `UTCTiming` element, which will allow the client to synchronize with server time rather than relying on the local clock.

**Comment by moacir69** [comment]
Thank you for the quick analysis!
Warm regards,

Moacir
