### ISSUE TITLE
android.media.MediaDrm$MediaDrmStateException: Failed to get provision request: DRM vendor-defined error: -2990

### ISSUE THREAD

**Issue by rahulkalamkar** [google/ExoPlayer#2260]
12-26 15:00:53.159 25271-4592/com.google.android.exoplayer2.demo E/MediaDrm-JNI: Illegal state exception: Failed to get provision request: DRM vendor-defined error: -2990 (-2990)
12-26 15:00:53.160 25271-4592/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                          android.media.MediaDrm$MediaDrmStateException: Failed to get provision request: DRM vendor-defined error: -2990
                                                                                              at android.media.MediaDrm.getProvisionRequestNative(Native Method)
                                                                                              at android.media.MediaDrm.getProvisionRequest(MediaDrm.java:881)
                                                                                              at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getProvisionRequest(FrameworkMediaDrm.java:107)
                                                                                              at com.google.android.exoplayer2.drm.StreamingDrmSessionManager.postProvisionRequest(StreamingDrmSessionManager.java:345)
                                                                                              at com.google.android.exoplayer2.drm.StreamingDrmSessionManager.openInternal(StreamingDrmSessionManager.java:331)
                                                                                              at com.google.android.exoplayer2.drm.StreamingDrmSessionManager.acquireSession(StreamingDrmSessionManager.java:266)
                                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:726)
                                                                                              at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324)
                                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489)
                                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472)
                                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                              at android.os.Looper.loop(Looper.java:207)
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                              at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
12-26 15:00:53.163 25271-25271/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [0.84]
                                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                     at android.os.Looper.loop(Looper.java:207)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                  Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get provision request: DRM vendor-defined error: -2990
                                                                                     at android.media.MediaDrm.getProvisionRequestNative(Native Method)
                                                                                     at android.media.MediaDrm.getProvisionRequest(MediaDrm.java:881)
                                                                                     at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getProvisionRequest(FrameworkMediaDrm.java:107)
                                                                                     at com.google.android.exoplayer2.drm.StreamingDrmSessionManager.postProvisionRequest(StreamingDrmSessionManager.java:345)
                                                                                     at com.google.android.exoplayer2.drm.StreamingDrmSessionManager.openInternal(StreamingDrmSessionManager.java:331)
                                                                                     at com.google.android.exoplayer2.drm.StreamingDrmSessionManager.acquireSession(StreamingDrmSessionManager.java:266)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:726)
                                                                                     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                     at android.os.Looper.loop(Looper.java:207) 
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by madhurkapadia** [comment]
I got the same error on particular one device LeEco Le 1s Eco (Le X509) or any LeEco Devices

**Comment by ojw28** [comment]
Closing because the issue does not include the information requested in the issue template. Please file a new issue including all of the requested information if you want us to investigate further. Thanks!

**Comment by rahulkalamkar** [comment]
It is related to your device
