### ISSUE TITLE
NPE in HlsMediaSource.releaseSource()

### ISSUE THREAD

**Issue by komissarovdenis** [google/ExoPlayer#2264]
Sometimes I have a crash with this stacktrace. 
Probably it happens when non prepared Source is goes to be released.
Could you, please, add check `playlistTracker` for null when `releaseSource()` is called?
Lib version is 2.1.1

```
AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
    Process: com.xxx, PID: 5770
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistTracker.release()' on a null object reference
                 at com.google.android.exoplayer2.source.hls.HlsMediaSource.releaseSource(HlsMediaSource.java:97)
                 at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:698)
                 at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:658)
                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:367)
                 at android.os.Handler.dispatchMessage(Handler.java:98)
                 at android.os.Looper.loop(Looper.java:154)
                 at android.os.HandlerThread.run(HandlerThread.java:61)
                 at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                 at InfoAboutApp.VersionCode(numberVersionCode:1047)
```

```
  @Override
  public void releaseSource() {
    playlistTracker.release();
    playlistTracker = null;
    sourceListener = null;
  }
```

**Comment by ojw28** [comment]
Yup, we will do this. Thanks!
