### ISSUE TITLE
Can exoplayer handle https redirects to http?

### ISSUE THREAD

**Issue by m5314** [google/ExoPlayer#2291]
I got an error when i play this video.
"https://vod.cc.163.com/file/5856574fda67d358bafcb545.mp4"

```
com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://vod.cc.163.com/file/5856574fda67d358bafcb545.mp4
                                                                      at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:195)
                                                                      at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                      at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:618)
                                                                      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)
                                                                   Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

**Comment by ojw28** [comment]
It can, but you need to enable it yourself when creating the data source factory. Are you using `DefaultDataSourceFactory`? If so you'll need to:

1. Use the constructor that takes another `DataSource.Factory` as the third argument.
1. Pass a `DefaultHttpDataSourceFactory` as that third argument. When you create your instance of `DefaultHttpDataSourceFactory`, set `allowCrossProtocolRedirects` to true.

If you know usage will be HTTP only you can just use a `DefaultHttpDataSourceFactory` directly.

**Comment by ojw28** [comment]
Although I don't think the issue you're seeing is due to a cross protocol redirect. It looks to me more likely that the server just isn't configured correctly, as per [this article](https://developer.android.com/training/articles/security-ssl.html#CommonProblems).
