### ISSUE TITLE
Can I run test under emulator?

### ISSUE THREAD

**Issue by bagusflyer** [google/ExoPlayer#230]
The demo doesn't work for DASH stream under my emulator. I got the following error message:

01-09 09:24:36.138    2340-2379/com.google.android.exoplayer.demo E/SoftAVC﹕ Decoder failed: -2
01-09 09:24:36.139    2340-2378/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.google.h264.decoder] ERROR(0x80001001)
01-09 09:24:36.139    2340-2378/com.google.android.exoplayer.demo E/ACodec﹕ signalError(omxError 0x80001001, internalError -2147483648)
01-09 09:24:36.140    2340-2377/com.google.android.exoplayer.demo E/MediaCodec﹕ Codec reported err 0x80001001, actionCode 0, while in state 6
01-09 09:24:36.142    2340-2369/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal runtime error.
    java.lang.IllegalStateException
            at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
            at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:983)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:497)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:422)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:398)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
01-09 09:24:36.159    2340-2340/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [7.89]
    com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:236)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.lang.IllegalStateException
            at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
            at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:983)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:497)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:422)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:398)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by bagusflyer** [comment]
To answer my own question. Yes. It needs the real device to run.
