### ISSUE TITLE
Reaches OOM

### ISSUE THREAD

**Issue by ankush38u** [google/ExoPlayer#2307]
Crashes on some devices with OutOfMemory while used internally by Firebase Ads.

Here is the stacktrace from crashlytics:

```
Fatal Exception: java.lang.OutOfMemoryError
       at com.google.android.gms.ads.exoplayer1.upstream.g.a(:com.google.android.gms.DynamiteModulesA:51)
       at com.google.android.gms.ads.exoplayer1.extractor.k.b(:com.google.android.gms.DynamiteModulesA:432)
       at com.google.android.gms.ads.exoplayer1.extractor.c.a(:com.google.android.gms.DynamiteModulesA:2384)
       at com.google.android.gms.ads.exoplayer1.extractor.mp4.f.b(:com.google.android.gms.DynamiteModulesA:311)
       at com.google.android.gms.ads.exoplayer1.extractor.mp4.f.a(:com.google.android.gms.DynamiteModulesA:108)
       at com.google.android.gms.ads.exoplayer1.extractor.h.c(:com.google.android.gms.DynamiteModulesA:615)
       at com.google.android.gms.ads.exoplayer1.upstream.t.run(:com.google.android.gms.DynamiteModulesA:242)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

Happens on android 4,5,6 all, frequecy is around 12-15 in a month.

**Comment by ojw28** [comment]
The fact your app ran out or memory whilst using ExoPlayer doesn't in itself indicate an ExoPlayer issue. It's the sum of all memory used by your app that results in the OOM; the exact point at which the OOM occurs can be irrelevant, and your app is equally likely leaking memory elsewhere.

12-15 also sounds like. . .barely anything, although without a baseline (e.g. number of playbacks / installs) it's impossible to say. . .

**Comment by ojw28** [comment]
Closing because there's no evidence this is really an ExoPlayer leak.
