### ISSUE TITLE
com.google.android.exoplayer2.source.BehindLiveWindowException(Audio Only,version:2.0.4)

### ISSUE THREAD

**Issue by jyh149129** [google/ExoPlayer#2323]
ExoPlayerImplInternal: Source error.
                                                              com.google.android.exoplayer2.source.BehindLiveWindowException
                                                                      at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:267)
                                                                      at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:338)
                                                                      at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:55)
                                                                      at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading(HlsMediaPeriod.java:211)
                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1089)
                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1076)
                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:289)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                      at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by AquilesCanta** [comment]
See #1782. Please pay attention to the issue template next time.
