### ISSUE TITLE
Stop playing DASH video occasionally

### ISSUE THREAD

**Issue by bagusflyer** [google/ExoPlayer#233]
The video playing (Simple Player) stopped from time to time with the following error message:

> 01-12 13:37:56.641    6250-6250/com.google.android.exoplayer.demo E/PlayerActivity﹕ Playback failed
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://192.168.40.65:1935/Hollywoodbuzz/Stream1/chunk_ctvideo_cfm4s_ridp0a0r0_cs39265206750_w1856643263_mpd.m4s
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:428)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:398)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://192.168.40.65:1935/Hollywoodbuzz/Stream1/chunk_ctvideo_cfm4s_ridp0a0r0_cs39265206750_w1856643263_mpd.m4s
            at com.google.android.exoplayer.upstream.HttpDataSource.open(HttpDataSource.java:236)
            at com.google.android.exoplayer.upstream.UriDataSource.open(UriDataSource.java:66)
            at com.google.android.exoplayer.upstream.DataSourceStream.load(DataSourceStream.java:223)
            at com.google.android.exoplayer.chunk.Chunk.load(Chunk.java:176)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:206)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.SocketTimeoutException: failed to connect to /192.168.40.65 (port 1935) after 8000ms
            at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
            at libcore.io.IoBridge.connect(IoBridge.java:122)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
            at java.net.Socket.connect(Socket.java:882)
            at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
            at com.android.okhttp.Connection.connect(Connection.java:148)
            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
            at com.android.okhttp.internal.http.HttpEngaine.sendRequest(HttpEngine.java:211)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
            at com.google.android.exoplayer.upstream.HttpDataSource.makeConnection(HttpDataSource.java:386)
            at com.google.android.exoplayer.upstream.HttpDataSource.open(HttpDataSource.java:234)
            at com.google.android.exoplayer.upstream.UriDataSource.open(UriDataSource.java:66)
            at com.google.android.exoplayer.upstream.DataSourceStream.load(DataSourceStream.java:223)
            at com.google.android.exoplayer.chunk.Chunk.load(Chunk.java:176)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:206)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

This video is never stopped when I play it through browser. That means the network has no problem at all. 

Any suggestion? Thanks

**Comment by ojw28** [comment]
That is a network connectivity issue, or an issue with the server. The fact that it plays through a browser doesn't imply this isn't the case. It may be that whatever browser player you're using has a larger connection timeout, or retries harder before failing, or is picking a different bitrate stream. That server doesn't respond to pings at all for me.

**Comment by bagusflyer** [comment]
Thanks for your reply.

You can't ping the server because that's an internal ip address.  We serve HLS, DASH, and Smooth streaming video at the same time through the same server. But HLS and Smooth streaming video never got the same problem. It only happened for DASH streaming so that we're not very suer it's a sever problem or the player's problem.

**Comment by ojw28** [comment]
Are you saying HLS and SmoothStreaming work correctly using ExoPlayer, but DASH fails? Or were you testing HLS and SmoothStreaming with a different player? Also, is this a Live stream, or an on-demand stream?

Knowing the above would be useful/interesting, however there's not too much we can do to help unless you can provide a publicly accessible stream that reproduces the issue (if you could do that, that would be great, and we'll take a look).

**Comment by ojw28** [comment]
Closing due to inactivity / nothing actionable.
