### ISSUE TITLE
getCapabilitiesForType (Native) exception on Samsung Tab 3

### ISSUE THREAD

**Issue by dobrusev** [google/ExoPlayer#2345]
Hello guys,

Current I'm using exoplayer v2.0.1 and DASH with Widevine stream. Playback fails with 

```
01-18 16:15:23.499 3759-4345/com.dazn.test E/MediaCodecUtil: Failed to query codec OMX.Intel.VideoDecoder.AVC (video/avc)
01-18 16:15:23.589 3759-4345/com.dazn.test E/ExoPlayerImplInternal: Renderer error.
                                                                    com.google.android.exoplayer2.ExoPlaybackException
                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.supportsFormat(MediaCodecRenderer.java:245)
                                                                        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:343)
                                                                        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:249)
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.selectTracks(ExoPlayerImplInternal.java:1247)
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.handlePrepared(ExoPlayerImplInternal.java:1242)
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1054)
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:281)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                        at android.os.Looper.loop(Looper.java:146)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                        at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:207)
                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java:145)
                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfo(MediaCodecUtil.java:121)
                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecSelector$1.getDecoderInfo(MediaCodecSelector.java:34)
                                                                        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.supportsFormat(MediaCodecVideoRenderer.java:184)
                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.supportsFormat(MediaCodecRenderer.java:243)
                                                                        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:343) 
                                                                        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:249) 
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.selectTracks(ExoPlayerImplInternal.java:1247) 
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.handlePrepared(ExoPlayerImplInternal.java:1242) 
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1054) 
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:281) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                        at android.os.Looper.loop(Looper.java:146) 
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                        at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                                     Caused by: java.lang.IllegalArgumentException
                                                                        at android.media.MediaCodecList.getCodecCapabilities(Native Method)
                                                                        at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:291)
                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:176)
                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java:145) 
                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfo(MediaCodecUtil.java:121) 
                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecSelector$1.getDecoderInfo(MediaCodecSelector.java:34) 
                                                                        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.supportsFormat(MediaCodecVideoRenderer.java:184) 
                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.supportsFormat(MediaCodecRenderer.java:243) 
                                                                        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:343) 
                                                                        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:249) 
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.selectTracks(ExoPlayerImplInternal.java:1247) 
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.handlePrepared(ExoPlayerImplInternal.java:1242) 
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1054) 
                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:281) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                        at android.os.Looper.loop(Looper.java:146) 
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                        at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```
I remember that on v1.x of exoplayer I was able to bypass this issue with setting the security level of the DRM to L3.

I try to do it again but it looks like I don't do it write since I get this error.
Here is the code that I use now:

```
@Override
protected DrmSessionManager<FrameworkMediaCrypto> buildDrmSessionManager(UUID uuid, String licenseUrl, Map<String, String> keyRequestProperties) throws UnsupportedDrmException {
		
               if (Util.SDK_INT < Build.VERSION_CODES.JELLY_BEAN_MR2) {
			return null;
		}

		AdvancedHttpMediaDrmCallback drmCallback = new AdvancedHttpMediaDrmCallback(contentLaUrl, buildHttpDataSourceFactory(false), keyRequestProperties);

		FrameworkMediaDrm mediaDrm = FrameworkMediaDrm.newInstance(uuid);

		if (useL3)
			mediaDrm.setPropertyString("securityLevel", "L3");
		return new StreamingDrmSessionManager<>(uuid, mediaDrm, drmCallback, null, mainHandler, drmSessionListener);
	}
```

Do I set the securityLevel properly?
Am I on a right way or this is completely different issue?

Regards,
Dobri Rusev

**Comment by ojw28** [comment]
Please provide a full bug report. The issue template explicitly states that a snippet of logcat is not sufficient.

**Comment by dobrusev** [comment]
HI @ojw28 

In our app we are playing DASH with Widevine DRM protection.
At some point we migrated to the new exoplayer v2 from 1.5.x.

The exception that we see is 
`android.media.MediaCodecList.getCodecCapabilities(Native Method)`
which make the playback to fail.

From the research that I did I saw that other people report that they experiencing the same issue and this is actually a device manufacturer issue.

Before we migrate from 1.5.x to 2.0.1  we were having playback on this device by enforcing secure level L3 on the DRM. From that being said I can conclude (maybe wrongly) that we don't property enforce the secure level on the version 2 exoplayer (code provided in my first comment).

Please be more specific what other information you need that will help you investigate the issue further.

Regards

**Comment by ojw28** [comment]
As per the issue template, we require:

> A bug report taken from the device just after the issue occurs, attached as a
  file. A bug report can be captured using "adb bugreport". Output from "adb
  logcat" or a log snippet is not sufficient.

So please run "adb bugreport" shortly after reproducing the issue, and attach the resulting output to this issue (e.g. as a file).

**Comment by dobrusev** [comment]
apologies that I didn't read carefully the issue template.

Here is the bugreport 
[bugreport.txt](https://github.com/google/ExoPlayer/files/716466/bugreport.txt)

**Comment by ojw28** [comment]
Thanks for the bug report. Does playback work if you simply comment out the `throw e` line [here](https://github.com/google/ExoPlayer/blob/r2.1.1/library/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecUtil.java#L210)? I'm not really sure there's a better solution to this problem.

If this does allow playback to proceed, we can add a device + decoder specific workaround to suppress the failure. Please confirm either way.

**Comment by dobrusev** [comment]
Thank's for the hint.
I will try it but it looks like we can't reproduce this issue any more.

**Comment by ojw28** [comment]
Closing for now, in that case.
