### ISSUE TITLE
Not able to certain stream .mp3 URLs with ExoPlayer

### ISSUE THREAD

**Issue by bbincybbaby** [google/ExoPlayer#2359]
I would like to create a music player using ExoPlayer. App working fine but certain urls like 

[https://d33av21req61rl.cloudfront.net/track-files/636febce-7840-4d3f-9486-049c10afeb48.mp3](url) 

not playing in Exoplayer. Error log provided below

```
E/ExoPlayerImplInternal: Source error.
                                                          com.google.android.exoplayer2.source.ExtractorMediaSource$UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                              at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:699)
                                                              at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:623)
                                                              at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                              at java.lang.Thread.run(Thread.java:818)
```

**Comment by andrewlewis** [comment]
The file format can't be detected because the stream starts with an HTML fragment that looks like some kind of error from PHP.

**Comment by bbincybbaby** [comment]
but 
[https://d33av21req61rl.cloudfront.net/track-files/34ef163a-2389-461f-9c99-07806befc439.mp3](url)

this one works fine

**Comment by andrewlewis** [comment]
That stream starts with an ID3 tag, whereas the first one has what looks like an error message in an HTML fragment at the start.

The Mp3Extractor currently sniffs only as far as the (maximum) MPEG audio frame size before giving up. Is it possible that the server that provided the first file is misconfigured?
