### ISSUE TITLE
Exoplayer unable to play FrameworkSampleSource created from mp4a-latm file

### ISSUE THREAD

**Issue by spark85** [google/ExoPlayer#236]
Hello, 

I'm creating a backup copy of an AAC_ATDS streaming audio file, created with MediaRecorder by writing the contents of the MediaRecorder to a local file.  However, these backups files are not playable on all devices.  Using the MediaExtractor I am able to determine that the encoding type of these files is mp4a-latm; which is a form raw AAC encoding.  What should I do to be able to play these files with Exoplayer?  

I get the following error message: 
01-13 12:24:50.295  26909-27301/com.instaradio E/OMXMaster﹕ A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
01-13 12:24:50.307  26909-27301/com.instaradio E/ACodec﹕ [OMX.google.aac.decoder] ERROR(0x80001001)
01-13 12:24:50.307  26909-27301/com.instaradio E/ACodec﹕ signalError(omxError 0x80001001, internalError -2147483648)
01-13 12:24:50.307  26909-27301/com.instaradio E/MediaCodec﹕ Codec reported err 0x80001001, actionCode 0, while in state 6
01-13 12:24:50.318  26909-27288/com.instaradio E/ExoPlayerImplInternal﹕ Internal runtime error.
    java.lang.IllegalStateException
            at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
            at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:720)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:420)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:398)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by ojw28** [comment]
FrameworkSampleSource is deprecated, so we wont be fixing this.
