### ISSUE TITLE
Unexpected exception for playing mp3 in Bluestacks emulator

### ISSUE THREAD

**Issue by Behrouz-m** [google/ExoPlayer#2363]
when I play mp3 files using http protocol in Bluestacks emulator I get following stack trace

```log
01-23 15:10:20.286 2757-3435/app_package_name E/ACodec: OMX/mediaserver died, signalling error!
01-23 15:10:20.286 2757-3435/app_package_name E/MediaCodec: Codec reported an error. (omx error 0x8000100d, internalError -32)
01-23 15:10:20.286 2757-3433/app_package_name E/ExoPlayerImplInternal: Internal runtime error.
                                                                         java.lang.IllegalStateException
                                                                             at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:852)
                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:484)
                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                             at android.os.Looper.loop(Looper.java:136)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                             at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
01-23 15:10:20.286 2757-2757/app_package_name E/EventLogger: playerFailed [0.21]
                                                               com.google.android.exoplayer2.ExoPlaybackException
                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:365)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                Caused by: java.lang.IllegalStateException
                                                                   at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
                                                                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:852)
                                                                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:484)
                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

sample files:
[sample.zip](https://github.com/google/ExoPlayer/files/723446/sample.zip)

**Comment by ojw28** [comment]
Please see [this FAQ](https://google.github.io/ExoPlayer/faqs.html#does-exoplayer-support-emulators).
