### ISSUE TITLE
DecoderInitializationException for Asus P021

### ISSUE THREAD

**Issue by replystreamingwidevine** [google/ExoPlayer#2380]
When we play linear content on Asus P021 device. When we try to play a linear channel with DRM, we got a DecoderInitializationException. Below you can find the snippet of the Exception

More info: 
a) The app is able to play successfully the VOD content.
b) And after playing one VOD content, when i retry to play again the linear content, it works correctly. 
c) If i switch from foreground to background and after that to foreground again (without executing point a or b), the app is able to play content

You can replicate the issue using the app shared for ticket #2334 

Snippet of the log:
```
com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.rk.video_decoder.avc.secure, MediaFormat(3, video/avc, -1, -1, 640, 360, 0, 1.0, -1, -1, null, 1000000, false, 720, 404, -1, -1, -1)
  at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400)
  at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.setSurface(MediaCodecVideoTrackRenderer.java:314)
  at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.handleMessage(MediaCodecVideoTrackRenderer.java:295)
  at com.google.android.exoplayer.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:589)
  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:229)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at android.os.Looper.loop(Looper.java:135)
  at android.os.HandlerThread.run(HandlerThread.java:61)
  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
Caused by: android.media.MediaCodec$CodecException: start failed
  at android.media.MediaCodec.native_start(Native Method)
  at android.media.MediaCodec.start(MediaCodec.java:612)
  at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:392)
  at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.setSurface(MediaCodecVideoTrackRenderer.java:314) 
  at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.handleMessage(MediaCodecVideoTrackRenderer.java:295) 
  at com.google.android.exoplayer.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:589) 
  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:229) 
  at android.os.Handler.dispatchMessage(Handler.java:98) 
  at android.os.Looper.loop(Looper.java:135) 
  at android.os.HandlerThread.run(HandlerThread.java:61) 
  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

**Comment by ojw28** [comment]
Please provide a full bug report. It would be helpful if you could stop filing issues without providing all of the information requested in the issue template. We're really not able to help with these issues without complete information, and having to respond to each one requesting it is not an efficient use of time.

**Comment by replystreamingwidevine** [comment]
Full bug report sent via mail to dev.exoplayer@gmail.com. Apk to reproduce already shared for ticket #2334

**Comment by replystreamingwidevine** [comment]
We have additional information on this topic:

1) The issue occurs when we switch from a channel DRM free to a channel with DRM. Does not happe if we start from a DRM'ed channel and we switch several time on DRM'ed channel  
2) The issue occurs also on the ExoPlayer Demo (1.5.9 but on 2.2.0 as well). We have modified the application to replicate this case

**Comment by ojw28** [comment]
Closing as part of a scrub of old device specific issues.
