### ISSUE TITLE
Domains with underscores fail to play

### ISSUE THREAD

**Issue by tdyer-aio** [google/ExoPlayer#239]
if you have a domain with an underscore in the domain the player will fail with an UnknownHostException.

The root cause of the UnknownHostException seems to be that when you create a URI from a URL it parses the host, and URI does not believe that domains can contain an underscore.

To test I created a hosts entry on my android device pointing to my local server called 'dayne_local' I also created a hosts entry called 'daynelocal' and streams pointing there worked as expected.

 java.net.UnknownHostException: http://dayne_local:8002/stream.m3u8
     at libcore.net.http.HttpConnection$Address.<init>(HttpConnection.java:283)
     at libcore.net.http.HttpConnection.connect(HttpConnection.java:128)
     at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:315)
     at libcore.net.http.HttpEngine.connect(HttpEngine.java:310)
     at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
     at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
     at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:80)
     at com.google.android.exoplayer.util.ManifestFetcher$ManifestLoadable.configureConnection(ManifestFetcher.java:381)
     at com.google.android.exoplayer.util.ManifestFetcher$ManifestLoadable.load(ManifestFetcher.java:363)
     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:206)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
	 at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	 at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	 at java.lang.Thread.run(Thread.java:856)

**Comment by ojw28** [comment]
I'm not sure I follow your diagnosis. According to the stack trace, the initial connection is failing at L363, which constructs a URL from a String (I'm not sure where Uri is involved). The URL string at the top of the stack trace also appears to have correctly preserved the underscore.

Could you clarify exactly what you think is happening? Thanks!

**Comment by tdyer-aio** [comment]
Hi,

In my codebase we previously always created a HEAD request to the resource before loading the video into the MediaPlayer. We recently found an issue with the same top half of the stack trace where doing something like:

```
                URL url = new URL(urlString);
                urlConnection = (HttpURLConnection) url.openConnection();
                urlConnection.setRequestMethod("HEAD");
                urlConnection.setRequestProperty("Connection", "close");
                urlConnection.setConnectTimeout(1000);
                urlConnection.setReadTimeout(1000);
                int responseCode = urlConnection.getResponseCode();
                if (responseCode != 200) {
                    return false;
                } else {
                    return true;
                }
```
with an underscore will cause the issue. 

The Address class inside HTTPConnection takes a constructor that contains a URI not a URL and it seems that when parsing a domain with an underscore it fails.

```
public Address(URI uri, SSLSocketFactory sslSocketFactory) throws UnknownHostException {
            this.proxy = null;
            this.requiresTunnel = false;
            this.uriHost = uri.getHost();
            this.uriPort = uri.getEffectivePort();
            this.sslSocketFactory = sslSocketFactory;
            this.socketHost = uriHost;
            this.socketPort = uriPort;
            if (uriHost == null) {
                throw new UnknownHostException(uri.toString());
            }
        }
```

Then at the end of the constructor urIHost == null and  ```throw new UnknownHostException(uri.toString());``` gets thrown.

**Comment by ojw28** [comment]
Thanks. Do you know of a potential fix or workaround at the ExoPlayer level? It feels to me like the underlying issue you describe is fairly deep in platform code.

**Comment by ojw28** [comment]
Actually, please see https://code.google.com/p/android/issues/detail?id=37577. The short version is that underscores aren't actually valid characters URLs.
