### ISSUE TITLE
Playing local mp3 using Exoplayer causing this error 

### ISSUE THREAD

**Issue by bbincybbaby** [google/ExoPlayer#2404]
Source error.

```
com.google.android.exoplayer2.source.ExtractorMediaSource$UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                              at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:699)
                                                              at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:623)
                                                              at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                              at java.lang.Thread.run(Thread.java:818)
```

Playing local mp3 using Exoplayer causing this error 

```
new ExtractorMediaSource(file:///data/data/com.SocialMob/cache/socialmobtest2059532438.mp3, mediaDataSourceFactory, new DefaultExtractorsFactory(),
                        mainHandler, this)
```

**Comment by andrewlewis** [comment]
Looks like the other issue you filed (#2359). We need the problematic media to investigate, as requested in the issue template.

**Comment by ojw28** [comment]
Closing due to lack of information.
