### ISSUE TITLE
Exoplayer crash

### ISSUE THREAD

**Issue by sandeshlasnapure** [google/ExoPlayer#2421]
### Logcat
```
E/OMXNodeInstance: OMX_GetExtensionIndex failed
02-04 17:37:53.987 4556-6026/ E/OMXNodeInstance: OMX_GetExtensionIndex failed
02-04 17:37:54.427 4556-6024/ E/SoftAVC: Decoder failed: -2
02-04 17:37:54.427 4556-6023/ E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
02-04 17:37:54.427 4556-6023/ E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -2147483648)
02-04 17:37:54.427 4556-5072/ E/ExoPlayerImplInternal: Internal runtime error.
                                                                      java.lang.IllegalStateException
                                                                          at android.media.MediaCodec.dequeueInputBuffer(Native Method)
                                                                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:542)
                                                                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:485)
                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                          at android.os.HandlerThread.run(HandlerThread.java:60)
                                                                          at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
02-04 17:37:54.437 4556-4556/ E/TAG: onPlayerError: null
02-04 17:37:54.437 4556-4556/ E/EventLogger: playerFailed [63.83]
                                                            com.google.android.exoplayer2.ExoPlaybackException
                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:365)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:137)
                                                                at android.os.HandlerThread.run(HandlerThread.java:60)
                                                                at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                             Caused by: java.lang.IllegalStateException
                                                                at android.media.MediaCodec.dequeueInputBuffer(Native Method)
                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:542)
                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:485)
                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                at android.os.Looper.loop(Looper.java:137) 
                                                                at android.os.HandlerThread.run(HandlerThread.java:60) 
                                                                at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
02-04 17:37:54.437 4556-4556/ E/TAG: onLoadingChanged: false
02-04 17:37:54.437 4556-4556/ E/TAG: onPlayerStateChanged: 1
```
### Used Exoplayer version - r2.1.1
Another issue I am facing is Exoplayer is not able to load custom layout below 5.0 
app:controller_layout_id resource is not found.

Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class com.google.android.exoplayer2.ui.SimpleExoPlayerView

```
Caused by: java.lang.reflect.InvocationTargetException
                                                                 at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                 at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                 at com.iptv.mylive.ui.activity.PlayerActivity.onCreate(PlayerActivity.java:148) 
                                                                 at android.app.Activity.performCreate(Activity.java:5008) 
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                                 at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                 at android.os.Looper.loop(Looper.java:137) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
`

` Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0200c2
                                                                 at android.content.res.Resources.getValue(Resources.java:1013)
                                                                 at android.support.v7.widget.ResourcesWrapper.getValue(ResourcesWrapper.java:204)
                                                                 at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:332)
                                                             	at android.support.v7.widget.AppCompatDrawableManag
```

Please need help.
Thanks.

**Comment by AquilesCanta** [comment]
These are two completely different issues, aren't they? Please, create one new issue per topic and most important of all:

Read the issue template and provide **all the required information**. Logcats alone are almost always insufficient.
