### ISSUE TITLE
java.lang.IllegalStateExceptionat at android.media.MediaCodec.native_dequeueOutputBuffer - 0x80001000 (OMX_ErrorInsufficientResources)

### ISSUE THREAD

**Issue by kartdroid** [google/ExoPlayer#2436]
- Video Decoder fails and we see no video when playing DASH + Widevine Content (Device Specific Issue)
- Play any DASH +DRM protected  (that is encoded using codecs="avc1.42C028") content  on ASUS_T00J device . 
-  [Sample.txt](https://github.com/google/ExoPlayer/files/765647/Sample.txt) - MPD File
-[AsusZenfone_Bigbangtheory_updated_trimmed.txt](https://github.com/google/ExoPlayer/files/765667/AsusZenfone_Bigbangtheory_updated_trimmed.txt) - Device Log 
- ExoPlayer Version : 1.5.14
- This issue is  specific to a device ASUS_T00J

```
02-09 11:25:28.086   227  9709 I VideoDecoder: updateFormatInfo: current size: 640 x 368, new size: 640 x 368

02-09 11:25:28.086   227  9709 I VideoDecoder: Cropping: left = 0, top = 0, right = 0, bottom = 8

02-09 11:25:28.086   227  9709 I VideoDecoder: actualBufferNeeded =17

02-09 11:25:28.086   227  9709 I VideoDecoder: set colorMatrix: 0x0 

02-09 11:25:28.086   227  9709 I VideoDecoder: set videoRange: 0 

02-09 11:25:28.086   227  9709 I VideoDecoder: No slice available for decoding.

02-09 11:25:28.086   227  9709 I VideoDecoder: Nalu type = 0x9 is skipped

02-09 11:25:28.086   227  9709 E VideoDecoder: Invalid parameter: nalu_data = NULL for naluType 0x7

02-09 11:25:28.086   227  9709 E OMXVideoDecoder: Decoder returned DECODE_MEMORY_FAIL

02-09 11:25:28.086   227  9709 E OMXVideoDecoderAVCSecure: OMXVideoDecoderBase::ProcessorProcess failed. Result: 0x80001000

02-09 11:25:28.086  9098  9464 D VSTB    : EventLoggerManager.attachLocationInfo(757)	Not attaching location because location services disabled in com.quickplay.core.config.exposed.defaultimpl.location.LocationManager@1798364d	(SerialExecutorThreadPool-Thread)

02-09 11:25:28.096  9098  9706 E ACodec  : [OMX.Intel.VideoDecoder.AVC.secure] ERROR(0x80001000)

02-09 11:25:28.096  9098  9706 E ACodec  : signalError(omxError 0x80001000, internalError -2147483648)

02-09 11:25:28.096  9098  9705 E MediaCodec: Codec reported err 0x80001000, actionCode 0, while in state 6

02-09 11:25:28.106  9098  9692 E ExoPlayerImplInternal: Internal runtime error.

02-09 11:25:28.106  9098  9692 E ExoPlayerImplInternal: java.lang.IllegalStateException

02-09 11:25:28.106  9098  9692 E ExoPlayerImplInternal: 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)

02-09 11:25:28.106  9098  9692 E ExoPlayerImplInternal: 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)

02-09 11:25:28.106  9098  9692 E ExoPlayerImplInternal: 	at com.quickplay.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(:922)

02-09 11:25:28.106  9098  9692 E ExoPlayerImplInternal: 	at com.quickplay.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(:528)

02-09 11:25:28.106  9098  9692 E ExoPlayerImplInternal: 	at com.quickplay.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(:128)

02-09 11:25:28.106  9098  9692 E ExoPlayerImplInternal: 	at com.quickplay.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(:432)

02-09 11:25:28.106  9098  9692 E ExoPlayerImplInternal: 	at com.quickplay.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(:211)

02-09 11:25:28.106  9098  9692 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)

02-09 11:25:28.106  9098  9692 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:135)

02-09 11:25:28.106  9098  9692 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)

02-09 11:25:28.106  9098  9692 E ExoPlayerImplInternal: 	at com.quickplay.google.android.exoplayer.util.PriorityHandlerThread.run(:40)
```

I understand that "0x80001000" (OMX_ErrorInsufficientResources) is returned by the decoder  but , we need few inputs from ExoPlayer Team to take the next steps in overcoming this problem .

The reason for this ticket is to understand the following : 
1) Could it be an issue with SurfaceView registration from applicaiton side ?  (as this is related to output buffers)
2) Could this be a content related issue ?
3) Is this an OEM specific issue  ?

Hi Team ,
Please clarify the above so that we can handle it appropriately on application side. 

Thanks !

**Comment by andrewlewis** [comment]
1. I doubt this is related to the output Surface, unless you are doing something non-standard. You could check that the error is reproducible in the ExoPlayer demo app to eliminate this possibility.
2. `E VideoDecoder: Invalid parameter: nalu_data = NULL for naluType 0x7` looks suspicious, as if the decoder is not getting SPS. Can you reproduce the error on other devices playing the same content?
3. It's quite likely so I'll mark this as device-specific for now. Testing on other devices is a good way to check.

There are some DRM-related warnings (`W WVCdm   : CdmEngine::ExtractWidevinePssh: Unable to read PSSH atom size`) but I'm not sure if they're significant. Please provide the output of `adb bugreport` after reproducing the error. The logcat output on its own is not sufficient to investigate this.

**Comment by kartdroid** [comment]
@andrewlewis  no we are not able to reproduce in other devices . Only in the mentioned device we see this error that too for all the contents only audio is rendered . Video decoder fails and goes back to idle state.

**Comment by kartdroid** [comment]
i am getting adb bugreport meanwhile

**Comment by andrewlewis** [comment]
Can you reproduce this error when playing the Widevine samples in the demo app? If so, please take the bug report after playing one of those. Thanks!

**Comment by kartdroid** [comment]
ok iam on it :+1:

**Comment by kartdroid** [comment]
Attaching ADB Device Logs + ADB Bugreport from our application


[our_app_adb_bugreport1.txt](https://github.com/google/ExoPlayer/files/766711/our_app_adb_bugreport1.txt)
[our_app_adb_device_log1.txt](https://github.com/google/ExoPlayer/files/766712/our_app_adb_device_log1.txt)

**Comment by kartdroid** [comment]
Attaching Demo App ADB Device Logs + ADB Bug report 

[demo_app_adb_bugreport.txt](https://github.com/google/ExoPlayer/files/766716/demo_app_adb_bugreport.txt)
[demo_app_adb_device_logs.txt](https://github.com/google/ExoPlayer/files/766717/demo_app_adb_device_logs.txt)


@andrewlewis  I have attached both the logs for reference .

However the Stack Trace looks different when playing our content vs Demo Content.

**Comment by kartdroid** [comment]
Observations so far : 
1) The Demo app fails because of a crypto exception whereas , our app fails because of a Decoder exception (failing to find NAL unit)
2) Our app is able to render audio (which means there was no problem in descrambling ? )
Are we missing any step in our application that could identify a DRM error ? 

Kindly help us to identify the difference . Thanks !

**Comment by ojw28** [comment]
@wvpaf - Could you take a look at the second bug report / device logs provided above. Specifically, this:

```
02-10 16:29:55.130 12839 12868 I WVCdm   : CdmEngine::OpenSession
02-10 16:29:55.130 12839 12868 I WVCdm   : Level3 Library May 16 2014 23:14:03
02-10 16:29:55.130 12839 12868 W WVCdm   : Could not read /data/mediadrm/IDM1013/ay64.dat2: No such file or directory
02-10 16:29:55.170 12839 12868 E DRM-LibSEP: resultlen = 112.
02-10 16:29:55.170 12839 12868 E DRM-LibSEP: wKeyDataSize = 72.
02-10 16:29:55.170 12839 12868 E DRM-LibSEP: wDeviceIDSize = 32.
02-10 16:29:55.170 12839 12868 E DRM-LibSEP: drm_wv_mod_load_usage_table():45: DEBUG - usage_table_data is NULL, retrieving expected size from FW.
02-10 16:29:55.170 12839 12868 D WVCdm   : OEMCrypto_Initialize Level 1 success. I will use level 1.
02-10 16:29:55.190 12839 12868 I WVCdm   : CdmEngine::QueryKeyControlInfo
02-10 16:29:55.200 12839 12868 W WVCdm   : BufferReader::Read<T> : Failure during parse: Not enough bytes (4)
02-10 16:29:55.200 12839 12868 W WVCdm   : CdmEngine::ExtractWidevinePssh: Unable to read PSSH atom size
02-10 16:29:55.200 12839 12868 W WVCdm   : BufferReader::Read<T> : Failure during parse: Not enough bytes (4)
02-10 16:29:55.200 12839 12868 W WVCdm   : CdmEngine::ExtractWidevinePssh: Unable to read PSSH atom size
02-10 16:29:55.200 12839 12868 I WVCdm   : CdmEngine::GenerateKeyRequest
02-10 16:29:55.210 12839 12868 D WVCdm   : PrepareKeyRequest: nonce=450873380
02-10 16:29:55.490 13362 13532 I OMXClient: Using client-side OMX mux.
02-10 16:29:55.500 12839 12869 E wrs-omxil-core: OMX_GetHandle(): exit failure, OMX.Intel.aac.decoder not found
02-10 16:29:55.500 12839 12869 W linker  : libstagefright_soft_aacdec_mdp.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
02-10 16:29:55.500 12839 12869 I MDP_OMX_CORE: Created OMXPlugin : OMX.Intel.aac.decoder
02-10 16:29:55.510 12839 12867 E OMXNodeInstance: setParameter(1866465283) ERROR: 0x8000101a
02-10 16:29:55.530 13362 13362 D EventLogger: audioDecoderInitialized [2.61, OMX.Intel.aac.decoder]
02-10 16:29:55.530 12839 12869 E DRM-LibSEP: drm_wv_mod_start_playback():6444: ERROR - Chaabi returned error value of 0x35.
02-10 16:29:55.530 12839 12869 E MDRMSession: DecryptCTR failed: DRM_WV_MOD_ERROR_MEMORY_NOT_ALLOCATED (0x35)
02-10 16:29:55.530 12839 12869 E WVCdm   : Decrypt error result in session sid2 during unencrypted block: 1
02-10 16:29:55.530 13362 13532 E MediaCodec: queueCSDInputBuffer failed w/ error -2998
02-10 16:29:55.530 13362 13362 D EventLogger: audioFormatChanged [2.61, id=0, mimeType=audio/mp4a-latm, bitrate=134359, channels=2, sample_rate=44100, language=eng]
02-10 16:29:55.530 13362 13453 E ExoPlayerImplInternal: Internal runtime error.
02-10 16:29:55.530 13362 13453 E ExoPlayerImplInternal: android.media.MediaCodec$CryptoException: Unknown Error
02-10 16:29:55.530 13362 13453 E ExoPlayerImplInternal: 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
02-10 16:29:55.530 13362 13453 E ExoPlayerImplInternal: 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
02-10 16:29:55.530 13362 13453 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:868)
02-10 16:29:55.530 13362 13453 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:489)
02-10 16:29:55.530 13362 13453 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464)
02-10 16:29:55.530 13362 13453 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
02-10 16:29:55.530 13362 13453 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
02-10 16:29:55.530 13362 13453 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:135)
02-10 16:29:55.530 13362 13453 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-10 16:29:55.530 13362 13453 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by kartdroid** [comment]
@ojw28 @wvpaf any updates for this issue ?  we are planning to have a fallback logic (to another software drm/decoder combo) based  on your inputs.  kindly advice

**Comment by venkataramanab** [comment]
This crash appeared in demo app too
Device: Google Nexus 4
Android version: 4.2.2
Android api version: 17
This crash appears on clicking Big Buck Bunny video in MISC section
```
com.google.android.exoplayer2.demo D/EventLogger: audioDecoderInitialized [1.07, OMX.google.aac.decoder]
com.google.android.exoplayer2.demo D/EventLogger: audioFormatChanged [1.07, id=2, mimeType=audio/mp4a-latm, channels=2, sample_rate=44100, language=und]
com.google.android.exoplayer2.demo E/SoftAVC: Decoder failed: -2
com.google.android.exoplayer2.demo E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
com.google.android.exoplayer2.demo E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -2147483648)
com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                            java.lang.IllegalStateException
                                                                at android.media.MediaCodec.dequeueInputBuffer(Native Method)
                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:548)
                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:490)
                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464)
                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:137)
                                                                at android.os.HandlerThread.run(HandlerThread.java:60)
                                                                at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
com.google.android.exoplayer2.demo E/EventLogger: playerFailed [1.08]
                                                  com.google.android.exoplayer2.ExoPlaybackException
                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                      at android.os.Looper.loop(Looper.java:137)
                                                      at android.os.HandlerThread.run(HandlerThread.java:60)
                                                      at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                   Caused by: java.lang.IllegalStateException
                                                      at android.media.MediaCodec.dequeueInputBuffer(Native Method)
                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:548)
                                                      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:490)
                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464)
                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                      at android.os.Looper.loop(Looper.java:137) 
                                                      at android.os.HandlerThread.run(HandlerThread.java:60) 
                                                      at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
com.google.android.exoplayer2.demo D/EventLogger: videoDisabled [1.08]
com.google.android.exoplayer2.demo D/EventLogger: audioDisabled [1.08]
com.google.android.exoplayer2.demo D/EventLogger: loading [false]
com.google.android.exoplayer2.demo D/EventLogger: state [1.08, true, I]
```

**Comment by wvpaf** [comment]
venkataramanab@ I think your issue is content related so not the same root cause.

ckarthickit@ the issue you are reported is with the SoC we will need to forward this data to Intel.

**Comment by kartdroid** [comment]
@wvpaf  thanks ! let us know once u hear back from Intel

**Comment by kartdroid** [comment]
sorry closed by mistake

**Comment by wvpaf** [comment]
Hi,
The OEMs, Asus and Intel investigated and agree this is an issue, however the chip is aged enough they are not planning any updates to this device platform.
