### ISSUE TITLE
HLS 302 Issue

### ISSUE THREAD

**Issue by tapankumar** [google/ExoPlayer#2470]
I am using Wowza Dyanamic Load Balancer and unable to play below HLS urls which gives 302.

It works well with VLC, Native Android and older version of EXO 1.5.7.

http://digilb.nexg.tv/redirect/live/aajtak.smil?scheme=m3u8&sf=net
and 
http://digilb.nexg.tv/redirect/live/amlst:aajtak?scheme=m3u8&sf=net&network=wifi

It throws below error in latest version of EXO.

02-18 11:38:25.878 29680-29680/com.google.android.exoplayer2.demo E/EventLogger: internalError [0.21, loadError]
                                                                                 com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:705)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:628)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
02-18 11:38:25.878 29680-29984/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Source error.
                                                                                           com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                               at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:705)
                                                                                               at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:628)
                                                                                               at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                               at java.lang.Thread.run(Thread.java:818)
02-18 11:38:25.880 29680-29680/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [0.21]
                                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:345)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                     at android.os.Looper.loop(Looper.java:207)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                  Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:705)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:628)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by andrewlewis** [comment]
Prepare the player with an `HlsMediaSource` to play an HLS stream. It looks like you're using `ExtractorMediaSource` at the moment.

**Comment by tapankumar** [comment]
Thanks.
I saw the code and you were right.

Here is my entry in media.exolist.json now

{
        "name": "Digivive LB with AMLST",
        "uri": "http://digilb.nexg.tv/redirect/live/amlst:aajtak?scheme=m3u8&sf=net&network=wifi",
        "extension": "m3u8"
      }

Here is the code from PlayerActivity which leads me to the right directions.

private MediaSource buildMediaSource(Uri uri, String overrideExtension) {
    int type = Util.inferContentType(!TextUtils.isEmpty(overrideExtension) ? "." + overrideExtension
        : uri.getLastPathSegment());
      //Log.d("Tapan",Integer.toString(type));
