### ISSUE TITLE
Subtitle usage sample

### ISSUE THREAD

**Issue by eseffair** [google/ExoPlayer#2471]
Can anyone provide a complete and functional example of how to load subtitles, and srt subtitles are supported?

**Comment by andrewlewis** [comment]
Does #2017 help?

**Comment by eseffair** [comment]
Hi @andrewlewis, I'm doing exactly that way, but I always get this exception...

```
java.lang.NullPointerException: Attempt to invoke interface method 'com.google.android.exoplayer2.upstream.DataSource com.google.android.exoplayer2.upstream.DataSource$Factory.createDataSource()' on a null object reference
                                                                                      at com.google.android.exoplayer2.source.SingleSampleMediaPeriod.continueLoading(SingleSampleMediaPeriod.java:119)
                                                                                      at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:55)
                                                                                      at com.google.android.exoplayer2.source.MergingMediaPeriod.continueLoading(MergingMediaPeriod.java:133)
                                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1299)
                                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1276)
                                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:316)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                      at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by andrewlewis** [comment]
It looks like the `DataSourceFactory` you're passing to `SingleSampleMediaSource` is null. Please share the code you're using to construct the `MediaSource`s.

**Comment by eseffair** [comment]
Hi @andrewlewis, thank you, I realized my mistake.
