### ISSUE TITLE
DASH live stream crashes player the same this issue : https://github.com/google/ExoPlayer/issues/1364

### ISSUE THREAD

**Issue by kinhdang** [google/ExoPlayer#2480]
Dear all !

We use ExoPlayer 1.5 with Dash stream, and sometime crash player with follow message: 
```
_java.lang.NullPointerException: Attempt to read from field 'java.util.HashMap com.google.android.exoplayer.dash.DashChunkSource$PeriodHolder.representationHolders' on a null object reference at com.google.android.exoplayer.dash.DashChunkSource.getChunkOperation(DashChunkSource.java:455)
at com.google.android.exoplayer.chunk.ChunkSampleSource.doChunkOperation(ChunkSampleSource.java:561) at com.google.android.exoplayer.chunk.ChunkSampleSource.updateLoadControl(ChunkSampleSource.java:435) at com.google.android.exoplayer.chunk.ChunkSampleSource.onLoadCompleted(ChunkSampleSource.java:361) at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.os.HandlerThread.run(HandlerThread.java:61)
at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)_
```

This issue already opened in https://github.com/google/ExoPlayer/issues/1364, but we do not seen any idea fix, so we re-open.
Anybody knows, please give idea solution how to fix this issue. 

Thanks.

**Comment by ojw28** [comment]
Most likely you're playing a multi-period DASH stream where the formats change going from one period to the next. You need to use V2 or above to play this type of stream.

It's not possible for us to diagnose further, since you've not provided most of the information we request in the issue template.
