### ISSUE TITLE
ExoPlayer 2.2.0 - Audio streaming stops after ~5 minutes  Nexus 5x 7.1.1

### ISSUE THREAD

**Issue by bratislavdamnjanovic** [google/ExoPlayer#2482]
Hi everyone. 

I saw discussions earlier on this subject, but couldn't find the solution.
The problem is similar - audio streaming stops after ~5 minutes when the device is in the sleep mode. The mobile device is not used in those 5 minutes.
Everything is working fine with Samsung Alpha, Samsung S5, LG G4, Alcatel One Touch Pop.
It looks like the problem is device specific - Nexus 5x?

The main reason I've switched to the ExoPlayer is that the MediaPlayer also stops permanently after ~5 minutes.

Currently ExoPlayer has mechanism that resumes the streaming when the device is no longer in the sleep state e.g. some button is clicked or Usb cable is plugged in. But that just happen when the waking the device is triggered in less than 1-2 minutes. 
After 5 more minutes waiting in the silence, I get the error:

```
02-21 14:26:48.186 19569-19608/app.krs.streamradiosolution.com.radiokrs E/ExoPlayerImplInternal: Source error.
                                                                                                 com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://radioservis.me:8030/live
                                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:195)
                                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:623)
                                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                                     at java.lang.Thread.run(Thread.java:761)
                                                                                                  Caused by: java.net.SocketTimeoutException: connect timed out
                                                                                                     at java.net.PlainSocketImpl.socketConnect(Native Method)
                                                                                                     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
                                                                                                     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
                                                                                                     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
                                                                                                     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
                                                                                                     at java.net.Socket.connect(Socket.java:605)
                                                                                                     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
                                                                                                     at com.android.okhttp.Connection.connectSocket(Connection.java:196)
                                                                                                     at com.android.okhttp.Connection.connect(Connection.java:172)
                                                                                                     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
                                                                                                     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
                                                                                                     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
                                                                                                     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
                                                                                                     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
                                                                                                     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
                                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:427)
                                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:357)
                                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193)
                                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:623) 
                                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
                                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                                     at java.lang.Thread.run(Thread.java:761) 
```

Thanks for any help!

**Comment by andrewlewis** [comment]
Please see #930 and #2276.
