### ISSUE TITLE
LoadTask: Unexpected exception loading stream

### ISSUE THREAD

**Issue by Merseyside** [google/ExoPlayer#2486]
Hello! I trying to play a mp3 file and it throws an exception below. I checked it with mp3 validator, its ok. AudioTrack class plays it well! Send mp3 file on your mail dev.exoplayer@gmail.com

```
java.lang.IllegalArgumentException
    at java.util.Arrays.copyOfRange(Arrays.java:2663)
    at com.google.android.exoplayer2.metadata.id3.Id3Decoder.decodePrivFrame(Id3Decoder.java:414)
    at com.google.android.exoplayer2.metadata.id3.Id3Decoder.decodeFrame(Id3Decoder.java:293)
    at com.google.android.exoplayer2.metadata.id3.Id3Decoder.decode(Id3Decoder.java:96)
    at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.peekId3Data(Mp3Extractor.java:287)
    at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.synchronize(Mp3Extractor.java:209)
    at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.sniff(Mp3Extractor.java:115)
    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:693)
    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:628)
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)    
```

**Comment by ojw28** [comment]
The mp3 file contains malformed ID3 data. Uploading it to http://tagmp3.net, making no changes and downloading the result removes the malformed ID3 data and results in a playable file.

That said, we'll make a change to handle (by ignoring) this type of malformed data, since it's trivial for us to do so.
