### ISSUE TITLE
While Playing video from internal storage in Exoplayer 2.0.4 it throws $FileDataSourceException: java.io.EOFException`

### ISSUE THREAD

**Issue by newandroidboy88** [google/ExoPlayer#2492]
While playing the internal Storage Video in Exoplayer 2.0.4
Video File was present in the InternalStorage but it throws error
```
com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.EOFException
                                                                       at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:70)
                                                                       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:596)
                                                                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                    Caused by: java.io.EOFException
                                                                       at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:67)at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:596) at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)  at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) at java.lang.Thread.run(Thread.java:818) 
```

**Comment by AquilesCanta** [comment]
See #2491.

**Comment by ojw28** [comment]
Closing due to lack of required information. Please provide proper reproduction steps and test media if you want us to take a look.
