### ISSUE TITLE
Exoplayer throws NullPointer Exception on streaming HLS sources in some devices! 

### ISSUE THREAD

**Issue by kanagalingam** [google/ExoPlayer#2493]
**Description:**
.m3u8 files (HLS) are not being played in some devices. Can't able to figure out the reason on why the video is not streamed on some devices! Logcat registers `NULLPOINTER EXCEPTION`
**VERSION OF EXOPLAYER USED:** 
Exoplayer version 2.0.4
**DEVICE ON WHICH ISSUE HAPPENS:**
Nexus7(Android 6), Samsung Note III.

**LOGCAT DURING THE ISSUE:**

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.google.android.exoplayer2.source.CompositeSequenceableLoader.getNextLoadPositionUs()' on a null object reference at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.getNextLoadPositionUs(HlsMediaPeriod.java:216) at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1080) at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1076) at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:289) at android.os.Handler.dispatchMessage(Handler.java:98)  at android.os.Looper.loop(Looper.java:148)at android.os.HandlerThread.run(HandlerThread.java:61)
at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1080)
                                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1076)
                                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:289)
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by AquilesCanta** [comment]
Are there devices where this issue does not reproduce? This would be strange for a NPE.

Please provide a stream to reproduce the issue.

**Comment by ojw28** [comment]
Closing due to inactivity.
