### ISSUE TITLE
Exoplayer not able play  .flv 

### ISSUE THREAD

**Issue by manishvwynk** [google/ExoPlayer#2499]
Exoplayer  not able  to play the the following .flv file  url :

 https://gcdn.2mdn.net/videoplayback/id/47e425d42c663115/itag/5/source/doubleclick_dmm/ratebypass/yes/ip/0.0.0.0/ipbits/0/expire/3630481824/sparams/id,itag,source,ratebypass,ip,ipbits,expire/signature/7C35723E638C5DBAD852C182970BD4E4FDE6E577.1EF904C82963E11E62A5881E3B381B6C868D32D4/key/ck2/file/file.flv

version of Exoplayer :2.0

video format : Sorenson Spark
audio format: MP3

Android version: 6

As android doesn't support Sorenson Spark for video I was assuming that atleast the audio should play.But we are getting below exception while playing the file

For similar file some time exoplayer crash, crash log of exoplayer as 

```
/EventLogger: internalError [1.83, loadError]
                                                                  com.google.android.exoplayer2.extractor.flv.TagPayloadReader$UnsupportedFormatException: Video format not supported: 2
                                                                      at com.google.android.exoplayer2.extractor.flv.VideoTagPayloadReader.parseHeader(VideoTagPayloadReader.java:73)
                                                                      at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:64)
                                                                      at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:253)
                                                                      at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:158)
                                                                      at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:609)
                                                                      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)
02-23 13:01:21.453 9560-24788/tv.accedo.airtel.wynk W/com.newrelic.agent.android: setBytesReceived(...) called on TransactionState in COMPLETE state
02-23 13:01:21.453 9560-24788/tv.accedo.airtel.wynk W/com.newrelic.agent.android: setStatusCode(...) called on TransactionState in COMPLETE state
02-23 13:01:21.717 9560-9560/tv.accedo.airtel.wynk E/EventLogger: internalError [2.22, loadError]
                                                                  com.google.android.exoplayer2.extractor.flv.TagPayloadReader$UnsupportedFormatException: Video format not supported: 0
                                                                      at com.google.android.exoplayer2.extractor.flv.VideoTagPayloadReader.parseHeader(VideoTagPayloadReader.java:73)
                                                                      at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:64)
                                                                      at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:253)
                                                                      at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:158)
                                                                      at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:609)
                                                                      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)
02-23 13:01:21.764 9560-24788/tv.accedo.airtel.wynk W/com.newrelic.agent.android: setBytesReceived(...) called on TransactionState in COMPLETE state
02-23 13:01:21.764 9560-24788/tv.accedo.airtel.wynk W/com.newrelic.agent.android: setStatusCode(...) called on TransactionState in COMPLETE state
02-23 13:01:23.201 9560-9560/tv.accedo.airtel.wynk E/EventLogger: internalError [3.71, loadError]
                                                                  com.google.android.exoplayer2.extractor.flv.TagPayloadReader$UnsupportedFormatException: Video format not supported: 11
                                                                      at com.google.android.exoplayer2.extractor.flv.VideoTagPayloadReader.parseHeader(VideoTagPayloadReader.java:73)
                                                                      at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:64)
                                                                      at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:253)
                                                                      at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:158)
                                                                      at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:609)
                                                                      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)
02-23 13:01:25.857 9560-9603/tv.accedo.airtel.wynk E/VC5: NATIVE_WINDOW_MIN_UNDEQUEUED_BUFFERS = 1
02-23 13:01:25.918 9560-9560/tv.accedo.airtel.wynk E/EventLogger: internalError [6.43, loadError]
                                                                  com.google.android.exoplayer2.extractor.flv.TagPayloadReader$UnsupportedFormatException: Video format not supported: 15
                                                                      at com.google.android.exoplayer2.extractor.flv.VideoTagPayloadReader.parseHeader(VideoTagPayloadReader.java:73)
                                                                      at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:64)
                                                                      at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:253)
                                                                      at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:158)
                                                                      at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:609)
                                                                      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)
02-23 13:01:25.923 9560-24861/tv.accedo.airtel.wynk E/ExoPlayerImplInternal: Source error.
                                                                             com.google.android.exoplayer2.extractor.flv.TagPayloadReader$UnsupportedFormatException: Video format not supported: 15
                                                                                 at com.google.android.exoplayer2.extractor.flv.VideoTagPayloadReader.parseHeader(VideoTagPayloadReader.java:73)
                                                                                 at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:64)
                                                                                 at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:253)
                                                                                 at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:158)
                                                                                 at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:609)
                                                                                 at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                 at java.lang.Thread.run(Thread.java:818)
02-23 13:01:25.924 9560-9560/tv.accedo.airtel.wynk D/EXO_PLAYER : EF: ExoPlayer onPlayerError Error : com.google.android.exoplayer2.ExoPlaybackException
02-23 13:01:25.925 9560-9560/tv.accedo.airtel.wynk E/EventLogger: playerFailed [6.43]
                                                                  com.google.android.exoplayer2.ExoPlaybackException
                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:310)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                      at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                   Caused by: com.google.android.exoplayer2.extractor.flv.TagPayloadReader$UnsupportedFormatException: Video format not supported: 15
                                                                      at com.google.android.exoplayer2.extractor.flv.VideoTagPayloadReader.parseHeader(VideoTagPayloadReader.java:73)
                                                                      at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:64)
                                                                      at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:253)
                                                                      at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:158)
                                                                      at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:609)
                                                                      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)
```

**Comment by ojw28** [comment]
We only support aac audio and h264 video in the flv container. We have no plan on expanding this support, since there's very little demand for it. We would accept high quality pull requests adding support for additional formats within flv, but will not be able to spend time providing guidance on how to implement it; you'd have to be sufficiently motivated to figure it out for yourself ;). Sorry!
