### ISSUE TITLE
play without sound and just for mpd format

### ISSUE THREAD

**Issue by gh-darvishani** [google/ExoPlayer#2505]
Hi
this is my code for create video player into dialog 
but this video player don't load mp4 format 
what is wrong on my code ?
`
public class VideoPlayer
{

    //            private static final String VIDEO_URI =
//                    "http://hadafapp.com/up/1487449143video_2017-01-29_23-54-45.mov";
    private     String VIDEO_URI =
            "http://www-itec.uni-klu.ac.at/ftp/datasets/DASHDataset2014/BigBuckBunny/4sec/BigBuckBunny_4s_onDemand_2014_05_09.mpd";

    private SimpleExoPlayer player;
    private SimpleExoPlayerView simpleExoPlayerView;
    private Handler mainHandler;
    private TrackSelection.Factory videoTrackSelectionFactory;
    private TrackSelector trackSelector;
    private LoadControl loadControl;
    private DataSource.Factory dataSourceFactory;
    private MediaSource videoSource;
    private Uri uri;
    private String userAgent;
    private static final DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();

        public VideoPlayer(String VIDEO_URI) {
        this.VIDEO_URI=VIDEO_URI;
        Dialog dialog=new Dialog(BaseActivity.activity,android.R.style.Theme_Black_NoTitleBar_Fullscreen);
        dialog.setContentView(R.layout.video_player);

         simpleExoPlayerView = (SimpleExoPlayerView) dialog.findViewById(R.id.dialog_player);
        userAgent = Util.getUserAgent(BaseActivity.activity,"SimpleDashExoPlayer");
        createPlayer();
        attachPlayerView();
        preparePlayer();

            dialog.show();

            final int BUFFER_SEGMENT_SIZE = 64 * 1024;
             final int BUFFER_SEGMENT_COUNT = 256;
             final int RENDERER_COUNT = 3;

    }

    // Create TrackSelection Factory, Track Selector, Handler, Load Control, and ExoPlayer Instance
    public void createPlayer(){
        mainHandler = new Handler();
        videoTrackSelectionFactory = new AdaptiveVideoTrackSelection.Factory(bandwidthMeter);
        trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
        loadControl = new DefaultLoadControl();
        player = ExoPlayerFactory.newSimpleInstance(BaseActivity.activity,trackSelector,loadControl);
    }

    // Set player to SimpleExoPlayerView
    public void attachPlayerView(){
        simpleExoPlayerView.setPlayer(player);
    }

    // Build Data Source Factory, Dash Media Source, and Prepare player using videoSource
    public void preparePlayer(){
        uriParse();
        dataSourceFactory = buildDataSourceFactory(bandwidthMeter);
        videoSource = new DashMediaSource(uri,buildDataSourceFactory(null),new DefaultDashChunkSource.Factory(dataSourceFactory),mainHandler,null);
        player.prepare(videoSource);
    }

    // Parse VIDEO_URI and Save at uri variable
    public void uriParse(){
        uri = Uri.parse(VIDEO_URI);
    }

    // Build Data Source Factory using DefaultBandwidthMeter and HttpDataSource.Factory
    private DataSource.Factory buildDataSourceFactory(DefaultBandwidthMeter bandwidthMeter){
        return new DefaultDataSourceFactory(BaseActivity.activity, bandwidthMeter, buildHttpDataSourceFactory(bandwidthMeter));
    }

    // Build Http Data Source Factory using DefaultBandwidthMeter
    private HttpDataSource.Factory buildHttpDataSourceFactory(DefaultBandwidthMeter bandwidthMeter){
        return new DefaultHttpDataSourceFactory(userAgent, bandwidthMeter);
    }

    // Activity onStop, player must be release because of memory saving
     public void onStop(){
         player.release();
    }

}
`

**Comment by ojw28** [comment]
The stream you link to doesn't contain any audio, so this is working as intended.

**Comment by gh-darvishani** [comment]
this link is a sample link and i use this file
`clips.vorwaerts-gmbh.de/big_buck_bunny.mp4`
when i open this link by my code just show a black page without time 
![photo_2017-02-27_00-24-48](https://cloud.githubusercontent.com/assets/5849044/23343587/3312e418-fc83-11e6-8dd0-42f5e2bc172e.jpg)

**Comment by ojw28** [comment]
That's a completely separate issue than the one originally reported here. The most recent link you've provided works fine for me. Note that you need a `http://` prefix (i.e. you should be using `http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4`, not just `clips.vorwaerts-gmbh.de/big_buck_bunny.mp4`).

If you're still having issues, please file an issue that includes all of the information requested in the issue template (in particular, a full bug report captured with `adb bugreport`). Else we do not have sufficient information to investigate the problem.

**Comment by gh-darvishani** [comment]
this is logcat
` D/AwWebContentsDelegateAdapter: onUploadBlockedAds num = 0
02-27 23:12:36.404 30152-30152/hadafapp.chalaksoft.com.hadaf V/AudioManager: playSoundEffect   effectType: 0
02-27 23:12:36.404 30152-30152/hadafapp.chalaksoft.com.hadaf V/AudioManager: querySoundEffectsEnabled...
02-27 23:12:36.404 30152-30152/hadafapp.chalaksoft.com.hadaf I/log: played:http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
02-27 23:12:36.604 30152-30152/hadafapp.chalaksoft.com.hadaf I/ExoPlayerImpl: Init 2.1.1 [hwSCL-Q, HUAWEI SCL-L21, HUAWEI, 22]
02-27 23:12:36.634 30152-30152/hadafapp.chalaksoft.com.hadaf I/ViewRootImpl: CPU Rendering VSync enable = false
02-27 23:12:36.644 30152-30152/hadafapp.chalaksoft.com.hadaf I/View: ssignParent(ViewParent parent) parent is: android.view.ViewRootImpl@2de7f761\`

and i see this log 
`

02-27 23:12:37.714 30152-31070/hadafapp.chalaksoft.com.hadaf I/System.out: close [socket][/0.0.0.0:51894]
02-27 23:12:37.714 30152-31070/hadafapp.chalaksoft.com.hadaf I/System.out: close [socket][/0.0.0.0:51894]
02-27 23:12:37.714 30152-31069/hadafapp.chalaksoft.com.hadaf E/ExoPlayerImplInternal: Source error.
                                                                                      com.google.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ������ftypmp42������...@1:305 in java.io.InputStreamReader@32e747) 
                                                                                          at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:101)
                                                                                          at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:54)
                                                                                          at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114)
                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                          at java.lang.Thread.run(Thread.java:831)
                                                                                       Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ������ftypmp42������...@1:305 in java.io.InputStreamReader@32e747) 
                                                                                          at org.kxml2.io.KXmlParser.next(KXmlParser.java:432)
                                                                                          at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
                                                                                          at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:94)
                                                                                          at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:54) 
                                                                                          at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114) 
                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                          at java.lang.Thread.run(Thread.java:831) 
02-27 23:12:44.424 30152-30152/hadafapp.chalaksoft.com.hadaf V/AudioManager: playSoundEffect   effectType: 0
02-27 23:12:44.424 30152-30152/hadafapp.chalaksoft.com.hadaf V/AudioManager: querySoundEffectsEnabled...
`

can you tell me what is wrong
