### ISSUE TITLE
Play less than 1 minutes live HlsMediaSource error

### ISSUE THREAD

**Issue by yangchaojiang** [google/ExoPlayer#2519]
/ExoPlayerImplInternal: Source error.
                                                                                     com.google.android.exoplayer2.source.BehindLiveWindowException
                                                                                         at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:232)
                                                                                         at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:340)
                                                                                         at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:55)
                                                                                         at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading(HlsMediaPeriod.java:194)
                                                                                         at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1299)
                                                                                         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1284)
                                                                                         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:324)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                         at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by AquilesCanta** [comment]
Please, see #1782.
