### ISSUE TITLE
OMX amlogic avc decoder error when playing HD content

### ISSUE THREAD

**Issue by casajavi** [google/ExoPlayer#2524]
Hello,

I have recently encountered a Widevine secured playback issue with the AMLogic MXQpro set top box running Android 6.0.0 and other similar set top boxes.

When the playback reaches 1080p or above quality on a Widevine secured asset it will throw this error:

```
03-02 15:11:58.283 9093-9265/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Renderer error.
                                                                                         com.google.android.exoplayer2.ExoPlaybackException
                                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:682)
                                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:490)
                                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464)
                                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                             at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                          Caused by: android.media.MediaCodec$CryptoException: Unknown Error
                                                                                             at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                             at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2292)
                                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:673)
                                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:490) 
                                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464) 
                                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                                             at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                             at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
03-02 15:11:58.290 9093-9093/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [14.07]
                                                                               com.google.android.exoplayer2.ExoPlaybackException
                                                                                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:682)
                                                                                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:490)
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464)
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                Caused by: android.media.MediaCodec$CryptoException: Unknown Error
                                                                                   at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                   at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2292)
                                                                                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:673)
                                                                                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:490) 
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464) 
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

This was tested using the Exoplayer 2.0 Demo (version r2.2.0) and using one of my assets as well as the WV: Secure HD (MP4,H265) and WV: Secure UHD (MP4,H265) test assets. This only happens with Secure assets. 

I cannot reproduce the issue using the a similar box with the same video decoder (OMX.amlogic.avc.decoder.awesome) on Android 4.4.2

I also can't reproduce this using Exoplayer 1.0.

I have attached a bug report of the issue. Any help would be highly appreciated.

Thanks!

[bugreport.txt](https://github.com/google/ExoPlayer/files/814469/bugreport.txt)

**Comment by ojw28** [comment]
Just to confirm, the claim here is that the same assets play correctly on the affected devices using ExoPlayer V1 (and that ExoPlayer V1 does switch up into the affected resolutions)? That sounds strange. I think our usage of the decoders and MediaDrm are essentially the same going from V1 to V2.

Are your assets H264 or HEVC? You mention HEVC assets in the demo app, but you also mention the H264 decoder on these devices. Please clarify. Thanks!

**Comment by casajavi** [comment]
Sorry for the very late reply....

So I verified on the ExoPlayer V1, the player does not ever switch up to the affected resolutions thats why I never saw the issue on that player.

Sorry for the confusion about the assets, let me clarify.
First I tested an asset from our end and that asset is H264, afterwards I tested with these Exoplayer v2 demo asset: **WV: Secure HD (MP4,H264) / WV: Secure UHD (MP4,H264)**. 

All of these assets cause the player to fail when switching to HD resolutions and all of these assets including mine are secured with widevine. 

The **WV: Clear HD (MP4,H264) / WV: Clear UHD (MP4,H264)** do work on this device and the player switches up to the highest resolution. 

I have tried with other devices and I cannot reproduce this problem.

**Comment by peyoh** [comment]
HI,
do you have WV CENC support enabled on the device? 
Just check it with "DRM info" package.

https://play.google.com/store/apps/details?id=com.androidfung.drminfo

**Comment by wvpaf** [comment]
Hi,
I looks like this issue was addressed in N. Can you update the device and retest?
Thanks.

**Comment by ojw28** [comment]
Closing on the assumption that the issue was fixed in N.
