### ISSUE TITLE
Failed to play

### ISSUE THREAD

**Issue by wanghc0** [google/ExoPlayer#2556]
Description:
I gave MediaSource a false url, like "http://cdn-media.jingzong.org/mp4/001.mp4 " , then, ExoPlayer returned an error : Source error.  After receiving this Error Msg, I released player,  and changed the url as "http://hls.ciguang.tv/hdtv/video.m3u8", which is a nice hls video source. Then, restart player.  But, it failed to play.  

When I replace "http://hls.ciguang.tv/hdtv/video.m3u8" as "http://cdn-media.jingzong.org/mp4/02/02-041/02-041-0001.mp4 ", it plays normal. But Still will send this Error Msg:
```
EventLogger: playerFailed [4.02]
                                                               com.google.android.exoplayer2.ExoPlaybackException
                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:360)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
                                                                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:618)
                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                   at java.lang.Thread.run(Thread.java:818)
```

Thanks.

---------------------

     The following are the logs:

---------------------

```W/ExoPlayerImplInternal: Ignoring messages sent after release.

EventLogger: internalError [18.00, loadError]
                                                               com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
                                                                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:618)
                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                   at java.lang.Thread.run(Thread.java:818)
```

----------------------

```
EventLogger: internalError [18.08, loadError]
                                                               com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
                                                                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:618)
                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                   at java.lang.Thread.run(Thread.java:818)
```

-----------------------

```
EventLogger: internalError [18.08, loadError]
                                                               com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
                                                                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:618)
                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                   at java.lang.Thread.run(Thread.java:818)
```

-----------------------

```
EventLogger: internalError [19.18, loadError]
                                                               com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
                                                                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:618)
                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                   at java.lang.Thread.run(Thread.java:818)
```

----------------------

```
internalError [21.27, loadError]
                                                               com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
                                                                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:618)
                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                   at java.lang.Thread.run(Thread.java:818)
```

-----------------------

```
ExoPlayerImplInternal: Source error.
                                                                         com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
                                                                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                             at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:618)
                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)
```

-----------------------

```
ExoPlayer ImplInternal: Ignoring messages sent after release.
```

---------------------
```
EventLogger: playerFailed [8.02]
                                                             com.google.android.exoplayer2.ExoPlaybackException
                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:360)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                 at android.os.Looper.loop(Looper.java:207)
                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                 at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                              Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
                                                                 at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                 at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                 at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:618)
                                                                 at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                 at java.lang.Thread.run(Thread.java:818)
```

**Comment by ojw28** [comment]
It's quite unclear what this issue is describing, but this sounds wrong:

> I released player, and changed the url as "http://hls.ciguang.tv/hdtv/video.m3u8", which is a nice hls video source.

As per the documentation for [release](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ExoPlayer.html#release--), the player must not be used after calling it. If you want to re-use the player instance you should just call `prepare` again with the new source. Call `release` only when you're completely done with the instance.

> When I replace "http://hls.ciguang.tv/hdtv/video.m3u8" as "http://cdn-media.jingzong.org/mp4/02/02-041/02-041-0001.mp4 ", it plays normal. But Still will send this Error Msg:

404 errors indicate some variants/segments declared in the HLS manifest/playlist are missing on the server. This is a content issue.
