### ISSUE TITLE
ExoPlayerImplInternal: Renderer error when creating more than 15 files

### ISSUE THREAD

**Issue by mcaquet** [google/ExoPlayer#2585]
Hello

I am using the ExoPlayer 2 to play a local audio files. My app builds several instances of SimpleExoPlayer, some of them are not working and I see the following exceptions:

```
E/ExoPlayerImplInternal: Renderer error.
   com.google.android.exoplayer2.ExoPlaybackException 
at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:339)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:891)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:484)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:136)
    at android.os.HandlerThread.run(HandlerThread.java:61)
	at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
Caused by: com.google.android.exoplayer2.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 61440)
    at com.google.android.exoplayer2.audio.AudioTrack.checkAudioTrackInitialized(AudioTrack.java:974)
    at com.google.android.exoplayer2.audio.AudioTrack.initialize(AudioTrack.java:521)
    at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:332)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:891) 
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:484) 
    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315) 
    at android.os.Handler.dispatchMessage(Handler.java:98) 
    at android.os.Looper.loop(Looper.java:136) 
    at android.os.HandlerThread.run(HandlerThread.java:61) 
    at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```
I don't get these exceptions when I load 15 audio files or less. Is there a limit on the number of SimpleExoPlayer instances that can be made ?

**Comment by andrewlewis** [comment]
I think the limitation here is that you can only create a limited number of audio tracks at once (hence the code in our audio track wrapper that makes sure we've released one underlying `android.media.AudioTrack` instance before creating another). Each `SimpleExoPlayer` will use its own audio track.

**Comment by mcaquet** [comment]
Thanks, but why is there such limitation ? Shouldn't it be the app developer responsibility, making sure that the app doesn't run out of memory ?

**Comment by ojw28** [comment]
The limited resource isn't in your app (or process). Hopefully it's fairly intuitive that audio playback requires allocation of some resources in the platform itself, and that such resources are finite. This is why there's a limit on the number of AudioTrack instances that an application can create.

If you need to play a large number of audio streams at once you probably need to be mixing them together in application space and sending the mixed audio to a single AudioTrack instance. This is not something ExoPlayer supports.
