### ISSUE TITLE
can not play .ts format video using exoplayer 

### ISSUE THREAD

**Issue by iamnitesh** [google/ExoPlayer#2589]
```
E/EventLogger: internalError [0.50, loadError]
                                                                      com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 401
                                                                          at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
                                                                          at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
                                                                          at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:824)
                                                                          at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)
```

**Comment by ojw28** [comment]
Looks like an authentication problem unrelated to ExoPlayer. Please see "401 Unauthorized" [here](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes).
