### ISSUE TITLE
Fatal Exception: java.lang.NoSuchFieldError: zzaCl, at com.google.android.exoplayer2.audio.AudioTrack.processBuffers

### ISSUE THREAD

**Issue by slezadav** [google/ExoPlayer#2637]
### Issue description
Crash reported from Crashlytics, potentially device specific.

### Reproduction steps
Not known

### Link to test content
Do not know exactly, which media was being played during crash

### Version of ExoPlayer being used
r2.3.1

### Device(s) and version(s) of Android being used
alps HM NOTE 1W , Android 4.2.2
http://specdevice.com/showspec.php?id=6c40-e0e8-82e0-db4272cb4183

```
### A full bug report captured from the device
Can provide only stacktrace from Crashlytics:
Fatal Exception: java.lang.NoSuchFieldError: zzaCl
       at com.google.android.exoplayer2.audio.AudioTrack.processBuffers(SourceFile:816)
       at com.google.android.exoplayer2.audio.AudioTrack.handleBuffer(SourceFile:779)
       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(SourceFile:366)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(SourceFile:938)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:506)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:2466)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:194)
       at android.os.HandlerThread.run(HandlerThread.java:60)
       at com.google.android.exoplayer2.util.PriorityHandlerThread.run(SourceFile:40)
```

**Comment by andrewlewis** [comment]
If you have a proguard map, please could you provide the deobfuscated field name? Thanks.

**Comment by slezadav** [comment]
Unfortunately I dont have access to the original mapping, but assuming the proguard is deterministic I built again from the same commit and probably not much help:

com.google.android.gms.internal.zzaav$zzb -> com.google.android.gms.internal.zzaav$zzb:
    com.google.android.gms.internal.zzaav zzaCl -> zzaCl

**Comment by andrewlewis** [comment]
This stack trace looks wrong to me: though AudioTrack:779 looks correct for the call to processBuffers, it doesn't make sense for AudioTrack:816 to be do a field access which could cause this. I don't have that specific device available but I wasn't able to reproduce the error on another API 17 device. Is it possible that the map used to get this stack trace in Crashlytics is outdated?

(The ExoPlayer core library doesn't depend on GMS or Firebase so I think the GMS internal package name is spurious/unrelated.)

**Comment by slezadav** [comment]
Fatal Exception: java.lang.NoSuchFieldError: Base_Widget_AppCompat_ActionBar_TabBar
       at com.google.android.exoplayer2.audio.AudioTrack.processBuffers(SourceFile:816)
       at com.google.android.exoplayer2.audio.AudioTrack.handleBuffer(SourceFile:779)
       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(SourceFile:366)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(SourceFile:938)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:506)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:2466)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:194)
       at android.os.HandlerThread.run(HandlerThread.java:60)
       at com.google.android.exoplayer2.util.PriorityHandlerThread.run(SourceFile:40)

**Comment by andrewlewis** [comment]
We don't use the support library and some line numbers in the stack trace don't make sense (e.g. ExoPlayerImplInternal:2466 doesn't exist) so I think there's something going wrong with how this is being proguarded/deobfuscated, or a problem with the JVM on that device.

I'll close this for now as I don't think there's anything actionable here, but please reopen if you can find a way to reproduce this or get a different stack trace in ExoPlayer that makes sense. Thanks!

**Comment by slezadav** [comment]
I have different trace from the same line 
Fatal Exception: java.lang.InternalError: bad sparse switch magic
       at com.google.android.exoplayer2.audio.AudioTrack.processBuffers(SourceFile:816)
       at com.google.android.exoplayer2.audio.AudioTrack.handleBuffer(SourceFile:779)
       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(SourceFile:366)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(SourceFile:938)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:510)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:2466)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:194)
       at android.os.HandlerThread.run(HandlerThread.java:60)
       at com.google.android.exoplayer2.util.PriorityHandlerThread.run(SourceFile:40)

**Comment by slezadav** [comment]
And another one
Fatal Exception: java.lang.NoSuchFieldError: windowNoTitle
       at com.google.android.exoplayer2.audio.AudioTrack.processBuffers(SourceFile:816)
       at com.google.android.exoplayer2.audio.AudioTrack.handleBuffer(SourceFile:779)
       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(SourceFile:366)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(SourceFile:938)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:506)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:2466)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:194)
       at android.os.HandlerThread.run(HandlerThread.java:60)
       at com.google.android.exoplayer2.util.PriorityHandlerThread.run(SourceFile:40)

**Comment by slezadav** [comment]
One more info, all the devices reporting crash on this line are rooted.

**Comment by ojw28** [comment]
As per above, this does not appear to be an ExoPlayer issue. The stack traces do not make sense. They reference line numbers and imply the existence of dependencies like ExoPlayer -> Base_Widget_AppCompat_ActionBar_TabBar that don't exist. If these devices are running a custom Android build, then given what you're seeing it's likely the Android build is broken.
