### ISSUE TITLE
Playing a 2nd video with GvrAudioProcessor causes unexpected ExoPlaybackException

### ISSUE THREAD

**Issue by mahjiang** [google/ExoPlayer#2675]
@andrewlewis 
I have followed the guidelines [here](https://medium.com/google-exoplayer/spatial-audio-with-exoplayer-and-gvr-cecb00e9da5f) to set up spatial audio for ExoPlayer. The first video I load plays without issue, but the second video will throw an IllegalStateException. The list of videos contains a mix of channel counts, so some have spatial audio tracks, and others do not. However, this issue occurs regardless of the channel counts of the videos.

```
AndroidJavaException:
java.lang.IllegalStateException
at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:79)
at com.google.android.exoplayer2.ExoPlaybackException.getSourceException(ExoPlaybackException.java:110)
at com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native Method)
at com.unity3d.player.ReflectionHelper.a(Unknown Source)
at com.unity3d.player.ReflectionHelper$1.invoke(Unknown Source)
at java.lang.reflect.Proxy.invoke(Proxy.java:813)
at $Proxy5.onPlayerError(Unknown Source)
at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:382)
at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:93)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6121)
at java.lang.reflect.Method.invoke(Native Method)
```

The `onPlayerError` callback identifies the exception as `TYPE_UNEXPECTED`, but I haven't been able to identify a root cause. 

When I don't override `buildAudioProcessors`, this issue does not occur. Is there a step I'm missing? Do I need to clear or flush some sort of cache between videos? Using `GvrAudioProcessor`'s `flush()` and `release()` methods do not work.

**Comment by andrewlewis** [comment]
Are you instantiating a new renderer or SimpleExoPlayer when you play the second video, or reusing the ones used to play the first video? Please provide full steps to reproduce the issue and I will take a look. Thanks.

**Comment by mahjiang** [comment]
I am doing neither. Reusing the ones from the first video with a new source:

`exoPlayer.prepare(sampleSource);`
 `exoPlayer.setPlayWhenReady(autoPlay);`

However, I have tried to instantiate a new SimpleExoPlayer, but that doesn't work either

**Comment by andrewlewis** [comment]
Unfortunately the underlying exception is not being logged properly because (based on the stack trace you posted above) it's being incorrectly accessed as a source exception.

I suspect the bug might be that `GvrAudioProcessor.release()` is not fully resetting the state, so `GvrAudioProcessor.flush()` will throw a NullPointerException when it's reused. If you need a workaround for now, please try instantiating a new GvrAudioProcessor and player each time.

**Comment by mahjiang** [comment]
Yes, I tried calling those myself and calling `flush()` indeed results in an NPE. I am using the workaround you suggested, and it works, so please disregard my earlier comment about a new instance of SimpleExoPlayer not working. Thanks!
