### ISSUE TITLE
Playback of dash manifest with text/vtt subtitle fails

### ISSUE THREAD

**Issue by hoihrig** [google/ExoPlayer#268]
Playback of the following DASH Manifest using the DemoPlayer fails:
http://dash.edgesuite.net/akamai/test/caption_test/ElephantsDream/elephants_dream_480p_heaac5_1.mpd

Adding the Manifest above to the Samples List and playing it with the Full Player gives the following Error Message:  "segmentBase must be of type SingleSegmentBase or MultiSegmentBase"

The above Manifest can be played with the dash.js reference player.

StackTrace:

:59:44.992  29135-29135/com.google.android.exoplayer.demo I/ExoPlayerImpl﹕ Init 1.1.0
01-27 18:59:45.072  29135-29235/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 175K, 3% free 7979K/8192K, paused 17ms, total 17ms
01-27 18:59:45.262  29135-29235/com.google.android.exoplayer.demo E/LoadTask﹕ Unexpected error loading stream
    java.lang.IllegalArgumentException: segmentBase must be of type SingleSegmentBase or MultiSegmentBase
            at com.google.android.exoplayer.dash.mpd.Representation.newInstance(Representation.java:91)
            at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.buildRepresentation(MediaPresentationDescriptionParser.java:318)
            at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseRepresentation(MediaPresentationDescriptionParser.java:306)
            at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseAdaptationSet(MediaPresentationDescriptionParser.java:184)
            at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parsePeriod(MediaPresentationDescriptionParser.java:138)
            at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseMediaPresentationDescription(MediaPresentationDescriptionParser.java:100)
            at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:72)
            at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:46)
            at com.google.android.exoplayer.util.ManifestFetcher$ManifestLoadable.load(ManifestFetcher.java:366)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:206)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by ojw28** [comment]
Interesting. We don't correctly handle the case where a single file contains the VTT captions for the whole video. We would correctly handle the exact same file were the manifest to define a SegmentList with a single entry corresponding to the file. We can fix this pretty easily (I'll do this). However, there are other issues with this video, which I believe are issues with the actual source:

Video:

- Every video frame is marked as a sync frame in the fmp4 container, which is incorrect. It causes temporary video corruption when seeking because ExoPlayer doesn't correctly locate the (real) nearest keyframe. Is this your stream, and if so are you aware of this? I've seen a few videos with this issue. If there's a particular packager that has this issue, it would be good to push them to get it fixed.

Subtitles:

- There's three bytes of unexpected data in front of the WEBVTT header in the captions file. I'm not sure if that's an issue with the file, or whether it's actually expected.
- We don't handle <c.red.caps> yet, but neither do we filter it out of the displayed text. We should fix that.
- The captions only cover the first 2:22 of the video. I assume this is a known issue.

**Comment by hoihrig** [comment]
Thanks for the fast answer. A fix for the issue would be greatly appreciated.

As it comes to the actual video: It is not my video, I just happen to stumble over a publicly available video having the same issue I am experiencing with another stream that has the same problem

**Comment by ojw28** [comment]
- We'll try and fix the base issue in the first half of next week.
- We'll also fix handling of the three bytes of data at the front of the WEBVTT file. This is a byte-order-mark, and is allowed by the spec.
