### ISSUE TITLE
Unable Stream HLS

### ISSUE THREAD

**Issue by khashayarghamati** [google/ExoPlayer#269]
hi
when i want stream hls i get error and crash application 

01-28 18:21:38.690    5836-6028/com.example.video E/ACodec﹕ [OMX.qcom.video.decoder.avc] ERROR(0x80001009)
01-28 18:21:38.690    5836-6027/com.example.video E/MediaCodec﹕ Codec reported an error. (omx error 0x80001009, internalError -2147483648)
01-28 18:21:38.690    5836-5862/com.example.video E/ExoPlayerImplInternal﹕ Internal runtime error.
    java.lang.IllegalStateException
            at android.media.MediaCodec.dequeueInputBuffer(Native Method)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:527)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:451)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:398)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
01-28 18:21:38.700    5836-5836/com.example.video E/PlayerActivity﹕ Playback failed
    com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:236)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.lang.IllegalStateException
            at android.media.MediaCodec.dequeueInputBuffer(Native Method)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:527)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:451)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:398)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by andudo** [comment]
@khashayarghamati can you provide a URL to the media stream you're using?

**Comment by khashayarghamati** [comment]
@andudo yes i have a m3u8 URL

**Comment by andudo** [comment]
@khashayarghamati please share it with us

**Comment by khashayarghamati** [comment]
@andudo http://www.whiteline.ir/video/5/stream

**Comment by ojw28** [comment]
That URL is a "404 Not Found" for me. Are you sure that's the correct m3u8 URL? Does it still work for you? If so, do you know if it's geo-restricted, or similar?

**Comment by ojw28** [comment]
Please re-open if you're able to provide a working stream.

**Comment by adeelpervaiz** [comment]
I am not sure, why this issue is closed, even if ULR is not exist, this should raise some exceptions gracefully, not crashing the whole app.

**Comment by ojw28** [comment]
There is no evidence in the log that the app crashed. In fact, this line explicitly indicated that the exception was caught internally to the player and propagated gracefully to the app's listener:

E/ExoPlayerImplInternal﹕ Internal runtime error.

The stack trace logging is just logging, and does not mean the process died.

In general, we won't keep issues open without reproduction steps, because it's not possible to determine how to fix them, or whether they're fixed already due to other changes.

**Comment by adeelpervaiz** [comment]
What do you think poster is saying that error comes and app crashes,
why don't you see that?

**Comment by ojw28** [comment]
The logs don't capture the crash, so there is no way to determine where the crash occurred (or even if it was definitely in ExoPlayer, as opposed to in their own app code). You're welcome to reopen the issue if you can provide the relevant logs or reproduction steps. Without either there's nothing we can do, so there's no value in keeping the issue open. Thanks.

**Comment by adeelpervaiz** [comment]
Well check this though


02-11 14:37:27.054: E/OMX-VDEC-1080P(2973): Extension: OMX.google.android.index.storeMetaDataInBuffers not implemented
02-11 14:37:27.054: E/OMXNodeInstance(2973): OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
02-11 14:37:27.054: E/OMX-VDEC-1080P(2973): Extension: OMX.google.android.index.prepareForAdaptivePlayback not implemented
02-11 14:37:27.054: E/OMX-VDEC-1080P(2973):  WARNING: failed in ioctl read next msg (-1)
02-11 14:37:27.054: E/OMX-VDEC-1080P(2973):  WARNING: read from pipe failed, ret -1 errno 9
02-11 14:37:27.104: E/AndroidRuntime(8690): FATAL EXCEPTION: main
02-11 14:37:27.104: E/AndroidRuntime(8690): Process: com.amerald.bcast, PID: 8690
02-11 14:37:27.104: E/AndroidRuntime(8690): java.lang.NullPointerException
02-11 14:37:27.104: E/AndroidRuntime(8690): 	at com.google.android.exoplayer.dash.DashMp4ChunkSource.<init>(DashMp4ChunkSource.java:76)
02-11 14:37:27.104: E/AndroidRuntime(8690): 	at com.google.android.exoplayer.demo.simple.DashVodRendererBuilder.onManifest(DashVodRendererBuilder.java:128)
02-11 14:37:27.104: E/AndroidRuntime(8690): 	at com.google.android.exoplayer.demo.simple.DashVodRendererBuilder.onManifest(DashVodRendererBuilder.java:1)
02-11 14:37:27.104: E/AndroidRuntime(8690): 	at com.google.android.exoplayer.util.ManifestFetcher.onPostExecute(ManifestFetcher.java:113)
02-11 14:37:27.104: E/AndroidRuntime(8690): 	at android.os.AsyncTask.finish(AsyncTask.java:632)
02-11 14:37:27.104: E/AndroidRuntime(8690): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
02-11 14:37:27.104: E/AndroidRuntime(8690): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
02-11 14:37:27.104: E/AndroidRuntime(8690): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-11 14:37:27.104: E/AndroidRuntime(8690): 	at android.os.Looper.loop(Looper.java:157)
02-11 14:37:27.104: E/AndroidRuntime(8690): 	at android.app.ActivityThread.main(ActivityThread.java:5867)
02-11 14:37:27.104: E/AndroidRuntime(8690): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-11 14:37:27.104: E/AndroidRuntime(8690): 	at java.lang.reflect.Method.invoke(Method.java:515)
02-11 14:37:27.104: E/AndroidRuntime(8690): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
02-11 14:37:27.104: E/AndroidRuntime(8690): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
02-11 14:37:27.104: E/AndroidRuntime(8690): 	at dalvik.system.NativeStart.main(Native Method)
02-11 14:37:27.124: E/ActivityManager(763): App crashed! Process: com.amerald.bcast

**Comment by khashayarghamati** [comment]
please test with this http://api.whiteline.ir/video/4/stream

**Comment by ojw28** [comment]
@adeelpervaiz - The stack trace is from a version of ExoPlayer that's over 6 months old, and has nothing to do with HLS. Please test on a newer version, and file a separate issue for the problem if it still occurs.

@khashayarghamati Thanks.

**Comment by khashayarghamati** [comment]
@ojw28 ;)

**Comment by ojw28** [comment]
That stream appears to be working fine for me running on a Nexus 5. On what device(s) do you see the issue with this stream? Does it happen all of the time, or was it just a one-off issue? Does rebooting the device fix it at all? Thanks!

**Comment by khashayarghamati** [comment]
on avd i get audio from video and on some device such as HTC First get grayscale frame and on ASUS Eee Pad Transformer Prime TF201 and HTC HD2 crash my app
