### ISSUE TITLE
How to setTrack before play video in code with ExoPlayer?

### ISSUE THREAD

**Issue by Dusam** [google/ExoPlayer#2694]
ExoPlayer Demo App is using a button to dialog to select video track, it can work in my Android Studio project. But now I want to setTrack before play video, somebody know how to do it?

I try to use FixedTrackSelection.Factory() to setTrack before play video,but it have some issue.

        public void initializePlayer(boolean SetAdaptiveTrack) {
        mediaDataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "XXX"), BANDWIDTH_METER);
        window = new Timeline.Window();
        mainHandler = new Handler();

        if (SetAdaptiveTrack == true){
            TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveVideoTrackSelection.Factory(BANDWIDTH_METER);
            trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
            trackSelectionHelper = new TrackSelectionHelper(trackSelector, videoTrackSelectionFactory);
            player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, new DefaultLoadControl());
            setTrackbyUser = true;
        }
        else {
            setTrackbyUser = false;
            TrackGroupArray trackGroupArray = videotrackGroups;
            TrackSelection.Factory TrackSelectionFactory = new FixedTrackSelection.Factory();
            TrackSelectionFactory.createTrackSelection(trackGroupArray.get(0), 0);
            TrackSelection f = TrackSelectionFactory.createTrackSelection(trackGroupArray.get(0), 0);
            trackSelector = new DefaultTrackSelector(TrackSelectionFactory);
            trackSelectionHelper = new TrackSelectionHelper(trackSelector, TrackSelectionFactory);
            player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, new DefaultLoadControl());
        }

        // 3. Create the player
        player.addListener(this);

        eventLogger = new EventLogger(trackSelector);
        player.addListener(eventLogger);
        player.setAudioDebugListener(eventLogger);
        player.setVideoDebugListener(eventLogger);
        player.setMetadataOutput(eventLogger);

        simpleExoPlayerView.setPlayer(player);
        player.setPlayWhenReady(true);

        // This is the MediaSource representing the media to be played.
        MediaSource Dashvideosource = new DashMediaSource(Uri.parse("http://www.youtube.com/api/manifest/dash/id/bf5bb2419360daf1/source/youtube?as=fmp4_audio_clear,fmp4_sd_hd_clear&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&ipbits=0&expire=19000000000&signature=51AF5F39AB0CEC3E5497CD9C900EBFEAECCCB5C7.8506521BFC350652163895D4C26DEE124209AA9E&key=ik0"),
                mediaDataSourceFactory, new DefaultDashChunkSource.Factory(mediaDataSourceFactory), mainHandler, eventLogger);

        player.prepare(Dashvideosource);
    }
```
@Override
public void onStart() {
    super.onStart();
    if (Util.SDK_INT > 23) {
        initializePlayer(true);
    }
}

@Override
public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
    updateButtonVisibilities();
    MappingTrackSelector.MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
    if (mappedTrackInfo != null) {
        trackGroups = trackSelector.getCurrentMappedTrackInfo().getTrackGroups(0);
        videotrackGroups = trackGroups;
        if (setTrackbyUser == true){
            releasePlayer();
            handlerEnd.removeCallbacksAndMessages(null);
            mainHandler.removeCallbacksAndMessages(null);
            initializePlayer(false);
        }
        if (mappedTrackInfo.getTrackTypeRendererSupport(C.TRACK_TYPE_VIDEO)
                == MappingTrackSelector.MappedTrackInfo.RENDERER_SUPPORT_UNSUPPORTED_TRACKS) {
            showToast(R.string.error_unsupported_video);
        }
        if (mappedTrackInfo.getTrackTypeRendererSupport(C.TRACK_TYPE_AUDIO)
                == MappingTrackSelector.MappedTrackInfo.RENDERER_SUPPORT_UNSUPPORTED_TRACKS) {
            showToast(R.string.error_unsupported_audio);
        }
    }
}
```

when I run my project it problem is:
```
E/ExoPlayerImplInternal: Internal runtime error.
                                                                                 java.lang.IllegalArgumentException
                                                                                     at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:37)
                                                                                     at com.google.android.exoplayer2.trackselection.FixedTrackSelection$Factory.createTrackSelection(FixedTrackSelection.java:51)
                                                                                     at com.google.android.exoplayer2.trackselection.FixedTrackSelection$Factory.createTrackSelection(FixedTrackSelection.java:30)
                                                                                     at com.google.android.exoplayer2.trackselection.DefaultTrackSelector.selectAdaptiveVideoTrack(DefaultTrackSelector.java:475)
                                                                                     at com.google.android.exoplayer2.trackselection.DefaultTrackSelector.selectVideoTrack(DefaultTrackSelector.java:446)
                                                                                     at com.google.android.exoplayer2.trackselection.DefaultTrackSelector.selectTracks(DefaultTrackSelector.java:407)
                                                                                     at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:298)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.selectTracks(ExoPlayerImplInternal.java:1468)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.handlePrepared(ExoPlayerImplInternal.java:1463)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1269)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:316)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
 E/EventLogger: playerFailed [0.24]
                                                                       com.google.android.exoplayer2.ExoPlaybackException
                                                                           at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                           at android.os.Looper.loop(Looper.java:136)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                           at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                        Caused by: java.lang.IllegalArgumentException
                                                                           at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:37)
                                                                           at com.google.android.exoplayer2.trackselection.FixedTrackSelection$Factory.createTrackSelection(FixedTrackSelection.java:51)
                                                                           at com.google.android.exoplayer2.trackselection.FixedTrackSelection$Factory.createTrackSelection(FixedTrackSelection.java:30)
                                                                           at com.google.android.exoplayer2.trackselection.DefaultTrackSelector.selectAdaptiveVideoTrack(DefaultTrackSelector.java:475)
                                                                           at com.google.android.exoplayer2.trackselection.DefaultTrackSelector.selectVideoTrack(DefaultTrackSelector.java:446)
                                                                           at com.google.android.exoplayer2.trackselection.DefaultTrackSelector.selectTracks(DefaultTrackSelector.java:407)
                                                                           at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:298)
                                                                           at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.selectTracks(ExoPlayerImplInternal.java:1468)
                                                                           at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.handlePrepared(ExoPlayerImplInternal.java:1463)
                                                                           at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1269)
                                                                           at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:316)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                           at android.os.Looper.loop(Looper.java:136) 
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                           at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

```

**Comment by sandeshlasnapure** [comment]
How you have resolved this issue? can you share code snippet please.

**Comment by Dusam** [comment]
I'm write it in onTracksChanged()
`
trackGroups = trackSelector.getCurrentMappedTrackInfo().getTrackGroups(0);

                    for (int i = 0; i < trackGroups.get(0).length; i++) {
                        int currentQuality= trackGroups.get(0).getFormat(i).height;

                        Quality = currentQuality;
                        QualityIndex = i;

                        if (Quality == 720) {
                            break;
                        }
                    }

                    trackSelector.setSelectionOverride(
                            0,
                            trackGroups,
                            new MappingTrackSelector.SelectionOverride(
                                    new FixedTrackSelection.Factory(),
                                    0,
                                    QualityIndex
                            )
                    );`
you can use this method to set 720p video and no change quality when playing video.
0 is the trackGroup index, I write directly 0 because i found it actually only one trackGroup is not trackGroups.

**Comment by sandeshlasnapure** [comment]
@Dusam  Thanks, its working. But when application comes from background to foreground it again follows the Adaptive nature. 
Can we restrict mediasource to play specific index track while preparing?

**Comment by Dusam** [comment]
If you want to play in the background, you need to set the layout view or view for ExoPlayer and make view Invisible.
if not set view, it will Adaptive to choose the format
