### ISSUE TITLE
EventLogger: playerFailed, Caused by: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by xpzzgh** [google/ExoPlayer#2716]
Hey, It's not play when I want to play a mp4 file with ExoPlayer 2.3.1 Demo.
I put file's url in media.exolist.json-Playlists-Cats>Dogs

Logcat: 

`04-22 18:49:41.909 12990-18922/com.google.android.exoplayer2.demo E/ACodec: [OMX.allwinner.video.decoder.avc] ERROR(0x80001009)
04-22 18:49:41.909 12990-18922/com.google.android.exoplayer2.demo E/ACodec: signalError(omxError 0x80001009, internalError -2147483648)
04-22 18:49:41.909 12990-18921/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported err 0x80001009, actionCode 0, while in state 6
04-22 18:49:41.916 12990-18898/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                           java.lang.IllegalStateException
                                                                                               at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                                               at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:882)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:506)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:466)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                               at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
04-22 18:49:41.921 12990-12990/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [0.43]
                                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                  Caused by: java.lang.IllegalStateException
                                                                                     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                                     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:882)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:506)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:466)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
04-22 18:49:41.950 12990-18922/com.google.android.exoplayer2.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f8a49b360
04-22 18:49:41.951 12990-18922/com.google.android.exoplayer2.demo W/ACodec: [OMX.allwinner.video.decoder.avc] can not return buffer 10 to native window
04-22 18:49:41.952 12990-18922/com.google.android.exoplayer2.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f8a49c7a0
04-22 18:49:41.953 12990-18922/com.google.android.exoplayer2.demo W/ACodec: [OMX.allwinner.video.decoder.avc] can not return buffer 9 to native window
04-22 18:49:41.954 12990-18922/com.google.android.exoplayer2.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f8a49dac0
04-22 18:49:41.954 12990-18922/com.google.android.exoplayer2.demo W/ACodec: [OMX.allwinner.video.decoder.avc] can not return buffer 8 to native window
04-22 18:49:41.956 12990-18922/com.google.android.exoplayer2.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f8a4b3560
04-22 18:49:41.956 12990-18922/com.google.android.exoplayer2.demo W/ACodec: [OMX.allwinner.video.decoder.avc] can not return buffer 7 to native window
04-22 18:49:41.975 12990-18898/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Stop failed.
                                                                                           java.lang.IllegalStateException
                                                                                               at android.media.MediaCodec.native_stop(Native Method)
                                                                                               at android.media.MediaCodec.stop(MediaCodec.java:1901)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:452)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:407)
                                                                                               at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:278)
                                                                                               at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:145)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:675)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:650)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:352)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                               at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)`

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
