### ISSUE TITLE
Smooth - Error when parsing UTF-16 encoded Manifest

### ISSUE THREAD

**Issue by ldelecroix** [google/ExoPlayer#2720]
Hello,

I've got a bug when i try to parse Smooth Manifest encoded with UTF-16. Here's the require form :

### Issue description
When parsing a Smooth Manifest encoded with UTF-16, a XmlPullParserException is triggered. 

### Reproduction steps
You can either : 
- try with one of the link below
- download a Manifest file that works, and save it with UTF-16 encryption (LE/BE, with/without BOM, the error is always triggered), then try to parse it.

### Link to test content
http://playready.directtaps.net/smoothstreaming/TTLSS720VC1/To_The_Limit_720.ism/Manifest
http://playready.directtaps.net/smoothstreaming/TTLSS720VC1PR/To_The_Limit_720.ism/Manifest

### Version of ExoPlayer being used
Version release-v2

### Device(s) and version(s) of Android being used
I did it on a personal Java7 project. I'm only using the parsing part of ExoPlayer, not the part that plays the media

### A full bug report captured from the device
Stack trace : 

```
#!java

 Exception in thread "main" com.google.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException: only whitespace content allowed before start tag and not \ufffd (position: START_DOCUMENT seen \ufffd... @1:1)
 at com.google.android.exoplayer2.source.smoothstreaming.manifest.SsManifestParser.parse(SsManifestParser.java:73)
 [...]
 Caused by: org.xmlpull.v1.XmlPullParserException: only whitespace content allowed before start tag and not \ufffd (position: START_DOCUMENT seen \ufffd... @1:1) 
 	at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1519)
 	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)
 	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
 	at com.google.android.exoplayer2.source.smoothstreaming.manifest.SsManifestParser$ElementParser.parse(SsManifestParser.java:157)
 	at com.google.android.exoplayer2.source.smoothstreaming.manifest.SsManifestParser.parse(SsManifestParser.java:71)
 	... 3 more
```

**Comment by ojw28** [comment]
As per Android's [Javadoc](https://developer.android.com/reference/org/xmlpull/v1/XmlPullParser.html), the `XmlPullParser.setInput` implementation is supposed to detect the input encoding.

Whatever platform you're running on, it appears to use `org.xmlpull.mxp1.MXParser` as the `XmlPullParser` implementation, and my guess would be that it's not correctly detecting the input encoding. Android devices I have to hand all seem to use `org.kxml2.io.KXmlParser`, which is detecting the input encoding correctly.

So as far as I can tell parsing is working correctly on Android devices. Non-Android platforms are outside the scope of this issue tracker.
