### ISSUE TITLE
Audio Keep repeating when playing mp3 over 12 minutes.

### ISSUE THREAD

**Issue by SuwandiSlasher** [google/ExoPlayer#2726]
### Issue description
1. video will keep repeating in same position.

### Reproduction steps
1. put String mp3 in MISC category from assets file
2. play audio file. wait after 3 minute.
3. video will keep repeating

### Link to test content
http://k003.kiwi6.com/hotlink/fhdbn390il/episode_1.mp3
below our server link
link removed

### Version of ExoPlayer being used
r2.3.1

### Device(s) and version(s) of Android being used
Device Samsung A5(2016) and Android M.
Device Xiaomi redmi 3 and Android L.

### A full bug report captured from the device
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/ACodec: [OMX.SEC.mp3.dec] signalFlush
I/ACodec: [OMX.SEC.mp3.dec] ExecutingState flushing now (codec owns 10/10 input, 0/5 output).
I/ACodec: [OMX.SEC.mp3.dec] Now Flushing
I/ACodec: [OMX.SEC.mp3.dec] FlushingState onOMXEvent(0,1,0)
I/ACodec: [OMX.SEC.mp3.dec] FlushingState onOMXEvent(0,1,1)
I/ACodec: [OMX.SEC.mp3.dec] Now Executing

When i try playing mp3 with length 12 minute using ExoPlayer keep getting above message and the audio keep repeating when it reach 3 minute:

And I am already try using demo application ,
putting mp3 in MISC category and play the audio.
it will have same problem.

when i split the mp3 into two piece, no error occured.

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by SuwandiSlasher** [comment]
@ojw28 thanks for you reply.
I just edit the issue above.

**Comment by ojw28** [comment]
Please can you provide a full bug report? The issue template explains how to capture one. Assuming an 8 line snippet of log output is the exact bit we need to debug this issue is probably not correct. Thanks!

**Comment by SuwandiSlasher** [comment]
When i using demo application, here is the log:
Looks like it happen in our server only.

> 04-25 22:43:06.997 22018-22018/com.google.android.exoplayer2.demo E/EventLogger: internalError [247.38, loadError]
                com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.io.IOException: unexpected end of stream
                    at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:269)
                    at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:128)
                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:257)
                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:59)
                    at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:490)
                    at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.readSample(Mp3Extractor.java:217)
                    at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.read(Mp3Extractor.java:189)
                    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:643)
                    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                    at java.lang.Thread.run(Thread.java:818)
                 Caused by: java.io.IOException: unexpected end of stream
                    at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:502)
                    at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                    at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:571)
                    at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:267)
                    at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:128) 
                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:257) 
                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:59) 
                    at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:490) 
                    at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.readSample(Mp3Extractor.java:217) 
                    at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.read(Mp3Extractor.java:189) 
                    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:643) 
                    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                    at java.lang.Thread.run(Thread.java:818) 

and here is log when iniatiate to play audio
>I/ExoPlayerImpl: Init 2.3.1 [ido, Redmi 3, Xiaomi, 22]
D/EventLogger: state [0.00, true, I]
I/ViewRootImpl: CPU Rendering VSync enable = true
D/EventLogger: state [0.01, true, B]
D/EventLogger: sourceInfo [periodCount=1, windowCount=1
D/EventLogger:   period [?]
D/EventLogger:   window [?, false, false]
D/EventLogger: ]
D/EventLogger: loading [true]
D/OpenGLRenderer: endAllStagingAnimators on 0x5597fea8d0 (ExpandableListView) with handle 0x55981c77c0
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3b7acf55 time:3650430
D/EventLogger: sourceInfo [periodCount=1, windowCount=1
D/EventLogger:   period [?]
D/EventLogger:   window [?, false, false]
D/EventLogger: ]
D/EventLogger: Tracks [
D/EventLogger:   Renderer:1 [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=null, mimeType=audio/mpeg, channels=2, sample_rate=44100, 
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger: ]
D/EventLogger: audioEnabled [0.19]

**Comment by ojw28** [comment]
Your server really isn't setup well for delivering media. It's serving content using chunked transfer encoding and does not indicate the content length in the response headers. You can see this using curl:

```
curl -v http://popo.festiware.com/files/episode/content/episode_86954697df8ee7def709e39a01567a0511f72795_1.mp3 > test.mp3
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 188.166.188.221...
* Connected to popo.festiware.com (188.166.188.221) port 80 (#0)
> GET /files/episode/content/episode_86954697df8ee7def709e39a01567a0511f72795_1.mp3 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: popo.festiware.com
> Accept: */*
> 
< HTTP/1.1 200 OK
* Server nginx is not blacklisted
< Server: nginx
< Content-Type: audio/mpeg
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: no-cache
< Date: Tue, 25 Apr 2017 16:22:02 GMT
```

For this particular piece of media, the result is that the player cannot determine the media duration, cannot seek and cannot resume. It actually looks to the player as though it's a live stream. At some point the connection is being disconnected (most likely from the server side), and the best the player can do is start again.

In contrast, if you try the other link:

```
curl -v http://k003.kiwi6.com/hotlink/fhdbn390il/episode_1.mp3 > test2.mp3* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.28.28.76...
* Connected to k003.kiwi6.com (104.28.28.76) port 80 (#0)
> GET /hotlink/fhdbn390il/episode_1.mp3 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: k003.kiwi6.com
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 25 Apr 2017 16:25:02 GMT
< Content-Type: audio/mpeg; charset=utf-8
< Content-Length: 11707455
< Connection: keep-alive
< Set-Cookie: __cfduid=d11e029c5853ae9ca4e19508439e524d21493137502; expires=Wed, 25-Apr-18 16:25:02 GMT; path=/; domain=.kiwi6.com; HttpOnly
< Last-Modified: Tue, 25 Apr 2017 13:36:10 GMT
< Cache-Control: public, max-age=1800
< ETag: "58ff50ca-b2a43f"
< CF-Cache-Status: HIT
< Expires: Tue, 25 Apr 2017 16:55:02 GMT
< Accept-Ranges: bytes
* Server cloudflare-nginx is not blacklisted
< Server: cloudflare-nginx
```

Note the presence of Content-Length in the response headers (allowing the player to determine how long the media is), that chunked transfer encoding is not used, and that the server supports partial range requests as indicated by the Accept-Ranges header (allowing the player to resume where it left off should the connection be broken).

You'll need to configure your server to better support serving of media.

**Comment by SuwandiSlasher** [comment]
Ok thanks for the reply,
It's seems not on library side.
but on server side.
