### ISSUE TITLE
Can't play some audio streams (M3U8)

### ISSUE THREAD

**Issue by eneasgesing** [google/ExoPlayer#2732]
### Issue description
Can't play some audio streams.

### Reproduction steps
Can't play audio streams listed below. They can be reproduced using Vitamio lib, with is no longer supported by Android 7. These streams, and similar others, are important for my app. And I'm loving Exoplayer.

### Link to test content
http://42747t.lp.azioncdn.net:1935/2747t/a/mp4:access_options/rtmp-live/atl_poa.sdp/playlist.m3u8
http://192747t.lp.azioncdn.net/2747t/a/mp4:access_options/rtmp-live/gau_centro.sdp/playlist.m3u8

### Version of ExoPlayer being used
2.3.1

### Device(s) and version(s) of Android being used
Tested on several Android versions, using emulators.

### A full bug report captured from the device
04-26 21:09:20.189 27953-27953/com.eneasgesing.radios.rs E/EventLogger: playerFailed [987.08]
                                                                        com.google.android.exoplayer2.ExoPlaybackException
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:345)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                            at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                         Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                            at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:713)
                                                                            at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:636)
                                                                            at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                            at java.lang.Thread.run(Thread.java:761)

**Comment by AquilesCanta** [comment]
The stack trace seems to indicate you are using an ExtractorMediaSource, while HlsMediaSource is the correct one for m3u8 playlists. Other than that, it seems to play well on the demo app.
