### ISSUE TITLE
Playback rate edge case

### ISSUE THREAD

**Issue by ericharlow** [google/ExoPlayer#2774]
First off I have to say thank you so much for the new playback rate feature going back to android 4.1.

### Issue description
I observed exoplayer crashing during the first second of audio playback.

### Reproduction steps
When exoplayer is loading audio for the first time and before the first second of audio has played, seek to the end and change the playback rate.

### Link to test content
Will work on emailing some test content. it is hls audio.

### Version of ExoPlayer being used
2.4

### Device(s) and version(s) of Android being used
Amazon KFFOWI Android 5.1.1 (api 22)

### A full bug report captured from the device
Will email a full bug report. Here is the logcat. 
`E/ExoPlayerImplInternal: Internal runtime error.
                                                                               java.lang.ArrayIndexOutOfBoundsException: length=2712; index=2712
                                                                                   at com.google.android.exoplayer2.audio.Sonic.interpolate(Sonic.java:378)
                                                                                   at com.google.android.exoplayer2.audio.Sonic.adjustRate(Sonic.java:405)
                                                                                   at com.google.android.exoplayer2.audio.Sonic.processStreamInput(Sonic.java:490)
                                                                                   at com.google.android.exoplayer2.audio.Sonic.queueInput(Sonic.java:127)
                                                                                   at com.google.android.exoplayer2.audio.SonicAudioProcessor.queueInput(SonicAudioProcessor.java:151)
                                                                                   at com.google.android.exoplayer2.audio.AudioTrack.processBuffers(AudioTrack.java:835)
                                                                                   at com.google.android.exoplayer2.audio.AudioTrack.handleBuffer(AudioTrack.java:815)
                                                                                   at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:376)
                                                                                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:955)
                                                                                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:510)
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by andrewlewis** [comment]
It would be useful to have sample media and specific steps to reproduce this, if possible. Thanks!
