### ISSUE TITLE
drm_scheme clearkey in android

### ISSUE THREAD

**Issue by Pash97** [google/ExoPlayer#2798]
I am encrypting video using clearkey. And want play with exoplayer in Android studio. Am able to play video without encryption. But not getting how to play using clearkey DASH. It's giving me DrmSession error. If anybody knows please help. Thank you in advance.

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
 
If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by Pash97** [comment]
I am using following command for creating mpd file for video

     ./packager input=~/Videos/AkaashVani.mp4,stream=audio,output=/var/www/html/data/akashvani/1280p/audio.mp4 input=~/Videos/AkaashVani.mp4,stream=video,output=/var/www/html/data/akashvani/1280p/video.mp4 

When i trigger it from android with exo player Video is playing perfectlly.

But when i create the mpd file along with encryption key

	./packager input=~/Videos/AkaashVani.mp4,stream=audio,output=/var/www/html/data/akashvani/1280p/audio.mp4 input=~/Videos/AkaashVani.mp4,stream=video,output=/var/www/html/data/akashvani/1280p/video.mp4 -enable_fixed_key_encryption -key_id="some key  --key="some key"

The android Studio gives following error

		Internal track renderer error.
                         com.google.android.exoplayer.ExoPlaybackException: Media requires a DrmSessionManager
                             at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:344)
                             at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768)
                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)
                             at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524)
                             at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507)
                             at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                             at android.os.Handler.dispatchMessage(Handler.java:98)
                             at android.os.Looper.loop(Looper.java:148)
                             at android.os.HandlerThread.run(HandlerThread.java:61)
                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by AquilesCanta** [comment]
Are you using the demo app? Are you adding your sample to "media.exolist.json" or similar and including `"drm_scheme": "playready"`?

**Comment by Pash97** [comment]
no am not using demo app Am new in exoplayer, so i don't know how to include sample in media.exolist.json and drm_scheme can you plz guide me how to do that..?

**Comment by AquilesCanta** [comment]
Have a look at the demo app. The method `initializePlayer()` in `PlayerActivity` is a good place to start.

**Comment by ojw28** [comment]
In addition to looking at the demo app as a starting point, if you're new to ExoPlayer you should definitely be using the latest version of ExoPlayer (i.e. 2.4.0). You're using a V1 release, which is quite old now.

**Comment by Pash97** [comment]
Can anybody explain me with example..?

**Comment by ojw28** [comment]
See https://github.com/google/ExoPlayer/issues/2827.
