### ISSUE TITLE
Can not play local TS file

### ISSUE THREAD

**Issue by gemiren** [google/ExoPlayer#2815]
### Issue description
Local TS file can not be played.

### Reproduction steps
Use the demo app to play the attached ts file. It will fail.

### Link to test content
The ts file can be downloaded from https://www.dropbox.com/s/w2sid8hhsyr01bo/Truth_20170501_185322.ts

### Version of ExoPlayer being used
2.4.0

### Device(s) and version(s) of Android being used
Nexus 5x. Android 7.1.1

### A full bug report captured from the device
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:750)
                                                                                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:647)
                                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                             at java.lang.Thread.run(Thread.java:818)

**Comment by Avetri** [comment]
It is not a TS file. It is a M2TS file, MPTS M2TS file with unconsistent DVB SI.

**Comment by AquilesCanta** [comment]
@Avetri is correct. ".m2ts" support is tracked  by #1488.
