### ISSUE TITLE
Problem providing key response to MediaDrm (Dash with Widevine)

### ISSUE THREAD

**Issue by jatago** [google/ExoPlayer#282]
Hello everyone, 

I am experiencing the following issue when trying to play content with Dash and Widevine. (custom content and custom proxy widevine license server)

The exception it is raised in this line of code:
```
mediaDrm.provideKeyResponse(sessionId, (byte[]) response);
```

```
02-05 19:24:29.037    5488-5488/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [6.47]
    com.google.android.exoplayer.ExoPlaybackException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2998
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:289)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:678)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:465)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:442)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:398)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2998
            at android.media.MediaDrm.provideKeyResponse(Native Method)
            at com.google.android.exoplayer.drm.StreamingDrmSessionManager.onKeyResponse(StreamingDrmSessionManager.java:287)
            at com.google.android.exoplayer.drm.StreamingDrmSessionManager.access$700(StreamingDrmSessionManager.java:42)
            at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostResponseHandler.handleMessage(StreamingDrmSessionManager.java:369)
```

From what I can see in the proxy (Charles) I setup in the middle, the license seems to be acquired correctly but for some reason the MediaDrm is failing to process it. Any hints? 

This is the struct of the license server response:
```
{
	"status": "OK",
	"license": "...",
	"license_metadata": {
		"content_id": "..."
	},
	"supported_tracks": [{
		"type": "SD"
	}],
	"make": "LG",
	"model": "Nexus 4",
	"security_level": 1,
	"internal_status": 0,
	"session_state": {
		"license_id": {
			"request_id": "...",
			"session_id": "...",
			"purchase_id": "",
			"type": "STREAMING",
			"version": 0
		},
		"signing_key": ...",
		"keybox_system_id": 
	}
}
```

Not idea what this provideKeyResponse method is expecting in the response object. 

Thanks and great project. Hopefully I can contribute my self as well in the future.

**Comment by ojw28** [comment]
Do the Widevine GTS samples in the ExoPlayer demo app work for you? If so then that would suggest that the device itself is fine, and that your response isn't formatted in the way that the Widevine plugin expects.

I'm not sure exactly what the expected format is. If the Widevine GTS samples do work, then I'd recommend attaching a debugger to the demo app and taking a look at the response data for that case. That may well give you enough to go on. If that fails, and if you have a contact at Widevine, you'd probably be best off asking them as a next step. If all else fails, let me know and I can do some more digging around.

Either way, let me know how you get on!

**Comment by jatago** [comment]
Thanks for the quick response! 

Yeap the Widevine GTS samples are working correctly in the devices which I tested so it is not a problem with the device itself. I also thought as you and attached a debugger and a proxy to the demo app to figure out what they are providing in that method but the proxy (charles) hangs up every time I try to take a look to the response of the staging widevine proxy server, and through the debugger the response when I try to read the InputStream in = new BufferedInputStream(urlConnection.getInputStream()); from the executePost method, gives me a really weird values. 

I will keep investigating a bit further today and let you know my findings, also if I manage to figure out what exactly needs to be provided in that method we could add it as documentation for someone else trying to perform the same implementation as me. 

Thanks again for the help and great job!

**Comment by jatago** [comment]
Ok I finally manage to solve it (indeed was really simple to do). In the DemoUtil.java class in the method executePost the only thing needed in my case was parse the response (which was a JSON object as mentioned before), extract the license attribute and IMPORTANT, in my case the license key was encoded in Base64 so I just had to add this lines of code: 

```
InputStream in = new BufferedInputStream(urlConnection.getInputStream());

        BufferedReader streamReader = new BufferedReader(new InputStreamReader(in, "UTF-8"));
        StringBuilder responseStrBuilder = new StringBuilder();

        String inputStr;
        while ((inputStr = streamReader.readLine()) != null)
            responseStrBuilder.append(inputStr);

        JSONObject jsonObject = new JSONObject(responseStrBuilder.toString());
        String license = (String) jsonObject.get("license");

        return Base64.decode(license, Base64.DEFAULT);
```

So in conclusion, to play widevine encrypted content just pass the license key (in our case Base64 encoded) to this byte[] response in order to playback the encrypted content. 

```
// Provide the decoded Base64 license key.
mediaDrm.provideKeyResponse(sessionId, (byte[]) response);
```

Thanks again for the help and hopefully this can speed up some else work!
