### ISSUE TITLE
Memory issues with ExoPlayerImplInternal and DefaultTrackOutput

### ISSUE THREAD

**Issue by RomiValladares** [google/ExoPlayer#2825]
### Question description
I'm using SimpleExoPlayerView in each Fragment inside a ViewPager that uses a FragmentStatePagerAdapter.

After some swipes, the memory goes from 30MB to 110MB, and then I start getting the following error:

```
E/ExoPlayerImplInternal: Renderer error.
  com.google.android.exoplayer2.ExoPlaybackException
      at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:382)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:955)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:510)
      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
      at android.os.Handler.dispatchMessage(Handler.java:98)
      at android.os.Looper.loop(Looper.java:148)
      at android.os.HandlerThread.run(HandlerThread.java:61)
   Caused by: com.google.android.exoplayer2.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(48000, 12, 48000)
      at com.google.android.exoplayer2.audio.AudioTrack.checkAudioTrackInitialized(AudioTrack.java:1358)
      at com.google.android.exoplayer2.audio.AudioTrack.initialize(AudioTrack.java:648)
      at com.google.android.exoplayer2.audio.AudioTrack.handleBuffer(AudioTrack.java:722)
      at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:376)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:955) 
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:510) 
      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
      at android.os.Handler.dispatchMessage(Handler.java:98) 
      at android.os.Looper.loop(Looper.java:148) 
      at android.os.HandlerThread.run(HandlerThread.java:61) 
```

Obviously there is something wrong with my code, and I'm not properly releasing the player. I can see that I have 120 references to DefaultTrackOutput, though I have 6 Fragments (with 2 SimpleExoPlayers each):

<img width="1217" alt="screen shot 2017-05-14 at 6 07 28 pm" src="https://cloud.githubusercontent.com/assets/8409964/26037738/3f4c3e30-38d0-11e7-9c2c-b9226005e747.png">
<img width="1221" alt="screen shot 2017-05-14 at 6 23 31 pm" src="https://cloud.githubusercontent.com/assets/8409964/26037831/7e9b8b16-38d2-11e7-98e4-7ebbddd64214.png">

This is how I'm releasing the player:
```
    public void release() {
        if (player != null) {
            player.prepare(null);
            player.removeListener(playerEventListener);
            player.stop();
            player.release();
            player = null;
        }
        setPlayerPlaying(false);
        if (simpleExoPlayerView != null) {
            simpleExoPlayerView.setPlayer(null);
            simpleExoPlayerView = null;
        }
        playerEventListener = null;

        removeExoPlayerLayout();

        if (uiProgressHandler != null) {
            uiProgressHandler.removeCallbacks(uiProgressRunner);
            uiProgressHandler.removeCallbacks(null);
            uiProgressHandler = null;
        }
        uiProgressRunner = null;
        handler = null;
        listener = null;

        released = true;
    }
```

I call that method on Fragment onDestroy, onDetach and onDestroyView.

I guess it's probably impossible to guess what the problem is, but any input is useful, I've been days trying to solve it. If someone has the time, I could make a sample project with the ViewPager.

### Version of ExoPlayer being used
r2.4.0

### hprof file
When the app reaches ~110MB

[Dropbox](https://www.dropbox.com/s/y609zp0uq2qb88x/discoversdk.hprof?dl=0) or [ufile](https://ufile.io/3ai7l)

**Comment by ojw28** [comment]
The hprof file shows there are 30 instances of `SimpleExoPlayer`, so yes it looks like application code is just not properly releasing player. Note that this is overkill for releasing a player:

```
player.prepare(null);
player.removeListener(playerEventListener);
player.stop();
player.release();
player = null;
```

Just calling `player.release` and then null-ing the reference is sufficient. Passing `null` to `player.prepare` is incorrect and will actually cause an internal playback failure, so you should definitely remove that line.

I'm going to close this, since it's not an ExoPlayer issue. If you need help debugging your own code, I'd suggest asking on StackOverflow.

**Comment by botondbutuza** [comment]
@ojw28 Sorry just piggybacking on this releasing a player question: we still need to remove `EventListener`s manually, right? I can't see anything in the `player.release()` code that'd indicate that `EventListener`s are cleaned up.

**Comment by ojw28** [comment]
It wont do any harm. I don't see why it would be necessary in general though (and our demo app doesn't unregister). The player holding a reference to a listener isn't going to stop the player from being GC'd. It's references in the opposite direction that you'd need to be wary of.
