### ISSUE TITLE
AudioFlinger can not create track

### ISSUE THREAD

**Issue by Merseyside** [google/ExoPlayer#2859]
My application is the music player. So tracks playing one by one. After for example 20 tracks playback stops and do not playing anything and logcat throws this errors:

`E/AudioTrack: AudioFlinger could not create track, status: -12
E/AudioTrack-JNI: Error -12 initializing AudioTrack
E/android.media.AudioTrack: Error code -20 when initializing AudioTrack.
E/ExoPlayerImplInternal: Renderer error.
                         com.google.android.exoplayer2.ExoPlaybackException
                             at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:382)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:955)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:510)
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                             at android.os.Handler.dispatchMessage(Handler.java:98)
                             at android.os.Looper.loop(Looper.java:148)
                             at android.os.HandlerThread.run(HandlerThread.java:61)
                          Caused by: com.google.android.exoplayer2.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 56704)
                             at com.google.android.exoplayer2.audio.AudioTrack.checkAudioTrackInitialized(AudioTrack.java:1358)
                             at com.google.android.exoplayer2.audio.AudioTrack.initialize(AudioTrack.java:648)
                             at com.google.android.exoplayer2.audio.AudioTrack.handleBuffer(AudioTrack.java:722)
                             at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:376)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:955) 
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:510) 
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                             at android.os.Looper.loop(Looper.java:148) 
                             at android.os.HandlerThread.run(HandlerThread.java:61) `
What happens?

**Comment by andrewlewis** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
 
If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

Note: if I had to guess based on the limited information provided, I'd say the device is running out of memory for AudioTrack buffers perhaps due to not releasing the players when you have finished with them.

**Comment by Merseyside** [comment]
### Issue description
I playing tracks one by one. In a moment when track 1 close to the end of playback one more ExoPlayer object start to play 'transition' sound from assets. in a moment when transition is close to end track 2 starts play. As result before ~ 20 tracks playback stops and i got errors in mu logcat.

### Reproduction steps
Start playback as decribed above and wait when ~ 20 tracks will be played.

### Link to test content
Any mp3 tracks you want

### Version of ExoPlayer being used
2.4.0

### Device(s) and version(s) of Android being used
Asus Zenfone 2 Selfie 6.0.1

### A full bug report captured from the device
`E/AudioTrack: AudioFlinger could not create track, status: -12 E/AudioTrack-JNI: Error -12 initializing AudioTrack E/android.media.AudioTrack: Error code -20 when initializing AudioTrack. E/ExoPlayerImplInternal: Renderer error. com.google.android.exoplayer2.ExoPlaybackException at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:382) at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:955) at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:510) at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) at android.os.Handler.dispatchMessage(Handler.java:98) at android.os.Looper.loop(Looper.java:148) at android.os.HandlerThread.run(HandlerThread.java:61) Caused by: com.google.android.exoplayer2.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 56704) at com.google.android.exoplayer2.audio.AudioTrack.checkAudioTrackInitialized(AudioTrack.java:1358) at com.google.android.exoplayer2.audio.AudioTrack.initialize(AudioTrack.java:648) at com.google.android.exoplayer2.audio.AudioTrack.handleBuffer(AudioTrack.java:722) at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:376) at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:955)  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:510)  at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)  at android.os.Handler.dispatchMessage(Handler.java:98)  at android.os.Looper.loop(Looper.java:148)  at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by andrewlewis** [comment]
Please provide the output of `adb bugreport`.
