### ISSUE TITLE
Multiple playback problem

### ISSUE THREAD

**Issue by brystel** [google/ExoPlayer#286]
Hello,
Is there possibility to play multiple video / stream at the same time?

I have created activity which try to play one stream and one local video at this same time in splitted window mode. I use DefaultRendererBuilder. I have got ExoPlayer from master branch.

Stream: http://html5demos.com/assets/dizzy.mp4 (from demo)
Local video codec: H264 / MPEG AAC

If I use another media problem still happens.

I am attaching logs:

`
02-09 16:12:55.646    2439-2505/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
02-09 16:12:55.646    2439-2509/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
02-09 16:12:55.646    2439-2509/com.google.android.exoplayer.demo E/ACodec﹕ Unable to instantiate decoder 'OMX.amlogic.avc.decoder.awesome'.
02-09 16:12:55.646    2439-2508/com.google.android.exoplayer.demo E/MediaCodec﹕ Codec reported an error. (omx error 0x80001003, internalError -2147483648)
02-09 16:12:55.646    2439-2505/com.google.android.exoplayer.demo I/ACodec﹕ onConfigureComponent native-window finished OMX.amlogic.avc.decoder.awesome
02-09 16:12:55.676    2439-2502/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 949K, 29% free 2438K/3412K, paused 22ms, total 22ms
02-09 16:12:55.676    2439-2503/com.google.android.exoplayer.demo W/ALooperRoster﹕ ALooper::handler_id ALooperRoster::registerHandler 13
02-09 16:12:55.676    2439-2503/com.google.android.exoplayer.demo W/ALooperRoster﹕ ALooper::handler_id ALooperRoster::registerHandler 14
02-09 16:12:55.686    2439-2502/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, MediaFormat(video/avc, 120031, 1280, 720, -1.0, -1, -1, -1, -1, -1)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:298)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:648)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:435)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:412)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:398)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, MediaFormat(video/avc, 120031, 1280, 720, -1.0, -1, -1, -1, -1, -1)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:295)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:648)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:435)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:412)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:398)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.io.IOException: Failed to allocate component instance
            at android.media.MediaCodec.native_setup(Native Method)
            at android.media.MediaCodec.<init>(MediaCodec.java:210)
            at android.media.MediaCodec.createByCodecName(MediaCodec.java:204)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:289)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:648)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:435)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:412)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:398)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
02-09 16:12:55.686    2439-2513/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
02-09 16:12:55.686    2439-2513/com.google.android.exoplayer.demo I/omx_core﹕ OMX_Init 66 gInitCount=1
02-09 16:12:55.686    2439-2513/com.google.android.exoplayer.demo V/AML_all_components﹕ --------------------------------
    author:aml.sh multi-media team
    branch name:   * jb-mr1-amlogic
    git version:   abf96fd33617f43c76e4cb608f30de81c31d47e0
    last changed:  Date:   Fri Feb 21 15:29:20 2014 +0800
    build-time:     Mon Feb 24 12:47:11 CST 2014
    build-name:     spike.liao
    uncommitted-file-num:1
    cd /mnt/nfsroot/spike.liao/kk-amlogic
    hostname droid09-sz
    --------------------------------
02-09 16:12:55.696    2439-2513/com.google.android.exoplayer.demo I/omx_core﹕ Core library has 22 components
02-09 16:12:55.696    2439-2513/com.google.android.exoplayer.demo E/OMXMaster﹕ A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
02-09 16:12:55.696    2439-2513/com.google.android.exoplayer.demo W/ALooperRoster﹕ ALooper::handler_id ALooperRoster::registerHandler 15
02-09 16:12:55.696    2439-2513/com.google.android.exoplayer.demo I/ACodec﹕ onConfigureComponent native-window finished OMX.google.aac.decoder
02-09 16:12:55.706    2439-2514/com.google.android.exoplayer.demo I/SoftAAC2﹕ Reconfiguring decoder: 0->44100 Hz, 0->2 channels
02-09 16:12:55.726    2439-2439/com.google.android.exoplayer.demo E/PlayerActivity﹕ Playback failed
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, MediaFormat(video/avc, 120031, 1280, 720, -1.0, -1, -1, -1, -1, -1)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:298)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:648)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:435)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:412)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:398)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, MediaFormat(video/avc, 120031, 1280, 720, -1.0, -1, -1, -1, -1, -1)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:295)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:648)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:435)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:412)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:398)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.io.IOException: Failed to allocate component instance
            at android.media.MediaCodec.native_setup(Native Method)
            at android.media.MediaCodec.<init>(MediaCodec.java:210)
            at android.media.MediaCodec.createByCodecName(MediaCodec.java:204)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:289)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:648)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:435)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:412)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:398)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
`

**Comment by ojw28** [comment]
See https://github.com/google/ExoPlayer/issues/273
