### ISSUE TITLE
Getting error while implementing Seekbar

### ISSUE THREAD

**Issue by Pash97** [google/ExoPlayer#2862]
**Attaching my logcat please tell me where am going wrong**

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.demo.drm/com.example.PlayerActivity}: java.lang.ClassCastException: com.google.android.exoplayer2.ui.DefaultTimeBar cannot be cast to com.example.previewseekbar.PreviewSeekBar
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ojw28** [comment]
Please stop filing this type of question here. The purpose of this issue tracker is to report actual issues with the ExoPlayer library, not as a place where you can get general programming help and your own code debugged. You need to ask this kind of question on StackOverflow.
