### ISSUE TITLE
Failed to play widevine dash secure uhd mp4,h265 sample

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#2879]
I tried to play secure uhd sample content but failed in demo app 1.5.16.

I changed MediaFormat KEY_MAX_INPUT_SIZE(MediaCodecVideoTrackRenderer.maybeSetMaxInputSize) but didn't work.

Do you know how to solve it? I do not know which part is the problem.

````
05-29 17:18:01.027 6343-6619/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                        java.lang.IllegalStateException: Buffer too small (2468160 < 2496983)
                                                                                            at com.google.android.exoplayer.SampleHolder.createReplacementBuffer(SampleHolder.java:148)
                                                                                            at com.google.android.exoplayer.SampleHolder.ensureSpaceForWrite(SampleHolder.java:100)
                                                                                            at com.google.android.exoplayer.extractor.RollingSampleBuffer.readSample(RollingSampleBuffer.java:192)
                                                                                            at com.google.android.exoplayer.extractor.DefaultTrackOutput.getSample(DefaultTrackOutput.java:144)
                                                                                            at com.google.android.exoplayer.chunk.ChunkSampleSource.readData(ChunkSampleSource.java:287)
                                                                                            at com.google.android.exoplayer.SampleSourceTrackRenderer.readSource(SampleSourceTrackRenderer.java:208)
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:637)
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:531)
                                                                                            at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
05-29 17:18:01.051 6343-6343/com.google.android.exoplayer.demo E/EventLogger: playerFailed [9.52]
                                                                              com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException: Buffer too small (2468160 < 2496983)
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:244)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                               Caused by: java.lang.IllegalStateException: Buffer too small (2468160 < 2496983)
                                                                                  at com.google.android.exoplayer.SampleHolder.createReplacementBuffer(SampleHolder.java:148)
                                                                                  at com.google.android.exoplayer.SampleHolder.ensureSpaceForWrite(SampleHolder.java:100)
                                                                                  at com.google.android.exoplayer.extractor.RollingSampleBuffer.readSample(RollingSampleBuffer.java:192)
                                                                                  at com.google.android.exoplayer.extractor.DefaultTrackOutput.getSample(DefaultTrackOutput.java:144)
                                                                                  at com.google.android.exoplayer.chunk.ChunkSampleSource.readData(ChunkSampleSource.java:287)
                                                                                  at com.google.android.exoplayer.SampleSourceTrackRenderer.readSource(SampleSourceTrackRenderer.java:208)
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:637)
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:531)
                                                                                  at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 

````

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
 
If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
