### ISSUE TITLE
ExoPlayer2 video get stuck when it reaches maximum bit rate, but audio keeps on playing.

### ISSUE THREAD

**Issue by sidpram** [google/ExoPlayer#2912]
Issue description:

When playing a specific HLS stream, ExoPlayer video get stuck when it reaches maximum bit rate. 1920x1080 video resolution in this case. But the audio keeps on playing. 

Reproduction steps

The issue can be reproduced in the demo app by playing the below HLS stream.

Link to test content
https://d1jm4snawz7e2z.cloudfront.net/hls/zeeredcarpet/clip1.m3u8

Please add the below code in media.exolist.json file.
 "name": "HLS",
    "samples": [
      {
        "name": "Zee Carpet HLS",
        "uri": "https://d1jm4snawz7e2z.cloudfront.net/hls/zeeredcarpet/clip1.m3u8"
      },

Version of ExoPlayer being used
2.4.1 in production release stable app

Device(s) and version(s) of Android being used

The issue reproduces consistently on Amlogic smart box Android 5.1.1, API 22.

**Comment by AquilesCanta** [comment]
Please include all the information required in the issue template. The bugreport is missing.

**Comment by sidpram** [comment]
Added bug report
[Bug_report_2.txt](https://github.com/google/ExoPlayer/files/1060659/Bug_report_2.txt)

**Comment by ojw28** [comment]
The only thing of note in the attached log is a playback failure due to a networking problem, which is outside of our control:

```
playerFailed [71.70]
com.google.android.exoplayer2.ExoPlaybackException
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:135)
    at android.os.HandlerThread.run(HandlerThread.java:61)
 Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://d1jm4snawz7e2z.cloudfront.net/hls/zeeredcarpet/clip1_400k00004.ts
    at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
    at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:253)
    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:202)
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
 Caused by: java.net.ConnectException: failed to connect to d1jm4snawz7e2z.cloudfront.net/52.222.136.57 (port 443) after 8000ms: isConnected failed: ENETUNREACH (Network is unreachable)
    at libcore.io.IoBridge.isConnected(IoBridge.java:238)
    at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
    at libcore.io.IoBridge.connect(IoBridge.java:122)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
    at java.net.Socket.connect(Socket.java:882)
    at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
    at com.android.okhttp.Connection.connect(Connection.java:152)
    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
    at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
    at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
    at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:429)
    at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:350)
    at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
    at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)†
    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:253)†
    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:202)†
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)†
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)†
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)†
    at java.lang.Thread.run(Thread.java:818)†
 Caused by: android.system.ErrnoException: isConnected failed: ENETUNREACH (Network is unreachable)
    at libcore.io.IoBridge.isConnected(IoBridge.java:223)
    at libcore.io.IoBridge.connectErrno(IoBridge.java:171)†
    at libcore.io.IoBridge.connect(IoBridge.java:122)†
```

The attached log does not appear to capture the issue described. It's also not a proper bug report (you should use `adb bugreport` to capture one, as explained in the issue template).

Closing, since there's nothing actionable we can do here.
