### ISSUE TITLE
Getting invalid time of seekbar & Video can't be played of any format.

### ISSUE THREAD

**Issue by maven-y** [google/ExoPlayer#2916]
Device Detail:

Version : Samsung 4.4.4 

video url https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears_sd.mpd 

`06-07 17:38:33.106 21844-26400/? E/ExoPlayerImplInternal: Renderer error.
                                                          com.google.android.exoplayer2.ExoPlaybackException
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:754)
                                                              at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:219)
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:491)
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:466)
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                              at android.os.Looper.loop(Looper.java:145)
                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                              at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                           Caused by: java.lang.IllegalStateException: Media requires a DrmSessionManager
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:754) 
                                                              at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:219) 
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:491) 
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:466) 
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                              at android.os.Looper.loop(Looper.java:145) 
                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                              at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
06-07 17:38:33.106 21844-21844/? E/EventLogger: playerFailed [2.70]
                                                com.google.android.exoplayer2.ExoPlaybackException
                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:754)
                                                    at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:219)
                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:491)
                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:466)
                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                    at android.os.Looper.loop(Looper.java:145)
                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                    at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                 Caused by: java.lang.IllegalStateException: Media requires a DrmSessionManager
                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:754) 
                                                    at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:219) 
                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:491) 
                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:466) 
                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                    at android.os.Looper.loop(Looper.java:145) 
                                                    at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                    at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)`

ScreenShots:

![mem](https://user-images.githubusercontent.com/6801363/26877883-050e977c-4ba9-11e7-8bd0-470bd636e76c.PNG)
![cpu](https://user-images.githubusercontent.com/6801363/26877888-0931c1ee-4ba9-11e7-84eb-bf46b8176361.PNG)

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
 
If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
