### ISSUE TITLE
UnrecognizedInputFormatException on mp3 that plays in other players

### ISSUE THREAD

**Issue by rustyshelf** [google/ExoPlayer#2951]
### Issue description
The linked MP3 file causes the following exception when loaded in ExoPlayer:
```
Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:722)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:645)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                     at java.lang.Thread.run(Thread.java:762)
```

It plays correctly through a lot of other players though.

### Reproduction steps
Play linked MP3 either downloaded or streamed, makes no difference.

### Link to test content
http://traffic.libsyn.com/wtfpod/WTF_-_EPISODE_819_ARIEL_LEVE.mp3?dest-id=14434

### Version of ExoPlayer being used
Version 2.4.1

### Device(s) and version(s) of Android being used
Devices tested: Samsung Galaxy S8, Pixel. This should fail on all devices though, as it seems ExoPlayer specific.

**Comment by andrewlewis** [comment]
The ID3 header indicates that the ID3 data ends at 317827 bytes but it actually ends at 325982 bytes. So I think this file is technically not valid.

You can get it to play by increasing `Mp3Extractor.MAX_SNIFF_BYTES`. The current value is set such that it searches up to the maximum size of one MPEG audio frame to resynchronize (4 KB). A larger search distance increases the time and space cost, which is bad if you are trying to play a format that is accepted by an extractor later in the list. It looks like the platform searches up to 128 KB.

Assuming this is a widespread problem, I will increase the search distance a bit so that this file plays. If you have any information about how the file was produced it would be useful to know so we can determine the search distance needed to work around whatever bug that set the wrong ID3 size.

**Comment by rustyshelf** [comment]
@andrewlewis the file is a podcast called "WTF with Marc Maron". It's one of the more popular podcasts out there with hundreds of thousands of listeners. We have roughly 50,000 of them on our platform and they aren't very happy at not being able to play these.

I'm not sure what process he uses to encode his files though I could probably find out. I'm also not sure how many other podcasters are having this same issue.

If it's possible to support this without introducing too many headaches that would be amazing.

**Comment by ojw28** [comment]
Andrew increased the sniffing distance a little. The chosen value is arbitrary though, and obviously playback will still fail if the same problem occurs but where the ID3 header is out by a larger value (unless we're missing something, the "proper" fix is to fix the media).
