### ISSUE TITLE
Crash in DVB subtitle handler

### ISSUE THREAD

**Issue by goffioul** [google/ExoPlayer#2957]
ExoPlayer version: 2.4.1
Sample stream: https://drive.google.com/open?id=0BwljeX6541LubXprdmEtTFdBT00
Steps to reproduce:
- start playback with plain HTTP
- enable a subtitle track

Backtrace:

	FATAL EXCEPTION: Thread-4
	Process: com.google.android.exoplayer2.demo, PID: 24109
	java.lang.ArrayIndexOutOfBoundsException: length=4; index=36
		at com.google.android.exoplayer2.text.dvb.DvbParser.paint8BitPixelCodeString(DvbParser.java:789)
		at com.google.android.exoplayer2.text.dvb.DvbParser.paintPixelDataSubBlock(DvbParser.java:638)
		at com.google.android.exoplayer2.text.dvb.DvbParser.paintPixelDataSubBlocks(DvbParser.java:592)
		at com.google.android.exoplayer2.text.dvb.DvbParser.decode(DvbParser.java:187)
		at com.google.android.exoplayer2.text.dvb.DvbDecoder.decode(DvbDecoder.java:47)
		at com.google.android.exoplayer2.text.dvb.DvbDecoder.decode(DvbDecoder.java:25)
		at com.google.android.exoplayer2.text.SimpleSubtitleDecoder.decode(SimpleSubtitleDecoder.java:70)
		at com.google.android.exoplayer2.text.SimpleSubtitleDecoder.decode(SimpleSubtitleDecoder.java:25)
		at com.google.android.exoplayer2.decoder.SimpleDecoder.decode(SimpleDecoder.java:222)
		at com.google.android.exoplayer2.decoder.SimpleDecoder.run(SimpleDecoder.java:188)
		at com.google.android.exoplayer2.decoder.SimpleDecoder.access$000(SimpleDecoder.java:25)
		at com.google.android.exoplayer2.decoder.SimpleDecoder$1.run(SimpleDecoder.java:66)

**Comment by ojw28** [comment]
There's a small issue in the DVB parser. I'll push a fix shortly. Brilliantly, there's also a small bug in the DVB spec itself, which corresponds to half of the issue :)!

**Comment by goffioul** [comment]
Verified in branch dev-v2. Subtitles now working fine. Thanks.
