### ISSUE TITLE
some device  exoplayer can not play

### ISSUE THREAD

**Issue by pheart** [google/ExoPlayer#2997]
6827/? E/MtkOmxAudioDecBase: Decoder Component Dec Error!
06-25 22:41:03.534 6567-6825/com.karaoke.singplus.test E/ACodec: [OMX.MTK.AUDIO.DECODER.AAC] ERROR(0x80001005)
06-25 22:41:03.534 6567-6825/com.karaoke.singplus.test E/MediaCodec: Codec reported an error. (omx error 0x80001005, internalError -1104)
06-25 22:41:03.535 135-6827/? E/MtkOmxAudioDecBase: Decoder Component Dec Error!
06-25 22:41:03.536 6567-6796/com.karaoke.singplus.test E/ExoPlayerImplInternal: Internal runtime error.
                                                                                java.lang.IllegalStateException
                                                                                    at android.media.MediaCodec.dequeueInputBuffer(Native Method)
                                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:557)
                                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:507)
                                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:466)
                                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:153)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:60)
                                                                                    at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
