### ISSUE TITLE
ArrayIndexOutOfBoundsException while playing MP4 file

### ISSUE THREAD

**Issue by zijing07** [google/ExoPlayer#3013]
### Issue description
When I use the demo app to play the [mp4 file](http://video.baixing.net/FoQpGjojBYOWlHhOT7HmS4Pk0kkI.mp4), the screen is black. 

I have checked the #2381 and #554 which are probably related to my problem, but I got nothing from them. 

However, I wondered if the media is broken, I tried both Chrome and iOS, the video can be playback normally in iOS with the system player while Chrome cannot neither play this video.

Information about this video: [link](http://video.baixing.net/FoQpGjojBYOWlHhOT7HmS4Pk0kkI.mp4?avinfo)

I also tried to remove the audio stream from the video, ExoPlayer can play if normally. The same video without audio stream is [here](http://7oxj36.com1.z0.glb.clouddn.com/only_video_car.mp4)

### Reproduction steps
1. modify `media.exolist.json` to 
    ```
    ...
    "name": "YouTube DASH",
    "samples": [
      {
        "name": "I can not play this",
        "uri": "http://video.baixing.net/FoQpGjojBYOWlHhOT7HmS4Pk0kkI.mp4"
      },
    ...
    ```
2. click the video, `PlayerActivity` is shown but with a black player screen

### Version of ExoPlayer being used
v2.4.3

### Device(s) and version(s) of Android being used
Xiaomi Redmi 3S Android 6.0.1 API 23

### A full bug report captured from the device
```
07-03 15:02:24.795 28735-15934/com.google.android.exoplayer2.demo E/LoadTask: Unexpected exception loading stream
                                                                              java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
                                                                                  at com.google.android.exoplayer2.util.ParsableBitArray.readBits(ParsableBitArray.java:172)
                                                                                  at com.google.android.exoplayer2.util.CodecSpecificDataUtil.getAacSamplingFrequency(CodecSpecificDataUtil.java:262)
                                                                                  at com.google.android.exoplayer2.util.CodecSpecificDataUtil.parseAacAudioSpecificConfig(CodecSpecificDataUtil.java:100)
                                                                                  at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseAudioSampleEntry(AtomParsers.java:894)
                                                                                  at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:612)
                                                                                  at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:89)
                                                                                  at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:333)
                                                                                  at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:276)
                                                                                  at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:267)
                                                                                  at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:147)
                                                                                  at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:652)
                                                                                  at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                  at java.lang.Thread.run(Thread.java:818)
07-03 15:02:24.796 28735-28735/com.google.android.exoplayer2.demo E/EventLogger: internalError [0.18, loadError]
                                                                                 com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: length=2; index=2
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
                                                                                     at com.google.android.exoplayer2.util.ParsableBitArray.readBits(ParsableBitArray.java:172)
                                                                                     at com.google.android.exoplayer2.util.CodecSpecificDataUtil.getAacSamplingFrequency(CodecSpecificDataUtil.java:262)
                                                                                     at com.google.android.exoplayer2.util.CodecSpecificDataUtil.parseAacAudioSpecificConfig(CodecSpecificDataUtil.java:100)
                                                                                     at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseAudioSampleEntry(AtomParsers.java:894)
                                                                                     at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:612)
                                                                                     at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:89)
                                                                                     at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:333)
                                                                                     at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:276)
                                                                                     at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:267)
                                                                                     at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:147)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:652)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                     at java.lang.Thread.run(Thread.java:818) 
07-03 15:02:24.996 28735-28735/com.google.android.exoplayer2.demo E/EventLogger: internalError [0.38, loadError]
                                                                                 com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: com.google.android.exoplayer2.upstream.DataSourceException
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:214)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640) 
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                     at java.lang.Thread.run(Thread.java:818) 
07-03 15:02:26.026 28735-28735/com.google.android.exoplayer2.demo E/EventLogger: internalError [1.41, loadError]
                                                                                 com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: com.google.android.exoplayer2.upstream.DataSourceException
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:214)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640) 
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                     at java.lang.Thread.run(Thread.java:818) 
07-03 15:02:28.186 28735-28735/com.google.android.exoplayer2.demo E/EventLogger: internalError [3.57, loadError]
                                                                                 com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: com.google.android.exoplayer2.upstream.DataSourceException
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:214)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640) 
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                     at java.lang.Thread.run(Thread.java:818) 
07-03 15:02:28.192 28735-15933/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Source error.
                                                                                           com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
                                                                                               at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                                               at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                               at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640)
                                                                                               at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                               at java.lang.Thread.run(Thread.java:818)
                                                                                            Caused by: com.google.android.exoplayer2.upstream.DataSourceException
                                                                                               at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:214)
                                                                                               at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                                                                                               at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640) 
                                                                                               at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                               at java.lang.Thread.run(Thread.java:818) 
07-03 15:02:28.194 28735-28735/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [3.58]
                                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                  Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: com.google.android.exoplayer2.upstream.DataSourceException
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:214)
```

**Comment by ojw28** [comment]
Looks like broken media to me; it appears to declare a video track with a broken audio sample entry.

**Comment by zijing07** [comment]
Thank you very much for the rapid reply!
