### ISSUE TITLE
Support lacing in Matroska Blocks

### ISSUE THREAD

**Issue by langxuelang** [google/ExoPlayer#3026]
when I play some mkv files,exoplayer report error below.

```
07-05 16:12:40.148 4984-6060/com.Android56 E/ExoPlayerImplInternal: Internal track renderer error.
                                                                    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.ParserException: Lacing only supported in SimpleBlocks.
                                                                        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:262)
                                                                        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:144)
                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:439)
                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                        at android.os.Looper.loop(Looper.java:156)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                     Caused by: com.google.android.exoplayer.ParserException: Lacing only supported in SimpleBlocks.
                                                                        at com.google.android.exoplayer.extractor.webm.WebmExtractor.binaryElement(WebmExtractor.java:901)
                                                                        at com.google.android.exoplayer.extractor.webm.WebmExtractor$InnerEbmlReaderOutput.binaryElement(WebmExtractor.java:1421)
                                                                        at com.google.android.exoplayer.extractor.webm.DefaultEbmlReader.read(DefaultEbmlReader.java:123)
                                                                        at com.google.android.exoplayer.extractor.webm.WebmExtractor.read(WebmExtractor.java:363)
                                                                        at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:835)
                                                                        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                        at java.lang.Thread.run(Thread.java:776)
```

and this is the link of file 
https://drive.google.com/open?id=0BwneL-jNaOWGMXRXN0RrYWNnUTQ

**Comment by andrewlewis** [comment]
The relevant error is "Lacing only supported in SimpleBlocks". Marking as an enhancement to support lacing in Blocks, but this seems to be rarely used so it's unlikely we will get round to it soon. (And if we do implement this, you'd need to upgrade to v2 to use it.)

If you need to use lacing, is it feasible for you to change the container to use only SimpleBlocks?

**Comment by langxuelang** [comment]
@andrewlewis thanks for your replying.So currently I will notice user not support this video format.

**Comment by anonym24** [comment]
just downloaded random movie and couldn't play it, got this error
so it's already v2 and not supported yet, so problem isn't going to be solved soon?

**Comment by ojw28** [comment]
As per response above, this is low priority and is unlikely to be resolved soon.

**Comment by anonym24** [comment]
@ojw28 well I downloaded one more random movie (mkv) and again this error, so it's not that rarely, I believe it will happen quite often

**Comment by ojw28** [comment]
We've received two reports of this error in the past six months, which does not suggest this is a widely used feature.

**Comment by anonym24** [comment]
@ojw28 I think not many developers tested with 2-5 gb (bdrip 720p) MKVs, for me the problem happened with such videos

**Comment by NitroXenon** [comment]
The exception is thrown when I try to play a link today.
Sample video:
https://docs.google.com/file/d/0B859uoPMN-bfWTZqRE5rdWpaMkU/preview

**Comment by andrewlewis** [comment]
I'm afraid we're still treating this as low priority. We can revisit it if someone can provide evidence that there is a lot of demand for playing files with this feature. I think we're also happy to accept pull requests that cleanly add this functionality to `MatroskaExtractor`. Sorry not to be more helpful.

**Comment by hahafamilia** [comment]
I am interested in this issue.
I also have the same problem.
The version I am using now is 2.7.3.
Is there a release version that updates this issue?

**Comment by andrewlewis** [comment]
No. We're still treating this as a low priority feature request.

**Comment by Cardas26** [comment]
I have this issue with a number of MKV's and would love to see it fixed. Exoplayer is used by the Emby  Android TV app to play movie files, and the issue has been reported on the Emby forums a number of times: 

[Report 1](https://emby.media/community/index.php?/topic/68895-auto-boxsets-and-file-playback-issues/?p=690419)

[Report 2](https://emby.media/community/index.php?/topic/61599-long-waittime-for-remote-content/?p=606982)

[Report 3](https://emby.media/community/index.php?/topic/35206-movies-plays-on-1-shield-but-not-another/?p=332686)

[Report 4](https://emby.media/community/index.php?/topic/39381-stm-package-with-nvidia-shield-android-tv/?p=370081)

[Report 5](https://emby.media/community/index.php?/topic/54314-mkv-unexpectedly-transcoded/?p=527591)

Also on the Plex forums:

[Report 1](https://forums.plex.tv/t/playback-has-stopped-because-the-connection-to-the-plex-media-server-has-been-lost/223353/4)

[Report 2](https://forums.plex.tv/t/why-this-file-cant-play-direct-on-android/164444/10)

[Report 3](https://forums.plex.tv/t/cant-play-file-on-nvidia-shield-tv/170152)

I would certainly welcome this feature. I'm sure the users who reported their issues in the links above would too.

**Comment by andrewlewis** [comment]
Thanks for the information.

We are still treating this as a low priority feature request. I think we'd also welcome a pull request that adds support.

[Also tracked by internal issue: b/122814967.]

**Comment by nimaaaaw** [comment]
@andrewlewis Hi there,
are you still treating this issue as a low priority?
cause I get this exception for almost half of the mkv movie files that are larger than 100mb
and please if you dont have plans to add this support, give me a heads up to fix it myself

thanks in advance

**Comment by ojw28** [comment]
> are you still treating this issue as a low priority?

Yes, as per what Andrew's already written above. We have no near term plans to work on this.

**Comment by ojw28** [comment]
This is supported in `dev-v2`.

**Comment by ojw28** [comment]
This is also supported in our `2.11.0` release.
