### ISSUE TITLE
ExoPlayerImplInternal: Internal runtime error.   java.lang.IllegalStateException at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)

### ISSUE THREAD

**Issue by Dusam** [google/ExoPlayer#3032]
ExoPlayer version: release-v2
Device:ASUS_Z017DA  Android version:6.0.1
Device:HTC_M8x  Android version:6.0

I am using Android JobScheduler and WindowManager to do background test with ExoPlayer, I set the test duration is 30 sec, but if it start background test, it was failed in 4-10 sec.

Here is the error code:

> 07-06 09:07:25.131 25657-26229/ E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
07-06 09:07:25.131 25657-26229/ E/ACodec: queueBuffer failed in onOutputBufferDrained: -19
07-06 09:07:25.131 25657-26229/ E/ACodec: signalError(omxError 0x80001001, internalError -19)
07-06 09:07:25.131 25657-26228/ E/MediaCodec: Codec reported err 0xffffffed, actionCode 0, while in state 6
07-06 09:07:25.139 25657-26173/ E/ExoPlayerImplInternal: Internal runtime error.
                                                                        java.lang.IllegalStateException
                                                                            at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
                                                                            at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2319)
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:548)
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:490)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                            at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
07-06 09:07:25.151 25657-26229/ E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f61c31000
07-06 09:07:25.151 25657-26229/ W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 35 to native window
07-06 09:07:25.151 25657-26229/ E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f61c10100
07-06 09:07:25.151 25657-26229/ W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 34 to native window
07-06 09:07:25.152 25657-26229/ E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f61c33160
07-06 09:07:25.152 25657-26229/ W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 32 to native window
07-06 09:07:25.152 25657-26229/ E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f61c331c0
07-06 09:07:25.152 25657-26229/ W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 31 to native window
07-06 09:07:25.152 25657-26229/ E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f61c33280
07-06 09:07:25.153 25657-26229/ W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 29 to native window
07-06 09:07:25.153 25657-26229/ E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f61c0f8c0
07-06 09:07:25.153 25657-26229/ W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 27 to native window
07-06 09:07:25.164 25657-26173/ E/ExoPlayerImplInternal: Stop failed.
                                                                        java.lang.IllegalStateException
                                                                            at android.media.MediaCodec.native_stop(Native Method)
                                                                            at android.media.MediaCodec.stop(MediaCodec.java:1901)
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:450)
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:405)
                                                                            at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:278)
                                                                            at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:145)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:673)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:648)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:352)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                            at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

I have already search problem if there the same problem, but not got the answer.
Please help me to solve this problem.
Thanks.

**Comment by andrewlewis** [comment]
We need the information requested in the issue template, especially a full bug report (`adb bugreport`) and preferably also instructions/code to reproduce this. Did you find it was not reproducible on other devices?

**Comment by Dusam** [comment]
It have the same problem on my partner device.
I use JobScheduler to play in background with close the screen.
I use handler to count 30 sec, then call `player.stop()` and `player.release()` to stop playing video.
but it always just only play 4-10 sec and then stop play video.
because if not set view to player, it can't use `player.getCurrentPosition()` to get the video current duration, so I use WindowManager and set player in WindowManager. I set it heigh and width = 1, make it can't be seen.

> 07-06 16:15:22.963 15605-16135/ E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
07-06 16:15:22.963 15605-16135/ E/ACodec: queueBuffer failed in onOutputBufferDrained: -19
07-06 16:15:22.963 15605-16135/ E/ACodec: signalError(omxError 0x80001001, internalError -19)
07-06 16:15:22.963 15605-16134/ E/MediaCodec: Codec reported err 0xffffffed, actionCode 0, while in state 6
07-06 16:15:22.965 15605-16065/ E/ExoPlayerImplInternal: Internal runtime error.
                                                                        java.lang.IllegalStateException
                                                                            at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
                                                                            at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2319)
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:548)
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:490)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                            at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
07-06 16:15:22.981 15605-16135/ E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f71b69b80
07-06 16:15:22.981 15605-16135/ W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 34 to native window
07-06 16:15:22.982 15605-16135/ E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f71b7bde0
07-06 16:15:22.982 15605-16135/ W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 33 to native window
07-06 16:15:22.982 15605-16135/ E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f71b7be40
07-06 16:15:22.982 15605-16135/ W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 32 to native window
07-06 16:15:22.982 15605-16135/ E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f71b7bf00
07-06 16:15:22.982 15605-16135/ W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 31 to native window
07-06 16:15:22.983 15605-16135/ E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f71b7cc80
07-06 16:15:22.983 15605-16135/ W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 28 to native window
07-06 16:15:22.983 15605-16135/ E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f71b7cce0
07-06 16:15:22.983 15605-16135/ W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 27 to native window
07-06 16:15:22.993 15605-15605/ I/VideoMOSTest: playTime = 6220, testTime = 7528
07-06 16:15:22.994 15605-16065/ E/ExoPlayerImplInternal: Stop failed.
                                                                        java.lang.IllegalStateException
                                                                            at android.media.MediaCodec.native_stop(Native Method)
                                                                            at android.media.MediaCodec.stop(MediaCodec.java:1901)
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:450)
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:405)
                                                                            at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:278)
                                                                            at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:145)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:673)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:648)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:352)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                            at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
07-06 16:15:23.010 15605-15605/ I/ current_state = PLAYER_IDLE
07-06 16:15:23.053 15605-15605/ I/ Stop BrackgroundTest.
07-06 16:15:23.294 15605-15605/ I/ play is null.

**Comment by ojw28** [comment]
It's really unclear what you're doing (and why), but that failure is indicative of you having told the player to render into an invalid `Surface`. How are you setting the surface on the player, and why are you setting one if you're playing in the background?

**Comment by ojw28** [comment]
As @andrewlewis noted, we really need you to fill in the issue template properly. The issue template *explicitly* states that copy/pasting logcat is not sufficient logging to attach when filing an issue. We also provide clear reproduction steps; the ones provided here are far to vague to allow us to easily reproduce what you're doing.

**Comment by Dusam** [comment]
I seem to find out where the problem is, I first close issue, if there are new problems to ask you again.
Thanks.

**Comment by michalliu** [comment]
This problems happens when you are trying to draw video on a surface already destroyed.
