### ISSUE TITLE
I can't set cookies for HLS stream, and server response 451 status code.

### ISSUE THREAD

**Issue by SvyatoslavLynda** [google/ExoPlayer#3045]
Hello, I work with api which used cookies for auth to stream content, but I can't put this cookies to HLS stream, I found one method how I can do it, but it doesn't work for me.
I added cookies to CookieStore.

Can you help me handle this flow?

**Comment by ojw28** [comment]
You may just need to set a default cookie manager. PlayerActivity in the demo app has code that does this, so I'd suggest taking a look at that.

Beyond that, there isn't sufficient information in this question for us to help. You'll have to properly describe how your authentication flow works if you require further assistance.

**Comment by SvyatoslavLynda** [comment]
Sorry my English is bad, but i try to describe my problem.

Yes I used default cookie manager for put my own cookies, but when I had try to play stream I had next 
```
exception: E/ExoPlayerImplInternal: Source error.
                                                                                           com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 451
                                                                                               at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:165)
                                                                                               at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                               at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
                                                                                               at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
                                                                                               at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114)
                                                                                               at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                               at java.lang.Thread.run(Thread.java:818)
```

**Comment by ojw28** [comment]
It looks like you're using the okhttp extension. If you don't use that (i.e. use DefaultHttpDataSource), does it work in that case? I suspect okhttp uses a different cookie store somewhere else?

It's not possible to provide further guidance without a clear description of how your authentication flow works, how you're setting the cookies and so on. Saying you put your own cookies, without describing exactly how you're doing it, is not enough information. Thanks!

**Comment by SvyatoslavLynda** [comment]
Sorry, problem has happened with server communicate.
