### ISSUE TITLE
DecoderInitializationException on Asus Zenpad S 8.0

### ISSUE THREAD

**Issue by Parseus** [google/ExoPlayer#3046]
### Issue description
Loading some videos on Asus Zenpad S 8.0 (e.g. videos recorded from the device's camera) cause ExoPlayer to throw DecoderInitializationException while trying to initialize ExoPlayer the OMX.Intel.VideoDecoder.AVC video codec:

```
> 07-11 14:24:08.235 11590-11730/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Renderer error.
                                                                                           com.google.android.exoplayer2.ExoPlaybackException
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:380)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:367)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:796)
                                                                                               at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:365)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:494)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                            Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Intel.VideoDecoder.AVC, Format(1, null, video/avc, -1, null, [1280, 720, -1.0], [-1, -1])
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:367) 
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:796) 
                                                                                               at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:365) 
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:494) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                            Caused by: android.media.MediaCodec$CodecException: Error 0xffffffc3
                                                                                               at android.media.MediaCodec.native_configure(Native Method)
                                                                                               at android.media.MediaCodec.configure(MediaCodec.java:1778)
                                                                                               at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:351)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:356)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:796) 
                                                                                               at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:365) 
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:494) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61) 
```
Android's MediaPlayer works fine with those videos.

### Reproduction steps
Add the attached sample file (made by recording from the device's camera) to the **media.exolist.json** file from the demo app and try to play it. Demo app should throw an exception in logcat and show a "Unable to instantiate deocder OMX.Intel.VideoDecoder.AVC" message in a Toast.

### Link to test content
[sample_zenpad.zip](https://github.com/google/ExoPlayer/files/1138854/sample_zenpad.zip)

### Version of ExoPlayer being used
2.4.3

### Device(s) and version(s) of Android being used
Asus Zenpad S 8.0 (Z580CA), Android 6.0.1

### A full bug report captured from the device
[adb_bugreport.txt](https://github.com/google/ExoPlayer/files/1138856/adb_bugreport.txt)

**Comment by ojw28** [comment]
Closing as part of a scrub of device specific issues that were filed more than 2 years ago.
