### ISSUE TITLE
Ooyala SDK for Exoplayer— NoClassDefFoundError: com.ooyala.android.player.exoplayer.ExoStreamPlayer

### ISSUE THREAD

**Issue by JhoangSS** [google/ExoPlayer#3054]
Question

**Situation:** Updating my Android Project from the old Ooyala SDK with VisualOn to the newest Ooyala SDK with Exoplyer. Plays a video through the Amazon Fire Stick.

**Problem:** After Updating the SDK, the project no longer works. We receive this error message:

.

**_"E/AndroidRuntime: FATAL EXCEPTION: main Process: com.ISN.firetv_isn, PID: 19650 java.lang.NoClassDefFoundError: com.ooyala.android.player.exoplayer.ExoStreamPlayer"
Looking at the NoClassDefFoundError, I feel like the code is missing an import of a package (But, overall I don't know)._**

.

**Please help me locate the problem. What could be the solution?**

.
.

**Android Studio Error Log:**

`07-12 11:16:36.087 24285-24285/com.ISN.firetv_isn E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.ISN.firetv_isn, PID: 24285
                                                                    java.lang.NoClassDefFoundError: com.ooyala.android.player.exoplayer.ExoStreamPlayer
                                                                        at com.ooyala.android.player.ExoMoviePlayer.createStreamPlayer(ExoMoviePlayer.java:12)
                                                                        at com.ooyala.android.player.MoviePlayer.init(MoviePlayer.java:50)
                                                                        at com.ooyala.android.OoyalaPlayerContextSwitcher.createAndInitPlayer(OoyalaPlayerContextSwitcher.java:107)
                                                                        at com.ooyala.android.OoyalaPlayer.prepareContent(OoyalaPlayer.java:1469)
                                                                        at com.ooyala.android.OoyalaPlayerContextSwitcher.processExitAdModes(OoyalaPlayerContextSwitcher.java:182)
                                                                        at com.ooyala.android.OoyalaPlayerContextSwitcher.processAdModes(OoyalaPlayerContextSwitcher.java:162)
                                                                        at com.ooyala.android.OoyalaPlayerContextSwitcher.startVideoWorkflow(OoyalaPlayerContextSwitcher.java:61)
                                                                        at com.ooyala.android.OoyalaPlayer.onCurrentItemChangeComplete(OoyalaPlayer.java:697)
                                                                        at com.ooyala.android.OoyalaPlayer.access$200(OoyalaPlayer.java:68)
                                                                        at com.ooyala.android.OoyalaPlayer$1$1.run(OoyalaPlayer.java:510)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5484)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-12 11:16:36.179 1005-1050/? E/InputDispatcher: channel 'bdff02a com.ISN.firetv_isn/com.isn.firetv_isn.KindlePlayer (server)' ~ Channel is unrecoverably broken and will be disposed!
`
.
.

**Android Studio Code:**

`

package com.isn.firetv_isn;

import android.content.Context;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.os.Bundle;
import android.app.Activity;
import android.util.Log;
import android.view.View;
import android.widget.Toast;

import com.ooyala.android.*;

import com.ooyala.android.OoyalaPlayer;
import com.ooyala.android.OoyalaPlayerLayout;
import com.ooyala.android.PlayerDomain;

import com.ooyala.android.ui.OoyalaPlayerLayoutController;

import java.util.Observable;
import java.util.Observer;

public class KindlePlayer extends Activity implements Observer {

    private static final String TAG = "This";
    private static final String EMBED  = "QwOWdodDqXerx-f5agXLKMBlfS-SXsoP";  //Embed Code, or Content ID
    private static final String PCODE  = "t3NzgxOleSzQvrNRj0uPn8xWnMlJ";
    private static final String DOMAIN = "http://www.ooyala.com";
    private OoyalaPlayer player;
    View decorView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION // hide nav bar
                | View.SYSTEM_UI_FLAG_FULLSCREEN // hide status bar
                | View.SYSTEM_UI_FLAG_IMMERSIVE);
        setContentView(R.layout.video_player);
        decorView = this.getWindow().getDecorView();

        OoyalaPlayerLayout playerLayout = (OoyalaPlayerLayout) findViewById(R.id.ooyalaPlayer);
        player = new OoyalaPlayer(PCODE, new PlayerDomain(DOMAIN));

        //set player controller
        OoyalaPlayerLayoutController playerLayoutController = new OoyalaPlayerLayoutController(playerLayout, player);
        playerLayoutController.setFullscreenButtonShowing(false);

        //player = playerLayoutController.getPlayer();
        if(isConnectedOnline()){
            ConnectivityManager cm = (ConnectivityManager) getSystemService(Context.CONNECTIVITY_SERVICE);
            if(cm.getActiveNetworkInfo().getType() == ConnectivityManager.TYPE_MOBILE){
                Toast.makeText(KindlePlayer.this, "Now using Mobile Network", Toast.LENGTH_SHORT).show();
            }
            if (player.setEmbedCode(EMBED)) {
                Log.d("Play", "Play");
                player.play();
            } else {
                Log.d(TAG, "Asset failed");
            }
        } else {
            Toast.makeText(KindlePlayer.this, "No Internet Connection", Toast.LENGTH_SHORT).show();
        }
    }

    @Override
    protected void onPause() {
        super.onPause();
        if (player != null) {
            Log.d("suspend", "suspend");
            player.pause();
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
        if (player != null) {
            Log.d("resume", "resume");
            player.resume();
            player.play();
        }
    }

    @Override
    public void update(Observable arg0, Object arg1) {
        if (arg0 != player) {
            return;
        }

        if (arg1 == OoyalaPlayer.TIME_CHANGED_NOTIFICATION_NAME) {
            return;
        }

        if (arg1 == OoyalaPlayer.ERROR_NOTIFICATION_NAME) {
            final String msg = "Error event received";
            if (player != null && player.getError() != null) {
                Log.e(TAG, msg, player.getError());
            }
            else {
                Log.e(TAG, msg);
            }
            return;
        }
        Log.d(KindlePlayer.class.getSimpleName(), "Notification Received: " + arg1 + " - state: " + player.getState());
    }

    @Override
    public void onWindowFocusChanged(boolean hasFocus) {
        super.onWindowFocusChanged(hasFocus);
        if (hasFocus) {
            decorView.setSystemUiVisibility(
                    View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                            | View.SYSTEM_UI_FLAG_IMMERSIVE
                            | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                            | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                            | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                            | View.SYSTEM_UI_FLAG_FULLSCREEN
                            | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);}
    }

    public boolean isConnectedOnline() {
        ConnectivityManager cm = (ConnectivityManager) getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkInfo ni = cm.getActiveNetworkInfo();
        return ni != null && ni.isConnected();
    }// end isConnectedOnline
}`

**Comment by ojw28** [comment]
This is a question relating to Ooyala, not Exoplayer. You'll need to ask somewhere Ooyala appropriate, rather than here.
