### ISSUE TITLE
Nimble Streamer WMSAUTH issue on IPV6 devices

### ISSUE THREAD

**Issue by jmso1921** [google/ExoPlayer#3066]
### Issue description
I use nimblestreamer.com and they have a protection called WMSAUTH, sort of like Akamai Auth Token based.  WMSPanel provides a token-based authorization to check each incoming connection signature against original published signature. The following Wowza entities may be protected: entire server, virtual host, application, application instance, separate stream. The protection consists of 3 parts - an agent on Wowza server side, a code snippet on a web page which generates a signature for the streaming media and a control interface to enable the protection.

As example, you have this URL for your live stream:
rtsp://ec2-test-ip.compute.amazonaws.com:1935/live/Stream1
The modified URL would be:
rtsp://ec2-test-ip.compute.amazonaws.com:1935/live?wmsAuthSign=c2VydmVyX3RpbWU9NS80LzIwMTIgODozMzowNSBBTSZoYXNoX3ZhbHVlPXE3MjN6aEVmdGFUOUJoWjBQTmw1TVE9PSZ2YWxpZG1pbnV0ZXM9MjA2/Stream1 

Example code is here: https://wmspanel.com/wmsauth/example_fancy

the key is generated by $ip . $key . $today . $validminutes;

key means the password which will be used later for setting up rule in control panel and validminutes means number of minutes while this signed link will be valid to let people read the page and start the playback. today is today's date and ip is the users ip.

The issue I'm having is on IPV6 devices the streams do not work.

My app as soon as you load it, it loads the wmsauth key, they you must select what video to watch and then hit play. It is not expiring the key because I put it to last for 20 minutes. I enabled IPV6 connections in the video server but it still doesn't work.

### Version of ExoPlayer being used
2.4.2

### Device(s) and version(s) of Android being used
Samsung Galaxy Note 3 Android 6.0.1
Samsung Galaxy Note 5 Android 6.0.1
Samsung Galaxy J7 V Android 7

### A full bug report captured from the device
07-14 15:22:06.934 10592-12914/com.jndev.mobapp E/ExoPlayerImplInternal: Source error.
                                                                         com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
                                                                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                             at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                             at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
                                                                             at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
                                                                             at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114)
                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                             at java.lang.Thread.run(Thread.java:761)

I saw someone comment on issue #625 having the same problem but didn't see anyone point out a solution.

I am not having a problem where it starts and stops, it legit doesn't start. I am sorry if I am missing anything, any help is appreciated.

**Comment by jmso1921** [comment]
I was able to fix this by disabling Cloudflare on my server.
