### ISSUE TITLE
IllegalArgumentException when playing clearkey encrypted video

### ISSUE THREAD

**Issue by mhassanist** [google/ExoPlayer#3073]
### Issue description
Trying to play Clearkey encrypted media using expo player and I get the below error. Please see this issue here https://github.com/videojs/videojs-contrib-eme/issues/20 shows the steps I took to encrypt the video and how it is currently working smoothly in firefox. It should give you full details about the content.

No I made this json file
```
{
"keys": [
{
	"kty": "oct",
	"k": "aac0f2b3b279926496a7f5d25da692f3",
	"kid": "279926496a7f5d25da69f2b3b2799a77"
},
{
	"kty": "oct",
	"k": "ccc0f2b3b279926496a7f5d25da692f6",
	"kid": "279926496a7f5d25da69f2b3b2799a7f"
}
],
"type": "temporary"
}
```

and tried it also in base64 format
```
{
"keys": [
{
	"kty": "oct",
	"k": "qsDys7J5kmSWp/XSXaaS8w",
	"kid": "J5kmSWp/XSXaafKzsnmadw"
},
{
	"kty": "oct",
	"k": "zMDys7J5kmSWp/XSXaaS9g",
	"kid": "J5kmSWp/XSXaafKzsnmafw"
}
],
"type": "temporary"
}
```

and when I run I get this error 

```
07-17 10:11:54.742 517-30798/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                         java.lang.IllegalArgumentException
                                                                                             at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                             at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2480)
                                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:699)
                                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
                                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
07-17 10:11:54.749 517-517/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [24.35]
                                                                             com.google.android.exoplayer2.ExoPlaybackException
                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:362)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                              Caused by: java.lang.IllegalArgumentException
                                                                                 at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                 at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2480)
                                                                                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:699)
                                                                                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                 at android.os.Looper.loop(Looper.java:154) 
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61) 
```

### Reproduction steps
Use the links below and set them in the player then choose clear key example.
Video Link to play: http://ec2-52-42-32-95.us-west-2.compute.amazonaws.com/shaka/shakaclear/
Plays in firefox only for now as I think chrome requires https

JSON file I use to provide the keys 
http://ec2-52-42-32-95.us-west-2.compute.amazonaws.com/shaka/shakaclear/key.json

### Link to test content
Video Link to play: http://ec2-52-42-32-95.us-west-2.compute.amazonaws.com/shaka/shakaclear/
Plays in firefox only for now as I think chrome requires https

JSON file I use to provide the keys 
http://ec2-52-42-32-95.us-west-2.compute.amazonaws.com/shaka/shakaclear/key.json

### Version of ExoPlayer being used
V2

### Device(s) and version(s) of Android being used
Android 7.1.1
GM  5 Plus d

### A full bug report captured from the device

*Full bug report attached

[bugreport-NNH90-2017-07-17-10-19-46.zip](https://github.com/google/ExoPlayer/files/1151816/bugreport-NNH90-2017-07-17-10-19-46.zip)

```
07-17 10:19:05.549 517-517/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init ExoPlayerLib/2.4.3 [gm5plus_sprout, GM 5 Plus d, General Mobile, 25]
07-17 10:19:05.551 517-517/com.google.android.exoplayer2.demo D/EventLogger: state [0.01, true, I]
07-17 10:19:05.615 517-517/com.google.android.exoplayer2.demo D/EventLogger: state [0.07, true, B]
07-17 10:19:05.706 517-538/com.google.android.exoplayer2.demo D/OpenGLRenderer: endAllActiveAnimators on 0xa8d6e880 (ExpandableListView) with handle 0x8e84a650
07-17 10:19:06.080 517-517/com.google.android.exoplayer2.demo D/EventLogger: sourceInfo [periodCount=1, windowCount=1
07-17 10:19:06.081 517-517/com.google.android.exoplayer2.demo D/EventLogger:   period [62.32]
07-17 10:19:06.081 517-517/com.google.android.exoplayer2.demo D/EventLogger:   window [62.32, true, false]
07-17 10:19:06.081 517-517/com.google.android.exoplayer2.demo D/EventLogger: ]
07-17 10:19:06.083 517-517/com.google.android.exoplayer2.demo D/EventLogger: loading [true]
07-17 10:19:06.103 517-517/com.google.android.exoplayer2.demo D/EventLogger: Tracks [
07-17 10:19:06.103 517-517/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:0 [
07-17 10:19:06.103 517-517/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
07-17 10:19:06.103 517-517/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=video/avc1, mimeType=video/avc, bitrate=240068, res=480x360, fps=25.0, supported=YES
07-17 10:19:06.103 517-517/com.google.android.exoplayer2.demo D/EventLogger:     ]
07-17 10:19:06.104 517-517/com.google.android.exoplayer2.demo D/EventLogger:   ]
07-17 10:19:06.104 517-517/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:1 [
07-17 10:19:06.104 517-517/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
07-17 10:19:06.104 517-517/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=audio/und/mp4a, mimeType=audio/mp4a-latm, bitrate=133241, channels=2, sample_rate=44100, supported=YES
07-17 10:19:06.104 517-517/com.google.android.exoplayer2.demo D/EventLogger:     ]
07-17 10:19:06.104 517-517/com.google.android.exoplayer2.demo D/EventLogger:   ]
07-17 10:19:06.104 517-517/com.google.android.exoplayer2.demo D/EventLogger: ]
07-17 10:19:06.105 517-517/com.google.android.exoplayer2.demo D/EventLogger: videoEnabled [0.56]
07-17 10:19:06.105 517-517/com.google.android.exoplayer2.demo D/EventLogger: audioEnabled [0.56]
07-17 10:19:06.534 517-7529/com.google.android.exoplayer2.demo I/OMXClient: MuxOMX ctor
07-17 10:19:06.544 517-517/com.google.android.exoplayer2.demo D/EventLogger: audioDecoderInitialized [1.00, OMX.google.aac.decoder]
07-17 10:19:06.544 517-517/com.google.android.exoplayer2.demo D/EventLogger: audioFormatChanged [1.00, id=audio/und/mp4a, mimeType=audio/mp4a-latm, bitrate=133241, channels=2, sample_rate=44100, language=und]
07-17 10:19:06.548 517-7509/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                        java.lang.IllegalArgumentException
                                                                                            at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                            at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2480)
                                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:699)
                                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
                                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
07-17 10:19:06.553 517-517/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [1.01]
                                                                             com.google.android.exoplayer2.ExoPlaybackException
                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:362)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                              Caused by: java.lang.IllegalArgumentException
                                                                                 at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                 at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2480)
                                                                                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:699)
                                                                                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                 at android.os.Looper.loop(Looper.java:154) 
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61) 
07-17 10:19:06.554 517-517/com.google.android.exoplayer2.demo D/EventLogger: videoDisabled [1.01]
07-17 10:19:06.560 517-517/com.google.android.exoplayer2.demo D/EventLogger: audioDisabled [1.02]
07-17 10:19:06.561 517-517/com.google.android.exoplayer2.demo D/EventLogger: loading [false]
07-17 10:19:06.564 517-517/com.google.android.exoplayer2.demo D/EventLogger: state [1.02, true, I]
07-17 10:19:49.667 517-534/com.google.android.exoplayer2.demo I/art: Starting a blocking GC Explicit
07-17 10:19:49.712 517-534/com.google.android.exoplayer2.demo I/art: Explicit concurrent mark sweep GC freed 6156(351KB) AllocSpace objects, 16(376KB) LOS objects, 40% free, 5MB/8MB, paused 422us total 44.873ms
07-17 10:20:00.713 517-517/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init ExoPlayerLib/2.4.3 [gm5plus_sprout, GM 5 Plus d, General Mobile, 25]
07-17 10:20:00.727 517-517/com.google.android.exoplayer2.demo D/EventLogger: state [0.02, true, I]
07-17 10:20:00.806 517-517/com.google.android.exoplayer2.demo D/EventLogger: state [0.10, true, B]
07-17 10:20:00.952 517-538/com.google.android.exoplayer2.demo D/OpenGLRenderer: endAllActiveAnimators on 0xa8d6e880 (ExpandableListView) with handle 0x8e84a4e0
07-17 10:20:01.822 517-517/com.google.android.exoplayer2.demo D/EventLogger: sourceInfo [periodCount=1, windowCount=1
07-17 10:20:01.823 517-517/com.google.android.exoplayer2.demo D/EventLogger:   period [62.32]
07-17 10:20:01.823 517-517/com.google.android.exoplayer2.demo D/EventLogger:   window [62.32, true, false]
07-17 10:20:01.823 517-517/com.google.android.exoplayer2.demo D/EventLogger: ]
07-17 10:20:01.830 517-517/com.google.android.exoplayer2.demo D/EventLogger: loading [true]
07-17 10:20:01.834 517-517/com.google.android.exoplayer2.demo D/EventLogger: Tracks [
07-17 10:20:01.834 517-517/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:0 [
07-17 10:20:01.834 517-517/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
07-17 10:20:01.834 517-517/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=video/avc1, mimeType=video/avc, bitrate=240068, res=480x360, fps=25.0, supported=YES
07-17 10:20:01.834 517-517/com.google.android.exoplayer2.demo D/EventLogger:     ]
07-17 10:20:01.834 517-517/com.google.android.exoplayer2.demo D/EventLogger:   ]
07-17 10:20:01.834 517-517/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:1 [
07-17 10:20:01.834 517-517/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
07-17 10:20:01.835 517-517/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=audio/und/mp4a, mimeType=audio/mp4a-latm, bitrate=133241, channels=2, sample_rate=44100, supported=YES
07-17 10:20:01.835 517-517/com.google.android.exoplayer2.demo D/EventLogger:     ]
07-17 10:20:01.835 517-517/com.google.android.exoplayer2.demo D/EventLogger:   ]
07-17 10:20:01.835 517-517/com.google.android.exoplayer2.demo D/EventLogger: ]
07-17 10:20:01.835 517-517/com.google.android.exoplayer2.demo D/EventLogger: videoEnabled [1.13]
07-17 10:20:01.836 517-517/com.google.android.exoplayer2.demo D/EventLogger: audioEnabled [1.13]
07-17 10:20:02.479 517-8544/com.google.android.exoplayer2.demo I/OMXClient: MuxOMX ctor
07-17 10:20:02.604 517-8543/com.google.android.exoplayer2.demo I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 529425
07-17 10:20:02.621 517-8544/com.google.android.exoplayer2.demo D/SurfaceUtils: set up nativeWindow 0x9022c808 for 480x360, color 0x7fa30c04, rotation 0, usage 0x42002900
07-17 10:20:02.633 517-517/com.google.android.exoplayer2.demo D/EventLogger: videoDecoderInitialized [1.93, OMX.qcom.video.decoder.avc]
07-17 10:20:02.633 517-517/com.google.android.exoplayer2.demo D/EventLogger: videoFormatChanged [1.93, id=video/avc1, mimeType=video/avc, bitrate=240068, res=480x360, fps=25.0]
07-17 10:20:02.637 517-8510/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                        java.lang.IllegalArgumentException
                                                                                            at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                            at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2480)
                                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:699)
                                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
                                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
07-17 10:20:02.640 517-517/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [1.93]
                                                                             com.google.android.exoplayer2.ExoPlaybackException
                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:362)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                              Caused by: java.lang.IllegalArgumentException
                                                                                 at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                 at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2480)
                                                                                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:699)
                                                                                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                 at android.os.Looper.loop(Looper.java:154) 
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61) 
07-17 10:20:02.671 517-517/com.google.android.exoplayer2.demo D/EventLogger: videoDisabled [1.97]
07-17 10:20:02.671 517-517/com.google.android.exoplayer2.demo D/EventLogger: audioDisabled [1.97]
07-17 10:20:02.671 517-517/com.google.android.exoplayer2.demo D/EventLogger: loading [false]
07-17 10:20:02.674 517-517/com.google.android.exoplayer2.demo D/EventLogger: state [1.97, true, I]
07-17 10:20:09.838 517-523/com.google.android.exoplayer2.demo I/art: Thread[3,tid=523,WaitingInMainSignalCatcherLoop,Thread*=0xa03a5800,peer=0x32c050d0,"Signal Catcher"]: reacting to signal 3
07-17 10:20:09.981 517-523/com.google.android.exoplayer2.demo I/art: Wrote stack traces to '/data/anr/traces.txt'
```

**Comment by ojw28** [comment]
What's the actual link to the content? The link provided above is to an html page, not a piece of media.

**Comment by ojw28** [comment]
Closing due to lack of required information.
