### ISSUE TITLE
Media Codec Exception when playing Widevine encrypted content .. stops working after 9 seconds

### ISSUE THREAD

**Issue by mhassanist** [google/ExoPlayer#3074]
### Issue description
Using your demo Application, trying to play my own Dash mpd stream. It plays only for 9 seconds ( the non-encrypted part) then it stops playing. It is encrypted using Widevine test provider.

### Reproduction steps
in the demo application, replace any mpd dash video link with this one
http://ec2-52-42-32-95.us-west-2.compute.amazonaws.com/play/v10mpd/live.mpd  and try to play. 

### Link to test content
http://ec2-52-42-32-95.us-west-2.compute.amazonaws.com/play/v10mpd/live.mpd 

### Version of ExoPlayer being used
v2

### Device(s) and version(s) of Android being used
Android 7.1.1
GM 5 Plus d

### A full bug report captured from the device
attached also.
```
07-17 11:39:19.192 18382-22391/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Renderer error.
                                                                                           com.google.android.exoplayer2.ExoPlaybackException
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:708)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                            Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
                                                                                               at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                               at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2480)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:699)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                               at android.os.Looper.loop(Looper.java:154) 
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61) 
07-17 11:39:19.197 18382-18382/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [13.24]
                                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:708)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                  Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
                                                                                     at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                     at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2480)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:699)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) 
07-17 11:39:19.238 18382-18382/com.google.android.exoplayer2.demo D/EventLogger: videoDisabled [13.28]
07-17 11:39:19.250 18382-18382/com.google.android.exoplayer2.demo D/EventLogger: audioDisabled [13.29]
07-17 11:39:19.250 18382-18382/com.google.android.exoplayer2.demo D/EventLogger: loading [false]
07-17 11:39:19.255 18382-18382/com.google.android.exoplayer2.demo D/EventLogger: state [13.30, true, I]
07-17 11:40:08.763 18382-18404/com.google.android.exoplayer2.demo I/art: Starting a blocking GC Explicit
07-17 11:40:08.801 18382-18404/com.google.android.exoplayer2.demo I/art: Explicit concurrent mark sweep GC freed 24738(1567KB) AllocSpace objects, 45(2MB) LOS objects, 40% free, 5MB/9MB, paused 405us total 37.457ms
07-17 11:40:37.640 18382-18388/com.google.android.exoplayer2.demo I/art: Thread[3,tid=18388,WaitingInMainSignalCatcherLoop,Thread*=0xa03a5800,peer=0x12c5c940,"Signal Catcher"]: reacting to signal 3
07-17 11:40:37.732 18382-18388/com.google.android.exoplayer2.demo I/art: Wrote stack traces to '/data/anr/traces.txt'
[bugreport2.zip](https://github.com/google/ExoPlayer/files/1151975/bugreport2.zip)

```

**Comment by ojw28** [comment]
That error indicates that the license response did not include the keys the content is encrypted with:
```
Error decrypting data: requested key has not been loaded
```
I don't know what "It is encrypted using Widevine test provider" means, or which license server you're using, but it sounds like a license server/content mismatch to me.
