### ISSUE TITLE
com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416

### ISSUE THREAD

**Issue by wwdn** [google/ExoPlayer#3092]
E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                 com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
                                                                                     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                                                                                     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:275)
                                                                                     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                  Caused by: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
                                                                                     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
                                                                                     at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
                                                                                     at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:824)
                                                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)

is   what?

**Comment by andrewlewis** [comment]
The server is returning HTTP status code 416 Range Not Satisfiable. The most probable cause is bad media, but there's not enough information here for us to diagnose it. If you find that this is an ExoPlayer bug please reopen the issue and provide all the information requested in the issue template.

**Comment by wwdn** [comment]
Thank you
