### ISSUE TITLE
void com.google.android.exoplayer2.source.MediaSource.releaseSource()

### ISSUE THREAD

**Issue by zhaocheng19940105** [google/ExoPlayer#3101]
uncaughtException:Attempt to invoke interface method 'void com.google.android.exoplayer2.source.MediaSource.releaseSource()' on a null object reference
07-26 18:03:21.132 8041-8574/com.abc.agency.teacher E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.exoplayer2.source.MediaSource.releaseSource()' on a null object reference
                                                                                  at com.google.android.exoplayer2.source.ConcatenatingMediaSource.releaseSource(ConcatenatingMediaSource.java:103)
                                                                                  at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:724)
                                                                                  at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:684)
                                                                                  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:364)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                  at android.os.Looper.loop(Looper.java:160)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)

in  onResume()  initializePlayer

**Comment by andrewlewis** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
