### ISSUE TITLE
Offline playback problem (not reliable)

### ISSUE THREAD

**Issue by dulmandakh** [google/ExoPlayer#3111]
### Issue description
I'm trying to implement offline playback in ExoPlayer, with OfflineLicenseHelper and DefaultDrmSessionManager. Online playback just works fine and sometimes offline playback works, but sometimes I get below error.

```
MediaDrm: Drm event (2,0)
ExoPlayerImplInternal: Renderer error.
com.google.android.exoplayer2.ExoPlaybackException
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:708)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:154)
    at android.os.HandlerThread.run(HandlerThread.java:61)
  Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
```

### Reproduction steps
Here is what I did
1. Download manifest file
2. Download media file (packaged using shaka-packager)
3. Download license with OfflineLicenseHelper.downloadLicense and save byte[]
4. DefaultDrmSessionManager.setMode(DefaultDrmSessionManager.MODE_PLAYBACK, saved byte[]);
5. Try to play local DASH manifest

### Link to test content
I'll send it by email.

### Version of ExoPlayer being used
2.4.4

### Device(s) and version(s) of Android being used
Samsung Galaxy S8 (Android 7.0) and Android Emulator with Android 7.0.

### A full bug report captured from the device
Capture a full bug report using "adb bugreport". Output from "adb logcat" or a
log snippet is NOT sufficient. Please attach the captured bug report as a file.
If you don't wish to post it publicly, please submit the issue, then email the
bug report to dev.exoplayer@gmail.com including the issue number in the subject
line.

**Comment by ojw28** [comment]
Please attach or mail a full bug report as requested at the bottom of the issue template (if you mail, please update this issue to prompt us to take another look). Thanks!

By the way, are you certain the offline license hasn't expired when you encounter this issue?

**Comment by ojw28** [comment]
Closing due to lack of information.
