### ISSUE TITLE
Playback stops at playback of Widevine HDCP Capabilities tests on Fire TV stick (1st generation)

### ISSUE THREAD

**Issue by ueno-yuhei** [google/ExoPlayer#3121]
### Issue description
This is an error that occurred when confirming Widevine playback in the demo application.
With HDCP content of widevine, an error is displayed after 8~9 seconds from playback start and playback stops.
If this error occurs, playback can not be resumed unless you press the retry button and exit.
It occurs in FireTVStick (1st generation).

Paste the contents of logcat at the time of error.

```
07-31 15:45:43.585 19118-20228/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Renderer error.
     com.google.android.exoplayer2.ExoPlaybackException
         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:708)
         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
         at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
         at android.os.Handler.dispatchMessage(Handler.java:98)
         at android.os.Looper.loop(Looper.java:135)
         at android.os.HandlerThread.run(HandlerThread.java:61)
      Caused by: android.media.MediaCodec$CryptoException: Error decrypting data.
         at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
         at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:978)
         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:699)
         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511) 
         at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
         at android.os.Handler.dispatchMessage(Handler.java:98) 
         at android.os.Looper.loop(Looper.java:135) 
         at android.os.HandlerThread.run(HandlerThread.java:61) 
```

The error log acquired by adb bugreport was ZIP and attach.

### Reproduction steps

Launch DemoApp
Select Widevine HDCP Capabilities Tests from the list
WV: HDCP: 1.0 required
WV: HDCP: 2.0 required
WV: HDCP: 2.1 required
WV: HDCP: 2.2 required
WV: HDCP: No digital output
Select one of them and start playback
Error occurred in 8 to 9 seconds and playback stopped

### Link to test content
none

### Version of ExoPlayer being used
r2.4.4

### Device(s) and version(s) of Android being used
amazon FireTV stick（1st generation)
FireOS 5.2.4.2
FireTV Home Version 5.7.3-20

### A full bug report captured from the device
[bugreport.txt.zip](https://github.com/google/ExoPlayer/files/1186803/bugreport.txt.zip)

Thank you and best regards,

**Comment by ojw28** [comment]
Do you actually expect this to work? Maybe first generation FireTV stick just doesn't support the HDCP levels that are required for this content, in which case failure is expected.

**Comment by wvpaf** [comment]
This seems to be working as intended. From this site : https://developer.amazon.com/public/solutions/devices/fire-tv/docs/device-and-platform-specifications 
gen 1 fire stick only supports hdcp v1.4.
