### ISSUE TITLE
Can't play hls stream: Unexpected exception loading stream java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Ryder68** [google/ExoPlayer#3126]
I'm using ExoPlayer Lib r2.5.0-beta1 & r2.4.4. But it's can't play this hls url: http://42.112.37.42/hls/4545780bfa790819/5/3/a7c6b7d36c0e01c57d6a6eb393de4b90fefc4af91b17b88a4673356e1ac70c6c/dnR2MQ==.m3u8

Log:
```
LoadTask: Unexpected exception loading stream
java.lang.IllegalArgumentException
   at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:37)
   at com.google.android.exoplayer2.util.ParsableByteArray.setPosition(ParsableByteArray.java:145)
   at com.google.android.exoplayer2.util.ParsableByteArray.skipBytes(ParsableByteArray.java:157)
   at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:285)
   at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:266)
   at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:202)
   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
   at java.lang.Thread.run(Thread.java:841)
```

That stream url working on Android default player, Vitamio Lib or VLC (on PC) but not work in ExoPlayer.
Please help me.

**Comment by ojw28** [comment]
I'm not sure "working" is quite accurate. I tried to play this stream on VLC, and whilst it does play, there are repeated freezes and a lot of errors in the logs. Less than 30s of playback yielded all of the following, which corresponded to visible jank:

```
[0x7fc1498b7fb8] ts demux error: MPEG-4 descriptor not found
[h264 @ 0x7fc148da5540] concealing 449 DC, 449 AC, 449 MV errors
[0x7fc148c43c38] httplive stream error: gap in sequence numbers found: new=338304 expected 338302
[0x7fc1498b7fb8] ts demux error: libdvbpsi (PSI decoder): TS discontinuity (received 0, expected 12) for PID 17
[0x7fc1498b7fb8] ts demux error: libdvbpsi (PSI decoder): TS discontinuity (received 0, expected 12) for PID 0
[0x7fc1498b7fb8] ts demux error: libdvbpsi (PSI decoder): TS discontinuity (received 0, expected 14) for PID 4096
[h264 @ 0x7fc148da5540] concealing 376 DC, 376 AC, 376 MV errors
[0x7fc148c43c38] httplive stream error: gap in sequence numbers found: new=338310 expected 338308
[0x7fc1498b7fb8] ts demux error: libdvbpsi (PSI decoder): TS discontinuity (received 6, expected 1) for PID 17
[0x7fc1498b7fb8] ts demux error: libdvbpsi (PSI decoder): TS discontinuity (received 6, expected 1) for PID 0
[0x7fc1498b7fb8] ts demux error: libdvbpsi (PSI decoder): TS discontinuity (received 6, expected 4) for PID 4096
[h264 @ 0x7fc148d4d200] concealing 1051 DC, 1051 AC, 1051 MV errors
[h264 @ 0x7fc148d4d200] concealing 698 DC, 698 AC, 698 MV errors
[h264 @ 0x7fc148d4cdc0] concealing 462 DC, 462 AC, 462 MV errors
[0x7fc148c43c38] httplive stream error: gap in sequence numbers found: new=338316 expected 338314
[0x7fc1498b7fb8] ts demux error: libdvbpsi (PSI decoder): TS discontinuity (received 12, expected 10) for PID 4096
[h264 @ 0x7fc148d4d200] concealing 202 DC, 202 AC, 202 MV errors
[h264 @ 0x7fc148d4cdc0] concealing 638 DC, 638 AC, 638 MV errors
[h264 @ 0x7fc148dfd880] concealing 1437 DC, 1437 AC, 1437 MV errors
[0x7fc148c43c38] httplive stream error: gap in sequence numbers found: new=338322 expected 338320
[0x7fc1498b7fb8] ts demux error: libdvbpsi (PSI decoder): TS discontinuity (received 2, expected 0) for PID 4096
[h264 @ 0x7fc148da5540] concealing 183 DC, 183 AC, 183 MV errors
[h264 @ 0x7fc148d4d200] cabac decode of qscale diff failed at 49 26
[h264 @ 0x7fc148d4d200] error while decoding MB 49 26, bytestream (-1)
[h264 @ 0x7fc148d4d200] concealing 216 DC, 216 AC, 216 MV errors
[h264 @ 0x7fc148d4d200] left block unavailable for requested intra4x4 mode -1 at 0 1
[h264 @ 0x7fc148d4d200] error while decoding MB 0 1, bytestream (118)
[h264 @ 0x7fc148d4d200] concealing 1615 DC, 1615 AC, 1615 MV errors
[h264 @ 0x7fc148d4d200] concealing 1520 DC, 1520 AC, 1520 MV errors
[0x7fc148c43c38] httplive stream error: gap in sequence numbers found: new=338328 expected 338326
[0x7fc1498b7fb8] ts demux error: libdvbpsi (PSI decoder): TS discontinuity (received 8, expected 6) for PID 4096
```

Which looks pretty broken to me.

**Comment by ojw28** [comment]
Using Apple's `mediastreamvalidator` tool also yields a "MUST fix" issues for every segment:

```
--------------------------------------------------------------------------------
MUST fix issues
--------------------------------------------------------------------------------

Error: Segment size cannot be divided evenly by 188. Partial TS packet found
--> Detail:  Segment size is 175673 = 188 * 934 + 81
--> Source:  http://42.112.37.42/hls/4545780bfa790819/5/3/a7c6b7d36c0e01c57d6a6eb393de4b90fefc4af91b17b88a4673356e1ac70c6c/dnR2MQ==.m3u8 - dnR2MQ==-338561.ts

--> Detail:  Segment size is 180191 = 188 * 958 + 87
--> Source:  http://42.112.37.42/hls/4545780bfa790819/5/3/a7c6b7d36c0e01c57d6a6eb393de4b90fefc4af91b17b88a4673356e1ac70c6c/dnR2MQ==.m3u8 - dnR2MQ==-338562.ts

--> Detail:  Segment size is 206803 = 188 * 1100 + 3
--> Source:  http://42.112.37.42/hls/4545780bfa790819/5/3/a7c6b7d36c0e01c57d6a6eb393de4b90fefc4af91b17b88a4673356e1ac70c6c/dnR2MQ==.m3u8 - dnR2MQ==-338563.ts

--> Detail:  Segment size is 164011 = 188 * 872 + 75
--> Source:  http://42.112.37.42/hls/4545780bfa790819/5/3/a7c6b7d36c0e01c57d6a6eb393de4b90fefc4af91b17b88a4673356e1ac70c6c/dnR2MQ==.m3u8 - dnR2MQ==-338564.ts

--> Detail:  Segment size is 166980 = 188 * 888 + 36
--> Source:  http://42.112.37.42/hls/4545780bfa790819/5/3/a7c6b7d36c0e01c57d6a6eb393de4b90fefc4af91b17b88a4673356e1ac70c6c/dnR2MQ==.m3u8 - dnR2MQ==-338565.ts

--> Detail:  Segment size is 157771 = 188 * 839 + 39
--> Source:  http://42.112.37.42/hls/4545780bfa790819/5/3/a7c6b7d36c0e01c57d6a6eb393de4b90fefc4af91b17b88a4673356e1ac70c6c/dnR2MQ==.m3u8 - dnR2MQ==-338566.ts

--> Detail:  Segment size is 162790 = 188 * 865 + 170
--> Source:  http://42.112.37.42/hls/4545780bfa790819/5/3/a7c6b7d36c0e01c57d6a6eb393de4b90fefc4af91b17b88a4673356e1ac70c6c/dnR2MQ==.m3u8 - dnR2MQ==-338567.ts

--> Detail:  Segment size is 178168 = 188 * 947 + 132
--> Source:  http://42.112.37.42/hls/4545780bfa790819/5/3/a7c6b7d36c0e01c57d6a6eb393de4b90fefc4af91b17b88a4673356e1ac70c6c/dnR2MQ==.m3u8 - dnR2MQ==-338568.ts

--> Detail:  Segment size is 184770 = 188 * 982 + 154
--> Source:  http://42.112.37.42/hls/4545780bfa790819/5/3/a7c6b7d36c0e01c57d6a6eb393de4b90fefc4af91b17b88a4673356e1ac70c6c/dnR2MQ==.m3u8 - dnR2MQ==-338569.ts

--> Detail:  Segment size is 187767 = 188 * 998 + 143
--> Source:  http://42.112.37.42/hls/4545780bfa790819/5/3/a7c6b7d36c0e01c57d6a6eb393de4b90fefc4af91b17b88a4673356e1ac70c6c/dnR2MQ==.m3u8 - dnR2MQ==-338570.ts
```

Closing the issue because the media is bad.

**Comment by Ryder68** [comment]
Oh.
It can only works well on Vietnam country.
I just test that stream and it still working.

![image](https://user-images.githubusercontent.com/30622400/28835176-ba8b184c-770e-11e7-83da-e45f8af73b70.png)

You can get stream url from this site:
http://vtv.vn/truyen-hinh-truc-tuyen/vtv1.htm

I don't thinks that stream is bad media.

note:
Update new stream:
http://42.112.37.42/hls/4545780bfa790819/5/3/6e4eb2c9fc5c4d9601b97edd78289b513cd99c20453b71b0346c8a805061daa6/dnR2MQ==.m3u8

**Comment by Ryder68** [comment]
@ojw28 Please help me :-(

**Comment by ojw28** [comment]
As per above, Apple's `mediastreamvalidator` indicates multiple "MUST fix" issues with the stream. If you can find a stream that passes Apple's validator and still fails in this way, please let us know and we'll take a look. You can read about the tool [here](https://developer.apple.com/library/content/technotes/tn2235/_index.html#//apple_ref/doc/uid/DTS40010221-CH1-VALIDATORTOOL).

**Comment by Ryder68** [comment]
@ojw28 Okie.
But why Android default player or Vitamio Lib can play that stream (i tested), and ExoPlayer can not play ?

**Comment by ojw28** [comment]
I'm not sure. There are many reasons why this kind of thing can happen (e.g. because we rely on different parts of the media stream, or are less robust to some issue with this particular stream). It's not something we're going to spend time investigating though. Our priority is to play properly formatted media really well, not to play malformed media less badly :).

**Comment by Ryder68** [comment]
Thank you :-)

**Comment by Ryder68** [comment]
@ojw28 Hi.
The above error was not called in <b>onPlayerError(ExoPlaybackException e)</b> function.
How can I know when that error occurred ?
Please!
