### ISSUE TITLE
how to play dash video if server only clice video AdaptationSet

### ISSUE THREAD

**Issue by yyyuuu777** [google/ExoPlayer#3129]
hi , My server mpd file only have video AdaptationSet , not have audio AdaptationSet , exoplayer will parse mpd file fail , i want to know how to play dash video if server only slice video AdaptationSet , Thank you !

here is my mpd file:
`<MPD minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H8M48.384S" maxSegmentDuration="PT0H0M10.000S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011"><ProgramInformation moreInformationURL="http://gpac.io"><Title>/usr/local/code/apvideo-convert/storage/data/video/released/2017-07-27/Od6SfBwbuJgBqIkonmBx_HD.mpd generated by GPAC</Title></ProgramInformation><Period duration="PT0H8M48.384S"><AdaptationSet segmentAlignment="true" maxWidth="480" maxHeight="272" maxFrameRate="24" par="480:272" lang="und" subsegmentAlignment="true" subsegmentStartsWithSAP="1"><ContentComponent id="1" contentType="video"/><ContentComponent id="2" contentType="audio"/><Representation id="1" mimeType="video/mp4" codecs="avc1.640015,mp4a.40.2" width="480" height="272" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="236001"><AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="1"/><BaseURL>Od6SfBwbuJgBqIkonmBx_HD_dashinit.mp4</BaseURL><SegmentBase indexRangeExact="true" indexRange="1415-2730"><Initialization range="0-1414"/></SegmentBase></Representation></AdaptationSet></Period></MPD>`

**Comment by ojw28** [comment]
Please provide all of the information requested in the issue template. What does "fail" mean. There's probably a stack trace in the logs that would save a lot of time...

**Comment by yyyuuu777** [comment]
Sorry , this is the log error :
`
E/LoadTask: Unexpected exception loading stream
            java.lang.IllegalStateException
                at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:79)
                at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.checkContentTypeConsistency(DashManifestParser.java:806)
                at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseAdaptationSet(DashManifestParser.java:262)
                at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parsePeriod(DashManifestParser.java:209)
                at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseMediaPresentationDescription(DashManifestParser.java:137)
                at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:99)
                at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:54)
                at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:115)
                at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                at java.lang.Thread.run(Thread.java:761)
D/EventLogger: state [1.03, true, B]
`
My server only cut the video, the audio is not separated, so my mpd file only one AdaptationSet, so you can play dash video stream

**Comment by ojw28** [comment]
Ah. We do not support muxed audio+video content in DASH, and have no plans to do so. Sorry.

**Comment by yyyuuu777** [comment]
Sorry, what do you mean by dash play, mp4 file video and audio must be separated before it?

**Comment by ojw28** [comment]
We only support DASH manifests where audio and video are split out into separate adaptation sets (and underlying that, yes, separate mp4 files).

**Comment by yyyuuu777** [comment]
ok , if  audio and video are not split out into separate adaptation sets ,the dash manifests only have video adaptation set  , Can  play it?

**Comment by ojw28** [comment]
As above, this is not something we support or plan to support. We only support demuxed (i.e. audio and video split into separate adaptations sets).
