### ISSUE TITLE
ClearKey DASH url provided in media.exolist.json returns 404

### ISSUE THREAD

**Issue by hishamMuneer** [google/ExoPlayer#3135]
*** ISSUES THAT IGNORE THIS TEMPLATE WILL BE CLOSED WITHOUT INVESTIGATION ***

### Issue description
ClearKey DASH url provided in media.exolist.json returns 404. The file doesn't exist on server. That is the only example present in the section. Please provide a working sample of Clear Key.

### Reproduction steps
Hit the link

### Link to test content
http://html5.cablelabs.com:8100/cenc/ck/dash.mpd

**Comment by ojw28** [comment]
Yeah. I don't see much option but to remove it, unless someone has other sample content we can use.

**Comment by hishamMuneer** [comment]
@ojw28 I have been trying to run "cenc" on exoplayer from last 3 days. Do you have any example to help me out? Any reference would be appreciated too. 

Please open the links given below and help me if have time. I think my key.json file is incorrect. I reused the one given in the sample but I after days of searching i am not able to find it anywhere.

This is what i have been trying till now: 

## Info

{
        "name": "ClearKey",
        "uri": "https://drmdemo-94ea7.firebaseapp.com/encrypt/manifest.mpd",
        "extension": "mpd",
        "drm_scheme": "cenc",
        "drm_license_url": "https://drmdemo-94ea7.firebaseapp.com/encrypt/key.json"
      }


## Getting following error: 

Illegal state exception: Failed to get key request: Unsupported scheme or data format (-2006)

## Full log trace:

```
08-03 20:44:52.180 23035-3940/com.google.android.exoplayer2.demo E/MediaDrm-JNI: Illegal state exception: Failed to get key request: Unsupported scheme or data format (-2006)
08-03 20:44:52.182 23035-3940/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Renderer error.
                                                                                          com.google.android.exoplayer2.ExoPlaybackException
                                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:305)
                                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:796)
                                                                                              at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:365)
                                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:494)
                                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                           Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: Unsupported scheme or data format
                                                                                              at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onError(DefaultDrmSessionManager.java:604)
                                                                                              at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onKeysError(DefaultDrmSessionManager.java:599)
                                                                                              at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.postKeyRequest(DefaultDrmSessionManager.java:548)
                                                                                              at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.doLicense(DefaultDrmSessionManager.java:480)
                                                                                              at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.openInternal(DefaultDrmSessionManager.java:430)
                                                                                              at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:352)
                                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:774)
                                                                                              at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:365) 
                                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:494) 
                                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                           Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: Unsupported scheme or data format
                                                                                              at android.media.MediaDrm.getKeyRequest(Native Method)
                                                                                              at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:86)
                                                                                              at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.postKeyRequest(DefaultDrmSessionManager.java:544)
                                                                                              at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.doLicense(DefaultDrmSessionManager.java:480) 
                                                                                              at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.openInternal(DefaultDrmSessionManager.java:430) 
                                                                                              at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:352) 
                                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:774) 
                                                                                              at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:365) 
                                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:494) 
                                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
08-03 20:44:52.182 23035-23035/com.google.android.exoplayer2.demo E/EventLogger: internalError [0.77, drmSessionManagerError]
                                                                                 android.media.MediaDrm$MediaDrmStateException: Failed to get key request: Unsupported scheme or data format
                                                                                     at android.media.MediaDrm.getKeyRequest(Native Method)
                                                                                     at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:86)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.postKeyRequest(DefaultDrmSessionManager.java:544)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.doLicense(DefaultDrmSessionManager.java:480)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.openInternal(DefaultDrmSessionManager.java:430)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:352)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:774)
                                                                                     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:365)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:494)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
08-03 20:44:52.184 23035-23035/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [0.78]
                                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:305)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:796)
                                                                                     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:365)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:494)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                  Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: Unsupported scheme or data format
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onError(DefaultDrmSessionManager.java:604)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onKeysError(DefaultDrmSessionManager.java:599)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.postKeyRequest(DefaultDrmSessionManager.java:548)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.doLicense(DefaultDrmSessionManager.java:480)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.openInternal(DefaultDrmSessionManager.java:430)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:352)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:774)
                                                                                     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:365) 
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:494) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                  Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: Unsupported scheme or data format
                                                                                     at android.media.MediaDrm.getKeyRequest(Native Method)
                                                                                     at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:86)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.postKeyRequest(DefaultDrmSessionManager.java:544)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.doLicense(DefaultDrmSessionManager.java:480) 
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.openInternal(DefaultDrmSessionManager.java:430) 
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:352) 
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:774) 
                                                                                     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:365) 
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:494) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) 
08-0
```

**Comment by ojw28** [comment]
Sorry, but debugging other people's media is outside the scope of this issue tracker. We will remove the 404'ing sample stream though.

**Comment by hishamMuneer** [comment]
Thanks.

**Comment by ojw28** [comment]
We'll push a change removing the
