### ISSUE TITLE
TS with h264 (MPEG-4 AVC) isn't starting

### ISSUE THREAD

**Issue by Novanic** [google/ExoPlayer#3154]
Hi,

I try to stream from my Panasonic DMR BST-950 (I think all hard disk recorder models of Panasonic are affected). ExoPlayer throws an com.google.android.exoplayer2.source.UnrecognizedInputFormatException when I try to use the demo with the URL of the TS. The URL is for example "http://192.168.178.57:60001/0003-0001-0421-EF15-143B_BDY". I thought the codec is already supported by ExoPlayer. I hope someone can help to get it running. :-) Thank you in advance.

VLC (on Windows) and Kodi (on Windows and on Fire TV Stick) can play the stream, VLC says the following:
Stream 0 (Video), Codec: H264 - MPEG-4 AVC (part 10) (h264)
Stream 1 (Audio), A52 Audio (aka AC3) (a52 ), Bitrate 384 kB/s
Stream 2 (Subtitle), Teletext
Stream 3 (Subtitle), DVB Subtitles (dvbs)

Here is the full log:
08-08 18:10:12.970 4356-4356/com.google.android.exoplayer2.demo I/art: Late-enabling -Xcheck:jni
08-08 18:10:13.003 4356-4363/com.google.android.exoplayer2.demo I/art: Debugger is no longer active
08-08 18:10:13.003 4356-4363/com.google.android.exoplayer2.demo I/art: Starting a blocking GC Instrumentation
08-08 18:10:13.292 4356-4356/com.google.android.exoplayer2.demo W/System: ClassLoader referenced unknown path: /data/app/com.google.android.exoplayer2.demo-2/lib/arm
08-08 18:10:13.322 4356-4356/com.google.android.exoplayer2.demo I/InstantRun: starting instant run server: is main process
08-08 18:10:13.323 4356-4371/com.google.android.exoplayer2.demo D/libEGL: loaded /vendor/lib/egl/libEGL_tegra.so
08-08 18:10:13.340 4356-4371/com.google.android.exoplayer2.demo D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_tegra.so
08-08 18:10:13.410 4356-4371/com.google.android.exoplayer2.demo D/libEGL: loaded /vendor/lib/egl/libGLESv2_tegra.so
08-08 18:10:13.554 4356-4375/com.google.android.exoplayer2.demo I/OpenGLRenderer: Initialized EGL, version 1.4
08-08 18:10:13.554 4356-4375/com.google.android.exoplayer2.demo D/OpenGLRenderer: Swap behavior 1
08-08 18:10:13.597 4356-4356/com.google.android.exoplayer2.demo W/InputMethodManager: Ignoring onBind: cur seq=22, given seq=21
08-08 18:10:20.452 4356-4356/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init 2cfbcb8 [ExoPlayerLib/2.5.0] [grouper, Nexus 7, Asus, 25]
08-08 18:10:20.480 4356-4356/com.google.android.exoplayer2.demo D/EventLogger: state [0.14, true, I]
08-08 18:10:20.506 4356-4356/com.google.android.exoplayer2.demo D/EventLogger: state [0.17, true, B]
08-08 18:10:20.507 4356-4356/com.google.android.exoplayer2.demo D/EventLogger: sourceInfo [periodCount=1, windowCount=1
08-08 18:10:20.507 4356-4356/com.google.android.exoplayer2.demo D/EventLogger:   period [?]
08-08 18:10:20.507 4356-4356/com.google.android.exoplayer2.demo D/EventLogger:   window [?, false, false]
08-08 18:10:20.507 4356-4356/com.google.android.exoplayer2.demo D/EventLogger: ]
08-08 18:10:20.646 4356-4398/com.google.android.exoplayer2.demo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
08-08 18:10:20.713 4356-4356/com.google.android.exoplayer2.demo D/EventLogger: loading [true]
08-08 18:10:27.468 4356-4356/com.google.android.exoplayer2.demo E/EventLogger: internalError [7.13, loadError]
                                                                               com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:774)
                                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:697)
                                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                   at java.lang.Thread.run(Thread.java:761)
08-08 18:10:27.474 4356-4396/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Source error.
                                                                                         com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:774)
                                                                                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:697)
                                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                             at java.lang.Thread.run(Thread.java:761)
08-08 18:10:27.478 4356-4356/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [7.14]
                                                                               com.google.android.exoplayer2.ExoPlaybackException
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:389)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:774)
                                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:697)
                                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                   at java.lang.Thread.run(Thread.java:761)
08-08 18:10:27.479 4356-4356/com.google.android.exoplayer2.demo D/EventLogger: loading [false]
08-08 18:10:27.479 4356-4356/com.google.android.exoplayer2.demo D/EventLogger: state [7.14, true, I]
08-08 18:11:12.313 4356-4356/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Release 2cfbcb8 [ExoPlayerLib/2.5.0] [grouper, Nexus 7, Asus, 25] [goog.exo.core, goog.exo.ui]

**Comment by andrewlewis** [comment]
It would be useful to have a sample of the stream. Please could you attach or email it to dev.exoplayer@gmail.com? If that's not possible, you'd need to step through `TsExtractor.sniff` and find out why this stream is being rejected.

**Comment by Novanic** [comment]
I already tried to force to process the stream by the TsExtractor by overridding the sniff method with just returning true. That "solved" the exception but it still doesn't start, so there seem to be at least one more problem.Therefore it should be more useful to provide an example of the stream. Is it possible to record a TS stream without convertion? Otherwise I have to try to host the original stream for some time via the internet, when would you have time to take a look at the stream?Thank you in advance and for the fast response.

**Comment by andrewlewis** [comment]
Can you just download and attach a portion of the stream? Or the quickest approach may just be for you to set a breakpoint in the sniff method and step through to find out which part of the data is not consistent with what the extractor's expecting.

**Comment by ojw28** [comment]
Is it possible the content is BDAV rather than regular MPEG-TS (https://github.com/google/ExoPlayer/issues/1488, https://en.wikipedia.org/wiki/.m2ts)?

**Comment by Novanic** [comment]
I have now sent an example to dev.exoplayer@gmail.com

The buffer array within the sniff method of TsExtractor has these values:
[0] = 25
[1] = -44
[2] = 81
[3] = -77
[4] = 71
[5] = 0
[6] = 30
[7] = 32
[8] = -73
[9] = -128
... = -1

**Comment by AquilesCanta** [comment]
I cannot access to the stream right now, but considering there are 4 bytes preceding the first sync byte (71), this is surely a BDAV TS, as @ojw28 points out.

You can confirm this yourself, if you find a byte with value 71 every 192 bytes, starting from the byte at position 4. Comment down here if this is not the case, please, and we will reopen.

This is not currently supported. Track  #1488 for support.

**Comment by Novanic** [comment]
Ok, maybe my example helps to add the support. In the discussion of #1488 it seems that a good example ist missing.

There are some patches in the discussion of #1488. Are these not working?

**Comment by AquilesCanta** [comment]
We need a proper pull request to take any patches into consideration. You are more than welcome to make this contribution!
