### ISSUE TITLE
High memory use when playing MP4 files from removable storage.

### ISSUE THREAD

**Issue by MateusZitelli** [google/ExoPlayer#3214]
### Issue description
High memory use when playing MP4 files from removable storage.

### Reproduction steps
Add to demo app `media.exolist.json` the an entry like that:

```
      {
        "name": "Removable storage playback",
        "playlist": [
          {
            "uri": "/storage/428F-19EF/All 360 Camera Samples/Insta360nano-2880x1440-Long.mp4"
          }
        ]
      },

```

Then launch the sample in the demo app.

### Link to test content
It worked with all videos big enough to fill the RAM.

### Version of ExoPlayer being used
r2.5.1

### Device(s) and version(s) of Android being used
Tested on:

- LG G3 (Android 5.0)
- Protruly D7 (Android 6.0)
- Samsung Galaxy S8 (Android 7.0)

### A full bug report captured from the device

```
08-28 19:11:36.543 620-620/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [14.40]
com.google.android.exoplayer2.ExoPlaybackException
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:389)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:154)
    at android.os.HandlerThread.run(HandlerThread.java:61)
 Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 65548 byte allocation with 48024 free bytes and 46KB until OOM
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:345)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:762)
 Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65548 byte allocation with 48024 free bytes and 46KB until OOM
    at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
    at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:592)
    at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:516)
    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:441)
    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:152)
    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:704)
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:762)
```

**Comment by ojw28** [comment]
I cannot reproduce this issue on an S8. I tried with a ~100MB video and memory usage was capped at ~16MB throughout. Please provide concrete reproduction steps.

**Comment by MateusZitelli** [comment]
Ok, [here is](https://drive.google.com/file/d/0B22nLuGDIyWSSDJGTGpYRlB3Rms/view?usp=sharing) the clip that triggers the event.

**Comment by ojw28** [comment]
The file isn't interleaved properly (it doesn't contain any audio at all until nearly 2GB into the end of the file (i.e. right at the end). Audio and video should really be interleaved approximately evenly throughout the file.

I don't think we have any particular need or intention to support this type of media. Whatever's producing this type of media should do a better job of it ;).
