### ISSUE TITLE
WebVTTCueParser Matcher and NullPointerException

### ISSUE THREAD

**Issue by q-litzler** [google/ExoPlayer#3228]
### Issue description
It is possible to encounter a NPE [here](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/text/webvtt/WebvttCueParser.java#L102), when `secondLine` is null.

`secondLine` can be null when the subtitle file is not well formatted.

Here is a [link](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6178785) to the RegexMatcher behavior regarding null arguments.

Proposed solution: Handle the NPE gracefully, somehow.

### Reproduction steps
This is happening in production of our app, and sadly I can't pinpoint the corrupted .vtt file on our end. (I would have to check hours of content in 10 different languages ..). If I find it, I will update this issue with a link to test content.

### Link to test content
See above

### Version of ExoPlayer being used
2.5.1

### Device(s) and version(s) of Android being used
All versions from 5.0 to 7.1.2. Wide range of devices. (This is happening in production)

### A full bug report captured from the device
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
       at java.util.regex.Matcher.reset(Matcher.java:995)
       at java.util.regex.Matcher.<init>(Matcher.java:174)
       at java.util.regex.Pattern.matcher(Pattern.java:1006)
       at com.google.android.exoplayer2.text.webvtt.WebvttCueParser.parseCue(WebvttCueParser.java:102)
       at com.google.android.exoplayer2.text.webvtt.WebvttDecoder.decode(WebvttDecoder.java:83)
       at com.google.android.exoplayer2.text.webvtt.WebvttDecoder.decode(WebvttDecoder.java:30)
       at com.google.android.exoplayer2.text.SimpleSubtitleDecoder.decode(SimpleSubtitleDecoder.java:70)
       at com.google.android.exoplayer2.text.SimpleSubtitleDecoder.decode(SimpleSubtitleDecoder.java:25)
       at com.google.android.exoplayer2.decoder.SimpleDecoder.decode(SimpleDecoder.java:222)
       at com.google.android.exoplayer2.decoder.SimpleDecoder.run(SimpleDecoder.java:188)
       at com.google.android.exoplayer2.decoder.SimpleDecoder.access$000(SimpleDecoder.java:25)
       at com.google.android.exoplayer2.decoder.SimpleDecoder$1.run(SimpleDecoder.java:66)
```

**Comment by dbrain** [comment]
This looks similar to https://github.com/google/ExoPlayer/pull/3185 which was an NPE when parsing the timing line of a subrip subtitle. Presumably also due to a corrupted subtitle file, but I could not reproduce myself (just saw Crashlytics issues).

Might be worth reviewing how all of the sub parsers handle corrupt subs / EOF in unexpected places.
