### ISSUE TITLE
Playing .h264 content fails

### ISSUE THREAD

**Issue by mahmoud-bahaa** [google/ExoPlayer#3232]
I get the following error when I try to play the file: java.lang.IllegalStateException: Top bit not zero: -7615023332543036719. These files are playable by VLC.
Is there another extractor I should be using?

### Issue description
I'm using ExtractorMediaSource to play .h264, however the exact mp4 content plays fine. This might be a missuse from my side.

### Reproduction steps
Playing any .h264 (raw bitstream) content.

### Version of ExoPlayer being used
2.5.1

### Device(s) and version(s) of Android being used
Android M

### A full bug report captured from the device
 E/ExoPlayerImplInternal: Source error.
                                                                                              com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: Top bit not zero: -8257344417688018912
                                                                                                  at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:337)
                                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                  at java.lang.Thread.run(Thread.java:818)
                                                                                               Caused by: java.lang.IllegalStateException: Top bit not zero: -8257344417688018912
                                                                                                  at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedLongToLong(ParsableByteArray.java:405)
                                                                                                  at com.google.android.exoplayer2.extractor.mp4.Sniffer.sniffInternal(Sniffer.java:111)
                                                                                                  at com.google.android.exoplayer2.extractor.mp4.Sniffer.sniffFragmented(Sniffer.java:73)
                                                                                                  at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.sniff(FragmentedMp4Extractor.java:213)
                                                                                                  at ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:756)
                                                                                                  at ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:691)
                                                                                                  at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                                  at java.lang.Thread.run(Thread.java:818)

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
