### ISSUE TITLE
UHD videos fails in Oppo A1601

### ISSUE THREAD

**Issue by MateusZitelli** [google/ExoPlayer#3265]
### Issue description
Fail to play UHD videos on Oppo A1601, while it plays flawlessly on the native player app. Moreover, I think this is relevant seeing that this phone have more the 7 million units sold and is the 8th most popular device in my user base.

### Reproduction steps
All UHD examples on the demo app fails with the same error.

### Link to test content
Not applicable.

### Version of ExoPlayer being used
r2.5.2

### Device(s) and version(s) of Android being used
Oppo A1601 with Android 5.1

### A full bug report captured from the device
```
09-14 19:37:15.683 12227-12544/com.google.android.exoplayer2.demo D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Now Loaded
09-14 19:37:15.685 12227-12532/com.google.android.exoplayer2.demo I/MediaCodec: [CreateByComponentName]line:166 OMX.MTK.VIDEO.DECODER.AVC
09-14 19:37:15.688 12227-12543/com.google.android.exoplayer2.demo I/MediaCodec: [onMessageReceived]line:1513 [DRM]set IsSecureVideo 
09-14 19:37:15.689 12227-12544/com.google.android.exoplayer2.demo D/ACodec: onConfigureComponent
09-14 19:37:15.690 12227-12544/com.google.android.exoplayer2.demo D/ACodec: Configuring CPU controlled video playback.
09-14 19:37:15.691 12227-12544/com.google.android.exoplayer2.demo D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] storeMetaDataInBuffers succeeded
09-14 19:37:15.692 12227-12544/com.google.android.exoplayer2.demo D/ACodec: GetVideoCodingTypeFromMime video/avc, video/avc
09-14 19:37:15.698 12227-12544/com.google.android.exoplayer2.demo E/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] configureCodec returning error 80000000
09-14 19:37:15.698 12227-12544/com.google.android.exoplayer2.demo E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
09-14 19:37:15.703 12227-12543/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 3
09-14 19:37:15.705 12227-12532/com.google.android.exoplayer2.demo E/MediaCodec: configure failed with err 0x80001001, resetting...
09-14 19:37:15.720 12227-12544/com.google.android.exoplayer2.demo D/ACodec: Now uninitialized
09-14 19:37:15.721 12227-12532/com.google.android.exoplayer2.demo D/ACodec: ~ACodec
09-14 19:37:15.721 12227-12532/com.google.android.exoplayer2.demo D/ACodec: Now uninitialized
09-14 19:37:15.722 12227-12544/com.google.android.exoplayer2.demo D/ACodec: onAllocateComponent
09-14 19:37:15.723 12227-12544/com.google.android.exoplayer2.demo I/OMXClient: Using client-side OMX mux.
09-14 19:37:15.723 12227-12544/com.google.android.exoplayer2.demo D/ACodec: mDeathNotifier is set
09-14 19:37:15.750 12227-12544/com.google.android.exoplayer2.demo D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Now Loaded
09-14 19:37:15.752 12227-12532/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Renderer error.
com.google.android.exoplayer2.ExoPlaybackException
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:395)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:382)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814)
    at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:435)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:574)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:210)
    at android.os.HandlerThread.run(HandlerThread.java:61)
 Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.AVC, Format(1, null, video/avc, 24089938, null, [3840, 1714, 30.0], [-1, -1])
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:382) 
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814) 
    at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:435) 
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513) 
    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:574) 
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350) 
    at android.os.Handler.dispatchMessage(Handler.java:107) 
    at android.os.Looper.loop(Looper.java:210) 
    at android.os.HandlerThread.run(HandlerThread.java:61) 
 Caused by: android.media.MediaCodec$CodecException: Error 0x80001001
    at android.media.MediaCodec.native_configure(Native Method)
    at android.media.MediaCodec.configure(MediaCodec.java:590)
    at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:405)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:371)
```

**Comment by ojw28** [comment]
Out of interest is this side-loaded content, or content you're serving from your own servers? I doubt there's much we'll be able to do about this, since the failure appears to be in the platform underneath us, but we can take a look.

**Comment by MateusZitelli** [comment]
The issue seems to be independent from the media source, in my application the video is loaded from the device storage itself.

**Comment by Caij** [comment]
Can't solve this problem?

**Comment by ojw28** [comment]
Closing as part of a scrub of device specific issues that were filed more than 2 years ago.
