### ISSUE TITLE
Philips: OMX.MTK.AUDIO.DECODER.DSPMP1 fails to initialize for audio/mpeg-L2

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#3266]
* checked with demo player from dev-v2, 340d0be40a6a1d744c79245289075b97db26f78e (2.5.2)
* fails to initialize decoder when _prefer_extension_decoders = false_, plays well with ffmpeg
* log from demo app playing both streams: https://drive.google.com/file/d/0Bww3WxdHUiM1dW1HNUR5aHU0QWc/view?usp=drivesdk
* apk with demo app configured for both streams: https://drive.google.com/file/d/0Bww3WxdHUiM1NV9fUHNYSzBXVVU/view?usp=drivesdk
* TS stream recorded from original stream: https://drive.google.com/file/d/0Bww3WxdHUiM1enMtOHRieE5wRGM/view?usp=drivesdk
* device:
```
System: 3.10.79 (eng.build_ci.20170707.132404)
Sdk: 23
Device: QM16XE_U
Product: QM16XE_U
Manufacturer: PHILIPS
Model: QM163E
```

```
com.google.android.exoplayer2.ExoPlaybackException
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:390)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:377)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:809)
	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:236)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:508)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:596)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:362)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.AUDIO.DECODER.DSPMP1, Format(410/413, null, audio/mpeg-L2, -1, lit, [-1, -1, -1.0], [2, 48000])
	... 9 more
Caused by: android.media.MediaCodec$CodecException: Error 0x80000001
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1778)
	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.configureCodec(MediaCodecAudioRenderer.java:218)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:366)
	... 8 more
```

This issue is most probably related to https://github.com/google/ExoPlayer/issues/1353, where same codec did have problems on Sony TV before system update to 6.0

Obviously this issue is for Philips devs, but probably ExoPlayer should blacklist it for proper renderer selection when `EXTENSION_RENDERER_MODE_ON` is used

**Comment by ojw28** [comment]
I doubt there's much we can do about this, beyond blacklisting the affected decoder on the affected API level(s) in `MediaCodecUtil.isCodecUsableDecoder`.

Please could you try doing that? How much it helps depends on whether there's a secondary decoder that works. If there is, you'd be in luck. If there isn't, you can still get playback to work when using `EXTENSION_RENDERER_MODE_ON` and an extension that provides the necessary decoder, as you correctly point out.

If such a change would be helpful to you, please send a pull request to our `dev-v2` branch. We do not have a device to reproduce or test on, so you're better placed to provide the fix. Thanks!

**Comment by stari4ek** [comment]
Sadly I do not have Philips TV device to test it properly, so all tests are done by users.

Stream has 3 audio tracks: two _mpeg/L2_ and one _ac3_
Blacklisting `OMX.MTK.AUDIO.DECODER.DSPMP1` brings another issue with playback: player selects AC3 track by default and there is no video when playing it. Disabling all tracks - brings video back.

```
00:58:28.814 Tracks [
00:58:28.814   Renderer:0 [
00:58:28.815     Group:0, adaptive_supported=N/A [
00:58:28.815       [X] Track:0, id=410/412, mimeType=video/avc, res=1920x1080, supported=YES
00:58:28.815     ]
00:58:28.815   ]
00:58:28.815   Renderer:1 [
00:58:28.815     Group:0, adaptive_supported=N/A [
00:58:28.815       [X] Track:0, id=410/415, mimeType=audio/ac3, channels=6, sample_rate=48000, language=lit, supported=YES
00:58:28.815     ]
00:58:28.815   ]
00:58:28.815   Renderer:2 [
00:58:28.815     Group:0, adaptive_supported=N/A [
00:58:28.816       [ ] Track:0, id=410/413, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, language=lit, supported=YES
00:58:28.816     ]
00:58:28.816     Group:1, adaptive_supported=N/A [
00:58:28.816       [ ] Track:0, id=410/414, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, language=qaa, supported=YES
00:58:28.817     ]
00:58:28.817   ]
00:58:28.817   Renderer:3 [
00:58:28.817     Group:0, adaptive_supported=N/A [
00:58:28.817       [ ] Track:0, id=410/8604, mimeType=application/cea-608, supported=YES
00:58:28.817     ]
00:58:28.817     Group:1, adaptive_supported=N/A [
00:58:28.817       [ ] Track:0, id=410/417, mimeType=application/dvbsubs, language=lit, supported=YES
00:58:28.817     ]
00:58:28.817   ]
00:58:28.817 ]
00:58:28.819 videoEnabled [0.70]
00:58:28.819 audioEnabled [0.70]
00:58:28.907 videoDecoderInitialized [0.78, OMX.MTK.VIDEO.DECODER.AVC]
00:58:28.907 videoFormatChanged [0.79, id=410/412, mimeType=video/avc, res=1920x1080]
00:58:28.942 audioDecoderInitialized [0.82, OMX.MTK.AUDIO.DECODER.DSPAC3]
00:58:28.943 audioFormatChanged [0.82, id=410/415, mimeType=audio/ac3, channels=6, sample_rate=48000, language=lit]
00:58:29.674 videoSizeChanged [1920, 1080]
00:58:29.674 renderedFirstFrame [Surface(name=null)/@0xaddd5]
00:58:37.740 state [9.62, true, R]
00:58:37.752 state [9.63, true, B]
```
with `EXTENSION_RENDERER_MODE_PREFER`:
```
00:57:02.022 videoDecoderInitialized [0.64, OMX.MTK.VIDEO.DECODER.AVC]
00:57:02.023 videoFormatChanged [0.64, id=410/412, mimeType=video/avc, res=1920x1080]
00:57:02.044 audioDecoderInitialized [0.66, ffmpegLavc57.70.100-mp3]
00:57:02.044 audioFormatChanged [0.66, id=410/413, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, language=lit]
00:57:02.065 audioSessionId [29]
00:57:02.882 videoSizeChanged [1920, 1080]
00:57:02.904 renderedFirstFrame [Surface(name=null)/@0x223baeb]
00:57:03.982 state [2.60, true, R]
```

Something is totally wrong with decoders on Philips. I think that forcing `EXTENSION_RENDERER_MODE_PREFER` for Philips is better solution in my case (android tv app) than trying to workaround all problematic decoders/situations on exoplayer's side, especially without real devices and playback tests on them.
Thank you.

**Comment by stari4ek** [comment]
Same for
```
Device: QM16XE_F
Product: QM16XE_F
Manufacturer: PHILIPS
Model: QM164E
```

**Comment by ojw28** [comment]
I don't think there's much we can do about this, unfortunately. Closing as obsolete / non-actionable.
