### ISSUE TITLE
HLS multiple streaming playing

### ISSUE THREAD

**Issue by hawkiq** [google/ExoPlayer#3269]
I know this this not Exoplayer fault but am confused,
I have two mp4 files with two URLs I've implement simple app to play them and two buttons to select between them its working perfectly,
But when switching to HLS streaming every time I try to change source it give me an error
my function to do this 
```
    private void initPlayer(String streamingURL) {
        mediaDataSourceFactory = new DefaultDataSourceFactory(this, (TransferListener<? super DataSource>) bandwidthMeter,
                new DefaultHttpDataSourceFactory(userAgent, (TransferListener<? super DataSource>) bandwidthMeter));
        bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory =
                new AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector =
                new DefaultTrackSelector(videoTrackSelectionFactory);
        // 2. Create a default LoadControl
        LoadControl loadControl = new DefaultLoadControl();
        // 3. Create the player
        player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);
        simpleExoPlayerView.requestFocus();

        simpleExoPlayerView.setPlayer(player);
        simpleExoPlayerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_FILL);
        // Measures bandwidth during playback. Can be null if not required.
        DefaultBandwidthMeter DefBandwidthMeter = new DefaultBandwidthMeter();
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this,
                userAgent, DefBandwidthMeter);
        // Produces Extractor instances for parsing the media data.
        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

        // This is the MediaSource representing the media to be played.
        Uri streamingVideoUri;
        streamingVideoUri = Uri.parse(streamingURL);
       // MediaSource videoSource = new HlsMediaSource(streamingVideoUri,
               // dataSourceFactory, extractorsFactory, null, null);
        MediaSource videoSource = new HlsMediaSource(streamingVideoUri, mediaDataSourceFactory,handler,eventListener);

        player.prepare(videoSource);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE);
        // Prepare the player with the source.
        player.setPlayWhenReady(true);
    }
```

button to change source

```
        sdBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toast.makeText(getApplicationContext(),streamingURLSD,Toast.LENGTH_SHORT).show();
               player.release();
                initPlayer(streamingURLSD);
                if(bAutoplay){
                    if(player!=null){
                        player.setPlayWhenReady(true);
                        bIsPlaying=true;
                    }
                }
            }
        });
```

error log

```FATAL EXCEPTION: main
                                                                 Process: iq.osamasw.hhls, PID: 28869
                                                                 java.lang.NullPointerException
                                                                     at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:107)
                                                                     at com.google.android.exoplayer2.source.AdaptiveMediaSourceEventListener$EventDispatcher.<init>(AdaptiveMediaSourceEventListener.java:183)
                                                                     at com.google.android.exoplayer2.source.AdaptiveMediaSourceEventListener$EventDispatcher.<init>(AdaptiveMediaSourceEventListener.java:178)
                                                                     at com.google.android.exoplayer2.source.hls.HlsMediaSource.<init>(HlsMediaSource.java:73)
                                                                     at com.google.android.exoplayer2.source.hls.HlsMediaSource.<init>(HlsMediaSource.java:63)
                                                                     at com.google.android.exoplayer2.source.hls.HlsMediaSource.<init>(HlsMediaSource.java:56)
                                                                     at iq.osamasw.hhls.PlayChannel.initPlayer(PlayChannel.java:300)
                                                                     at iq.osamasw.hhls.PlayChannel.access$700(PlayChannel.java:58)
                                                                     at iq.osamasw.hhls.PlayChannel$7.onClick(PlayChannel.java:215)
                                                                     at android.view.View.performClick(View.java:6213)
                                                                     at android.widget.TextView.performClick(TextView.java:11074)
                                                                     at android.view.View$PerformClick.run(View.java:23645)
                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by ojw28** [comment]
If you look at `AdaptiveMediaSourceEventListener.java:183`, you should be able to deduce this failure is because you're passing a null handler and non-null eventListener when building the `HlsMediaSource`. If you're passing a non-null eventListener, the handler is not allowed to be null.
