### ISSUE TITLE
Decoder init failed: OMX.qcom.video.decoder.avc

### ISSUE THREAD

**Issue by mraj0045** [google/ExoPlayer#3282]
Device MotoE2, Android 5.1.
I'm playing this video from the asset folder.
I will email the video.

```
 Renderer error.
com.google.android.exoplayer2.ExoPlaybackException
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:395)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:382)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:435)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:574)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)
 Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [1920, 1080, -1.0], [-1, -1])
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:382) 
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814) 
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:435) 
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513) 
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:574) 
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350) 
	at android.os.Handler.dispatchMessage(Handler.java:98) 
	at android.os.Looper.loop(Looper.java:135) 
	at android.os.HandlerThread.run(HandlerThread.java:61) 
 Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:584)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:405)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:371)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814) 
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:435) 
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513) 
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:574) 
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350) 
	at android.os.Handler.dispatchMessage(Handler.java:98) 
	at android.os.Looper.loop(Looper.java:135) 
	at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by ojw28** [comment]
Please provide a full bug report, as requested in the issue template.

**Comment by mraj0045** [comment]
[bugreport.txt](https://github.com/google/ExoPlayer/files/1323581/bugreport.txt)
While Playing video from asset folder `Decoder init failed: OMX.qcom.video.decoder.avc`  the issue occurs and video is not playing.

Reproduction Steps:
Play the video from the asset folder using the Exoplayer Demo App.
Exoplayer version used: r2.5.3
Device MotoE2, Android 5.1

**Comment by ojw28** [comment]
The bug report provided does not capture the issue described. Please capture a bug report shortly after reproducing the problem. Thanks.

**Comment by mraj0045** [comment]
@ojw28 I have captured the bug report as you have mentioned.

[bug_report.txt](https://github.com/google/ExoPlayer/files/1340114/bug_report.txt)
[logcat.txt](https://github.com/google/ExoPlayer/files/1340113/logcat.txt)

**Comment by ojw28** [comment]
I think you're just trying to play a video that exceeds the capabilities of the device. In the bug report:

```
MediaCodecInfo: NoSupport [size.support, 1920x1080] [OMX.qcom.video.decoder.avc, video/avc] [otus_ds, MotoE2, motorola, 22]
```

Note that the video you're trying to play has 4x the number of pixels as the display. It's quite common for devices to only be able to decode approximately 1x the number of pixels as the display.
