### ISSUE TITLE
UnexpectedLengthException thrown frmo DefaultHttpDataSource.read

### ISSUE THREAD

**Issue by samek** [google/ExoPlayer#329]
Hi, 

On samsung GT-I8190 with 4.1.2 none of the HLS video  play, which do work on other devices (tested on Nexus 5 / 7 /9, Philips android TV, Lenovo A7)
 
HLS is AES encrypted. Looking at the log file It seems that It has to do something with the key (length) ? 

In the logs I get:  
 
02-26 16:47:57.857  28188-28907/? E/ExoPlayerImplInternalï¹• Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: com.google.android.exoplayer.upstream.UnexpectedLengthException: Expected: 37, got: 16
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:223)
            at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:115)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: com.google.android.exoplayer.upstream.UnexpectedLengthException: Expected: 37, got: 16
            at com.google.android.exoplayer.upstream.HttpDataSource.read(HttpDataSource.java:318)
            at com.google.android.exoplayer.upstream.UriDataSource.read(UriDataSource.java:71)
            at com.google.android.exoplayer.util.BitArray.append(BitArray.java:104)
            at com.google.android.exoplayer.hls.BitArrayChunk.load(BitArrayChunk.java:92)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:206)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: com.google.android.exoplayer.upstream.UnexpectedLengthException: Expected: 37, got: 16
Â Â Â Â Â Â Â Â Â Â Â Â at com.google.android.exoplayer.upstream.HttpDataSource.read(HttpDataSource.java:318)
Â Â Â Â Â Â Â Â Â Â Â Â at com.google.android.exoplayer.upstream.UriDataSource.read(UriDataSource.java:71)
Â Â Â Â Â Â Â Â Â Â Â Â at com.google.android.exoplayer.util.BitArray.append(BitArray.java:104)
Â Â Â Â Â Â Â Â Â Â Â Â at com.google.android.exoplayer.hls.BitArrayChunk.load(BitArrayChunk.java:92)
Â Â Â Â Â Â Â Â Â Â Â Â at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:206)
Â Â Â Â Â Â Â Â Â Â Â Â at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
Â Â Â Â Â Â Â Â Â Â Â Â at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
Â Â Â Â Â Â Â Â Â Â Â Â at java.util.concurrent.FutureTask.run(FutureTask.java:137)
Â Â Â Â Â Â Â Â Â Â Â Â at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
Â Â Â Â Â Â Â Â Â Â Â Â at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
Â Â Â Â Â Â Â Â Â Â Â Â at java.lang.Thread.run(Thread.java:856)
02-26 16:47:57.857  28188-28188/? E/EventLoggerï¹• playerFailed [5.59]
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: com.google.android.exoplayer.upstream.UnexpectedLengthException: Expected: 37, got: 16
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:223)
            at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:115)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: com.google.android.exoplayer.upstream.UnexpectedLengthException: Expected: 37, got: 16
            at com.google.android.exoplayer.upstream.HttpDataSource.read(HttpDataSource.java:318)
            at com.google.android.exoplayer.upstream.UriDataSource.read(UriDataSource.java:71)
            at com.google.android.exoplayer.util.BitArray.append(BitArray.java:104)
            at com.google.android.exoplayer.hls.BitArrayChunk.load(BitArrayChunk.java:92)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:206)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: com.google.android.exoplayer.upstream.UnexpectedLengthException: Expected: 37, got: 16
Â Â Â Â Â Â Â Â Â Â Â Â at com.google.android.exoplayer.upstream.HttpDataSource.read(HttpDataSource.java:318)
Â Â Â Â Â Â Â Â Â Â Â Â at com.google.android.exoplayer.upstream.UriDataSource.read(UriDataSource.java:71)
Â Â Â Â Â Â Â Â Â Â Â Â at com.google.android.exoplayer.util.BitArray.append(BitArray.java:104)
Â Â Â Â Â Â Â Â Â Â Â Â at com.google.android.exoplayer.hls.BitArrayChunk.load(BitArrayChunk.java:92)
Â Â Â Â Â Â Â Â Â Â Â Â at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:206)
Â Â Â Â Â Â Â Â Â Â Â Â at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
Â Â Â Â Â Â Â Â Â Â Â Â at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
Â Â Â Â Â Â Â Â Â Â Â Â at java.util.concurrent.FutureTask.run(FutureTask.java:137)
Â Â Â Â Â Â Â Â Â Â Â Â at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
Â Â Â Â Â Â Â Â Â Â Â Â at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
Â Â Â Â Â Â Â Â Â Â Â Â at java.lang.Thread.run(Thread.java:856)

**Comment by ojw28** [comment]
Please provide a link to a test stream that reproduces the issue. I don't think the error is related to AES. It looks more like the content that's read from the server is for some reason not of the expected length.

**Comment by samek** [comment]
ojw28 Is there a way of sending the url privately Since I really should not post it here ?

**Comment by ojw28** [comment]
You can email it to olly.exoplayer@gmail.com.

**Comment by samek** [comment]
sent.

**Comment by ojw28** [comment]
Thanks! This is related to the way HttpUrlConnection supports transparent gzip, although I'm not sure why it's so device specific.

- Some thought will be needed to determine the best "proper" fix for this, but if you want a quick local fix for this, you can safely remove lines 315-320 in [HttpDataSource](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/upstream/HttpDataSource.java#L315). If you're using the dev branch then this code has moved to a class called DefaultHttpDataSource, so you'd need to delete the equivalent code block there (note - the line numbers are different).

- Having fixed the issue, I pretty reliably see a native crash in the video decoder about 39 seconds into the content. It seems the device can't copy with your highest bitrate stream, so you'll need to find a way of disabling it for this device.

**Comment by samek** [comment]
Great news. I'll test it as when I'm in the office.  It seams like most of  4.1.x are having this problem? Yesterday I got a tabled with 4.1.2 - same issue.

**Comment by ojw28** [comment]
This should be fixed on the dev branch. Please validate, and let me know if you're still seeing issues.
