### ISSUE TITLE
MediaCodec CryptoException on *some* devices with Widevine L1 encryption

### ISSUE THREAD

**Issue by SoroushDMA** [google/ExoPlayer#3310]
### Issue description
DASH playback of H.264 content protected with Widevine Modular DRM on some devices is failing if the license enforces Widevine L1 security, but succeeds if the license allows L3
This issue happens only on a set of devices such as Samsung galaxy s7, s8 edge

### Reproduction steps
I just put our video URL and license URL in the `media.exolist.json` file of the demo app. It worked for some devices such as: Google Pixel Oreo, Nexus 5x Nougat, Nexus 6 Marshmallow

Same test fails for: Samsung Galaxy S8 edge Nougat, Samsung Galaxy S7 edge Nougat, Samsung Galaxy S4 Lollipop

I have to emphasize that same content with Widevine L3 security on license works on all devices.

### Link to test content
I can provide a link to the content via email if it's required. Please let me know, since the license will expire after 24 hour.

### Version of ExoPlayer being used
I tested this against Exoplayer 2.5.3 and Exoplayer 2.3.1

### Device(s) and version(s) of Android being used
Devices that successfully could playback the content:
- Google Pixel - Oreo 
-  Nexus 5x  - Nougat
-  Nexus 6 - Marshmallow

Devices that failed to playback:

- Samsung Galaxy S8 edge Nougat
- Samsung Galaxy S7 edge Nougat
- Samsung Galaxy S4 Lollipop

### A full bug report captured from the device

```

09-29 13:40:40.395 30757-31810/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Renderer error.
                                                                                           com.google.android.exoplayer2.ExoPlaybackException
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:727)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:530)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:574)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                            Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: unspecified error
                                                                                               at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                               at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2478)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:718)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:530) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:574) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350) 
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                               at android.os.Looper.loop(Looper.java:154) 
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61) 
09-29 13:40:40.398 30757-32207/com.google.android.exoplayer2.demo I/ACodec: [OMX.Exynos.avc.dec.secure] Now Executing->Idle
09-29 13:40:40.408 30757-30757/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [4.39]
                                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:727)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:530)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:574)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                  Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: unspecified error
                                                                                     at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                     at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2478)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:718)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:530) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:574) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) ```

**Comment by ojw28** [comment]
Please provide a *full* bug report, as requested in the issue template.

**Comment by SoroushDMA** [comment]
[mybugreport.zip](https://github.com/google/ExoPlayer/files/1349787/mybugreport.zip)

**Comment by SoroushDMA** [comment]
Attached the bug report

**Comment by SoroushDMA** [comment]
[mybugreport.zip](https://github.com/google/ExoPlayer/files/1349822/mybugreport.zip)

**Comment by fredgc** [comment]
We are sharing your bugreport with Samsung.

**Comment by mayankgarg58** [comment]
Hello,

Can you please tell me exact reprodution steps and application used in the issue?

We need to reproduce this issue at our end to fetch more i formation with debug binary.

**Comment by SoroushDMA** [comment]
@mayankgarg58 You need to have a Widevine DASH content on your server which the L1 security level is enforced. Then try to play the content using Exoplayer with one of the devices I mentioned in the description.

**Comment by SoroushDMA** [comment]
@mayankgarg58 You need to have a Widevine DASH content on your server which the L1 security level is enforced. Then try to play the content using Exoplayer with one of the devices I mentioned in the description.

**Comment by mayankgarg58** [comment]
I tried to play secure content using exoplayer application.
I could not reproduce the issue.
Is there any proper way to reproduce it.?

**Comment by SoroushDMA** [comment]
Is your content L1 secure? If that's the case and you can't reproduce is, I can send a message directly to you, but the URL will be valid for 12 hours only.

**Comment by mayankgarg58** [comment]
Yes. Content is secure. I mean L1.
And i used exoplayer demo app. 
Can you give me the application you are using.
And provide url as well. I ll check at my end.

**Comment by wvpaf** [comment]
Hi @SoroushDMA, can you please provide @mayankgarg58 the info requested? Thanks.

**Comment by SoroushDMA** [comment]
@wvpaf @mayankgarg58 unfortunately i can't provide any link on public forum, can I have your email so I can send it to you directly?

BTW, I'm using exoplayer demo code for testing.

**Comment by wvpaf** [comment]
If you use  dev.exoplayer@gmail.com, we can attempt to get the data to @mayankgarg58.

thanks.

**Comment by mayankgarg58** [comment]
Id- m.garg@samsung.com
I am using exoplayer demo app.

**Comment by wvpaf** [comment]
closing due to inactivity.
