### ISSUE TITLE
Ffmpeg Audio Renderer: how to play remote .aac file

### ISSUE THREAD

**Issue by alexmprog** [google/ExoPlayer#3331]
Hi everyone, 
I tried to play .aac file [https://myserver.com/path/to/file/temp.acc](url) using ExoPlayer with Ffmpeg extension. This file was uploaded from Iphone. I have already built extension and added all code to my project(using Readme.md notes for github)
I tried to start play like this:
`
		audioMediaPlayer = ExoPlayerFactory.newSimpleInstance(
				new DefaultRenderersFactory(viewContext, null, EXTENSION_RENDERER_MODE_PREFER),
				new DefaultTrackSelector(), new DefaultLoadControl());

		List<byte[]> encoderData = new ArrayList<>();
		encoderData.add(new byte[]{});
		Format format = Format.createAudioSampleFormat(null, MimeTypes.AUDIO_AAC, null, Format.NO_VALUE,
				Format.NO_VALUE, 1, 44100, C.ENCODING_PCM_16BIT, encoderData, null, 0, null);

		
		MediaSource mediaSource = new SingleSampleMediaSource(uri, new DefaultHttpDataSourceFactory("client"),
				format, 0);

		audioMediaPlayer.setPlayWhenReady(true);
		audioMediaPlayer.prepare(mediaSource);
`

I added empty data to Format object, because I don't know how prepare .aac decoder initial data here. I got error here : 
`
 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.render(SimpleDecoderAudioRenderer.java:221)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:574)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                  Caused by: com.google.android.exoplayer2.ext.ffmpeg.FfmpegDecoderException: Error decoding (see logcat). Code: -1094995529
                                                                                     at com.google.android.exoplayer2.ext.ffmpeg.FfmpegDecoder.decode(FfmpegDecoder.java:88)
                                                                                     at com.google.android.exoplayer2.ext.ffmpeg.FfmpegDecoder.decode(FfmpegDecoder.java:30)
                                                                                     at com.google.android.exoplayer2.decoder.SimpleDecoder.decode(SimpleDecoder.java:222)
                                                                                     at com.google.android.exoplayer2.decoder.SimpleDecoder.run(SimpleDecoder.java:188)
                                                                                     at com.google.android.exoplayer2.decoder.SimpleDecoder.access$000(SimpleDecoder.java:25)
                                                                                     at com.google.android.exoplayer2.decoder.SimpleDecoder$1.run(SimpleDecoder.java:66)
`
If I correctly understand I didn't initialized ffmpeg decoder correctly. But I don't have initial data for decoder at that moment. How to fix this issue? I also tried use ExtractorMediaSource, but in this case FfmpegAudioRenderer was ignored - ExoPlayer check on extractors under DefaultExtractorsFactory. 
Best Regards, Alex.

**Comment by andrewlewis** [comment]
`FfmpegAudioRenderer` decodes and renders audio samples. For extraction you do need to use `ExtractorMediaSource`. Did you build ffmpeg with `--enable-decoder=aac`? Does the audio play fine with `MediaCodecAudioRenderer` when you don't prefer the extension renderer? It would be useful to have a link to the media you're trying to play too.

**Comment by alexmprog** [comment]
Hi, @andrewlewis Thanks for you answer. 
Yes, I built ffmpeg extension correctly - included --enable-decoder=aac
I can not share file for now - it's protected by NDA.
On IOS side this file was recorded using code very similar to this:
`
NSURL *soundFileURL = [NSURL fileURLWithPath:soundFilePath];
NSDictionary *recordSettings = [NSDictionary dictionaryWithObjectsAndKeys:
                                  [NSNumber numberWithInt:kAudioFormatMPEG4AAC], AVFormatIDKey,
                                  [NSNumber numberWithInt:AVAudioQualityMin], AVEncoderAudioQualityKey,
                                  [NSNumber numberWithInt:16], AVEncoderBitRateKey,
                                  [NSNumber numberWithInt: 1], AVNumberOfChannelsKey,
                                  [NSNumber numberWithFloat:8000.0], AVSampleRateKey,
                                  nil];
`
and this file was upload to server - it's a .aac file.
I tried first use ExtractorMediaSource which is part of ExoPlayer lib, but I got this error:
`
if (extractor == null) {
        throw new UnrecognizedInputFormatException("None of the available extractors ("
            + Util.getCommaDelimitedSimpleClassNames(extractors) + ") could read the stream.", uri);
      }
` from ExtractorMediaPeriod.java class. So it means default Extractors can not process this file.  And when I used ExtractorMediaSource FfmpegAudioRenderer was ignored when tried to player source - i used this option for creation factory:
`
new DefaultRenderersFactory(viewContext, null, EXTENSION_RENDERER_MODE_PREFER),
`
That's why I try to use SingleSampleMediaSource. But this media source required Format object. And if correctly understand we need to have byte[] init data, which aac encoder get during recording process on IOS - we should use for configuration of ffmpeg decoder. Is encoderData is required for Ffmpeg decoder?
`
List<byte[]> encoderData = new ArrayList<>();
	encoderData.add(new byte[]{});
	Format format = Format.createAudioSampleFormat(null, MimeTypes.AUDIO_AAC, null, Format.NO_VALUE,
			Format.NO_VALUE, 1, 44100, C.ENCODING_PCM_16BIT, encoderData, null, 0, null);
`
Best Regards, Alex.

**Comment by ojw28** [comment]
The file will have a sample format (aac) and a container format (?). The problem is that ExoPlayer is not recognizing the container format, not that it can't handle aac sample data. I think we need a sample media file or information about the container to make progress here.

Would it be possible for you to produce another file in the same way whose content is not protected by NDA?

**Comment by alexmprog** [comment]
[test.zip](https://github.com/google/ExoPlayer/files/1375773/test.zip)
Hi @ojw28. Thanks for your answer. Ok, I added two files in attachments. One file recored on IOS, second on Android. On android file was recorded using code like this:
`recorder.setAudioSource(MediaRecorder.AudioSource.MIC);
		recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);
		recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);
		recorder.setAudioEncodingBitRate(16);
		recorder.setAudioSamplingRate(44100);
		recorder.setAudioChannels(1);
`

On IOS like this(may be only bitrate was different):
`NSDictionary *recordSettings = [NSDictionary dictionaryWithObjectsAndKeys:
                                  [NSNumber numberWithInt:kAudioFormatMPEG4AAC], AVFormatIDKey,
                                  [NSNumber numberWithInt:AVAudioQualityMin], AVEncoderAudioQualityKey,
                                  [NSNumber numberWithInt:16], AVEncoderBitRateKey,
                                  [NSNumber numberWithInt: 1], AVNumberOfChannelsKey,
                                  [NSNumber numberWithFloat:8000.0], AVSampleRateKey,
                                  [NSNumber numberWithInt:8], AVLinearPCMBitDepthKey,
                                  nil];
`

Then I tried play two files using default ExoPlayer : 
`SimpleExoPlayer audioMediaPlayer = ExoPlayerFactory.newSimpleInstance(
				new DefaultRenderersFactory(viewContext, null, EXTENSION_RENDERER_MODE_PREFER),
				new DefaultTrackSelector(), new DefaultLoadControl());
		MediaSource mediaSource = new ExtractorMediaSource(uri, new DefaultHttpDataSourceFactory("client"),
				new DefaultExtractorsFactory(), null, null);
		audioMediaPlayer.setPlayWhenReady(true);
		audioMediaPlayer.prepare(mediaSource);`
Now file, which was recorded on Android play fine(I have method invocation inside FfmpegDecoder java class), but playback file from IOS has error:
`
Source error.
                                                                                 com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:774)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:697)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                     at java.lang.Thread.run(Thread.java:762)
`

When I turn off Ffmpeg extension(used EXTENSION_RENDERER_MODE_OFF), file which was recorded on Android also playable by Mp4Extractor, but I don't have any callback in FfmpegDecoder class. Please check these cases.
Best Regards, Alex.

**Comment by ojw28** [comment]
The iOS file doesn't play in either VLC (which is well known to play "almost anything") or Chrome either. Neither does mediainfo derive any useful information from it (see outputs below). I don't know about recording on iOS, but it appears that the way you're doing it is either not portable or broken. You probably need to fix the iOS recording side to produce files that are can be played back by other players.

```
> mediainfo aac_ios.aac 
General
Complete name                            : aac_ios.aac
File size                                : 53.7 KiB
```

```
> mediainfo aac_android.aac 
General
Complete name                            : aac_android.aac
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42
File size                                : 7.31 KiB
Duration                                 : 4s 365ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 13.7 Kbps
Encoded date                             : UTC 2017-10-11 13:32:09
Tagged date                              : UTC 2017-10-11 13:32:09
com.android.version                      : 7.0

Audio
ID                                       : 1
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 4s 365ms
Bit rate mode                            : Constant
Bit rate                                 : 10.9 Kbps
Nominal bit rate                         : 8 192 bps
Channel(s)                               : 1 channel
Channel positions                        : Front: C
Sampling rate                            : 44.1 KHz
Compression mode                         : Lossy
Stream size                              : 5.83 KiB (80%)
Title                                    : SoundHandle
Language                                 : English
Encoded date                             : UTC 2017-10-11 13:32:09
Tagged date                              : UTC 2017-10-11 13:32:09
```

**Comment by alexmprog** [comment]
@ojw28 Thanks for your answer. Yes, you're right. We will fix audio recording on IOS side. This issue should be closed. 
Best regards, Alex.
