### ISSUE TITLE
DashMediaSource throws an exception and dies when subtitle track is removed from manifest

### ISSUE THREAD

**Issue by jeeb** [google/ExoPlayer#3343]
### Issue description
Happens both with an application utilizing ExoPlayer as a library as well as the demo application.

Playback of content where the subtitle track can appear or disappear dynamically depending on whether or not subtitles exist for the current time line within the manifest throws an exception. While in VOD cases this would not happen, with live streams this can easily happen.

It is highly likely that this would happen in case of any stream type, rather than limited to subtitles.

### Reproduction steps
* Open an MPEG-DASH stream where the manifest initially contains a certain alternative track.
* Then remove the track.

### Link to test content
It should be enough to replace a manifest that initially contains subtitles underneath the player with one that doesn't contain subtitles.

### Version of ExoPlayer being used
r2.5.3 (pulled latest _release-v2_)

### Device(s) and version(s) of Android being used
Not specific to a specific device or Android version, but debugged with OnePlus One, sporting Android 6.0.

### A full bug report captured from the device
Back-trace of where the IndexOutOfBoundsException happens.
```
10-11 18:06:59.804 782-1054/com.google.android.exoplayer2.demo E/AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
                                                                                 Process: com.google.android.exoplayer2.demo, PID: 782
                                                                                 Theme: themes:{default=overlay:com.cyngn.hexo, iconPack:com.cyngn.hexoicons, fontPkg:com.cyngn.hexo, com.android.systemui=overlay:com.cyngn.hexo, com.android.systemui.navbar=overlay:com.cyngn.hexo}
                                                                                 java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
                                                                                     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                     at java.util.ArrayList.get(ArrayList.java:308)
                                                                                     at java.util.Collections$UnmodifiableList.get(Collections.java:1054)
                                                                                     at com.google.android.exoplayer2.source.dash.DefaultDashChunkSource.getRepresentations(DefaultDashChunkSource.java:309)
                                                                                     at com.google.android.exoplayer2.source.dash.DefaultDashChunkSource.updateManifest(DefaultDashChunkSource.java:148)
                                                                                     at com.google.android.exoplayer2.source.dash.DashMediaPeriod.updateManifest(DashMediaPeriod.java:96)
                                                                                     at com.google.android.exoplayer2.source.dash.DashMediaSource.processManifest(DashMediaSource.java:465)
                                                                                     at com.google.android.exoplayer2.source.dash.DashMediaSource.onManifestLoadCompleted(DashMediaSource.java:373)
                                                                                     at com.google.android.exoplayer2.source.dash.DashMediaSource$ManifestCallback.onLoadCompleted(DashMediaSource.java:740)
                                                                                     at com.google.android.exoplayer2.source.dash.DashMediaSource$ManifestCallback.onLoadCompleted(DashMediaSource.java:734)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:383)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by ojw28** [comment]
I don't think it's valid in the DASH spec to dynamically remove (or add) Representation or AdaptationSet elements to an existing Period. You're supposed to start a new Period if you want to change the available Representations or AdaptationSets. We already handle this case correctly in ExoPlayer.

It's pretty standard to start a new Period at points where the underlying content changes (e.g. start of an ad, start of a new piece of content), which are typically the point at which the available Representations change. Within a single piece of content, if there's a subtitle track, you should typically represent gaps between subtitles as empty chunks, rather than removing the whole Representation or anything like that.

**Comment by dwbuiten** [comment]
I get that it's not valid input, but shouldn't it be handled better than exploding?

**Comment by ojw28** [comment]
Didn't spot this was actually killing the whole process. Yes, it shouldn't do that, and this is tracked by https://github.com/google/ExoPlayer/issues/2795. We're not going to make any attempt to continue playback though. We'll just change it to be a playback failure rather than causing process death (the application could attempt to start playback again if it chose to do so).

I disagree this is easy or likely to happen. In a correct DASH streaming implementation this will *never* happen. If it does happen, the streaming provider should just go and fix it.

**Comment by dwbuiten** [comment]
That seems fair enough to me

> I disagree this is easy or likely to happen. In a correct DASH streaming implementation this will never happen. If it does happen, the streaming provider should just go and fix it.

However, you can never make the assumption that users will not to ridiculous things or have correct implementations. This is the internet, after all. Rejecting them is fine, of course, but they'll exist...

**Comment by ojw28** [comment]
Yep; I think failing the playback gracefully (i.e. not crashing) is the appropriate level of handling for this kind of thing though :). Thanks!

**Comment by jeeb** [comment]
Cheers. I will take this up with the media server folk. They seem to be checking if there were any fragments/samples in the buffer calculated for a given time segment during the request (this is a live stream that's constantly being ingested) and if there happen to be no such things the stream gets removed. The Period of the live manifest seems to always be 1 so I will guess that's static.

In other words, I'll go complain to those folks, thanks for the quick response :) .

**Comment by ba-a** [comment]
I think the DASH specification is not completely clear about this. There are some valid reasons that the amount of `AdaptionSets` could change during a Playout. For example subtitles.   

Imagine a livestream where subtitles are available and they stop being available at a certain point (because the program changed f.e.). 
Then you would get one manifest with the `text` AdaptionSet and when the next one without the subtitle arrives the player crashes during the manifest update.

So you have to make every user reload the stream (well he has to anyways because the process crashed :) ).
We tried that, I will add the manifest sample in case you want to take a look.

[AdaptionSet Problem.txt](https://github.com/google/ExoPlayer/files/1395159/AdaptionSet.Problem.txt)

Cheers.

**Comment by ojw28** [comment]
@ba-a - The DASH specification handles the exact case you describe by allowing you to start a new Period element. Moving to a new Period allows you to change the AdaptationSet elements, and we already handle this correctly in ExoPlayer.

**Comment by ba-a** [comment]
Alright, thanks for your response. I will discuss this with our Video Backend Team.
