### ISSUE TITLE
response code -1

### ISSUE THREAD

**Issue by fernandomaciel78** [google/ExoPlayer#3346]
My attempts at streaming radio where AAC is is not trying to succeed. Always returns the log below.
What can I be doing wrong?
E/ExoPlayerImplInternal: Source error.
                                                                                  com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: -1
                                                                                      at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                                      at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                      at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
                                                                                      at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
                                                                                      at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:113)
                                                                                      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                                      at java.lang.Thread.run(Thread.java:841)

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by ojw28** [comment]
Also, a search of [existing issues](https://github.com/google/ExoPlayer/issues?utf8=%E2%9C%93&q=%22InvalidResponseCodeException%3A%20Response%20code%3A%20-1%22) should help answer this ;)...
