### ISSUE TITLE
E/ExoPlayerImplInternal﹕ Internal track renderer error.

### ISSUE THREAD

**Issue by HugoGresse** [google/ExoPlayer#338]
I've some issue with lastest version on Master which cause ExoPlayer to fail preparing the video. Here the complete log : 

    03-06 11:35:53.767  16830-16830/com.example.sdkapptest I/ExoPlayerImpl﹕ Init 1.2.3
    03-06 11:35:53.767  16830-16830/com.example.sdkapptest D/EventLogger﹕ start [0]
    03-06 11:35:53.767  16830-16830/com.example.sdkapptest D/EventLogger﹕ state [0.00, false, P]
    03-06 11:35:53.767  16830-16830/com.example.sdkapptest I/dalvikvm﹕ Could not find method android.media.MediaCodec.releaseOutputBuffer, referenced from method com.google.android.exoplayer.MediaCodecVideoTrackRenderer.renderOutputBufferTimedV21
    03-06 11:35:53.767  16830-16830/com.example.sdkapptest W/dalvikvm﹕ VFY: unable to resolve virtual method 928: Landroid/media/MediaCodec;.releaseOutputBuffer (IJ)V
    03-06 11:35:53.767  16830-16830/com.example.sdkapptest D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0008
    03-06 11:35:53.767  16830-16830/com.example.sdkapptest I/dalvikvm﹕ Could not find method android.media.AudioTrack.write, referenced from method com.google.android.exoplayer.audio.AudioTrack.writeNonBlockingV21
    03-06 11:35:53.777  16830-16830/com.example.sdkapptest W/dalvikvm﹕ VFY: unable to resolve virtual method 911: Landroid/media/AudioTrack;.write (Ljava/nio/ByteBuffer;II)I
    03-06 11:35:53.777  16830-16830/com.example.sdkapptest D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0001
    03-06 11:36:03.817  16830-16912/com.example.sdkapptest I/ChromiumHTTPDataSourceSupport﹕ Request failed with status 4 and os_error -105
    03-06 11:36:03.827  16830-16911/com.example.sdkapptest E/ExoPlayerImplInternal﹕ Internal track renderer error.
        com.google.android.exoplayer.ExoPlaybackException: java.io.IOException: Failed to instantiate extractor.
                at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:223)
                at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:115)
                at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
                at android.os.Handler.dispatchMessage(Handler.java:98)
                at android.os.Looper.loop(Looper.java:136)
                at android.os.HandlerThread.run(HandlerThread.java:61)
                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
         Caused by: java.io.IOException: Failed to instantiate extractor.
                at android.media.MediaExtractor.setDataSource(Native Method)
                at android.media.MediaExtractor.setDataSource(MediaExtractor.java:140)
                at android.media.MediaExtractor.setDataSource(MediaExtractor.java:115)
                at com.google.android.exoplayer.source.FrameworkSampleExtractor.prepare(FrameworkSampleExtractor.java:104)
                at com.google.android.exoplayer.source.DefaultSampleSource.prepare(DefaultSampleSource.java:63)
                at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:218)
                at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:115)
                at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
                at android.os.Handler.dispatchMessage(Handler.java:98)
                at android.os.Looper.loop(Looper.java:136)
                at android.os.HandlerThread.run(HandlerThread.java:61)
                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
    03-06 11:36:03.827  16830-16830/com.example.sdkapptest E/MyExoPlayer﹕ Playback failed
        com.google.android.exoplayer.ExoPlaybackException: java.io.IOException: Failed to instantiate extractor.
                at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:223)
                at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:115)
                at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
                at android.os.Handler.dispatchMessage(Handler.java:98)
                at android.os.Looper.loop(Looper.java:136)
                at android.os.HandlerThread.run(HandlerThread.java:61)
                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
         Caused by: java.io.IOException: Failed to instantiate extractor.
                at android.media.MediaExtractor.setDataSource(Native Method)
                at android.media.MediaExtractor.setDataSource(MediaExtractor.java:140)
                at android.media.MediaExtractor.setDataSource(MediaExtractor.java:115)
                at com.google.android.exoplayer.source.FrameworkSampleExtractor.prepare(FrameworkSampleExtractor.java:104)
                at com.google.android.exoplayer.source.DefaultSampleSource.prepare(DefaultSampleSource.java:63)
                at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:218)
                at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:115)
                at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
                at android.os.Handler.dispatchMessage(Handler.java:98)
                at android.os.Looper.loop(Looper.java:136)
                at android.os.HandlerThread.run(HandlerThread.java:61)
                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
    03-06 11:36:03.847  16830-16830/com.example.apptest E/EventLogger﹕ playerFailed [10.08]
        com.google.android.exoplayer.ExoPlaybackException: java.io.IOException: Failed to instantiate extractor.
                at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:223)
                at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:115)
                at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
                at android.os.Handler.dispatchMessage(Handler.java:98)
                at android.os.Looper.loop(Looper.java:136)
                at android.os.HandlerThread.run(HandlerThread.java:61)
                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
         Caused by: java.io.IOException: Failed to instantiate extractor.
                at android.media.MediaExtractor.setDataSource(Native Method)
                at android.media.MediaExtractor.setDataSource(MediaExtractor.java:140)
                at android.media.MediaExtractor.setDataSource(MediaExtractor.java:115)
                at com.google.android.exoplayer.source.FrameworkSampleExtractor.prepare(FrameworkSampleExtractor.java:104)
                at com.google.android.exoplayer.source.DefaultSampleSource.prepare(DefaultSampleSource.java:63)
                at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:218)
                at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:115)
                at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
                at android.os.Handler.dispatchMessage(Handler.java:98)
                at android.os.Looper.loop(Looper.java:136)
                at android.os.HandlerThread.run(HandlerThread.java:61)
                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
    03-06 11:36:03.857  16830-16830/com.example.sdkapptest D/EventLogger﹕ state [10.09, false, I]

Device : Nexus 5 android 4.4.4

**Comment by ojw28** [comment]
What type of media are you playing? The failure is in MediaExtractor. On the dev branch we now support quite a few media types directly, so that we don't need to rely on MediaExtractor at all. Specifically, we currently support MP4, MP3 and AAC (WebM is coming soon).

**Comment by ojw28** [comment]
We now support MP4, MP3, AAC, TS, WebM directly, without MediaExtractor. Closing this.
