### ISSUE TITLE
Top bit not zero when playing MP4

### ISSUE THREAD

**Issue by NitroXenon** [google/ExoPlayer#3384]
### Issue description
ExoPlayer is unable to stream this specific mp4 file. An IllegalStateException is being thrown immediately after playback has started. However, this video can be streamed by VLC Player, MX Player, and Chrome flawlessly. So, is there any way to play the video on ExoPlayer?

```
com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: Top bit not zero: -72
                                                                            at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:337)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                            at java.lang.Thread.run(Thread.java:761)
                                                                         Caused by: java.lang.IllegalStateException: Top bit not zero: -72
                                                                            at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:380)
                                                                            at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:242)
                                                                            at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:355)
                                                                            at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:290)
                                                                            at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:281)
                                                                            at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:147)
                                                                            at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:704)
                                                                            at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                            at java.lang.Thread.run(Thread.java:761) 
```

### Reproduction steps
Just attempt to play the file using a regular ExtractorMediaSource.

### Link to test content
http://7xi8k7.com1.z0.glb.clouddn.com/125559181215fba916b92610.mp4

### Version of ExoPlayer being used
r2.5.3

### Device(s) and version(s) of Android being used
Android Emulator - Nougat
Samsung Galaxy S7 - Nougat

**Comment by NitroXenon** [comment]
@andrewlewis @ojw28 Any workaround for this issue? It has been affecting thousands of users of my app every day. 😢

**Comment by ojw28** [comment]
If the media were encoded properly this wouldn't happen. Is this content you're producing/distributing yourself?

**Comment by NitroXenon** [comment]
No. All contents are found on the Internet and users can stream them in my app. The test content is just one of an example content that produces an exception in my app.

**Comment by ojw28** [comment]
I don't really understand the comment that it's affecting thousands of your users. Is it really? Are thousands of users all trying to play this particular video, or are many videos affected (which seems unlikely given we've not been provided with any other piece of media in the past two years with this problem ;))? Please clarify.

**Comment by ojw28** [comment]
@NitroXenon Please clarify.

**Comment by ojw28** [comment]
I think we'll relax parsing to allow playback of this stream. It is broken though (it contains a negative sample delta, where-as the BMFF spec requires sample deltas to be unsigned).

**Comment by NitroXenon** [comment]
@ojw28 Sorry for the late response. I guess there are some videos affected. Unfortunately, I don't track what my users have watched in my app and I don't provide the media content, so I'm unable to give you more affected samples. Currently, there are around 1k affected users every day.

**Comment by NitroXenon** [comment]
All of the video players and browsers on my laptop can handle this stream actually. It would be great if ExoPlayer can handle it too.
