### ISSUE TITLE
LoopingMediaSource does not loop after a seek

### ISSUE THREAD

**Issue by b0g8** [google/ExoPlayer#3391]
### Issue description
I have an mp3 file (tested with several) played in a loop with LoopingMediaSource. It plays fine,in loop, if no interaction occurs, but if a seek is performed, it will stop at the end of current playback, and shortly after appears an EOFException:

```
10-24 11:32:31.037 22992-25383 E/ExoPlayerImplInternal: Source error.
                                                        com.google.android.exoplayer2.upstream.ContentDataSource$ContentDataSourceException: java.io.EOFException
                                                            at com.google.android.exoplayer2.upstream.ContentDataSource.read(ContentDataSource.java:137)
                                                            at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:142)
                                                            at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:257)
                                                            at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:132)
                                                            at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:113)
                                                            at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.readSample(Mp3Extractor.java:201)
                                                            at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.read(Mp3Extractor.java:195)
                                                            at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:704)
                                                            at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                            at java.lang.Thread.run(Thread.java:762)
                                                         Caused by: java.io.EOFException
                                                            at com.google.android.exoplayer2.upstream.ContentDataSource.read(ContentDataSource.java:137) 
                                                            at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:142) 
                                                            at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:257) 
                                                            at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:132) 
                                                            at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:113) 
                                                            at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.readSample(Mp3Extractor.java:201) 
                                                            at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.read(Mp3Extractor.java:195) 
                                                            at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:704) 
                                                            at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315) 
                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                            at java.lang.Thread.run(Thread.java:762) 
```

### Reproduction steps
Use an mp3 file as source:
```
musicSource = new LoopingMediaSource(new ExtractorMediaSource(musicFile, buildDataSourceFactory(false), new DefaultExtractorsFactory(),
                null, null));
player.prepare(musicSource, true, true);
```

### Link to test content
Tested with several mp3 files.

### Version of ExoPlayer being used
2.5.1

### Device(s) and version(s) of Android being used
S7, android 7

**Comment by ojw28** [comment]
This was fixed in 2.5.2. See https://github.com/google/ExoPlayer/issues/3216.
