### ISSUE TITLE
Video failed to load sometimes in RecyclerView

### ISSUE THREAD

**Issue by ominfowave** [google/ExoPlayer#3411]
### Issue description
Video which are around 1 minute length sometimes fails to load in RecyclerView, this occurs randomly on first load or after scrolling back to the video, sometimes this problem dose not appear.  

### Reproduction steps
Host videos on server, create RecylerView with video loading from server of more then 20 items, load recyclerview or scroll the list. 

### Link to test content
Sent to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
compile 'com.google.android.exoplayer:exoplayer-core:r2.+'
compile 'com.google.android.exoplayer:exoplayer-ui:r2.+'

### Device(s) and version(s) of Android being used
Redmi Note 3, Android 6.0.1
Lenovo K5 Note, Android 6.0

### A full bug report captured from the device
```
E/ExoPlayerImplInternal: Renderer error.
com.google.android.exoplayer2.ExoPlaybackException
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:416)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:403)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:837)
    at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:435)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:534)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:578)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:154)
    at android.os.HandlerThread.run(HandlerThread.java:61)
 Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.mpeg4, Format(1, null, video/mp4v-es, -1, null, [360, 640, -1.0], [-1, -1])
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:403) 
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:837) 
    at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:435) 
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:534) 
    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:578) 
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350) 
    at android.os.Handler.dispatchMessage(Handler.java:98) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.os.HandlerThread.run(HandlerThread.java:61) 
 Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.mpeg4, error 0xfffffff4
    at android.media.MediaCodec.native_setup(Native Method)
    at android.media.MediaCodec.<init>(MediaCodec.java:1670)
    at android.media.MediaCodec.createByCodecName(MediaCodec.java:1651)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:389)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:837) 
    at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:435) 
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:534) 
    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:578) 
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350) 
    at android.os.Handler.dispatchMessage(Handler.java:98) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by ojw28** [comment]
* Please attach a proper bug report, as described in the issue template.
* How many players do you have instantiated at once, and are you certain you're releasing them correctly?
* As an aside, it's considered bad practice to use "+" in your gradle dependencies. See [here](http://blog.danlew.net/2015/09/09/dont-use-dynamic-versions-for-your-dependencies/).
