### ISSUE TITLE
Demo application Internal runtime error  for HLS stream (Lenovo A369i - Android 4.2.2)

### ISSUE THREAD

**Issue by j3dd4h** [google/ExoPlayer#347]
I have tried the demo application (hls) is working on Samsung Galaxy but  not working on lenovo A369i,  only sound is working when video set to off.

=============================================
03-10 22:56:41.798  24878-25022/com.google.android.exoplayer.demo W/SurfaceTextureClient﹕ [STC::setBufferCount] set buffer count to 21
03-10 22:56:41.867  24878-25027/com.google.android.exoplayer.demo E/ACodec﹕ cannot find aac bit rate
03-10 22:56:41.872  24878-25022/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.MTK.VIDEO.DECODER.AVC] ERROR(0x80001005)
03-10 22:56:41.872  24878-25022/com.google.android.exoplayer.demo W/ACodec
OMXCodec::onEvent--OMX Bad Parameter!!
03-10 22:56:41.872  24878-25022/com.google.android.exoplayer.demo E/MediaCodec﹕ Codec reported an error. (omx error 0x80001005, internalError -1103)
03-10 22:56:41.923  24878-24955/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal runtime error.
    java.lang.IllegalStateException
            at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:733)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:448)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:103)
            at android.os.Looper.loop(Looper.java:194)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
03-10 22:56:41.935  24878-24878/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [150.22]
    com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:236)
            at android.os.Handler.dispatchMessage(Handler.java:103)
            at android.os.Looper.loop(Looper.java:194)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.lang.IllegalStateException
            at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:733)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:448)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:103)
            at android.os.Looper.loop(Looper.java:194)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

==================================

**Comment by pochadri** [comment]
+1

**Comment by gupta-sachin** [comment]
+1

**Comment by ZuZuK** [comment]
have same issue with HLS stream videos and general HLS videos on devices with MT6572 processor like Lenovo A369i or maybe all MT*** processors

have full log with additional MtkOMX library info: http://pastebin.com/raw.php?i=qv24QTNB

**Comment by wajidp** [comment]
any update on this?

**Comment by ojw28** [comment]
Please could someone attach a full bug report (captured with "adb bugreport") to this issue, captured shortly after encountering the issue using ExoPlayer's demo app v1.5.10 or later? Output from "adb logcat" is not sufficient. Thanks!

**Comment by ojw28** [comment]
Closing due to lack of required information.
