### ISSUE TITLE
Getting a 403 response code error from exoplayer

### ISSUE THREAD

**Issue by devnullpointer** [google/ExoPlayer#3472]
### Issue description
When playing an http mp4 stream in my activity I get a 403 response code from exoplayer. When I plug the same url in the demo app it plays immediately. I have checked my code against the demo's player activity and I can't see any difference or missing code that would result in me getting the 403 and the demo app working. Can someone with better trained eyes check it out for me and point me in the right direction?

### Reproduction steps
Pass url to custom exoplayer player activity. results in 403 response code. Demo app plays stream fine.

### Link to test content
email sent to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
2.5.4

### Device(s) and version(s) of Android being used
Pixel C 7.1.1

### A full bug report captured from the device
```
E/EventLogger: internalError [3.76, loadError]
                                                                          com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
                                                                              at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                              at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:137)
                                                                              at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692)
                                                                              at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:761)

E/EventLogger: playerFailed [3.78]
                                                                          com.google.android.exoplayer2.ExoPlaybackException
                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:399)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                           Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
                                                                              at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                              at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:137)
                                                                              at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692)
                                                                              at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:761)```

**Comment by devnullpointer** [comment]
Could it be because I did not include, compile, and depend on extensions like Flac, FFmpeg, etc.. that I'm getting these errors?

**Comment by AquilesCanta** [comment]
Are you setting a cookie manager?

**Comment by AquilesCanta** [comment]
> Could it be because I did not include, compile, and depend on extensions like Flac, FFmpeg, etc.. that I'm getting these errors?

No, not really possible.

**Comment by devnullpointer** [comment]
@AquilesCanta Yes I am.
```Java
    private static final CookieManager DEFAULT_COOKIE_MANAGER;
    static
    {
        DEFAULT_COOKIE_MANAGER = new CookieManager();
        DEFAULT_COOKIE_MANAGER.setCookiePolicy(CookiePolicy.ACCEPT_ORIGINAL_SERVER);
    }
...

    if (CookieHandler.getDefault() != DEFAULT_COOKIE_MANAGER)
    {
        CookieHandler.setDefault(DEFAULT_COOKIE_MANAGER);
    }
```

**Comment by devnullpointer** [comment]
@AquilesCanta you are correct, I just tried the exoplayer without extensions and the stream played as well. Still don't know why I'm getting a 403...

**Comment by devnullpointer** [comment]
Here's my Player Activity..
```Java
public class ExoPlayerActivity extends AppCompatActivity implements OnClickListener, EventListener,
        PlaybackControlView.VisibilityListener
{
    private static final String TAG = ExoPlayerActivity.class.getName();

    private static final DefaultBandwidthMeter BANDWIDTH_METER = new DefaultBandwidthMeter();
    private static final CookieManager DEFAULT_COOKIE_MANAGER;
    static
    {
        DEFAULT_COOKIE_MANAGER = new CookieManager();
        DEFAULT_COOKIE_MANAGER.setCookiePolicy(CookiePolicy.ACCEPT_ALL);
    }

    private SimpleExoPlayerView playerView;
    private SimpleExoPlayer player;
    private DataSource.Factory mediaDataSourceFactory;
    private DefaultTrackSelector trackSelector;
    private TrackSelectionHelper trackSelectionHelper;
    private Handler mainHandler;
    private EventLogger eventLogger;

    private int currentWindow;
    private boolean playWhenReady = true;
    private long playbackPosition;
    private int id;

    private Uri playbackUri;

    private ProgressDialog buffering;
    private boolean isSeekComplete;

    private TrackGroupArray lastSeenTrackGroupArray;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);

        mediaDataSourceFactory = buildDataSourceFactory(true);
        mainHandler = new Handler();
        if (CookieHandler.getDefault() != DEFAULT_COOKIE_MANAGER)
        {
            CookieHandler.setDefault(DEFAULT_COOKIE_MANAGER);
        }

        setContentView(R.layout.activity_exoplayer);

        playbackUri = getIntent().getData();
        playbackPosition = getIntent().getLongExtra(PlaybackActivity.EXTRA_POSITION, 0);
        id = getIntent().getIntExtra(PlaybackActivity.EXTRA_VIDEOID, 0);

        playerView = (SimpleExoPlayerView) findViewById(R.id.video_view);
        playerView.setControllerVisibilityListener(this);
        playerView.requestFocus();

        buffering = new ProgressDialog(this);
        buffering.setIndeterminate(true);
        buffering.setMessage("Buffering video ...");
        buffering.show();
    }

    @Override
    public void onStart()
    {
        super.onStart();
        initializePlayer();
    }

    @Override
    public void onResume()
    {
        super.onResume();
        hideSystemUi();
        if (player == null)
        {
            initializePlayer();
        }
    }

    @Override
    protected void onStop()
    {
        super.onStop();

        if (buffering != null)
        {
            buffering.dismiss();
        }
        releasePlayer();
    }

    @Override
    protected void onPause()
    {
        super.onPause();

        if (buffering != null)
        {
            buffering.dismiss();
        }
        releasePlayer();
    }

    private void hideSystemUi()
    {
        playerView.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LOW_PROFILE
                | View.SYSTEM_UI_FLAG_FULLSCREEN
                | View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION);
    }

    @Override
    public boolean dispatchKeyEvent(final KeyEvent event)
    {
        // If the event was not handled then see if the player view can handle it.
        return super.dispatchKeyEvent(event) || playerView.dispatchKeyEvent(event);
    }

    // OnClickListener methods

    @Override
    public void onClick(final View view)
    {
//        if (view == retryButton) {
//            initializePlayer();
//        } else if (view.getParent() == debugRootView) {
//            MappingTrackSelector.MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
//            if (mappedTrackInfo != null) {
//                trackSelectionHelper.showSelectionDialog(this, ((Button) view).getText(),
//                        trackSelector.getCurrentMappedTrackInfo(), (int) view.getTag());
//            }
//        }
    }

    // PlaybackControlView.VisibilityListener implementation
    @Override
    public void onVisibilityChange(final int visibility) {
//        debugRootView.setVisibility(visibility);
    }

    private void initializePlayer()
    {
        final TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(BANDWIDTH_METER);
        trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
        trackSelectionHelper = new TrackSelectionHelper(trackSelector, videoTrackSelectionFactory);

        lastSeenTrackGroupArray = null;
        eventLogger = new EventLogger(trackSelector);

        @DefaultRenderersFactory.ExtensionRendererMode int extensionRendererMode = DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER;
        final DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(this,null, extensionRendererMode);

        player = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector);
        player.addListener(this);
        player.addListener(eventLogger);
        player.addMetadataOutput(eventLogger);
        player.setAudioDebugListener(eventLogger);
        player.setVideoDebugListener(eventLogger);

        playerView.setPlayer(player);

        player.setPlayWhenReady(playWhenReady);

        currentWindow = player.getCurrentWindowIndex();

        final MediaSource mediaSource = buildMediaSource(playbackUri, playbackUri.getPath().substring(playbackUri.getPath().lastIndexOf(".") + 1));
        player.prepare(mediaSource);
    }

    private MediaSource buildMediaSource(final Uri uri, final String overrideExtension)
    {
        int type = TextUtils.isEmpty(overrideExtension) ? Util.inferContentType(uri)
                : Util.inferContentType("." + overrideExtension);
        switch (type)
        {
            case C.TYPE_SS:
                return new SsMediaSource(uri, buildDataSourceFactory(false),
                        new DefaultSsChunkSource.Factory(mediaDataSourceFactory), mainHandler, eventLogger);
            case C.TYPE_DASH:
                return new DashMediaSource(uri, buildDataSourceFactory(false),
                        new DefaultDashChunkSource.Factory(mediaDataSourceFactory), mainHandler, eventLogger);
            case C.TYPE_HLS:
                return new HlsMediaSource(uri, mediaDataSourceFactory, mainHandler, eventLogger);
            case C.TYPE_OTHER:
                return new ExtractorMediaSource(uri, mediaDataSourceFactory, new DefaultExtractorsFactory(),
                        mainHandler, eventLogger);
            default:
            {
                throw new IllegalStateException("Unsupported type: " + type);
            }
        }
    }

    private DataSource.Factory buildDataSourceFactory(final boolean useBandwithMeter)
    {
        return new DefaultDataSourceFactory(this, useBandwithMeter ? BANDWIDTH_METER : null,
                new DefaultHttpDataSourceFactory(Config.USER_AGENT, useBandwithMeter ? BANDWIDTH_METER : null));
    }

    private void releasePlayer()
    {
        if (player != null)
        {
            playbackPosition = player.getCurrentPosition();
            currentWindow = player.getCurrentWindowIndex();
            playWhenReady = player.getPlayWhenReady();
            player.release();
            player = null;
            trackSelector = null;
            trackSelectionHelper = null;
            eventLogger = null;
        }
    }

    private void addBookmark()
    {
        if (player.getCurrentPosition() > 30000)
        {
            final BookmarksDbHelper dbHelper = new BookmarksDbHelper(this);
            dbHelper.addOrUpdateBookmark(id, player.getCurrentPosition());
            dbHelper.close();
        }
    }

    @Override
    public void onBackPressed()
    {
        addBookmark();

        player.stop();
        releasePlayer();

        final Intent data = new Intent();
        setResult(RESULT_OK,data);
        finish();
    }

    @Override
    public void onTimelineChanged(final Timeline timeline, final Object manifest)
    {
        Log.d(TAG, "ExoPlayer: Timeline Changed." + timeline.toString());
    }

    @Override
    public void onTracksChanged(final TrackGroupArray trackGroups, final TrackSelectionArray trackSelections)
    {
        Log.d(TAG, "ExoPlayer: Tracks changed.");
        if (trackGroups != lastSeenTrackGroupArray)
        {
            final MappingTrackSelector.MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
            if (mappedTrackInfo != null)
            {
                if (mappedTrackInfo.getTrackTypeRendererSupport(C.TRACK_TYPE_VIDEO)
                        == MappingTrackSelector.MappedTrackInfo.RENDERER_SUPPORT_UNSUPPORTED_TRACKS)
                {
                    AppUtils.showToast(getApplication(), R.string.error_unsupported_video);
                }
                if (mappedTrackInfo.getTrackTypeRendererSupport(C.TRACK_TYPE_AUDIO)
                        == MappingTrackSelector.MappedTrackInfo.RENDERER_SUPPORT_UNSUPPORTED_TRACKS)
                {
                    AppUtils.showToast(getApplication(), R.string.error_unsupported_audio);
                }
            }
            lastSeenTrackGroupArray = trackGroups;
        }
    }

    @Override
    public void onLoadingChanged(final boolean isLoading)
    {
        Log.d(TAG, "ExoPlayer: Loading changed.");
    }

    @Override
    public void onPlayerStateChanged(final boolean playWhenReady, final int playbackState)
    {
        Log.d(TAG, "ExoPlayer: Player State Changed.");
        if (playbackState == Player.STATE_READY)
        {
            buffering.dismiss();
            if (playbackPosition > 0 && !isSeekComplete)
            {
                player.seekTo(currentWindow, playbackPosition);
                isSeekComplete = true;
            }
        }
    }

    @Override
    public void onRepeatModeChanged(final int repeatMode)
    {
        Log.d(TAG, "ExoPlayer: Repeat Mode Changed");
    }

    @Override
    public void onPlayerError(final ExoPlaybackException error)
    {
        Log.e(TAG, "ExoPlayer: Player Error.", error);

        String errorString = null;
        if (error.type == ExoPlaybackException.TYPE_RENDERER)
        {
            final Exception cause = error.getRendererException();
            if (cause instanceof MediaCodecRenderer.DecoderInitializationException)
            {
                // Special case for decoder initialization failures.
                final MediaCodecRenderer.DecoderInitializationException decoderInitializationException =
                        (MediaCodecRenderer.DecoderInitializationException) cause;
                if (decoderInitializationException.decoderName == null)
                {
                    if (decoderInitializationException.getCause() instanceof MediaCodecUtil.DecoderQueryException)
                    {
                        errorString = getString(R.string.error_querying_decoders);
                    }
                    else if (decoderInitializationException.secureDecoderRequired)
                    {
                        errorString = getString(R.string.error_no_secure_decoder,
                                decoderInitializationException.mimeType);
                    }
                    else
                    {
                        errorString = getString(R.string.error_no_decoder,
                                decoderInitializationException.mimeType);
                    }
                }
                else
                {
                    errorString = getString(R.string.error_instantiating_decoder,
                            decoderInitializationException.decoderName);
                }
            }
        }
        else if (error.getSourceException().getMessage().contains("403"))
        {
            errorString = String.format(getString(R.string.exo_403), "Error Code: " + error.getSourceException().getMessage());
        }
        else
        {
            errorString = String.format(getString(R.string.exo_error_playback), "Error Code: " + error.getSourceException().getMessage());
        }

        final AlertDialog dialog = new AlertDialog.Builder(ExoPlayerActivity.this)
                .setTitle(R.string.exo_error_title)
                .setMessage(errorString)
                .setPositiveButton(R.string.ok, new DialogInterface.OnClickListener()
                {
                    @Override
                    public void onClick(final DialogInterface dialog, final int id)
                    {
                        addBookmark();

                        player.stop();
                        releasePlayer();

                        final Intent data = new Intent();
                        setResult(RESULT_CANCELED,data);

                        finish();
                    }
                })
                .create();
        dialog.show();
    }

    @Override
    public void onPositionDiscontinuity()
    {
        Log.d(TAG, "ExoPlayer: Position Discontinuity.");
    }

    @Override
    public void onPlaybackParametersChanged(final PlaybackParameters playbackParameters)
    {
        Log.d(TAG, "ExoPlayer: Playback Parameters Changed.");
    }
}
```

**Comment by AquilesCanta** [comment]
The easiest way to diagnose this is to compare the http request that the DemoApp is making and the one your app is making. Android Studio's network analyzer should make this fairly easy. There is either a header difference that is causing this (maybe the UserAgent?). Once you spot the difference, it should be easy to fix.

**Comment by devnullpointer** [comment]
That would be great if i could get the demo app to run in debug mode, the option is not available, and when i try to create a configuration for it, it won't let me. I can only build the apk and deploy. If i start the profiler and select the running exoplayer process it tells me advanced profiling is not available for it.

**Comment by devnullpointer** [comment]
There is a redirect that is happening and a cookie is supposed to be set. When i test the url using okhttp and a request builder the request gets forwarded and the cookie is set and the stream is good, unfortunately in exo that's not happening.

also if I look at the response for the call i make using okhttp I get status content-type and size in the response headers, similarly in the response headers for the call being made by exo those values are not present.

I've also changed the cookie policy to accept_all and still get a 403.

**Comment by AquilesCanta** [comment]
You could also the [Sthetho extension](https://medium.com/google-exoplayer/enabling-stetho-on-exoplayer-2-demo-application-126807a37cb3) for sniffing the HTTP requests. I think the way to go is to compare the requests (the one that works and the one that doesn't). `curl` might help in creating a working request. Unfortunately, this is not something I can do for you.

**Comment by devnullpointer** [comment]
The requests are the same based on the profiler.

**Comment by AquilesCanta** [comment]
From the code you provided, the User Agent contains the substring "My App Name", whereas the demo app doesn't. I don't think they can be the same.

**Comment by devnullpointer** [comment]
When I call the url via okhttp to test the stream I get the following headers back:
![image](https://user-images.githubusercontent.com/3925946/32953837-6ac930da-cb7f-11e7-8131-03c0da61da7d.png)


when my exoplayer calls the url i dont get any headers back.

**Comment by devnullpointer** [comment]
It's like my exoplayer activity wont follow redirects, but the demo app will.

**Comment by andrewlewis** [comment]
- What are the redirects? Which one isn't followed?
- An image containing response headers is not that useful. It might be useful to see the requests as text.

**Comment by devnullpointer** [comment]
Here's the response when I play the url through the demo app:
![image](https://user-images.githubusercontent.com/3925946/32956352-8506a426-cb86-11e7-9a92-b57ebf20793a.png)

Here's the response when I test the stream using okhttp before calling the player activity:
![image](https://user-images.githubusercontent.com/3925946/32956656-5f3bcffe-cb87-11e7-8849-3ffa114e4407.png)

and when i pass the uri to the playback activity:
![image](https://user-images.githubusercontent.com/3925946/32956690-7c36faac-cb87-11e7-8c63-02e14e2d8ac4.png)


I also noticed in the profiler that the demo app has only 1 call to the uri, where as in my app profiler i see 4 calls to the uri which might cause the server to return a 403

**Comment by devnullpointer** [comment]
Sorry for my poor writing skills..
![image](https://user-images.githubusercontent.com/3925946/32956835-fcb0e6c0-cb87-11e7-871f-dfa6cd8df035.png)

**Comment by AquilesCanta** [comment]
Have you tried removing the cookie manager?

**Comment by devnullpointer** [comment]
Yeah, no difference.

**Comment by andrewlewis** [comment]
Does the request made by the player (which gets a 403 response) have a cookie set? It would really be helpful to see that request + response in text format (via email if preferred).

**Comment by devnullpointer** [comment]
From the profiler? or logger?

**Comment by devnullpointer** [comment]
> From the code you provided, the User Agent contains the substring "My App Name", whereas the demo app doesn't. I don't think they can be the same.

I changed that part of the code to return a standard User Agent:
```
Mozilla/5.0 (Linux; U; Android 4.0.3; ko-kr; LG-L160L Build/IML74K) AppleWebkit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
```

**Comment by devnullpointer** [comment]
> Does the request made by the player (which gets a 403 response) have a cookie set? It would really be helpful to see that request + response in text format (via email if preferred).

The demo app doesn't set any cookies either. Here's the demo request/response headers from the profiler.
![image](https://user-images.githubusercontent.com/3925946/32959145-aa1cf7d0-cb8e-11e7-8aeb-8782d9f56fbe.png)

**Comment by devnullpointer** [comment]
@andrewlewis I emailed you the debug data of a breakpoint in the DefaultHttpDataSource whre it opens the url connection called from my app and from the demo app.

**Comment by AquilesCanta** [comment]
The content is now returning a 404. Can you fix it? Or send a replacement link to reproduce the issue?

**Comment by devnullpointer** [comment]
who do I thank for that?

**Comment by devnullpointer** [comment]
I think its back.

**Comment by devnullpointer** [comment]
it should be working

**Comment by devnullpointer** [comment]
LinkL
https://streamango.com/v/d/oooapconaccrnqbe~1511104976~70.81.0.0~ltlYQSWe/718

**Comment by devnullpointer** [comment]
link sent

**Comment by devnullpointer** [comment]
I just copied the player activity and all underlying required layouts/strings to my app, called that instead of my player activity and I still get the response code 403. When I run the demo app I don't get the 403.

**Comment by AquilesCanta** [comment]
We are going to look into this again next week. If possible keep it online, se we can access it.

**Comment by devnullpointer** [comment]
Can you guys confirm that there is nothing wrong with my player activity class?

**Comment by AquilesCanta** [comment]
No, we can't do that unfortunately. That would require us to carefully read the whole class, and even if we did, nothing guarantees that another piece of your app is not modifying the global context. We will look into this, but we cannot make any promises on timelines. You should definitely try to diagnose the issue as well. Please reach out if you manage to do so.

**Comment by ojw28** [comment]
If the content works successfully in the demo app, on the same device, then there must be something different in your app (not necessarily in your player activity). Are you sure you don't depend on some other library that's messing around with the default cookie manager, or something like that (libraries probably shouldn't do this, but that doesn't necessarily mean they wont!).

In any case, this doesn't seem like something we should spend much more time on unless you can provide reproduction steps in the demo app. It's really up to the app developer to debug such issues. You may have to try and build a minimal app containing only a stripped down version of your player activity, verify that that works, then add in other dependencies and pieces of your app until it breaks.

**Comment by devnullpointer** [comment]
Seems like it was the cookie handler/manager after all. I made sure I was using the same CookieHandler in both my okhttp service class and the exo player activity and its working perfectly now.

Thanks for the time and help. Greatly appreciated!
