### ISSUE TITLE
exoplayer returning null message DROID RAZR HD (vanquish) android 4.1

### ISSUE THREAD

**Issue by khurram25** [google/ExoPlayer#348]
java.lang.NullPointerException: println needs a message
at android.util.Log.println_native_inner(Native Method)
at android.util.Log.println_native(Log.java:284)
at android.util.Log.d(Log.java:316)
at com.google.android.libraries.mediaframework.layeredvideo.VideoSurfaceLayer$1.onError(VideoSurfaceLayer.java:55)
at com.google.android.libraries.mediaframework.exoplayerextensions.ExoplayerWrapper.onRenderersError(ExoplayerWrapper.java:624)
at com.google.android.libraries.mediaframework.exoplayerextensions.ExoplayerWrapper$InternalRendererBuilderCallback.onRenderersError(ExoplayerWrapper.java:976)
at com.google.android.libraries.mediaframework.exoplayerextensions.HlsRendererBuilder.onManifestError(HlsRendererBuilder.java:76)
at com.google.android.exoplayer.util.ManifestFetcher$SingleFetchHelper.onLoadError(ManifestFetcher.java:327)
at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:234)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5021)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
at dalvik.system.NativeStart.main(Native Method)

**Comment by ojw28** [comment]
- Playback failed because the HLS manifest wasn't loaded successfully. There's no evidence to suggest this isn't working correctly (e.g. due to networking issues).
- The issue you then see is a problem with VideoSurfaceLayer in [GMF](https://github.com/googleads/google-media-framework-android/issues), not ExoPlayer. It shouldn't be printing null to Log.d. I've filed this for you under the correct project: https://github.com/googleads/google-media-framework-android/issues/49
