### ISSUE TITLE
UnrecognizedInputFormatException when switching between 3g/wifi

### ISSUE THREAD

**Issue by alonaviram** [google/ExoPlayer#3483]
I'm using ExoPlayer on a list of videos.
This is my code (relevant to the issue):
```
public class SingleVideoPlayer {
    private SimpleExoPlayer exoPlayer;
    private Context context;
    private ImaAdsLoader imaAdsLoader;

    public SingleVideoPlayer(Context context, String adTagUrl) {
        this.context = context;

        imaAdsLoader = new ImaAdsLoader(context, Uri.parse(adTagUrl));
        DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        DefaultTrackSelector trackSelector = new DefaultTrackSelector(bandwidthMeter);
        exoPlayer = ExoPlayerFactory.newSimpleInstance(this.context, trackSelector);
    }


    public void playVideoItem(final VideoListItem videoListItem, final VideoViewHolder viewHolder, int newActiveViewPosition) {
        setNewSource(videoListItem.getVideoUrl(), viewHolder.getSimpleExoPlayerView());
        viewHolder.getSimpleExoPlayerView().setPlayer(exoPlayer);
    }

    public void setNewSource(String videoUrl, FrameLayout adUiContainer) {
        Uri uri = Uri.parse(videoUrl);
        String userAgent = Util.getUserAgent(context, "appName");
        MyCacheDataSourceFactory cacheDataSourceFactory = new MyCacheDataSourceFactory(context);
        MediaSource mediaSource = new HlsMediaSource(uri, cacheDataSourceFactory, null, null);
        ImaAdsMediaSource imaAdsMediaSource =
                new ImaAdsMediaSource(mediaSource, cacheDataSourceFactory, imaAdsLoader, adUiContainer);
        exoPlayer.prepare(imaAdsMediaSource);
        exoPlayer.setPlayWhenReady(true);
    }

    public void stopPlayback(VideoViewHolder viewHolder, int oldActivePosition) {
        exoPlayer.stop();
    }
}
```
when i switch connectivity between 3g and wifi while i scroll between videos i get this exception (with some logs i catched):
```
11-20 15:45:56.275 9978-11150/com.my.app.debug E/ExoPlayerImplInternal: Source error.
                                                                                com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
                                                                                    at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:119)
                                                                                    at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:43)
                                                                                    at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:115)
                                                                                    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                    at java.lang.Thread.run(Thread.java:764)
11-20 15:45:56.287 9978-9978/com.my.app.debug E/TAG: onLoadError() called with: dataSpec = [DataSpec[http://my-url.m3u8, null, 0, 0, -1, null, 1]], dataType = [4], trackType = [-1], trackFormat = [null], trackSelectionReason = [0], trackSelectionData = [null], mediaStartTimeMs = [-9223372036854775807], mediaEndTimeMs = [-9223372036854775807], elapsedRealtimeMs = [334873988], loadDurationMs = [9], bytesLoaded = [401], error = [com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.], wasCanceled = [true]
11-20 15:45:56.287 9978-9978/com.my.app.debug E/TAG: onPlayerError() called with: error = [com.google.android.exoplayer2.ExoPlaybackException]
```
the connectivity should be changed exactly in the moment when the new video is loaded.
it's not specific to url, it may happen on every url i tried, anyway,  on demand i can send some url's it happened to me.

This is how i build my cache datasource factory: 
```
public class MyCacheDataSourceFactory implements DataSource.Factory {
    private static final long DEFAULT_MAX_FILE_SIZE = 5 * 1024 * 1024;
    /**
     * 250 MB of cache.
     */
    private static final long DEFAULT_MAX_CACHE_SIZE = 250 * 1024 * 1024;
    private final DataSource.Factory cacheDataSource;

    public MyCacheDataSourceFactory(Context context) {
        this(context, DEFAULT_MAX_CACHE_SIZE, DEFAULT_MAX_FILE_SIZE);
    }

    private MyCacheDataSourceFactory(Context context, long maxCacheSize, long maxFileSize) {
        String userAgent = Util.getUserAgent(context, "appName");
        DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        CacheEvictor evictor = new LeastRecentlyUsedCacheEvictor(maxCacheSize);
        SimpleCache simpleCache = new SimpleCache(new File(context.getCacheDir(), "media"), evictor);
        DefaultDataSourceFactory upstreamFactory = new DefaultDataSourceFactory
                (context, userAgent, bandwidthMeter);
        cacheDataSource = new CacheDataSourceFactory(simpleCache, upstreamFactory, 0, maxFileSize);
    }

    @Override
    public DataSource createDataSource() {
        return cacheDataSource.createDataSource();
    }
}
```
note: 
- the video plays perfectly before this error occurs
- the video will not play again on the app until re-installing (that's why i think it's related to caching somehow)
thanks alot!

**Comment by andrewlewis** [comment]
Could you clarify when the cache is being hit and when data is being loaded from the network to populate the cache? Is it possible that the server is responding with data that isn't an HLS playlist just after the connectivity change, and the invalid response is getting cached? Do you still see a source error if you remove the cache completely?

**Comment by andrewlewis** [comment]
Closing due to inactivity. Please try again on the latest release and file a new issue with the requested information if the issue is still reproducible there.
