### ISSUE TITLE
Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat in Samsung Galaxy 7 Pro

### ISSUE THREAD

**Issue by ashishvirani** [google/ExoPlayer#3492]
*** Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat in Samsung Galaxy 7 Pro ***

i got error when Record Video from samsung galaxy on7 pro and apply video speed sucsessfully but this video not play pn samsung galaxy on7 pro.
			it work normal on other android smartphone
			My Android Version: 6.0
			i use ads video mp4
			ver exoplay : r1.5.8

```
11-23 17:42:01.012 14189-16150/com.aspiration.slowmotionvideo E/ExoPlayerImplInternal: Internal track renderer error.
	   com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, 43028, 1080, 1920, 0, 1.0, -1, -1, null, 480000, false, -1, -1, -1, -1, -1)
		   at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:414)
		   at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400)
		   at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768)
		   at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)
		   at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524)
		   at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507)
		   at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
		   at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
		   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
		   at android.os.Handler.dispatchMessage(Handler.java:98)
		   at android.os.Looper.loop(Looper.java:148)
		   at android.os.HandlerThread.run(HandlerThread.java:61)
		   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
		Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, 43028, 1080, 1920, 0, 1.0, -1, -1, null, 480000, false, -1, -1, -1, -1, -1)
		   at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400) 
		   at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768) 
		   at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333) 
		   at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524) 
		   at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507) 
		   at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
		   at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434) 
		   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
		   at android.os.Handler.dispatchMessage(Handler.java:98) 
		   at android.os.Looper.loop(Looper.java:148) 
		   at android.os.HandlerThread.run(HandlerThread.java:61) 
		   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
		Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
		   at android.media.MediaCodec.native_configure(Native Method)
		   at android.media.MediaCodec.configure(MediaCodec.java:1778)
		   at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:328)
		   at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:389)
		   at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768) 
		   at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333) 
		   at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524) 
		   at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507) 
		   at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
		   at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434) 
		   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
		   at android.os.Handler.dispatchMessage(Handler.java:98) 
		   at android.os.Looper.loop(Looper.java:148) 
		   at android.os.HandlerThread.run(HandlerThread.java:61) 
		   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
11-23 17:42:01.102 14189-14189/com.aspiration.slowmotionvideo E/EventLogger: internalError [0.25, decoderInitializationError]
		 com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, 43028, 1080, 1920, 0, 1.0, -1, -1, null, 480000, false, -1, -1, -1, -1, -1)
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400)
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768)
			 at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524)
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507)
			 at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
			 at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
			 at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
			 at android.os.Handler.dispatchMessage(Handler.java:98)
			 at android.os.Looper.loop(Looper.java:148)
			 at android.os.HandlerThread.run(HandlerThread.java:61)
			 at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
		  Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
			 at android.media.MediaCodec.native_configure(Native Method)
			 at android.media.MediaCodec.configure(MediaCodec.java:1778)
			 at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:328)
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:389)
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768) 
			 at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333) 
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524) 
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507) 
			 at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
			 at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434) 
			 at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
			 at android.os.Handler.dispatchMessage(Handler.java:98) 
			 at android.os.Looper.loop(Looper.java:148) 
			 at android.os.HandlerThread.run(HandlerThread.java:61) 
			 at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
11-23 17:42:01.102 14189-14189/com.aspiration.slowmotionvideo E/EventLogger: playerFailed [0.25]
		 com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, 43028, 1080, 1920, 0, 1.0, -1, -1, null, 480000, false, -1, -1, -1, -1, -1)
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:414)
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400)
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768)
			 at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524)
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507)
			 at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
			 at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
			 at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
			 at android.os.Handler.dispatchMessage(Handler.java:98)
			 at android.os.Looper.loop(Looper.java:148)
			 at android.os.HandlerThread.run(HandlerThread.java:61)
			 at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
		  Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, 43028, 1080, 1920, 0, 1.0, -1, -1, null, 480000, false, -1, -1, -1, -1, -1)
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400) 
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768) 
			 at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333) 
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524) 
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507) 
			 at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
			 at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434) 
			 at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
			 at android.os.Handler.dispatchMessage(Handler.java:98) 
			 at android.os.Looper.loop(Looper.java:148) 
			 at android.os.HandlerThread.run(HandlerThread.java:61) 
			 at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
		  Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
			 at android.media.MediaCodec.native_configure(Native Method)
			 at android.media.MediaCodec.configure(MediaCodec.java:1778)
			 at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:328)
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:389)
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768) 
			 at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333) 
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524) 
			 at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507) 
			 at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
			 at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434) 
			 at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
			 at android.os.Handler.dispatchMessage(Handler.java:98) 
			 at android.os.Looper.loop(Looper.java:148) 
			 at android.os.HandlerThread.run(HandlerThread.java:61) 
			 at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

**Comment by ojw28** [comment]
Please provide a link to the problematic video, so we can give it a try. Please also try and reproduce with the ExoPlayer demo app. Thanks.

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
