### ISSUE TITLE
Exoplayer 2.6.0 crash

### ISSUE THREAD

**Issue by Tolriq** [google/ExoPlayer#3511]
### Issue description

After updating to 2.6.0 in production I've seen crash in Crashlytics.
Currently only 1 device but push is recent and ExoPlayer is not a widely used feature.
(Used only for Audio Playback)

### Reproduction steps

No details as from crash reporting tool.

### Link to test content
N/A

### Version of ExoPlayer being used
Specify the absolute version number. Avoid using terms such as "latest".
2.6.0 + flac extension

### Device(s) and version(s) of Android being used

For the moment only reported on Galaxy S7 / Android 7.0

### A full bug report captured from the device
No access to device :(
Crash log:

Proguard used, so inlining can change line numbers.

```
Fatal Exception: java.lang.AbstractMethodError: abstract method "int com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.decoderReinitializationState()"
       at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.supportsFormat(SimpleDecoderAudioRenderer.java:184)
       at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:2658)
       at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.selectTracks(ExoPlayerImplInternal.java:1644)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.handlePrepared(ExoPlayerImplInternal.java:14622)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by andrewlewis** [comment]
This looks very weird, as if proguard is doing the wrong thing. Is there anything special about how you're using proguard? Can you reproduce the error?

**Comment by Tolriq** [comment]
@andrewlewis I can't reproduce and I do use that part of the app frequently on multiple devices.

I use proguard with optimize, the configuration is normal and there was no problem at all with 2.5.4 that was in production before, the app is in prod since many years and proguard configuration have not changed since a long time.

Just got another report on Huawei P8 Lite Android 6.0

Not really sure what I can provide more as there's no specific ExoPlayer proguard except if the library does embed some configuration.

And it seems to still work for the vast majority of users.

**Comment by andrewlewis** [comment]
I'm not sure whether your analytics has this info, but can you see whether it fails on 100% of Huawei P8 Lite Android 6.0 and Samsung Galaxy S7 Android 7.0 builds, or whether it's working for some users and failing for others on those devices?

Please could you also double check you're using the right proguard map to deobfuscate the stack trace? Thanks.

**Comment by Tolriq** [comment]
@andrewlewis 
Had another crash this night on Huawey Y625-U43 Android 4.4.2

Can't really tell if it's crashing 100% on those devices as for the moment no users have contact me about the issue :( Can just tell it happened multiple times on those devices near the same time, so could imagine for those who have the issue it's reproductible.

Working well here on S6 Android 7 + Nexus 9 / 10

```
Fatal Exception: java.lang.AbstractMethodError: abstract method not implemented
       at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.supportsFormatInternal$5c1e9231(SimpleDecoderAudioRenderer.java)
       at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.supportsFormat(SimpleDecoderAudioRenderer.java:184)
       at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:2658)
       at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.selectTracks(ExoPlayerImplInternal.java:1644)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.handlePrepared(ExoPlayerImplInternal.java:14622)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

Proguard maps are auto handled by Crashlytics, but I did a manual check and get the same thing.

But it's actually effectively quite strange, as this new crash seems to correspond correctly to 2.6.0 code, the previous one does not.

Both logs are from the exact same APK and the one I'm testing on my devices. (I do ABI split but they are all armv7 one)

Edit: Only testing here with mp3 and flac, is there some other format that could take another path that I should test to try to reproduce ?

**Comment by alessandrojp** [comment]
I'm getting a similar error `java.lang.AbstractMethodError` on Android 6.0.1 using 2.6.0 version and I'm not using proguard.
Before that it was working without any problem.


```
java.lang.AbstractMethodError: abstract method "int com.google.android.exoplayer2.audio.AudioProcessor.getOutputSampleRateHz()"
                                                                                    at com.google.android.exoplayer2.audio.DefaultAudioSink.configure(DefaultAudioSink.java:356)
                                                                                    at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onOutputFormatChanged(MediaCodecAudioRenderer.java:292)
                                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.processOutputFormat(MediaCodecRenderer.java:1027)
                                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:969)
                                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:552)
                                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
                                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by andrewlewis** [comment]
@alessandrojp This should be caught at compile time. Is the device running the 'official' system image, or a custom ROM? Please provide the output of `adb shell getprop ro.build.fingerprint` (or even better a full bug report). Thanks.

**Comment by alessandrojp** [comment]
@andrewlewis thanks for reply

Yes, it is running the official system image.
`KDDI/SHV35_jp_kdi/SHV35:6.0.1/S6020/01.00.00:user/release-keys`

I will provide you a full bug report later.

**Comment by Tolriq** [comment]
@andrewlewis Seeing more and more crashes :(

The first one occurs on Android 5 6 7, the second one on Android 4.x

So far all LG / Samsung / Huawei

**Comment by ojw28** [comment]
This looks like a problem with the way you're including ExoPlayer in your project, or a proguard or VM issue. I don't think it's an issue with the library itself.

Note that the one previous report of `AbstractMethodError`  (https://github.com/google/ExoPlayer/issues/1706#issuecomment-317009023) was resolved by switching from a strange way of including ExoPlayer in a project, over to the way we recommend. If you're building ExoPlayer from source you should probably try this. If you're not, this isn't relevant.

**Comment by Tolriq** [comment]
Well
```
    implementation "com.google.android.exoplayer:exoplayer-core:${versions.exoPlayer}"
    implementation "com.google.android.exoplayer:extension-okhttp:${versions.exoPlayer}"
```
+ flac extension as aar following exactly the build process.

And no such errors with r2.5.4. (And nothing changed except the version number)

Don't really know what I can change at all.

**Comment by ojw28** [comment]
That looks correct. I still think this is correct though:

> This looks like a problem with the way you're including ExoPlayer in your project, or a proguard or VM issue. I don't think it's an issue with the library itself.

Is it possible you're somehow including two different versions of ExoPlayer in your final apk (e.g. because some other dependency you're using has directly embedded a different version of ExoPlayer inside of itself, or similar)?

**Comment by Tolriq** [comment]
Nope triple checked. Only remaining would be change in library that would require a change in proguard configuration.
I just need a way to reproduce to be able to find cause. I just can't understand why it would not touch every devices / users.

**Comment by sylvain-toptal** [comment]
I'm also having something similar :
```
12-08 14:17:29.550 E/AndroidRuntime(15869): java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$EventListener.onSeekProcessed()"
12-08 14:17:29.550 E/AndroidRuntime(15869): 	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:554)
12-08 14:17:29.550 E/AndroidRuntime(15869): 	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:476)
12-08 14:17:29.550 E/AndroidRuntime(15869): 	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:100)
12-08 14:17:29.550 E/AndroidRuntime(15869): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-08 14:17:29.550 E/AndroidRuntime(15869): 	at android.os.Looper.loop(Looper.java:145)
12-08 14:17:29.550 E/AndroidRuntime(15869): 	at android.app.ActivityThread.main(ActivityThread.java:5942)
12-08 14:17:29.550 E/AndroidRuntime(15869): 	at java.lang.reflect.Method.invoke(Native Method)
12-08 14:17:29.550 E/AndroidRuntime(15869): 	at java.lang.reflect.Method.invoke(Method.java:372)
12-08 14:17:29.550 E/AndroidRuntime(15869): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
12-08 14:17:29.550 E/AndroidRuntime(15869): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

```

**Comment by Tolriq** [comment]
Well I've published another release build without any exoplayer changes and it seems the problem is no more present.

Can only imagine the clean before build left something behind. Will add some security to fail on clean in case of. Closing this so.

**Comment by sylvain-toptal** [comment]
I think my crash was due to a discrepancy between the runtime Exoplayer version and the one expected by Mux.
