### ISSUE TITLE
Cannot play MP4 stream (IllegalStateException, Codec reported err 0x80001001)

### ISSUE THREAD

**Issue by cdhowie** [google/ExoPlayer#3512]
### Issue description
When attempting to play specific MP4 streams, the player will not start and issues an exception.  This happens on an API level 22 AVD, but does not happen on API level 26 devices.

### Reproduction steps
Simply attempt to play the stream.

### Link to test content
[Link](https://bcsecure04-a.akamaihd.net/hd2/o1/4338955640001/4338955640001_5157111715001_5157088401001.mp4?pubId=4338955640001&videoId=5157088401001)

### Version of ExoPlayer being used
2.5.4

### Device(s) and version(s) of Android being used
AVD: Nexus 6 hardware profile, Android 5.1.1 image (API level 22).

### A full bug report captured from the device
[bugreport-Nexus_6_API_22-2017-11-28-13-52-26-69d55aed-7c29-44eb-b4a3-6eef8a8ab6ed.zip](https://github.com/google/ExoPlayer/files/1511213/bugreport-Nexus_6_API_22-2017-11-28-13-52-26-69d55aed-7c29-44eb-b4a3-6eef8a8ab6ed.zip)

Most likely the relevant log snippet:

```
11-28 13:22:30.753 3786-3836/com.imavex.itiswritten W/OMXNodeInstance: [1:google.h264.decoder] component does not support metadata mode; using fallback
11-28 13:22:30.753 3786-3836/com.imavex.itiswritten E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
11-28 13:22:30.762 3786-3807/com.imavex.itiswritten D/EGL_emulation: eglMakeCurrent: 0xae834ee0: ver 2 0
11-28 13:22:30.762 3786-3837/com.imavex.itiswritten E/SoftAVC: Decoder failed: -2
11-28 13:22:30.762 3786-3836/com.imavex.itiswritten E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
11-28 13:22:30.762 3786-3836/com.imavex.itiswritten E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
11-28 13:22:30.763 3786-3835/com.imavex.itiswritten E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
11-28 13:22:30.767 3786-3832/com.imavex.itiswritten E/ExoPlayerImplInternal: Internal runtime error.
                                                                             java.lang.IllegalStateException
                                                                                 at android.media.MediaCodec.native_queueInputBuffer(Native Method)
                                                                                 at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:831)
                                                                                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:741)
                                                                                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:551)
                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:578)
                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
11-28 13:22:30.797 3786-3832/com.imavex.itiswritten E/ExoPlayerImplInternal: Stop failed.
                                                                             java.lang.IllegalStateException
                                                                                 at android.media.MediaCodec.native_stop(Native Method)
                                                                                 at android.media.MediaCodec.stop(MediaCodec.java:628)
                                                                                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:495)
                                                                                 at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:414)
                                                                                 at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:449)
                                                                                 at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:317)
                                                                                 at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:147)
                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:828)
                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:803)
                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:406)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by ojw28** [comment]
Please see the [bottom FAQ](https://google.github.io/ExoPlayer/faqs.html#does-exoplayer-support-emulators) regarding emulator/virtual-device support. Thanks!

**Comment by cdhowie** [comment]
@ojw28 Jeez, I even remember reading that very paragraph last week. 🤦‍♂️ 

Thanks for the link, and sorry for the noise.
