### ISSUE TITLE
Slow connection crash - Source Error

### ISSUE THREAD

**Issue by jboisjo** [google/ExoPlayer#3528]
Hi, 

i'm using the last version (exoplayer 2.6.0) and i'm simulating a slow connection to handle a slow or crash situation. 

I'm trying one of our DASH live playlist which the first profil has a 640x360 (900kbps) and
right now, i'm having a 10mbps connection (1.5 MB/s).

Normally, the player will be buffering segments and play them once it's downloaded but after 3-4 segments, i'm getting a crash error

```
internalError [324.69, loadError]
                                                                            internalError [324.69, loadError]
                                                                            com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to  #'urlplaylist'
                                                                                at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
                                                                                at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
                                                                                at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
                                                                                at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:125)
                                                                                at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                at java.lang.Thread.run(Thread.java:761)


11-30 16:52:41.034 13617-13840/ExoPlayerImplInternal: Source error.
                                                                                      com.google.android.exoplayer2.source.BehindLiveWindowException
                                                                                          at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:280)
                                                                                          at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:466)
                                                                                          at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:71)
                                                                                          at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading(HlsMediaPeriod.java:194)
                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.continueLoading(ExoPlayerImplInternal.java:1640)
                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1439)
                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1432)
                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:334)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
```

Is there any solution out there to handle slow connection and keep them on Buffering and not make the player crash?

Thank you very much!

**Comment by andrewlewis** [comment]
Please provide the information requested in the issue template, especially a link to the media you're trying to play.

Is `#'urlplaylist'` what's actually logged? Looks like it should be an actual URL, so that may indicate that the manifest is wrong. In general, if you handle a loading error via the player's listener you can re-prepare the player with a new `MediaSource` to retry. The process should not crash.

**Comment by ojw28** [comment]
A stack trace being logged doesn't necessarily mean anything crashed. This looks like a standard playback failure due to falling behind the window of a live stream, which is caused by a combination of buffering and the content exposing a relatively small live window. The only fixes are to decrease the bandwidth requirements of the content (e.g. by providing a lower bitrate variant), increase the size of the content's live window (e.g. keep segments available in the media playlist for longer), or connect over a higher bandwidth connection.
