### ISSUE TITLE
How I can customize the start and the end positions for an HLS stream ?

### ISSUE THREAD

**Issue by Sara-Tareq** [google/ExoPlayer#3550]
Hello ,
I want to set a start and an end position so a different duration other than the values coming in the hls manifest from the stream url, In other words, I want to trim the video stream, how can I achieve that using exoplayer ?

**Comment by andrewlewis** [comment]
Have you tried wrapping your `HlsMediaSource` in a `ClippingMediaSource`?

**Comment by Sara-Tareq** [comment]
Hi Andrew, thanks for your reply, it actually worked but when I tried to add an Ad using ImaAdsMediaSource in v2.6.0 I got an exception :
playerFailed [115066.66]
                                                                       com.google.android.exoplayer2.ExoPlaybackException
                                                                           at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:360)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                        Caused by: java.lang.IllegalArgumentException
                                                                           at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:37)
                                                                           at com.google.android.exoplayer2.source.ads.AdsMediaSource.prepareSource(AdsMediaSource.java:140)
                                                                           at com.google.android.exoplayer2.ext.ima.ImaAdsMediaSource.prepareSource(ImaAdsMediaSource.java:75)
                                                                           at com.google.android.exoplayer2.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:395)
                                                                           at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:290)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                           at android.os.Looper.loop(Looper.java:154) 
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)


And also I want to ask it's stated in the ClippingMediaSource documentation that it's valid only for a replay stream not live , how can I set a starting position only in case of live stream ?

**Comment by andrewlewis** [comment]
The ads media source must be the top-level source (meaning that it isn't wrapped by another source, so you prepare the player with it directly). You may be able to clip the content source before passing it to the ads media source, so that the ads media source is still top-level.

There are various clipping cases we don't support, but on the `dev-v2` branch we removed the requirement that the wrapped source doesn't have a dynamic window, so it might be worth trying that.

**Comment by Sara-Tareq** [comment]
I checked the new released version 2.6.1 and the clipping media source is still not supporting live streams and it's only available on the dev-v2, Is there a reason for that and Is the clipping media source dev source can be used in an app to be released ?

**Comment by andrewlewis** [comment]
@ojw28 Any idea when the change to `ClippingMediaSource` to support dynamic child windows will be released?

**Comment by ojw28** [comment]
It will probably be in 2.7.0, for which we don't have an ETA currently, sorry. It's somewhat unclear to me that this will even resolve the issue described here (@Sara-Tareq - Have you tested and confirmed this works using the latest `dev-v2`?).

**Comment by Sara-Tareq** [comment]
@ojw28 yes I tested using dev-v2 and the live stream was getting clipped, I set the start pos as a value and the end pos as C.TIME_END_OF_SOURCE

**Comment by ojw28** [comment]
Moving discussion to: https://github.com/google/ExoPlayer/issues/3683.
