### ISSUE TITLE
BadPaddingException: EVP_CipherFinal_ex

### ISSUE THREAD

**Issue by yurilaguta** [google/ExoPlayer#3557]
### Issue description
Observed:
Error thrown when playing a stream
Expected:
No error should be thrown

### Reproduction steps
Play hls steam in demo app

### Link to test content
Sent by email

### Version of ExoPlayer being used
2.6.0, in demo reproduced on 2.5.4

### Device(s) and version(s) of Android being used
Nexus 10 Android 5.1 Lollipop

### A full bug report captured from the device
[bug_report_EVP_CipherFinal.txt](https://github.com/google/ExoPlayer/files/1537306/bug_report_EVP_CipherFinal.txt)

**Comment by ojw28** [comment]
The provided stream is 2 hours 30 minutes long. When does this error occur exactly?

**Comment by yurilaguta** [comment]
It occurred in the first 3 minutes randomly

Best Regards,
Yura.

**Comment by ojw28** [comment]
Stack trace:

```
12-07 10:45:57.785 27201 27201 E EventLogger: java.io.IOException: Error while finalizing cipher
12-07 10:45:57.785 27201 27201 E EventLogger: 	at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:104)
12-07 10:45:57.785 27201 27201 E EventLogger: 	at javax.crypto.CipherInputStream.read(CipherInputStream.java:155)
12-07 10:45:57.785 27201 27201 E EventLogger: 	at com.google.android.exoplayer2.source.hls.Aes128DataSource.read(Aes128DataSource.java:96)
12-07 10:45:57.785 27201 27201 E EventLogger: 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:257)
12-07 10:45:57.785 27201 27201 E EventLogger: 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:59)
12-07 10:45:57.785 27201 27201 E EventLogger: 	at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:233)
12-07 10:45:57.785 27201 27201 E EventLogger: 	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:255)
12-07 10:45:57.785 27201 27201 E EventLogger: 	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:191)
12-07 10:45:57.785 27201 27201 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
12-07 10:45:57.785 27201 27201 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-07 10:45:57.785 27201 27201 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-07 10:45:57.785 27201 27201 E EventLogger: 	at java.lang.Thread.run(Thread.java:818)
12-07 10:45:57.785 27201 27201 E EventLogger: Caused by: javax.crypto.BadPaddingException: EVP_CipherFinal_ex
12-07 10:45:57.785 27201 27201 E EventLogger: 	at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
12-07 10:45:57.785 27201 27201 E EventLogger: 	at com.android.org.conscrypt.OpenSSLCipher.doFinalInternal(OpenSSLCipher.java:430)
12-07 10:45:57.785 27201 27201 E EventLogger: 	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:490)
12-07 10:45:57.785 27201 27201 E EventLogger: 	at javax.crypto.Cipher.doFinal(Cipher.java:1314)
12-07 10:45:57.785 27201 27201 E EventLogger: 	at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:102)
12-07 10:45:57.785 27201 27201 E EventLogger: 	... 11 more
```

If I try and force use of BouncyCastle instead I see a similar failure from that Cipher provider too:

```
E/EventLogger( 4335): java.io.IOException: Error while finalizing cipher
E/EventLogger( 4335): 	at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:104)
E/EventLogger( 4335): 	at javax.crypto.CipherInputStream.read(CipherInputStream.java:155)
E/EventLogger( 4335): 	at com.google.android.exoplayer2.source.hls.Aes128DataSource.read(Aes128DataSource.java:99)
E/EventLogger( 4335): 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:257)
E/EventLogger( 4335): 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:59)
E/EventLogger( 4335): 	at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:233)
E/EventLogger( 4335): 	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:255)
E/EventLogger( 4335): 	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:191)
E/EventLogger( 4335): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
E/EventLogger( 4335): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/EventLogger( 4335): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/EventLogger( 4335): 	at java.lang.Thread.run(Thread.java:818)
E/EventLogger( 4335): Caused by: javax.crypto.BadPaddingException: pad block corrupted
E/EventLogger( 4335): 	at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:898)
E/EventLogger( 4335): 	at javax.crypto.Cipher.doFinal(Cipher.java:1314)
E/EventLogger( 4335): 	at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:102)
E/EventLogger( 4335): 	... 11 more
```

**Comment by ojw28** [comment]
It looks like the content is able to play successfully if the Cipher is changed to `"AES/CBC/NoPadding"` in `Aes128DataSource`. This, along with the fact two different Cipher implementations are both complaining, and the fact I'm able to play other encrypted content successfully on the same device, suggests that the content does not have PKCS7 padding, as is required by the HLS specification.

I do see that the content plays successfully on some other devices, although this may just be down to those devices being more lenient when bad padding is encountered.

If this is your content, please could you try and validate that PKCS7 padding is being used?

**Comment by yurilaguta** [comment]
Thanks @ojw28 I'll check with people responsible for content and let you know.

**Comment by yurilaguta** [comment]
@ojw28 steams has been working fine for the last 10 days. Seems like it was a content issue. Thanks.
