### ISSUE TITLE
Assertions.checkState() Illeagal state exception in HLS prepareSource

### ISSUE THREAD

**Issue by rranjithkumar100** [google/ExoPlayer#3568]
**### Issue description**
I use the DynamicConcatenatingMediaSource with ClippingMediaSource.

**Purpose of my player**
Play the movie for particular duration & play the video ads in middle of the movie. 
So I clip the movie with help of ClippingMediaSource & add the video ads & again clip the balance movie --> add it all into DynamicConcatenatingMediaSource 

Note : Same code working in some movies. But this error only occur for one movie. 
But this movie M3U8 is valid(verified with VLC player).  

In my error log I got error at HlsMediaSource.java:96 
so I check this 96th line  --> **Assertions.checkState(playlistTracker == null);**  //this maybe helpful

**Sample code:** 
    
     ClippingMediaSource clippingMediaSource = new ClippingMediaSource(movieMediaSource, mSeekMicroSeconds, breakTimeMicroSeconds);
     concatenatingMediaSource.addMediaSource(mediaSourceIndex, clippingMediaSource);

My HLSMediaSource code

       DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, "MOD"), mBandwidthMeter);
      MediaSource videoSource = new HlsMediaSource(mp4VideoUri, dataSourceFactory, mainHandler, this);

After checking some references (from old issues) they suggest put seekTo() before prepare()

**I tried following but same error occur**

        mExoPlayer.seekTo(0L);
        mExoPlayer.prepare(mediaSource);

### Version of ExoPlayer being used

  compile 'com.google.android.exoplayer:exoplayer:r2.5.4'

### Device(s) and version(s) of Android being used

Lenova A6000 plus & Android 5.0.1 

LOG
     
```
java.lang.IllegalStateException at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:79)
 at com.google.android.exoplayer2.source.hls.HlsMediaSource.prepareSource(HlsMediaSource.java:96)
  at com.google.android.exoplayer2.source.ClippingMediaSource.prepareSource(ClippingMediaSource.java:89)
   at com.google.android.exoplayer2.source.DynamicConcatenatingMediaSource.addMediaSourceInternal(DynamicConcatenatingMediaSource.java:284)
                                                                         at com.google.android.exoplayer2.source.DynamicConcatenatingMediaSource.addMediaSourcesInternal(DynamicConcatenatingMediaSource.java:294)
                                                                         at com.google.android.exoplayer2.source.DynamicConcatenatingMediaSource.prepareSource(DynamicConcatenatingMediaSource.java:182)
                                                                         at com.google.android.exoplayer2.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:439)
                                                                         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:338)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by ojw28** [comment]
The error suggests that you're reusing `HlsMediaSource` instances. For example, perhaps you're adding the same instance more than once to a dynamic concatenating media source. You should instead create a new instance each time.

You should do this for all `MediaSource` types, although it's possible that the HLS implementation is the only one that fails (at least in an obvious way) as a result of not doing so.

Related documentation about not re-using `MediaSource` instances can be found [here](https://google.github.io/ExoPlayer/guide.html#mediasource) and [here](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/DynamicConcatenatingMediaSource.html#addMediaSource-int-com.google.android.exoplayer2.source.MediaSource-).

**Comment by rranjithkumar100** [comment]
You save my day. Thanks again @ojw28
