### ISSUE TITLE
Mpeg Dash live streaming 416 exception while playing the video

### ISSUE THREAD

**Issue by RadhikaBalla** [google/ExoPlayer#3573]
Hi...

   While playing mpeg dash live stream which is coming from wowza streaming engine, it is giving 416 exception using Exoplayer -release-v2. At the beginning of stream one video frame is coming, after that it is giving '416' error. If we play the same stream in other players like http://hlstester.com/ it is playing without any interruption. 

**This is the Stream URL that I am playing. Please help me out in fixing this issue.**
 
 http://183.82.107.32:1935/live/mystream1/manifest.mpd

 **And following is the error that I am getting while playing the stream.**

```
com.google.android.exoplayer2.demo E/EventLogger: internalError [80.32, loadError]
com.google.android.exoplayer2.extractor.flv.TagPayloadReader$UnsupportedFormatException: Audio format not supported: 2
  at com.google.android.exoplayer2.extractor.flv.AudioTagPayloadReader.parseHeader(AudioTagPayloadReader.java:68)
  at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:64)
  at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:254)
  at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:159)
  at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:643)
  at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                   at java.lang.Thread.run(Thread.java:761)
```

**Comment by ojw28** [comment]
This issue seems quite confused:

1. The stack trace above does not look like it corresponds to playing a DASH stream, and is unrelated to the error mentioned in the title and description.
1. http://hlstester.com/ does not appear to support DASH content, and does not appear to successfully play the referenced stream.
1. There is no bug report captured with `adb bugreport` provided, as is explicitly requested in our issue template. Providing one would have saved us a bunch of time, by making the initial failure immediately clear. Which looks like it's:

```
 com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: length=1; index=1
 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:337)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
 	at java.lang.Thread.run(Thread.java:762)
 Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
 	at com.google.android.exoplayer2.util.ParsableBitArray.readBits(ParsableBitArray.java:178)
 	at com.google.android.exoplayer2.util.CodecSpecificDataUtil.getAacSamplingFrequency(CodecSpecificDataUtil.java:314)
 	at com.google.android.exoplayer2.util.CodecSpecificDataUtil.parseAacAudioSpecificConfig(CodecSpecificDataUtil.java:109)
 	at com.google.android.exoplayer2.util.CodecSpecificDataUtil.parseAacAudioSpecificConfig(CodecSpecificDataUtil.java:93)
 	at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseAudioSampleEntry(AtomParsers.java:932)
 	at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:630)
 	at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:91)
 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onMoovContainerAtomRead(FragmentedMp4Extractor.java:479)
```

**Comment by ojw28** [comment]
I can't get the referenced stream to play in any of:

* https://shaka-player-demo.appspot.com/demo/#lang=en-US
* http://reference.dashif.org/dash.js/v2.6.4/samples/dash-if-reference-player/index.html
* https://bitmovin.com/hls-mpeg-dash-test-player/

Closing on the assumption the media is bad. Please provide more information, and preferably details of the stream playing successfully in some other player, if you want us to investigate further. Thanks.
