### ISSUE TITLE
ArrayIndexOutOfBoundsException on playback HLS live stream the lastest version 

### ISSUE THREAD

**Issue by crossle** [google/ExoPlayer#358]
```
          LoadTask  E  Unexpected error loading stream
                        E  java.lang.ArrayIndexOutOfBoundsException
                        E      at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
                        E      at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:165)
                        E      at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:206)
                        E      at com.google.android.exoplayer.upstream.UriDataSource.read(UriDataSource.java:71)
                        E      at com.google.android.exoplayer.hls.parser.DataSourceExtractorInput.skipFully(DataSourceExtractorInput.java:85)
                        E      at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:113)
                        E      at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:241)
                        E      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                        E      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                        E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                        E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                        E      at java.lang.Thread.run(Thread.java:818)
                        E  Unexpected error loading stream
                        E  java.lang.ArrayIndexOutOfBoundsException
                        E      at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
                        E      at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:165)
                        E      at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:206)
                        E      at com.google.android.exoplayer.upstream.UriDataSource.read(UriDataSource.java:71)
                        E      at com.google.android.exoplayer.hls.parser.DataSourceExtractorInput.skipFully(DataSourceExtractorInput.java:85)
                        E      at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:113)
                        E      at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:241)
                        E      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                        E      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                        E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                        E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                        E      at java.lang.Thread.run(Thread.java:818)

```

**Comment by crossle** [comment]
```
    E  com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBounds
                           Exception: null
                        E      at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:453)
                        E      at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
                        E      at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
                        E      at android.os.Handler.dispatchMessage(Handler.java:98)
                        E      at android.os.Looper.loop(Looper.java:135)
                        E      at android.os.HandlerThread.run(HandlerThread.java:61)
                        E      at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                        E  Caused by: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: null
                        E      at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:253)
                        E      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                        E      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                        E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                        E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                        E      at java.lang.Thread.run(Thread.java:818)
                        E  Caused by: java.lang.ArrayIndexOutOfBoundsException
                        E      at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
                        E      at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:165)
                        E      at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:206)
                        E      at com.google.android.exoplayer.upstream.UriDataSource.read(UriDataSource.java:71)
                        E      at com.google.android.exoplayer.hls.parser.DataSourceExtractorInput.skipFully(DataSourceExtractorInput.java:85)
                        E      at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:113)
                        E      at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:241)
                        E      ... 5 more

```

**Comment by ojw28** [comment]
We're doing some fairly major refactoring on the dev branch currently, so you might see a few issues such as this one (reporting them is still useful though, so thanks!). This specific problem is easy to fix.

**Comment by ojw28** [comment]
Fixed in https://github.com/google/ExoPlayer/commit/e54d07c1b09ee051d4ceedcde12f50433111c45d
