### ISSUE TITLE
Exoplayer midroll stuck when vast document is empty

### ISSUE THREAD

**Issue by orhunkupeli7** [google/ExoPlayer#3584]
If vast document is empty player stucks.

Create an empty vast document for a midroll like:
`<VAST` xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="3.0"/>

Example link:
http://rmcdn.2mdn.net/MotifFiles/html/1248596/android_1330378998288.mp4

Player Version:
Version of exoplayer 2.6.0

Device: Nexus 5x API 24
Bug report:
12-13 13:57:59.772 7678-7678/com.google.android.exoplayer2.imademo W/ImaAdsLoader: onAdEvent: LOG
12-13 13:57:59.772 7678-7678/com.google.android.exoplayer2.imademo W/ImaAdsLoader:   type: adLoadError
12-13 13:57:59.772 7678-7678/com.google.android.exoplayer2.imademo W/ImaAdsLoader:   errorCode: 1009
12-13 13:57:59.772 7678-7678/com.google.android.exoplayer2.imademo W/ImaAdsLoader:   errorMessage: The response does not contain any valid ads.
However it's an empty vast document
[bugreport-NYC-2017-12-13-13-58-12.zip](https://github.com/google/ExoPlayer/files/1555704/bugreport-NYC-2017-12-13-13-58-12.zip)

**Comment by equistar** [comment]
Hi @andrewlewis , Any updates on this bug. ?

**Comment by jazimm** [comment]
I'm experiencing the same issue when the response is empty. Rather than the empty ad being skipped and content resuming the player simply hangs.

**Comment by andrewlewis** [comment]
A fix for this is in review at the moment. Hopefully it will be on the development branch within the next couple of weeks. Thanks for your patience.

**Comment by andrewlewis** [comment]
Still working on this but it's likely to take a bit longer as it requires changes to how we handle ad timeline updates.

**Comment by wezley98** [comment]
Hi @andrewlewis, This is blocking us from updating our current implementation to exoplayer v2 from v1, is there any update on this issue please?

**Comment by andrewlewis** [comment]
We plan to push an update to the development branch that should fix this later this week, or early next week. Sorry for the delay.

**Comment by andrewlewis** [comment]
Please give the fix on `dev-v2` a try and let me know if you see any remaining problems related to empty midrolls. Thanks!

**Comment by wezley98** [comment]
@andrewlewis tested with the IMA demo on dev-v2 unfortunately it's not working correctly.

```
27.165 10548-10548/com.google.android.exoplayer2.imademo W/AdsMediaSource: Ad load error
                                                                                       java.io.IOException: Ad error: com.google.obf.gk@aba7a39
                                                                                           at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.maybeNotifyAdError(ImaAdsLoader.java:836)
                                                                                           at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.onAdError(ImaAdsLoader.java:554)
                                                                                           at com.google.obf.he.a(IMASDK:8)
                                                                                           at com.google.obf.gy.a(IMASDK:60)
                                                                                           at com.google.obf.gy.a(IMASDK:95)
                                                                                           at com.google.obf.gq.a(IMASDK:71)
                                                                                           at com.google.obf.hj.f(IMASDK:202)
                                                                                           at com.google.obf.hj.a(IMASDK:41)
                                                                                           at com.google.obf.hk.b(IMASDK:39)
                                                                                           at com.google.obf.hk$1.shouldOverrideUrlLoading(IMASDK:4)
                                                                                           at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
                                                                                           at com.android.webview.chromium.Ap.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:75)
                                                                                           at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:15)
                                                                                           at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:160)
                                                                                           at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                                                           at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                        Caused by: AdError [errorType: PLAY, errorCode: AdErrorCode [name: VAST_LINEAR_ASSET_MISMATCH, number: 403], message: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities.]
                                                                                           at com.google.obf.gy.a(IMASDK:94)
                                                                                           at com.google.obf.gq.a(IMASDK:71) 
                                                                                           at com.google.obf.hj.f(IMASDK:202) 
                                                                                           at com.google.obf.hj.a(IMASDK:41) 
                                                                                           at com.google.obf.hk.b(IMASDK:39) 
                                                                                           at com.google.obf.hk$1.shouldOverrideUrlLoading(IMASDK:4) 
                                                                                           at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73) 
                                                                                           at com.android.webview.chromium.Ap.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:75) 
                                                                                           at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:15) 
                                                                                           at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:160) 
                                                                                           at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method) 
                                                                                           at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                           at android.os.Looper.loop(Looper.java:164) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
``` 

We expect a 403 and no ad to play but the video content does not play and the player hangs. For testing you can you the following VAST tag.

```
https://skygo.neodatagroup.com/ad/skySport.jsp?f=preroll-clip&device=phone&params=%7B%22nlid%22%3A%221f2d25c4-23be-45c9-9332-097281b96d22%22%2C%22uid%22%3A%22%22%2C%22userType%22%3A%224%22%2C%22gender%22%3A%22%22%2C%22trialexpire%22%3A%22%22%2C%22adv%22%3A%22true%22%2C%22os%22%3A%22android%22%2C%22path%22%3A%22Calciomercato%2Fcalciomercato%22%2C%22advCategory%22%3A%22Calciomercato%22%2C%22advSportname%22%3A%22calciomercato%22%2C%22videoChannel%22%3A%22sport%22%2C%22videoSubchannel%22%3A%22calciomercato%22%2C%22videoDuration%22%3A%2242%22%2C%22videoTag%3A%22%3A%5B%22%22%2C%22%22%2C%22%22%5D%2C%22videoAdv%22%3A%221%22%7D
```

**Comment by andrewlewis** [comment]
That error is different from the empty midroll case handled here, and is tracked in #3801.

**Comment by wezley98** [comment]
@andrewlewis Thanks, I have updated the other ticket with my example.

**Comment by fpittersacc** [comment]
Hi @andrewlewis, it seems this issue is still happening under some conditions: when Preroll + Midroll (or Preroll + Postroll), after the empty Preroll, when reaching the Midroll (or Postroll) it gets stuck, like paused, without any further events.

We are able to reproduce the same behavior with following steps:
1. Replace  Ad TAG on IMA Demo with [
IMA Sample Tags](https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags)

VMAP Pre-, Mid-, and Post-rolls, Single Ads
`https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=`

2. Block the specific Ad requests with Charles: 
`https://pubads.g.doubleclick.net/gampad/ads?slotname=`

The player will correctly skip the first Ad error, but it seems is not correctly handling further Ads indexes, or maybe not correctly reporting the time to the underlying IMA library.

Let me know if you need any further information or it would be better to create a new issue.

**Comment by andrewlewis** [comment]
@fpittersacc Thank you for the information. Please do file a new issue and I'll investigate further.
