### ISSUE TITLE
play mkv - ExoPlaybackException, ACodec: [OMX.qcom.video.decoder.avc] ERROR(0x80001009)

### ISSUE THREAD

**Issue by anonym24** [google/ExoPlayer#3601]
### Issue description
ExoPlayer won't play next mkv file

```
Format                                   : Matroska
Format version                           : Version 2
File size                                : 1.86 GiB
Duration                                 : 26mn 29s
Overall bit rate mode                    : Variable
Overall bit rate                         : 10.1 Mbps
Encoded date                             : UTC 2013-07-22 13:19:58
Writing application                      : mkvmerge v5.7.0 ('The Whirlwind') built on Jul 29 2012 15:12:35
Writing library                          : libebml v1.2.3 + libmatroska v1.3.0

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High 10@L4
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 26mn 29s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Scan type                                : Progressive
Writing library                          : x264 core 125 r2200+677M 3a754e7
Encoding settings                        : cabac=1 / ref=3 / deblock=1:-1:-1 / analyse=0x3:0x133 / me=umh / subme=7 / psy=1 / fade_compensate=0.00 / psy_rd=0.90:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=0 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / fgo=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc=crf / mbtree=0 / crf=15.5000 / qcomp=0.60 / qpmin=2 / qpmax=51 / qpstep=4 / ip_ratio=1.40 / pb_ratio=1.30 / aq=1:0.90
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Codec ID                                 : A_FLAC
Duration                                 : 26mn 29s
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Writing library                          : Lavf52.58.0
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No
```

MX Player can play this file

### Reproduction steps
```
fileVideo = new File(Environment.getExternalStorageDirectory() + "/mkv3.mkv");
MediaSource mediaSource = new ExtractorMediaSource(Uri.fromFile(fileVideo),
                factory, new DefaultExtractorsFactory(), mainHandler, eventLogger);
exo.prepare(mediaSource);
exo.setPlayWhenReady(true);
```

### Link to test content
download - magnet:?xt=urn:btih:FC97F177CF58EF49BF9A01E19BE88373AF345EDB

### Version of ExoPlayer being used
2.6.0 (same issue on r2.5.2)

### Device(s) and version(s) of Android being used
Redmi 4 Prime, Android 6.0.1

### A full bug report captured from the device
```
12-16 16:43:38.896 21489-21489/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init 88cf274 [ExoPlayerLib/2.6.0] [markw, Redmi 4, Xiaomi, 23]
12-16 16:43:38.936 21489-21542/com.google.android.exoplayer2.demo D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
12-16 16:43:38.942 21489-21489/com.google.android.exoplayer2.demo D/ActivityThreadInjector: clearCachedDrawables.
12-16 16:43:38.978 21489-21542/com.google.android.exoplayer2.demo I/Adreno: QUALCOMM build                   : 05151ca, I74772a33ad
                                                                            Build Date                       : 09/13/16
                                                                            OpenGL ES Shader Compiler Version: XE031.08.00.00
                                                                            Local Branch                     : 
                                                                            Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.5.3_RB1.06.00.01.211.047
                                                                            Remote Branch                    : NONE
                                                                            Reconstruct Branch               : NOTHING
12-16 16:43:38.984 21489-21542/com.google.android.exoplayer2.demo I/OpenGLRenderer: Initialized EGL, version 1.4
12-16 16:43:38.987 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: state [0.15, false, B]
12-16 16:43:38.989 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: sourceInfo [periodCount=1, windowCount=1
12-16 16:43:38.989 21489-21489/com.google.android.exoplayer2.demo D/EventLogger:   period [?]
12-16 16:43:38.989 21489-21489/com.google.android.exoplayer2.demo D/EventLogger:   window [?, false, false]
12-16 16:43:38.989 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: ]
12-16 16:43:39.007 21489-21542/com.google.android.exoplayer2.demo E/HAL: Dawei load: module=/system/lib64/hw/gralloc.msm8953.so
12-16 16:43:39.041 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: loading [true]
12-16 16:43:39.157 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: sourceInfo [periodCount=1, windowCount=1
12-16 16:43:39.157 21489-21489/com.google.android.exoplayer2.demo D/EventLogger:   period [1589.59]
12-16 16:43:39.158 21489-21489/com.google.android.exoplayer2.demo D/EventLogger:   window [1589.59, true, false]
12-16 16:43:39.158 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: ]
12-16 16:43:39.181 21489-21541/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
12-16 16:43:39.181 21489-21541/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
12-16 16:43:39.185 21489-21541/com.google.android.exoplayer2.demo W/Utils: could not parse long range '175-174'
12-16 16:43:39.188 21489-21541/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
12-16 16:43:39.189 21489-21541/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
12-16 16:43:39.193 21489-21541/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/x-ms-wmv
12-16 16:43:39.195 21489-21541/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/x-ms-wmv
12-16 16:43:39.196 21489-21541/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/wvc1
12-16 16:43:39.197 21489-21541/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/wvc1
12-16 16:43:39.198 21489-21541/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/divx
12-16 16:43:39.199 21489-21541/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/divx311
12-16 16:43:39.200 21489-21541/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/divx4
12-16 16:43:39.206 21489-21541/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/mp4v-esdp
12-16 16:43:39.215 21489-21541/com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
12-16 16:43:39.224 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: Tracks [
12-16 16:43:39.224 21489-21489/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:0 [
12-16 16:43:39.225 21489-21489/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
12-16 16:43:39.225 21489-21489/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=1, mimeType=video/avc, res=1920x1080, supported=YES
12-16 16:43:39.225 21489-21489/com.google.android.exoplayer2.demo D/EventLogger:     ]
12-16 16:43:39.225 21489-21489/com.google.android.exoplayer2.demo D/EventLogger:   ]
12-16 16:43:39.225 21489-21489/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:1 [
12-16 16:43:39.225 21489-21489/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
12-16 16:43:39.225 21489-21489/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=2, mimeType=audio/flac, channels=2, sample_rate=48000, language=jpn, supported=YES
12-16 16:43:39.225 21489-21489/com.google.android.exoplayer2.demo D/EventLogger:     ]
12-16 16:43:39.225 21489-21489/com.google.android.exoplayer2.demo D/EventLogger:   ]
12-16 16:43:39.225 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: ]
12-16 16:43:39.226 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: videoEnabled [0.39]
12-16 16:43:39.226 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: audioEnabled [0.39]
12-16 16:43:39.229 21489-21546/com.google.android.exoplayer2.demo I/OMXClient: Using client-side OMX mux.
                                                                               
                                                                               [ 12-16 16:43:39.236   720:14776 E/         ]
                                                                               Service not available yet
12-16 16:43:39.360 21489-21545/com.google.android.exoplayer2.demo I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 22004737
12-16 16:43:39.364 21489-21546/com.google.android.exoplayer2.demo I/ExtendedACodec: setupVideoDecoder()
12-16 16:43:39.364 21489-21546/com.google.android.exoplayer2.demo I/ExtendedACodec: vpp-enable search is 0 and value is 0
12-16 16:43:39.382 21489-21546/com.google.android.exoplayer2.demo I/ExtendedACodec: Decoder will be in frame by frame mode
12-16 16:43:39.383 21489-21546/com.google.android.exoplayer2.demo W/ExtendedACodec: Failed to set frame packing format on component
12-16 16:43:39.433 21489-21546/com.google.android.exoplayer2.demo D/SurfaceUtils: set up nativeWindow 0x55860ebe60 for 1920x1080, color 0x7fa30c06, rotation 0, usage 0x2002900
12-16 16:43:39.453 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: videoDecoderInitialized [0.61, OMX.qcom.video.decoder.avc]
12-16 16:43:39.455 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: videoFormatChanged [0.62, id=1, mimeType=video/avc, res=1920x1080]
12-16 16:43:39.459 21489-21556/com.google.android.exoplayer2.demo I/OMXClient: Using client-side OMX mux.
12-16 16:43:39.465 21489-21556/com.google.android.exoplayer2.demo I/ExtendedACodec: no bitwidth, setting default bitwidth as 16 bits
12-16 16:43:39.465 21489-21556/com.google.android.exoplayer2.demo I/ExtendedACodec: no min blksize, setting default block size as 16
12-16 16:43:39.465 21489-21556/com.google.android.exoplayer2.demo I/ExtendedACodec: no max blksize, setting default block size as 16
12-16 16:43:39.465 21489-21556/com.google.android.exoplayer2.demo I/ExtendedACodec: no min frame size, setting default frame size as 0
12-16 16:43:39.465 21489-21556/com.google.android.exoplayer2.demo I/ExtendedACodec: no max frame size, setting default frame size as 0
12-16 16:43:39.475 21489-21546/com.google.android.exoplayer2.demo E/ACodec: [OMX.qcom.video.decoder.avc] ERROR(0x80001009)
12-16 16:43:39.475 21489-21546/com.google.android.exoplayer2.demo E/ACodec: signalError(omxError 0x80001009, internalError -2147483648)
12-16 16:43:39.476 21489-21545/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported err 0x80001009, actionCode 0, while in state 6
12-16 16:43:39.483 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: audioDecoderInitialized [0.64, OMX.qti.audio.decoder.flac]
12-16 16:43:39.483 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: audioFormatChanged [0.64, id=2, mimeType=audio/flac, channels=2, sample_rate=48000, language=jpn]
12-16 16:43:39.497 21489-21541/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                           java.lang.IllegalStateException
                                                                                               at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                                               at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:942)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:552)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
12-16 16:43:39.499 21489-21489/com.google.android.exoplayer2.demo D/JoelDebug: onPlayerError()
12-16 16:43:39.500 21489-21489/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [0.66]
                                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:360)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                  Caused by: java.lang.IllegalStateException
                                                                                     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                                     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:942)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:552)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) 
12-16 16:43:39.504 21489-21546/com.google.android.exoplayer2.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x5586027e50
12-16 16:43:39.505 21489-21546/com.google.android.exoplayer2.demo W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 26 to native window
12-16 16:43:39.506 21489-21546/com.google.android.exoplayer2.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x55860fed80
12-16 16:43:39.506 21489-21546/com.google.android.exoplayer2.demo W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 25 to native window
12-16 16:43:39.506 21489-21546/com.google.android.exoplayer2.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x5586104760
12-16 16:43:39.507 21489-21546/com.google.android.exoplayer2.demo W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 24 to native window
12-16 16:43:39.507 21489-21546/com.google.android.exoplayer2.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x55860fe940
12-16 16:43:39.507 21489-21546/com.google.android.exoplayer2.demo W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 23 to native window
12-16 16:43:39.525 21489-21541/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Stop failed.
                                                                                           java.lang.IllegalStateException
                                                                                               at android.media.MediaCodec.native_stop(Native Method)
                                                                                               at android.media.MediaCodec.stop(MediaCodec.java:1901)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:497)
                                                                                               at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:424)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:451)
                                                                                               at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:326)
                                                                                               at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:150)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:865)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:813)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:790)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:362)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
12-16 16:43:39.526 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: videoDisabled [0.69]
12-16 16:43:39.539 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: audioDisabled [0.70]
12-16 16:43:39.540 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: loading [false]
12-16 16:43:39.541 21489-21489/com.google.android.exoplayer2.demo D/EventLogger: state [0.70, false, I]
```

**Comment by anonym24** [comment]
@ojw28 did you download sample? is it working for you ok in ExoPlayer? which test devices do you use?

also mb I rely on ExoPlayer too hard, trying to play such MKV videos (bdrip, 720/1080 or even bigger)
and it's just more than Android MediaPlayer API (like subtitles and DASH stream) but it's not going to be VLC, MX Player or FFmpeg?

then could you please clarify me about this project, is it going to get as close as possible to other popular players (mb in the future or already on it's way)? or is it going to depend on more what Android OS and Device's Hardware can do by default?

**Comment by ojw28** [comment]
The primary goal of ExoPlayer has never been to play whatever random (possibly broken) media file you throw at it. Our primary goal is to do a really good job of playing sensibly prepared media (e.g. media that doesn't use exotic codec features that hardly anyone else else uses, unreasonably high bit-rates, weird audio formats etc). This makes sense, since the vast majority of ExoPlayer usage is via large streaming apps (e.g. YouTube) who deliver media in a sensible way.

I didn't download the test link. We're not going to start downloading media over P2P networks. If you can provide some test content via http/https/email, please do so. Marking as "need more info" as a result. Thanks!

**Comment by anonym24** [comment]
ok, then I guess it's more for online streams than local files (because for local files user of android would want to play anything, what vlc or mxplayer can do)
many users downloads such videos using torrents (it's no a secret) - movies, tv series, animated sitcoms, anime. many of such videos are mkv (bdrip, hdtvrips..)
so what I test (videos) is popular enough, not broken
people wouldn't download mxplayer (it has many downloads) if they would be happy only with mp4 and factory video player app (based on MediaPlayer API)

for my project I think I'll use something different (libvlc for example) but here link anyway to test video for the issue https://uploadfiles.io/0a59m

**Comment by ojw28** [comment]
Yes, our primary goal probably does correspond more to streaming and playback of content recorded by the device's camera, than it does playback of side-loaded content. We aim to do a good job of supporting side-loaded content too, it's just not our primary focus.

Anyway, staying on topic: This issue has not yet been diagnosed, except it appears likely to be a device specific issue. We'll take a look when we have a chance. Thanks.

**Comment by shaopx** [comment]
i face the same issue.
when I do portrait and landscape switch more than 3 times . this exception will occur, I guess somehow the surface is not available during the switching.  But i dont know how to fix it.

**Comment by ojw28** [comment]
Please disregard the @google-oss-bot comment.

**Comment by ojw28** [comment]
Closing as part of a scrub of device specific issues that were filed more than 2 years ago.
