### ISSUE TITLE
OMX-VDEC-1080P: Unsupported WxH = (1920)x(3414) supported range is min(64)x(64) - max(1920)x(1920)

### ISSUE THREAD

**Issue by shoyu666** [google/ExoPlayer#3607]
###### version
com.google.android.exoplayer:exoplayer:2.6.0
###### <br>description 
- mp4  1920x3414
- xiaomi redmi 4x android 6.0.1(MMB29M)(miui 8.5.4.0)
- other device work fine (xiaomi noto,huawei ... )
##### maybe important error log
```
OMX-VDEC-1080P: Unsupported WxH = (1920)x(3414) supported range is min(64)x(64) - max(1920)x(1920)
```
##### question
dear auth:
                it seem my device not support 4k vedio,What should I do,need help（tip）
##### error log
```
12-18 16:47:09.509 18819-18819/com.wakeup.wakeup D/EventLogger: sourceInfo [periodCount=0, windowCount=0
12-18 16:47:09.510 18819-18819/com.wakeup.wakeup D/EventLogger: ]
12-18 16:47:09.510 18819-18819/com.wakeup.wakeup D/EventLogger: Tracks []
12-18 16:47:09.520 18819-18819/com.wakeup.wakeup D/EventLogger: state [1557.17, true, B]
12-18 16:47:09.519 3329-3569/? I/XiaomiFirewall: firewall pkgName:com.wakeup.wakeup, result:0x0
12-18 16:47:09.520 18819-18819/com.wakeup.wakeup D/EventLogger: sourceInfo [periodCount=1, windowCount=1
12-18 16:47:09.521 18819-18819/com.wakeup.wakeup D/EventLogger:   period [?]
12-18 16:47:09.521 18819-18819/com.wakeup.wakeup D/EventLogger:   window [?, false, false]
12-18 16:47:09.521 18819-18819/com.wakeup.wakeup D/EventLogger: ]
12-18 16:47:09.522 18819-18819/com.wakeup.wakeup D/EventLogger: loading [true]
12-18 16:47:10.338 688-781/? D/ThermalEngine: sensor_wait: case_therm Wait done.
12-18 16:47:10.340 688-781/? D/ThermalEngine: sensor_monitor: case_therm Reading 37000 .
12-18 16:47:10.340 688-781/? I/ThermalEngine: Sensor:case_therm:37000 mC
12-18 16:47:10.340 688-781/? D/ThermalEngine: update_active_thresh: case_therm Active(1), Hi(1) 42000, Lo(0) -2147483648, Interval(1) 1000
12-18 16:47:10.340 688-781/? D/ThermalEngine: sensor_monitor: case_therm Sensor wait.
12-18 16:47:10.340 688-781/? D/ThermalEngine: sensor_wait: case_therm Wait start. 1000ms
12-18 16:47:10.564 851-851/? I/MSM-irqbalance: Decided to move IRQ3 from CPU2 [P:0] to CPU4 [P:1] (banned)
12-18 16:47:10.564 851-851/? I/MSM-irqbalance: Decided to move IRQ5 from CPU2 [P:0] to CPU5 [P:1] (banned)
12-18 16:47:10.565 851-851/? I/MSM-irqbalance: Decided to move IRQ3 from CPU0 [P:0] to CPU6 [P:1] (banned)
12-18 16:47:10.565 851-851/? I/MSM-irqbalance: Decided to move IRQ5 from CPU0 [P:0] to CPU7 [P:1] (banned)
12-18 16:47:11.132 5590-5590/? D/wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
12-18 16:47:11.134 5590-5590/? D/wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=229376 outq=0 send_len=48
12-18 16:47:11.135 1420-1772/? D/ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 1395]
12-18 16:47:11.141 18516-18516/? D/StatusBar.NetworkController: slot=-10;action=android.net.wifi.RSSI_CHANGED
12-18 16:47:11.143 18516-18516/? D/StatusBar.NetworkController: updateNetworkName chosenNetType=16;mNetworkName[0]=移动
12-18 16:47:11.147 18516-18516/? D/StatusBar.NetworkController: updateNetworkName chosenNetType=10;mNetworkName[1]=联通 3G
12-18 16:47:11.341 688-781/? D/ThermalEngine: sensor_wait: case_therm Wait done.
12-18 16:47:11.342 688-781/? D/ThermalEngine: sensor_monitor: case_therm Reading 37000 .
12-18 16:47:11.342 688-781/? I/ThermalEngine: Sensor:case_therm:37000 mC
12-18 16:47:11.343 688-781/? D/ThermalEngine: update_active_thresh: case_therm Active(1), Hi(1) 42000, Lo(0) -2147483648, Interval(1) 1000
12-18 16:47:11.343 688-781/? D/ThermalEngine: sensor_monitor: case_therm Sensor wait.
12-18 16:47:11.343 688-781/? D/ThermalEngine: sensor_wait: case_therm Wait start. 1000ms
12-18 16:47:11.434 18819-19793/com.wakeup.wakeup D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1920x3414x-1.0] [OMX.qcom.video.decoder.avc, video/avc] [santoni, Redmi 4X, Xiaomi, 23]
12-18 16:47:11.434 18819-19793/com.wakeup.wakeup D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1920x3414x-1.0] [OMX.qcom.video.decoder.avc, video/avc] [santoni, Redmi 4X, Xiaomi, 23]
12-18 16:47:11.435 18819-18819/com.wakeup.wakeup D/EventLogger: sourceInfo [periodCount=1, windowCount=1
12-18 16:47:11.436 18819-18819/com.wakeup.wakeup D/EventLogger:   period [200.76]
12-18 16:47:11.436 18819-18819/com.wakeup.wakeup D/EventLogger:   window [200.76, true, false]
12-18 16:47:11.436 18819-18819/com.wakeup.wakeup D/EventLogger: ]
12-18 16:47:11.437 18819-18819/com.wakeup.wakeup D/EventLogger: Tracks [
12-18 16:47:11.437 18819-18819/com.wakeup.wakeup D/EventLogger:   Renderer:0 [
12-18 16:47:11.437 18819-18819/com.wakeup.wakeup D/EventLogger:     Group:0, adaptive_supported=N/A [
12-18 16:47:11.437 18819-18819/com.wakeup.wakeup D/EventLogger:       [X] Track:0, id=1, mimeType=video/avc, res=1920x3414, supported=NO_EXCEEDS_CAPABILITIES
12-18 16:47:11.437 18819-18819/com.wakeup.wakeup D/EventLogger:     ]
12-18 16:47:11.437 18819-18819/com.wakeup.wakeup D/EventLogger:   ]
12-18 16:47:11.438 18819-18819/com.wakeup.wakeup D/EventLogger:   Renderer:1 [
12-18 16:47:11.438 18819-18819/com.wakeup.wakeup D/EventLogger:     Group:0, adaptive_supported=N/A [
12-18 16:47:11.438 18819-18819/com.wakeup.wakeup D/EventLogger:       [X] Track:0, id=2, mimeType=audio/mp4a-latm, channels=2, sample_rate=44100, language=und, supported=YES
12-18 16:47:11.438 18819-18819/com.wakeup.wakeup D/EventLogger:     ]
12-18 16:47:11.438 18819-18819/com.wakeup.wakeup D/EventLogger:     Metadata [
12-18 16:47:11.438 18819-18819/com.wakeup.wakeup D/EventLogger:       TSSE: value=www.aliyun.com - Media Transcoding
12-18 16:47:11.438 18819-18819/com.wakeup.wakeup D/EventLogger:     ]
12-18 16:47:11.438 18819-18819/com.wakeup.wakeup D/EventLogger:   ]
12-18 16:47:11.438 18819-18819/com.wakeup.wakeup D/EventLogger: ]
12-18 16:47:11.441 18819-28191/com.wakeup.wakeup I/OMXClient: Using client-side OMX mux.
                                                              
                                                              [ 12-18 16:47:11.454   678: 1782 E/         ]
                                                              Service not available yet
12-18 16:47:11.456 3978-3993/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-18 16:47:11.457 678-1782/? I/OMX-VDEC-1080P: Video slvp perflock acquired
12-18 16:47:11.624 678-1782/? I/OMX-VDEC-1080P: component_init: OMX.qcom.video.decoder.avc : fd=59
12-18 16:47:11.637 678-1782/? I/OMX-VDEC-1080P: omx_vdec::component_init() success : fd=59
12-18 16:47:11.639 18819-28190/com.wakeup.wakeup I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 19270662
12-18 16:47:11.641 678-8254/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
12-18 16:47:11.642 18819-28191/com.wakeup.wakeup I/ExtendedACodec: setupVideoDecoder()
12-18 16:47:11.642 18819-28191/com.wakeup.wakeup I/ExtendedACodec: vpp-enable search is 0 and value is 0
12-18 16:47:11.646 678-3821/? E/OMX-VDEC-1080P: Unsupported WxH = (1920)x(3414) supported range is min(64)x(64) - max(1920)x(1920)
12-18 16:47:11.646 678-3821/? E/OMX-VDEC-1080P: set_parameter: Error: 0x80001019, setting param 0x2000001
12-18 16:47:11.646 678-3821/? E/OMXNodeInstance: setParameter(17db:qcom.decoder.avc, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
12-18 16:47:11.646 18819-28191/com.wakeup.wakeup E/ACodec: [OMX.qcom.video.decoder.avc] configureCodec returning error -1010
12-18 16:47:11.647 18819-28191/com.wakeup.wakeup E/ACodec: signalError(omxError 0x80001001, internalError -1010)
12-18 16:47:11.647 18819-28190/com.wakeup.wakeup E/MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3
12-18 16:47:11.648 18819-19793/com.wakeup.wakeup E/MediaCodec: configure failed with err 0xfffffc0e, resetting...
12-18 16:47:11.650 678-1782/? I/OMX-VDEC-1080P: omx_vdec::component_deinit() complete
12-18 16:47:11.652 678-1782/? I/OMX-VDEC-1080P: Exit OMX vdec Destructor: fd=59
12-18 16:47:11.653 678-1782/? I/OMX-VDEC-1080P: Video slvp perflock released
12-18 16:47:11.656 18819-28191/com.wakeup.wakeup I/OMXClient: Using client-side OMX mux.
                                                              
                                                              [ 12-18 16:47:11.667   678: 3821 E/         ]
                                                              Service not available yet
12-18 16:47:11.669 3978-3993/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-18 16:47:11.669 678-3821/? I/OMX-VDEC-1080P: Video slvp perflock acquired
12-18 16:47:11.670 678-3821/? I/OMX-VDEC-1080P: component_init: OMX.qcom.video.decoder.avc : fd=59
12-18 16:47:11.680 678-3821/? I/OMX-VDEC-1080P: omx_vdec::component_init() success : fd=59
12-18 16:47:11.682 18819-19793/com.wakeup.wakeup E/ExoPlayerImplInternal: Renderer error.
                                                                          com.google.android.exoplayer2.ExoPlaybackException
                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:418)
                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:405)
                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:839)
                                                                              at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:455)
                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:536)
                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                           Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [1920, 3414, -1.0], [-1, -1])
                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:405) 
                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:839) 
                                                                              at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:455) 
                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:536) 
                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560) 
                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                              at android.os.Looper.loop(Looper.java:154) 
                                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                           Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
                                                                              at android.media.MediaCodec.native_configure(Native Method)
                                                                              at android.media.MediaCodec.configure(MediaCodec.java:1778)
                                                                              at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:414)
                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:394)
                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:839) 
                                                                              at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:455) 
                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:536) 
                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560) 
                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                              at android.os.Looper.loop(Looper.java:154) 
                                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
12-18 16:47:11.683 678-2283/? I/OMX-VDEC-1080P: omx_vdec::component_deinit() complete
12-18 16:47:11.685 18819-18819/com.wakeup.wakeup E/EventLogger: playerFailed [1559.33]
                                                                com.google.android.exoplayer2.ExoPlaybackException
                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:418)
                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:405)
                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:839)
                                                                    at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:455)
                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:536)
                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                 Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [1920, 3414, -1.0], [-1, -1])
                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:405) 
                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:839) 
                                                                    at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:455) 
                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:536) 
                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560) 
                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                    at android.os.Looper.loop(Looper.java:154) 
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                 Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
                                                                    at android.media.MediaCodec.native_configure(Native Method)
                                                                    at android.media.MediaCodec.configure(MediaCodec.java:1778)
                                                                    at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:414)
                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:394)
                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:839) 
                                                                    at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:455) 
                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:536) 
                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560) 
                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                    at android.os.Looper.loop(Looper.java:154) 
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61) 
12-18 16:47:11.686 678-2283/? I/OMX-VDEC-1080P: Exit OMX vdec Destructor: fd=59
12-18 16:47:11.686 678-2283/? I/OMX-VDEC-1080P: Video slvp perflock released
12-18 16:47:11.688 18819-18819/com.wakeup.wakeup D/EventLogger: loading [false]
12-18 16:47:11.689 18819-18819/com.wakeup.wakeup D/EventLogger: state [1559.33, true, I]
12-18 16:47:12.343 688-781/? D/ThermalEngine: sensor_wait: case_therm Wait done.
12-18 16:47:12.345 688-781/? D/ThermalEngine: sensor_monitor: case_therm Reading 37000 .
12-18 16:47:12.345 688-781/? I/ThermalEngine: Sensor:case_therm:37000 mC
12-18 16:47:12.345 688-781/? D/ThermalEngine: update_active_thresh: case_therm Active(1), Hi(1) 42000, Lo(0) -2147483648, Interval(1) 1000
12-18 16:47:12.345 688-781/? D/ThermalEngine: sensor_monitor: case_therm Sensor wait.
12-18 16:47:12.345 688-781/? D/ThermalEngine: sensor_wait: case_therm Wait start. 1000ms
12-18 16:47:12.948 18516-18516/? D/StatusBar.NetworkController: onSignalStrengthsChanged received on slotId :1signalStrength=SignalStrength: 31 0 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 gsm|lte level=5 cdmdlevel=0 evdolevel=0
12-18 16:47:13.345 688-781/? D/ThermalEngine: sensor_wait: case_therm Wait done.
12-18 16:47:13.347 688-781/? D/ThermalEngine: sensor_monitor: case_therm Reading 37000 .
12-18 16:47:13.347 688-781/? I/ThermalEngine: Sensor:case_therm:37000 mC
12-18 16:47:13.347 688-781/? D/ThermalEngine: update_active_thresh: case_therm Active(1), Hi(1) 42000, Lo(0) -2147483648, Interval(1) 1000
12-18 16:47:13.347 688-781/? D/ThermalEngine: sensor_monitor: case_therm Sensor wait.
12-18 16:47:13
```

**Comment by andrewlewis** [comment]
As you've identified, it looks like the device just doesn't support decoding the format you're trying to play, so I'm afraid we can't really do anything about this. Perhaps you can transcode the input video to a lower resolution?
