### ISSUE TITLE
java.lang.IllegalStateException at android.media.MediaCodec.native_queueInputBuffer

### ISSUE THREAD

**Issue by olenev** [google/ExoPlayer#3623]
Faced with problem like in issues
https://github.com/google/ExoPlayer/issues/1997
https://github.com/google/ExoPlayer/issues/1383
https://github.com/google/ExoPlayer/issues/3032

This problem reproduces on some Samsung devices, for examples:
SM-J120H Android 5.1.1. API 22
SM-N910F API 23
SM-G950F API 24
SM-G955F API 24

Used links for mp4 video, and some videos not loads on these devices. Also tested videos on few Nexus, LG and Xiaomi devices and all works fine without any errors.
Gradle imports
```
implementation 'com.google.android.exoplayer:exoplayer-core:2.6.0'
implementation 'com.google.android.exoplayer:exoplayer-ui:2.6.0'
```
Player implementation like this:
```
ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
Context context = App.getApp();
        DataSource.Factory dataSourceFactory =  new DefaultDataSourceFactory(context, Util.getUserAgent(context, context.getString(R.string.app_name)))
BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory =
                new AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector =
                new DefaultTrackSelector(videoTrackSelectionFactory);
        RenderersFactory renderersFactory = new DefaultRenderersFactory(context);

        DefaultLoadControl loadControl = new DefaultLoadControl(
                new DefaultAllocator(false, C.DEFAULT_BUFFER_SEGMENT_SIZE),
               3000, getMaxBufferSize(), 3000, 3000);
SimpleExoPlayer player = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector, loadControl);
simpleExoPlayerView.setPlayer(player);
MediaSource source = new ExtractorMediaSource(Uri.parse(videoUrl),
                    dataSourceFactory, extractorsFactory, null, new ExtractorMediaSource.EventListener() {
                @Override
                public void onLoadError(IOException error) {
              /////////
                }
            });
player.prepare(source);
player.setPlayWhenReady(true);
```
simpleExoPlayerView is SimpleExoPlayerView from exoplayer-ui:2.6.0 
Stack trace

```
I/ACodec: [OMX.sprd.h264.decoder] Now Loaded
E/ACodec: [OMX.sprd.h264.decoder] storeMetaDataInBuffers failed w/ err -2147483648
W/ACodec: [OMX.sprd.h264.decoder] prepareForAdaptivePlayback failed w/ err -2147483648
I/ACodec: [OMX.sprd.h264.decoder] Now Loaded->Idle
I/ACodec: [OMX.sprd.h264.decoder] configureOutputBuffersFromNativeWindow setBufferCount : 9, minUndequeuedBuffers : 4
I/ACodec: [OMX.sprd.h264.decoder] Allocating 9 buffers from a native window of size 3133440 on output port
I/ACodec: [OMX.sprd.h264.decoder] Now Idle->Executing
I/ACodec: [OMX.sprd.h264.decoder] Now Executing
E/ACodec: [OMX.sprd.h264.decoder] ERROR(0x80001020)
E/ACodec: signalError(omxError 0x80001020, internalError -2147483648)
E/MediaCodec: Codec reported err 0x80001020, actionCode 0, while in state 6
E/ExoPlayerImplInternal: Internal runtime error.

 java.lang.IllegalStateException
        at android.media.MediaCodec.native_queueInputBuffer(Native Method)
        at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:831)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:743)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:553)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)

I/ACodec: [OMX.sprd.h264.decoder] Now Executing->Idle
E/Surface: getSlotFromBufferLocked: unknown buffer: 0x97daa100
W/ACodec: [OMX.sprd.h264.decoder] can not return buffer 0xb290a100 to native window
E/Surface: getSlotFromBufferLocked: unknown buffer: 0x97cfa3a0
W/ACodec: [OMX.sprd.h264.decoder] can not return buffer 0xb0d03a60 to native window
E/Surface: getSlotFromBufferLocked: unknown buffer: 0x97cfa940
W/ACodec: [OMX.sprd.h264.decoder] can not return buffer 0xb290a380 to native window
E/Surface: getSlotFromBufferLocked: unknown buffer: 0x97cfa460
W/ACodec: [OMX.sprd.h264.decoder] can not return buffer 0xb290ab50 to native window
E/Surface: getSlotFromBufferLocked: unknown buffer: 0x97cfa340
W/ACodec: [OMX.sprd.h264.decoder] can not return buffer 0xb290ace0 to native window
I/ACodec: [OMX.sprd.h264.decoder] Now Idle->Loaded
I/ACodec: [OMX.sprd.h264.decoder] Now Loaded
I/ACodec:  [OMX.sprd.h264.decoder] Now uninitialized
E/ExoPlayerImplInternal: Stop failed.

java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:628)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:497)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:424)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:451)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:326)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:150)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:865)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:790)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:362)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by andrewlewis** [comment]
Please could you provide a full bug report captured using `adb bugreport` just after seeing this error?

**Comment by olenev** [comment]
Attached file with logs
[exoplayer_illegular_exception.txt](https://github.com/google/ExoPlayer/files/1579265/exoplayer_illegular_exception.txt)

**Comment by andrewlewis** [comment]
It looks like 0x80001020 means the input format wasn't handled correctly. Please provide a link to the file you're trying to play and also send an actual bug report captured using `adb bugreport` (via email to dev.exoplayer@gmail.com if you don't want to post it here)?

**Comment by olenev** [comment]
@andrewlewis  try to load videos by links:
1. http://d24cq1nx03h9us.cloudfront.net/exercises/videos_720p/8766_1.mp4
2. http://d24cq1nx03h9us.cloudfront.net/exercises/videos_720p/8767_1.mp4
3. http://d24cq1nx03h9us.cloudfront.net/exercises/videos_720p/8768_1.mp4
4. http://d24cq1nx03h9us.cloudfront.net/exercises/videos_720p/8769_1.mp4
5. http://d24cq1nx03h9us.cloudfront.net/exercises/videos_720p/8774_2.mp4
Video by first link loads and plays, another videos are buffer, but not play. Exceptions and logs like described above.

**Comment by ojw28** [comment]
* Please provide full bug reports captured with `adb bugreport` via email or here, captured shortly after reproducing the issue. The logcat snippets provided are not sufficient for us to investigate the issue.
* Please provide a bug report for each individual device mentioned. It looks like the failure in the logcat snippet provided so far would only occur on devices with Spreadtrum chipsets, but as far as I've been able to establish from looking around online, only one of the four devices mentioned ships with one. So either the listed devices are inaccurate, or the other three fail in some other way.

Thanks!

**Comment by olenev** [comment]
@ojw28 here bug report from Samsung SM-J120H Android 5.1.1 API 22
[bugreport.txt](https://github.com/google/ExoPlayer/files/1585538/bugreport.txt)

**Comment by olenev** [comment]
Also found another issue today - Exoplayer crashes on Nexus 5 when in fragment call in onStop() method code  
 if (videoPlayer.getPlayWhenReady()) {
            videoPlayer.setPlayWhenReady(false);
        }  
I reproduce in such case: 
- turn off phone
- wait few secs
- turn on
- press play button
video just plays second and freeze with log 
```
stack trace similar but internal error differ `E/ACodec: signalError(omxError 0x80001001, internalError -19)`

```
E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
E/ACodec: queueBuffer failed in onOutputBufferDrained: -19
E/ACodec: signalError(omxError 0x80001001, internalError -19)
E/MediaCodec: Codec reported err 0xffffffed, actionCode 0, while in state 6
E/ExoPlayerImplInternal: Internal runtime error.

java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2007)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:497)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:424)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:451)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:326)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:150)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:865)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:790)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:362)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
W/IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
V/FA: Inactivity, disconnecting from the service
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2507)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:616)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:553)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by olenev** [comment]
@ojw28 , bug report from Nexus 5 related to issue when stop player 
[bugreportNexus.zip](https://github.com/google/ExoPlayer/files/1585611/bugreportNexus.zip)

**Comment by cfxmys** [comment]
i have the same issue   on API21 device, but on  API19 device is ok

**Comment by pals-ric** [comment]
even i am getting some issue like this 
https://stackoverflow.com/questions/50226250/java-lang-illegalstateexception-at-android-media-mediacodec-native-queueinputbuf?noredirect=1#comment87471939_50226250

**Comment by andrewlewis** [comment]
@olenev The bug report from the Samsung SM-J120H linked above doesn't appear to include the original error. Please could you reproduce the issue and take the bug report immediately afterwards?

For the Nexus 5 issue it looks like the surface used by one of the decoders is not valid. There are also multiple players active at the same time. Please make sure your app is handling the surface lifecycle properly (either via `SimpleExoPlayer` or in your own surface texture listener).

**Comment by andrewlewis** [comment]
Closing due to inactivity. If we need to investigate anything here further, please file a new issue and provide all the information requested in the issue template.
