### ISSUE TITLE
Support multi-track FMP4 and WebM playbacks

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#363]
Currently FMP4 and WebM playbacks are supported only in the context of demuxed DASH streams.

We're working on an extractor model that will allow the FMP4 and WebM extractors to be used in a standalone way, but for this to be useful, we need the extractors to support multiple tracks (i.e. audio+video in a single stream).

**Comment by ojw28** [comment]
This is done for WebM. Not yet done for FMP4.

**Comment by Oleur** [comment]
Any clues about the release date for the multi-track FMP4 playback support ? Thanks.

**Comment by elixiroflife4u** [comment]
The following video still gives an array of bounds 

http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4
This seems similar to issue #554 (but doesn't seem to be resolved by the patch put for it ). Since that  issue was closed, I am putting the comment here.

Stack trace below
<pre>
06-23 16:13:25.827   7133-23064/com.google.android.exoplayer.demo E/LoadTask﹕ Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
            at com.google.android.exoplayer.util.CodecSpecificDataUtil.parseAudioSpecificConfig(CodecSpecificDataUtil.java:53)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseAudioSampleEntry(AtomParsers.java:546)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:342)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:66)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:227)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:208)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:103)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:611)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
06-23 16:13:27.098   7133-23064/com.google.android.exoplayer.demo E/LoadTask﹕ Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
            at com.google.android.exoplayer.util.CodecSpecificDataUtil.parseAudioSpecificConfig(CodecSpecificDataUtil.java:53)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseAudioSampleEntry(AtomParsers.java:546)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:342)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:66)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:227)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:208)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:103)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:611)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
06-23 16:13:29.200    7133-7137/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_CONCURRENT freed 2717K, 47% free 5877K/10928K, paused 2ms+3ms, total 20ms
06-23 16:13:29.370   7133-23064/com.google.android.exoplayer.demo E/LoadTask﹕ Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
            at com.google.android.exoplayer.util.CodecSpecificDataUtil.parseAudioSpecificConfig(CodecSpecificDataUtil.java:53)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseAudioSampleEntry(AtomParsers.java:546)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:342)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:66)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:227)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:208)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:103)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:611)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
</pre>

**Comment by david2658** [comment]
Hi. Is there any plan to support multi-track fmp4? I have a DASH case containing the multi-track fmp4. The following url is that case, http://connectedplanet.tv/olvs/test/mpeg_dash/files/negative/playlist.mpd.
If you will fix this problem, please tell us. Thanks!

**Comment by ojw28** [comment]
Note - We have no plans to support mult-track FMP4 in the context of DASH. We provide support for standalone media only. For DASH we require that content is demuxed into separate streams.
