### ISSUE TITLE
help for file mkv to audio problem ac3

### ISSUE THREAD

**Issue by xoceunder** [google/ExoPlayer#3641]
this error

```
12-25 22:27:08.916 2092-3335/com.livetv.android E/ACodec: [OMX.ffmpeg.hevc.decoder] configureCodec returning error -1010
12-25 22:27:08.916 2092-3334/com.livetv.android E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -1010)
12-25 22:27:08.916 2092-3330/com.livetv.android E/ExoPlayerImplInternal: Renderer error.
                                                                         com.google.android.exoplayer2.ExoPlaybackException
                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:371)
                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:359)
                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:754)
                                                                             at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:325)
                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:496)
                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:479)
                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                             at android.os.Looper.loop(Looper.java:136)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                             at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                          Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.ffmpeg.hevc.decoder, Format(1, null, video/hevc, -1, , null, [3840, 1600, -1.0], [-1, -1])
                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:359) 
                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:754) 
                                                                             at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:325) 
                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:496) 
                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:479) 
                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                             at android.os.Looper.loop(Looper.java:136) 
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                             at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                                          Caused by: java.lang.IllegalStateException
                                                                             at android.media.MediaCodec.native_configure(Native Method)
                                                                             at android.media.MediaCodec.configure(MediaCodec.java:262)
                                                                             at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:314)
                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:348)
                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:754) 
                                                                             at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:325) 
                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:496) 
                                                                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:479) 
                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                             at android.os.Looper.loop(Looper.java:136) 
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                             at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

**Comment by xoceunder** [comment]
![screenshot_12](https://user-images.githubusercontent.com/12431116/34388303-4061d6c2-eb09-11e7-9d20-582cc00aa0b3.png)

**Comment by erdemguven** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by ojw28** [comment]
Closing due to lack of information.
