### ISSUE TITLE
ExoPlayer unable to use surface passed via AIDL.

### ISSUE THREAD

**Issue by digitalix** [google/ExoPlayer#3649]
### Issue description
ExoPlayer is unable to use the surface passed between processes. I did some tests and I found out that surface is invalid if used in a different thread than the surface object was passed. Is there any way to force ExoPlayer to render using the thread which called prepare?

### Reproduction steps
The easiest way to reproduce it is to create two projects app and service. Service should export AIDL interface which accepts Surface object then once the object is in service app the object should be passed to ExoPlayer and then there will be an exception as below.

```
E/ExoPlayerImplInternal: Renderer error.
        com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:418)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:405)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:839)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:455)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:251)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [854, 480, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:405) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:839) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:455) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:251) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
        Caused by: java.lang.IllegalArgumentException: The surface has been released
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1940)
        at android.media.MediaCodec.configure(MediaCodec.java:1869)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:414)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:394)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:839) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:455) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:251) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

### Link to test content
Any video file will reproduce it.

### Version of ExoPlayer being used
2.6.0

### Device(s) and version(s) of Android being used
Device: Sony Xperia XZ1
Android Version: 8.0.0

**Comment by ojw28** [comment]
Is this specific to the XZ1 or some subset of devices, or does it happen on all devices?

> I did some tests and I found out that surface is invalid if used in a different thread than the surface object was passed.

What does "was passed" mean in this sentence (i.e. what specific method call are you referring to)? 

Intuitively it feels unlikely to me that this is true. The error strongly implies the surface really has been released, as opposed to it just being accessed on the wrong thread, in which case the correct fix should be working out why the surface is released and preventing that from happening (or if it was released for a good reason, working out why the player still has access to it after this occurs).

> Is there any way to force ExoPlayer to render using the thread which called prepare?

No, but as above I don't think this is the right solution anyway.

> The easiest way to reproduce it is to create two projects app and service. Service should export AIDL interface which accepts Surface object then once the object is in service app the object should be passed to ExoPlayer and then there will be an exception as below.

We're far more likely to investigate this in a timely manner if a minimal sample is provided (e.g. as a project on GitHub, or as source code by email). It a fairly non-trivial investment for us to build our own two project sample to try and reproduce, with no guarantee we'll even manage to reproduce once we've done so. Would you be able to provide one?

Thanks!

**Comment by digitalix** [comment]
Thanks for the reply!
By "was passed" I mean I've made a method using AIDL "setSurface(Surface surface)" once my app is connected to the service which runs in the different process my app calls this method and the implementation on the service side calls "setVideoSurface()" which results in the error. 

Also, it happens on Sony Xperia Z5 (Android 7.1) as well.

In the past few days, I've found a walk-around by creating another AIDL interface which would be set by the app and then the service would use that to request a surface from the app. As I said previously for some reason surface object is valid only in the thread which got the surface so I used "exoplayer.getPlaybackLooper()" so it requests the surface via the thread that is used by Exoplayer and it works! It's not the perfect solution as it leads to deadlocks in some cases but at least it works.

I'll try to create a sample app this week.

**Comment by digitalix** [comment]
I tried to create the sample app but I was no longer able to reproduce it. Then I tested it again on my app and it works there as well. Now I think that I maybe the surface was recreated or something in meantime but I need to do more testing.

Looks like it was my fault, I'll try to do some more testing to find out what is going.

Please leave it open for a few days more in case if it wasn't my fault.
