### ISSUE TITLE
MultiExoPlayer in Recyclerview Bug

### ISSUE THREAD

**Issue by xiaoyepadzhang** [google/ExoPlayer#3668]
Hi, I want to report to you a bug that trouble me a lot of time.

**Issue description**
1. We had made a multi EXOPlayer in vertical list view by recyclerview，each view container a EXOPlayer instance and play the one which is center in the view display, and other EXOPlayer attach in the view will be release.  They are all m3u8(use HLSMediaSource), But we found that its probability when I start to play a video , it suddenly can not play and throw the exception,  and after that **all the player** can not play with the same exception, every EXOPlayer is been 'dead', they are not the same url. 
2. By the way about this bug ,  i often  play the same video(same url)  in other pager, such as i play url A in list view, and i go another view to play url A and pause the previous player with url A.
3. And if I finish the application  and restart the app, it will be everything ok .  but i think this is a bad experience.  can you provide me some useful information about this bug?
4. I give two log type below ,  every log have no relevance, they occur at different devices, but when the EXOPlayer is 'dead', they will throw the same exception, such as one of these exception.

Thanks!

**Log**
**1.**
`E/AudioFlinger: no more track names available
01-03 15:39:15.280 658-1601/? E/AudioFlinger: createTrack_l() initCheck failed -12; no control block?
01-03 15:39:15.281 445-1665/? I/gralloc: alloc_device_free:586: Free handle(0x7150032800)
01-03 15:39:15.282 20139-27532/? E/AudioTrack: AudioFlinger could not create track, status: -12
01-03 15:39:15.282 20139-27532/? E/AudioTrack-JNI: Error -12 initializing AudioTrack
01-03 15:39:15.282 20139-27532/? E/android.media.AudioTrack: Error code -20 when initializing AudioTrack.
01-03 15:39:15.283 20139-27532/? E/ExoPlayerImplInternal: Renderer error.
                                                          com.google.android.exoplayer2.h
                                                              at com.google.android.exoplayer2.a.l.a(MediaCodecAudioRenderer.java:427)
                                                              at com.google.android.exoplayer2.e.b.b(MediaCodecRenderer.java:998)
                                                              at com.google.android.exoplayer2.e.b.a(MediaCodecRenderer.java:552)
                                                              at com.google.android.exoplayer2.l.i(ExoPlayerImplInternal.java:560)
                                                              at com.google.android.exoplayer2.l.handleMessage(ExoPlayerImplInternal.java:306)
                                                              at android.os.Handler.dispatchMessage(Handler.java:101)
                                                              at android.os.Looper.loop(Looper.java:156)
                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                           Caused by: com.google.android.exoplayer2.a.h$b: AudioTrack init failed: 0, Config(44100, 12, 44100)
                                                              at com.google.android.exoplayer2.a.j.x(DefaultAudioSink.java:1179)
                                                              at com.google.android.exoplayer2.a.j.l(DefaultAudioSink.java:489)
                                                              at com.google.android.exoplayer2.a.j.a(DefaultAudioSink.java:539)
                                                              at com.google.android.exoplayer2.a.l.a(MediaCodecAudioRenderer.java:421)
                                                              at com.google.android.exoplayer2.e.b.b(MediaCodecRenderer.java:998) 
                                                              at com.google.android.exoplayer2.e.b.a(MediaCodecRenderer.java:552) 
                                                              at com.google.android.exoplayer2.l.i(ExoPlayerImplInternal.java:560) 
                                                              at com.google.android.exoplayer2.l.handleMessage(ExoPlayerImplInternal.java:306) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:101) 
                                                              at android.os.Looper.loop(Looper.java:156) 
                                                              at android.os.HandlerThread.run(HandlerThread.java:61) `

**2.**
`01-03 17:10:28.285 21770-23450/? E/ACodec: found 1 codecs
01-03 17:10:28.288 21770-23450/? E/ACodec: codec OMX.google.aac.decoder selected
01-03 17:10:28.301 607-21734/? E/IMemory: binder=0xf48c0a00 transaction failed fd=-2147483647, size=0, err=-2147483646 (Unknown error 2147483646)
01-03 17:10:28.301 607-21734/? E/IMemory: cannot dup fd=-2147483647, size=0, err=-2147483646 (Bad file descriptor)
01-03 17:10:28.301 607-21734/? E/IMemory: cannot map BpMemoryHeap (binder=0xf48c0a00), size=0, fd=-1 (Bad file descriptor)
01-03 17:10:28.302 21770-23450/? E/ACodec: Failed to allocate buffers after transitioning to IDLE state (error 0xffffffea)
01-03 17:10:28.302 21770-23450/? E/ACodec: signalError(omxError 0x80001001, internalError -22)
01-03 17:10:28.302 607-21737/? E/OMXNodeInstance: b/25884056
01-03 17:10:28.302 21770-23450/? E/MediaCodec: Codec reported err 0xffffffea, actionCode 0, while in state 5
01-03 17:10:28.304 21770-23440/? E/ExoPlayerImplInternal: Renderer error.
                                                          com.google.android.exoplayer2.h
                                                              at com.google.android.exoplayer2.e.b.a(MediaCodecRenderer.java:418)
                                                              at com.google.android.exoplayer2.e.b.x(MediaCodecRenderer.java:405)
                                                              at com.google.android.exoplayer2.e.b.b(MediaCodecRenderer.java:839)
                                                              at com.google.android.exoplayer2.a.l.b(MediaCodecAudioRenderer.java:261)
                                                              at com.google.android.exoplayer2.e.b.a(MediaCodecRenderer.java:536)
                                                              at com.google.android.exoplayer2.l.i(ExoPlayerImplInternal.java:560)
                                                              at com.google.android.exoplayer2.l.handleMessage(ExoPlayerImplInternal.java:306)
                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                              at android.os.Looper.loop(Looper.java:159)
                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                           Caused by: com.google.android.exoplayer2.e.b$a: Decoder init failed: OMX.google.aac.decoder, Format(1/15, null, audio/mp4a-latm, -1, und, [-1, -1, -1.0], [2, 44100])
                                                              at com.google.android.exoplayer2.e.b.x(MediaCodecRenderer.java:405) 
                                                              at com.google.android.exoplayer2.e.b.b(MediaCodecRenderer.java:839) 
                                                              at com.google.android.exoplayer2.a.l.b(MediaCodecAudioRenderer.java:261) 
                                                              at com.google.android.exoplayer2.e.b.a(MediaCodecRenderer.java:536) 
                                                              at com.google.android.exoplayer2.l.i(ExoPlayerImplInternal.java:560) 
                                                              at com.google.android.exoplayer2.l.handleMessage(ExoPlayerImplInternal.java:306) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                              at android.os.Looper.loop(Looper.java:159) 
                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                           Caused by: java.lang.IllegalArgumentException: start failed
                                                              at android.media.MediaCodec.native_start(Native Method)
                                                              at android.media.MediaCodec.start(MediaCodec.java:1991)
                                                              at com.google.android.exoplayer2.e.b.x(MediaCodecRenderer.java:397)
                                                              at com.google.android.exoplayer2.e.b.b(MediaCodecRenderer.java:839) 
                                                              at com.google.android.exoplayer2.a.l.b(MediaCodecAudioRenderer.java:261) 
                                                              at com.google.android.exoplayer2.e.b.a(MediaCodecRenderer.java:536) 
                                                              at com.google.android.exoplayer2.l.i(ExoPlayerImplInternal.java:560) 
                                                              at com.google.android.exoplayer2.l.handleMessage(ExoPlayerImplInternal.java:306) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                              at android.os.Looper.loop(Looper.java:159) 
                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
01-03 17:10:28.305 21770-21770/? E/ExoVideoView: null onPlayerError: com.google.android.exoplayer2.h
01-03 17:10:28.340 21770-23440/? E/ExoPlayerImplInternal: Stop failed.
                                                          java.lang.IllegalStateException
                                                              at android.media.MediaCodec.native_stop(Native Method)
                                                              at android.media.MediaCodec.stop(MediaCodec.java:2007)
                                                              at com.google.android.exoplayer2.e.b.A(MediaCodecRenderer.java:497)
                                                              at com.google.android.exoplayer2.e.b.p(MediaCodecRenderer.java:451)
                                                              at com.google.android.exoplayer2.a.l.p(MediaCodecAudioRenderer.java:364)
                                                              at com.google.android.exoplayer2.a.l(BaseRenderer.java:150)
                                                              at com.google.android.exoplayer2.l.b(ExoPlayerImplInternal.java:865)
                                                              at com.google.android.exoplayer2.l.f(ExoPlayerImplInternal.java:813)
                                                              at com.google.android.exoplayer2.l.j(ExoPlayerImplInternal.java:790)
                                                              at com.google.android.exoplayer2.l.handleMessage(ExoPlayerImplInternal.java:351)
                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                              at android.os.Looper.loop(Looper.java:159)
                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
01-03 17:10:28.341 21770-21770/? E/ExoVideoView: notifyStatus: 6
01-03 17:10:29.075 21770-21770/? E/ItemView: onDetachedFromWindow: `

**Comment by xiaoyepadzhang** [comment]
Version of ExoPlayer
2.6.0

**Comment by xiaoyepadzhang** [comment]
@andrewlewis  sorry i forget to assign you ...

**Comment by andrewlewis** [comment]
Please could you provide a full bug report captured just after reproducing the error using `adb bug report`?

**Comment by tonihei** [comment]
"no more track names available" sounds as if the audio decoder has too many AudioTracks at the same time and then transitions to an error state letting all the other players using the same decoder fail as well. 

Do you call player.release() on all the players you don't use?

@andrewlewis Any idea what might cause that?

**Comment by andrewlewis** [comment]
Yes, it sounds like players are not being released correctly. The bug report will let us verify that there are too many `AudioTrack`s by looking at the service dump for the audio flinger (each one consumes from shared memory, and when this runs out it's not possible to create another `AudioTrack`).

**Comment by xiaoyepadzhang** [comment]
i store this two logs with AS Logcat few days ago  @andrewlewis 
[log2.txt](https://github.com/google/ExoPlayer/files/1606189/log2.txt)
[log1.txt](https://github.com/google/ExoPlayer/files/1606190/log1.txt)

**Comment by andrewlewis** [comment]
The output of `adb bugreport` contains more information just logcat, but if you can't provide that `adb shell dumpsys media.audio_flinger` would also let us confirm that `AudioTrack`s are leaking.

In `log2.txt` a `MediaCodec` is failing to start which is a further indication that players are not being released correctly. Please could you check how you're managing the lifecycle of the players? As a first step to fixing the issue, you could try ensure that only one unreleased `ExoPlayer` instance exists at a time.

**Comment by xiaoyepadzhang** [comment]
ok, i will In-depth check about the leaking. And if still has the question , i will send bug report to you.
Thanks a lot.

**Comment by xiaoyepadzhang** [comment]
[bugreport-HUAWEIFRD-AL10-2018-01-08-16-49-16.zip](https://github.com/google/ExoPlayer/files/1610990/bugreport-HUAWEIFRD-AL10-2018-01-08-16-49-16.zip)
@andrewlewis Hi
After I resolved a leak, And I still found the exception appeared, just few minutes ago, and I had pull the bugReport this time, can you help me to analysis this report?

**Device Brand**
HUAWEI Honor 8

**Device Version**
Android 7.0&EMUI 5.0.1

**Comment by andrewlewis** [comment]
Are you sure the leak is fixed? Looking at the bug report it appears there are 14 inactive AudioTracks and 15 ExoPlayer playback threads associated with your process.

**Comment by xiaoyepadzhang** [comment]
@andrewlewis If i had called player.release() but the textureView or other parent view is Leaking,  it will also make to this leaking?

**Comment by xiaoyepadzhang** [comment]
@andrewlewis  I had solved the leaking. you can close this issue now, Thanks a lot!
