### ISSUE TITLE
ExoPlayer Decoder failed on Android Version 5.1

### ISSUE THREAD

**Issue by kuldiep** [google/ExoPlayer#3686]
### Issue description
exo player is throwing exceptions and gives error code Error 0xfffffc0e while streaming video on my Moto E2 phone which has android version 5.1, Kernel version 3.4.42 and  Build number LPCS23. 13-56-5. also could not find documentation on the above error code.  

### Reproduction steps
initialize player with given url (i will send you video URL in email)
try with Motorola e2 with version 5.1
player will directly call onPlayerError() with following Exceptions in logcat

### Version of ExoPlayer being used
2.5.1

### Device(s) and version(s) of Android being used
Motorola E2, and version is 5.1

### A full bug report captured from the device

```
 onPlayerError: Error cause
                                                                 com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [1920, 1080, -1.0], [-1, -1])
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:382)
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814)
                                                                     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:432)
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513)
                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:564)
                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                  Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
                                                                     at android.media.MediaCodec.native_configure(Native Method)
                                                                     at android.media.MediaCodec.configure(MediaCodec.java:584)
                                                                     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:403)
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:371)
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814) 
                                                                     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:432) 
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513) 
                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:564) 
                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) 
01-09 13:44:59.699 27958-27958/com.lxltech.sc.participant D/LOG: onPlayerError: exception 
                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:395)
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:382)
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814)
                                                                     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:432)
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513)
                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:564)
                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                  Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [1920, 1080, -1.0], [-1, -1])
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:382) 
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814) 
                                                                     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:432) 
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513) 
                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:564) 
                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                  Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
                                                                     at android.media.MediaCodec.native_configure(Native Method)
                                                                     at android.media.MediaCodec.configure(MediaCodec.java:584)
                                                                     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:403)
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:371)
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814) 
                                                                     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:432) 
                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513) 
                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:564) 
                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) 
01-09 13:44:59.699 27958-27958/com.lxltech.sc.participant D/LOG: onPlayerError: exception type 1
```

**Comment by kuldiep** [comment]
@ojw28 is it device specific issue or anything else ..i am confused? any solution for this?

**Comment by ojw28** [comment]
It looks device specific, but i's hard to say without being provided with any content that reproduces the issue, as requested in the issue template. Please provide some so that we can reproduce the issue in our demo app.

**Comment by kuldiep** [comment]
@ojw28 i have updated issue with Reproduction steps...and will send URL in mail asap.

**Comment by kuldiep** [comment]
@ojw28 i have sent url in mail id given in template, please check it.

**Comment by ojw28** [comment]
It's probably just that this device is unable to play 1080p video (I'd expect playback of 720p video to succeed on this device). You can validate this theory by trying playback on the device using our demo app, and looking for the following in the logs:
```
supported=NO_EXCEEDS_CAPABILITIES
```
This indicates that the device is not capable of playing the stream, although we try anyway because some devices under report their true capabilities. If the stream really cant be played, a failure will occur such as the one above.
