### ISSUE TITLE
Decoder init failed with TextureView and DASH/Widevine

### ISSUE THREAD

**Issue by brillenheini** [google/ExoPlayer#370]
Using DASH with Widevine and a TextureView results in this error on some devices:

`com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc.secure, MediaFormat(video/avc, -1, 640, 360, 1.0, -1, -1, -1, 1920, 1080)`

The error can be reproduces with the "WIDEVINE GTS DASH" videos in the demo application on these devices:
Nexus 6 (Android 5.1)
Samsung Galaxy S4 (Android 4.4.2)

A modified version of the demo application for easier testing:
https://github.com/brillenheini/ExoPlayer/tree/TextureView

Full log:
```
03-26 10:45:09.116    5996-5996/com.google.android.exoplayer.demo I/ExoPlayerImpl﹕ Init 1.2.3
03-26 10:45:09.122    5996-5996/com.google.android.exoplayer.demo D/EventLogger﹕ start [0]
03-26 10:45:09.124    5996-5996/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, false, P]
03-26 10:45:09.129    5996-5996/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.01, true, P]
03-26 10:45:09.225    5996-6015/com.google.android.exoplayer.demo D/OpenGLRenderer﹕ endAllStagingAnimators on 0xb49b4880 (ListView) with handle 0xa0869430
03-26 10:45:09.774    5996-5996/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.65, false, I]
03-26 10:45:09.774    5996-5996/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.65, true, I]
03-26 10:45:09.786    5996-5996/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.66, true, P]
03-26 10:45:09.788    5996-5996/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.67, true, B]
03-26 10:45:09.953    5996-5996/com.google.android.exoplayer.demo D/EventLogger﹕ bandwidth [0.83, 1817, 0.00, 7268000]
03-26 10:45:09.958    5996-5996/com.google.android.exoplayer.demo D/EventLogger﹕ videoFormat [0.84, 143, 0]
03-26 10:45:10.204    5996-5996/com.google.android.exoplayer.demo D/EventLogger﹕ bandwidth [1.08, 97427, 0.08, 9622419]
03-26 10:45:10.323    5996-5996/com.google.android.exoplayer.demo D/EventLogger﹕ bandwidth [1.20, 373295, 0.12, 24886332]
03-26 10:45:10.492    5996-6063/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
03-26 10:45:10.820    5996-6063/com.google.android.exoplayer.demo E/ACodec﹕ native window could not be authenticated
03-26 10:45:10.820    5996-6063/com.google.android.exoplayer.demo E/ACodec﹕ Failed to allocate buffers after transitioning to IDLE state (error 0xffffffff)
03-26 10:45:10.820    5996-6063/com.google.android.exoplayer.demo E/ACodec﹕ signalError(omxError 0x80001001, internalError -1)
03-26 10:45:10.820    5996-6062/com.google.android.exoplayer.demo E/MediaCodec﹕ Codec reported err 0xffffffff, actionCode 0, while in state 5
03-26 10:45:10.822    5996-5996/com.google.android.exoplayer.demo E/EventLogger﹕ internalError [1.70, decoderInitializationError]
    com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc.secure, MediaFormat(video/avc, -1, 640, 360, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:322)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:660)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:462)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:442)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: android.media.MediaCodec$CodecException: start failed
            at android.media.MediaCodec.native_start(Native Method)
            at android.media.MediaCodec.start(MediaCodec.java:612)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:318)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:660)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:462)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:442)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
03-26 10:45:10.822    5996-6048/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc.secure, MediaFormat(video/avc, -1, 640, 360, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:335)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:322)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:660)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:462)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:442)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc.secure, MediaFormat(video/avc, -1, 640, 360, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:322)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:660)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:462)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:442)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: android.media.MediaCodec$CodecException: start failed
            at android.media.MediaCodec.native_start(Native Method)
            at android.media.MediaCodec.start(MediaCodec.java:612)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:318)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:660)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:462)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:442)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
03-26 10:45:10.831    5996-5996/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [1.71]
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc.secure, MediaFormat(video/avc, -1, 640, 360, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:335)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:322)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:660)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:462)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:442)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc.secure, MediaFormat(video/avc, -1, 640, 360, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:322)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:660)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:462)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:442)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: android.media.MediaCodec$CodecException: start failed
            at android.media.MediaCodec.native_start(Native Method)
            at android.media.MediaCodec.start(MediaCodec.java:612)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:318)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:660)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:462)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:442)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
03-26 10:45:10.865    5996-6048/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Stop failed.
    java.lang.IllegalStateException
            at android.media.MediaCodec.native_stop(Native Method)
            at android.media.MediaCodec.stop(MediaCodec.java:628)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.releaseCodec(MediaCodecTrackRenderer.java:381)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onDisabled(MediaCodecTrackRenderer.java:355)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onDisabled(MediaCodecVideoTrackRenderer.java:325)
            at com.google.android.exoplayer.TrackRenderer.disable(TrackRenderer.java:212)
            at com.google.android.exoplayer.ExoPlayerImplInternal.stopAndDisable(ExoPlayerImplInternal.java:512)
            at com.google.android.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:499)
            at com.google.android.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:479)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:232)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
03-26 10:45:10.906    5996-5996/com.google.android.exoplayer.demo D/EventLogger﹕ state [1.78, true, I]
```

**Comment by ojw28** [comment]
This is working as intended. For DRM protected content where the license requires that the secure video path be used, rendering to a TextureView isn't possible (because it's not secure).

**Comment by brillenheini** [comment]
But it is working on some devices, Nexus 7 with Android 5.1 for example.

**Comment by ojw28** [comment]
Do the two "secure video path" videos work on your Nexus 7 in that way? Or are you talking about some of the other WV GTS samples? Which videos exactly are you referring to?

**Comment by brillenheini** [comment]
On the Nexus 6, none of the Widevine GTS DASH samples are starting. They are all resulting in the above error.

Nexus 7 (the old one):
WV: HDCP not specified - working
WV: HDCP not required - working
WV: HDCP required - fails
WV: Secure video path required - fails
WV: HDCP + secure video path required - fails

The failing videos are playing for about 9 seconds and then stopping with a different error:
```
03-26 12:37:16.010  15693-16462/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: android.media.MediaCodec$CryptoException: Error decrypting data.
            at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:609)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:450)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: android.media.MediaCodec$CryptoException: Error decrypting data.
            at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
            at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:956)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:601)
```

**Comment by ojw28** [comment]
It's possible that the other devices could be a little more permissive where the license doesn't require HDCP or secure video path, but it's definitely WAI that playback to a TextureView fails in the secure video path cases.

I can follow up internally, but in practice, you should just always use SurfaceView if you're using drm.

**Comment by brillenheini** [comment]
Thanks.
