### ISSUE TITLE
Cannot seek full buffered MP4 video on using new Mp4SampleExtractor

### ISSUE THREAD

**Issue by vipulpurohit** [google/ExoPlayer#371]
Hello
We are facing some issues with new Mp4SampleExtractor. We are trying to play a MP4 video via HTTP link. All went well till we play full video once but after closing video player when we replay video again (buffer is 100% now) and try to seek video it get stuck and throw this error :

```
03-27 17:05:49.561  13323-14270/E/ExoPlayerImplInternal﹕ Internal runtime error.
    java.lang.IllegalArgumentException: Top bit not zero: -343067581
            at com.google.android.exoplayer.mp4.Mp4Util.readUnsignedIntToInt(Mp4Util.java:73)
            at com.google.android.exoplayer.mp4.Mp4Util.replaceLengthPrefixesWithAvcStartCodes(Mp4Util.java:87)
            at com.google.android.exoplayer.source.Mp4SampleExtractor.readSample(Mp4SampleExtractor.java:398)
            at com.google.android.exoplayer.source.DefaultSampleSource.readData(DefaultSampleSource.java:135)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:530)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:447)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
03-27 17:05:49.581  13323-13323/ E/EventLogger﹕ playerFailed [4.12]
    com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalArgumentException: Top bit not zero: -343067581
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:236)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.lang.IllegalArgumentException: Top bit not zero: -343067581
            at com.google.android.exoplayer.mp4.Mp4Util.readUnsignedIntToInt(Mp4Util.java:73)
            at com.google.android.exoplayer.mp4.Mp4Util.replaceLengthPrefixesWithAvcStartCodes(Mp4Util.java:87)
            at com.google.android.exoplayer.source.Mp4SampleExtractor.readSample(Mp4SampleExtractor.java:398)
            at com.google.android.exoplayer.source.DefaultSampleSource.readData(DefaultSampleSource.java:135)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:530)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:447)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by ojw28** [comment]
We'll be pushing a fairly major revision of the new MP4 stuff fairly soon. Note that this is still work in progress, so use it at your own risk ;)!

**Comment by ojw28** [comment]
We've rewritten much of this code, so I'm going to mark this as fixed. If it still occurs on latest dev, please re-open (with new stack trace logs, since all of the line numbers will have changed).

**Comment by dmota-systango** [comment]
You can use LoopingMediaSource as source instead.

MediaSource source = new ExtractorMediaSource(videoUri, ...);
// Loops the video indefinitely.
LoopingMediaSource loopingSource = new LoopingMediaSource(source);

Ref: https://google.github.io/ExoPlayer/guide.html#seamlessly-looping-a-video
