### ISSUE TITLE
IMA extension should specify required proguard rules

### ISSUE THREAD

**Issue by tonnyavery** [google/ExoPlayer#3723]
Any proguard settings available for ExoPlayer?

Building with minifyEnabled: true
When starting the player, get exception:

```
 java.lang.AssertionError: java.lang.NoSuchFieldException: adBreakEnded
                                                     at com.google.obf.fm$a.<init>(SourceFile:17)
                                                     at com.google.obf.fm$17.a(SourceFile:7)
                                                     at com.google.obf.dq.a(SourceFile:99)
                                                     at com.google.obf.fl.write(SourceFile:10)
                                                     at com.google.obf.ff$a.a(SourceFile:41)
                                                     at com.google.obf.ff$a.write(SourceFile:84)
                                                     at com.google.obf.dq.a(SourceFile:144)
                                                     at com.google.obf.dq.a(SourceFile:132)
                                                     at com.google.obf.dq.a(SourceFile:129)
                                                     at com.google.obf.dq.a(SourceFile:127)
                                                     at com.google.obf.gs.e(SourceFile:29)
                                                     at com.google.obf.gu.a(SourceFile:19)
                                                     at com.google.obf.gt.d(SourceFile:276)
                                                     at com.google.obf.gt.b(SourceFile:273)
                                                     at com.google.obf.gt.a(SourceFile:90)
                                                     at com.google.obf.gt.a(SourceFile:65)
                                                     at com.google.obf.gt.a(SourceFile:53)
                                                     at com.google.obf.gu.b(SourceFile:39)
                                                     at com.google.obf.gu$1.shouldOverrideUrlLoading(SourceFile:4)
                                                     at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
                                                     at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:72)
                                                     at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:15)
                                                     at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:157)
                                                     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:7)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                  Caused by: java.lang.NoSuchFieldException: adBreakEnded
                                                     at java.lang.Class.getField(Class.java:1549)
                                                     at com.google.obf.fm$a.<init>(SourceFile:6)
```

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by tonnyavery** [comment]
### Issue description
With proguard enabled, application crashes on player start
```
java.lang.AssertionError: java.lang.NoSuchFieldException: adBreakEnded
                                                     at com.google.obf.fm$a.<init>(SourceFile:17)
                                                     at com.google.obf.fm$17.a(SourceFile:7)
                                                     at com.google.obf.dq.a(SourceFile:99)
                                                     at com.google.obf.fl.write(SourceFile:10)
                                                     at com.google.obf.ff$a.a(SourceFile:41)
                                                     at com.google.obf.ff$a.write(SourceFile:84)
                                                     at com.google.obf.dq.a(SourceFile:144)
                                                     at com.google.obf.dq.a(SourceFile:132)
                                                     at com.google.obf.dq.a(SourceFile:129)
                                                     at com.google.obf.dq.a(SourceFile:127)
                                                     at com.google.obf.gs.e(SourceFile:29)
                                                     at com.google.obf.gu.a(SourceFile:19)
                                                     at com.google.obf.gt.d(SourceFile:276)
                                                     at com.google.obf.gt.b(SourceFile:273)
                                                     at com.google.obf.gt.a(SourceFile:90)
                                                     at com.google.obf.gt.a(SourceFile:65)
                                                     at com.google.obf.gt.a(SourceFile:53)
                                                     at com.google.obf.gu.b(SourceFile:39)
                                                     at com.google.obf.gu$1.shouldOverrideUrlLoading(SourceFile:4)
                                                     at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
                                                     at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:72)
                                                     at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:15)
                                                     at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:157)
                                                     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:7)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                  Caused by: java.lang.NoSuchFieldException: adBreakEnded
                                                     at java.lang.Class.getField(Class.java:1549)
                                                     at com.google.obf.fm$a.<init>(SourceFile:6)
```

### Reproduction steps
Enable proguard on app with ExoPlayer

### Link to test content
Provide a link to media that reproduces the issue. If you don't wish to post it
publicly, please submit the issue, then email the link to
dev.exoplayer@gmail.com including the issue number in the subject line.

### Version of ExoPlayer being used
2.6.0

### Device(s) and version(s) of Android being used
Samsung S8, Nexus 6p

### A full bug report captured from the device
Sent to email

**Comment by tonnyavery** [comment]
This was related to IMA extension.
Seems that exoplayer ima extension doesn't include proguard configuration. Adding these rules solved the problem so far:
https://groups.google.com/forum/#!topic/ima-sdk/uU-Oidq4mPg

**Comment by ojw28** [comment]
I think IMA should be distributed as an aar that includes the proguard rules it needs. App developers should ideally not have to specify the rules in their own proguard file.

Until that happens, we can probably add the rules into our IMA extension aar, which would at least solve the problem for app developers depending on IMA via our extension (provided we remember to update the rules then updating to a newer version of IMA).

**Comment by ojw28** [comment]
We've added the proguard config to ExoPlayer's IMA extension module. For some reason I was unable to reproduce the actual problem, and so was unable to verify that doing this removes the need for applications to add the proguard config themselves. Hopefully this is the case though!
