### ISSUE TITLE
"Unable to connect to rawresource," i can't load subtitles

### ISSUE THREAD

**Issue by gersard** [google/ExoPlayer#3767]
### Issue description
I can´t load subtitles from raw folder (.srt and .vtt). i tried 2 options to load the subtitles files

### Reproduction steps
I have a simple video player that load a video without problems. But when i try to load a subtitles from raw resource i got the catch excepcion described below.

The code:

#### Option 1 
 ```
Uri uriSubs = RawResourceDataSource.buildRawResourceUri(R.raw.sub2);
DefaultDataSourceFactory fac = new DefaultDataSourceFactory(this, Util.getUserAgent(this,"Santiago Indígena"));
MediaSource subSource = new 
Format subtitleFormat = Format.createTextSampleFormat(
               "0", // An identifier for the track. May be null.
               MimeTypes.APPLICATION_SUBRIP, // The mime type. Must be set correctly.
               Format.NO_VALUE, // Selection flags for the track.
               "es");
SingleSampleMediaSource.Factory(fac).createMediaSource(uriSubs,subtitleFormat, C.TIME_UNSET);
 ```
#### Option 2

 ```
Uri uriSubs = RawResourceDataSource.buildRawResourceUri(R.raw.sub2);
DataSpec dataSpecSub = new DataSpec(uriSubs);
final RawResourceDataSource subDataSource = new RawResourceDataSource(this);


        try {
            subDataSource.open(dataSpecSub);
        } catch (RawResourceDataSource.RawResourceDataSourceException e) {
            e.printStackTrace();
        }

  DataSource.Factory subFactory = new DataSource.Factory() {
            @Override
            public DataSource createDataSource() {
                return subDataSource;
            }
        };

  Format subtitleFormat = Format.createTextSampleFormat(
                "0", // An identifier for the track. May be null.
                MimeTypes.APPLICATION_SUBRIP, // The mime type. Must be set correctly.
                Format.NO_VALUE, // Selection flags for the track.
                "es");

MediaSource subSource = new SingleSampleMediaSource.Factory(subFactory).createMediaSource(uriSubs,subtitleFormat, C.TIME_UNSET);
```
### Version of ExoPlayer being used
2.6.1

### Device(s) and version(s) of Android being used
Android 6.0

### Exception from option 1

com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to rawresource:///2131558400
    at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
    at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:141)
    at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SourceLoadable.load(SingleSampleMediaPeriod.java:318)
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
 Caused by: java.net.MalformedURLException: Unknown protocol: rawresource
    at java.net.URL.<init>(URL.java:182)
    at java.net.URL.<init>(URL.java:125)
    at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:341)
    at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
    at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:141) 
    at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SourceLoadable.load(SingleSampleMediaPeriod.java:318) 
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
    at java.lang.Thread.run(Thread.java:818) 

### Exception from option 2

FATAL EXCEPTION: main
                                                                                Process: cl.assertsoft.santiagoindigena, PID: 11685
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{cl.assertsoft.santiagoindigena/cl.assertsoft.santiagoindigena.ui.activity.VideoActivity}: android.content.res.Resources$NotFoundException: File res/raw/sub2.srt from drawable resource ID #0x7f0d0000
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2447)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511)
                                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5480)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                 Caused by: android.content.res.Resources$NotFoundException: File res/raw/sub2.srt from drawable resource ID #0x7f0d0000
                                                                                    at android.content.res.Resources.openRawResourceFd(Resources.java:1330)
                                                                                    at com.google.android.exoplayer2.upstream.RawResourceDataSource.open(RawResourceDataSource.java:104)
                                                                                    at cl.assertsoft.santiagoindigena.ui.activity.VideoActivity.onCreate(VideoActivity.java:127)
                                                                                    at android.app.Activity.performCreate(Activity.java:6308)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511) 
                                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5480) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                 Caused by: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
                                                                                    at android.content.res.AssetManager.openNonAssetFdNative(Native Method)
                                                                                    at android.content.res.AssetManager.openNonAssetFd(AssetManager.java:431)
                                                                                    at android.content.res.Resources.openRawResourceFd(Resources.java:1327)
                                                                                    at com.google.android.exoplayer2.upstream.RawResourceDataSource.open(RawResourceDataSource.java:104) 
                                                                                    at cl.assertsoft.santiagoindigena.ui.activity.VideoActivity.onCreate(VideoActivity.java:127) 
                                                                                    at android.app.Activity.performCreate(Activity.java:6308) 
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511) 
                                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5480) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ojw28** [comment]
* The problem with Option 1 is that `DefaultDataSource` doesn't know how to handle raw resource uris. The good news is that this is supported in our `dev-v2` branch, where this approach should just work. The change that added support was https://github.com/google/ExoPlayer/pull/3719. This will be included in our next release (probably next week).
* The problem with Option 2 is that your `DataSource.Factory` implementation doesn't implement the interface correctly. In particular `createDataSource` should create an instance, not return the same instance every time. It shouldn't do anything like open the `DataSource` or anything like that. So you should implement it more like the snippet of code below. You should then just be able to drop it in instead of `DefaultDataSourceFactory`. This approach should work with the current release.

```
public class RawResourceDataSourceFactory implements DataSource.Factory {

  private final Context context;

  public RawResourceDataSourceFactory(Context context) {
    this.context = context.getApplicationContext();
  }

  @Override
  public DataSource createDataSource() {
    return new RawResourceDataSource(context);
  }

}
```
