### ISSUE TITLE
FLAC Extension doesn't play high sample rate files (for example 192khz)

### ISSUE THREAD

**Issue by Denis55ka** [google/ExoPlayer#3769]
### Issue description
FLAC Extension doesn't play audio with high sample rate (for example 192khz). It throws with exception E/FLACParser: unsupported sample rate 192000

### Version of ExoPlayer being used
2.6.1

### Device(s) and version(s) of Android being used
Xiaomi Mi5

### A full bug report captured from the device

E/FLACParser: unsupported sample rate 192000
E/FLACParser: unsupported sample rate 192000
E/ExoPlayerImplInternal: Source error.
                         java.io.IOException: Metadata decoding failed
                             at com.google.android.exoplayer2.ext.flac.FlacExtractor.read(FlacExtractor.java:98)
                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:749)
                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                             at java.lang.Thread.run(Thread.java:760)

**Comment by erdemguven** [comment]
Thanks for reporting this. I'll look into this but not likely to be soon.

**Comment by ojw28** [comment]
@botaydotcom - This looks extractor related (probably just need to add support for the extra sample rate).

**Comment by botaydotcom** [comment]
This issue is fixed in the referenced commit. Please help us to check whether it works for you using the dev-v2 branch.
