### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by axet** [google/ExoPlayer#3792]
#2309

seems like regression with exoplayer:r2.5.4

```
02-03 21:46:28.536 2741-20507/com.github.axet.torrentclient E/LoadTask: Unexpected exception loading stream
                                                                        java.lang.StringIndexOutOfBoundsException: length=108; regionStart=110; regionLength=-2
                                                                            at java.lang.StringFactory.newStringFromBytes(StringFactory.java:69)
                                                                            at java.lang.StringFactory.newStringFromBytes(StringFactory.java:59)
                                                                            at com.google.android.exoplayer2.metadata.id3.Id3Decoder.decodeGeobFrame(Id3Decoder.java:510)
                                                                            at com.google.android.exoplayer2.metadata.id3.Id3Decoder.decodeFrame(Id3Decoder.java:361)
                                                                            at com.google.android.exoplayer2.metadata.id3.Id3Decoder.decode(Id3Decoder.java:135)
                                                                            at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.peekId3Data(Mp3Extractor.java:330)
                                                                            at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.synchronize(Mp3Extractor.java:248)
                                                                            at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.sniff(Mp3Extractor.java:149)
                                                                            at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:762)
                                                                            at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:697)
                                                                            at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                            at java.lang.Thread.run(Thread.java:761)

```

**Comment by AquilesCanta** [comment]
Can you send a link/media sample to dev.exoplayer@gmail.com?

**Comment by axet** [comment]
done

**Comment by AquilesCanta** [comment]
Could you point us to the last ExoPlayer version on which you know this issue did not occur?

**Comment by axet** [comment]
Nope. It seems #2309 only fixes for `decodeCommentFrame`, but left unchanged same code in `decodeGeobFrame`

It is not a regression recent 2.6.1 also fails.

```
Caused by: java.lang.StringIndexOutOfBoundsException: length=24; regionStart=26; regionLength=-2
   at java.lang.StringFactory.newStringFromBytes(StringFactory.java:69)
   at java.lang.StringFactory.newStringFromBytes(StringFactory.java:59)
   at com.google.android.exoplayer2.metadata.id3.Id3Decoder.decodeGeobFrame(Id3Decoder.java:510)
   at com.google.android.exoplayer2.metadata.id3.Id3Decoder.decodeFrame(Id3Decoder.java:361)
   at com.google.android.exoplayer2.metadata.id3.Id3Decoder.decode(Id3Decoder.java:135)
   at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.peekId3Data(Mp3Extractor.java:327)
   at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.synchronize(Mp3Extractor.java:245)
   at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.sniff(Mp3Extractor.java:144)
   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:808)
   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:742)
   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
   at java.lang.Thread.run(Thread.java:761) 
```
