### ISSUE TITLE
What to do when there's a problem with ad source?

### ISSUE THREAD

**Issue by grajzer** [google/ExoPlayer#3801]
If there's a problem with ad, player just won't do anything. How to deal with this situation?

Here's an example ad tag URL you can use in exoplayer demo-ima app:
"https://vid.springserve.com/vast/183355?w=400&h=300&url=com.google&cb=1233445"

onAdLoadError is called and the following error is fired "AdErrorCode [name: VAST_LINEAR_ASSET_MISMATCH, number: 403], message: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities." 

Exoplayer should continue playing the video in cases like this.

**Comment by wezley98** [comment]
Another example:

```
27.165 10548-10548/com.google.android.exoplayer2.imademo W/AdsMediaSource: Ad load error
                                                                                       java.io.IOException: Ad error: com.google.obf.gk@aba7a39
                                                                                           at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.maybeNotifyAdError(ImaAdsLoader.java:836)
                                                                                           at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.onAdError(ImaAdsLoader.java:554)
                                                                                           at com.google.obf.he.a(IMASDK:8)
                                                                                           at com.google.obf.gy.a(IMASDK:60)
                                                                                           at com.google.obf.gy.a(IMASDK:95)
                                                                                           at com.google.obf.gq.a(IMASDK:71)
                                                                                           at com.google.obf.hj.f(IMASDK:202)
                                                                                           at com.google.obf.hj.a(IMASDK:41)
                                                                                           at com.google.obf.hk.b(IMASDK:39)
                                                                                           at com.google.obf.hk$1.shouldOverrideUrlLoading(IMASDK:4)
                                                                                           at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
                                                                                           at com.android.webview.chromium.Ap.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:75)
                                                                                           at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:15)
                                                                                           at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:160)
                                                                                           at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                                                           at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                        Caused by: AdError [errorType: PLAY, errorCode: AdErrorCode [name: VAST_LINEAR_ASSET_MISMATCH, number: 403], message: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities.]
                                                                                           at com.google.obf.gy.a(IMASDK:94)
                                                                                           at com.google.obf.gq.a(IMASDK:71) 
                                                                                           at com.google.obf.hj.f(IMASDK:202) 
                                                                                           at com.google.obf.hj.a(IMASDK:41) 
                                                                                           at com.google.obf.hk.b(IMASDK:39) 
                                                                                           at com.google.obf.hk$1.shouldOverrideUrlLoading(IMASDK:4) 
                                                                                           at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73) 
                                                                                           at com.android.webview.chromium.Ap.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:75) 
                                                                                           at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:15) 
                                                                                           at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:160) 
                                                                                           at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method) 
                                                                                           at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                           at android.os.Looper.loop(Looper.java:164) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
``` 

We expect a 403 and no ad to play but the video content does not play and the player hangs. For testing you can use the following VAST tag.

```
https://skygo.neodatagroup.com/ad/skySport.jsp?f=preroll-clip&device=phone&params=%7B%22nlid%22%3A%221f2d25c4-23be-45c9-9332-097281b96d22%22%2C%22uid%22%3A%22%22%2C%22userType%22%3A%224%22%2C%22gender%22%3A%22%22%2C%22trialexpire%22%3A%22%22%2C%22adv%22%3A%22true%22%2C%22os%22%3A%22android%22%2C%22path%22%3A%22Calciomercato%2Fcalciomercato%22%2C%22advCategory%22%3A%22Calciomercato%22%2C%22advSportname%22%3A%22calciomercato%22%2C%22videoChannel%22%3A%22sport%22%2C%22videoSubchannel%22%3A%22calciomercato%22%2C%22videoDuration%22%3A%2242%22%2C%22videoTag%3A%22%3A%5B%22%22%2C%22%22%2C%22%22%5D%2C%22videoAdv%22%3A%221%22%7D
```
