### ISSUE TITLE
Play OGG file from OBB expansion file using Exoplayer not working.

### ISSUE THREAD

**Issue by charlest05** [google/ExoPlayer#3802]
I've recently switched my app audio file(OGG) resources to a Expansion File. problem is that when I read an audio file using APEZProvider the app doesn't play anything.  please help thanks.

See Exoplayer Error:
`E/ExoPlayerImplInternal: Source error.
                     com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:705)
                         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:628)
                         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                         at java.lang.Thread.run(Thread.java:818)
E/MMParserExtractor: FileSource::FILE_SOURCE_DATA_EN`

My Custom APEZProvider:

`public class ZipFileContentProvider extends APEZProvider {
String AUTHORITY = "sample.sample";

@Override
public String getAuthority() {
    return AUTHORITY;
}

public Uri readAudioFileFromObb(String filename){

    String path = "content://" + AUTHORITY + File.separator + filename;

    return Uri.parse(path);
}
}`

My AndroidManifest.xml

`    <provider
        android:authorities="sample.sample"
        android:name=".PlaySong.ZipFileContentProvider"
        android:exported="true"
        android:multiprocess="true">
        <meta-data
            android:name="mainVersion"
            android:value="14"></meta-data>
    </provider>`

Exoplayer Version = 'r2.2.0'

[https://stackoverflow.com/questions/48564644/unable-to-play-ogg-audio-file-in-exoplayer-from-android-expansion-file-obb](see also my StackOverflow question about this)

**Comment by AquilesCanta** [comment]
The exception you encounter means that none of the extractors could recognize the format of the file. Make sure it is not being stored/packed as something else (e.g. a compressed format). We cannot help users debug their app, unfortunately. If you have evidence to think this is an ExoPlayer issue, please provide all relevant information below and we will reopen the issue.

**Comment by charlest05** [comment]
thanks for you response AquilesCanta.
