### ISSUE TITLE
FlacExtractor NullPointer Exception

### ISSUE THREAD

**Issue by fishingcats** [google/ExoPlayer#3806]
I met this issue when I tried to play *.flac audio file with Exoplayer( I have configed the project correctly and I can play other audio files normally: *.ac3/*.mp3 ...):

02-06 16:59:28.159 8428-8604/com.iflytek.autofly.voicewill E/Loader: Loader | load:ExtractingLoadable
02-06 16:59:28.163 8428-8604/com.iflytek.autofly.voicewill E/LoadTask: Unexpected exception loading stream
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.ext.flac.FlacDecoderJni.setData(com.google.android.exoplayer2.extractor.ExtractorInput)' on a null object reference
                                                                           at com.google.android.exoplayer2.ext.flac.FlacExtractor.read(FlacExtractor.java:98)
                                                                           at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:749)
                                                                           at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:316)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at java.lang.Thread.run(Thread.java:761)

**Comment by erdemguven** [comment]
Have you built the native library?
https://github.com/google/ExoPlayer/tree/release-v2/extensions/flac

**Comment by ojw28** [comment]
Closing due to lack of information.
