### ISSUE TITLE
IllegalStateException when using the Mp4RendererBuilder

### ISSUE THREAD

**Issue by andreimarinescu** [google/ExoPlayer#384]
When trying to play this MP4 file: http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4, I'm getting the stacktrace below (in the latest dev branch demo app). When using the DefaultRendererBuilder, playback is fine. Should this be considered a bug, or an issue with the video file itself? The test was made on a Nexus 5 running the latest 5.1 stock ROM.

>04-07 12:12:49.548  21425-21731/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal runtime error.
>    java.lang.IllegalStateException
            at com.google.android.exoplayer.util.Assertions.checkState(Assertions.java:66)
            at com.google.android.exoplayer.mp4.CommonMp4AtomParsers.parseTrak(CommonMp4AtomParsers.java:52)
            at com.google.android.exoplayer.source.Mp4SampleExtractor.processMoovAtom(Mp4SampleExtractor.java:676)
            at com.google.android.exoplayer.source.Mp4SampleExtractor.onContainerAtomRead(Mp4SampleExtractor.java:648)
            at com.google.android.exoplayer.source.Mp4SampleExtractor.readAtomPayload(Mp4SampleExtractor.java:638)
            at com.google.android.exoplayer.source.Mp4SampleExtractor.readHeaders(Mp4SampleExtractor.java:544)
            at com.google.android.exoplayer.source.Mp4SampleExtractor.prepare(Mp4SampleExtractor.java:186)
            at com.google.android.exoplayer.source.DefaultSampleSource.prepare(DefaultSampleSource.java:64)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:233)
            at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:115)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
04-07 12:12:49.560  21425-21425/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [0.42]
    com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:236)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.lang.IllegalStateException
            at com.google.android.exoplayer.util.Assertions.checkState(Assertions.java:66)
            at com.google.android.exoplayer.mp4.CommonMp4AtomParsers.parseTrak(CommonMp4AtomParsers.java:52)
            at com.google.android.exoplayer.source.Mp4SampleExtractor.processMoovAtom(Mp4SampleExtractor.java:676)
            at com.google.android.exoplayer.source.Mp4SampleExtractor.onContainerAtomRead(Mp4SampleExtractor.java:648)
            at com.google.android.exoplayer.source.Mp4SampleExtractor.readAtomPayload(Mp4SampleExtractor.java:638)
            at com.google.android.exoplayer.source.Mp4SampleExtractor.readHeaders(Mp4SampleExtractor.java:544)
            at com.google.android.exoplayer.source.Mp4SampleExtractor.prepare(Mp4SampleExtractor.java:186)
            at com.google.android.exoplayer.source.DefaultSampleSource.prepare(DefaultSampleSource.java:64)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:233)
            at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:115)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by ojw28** [comment]
We'll push a fix for this soon (eta later in the week).

**Comment by ojw28** [comment]
Note - The root issue is that the extractor fails when it encounters unsupported tracks in the stream (e.g. HINT tracks). The fix will be to skip them instead.

**Comment by andreimarinescu** [comment]
Thanks, @ojw28 for the quick reply!

**Comment by ojw28** [comment]
Fixed in dev.
