### ISSUE TITLE
Cant play encrypted video with clear_key drm scheme in Exoplayer2.

### ISSUE THREAD

**Issue by nishannorunobi** [google/ExoPlayer#3856]
**logcat log:**
```
02-15 18:39:27.889 3103-21756/? E/JsonWebKey: Failed to decode key id(YWJiYTI3MWU4YmNmNTUyYmJkMmU4NmE0MzRhOWE1ZDk=)
02-15 18:39:27.890 22715-22715/com.google.android.exoplayer2.imademo I/MediaDrm: Drm event (4,0)
02-15 18:39:27.891 22715-22715/com.google.android.exoplayer2.imademo D/EventLogger: drmKeysLoaded [0.66]
02-15 18:39:27.897 22715-22744/com.google.android.exoplayer2.imademo E/ExoPlayerImplInternal: Renderer error.
                                                                                              com.google.android.exoplayer2.ExoPlaybackException
                                                                                                  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:750)
                                                                                                  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:553)
                                                                                                  at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
                                                                                                  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                                                  at android.os.HandlerThread.run(HandlerThread.java:65)
                                                                                               Caused by: android.media.MediaCodec$CryptoException: Crypto key not available
                                                                                                  at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                                  at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2542)
                                                                                                  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:741)
                                                                                                  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:553) 
                                                                                                  at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560) 
                                                                                                  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306) 
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                  at android.os.Looper.loop(Looper.java:164) 
                                                                                                  at android.os.HandlerThread.run(HandlerThread.java:65) 
02-15 18:39:27.900 22715-22715/com.google.android.exoplayer2.imademo E/EventLogger: playerFailed [0.67]
                                                                                    com.google.android.exoplayer2.ExoPlaybackException
                                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:750)
                                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:553)
                                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
                                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:164)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:65)
                                                                                     Caused by: android.media.MediaCodec$CryptoException: Crypto key not available
                                                                                        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2542)
                                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:741)
                                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:553) 
                                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560) 
                                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                        at android.os.Looper.loop(Looper.java:164) 
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:65) 
02-15 18:39:27.911 22715-22752/com.google.android.exoplayer2.imademo D/SurfaceUtils: disconnecting from surface 0x7703a6a010, reason disconnectFromSurface
02-15 18:39:27.913 3111-31836/? I/OMX-VDEC-1080P: omx_vdec::component_deinit() complete
02-15 18:39:27.916 3111-31836/? I/OMX-VDEC-1080P: Exit OMX vdec Destructor: fd=17
02-15 18:39:27.924 22715-22715/com.google.android.exoplayer2.imademo D/EventLogger: videoDisabled [0.70]
02-15 18:39:27.927 22715-22715/com.google.android.exoplayer2.imademo D/EventLogger: loading [false]
02-15 18:39:27.933 22715-22715/com.google.android.exoplayer2.imademo D/EventLogger: state [0.70, true, I]
```
**Tools:**
1. ShakaPackager
2. ffmpeg
3. Exoplayer2
4. video file name : original.mp4
5. Ide: android studio
6. dev environment : windows
7. Tested Device : Emulator nexus5x and real device nexus5x
8. Encryption with clear_key scheme

**Steps**
step 01: converted the video to h264_baseline coded using ffmpeg with following command

```
ffmpeg -i original.mp4 -c:a copy \

  -vf "scale=-2:360" \

  -c:v libx264 -profile:v baseline -level:v 3.0 \

  -x264opts scenecut=0:open_gop=0:min-keyint=72:keyint=72 \

  -minrate 600k -maxrate 600k -bufsize 600k -b:v 600k \

  -y h264_baseline_360p_600.mp4
```

step 02: encrypted video with shaka-packager with following command and key:keyId
key : 69eaa802a6763af979e8d1940fb88392
keyId : abba271e8bcf552bbd2e86a434a9a5d9

`./packager-osx in=h264_baseline_360p_600.mp4,stream=video,output=h264_360.mp4 --enable_raw_key_encryption --keys label=:key_id=abba271e8bcf552bbd2e86a434a9a5d9:key=69eaa802a6763af979e8d1940fb88392 --clear_lead 0`

Step 03 : cloned and imported Exoplayer2 from 
>>git clone https://github.com/googlecodelabs/exoplayer-intro.git
help site >> https://codelabs.developers.google.com/codelabs/exoplayer-intro/#1

step 05: Copied encrypted video file in android project location: resource/raw/encrypted.mp4

step 04 : android code below.
**DataSrouce : below** 
```
private DataSource.Factory getDataSourceFactory(Context context) {
        DataSource.Factory dataSourceFactory = null;
        DataSpec dataSpec = new DataSpec(RawResourceDataSource.buildRawResourceUri(R.raw.encrypted));
        final RawResourceDataSource rawResourceDataSource = new RawResourceDataSource(context);
        try {
            rawResourceDataSource.open(dataSpec);
        } catch (RawResourceDataSource.RawResourceDataSourceException e) {
            e.printStackTrace();
        }

        dataSourceFactory = new DataSource.Factory() {
            @Override
            public DataSource createDataSource() {
                return rawResourceDataSource;
            }
        };
        return dataSourceFactory;
    }
```

**Drm Session Builder: below with key info**
key : 69eaa802a6763af979e8d1940fb88392
base64 encoded key : NjllYWE4MDJhNjc2M2FmOTc5ZThkMTk0MGZiODgzOTI=
keyId : abba271e8bcf552bbd2e86a434a9a5d9
base64 encoded keyId : YWJiYTI3MWU4YmNmNTUyYmJkMmU4NmE0MzRhOWE1ZDk=

```
private DrmSessionManager<FrameworkMediaCrypto> buildDrmSessionManager(Context context) throws UnsupportedDrmException {
        DrmSessionManager<FrameworkMediaCrypto> drmSessionManager = null;
        Intent intent = ((Activity) context).getIntent();
        String drmScheme = "clearkey";
        UUID uuid = C.CLEARKEY_UUID;

        LocalMediaDrmCallback drmCallback =
                new LocalMediaDrmCallback(
                "{\"keys\":[{\"kty\":\"oct\",\"k\":\"NjllYWE4MDJhNjc2M2FmOTc5ZThkMTk0MGZiODgzOTI=\",\"kid\":\"YWJiYTI3MWU4YmNmNTUyYmJkMmU4NmE0MzRhOWE1ZDk=\"}],\"type\":\"temporary\"}".getBytes());
        FrameworkMediaDrm  fmDrm = FrameworkMediaDrm.newInstance(uuid);
        drmSessionManager = new DefaultDrmSessionManager<FrameworkMediaCrypto>(
                uuid,
                fmDrm,
                drmCallback,
                null,
                mainHandler,
                eventLogger);
        return drmSessionManager;
    }
```

**Player Initializer : below**

```
TrackSelection.Factory adaptiveTrackSelectionFactory =
                new AdaptiveTrackSelection.Factory(new DefaultBandwidthMeter());
        trackSelector = new DefaultTrackSelector(adaptiveTrackSelectionFactory);
        eventLogger = new EventLogger(trackSelector);
        mainHandler = new Handler();
        @DefaultRenderersFactory.ExtensionRendererMode int extensionRendererMode = DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER;
        DrmSessionManager<FrameworkMediaCrypto> drmSessionManager = null;
        try {
            drmSessionManager = buildDrmSessionManager(context);
        } catch (UnsupportedDrmException e) {
            e.printStackTrace();
        }
        DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(context,
                drmSessionManager, extensionRendererMode);

        player = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector);
		
		simpleExoPlayerView.setPlayer(player);

        DataSource.Factory dataSourceFactory = getDataSourceFactory(context);
        MediaSource contentMediaSource =
                new ExtractorMediaSource.Factory(dataSourceFactory)
                        .createMediaSource(dataSourceFactory.createDataSource().getUri());
        player.addListener(new PlayerEventListener());
        player.addListener(eventLogger);
        player.addMetadataOutput(eventLogger);
        player.addAudioDebugListener(eventLogger);
        player.addVideoDebugListener(eventLogger);
        player.seekTo(contentPosition);
        player.setPlayWhenReady(true);
        player.prepare(contentMediaSource);
```
		
**Imported packages:**
package com.google.android.exoplayer2.imademo;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Handler;
import android.util.Base64;

import com.google.android.exoplayer2.DefaultRenderersFactory;
import com.google.android.exoplayer2.ExoPlayer;
import com.google.android.exoplayer2.ExoPlayerFactory;
import com.google.android.exoplayer2.Player;
import com.google.android.exoplayer2.SimpleExoPlayer;
import com.google.android.exoplayer2.drm.DefaultDrmSessionManager;
import com.google.android.exoplayer2.drm.DrmSessionManager;
import com.google.android.exoplayer2.drm.FrameworkMediaCrypto;
import com.google.android.exoplayer2.drm.FrameworkMediaDrm;
import com.google.android.exoplayer2.drm.LocalMediaDrmCallback;
import com.google.android.exoplayer2.drm.UnsupportedDrmException;
import com.google.android.exoplayer2.source.ExtractorMediaSource;
import com.google.android.exoplayer2.source.MediaSource;
import com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection;
import com.google.android.exoplayer2.trackselection.DefaultTrackSelector;
import com.google.android.exoplayer2.trackselection.TrackSelection;
import com.google.android.exoplayer2.ui.SimpleExoPlayerView;
import com.google.android.exoplayer2.upstream.DataSource;
import com.google.android.exoplayer2.upstream.DataSpec;
import com.google.android.exoplayer2.upstream.DefaultBandwidthMeter;
import com.google.android.exoplayer2.upstream.RawResourceDataSource;

**help links**
https://github.com/google/ExoPlayer/issues/3178
https://github.com/google/ExoPlayer/issues/949
https://developer.android.com/reference/android/media/MediaDrm.html
https://github.com/google/ExoPlayer/issues/2361
https://github.com/google/ExoPlayer/issues/2467

Thanks in advance

**Comment by nishannorunobi** [comment]
Full logcat for above problem.
[new 2.txt](https://github.com/google/ExoPlayer/files/1730438/new.2.txt)

**Comment by nishannorunobi** [comment]
**What is your encoding type of the given issue https://github.com/google/ExoPlayer/issues/3201 ?**

From the issue : https://github.com/google/ExoPlayer/issues/3201
last comment quoted below:

> KEY ; 0a247b0751cbf1a827e2fedfb87479a2
> encoded key : CiR7B1HL8agn4v7fuHR5og (unknown encoding)

base64 encoded key : MGEyNDdiMDc1MWNiZjFhODI3ZTJmZWRmYjg3NDc5YTI=
I used base64 encoder site with utf-8 : https://www.base64encode.org/

> KID : 91341951696b5e1ba232439ecec1f12a
> encoded kid : kTQZUWlrXhuiMkOezsHxKg (unknown encoding)

base64 encoded kid : OTEzNDE5NTE2OTZiNWUxYmEyMzI0MzllY2VjMWYxMmE=

> Good news: I was able to get the sample content working. You need to use the very latest dev-v2 branch, since there are some changes that are required to successfully play this kind of content that haven't made it into a stable release yet. On that branch, you can initialize your DrmSessionManager as follows to play the content:

> LocalMediaDrmCallback drmCallback = new LocalMediaDrmCallback(
>     "{\"keys\":[{\"kty\":\"oct\",\"k\":\"CiR7B1HL8agn4v7fuHR5og\",\"kid\":\"kTQZUWlrXhuiMkOezsHxKg\"}],\"type\":\"temporary\"}".getBytes());
> DrmSessionManager manager = new DefaultDrmSessionManager<>(C.CLEARKEY_UUID,
>     FrameworkMediaDrm.newInstance(C.CLEARKEY_UUID), drmCallback, null, mainHandler,
>     eventLogger);

	

**NB :** the encoding type worked for me.
Please let me know the encoding type you used.
thanks.

**Comment by ojw28** [comment]
The problem is that you're taking the key, treating it as a string, then trying to base64url encode it. It's not a string, but rather it's a 128 bit number, and you need to treat it as one when you do the encoding. As an example, if you have the key:
```
91341951696b5e1ba232439ecec1f12a
```
Then the equivalent byte[] in Java is:
```
ByteBuffer buffer = ByteBuffer.allocate(16);
buffer.putLong(0x91341951696b5e1bL);
buffer.putLong(0xa232439ecec1f12aL);
byte[] kidBytes = buffer.array();
```
You can then base64 encode the bytes without padding:
```
String base64Kid = Base64.encodeToString(kidBytes, Base64.NO_PADDING);
```
Which gives you:
```
kTQZUWlrXhuiMkOezsHxKg
```

Doing the same for your KID and KEY gives:
```
key : 69eaa802a6763af979e8d1940fb88392
base64 encoded key : aeqoAqZ2Ovl56NGUD7iDkg
keyId : abba271e8bcf552bbd2e86a434a9a5d9
base64 encoded keyId : q7onHovPVSu9LoakNKml2Q
```

One final caveat, is that you're required to encode keys using base64url encoding, not base64. This means if your encoded strings have `+` or `/` in, you need to replace those with `-` and `_` respectively. In your sample keys, there are no `+` or `/` characters and so this isn't necessary.

**Comment by nishannorunobi** [comment]
Thanks for your instant reply.
Its working now.
Your are right. My encoding steps was not correct.
@ojw28
