### ISSUE TITLE
ExoPlayer: Handle Socket Exception Timeout

### ISSUE THREAD

**Issue by nilac8991** [google/ExoPlayer#3875]
Hello, I was searching all over Google for an already answer but I think there's none of them.
There's a situation with an FM stream which in some cases it goes in Time out, my simple question, is there a way to handle this specific exception?

Thank you, and if more informations are needed I am right here :)

Edit. I already tried using the listener for the error events but it doesn't recognise it as it seems

```E/ExoPlayerImplInternal: Source error.
                                                                                   com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://stream.profm.ro:8012/profm.mp3
                                                                                       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
                                                                                       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:137)
                                                                                       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692)
                                                                                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                       at java.lang.Thread.run(Thread.java:761)
                                                                                    Caused by: java.net.SocketTimeoutException: connect timed out
                                                                                       at java.net.PlainSocketImpl.socketConnect(Native Method)
                                                                                       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
                                                                                       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
                                                                                       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
                                                                                       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
                                                                                       at java.net.Socket.connect(Socket.java:605)
                                                                                       at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
                                                                                       at com.android.okhttp.Connection.connectSocket(Connection.java:196)
                                                                                       at com.android.okhttp.Connection.connect(Connection.java:172)
                                                                                       at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
                                                                                       at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
                                                                                       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
                                                                                       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
                                                                                       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
                                                                                       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
                                                                                       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:429)
                                                                                       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:350)
                                                                                       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
                                                                                       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:137) 
                                                                                       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692) 
                                                                                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                       at java.lang.Thread.run(Thread.java:761)
```

**Comment by andrewlewis** [comment]
Does this not get notified via `onPlayerError` in an `ExoPlaybackException` with `TYPE_SOURCE`?

If you want to get notifications about every load error without waiting for retrying, you can also set an event listener directly on the `ExtractorMediaSource` via `ExtractorMediaSource.Factory.createMediaSource(uri, eventHandler, eventListener)`.

**Comment by nilac8991** [comment]
No, it wasn't handled it just gave the exception but I will try the method you gave in a while and report back,
Thanks!

**Comment by nilac8991** [comment]
Nope, @andrewlewis  I tried and it still crash :/  no events are displayed so the listener isn't mapping this exception or I am doing something wrong maybe...

**Comment by ojw28** [comment]
A stack trace being logged does not indicate a crash (there is nothing in this issue that suggests your process is crashing). This type of error should definitely be reported to any listeners that you've registered on the player instance, via `Player.EventListener.onPlayerError`.

**Comment by nilac8991** [comment]
Yeah sorry was intending exception not crash (Don't know why I wrote that), anyway I rewrote the entire service where the ExoPlayer instance was present and now everything works fine as it should so for sure I was doing something wrong.
Thanks for your help guys, really appreciated!
