### ISSUE TITLE
Exception when rewinding due to negative playback speed

### ISSUE THREAD

**Issue by clhols** [google/ExoPlayer#3895]
I am using the Live Channels Android TV app and ExoPlayer 2.7.0.

When I start playback of a recording and press the rewind button, I get the following error:

D/BaseTvInputService: Set playback speed to -2.0 and pitch 1.0
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.IllegalArgumentException
        at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:37)
        at com.google.android.exoplayer2.PlaybackParameters.<init>(PlaybackParameters.java:49)
        at com.google.android.exoplayer2.SimpleExoPlayer.setPlaybackParams(SimpleExoPlayer.java:339)
        at com.google.android.media.tv.companionlibrary.BaseTvInputService$Session.onTimeShiftSetPlaybackParams(BaseTvInputService.java:468)
        at android.media.tv.TvInputService$Session.timeShiftSetPlaybackParams(TvInputService.java:1350)
        at android.media.tv.ITvInputSessionWrapper.executeMessage(ITvInputSessionWrapper.java:211)
        at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6120)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

So the Live Channels app wants to playback in reverse but the PlaybackParameters asserts the playback speed to be positive.

**Comment by ojw28** [comment]
ExoPlayer doesn't support negative playback speeds, so this is working as intended from the point of view of the library.

I'm a bit confused as to what you're doing. Are you taking the Live Channels source code and trying to update the version of ExoPlayer used? If so, it feels like this is an issue with how you've performed the update. I have a feeling Live Channels app uses a customized version of ExoPlayer, which may make upgrading the version used more difficult.

**Comment by clhols** [comment]
Live Channels just shows a "surface" from the player of the app delivering the content. So it uses the ExoPlayer of my app (https://github.com/clhols/drchannels) when showing content.
I tried with ExoPlayer 2.6 and it just sets playback speed to 0.2 when Live Channels tries to do negative speed but it doesn't crash.
I will try to see if I can prevent Live Channels from allowing negative playback speeds.

You should probably update the companion library in the samples project as it doesn't call setPitch that is also asserted on in the new player version.

**Comment by ojw28** [comment]
So if I understand correctly, this is a bug in your application code. You're calling `setPlaybackParameters` with a negative speed, which is not supported. I guess Live Channels is requesting a negative playback speed, but there's probably nothing forcing you to pass that negative speed through to the `ExoPlayer` instance. You could do something else, for example pause the player and then schedule seek calls every second or so to gradually rewind the playback position, for as long as the requested playback speed is negative.

**Comment by clhols** [comment]
Ok, thanks for the info.
