### ISSUE TITLE
ExoPlayerImplInternal: Internal runtime error. in MediaCodec.native_dequeueInputBuffer

### ISSUE THREAD

**Issue by saschpe** [google/ExoPlayer#3896]
### Issue description
```
02-25 11:45:46.545 12157-14227/foo.debug E/ACodec: OMX/mediaserver died, signalling error!
02-25 11:45:46.545 12157-14227/foo.debug E/ACodec: signalError(omxError 0x8000100d, internalError -32)
02-25 11:45:46.545 12157-14227/foo.debug E/MediaCodec: Codec reported err 0xffffffe0, actionCode 0, while in state 6
02-25 11:45:46.546 12157-14227/foo.debug E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
02-25 11:45:46.546 12157-14227/foo.debug E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
02-25 11:45:46.546 12157-14227/foo.debug E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 0
02-25 11:45:46.546 12157-14227/foo.debug E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 0
02-25 11:45:46.556 12157-14222/foo.debug E/ExoPlayerImplInternal: Internal runtime error.
 java.lang.IllegalStateException
  at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
  at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2569)
  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:616)
  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:553)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:164)
  at android.os.HandlerThread.run(HandlerThread.java:65)
02-25 11:45:46.557 12157-12157/foo.debug E/ap_LocalPlayback: ExoPlayer error: what=
02-25 11:45:46.561 12157-14222/foo.debug E/ExoPlayerImplInternal: Stop failed.
 java.lang.IllegalStateException
  at android.media.MediaCodec.native_stop(Native Method)
  at android.media.MediaCodec.stop(MediaCodec.java:2067)
  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:497)
  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:451)
  at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onDisabled(MediaCodecAudioRenderer.java:376)
  at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:150)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:865)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:813)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:790)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:362)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:164)
  at android.os.HandlerThread.run(HandlerThread.java:65)
```
### Link to test content
http://ice3.somafm.com/defcon-32-aac

### Version of ExoPlayer being used
2.6.1

### Device(s) and version(s) of Android being used
Emulator, API 27, x86.

### A full bug report captured from the device
[bugreport-sdk_gphone_x86-OSM1.180201.007-2018-02-25-11-50-10.zip](https://github.com/google/ExoPlayer/files/1755901/bugreport-sdk_gphone_x86-OSM1.180201.007-2018-02-25-11-50-10.zip)

**Comment by erdemguven** [comment]
I couldn't download the linked media. Please email it to dev.exoplayer@gmail.com. Thanks.

**Comment by RaphaelJenni** [comment]
Got the same error. Any updates?

**Comment by magillus** [comment]
I just saw the same error on my application.
Is there a way to catch such crash error and let application deal with it, not forcing process to die?

**Comment by magillus** [comment]
In my case it was audio codec issue in media with 96kHz track.

**Comment by RaphaelJenni** [comment]
For me the problem was solved when I started my notification via `startForeground(...)`. Maybe this helps. (I only use audio)
