### ISSUE TITLE
MPD file not working

### ISSUE THREAD

**Issue by Anmolk22** [google/ExoPlayer#3897]
It's not an issue but I am trying to figure out why the exoplayer is not able to stream using the MPD file when I am directly putting the link to the videofile it seems to be streaming. I've attached the attachment containg both the code I am using to stream as well as the sample mpd file.

When using the mpd file I am getting the below exception

`Source error.
                                                                                                      com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                                          at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:924)
                                                                                                          at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:846)
                                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                                          at java.lang.Thread.run(Thread.java:761)
`

I've also tried using the mpd file link from the demos/main/assets but same issue still exists.

[sample.zip](https://github.com/google/ExoPlayer/files/1756389/sample.zip)

**Comment by ojw28** [comment]
You should be using `DashMediaSource` instead of `ExtractorMediaSource` when playing DASH streams.

**Comment by Anmolk22** [comment]
@ojw28 Yes I've updated the code accordingly but I am getting the below mentioned error. Thanks for the quick reply I've checked with the samply urls from the explayer demos assets sample urls and it has started working. So, I think the issue is with the MPD file.

```
Unexpected exception loading stream
                                                                                         java.lang.IllegalStateException
                                                                                             at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:79)
                                                                                             at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.checkContentTypeConsistency(DashManifestParser.java:1009)
                                                                                             at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseAdaptationSet(DashManifestParser.java:276)
                                                                                             at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parsePeriod(DashManifestParser.java:215)
                                                                                             at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseMediaPresentationDescription(DashManifestParser.java:142)
                                                                                             at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:103)
                                                                                             at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:58)
                                                                                             at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:130)
                                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                             at java.lang.Thread.run(Thread.java:761)
02-25 23:07:35.977 25635-25913/com.safety.callblocker.callblockerapplication E/ExoPlayerImplInternal: Source error.
                                                                                                      com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
                                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:330)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                                          at java.lang.Thread.run(Thread.java:761)
                                                                                                       Caused by: java.lang.IllegalStateException
                                                                                                          at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:79)
                                                                                                          at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.checkContentTypeConsistency(DashManifestParser.java:1009)
                                                                                                          at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseAdaptationSet(DashManifestParser.java:276)
                                                                                                          at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parsePeriod(DashManifestParser.java:215)
                                                                                                          at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseMediaPresentationDescription(DashManifestParser.java:142)
                                                                                                          at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:103)
                                                                                                          at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:58)
                                                                                                          at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:130)
                                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                                          at java.lang.Thread.run(Thread.java:761) 
```

**Comment by ojw28** [comment]
Yes, that looks like a problem with the manifest.

**Comment by Anmolk22** [comment]
@ojw28 Thanks you soo much for your help. Just found out the cause was with the MPD file. Used Shaka Packager and it started working like a charm. 

Thanks !!!
