### ISSUE TITLE
Can't play the flac file with Exoplayer

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#3908]
Hi All,

I used this library to play the music. But when I play the flac file, it can't play and fire the errors.

E/ExoPlayerImplInternal: Source error.                                          com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:774)
                                                at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:697)
                                                at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                at java.lang.Thread.run(Thread.java:761)

Do you have any suggestion ? Thanks in advance.

**Comment by erdemguven** [comment]
Please make sure you have build and included [Flac extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/flac).
