### ISSUE TITLE
HLS encrypted stream (AES 128 CBC) throws IllegalBlockSizeException

### ISSUE THREAD

**Issue by tstaszak89** [google/ExoPlayer#3917]
### Issue description
IllegalBlockSizeException occurs while playing HLS encrypted stream (AES 128 CBC). It is plying correct for a few seconds, next at the end of decryption of single ts - exception occurs and playback is stopped. 
According to HLS encryption specification (https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/HLS_Sample_Encryption/Encryption/Encryption.html#//apple_ref/doc/uid/TP40012862-CH2-SW7) no padding is used and end of data is not encrypted. Last bytes of data that are smaller than block size (16 bytes) are not encrypted but ExoPlayer tries to decrypt them - then exception occurs.
The stream on which the problem can be repeated is fully compliant with the specification of HLS AES 128 CBC encryption.

### Version of ExoPlayer being used
2.7.0

### Device(s) and version(s) of Android being used
Xiaomi Redmi 4 Pro Android 6.0.1

### A full bug report captured from the device
```
com.google.android.exoplayer2.ExoPlaybackException
   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:349)
   at android.os.Handler.dispatchMessage(Handler.java)
   at android.os.Looper.loop(Looper.java)
   at android.os.HandlerThread.run(HandlerThread.java)
Caused by: java.io.IOException: Error while finalizing cipher
   at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:104)
   at javax.crypto.CipherInputStream.read(CipherInputStream.java:155)
   at com.google.android.exoplayer2.source.hls.Aes128DataSource.read(Aes128DataSource.java:96)
   at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:260)
   at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61)
   at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:236)
   at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:285)
   at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:219)
   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
   at java.lang.Thread.run(Thread.java:818)
Caused by: javax.crypto.IllegalBlockSizeException: error:1e06b07b:Cipher functions:EVP_DecryptFinal_ex:WRONG_FINAL_BLOCK_LENGTH
   at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
   at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:568)
   at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:385)
   at javax.crypto.Cipher.doFinal(Cipher.java:1476)
   at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:102)
   at javax.crypto.CipherInputStream.read(CipherInputStream.java:155) 
   at com.google.android.exoplayer2.source.hls.Aes128DataSource.read(Aes128DataSource.java:96) 
   at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:260) 
   at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61) 
   at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:236) 
   at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:285) 
   at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:219) 
   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308) 
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
   at java.lang.Thread.run(Thread.java:818) 
```

**Comment by ojw28** [comment]
If you're specifying encryption method `AES-128` then I don't think your stream is compliant. According to the HLS RFC:
```
An encryption method of AES-128 signals that Media Segments are
completely encrypted using the Advanced Encryption Standard
[AES_128] with a 128-bit key, Cipher Block Chaining, and PKCS7
padding [RFC5652].  CBC is restarted on each segment boundary,
using either the IV attribute value or the Media Sequence Number
as the IV; see Section 5.2.
```

I think the documentation you've linked to is for encryption method `SAMPLE-AES`. We do not support this mode, as per our [supported formats page](http://google.github.io/ExoPlayer/supported-formats.html). We're unlikely to add support due to industry shifts toward common encryption.

**Comment by tstaszak89** [comment]
Thank you for very quick answer.

After reading about AES-128 and SAMPLE-AES standards it looks like the stream that I described combines those standards. Entire ts file is encrypted (AES-128) without padding and final block is not encrypted (SAMPLE-AES). Now I need to implement this myself. Will the [ExoPlayer/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/Aes128DataSource.java](https://github.com/google/ExoPlayer/blob/release-v2/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/Aes128DataSource.java)
 file be a good place to start?

**Comment by ojw28** [comment]
That's probably the best place to start, but I don't think we can spend time providing further guidance. For what it's worth, you'd really be better off just following the spec properly.

**Comment by tstaszak89** [comment]
Ok, thank you very much for your time.
