### ISSUE TITLE
Failed to initialize dummy surface - java.lang.IllegalStateException: eglMakeCurrent failed

### ISSUE THREAD

**Issue by gregkorossy** [google/ExoPlayer#3939]
I'm using ExoPlayer v2.7.0. My app changes `Player` instances about every 1 hour instead of changing media sources (technically the program should change every hour or so). This is due to the fact that some previous versions of the device it's running on have some issues with the kernel implementation and if a player is used for too long, it just crashes the whole system. However, the problem is not with earlier versions of Android, but API 23 (6.0 - Marshmallow).

So, on Android 6.0 the players change every 1 hour and it goes well for like 8 hours but then the new player instance cannot be created (or the media sources cannot be added) with this error happening:

```
03-04 10:00:00.109 27628-27709/com.example.app I/ExoPlayerImpl: Release f9ca357 [ExoPlayerLib/2.7.0] [octopus-f1, Q896S, Allwinner, 23] [goog.exo.core, goog.exo.ui]
03-04 10:00:00.169 27628-17312/com.example.app I/OMXClient: Using client-side OMX mux.
03-04 10:00:00.547 27628-17317/com.example.app E/IMGSRV: :0: PVRSRVAllocDeviceMem: Error 1 returned
03-04 10:00:00.547 27628-17317/com.example.app E/IMGSRV: :0: CBUF_CreateBuffer: DeviceMem alloc of 0xc800 failed for buffer 5
03-04 10:00:00.547 27628-17317/com.example.app E/IMGSRV: :0: InitContext: Failed to create buffer 5
03-04 10:00:00.550 27628-17317/com.example.app E/IMGSRV: :0: GLES2CreateGC: Failed to init the gc
03-04 10:00:00.574 27628-17317/com.example.app E/libEGL: eglMakeCurrent:754 error 3009 (EGL_BAD_MATCH)
03-04 10:00:00.575 27628-17317/com.example.app E/DummySurface: Failed to initialize dummy surface
                                                               java.lang.IllegalStateException: eglMakeCurrent failed
                                                                   at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:93)
                                                                   at com.google.android.exoplayer2.video.DummySurface$DummySurfaceThread.initInternal(DummySurface.java:329)
                                                                   at com.google.android.exoplayer2.video.DummySurface$DummySurfaceThread.handleMessage(DummySurface.java:228)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
03-04 10:00:00.576 27628-17301/com.example.app E/ExoPlayerImplInternal: Renderer error.
                                                                        com.google.android.exoplayer2.ExoPlaybackException
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:420)
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:407)
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:898)
                                                                            at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:469)
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:551)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                         Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.allwinner.video.decoder.avc, Format(1, null, video/avc, -1, null, [1024, 600, -1.0], [-1, -1])
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:407) 
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:898) 
                                                                            at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:469) 
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:551) 
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                         Caused by: java.lang.IllegalStateException: eglMakeCurrent failed
                                                                            at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:93)
                                                                            at com.google.android.exoplayer2.video.DummySurface$DummySurfaceThread.initInternal(DummySurface.java:329)
                                                                            at com.google.android.exoplayer2.video.DummySurface$DummySurfaceThread.handleMessage(DummySurface.java:228)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61) 
```

The old players always get stopped and released when the new one takes place (not necessarily when the new player is created because it has to wait for the current media to be played through). 
This does not happen on either Android 4.2 nor 4.4, so I guess the `DummySurface` messes up things. 
Is it possible that the GL surface is not getting released? Does the `release()` call need to happen on the same thread as the instance creation?

**Comment by gregkorossy** [comment]
As I was investigating this issue, came to the conclusion that something seemed to be wrong with the `DummySurface`, specifically, it seemed like it wouldn't get released properly. The version is still 2.7.0, the device it's running on is API 23 (Android 6.0).

I created a quick sample to reproduce the issue (using [RxJava 2](https://github.com/ReactiveX/RxJava)). Some notes:

- thread count is there to check whether the `DummySurfaceThread` actually dies
- the 500ms period is there to ensure that the threads actually have time to init / release things
- the `maxCount` value might need to be increased on different devices in order to reproduce the issue

And the code:

```java
final long maxCount = 300;

Observable
    .intervalRange(0, maxCount, 0, 500, TimeUnit.MILLISECONDS)
    .subscribeOn(Schedulers.computation())
    .observeOn(Schedulers.computation())
    .map(i -> {
        Log.d("DummySurface", "Creating DummySurface #" + i);
        return new Pair<>(i, DummySurface.newInstanceV17(MainActivity.this, false));
    })
    .subscribe(dummySurface -> {
        Log.d("DummySurface", "Index: " + dummySurface.first + ", dummySurface: " + dummySurface.second);

        Set<Thread> threadSet = Thread.getAllStackTraces().keySet();
        int counter = 0;
        for (Thread thread : threadSet) {
            if ("dummySurface".equalsIgnoreCase(thread.getName())) {
                counter++;
            }
        }

        Log.d("DummySurface", "'dummySurface' thread count: " + counter);

        dummySurface.second.release();
    }, throwable -> {
        Log.d("DummySurface", "error: " + throwable.getMessage(), throwable);
    });
```

Running the sample produces the following log:

```
D/DummySurface: Creating DummySurface #0
D/DummySurface: Index: 0, dummySurface: Surface(name=android.graphics.SurfaceTexture@6cc3338)/@0x1dd0f11
D/DummySurface: 'dummySurface' thread count: 1
D/DummySurface: Creating DummySurface #1
D/DummySurface: Index: 1, dummySurface: Surface(name=android.graphics.SurfaceTexture@5ce2312)/@0x9609ae3
D/DummySurface: 'dummySurface' thread count: 1
...
```

However, when it reaches index 273, creating the `DummySurface` instance fails with the following exception:

```
...
D/DummySurface: Creating DummySurface #273
E/IMGSRV: :0: PVRSRVAllocDeviceMem: Error 1 returned
E/IMGSRV: :0: CBUF_CreateBuffer: DeviceMem alloc of 0xc800 failed for buffer 5
E/IMGSRV: :0: InitContext: Failed to create buffer 5
E/IMGSRV: :0: GLES2CreateGC: Failed to init the gc
E/libEGL: eglMakeCurrent:754 error 3009 (EGL_BAD_MATCH)
E/DummySurface: Failed to initialize dummy surface
				java.lang.IllegalStateException: eglMakeCurrent failed
				   at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:93)
				   at com.google.android.exoplayer2.video.DummySurface$DummySurfaceThread.initInternal(DummySurface.java:329)
				   at com.google.android.exoplayer2.video.DummySurface$DummySurfaceThread.handleMessage(DummySurface.java:228)
				   at android.os.Handler.dispatchMessage(Handler.java:98)
				   at android.os.Looper.loop(Looper.java:148)
				   at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by ojw28** [comment]
So, is the conclusion that `DummySurface` instances are released properly, but that eventually initialization fails anyway? If so then that sounds more like a leak in the underlying platform than in ExoPlayer. Is the issue specific to whatever the particular device is that you're testing on?

**Comment by gregkorossy** [comment]
Trying to figure that out. It's kind of difficult to get hold of a similar API 23 device these days... 
(It's a Sibo Q896S device.)

**Comment by gregkorossy** [comment]
It seems like that disabling the `DummySurface` creation by returning `false` in `MediaCodecVideoRenderer `'s `shouldUseDummySurface()` increases the lifespan of the app on these probably buggy devices. Is there a way to let the developers decide whether they want dummy surface in the pre-compiled library? Cloning and maintaining the repo for modifying this behavior seems a bit overkill IMO.

**Comment by ojw28** [comment]
Is there a way for you to provide us with the exact [Build.MODEL](https://developer.android.com/reference/android/os/Build.html#MODEL) or [DEVICE](https://developer.android.com/reference/android/os/Build.html#DEVICE), as well as the [MANUFACTURER](https://developer.android.com/reference/android/os/Build.html#MANUFACTURER) values for devices you believe to be affected? We'd rather put in place workarounds than leave it up to individual app developers to do so.

By the way, I think you can avoid `DummySurface` ever being instantiated if you make sure your player instance isn't prepared without a valid `Surface` to render to. If this is just a case of swapping around the order of some calls in your app (e.g. to make sure the surface gets set before the player is prepared), then you'd do well to do that. Even on devices where `DummySurface` isn't buggy you'll get a bit of a performance win just through doing less unnecessary work.

**Comment by gregkorossy** [comment]
MANUFACTURER: Allwinner
MODEL: Q896S
DEVICE: octopus-f1
Also, the OS version ([Build.VERSION.RELEASE](https://developer.android.com/reference/android/os/Build.VERSION.html#RELEASE)) is 6.0.1.

The thing is that the player might not be attached to a surface because of scheduling done in the background. It might be possible to prepare the player only if it is attached but what happens if I detach it while it is prepared? I guess it would create a dummy surface at that point. Since this device is used in kiosk mode and the current content is changed pretty often (meaning the screen might display a different player and / or UI elements), the performance hit of constantly preparing a new player would be significant in this case.

**Comment by ojw28** [comment]
Thanks for the info! I'm not sure there's a huge amount we can do about this; it seems like an issue with the underlying platform (and so you should report it to the device manufacturer). We could disable DummySurface on the affected device, I guess.

> I'm using ExoPlayer v2.7.0. My app changes Player instances about every 1 hour instead of changing media sources (technically the program should change every hour or so). This is due to the fact that some previous versions of the device it's running on have some issues with the kernel implementation and if a player is used for too long, it just crashes the whole system. However, the problem is not with earlier versions of Android, but API 23 (6.0 - Marshmallow).

From a pragmatic point of view, if the kernel issue that requires you to change player instance every hour is fixed by Marshmallow, why don't you just only change the player when running on earlier versions? Then you wouldn't be recreating the player every hour on Marshmallow, which would largely mitigate the DummySurface problem.

**Comment by ojw28** [comment]
> Is there a way to let the developers decide whether they want dummy surface in the pre-compiled library?

You can extend `MediaCodecVideoRenderer` and override `codecNeedsSetOutputSurfaceWorkaround` so that it returns false on affected devices. This should disable use of `DummySurface`. You'll need to inject your extended renderer when creating the player. Depending on which `ExoPlayerFactory` method you're using, you may need to extend `DefaultRenderersFactory` and override `buildVideoRenderers` to do this.

If you can confirm that adding this device to `codecNeedsSetOutputSurfaceWorkaround` resolves the issue, then feel free to send a pull request adding `octopus-f1` to the giant `Util.DEVICE` switch statement in that method. If you do this, please send it to the `dev-v2` branch. The library would then contain the fix directly, and you wouldn't need to override or extend anything.
