### ISSUE TITLE
Mediasource exception with IMA when playlist

### ISSUE THREAD

**Issue by kinhdang** [google/ExoPlayer#3940]
Dear all !

We have a little problems with playlist and ima.
- Create createAdsMediaSource with single stream mp4, working properly.
- Create MediaSource, muilti stream mp4 with ConcatenatingMediaSource, working properly.

But when createAdsMediaSource with muilti stream then we have an error follow, any one have the same, please help.

Thanks,

FATAL EXCEPTION: ExoPlayerImplInternal:Handler
                                                               Process: com.unoipbox.vod, PID: 914
                                                               java.lang.IllegalStateException
                                                                   at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:79)
                                                                   at com.google.android.exoplayer2.source.ads.SinglePeriodAdTimeline.<init>(SinglePeriodAdTimeline.java:39)
                                                                   at com.google.android.exoplayer2.source.ads.AdsMediaSource.maybeUpdateSourceInfo(AdsMediaSource.java:349)
                                                                   at com.google.android.exoplayer2.source.ads.AdsMediaSource.onAdPlaybackState(AdsMediaSource.java:323)
                                                                   at com.google.android.exoplayer2.source.ads.AdsMediaSource.access$300(AdsMediaSource.java:45)
                                                                   at com.google.android.exoplayer2.source.ads.AdsMediaSource$ComponentListener$1.run(AdsMediaSource.java:388)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by andrewlewis** [comment]
It's not possible to insert ads in multi-period timelines using the IMA extension at the moment. #3693 tracks the enhancement.

**Comment by kinhdang** [comment]
Thanks,
