### ISSUE TITLE
DummySurface not released properly?

### ISSUE THREAD

**Issue by gregkorossy** [google/ExoPlayer#3944]
As I was investigating #3939, came to the conclusion that something seemed to be wrong with the `DummySurface`, specifically, it seemed like it wouldn't get released properly. The version is still 2.7.0, the device it's running on is API 23 (Android 6.0).

I created a quick sample to reproduce the issue (using [RxJava 2](https://github.com/ReactiveX/RxJava)). Some notes:

- thread count is there to check whether the `DummySurfaceThread` actually dies
- the 500ms period is there to ensure that the threads actually have time to init / release things
- the `maxCount` value might need to be increased on different devices in order to reproduce the issue

And the code:

```java
final long maxCount = 300;

Observable
    .intervalRange(0, maxCount, 0, 500, TimeUnit.MILLISECONDS)
    .subscribeOn(Schedulers.computation())
    .observeOn(Schedulers.computation())
    .map(i -> {
        Log.d("DummySurface", "Creating DummySurface #" + i);
        return new Pair<>(i, DummySurface.newInstanceV17(MainActivity.this, false));
    })
    .subscribe(dummySurface -> {
        Log.d("DummySurface", "Index: " + dummySurface.first + ", dummySurface: " + dummySurface.second);

        Set<Thread> threadSet = Thread.getAllStackTraces().keySet();
        int counter = 0;
        for (Thread thread : threadSet) {
            if ("dummySurface".equalsIgnoreCase(thread.getName())) {
                counter++;
            }
        }

        Log.d("DummySurface", "'dummySurface' thread count: " + counter);

        dummySurface.second.release();
    }, throwable -> {
        Log.d("DummySurface", "error: " + throwable.getMessage(), throwable);
    });
```

Running the sample produces the following log:

```
D/DummySurface: Creating DummySurface #0
D/DummySurface: Index: 0, dummySurface: Surface(name=android.graphics.SurfaceTexture@6cc3338)/@0x1dd0f11
D/DummySurface: 'dummySurface' thread count: 1
D/DummySurface: Creating DummySurface #1
D/DummySurface: Index: 1, dummySurface: Surface(name=android.graphics.SurfaceTexture@5ce2312)/@0x9609ae3
D/DummySurface: 'dummySurface' thread count: 1
...
```

However, when it reaches index 273, creating the `DummySurface` instance fails with the following exception:

```
...
D/DummySurface: Creating DummySurface #273
E/IMGSRV: :0: PVRSRVAllocDeviceMem: Error 1 returned
E/IMGSRV: :0: CBUF_CreateBuffer: DeviceMem alloc of 0xc800 failed for buffer 5
E/IMGSRV: :0: InitContext: Failed to create buffer 5
E/IMGSRV: :0: GLES2CreateGC: Failed to init the gc
E/libEGL: eglMakeCurrent:754 error 3009 (EGL_BAD_MATCH)
E/DummySurface: Failed to initialize dummy surface
				java.lang.IllegalStateException: eglMakeCurrent failed
				   at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:93)
				   at com.google.android.exoplayer2.video.DummySurface$DummySurfaceThread.initInternal(DummySurface.java:329)
				   at com.google.android.exoplayer2.video.DummySurface$DummySurfaceThread.handleMessage(DummySurface.java:228)
				   at android.os.Handler.dispatchMessage(Handler.java:98)
				   at android.os.Looper.loop(Looper.java:148)
				   at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by ojw28** [comment]
Please can you put this in the same issue as it's related to, rather than opening a new one? Closing this one as a duplicate.

**Comment by gregkorossy** [comment]
Added to the other one.
