### ISSUE TITLE
How to use DownloadManager and DownloadService class?

### ISSUE THREAD

**Issue by pranit21** [google/ExoPlayer#3955]
I am trying to implement DownloadManager and DownloadService to download dash files offline. Can anyone tell me how to use these classes to download files locally and use them in player after downloading?

**Comment by erdemguven** [comment]
Currently I'm preparing a post explaining the usage. It might be released in a couple of weeks. Please wait for it.

**Comment by pranit21** [comment]
@erdemguven Thanks for the update! But can you give me some hint on how to use it, because I have to give prototype for the client in this week.

I have tried using DashDownloader but it was giving me following error:
```
com.google.android.exoplayer2.offline.DownloadException: Unbounded index for representation: 0.0.0
    at com.google.android.exoplayer2.source.dash.offline.DashDownloader.getSegments(DashDownloader.java:121)
    at com.google.android.exoplayer2.source.dash.offline.DashDownloader.getSegments(DashDownloader.java:67)
    at com.google.android.exoplayer2.offline.SegmentDownloader.initStatus(SegmentDownloader.java:300)
    at com.google.android.exoplayer2.offline.SegmentDownloader.download(SegmentDownloader.java:160)
    at com.morepranit.offlinevideo.DownloadService$override.startDownload(DownloadService.java:102)
    at com.morepranit.offlinevideo.DownloadService$override.static$access$000(DownloadService.java:37)
    at com.morepranit.offlinevideo.DownloadService$override.access$dispatch(DownloadService.java)
    at com.morepranit.offlinevideo.DownloadService.access$000(DownloadService.java:0)
    at com.morepranit.offlinevideo.DownloadService$1.run(DownloadService.java:53)
    at java.lang.Thread.run(Thread.java:761)
```

Though all the representations were present: 
0.0.0
0.0.1
0.1.0

I have used following url:
[https://bae.sgp1.digitaloceanspaces.com/videos/121/dash/590b546f0d4e3896f611cd51d718e32f.mpd](https://bae.sgp1.digitaloceanspaces.com/videos/121/dash/590b546f0d4e3896f611cd51d718e32f.mpd)

Can you guide me on this? What am I doing wrong?

I was using following code which was mentioned in DashDownloader documentation:
```
SimpleCache cache = new SimpleCache(downloadFolder, new NoOpCacheEvictor());
 DefaultHttpDataSourceFactory factory = new DefaultHttpDataSourceFactory("ExoPlayer", null);
 DownloaderConstructorHelper constructorHelper =
     new DownloaderConstructorHelper(cache, factory);
 DashDownloader dashDownloader = new DashDownloader(manifestUrl, constructorHelper);
 // Select the first representation of the first adaptation set of the first period
 dashDownloader.selectRepresentations(new RepresentationKey[] {new RepresentationKey(0, 0, 0)});
 dashDownloader.download(new ProgressListener() {
   {@literal @}Override
   public void onDownloadProgress(Downloader downloader, float downloadPercentage,
       long downloadedBytes) {
     // Invoked periodically during the download.
   }
 });
```

**Comment by kvillnv** [comment]
@erdemguven, I'm looking forward for this documentation as well.
Is it the DownloadManager that is going to instruct the DashDownloader to update and download the next segments?
because for now I have just used DashDownloader and it does not take all the segments of my Dash playlist, it always stops at 59sec. So now, I am exploring how to use DownloadManager but I cant instantiate it, and there is no explanation about how to use the Deserializer.

@pranit21 I am using the same code and it works (not for more than 59sec), I am not sure how to solve your issue, but do you have the same probem if you don't set the representationKeys? (it should take all of them) if you still have an error, try another source.

**Comment by pranit21** [comment]
Hi @kvillnv, 
As per your suggestion if I choose other representation keys or no representation keys at all, then I get following error:
```
com.google.android.exoplayer2.upstream.cache.CacheDataSink$CacheDataSinkException: java.io.FileNotFoundException: /data/user/0/com.morepranit.offlinevideo/files/video_id/0.0.1520439899797.v3.exo (Not a directory)
    at com.google.android.exoplayer2.upstream.cache.CacheDataSink.open(CacheDataSink.java:104)
    at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:48)
    at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:372)
    at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:215)
    at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
    at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
    at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:129)
    at com.google.android.exoplayer2.source.dash.DashUtil.loadManifest(DashUtil.java:58)
    at com.google.android.exoplayer2.source.dash.offline.DashDownloader.getManifest(DashDownloader.java:94)
    at com.google.android.exoplayer2.source.dash.offline.DashDownloader.getManifest(DashDownloader.java:67)
    at com.google.android.exoplayer2.offline.SegmentDownloader.getManifestIfNeeded(SegmentDownloader.java:320)
    at com.google.android.exoplayer2.offline.SegmentDownloader.getManifest(SegmentDownloader.java:99)
    at com.google.android.exoplayer2.source.dash.offline.DashDownloader.getAllRepresentationKeys(DashDownloader.java:79)
    at com.morepranit.offlinevideo.DownloadService.startDownload(DownloadService.java:89)
    at com.morepranit.offlinevideo.DownloadService.access$000(DownloadService.java:37)
    at com.morepranit.offlinevideo.DownloadService$1.run(DownloadService.java:53)
    at java.lang.Thread.run(Thread.java:761)
Caused by: java.io.FileNotFoundException: /data/user/0/com.morepranit.offlinevideo/files/video_id/0.0.1520440271320.v3.exo (Not a directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
    at com.google.android.exoplayer2.upstream.cache.CacheDataSink.openNextOutputStream(CacheDataSink.java:149)
    at com.google.android.exoplayer2.upstream.cache.CacheDataSink.open(CacheDataSink.java:102)
	... 16 more
```

Though video_id directory already exists. Any suggestions what might be the issue?

**Comment by kvillnv** [comment]
I don't know how you instantiate your File for the simpleCache. mine is on the external storage, here is how I do it:
```
File downloadFolder = getPrivateStorageDir(context, mediaId); 
//mediaid is the name of the folder you want to create for the current media
   Log.d("File: ", downloadFolder.getAbsolutePath());
   SimpleCache cache = new SimpleCache(downloadFolder, new NoOpCacheEvictor());

```
the method (if you dont have an external drive, change the getExternalFilesDir()):
```
private File getPrivateStorageDir(Context context, String folderName) {
            File file = new File(context.getExternalFilesDir(
                    Environment.DIRECTORY_MOVIES), folderName);
            if (!file.mkdirs()) {
                Log.e("File ", "Directory not created");
            }
            return file;
        }
```

If you have success with this, please let me know if you are able to download more than 59sec

**Comment by pranit21** [comment]
@kvillnv,

Sorry it was my mistake. I was using wrong representationKey (1.0.0) which was not there.

I am using 
`File downloadFolder = new File(getFilesDir(), "video_id");`
for instantiation of File.

But still w/o any representationKey and with specifying any key, I am still getting 
`Unbounded index for representation` error. Sometimes it gives this error and sometimes not.

I have tried with your code also, but same error. :(

**Comment by pranit21** [comment]
Hi @kvillnv,

I was able to solve the issue thanks to @drjunja, https://github.com/google/ExoPlayer/issues/3729#issue-289918866. 
`C.TIME_UNSET` parameter used in current code, gets segmentCount only if `<SegmentTimeline>` tag is present in mpd. But there is no `<SegmentTimeline>` tag in my mpd, which was causing `Unbound index for representation` error. 

There was this code in DashDownloader.java file:
```
int segmentCount = index.getSegmentCount(C.TIME_UNSET);
if (segmentCount == DashSegmentIndex.INDEX_UNBOUNDED) {
    throw new DownloadException("Unbounded index for representation: " + key);
}
```

which I replaced with following code:
```
long periodDurationUs = manifest.getPeriodDurationUs(key.periodIndex);
int segmentCount = index.getSegmentCount(periodDurationUs);
if (segmentCount == DashSegmentIndex.INDEX_UNBOUNDED) {
    throw new DownloadException("Unbounded index for representation: " + key);
}
```

And then it worked. I was able to download full video.

And if you are using DownloadManager & DownloadService, then you can use default deserializer mentioned in `DashDownloadAction` class - `DashDownloadAction.DESERIALIZER`, I guess. Let me know if you are able to download videos using DownloadManager & DownloadService.

**Comment by kvillnv** [comment]
@pranit21 
Yes me too I was able to implement the DownloadManager today and download a full video.
I didn't need to change the segmentCount.

Now I am working on downloading live video, and it might actually be something about segmentCounts. I need to find a way to make the segmentCount dynamic.. because the last segments do not exist yet and it seems that the downloader makes the count when you start downloading. I'll try tomorrow

**Comment by pranit21** [comment]
@kvillnv,

That's great! Can you share your code on how you have implemented DownloadManager. Because I am trying to implement it with no luck.

**Comment by pranit21** [comment]
One more thing, when I try to create media source by using following code, media is not playing.

```
private MediaSource buildMediaSource(Uri uri) {
        File downloadFolder = getPrivateStorageDir(this, "video_id");
        SimpleCache cache = new SimpleCache(downloadFolder, new NoOpCacheEvictor());
        DefaultHttpDataSourceFactory factory = new DefaultHttpDataSourceFactory("ExoPlayer", null);
        //CacheDataSource cacheDataSource = new CacheDataSource(cache, factory.createDataSource(), CacheDataSource.FLAG_BLOCK_ON_CACHE);

        return new DashMediaSource.Factory(
                    new DefaultDashChunkSource.Factory(mediaDataSourceFactory),
                    new CacheDataSourceFactory(cache, factory, CacheDataSource.FLAG_BLOCK_ON_CACHE)
                ).createMediaSource(uri);
}
```

Though all the data has been downloaded and cached. Is there anything that I am missing?

**Comment by pranit21** [comment]
Can anyone tell me how to use CacheDataSource in MediaSource? I have tried various ways, but it is not loading from cache. It gives me `E/ExoPlayerImplInternal: Source error.` always.

Am I using it wrong way?

**Comment by douib** [comment]
@pranit21 Ensure you have Write_storage granted.

**Comment by pranit21** [comment]
@douib,

Thanks for your response! 

Write Storage is not needed, since it is private storage. But my issue got resolved. Refer https://github.com/google/ExoPlayer/issues/3976

It was related to representation downloaded. CachedDataSource was not picking downloaded representation from the track automatically, instead I had to forcefully select the representation which I have downloaded.

**Comment by molocco** [comment]
@erdemguven Did you manage to do any progress in that post to use the download manager? If, so, would you mind providing the link for it? (I looked around and couldn't find anything).

**Comment by erdemguven** [comment]
Please see my [Downloading Streams](https://medium.com/google-exoplayer/downloading-streams-6d259eec7f95) blog post on Medium.

**Comment by Waleedasim** [comment]
@pranit can you please guide me how to download hls videos for offline view your help would be appreciated. further I try from @erdemguven blog but its not helped me
