### ISSUE TITLE
 Does not play h265

### ISSUE THREAD

**Issue by RAISERALEX21** [google/ExoPlayer#3996]
**# When trying to play content on h265, Exoplayer remains loaded and does not play the content.

Just send me the following code, and no longer do any process. I'm a bit stuck with this. I hope you can help me :(**

GRADLE:
    compile 'com.google.android.exoplayer:exoplayer:r2.4.2'

ANDROID VERSION:
    7.0

```
03-15 13:49:25.427 1635-2371/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot get param: VDEC_DRV_GET_TYPE_GET_FRAME_CROP_INFO
03-15 13:49:25.428 1635-2560/? E/MtkOmxVdecEx: [0xb1e0d000] MtkOmxVdec::GetExtensionIndex Unknown parameter name: OMX.google.android.index.configureVideoTunnelMode
03-15 13:49:25.428 1635-2560/? E/MtkOmxVdecEx: [0xb1e0d000] MtkOmxVdec::GetExtensionIndex Unknown parameter name: OMX.google.android.index.useAndroidNativeBuffer2
03-15 13:49:25.429 1635-1799/? E/OMXNodeInstance: getConfig(663003c:MTK.DECODER.HEVC, ConfigCommonOutputCrop(0x700000f)) ERROR: BadParameter(0x80001005)
03-15 13:49:25.446 1635-17477/? E/OMXNodeInstance: setParameter(663003c:MTK.DECODER.HEVC, ParamPortDefinition(0x2000001)) ERROR: BadParameter(0x80001005)
03-15 13:49:25.446 1635-1799/? E/OMXNodeInstance: setParameter(663003c:MTK.DECODER.HEVC, ParamPortDefinition(0x2000001)) ERROR: BadParameter(0x80001005)
03-15 13:49:25.446 1635-2560/? E/OMXNodeInstance: setParameter(663003c:MTK.DECODER.HEVC, ParamPortDefinition(0x2000001)) ERROR: BadParameter(0x80001005)
03-15 13:49:25.447 1635-2371/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot get param: VDEC_DRV_GET_TYPE_GET_FRAME_CROP_INFO
03-15 13:49:25.448 1635-17477/? E/MtkOmxMVAMgr: [0xb1e1a028] [ERROR] Can not find MVA from VA: 0xb1e0b230
03-15 13:49:25.465 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -20
03-15 13:49:25.465 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:25.466 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:25.466 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:25.466 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] first time init HW fail, set kernel log detect count to larger
03-15 13:49:26.242 1635-17477/? E/SoftOMXPlugin: make component instance, need dlopen(libstagefright_soft_aacdec.so)!
03-15 13:49:26.252 16481-17717/com.dla.android E/ACodec: cannot find aac bit rate
03-15 13:49:26.255 1635-2371/? E/OMXNodeInstance: getParameter(663003d:google.aac.decoder, ??(0x7f200406)) ERROR: UnsupportedIndex(0x8000101a)
03-15 13:49:26.500 1377-1380/? E/FPO_MSG: Invalid PerfServ handle
03-15 13:49:26.963 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x28 0x1 0xac 0x18!!
03-15 13:49:26.963 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:26.963 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:26.965 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:26.965 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:26.968 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xd1 0x5!!
03-15 13:49:26.968 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:26.968 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:26.969 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:26.969 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:26.975 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe2 0x12!!
03-15 13:49:26.975 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:26.975 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:26.976 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:26.976 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:26.978 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe1 0x13!!
03-15 13:49:26.978 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:26.978 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:26.979 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:26.979 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:26.980 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe0 0x91!!
03-15 13:49:26.980 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:26.980 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:26.982 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:26.982 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:26.983 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe1 0x9b!!
03-15 13:49:26.983 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:26.983 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:26.984 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:26.985 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:26.989 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe3 0x1a!!
03-15 13:49:26.989 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:26.989 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:26.990 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:26.990 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:26.994 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe2 0x9b!!
03-15 13:49:26.994 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:26.994 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:26.995 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:26.995 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:26.998 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe3 0x9a!!
03-15 13:49:26.998 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:26.999 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.000 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.000 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.005 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xd2 0x2!!
03-15 13:49:27.005 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.005 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.005 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.005 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.009 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe6 0x1a!!
03-15 13:49:27.009 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.009 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.009 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.010 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.011 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe5 0x13!!
03-15 13:49:27.011 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.011 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.012 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.012 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.014 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe4 0x91!!
03-15 13:49:27.014 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.014 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.015 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.015 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.023 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe5 0x9b!!
03-15 13:49:27.023 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.023 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.024 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.024 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.026 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe7 0x1a!!
03-15 13:49:27.026 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.026 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.027 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.027 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.028 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe6 0x9b!!
03-15 13:49:27.028 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.028 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.029 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.030 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.031 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe7 0x9a!!
03-15 13:49:27.031 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.031 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.032 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.032 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.033 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xd3 0x2!!
03-15 13:49:27.033 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.033 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.034 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.034 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.037 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xea 0x1a!!
03-15 13:49:27.037 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.037 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.038 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.039 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.040 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe9 0x13!!
03-15 13:49:27.040 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.040 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.041 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.041 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.044 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe8 0x91!!
03-15 13:49:27.044 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.044 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.046 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.046 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.047 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xe9 0x9b!!
03-15 13:49:27.047 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.047 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.048 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.048 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.049 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xeb 0x1a!!
03-15 13:49:27.049 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.049 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.050 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.050 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.051 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xea 0x9b!!
03-15 13:49:27.051 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.051 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.053 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.053 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.056 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xeb 0x9a!!
03-15 13:49:27.056 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.056 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.057 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.058 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.059 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xd3 0x42!!
03-15 13:49:27.059 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.059 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.060 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.060 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.066 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xec 0x9a!!
03-15 13:49:27.066 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.066 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.067 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.067 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.068 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xd3 0xe2!!
03-15 13:49:27.068 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.068 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.069 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.069 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed and retry
03-15 13:49:27.070 1635-17710/? E/VDO_LOG: [Err] invalid NALU - 0x2 0x1 0xee 0x9a!!
03-15 13:49:27.070 1635-17710/? E/VDO_LOG: [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -11
03-15 13:49:27.070 1635-17710/? E/VDO_LOG: [Err] Error code -10
03-15 13:49:27.071 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] [ERROR] Cannot init driver
03-15 13:49:27.071 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed over 30 times
03-15 13:49:27.071 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] fatal error detect, set kernel log detect count to original
03-15 13:49:27.072 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] InitVideoDecodeHW failed (not compatible
03-15 13:49:27.072 1635-17710/? E/MtkOmxVdecEx: [0xb1e0d000] something wrong when decoding....
03-15 13:49:27.073 16481-17707/com.dla.android E/ACodec: [OMX.MTK.VIDEO.DECODER.HEVC] ERROR(0x80001005)
03-15 13:49:27.073 16481-17707/com.dla.android E/ACodec: signalError(omxError 0x80001005, internalError -2147483648)
03-15 13:49:27.074 16481-17706/com.dla.android E/MediaCodec: Codec reported err 0xfffffbb1, actionCode 0, while in state 6
03-15 13:49:27.078 16481-17691/com.dla.android E/ExoPlayerImplInternal: Internal runtime error.
                                                                        java.lang.IllegalStateException
                                                                            at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
                                                                            at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2518)
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:574)
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                            at android.os.Looper.loop(Looper.java:203)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
03-15 13:49:27.080 1635-17709/? E/MtkOmxMVAMgr: [0xb1e1a028] [ERROR] Can not find MVA from VA: 0x0
03-15 13:49:27.080 1635-17709/? E/MtkOmxMVAMgr: [0xb1e1a028] [ERROR] Can not find MVA from VA: 0x0
03-15 13:49:27.086 16481-17707/com.dla.android E/Surface: getSlotFromBufferLocked: unknown buffer: 0x8ca285c0
03-15 13:49:27.086 16481-17707/com.dla.android E/ACodec: failed to cancel buffer from native window: 0x96b9ea08, err = -22
03-15 13:49:27.087 16481-17707/com.dla.android E/Surface: getSlotFromBufferLocked: unknown buffer: 0x8ca28680
03-15 13:49:27.087 16481-17707/com.dla.android E/ACodec: failed to cancel buffer from native window: 0x96b9ea08, err = -22
03-15 13:49:27.095 16481-16481/com.dla.android E/EventLogger: playerFailed [3.06]
                                                              com.google.android.exoplayer2.ExoPlaybackException
                                                                  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:362)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                  at android.os.Looper.loop(Looper.java:203)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                               Caused by: java.lang.IllegalStateException
                                                                  at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
                                                                  at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2518)
                                                                  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:574)
                                                                  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
                                                                  at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                  at android.os.Looper.loop(Looper.java:203) 
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61) 
03-15 13:49:27.108 16481-17691/com.dla.android E/ExoPlayerImplInternal: Stop failed.
                                                                        java.lang.IllegalStateException
                                                                            at android.media.MediaCodec.native_stop(Native Method)
                                                                            at android.media.MediaCodec.stop(MediaCodec.java:2018)
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:455)
                                                                            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:409)
                                                                            at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:283)
                                                                            at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:147)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:709)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:684)
                                                                            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:364)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                            at android.os.Looper.loop(Looper.java:203)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
03-15 13:49:27.115 1635-2560/? E/SoftOMXPlugin: destroy component instance, need dlclose()!
03-15 13:49:29.501 1377-1380/? E/FPO_MSG: Invalid PerfServ handle
03-15 13:49:31.503 1377-1380/? E/FPO_MSG: Invalid PerfServ handle
03-15 13:49:37.509 1377-1380/? E/FPO_MSG: Invalid PerfServ handle
03-15 13:49:39.510 1377-1380/? E/FPO_MSG: Invalid PerfServ handle
03-15 13:49:46.523 1377-1380/? E/FPO_MSG: Invalid PerfServ handle
03-15 13:49:48.532 1377-1380/? E/FPO_MSG: Invalid PerfServ handle
```

**Comment by botaydotcom** [comment]
Hi @RAISERALEX21 ,
I think this is most probably a device specific issue. Could you please provide us with:
- The name of the device you are testing this on.
- The URL/content that you tried with.

That will help us to give further analysis. Thank you very much.

**Comment by ojw28** [comment]
Closing due to lack of information. If you're able to provide additional information please do so here, and we'll reopen the issue.
