### ISSUE TITLE
MPEG-DASH broadcast watching error: `com.google.android.exoplayer2.source.BehindLiveWindowException`

### ISSUE THREAD

**Issue by petersamokhin** [google/ExoPlayer#4009]
Hello.
I am using ExoPlayer (2.6.1) for showing broadcast. 
The error is:
```
com.***.android.*** E/ExoPlayerImplInternal: Source error.
          com.google.android.exoplayer2.source.BehindLiveWindowException
              at com.google.android.exoplayer2.source.dash.DefaultDashChunkSource.getNextChunk(DefaultDashChunkSource.java:248)
              at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.continueLoading(ChunkSampleStream.java:374)
              at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:71)
              at com.google.android.exoplayer2.source.dash.DashMediaPeriod.continueLoading(DashMediaPeriod.java:195)
              at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.continueLoading(ExoPlayerImplInternal.java:1640)
              at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1439)
              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1432)
              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:334)
              at android.os.Handler.dispatchMessage(Handler.java:107)
              at android.os.Looper.loop(Looper.java:194)
              at android.os.HandlerThread.run(HandlerThread.java:61)
```

Error causes with watching of any MPEG-DASH broadcast (`.mpd`), if there are any background task between downloading chunks. 
I was need to save broadcast during watching, but don't want to do double downloading.
Made own 'bytes sniffer' that does only saving bytes (that are already downloaded by ExoPlayer) to own buffer.
There are no delay, because all work made in bg thread.
But on some devices this error can happens.

Seen #1782, but I'm talking about mpd, not HLS (but maybe here no difference?). And #1782 has no solution for this error.

**UPD**: without background work error can happen too.

**Comment by AquilesCanta** [comment]
BehindLiveWindowException happens when the loading position falls behing the chunk window that the live manifest offers. There are several ways to prevent it, but if it happens, your only option is to reprepare the player. This is [done in the demo app](https://github.com/google/ExoPlayer/blob/r2.7.1/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L570). 

If you want to prevent it from happening, you could try detecting it beforehand (have a look at the currentPosition and bufferedPosition) and seeking back to a safe position in the window. Altering playback speed might also work if the cause of the falling back is not insufficient network bandwidth.

If this does not answer your question, please clarify below and we will reopen the issue.
