### ISSUE TITLE
mkv video play error

### ISSUE THREAD

**Issue by tangmingscau** [google/ExoPlayer#4010]
I tried to play video in MKV format, but there was no video, only sound. There are some erroneous logs here.

```
 internalError [5.92, loadError]
                                                                                 com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NullPointerException: null
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:337)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                     at java.lang.Thread.run(Thread.java:841)
                                                                                  Caused by: java.lang.NullPointerException
                                                                                     at com.google.android.exoplayer2.util.ParsableByteArray.<init>(ParsableByteArray.java:55)
                                                                                     at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$Track.initializeOutput(MatroskaExtractor.java:1613)
                                                                                     at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.endMasterElement(MatroskaExtractor.java:642)
                                                                                     at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$InnerEbmlReaderOutput.endMasterElement(MatroskaExtractor.java:1490)
                                                                                     at com.google.android.exoplayer2.extractor.mkv.DefaultEbmlReader.read(DefaultEbmlReader.java:69)
                                                                                     at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.read(MatroskaExtractor.java:429)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:751)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                     at java.lang.Thread.run(Thread.java:841)
```
Can you give me some advice?

**Comment by ojw28** [comment]
We can't debug this issue without sample media that reproduces the issue. Please provide a link here, or send one to: dev.exoplayer@gmail.com

Thanks!

**Comment by tangmingscau** [comment]
Thank you for your advice. In the end, I use other format tools to convert to MKV format video. It is found that it can be played, so it should be a bit of a problem when the format tool is converted to MKV music, but I will still send this problematic music to you. Thanks

**Comment by AquilesCanta** [comment]
Closing under the assumption that the issue was in the media. Please file a new issue including all the information required in the issue template if a new problem arises.

**Comment by ojw28** [comment]
This issue occurs when the codecs string is zero padded, which is apparently allowed according to the MKV specification. It's pretty weird that the tool you're using would opt to zero pad, given there's no need to do so, but we should still handle this correctly in the player. We'll push a fix shortly.
