### ISSUE TITLE
Exoplayer doesn't check if any other stream in .m3u8 works if one of them gives 403 (HLS)

### ISSUE THREAD

**Issue by pju-intive** [google/ExoPlayer#4044]
### Issue description
Having stream with different bitrates, one of them returns 403.
ExoPlayer checks it 4 times then gives up and returns with 403.
Even if there is one with lower bitrate it doesn't check it, to save stream.
Other platforms works this way (checks all of possible streams) and make it more failure tolerant for us.

### Reproduction steps
Have .m3u8 with one or few streams in it returns 403 and other works fine.

### Link to test content
sorry, but I only had it for brief time, will work with provider to make one available in future.

### Version of ExoPlayer being used
r2.5.1
2.7.1

### Device(s) and version(s) of Android being used
Google Pixel with Android 8.0
Emulator with 7.1 image in

### A full bug report captured from the device
com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
                                                                             at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:175)
                                                                             at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
                                                                             at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
                                                                             at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:129)
                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                             at java.lang.Thread.run(Thread.java:761)

**Comment by AquilesCanta** [comment]
403 is not considered to be blacklistable (404 and 410 currently are). The customizabilty of error handling across media sources (mainly adaptive ones) is tracked by #2981. If you control the media, you might want to try using 404 instead.

**Comment by pju-intive** [comment]
than

**Comment by pju-intive** [comment]
thanks for response, will work with it
