### ISSUE TITLE
HLS AES fails to play with  java.io.IOException: Error while finalizing cipher

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#4053]
hi @ojw28 
We have HLS media which can be played on safari and mobile chrome
but on exo player 2.7.0 it fails to play with the below exception

This can be reproduced on demo app
one thing I noticed is that if I set the bitrate lo lower bitrate and select "Retry" it will play 20sec
while next ts's keep throwing exceptions
and stop playing afterwards

What can be the reason for that?

URL will be sent to the exo player dev email
10x
Gilad

03-29 22:39:55.096 11638-11638/? E/EventLogger: internalError [17.49, loadError]
                                                java.io.IOException: Error while finalizing cipher
                                                    at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:104)
                                                    at javax.crypto.CipherInputStream.read(CipherInputStream.java:155)
                                                    at com.google.android.exoplayer2.source.hls.Aes128DataSource.read(Aes128DataSource.java:96)
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:257)
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:59)
                                                    at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:233)
                                                    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:255)
                                                    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:191)
                                                    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                    at java.lang.Thread.run(Thread.java:818)
                                                 Caused by: javax.crypto.BadPaddingException: error:1e06b065:Cipher functions:EVP_DecryptFinal_ex:BAD_DECRYPT
                                                    at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
                                                    at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:568)
                                                    at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:385)
                                                    at javax.crypto.Cipher.doFinal(Cipher.java:1476)
                                                    at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:102)
                                                    at javax.crypto.CipherInputStream.read(CipherInputStream.java:155) 
                                                    at com.google.android.exoplayer2.source.hls.Aes128DataSource.read(Aes128DataSource.java:96) 
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:257) 
                                                    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:59) 
                                                    at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:233) 
                                                    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:255) 
                                                    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:191) 
                                                    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315) 
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                    at java.lang.Thread.run(Thread.java:818)

**Comment by ojw28** [comment]
Link is a 404 for me. Perhaps it's geo-restricted?

**Comment by tonihei** [comment]
Closing due to inactivity.

**Comment by giladna** [comment]
@tonihei 

you may use vpn to India for this please

**Comment by ojw28** [comment]
We really need non-georestricted test content to investigate issues efficiently. We shouldn't have to jump through hoops to help you with your issues. Thanks!

**Comment by giladna** [comment]
tested again this media and now it works ok 

please close issue
