### ISSUE TITLE
Exoplayer ANR for m3u8 content which is not live

### ISSUE THREAD

**Issue by Yadunath** [google/ExoPlayer#4092]
I am facing ANR issue for m3u8 content (live).For live content it's playing properly,but if the video is not live then it's taking time and anr is happening.on video state is changing but video is not playing .
Attaching the log below.

"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x755ba5c8 self=0xe7985400
  | sysTid=1430 nice=-10 cgrp=default sched=0/0 handle=0xea67f534
  | state=S schedstat=( 13901582844 1391760430 12194 ) utm=1288 stm=102 core=0 HZ=100
  | stack=0xff7ee000-0xff7f0000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x0abed240> (a com.google.android.exoplayer2.ExoPlayerImplInternal)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.blockingSendMessages(ExoPlayerImplInternal.java:221)
  - locked <0x0abed240> (a com.google.android.exoplayer2.ExoPlayerImplInternal)
  at com.google.android.exoplayer2.ExoPlayerImpl.blockingSendMessages(ExoPlayerImpl.java:311)
  at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurfaceInternal(SimpleExoPlayer.java:907)
  at com.google.android.exoplayer2.SimpleExoPlayer.access$1200(SimpleExoPlayer.java:51)
  at com.google.android.exoplayer2.SimpleExoPlayer$ComponentListener.surfaceDestroyed(SimpleExoPlayer.java:1076)
  at android.view.SurfaceView.updateWindow(SurfaceView.java:588)
  at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:247)
  at android.view.View.dispatchDetachedFromWindow(View.java:15551)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
