### ISSUE TITLE
CryptoException: Operation not supported - DRM is not playable on Android GO device 8.1.0

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#4101]
Hi,

In ExoPlayer Demo app we try to play WV: Secure SD content and we get the following exception:

One thing that I need to mention that this device finger print is as following:
```
"system": {
        "RELEASE": "8.1.0",
        "SDK_INT": 27,
        "BRAND": "google",
        "MODEL": "gobo",
        "MANUFACTURER": "alps",
        "TAGS": "dev-keys",
        "FINGERPRINT": "google/gobo/gobo:8.1.0/OMB1.171031.003/4428322:user/dev-keys",
        "ARCH": {
            "os.arch": "armv7l",
            "SUPPORTED_ABIS": [
                "armeabi-v7a",
                "armeabi"
            ],
            "SUPPORTED_32_BIT_ABIS": [
                "armeabi-v7a",
                "armeabi"
            ],
            "SUPPORTED_64_BIT_ABIS": []
        }
    }
```
What could  be the reason for this exception?

10x
Gilad
-------
```
04-09 03:53:35.991 19856-19856/com.google.android.exoplayer2.demo D/Surface: Surface::allocateBuffers(this=0x93124800)
04-09 03:53:35.992 19856-19875/com.google.android.exoplayer2.demo D/Surface: Surface::connect(this=0x93124800,api=1)
04-09 03:53:35.999 19856-19875/com.google.android.exoplayer2.demo D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
04-09 03:53:36.033 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: register, handle(0xace54c60) (w:480 h:854 s:480 f:0x1 u:b00)
04-09 03:53:36.078 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: register, handle(0xace55280) (w:480 h:854 s:480 f:0x1 u:b00)
04-09 03:53:36.087 19856-19856/com.google.android.exoplayer2.demo D/Surface: Surface::disconnect(this=0x91670800,api=-1)
04-09 03:53:36.095 19856-19875/com.google.android.exoplayer2.demo D/Surface: Surface::disconnect(this=0x91670000,api=1)
04-09 03:53:36.097 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: unregister, handle(0xace56160) (w:480 h:782 s:480 f:0x1 u:b00)
    unregister, handle(0xace55c20) (w:480 h:782 s:480 f:0x1 u:b00)
04-09 03:53:36.098 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: unregister, handle(0xace55ec0) (w:480 h:782 s:480 f:0x1 u:b00)
04-09 03:53:36.098 19856-19875/com.google.android.exoplayer2.demo D/Surface: Surface::disconnect(this=0x91670000,api=1)
04-09 03:53:36.101 19856-19875/com.google.android.exoplayer2.demo W/libEGL: EGLNativeWindowType 0x91670008 disconnect failed
04-09 03:53:36.356 19856-19856/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Release fd6b1fe [ExoPlayerLib/2.6.1] [gobo, gobo, alps, 27] [goog.exo.core, goog.exo.ui, goog.exo.dash]
04-09 03:53:37.574 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: register, handle(0xace551a0) (w:480 h:854 s:480 f:0x1 u:b00)
04-09 03:53:44.048 19856-19856/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init c983b6a [ExoPlayerLib/2.6.1] [gobo, gobo, alps, 27]
04-09 03:53:44.058 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: state [0.04, true, I]
04-09 03:53:44.092 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: state [0.07, true, B]
04-09 03:53:44.095 19856-20434/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest>>
04-09 03:53:44.102 19856-20434/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest<<
04-09 03:53:44.169 19856-19875/com.google.android.exoplayer2.demo D/Surface: Surface::connect(this=0x8f5ff000,api=1)
04-09 03:53:44.173 19856-19875/com.google.android.exoplayer2.demo D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
04-09 03:53:44.246 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: register, handle(0xace56160) (w:480 h:782 s:480 f:0x1 u:b00)
04-09 03:53:44.298 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: register, handle(0xace56400) (w:480 h:782 s:480 f:0x1 u:b00)
04-09 03:53:44.329 19856-19875/com.google.android.exoplayer2.demo D/Surface: Surface::disconnect(this=0x93124800,api=1)
04-09 03:53:44.331 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: unregister, handle(0xace54d40) (w:480 h:854 s:480 f:0x1 u:b00)
04-09 03:53:44.332 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: unregister, handle(0xace557c0) (w:480 h:854 s:480 f:0x1 u:b00)
    unregister, handle(0xace558a0) (w:480 h:854 s:480 f:0x1 u:b00)
04-09 03:53:44.332 19856-19875/com.google.android.exoplayer2.demo D/Surface: Surface::disconnect(this=0x93124800,api=1)
04-09 03:53:44.332 19856-19875/com.google.android.exoplayer2.demo W/libEGL: EGLNativeWindowType 0x93124808 disconnect failed
04-09 03:53:44.333 19856-19875/com.google.android.exoplayer2.demo D/OpenGLRenderer: endAllActiveAnimators on 0x920dc980 (ExpandableListView) with handle 0x920222f0
04-09 03:53:44.416 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: sourceInfo [periodCount=1, windowCount=1
04-09 03:53:44.417 19856-19856/com.google.android.exoplayer2.demo D/EventLogger:   period [734.00]
04-09 03:53:44.418 19856-19856/com.google.android.exoplayer2.demo D/EventLogger:   window [734.00, true, false]
    ]
04-09 03:53:44.433 19856-20433/com.google.android.exoplayer2.demo D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.64002a, video/avc] [OMX.MTK.VIDEO.DECODER.AVC, video/avc] [gobo, gobo, alps, 27]
04-09 03:53:44.441 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: loading [true]
04-09 03:53:44.458 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: Tracks [
04-09 03:53:44.459 19856-19856/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:0 [
        Group:0, adaptive_supported=YES [
          [X] Track:0, id=1, mimeType=video/avc, bitrate=772315, res=320x142, fps=24.0, supported=YES
04-09 03:53:44.460 19856-19856/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:1, id=2, mimeType=video/avc, bitrate=1777315, res=854x380, fps=24.0, supported=YES
          [X] Track:2, id=3, mimeType=video/avc, bitrate=7206998, res=1280x570, fps=24.0, supported=YES
          [ ] Track:3, id=4, mimeType=video/avc, bitrate=18320008, res=1920x856, fps=24.0, supported=NO_EXCEEDS_CAPABILITIES
        ]
      ]
04-09 03:53:44.461 19856-19856/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:1 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=0, mimeType=audio/mp4a-latm, bitrate=134359, channels=2, sample_rate=44100, language=en, supported=YES
        ]
      ]
    ]
04-09 03:53:44.463 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: videoEnabled [0.44]
04-09 03:53:44.465 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: audioEnabled [0.44]
04-09 03:53:44.486 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: register, handle(0xace54c60) (w:480 h:782 s:480 f:0x1 u:b00)
04-09 03:53:44.519 19856-20435/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest>>
04-09 03:53:44.521 19856-20435/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest<<
04-09 03:53:44.589 19856-20436/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest>>
04-09 03:53:44.594 19856-20436/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest<<
04-09 03:53:44.970 19856-20435/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest>>
04-09 03:53:44.973 19856-20435/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest<<
04-09 03:53:45.007 19856-20436/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest>>
04-09 03:53:45.009 19856-20436/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest<<
04-09 03:53:45.661 19856-20442/com.google.android.exoplayer2.demo I/OMXClient: Treble IOmx obtained
04-09 03:53:45.685 19856-20438/com.google.android.exoplayer2.demo I/System.out: Check isMmsSendPdu
04-09 03:53:45.689 19856-20438/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest<<
04-09 03:53:45.700 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: audioDecoderInitialized [1.68, OMX.google.aac.decoder]
04-09 03:53:45.702 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: audioFormatChanged [1.68, id=0, mimeType=audio/mp4a-latm, bitrate=134359, channels=2, sample_rate=44100, language=eng]
04-09 03:53:45.703 19856-20442/com.google.android.exoplayer2.demo E/MediaCodec: queueCSDInputBuffer failed w/ error -2006
04-09 03:53:45.712 19856-20433/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
    android.media.MediaCodec$CryptoException: Operation not supported in this configuration
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2637)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:942)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:552)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
04-09 03:53:45.742 19856-20433/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Stop failed.
    android.media.MediaCodec$CryptoException: Operation not supported in this configuration
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2072)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:497)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:451)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onDisabled(MediaCodecAudioRenderer.java:376)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:150)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:865)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:790)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:362)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
04-09 03:53:45.752 19856-19856/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [1.73]
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:360)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.media.MediaCodec$CryptoException: Operation not supported in this configuration
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2637)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:942)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:552)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
04-09 03:53:45.754 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: videoDisabled [1.73]
04-09 03:53:45.769 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: audioDisabled [1.75]
    loading [false]
04-09 03:53:45.788 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: state [1.76, true, I]
04-09 03:53:45.825 19856-19867/com.google.android.exoplayer2.demo I/zygote: Background concurrent copying GC freed 5463(433KB) AllocSpace objects, 4(272KB) LOS objects, 25% free, 2MB/3MB, paused 343us total 168.530ms
04-09 03:54:31.376 19856-19875/com.google.android.exoplayer2.demo D/Surface: Surface::connect(this=0x93124800,api=1)
04-09 03:54:31.376 19856-19856/com.google.android.exoplayer2.demo D/Surface: Surface::allocateBuffers(this=0x93124800)
04-09 03:54:31.389 19856-19875/com.google.android.exoplayer2.demo D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
04-09 03:54:31.401 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: register, handle(0xace551a0) (w:480 h:854 s:480 f:0x1 u:b00)
04-09 03:54:31.447 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: register, handle(0xace557c0) (w:480 h:854 s:480 f:0x1 u:b00)
04-09 03:54:31.456 19856-19856/com.google.android.exoplayer2.demo D/Surface: Surface::disconnect(this=0x8f5ff800,api=-1)
04-09 03:54:31.463 19856-19875/com.google.android.exoplayer2.demo D/Surface: Surface::disconnect(this=0x8f5ff000,api=1)
04-09 03:54:31.466 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: unregister, handle(0xace54d40) (w:480 h:782 s:480 f:0x1 u:b00)
04-09 03:54:31.467 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: unregister, handle(0xace56240) (w:480 h:782 s:480 f:0x1 u:b00)
    unregister, handle(0xace564e0) (w:480 h:782 s:480 f:0x1 u:b00)
04-09 03:54:31.467 19856-19875/com.google.android.exoplayer2.demo D/Surface: Surface::disconnect(this=0x8f5ff000,api=1)
04-09 03:54:31.468 19856-19875/com.google.android.exoplayer2.demo W/libEGL: EGLNativeWindowType 0x8f5ff008 disconnect failed
04-09 03:54:31.720 19856-19856/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Release c983b6a [ExoPlayerLib/2.6.1] [gobo, gobo, alps, 27] [goog.exo.core, goog.exo.ui, goog.exo.dash]
04-09 03:54:32.961 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: register, handle(0xace54c60) (w:480 h:854 s:480 f:0x1 u:b00)
04-09 03:54:45.760 19856-19856/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init c91b6ca [ExoPlayerLib/2.6.1] [gobo, gobo, alps, 27]
04-09 03:54:45.772 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: state [0.04, true, I]
04-09 03:54:45.806 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: state [0.07, true, B]
04-09 03:54:45.817 19856-20478/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest>>
04-09 03:54:45.820 19856-20478/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest<<
04-09 03:54:45.873 19856-19875/com.google.android.exoplayer2.demo D/Surface: Surface::connect(this=0x8f57f000,api=1)
04-09 03:54:45.879 19856-19875/com.google.android.exoplayer2.demo D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
04-09 03:54:45.967 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: register, handle(0xace56160) (w:480 h:782 s:480 f:0x1 u:b00)
04-09 03:54:46.023 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: register, handle(0xace56400) (w:480 h:782 s:480 f:0x1 u:b00)
04-09 03:54:46.047 19856-19875/com.google.android.exoplayer2.demo D/Surface: Surface::disconnect(this=0x93124800,api=1)
04-09 03:54:46.049 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: unregister, handle(0xace54d40) (w:480 h:854 s:480 f:0x1 u:b00)
04-09 03:54:46.051 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: unregister, handle(0xace55280) (w:480 h:854 s:480 f:0x1 u:b00)
04-09 03:54:46.054 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: unregister, handle(0xace558a0) (w:480 h:854 s:480 f:0x1 u:b00)
04-09 03:54:46.054 19856-19875/com.google.android.exoplayer2.demo D/Surface: Surface::disconnect(this=0x93124800,api=1)
04-09 03:54:46.054 19856-19875/com.google.android.exoplayer2.demo W/libEGL: EGLNativeWindowType 0x93124808 disconnect failed
04-09 03:54:46.055 19856-19875/com.google.android.exoplayer2.demo D/OpenGLRenderer: endAllActiveAnimators on 0x920dc980 (ExpandableListView) with handle 0x92358b70
04-09 03:54:46.290 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: sourceInfo [periodCount=1, windowCount=1
04-09 03:54:46.291 19856-19856/com.google.android.exoplayer2.demo D/EventLogger:   period [734.00]
04-09 03:54:46.292 19856-19856/com.google.android.exoplayer2.demo D/EventLogger:   window [734.00, true, false]
    ]
04-09 03:54:46.305 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: loading [true]
04-09 03:54:46.324 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: Tracks [
      Renderer:0 [
        Group:0, adaptive_supported=YES [
04-09 03:54:46.325 19856-19856/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=1, mimeType=video/avc, bitrate=772315, res=320x142, fps=24.0, supported=YES
          [X] Track:1, id=2, mimeType=video/avc, bitrate=1777315, res=854x380, fps=24.0, supported=YES
        ]
      ]
      Renderer:1 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=0, mimeType=audio/mp4a-latm, bitrate=134359, channels=2, sample_rate=44100, language=en, supported=YES
04-09 03:54:46.326 19856-19856/com.google.android.exoplayer2.demo D/EventLogger:     ]
      ]
    ]
04-09 03:54:46.328 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: videoEnabled [0.59]
04-09 03:54:46.329 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: audioEnabled [0.59]
04-09 03:54:46.346 19856-19875/com.google.android.exoplayer2.demo D/GraphicBuffer: register, handle(0xace54c60) (w:480 h:782 s:480 f:0x1 u:b00)
04-09 03:54:46.353 19856-20479/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest>>
04-09 03:54:46.355 19856-20479/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest<<
04-09 03:54:46.421 19856-20480/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest>>
04-09 03:54:46.423 19856-20480/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest<<
04-09 03:54:46.686 19856-20479/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest>>
04-09 03:54:46.687 19856-20479/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest<<
04-09 03:54:46.822 19856-20480/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest>>
04-09 03:54:46.823 19856-20480/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest<<
04-09 03:54:47.401 19856-20486/com.google.android.exoplayer2.demo I/OMXClient: Treble IOmx obtained
04-09 03:54:47.426 19856-20482/com.google.android.exoplayer2.demo I/System.out: Check isMmsSendPdu
04-09 03:54:47.430 19856-20482/com.google.android.exoplayer2.demo I/System.out: [OkHttp] sendRequest<<
04-09 03:54:47.454 19856-20486/com.google.android.exoplayer2.demo E/MediaCodec: queueCSDInputBuffer failed w/ error -2006
04-09 03:54:47.456 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: audioDecoderInitialized [1.72, OMX.google.aac.decoder]
04-09 03:54:47.457 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: audioFormatChanged [1.72, id=0, mimeType=audio/mp4a-latm, bitrate=134359, channels=2, sample_rate=44100, language=eng]
04-09 03:54:47.457 19856-20477/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
    android.media.MediaCodec$CryptoException: Operation not supported in this configuration
       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2637)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:942)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:552)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
04-09 03:54:47.483 19856-20477/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Stop failed.
    android.media.MediaCodec$CryptoException: Operation not supported in this configuration
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2072)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:497)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:451)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onDisabled(MediaCodecAudioRenderer.java:376)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:150)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:865)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:790)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:362)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
04-09 03:54:47.492 19856-19856/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [1.75]
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:360)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.media.MediaCodec$CryptoException: Operation not supported in this configuration
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2637)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:942)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:552)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
04-09 03:54:47.494 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: videoDisabled [1.76]
04-09 03:54:47.507 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: audioDisabled [1.77]
04-09 03:54:47.508 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: loading [false]
04-09 03:54:47.526 19856-19867/com.google.android.exoplayer2.demo I/zygote: Background concurrent copying GC freed 2914(293KB) AllocSpace objects, 1(68KB) LOS objects, 24% free, 3MB/4MB, paused 188us total 177.310ms
04-09 03:54:47.528 19856-19856/com.google.android.exoplayer2.demo D/EventLogger: state [1.79, true, I]
```

**Comment by erdemguven** [comment]
What's the model of the device? Does it play any other WV content?

**Comment by giladna** [comment]
@erdemguven 

The model is Hewawi Android go new device which cant play WV modular 
```
"RELEASE": "8.1.0",
"SDK_INT": 27,
"BRAND": "google",
"MODEL": "gobo",
"MANUFACTURER": "alps",
"TAGS": "dev-keys",
"FINGERPRINT": "google/gobo/gobo:8.1.0/OMB1.171031.003/4428322:user/**dev-keys**",
```

```
   "drm": {
        "modular": {
            "widevine": {
                "properties": {
                    "vendor": "Google",
                    "version": "v5.1.0-android",
                    "description": "Widevine CDM",
                    "algorithms": "AES/CBC/NoPadding,HmacSHA256",
                    "securityLevel": "L3",
                    "systemId": "4445",
                    "privacyMode": "disable",
                    "sessionSharing": "disable",
                    "usageReportingSupport": "True",
                    "appId": "",
                    "origin": "",
                    "hdcpLevel": "Unprotected",
                    "maxHdcpLevel": "Unprotected",
                    "maxNumberOfSessions": "16",
                    "numberOfOpenSessions": "0",
                    "deviceUniqueId": "czZNQLkP9C4IOI0FhacV9kF7b5GxRbau9fwYPk5mwaw=",
                    "provisioningUniqueId": "jMmyv0bwC9H3x3L6eljqCb6EkG5OuklRCgPnwbGZPlM=",
                    "serviceCertificate": ""
                },
```

**Comment by erdemguven** [comment]
Is it Huawei Y5 Lite?

**Comment by giladna** [comment]
@erdemguven 
@wvpaf 

this device can play drm on ExoPlayer 2.6.0 so seems some logic is broken now.

Sending the device details in mail
this is new device.

**Comment by giladna** [comment]
@erdemguven 
any update about this?

10x

**Comment by jt64** [comment]
Devices that are security level L3, as is confirmed in your drm device info, are not able to play content that requires a secure data path.

   "drm": {
        "modular": {
            "widevine": {
                "properties": {
                    "securityLevel": "L3",  <----------------- This shows device security level

The ExoPlayer test case "WV: Secure SD content" requires a secure data path, so this is working as intended.
