### ISSUE TITLE
Cast Extension: HLS master.m3u8 not playing on ChromeCast

### ISSUE THREAD

**Issue by drayan85** [google/ExoPlayer#4110]
### Issue description
When we try to cast the HLS streaming using 'master.m3u8' file not playing on ChromeCast Device

```
#EXTM3U
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,PROGRAM-ID=1,BANDWIDTH=328731,RESOLUTION=640x360
364586918.mp4.m3u8
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,PROGRAM-ID=1,BANDWIDTH=1127062,RESOLUTION=1280x720
364586926.mp4.m3u8
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,PROGRAM-ID=1,BANDWIDTH=323929,RESOLUTION=480x270
364586924.mp4.m3u8
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,PROGRAM-ID=1,BANDWIDTH=2942239,RESOLUTION=1920x1080
364586922.mp4.m3u8
```

### Reproduction steps
In Cast demo app: DemoUtil.java
//App sample static block
``samples.add(new Sample("will provide the url via email", "Testing (HLS)", MIME_TYPE_HLS));``

### Link to test content
HLS file link has been sent via email

### Version of ExoPlayer being used
release-v2

### Device(s) and version(s) of Android being used
Nexus 6P
Android version 8.1.0
api 'com.google.android.gms:play-services-cast-framework:11.4.2' 

### A full bug report captured from the device
```
04-11 14:42:03.039 25574-25574/? I/zygote64: Late-enabling -Xcheck:jni
04-11 14:42:03.369 25574-25574/com.google.android.exoplayer2.castdemo I/InstantRun: starting instant run server: is main process
04-11 14:42:03.526 25574-25574/com.google.android.exoplayer2.castdemo V/MediaRouter: Adding route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
04-11 14:42:03.530 25574-25574/com.google.android.exoplayer2.castdemo V/MediaRouter: Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
04-11 14:42:03.537 25574-25574/com.google.android.exoplayer2.castdemo I/MediaRouter: Found default route: MediaRouter.RouteInfo{ uniqueId=android/.support.v7.media.SystemMediaRouteProvider:DEFAULT_ROUTE, name=Phone, description=null, iconUri=null, enabled=true, connecting=false, connectionState=0, canDisconnect=false, playbackType=0, playbackStream=3, deviceType=0, volumeHandling=1, volume=0, volumeMax=15, presentationDisplayId=-1, extras=null, settingsIntent=null, providerPackageName=android }
    Unselecting the current route because it is no longer selectable: null
04-11 14:42:03.549 25574-25574/com.google.android.exoplayer2.castdemo W/zygote64: Unsupported class loader
04-11 14:42:03.551 25574-25574/com.google.android.exoplayer2.castdemo W/zygote64: Skipping duplicate class check due to unsupported classloader
04-11 14:42:03.553 25574-25574/com.google.android.exoplayer2.castdemo I/DynamiteModule: Considering local module com.google.android.gms.cast.framework.dynamite:0 and remote module com.google.android.gms.cast.framework.dynamite:215
    Selected remote version of com.google.android.gms.cast.framework.dynamite, version >= 215
04-11 14:42:03.581 25574-25574/com.google.android.exoplayer2.castdemo W/zygote64: Unsupported class loader
04-11 14:42:03.583 25574-25574/com.google.android.exoplayer2.castdemo W/zygote64: Skipping duplicate class check due to unsupported classloader
04-11 14:42:03.598 25574-25574/com.google.android.exoplayer2.castdemo I/CastDynamiteModuleImpl: ua created by ClassLoader ae[DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/0000005a/DynamiteModulesC_GmsCore_prodmnc_alldpi_release.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/0000005a/n/arm64-v8a, /system/lib64, /vendor/lib64]]].
04-11 14:42:03.980 25574-25579/com.google.android.exoplayer2.castdemo I/zygote64: Do partial code cache collection, code=29KB, data=28KB
    After code cache collection, code=29KB, data=28KB
    Increasing code cache capacity to 128KB
04-11 14:42:03.981 25574-25579/com.google.android.exoplayer2.castdemo I/zygote64: Compiler allocated 4MB to compile void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int)
04-11 14:42:03.985 25574-25579/com.google.android.exoplayer2.castdemo I/zygote64: Do partial code cache collection, code=61KB, data=36KB
04-11 14:42:03.985 25574-25579/com.google.android.exoplayer2.castdemo I/zygote64: After code cache collection, code=61KB, data=36KB
    Increasing code cache capacity to 256KB
04-11 14:42:04.029 25574-25574/com.google.android.exoplayer2.castdemo I/ExoPlayerImpl: Init f5f3774 [ExoPlayerLib/2.7.2] [angler, Nexus 6P, Huawei, 27]
04-11 14:42:04.071 25574-25630/com.google.android.exoplayer2.castdemo D/OpenGLRenderer: HWUI GL Pipeline
04-11 14:42:04.079 25574-25574/com.google.android.exoplayer2.castdemo V/MediaRouter: Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
04-11 14:42:04.128 25574-25630/com.google.android.exoplayer2.castdemo I/Adreno: QUALCOMM build                   : 8e59954, I0be83d0d26
    Build Date                       : 09/22/17
    OpenGL ES Shader Compiler Version: EV031.21.02.00
    Local Branch                     : O17A
    Remote Branch                    :
    Remote Branch                    :
    Reconstruct Branch               :
04-11 14:42:04.130 25574-25630/com.google.android.exoplayer2.castdemo D/vndksupport: Loading /vendor/lib64/hw/gralloc.msm8994.so from current namespace instead of sphal namespace.
04-11 14:42:04.138 25574-25630/com.google.android.exoplayer2.castdemo I/Adreno: PFP: 0x00000000, ME: 0x00000000
04-11 14:42:04.147 25574-25630/com.google.android.exoplayer2.castdemo I/zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
04-11 14:42:04.148 25574-25630/com.google.android.exoplayer2.castdemo I/OpenGLRenderer: Initialized EGL, version 1.4
04-11 14:42:04.148 25574-25630/com.google.android.exoplayer2.castdemo D/OpenGLRenderer: Swap behavior 2
04-11 14:42:04.235 25574-25630/com.google.android.exoplayer2.castdemo D/vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
04-11 14:42:04.236 25574-25630/com.google.android.exoplayer2.castdemo D/vndksupport: Loading /vendor/lib64/hw/gralloc.msm8994.so from current namespace instead of sphal namespace.
04-11 14:42:04.384 25574-25574/com.google.android.exoplayer2.castdemo V/MediaRouter: Adding route: UserRouteInfo{ name=MY Chromecast, description=Chromecast, status=null, category=RouteCategory{ name=Devices types=ROUTE_TYPE_USER  groupable=false }, supportedTypes=ROUTE_TYPE_USER , presentationDisplay=null }
04-11 14:42:06.695 25574-25579/com.google.android.exoplayer2.castdemo I/zygote64: Do full code cache collection, code=89KB, data=89KB
04-11 14:42:06.696 25574-25579/com.google.android.exoplayer2.castdemo I/zygote64: After code cache collection, code=86KB, data=65KB
04-11 14:42:08.066 25574-25725/com.google.android.exoplayer2.castdemo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
04-11 14:42:08.846 25574-25630/com.google.android.exoplayer2.castdemo D/OpenGLRenderer: endAllActiveAnimators on 0x7d76c52400 (ListView) with handle 0x7d84cd1240
04-11 14:42:08.932 25574-25579/com.google.android.exoplayer2.castdemo I/zygote64: Do partial code cache collection, code=105KB, data=88KB
    After code cache collection, code=105KB, data=88KB
    Increasing code cache capacity to 512KB
    Compiler allocated 6MB to compile void android.view.ViewRootImpl.performTraversals()
04-11 14:42:13.111 25574-25628/com.google.android.exoplayer2.castdemo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
04-11 14:42:13.125 25574-25628/com.google.android.exoplayer2.castdemo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
04-11 14:42:13.244 25574-25826/com.google.android.exoplayer2.castdemo D/SurfaceUtils: connecting to surface 0x7d76d41010, reason connectToSurface
04-11 14:42:13.245 25574-25826/com.google.android.exoplayer2.castdemo I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 26187777
04-11 14:42:13.245 25574-25826/com.google.android.exoplayer2.castdemo D/SurfaceUtils: disconnecting from surface 0x7d76d41010, reason connectToSurface(reconnect)
    connecting to surface 0x7d76d41010, reason connectToSurface(reconnect)
04-11 14:42:13.270 25574-25827/com.google.android.exoplayer2.castdemo D/SurfaceUtils: set up nativeWindow 0x7d76d41010 for 640x360, color 0x7fa30c04, rotation 0, usage 0x42002900
04-11 14:42:13.289 25574-25837/com.google.android.exoplayer2.castdemo I/ACodec: codec does not support config priority (err -2147483648)
04-11 14:42:13.308 25574-25827/com.google.android.exoplayer2.castdemo D/SurfaceUtils: set up nativeWindow 0x7d76d41010 for 640x368, color 0x7fa30c04, rotation 0, usage 0x42002900
04-11 14:42:13.369 25574-25628/com.google.android.exoplayer2.castdemo D/AudioTrack: Client defaulted notificationFrames to 6000 for frameCount 12000
04-11 14:42:13.442 25574-25574/com.google.android.exoplayer2.castdemo V/MediaRouter: onRestoreRoute() : route=RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
04-11 14:42:13.443 25574-25574/com.google.android.exoplayer2.castdemo V/MediaRouter: Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
04-11 14:42:15.342 25574-25579/com.google.android.exoplayer2.castdemo I/zygote64: Do full code cache collection, code=247KB, data=175KB
04-11 14:42:15.343 25574-25579/com.google.android.exoplayer2.castdemo I/zygote64: After code cache collection, code=243KB, data=139KB
04-11 14:42:17.867 25574-25579/com.google.android.exoplayer2.castdemo I/zygote64: Do partial code cache collection, code=250KB, data=149KB
    After code cache collection, code=250KB, data=149KB
    Increasing code cache capacity to 1024KB
04-11 14:42:21.637 25574-25574/com.google.android.exoplayer2.castdemo V/MediaRouter: Selecting route: UserRouteInfo{ name=MY Chromecast, description=Chromecast, status=null, category=RouteCategory{ name=Devices types=ROUTE_TYPE_USER  groupable=false }, supportedTypes=ROUTE_TYPE_USER , presentationDisplay=null }
04-11 14:42:21.666 25574-25574/com.google.android.exoplayer2.castdemo I/DynamiteModule: Considering local module com.google.android.gms.cast.framework.dynamite:0 and remote module com.google.android.gms.cast.framework.dynamite:215
    Selected remote version of com.google.android.gms.cast.framework.dynamite, version >= 215
04-11 14:42:21.676 25574-25574/com.google.android.exoplayer2.castdemo I/CastDynamiteModuleImpl: ua created by ClassLoader ae[DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/0000005a/DynamiteModulesC_GmsCore_prodmnc_alldpi_release.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/0000005a/n/arm64-v8a, /system/lib64, /vendor/lib64]]].
04-11 14:42:21.682 25574-25574/com.google.android.exoplayer2.castdemo I/DynamiteModule: Considering local module com.google.android.gms.cast.framework.dynamite:0 and remote module com.google.android.gms.cast.framework.dynamite:215
    Selected remote version of com.google.android.gms.cast.framework.dynamite, version >= 215
04-11 14:42:21.688 25574-25574/com.google.android.exoplayer2.castdemo I/CastDynamiteModuleImpl: ua created by ClassLoader ae[DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/0000005a/DynamiteModulesC_GmsCore_prodmnc_alldpi_release.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/0000005a/n/arm64-v8a, /system/lib64, /vendor/lib64]]].
04-11 14:42:22.303 25574-25826/com.google.android.exoplayer2.castdemo D/SurfaceUtils: connecting to surface 0x7d76c35010, reason connectToSurface
04-11 14:42:22.303 25574-25826/com.google.android.exoplayer2.castdemo I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 26187778
04-11 14:42:22.303 25574-25826/com.google.android.exoplayer2.castdemo D/SurfaceUtils: disconnecting from surface 0x7d76c35010, reason connectToSurface(reconnect)
    connecting to surface 0x7d76c35010, reason connectToSurface(reconnect)
04-11 14:42:22.304 25574-25827/com.google.android.exoplayer2.castdemo D/SurfaceUtils: set up nativeWindow 0x7d76c35010 for 640x368, color 0x7fa30c04, rotation 0, usage 0x42002900
04-11 14:42:22.304 25574-25826/com.google.android.exoplayer2.castdemo D/SurfaceUtils: disconnecting from surface 0x7d76d41010, reason disconnectFromSurface
04-11 14:42:22.323 25574-25826/com.google.android.exoplayer2.castdemo D/SurfaceUtils: disconnecting from surface 0x7d76c35010, reason disconnectFromSurface
```

**Comment by AquilesCanta** [comment]
Thanks for your report! [internal ref: b/64523754].

**Comment by drayan85** [comment]
Any updates @AquilesCanta ?

**Comment by AquilesCanta** [comment]
Hi @drayan85, sorry for the delay. Just now have I received an update from the cast team. Mp4 segment support is under development on their side, so there is not much we cannot do about it. I just wanted to confirm the format of the segments, but seems that the segments have been removed from the server.

**Comment by drayan85** [comment]
@AquilesCanta Thanks, Still the link which I have sent via email is working on my end (On Safari Browser I can play the HLS file using their inbuilt HLS player). I have resent the email again with One more our hosted HLS file URL and hosted URL has h264 segment which is also not working in ChromeCast.

**Comment by AquilesCanta** [comment]
Thanks for the streams. They are indeed transport streams. I will post any findings here. Thanks for your patience.

**Comment by Milananas** [comment]
We are experiencing the same issues on our platform with HLS packaged mp4 streams with JWPlayer, as described in [this](https://github.com/jwplayer/jwplayer/issues/2815) issue. Strangely casting to Chromecast does work with Shaka-Player.

**Comment by AquilesCanta** [comment]
> Strangely casting to Chromecast does work with Shaka-Player.

With HLS+mp4 segments? According to the cast team, this is under development.

**Comment by DutchChannels** [comment]
Yes, hghazzi mentioned in that thread that it works because the Shaka-Player uses a custom receiver.

**Comment by Milananas** [comment]
Yes, hghazzi mentioned in that thread that it works because the Shaka-Player uses a custom receiver.

**Comment by AquilesCanta** [comment]
We might see if casting to the shaka receiver app is an option for our own demo app.

**Comment by drayan85** [comment]
I have found some more information.

In the `PlayerManger.java` modified the method to catch the actual error as follows.
```
public void addItem(Sample sample) {
     mediaQueue.add(sample);
     if (currentPlayer == exoPlayer) {
         dynamicConcatenatingMediaSource.addMediaSource(buildMediaSource(sample));
     } else {
         try{
             castPlayer.addItems(buildMediaQueueItem(sample));
         }catch(Exception e){
             e.printStackTrace();
         }
     }
 }
```

After that when I tired the same URL which I have sent via email, I am getting following logs.

```
04-20 11:15:51.002 13227-13227/com.google.android.exoplayer2.castdemo W/MediaControlChannel: received unexpected error: Invalid Request.
04-20 11:15:51.034 13227-13227/com.google.android.exoplayer2.castdemo E/MediaNotificationServiceImpl: Unregistering trampoline BroadcastReceiver failed
    java.lang.IllegalArgumentException: Receiver not registered: xt@ef9ba9f
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1193)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1449)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:645)
        at xs.b(:com.google.android.gms.dynamite_dynamitemodulesc@12529021@12.5.29 (040400-192802242):111)
        at xk.onTransact(:com.google.android.gms.dynamite_dynamitemodulesc@12529021@12.5.29 (040400-192802242):22)
        at android.os.Binder.transact(Binder.java:627)
        at com.google.android.gms.internal.zzeb.zzb(Unknown Source:7)
        at com.google.android.gms.cast.framework.media.zze.onDestroy(Unknown Source:5)
        at com.google.android.gms.cast.framework.media.MediaNotificationService.onDestroy(Unknown Source:2)
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3504)
        at android.app.ActivityThread.-wrap26(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1697)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by AquilesCanta** [comment]
Is your app crashing when you try to play HLS streams? If addItems was actually throwing, and you removed that try, the app would crash as things are right now. Are you sure the origin of the logging is not the Cast framework internals?

**Comment by drayan85** [comment]
> Is your app crashing when you try to play HLS streams?

No App is not crashing.

> If addItems was actually throwing, and you removed that try, the app would crash as things are right now.
 
Even if I remove the try catch block, it will not crash the app or either it will not print any error logs( Logs will look like as I posted in the first place).

> Are you sure the origin of the logging is not the Cast framework internals?

I guess the error is from exoplayer itself since I can see error logs starting from  `MediaControlChannel ` &`MediaNotificationServiceImpl`
```
04-20 11:15:51.002 13227-13227/com.google.android.exoplayer2.castdemo W/MediaControlChannel: received unexpected error: Invalid Request.
04-20 11:15:51.034 13227-13227/com.google.android.exoplayer2.castdemo E/MediaNotificationServiceImpl: Unregistering trampoline BroadcastReceiver failed
```
So I couldn't find what went wrong. So I was trying to understand what is exactly went wrong. That's why I add that try catch block to see the error logs.

**Comment by AquilesCanta** [comment]
(sorry for the if/try confusion, I have edited the comments by replacing if with try, as you correctly interpreted). Both MediaControlChannel and MediaNotificationServiceImpl are cast classes, they are not part of ExoPlayer.

Have you by chance tried playing using shaka? We are considering moving away from the default receiver app towards either the shaka receiver app (if possible) or an end-to-end solution (by implementing our own receiver app using shaka). In this case we are going to be able to provide much better support for the cast extension.

Regarding the try catch, please double check the catch block is actually executing at any point.

**Comment by drayan85** [comment]
> Regarding the try catch, please double check the catch block is actually executing at any point.

Sorry my bad I couldn't reproduce error logs now.  I think I was wrong. Now I am only getting below log.

```
04-20 18:24:03.829 4867-4867/com.google.android.exoplayer2.castdemo W/MediaControlChannel: received unexpected error: Invalid Request.
```

**Comment by drayan85** [comment]
Any updates @AquilesCanta ?

**Comment by AquilesCanta** [comment]
Unfortunately, no. We are working on it, though. Thanks for your patience. It may still take some more time.

**Comment by drayan85** [comment]
Any updates @AquilesCanta?

**Comment by AquilesCanta** [comment]
Hi @drayan85, the stream sent to us via e-mail with the subject "Issue #4110" seem to be working as intended. Both locally (played using ExoPlayer) and casted. Feel free to try them in the demo app. Could you please verify this? Post below if you encounter any issues, and I will reopen this.

**Comment by AquilesCanta** [comment]
If you do encounter issues, don't forget to include precise repro steps, please. Thanks!

**Comment by drayan85** [comment]
@AquilesCanta Now it is working with ExoPlayer v2.10.2. Thanks
