### ISSUE TITLE
exoPlayer how can i use for encrypted url widevine dash 

### ISSUE THREAD

**Issue by luckylook** [google/ExoPlayer#4122]
i have licesnce and url manifest mpd video 
I do not understand where I should insert the url to get streaming dcrypted key
please help 
thx

**Comment by erdemguven** [comment]
Please loot at https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java
and see how the value passed by DRM_LICENSE_URL is used.

**Comment by luckylook** [comment]
i did it because of that i ask what wrong i have my license and my video
uri

"name": "zion 2",
"uri": "my video manifest dash file",
"drm_license_url": "my license",
"drm_scheme": "widevine",


in this situation i get this error

 playerFailed [5.89]

        com.google.android.exoplayer2.ExoPlaybackException

            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.shouldWaitForKeys(MediaCodecRenderer.java:836)

            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:733)

            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:568)

            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)

            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)

            at android.os.Handler.dispatchMessage(Handler.java:101)

            at android.os.Looper.loop(Looper.java:164)

            at android.os.HandlerThread.run(HandlerThread.java:65)

         Caused by:
com.google.android.exoplayer2.drm.DrmSession$DrmSessionException:
com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException:
Response code: 415

            at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:440)

            at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:435)

            at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:383)

            at com.google.android.exoplayer2.drm.DefaultDrmSession.access$200(DefaultDrmSession.java:40)

            at com.google.android.exoplayer2.drm.DefaultDrmSession$PostResponseHandler.handleMessage(DefaultDrmSession.java:497)

            at android.os.Handler.dispatchMessage(Handler.java:105)

            at android.os.Looper.loop(Looper.java:164)

            at android.os.HandlerThread.run(HandlerThread.java:65)

         Caused by:
com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException:
Response code: 415

            at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)

            at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)

            at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)

            at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)

            at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:124)

            at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:145)

            at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:130)

            at com.google.android.exoplayer2.drm.DefaultDrmSession$PostRequestHandler.handleMessage(DefaultDrmSession.java:528)

            at android.os.Handler.dispatchMessage(Handler.java:105)

            at android.os.Looper.loop(Looper.java:164)

            at android.os.HandlerThread.run(HandlerThread.java:65)

and if i remove the widevine scheme none playable for this device my
device is oneplus 5t oreo version

checked also in samsung galaxy 5 6 7


thx



2018-04-15 23:49 GMT+03:00 Erdem Guven <notifications@github.com>:

**Comment by ojw28** [comment]
This is tracked by #4125

**Comment by luckylook** [comment]
what info do u need?

**Comment by luckylook** [comment]
dear ojw28,

i am having an issue playing my encrypted url widevine stream.
right now i am getting only the time length of the video and able to play
it without any view or sound, and no exceptions.
can you please tell me what else do i need to build in order to play it
properly? or for that matter, have you encountered with this problem in the
past?

thank you for all your help

liri or
head of office


2018-04-16 13:01 GMT+03:00 ojw28 <notifications@github.com>:

**Comment by ojw28** [comment]
Please wait for an update on #4125. Thanks.
