### ISSUE TITLE
Cannot play .mp4 videos

### ISSUE THREAD

**Issue by FirdousNath** [google/ExoPlayer#4124]
[this is same as #3953 ](https://github.com/google/ExoPlayer/issues/3953)

```
AppsFlyer_4.5.0: data: {"device":"Q350","firstLaunchDate":"2018-04-10_2330+0530","installDate":"2018-04-10_2324+0530","sdk":"23","carrier":"BSNL Mobile",,"date1":"2018-04-10_2324+0530","af_preinstalled":"false","advertiserIdEnabled":"true","iaecounter":"0","lang_code":"en","appsflyerKey":"zn****************8TE7","app_version_name":"1.5","lang":"English","timepassedsincelastlaunch":"11","dkh":"znjKLA4s","advertiserId":"b6ae9653-5753-4ba6-b6a6-ed60cc31b6fe","isGaidWithGps":"true","deviceType":"user","af_v":"4a9c3c8442d152a2e85175a5523f9449fd6b6c3d","app_version_code":"6","af_events_api":"1","platformextension":"android_native","network":"MOBILE","operator":"BSNL Mobile","country":"US","date2":"2018-04-10_2324+0530","brand":"Micromax","af_timestamp":"1523613114187","uid":"1523382873665-422522010808811980","isFirstCall":"true","counter":"81","model":"Micromax Q350","product":"Q350"}

04-13 15:21:54.565  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = false, this = android.widget.VideoView{6a8055a GFE...... ......I. 0,0-0,0 #7f0e04b3 app:id/video}
04-13 15:21:54.566  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{d9446b9 V.E...... ......ID 0,0-854,480}
04-13 15:21:54.566  7864  7864 I SurfaceView: Changes: creating=false format=false size=false visible=false left=false top=false mUpdateWindowNeeded=true mReportDrawNeeded=true redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=true, this = android.view.SurfaceView{d9446b9 V.E...... ......ID 0,0-854,480}
04-13 15:21:54.566  7864  7864 I SurfaceView: Cur surface: Surface(name=null)/@0x2f6c034, this = android.view.SurfaceView{d9446b9 V.E...... ......ID 0,0-854,480}
04-13 15:21:54.569  7864  7864 I SurfaceView: New surface: Surface(name=null)/@0xe043ca3, vis=true, frame=Rect(0, 0 - 854, 480), this = android.view.SurfaceView{d9446b9 V.E...... ......ID 0,0-854,480}
04-13 15:21:54.570  7864  7864 I SurfaceView: surfaceRedrawNeeded, this = android.view.SurfaceView{d9446b9 V.E...... ......ID 0,0-854,480}
04-13 15:21:54.570  7864  7864 I SurfaceView: finishedDrawing, this = android.view.SurfaceView{d9446b9 V.E...... ......ID 0,0-854,480}
04-13 15:21:54.570  7864  7864 V SurfaceView: Layout: x=0 y=0 w=854 h=480, frame=Rect(0, 0 - 854, 480), this = android.view.SurfaceView{d9446b9 V.E...... ......ID 0,0-854,480}
04-13 15:21:54.572  7864  7864 I SurfaceView: Punch a hole(dispatchDraw), w = 854, h = 480, this = android.view.SurfaceView{d9446b9 V.E...... ........ 0,0-854,480}
04-13 15:21:54.591  7864  7864 I SurfaceView: updateWindow -- UPDATE_WINDOW_MSG, this = Handler (android.view.SurfaceView$1) {24bf2da}
04-13 15:21:54.741  7864  7864 I SurfaceView: updateWindow -- setFrame, this = android.view.SurfaceView{d9446b9 V.E...... ......I. 0,0-854,480}
04-13 15:21:54.742  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = false, this = android.widget.VideoView{6a8055a GFE...... ......I. 0,0-0,0 #7f0e04b3 app:id/video}
04-13 15:21:54.742  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{d9446b9 V.E...... ......I. 0,0-854,480}
04-13 15:21:54.743  7864  7864 I SurfaceView: Punch a hole(dispatchDraw), w = 854, h = 480, this = android.view.SurfaceView{d9446b9 V.E...... ........ 0,0-854,480}
04-13 15:21:54.889  7864  7864 I SurfaceView: updateWindow -- setFrame, this = android.view.SurfaceView{d9446b9 V.E...... ......I. 0,0-854,480}
04-13 15:21:54.889  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = false, this = android.widget.VideoView{6a8055a GFE...... ......I. 0,0-0,0 #7f0e04b3 app:id/video}
04-13 15:21:54.889  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{d9446b9 V.E...... ......I. 0,0-854,480}
04-13 15:21:54.890  7864  7864 I SurfaceView: Punch a hole(dispatchDraw), w = 854, h = 480, this = android.view.SurfaceView{d9446b9 V.E...... ........ 0,0-854,480}
04-13 15:21:54.906  7864  8109 D libc-netbsd: [getaddrinfo]: hostname=t.appsflyer.com; servname=(null); netid=0; mark=0
04-13 15:21:54.906  7864  8109 D libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
04-13 15:21:55.564  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = false, this = android.widget.VideoView{6a8055a GFE...... ......I. 0,0-0,0 #7f0e04b3 app:id/video}
04-13 15:21:55.564  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{d9446b9 V.E...... ........ 0,0-854,480}
04-13 15:21:56.568  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = false, this = android.widget.VideoView{6a8055a GFE...... ......I. 0,0-0,0 #7f0e04b3 app:id/video}
04-13 15:21:56.568  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{d9446b9 V.E...... ........ 0,0-854,480}
04-13 15:21:56.895  7864  8110 E NativeCrypto: ssl=0xb94902f0 cert_verify_callback x509_store_ctx=0x9d722d2c arg=0x0
04-13 15:21:56.895  7864  8110 E NativeCrypto: ssl=0xb94902f0 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
04-13 15:21:57.157  7864  8109 D AppsFlyer_4.5.0: response code: 404
04-13 15:21:57.574  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = false, this = android.widget.VideoView{6a8055a GFE...... ......I. 0,0-0,0 #7f0e04b3 app:id/video}
04-13 15:21:57.576  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{d9446b9 V.E...... ........ 0,0-854,480}
04-13 15:21:58.596  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = false, this = android.widget.VideoView{6a8055a GFE...... ......I. 0,0-0,0 #7f0e04b3 app:id/video}
04-13 15:21:58.596  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{d9446b9 V.E...... ........ 0,0-854,480}
04-13 15:21:59.498  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = false, this = android.widget.VideoView{6a8055a GFE...... ......I. 0,0-0,0 #7f0e04b3 app:id/video}
04-13 15:21:59.498  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{d9446b9 V.E...... ........ 0,0-854,480}
04-13 15:21:59.545  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = false, this = android.widget.VideoView{6a8055a GFE...... ......I. 0,0-0,0 #7f0e04b3 app:id/video}
04-13 15:21:59.545  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{d9446b9 V.E...... ........ 0,0-854,480}
04-13 15:22:06.702  7864  8119 D SurfaceUtils: set up nativeWindow 0xb973ba38 for 1280x720, color 0x23, rotation 0, usage 0x2933
04-13 15:22:06.870  7864  8125 E ACodec  : cannot find aac bit rate
04-13 15:22:06.871  7864  8125 E OMXNodeInstance: getParameter(1:google.aac.decoder, ??(0x7f200406)) ERROR: UnsupportedIndex(0x8000101a)
04-13 15:22:06.877  7864  8119 E ACodec  : [OMX.MTK.VIDEO.DECODER.AVC] ERROR(0x80001005)
04-13 15:22:06.877  7864  8119 E ACodec  : signalError(omxError 0x80001005, internalError -2147483648)
04-13 15:22:06.878  7864  8118 E MediaCodec: Codec reported err 0xfffffbb1, actionCode 0, while in state 6
04-13 15:22:06.879  7864  8126 I hexdump : 00000000:  11 90                                             ..
04-13 15:22:06.896  7864  8108 E ExoPlayerImplInternal: Internal runtime error.
04-13 15:22:06.896  7864  8108 E ExoPlayerImplInternal: java.lang.IllegalStateException
04-13 15:22:06.896  7864  8108 E ExoPlayerImplInternal: 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
04-13 15:22:06.896  7864  8108 E ExoPlayerImplInternal: 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2392)
04-13 15:22:06.896  7864  8108 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:899)
04-13 15:22:06.896  7864  8108 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:510)
04-13 15:22:06.896  7864  8108 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
04-13 15:22:06.896  7864  8108 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
04-13 15:22:06.896  7864  8108 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-13 15:22:06.896  7864  8108 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:207)
04-13 15:22:06.896  7864  8108 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
04-13 15:22:06.904  7864  8119 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb9315ca0
04-13 15:22:06.906  7864  8119 E ACodec  : failed to cancel buffer from native window: 0xb973ba38, err = -22
04-13 15:22:06.908  7864  8119 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb9332a00
04-13 15:22:06.908  7864  8119 E ACodec  : failed to cancel buffer from native window: 0xb973ba38, err = -22
04-13 15:22:06.914  7864  8119 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb9680508
04-13 15:22:06.915  7864  8119 E ACodec  : failed to cancel buffer from native window: 0xb973ba38, err = -22
04-13 15:22:06.934  7864  8108 E ExoPlayerImplInternal: Stop failed.
04-13 15:22:06.934  7864  8108 E ExoPlayerImplInternal: java.lang.IllegalStateException
04-13 15:22:06.934  7864  8108 E ExoPlayerImplInternal: 	at android.media.MediaCodec.native_stop(Native Method)
04-13 15:22:06.934  7864  8108 E ExoPlayerImplInternal: 	at android.media.MediaCodec.stop(MediaCodec.java:1914)
04-13 15:22:06.934  7864  8108 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:455)
04-13 15:22:06.934  7864  8108 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:409)
04-13 15:22:06.934  7864  8108 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:283)
04-13 15:22:06.934  7864  8108 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:145)
04-13 15:22:06.934  7864  8108 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:709)
04-13 15:22:06.934  7864  8108 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:684)
04-13 15:22:06.934  7864  8108 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:364)
04-13 15:22:06.934  7864  8108 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-13 15:22:06.934  7864  8108 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:207)
04-13 15:22:06.934  7864  8108 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
04-13 15:22:06.960  7864  7864 I TEST    : onLoadingChanged: false
04-13 15:22:06.960  7864  7864 I TEST    : Buffered Position: 128
04-13 15:22:06.960  7864  7864 I TEST    : Buffered Percentage: 0
04-13 15:22:06.970  7864  7864 I TEST    : ExoPlayer State is: IDLE
04-13 15:22:06.979  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = false, this = android.widget.VideoView{6a8055a GFE...... ......I. 0,0-0,0 #7f0e04b3 app:id/video}
04-13 15:22:06.980  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{d9446b9 V.E...... ........ 0,0-854,480}
04-13 15:22:07.165  7864  7864 D usershow: 13000
04-13 15:22:07.184  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = false, this = android.widget.VideoView{6a8055a GFE...... ......I. 0,0-0,0 #7f0e04b3 app:id/video}
04-13 15:22:07.185  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{d9446b9 V.E...... ........ 0,0-854,480}
04-13 15:22:10.197  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = false, this = android.widget.VideoView{6a8055a GFE...... ......I. 0,0-0,0 #7f0e04b3 app:id/video}
04-13 15:22:10.197  7864  7864 I SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{d9446b9 V.E...... ........ 0,0-854,480}
04-13 15:22:14.910  7864  7864 I TEST    : ExoPlayer State is: IDLE
```

**Comment by erdemguven** [comment]
Please add any new information to the original issue instead of opening new issues.
