### ISSUE TITLE
can't play dash protected widevine video in exoplayer get Error

### ISSUE THREAD

**Issue by luckylook** [google/ExoPlayer#4125]
hi 
i am trying to play protected video and i get exoPlaybackException idunno why
i have the license i passed it HttpMediaDrmCallback to my DefaultDrmSessionManager

```
E/ExoPlayerImplInternal: Renderer error.
                                                                                    com.google.android.exoplayer2.ExoPlaybackException
                                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.shouldWaitForKeys(MediaCodecRenderer.java:836)
                                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:733)
                                                                                        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:568)
                                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
                                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                                        at android.os.Looper.loop(Looper.java:164)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:65)
                                                                                     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 415
                                                                                        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:440)
                                                                                        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:435)
                                                                                        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:383)
                                                                                        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$200(DefaultDrmSession.java:40)
                                                                                        at com.google.android.exoplayer2.drm.DefaultDrmSession$PostResponseHandler.handleMessage(DefaultDrmSession.java:497)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                        at android.os.Looper.loop(Looper.java:164) 
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:65) 
                                                                                     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 415
                                                                                        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                                        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
                                                                                        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)
                                                                                        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)
                                                                                        at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:124)
                                                                                        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:145)
                                                                                        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:130)
                                                                                        at com.google.android.exoplayer2.drm.DefaultDrmSession$PostRequestHandler.handleMessage(DefaultDrmSession.java:528)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                        at android.os.Looper.loop(Looper.java:164) 
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:65) 
```
use 2.7.3 exoplayer version
one plus 5t  - O

**Comment by ojw28** [comment]
The license server is responding with an [http 415 error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415). You'll need to work out why your license server is doing this, and resolve it.

**Comment by luckylook** [comment]
thank you for your quick respond :)
just to make sure, we do see the cleared url from the server. just the
encrypted widevine url is playing but is not showing the view or sound.
do you still think the problem is in the server?

2018-04-16 14:12 GMT+03:00 ojw28 <notifications@github.com>:

**Comment by ojw28** [comment]
I don't understand what this means. The log above indicates a http 415 error. You haven't provided any reproduction steps or a clear description of the problem, beyond what's in the log, and so we are unable to assist further.

**Comment by luckylook** [comment]
forget about the log above
Our ExoPlayer plays cleared url stream perfectly. but if it is with
widevine encrypted then it shows a black screen and no sound.

we have already tried the ExoPlayer example, and bunch of other tries with
no luck.

have you encounter with this problem?

2018-04-16 15:26 GMT+03:00 ojw28 <notifications@github.com>:

**Comment by ojw28** [comment]
> have you encounter with this problem?

Nope!

**Comment by luckylook** [comment]
dear ojw28

i am using the demo app
create a new sample in the json file

{

"name": "zion 2",
"uri": "http://37.142.44.5:5554/sdash/PL141004/5.mpd/Manifest?device=NAGRA-WV-BASE-VOD",
"drm_license_url":
"https://ssolab1.nagra.com/netssp/NETKIM2T/wvls/contentlicenseservice/v1/licenses",
"extension": "mpd"}

and i get this error

04-18 11:50:12.141 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 65536 for video/avc
04-18 11:50:12.141 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
04-18 11:50:12.141 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 524288 for video/avc
04-18 11:50:12.141 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
04-18 11:50:12.150 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 65536 for video/avc
04-18 11:50:12.150 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
04-18 11:50:12.150 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 524288 for video/avc
04-18 11:50:12.150 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
04-18 11:50:12.151 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 65536 for video/avc
04-18 11:50:12.151 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
04-18 11:50:12.151 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 524288 for video/avc
04-18 11:50:12.151 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
04-18 11:50:12.154 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
04-18 11:50:12.155 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
04-18 11:50:12.158 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unsupported mime video/x-ms-wmv
04-18 11:50:12.159 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unsupported mime video/x-ms-wmv
04-18 11:50:12.160 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unsupported mime video/divx
04-18 11:50:12.162 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unsupported mime video/divx311
04-18 11:50:12.163 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unsupported mime video/divx4
04-18 11:50:12.173 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unsupported mime video/mp4v-esdp
04-18 11:50:12.184 11598-11643/com.google.android.exoplayer2.demo
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
04-18 11:50:12.188 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 65536 for video/avc
04-18 11:50:12.188 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
04-18 11:50:12.188 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 524288 for video/avc
04-18 11:50:12.188 11598-11643/com.google.android.exoplayer2.demo
W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc

i check the link of the encrypted video its ok

and also the license

what could be the problem?

thx


2018-04-16 17:05 GMT+03:00 ojw28 <notifications@github.com>:

**Comment by ojw28** [comment]
The sample is playing without audio and video because you haven't specified the DRM scheme in the JSON you've added to the demo app. Add `"drm_scheme": "widevine"` to fix this:

```
"name": "zion 2",
"uri": "http://37.142.44.5:5554/sdash/PL141004/5.mpd/Manifest?device=NAGRA-WV-BASE-VOD",
"drm_scheme": "widevine",
"drm_license_url":
"https://ssolab1.nagra.com/netssp/NETKIM2T/wvls/contentlicenseservice/v1/licenses",
"extension": "mpd"}
```

Once you do this you'll see your license server is responding with 415 status codes, as in your original report. My original advice for that problem still applied:

> The license server is responding with an http 415 error. You'll need to work out why your license server is doing this, and resolve it.

**Comment by luckylook** [comment]
hi ojw28

my boss said that iget 415 beacuse i need to insert a token
where should i put it on the demo?
this is the token...

*Content URL:*



http://37.142.44.5:5554/sdash/PL141004/5.mpd/Manifest?
device=NAGRA-WV-BASE-VOD



*nv-authorizations (http header):*



"eyJraWQiOiI2Nzc3NTkiLCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.
eyJ2ZXIiOiIxLjAiLCJ0eXAiOiJDb250ZW50QXV0aFoiLCJjb250ZW50Umln
aHRzIjpbeyJkZWZhdWx0S2NJZHMiOlsiM2E4ZDRhZGEtNDMyYi00Mjk4LWEw
NTMtMDNmNWE5MmMyOTY2Il0sImNvbnRlbnRJZCI6IlBMMTQxMDA0IiwiZW5j
cnlwdGlvbk1ldGhvZCI6IlJBV19BRVNfMTI4X0NUUl9DRU5DIiwiZGVmYXVs
dFVzYWdlUnVsZXMiOnsibWluTGV2ZWwiOjB9fV19.BTq4edWAdeNYwnNdwpEg3M5hn031-
t0BzWOhQT1vHzs"



*License server URL:*

https://ssolab1.nagra.com/netssp/NETKIM2T/wvls/contentlicenseservice/v1/
licenses


thx


2018-04-18 18:49 GMT+03:00 ojw28 <notifications@github.com>:

**Comment by ojw28** [comment]
If the token is supposed to be specified as a HTTP header on the key request, you can set it using `drm_key_request_properties` in the demo app, as described [here](https://google.github.io/ExoPlayer/demo-application.html). For example:

```
{
  "name": "zion 2",
  "uri": "http://37.142.44.5:5554/sdash/PL141004/5.mpd/Manifest?device=NAGRA-WV-BASE-VOD",
  "drm_scheme": "widevine",
  "drm_license_url":
  "https://ssolab1.nagra.com/netssp/NETKIM2T/wvls/contentlicenseservice/v1/licenses",
  "drm_key_request_properties": {
    "header-name": "header-value"
  },
  "extension": "mpd"
}
```
Further debugging authorization issues to your license server is something you'll need to investigate yourselves, unless you can identify an actual bug in ExoPlayer that you'd like us to address. Thanks!

**Comment by luckylook** [comment]
thx
i am still trying to figure it out
u know something about widevine key or widevine challenge?
i talk with are service that supply the license URL and they succeeded to
play this video with their own Player but its not support AndroidTV so it
doesn't help me :/
any idea?



2018-04-23 1:17 GMT+03:00 ojw28 <notifications@github.com>:

**Comment by ojw28** [comment]
You need to find out why the license server is issuing a 415 response, and resolve that, whether that's by adding a HTTP header to the key request, or by some other means. I don't think there's anything particularly Widevine or ExoPlayer specific about this, it's simply about figuring out why your license server isn't happy with the requests, and resolving that.

**Comment by tbertschi** [comment]
In case it helps, I add a somehow similar issue, and it apparently helped to base64-encode and JSON wrap the widevine license request before sending it to the Nagra SSP server:

Content-Type: application/json 
{ "challenge": "<base64 encoded widevine binary license request>" }

**Comment by luckylook** [comment]
Can i ask you
Where i can find the challenge for all devices?
Thx


בתאריך יום ו׳, 4 במאי 2018, 17:02, מאת tbertschi ‏<notifications@github.com

**Comment by tbertschi** [comment]
Not sure what you mean. All I'm saying is that google CDM returns a license request in binary format, and that, to push it as an HTTPS request to SSP server, you first need to base64 encode that binary request, and encapsulate it in JSON: {"challenge":"Tm90IGEgcmVhbCBsaWNlbnNlIHJlcXVlc3Q="}, then use that as payload of your http challenge request.

What do you mean by challenge for all devices? You mean for all DRMs?

**Comment by luckylook** [comment]
i talked with nagra support and they told me that i need to achieve a
challenge license per device then send Post request
header authorization token that i have
challenge in the body(i dont know from where i can generate that)
and header application/json
my respone will be a license
 to play the video in the exoPlayer

בתאריך יום ו׳, 4 במאי 2018, 17:25, מאת tbertschi ‏<notifications@github.com

**Comment by luckylook** [comment]
hi
i did what you told me now i get license on executePost and i return the
license byte[]
and i get that

05-06 17:53:30.451 28080-28122/com.example.administrator.myapplication
E/ExoPlayerImplInternal: Playback error.

                    com.google.android.exoplayer2.ExoPlaybackException

                        at
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:765)

                        at
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:568)

                        at
com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)

                        at
com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)

                        at
android.os.Handler.dispatchMessage(Handler.java:102)

                        at android.os.Looper.loop(Looper.java:164)

                        at
android.os.HandlerThread.run(HandlerThread.java:65)

                     Caused by: android.media.MediaCodec$CryptoException:
Required output protections are not active

                        at
android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)

                        at
android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2551)

                        at
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:756)

                        at
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:568)

                        at
com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)

                        at
com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)

                        at
android.os.Handler.dispatchMessage(Handler.java:102)

                        at android.os.Looper.loop(Looper.java:164)

                        at
android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by ojw28** [comment]
Judging from `Caused by: android.media.MediaCodec$CryptoException:
Required output protections are not active`, I'd guess the device doesn't support a secure output path, and the license configuration requires one. In other words, the security requirement specified in the license is more stringent than the device is able to support. Hence playback failure is expected.

**Comment by luckylook** [comment]
thanks Ojw28 and tbertschi
now its work on my Huawei device but i cant play it on my OnePlus 5T do you
have any idea?

2018-05-06 19:41 GMT+03:00 ojw28 <notifications@github.com>:

**Comment by ojw28** [comment]
Not all devices support a secure output path, which I suspect is what your license is specifying. To enable playback on such devices, most streaming providers will make lower resolutions of their content available without specifying the need for a secure output path in the license. You can query on device whether a secure output path is provided by obtaining a `DefaultDrmSessionManager`, then doing:
```
String securityLevel = sessionManager.getPropertyString("securityLevel")
```
If `securityLevel` is `L1` then a secure output path is provided. If it's `L3` then one isn't.

By the way, for OnePlus 5T I think you can get a secure output path enabled if you mail them your device. See [this news article](https://www.theverge.com/2018/2/25/17050146/oneplus-5-5t-phone-update-hd-stream-mail-drm-widevine-security).

**Comment by luckylook** [comment]
ok..
i can't mail them for 20,000 devices...
security on Huawei is :L3 and also on OnePlues5T
maybe is the video decryption?

2018-05-07 17:17 GMT+03:00 ojw28 <notifications@github.com>:

**Comment by luckylook** [comment]
thank you very much,the video was encrypted too strongly we reduce it
little bit and now everything ok.
you can close the topic.

בתאריך יום ג׳, 8 במאי 2018, 11:36, מאת zion aronov ‏<aronovzion@gmail.com>:

**Comment by hezie100** [comment]
Hi,
I'd like to have more details on the Exo player specifications, especially on LIVE (channels) DASH streaming.
what's the required video codec ?
what's the required amount of Levels/ bit rates in manifest ?
what's the required chunk size for the segments ?
do I need to set any sliding window for the player to be able to seek in time or not ?
what's the setup required in order to gain the maximum video quality on LIVE DASH with the Exo player ?
thank you!
