### ISSUE TITLE
Playing back MediaStore files using ExtractorSampleSource?

### ISSUE THREAD

**Issue by Nezz** [google/ExoPlayer#413]
MediaStore files have a special uri like this:
`content://media/external/audio/media/269`

How can I play these using the new extractor model?

Using `DefaultUriDataSource` it fails for me with the following error:

```

04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): Internal track renderer error.
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to content://media/external/audio/media/269
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:253)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:115)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
OnPlayerError: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to content://media/external/audio/media/269
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at android.os.Looper.loop(Looper.java:151)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at android.os.HandlerThread.run(HandlerThread.java:60)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to content://media/external/audio/media/269
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:151)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:66)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:598)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:241)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at java.lang.Thread.run(Thread.java:856)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): Caused by: java.net.MalformedURLException: Unknown protocol: content
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at java.net.URL.<init>(URL.java:184)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at java.net.URL.<init>(URL.java:127)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at com.google.android.exoplayer.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:287)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:149)
04-23 23:03:23.869 E/ExoPlayerImplInternal(15932): 	... 8 more
```

**Comment by ptran-gpfw** [comment]
The file path URI needs to be passed in, ie scheme must be 'file://' not 'content://'.
The file URI can be retrieved from the MediaStore URI, perhaps these StackOverflow answers can help:
* http://stackoverflow.com/questions/3401579/get-filename-and-path-from-uri-from-mediastore
* http://stackoverflow.com/questions/26965016/get-file-path-from-uri

**Comment by Ood-Tsen** [comment]
Actually, not all 'content://' can translate to the 'file://' .

I have add a class 'ContentDataSource' for this case.
You can check the [poll request #416](https://github.com/google/ExoPlayer/pull/416).

**Comment by ojw28** [comment]
Supported as of https://github.com/google/ExoPlayer/pull/465/files
