### ISSUE TITLE
ExoPlaybackException IllegalStateException on newest version (2.7.3)

### ISSUE THREAD

**Issue by aanhurets** [google/ExoPlayer#4136]
Hello
I have the issue in the library. I have been using the newest version 2.7.3. I have found some similar questions, but these are very old. Below my log:

```
Non-fatal Exception: com.google.android.exoplayer2.ExoPlaybackException
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)

Caused by java.lang.IllegalStateException
       at android.media.MediaCodec.native_dequeueOutputBuffer(MediaCodec.java)
       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(Unknown Source)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(Unknown Source)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(Unknown Source)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)

#0. Crashed: main
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)


```

**Comment by botaydotcom** [comment]
Hi @aangurets,
I think this is probably a device specific issue. Please try to reproduce the issue with our demo app, and provide us with more info so we can analyse this issue, including:
- Reproduction steps
- Link to test content
- Device(s) and version(s) of Android being used
- A full bug report captured from the device

We will look into this once we get the information. Thank you very much.

**Comment by aanhurets** [comment]
Hi, @botaydotcom 
I have only Fabric's bug report from my users (Which I've shared already)
This issue affects many devices and versions (please, see screenshot https://prnt.sc/j6d2fz)

**Comment by botaydotcom** [comment]
Unfortunately we can't help in this case, because the issue doesn't have enough information for us to work on.
Please check out some [similar issues](https://github.com/google/ExoPlayer/search?q=at+android.media.MediaCodec.native_dequeueOutputBuffer%28MediaCodec.java%29&type=Issues), although I have briefly looked at them and they seemed mostly device-specific.
