### ISSUE TITLE
Exoplayer2: UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.

### ISSUE THREAD

**Issue by anasAJ** [google/ExoPlayer#4141]
Please i'm Developping an App based on Android tv Activity And i've created a Class getting me m3u8 links from a file to play it as URI the HLS player .
When i try to play the link i get the following error:
    
    E/ExoPlayerImplInternal: Source error.
                         com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
                             at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:148)
                             at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:48)
                             at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:130)
                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                             at java.lang.Thread.run(Thread.java:818)

I've tried to give the correct form of m3u file by adding programmatically Strings like #EXTM3U... to get this :

    #EXTM3U
    #EXTINF:-1,Title-test
    http://test.co:8080/live/eglS9qxjAgeglS9qxjAg/eglS9qxjAg.m3u8

But i get error caus basically it's not a valid URI to use as parametre on `HlsMediaSource()`.
Can any one help ? thank you.

**Comment by AquilesCanta** [comment]
Please see #3722 and #4066 in case they are relevant.

Can you provide the contents referred by the uri? If you don't want to disclose them, please send them to dev.exoplayer@gmail.com following the instructions of the issue template. The listed contents are not valid. Even if `#EXTINF:-1` was supported, the URI should point to a media file (I am assuming it is not the case due to the extension, ignore if this is the case).

**Comment by anasAJ** [comment]
Thank you @AquilesCanta , in my uri i have a simple well working link ending by m3u8 lik :  http://test.co:8080/live/eglS9qxjAgeglS9qxjAg/eglS9qxjAg.m3u8

**Comment by AquilesCanta** [comment]
Have you tried passing that uri to the HlsMediaSource? Without the contents, I cannot assist any further.

**Comment by anasAJ** [comment]
Uri myUri = Uri.parse("http://test.co:8080/live/eglS9qxjAgeglS9qxjAg/eglS9qxjAg.m3u8");
        MediaSource videoSource = new HlsMediaSource(myUri,dataSourceFactory,mainHandler, new MediaSourceEventListener() {...
thats simply my code and all my params are correct and running with no errors.
So this code are giving this error:

     E/ExoPlayerImplInternal: Source error.
                     com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
                         at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:148)
                         at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:48)
                         at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:130)
                         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                         at java.lang.Thread.run(Thread.java:818)

**Comment by AquilesCanta** [comment]
> Without the contents, I cannot assist any further.

**Comment by ghost** [comment]
Is it a close issue?

**Comment by ojw28** [comment]
Pretty sure this is a duplicate of https://github.com/google/ExoPlayer/issues/4066.
