### ISSUE TITLE
castdemo get crash in xiaomi settop box 4 android 6.0.1

### ISSUE THREAD

**Issue by liushaofang** [google/ExoPlayer#4160]
After I build and launch exoplayer2.castdemo  on xiaomi settop box 4, which got crash with following error:
`04-20 17:58:56.830 11186-11186/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.exoplayer2.castdemo, PID: 11186
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.exoplayer2.castdemo/com.google.android.exoplayer2.castdemo.MainActivity}: java.lang.RuntimeException: com.google.android.gms.dynamite.DynamiteModule$zzc: No acceptable module found. Local version is 0 and remote version is 0.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5422)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:733)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
     Caused by: java.lang.RuntimeException: com.google.android.gms.dynamite.DynamiteModule$zzc: No acceptable module found. Local version is 0 and remote version is 0.
        at com.google.android.gms.internal.zzavl.zzbp(Unknown Source)
        at com.google.android.gms.internal.zzavl.zza(Unknown Source)
        at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source)
        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source)
        at com.google.android.exoplayer2.castdemo.MainActivity.onCreate(MainActivity.java:66)
        at android.app.Activity.performCreate(Activity.java:6251)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5422) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:733) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623) 
     Caused by: com.google.android.gms.dynamite.DynamiteModule$zzc: No acceptable module found. Local version is 0 and remote version is 0.
        at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
        at com.google.android.gms.internal.zzavl.zzbp(Unknown Source) 
        at com.google.android.gms.internal.zzavl.zza(Unknown Source) 
        at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source) 
        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source) 
        at com.google.android.exoplayer2.castdemo.MainActivity.onCreate(MainActivity.java:66) 
        at android.app.Activity.performCreate(Activity.java:6251) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5422) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:733) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623) 
04-20 17:58:56.832 3885-3907/system_process W/ActivityManager:   Force finishing activity com.google.android.exoplayer2.castdemo/.MainActivity`
The box run android 6.0.1, could anyone do me a favor to figure out the crash reason?

**Comment by liushaofang** [comment]
maybe extension-cast.gradle dependencies is the problem, 
dependencies {
    // These dependencies are necessary to force the supportLibraryVersion of
    // com.android.support:support-v4, com.android.support:appcompat-v7 and
    // com.android.support:mediarouter-v7 to be used. Else older versions are
    // used, for example:
    // com.google.android.gms:play-services-cast-framework:11.4.2
    // |-- com.google.android.gms:play-services-basement:11.4.2
    //   |-- com.android.support:support-v4:25.2.0
    api 'com.android.support:support-v4:' + supportLibraryVersion
    api 'com.android.support:appcompat-v7:' + supportLibraryVersion
    api 'com.android.support:mediarouter-v7:' + supportLibraryVersion
    api 'com.google.android.gms:play-services-cast-framework:' + playServicesLibraryVersion
    implementation project(modulePrefix + 'library-core')
    implementation project(modulePrefix + 'library-ui')
    testImplementation project(modulePrefix + 'testutils')
    testImplementation 'junit:junit:' + junitVersion
    testImplementation 'org.mockito:mockito-core:' + mockitoVersion
    testImplementation 'org.robolectric:robolectric:' + robolectricVersion
    testImplementation project(modulePrefix + 'testutils-robolectric')
}
but I don't know how to fix this problem, I need your instructions.

**Comment by AquilesCanta** [comment]
The first thing i'd try would be updating google play services on the device (what version are you running, by the way?).

**Comment by AquilesCanta** [comment]
Closing due to lack of activity.
