### ISSUE TITLE
Parse Error while streaming m3u8 files from livestream.com

### ISSUE THREAD

**Issue by siddhism** [google/ExoPlayer#4192]
### Reproduction steps
Hello, we have following *.m3u8 file from livestream.com for playing VOD. 

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:15
#EXTINF:14.572,
<media_url>
#EXTINF:-26.365,
<media_url>
#EXT-X-ENDLIST
```

Here is the stack trace when we try to play it with exoplayer. For negative values the regex is not matching which is causing the issue. 

```
 com.google.android.exoplayer2.ParserException: Couldn't match #EXTINF:([\d\.]+)\b in #EXTINF:-26.365,
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parseStringAttr(HlsPlaylistParser.java:538)
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parseDoubleAttr(HlsPlaylistParser.java:525)
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parseMediaPlaylist(HlsPlaylistParser.java:407)
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:167)
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:48)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:130)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
```

### Link to test content
Sent to email. 

Although issue  [4066](https://github.com/google/ExoPlayer/issues/4066) is similar. but the extension of our stream urls is m3u8 however in the header its mentioned as m3u. 

According to HLS Spec, the tag attribute value needs to be a positive value. But that makes it a blocker for us, is it something which only the provider can solve? 

Thanks

**Comment by ojw28** [comment]
The content provider should fix their bad media.

**Comment by AquilesCanta** [comment]
You can always implement your own playlist parser to work around this, if needed.
