### ISSUE TITLE
com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://59fb16.entrypoint.cloud.wowza.com/app-e4ef/ngrp:ba46c471_all/playlist.m3u8

### ISSUE THREAD

**Issue by kirankaushal** [google/ExoPlayer#4204]
Hello all,
 I am using Exo Player library to play HSL type video.But getting below error.I am able to playback on wowza server but not on Exo player

```
ExoPlayerImplInternal: Source error.                                                                                       com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://59fb16.entrypoint.cloud.wowza.com/app-e3ef/ngrp:ba46c478_all/playlist.m3u8
   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:195)
   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
   at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
   at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
   at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114)
   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
   at java.lang.Thread.run(Thread.java:818)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
   at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:306)
   at com.android.okhttp.Connection.upgradeToTls(Connection.java:197)
   at com.android.okhttp.Connection.connect(Connection.java:151)
   at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
   at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
   at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
   at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
   at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
   at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:427)
   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:351)
   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193)
   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
   at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101) 
   at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64) 
   at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114) 
   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
   at java.lang.Thread.run(Thread.java:818) 
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
   at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318)
   at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219)
   at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:113)
   at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:525)
   at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
   at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:302)
   at com.android.okhttp.Connection.upgradeToTls(Connection.java:197) 
   at com.android.okhttp.Connection.connect(Connection.java:151) 
   at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276) 
   at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211) 
   at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373) 
   at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106) 
   at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89) 
   at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25) 
   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:427) 
   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:351) 
   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193) 
   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
   at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101) 
   at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64) 
   at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114) 
   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
   at java.lang.Thread.run(Thread.java:818) 
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
   at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318) 
   at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219) 
   at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:113) 
   at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:525) 
   at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
   at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:302) 
   at com.android.okhttp.Connection.upgradeToTls(Connection.java:197) 
   at com.android.okhttp.Connection.connect(Connection.java:151) 
   at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276) 
   at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211) 
   at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373) 
   at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106) 
   at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89) 
   at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25) 
   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:427) 
   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:351) 
   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193) 
   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
   at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101) 
   at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64) 
   at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114) 
   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
   at java.lang.Thread.run(Thread.java:818) 
```

**Comment by FD-** [comment]
java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

Could be because you use a self-signed certificate for your server. It definitely doesn't look like an issue of ExoPlayer.

**Comment by kirankaushal** [comment]
That url is provided by wowza cloud .Do u have an idea about url generation in wowza cloud

**Comment by ojw28** [comment]
Agreed this is not an ExoPlayer issue. There's a lot of information about this issue online, if you just search for "Trust anchor for certification path not found".
