### ISSUE TITLE
Android strictmode error-   java.lang.Throwable: Explicit termination method 'close' not called

### ISSUE THREAD

**Issue by getashok2003** [google/ExoPlayer#4205]
Sting TV android box
Android version - 7.0
Scenario - OTT content playback 
Always seeing this -YES
Exopalyer version - r2.4.1

```
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:222)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
        at com.android.okhttp.okio.Okio.sink(Okio.java:179)
        at com.android.okhttp.internal.io.FileSystem$1.sink(FileSystem.java:49)
        at com.android.okhttp.internal.DiskLruCache$Editor.newSink(DiskLruCache.java:875)
        at com.android.okhttp.Cache$CacheRequestImpl.<init>(Cache.java:431)
        at com.android.okhttp.Cache.put(Cache.java:240)
        at com.android.okhttp.Cache.-wrap0(Cache.java)
        at com.android.okhttp.Cache$1.put(Cache.java:142)
        at com.android.okhttp.internal.http.HttpEngine.maybeCache(HttpEngine.java:546)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:820)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:204)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)
        at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:103)
        at javax.crypto.CipherInputStream.read(CipherInputStream.java:224)
        at com.google.android.exoplayer2.source.hls.Aes128DataSource.read(Aes128DataSource.java:96)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:257)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:59)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:232)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:266)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:202)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by ojw28** [comment]
I think this is a bug in the platform network stack, similar to [this one](https://github.com/square/okhttp/issues/2487) (the platform network stack uses OkHttp for its implementation).

If it's not causing any visible problem then I think it's safe to ignore the strict mode violation. You could also choose to use our [OkHttp extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/okhttp), which lets you use an up to date version of OkHttp, and also to use the same version across all devices so as to minimize the potential for different behavior on different devices. I do not believe newer versions of OkHttp are affected by this issue.
