### ISSUE TITLE
ExoPlayerImplInternal: Internal runtime error

### ISSUE THREAD

**Issue by pals-ric** [google/ExoPlayer#4216]
05-07 19:28:34.697 31757-31999/com.ideacellular.digitalvideo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                      java.lang.IllegalStateException
                                                                                          at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
                                                                                          at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2507)
                                                                                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:631)
                                                                                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:568)
                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
    05-07 19:28:34.728 31757-31999/com.ideacellular.digitalvideo E/ExoPlayerImplInternal: Stop failed.
                                                                                      java.lang.IllegalStateException
                                                                                          at android.media.MediaCodec.native_stop(Native Method)
                                                                                          at android.media.MediaCodec.stop(MediaCodec.java:2007)
                                                                                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:512)
                                                                                          at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:439)
                                                                                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:468)
                                                                                          at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:341)
                                                                                          at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:150)
                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:972)
                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:772)
                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:735)
                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by pals-ric** [comment]
hi
I have added last working solution `https://github.com/google/ExoPlayer/issues/3032`    for draggable panel landscape mode so I am getting this error in simple exo player please help me out with this.

**Comment by pallavirichhariya22** [comment]
can anybody suggest me solution.

**Comment by tonihei** [comment]
Can you please provide the information requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE) for us to take a look? 

From the error you posted, I guess this is happening after you left the activity with ExoPlayer? The system media codec sometimes fails to stop in such cases.

**Comment by pals-ric** [comment]
i have added below code in onconfiguration change 

     View playerView = videoPlayerFragment.getView();
                    frameLayout= (FrameLayout) findViewById(R.id.drag_view);
                    frameLayout.removeView(playerView);
                    draggablePanel.addView(playerView, playerView.getLayoutParams());


because of this code some view is removing . I am not able to identify which mandatory view is removing . if i am not removing that is throwing exception that a child cant have two parent for draggable panel i am changing the parent  and adding view to draggable panel.

**Comment by tonihei** [comment]
This seems unrelated, or least it's unclear what causes the error.

Again, can you please provide clear reproduction steps (ideally in our demo app)? Otherwise, it's not possible for us to understand what's going on and to investigate.

**Comment by pals-ric** [comment]
i tried this solution in my code 

https://www.google.com/url?q=https://github.com/pedrovgs/DraggablePanel/issues/78&sa=D&source=hangouts&ust=1525861209276000&usg=AFQjCNEz_McjriPWiBDAL0uY0ZmtcbBvcA

last working solution i have one thierd party exoplayer which is running fine with this solution but for my player video is not comming while rotation .

**Comment by pals-ric** [comment]
only subtitles are running video went somewhere

**Comment by pals-ric** [comment]
i am getting everything running only video is not appearing

**Comment by tonihei** [comment]
We can't help you debug issues with DraggablePanel or generic Android developement. That's something you need to bring up with them or ask on StackOverflow or similar. 

If you want us to look into a specific ExoPlayer issue, please make sure to boil it down to its source as much as possible such that we can actually reproduce it.

**Comment by pals-ric** [comment]
what view i should remove according to `https://github.com/pedrovgs/DraggablePanel/issues/78` solution for now i am removing whole layout so some surface view and compont listener is getting removed along with that .

**Comment by tonihei** [comment]
As I said, please file any issues you have with DraggablePanel on their site.

Closing as this doesn't seem to be an ExoPlayer problem.

**Comment by JuhDuh26** [comment]
I also intermittently get this issue when adding and removing the Exoplayer View into a ScrollView dynamically at runtime, it then breaks all instances of Exoplayer in my app until a hard restart of the app is done! 

Why would this exception being thrown in one instance of Exoplayer, break it for all other instances in other activities and fragments?

**Comment by ojw28** [comment]
This issue has been locked as it was closed some time ago. But to answer your question, that can only really occur if something in the platform underneath us gets into a bad state.
