### ISSUE TITLE
Get an issue while using ima ads (may be special exception)

### ISSUE THREAD

**Issue by kinhdang** [google/ExoPlayer#4231]
Dear all !

We use exoplayer 2.7.1, and it works properly. but recent we get an issue with log file detail follow, may be this issue is exception specialy, we only post here, if any knows, please share idea how to improved.

THanks.

ANDROID_VERSION=4.2.2 
BRAND=rk31sdk
PHONE_MODEL=IPTV1
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException
at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.loadAd(Unknown Source)
at com.google.obf.hm.a(Unknown Source)
at com.google.obf.hj.e(Unknown Source)
at com.google.obf.hj.a(Unknown Source)
at com.google.obf.hk.b(Unknown Source)
at com.google.obf.hk$1.shouldOverrideUrlLoading(Unknown Source)
at android.webkit.CallbackProxy.uiOverrideUrlLoading(CallbackProxy.java:270)
at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:383)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)

**Comment by andrewlewis** [comment]
If `loadAd` were called after releasing the ads manager that could cause this, but that is unexpected. Do you have steps to reproduce the issue or any other information about the circumstances under which the crash occurred?

**Comment by kinhdang** [comment]
Thanks andrewlewis !

unfortunately, this issue we got by end user when they using our app, we will monitor more this case, and report in here.

Many thanks.
