### ISSUE TITLE
MediaCodec error in Huawey Nexus after May 5, security update 

### ISSUE THREAD

**Issue by VictorPurMar** [google/ExoPlayer#4267]
### Issue description

The MediaCodec failed to start in HUAWEY NEXUS P6 when trying to reproduce a hls video.
Is working in other devices.

Actually it was working also in this device ( Android 8.1 ) , but start crashing after the May 5 , 2018 security update.

The issue disappear after a factory reset.
 Probably there was an error installing the update... but i'm worried for the future users. Factory reset is not the best solution to solve it almost for the common user.

Any clue to identify the issue will be appreciated.

Thanks in advance,

```
05-17 09:56:51.950 608-3332/? E/OMX-VDEC-1080P: Map Failed to allocate input buffer
05-17 09:56:51.950 608-3332/? E/OMXNodeInstance: allocateBuffer(0xf31c6a04:qcom.decoder.avc, Input:0 6643712@0xee52e000) ERROR: InsufficientResources(0x80001000)
05-17 09:56:51.951 10109-10433/tv.mycujoo.mycujooplayer.dev.debug E/ACodec: Failed to allocate buffers after transitioning to IDLE state (error 0xfffffff4)
    signalError(omxError 0x80001001, internalError -12)
05-17 09:56:51.951 10109-10432/tv.mycujoo.mycujooplayer.dev.debug E/MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 5
05-17 09:56:51.951 608-10439/? E/OMX-VDEC-1080P: ERROR::send_command_proxy(): Loaded-->Loaded
05-17 09:56:51.951 608-24537/? E/OMXNodeInstance: b/25884056
05-17 09:56:51.952 10109-10433/tv.mycujoo.mycujooplayer.dev.debug E/ACodec: [OMX.qcom.video.decoder.avc] ERROR(0x80001012)
    signalError(omxError 0x80001012, internalError -2147483648)
05-17 09:56:51.955 10109-10432/tv.mycujoo.mycujooplayer.dev.debug E/MediaCodec: Codec reported err 0x80001012, actionCode 0, while in state 0
05-17 09:56:51.957 596-17525/? E/ResourceManagerService: getLowestPriorityBiggestClient_l: lowest priority 0 vs caller priority 0
05-17 09:56:51.965 10109-10344/tv.mycujoo.mycujooplayer.dev.debug E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:420)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:407)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:898)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:468)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:551)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1/27, null, video/avc, -1, null, [426, 240, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:407) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:898) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:468) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:551) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2051)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:400)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:898) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:468) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:551) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
05-17 09:56:51.993 10109-10344/tv.mycujoo.mycujooplayer.dev.debug E/ExoPlayerImplInternal: Stop failed.

```

### Reproduction steps
Only i could reproduce using this Huawey device.

### Version of ExoPlayer being used
2.7.3

### Device(s) and version(s) of Android being used
Huawey nexus p6 , Android 8.1 
The problem appears after the May 5, 2018 security update.

### A full bug report captured from the device

[bugreport-angler-OPM2.171019.029.A1-2018-05-16-16-42-39.txt](https://github.com/google/ExoPlayer/files/2012653/bugreport-angler-OPM2.171019.029.A1-2018-05-16-16-42-39.txt)

**Comment by andrewlewis** [comment]
- Please could you take a bug report just after seeing the error? The one provided doesn't include logging just before the stack trace was output.
- "Probably there was an error installing the update" -- did you see some other error while installing the update?
- Did this happen while trying to play DRM-protected content? Or does it seem to affect all video playbacks?

**Comment by VictorPurMar** [comment]
Please could you take a bug report just after seeing the error?
Sorry... i can't reproduce it again. I reinstall the so (fabric reset) and the error seems repaired.

did you see some other error while installing the update?
No the updating was apparently normal. 

Did this happen while trying to play DRM-protected content? 
Nope, its an open hls video.

Thanks again.

**Comment by ojw28** [comment]
Did you try just rebooting the device (but not doing a full factory reset) after the update was installed and prior to factory resetting?

It seems most likely to me that the device got into a bad state (possibly as a result of the update, but most likely just by chance at around the same time), and that a normal reboot would have resolved the issue. If so then I'm not sure there's much for us to do here. If you can categorically state that rebooting didn't resolve the issue but factory resetting did, then I guess it might warrant further investigation.

**Comment by ojw28** [comment]
Closing due to lack of updates.
