### ISSUE TITLE
Exception while seeking video

### ISSUE THREAD

**Issue by petersamokhin** [google/ExoPlayer#4268]
### Issue description
In another issue was the problem with `sidx` boxes after concatenation of a lot of files into one big video. Based on @ojw28 's answers I made my file great. But video still not seekable for ExoPlayer.

---
Your example [video](https://www.google.com/url?q=https://storage.googleapis.com/exoplayer-test-media-1/gen-3/screens/dash-vod-single-segment/video-avc-baseline-480.mp4&usg=AFQjCNHjnNzWr0KgtfyOTJqK3rDDcHNERA):
<img src="https://i.imgur.com/bICpiqr.png" width="610" height="120" />
<p dir='rtl' align='right'>Example provided by @ojw28 in #4197</p>

My result video:
<img src="https://i.imgur.com/DcvN9G1.png" width="610" height="150" />
<p dir='rtl' align='right'>Used http://mp4parser.com/ for parsing</p>

---

My video now is correct. It contains only one `sidx` box with info about all references. It's playable by any player, including ExoPlayer. 

---
<details>
<summary>(<i>click to expand</i>) <b>Show stacktraces</b></summary>

```kotlin
05-14 17:20:44.518 10417-10467/com.domain.android.appname E/ExoPlayerImplInternal: Source error.
com.google.android.exoplayer2.ParserException: Skipping atom with length > 2147483647 (unsupported).
    at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomHeader(FragmentedMp4Extractor.java:408)
    at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:306)
    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:853)
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
```

```kotlin
05-17 15:11:50.099 5111-5154/com.domain.android.appname E/ExoPlayerImplInternal: Source error.
java.io.EOFException
    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:265)
    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:102)
    at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:110)
    at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:423)
    at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:311)
    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:853)
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
```
</details>

---

**UPD**: in some cases video can be unplayable by ExoPlayer (duration is correct, but only first frame is showing during playing). Any attempt to seek causes crash. But even standard android's `VideoView` and `MediaPlayer` can play (but also can't seek) this video, and ExoPlayer can't.

---
### Reproduction steps
Simply open this video by 
```kotlin
val defaultDataSourceFactory = DefaultDataSourceFactory(DefaultBandwidthMeter())
val extractorMediaSourceFactory = ExtractorMediaSource.Factory(defaultDataSourceFactory)
val mediaSource = extractorMediaSourceFactory.createMediaSource("file:///.../video.m4v")
player.prepare(mediaSource)
```
and try to seek back ("rewind" <kbd>◁◁</kbd>) or to any position by seekbar.

---
### Link to test content
Sent to dev.exoplayer@gmail.com from contact@petersamokhin.com with subject **`#4268`**.

---
### Version of ExoPlayer being used
```
com.google.android.exoplayer:exoplayer-core:2.8.0
com.google.android.exoplayer:exoplayer-dash:2.8.0
com.google.android.exoplayer:exoplayer-ui:2.8.0
```

---
### Device(s) and version(s) of Android being used
Phipips S309 (API 21), Xiaomi Mi A1 (API 25), Google Emulator 'Nexus 5X' (API 19, 21, 27).

---
### A full bug report captured from the device
Sent to dev.exoplayer@gmail.com in one message with the video sample. From contact@petersamokhin.com and with subject **`#4268`**.

---
### And the question
What's wrong with my files?
Files contain correct boxes (all parsers that I've used parsed them correctly).
There are only one `sidx` box with correct information about all references (video chunks with `moof` & `mdat` boxes).
What I need to change? Why in some cases video can be unplayable? Why in ALL cases I can't seek in video? 
Almost all players that I tried to use, played these files without any error, and they also were able to seek. @ojw28 said that those players are using binary search or another features that ExoPlayer won't use.
@ojw28 also said that problem is in incorrect `sidx` boxes, that `time->byte` mapping is needed. But now this mapping is here. Now what?

**Comment by andrewlewis** [comment]
I think the time to byte is wrong: when I added some logging to output the atom name, size and its position in the stream, after seeking I get:

```
05-21 16:43:24.844 27711 28081 W DEBUG   : Atom of type tfdt of size 20 at 3261
05-21 16:43:24.844 27711 28081 W DEBUG   : Atom of type trun of size 500 at 3281
05-21 16:43:24.852 27711 28081 W DEBUG   : Atom of type qﾐw; of size 2104182295 at 556667
```

The last line indicates that we tried to read an atom header and size but actually read some other data.

Could you check your segment indices and make sure the chunk offsets are correct?

**Comment by ojw28** [comment]
Closing because the media is still not correct. Helping with media creation is beyond the scope of this issue tracker.
