### ISSUE TITLE
Geo Restricted Video Url not recognised:  com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#4271]
My Video ulr is georestricted: 

  com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:148)
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:48)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:130)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
05-18 16:06:19.146 22841-23485/ws.datamate.android.livesports E/JZExoPlayer: onPlayerErrorcom.google.android.exoplayer2.ExoPlaybackException
    onTimelineChanged
    onPlayerStateChanged1/ready=true
05-18 16:06:19.146 22841-22841/ws.datamate.android.livesports E/JiaoZiVideoPlayer: onError 1000 - 1000 [262466486]

**Comment by andrewlewis** [comment]
Can you provide the playlist, so we can see if this is an ExoPlayer issue or a problem with the stream?

There are some [other issues](https://github.com/google/ExoPlayer/search?q=%22Input+does+not+start+with+the+%23EXTM3U+header.%22&type=Issues) mentioning that error message which may be helpful.

**Comment by ghost** [comment]
Sure, here is the URL: http://80.82.70.138:8088/live/starsports1gr/playlist.m3u8?id=31776&wowzasessionid=3366108294&pk=1eb7a09031dcaee935957fe956a3948ea18e43925ac3cb2d97f12e760e1ffbb0

Only avail form Bangladesh and working from my browser html5 Player not in exoplayer

**Comment by andrewlewis** [comment]
Could you post the actual contents of that file?

**Comment by ojw28** [comment]
I tried requesting the URL through a proxy. It returned HTTP status code 200 (i.e. OK) but no data. The Content-Length header explicitly indicates a length of 0. Playback then fails with the error above. So I think the URL is just not serving any content.
