### ISSUE TITLE
Getting BehindLiveWindowException in between the play.

### ISSUE THREAD

**Issue by infernal221** [google/ExoPlayer#4272]
Player with multi-bitrate initializes and then it selects one bitrate with index and start segment and player plays. But in some time from the selected bitrate from the index new segment is not getting called. We receive below exception. IT happens with live streams HLS. Exoplayer version is 2.6.1.

com.google.android.exoplayer2.source.BehindLiveWindowException
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:280)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:466)
        at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:71)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading(HlsMediaPeriod.java:194)
        at com.google.android.exoplayer2.source.DeferredMediaPeriod.continueLoading(DeferredMediaPeriod.java:124)
        at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.continueLoading(ExoPlayerImplInternal.java:1640)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1439)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1432)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:334)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by AquilesCanta** [comment]
I don't understand what the issue here is. Also, could you explicitly point out how this differs from existing BehindLiveWindowException issues?

**Comment by ojw28** [comment]
Closing due to lack of information.
