### ISSUE TITLE
Can't load HLS streams with MP4 without mvex atom

### ISSUE THREAD

**Issue by jknobel** [google/ExoPlayer#4274]
### Issue description
We have a device that records video and writes mp4 files with a duration of 4 seconds, every 4 seconds into a folder. We then use an HLS stream to allow a user to view the last 24 hours of footage to review. It's not a live-stream (you can't view what's happening now... new items are not added to the playlist), but it's also not produced/finalized content either which is why we've set up our HLS stream in this way. 

FragmentedMP4Extractor throws a NullPointerException when trying to load our MP4 files due to being unable to find the MVEX atom, which our files do not have. The streams play just fine on iOS/MacOS, so there's enough information there to play the files,  but it fails in ExoPlayer. 

### Reproduction steps
Load up ExoPlayer using an HLSMediaSource with the URL provided below in the test content. Exoplayer will throw a NullPointerException when loading the first initialization segment and trying to parse it.

### Link to test content
http://206.189.171.59/test-outside.m3u8

### Version of ExoPlayer being used
2.8.0

### Device(s) and version(s) of Android being used
Pixel 2 | Android 8.1.0 | 100% reproducable

### A full bug report captured from the device
Bug report has been e-mailed, though relevant stack trace has been pasted below:

`05-18 12:16:32.811 9911-10055/us.***.**** E/LoadTask: Unexpected exception loading stream
    java.lang.NullPointerException: Attempt to read from field 'java.util.List com.google.android.exoplayer2.extractor.mp4.Atom$ContainerAtom.leafChildren' on a null object reference
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onMoovContainerAtomRead(FragmentedMp4Extractor.java:472)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onContainerAtomRead(FragmentedMp4Extractor.java:454)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.processAtomEnded(FragmentedMp4Extractor.java:434)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:429)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:315)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.maybeLoadInitData(HlsMediaChunk.java:239)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:216)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
05-18 12:16:32.846 9911-10053/us.***.***** E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.ParserException: Atom size less than header length (unsupported).
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomHeader(FragmentedMp4Extractor.java:364)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:310)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.maybeLoadInitData(HlsMediaChunk.java:239)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:216)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by AquilesCanta** [comment]
Please have a look at [this spec section](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-3.3):

```
 The Media Initialization Section for an fMP4 Segment MUST contain a
 File Type Box ('ftyp') containing a brand that is compatible with
 'iso6' or higher.  The File Type Box MUST be followed by a Movie Box.
 The Movie Box MUST contain a Track Box ('trak') for every Track
 Fragment Box ('traf') in the fMP4 Segment, with matching track_ID.
 Each Track Box SHOULD contain a sample table, but its sample count
 MUST be zero.  Movie Header Boxes ('mvhd') and Track Header Boxes
 ('tkhd') MUST have durations of zero.  A Movie Extends Box ('mvex')
 MUST follow the last Track Box.
```

According to this the described media is not spec compliant. Let me know if I am missing anything here.

**Comment by jknobel** [comment]
@AquilesCanta Right, the files are not fMP4s. Can HLS work with non-fragmented MP4 files? It does work perfectly fine on all the apple platforms and these streams are already used in released apps for iOS, so trying to get it to work without modifications for Android.

**Comment by AquilesCanta** [comment]
This is not supported out of the box, unfortunately. I suppose you could implement your own HlsExtractorFactory and create an Mp4Extractor instead of a FragmentedMp4Extractor. The problem with this is timestamp adjustment. To achieve it, you might be able to create a wrapper around the existing extractor to handle timestmaps in a similar fashion to what the fragmented one does. Also, you might be able to fork the fragmented one and support the lack of mvex. If it is not a big / awkward change, it might even make sense to create a pull request for it. However, I doubt this is something that we would like to put in our roadmap.
