### ISSUE TITLE
SRT subs position tags

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#4306]
**### Issue description**
It doesn't recognize the position of the subtitles. I don't know if its possible just ignore and not show the tag, or position in the correct place.

### Link to test content
![Image of subs](http://images2.imagebam.com/f2/a4/9f/6c5c3d878070534.jpg)

### Version of ExoPlayer being used
Plex android app embedded.

**Comment by ojw28** [comment]
According to [this thread](https://forum.videohelp.com/threads/332300-How-to-position-a-subtitle-in-a-srt-file) positional tags like `{\an8}` aren't actually part of the SRT format, although some tools do appear to support such tags.

It's really hard for us to support subtitle formats that aren't properly specified, and in particular where undocumented additions have been made, as appears to be the case here. I'm going to class this as an enhancement rather than a bug, since the tags aren't really part of SRT, and mark it as low priority. We would accept a pull request into the `dev-v2` branch to either ignore such tags or handle them properly, so please feel free to send such a request if you're sufficiently motivated to fix this yourself. Thanks!

**Comment by szaboa** [comment]
After a quick research, I got the same conclusion as mentioned above, those tags are not part of the SRT format. People started to borrow these tags from other places over time and step by step the players started to support them. These tags are taken from ASS (https://www.matroska.org/technical/specs/subtitles/ssa.html). I will try to add support for these ```\an``` tags, as my first contribution to ExoPlayer. What do you think @ojw28 ?

**Comment by ojw28** [comment]
That would be great! A few things to keep in mind to help us merge any changes with minimal effort:

1. I would not envisage you needing to change anything in `Cue`, `SubtitlePainter` or `SubtitleView` to achieve this. `Cue` already supports positioning that's hopefully flexible for what you need to do, and the UI classes already make use of it. If you find yourself needing to edit those classes, I'd suggest we discuss that before you go too far :).
1. Given the tags aren't part of the format, please make sure you're handling of them is really robust (i.e. does not crash if the tag isn't exactly as expected). We can't really have loads of confidence that they'll be formatted correctly, given they've not been properly defined :).

Thanks!

**Comment by szaboa** [comment]
Sure thing! 
Just started to working on it, I will do the pull-request once is done, thank you :)

**Comment by szaboa** [comment]
@ojw28 
I am about to extend ```com.google.android.exoplayer2.text.subrip.SubripDecoderTest```, but it seems all the tests are failing for me:

```
WARNING: No manifest file found at ./src/test/AndroidManifest.xml.
Falling back to the Android OS resources only.
To remove this warning, annotate your test class with @Config(manifest=Config.NONE).
No such manifest file: ./src/test/AndroidManifest.xml

java.io.FileNotFoundException: Asset file subrip/typical_negative_timestamps not found

	at org.robolectric.shadows.ShadowAssetManager.findAssetFile(ShadowAssetManager.java:348)
	at org.robolectric.shadows.ShadowAssetManager.open(ShadowAssetManager.java:322)
	at android.content.res.AssetManager.open(AssetManager.java)
	at com.google.android.exoplayer2.testutil.TestUtil.getInputStream(TestUtil.java:142)
	at com.google.android.exoplayer2.testutil.TestUtil.getByteArray(TestUtil.java:138)
	at com.google.android.exoplayer2.text.subrip.SubripDecoderTest.testDecodeTypicalNegativeTimestamps(SubripDecoderTest.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:568)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

This is a known issue or what am I missing? :)

**Comment by ojw28** [comment]
That's an Android Studio bug, where it doesn't set the working directory properly. After you first try and run the tests (and they fail), you'll see it as the thing that's selected to run in the drop-down (by default near the top right of the Android Studio UI). Click the drop-down and select "Edit Configuration". You should see a "Working directory" configuration property for the tests. Click the icon at the far right of that box, and select "MODULE_DIR", then click OK. Re-run the tests and they should work correctly.

**Comment by szaboa** [comment]
@ojw28, It seems I am ready with this one, here is the pull request: 

New one: https://github.com/google/ExoPlayer/pull/4582

~~https://github.com/google/ExoPlayer/pull/4569~~ Closed this, because the pull request was made from dev-2 and not a feature branch
