### ISSUE TITLE
Exception on press back button on Moto C

### ISSUE THREAD

**Issue by Anton111111** [google/ExoPlayer#4315]
### Issue description
I see issue on Moto C device. When i go out from activity with player i get exception. 

### Reproduction steps
You can easy reproduce it with demo from this repository. 

- Simple start demo (https://github.com/google/ExoPlayer/tree/release-v2/demos/main)
- start any video
- press back button

### Version of ExoPlayer being used
I see this error on 2.7.*, 2.8.0, 2.8.1 versions

### Device(s) and version(s) of Android being used
Moto C (Android 7.0)

### A full bug report captured from the device
```
Exception from logcat:
05-29 10:01:37.072 2828-3249/com.google.android.exoplayer2.demo E/ACodec: new surface holds onto more buffers (2) than planned for (1)
05-29 10:01:37.074 2828-2828/com.google.android.exoplayer2.demo I/SurfaceView: surfaceDestroyed callback -, this = android.view.SurfaceView{659b197 V.E...... ........ 0,0-480,270}
05-29 10:01:37.074 2828-3240/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1914)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:915)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:405)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:372)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:861)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:829)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:811)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:328)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:203)
        at android.os.HandlerThread.run(HandlerThread.java:61)
05-29 10:01:37.074 2828-3240/com.google.android.exoplayer2.demo I/MediaCodec: [stop]line:640 [OMX.MTK.VIDEO.DECODER.AVC]+++
05-29 10:01:37.075 2828-3249/com.google.android.exoplayer2.demo D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Executing::kWhatShutdown keepComponentAllocated 1
05-29 10:01:37.076 2828-3249/com.google.android.exoplayer2.demo D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Now Executing->Idle
```

**Comment by Anton111111** [comment]
I created pull request to fix it:
https://github.com/google/ExoPlayer/pull/4316
