### ISSUE TITLE
ConcatenatingMediaSource 403 issue on the second video

### ISSUE THREAD

**Issue by alexandru-calinoiu** [google/ExoPlayer#4320]
### Issue description
I get 403 when playing HLS movies using ConcatenatingMediaSource.
The videos are served from Akamai, and that apparently requires some cookies to be stored.

I've tried this with `DefaultHttpDefaultDataSourceFactory` it worked for 1 video
I've also tried with `OkHttpDataSourceFactory` and https://github.com/franmontiel/PersistentCookieJar and that wored also

### Reproduction steps
- Create 2 hls data sources

```kotlin
    private fun createHlsMediaSource(videoUrl: String): HlsMediaSource {
        val videoUri = videoUrl.toUri()

        return HlsMediaSource.Factory(
                DefaultHlsDataSourceFactory(dataSourceFactory))
                .createMediaSource(videoUri)
    }
```

- add those media sources to a concatenating media source

```kotlin
val concatenatingMediaSource = ConcatenatingMediaSource(false)
videos.map { mediaSourceFactory.create(it.videoUrl, it.subtitleUrl, it.audioUrl) }
                .forEach { concatenatingMediaSource.addMediaSource(it) }
player?.prepare(concatenatingMediaSource, false, false)
```

### Link to test content
I can't provide any as it's propertary :(

### Version of ExoPlayer being used
2.8.1

### Device(s) and version(s) of Android being used
nexus 2

### A full bug report captured from the device

```
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:175)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:272)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:219)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
```

**Comment by alexandru-calinoiu** [comment]
Managed to work around this issue by using a new instance of a DataSourceFactory for each MediaSource,

Note that I needed to overwrite the default cookie jar for each of the instance without a new cookiejar this did not worked.

```
                val cookieManager = CookieManager()
                cookieManager.setCookiePolicy(CookiePolicy.ACCEPT_ALL)
                val client = OkHttpClient.Builder()
                        .cookieJar(JavaNetCookieJar(cookieManager))
                        .build()
                OkHttpDataSourceFactory(client, userAgent, bandwidthMeter)
```
