### ISSUE TITLE
decoder init exception 

### ISSUE THREAD

**Issue by getashok2003** [google/ExoPlayer#4324]
Sting TV android box
Android version - 7.0
Scenario - OTT content playback
Always seeing this -YES Andriod TV
Exoplayer version - r2.8.1

**stack trace** 
E/ExoPlayerImplInternal:Playback error.                                                                   
com.google.android.exoplayer2.ExoPlaybackException
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:441)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:428)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:920)
at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:503)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:557)
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Marvell.video_decoder.avc, Format(1/27, null, video/avc, -1, null, [640, 360, -1.0], [-1, -1])       

**Playback failed** 
ExoPlayerImplInternal: Stop failed.
java.lang.IllegalStateException
at android.media.MediaCodec.native_stop(Native Method)
at android.media.MediaCodec.stop(MediaCodec.java:2084)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:518)
at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:474)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:474)
at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:362)
at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:153)
at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:972)
 at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:768)
at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:731)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:343)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:154)
 at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by botaydotcom** [comment]
Hi @getashok2003,
I have done a quick search for other similar issues, and it's most likely a device-specific problem. Could you provide a full bug report, as requested in the issue template? Thank you.

**Comment by getashok2003** [comment]
### Reproduction steps
1. Sting android TV box was put overnight testing.
2. Next day play of any service like VOD, Live and Recorded did not work 
3. In all case decoder throwDecoderInitError is seen. 

### Link to test content-
Its not specific to content

### Version of ExoPlayer being used
2.8.1

### Device(s) and version(s) of Android being used
Sting android TV box by Technicolor -Android version - 7.0

will share bug report if this issues reported again.

**Comment by botaydotcom** [comment]
Closing the issue as the required info is not received.
