### ISSUE TITLE
AdsMediaSource$ComponentListener.release()' on a null object reference

### ISSUE THREAD

**Issue by narasimharao11** [google/ExoPlayer#4354]
I am getting com.google.android.exoplayer2.source.ads.AdsMediaSource$ComponentListener.release()' on a null object reference for some devices like 

samsung,motorola,HTC and OnePlus --os versions(6 and 7)

using exoplayer version 2.7.1.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.source.ads.AdsMediaSource$ComponentListener.release()' on a null object reference
       at com.google.android.exoplayer2.source.ads.AdsMediaSource.releaseSource(AdsMediaSource.java:281)
       at com.google.android.exoplayer2.source.CompositeMediaSource.releaseSource(CompositeMediaSource.java:59)
       at com.google.android.exoplayer2.source.ads.AdsMediaSource.releaseSource(AdsMediaSource.java:280)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:805)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:735)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:157)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by andrewlewis** [comment]
The stack trace is strange: it looks like the `AdsMediaSource` has another `AdsMediaSource` as its child. Please could you share the code you're using to construct the media source?

**Comment by ojw28** [comment]
Closing due to lack of information.
