### ISSUE TITLE
AC3 Audio Dolby 5.1 issue (DASH)

### ISSUE THREAD

**Issue by jboisjo** [google/ExoPlayer#4359]
### Issue description
We are having issue with our device that can't read AC3 Dolby 5.1 audio

```
06-08 13:19:58.708 5855-5921/E/AudioTrack: Could not get audio output for session 1121, stream type -1, usage 1, sample rate 48000, format 0x9000000, channel mask 0x37, flags 0x1
06-08 13:19:58.709 5855-5921/debug E/AudioTrack-JNI: Error -22 initializing AudioTrack
06-08 13:19:58.709 5855-5921/E/android.media.AudioTrack: Error code -20 when initializing AudioTrack.
06-08 13:19:58.711 5855-5921/E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:535)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1088)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:573)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 220, 20480)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:1130)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:561)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:617)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:529)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1088) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:573) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

### Reproduction steps
I tried to set the AudioCapabilities to null

```
new MediaCodecAudioRenderer(
            context,
            MediaCodecSelector.DEFAULT,
            drmSessionManager,
            /* playClearSamplesWithoutKeys= */ false,
            eventHandler,
            eventListener,
            AudioCapabilities.getCapabilities(context) -> null,
            audioProcessors));
```

and it's working but we don't get Dolby 5.1 sound. 

I found a solution that you guys did for the Nvidia Shield and we need to have the same work around for our specific Android device. 

In the DefaultAudioSink class, there this work around.

```
int channelConfig;
    switch (channelCount) {
      case 1:
        channelConfig = AudioFormat.CHANNEL_OUT_MONO;
        break;
      case 2:
        channelConfig = AudioFormat.CHANNEL_OUT_STEREO;
        break;
      case 3:
        channelConfig = AudioFormat.CHANNEL_OUT_STEREO | AudioFormat.CHANNEL_OUT_FRONT_CENTER;
        break;
      case 4:
        channelConfig = AudioFormat.CHANNEL_OUT_QUAD;
        break;
      case 5:
        channelConfig = AudioFormat.CHANNEL_OUT_QUAD | AudioFormat.CHANNEL_OUT_FRONT_CENTER;
        break;
      case 6:
        channelConfig = AudioFormat.CHANNEL_OUT_5POINT1;
        break;
      case 7:
        channelConfig = AudioFormat.CHANNEL_OUT_5POINT1 | AudioFormat.CHANNEL_OUT_BACK_CENTER;
        break;
      case 8:
        channelConfig = C.CHANNEL_OUT_7POINT1_SURROUND;
        break;
      default:
        throw new ConfigurationException("Unsupported channel count: " + channelCount);
    }
```

```
// Workaround for overly strict channel configuration checks on nVidia Shield.
    if (Util.SDK_INT <= 23 && "foster".equals(Util.DEVICE) && "NVIDIA".equals(Util.MANUFACTURER)) {
      switch (channelCount) {
        case 7:
          channelConfig = C.CHANNEL_OUT_7POINT1_SURROUND;
          break;
        case 3:
        case 5:
          channelConfig = AudioFormat.CHANNEL_OUT_5POINT1;
          break;
        default:
          break;
      }
    }
```

I think it will fix alot of user's device issue causing the AC3 5.1 Dolby errors on certain devices.

Just above, i debug the whole thing and it goes straight to case 5 and the 

`channelConfig = AudioFormat.CHANNEL_OUT_QUAD | AudioFormat.CHANNEL_OUT_FRONT_CENTER;
`

and it should be 
`channelConfig = AudioFormat.CHANNEL_OUT_5POINT1;`

So we basically needs this fix that the users can have access to Dolby 5.1 AC3.

### Version of ExoPlayer being used
2.8.1

**Comment by andrewlewis** [comment]
Passing `null` as the `AudioCapabilities` will mean that playback of AC-3 content will not be able to use encoded audio output (passthrough). So it will only work if the device has a decoder for the format, which is quite rare.

We currently set the channel configuration based on guidance in the [AudioFormat documentation](https://developer.android.com/reference/android/media/AudioFormat#channelPositionMask).

Please could you provide a full bug report captured with `adb bugreport` just after seeing this error, either attached here or via email to `dev.exoplayer@gmail.com` (with subject "Issue #4359")? Then we can make a targeted workaround like the one for NVIDIA Shield. Thanks!

**Comment by Arayldan** [comment]
I work with @jboisjo. I sent you an email with the bugreport.
Thanks!

**Comment by andrewlewis** [comment]
Thanks. I've followed up via email.

**Comment by andrewlewis** [comment]
Closing as this turned out to be a problem with the input media.
