### ISSUE TITLE
Rewinding issue when playing Encrypted Videos

### ISSUE THREAD

**Issue by YuxSong** [google/ExoPlayer#4368]
com.example.android.tvleanback E/LoadTask: Unexpected exception loading stream
    java.lang.IllegalStateException: Top bit not zero: -871305648
        at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:388)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:474)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:179)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:749)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

I add a custom datesource class to the Exoplayer sample , so that it can play aes-encrypted mp4 videos, everything goes well  except the rewind button, when i click the rewind button , the video stuck and throw the IllegalStateException: Top bit not zero .  What's wrong with it ? Please help !!!  0.0

**Comment by AquilesCanta** [comment]
Unfortunately, we don't have the bandwidth to debug this for you. It most likely depends on the way you are implementing encryption and decryption. If you are using Aes128DataSource, make sure decryption is correctly block-bounded and the initialization vector for the block is correctly set, otherwise the output will be wrong. Plus, if you are using CBC, seeking might get tricky. Spend some time choosing the right encryption scheme for you (maybe CTR is a good first solution) and understanding how it works.

Please, next time you file an issue, provide all the information required in the issue template.
