### ISSUE TITLE
Crash reported pointing internal to player.

### ISSUE THREAD

**Issue by getashok2003** [google/ExoPlayer#4408]
Android: 7.0
Android Build: 3.0.1
Manufacturer: Technicolor
Model: STING
Thread: Thread-892-1414
CrashReporter Key: b6cca6f9-594d-46e5-b72c-ca6aeec8ddef
Start Date: 2018-06-21T16:25:11.413Z
Date: 2018-06-21T16:38:23.324Z
This all are seen during HLS playback.
Exoplayer version -2.8.1
-------------------------1st crash --------------------------
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
	at java.util.ArrayList.fastRemove(ArrayList.java:531)
	at java.util.ArrayList.remove(ArrayList.java:514)
	at com.google.android.exoplayer2.analytics.AnalyticsCollector$MediaPeriodQueueTracker.onMediaPeriodReleased(SourceFile:737)
	at com.google.android.exoplayer2.analytics.AnalyticsCollector.onMediaPeriodReleased(SourceFile:314)
	at com.google.android.exoplayer2.analytics.AnalyticsCollector.resetForNewMediaSource(SourceFile:166)
	at com.google.android.exoplayer2.SimpleExoPlayer.stop(SourceFile:781)
	at com.google.android.exoplayer2.SimpleExoPlayer.stop(SourceFile:772)
	at com.b.a.a.a(SourceFile:1148)
	at com.b.a.a.b(SourceFile:1221)

-------------------------2nd crash --------------------------
java.lang.IndexOutOfBoundsException: Index: 0, Size: -1
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.google.android.exoplayer2.analytics.AnalyticsCollector$MediaPeriodQueueTracker.onMediaPeriodReleased(SourceFile:739)
	at com.google.android.exoplayer2.analytics.AnalyticsCollector.onMediaPeriodReleased(SourceFile:314)
	at com.google.android.exoplayer2.analytics.AnalyticsCollector.resetForNewMediaSource(SourceFile:166)
	at com.google.android.exoplayer2.SimpleExoPlayer.stop(SourceFile:781)
	at com.google.android.exoplayer2.SimpleExoPlayer.stop(SourceFile:772)
	at com.b.a.a.a(SourceFile:1148)
	at com.b.a.a.b(SourceFile:1221)
-------------------------3rd crash --------------------------
	at com.google.android.exoplayer2.Timeline$1.getWindow(SourceFile:506)
	at com.google.android.exoplayer2.Timeline.getWindow(SourceFile:633)
	at com.google.android.exoplayer2.Timeline.getWindow(SourceFile:620)
	at com.b.a.a.s(SourceFile:902)
	at com.b.a.a.A(SourceFile:99)
	at com.b.a.a$9.run(SourceFile:940)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by tonihei** [comment]
That most likely happened because the player was accessed from different threads simultaneously. 

Please note that all player methods must be called from the same thread. This must be the thread you created the player on (or the main thread if that thread doesn't have a Looper). We also recently added an option for #4278 to specify your own Looper to use for player access.

**Comment by tonihei** [comment]
Closing for now as the question is answered and the discussion in #4463 is used to track changes regarding this problem.
