### ISSUE TITLE
Errors when trying to download HLS using HlsDownloadAction or HlsDownloadHelper

### ISSUE THREAD

**Issue by AndreyAsadchy** [google/ExoPlayer#4430]
### Issue description
With **HlsDownloadAction** the error is:
```
E/DownloadService: Failed to handle ADD action
    com.google.android.exoplayer2.offline.DownloadException: No deserializer found for:hls, 0
        at com.google.android.exoplayer2.offline.DownloadAction.deserializeFromStream(DownloadAction.java:77)
        at com.google.android.exoplayer2.offline.DownloadManager.handleAction(DownloadManager.java:239)
        at com.google.android.exoplayer2.offline.DownloadService.onStartCommand(DownloadService.java:224)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3375)
        at android.app.ActivityThread.-wrap21(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1621)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6221)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

And with **HlsDownloadHelper**:
```
java.lang.NullPointerException
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:110)
        at com.google.android.exoplayer2.source.hls.offline.HlsDownloadHelper.getDownloadAction(HlsDownloadHelper.java:100)
```
### Reproduction steps
**HlsDownloadAction**:
```
HlsDownloadAction hlsDownloadAction = new HlsDownloadAction(Uri.parse(url), false, null, Collections.emptyList());
PlayerUtils.startDownload(getApplication(), hlsDownloadAction);
```

**HlsDownloadHelper**:

```
CacheDataSourceFactory factory = new CacheDataSourceFactory(DownloadUtils.getCache(getApplication()), getDataSourceFactory());
PlayerUtils.startDownload(getApplication(),  new HlsDownloadHelper(Uri.parse(url), factory).getDownloadAction(null, Collections.emptyList()));
```

startDownload method:
```
public static void startDownload(Context context, DownloadAction downloadAction) {
      DownloadService.startWithAction(context, MediaDownloadService.class, downloadAction, false);
}
```

MediaDownloadService:
```
public class MediaDownloadService extends DownloadService {

    private static final String CHANNEL_ID = "download_channel";
    private static final int JOB_ID = 1;
    private static final int FOREGROUND_NOTIFICATION_ID = 1;

    public MediaDownloadService() {
        super(FOREGROUND_NOTIFICATION_ID, DEFAULT_FOREGROUND_NOTIFICATION_UPDATE_INTERVAL, CHANNEL_ID, R.string.all_time); //TODO change
    }

    @Override
    protected DownloadManager getDownloadManager() {
        return DownloadUtils.getDownloadManager(this);
    }

    @Nullable
    @Override
    protected Scheduler getScheduler() {
        return Util.SDK_INT >= 21 ? new PlatformScheduler(this, JOB_ID) : null;
    }

    @Override
    protected Notification getForegroundNotification(DownloadManager.TaskState[] taskStates) {
        return DownloadNotificationUtil.buildProgressNotification(this, R.drawable.exo_controls_play, CHANNEL_ID, null, null, taskStates);
    }

    @Override
    protected void onTaskStateChanged(DownloadManager.TaskState taskState) {
        if (taskState.action.isRemoveAction) {
            return;
        }
        Notification notification = null;
        if (taskState.state == DownloadManager.TaskState.STATE_COMPLETED) {
            notification = DownloadNotificationUtil.buildDownloadCompletedNotification(
                    this,
                    R.drawable.exo_controls_play,
                    CHANNEL_ID,
                    null,
                    Util.fromUtf8Bytes(taskState.action.data));
        } else if (taskState.state == DownloadManager.TaskState.STATE_FAILED) {
            notification = DownloadNotificationUtil.buildDownloadFailedNotification(
                    this,
                    R.drawable.exo_controls_play,
                    CHANNEL_ID,
                    null,
                    Util.fromUtf8Bytes(taskState.action.data));
        }
        int notificationId = FOREGROUND_NOTIFICATION_ID + 1 + taskState.taskId;
        NotificationUtil.setNotification(this, notificationId, notification);
    }
}
```
### Link to test content
Any playlist, for example:
https://vod171-ttvnw.akamaized.net/4a97f011b0afb89557ef_starladder5_28944057744_877673773/chunked/highlight-268888753.m3u8

### Version of ExoPlayer being used
2.8.1

### Device(s) and version(s) of Android being used
Emulator Nexus_5X_API_27_x86 - Android 8.1
Xiaomi Redmi 4X - Android 7.1.2

### A full bug report captured from the device
[hlsdownloadaction.zip](https://github.com/google/ExoPlayer/files/2136754/hlsdownloadaction.zip)
[hlsdownloadhelper.zip](https://github.com/google/ExoPlayer/files/2136755/hlsdownloadhelper.zip)

**Comment by erdemguven** [comment]
"No deserializer found for:hls", when you create your DownloadManager, you need to pass HlsDownloadAction.DESERIALIZER as one the deserializers.

About HlsDownloadHelper exception, you need call getTrackGroups() before getDownloadAction().

**Comment by AndreyAsadchy** [comment]
The problem was that i was passing ProgressiveDownloadAction.DESERIALIZER instead of HlsDownloadAction.DESERIALIZER, so it's working now. Thank you.
