### ISSUE TITLE
Unable to instantiate codec 'OMX.qcom.video.decoder.avc'

### ISSUE THREAD

**Issue by ChinhQT** [google/ExoPlayer#4438]
Hi Google,

I often meet this issue. You can't play any videos when having this problem. How to resolve this problem ? Thanks in advance.

06-27 14:55:15.576 5394-8423/app.video E/ACodec: Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.
    signalError(omxError 0xfffffff4, internalError -12)
06-27 14:55:15.576 5394-8422/app.video E/MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 1
06-27 14:55:15.585 5394-8416/app.video W/MediaCodec-JNI: try to release MediaCodec from JMediaCodec::~JMediaCodec()...
06-27 14:55:15.587 5394-8416/app.video W/MediaCodec-JNI: done releasing MediaCodec from JMediaCodec::~JMediaCodec().
06-27 14:55:15.588 5394-8416/app.video E/ExoPlayerImplInternal: Renderer error.
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(Unknown Source:4)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(Unknown Source:305)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(Unknown Source:149)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(Unknown Source:0)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(Unknown Source:34)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(Unknown Source:78)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(Unknown Source:113)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [560, 316, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(Unknown Source:302)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(Unknown Source:149) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(Unknown Source:0) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(Unknown Source:34) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(Unknown Source:78) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(Unknown Source:113) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1786)
        at android.media.MediaCodec.createByCodecName(MediaCodec.java:1767)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(Unknown Source:242)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(Unknown Source:149) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(Unknown Source:0) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(Unknown Source:34) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(Unknown Source:78) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(Unknown Source:113) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by andrewlewis** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
