### ISSUE TITLE
h 265 video not working on exoplayer

### ISSUE THREAD

**Issue by chetan8378** [google/ExoPlayer#4450]
Hello Andrewlewis,

Please download the video provided with the given link and provide solution for the same

https://drive.google.com/file/d/1sGmrzM1cKYL3lf6-HQ3GtHrvAvWpqap5/view?usp=sharing

when we tried to play this video with our application using ExoPlayer it shows below mention log cat error.

E/ACodec: [OMX.rk.video_decoder.hevc] storeMetaDataInBuffers failed w/ err -1010
01-01 08:36:29.811 148-542/? E/mpp_log: open_vpu_memory_pool in
01-01 08:36:29.814 148-542/? E/OMXNodeInstance: getConfig(27:rk._decoder.hevc, ConfigCommonOutputCrop(0x700000f)) ERROR: UnsupportedIndex(0x8000101a)
01-01 08:36:30.319 148-3202/? E/H265HAL: mpp_buffer_group_get_internal used ion in

**Comment by chetan8378** [comment]
Please give suggestions

**Comment by chetan8378** [comment]
While running on device below marshmellow getting this error

07-02 12:00:19.684 29404-29792/? E/ACodec: [OMX.MTK.VIDEO.DECODER.HEVC] configureCodec returning error 80000000
07-02 12:00:19.684 29404-29791/? E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -2147483648)
07-02 12:00:19.685 29404-29443/? E/dalvikvm: Could not find class 'android.media.MediaCodec$CodecException', referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException.getDiagnosticInfoV21
07-02 12:00:19.691 29404-29443/? E/ExoPlayerImplInternal: Playback error.
                                                          com.google.android.exoplayer2.ExoPlaybackException
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:441)
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:428)
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:920)
                                                              at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:503)
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:557)
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
                                                              at android.os.Handler.dispatchMessage(Handler.java:106)
                                                              at android.os.Looper.loop(Looper.java:193)
                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                           Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.HEVC, Format(3, null, video/hevc, -1, null, [1920, 1080, -1.0], [-1, -1])
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:428) 
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:920) 
                                                              at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:503) 
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:557) 
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                              at android.os.Looper.loop(Looper.java:193) 
                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                           Caused by: java.lang.IllegalStateException
                                                              at android.media.MediaCodec.native_configure(Native Method)
                                                              at android.media.MediaCodec.configure(MediaCodec.java:267)
                                                              at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:450)
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:418)
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:920) 
                                                              at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:503) 
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:557) 
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                              at android.os.Looper.loop(Looper.java:193) 
                                                              at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by andrewlewis** [comment]
Please could you take a bug report with `adb bugreport` just after reproducing this error and attach it here or email it to `dev.exoplayer@gmail.com` with subject "Issue #4450"? Then we can see if there's any useful logging before the `DecoderInitializationException` is thrown.

**Comment by chetan8378** [comment]
Please check attached bug report generated after reproducing this error also I have email the bug report to the given email id.
[BugReports.txt](https://github.com/google/ExoPlayer/files/2157729/BugReports.txt)

**Comment by andrewlewis** [comment]
The logcat in the bug report only contains logging for a few seconds, and doesn't include a `DecoderInitializationException` unfortunately. Could you run `adb logcat`, reproduce the issue then attach the logging?

**Comment by chetan8378** [comment]
Please check attached bug report generated after reproducing this error and let me know if you need other details too. 
[BugReports.txt](https://github.com/google/ExoPlayer/files/2158205/BugReports.txt)

**Comment by andrewlewis** [comment]
Thanks. The underlying issue is probably indicated by "D MtkOmxVdec: Unsupported Video Resolution (1920, 1080), MAX(1280, 736)".

This device is running Android K, and there was no requirement to include any H.265/HEVC decoder in that version (see the [Android K CDD](https://source.android.com/compatibility/4.4/android-4.4-cdd#section-5.1)). Even when the requirement was added in Android L, only Android TV devices were required to support resolutions above 360p ([Android L CDD](https://source.android.com/compatibility/5.0/android-5.0-cdd#5_3_video_decoding)). So I think this media exceeds the baseline level of support from the platform and it's worked as intended that it can't be played.

**Comment by chetan8378** [comment]
Thank you @andrewlewis for your cooperation's
