### ISSUE TITLE
NullPointerException when DownloadService is re-started by Android and action is NULL

### ISSUE THREAD

**Issue by fpittersacc** [google/ExoPlayer#4488]
### Issue description
When DownloadService is re-launched by Android OS the intent passed on `onStartCommand` is NULL. Then a NPE is raised on DownloadService::230 -> `switch (intentAction) {`

As a temporary workaround you can protect the intent passed to DownloadService extending `onStartCommand` on your version of `DemoDownloadService`.

### Reproduction steps
Using ExoPlayer Demo:
1. Start a download.
2. Stop the application using Android Studio "Terminates selected application" button on Logcat tab. 

Service will be started again by OS.

### Version of ExoPlayer being used
2.8.2

### Device(s) and version(s) of Android being used
Nexus 5X - 8.1.0,
Samsung S6 - 6.0.1 
(Should be reproducible on any Android device/version)

### A full bug report captured from the device
```
07-09 12:46:55.421 30358-30358/com.google.android.exoplayer2.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.exoplayer2.demo, PID: 30358
    java.lang.RuntimeException: Unable to start service com.google.android.exoplayer2.demo.DemoDownloadService@7d9833f with null: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4080)
        at android.app.ActivityThread.access$2400(ActivityThread.java:222)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1898)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7229)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at com.google.android.exoplayer2.offline.DownloadService.onStartCommand(DownloadService.java:229)
```
[bugreport-bullhead-OPM2.171019.029-2018-07-09-13-12-43.zip](https://github.com/google/ExoPlayer/files/2175869/bugreport-bullhead-OPM2.171019.029-2018-07-09-13-12-43.zip)

**Comment by ojw28** [comment]
Fixed in `dev-v2`.
