### ISSUE TITLE
IllegalStateException: Assertions.checkState When using same instance of SimpleCache

### ISSUE THREAD

**Issue by joecizac** [google/ExoPlayer#4490]
Hi,
I am getting the exception
```
java.lang.IllegalStateException
at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
at com.google.android.exoplayer2.upstream.cache.SimpleCache.getContentMetadata(SimpleCache.java:348)
at com.google.android.exoplayer2.upstream.cache.SimpleCache.getContentLength(SimpleCache.java:335)
at com.google.android.exoplayer2.upstream.cache.CacheUtil.getCached(CacheUtil.java:88)
```
 when I'm trying to use the singleton instance of SimpleCache.
```
companion object DownloadCache {
        private var downloadCache: Cache? = null
        private var downloadDirectory: File? = null

        @Synchronized
        internal fun getDownloadCache(context: Context): Cache {
            if (downloadCache == null) {
                val downloadContentDirectory = File(getDownloadDirectory(context), "cache")
                downloadCache = SimpleCache(downloadContentDirectory, NoOpCacheEvictor())
            }
            return downloadCache!!
        }

        private fun getDownloadDirectory(context: Context): File {
            if (downloadDirectory == null) {
                downloadDirectory = File(LogTrackUtil().getDir(context))
                if (downloadDirectory == null) {
                    downloadDirectory = context.filesDir
                }
            }
            return downloadDirectory!!
        }
    }
```

I am checking the cached data for a particular URL.
The below code works perfectly for the first time but following calls to this code throws the exception.
```
downloadCache = VideoPlayerUtil.getDownloadCache(mContext!!) as SimpleCache
val uri = Uri.parse(mExercise?.fileUrl)
val counters = CacheUtil.CachingCounters()
CacheUtil.getCached(DataSpec(uri), downloadCache, counters)
```

What am I doing wrong?? Please help.

**Comment by erdemguven** [comment]
Probably, you're releasing your singleton instance of SimpleCache (using SimpleCache.release() method) at some point and then try to reuse it. That's why it's throwing that exception.

As you use a singleton, I think you can just remove the call to release(). Otherwise you need to recreate another SimpleCache instance after release() call.

**Comment by joecizac** [comment]
Oh such a silly mistake.
Thank you so much
