### ISSUE TITLE
NullPointerException for getBackground() of defaultTimeBar

### ISSUE THREAD

**Issue by halil-raso** [google/ExoPlayer#4504]
Hi

I need to get background of the defaultTimeBar (player controller) of exoplayer. but it throws null pointer exception.

Thanks in advance.

**Comment by halil-raso** [comment]
I need background of defaulttimebar for setting color filter at runtime.

**Comment by botaydotcom** [comment]
Hi @halil-raso,
 
Could you provide more information as required by the template? This includes the version of ExoPlayer used, a bug report captured when you encountered this error, and steps to reproduce your issue.

From what is reported here, I can't know what NPE was produced?
- Was that calling `DefaultTimeBar.getBackground()` led to NPE from somewhere inside that method (I tried with the latest version and didn't see this)?
- Or was that a timeBar you tried to call `getBackground()` on was null when you called this method on it? 
- Or was that getBackground() returned null, and you used that result to do something, which led to the NPE?

**Comment by halil-raso** [comment]
Hi @botaydotcom 

First thanks for answer. I am using last version of the exoplayer. Actually I need to change color of player controller views' colors. I successfully changed the color of these views except defaulttimebar'color. 
I could set attribute like app:played_color but what I need is setting such color at runtime. To achieve that I do the following:
`        ImageButton prevButton =findViewById(R.id.exo_prev);
        prevButton.setColorFilter(getResources().getColor(MainActivity.mood), PorterDuff.Mode.SRC_IN);
        ImageButton nextButton =findViewById(R.id.exo_next);
        nextButton.setColorFilter(getResources().getColor(MainActivity.mood), PorterDuff.Mode.SRC_IN);
        ImageButton fforwardButton =findViewById(R.id.exo_ffwd);
        fforwardButton.setColorFilter(getResources().getColor(MainActivity.mood), PorterDuff.Mode.SRC_IN);
        ImageButton rewindButton =findViewById(R.id.exo_rew);
        rewindButton.setColorFilter(getResources().getColor(MainActivity.mood), PorterDuff.Mode.SRC_IN);
        ImageButton playButton =findViewById(R.id.exo_play);
        playButton.setColorFilter(getResources().getColor(MainActivity.mood), PorterDuff.Mode.SRC_IN);
        ImageButton pauseButton =findViewById(R.id.exo_pause);
        pauseButton.setColorFilter(getResources().getColor(MainActivity.mood), PorterDuff.Mode.SRC_IN);
        TextView durationTextView = findViewById(R.id.exo_duration);
        durationTextView.setTextColor(getResources().getColor(MainActivity.mood));
        TextView positionTextView = findViewById(R.id.exo_position);
        positionTextView.setTextColor(getResources().getColor(MainActivity.mood));
        DefaultTimeBar defaultTimeBar =  findViewById(R.id.exo_progress);
        defaultTimeBar.getBackground().setColorFilter(getResources().getColor(MainActivity.mood), PorterDuff.Mode.SRC_IN);`

The exception thrown when trying to getbackground of defaultimebar. the code before that line works well.

ava.lang.RuntimeException: Unable to resume activity {com.maysiber.halil.ivme1/com.maysiber.halil.ivme.activities.VideoPlayerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(int, android.graphics.PorterDuff$Mode)' on a null object reference
                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(int, android.graphics.PorterDuff$Mode)' on a null object reference
                      at com.maysiber.halil.ivme.activities.VideoPlayerActivity.changeColorOfPlayerIcons(VideoPlayerActivity.java:219)
                      at com.maysiber.halil.ivme.activities.VideoPlayerActivity.init(VideoPlayerActivity.java:195)
                      at com.maysiber.halil.ivme.activities.VideoPlayerActivity.onResume(VideoPlayerActivity.java:248)
                      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
                      at android.app.Activity.performResume(Activity.java:6312)
                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)

Thanks in advance

**Comment by botaydotcom** [comment]
Since you are calling `defaultTimeBar.getBackground().setColorFilter(getResources().getColor(MainActivity.mood), PorterDuff.Mode.SRC_IN);`, when `defaultTimeBar.getBackground()` returns null, so it produces an NPE. There is no problem here with ExoPlayer library.

`DefaultTimeBar` does not use a background drawable/color, but draw itself using a few custom `Painter`. You can check out the code for `DefaultTimeBar.drawTimeBar()` and `DefaultTimeBar.drawPlayhead()` to get a better idea about this process.

If you want to set some custom colors at run time, you can use one of the `DefaultTimeBar.setXXXColor()` methods for this. Please check out `DefaultTimeBar` java doc to find out which `setColor()` method you should use for which scenario. For example, using app:played_color has the same effect as using method `setPlayedColor()`.
