### ISSUE TITLE
App Crashes on specific samsung devices 4.4.2

### ISSUE THREAD

**Issue by atif-afridi** [google/ExoPlayer#4506]
i am receiving the following crash on fabric with a user 

Fatal Exception: java.lang.NoClassDefFoundError
net.butterflytv.rtmp_client.RtmpClient

Detailed report i got on fabric

```
Fatal Exception: java.lang.NoClassDefFoundError: net.butterflytv.rtmp_client.RtmpClient
       at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:56)
       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:848)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by botaydotcom** [comment]
Hi @atif-afridi, 
The class should be there if you have a dependency on rmtp-client, which I think is necessary for the code to compile anyway. This seems to be a problem with the app installation for that particular user. I don't think we can offer any help in this case.

**Comment by atif-afridi** [comment]
Thanks for your response @botaydotcom  .. you mean i have to make the app installation again ? or what is the solution ?

**Comment by botaydotcom** [comment]
I guess if you are offering support for that particular user, then you can ask them to try re-install the app.

**Comment by atif-afridi** [comment]
@botaydotcom okay.. thanks for your words
