### ISSUE TITLE
Exception while pause then play live exoplayer version 2.8.2

### ISSUE THREAD

**Issue by luckylook** [google/ExoPlayer#4522]
Hi, I am getting this exception while I am trying to pause live video and then play it.
issue: I am playing live streaming then I click pause the video pauses (like regular behavior) then I wait about 15 sec and hit play the video plays about 10 sec and then I get exception below.
(Also, I noticed this first on version 2.7.3, I then upgraded to the latest version 2.8.2 and still the issue remains)

```
ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.BehindLiveWindowException
        at com.google.android.exoplayer2.source.dash.DefaultDashChunkSource.getNextChunk(DefaultDashChunkSource.java:317)
        at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.continueLoading(ChunkSampleStream.java:464)
        at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:78)
        at com.google.android.exoplayer2.source.dash.DashMediaPeriod.continueLoading(DashMediaPeriod.java:323)
        at com.google.android.exoplayer2.MediaPeriodHolder.continueLoading(MediaPeriodHolder.java:157)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1542)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1372)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:495)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
thx.

**Comment by ojw28** [comment]
This is working as intended. The server is only making the content available for a short window of time. If you pause the player, it will fall behind this window and will no longer be able to request media from the playback position (it will still be able to play out what it has in its buffer when you resume, but it wont be able to request any more).

If you control the serving side, you should make the live window at least as large as the period for which you want to allow users to pause and resume in this way.

**Comment by ojw28** [comment]
Note also that upon receiving `BehindLiveWindowException`, you can implement logic in your application code to automatically resume playback from the live edge. The demo app does this in its `PlayerActivity` class (see `onPlayerError` and `isBehindLiveWindow` in that class for details).

**Comment by luckylook** [comment]
ok thx :)

**Comment by luckylook** [comment]
how can i go back to live mode i trying to use player.seekTo(0) and that
return me to the start of the buffer when i hit pause

2018-07-17 14:07 GMT+03:00 ojw28 <notifications@github.com>:

**Comment by ojw28** [comment]
Use `seekToDefaultPosition` or `seekTo(C.TIME_UNSET)`.

**Comment by luckylook** [comment]
Thanks, but I have another problem right now :/
when I stop playing I call player.stop() and then player.release().
player.stop() runs with no errors but when player.release() is called right after it works fine sometimes but other times the app gets stuck when the code reaches player.release()
No exception is Thrown and the app is frozen/stuck and I get this:
I/ExoPlayerImpl: Release 21ad691 [ExoPlayerLib/2.8.2] [fugu, Nexus Player, Asus, 26] [goog.exo.core, goog.exo.ui, goog.exo.dash]
D/SurfaceUtils: disconnecting from surface 0xd192e808, reason pushBlankBuffersToNativeWindow
Thread[3,tid=23098,WaitingInMainSignalCatcherLoop,Thread*=0xeff24200,peer=0x13483690,"Signal Catcher"]: reacting to signal 3
