### ISSUE TITLE
ChunkSampleStream cannot handle empty chunks

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#4533]
It assumes a source has at least one sample. If it doesn't and reports EOS immediately, this happens:

```
 java.lang.ArrayIndexOutOfBoundsException: length=5; index=-1
       at java.util.ArrayList.get(ArrayList.java:439)
       at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.maybeNotifyPrimaryTrackFormatChanged(ChunkSampleStream.java:582)
       at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.maybeNotifyPrimaryTrackFormatChanged(ChunkSampleStream.java:577)
       at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.readData(ChunkSampleStream.java:358)
       at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:288)
       at com.google.android.exoplayer2.text.TextRenderer.render(TextRenderer.java:230)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

There are also some related edge cases to do with empty chunks:

* Should we report their formats to `downstreamFormatChanged` (probably yes, but we don't currently do this in all cases).
* Should we do this even if it's the very last chunk (probably yes).
* Should `discardBuffer` discard empty chunks immediately before the current position (probably no, since it breaks reporting their formats).

**Comment by brozikcz** [comment]
We have the same problem in our app when the subtitle track is not available (404 from the server).
We use dash / mpd playlist and it works fine until the user selects the unavailable subtitle.

ExoPlayer 2.8.1

**Comment by ojw28** [comment]
@brozikcz - It's unclear to me that the problem is the same. I think the failure mode is probably different for your case. Also, why are subtitle tracks declared in the manifest if they're not available?
