### ISSUE TITLE
Error inflating class com.google.android.exoplayer2.ui.PlayerControlView

### ISSUE THREAD

**Issue by zishanj** [google/ExoPlayer#4553]
In my activity layout I am using custom player like this:

```
<com.google.android.exoplayer2.ui.PlayerControlView
                android:id="@+id/playerControls"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:show_timeout="0"
                app:controller_layout_id="@layout/layout_player"/>
```

and this is `layout_player` controller from above:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/ll_player"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:divider="?android:attr/dividerHorizontal"
    android:orientation="vertical"
    android:gravity="center"
    android:paddingBottom="@dimen/space"
    android:showDividers="beginning">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:paddingRight="@dimen/activity_vertical_margin"
        android:paddingLeft="@dimen/activity_vertical_margin"
        android:paddingTop="@dimen/space"
        android:gravity="center"
        android:animateLayoutChanges="true">

        <ImageButton android:id="@id/exo_play"
            android:layout_width="@dimen/player_button_play_width"
            android:layout_height="@dimen/player_button_play_height"
            style="@style/ExoMediaButton.Play"
            android:background="@drawable/fab_ripple"/>

        <ImageButton android:id="@id/exo_pause"
            android:layout_width="@dimen/player_button_play_width"
            android:layout_height="@dimen/player_button_play_height"
            style="@style/ExoMediaButton.Pause"
            android:background="@drawable/fab_ripple"/>

        <RelativeLayout
            android:id="@+id/layout_seekbar"
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:visibility="gone">
            <TextView
                android:id="@+id/exo_position"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="@dimen/space"
                android:text="0:00"
                android:layout_alignParentStart="true"
                android:layout_alignParentTop="true"/>
            <TextView
                android:id="@+id/exo_duration"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginEnd="@dimen/space"
                android:text="0:00"
                android:layout_alignParentEnd="true"
                android:layout_alignParentTop="true"/>
            <com.google.android.exoplayer2.ui.DefaultTimeBar
                android:id="@id/exo_progress"
                android:layout_width="match_parent"
                android:layout_height="26dp"
                android:layout_below="@id/exo_position"
                app:scrubber_color="@color/colorAccent"
                app:played_color="@color/colorPrimary"
                app:buffered_color="@color/colorAccent"/>
        </RelativeLayout>

        <ImageButton
            android:id="@+id/btnFavorite"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:visibility="gone"
            android:layout_marginStart="@dimen/space"
            android:background="@drawable/ripple"
            android:tint="@color/colorAccent"
            android:contentDescription="@string/accessibility_favorite"
            app:srcCompat="@drawable/player_favorite_button"/>

        <ImageButton
            android:id="@+id/btnShare"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:visibility="gone"
            android:layout_marginStart="@dimen/space"
            android:background="@drawable/ripple"
            android:tint="@color/colorAccent"
            android:contentDescription="@string/accessibility_share"
            app:srcCompat="@drawable/ic_share_black_24dp"/>

        <ImageButton
            android:id="@+id/btnDownload"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:visibility="gone"
            android:layout_marginStart="@dimen/space"
            android:background="@drawable/ripple"
            android:contentDescription="@string/accessibility_download"
            app:srcCompat="@drawable/ic_file_download_black_24dp"/>
    </LinearLayout>
</LinearLayout>
```

In my activity I am referencing this layout using `ButterKnife` like this:

```
@BindView(R.id.playerControls)
PlayerControlView playerControls;
```

But on some devices user have reported this random crash:

```
Caused by android.view.InflateException: Binary XML file line #37: Binary XML file line #37: Error inflating class com.google.android.exoplayer2.ui.PlayerControlView
       at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at android.support.v7.app.AppCompatDelegateImplV9.onPostCreate(Unknown Source)
       at android.support.v7.app.AppCompatActivity.setContentView(Unknown Source)
       at com.test.download.DownloadActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6323)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
       at android.app.ActivityThread.access$900(ActivityThread.java:153)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5451)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ojw28** [comment]
It's quite hard to say what's causing this, particularly given you have a custom controller layout. Are you sure that exception is the root cause? I wouldn't be surprised if there's another "Caused by" exception after it, or else something in the logs before it, that gives the true root cause. Are you able to reproduce locally?

**Comment by zishanj** [comment]
I just investigated further and came to know that there was one image button which was not referenced correctly in the player layout. My bad! :)
