### ISSUE TITLE
Unable to play Big Buck Bunny(MP4) in the sample list on emulator

### ISSUE THREAD

**Issue by devenkhari** [google/ExoPlayer#456]
Hello,

In the Sample Chooser list, I clicked on Misc->Big Buck Bunny (MP4) but it didn't play rather there was some exception message which is appended below. The emulator is NEXUS_5_API_21_x86 and IDE is Android Studio. The earlier version of ExoPlayer was able to play on the same emulator. Please check what is going wrong.

Thanks!

05-14 02:46:00.628    1807-2304/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal runtime error.
    java.lang.IllegalStateException
            at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
            at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:819)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:502)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
05-14 02:46:00.639    1807-1807/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [2.36]
    com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:236)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.lang.IllegalStateException
            at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
            at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:819)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:502)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
05-14 02:46:00.694    1807-1876/com.google.android.exoplayer.demo W/EGL_emulation﹕ eglSurfaceAttrib not implemented
05-14 02:46:00.694    1807-1876/com.google.android.exoplayer.demo W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa5c43220, error=EGL_SUCCESS
05-14 02:46:00.716    1807-1807/com.google.android.exoplayer.demo D/EventLogger﹕ state [2.44, true, I]

**Comment by ojw28** [comment]
If it runs on a real device (which it does) then the bug is in the emulator, not in ExoPlayer. You should file a bug there instead.

**Comment by devenkhari** [comment]
Thanks for your prompt reply.
I wonder how the earlier version which I built last week from dev branch was working on the same emulator.

Regards

**Comment by devenkhari** [comment]
Yes, it is working on devices. I checked it on  multiple devices.

Thanks for your response.

Regards,
Deven
