### ISSUE TITLE
A resource was acquired at attached stack trace but never released

### ISSUE THREAD

**Issue by lminwang** [google/ExoPlayer#4576]
java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:222)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
        at okio.Okio.sink(Okio.java:181)
        at okhttp3.internal.io.FileSystem$1.sink(FileSystem.java:49)
        at okhttp3.internal.cache.DiskLruCache$Editor.newSink(DiskLruCache.java:899)
        at okhttp3.Cache$CacheRequestImpl.<init>(Cache.java:438)
        at okhttp3.Cache.put(Cache.java:251)
        at okhttp3.Cache$1.put(Cache.java:149)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:131)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.xiangkan.playersdk.videoplayer.OKHttpVideoClient$1.intercept(OKHttpVideoClient.java:46)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:152)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:42)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:314)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:189)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
