### ISSUE TITLE
When app is crashed because of download or delete, app could not play download content.

### ISSUE THREAD

**Issue by changja88** [google/ExoPlayer#4586]
When app is crashed because of download or delete, app could not play download content.
Before crash, everything works fine

```
07-27 10:06:58.785 29026-29026/laftel.net.laftel E/EventLogger: internalError [0.74, 0.00, window=0, period=0, loadError]
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 401
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:401)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:242)
        at com.google.android.exoplayer2.source.chunk.DataChunk.load(DataChunk.java:81)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
```

**Comment by AquilesCanta** [comment]
The provided snippet contains a invalid response code with the server, which I strongly doubt has anything to do with downloading. Please provide all the information requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE) and precise reproduction steps. If possible, in the demo app. We'll reopen once you include all requested information and post below. Thanks!
