### ISSUE TITLE
SingleSampleMediaSource doesn't work

### ISSUE THREAD

**Issue by Khang-NT** [google/ExoPlayer#4600]
### Issue description
I have list of audio + video streams with various quality. I created `SingleSampleMediaSource`s then merge them using `MergingMediaSource`,  it seems like not working.
But when I replace `SingleSampleMediaSource` with `ExtractorMediaSource`, then everything work fine. The reason I don't want to use `ExtractorMediaSource` is because `ExtractorMediaSource` establish connection to every stream to extract its format, it's very slow. I do know the format of each sample, so I use `SingleSampleMediaSource`.

### Reproduction steps 
This is my code:
```kotlin
val format = Format.createAudioContainerFormat(
                        null,
                        "audio/mp4", // container mime type
                        "audio/mp4a-latm", // sample mime type
                        "mp4a.40.2", // codecs
                        Format.NO_VALUE,
                        2, // channel count
                        44100, // sample rate
                        null,
                        C.SELECTION_FLAG_AUTOSELECT,
                        null
                )
val singleSampleMs = singleSampleMsFactory.createMediaSource(uri, format, C.TIME_UNSET)
```
### Link to test content
[test.mp4.zip](https://github.com/google/ExoPlayer/files/2244797/test.mp4.zip)

### Version of ExoPlayer being used
`2.8.2`

### Device(s) and version(s) of Android being used
Samsung S7

### A full bug report captured from the device
I found a crash log `Buffer too small (8192 < 4712674)`:
```
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:354)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.IllegalStateException: Buffer too small (8192 < 4712674)
        at com.google.android.exoplayer2.decoder.DecoderInputBuffer.createReplacementByteBuffer(DecoderInputBuffer.java:160)
        at com.google.android.exoplayer2.decoder.DecoderInputBuffer.ensureSpaceForWrite(DecoderInputBuffer.java:110)
        at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SampleStreamImpl.readData(SingleSampleMediaPeriod.java:297)
        at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:288)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:684)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

[test.mp4.zip](https://github.com/google/ExoPlayer/files/2244797/test.mp4.zip)

**Comment by erdemguven** [comment]
You can't use SingleSampleMediaSource to load regular media files (mp4 and other). You should use ExtractorMediaSource. 
If all the media is mp4 you can use Mp4Extractor.FACTORY with ExtractorMediaSource which might speed up start time.
@ojw28 Is there any other way to speed up ExtractorMediaSource if the format is known?

**Comment by ojw28** [comment]
> I have list of audio + video streams with various quality

There are multiple proper adaptive streaming standards for this kind of thing (DASH, HLS and SmoothStreaming). I suggest you use one of them, if you want to do this properly, rather than attempting to hack together an ad-hoc solution.
