### ISSUE TITLE
Random false EOFException when playing MP4 from local file

### ISSUE THREAD

**Issue by koral--** [google/ExoPlayer#4601]
### Issue description
Sometimes playing local MP4 produces false `EOFException`. It happens randomly. First retry in `onPlayerError` always works around this issue. MP4s are produced by MediaCodec on the same device. They always have portrait aspect ratio and are no longer than 6.5 s.

Message printed to the logcat by ExoPlayer library:
```
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.EOFException
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:70)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:848)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: java.io.EOFException
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:67)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:848) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:762) 
```

Exception received in `onPlayerError`:
```
com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:349)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.EOFException
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:70)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:848)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
    Caused by: java.io.EOFException
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:67)
    	... 6 more
```

### Reproduction steps
Play an mp4 from local `file://` Uri like this:
```kotlin
with(simpleExoPlayer) {
            playWhenReady = <true or false>
            repeatMode = Player.REPEAT_MODE_ALL
            volume = 0f
            addListener(object : Player.DefaultEventListener() {
                override fun onPlayerError(error: ExoPlaybackException) {
                    error.printStackTrace()
                }
            })

            prepare(ExtractorMediaSource.Factory(DefaultDataSourceFactory(appContext, Util.getUserAgent(appContext, "App")))
            .createMediaSource(uri))
        }
```

### Link to test content
[record.mp4.zip](https://github.com/google/ExoPlayer/files/2245246/record.mp4.zip)

### Version of ExoPlayer being used
2.8.1

### Device(s) and version(s) of Android being used
Multiple devices e.g. Samsung Galaxy S9+, S7, Pixel 2.
Haven't tested below Android 5.0 (API level 21), due to minSdkVersion of app.
Bugreport and sample MP4 are from S7 with Android 7.0.

### A full bug report captured from the device
Sent to dev.exoplayer@gmail.com

**Comment by erdemguven** [comment]
I tried playing the file you provided in a loop on Pixel 2 but couldn't manage to repeat the issue. I don't know what else we can do about it.

**Comment by koral--** [comment]
It reproduces randomly (sometimes few times in a row, sometimes never for 20 tries). 
Direct reason of that EOFException is that `dataSpec.position` value is much larger (a few orders of magnitude) than file length in `FileDataSource#open()`. Maybe this is some hint.

**Comment by ojw28** [comment]
Possibly theories:

* Whatever's writing the file hasn't fully flushed the data to disk at the point when you attempt to play it back.
* The SD card is unreliable on the test device.

To try and test these theories, could you try side-loading the same file onto a different device, and seeing if the issue reproduces there.

Also, it's somewhat curious that the file is ~13MB, but only contains a few hundred bytes of actual media data. That doesn't seem correct?

**Comment by koral--** [comment]
Thanks. I'll try side-loading that file.

ad theory 1.
MP4 is produced by `MediaCodec` and `MediaMuxer`. Before attempt to play back a file they are released synchronously (using their `release()` methods).

ad theory 2.
File is saved into internal storage and it happened on few different devices.

Regarding file size. It has ~10 Mb/s bitrate and 1 i-frame per second. It is camera recording, showing non-moving piece of paper. Not sure if it is normal for those conditions.

I'll get back here as soon I test what happens with sideloaded file.

**Comment by ojw28** [comment]
> Regarding file size. It has ~10 Mb/s bitrate and 1 i-frame per second. It is camera recording, showing non-moving piece of paper. Not sure if it is normal for those conditions.

I'm not sure if something went wrong with the recording, but the actual file only contains 5 frames of video (occupying only the first ~250K of the file), and has a media duration of ~101ms. So it definitely shouldn't end up being ~13MB.

**Comment by koral--** [comment]
Thanks for that hint.
I haven't yet checked theories 1. and 2. but there is an explanation why file has ~13 MB and only ~250 KB of usable data.
Basically we are using the same output file path and `MediaMuxer` does not truncate it. So there might be a longer file produced in the past at the same path and new creation has overwritten only the first ~250 KB. 

That is a bug on our side and we need to fix it by e.g. truncating the file. However, it does not explain why results are random for the same file.

**Comment by ojw28** [comment]
I don't think there's enough evidence this is an ExoPlayer bug, so removing the label for now. It seems more likely to be an issue with the way the files are being written. In which case you will not be able to reproduce by side-loading, so definitely let us know if you manage to do that!

**Comment by koral--** [comment]
I could not reproduce that issue with sideloaded file (both valid or one with extra trailing bytes). However once (when playing malformed file attached few posts above) I've encountered this unhandled exception:
```
    java.lang.IndexOutOfBoundsException
        at com.google.android.exoplayer2.Timeline$1.getPeriod(Timeline.java:516)
        at com.google.android.exoplayer2.Timeline.getPeriod(Timeline.java:749)
        at com.google.android.exoplayer2.ExoPlayerImpl.playbackInfoPositionUsToWindowPositionMs(ExoPlayerImpl.java:697)
        at com.google.android.exoplayer2.ExoPlayerImpl.getCurrentPosition(ExoPlayerImpl.java:465)
        at com.google.android.exoplayer2.ExoPlayerImpl.getContentPosition(ExoPlayerImpl.java:520)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:557)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:584)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.generatePlayingMediaPeriodEventTime(AnalyticsCollector.java:594)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.onTimelineChanged(AnalyticsCollector.java:408)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:661)
        at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:613)
        at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:558)
        at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:106)
        at android.os.Handler.dispatchMessage(Handler.java:105)
```
Does this one qualify as a bug?

**Comment by koral--** [comment]
OK, it seems that I figured out the reason of the last one and it looks unrelated. So there is no issue in ExoPlayer library.

Thanks for your hints and sorry for wasting your time.

**Comment by ojw28** [comment]
@tonihei - Might be worth taking a quick look at the stack trace above (just because I'm not sure it should ever be possible for IOOB to happen there).

**Comment by koral--** [comment]
I was able to capture a bugreport with that IOOB, reported as #4641.
