### ISSUE TITLE
java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/android/exoplayer2/upstream/DefaultAllocator;IIJJ)V in class Lcom/google/android/exoplayer2/DefaultLoadControl

### ISSUE THREAD

**Issue by ronit-kadwane** [google/ExoPlayer#4607]
I am developing react-native app using [react-native-track-player](https://github.com/react-native-kit/react-native-track-player) library, which is based on **ExoPlayer**.

Runtime error 

```
java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/android/exoplayer2/upstream/DefaultAllocator;IIJJ)V in class Lcom/google/android/exoplayer2/DefaultLoadControl; or its super classes (declaration of 'com.google.android.exoplayer2.DefaultLoadControl' appears in /data/app/com.joycemeyerministries.partner-2/base.apk)
        at guichaguri.trackplayer.player.players.ExoPlayback.<init>(ExoPlayback.java:62)
        at guichaguri.trackplayer.logic.MediaManager.createLocalPlayback(MediaManager.java:65)
        at guichaguri.trackplayer.logic.MediaManager.setupPlayer(MediaManager.java:78)
        at guichaguri.trackplayer.logic.components.MediaWrapper.setupPlayer(MediaWrapper.java:36)
        at guichaguri.trackplayer.TrackModule$1.run(TrackModule.java:143)
        at android.os.Handler.handleCallback(Handler.java:746)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5459)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

```
code snippet from where error occurring 
```
        DefaultAllocator allocator = new DefaultAllocator(true, 0x10000);  //ExoPlayback.java:62
        LoadControl control = new DefaultLoadControl(allocator, minBuffer, maxBuffer, playBuffer, playBuffer * multiplier);

        player = ExoPlayerFactory.newSimpleInstance(new DefaultRenderersFactory(context), new DefaultTrackSelector(), control);
        player.setAudioStreamType(C.STREAM_TYPE_MUSIC);

```
[here](https://github.com/react-native-kit/react-native-track-player/issues/236) is same issue posted but issue is open.

**Comment by erdemguven** [comment]
I think this issue should be resolved on react-native-track-player side.
