### ISSUE TITLE
HLS crash when RESOLUTION=0x0

### ISSUE THREAD

**Issue by hansvdg** [google/ExoPlayer#461]
Exoplayer: r1.3.1 from jcenter.

When playing HLS with unknown resolutions playback fails.
The master playlist looks like this:
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=627168,RESOLUTION=0x0
<baseurl>/1.m3u8

The exeption is this:
java.lang.ArithmeticException: divide by zero
            at com.google.android.exoplayer.util.Util.ceilDivide(Util.java:189)
            at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.getMaxVideoSizeInViewport(VideoFormatSelectorUtil.java:180)
            at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.selectVideoFormats(VideoFormatSelectorUtil.java:112)
            at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.selectVideoFormatsForDefaultDisplay(VideoFormatSelectorUtil.java:61)
            at <mypackage>.HlsRendererBuilder.onSingleManifest(HlsRendererBuilder.java:97)
            at <mypackage>.HlsRendererBuilder.onSingleManifest(HlsRendererBuilder.java:50)
            at com.google.android.exoplayer.util.ManifestFetcher$SingleFetchHelper.onLoadCompleted(ManifestFetcher.java:328)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:277)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by ojw28** [comment]
If the resolution is unknown then the RESOLUTION tag should be excluded from the playlist. Including it explicitly indicates that the resolution is 0x0, which is invalid.

We'll fix ExoPlayer to treat 0x0 as unknown, since it's easy to do, but I think whoever is generating this playlist file should fix the playlist to exclude the tag regardless.

**Comment by takn** [comment]
Does this fix work well with audio only tracks? A lot of times playlists will include an audio only track set (incorrectly) with a 0x0 resolution.
For example:

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=264000,CODECS="avc1.42001e, mp4a.40.2",RESOLUTION=416x234
file-264k.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=464000,CODECS="avc1.42001e, mp4a.40.2",RESOLUTION=480x270
file-464k.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=664000,CODECS="avc1.42001e, mp4a.40.2",RESOLUTION=640x360
file-664k.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5128000,CODECS="avc1.4d001f, mp4a.40.2",RESOLUTION=1280x720
file-5128k.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=8628000,CODECS="avc1.640028, mp4a.40.2",RESOLUTION=1920x1080
file-8628k.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=64000,CODECS="mp4a.40.2",RESOLUTION=0x0
file-64k.m3u8

**Comment by ojw28** [comment]
Should do yes.
