### ISSUE TITLE
HLS not working with AAC audio

### ISSUE THREAD

**Issue by TarifHatoum** [google/ExoPlayer#4636]
Playing a url with HLS and AAC audio results in a crash as below: 
**Reproduction steps:** 
use the link : http://185.99.32.173:1935/dvr/test1.stream_aac/playlist.m3u8?DVR

**Source error:**
                                                                                 com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://185.99.32.173:1935/dvr/test1.stream_aac/playlist.m3u8?DVR
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                     at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
                                                                                     at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
                                                                                     at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: java.net.SocketTimeoutException: failed to connect to /172.25.0.2 (port 1935) after 2000ms
                                                                                     at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
                                                                                     at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                                     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                                     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
                                                                                     at java.net.Socket.connect(Socket.java:884)
                                                                                     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
                                                                                     at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:434)
                                                                                     at com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:105)
                                                                                     at com.android.okhttp.Connection.connect(Connection.java:1331)
                                                                                     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410)
                                                                                     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131)
                                                                                     at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:484)
                                                                                     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:465)
                                                                                     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371)
                                                                                     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:476)
                                                                                     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:118)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:429)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:350)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                                                                                     at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101) 
                                                                                     at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64) 
                                                                                     at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114) 
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                     at java.lang.Thread.run(Thread.java:818) 

**Version of ExoPlayer being used**
Release 2.3.1
Release 2.4.2
Release 2.7.1

**Device(s) and version(s) of Android being used**
Android studio device emulator,
All Samsung devices

Please waiting for your reply since its a critical issue

**Comment by AquilesCanta** [comment]
Hi, I can successfully play the provided stream. Aside, the issue you are encountering does not seem to be ExoPlayer-related. It seems to be related to network issues. Please provide precise steps to reproduce in the demo app for us to take a look.
