### ISSUE TITLE
Getting NullPointerException in DefaultHlsPlaylistTracker

### ISSUE THREAD

**Issue by harshitwynk** [google/ExoPlayer#4637]
### Issue description
Some users of my app on production are getting crash.
PFB the crash logs

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.g.t.c()' on a null object reference
       at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker.release(DefaultHlsPlaylistTracker.java:113)
       at com.google.android.exoplayer2.source.hls.HlsMediaSource.releaseSourceInternal(HlsMediaSource.java:404)
       at com.google.android.exoplayer2.source.BaseMediaSource.prepareSourceInternal(BaseMediaSource.java:150)
       at com.google.android.exoplayer2.source.CompositeMediaSource.releaseSourceInternal(CompositeMediaSource.java:65)
       at com.google.android.exoplayer2.source.ConcatenatingMediaSource.releaseSourceInternal(ConcatenatingMediaSource.java:423)
       at com.google.android.exoplayer2.source.BaseMediaSource.prepareSourceInternal(BaseMediaSource.java:150)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:802)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:731)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:353)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:165)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

[stacktrace2.txt](https://github.com/google/ExoPlayer/files/2276754/stacktrace2.txt)

### Version of ExoPlayer being used
Exoplayer version - 2.8.2

### Device(s) and version(s) of Android being used
Device-Redmi Note 4     Android-7.0
Device-Mi A1     Android-8.1.0

[Uploading stacktrace2.txt…]()

**Comment by andrewlewis** [comment]
The stack trace doesn't quite make sense: `resetInternal` doesn't call `prepareSourceInternal` on the given line for example. Please could you check the right proguard map is being applied? It looks like `DefaultHlsPlaylistTracker` is being released twice but that's not expected to happen.

**Comment by chandraveerr** [comment]
I am also facing the exactly same crash in my app in production on exoplayer version 2.8.2. This crash happens while adding or removing media in ConcatenatingMediaSource using addMediaSource or removeMediaSource

**Comment by saipsa** [comment]
I am also having this issue. I am using exoplayer 2.8.2. It didn't happen on earlier versions.

**Comment by andrewlewis** [comment]
@saipsa Please could you provide the stack trace for the exception?

**Comment by saipsa** [comment]
@andrewlewis 
```
java.lang.NullPointerException: 
 
  at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker.release (DefaultHlsPlaylistTracker.java:113)
 
  at com.google.android.exoplayer2.source.hls.HlsMediaSource.releaseSourceInternal (HlsMediaSource.java:404)
 
  at com.google.android.exoplayer2.source.BaseMediaSource.releaseSource (BaseMediaSource.java:150)
 
  at com.google.android.exoplayer2.source.CompositeMediaSource.releaseSourceInternal (CompositeMediaSource.java:65)
 
  at com.google.android.exoplayer2.source.LoopingMediaSource.releaseSourceInternal (LoopingMediaSource.java:83)
 
  at com.google.android.exoplayer2.source.BaseMediaSource.releaseSource (BaseMediaSource.java:150)
 
  at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal (ExoPlayerImplInternal.java:802)
 
  at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal (ExoPlayerImplInternal.java:731)
 
  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage (ExoPlayerImplInternal.java:353)
 
  at android.os.Handler.dispatchMessage (Handler.java:101)
 
  at android.os.Looper.loop (Looper.java:164)
 
  at android.os.HandlerThread.run (HandlerThread.java:65)
```

**Comment by andrewlewis** [comment]
@saipsa Please make sure your app code isn't releasing the `MediaSource` (see also #3508).
