### ISSUE TITLE
Random IndexOutOfBoundsExceptions from Timeline.EMPTY.getPeriod

### ISSUE THREAD

**Issue by koral--** [google/ExoPlayer#4641]
### Issue description
`IndexOutOfBoundsException` is sometimes thrown. It seems to not depend on file nor device.

```
FATAL EXCEPTION: main
    Process: <stripped>, PID: 5219
    java.lang.IndexOutOfBoundsException
        at com.google.android.exoplayer2.Timeline$1.getPeriod(Timeline.java:516)
        at com.google.android.exoplayer2.Timeline.getPeriod(Timeline.java:749)
        at com.google.android.exoplayer2.ExoPlayerImpl.playbackInfoPositionUsToWindowPositionMs(ExoPlayerImpl.java:697)
        at com.google.android.exoplayer2.ExoPlayerImpl.getCurrentPosition(ExoPlayerImpl.java:465)
        at com.google.android.exoplayer2.ExoPlayerImpl.getContentPosition(ExoPlayerImpl.java:520)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:557)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:584)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.generatePlayingMediaPeriodEventTime(AnalyticsCollector.java:594)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.onTimelineChanged(AnalyticsCollector.java:408)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:661)
        at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:613)
        at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:558)
        at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:106)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5376)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

### Reproduction steps
Exact steps unknown. Interaction with ExoPlayer consist of using `SimpleExoPlayer` with local MP4s and seeking. Issue occurs just after starting playback.

### Link to test content
Sent to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
2.8.1

### Device(s) and version(s) of Android being used
Bugreport is from LG G4 H525-n with Android 5.0.2. However, it was observed also on other devices (probably Samsung Galaxy S7, S8 or S9+ with Android 6 to 8). Not tested on Android < 5 (API Level < 21).

### A full bug report captured from the device
Sent to dev.exoplayer@gmail.com

**Comment by tonihei** [comment]
This is most likely caused by parallel access to the player. Please only use the thread the player was created on to access the player, as described in the [developer guide](https://google.github.io/ExoPlayer/guide.html) under "Creating the player".

If you like, you can also comment on #4463 about why you use ExoPlayer from other threads and why it is needed to help us better understand your needs.

**Comment by koral--** [comment]
Thanks, it seems that parallel access from different threads is a reason here. 
BTW there is a bug in the last sentence of paragraph you linked. Instead of clickable Looper link there is a `{@link Looper}` text.

**Comment by tonihei** [comment]
Indeed :) Thanks for spotting that!
