### ISSUE TITLE
AES encrypted m3u8 stream error: "Cannot find sync byte. Most likely not a Transport Stream."

### ISSUE THREAD

**Issue by DeveloperMCD** [google/ExoPlayer#4660]
### Issue description
I have an M3U8 file, generated by FFMPEG (original source is an MP4 with AAC audio). It generates a series of .ts files: 720p_000.ts,  720p_001.ts, etc. I also add AES encryption. When I try to play the main .m3u8 file in exoplayer, it gives me an error.

NOTE: The file plays fine using hls.js, and it also plays in VLC, albeit with a bit of prodding (selecting the right Muxer) and in VLC there is popping and a bit of stuttering. But in HLS.js playback is butter smooth:
http://www.developermcd.com/cc/

Pertinent code on website:
```  var video = document.getElementById('video');
  if(Hls.isSupported()) {
    var hls = new Hls();
    hls.loadSource('ionic/720p.m3u8');
    hls.attachMedia(video);
    hls.on(Hls.Events.MANIFEST_PARSED,function() {
      video.play();
  });
 }
```

### Reproduction steps
```
MediaSource mediaSource = new HlsMediaSource.Factory(mediaDataSourceFactory)
 .createMediaSource(Uri.parse("http://www.developermcd.com/cc/ionic/720p.m3u8"));

```

### Link to test content
http://www.developermcd.com/cc/ionic/720p.m3u8

### Version of ExoPlayer being used
**2.8.3** (the latest version as of August 14, 2018)

### Device(s) and version(s) of Android being used
Tested on physical FireTV device: (Toshiba 43-inch 4K Ultra HD Smart LED TV HDR - Fire TV Edition) Android Nougat 7.1.2, API 25.

### A full bug report captured from the device
  **com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.**

```
08-14 12:06:39.541 16417-16417/? I/art: Late-enabling -Xcheck:jni
08-14 12:06:39.568 16417-16424/? I/art: Debugger is no longer active
08-14 12:06:39.568 16417-16424/? I/art: Starting a blocking GC Instrumentation
08-14 12:06:39.586 16417-16417/? D/VendorDisplayManagerGlobalCallback: callGetInstance: nil
08-14 12:06:39.884 16417-16417/? W/System: ClassLoader referenced unknown path: /data/app/com.yusufcakmak.exoplayersample-1/lib/arm
08-14 12:06:39.885 16417-16417/? W/System: ClassLoader referenced unknown path: /system/priv-app/MetricsApi/lib/arm
08-14 12:06:39.913 16417-16417/? I/FrameworkJumpTable: Successfully loaded all classes
08-14 12:06:39.928 16417-16417/? I/FrameworkJumpTable: Successfully loaded all methods
08-14 12:06:39.931 16417-16417/? I/FrameworkJumpTable: Successfully loaded all fields
08-14 12:06:39.931 16417-16417/? I/FrameworkJumpTable: Successfully loaded all constructors
08-14 12:06:39.934 16417-16417/? I/InstantRun: starting instant run server: is main process
08-14 12:06:40.233 16417-16417/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
08-14 12:06:40.473 16417-16577/? I/OpenGLRenderer: Initialized EGL, version 1.4
08-14 12:06:40.473 16417-16577/? D/OpenGLRenderer: Swap behavior 1
08-14 12:06:40.480 16417-16577/? D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
08-14 12:06:40.515 16417-16417/? W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
08-14 12:06:45.591 16417-16417/com.yusufcakmak.exoplayersample I/ExoPlayerImpl: Init da90782 [ExoPlayerLib/2.8.3] [keira, AFTKMST12, Amazon, 25]
08-14 12:06:45.654 16417-16622/com.yusufcakmak.exoplayersample D/NetworkSecurityConfig: No Network Security Config specified, using platform default
08-14 12:06:45.686 16417-16577/com.yusufcakmak.exoplayersample D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
08-14 12:06:45.789 16417-16621/com.yusufcakmak.exoplayersample E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:256)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:280)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:214)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
08-14 12:06:49.884 16417-16577/com.yusufcakmak.exoplayersample D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
08-14 12:06:50.122 16417-16417/com.yusufcakmak.exoplayersample I/ExoPlayerImpl: Release da90782 [ExoPlayerLib/2.8.3] [keira, AFTKMST12, Amazon, 25] [goog.exo.core, goog.exo.ui, goog.exo.hls]
```

I realize that similar bugs have been reported, but I believe my case warrants further attention for 2 reasons:

1. I have provided a public *.m3u8 file that can be analyzed. (I haven't made basic errors like posting a URL to localhost://_______)
2. One of the "solutions" proffered in the other bug reports didn't work.

When I change the m3u8 to use *.mp4 instead of *.ts for the fragment files, I get a different error:

 **com.google.android.exoplayer2.ParserException: Skipping atom with length > 2147483647 (unsupported).**

```08-14 12:18:08.841 17094-17094/? D/VendorDisplayManagerGlobalCallback: callGetInstance: nil
08-14 12:18:09.151 17094-17094/? W/System: ClassLoader referenced unknown path: /data/app/com.yusufcakmak.exoplayersample-2/lib/arm
08-14 12:18:09.152 17094-17094/? W/System: ClassLoader referenced unknown path: /system/priv-app/MetricsApi/lib/arm
08-14 12:18:09.170 17094-17094/? I/FrameworkJumpTable: Successfully loaded all classes
08-14 12:18:09.183 17094-17094/? I/FrameworkJumpTable: Successfully loaded all methods
08-14 12:18:09.185 17094-17094/? I/FrameworkJumpTable: Successfully loaded all fields
    Successfully loaded all constructors
08-14 12:18:09.187 17094-17094/? I/InstantRun: starting instant run server: is main process
08-14 12:18:09.479 17094-17094/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
08-14 12:18:09.747 17094-17127/? I/OpenGLRenderer: Initialized EGL, version 1.4
08-14 12:18:09.747 17094-17127/? D/OpenGLRenderer: Swap behavior 1
08-14 12:18:09.754 17094-17127/? D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
08-14 12:18:09.793 17094-17094/? W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
08-14 12:18:12.913 17094-17094/com.yusufcakmak.exoplayersample I/ExoPlayerImpl: Init da90782 [ExoPlayerLib/2.8.3] [keira, AFTKMST12, Amazon, 25]
08-14 12:18:12.966 17094-17151/com.yusufcakmak.exoplayersample D/NetworkSecurityConfig: No Network Security Config specified, using platform default
08-14 12:18:12.993 17094-17127/com.yusufcakmak.exoplayersample D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
08-14 12:18:13.107 17094-17150/com.yusufcakmak.exoplayersample E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.ParserException: Skipping atom with length > 2147483647 (unsupported).
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomHeader(FragmentedMp4Extractor.java:411)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:309)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:280)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:214)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
08-14 12:18:16.865 17094-17127/com.yusufcakmak.exoplayersample D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
08-14 12:18:17.111 17094-17094/com.yusufcakmak.exoplayersample I/ExoPlayerImpl: Release da90782 [ExoPlayerLib/2.8.3] [keira, AFTKMST12, Amazon, 25] [goog.exo.core, goog.exo.ui, goog.exo.hls]
```

**Comment by AquilesCanta** [comment]
The key looks weird. From the spec:

_[AES_128] encryption uses 16-octet keys.  If the KEYFORMAT of an EXT-X-KEY tag is "identity", the Key file is a single packed array of 16 octets in binary format._

If the key is wrong then decryption will fail and the extractor input will not be container compliant. You should make sure that encryption follows the specification and that the decrypted content matches the original content.

**Comment by wangdaliu** [comment]
@AquilesCanta  i also have this issue `Cannot find sync byte. Most likely not a Transport Stream` with https://d10xbpcmtwxcsn.cloudfront.net/HLS/SampleTrimmed.m3u8(H265). And I can open this in safari.
