### ISSUE TITLE
ReleaseSource causes NullPointerException

### ISSUE THREAD

**Issue by casolorz** [google/ExoPlayer#4677]
I'm loading an m3u8 on ExoPlayer 2.8.2. When the user plays stop I call `releaseSource` on my `HlsMediaSource`. I create the `HlsMediaSource` like this ` new HlsMediaSource.Factory(defaultDataSourceFactory).createMediaSource(uri);`

I didn't have this problem when I used ExoPlayer 2.2.0 but MoPub updated to 2.8.2 so I was forced to update my code as well. What am I doing wrong? Should I not be calling `releaseSource`?

Here is the exception:

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.upstream.Loader.release()' on a null object reference
        at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker.release(DefaultHlsPlaylistTracker.java:113)
        at com.google.android.exoplayer2.source.hls.HlsMediaSource.releaseSourceInternal(HlsMediaSource.java:404)
        at com.google.android.exoplayer2.source.BaseMediaSource.releaseSource(BaseMediaSource.java:150)

Thanks.

**Comment by casolorz** [comment]
Just realized my call to stop and release `SimpleExoPlayer` already does that and that is why there is a null for `initialPlaylistLoader`.
