### ISSUE TITLE
Support continued playback of merged source if some child sources are unavailable

### ISSUE THREAD

**Issue by vipulim** [google/ExoPlayer#4688]
### Issue description
I need to create a player in which multiple live streams should play in synchronization, which I've achieved by following @ojw28 solution in #2855. I'm able to play multiple live streams using multiple renderers. 

Now when any of the live streams are broken (not broadcasting or the link does not exist at all - HTTP 404), none of the renderers start playing, all of the provide source should be live to start playback.
I'm getting source list from API and their live status are unknown to me. 

Is there any way I can play the rest of the renderer if any of the sources is unavailable?
One way I can see is to implement `MediaSourceEventListener` and track which source is having an issue and then get the index of the renderer attached with the source and update `TrackSelector` for not to load that renderer.

Don't know if its a right approach or not.
Can you please guide me.

Thanks in advance!

### Reproduction steps
Same as @derekw0311 described in issue #4014:

> 
        1. Build a custom RenderersFactory that builds multiple video renderers.
        2. Create multiple ExtractorMediaSources and combine them use MergingMediaSource
        3. Build a custom TrackSelector to select correct tracks for each of the video renderers
        4. Map textureSurface to the corresponding renderers using 'createMessage'

### Link to test content
Unfortunately, my media server is on my local environment so I cannot share the live feed links but you can use some open VOD links like:
- http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8
- http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8

For the unavailable stream, you can use any dummy link.
### Version of ExoPlayer being used
ExoPlayer: 2.8.3

### Device(s) and version(s) of Android being used
I've tested this on Galaxy S8, OnePlus One, Nexus 5X devices
and on Android OS version 7.1 and 8.1

### A full bug report captured from the device
NA

**Comment by vipulim** [comment]
Can anyone please respond on this issue?

**Comment by ojw28** [comment]
I would suggest you try the following (although I haven't tried this, so you might encounter a reason it doesn't work):

* Implement a `Renderer` that wraps another `Renderer`. To start with just implement it to call through to the wrapped `Renderer`.
* Modify `maybeThrowStreamError` to never throw, but instead catch any exception thrown by the wrapped `Renderer`, and set a boolean `sourceError` flag.
* Modify `isReady`, `isEnded` and `hasReadStreamToEnd` to always return true rather than calling through to the wrapped `Renderer` if the `sourceError` flag is set.
* Clear the `sourceError` flag in `enable` and `replaceStream`, before calling through to the wrapped `Renderer`.
* When the flag is set you probably want to turn some methods into no-ops. For example `render` should probably do nothing in this case.

Once you have this, try wrapping all of the `Renderer`s that your player is using with your new wrapper. If you have one stream that you do want to cause playback to fail (e.g. the primary one), don't wrap the corresponding `Renderer`s. Does that result in the desired behavior?

**Comment by vipulim** [comment]
Thanks, @ojw28 for your detailed answer.
I've created a wrapper `renderer` which wraps my original renderer and modified the code according to your instructions. 

But `maybeThrowStreamError` never get called on wrapper renderer. Other renderers still getting stopped if one of the sources is unreachable.

According to your 2nd point:
> Modify maybeThrowStreamError to never throw, but instead catch any exception thrown by the wrapped Renderer, and set a boolean sourceError flag.

I don't know how to catch exceptions thrown by the renderer, I might be missing something. Can you please guide me with this too.

I'm getting the following exception when I add an unreachable media source:
```
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:175)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:137)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```
As per my limited knowledge it seems more like data soruce error rather than related with renderer, renderes might not getting notfied about this.

Below is wrapper class code:
```
public class WrapperRenderer implements Renderer {
    private static final String TAG = WrapperRenderer.class.getSimpleName();

    private ExoCodecVideoRenderer mExoCodecVideoRenderer;
    private boolean mSourceError;

    public WrapperRenderer(ExoCodecVideoRenderer mExoCodecVideoRenderer) {
        this.mExoCodecVideoRenderer = mExoCodecVideoRenderer;
    }

    @Override
    public int getTrackType() {
        return mExoCodecVideoRenderer.getTrackType();
    }

    @Override
    public RendererCapabilities getCapabilities() {
        return mExoCodecVideoRenderer.getCapabilities();
    }

    @Override
    public void setIndex(int index) {
        mExoCodecVideoRenderer.setIndex(index);
    }

    @Override
    public MediaClock getMediaClock() {
        return mExoCodecVideoRenderer.getMediaClock();
    }

    @Override
    public int getState() {
        return mExoCodecVideoRenderer.getState();
    }

    @Override
    public void enable(RendererConfiguration configuration, Format[] formats, SampleStream stream, long positionUs, boolean joining, long offsetUs) throws ExoPlaybackException {
        mSourceError = false;
        mExoCodecVideoRenderer.enable(configuration, formats, stream, positionUs, joining, offsetUs);
    }

    @Override
    public void start() throws ExoPlaybackException {
        mExoCodecVideoRenderer.start();
    }

    @Override
    public void replaceStream(Format[] formats, SampleStream stream, long offsetUs) throws ExoPlaybackException {
        mSourceError = false;
        mExoCodecVideoRenderer.replaceStream(formats, stream, offsetUs);
    }

    @Override
    public SampleStream getStream() {
        return mExoCodecVideoRenderer.getStream();
    }

    @Override
    public boolean hasReadStreamToEnd() {
        if (mSourceError) {
            return true;
        }
        return mExoCodecVideoRenderer.hasReadStreamToEnd();
    }

    @Override
    public void setCurrentStreamFinal() {
        mExoCodecVideoRenderer.setCurrentStreamFinal();
    }

    @Override
    public boolean isCurrentStreamFinal() {
        return mExoCodecVideoRenderer.isCurrentStreamFinal();
    }

    @Override
    public void maybeThrowStreamError() {
        Log.e(TAG, "Error occurred in wrapper renderer class");
        this.mSourceError = true;
    }

    @Override
    public void resetPosition(long positionUs) throws ExoPlaybackException {
        mExoCodecVideoRenderer.resetPosition(positionUs);
    }

    @Override
    public void render(long positionUs, long elapsedRealtimeUs) throws ExoPlaybackException {
        mExoCodecVideoRenderer.render(positionUs, elapsedRealtimeUs);
    }

    @Override
    public boolean isReady() {
        if (mSourceError) {
            return true;
        }
        return mExoCodecVideoRenderer.isReady();
    }

    @Override
    public boolean isEnded() {
        if (mSourceError) {
            return true;
        }
        return mExoCodecVideoRenderer.isEnded();
    }

    @Override
    public void stop() throws ExoPlaybackException {
        mExoCodecVideoRenderer.stop();
    }

    @Override
    public void disable() {
        mExoCodecVideoRenderer.disable();
    }

    @Override
    public void handleMessage(int messageType, Object payload) throws ExoPlaybackException {
        mExoCodecVideoRenderer.handleMessage(messageType, payload);
    }
}
```

**Comment by ojw28** [comment]
> I don't know how to catch exceptions thrown by the renderer, I might be missing something. Can you please guide me with this too.

```
try {
  wrappedRenderer.maybeThrowStreamError();
} catch (IOException e) {
  // Do not re-throw.
  mSourceError = true;
}
```

> But maybeThrowStreamError never get called on wrapper renderer. Other renderers still getting stopped if one of the sources is unreachable... As per my limited knowledge it seems more like data soruce error rather than related with renderer, renderes might not getting notfied about this.

Ah, yes. Source errors can be propagated both through the `Renderer` (failure during playback), or directly from the source (during preparation). My solution only covers the first case, where-as you're most likely hitting the second.

You might need to do something similar, but wrapping `MediaSource`/`MediaPeriod`/`SampleStream` instead. This approach could be used to suppress all errors being thrown out of the source. It's probably quite complicated to do though.

**Comment by vipulim** [comment]
@ojw28 
Seems like it's beyond my competence.
Kindly let me know if you guys have any plan to include any simplified mechanism of doing this in ExoPlayer in future.

Thanks for your support.

**Comment by ojw28** [comment]
I've marked this as a low priority enhancement. We may look at adding support in the future.

**Comment by tonihei** [comment]
#4343 also tracks a similar issue for skipping media sources in ConcateningMediaSource if they fail to load.
