### ISSUE TITLE
How to play live audio streaming url with https?

### ISSUE THREAD

**Issue by deven-rajput** [google/ExoPlayer#4697]
How to play live audio streaming with https?

Live Audio url="https://hls_live_sanjha-i.akamaihd.net/hls/live/582260/abpsanjha/masterhls_a_32.m3u8

### We are using a version of ExoPlayer
    implementation 'com.google.android.exoplayer:exoplayer-core:2.8.2'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.8.2'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.8.2'
    implementation 'com.google.android.exoplayer:exoplayer:2.8.2'
    implementation 'com.google.android.exoplayer:extension-ima:2.8.2'
    implementation 'com.google.android.exoplayer:extension-okhttp:2.8.2'

### Device(s) and version(s) of Android being used
All devices.

### A full bug report captured from the device

```
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://hls_live_sanjha-i.akamaihd.net/hls/live/582260/abpsanjha/masterhls_a_32.m3u8
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:137)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
     Caused by: javax.net.ssl.SSLHandshakeException: java.lang.IllegalArgumentException: Invalid input to toASCII: hls_live_sanjha-i.akamaihd.net
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
        at com.android.okhttp.Connection.connectTls(Connection.java:235)
        at com.android.okhttp.Connection.connectSocket(Connection.java:199)
        at com.android.okhttp.Connection.connect(Connection.java:172)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:429)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:350)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:137) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:760) 
     Caused by: java.security.cert.CertificateException: java.lang.IllegalArgumentException: Invalid input to toASCII: hls_live_sanjha-i.akamaihd.net
        at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:617)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
        at com.android.okhttp.Connection.connectTls(Connection.java:235) 
        at com.android.okhttp.Connection.connectSocket(Connection.java:199) 
        at com.android.okhttp.Connection.connect(Connection.java:172) 
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367) 
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130) 
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330) 
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126) 
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89) 
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:429) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:350) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:137) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:760) 
     Caused by: java.lang.IllegalArgumentException: Invalid input to toASCII: hls_live_sanjha-i.akamaihd.net
        at java.net.IDN.toASCII(IDN.java:112)
        at javax.net.ssl.SNIHostName.<init>(SNIHostName.java:99)
        at com.android.org.conscrypt.Platform.getSSLParameters(Platform.java:133)
        at com.android.org.conscrypt.OpenSSLSocketImpl.getSSLParameters(OpenSSLSocketImpl.java:1320)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:302)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
        at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357) 
        at com.android.okhttp.Connection.connectTls(Connection.java:235) 
        at com.android.okhttp.Connection.connectSocket(Connection.java:199) 
        at com.android.okhttp.Connection.connect(Connection.java:172) 
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367) 
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130) 
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330) 
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126) 
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89) 
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:429) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:350) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:137) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:760) 
     Caused by: The input does not conform to the STD 3 ASCII rules. line:  0. preContext:  . postContext: e_sanjha-i
    
        at android.icu.impl.IDNA2003.convertToASCII(IDNA2003.java:214)
        at android.icu.impl.IDNA2003.convertIDNToASCII(IDNA2003.java:275)
        at android.icu.text.IDNA.convertIDNToASCII(IDNA.java:652)
        at java.net.IDN.toASCII(IDN.java:110)
        	... 32 more
```

**Comment by ojw28** [comment]
Please see: https://stackoverflow.com/questions/5362954/why-use-instead-off-in-url, which suggests that:

* Use of underscore in the host name of a URL is invalid
* Several network libraries refuse to handle underscore when present in the host name

This is the case for the Android network stack, it seems. So the solution is to not use underscores in the host name.
