### ISSUE TITLE
Getting EOFException when using ExtractorSampleSource with MP4Extractor

### ISSUE THREAD

**Issue by raylee4204** [google/ExoPlayer#471]
Using 1.3.2 version of Exoplayer, I'm having an issue with playing audio from url.

The link i'm using to play is http://previews.7digital.com/clip/23154814?shopid=1756&userId=qa-856&formatId=56&oauth_consumer_key=7dwqyampfmhr&oauth_nonce=1432144628919&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1432144628&oauth_signature=%2BOztZIB4rVOFxH%2F8zN9kpTmTMvc%3D

The logs are :
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.io.EOFException
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:253)
            at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:116)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:155)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.io.EOFException
            at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:254)
            at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:165)
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:68)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomHeader(Mp4Extractor.java:142)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:98)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:615)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:242)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.io.EOFException
            at com.google.android.exoplayer.upstream.DefaultHttpDataSource.skipInternal(DefaultHttpDataSource.java:496)
            at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:251)
            at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:165)
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:68)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomHeader(Mp4Extractor.java:142)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:98)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:615)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:242)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by raylee4204** [comment]
The source is mp3 file. Closing this

**Comment by manishmips28** [comment]
I am getting same exception while playing video using DASH url .Scenario is while I pressed home button between playing content some time its resume video but some time I am getting java.io.EOFException
following is exception log please help .

`EventLogger: internalError [3.97, loadError]
                                                                   java.io.EOFException
                                                                       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:252)
                                                                       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
                                                                       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:76)
                                                                       at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:346)
                                                                       at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:248)
                                                                       at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:127)
                                                                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
ExoPlayerImplInternal: Source error.
                                                                             java.io.EOFException
                                                                                 at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:252)
                                                                                 at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
                                                                                 at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:76)
                                                                                 at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:346)
                                                                                 at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:248)
                                                                                 at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:127)
                                                                                 at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                 at java.lang.Thread.run(Thread.java:841)
E/EventLogger: playerFailed [3.98]
                                                                   com.google.android.exoplayer2.ExoPlaybackException
                                                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:345)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                       at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                    Caused by: java.io.EOFException
                                                                       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:252)
                                                                       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
                                                                       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:76)
                                                                       at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:346)
                                                                       at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:248)
                                                                       at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:127)
                                                                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:841)`
