### ISSUE TITLE
Connection with Firebase is not stable

### ISSUE THREAD

**Issue by ArcherEmiya05** [google/ExoPlayer#4734]
Sometimes streaming with Exoplayer using FirebaseStorage gets an error and stuck in buffering.

Exoplayer 2.8.1

LG K10
Android M

              E/ExoPlayerImplInternal: Source error.
                         com.google.android.exoplayer2.k.r$e: Response code: 402
                             at com.google.android.exoplayer2.k.o.a(DefaultHttpDataSource.java:211)
                             at com.google.android.exoplayer2.k.m.a(DefaultDataSource.java:147)
                             at com.google.android.exoplayer2.h.j$a.c(ExtractorMediaPeriod.java:848)
                             at com.google.android.exoplayer2.k.s$b.run(Loader.java:317)
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                             at java.lang.Thread.run(Thread.java:818)

Is this an error from the server itself?

**Comment by ojw28** [comment]
A quick search for `firebase storage "402"` suggests to me that you're hitting a Firebase Storage quota limit. I'd suggest you investigate that. In any case, the root issue here is that the server is returning a HTTP status code 402. This is not an ExoPlayer issue, but rather that the server choosing not to serve the content.
