### ISSUE TITLE
My url previously on http than i was SSl so its https url and then i am facing below issue

### ISSUE THREAD

**Issue by anilsangani** [google/ExoPlayer#4736]
i just called all audio file from server put it in recyclerview than play it with exoplayer

 Source error.

```                                                       com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 302
                                                           at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                           at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:141)
                                                           at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:737)
                                                           at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                           at java.lang.Thread.run(Thread.java:761)
```

**Comment by AquilesCanta** [comment]
Is `allowCrossProtocolRedirects == true` in your `DefaultHttpDataSource`? If not, please set it to true. If it is true, then please file the full issue template and we will reopen the issue. Thanks!

**Comment by anilsangani** [comment]
How to set allowCrossProtocolRedirects == true , i was trying many times but i didnt find any solution
please help me

```java
        renderersFactory = new DefaultRenderersFactory(getActivity());
        bandwidthMeter = new DefaultBandwidthMeter();
        trackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        trackSelector = new DefaultTrackSelector(trackSelectionFactory);
        loadControl = new DefaultLoadControl();
        player = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector, loadControl);
        dataSourceFactory = new DefaultDataSourceFactory(getActivity(), "ExoplayerDemo");
        extractorsFactory = new DefaultExtractorsFactory();`


ringtoneAdapter = new RingtoneAdapter1(ringtoneList, getActivity(), player, mediaSource, trackSelectionFactory, dataSourceFactory, extractorsFactory, mainHandler, renderersFactory, bandwidthMeter, loadControl, trackSelector, playeditem, Boolean.valueOf(false));


mediaSource = new ExtractorMediaSource
                            .Factory(dataSourceFactory)
                            .setExtractorsFactory(extractorsFactory)
                            .createMediaSource(Uri.parse(ringtoneList.get(position).getUrl()), mainHandler, null);
                    player.seekTo(0);

  player.setPlayWhenReady(true);
                    player.prepare(mediaSource);
```

**Comment by AquilesCanta** [comment]
Instead of passing a DefaultDataSourceFactory to the ExtractorMediaSource builder, create a custom factory that sets allowCrossProtocolRedirects to true. You need to do basically the same that DefaultDataSourceFactory does, except you need to change the `DefaultDataSource` constructor that gets used in `DefaultDataSource#createDataSource()` to be `DefaultDataSource(Context context, String userAgent, boolean allowCrossProtocolRedirects)`. Hope this helps.

**Comment by anilsangani** [comment]
I dont understand please can you give more details
