### ISSUE TITLE
demo-cast error

### ISSUE THREAD

**Issue by 986558210** [google/ExoPlayer#4743]
Caused by: java.lang.RuntimeException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
        at com.google.android.gms.internal.cast.zze.zzf(Unknown Source)
        at com.google.android.gms.internal.cast.zze.zza(Unknown Source)
        at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source)
        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source)
        at com.google.android.exoplayer2.castdemo.MainActivity.onCreate(MainActivity.java:66)

**Comment by AquilesCanta** [comment]
Please try updating Google Play Services on the device. If this does not fix your issue please fill all information requested in the issue template. If it does fix your issue, please let us know so we try adding a workaround to our cast demo app.

**Comment by 986558210** [comment]
Oh, I see. I did not install the Google Play Service and I can`t install it because I`m in China.  Thank you.
