### ISSUE TITLE
Question - Listening to Exceptions / Errors

### ISSUE THREAD

**Issue by pbertsch** [google/ExoPlayer#4761]
Hi,

Is there a way to listen to EOFException which sometimes happen inside the SampleQueue.sampleData method. I want to Skip those videos in my playlist.

`E/ExoPlayerImplInternal: Source error.
                         java.io.EOFException
                             at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:553)
                             at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:544)
                             at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:191)
                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:856)
                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                             at java.lang.Thread.run(Thread.java:818)`

**Comment by pbertsch** [comment]
I found the solution, sorry for bothering.
