### ISSUE TITLE
onPlayerError return error exception

### ISSUE THREAD

**Issue by reallychenchi** [google/ExoPlayer#4770]
I use explayer 2.4.1, and some users(not all) report this error, I can not get the actual video file in user's phone, any one can help to give some suggestion about the exception? Why it happens and what should I do for this exception?

com.google.android.exoplayer2.e
	at com.google.android.exoplayer2.i.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.IllegalStateException
	at android.media.MediaCodec.native_stop(Native Method)
	at android.media.MediaCodec.stop(MediaCodec.java:2007)
	at com.google.android.exoplayer2.e.b.C(Unknown Source)
	at com.google.android.exoplayer2.l.d.a(Unknown Source)
	at com.google.android.exoplayer2.l.d.a(Unknown Source)
	at com.google.android.exoplayer2.i.c(Unknown Source)
	... 4 more
java.lang.IllegalStateException
	at android.media.MediaCodec.native_stop(Native Method)
	at android.media.MediaCodec.stop(MediaCodec.java:2007)
	at com.google.android.exoplayer2.e.b.C(Unknown Source)
	at com.google.android.exoplayer2.l.d.a(Unknown Source)
	at com.google.android.exoplayer2.l.d.a(Unknown Source)
	at com.google.android.exoplayer2.i.c(Unknown Source)
	at com.google.android.exoplayer2.i.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by tonihei** [comment]
I've seen this exception before when the user leaves the app and this is part of the final release of the player. That's probably a platform bug and we haven't found any negative effects yet. Also happens in our demo app. 

If you think it happens in another situation, please try to get more reproduction info, bugreports etc. to allow us to better understand what's going on.

**Comment by tonihei** [comment]
Closing for now as no further information is available. If you get something new which isn't explained by the effect I described above, please feel free to reopen the issue.
