### ISSUE TITLE
Unable to playback the hls .v3.exo chunks downloaded [UnrecognizedInputFormatException]

### ISSUE THREAD

**Issue by billyjoker** [google/ExoPlayer#4808]
I am trying to playback offline dowloaded HLS. So, currently i have a dir with all the "xxx.v3.exo" chunks, and i followed this [guide](https://medium.com/google-exoplayer/downloading-streams-6d259eec7f95), but i have got this thrown exception:

```
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:820)
at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:742)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
I do not why it says that, becaused i have all the renderers properly setted, any ideas? Thanks in advance.

```

I've turned off the wifi in order to force reproduce the offline content, with no success, any idea? Any help would be very appreciated.

Version of ExoPlayer being used
2.6.1

Device(s) and version(s) of Android being used
LG G3 Android 5.0

**Comment by ojw28** [comment]
It appears you are using `ExtractorMediaSource`, where-as for HLS you should be using `HlsMediaSource`.
