### ISSUE TITLE
Decrypting Keyfile URI before it's used for AES decryption by the library

### ISSUE THREAD

**Issue by DeveloperMCD** [google/ExoPlayer#4820]
Hi,
I'm trying to play back an HLS media playlist with Exoplayer2, but my use case seems to set me apart from at least 95% of developers who use Exoplayer. I can't include the actual AES key in the *.m3u8 file 
(EXT-X-KEY:METHOD=AES-128,URI="http://website.com/aes.key")
I'm trying to encrypt this AES key with RSA encryption.

So the URI included in the media playlist doesn't lead to the final key, but to an _intermediate key_ which is actually an RSA-encrypted version of the actual key.

Is it possible with Exoplayer API to intercept this key before it's used for decryption and modify it?

I found one thread/issue which talked about creating a DataSource "wrapper", but there is no sample code. I also tried Google and other documentation, to no avail. Would it be possible to get some assistance or example code to help solve this particular problem? Thanks!

**Comment by ojw28** [comment]
> I'm trying to encrypt this AES key with RSA encryption ... So the URI included in the media playlist doesn't lead to the final key, but to an intermediate key which is actually an RSA-encrypted version of the actual key.

Why? Is this any way spec compliant? Why don't you just serve the key file over https?

**Comment by DeveloperMCD** [comment]
This requirement was added to our design for security reasons. Our idea is to protect a video by keeping it encrypted (we are using USB flash drives) and only one user's hardware can unencrypt that file -- which is needed to play back the video.

If I need to intercept the loading of the Keyfile to do something with it first (for example, un-encrypt it with the RSA private key), how do I do this with a custom DataSource?

1. We're trying to rely on Internet access as little as possible; it has to do with the specifics of the project's requirements and use-case. We are relying on USB flash drives for data rather than the Internet.

Incidentally, the application works fine with AES-encrypted HLS videos that include the AES file (URL) right in the *.m3u8 manifest. But unfortunately for me, the requirements involve RSA encrypting this key as well.

2. I can't just serve up the same RSA-encrypted AES key for all users, because each user is going to get his own RSA private/public key pair. That's part of the security model for our application. The AES key served up to Alice is going to be encrypted with Alice's public key, whereas the key served up to Bob will be encrypted with Bob's public key instead. So Alice and Bob can't un-encrypt each other's AES keys, even if they get physical access to the encrypted files.

**Comment by ojw28** [comment]
Are you trying to make this approach work cross-platform? And is there a reason you're not using CENC / Widevine, which I think would be the more standard way of doing this?

If you can't use Widevine and the design is specific for Android, then to follow your existing proposal, you'll need to:

* Make sure you have a clear way of distinguishing key file Uris from other Uris (e.g. special file extension).
* Implement a custom `DataSource` that wraps `DefaultDataSource`. Initially just implement it to call through to the wrapped `DefaultDataSource` for all methods. Make a `DataSource.Factory` for creating instances of your custom `DataSource` and start using it when building your `HlsMediaSource` instances for playb ack. At this point things should work just as before, but all data will now be being read through instances of your custom `DataSource`.
* Add logic into your custom `DataSource` that detects when it's being opened to read a key file (e.g. using the special file extension). When it's reading this data, enable some extra decryption logic that you'll need to implement, to decrypt the data as it's being read through.

**Comment by DeveloperMCD** [comment]
Here is what I have -- I'm getting an error when I try to access the local HTTP server. There must be something basic I'm doing wrong.

```
    private void prepareMediaForPlaying(Uri mediaSourceUri) {

        DataSource.Factory customDS = new DataSource.Factory(){

            @Override
            public DataSource createDataSource() {
                return new CustomDataSource(getContext());
            }

        };

        try {

            /*
            // THIS WORKS with regular AES key (no RSA encryption)
            HlsMediaSource mediaSource =
                    new HlsMediaSource(
                            mediaSourceUri,
                            new DefaultDataSourceFactory(getActivity(), userAgent),
                            1,
                            mainHandler,
                            null);
           */


            HlsMediaSource mediaSource =
                    new HlsMediaSource(
                            mediaSourceUri,
                            customDS,
                            1,
                            mainHandler,
                            null);


            mPlayer.prepare(mediaSource);

        }
        catch (Error ex){
            System.out.printf(ex.getMessage());
        }

    }
```
And here is the custom DataSource:

```
public class CustomDataSource implements DataSource {
    private DataSource upstream;

    public CustomDataSource(Context ctx) {
        super();

        upstream = new DefaultDataSource(ctx, new DefaultBandwidthMeter(),
                Util.getUserAgent(ctx,null),
        10,
        10,
        true);

    }

    @Override
    public void close() throws IOException {
        upstream.close();
    }

    @Override
    public long open(DataSpec dataSpec) throws IOException {
        return upstream.open(dataSpec);
    }

    @Override
    public int read(byte[] buffer, int offset, int readLength) throws IOException {
        return upstream.read(buffer,offset,readLength);
    }

    @Override
    public Uri getUri() {
        return upstream.getUri();
    }

}

```

**Comment by DeveloperMCD** [comment]
Here is the error I got:

```09-18 20:44:30.169 14638-14911/com.example.android.settopbox E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://localhost:8000/arrow/playlist.m3u8
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.example.android.settopbox.data.CustomDataSource.open(CustomDataSource.java:64)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:137)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.net.SocketTimeoutException: timeout
        at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:782)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:358)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147) 
        at com.example.android.settopbox.data.CustomDataSource.open(CustomDataSource.java:64) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:137) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:151)
        at java.net.SocketInputStream.read(SocketInputStream.java:120)
        at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306) 
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300) 
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196) 
        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191) 
        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80) 
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906) 
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:782) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:358) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147) 
        at com.example.android.settopbox.data.CustomDataSource.open(CustomDataSource.java:64) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:137) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
09-18 20:44:30.173 14638-14915/com.example.android.settopbox E/fi.iki.elonen.NanoHTTPD: Could not send response to the client
    java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:112)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
        at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1694)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1667)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1657)
        at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:761)
09-18 20:44:30.185 14638-14916/com.example.android.settopbox E/fi.iki.elonen.NanoHTTPD: Could not send response to the client
    java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:112)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
        at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1694)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1667)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1657)
        at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:761)```

**Comment by ojw28** [comment]
You seem to be specifying 10ms timeouts, and then timing out. You probably need significantly higher values. By default they're 8000ms.
```
public CustomDataSource(Context ctx) {
        super();
        upstream = new DefaultDataSource(
            ctx,
            new DefaultBandwidthMeter(),            // <---------
            Util.getUserAgent(ctx,null),
            10,            // <----------------------------------
            10,            // <----------------------------------
            true);
    }
```
Also:
* Making a new `DefaultBandwidthMeter` internally like this will break adaptive playback, if you're needing that. If you're not needing that then what you're doing looks fine, but you may as well pass `null`.
* It's generally more flexible if you pass the upstream `DataSource` into the `CustomDataSource` constructor. As a good example of an existing wrapping `DataSource` implementation, take a look at `AesCipherDataSource` in the library.
* Why are you using a local HTTP server? I've seen various attempts to do this internally in the past, and they've all been error prone and unreliable. You can probably just implement a `DataSource` that accesses where-ever the data is directly?
