### ISSUE TITLE
Out of memory Exoplayer in Fragment inside Viewpager

### ISSUE THREAD

**Issue by cinohub** [google/ExoPlayer#4850]
I have used Exoplayer to stream video online from internet. My player work inside fragmet inside viewpager. The crash happen when I played about 10 videos .
Here is my logcat : 
`E/LoadTask: OutOfMemory error loading stream
    java.lang.OutOfMemoryError: Failed to allocate a 65548 byte allocation with 22600 free bytes and 22KB until OOM
        at com.android.okio.Segment.<init>(Segment.java:37)
        at com.android.okio.SegmentPool.take(SegmentPool.java:48)
        at com.android.okio.OkBuffer.writableSegment(OkBuffer.java:505)
        at com.android.okio.Okio$2.read(Okio.java:114)
        at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:469)
        at com.android.okhttp.internal.Util.skipAll(Util.java:227)
        at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:239)
        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:491)
        at com.android.okio.RealBufferedSource.close(RealBufferedSource.java:204)
        at com.android.okio.RealBufferedSource$1.close(RealBufferedSource.java:187)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.close(DefaultHttpDataSource.java:279)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.close(DefaultDataSource.java:164)
        at com.google.android.exoplayer2.util.Util.closeQuietly(Util.java:231)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:867)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)`

Here is my config code : 
`  
MediaSource mediaSource = new ExtractorMediaSource.Factory(new DefaultDataSourceFactory(getContext(), Util.getUserAgent(getContext(), getString(R.string.app_name)), (TransferListener<? super DataSource>) new DefaultBandwidthMeter()))
                        .createMediaSource(Uri.parse(content.getUrl())); 
                TrackSelection.Factory videoTrackSelectionFactory =
                        new AdaptiveTrackSelection.Factory(new DefaultBandwidthMeter());
                trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
                player = ExoPlayerFactory.newSimpleInstance(getContext(), trackSelector);
                playerView.setPlayer(player);
                player.prepare(mediaSource);
                player.setRepeatMode(Player.REPEAT_MODE_ONE);
                player.setPlayWhenReady(false);`

**Comment by andrewlewis** [comment]
> when I played about 10 videos

Are these playing at the same time in multiple players? Please check your app's code to make sure you're releasing players when they aren't needed.

**Comment by cinohub** [comment]
> > when I played about 10 videos
> 
> Are these playing at the same time in multiple players? Please check your app's code to make sure you're releasing players when they aren't needed.


Thanks for fast reply.
I play video when setUserVisibleHint() method fire. and pause video when onPause() fire. 
Here is my code play and pause : 
`
 private void pausePlayer() {

        if (player != null) {
            player.setPlayWhenReady(false);
            player.getPlaybackState();
        }
    }

    private void startPlayer() {
        if (player != null) {
            player.seekTo(0);
            player.setPlayWhenReady(true);
            player.getPlaybackState();
        }

    }
`

Do you have any idea to release player when fragment not visible by user. I use fragment inside viewpager. Player auto play video when fragment visible, so it working about 10 video and crash with OOM.

**Comment by andrewlewis** [comment]
You should probably be calling `player.release()` on any instances that aren't visible to the user. It may be better to have just one player instance for your app, and change its output view as needed.

**Comment by andrewlewis** [comment]
Closing as this seems like an app issue with using too many players at the same time.
