### ISSUE TITLE
Unable to initialize MediaDrm on KitKat emulator

### ISSUE THREAD

**Issue by mathemandy** [google/ExoPlayer#4889]
### Issue description
I am trying to integrate DRM into my app and it fails to instantiate on api 19 which is our lowest support device

### Reproduction steps

this is where i instantiate the player
```
        if (newExo)
            try {
                DrmSessionManager<FrameworkMediaCrypto> drmSessionManager = buildOnlineDrmSessionManager(LICENCE_URL);

                exoPlayer = ExoPlayerFactory.newSimpleInstance(new DefaultRenderersFactory(this, drmSessionManager), trackSelector, loadControl);
            } catch (UnsupportedDrmException e ){

            LogHelper.e(TAG, e.getMessage());
            }
        exoPlayer.addListener(this);
        exoPlayer.setPlayWhenReady(true);
        source = initMediaSource();
        exoPlayer.prepare(source);
        exoPlayer.seekTo(currentPosition, C.TIME_UNSET);
```

then i build the drm.

```
private DrmSessionManager<FrameworkMediaCrypto> buildOnlineDrmSessionManager (String licenseUrl)throws UnsupportedDrmException{
        HttpDataSource.Factory httpDataSourceFactory = new DefaultHttpDataSourceFactory(userAgent);
        MediaDrmCallback drmCallback = new HttpMediaDrmCallback(licenseUrl, httpDataSourceFactory);
        return DefaultDrmSessionManager.newWidevineInstance(drmCallback, null, null, mEventLogger);

    } 
```

### Version of ExoPlayer being used
  implementation 'com.google.android.exoplayer:exoplayer:2.8.1'

### Device(s) and version(s) of Android being used
Works fine on API > KITKAT
Fails on Android X86 Emulator 4.4.2

### A full bug report captured from the device
```
09-28 11:05:01.573 11731-11731/ng.groove.udux E/playSong: Request to play song received
09-28 11:05:01.573 11731-11731/ng.groove.udux E/dispatcher: Broadcast::SHOW_LOADING
09-28 11:05:01.613 11731-11731/ng.groove.udux E/dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method ng.groove.udux.player.MediaPlayerService.createChannel
09-28 11:05:01.613 11731-11731/ng.groove.udux W/dalvikvm: VFY: unable to resolve new-instance 33 (Landroid/app/NotificationChannel;) in Lng/groove/udux/player/MediaPlayerService;
09-28 11:05:01.613 11731-11731/ng.groove.udux D/dalvikvm: VFY: replacing opcode 0x22 at 0x0014
09-28 11:05:01.613 11731-11731/ng.groove.udux E/dalvikvm: Could not find class 'android.media.session.MediaSessionManager', referenced from method ng.groove.udux.player.MediaPlayerService.initMediaSession
09-28 11:05:01.613 11731-11731/ng.groove.udux W/dalvikvm: VFY: unable to resolve check-cast 128 (Landroid/media/session/MediaSessionManager;) in Lng/groove/udux/player/MediaPlayerService;
09-28 11:05:01.613 11731-11731/ng.groove.udux D/dalvikvm: VFY: replacing opcode 0x1f at 0x002a
    DexOpt: unable to opt direct call 0x004a at 0x16 in Lng/groove/udux/player/MediaPlayerService;.createChannel
09-28 11:05:01.613 11731-11731/ng.groove.udux I/dalvikvm: Could not find method android.view.Display.getMode, referenced from method com.google.android.exoplayer2.util.Util.getDisplaySizeV23
09-28 11:05:01.613 11731-11731/ng.groove.udux W/dalvikvm: VFY: unable to resolve virtual method 23551: Landroid/view/Display;.getMode ()Landroid/view/Display$Mode;
09-28 11:05:01.613 11731-11731/ng.groove.udux D/dalvikvm: VFY: replacing opcode 0x6e at 0x0000
09-28 11:05:01.613 11731-11731/ng.groove.udux I/dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method com.google.android.exoplayer2.util.Util.maybeRequestReadExternalStoragePermission
09-28 11:05:01.613 11731-11731/ng.groove.udux W/dalvikvm: VFY: unable to resolve virtual method 129: Landroid/app/Activity;.checkSelfPermission (Ljava/lang/String;)I
09-28 11:05:01.613 11731-11731/ng.groove.udux D/dalvikvm: VFY: replacing opcode 0x6e at 0x0016
09-28 11:05:01.623 11731-11731/ng.groove.udux I/dalvikvm: Could not find method android.content.Context.startForegroundService, referenced from method com.google.android.exoplayer2.util.Util.startForegroundService
09-28 11:05:01.623 11731-11731/ng.groove.udux W/dalvikvm: VFY: unable to resolve virtual method 883: Landroid/content/Context;.startForegroundService (Landroid/content/Intent;)Landroid/content/ComponentName;
09-28 11:05:01.623 11731-11731/ng.groove.udux D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
09-28 11:05:01.633 11731-11731/ng.groove.udux I/dalvikvm: Could not find method android.content.Context.startForegroundService, referenced from method android.support.v4.media.session.MediaButtonReceiver.startForegroundService
09-28 11:05:01.633 11731-11731/ng.groove.udux W/dalvikvm: VFY: unable to resolve virtual method 883: Landroid/content/Context;.startForegroundService (Landroid/content/Intent;)Landroid/content/ComponentName;
09-28 11:05:01.633 11731-11731/ng.groove.udux D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
09-28 11:05:01.643 11731-11731/ng.groove.udux I/dalvikvm: Could not find method android.media.AudioManager.generateAudioSessionId, referenced from method com.google.android.exoplayer2.C.generateAudioSessionIdV21
09-28 11:05:01.643 11731-11731/ng.groove.udux W/dalvikvm: VFY: unable to resolve virtual method 1683: Landroid/media/AudioManager;.generateAudioSessionId ()I
09-28 11:05:01.643 11731-11731/ng.groove.udux D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
09-28 11:05:01.643 11731-11731/ng.groove.udux I/dalvikvm: Could not find method android.media.MediaDrm.setOnKeyStatusChangeListener, referenced from method com.google.android.exoplayer2.drm.FrameworkMediaDrm.setOnKeyStatusChangeListener
09-28 11:05:01.643 11731-11731/ng.groove.udux W/dalvikvm: VFY: unable to resolve virtual method 1799: Landroid/media/MediaDrm;.setOnKeyStatusChangeListener (Landroid/media/MediaDrm$OnKeyStatusChangeListener;Landroid/os/Handler;)V
09-28 11:05:01.643 11731-11731/ng.groove.udux D/dalvikvm: VFY: replacing opcode 0x6e at 0x0018
09-28 11:05:01.643 11731-11731/ng.groove.udux I/dalvikvm: Failed resolving Lcom/google/android/exoplayer2/drm/FrameworkMediaDrm$2; interface 338 'Landroid/media/MediaDrm$OnKeyStatusChangeListener;'
09-28 11:05:01.643 11731-11731/ng.groove.udux W/dalvikvm: Link of class 'Lcom/google/android/exoplayer2/drm/FrameworkMediaDrm$2;' failed
09-28 11:05:01.643 11731-11731/ng.groove.udux E/dalvikvm: Could not find class 'com.google.android.exoplayer2.drm.FrameworkMediaDrm$2', referenced from method com.google.android.exoplayer2.drm.FrameworkMediaDrm.setOnKeyStatusChangeListener
09-28 11:05:01.643 11731-11731/ng.groove.udux W/dalvikvm: VFY: unable to resolve new-instance 5308 (Lcom/google/android/exoplayer2/drm/FrameworkMediaDrm$2;) in Lcom/google/android/exoplayer2/drm/FrameworkMediaDrm;
09-28 11:05:01.643 11731-11731/ng.groove.udux D/dalvikvm: VFY: replacing opcode 0x22 at 0x0013
09-28 11:05:01.643 11731-11731/ng.groove.udux I/dalvikvm: Failed resolving Lcom/google/android/exoplayer2/drm/FrameworkMediaDrm$2; interface 338 'Landroid/media/MediaDrm$OnKeyStatusChangeListener;'
09-28 11:05:01.643 11731-11731/ng.groove.udux W/dalvikvm: Link of class 'Lcom/google/android/exoplayer2/drm/FrameworkMediaDrm$2;' failed
09-28 11:05:01.643 11731-11731/ng.groove.udux D/dalvikvm: DexOpt: unable to opt direct call 0x93b2 at 0x15 in Lcom/google/android/exoplayer2/drm/FrameworkMediaDrm;.setOnKeyStatusChangeListener
09-28 11:05:01.643 11731-11731/ng.groove.udux E/udux_MediaPlayerService: android.media.UnsupportedSchemeException: Failed to instantiate drm object.
09-28 11:05:01.643 11731-11731/ng.groove.udux D/AndroidRuntime: Shutting down VM
09-28 11:05:01.643 11731-11731/ng.groove.udux W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xb0d3db20)
09-28 11:05:01.643 11731-11731/ng.groove.udux D/CrashlyticsCore: Crashlytics is handling uncaught exception "java.lang.RuntimeException: Unable to start service ng.groove.udux.player.MediaPlayerService@b17e40c8 with Intent { cmp=ng.groove.udux/.player.MediaPlayerService }: java.lang.NullPointerException" from thread main
09-28 11:05:01.643 11731-11781/ng.groove.udux D/Answers: Logged crash
09-28 11:05:01.653 11731-11781/ng.groove.udux D/CrashlyticsCore: No log data to include with this event.
09-28 11:05:01.673 11731-11781/ng.groove.udux D/dalvikvm: GC_FOR_ALLOC freed 4358K, 16% free 17672K/20848K, paused 9ms, total 9ms
09-28 11:05:01.713 11731-11781/ng.groove.udux D/CrashlyticsCore: Skipping logging Crashlytics event to Firebase, FirebaseCrash exists
    Closing open sessions.
    Closing session: 5BADFB54028B-0001-2DD3-0294D7FF140F
    Collecting session parts for ID 5BADFB54028B-0001-2DD3-0294D7FF140F
    Session 5BADFB54028B-0001-2DD3-0294D7FF140F has fatal exception: true
    Session 5BADFB54028B-0001-2DD3-0294D7FF140F has non-fatal exceptions: false
    Collecting SessionStart data for session ID 5BADFB54028B-0001-2DD3-0294D7FF140F
    Collecting SessionUser data for session ID 5BADFB54028B-0001-2DD3-0294D7FF140F
    Collecting SessionApp data for session ID 5BADFB54028B-0001-2DD3-0294D7FF140F
    Collecting SessionOS data for session ID 5BADFB54028B-0001-2DD3-0294D7FF140F
    Collecting SessionDevice data for session ID 5BADFB54028B-0001-2DD3-0294D7FF140F
    Removing session part files for ID 5BADFB54028B-0001-2DD3-0294D7FF140F
    Opening a new session with ID 5BADFCCD02D8-0002-2DD3-0294D7FF140F
09-28 11:05:01.713 11731-11781/ng.groove.udux D/Beta: Beta device token present: false
09-28 11:05:01.723 11731-11731/ng.groove.udux D/CrashlyticsCore: Crashlytics completed exception processing. Invoking default exception handler.
09-28 11:05:01.723 11731-11731/ng.groove.udux E/UncaughtException: java.lang.RuntimeException: Unable to start service ng.groove.udux.player.MediaPlayerService@b17e40c8 with Intent { cmp=ng.groove.udux/.player.MediaPlayerService }: java.lang.NullPointerException
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2719)
        at android.app.ActivityThread.access$2100(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
        at ng.groove.udux.player.MediaPlayerService.initExo(MediaPlayerService.java:358)
        at ng.groove.udux.player.MediaPlayerService.onStartCommand(MediaPlayerService.java:283)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2702)
        at android.app.ActivityThread.access$2100(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by erdemguven** [comment]
Please test the code on a real device and let us know the result:
https://google.github.io/ExoPlayer/faqs.html#does-exoplayer-support-emulators
