### ISSUE TITLE
E/ExoPlayerImplInternal: Renderer error.

### ISSUE THREAD

**Issue by JamesXu20150314** [google/ExoPlayer#4929]
Hello,

I encounter an issue with ExoPlayer when I use "player.setVideoSurface(surface);", as follows:

```
  E/ExoPlayerImplInternal: Renderer error.
      com.google.android.exoplayer2.ExoPlaybackException
          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:420)
          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:407)
          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:898)
          at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:469)
          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:551)
          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
          at android.os.Handler.dispatchMessage(Handler.java:102)
          at android.os.Looper.loop(Looper.java:164)
          at android.os.HandlerThread.run(HandlerThread.java:65)
       Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.vp8, Format(1, null, video/x-vnd.on2.vp8, -1, null, [1280, 640, -1.0], [-1, -1])
          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:407) 
          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:898) 
          at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:469) 
          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:551) 
          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
          at android.os.Handler.dispatchMessage(Handler.java:102) 
          at android.os.Looper.loop(Looper.java:164) 
          at android.os.HandlerThread.run(HandlerThread.java:65) 
       Caused by: java.lang.IllegalArgumentException: The surface has been released
          at android.media.MediaCodec.nativeconfigure(Native Method)
          at android.media.MediaCodec.configure(MediaCodec.java:1943)
          at android.media.MediaCodec.configure(MediaCodec.java:1872)
          at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:428)
          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:397)
          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:898) 
          at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:469) 
          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:551) 
          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
          at android.os.Handler.dispatchMessage(Handler.java:102) 
          at android.os.Looper.loop(Looper.java:164) 
          at android.os.HandlerThread.run(HandlerThread.java:65)
```

Who knows why?

Thanks.

**Comment by JamesXu20150314** [comment]
I also encounter this error：

```
10-10 21:17:47.910 1815-1816/? E/ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
10-10 21:17:47.910 1815-1816/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
10-10 21:17:48.082 1434-7963/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.youtube-L32HoIoHGpUZLIBY4B9PCg==/base.apk
10-10 21:17:48.082 1434-7963/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.youtube-L32HoIoHGpUZLIBY4B9PCg==/base.apk
10-10 21:17:48.083 1434-7963/? E/ResourcesManager: failed to add asset path /data/app/com.facebook.katana-dPlkpM8tyyWReBEGgXW80w==/base.apk
10-10 21:17:48.085 1434-7963/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.dialer-kV7anOxEC4cLKs3BKDWYIg==/base.apk
10-10 21:17:48.086 1434-7963/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.dialer-kV7anOxEC4cLKs3BKDWYIg==/base.apk
10-10 21:17:48.086 1434-7963/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.dialer-kV7anOxEC4cLKs3BKDWYIg==/base.apk
10-10 21:17:48.087 1434-7963/? E/ResourcesManager: failed to add asset path /data/app/com.android.vending-VTuWxILiq4QV1o8Qopa6HA==/base.apk
10-10 21:17:48.338 718-8270/? E/OMX-VDEC-1080P: Enable/Disable allocate-native-handle allowed only on input port!
    set_parameter: Error: 0x80001019, setting param 0x7f00005b
10-10 21:17:48.338 718-8270/? E/OMXNodeInstance: setParameter(0xe95a3ac4:qcom.decoder.vp8, OMX.google.android.index.allocateNativeHandle(0x7f00005b): Output:1 en=0) ERROR: UnsupportedSetting(0x80001019)
10-10 21:17:48.338 718-8270/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
10-10 21:17:48.344 718-23659/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
      Extension: OMX.google.android.index.configureVideoTunnelMode not implemented
10-10 21:17:48.345 718-23659/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.useAndroidNativeBuffer is supported
10-10 21:17:48.345 718-8270/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.describeHDRStaticInfo not implemented
      get_parameter: unknown param 6f600007
10-10 21:17:48.345 718-8270/? E/OMXNodeInstance: getParameter(0xe95a3ac4:qcom.decoder.vp8, ParamVideoAndroidVp8Encoder(0x6f600007)) ERROR: UnsupportedIndex(0x8000101a)
10-10 21:17:48.348 718-1471/? E/OMX-VDEC-1080P: Does not handle dataspace request
10-10 21:17:48.348 718-1471/? E/OMXNodeInstance: getConfig(0xe95a3ac4:qcom.decoder.vp8, ??(0x7f00005e)) ERROR: UnsupportedSetting(0x80001019)
10-10 21:17:48.358 718-1471/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.AndroidNativeBufferConsumerUsage not implemented
10-10 21:17:48.370 718-1471/? E/OMXNodeInstance: setConfig(0xeb7a2f00:google.vorbis.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
10-10 21:17:48.370 718-1471/? E/OMXNodeInstance: getConfig(0xeb7a2f00:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
10-10 21:17:49.187 718-8270/? E/OMX-VDEC-1080P: Does not handle dataspace request
10-10 21:17:49.187 718-8270/? E/OMXNodeInstance: getConfig(0xe95a3ac4:qcom.decoder.vp8, ??(0x7f00005e)) ERROR: UnsupportedSetting(0x80001019)
10-10 21:17:49.213 1815-1816/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [15, 4, 0]
10-10 21:17:47.910 1815-1816/? E/ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
10-10 21:17:47.910 1815-1816/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
10-10 21:17:48.082 1434-7963/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.youtube-L32HoIoHGpUZLIBY4B9PCg==/base.apk
10-10 21:17:48.082 1434-7963/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.youtube-L32HoIoHGpUZLIBY4B9PCg==/base.apk
10-10 21:17:48.083 1434-7963/? E/ResourcesManager: failed to add asset path /data/app/com.facebook.katana-dPlkpM8tyyWReBEGgXW80w==/base.apk
10-10 21:17:48.085 1434-7963/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.dialer-kV7anOxEC4cLKs3BKDWYIg==/base.apk
10-10 21:17:48.086 1434-7963/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.dialer-kV7anOxEC4cLKs3BKDWYIg==/base.apk
10-10 21:17:48.086 1434-7963/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.dialer-kV7anOxEC4cLKs3BKDWYIg==/base.apk
10-10 21:17:48.087 1434-7963/? E/ResourcesManager: failed to add asset path /data/app/com.android.vending-VTuWxILiq4QV1o8Qopa6HA==/base.apk
10-10 21:17:48.338 718-8270/? E/OMX-VDEC-1080P: Enable/Disable allocate-native-handle allowed only on input port!
set_parameter: Error: 0x80001019, setting param 0x7f00005b
10-10 21:17:48.338 718-8270/? E/OMXNodeInstance: setParameter(0xe95a3ac4:qcom.decoder.vp8, OMX.google.android.index.allocateNativeHandle(0x7f00005b): Output:1 en=0) ERROR: UnsupportedSetting(0x80001019)
10-10 21:17:48.338 718-8270/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
10-10 21:17:48.344 718-23659/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
Extension: OMX.google.android.index.configureVideoTunnelMode not implemented
10-10 21:17:48.345 718-23659/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.useAndroidNativeBuffer is supported
10-10 21:17:48.345 718-8270/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.describeHDRStaticInfo not implemented
get_parameter: unknown param 6f600007
10-10 21:17:48.345 718-8270/? E/OMXNodeInstance: getParameter(0xe95a3ac4:qcom.decoder.vp8, ParamVideoAndroidVp8Encoder(0x6f600007)) ERROR: UnsupportedIndex(0x8000101a)
10-10 21:17:48.348 718-1471/? E/OMX-VDEC-1080P: Does not handle dataspace request
10-10 21:17:48.348 718-1471/? E/OMXNodeInstance: getConfig(0xe95a3ac4:qcom.decoder.vp8, ??(0x7f00005e)) ERROR: UnsupportedSetting(0x80001019)
10-10 21:17:48.358 718-1471/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.AndroidNativeBufferConsumerUsage not implemented
10-10 21:17:48.370 718-1471/? E/OMXNodeInstance: setConfig(0xeb7a2f00:google.vorbis.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
10-10 21:17:48.370 718-1471/? E/OMXNodeInstance: getConfig(0xeb7a2f00:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
10-10 21:17:49.187 718-8270/? E/OMX-VDEC-1080P: Does not handle dataspace request
10-10 21:17:49.187 718-8270/? E/OMXNodeInstance: getConfig(0xe95a3ac4:qcom.decoder.vp8, ??(0x7f00005e)) ERROR: UnsupportedSetting(0x80001019)
10-10 21:17:49.213 1815-1816/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [15, 4, 0]
```

**Comment by ojw28** [comment]
The first error is exactly what the logs say:

> The surface has been released

If you want to pass a surface directly to the player, you need to make sure you're only passing a valid surface (and that you're removing it from the player when the surface is destroyed). As per the [Javadoc](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#setVideoSurface-android.view.Surface-):

> The caller is responsible for tracking the lifecycle of the surface, and must clear the surface by calling setVideoSurface(null) if the surface is destroyed. If the surface is held by a SurfaceView, TextureView or SurfaceHolder then it's recommended to use Player.VideoComponent.setVideoSurfaceView(SurfaceView), Player.VideoComponent.setVideoTextureView(TextureView) or Player.VideoComponent.setVideoSurfaceHolder(SurfaceHolder) rather than this method, since passing the holder allows the player to track the lifecycle of the surface automatically.

**Comment by Danishbutt1122** [comment]
@ojw28  #4925 check my issue... you did not answer my question sir :/
