### ISSUE TITLE
Play video from .exo files

### ISSUE THREAD

**Issue by marcosmagno** [google/ExoPlayer#4937]
How can I play a video from multiple .exo files that I download on a mobile phone.
I have a list of 20 .exi files and an .exi file.

**Comment by tonihei** [comment]
These are not meant to be played directly. Please use a CacheDataSource with the same configuration (same uri etc.) as you used to save these files.

**Comment by marcosmagno** [comment]
@tonihei I'm sending these files to other phones (via D2D). I can not play this list of .exo files on other phones that are without internet access? D2D clients need to have access to the internet?

**Comment by tonihei** [comment]
You don't need internet access to play the files, but you do need the original uri in the media source and data source setup. This ensures the Cache finds the correct file. 
For example:
```
new ExtractorMediaSource.Factory(
    new CacheDataSourceFactory(
        cachePointingToTheCopiedFiles, 
        new DefaultDataSourceFactory(context, userAgent)))
    .creatMediaSource(uriUsedForDownloadingTheFile);
```

@erdemguven may be able to provide further hints.

**Comment by tonihei** [comment]
I guess the question was answered, so closing the issue. Please reopen if that's not the case.

**Comment by marcosmagno** [comment]
Hello .... I could not make the video play from the .exo files. Look at my scenery:
1 - I download the video via DASH. (OK)
2 - Save the .exo files locally (OK)
3 - Send the .exo files to other mobiles (via Wi-Fi connection (D2D)) (OK)
4 - I want to play the .exo files on these phones (still can not)


Codes:

1 - Download do vídeo
 threadDownload = new Thread(new Runnable() {
            @Override
            public void run() {
                File cacheDirectory = new File(getApplicationContext().getExternalCacheDir(), "downloads");
                SimpleCache cache = new SimpleCache(cacheDirectory, new NoOpCacheEvictor());

                //DefaultHttpDataSourceFactory factory = new DefaultHttpDataSourceFactory("ExoPlayer", null);
                DownloaderConstructorHelper constructorHelper =
                        new DownloaderConstructorHelper(cache, manifestDataSourceFactory);

                DashDownloader dashDownloader = new DashDownloader(uriRecv, constructorHelper);
                try {
                    dashDownloader.download(new Downloader.ProgressListener() {
                        @Override
                        public void onDownloadProgress(Downloader downloader, float downloadPercentage, long downloadedBytes) {

                        }
                    });
                    dashDownloader.getDownloadPercentage();
                }
                catch (IOException e) {
                    e.printStackTrace();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });


4 - Play video from .exo files

//read up from the local system
        File cacheDirectory = new File(getApplicationContext().getExternalCacheDir(), "downloads");
        SimpleCache cache = new SimpleCache(cacheDirectory,  new NoOpCacheEvictor());

        FileDataSourceFactory fileDataSource = new FileDataSourceFactory();
        MediaSource mediaSource = new DashMediaSource(
                Uri.parse(String.valueOf(uriRecv)),
                new CacheDataSourceFactory(
                        cache, fileDataSource, CacheDataSource.FLAG_BLOCK_ON_CACHE),
                new DefaultDashChunkSource.Factory(new CacheDataSourceFactory(cache, fileDataSource, CacheDataSource.FLAG_BLOCK_ON_CACHE)),
                null,
                null
        );

        return mediaSource;

------------------------------------------------------------------------------------------------------
With this code, the video shows only the first frame (the initial image of the video). Here's the LOG:
------------------------------------------------------------------------------------------------------



Com esse código, o video aparece apenas o primeiro frame (a imagem inicial do video). Segue o LOG:
04-12 18:26:49.032 24089-24122/com.example.exoplayercodelab E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /BBB_2sec/x264/segment_7502.m4s: open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:70)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:45)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:401)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:242)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:116)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.io.FileNotFoundException: /BBB_2sec/x264/segment_7502.m4s: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:452)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:62)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:45) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:401) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:242) 
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:116) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
