### ISSUE TITLE
 PlayReady sample

### ISSUE THREAD

**Issue by kienbk1910** [google/ExoPlayer#495]
Hello, I have a proplem with sample app .When I run sample PlayReady, Video don't run, it always is idle state. My device is Samsung S6. This is error log.
 com.google.android.exoplayer.ExoPlaybackException: android.media.MediaCryptoException: Failed to instantiate crypto object.
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:289)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:660)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:462)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:442)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:145)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: android.media.MediaCryptoException: Failed to instantiate crypto object.
            at android.media.MediaCrypto.native_setup(Native Method)
            at android.media.MediaCrypto.<init>(MediaCrypto.java:63)
            at com.google.android.exoplayer.drm.StreamingDrmSessionManager.openInternal(StreamingDrmSessionManager.java:217)
            at com.google.android.exoplayer.drm.StreamingDrmSessionManager.open(StreamingDrmSessionManager.java:189)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:284)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:660)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:462)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:442)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:145)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

Thanks you.

**Comment by Ood-Tsen** [comment]
Does S6 support PlayReady ?
I don't find it on the [website](http://www.drmtoday.com/playready/) ?

Supported Platforms , Common examples of supported platforms include:

    Silverlight
    Internet Explorer 11 (on Windows 8.1)
    Windows Phone
    Chromecast / Google TV / Android TV
    Connected TVs (dependent on manufacturer)
    Samsung Smart TVs
    Smart TV Alliance
    Xbox One / 360
    PlayStation 4

**Comment by kienbk1910** [comment]
Thanks you! When I test other device, It  throws UnsupportedSchemeException. But S6 don't throws  
UnsupportedSchemeException

**Comment by ojw28** [comment]
I'm not sure if Samsung intended to provide PlayReady support or not for the S6, but your experience suggests that it doesn't work. You'd have to ask Samsung. AndroidTV devices do support PlayReady, so you should test on one of those if you want to try out PlayReady support.
