### ISSUE TITLE
EXOplayer fails to play channels on Android Versions from 4.2 to 5.0 

### ISSUE THREAD

**Issue by littlelitleStar** [google/ExoPlayer#4952]
EXOplayer fails to play channels on Android Versions from 4.2 to 5.0 
with logcat errors.

`10-14 01:07:58.011 3037-3198/com.example.danish.iptv E/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
10-14 01:07:58.011 3037-3198/com.example.danish.iptv E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -2147483648
10-14 01:07:58.023 3037-3199/com.example.danish.iptv E/SoftAVC: Decoder failed: -2
10-14 01:07:58.023 3037-3198/com.example.danish.iptv E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
    signalError(omxError 0x80001001, internalError -2147483648)
10-14 01:07:58.024 3037-3197/com.example.danish.iptv E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
10-14 01:07:58.026 3037-3175/com.example.danish.iptv E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_queueInputBuffer(Native Method)
        at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:831)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:764)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by littlelitleStar** [comment]
Anyone here,....................

**Comment by andrewlewis** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by littlelitleStar** [comment]
I have sended it , and im waiting for any answer

**Comment by andrewlewis** [comment]
I think this may be a case of trying to play a H.264/AVC Main profile stream with a decoder that doesn't support it. Support for Main profile was only mandatory from Android M.

Could you try to play the stream in the ExoPlayer demo app and take a full bug report captured via `adb bugreport` just after playback fails? This will include more logging which might help seeing exactly what is going wrong. Thanks.

**Comment by andrewlewis** [comment]
I don't think we received a full bug report (just a snippet of logcat) so closing. Please send a full bug report and reply here if you want us to investigate further.
