### ISSUE TITLE
Question on Release-2.7.0

### ISSUE THREAD

**Issue by weizhaoj** [google/ExoPlayer#4967]
I checked below to understand the supported-format Exoplayer supported.
https://google.github.io/ExoPlayer/supported-formats.html

I have two question:
Q1: Does Exoplayer support MPEG-DASH? Please refer to below content.
http://amssamples.streaming.mediaservices.windows.net/683f7e47-bd83-4427-b0a3-26a6c4547782/BigBuckBunny.ism/manifest(format=mpd-time-csf)
Q2: In HLS, it says it doesn't support "Sample AES-128". Does it mean it doesn't support AES-128 CTR mode?

Thank you.

**Comment by weizhaoj** [comment]
Below is the log when play a MPEG-DASH stream:
```
10-08 17:32:30.037  1976  5729 E ExoPlayerImplInternal: Source error.
10-08 17:32:30.037  1976  5729 E ExoPlayerImplInternal: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
10-08 17:32:30.037  1976  5729 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:722)
10-08 17:32:30.037  1976  5729 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:645)
10-08 17:32:30.037  1976  5729 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
10-08 17:32:30.037  1976  5729 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-08 17:32:30.037  1976  5729 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-08 17:32:30.037  1976  5729 E ExoPlayerImplInternal: 	at java.lang.Thread.run(Thread.java:764)
10-08 17:32:30.038   484   516 I ActivityManager: Displayed com.google.android.exoplayer2.demo/.PlayerActivity: +150ms
10-08 17:32:30.041  1976  1976 E EventLogger: internalError [0.08, loadError]
10-08 17:32:30.041  1976  1976 E EventLogger: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
10-08 17:32:30.041  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:722)
10-08 17:32:30.041  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:645)
10-08 17:32:30.041  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
10-08 17:32:30.041  1976  1976 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-08 17:32:30.041  1976  1976 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-08 17:32:30.041  1976  1976 E EventLogger: 	at java.lang.Thread.run(Thread.java:764)
10-08 17:32:30.051  1976  1976 E EventLogger: playerFailed [0.09]
10-08 17:32:30.051  1976  1976 E EventLogger: com.google.android.exoplayer2.ExoPlaybackException
10-08 17:32:30.051  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
10-08 17:32:30.051  1976  1976 E EventLogger: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-08 17:32:30.051  1976  1976 E EventLogger: 	at android.os.Looper.loop(Looper.java:193)
10-08 17:32:30.051  1976  1976 E EventLogger: 	at android.os.HandlerThread.run(HandlerThread.java:65)
10-08 17:32:30.051  1976  1976 E EventLogger: Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
10-08 17:32:30.051  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:722)
10-08 17:32:30.051  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:645)
10-08 17:32:30.051  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
10-08 17:32:30.051  1976  1976 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-08 17:32:30.051  1976  1976 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-08 17:32:30.051  1976  1976 E EventLogger: 	at java.lang.Thread.run(Thread.java:764)
10-08 17:32:30.051  1976  1976 D EventLogger: loading [false]
10-08 17:32:30.052  1976  1976 D EventLogger: state [0.09, true, I]
```

**Comment by andrewlewis** [comment]
For the first question please try using `DashMediaSource` instead of `ExtractorMediaSource`.

For the second question I think we only support AES-128 CBC mode but @AquilesCanta can confirm

**Comment by weizhaoj** [comment]
@andrewlewis Could you suggest how to switch "ExtractorMediaSource" to "DashMediaSource"?
We download the src code package and change the media.exolist.json in demo/src/main/assets/ to include MPEG-DASH like below:

{
    "name": "Playready 2.x tests",
    "samples": [
      {
      "name": " CLEAR: Big Buck Bunny , H264 AAC 1080p, MPEG-DASH",
      "uri": "http://amssamples.streaming.mediaservices.windows.net/683f7e47-bd83-4427-b0a3-26a6c4547782/BigBuckBunny.ism/manifest(format=mpd-time-csf)"
      },
.............
}

What else we need to change to make "DashMediaSource" take effect?

**Comment by andrewlewis** [comment]
If you're using the `PlayerActivity` from the demo app, please try adding `"extension": "mpd"` alongside name and uri.

**Comment by weizhaoj** [comment]
@andrewlewis After we adding "extension": "mpd", the stream can be played successfully.
Thank you for your support.

**Comment by weizhaoj** [comment]
@AquilesCanta Can you help to confirm if AES-128-CTR scheme has been supported in HLS? Thanks.

**Comment by ojw28** [comment]
The two possible methods in the HLS spec are `AES-128` and `SAMPLE-AES`. We support `AES-128` and do not support `SAMPLE-AES`.

Note that your question is ambiguous, since both of these methods use AES-128 CBC. `AES-128` (supported) applies AES-128 CBC to entire media segments. `SAMPLE-AES` (unsupported) applies AES-128 CBC to media samples within the segments.
