### ISSUE TITLE
HLS Mixed Playlist

### ISSUE THREAD

**Issue by ldimitroff** [google/ExoPlayer#499]
I get this issue when trying to play a Mixed Playlist:

05-27 17:30:33.251  21360-22097/com.longtailvideo.jwplayer.demo E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: java.io.IOException: Failed to instantiate extractor.
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:253)
            at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:116)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:157)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.io.IOException: Failed to instantiate extractor.
            at android.media.MediaExtractor.setDataSource(Native Method)
            at android.media.MediaExtractor.setDataSource(MediaExtractor.java:140)
            at android.media.MediaExtractor.setDataSource(MediaExtractor.java:115)
            at com.google.android.exoplayer.FrameworkSampleSource.prepare(FrameworkSampleSource.java:135)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:248)
            at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:116)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:157)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
05-27 17:30:33.251  21360-21360/com.longtailvideo.jwplayer.demo E/ExoPlayerMediaProvider﹕ Exo-onPlayerError

**Comment by ojw28** [comment]
What is a mixed playlist?

**Comment by ldimitroff** [comment]
Sorry about that, here's the input of the stream I was trying to reproduce:
http://104.130.27.158:6060/bitrate_0.m3u8

I think they mean "mixed-playlist" for a stream with aac and ts files inside. Looking at this stream, it's a live audio  only, witch can't be played, getting the error above on ExoPlayer.

Maybe we should rename the topic of this thread to a better descriptive name.

**Comment by ojw28** [comment]
Oh right. Looking again, this appears to be a bug in MediaExtractor, under FrameworkSampleSource. You shouldn't use that class (ideally at all - see the warning in the Javadoc). You definitely shouldn't use it for HLS. Use HlsSampleSource instead, which appears to be able to play this just fine in the demo app, if I add the following sample to Samples.java:

```
    new Sample("Test",
        "http://104.130.27.158:6060/bitrate_0.m3u8", DemoUtil.TYPE_HLS),
```

**Comment by ldimitroff** [comment]
I'm using HlsSampleSource, here's a code snippet:

	@Override
	public void onSingleManifest(HlsPlaylist hlsPlaylist) {
		DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();

		DataSource dataSource = new DefaultUriDataSource(userAgent, bandwidthMeter);
		HlsChunkSource chunkSource = new HlsChunkSource(dataSource, mUrl, hlsPlaylist, bandwidthMeter, null, HlsChunkSource.ADAPTIVE_MODE_SPLICE, audioCapabilities);
		HlsSampleSource sampleSource = new HlsSampleSource(chunkSource, true, 3, REQUESTED_BUFFER_SIZE, REQUESTED_BUFFER_DURATION_MS, getMainHandler(), this, TYPE_VIDEO);
		videoRenderer = new MediaCodecVideoTrackRenderer(sampleSource, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT, 5000, getMainHandler(), this, 50);
		audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource);

		id3Renderer = new MetadataTrackRenderer<Map<String, Object>>(sampleSource, new Id3Parser(), getId3MetadataRenderer(), getMainHandler().getLooper());

		exoPlayer.prepare(getTrackRenderers(videoRenderer, audioRenderer, id3Renderer));

		// Pass the surface to the video renderer.
		setSurface(mSurface);

		exoPlayer.setPlayWhenReady(true);
	}

The get track renderers is something like you have on the demo in order not to pass a null renderer into the exoplayer.

**Comment by ojw28** [comment]
The stack trace has FrameworkSampleSource in it (and not HlsSampleSource), so...?! If it doesn't work in the demo app when you add the same as above then please re-open. Otherwise it's something wrong in your code.

**Comment by ldimitroff** [comment]
Hmm, I was using 1.3.1 dev branch... 1.3.3 from Master works on your demo.

Sorry about the confusion and time spent on this.
