### ISSUE TITLE
Problems using different key ids for video and audio

### ISSUE THREAD

**Issue by bergmark** [google/ExoPlayer#4992]
We are testing a playlist that contains video and audio tracks that have different key IDs using our own DRM proxy.

Shaka Player makes one license request for each key ID, whereas ExoPlayer seems to do only one license request (which key ID/track it picks is inconsistent). ExoPlayer then fails with

```
  Caused by: android.media.MediaCodec$CryptoException: Crypto key not available
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2532)
        at com.google.android.exoplayer2.f.b.v(Unknown Source:379)
        at com.google.android.exoplayer2.f.b.a(Unknown Source:74)
        at com.google.android.exoplayer2.j.h(Unknown Source:78)
        at com.google.android.exoplayer2.j.handleMessage(Unknown Source:114)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

We have previously used the same key id and security level 1 for audio and video, but ran into issues playing audio with security level 5 in ExoPlayer on some devices.

We have also tried using unencrypted audio, this works everywhere, but we need to keep audio encrypted.

## Questions
* What is the expected ExoPlayer behavior? Should it make one license request for each key ID, or just one request containing both?
* Do you have any idea what we could be doing wrong?

## Attachments

Included below is
* Our playlist
* The original license request made by the android device
* The license request our proxy makes to the Widevine DRM service
* The license response received from the Widevine DRM service

### Playlist
```xml
<?xml version="1.0"?>
<MPD type="dynamic" availabilityStartTime="1970-01-01T00:00:31Z" publishTime="1970-01-01T00:00:31Z" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" xmlns:mspr="urn:microsoft:playready" minBufferTime="PT2.0S" minimumUpdatePeriod="P100Y" timeShiftBufferDepth="PT7200S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
 <Period id="1" start="PT0S">
  <AdaptationSet contentType="video" mimeType="video/mp4" segmentAlignment="true" bitstreamSwitching="true" maxWidth="1280" maxHeight="720" maxFrameRate="25">
   <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>
   <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
    <cenc:pssh>*OBFUSCATED*</cenc:pssh>
   </ContentProtection>
   <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="*OBFUSCATED*" />
   <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95" value="MSPR 2.0">
    <cenc:pssh>*OBFUSCATED*</cenc:pssh>
    <mspr:pro>*OBFUSCATED*</mspr:pro>
   </ContentProtection>
   <ContentProtection schemeIdUri="urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b">
    <cenc:pssh>*OBFUSCATED*</cenc:pssh>
   </ContentProtection>
   <SegmentTemplate timescale="10000000" duration="60000000" media="$RepresentationID$/$Number$.m4s" startNumber="0" initialization="$RepresentationID$/init.mp4"/>
   <Representation id="video/400000" codecs="avc1.4d401e" width="800" height="450" frameRate="25" startWithSAP="1" bandwidth="400000"></Representation>
   <Representation id="video/800000" codecs="avc1.4d401e" width="800" height="450" frameRate="25" startWithSAP="1" bandwidth="800000"></Representation>
   <Representation id="video/1600000" codecs="avc1.4d401f" width="1280" height="720" frameRate="25" startWithSAP="1" bandwidth="1600000"></Representation>
   <Representation id="video/2700000" codecs="avc1.4d401f" width="1280" height="720" frameRate="25" startWithSAP="1" bandwidth="2700000"></Representation>
  </AdaptationSet>
  <AdaptationSet contentType="audio" mimeType="audio/mp4" segmentAlignment="true" bitstreamSwitching="true" lang="deu">
   <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
   <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>
   <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
    <cenc:pssh>*OBFUSCATED*</cenc:pssh>
   </ContentProtection>
   <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="*OBFUSCATED*" />
   <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95" value="MSPR 2.0">
    <cenc:pssh>*OBFUSCATED*</cenc:pssh>
    <mspr:pro>*OBFUSCATED*</mspr:pro>
   </ContentProtection>
   <ContentProtection schemeIdUri="urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b">
    <cenc:pssh>*OBFUSCATED*</cenc:pssh>
   </ContentProtection>
   <SegmentTemplate timescale="48000" duration="288000" media="$RepresentationID$/$Number$.m4s" startNumber="0" initialization="$RepresentationID$/init.mp4"/>
   <Representation id="audiodeu/48000" codecs="mp4a.40.2" audioSamplingRate="48000" startWithSAP="1" bandwidth="48000"></Representation>
   <Representation id="audiodeu/96000" codecs="mp4a.40.2" audioSamplingRate="48000" startWithSAP="1" bandwidth="96000"></Representation>
   <Representation id="audiodeu/128000" codecs="mp4a.40.2" audioSamplingRate="48000" startWithSAP="1" bandwidth="128000"></Representation>
  </AdaptationSet>
 </Period>
 <UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-head:2014" value="*OBFUSCATED*"/>
 <UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-iso:2014" value="*OBFUSCATED*"/>
</MPD>
```

### Original android license request
```protobuf
client_id {
  type: DEVICE_CERTIFICATE
  token: "*OBFUSCATED*"
  client_info {
    name: "company_name"
    value: "samsung"
  }
  client_info {
    name: "model_name"
    value: "SM-G950F"
  }
  client_info {
    name: "architecture_name"
    value: "arm64-v8a"
  }
  client_info {
    name: "device_name"
    value: "dreamlte"
  }
  client_info {
    name: "product_name"
    value: "dreamltexx"
  }
  client_info {
    name: "build_info"
    value: "samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU4CRI5:user/release-keys"
  }
  client_info {
    name: "device_id"
    value: "SECPHONE_00000000000000001585474"
  }
  client_info {
    name: "widevine_cdm_version"
    value: "v5.0.0-android"
  }
  client_info {
    name: "oem_crypto_security_patch_level"
    value: "0"
  }
  client_capabilities {
    session_token: true
    oem_crypto_api_version: 11
    4: 255
    6: 0
    8: 0
    9: 0
  }
}
content_id {
  cenc_id {
    pssh: "*OBFUSCATED*"
    license_type: STREAMING
    request_id: "610B5B8BA1A623C30D00000000000000"
  }
}
type: NEW
request_time: 1540206844
protocol_version: VERSION_2_1
key_control_nonce: 609507093
```

### Proxy license request
```json
{
  "provider": "*OBFUSCATED*",
  "payload": {
    "clientId": {
      "type": "DRM_DEVICE_CERTIFICATE",
      "token": "*OBFUSCATED*",
      "clientInfo": [
        {
          "name": "company_name",
          "value": "samsung"
        },
        {
          "name": "model_name",
          "value": "SM-G950F"
        },
        {
          "name": "architecture_name",
          "value": "arm64-v8a"
        },
        {
          "name": "device_name",
          "value": "dreamlte"
        },
        {
          "name": "product_name",
          "value": "dreamltexx"
        },
        {
          "name": "build_info",
          "value": "samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU4CRI5:user/release-keys"
        },
        {
          "name": "device_id",
          "value": "SECPHONE_00000000000000001585474"
        },
        {
          "name": "widevine_cdm_version",
          "value": "v5.0.0-android"
        },
        {
          "name": "oem_crypto_security_patch_level",
          "value": "0"
        }
      ],
      "clientCapabilities": {
        "sessionToken": true,
        "maxHdcpVersion": "HDCP_NO_DIGITAL_OUTPUT",
        "oemCryptoApiVersion": 11,
        "antiRollbackUsageTable": false,
        "canUpdateSrm": false,
        "supportedCertificateKeyType": [
          "RSA_2048"
        ]
      }
    },
    "contentId": {
      "cencIdDeprecated": {
        "pssh": [
          "*OBFUSCATED*"
        ],
        "licenseType": "STREAMING",
        "requestId": "MzA3MjNBQzZBRTA1OTlCODExMDAwMDAwMDAwMDAwMDA="
      }
    },
    "type": "NEW",
    "requestTime": "1540207032",
    "protocolVersion": "VERSION_2_1",
    "keyControlNonce": 1592257037
  },
  "use_policy_overrides_exclusively": true,
  "policy_overrides": {
    "can_play": true,
    "can_persist": false,
    "renewal_delay_seconds": 10,
    "can_renew": false,
    "license_duration_seconds": 21600
  },
  "content_key_specs": [
    {
      "track_type": "AUDIO",
      "required_output_protection": {
        "hdcp": "HDCP_NONE"
      },
      "key": "*OBFUSCATED*",
      "key_id": "",
      "security_level": 1
    }
  ],
  "content_id": "MTI5NTI="
}
```

### License Response
```json
{
  "status": "OK",
  "license": {
	"id":{
		"requestId":"MzA3MjNBQzZBRTA1OTlCODExMDAwMDAwMDAwMDAwMDA=",
		"sessionId":"MzA3MjNBQzZBRTA1OTlCODExMDAwMDAwMDAwMDAwMDA=",
		"purchaseId":"",
		"type":"STREAMING",
		"version":0
	},
	"policy":{
		"canPlay":true,
		"canPersist":false,
		"canRenew":false,
		"licenseDurationSeconds":"21600",
		"renewalDelaySeconds":"10"
	},
	"key":[{
		"iv":"*OBFUSCATED*",
		"type":"SIGNING"
	},{
		"id":"*OBFUSCATED*",
		"iv":"*OBFUSCATED*",
		"type":"CONTENT",
		"level":"SW_SECURE_CRYPTO",
		"requiredProtection":{
			"hdcp":"HDCP_NONE"
		},
		"keyControl":{
			"keyControlBlock":"*OBFUSCATED*",
			"iv":"*OBFUSCATED*"
		},
		"trackLabel":"AUDIO"
	}],
	"licenseStartTime":"1540207032",
	"remoteAttestationVerified":true,
	"protectionScheme":0,
	"platformVerificationStatus":"PLATFORM_HARDWARE_VERIFIED"
},
  "license_metadata": {
    "content_id": "MTI5NTI=",
    "license_type": "STREAMING",
    "request_type": "NEW"
  },
  "supported_tracks": [
    {
      "type": "AUDIO",
      "key_id": "*OBFUSCATED*"
    }
  ],
  "make": "Samsung",
  "model": "dreamlte",
  "remote_attestation_verified": true,
  "security_level": 1,
  "internal_status": 0,
  "session_state": {
    "license_id": {
      "request_id": "MzA3MjNBQzZBRTA1OTlCODExMDAwMDAwMDAwMDAwMDA=",
      "session_id": "MzA3MjNBQzZBRTA1OTlCODExMDAwMDAwMDAwMDAwMDA=",
      "purchase_id": "",
      "type": "STREAMING",
      "version": 0
    },
    "signing_key": "*OBFUSCATED*",
    "keybox_system_id": 7169,
    "license_counter": 0
  },
  "drm_cert_serial_number": "OTE0MDg2MmRiM2VlMjlhMmVlZDVmMTI5YzhkNjk1NjY=",
  "device_whitelist_state": "DEVICE_WHITELISTED",
  "message_type": "LICENSE",
  "platform": "Android",
  "device_state": "RELEASED",
  "pssh_data": {
    "key_id": [
      "*OBFUSCATED*"
    ],
    "content_id": "*OBFUSCATED*"
  },
  "client_max_hdcp_version": "HDCP_NO_DIGITAL_OUTPUT",
  "client_info": [
    {
      "name": "company_name",
      "value": "samsung"
    },
    {
      "name": "model_name",
      "value": "SM-G950F"
    },
    {
      "name": "architecture_name",
      "value": "arm64-v8a"
    },
    {
      "name": "device_name",
      "value": "dreamlte"
    },
    {
      "name": "product_name",
      "value": "dreamltexx"
    },
    {
      "name": "build_info",
      "value": "samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU4CRI5:user/release-keys"
    },
    {
      "name": "device_id",
      "value": "SECPHONE_00000000000000001585474"
    },
    {
      "name": "widevine_cdm_version",
      "value": "v5.0.0-android"
    },
    {
      "name": "oem_crypto_security_patch_level",
      "value": "0"
    }
  ],
  "platform_verification_status": "PLATFORM_HARDWARE_VERIFIED",
  "content_owner": "*OBFUSCATED*",
  "content_provider": "*OBFUSCATED*"
}
```

**Comment by ojw28** [comment]
Have you read our [Drm page](http://google.github.io/ExoPlayer/drm.html)?

**Comment by bergmark** [comment]
No i completely missed that page!

Thanks a lot, it looks promising. We have some more testing to do, I'll report back!

**Comment by bergmark** [comment]
We managed to resolve everything by enabling `multiSession`, it also turned out we were using the wrong key for audio. Thanks again!
