### ISSUE TITLE
SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by m-franco** [google/ExoPlayer#5009]
I have exoplayer 2.9.0 and  i can't play a DRM content with this error.

In an older version of exoplayer the same content plays correctly.

I can't edit the code because the error happens in the locked classes of the library.

Any Help?

com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ .mpd?dvr_window_length=30
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:249)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:833)
     Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by ojw28** [comment]
This is already covered by [existing issues](https://github.com/google/ExoPlayer/issues?utf8=%E2%9C%93&q=is%3Aissue+%22Trust+anchor+for+certification+path+not+found%22+).
