### ISSUE TITLE
Exoplayer sets Content-Length header by default in license server call

### ISSUE THREAD

**Issue by acollazomayer** [google/ExoPlayer#5036]
### Issue description
Im implementing DRM with exoplayer to a custom license server. This license server does not allow the Header `Content-Length` however, The Request to the license server is setting it by default. I have no control of the license server. How can I omit this header.

### Version of ExoPlayer being used
I am using 2.9.0

### Device(s) and version(s) of Android being used
Im using android version 7.1.2

### A full bug report captured from the device
```
10-31 13:04:16.118  9926  9926 D setDrmLicenseHeader: [Ljava.lang.String;@d3fb5b9
10-31 13:04:16.119  9926  9926 D setDrmLicenseHeader: [Ljava.lang.String;@394edfe
10-31 13:04:19.399  9926  9931 I art     : Do partial code cache collection, code=251KB, data=219KB
10-31 13:04:19.403  9926  9931 I art     : After code cache collection, code=250KB, data=219KB
10-31 13:04:19.403  9926  9931 I art     : Increasing code cache capacity to 1024KB
10-31 13:04:21.744  9926  9926 E DRM Error: exception
10-31 13:04:21.744  9926  9926 E DRM Error: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
10-31 13:04:21.744  9926  9926 E DRM Error: 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:298)
10-31 13:04:21.744  9926  9926 E DRM Error: 	at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
10-31 13:04:21.744  9926  9926 E DRM Error: 	at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)
10-31 13:04:21.744  9926  9926 E DRM Error: 	at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)
10-31 13:04:21.744  9926  9926 E DRM Error: 	at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:140)
10-31 13:04:21.744  9926  9926 E DRM Error: 	at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:160)
10-31 13:04:21.744  9926  9926 E DRM Error: 	at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:135)
10-31 13:04:21.744  9926  9926 E DRM Error: 	at com.google.android.exoplayer2.drm.DefaultDrmSession$PostRequestHandler.handleMessage(DefaultDrmSession.java:507)
10-31 13:04:21.744  9926  9926 E DRM Error: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-31 13:04:21.744  9926  9926 E DRM Error: 	at android.os.Looper.loop(Looper.java:154)
10-31 13:04:21.744  9926  9926 E DRM Error: 	at android.os.HandlerThread.run(HandlerThread.java:61)
10-31 13:04:21.744  9926  9926 D DRM Info: onDrmSessionManagerError
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: Playback error.
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.shouldWaitForKeys(MediaCodecRenderer.java:1022)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:975)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:650)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:530)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:154)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:443)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:438)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:403)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:44)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSession$PostResponseHandler.handleMessage(DefaultDrmSession.java:473)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	... 2 more
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:298)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:140)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:160)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:135)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSession$PostRequestHandler.handleMessage(DefaultDrmSession.java:507)
10-31 13:04:21.752  9926 10179 E ExoPlayerImplInternal: 	... 3 more
10-31 13:04:21.753  4139 10188 I OmxComponent: OMX_CommandStateSet 716 Cmd 0 nParam1 0x2
10-31 13:04:21.753  4139 10188 I OmxComponent: STATE_SET:   OMX_StateExecuting => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome.secure
10-31 13:04:21.754  4139 10188 I OmxComponent: OMX.amlogic.avc.decoder.awesome.secure: flush input
10-31 13:04:21.754  4139 10188 V AmlogicVideoDecoderAwesome: flushInput:749 >
10-31 13:04:21.754  4139 10188 V OMX_WorkerPeer: hardware/amlogic/omx/omx_framework/WorkerPeer.cpp:flushInput:56 --------------------
10-31 13:04:21.754  4139 10188 V AmlogicVideoDecoderAwesome: pause:232 >
10-31 13:04:21.754  4139 10188 V AmlogicVideoDecoderAwesome: reset:272 >
10-31 13:04:21.754  4139 10188 D AmlogicVideoDecoderAwesome: reset_1
10-31 13:04:21.754  4139 10188 I amcodec : AMSTREAM_SET_OMX_RUNNING ret=0
10-31 13:04:21.882  4139 10188 I amcodec : [codec_reset:1075]ret=0
10-31 13:04:21.885  4139 10188 D AmlogicVideoDecoderAwesome: reset_2
10-31 13:04:21.885  4139 10188 D AmlogicVideoDecoderAwesome: mDTaskStatus=1
10-31 13:04:21.885  4139 10188 V AmlogicVideoDecoderAwesome: start:240 >
10-31 13:04:21.885  4139 10188 E ThreadWorker: pthread on exit wait clean
10-31 13:04:21.886  4139 10188 D AmlogicVideoDecoderAwesome: mVideo start
10-31 13:04:21.886  4139 10188 V AmlogicVideoDecoderAwesome: flushInput:774 >
10-31 13:04:21.886  4139 10188 I OmxComponent: OMX.amlogic.avc.decoder.awesome.secure: flush output
10-31 13:04:21.886  4139 10188 V AmlogicVideoDecoderAwesome: flushOutput:777 >
10-31 13:04:21.886  4139 10201 V OMX_WorkerPeer: hardware/amlogic/omx/omx_framework/WorkerPeer.cpp:runWorkerStatic:152 --------------------
10-31 13:04:21.886  4139 10201 V OMX_WorkerPeer: hardware/amlogic/omx/omx_framework/WorkerPeer.cpp:runWorker:158 --------------------
10-31 13:04:21.886  4139 10188 D AmlogicVideoDecoderAwesome: flushOutput: fillBufferDone_OMX_BUFFERFLAG_EOS
10-31 13:04:21.886  4139 10188 D AmlogicVideoDecoderAwesome: flushOutput: fillBufferDone_OMX_BUFFERFLAG_EOS
10-31 13:04:21.886  4139 10188 D AmlogicVideoDecoderAwesome: flushOutput: fillBufferDone_OMX_BUFFERFLAG_EOS
10-31 13:04:21.886  4139 10188 D AmlogicVideoDecoderAwesome: flushOutput: fillBufferDone_OMX_BUFFERFLAG_EOS
10-31 13:04:21.886  4139 10188 D AmlogicVideoDecoderAwesome: mVideo stop
10-31 13:04:21.888  4139 10188 V AmlogicVideoDecoderAwesome: stop:262 >
10-31 13:04:21.897  4139 10188 I OmxComponent: STATE_TRANS: OMX_StateExecuting => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome.secure
10-31 13:04:21.897  4139 10188 I OmxComponent: STATE_TRANS: OMX_StateExecuting => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome.secure
10-31 13:04:21.897  4139 10188 I OmxComponent: STATE_TRANS: OMX_StateExecuting => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome.secure
10-31 13:04:21.897  4139 10188 I OmxComponent: STATE_TRANS: OMX_StateExecuting => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome.secure
10-31 13:04:21.897  4139 10188 I OmxComponent: STATE_TRANS: OMX_StateExecuting => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome.secure
10-31 13:04:21.897  4139 10188 I OmxComponent: STATE_DONE:  OMX_StateExecuting => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome.secure
10-31 13:04:21.898  4139 10188 I OmxComponent: OMX_CommandStateSet 716 Cmd 0 nParam1 0x1
10-31 13:04:21.898  4139 10188 I OmxComponent: STATE_SET:   OMX_StateIdle => OMX_StateLoaded : OMX.amlogic.avc.decoder.awesome.secure
10-31 13:04:21.898  4139 10188 V AmlogicVideoDecoderAwesome: releaseResources:305 >
10-31 13:04:21.898  4139 10188 V AmlogicVideoDecoderAwesome: tearDown:653 >
10-31 13:04:21.898  4139 10188 V AmlogicVideoDecoderAwesome: tearDown:1065 >
10-31 13:04:21.898  4139 10188 V AmlogicVideoDecoderAwesome: initializeState_l:1117 >
10-31 13:04:21.904  4101  4154 I SystemControl: Matched uevent message with pattern: DEVPATH=/devices/virtual/tv/tv
10-31 13:04:21.904  4101  4154 I SystemControl: HDCP TX switch_name: end_hint ,switch_state: 0
10-31 13:04:21.904  4101  4154 D SystemControl: Video framerate switchName: end_hint, switchState: 0, current display mode:1080p60hz, frame rate status:0[0:off 1:pulldown 2:force switch]
10-31 13:04:21.904  4101  4154 D SystemControl: hdmi frame rate is off
10-31 13:04:21.908  9926 10187 D SurfaceUtils: set up nativeWindow 0xc9339008 for 1x1, color 0x2, rotation 0, usage 0x930
10-31 13:04:21.909  4105  4113 E ion     : ioctl c0144900 failed with code -1: No such device
10-31 13:04:21.913  4105  4929 E ion     : ioctl c0144900 failed with code -1: No such device
10-31 13:04:21.929  4139 10188 E amdrmutils: segment 0: [67c00000-71bfffff]
10-31 13:04:21.929  4139 10188 I secmem_tz: used 1, i 0, start 67c00000 size a000000
10-31 13:04:21.929  4139 10188 I secmem_tz: used 1, i 1, start 0 size 1
10-31 13:04:21.959  4139 10188 D AmlogicVideoDecoderAwesome: close seclib handle
10-31 13:04:21.959  4139 10188 V AmlogicVideoDecoderAwesome: get def maping [decoder ppmgr deinterlace amvideo]
10-31 13:04:21.959  4139 10188 V AmlogicVideoDecoderAwesome: disable osd or video__rm default,ret=0
10-31 13:04:21.965  4139 10188 V AmlogicVideoDecoderAwesome: disable osd video ...0
10-31 13:04:21.965  4139 10188 I OmxComponent: STATE_TRANS: OMX_StateIdle => OMX_StateLoaded : OMX.amlogic.avc.decoder.awesome.secure
10-31 13:04:21.965  4139 10188 I OmxComponent: STATE_DONE:  OMX_StateIdle => OMX_StateLoaded : OMX.amlogic.avc.decoder.awesome.secure
10-31 13:04:21.968  4139  4602 D OmxComponentManagerImpl: DecreaseEntryNumByName pEntry->mNum=1, pEntry->mMaxNum:1,componentName:OMX.amlogic.avc.decoder.awesome.secure
10-31 13:04:21.968  4139  4602 I omx_core: OMX_freeHandle_num_= 0
10-31 13:04:21.968  4139  4602 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoderAwesome
10-31 13:04:21.968  4139  4602 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoder
10-31 13:04:21.984  4140  4140 I WVCdm   : CdmEngine::CloseSession
10-31 13:04:21.989  9926  9926 D ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=idle
```

**Comment by ojw28** [comment]
> This license server does not allow the Header Content-Length however

I'm not sure this is a valid thing for a server to do. Is it? I think the `Content-Length` field is filled in by the underlying network stack; and it's expected that all servers should support it.

**Comment by acollazomayer** [comment]
@ojw28 The thing with the license servers we use is that they are very restricting. I make the same call to the license server form a DashJS drm implementation and its reproducing with no problem. When i make it with exoplayer I am getting an error code of 400 (Which in this case implies a mismatch in the headers. And the only difference between the two calls is the Content-Length Header

**Comment by ojw28** [comment]
Right, but at some point there has to be a minimum level of support provided by the server.

You might be able to "fix" the problem on the client side by removing [this line](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.java#L520), or possibly replacing it with a call to `setChunkedStreamingMode`. Beyond that, unless you can point to ExoPlayer actually being broken in some way as opposed to this being a server issue, I think you'll have to figure this one out by yourselves.

**Comment by acollazomayer** [comment]
@ojw28 Thanks ojw28 I will try to do this. I found out that now i have to send to reproduce two times and then after that the license server is returning 200. Which is also wierd. However i can reproduce.

Thanks!!!

**Comment by ojw28** [comment]
Closing as I do not see this as an ExoPlayer issue.
