### ISSUE TITLE
setPlayWhenReady function crashing CastPlayer when calling it with value false and then true while player state buffering

### ISSUE THREAD

**Issue by itboy87** [google/ExoPlayer#5053]
### Issue description
Player crash when video casting on chromecast and playstate is buffering then if we set CastPlayer.setPlayWhenReady(false) and then CastPlayer.setPlayWhenReady(true) in sequence. CastPlayer crash and cast stop working. According to crash first CastPlayer.setPlayWhenReady(false) was not committed which cause crash check logs below. I think it will be fixed if i will wait for player state to change and then set CastPlayer.setPlayWhenReady. But i think that should be handled well by cast player or it should be function like CastPlayer. isPlayWhenReadyCommitted. I see that function already somewhere in docs but i can't access that in code. This error is only on custom player view.

### Reproduction steps
when video cast start buffering on tv call function CastPlayer.setPlayWhenReady(false) and then CastPlayer.setPlayWhenReady(true). It will print crash logs
This is my code if function called pausePlayer and then playPlayer while buffering on cast tv it will crash.

```
public void playPlayer() {
        if (getPlayer() != null && !getPlayer().getPlayWhenReady()) {
            getPlayer().setPlayWhenReady(true);
        }
    }

    public void pausePlayer() {
        if (getPlayer() != null && getPlayer().getPlayWhenReady()) {
            getPlayer().setPlayWhenReady(false);
        }
    }
```

### Link to test content
this issue on every link mp4 video link

### Version of ExoPlayer being used
Exoplayer and extension-cast both 2.9.0

### Device(s) and version(s) of Android being used
Samsung S9 Android Oreo

### A full bug report captured from the device
```
2018-11-04 19:27:42.572 23555-23555/? E/RemoteMediaClient: Result already set when calling onRequestReplaced
    java.lang.IllegalStateException: Results have already been set
        at com.google.android.gms.common.internal.Preconditions.checkState(Unknown Source:29)
        at com.google.android.gms.common.api.internal.BasePendingResult.setResult(Unknown Source:129)
        at com.google.android.gms.cast.framework.media.zzaw.zzb(Unknown Source:2)
        at com.google.android.gms.internal.cast.zzdn.zza(Unknown Source:13)
        at com.google.android.gms.internal.cast.zzdh.zzc(Unknown Source:97)
        at com.google.android.gms.cast.framework.media.zzap.zzb(Unknown Source:3)
        at com.google.android.gms.cast.framework.media.RemoteMediaClient$zzc.doExecute(Unknown Source:16)
        at com.google.android.gms.common.api.internal.BaseImplementation$ApiMethodImpl.run(Unknown Source:19)
        at com.google.android.gms.common.api.internal.zaah.execute(Unknown Source:20)
        at com.google.android.gms.common.api.internal.zabe.execute(Unknown Source:23)
        at com.google.android.gms.common.api.internal.zaaw.execute(Unknown Source:74)
        at com.google.android.gms.cast.framework.media.RemoteMediaClient.zza(Unknown Source:353)
        at com.google.android.gms.cast.framework.media.RemoteMediaClient
.play(Unknown Source:73)
        at com.google.android.gms.cast.framework.media.RemoteMediaClient.play(Unknown Source:68)
        at com.google.android.exoplayer2.ext.cast.CastPlayer.setPlayWhenReady(CastPlayer.java:333)
```

**Comment by itboy87** [comment]
i changed my code with this now its working fine
```
@Override
public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                VideoPlayerHelper.this.playWhenReady = playWhenReady;
             // other logics          
}
public void playPlayer() {
        if (getPlayer() != null && !playWhenReady) {
            playWhenReady = true;
            getPlayer().setPlayWhenReady(true);
        }
    }

    public void pausePlayer() {
        if (getPlayer() != null && playWhenReady) {
            playWhenReady = false;
            getPlayer().setPlayWhenReady(false);
        }
    }
```
I added my own variable playWhenReady and changing it on pause, play and when playerstate change. Now its not crashing.

**Comment by AquilesCanta** [comment]
Hi @itboy87, is this still an issue for you? I'm not able to reproduce by introducing the following code in the demo app:

```java
  @Override
  public void onPlaybackStateChanged(@Player.State int playbackState) {
    if (playbackState == Player.STATE_BUFFERING) {
      currentPlayer.setPlayWhenReady(false);
      currentPlayer.setPlayWhenReady(true);
    }
    ...
```

If it's still an issue can you provide some insight on how we may be able to reproduce? Perhaps you can provide a minimal sample app or code snipped for me to try?
