### ISSUE TITLE
the video that is recorded with android Camera2 doesn't play with exoplayer

### ISSUE THREAD

**Issue by fahime-ghasemi** [google/ExoPlayer#5060]
I added a fragment to android-Camera2Video that has an ExoPlayer to play video that is recorded.
At the end of stopRecordingVideo method, I passed the mNextVideoAbsolutePath variable to a new fragment to play it in exoplayer. but I got the following error.

2018-11-05 18:22:55.538 6128-6830/com.example.android.camera2video E/LoadTask: Unexpected exception loading stream
java.lang.IllegalStateException: Top bit not zero: -696383949
at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:389)
at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:174)
at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.getTrackSampleTables(Mp4Extractor.java:455)
at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:390)
at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:358)
at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:349)
at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:180)
at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:898)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:762)

2018-11-05 18:22:58.550 6128-6829/com.example.android.camera2video E/ExoPlayerImplInternal: Source error.
java.io.EOFException
at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:265)
at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:72)
at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:81)
at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:334)
at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:180)
at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:898)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:762)

**Comment by AquilesCanta** [comment]
This looks a lot like a malformed media issue. Can you please provide us with a sample to reproduce the issue? If the media is not being generated correctly there is not much else we can do to help.

We will reopen the issue once the media is provided.
