### ISSUE TITLE
How to play DASH multicast chunks (.m4s) in Exoplayer.

### ISSUE THREAD

**Issue by shepiu** [google/ExoPlayer#5094]
### Issue description
We are receiving the .m4s chunk of the DASH(.mpd) media file from the multicast broadcaster using the UdpDataSource class but unable to play video(.m4s chunks) using DashMediaSource Factory.

Please let me know how to play .m4s chunks directly in Exoplayer?.

### Reproduction steps
Once we received the (.m4s) chunk and passed that chunk to DashMediaSource at that time Exoplayer gives the parsing exception.

### Version of ExoPlayer being used
I am using com.google.android.exoplayer:exoplayer:r2.4.3 version.

### Device(s) and version(s) of Android being used
It is occurring on all android phones having API level greater than 25.

### A full bug report captured from the device
ExoPlayerImplInternal: Source error.
                                                                                         com.google.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:9 in java.io.InputStreamReader@b16971d) 
                                                                                             at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:101)
                                                                                             at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:54)
                                                                                             at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:126)
                                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                             at java.lang.Thread.run(Thread.java:764)
                                                                                          Caused by: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:9 in java.io.InputStreamReader@b16971d) 
                                                                                             at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1220)
                                                                                             at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1402)
                                                                                             at org.kxml2.io.KXmlParser.next(KXmlParser.java:393)
                                                                                             at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
                                                                                             at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:94)
                                                                                             at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:54) 
                                                                                             at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:126) 
                                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315) 
                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                             at java.lang.Thread.run(Thread.java:764) 
11-13 00:09:05.801 7788-7788/com.google.android.exoplayer2.demo E/EventLogger: internalError [0.27, loadError]

**Comment by tonihei** [comment]
The error message indicates your manifest is malformed xml. Can you provide us with example media to investigate further?

**Comment by shepiu** [comment]
I have mailed you a broadcaster from where I am receiving the .m4s, you can try it and let me know how to play those chunks in Exoplayer.

**Comment by tonihei** [comment]
Can you send an example of the manifest instead? I don't think I can run the server myself locally.

**Comment by shepiu** [comment]
Hi team, 
I have mailed you an manifest file along with the .m4s chunk URL, please have a look into it. 

In our application, we are streaming the live channels using the MPEG-DASH streams. we are able to play DASH streams (.mpd) directly in Exoplayer using the DashMediaSource and DefaultDashChunkSource.Factory. Now we want to implement the multi-casting for DASH streams, for that we have implemented the multicast broadcaster which is basically reading the DASH stream and sending the .m4s chunk. We are able to receive those chunks using the UdpDataSource but Exoplayer is unable to parse these chunks.

Please let me know how to parse those .m4s chunks directly in Exoplayer to play the video.

Thanks for your Help!

**Comment by tonihei** [comment]
I tried the provided manifest and it can be parsed fine. However, I wasn't able to play the streams because the content is encrypted. Can you provide a non-encrypted test stream or the DRM license for this one?

**Comment by shepiu** [comment]
Okay, that is the problem which I am facing.
I am successfully able to play the manifest file as it doing the unicasting i.e we are directly initializing the Exoplayer with .mpd file URI but when I tried to play the (.m4s) chunks which I am receiving from the multicast address (224.100.0.1), It is giving me the above XmlPullParserException.

Here is the code how I am preparing the DashMediaSource Factory using UdpDataSource.

Uri uri = Uri.parse("udp://@224.100.0.1:9050");
MediaSource udpMedia = new DashMediaSource.Factory(
                new DefaultDashChunkSource.Factory(factory),
                 buildDataSourceFactory())
                 .createMediaSource(uri);

private DataSource.Factory buildDataSourceFactory() {
    return new UdpDataSource.Factory(){
      @Override
      public DataSource createDataSource() {
        return new UdpDataSource(null, 3000, 100000);
      }
    };
  }

When I receive the .m4s chunk from the multicast address in the UdpDataSource, Exoplayer is unable to parse the chunk.

**Comment by tonihei** [comment]
You probably need an ExtractorMediaSource to play the chunks directly as they are no longer a DASH stream when played on their own. Also, I suspect you still need to decrypt them as the manifest indicated that they are encrypted.

**Comment by shepiu** [comment]
Thanks for the help and yes, URL is encrypted.

I have tried to play multicast chunks using ExtractorMediaSource but it's giving me the following exception.

Here is the code for how I have initialized ExtractorMediaSource.
Uri uri = Uri.parse("udp://@224.100.0.1:9050");
        new ExtractorMediaSource.Factory(buildDataSourceFactory(true))
                .createMediaSource(uri, handler, listener);

private DataSource.Factory buildDataSourceFactory() {
return new UdpDataSource.Factory(){
@override
public DataSource createDataSource() {
return new UdpDataSource(null, 3000, 100000);
}};}

Exception: 
com.google.android.exoplayer2.source.ExtractorMediaSource$UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:678)
at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:602)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Source error.
com.google.android.exoplayer2.source.ExtractorMediaSource$UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:678)
at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:602)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [0.85]
com.google.android.exoplayer2.ExoPlaybackException
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:310)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)
at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
Caused by: com.google.android.exoplayer2.source.ExtractorMediaSource$UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:678)
at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:602)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)


Please let me know how should I play .m4s chunks directly in Exoplayer.

**Comment by tonihei** [comment]
As already noted above, the content is encrypted and you need an drm session manager to load the keys for decryption. See [here](https://google.github.io/ExoPlayer/drm.html) for explanations.

**Comment by tonihei** [comment]
Closing due to inactivity.
