### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by AllenVork** [google/ExoPlayer#5099]
suspend all histogram:	Sum: 32.248ms 99% C.I. 3us-4856.319us Avg: 316.156us Max: 5225us
DALVIK THREADS (87):
"Signal Catcher" daemon prio=5 tid=3 Runnable
  | group="system" sCount=0 dsCount=0 obj=0x12c68940 self=0x7f9c897400
  | sysTid=13647 nice=0 cgrp=default sched=0/0 handle=0x7f9bdfc450
  | state=R schedstat=( 52628614 134385 84 ) utm=2 stm=3 core=5 HZ=100
  | stack=0x7f9bd02000-0x7f9bd04000 stackSize=1005KB
  | held mutexes= "mutator lock"(shared held)
  (no managed stack frames)

"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x75f2a000 self=0x7f9c896a00
  | sysTid=13641 nice=-10 cgrp=default sched=0/0 handle=0x7fa0dfaa98
  | state=S schedstat=( 11821516173 3082137127 14014 ) utm=1071 stm=111 core=1 HZ=100
  | stack=0x7fc3326000-0x7fc3328000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x0d6c64ad> (a com.google.android.exoplayer2.PlayerMessage)
  at com.google.android.exoplayer2.PlayerMessage.blockUntilDelivered(SourceFile:282)
  at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurfaceInternal(SourceFile:962)
  at com.google.android.exoplayer2.SimpleExoPlayer.a(SourceFile:59)
  at com.google.android.exoplayer2.SimpleExoPlayer$ComponentListener.surfaceDestroyed(SourceFile:1134)
  at android.view.SurfaceView.updateWindow(SurfaceView.java:672)
  at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:276)
  at android.view.View.dispatchWindowVisibilityChanged(View.java:10582)
  at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)
  at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)
  at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)
  ... repeated 4 times
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1804)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1493)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7073)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:924)
  at android.view.Choreographer.doCallbacks(Choreographer.java:726)
  at android.view.Choreographer.doFrame(Choreographer.java:660)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:910)
  at android.os.Handler.handleCallback(Handler.java:836)
  at android.os.Handler.dispatchMessage(Handler.java:103)
  at android.os.Looper.loop(Looper.java:203)
  at android.app.ActivityThread.main(ActivityThread.java:6564)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by tonihei** [comment]
That's most likely an issue with the device not handling surface switching properly. 

To add the workaround to our code please let us know the BUILD.DEVICE and BUILD.MODEL values, as well as the used codec. This would also be part of the bugreport which we request for each reported issue.

**Comment by tonihei** [comment]
Closing as we haven't received any new information.
