### ISSUE TITLE
ExoPlayerImplInternal: Renderer error

### ISSUE THREAD

**Issue by yy1415326206** [google/ExoPlayer#5100]
15:03:12.806 31903-18240/com.ydwx.yoyo E/ExoPlayerImplInternal: Renderer error.
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:418)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:405)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:839)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:455)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, video/avc, -1, null, [1280, 2768, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:405) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:839) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:455) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc03
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:577)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:414)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:394)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:839) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:455) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by yy1415326206** [comment]
version 2.6.0

**Comment by tonihei** [comment]
Please provide the full information requested in the [issue template.](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE)

**Comment by yy1415326206** [comment]
I/ExoPlayerImpl: Init cb69fb2 [ExoPlayerLib/2.6.0] [o5ltechn, SM-G5500, samsung, 22]
11-14 09:46:26.081 18705-18705/com.ydwx.yoyo D/skia: --- SkImageDecoder::Factory returned null
11-14 09:46:26.086 18705-19059/com.ydwx.yoyo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
11-14 09:46:26.086 18705-19059/com.ydwx.yoyo I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
11-14 09:46:26.091 18705-19059/com.ydwx.yoyo I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
11-14 09:46:26.106 18705-18874/com.ydwx.yoyo I/qtaguid: Untagging socket 103
11-14 09:46:26.116 18705-18705/com.ydwx.yoyo D/SRIB_DBQ: SurfaceView:updateWindow: viewRoot.sSVBufferCount=-1 mSVBufferCount=-1
11-14 09:46:26.206 18705-19058/com.ydwx.yoyo D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1280x2768x-1.0] [OMX.Exynos.avc.dec, video/avc] [o5ltechn, SM-G5500, samsung, 22]
11-14 09:46:26.206 18705-19058/com.ydwx.yoyo D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1280x2768x-1.0] [OMX.Exynos.avc.dec, video/avc] [o5ltechn, SM-G5500, samsung, 22]
11-14 09:46:26.211 18705-19058/com.ydwx.yoyo I/ACodec:  [] Now uninitialized
11-14 09:46:26.216 18705-19062/com.ydwx.yoyo I/OMXClient: Using client-side OMX mux.
11-14 09:46:26.241 18705-19062/com.ydwx.yoyo I/ACodec: [OMX.Exynos.avc.dec] Now Loaded
11-14 09:46:26.241 18705-19062/com.ydwx.yoyo I/ACodec: can't find wfdsink-exynos-enable
11-14 09:46:26.246 18705-19062/com.ydwx.yoyo E/ACodec:  configureCodec multi window instance fail  appPid : 18705
11-14 09:46:26.246 18705-19062/com.ydwx.yoyo E/ACodec: [OMX.Exynos.avc.dec] configureCodec returning error -1021
11-14 09:46:26.246 18705-19062/com.ydwx.yoyo E/ACodec: signalError(omxError 0x80001001, internalError -1021)
11-14 09:46:26.246 18705-19061/com.ydwx.yoyo E/MediaCodec: Codec reported err 0xfffffc03, actionCode 0, while in state 3
11-14 09:46:26.251 18705-19058/com.ydwx.yoyo E/MediaCodec: configure failed with err 0xfffffc03, resetting...
11-14 09:46:26.256 18705-19062/com.ydwx.yoyo I/ACodec:  [OMX.Exynos.avc.dec] Now uninitialized
11-14 09:46:26.256 18705-19058/com.ydwx.yoyo I/ACodec:  [] Now uninitialized
11-14 09:46:26.261 18705-19062/com.ydwx.yoyo I/OMXClient: Using client-side OMX mux.
11-14 09:46:26.276 18705-19062/com.ydwx.yoyo I/ACodec: [OMX.Exynos.avc.dec] Now Loaded
11-14 09:46:26.281 18705-19058/com.ydwx.yoyo E/ExoPlayerImplInternal: Renderer error.
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:418)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:405)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:839)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:455)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, video/avc, -1, null, [1280, 2768, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:405) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:839) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:455) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc03
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:577)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:414)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:394)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:839) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:455) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
11-14 09:46:26.286 18705-19062/com.ydwx.yoyo I/ACodec:  [OMX.Exynos.avc.dec] Now uninitialized

**Comment by yy1415326206** [comment]
private void initPalyer() {
        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory trackFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector = new DefaultTrackSelector(trackFactory);
        mPlayer = ExoPlayerFactory.newSimpleInstance(mActivity, trackSelector);
        simpleExoPlayerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_ZOOM);
        simpleExoPlayerView.setUseController(false);
        simpleExoPlayerView.setUseArtwork(true);
        simpleExoPlayerView.setDefaultArtwork(BitmapFactory.decodeResource(getResources(), R.drawable.default_pic_rect));
        simpleExoPlayerView.setPlayer(mPlayer);
    }

    private void playVideo(final String url) {
        DefaultBandwidthMeter defaultBandwidthMeter = new DefaultBandwidthMeter();
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(mActivity
                , Util.getUserAgent(mActivity, "playVideo")
                , defaultBandwidthMeter);
        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
        ((DefaultExtractorsFactory) extractorsFactory).setMp4ExtractorFlags(Mp4Extractor.FLAG_WORKAROUND_IGNORE_EDIT_LISTS);
        Uri uri = Uri.parse(url);
        MediaSource mediaSource = new ExtractorMediaSource(uri
                , dataSourceFactory, extractorsFactory, null, null);
        // 循环播放
        MediaSource loopVideoSource = new LoopingMediaSource(mediaSource);
        mPlayer.prepare(mediaSource);
        mPlayer.setVolume(1);
        mPlayer.prepare(loopVideoSource);
        mPlayer.setPlayWhenReady(true);
    }

**Comment by tonihei** [comment]
It seems the decoder on this device doesn't support the format:
11-14 09:46:26.206 18705-19058/com.ydwx.yoyo D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1280x2768x-1.0] [OMX.Exynos.avc.dec, video/avc] [o5ltechn, SM-G5500, samsung, 22]

If you attach an EventLogger to ExoPlayer (`mPlayer.addAnalyticsListener(new EventLogger(trackSelector))`), you should hopefully see a line with the format which says NO_EXCEEDS_CAPABILITIES or just NO.

**Comment by tonihei** [comment]
I'll close the issue because the question was probably answered.
