### ISSUE TITLE
Unable to Play offline Protected DRM content in Exoplayer 2 

### ISSUE THREAD

**Issue by MuviDeveloper** [google/ExoPlayer#5123]
### Issue description
I had gone through @erdemguven https://gist.github.com/erdemguven/8c5fb4d87f084456c81245f553ba3a2f and modified the changes according to that and was successful in downloading the DRM content but to play it still requires internet connection and when trying to download the licence key using OfflineLicenceHelper class it gives out 403 error. 

"byte[] offlineLicenseKeySetId = offlineLicenseHelper.downloadLicense(drmInitData); "
com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403" 

And I have also tried with CustomDRMCallback class to get the response byte[] from executePost method and used that as offline key but in this case, I got the following error: 
Failed to handle Key Response 

* The full stack trace along with Video and Licence URL has been shared in the mail
[Failed to handle Key Response.txt](https://github.com/google/ExoPlayer/files/2598171/Failed.to.handle.Key.Response.txt)

###Version of ExoPlayer being used
2.9.1
(https://github.com/google/ExoPlayer/files/2598157/Failed.to.handle.Key.Response.txt)

###Device(s) and version(s) of Android being used
device: One Plus 5
android version: 8.1.0

**Comment by MuviDeveloper** [comment]
Hi Please find the updated video url and License Url (* this license is only valid for 24 hours) 

License url - https://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=BAAAABSMKaUAAABgjJOuprMPWJQ14_e8mpz4iGYjrxHusDeQdC3CtMu6HC25QYBPaGHDX02k2PoUycZTgG7vdTGAK1GVPYwtDT9zUBwQTGODKXfKZMwqpUFkGEKWgPEaNtsHw-hTZ8uEYhcNPsj-Izsy5VM1PnGe7HQ1TEngwZs

Video Url- https://d1gafjrnux9y1n.cloudfront.net/4050/EncodedVideo/uploads/movie_stream/full_movie/93913/stream.mpd

**Comment by AchibanaUkyo** [comment]
Just FYI I'm doing the similar integration and what I met is that the server may not support the offline license request:)

**Comment by MuviDeveloper** [comment]
> Just FYI I'm doing the similar integration and what I met is that the server may not support the offline license request:)

Hi @AchibanaUkyo
 
Are you saying about the ExpressPlay Server? Currently we are using the JNI libraries and MarlinBB provided by ExpressPlay to download and play the protected DRM content and because of this the APK size has increased to 45-50 mb.

**Comment by AchibanaUkyo** [comment]
From the license server url it should be ExpressPlay then. Check with them how to support offline widevine license request (maybe in the token)?

**Comment by MuviDeveloper** [comment]
Please find the error log while trying to download licence token using offlineLicenseHelper class: 

```
11-28 18:43:51.445 18579-18605/com.google.android.exoplayer2.demo E/perksocial: license download failed
    com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:443)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:438)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:403)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:44)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$PostResponseHandler.handleMessage(DefaultDrmSession.java:473)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)
        at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:140)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:160)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:135)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$PostRequestHandler.handleMessage(DefaultDrmSession.java:507)
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

**Comment by sravan1213** [comment]
@Muvidevlopers check whether you are adding following flag while generating express-play licence url. 

generalFlags | A 4 byte hexadecimal string representing the license flags. Allowed values are as follows: ‘00000000’ – (default value) no persistence ‘00000001’ – persistent license
-- | --

https://www.intertrust.com/products/drm-system/developer/restapi/#widevine-license-token-request

**Comment by ojw28** [comment]
Closing on the assumption that the post above answered this query. Either way, given you're seeing a 403 response code, this is likely a server/license configuration issue, rather than a problem with ExoPlayer.
