### ISSUE TITLE
I want to change Uri ,When I was playing .m3u8 file.

### ISSUE THREAD

**Issue by PreviousTlx** [google/ExoPlayer#5156]
// I want to change uri to play other .m3u8 file when I was playing .m3u8 file.
                            bandwidthMeter = new DefaultBandwidthMeter();
                            videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
                            trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
                            player = ExoPlayerFactory.newSimpleInstance(CourseDetailActivity.this, trackSelector);
                            dataSourceFactory = new DefaultDataSourceFactory(MyApplication.getAppContext(),
                                    Util.getUserAgent(MyApplication.getAppContext(), "ExoPlayer"), bandwidthMeter);
                            hlsMediaSource = new HlsMediaSource.Factory(dataSourceFactory).
                                    createMediaSource(Uri.parse(getHdModelResponses.get(0).getSrc() + "&a=1.m3u8"));
                            concatenatedSource = new ConcatenatingMediaSource(hlsMediaSource);
                            //MediaSource mediaSource = new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource();
                            player.prepare(concatenatedSource);
                            player.setPlayWhenReady(true);
                            exoPlayView.setPlayer(player);
//This code was playing a .m3u8 file.
________________________________________________________________________________________________________

hlsMediaSources = new HlsMediaSource.Factory(dataSourceFactory).
                        createMediaSource(Uri.parse(getHdModelResponses.get(0).getSrc() + "&a=1.m3u8"));
                if (concatenatedSource.getSize()>0){
                    concatenatedSource.removeMediaSource(0);
                }
                concatenatedSource.addMediaSource(hlsMediaSources);
// This code was change uri.But i had get an error.
____________________________________________________________________________________________________________
//error 
ExoPlayerImplInternal: Source error.
com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by andrewlewis** [comment]
The server is returning HTTP status code 404 Not Found, so please check the URLs you're requesting.

**Comment by PreviousTlx** [comment]
I had check url,it was right .Because when i only play the change uri .It can work.However ,when i was change url.It not work.

**Comment by PreviousTlx** [comment]
Thanks .I had found my RxManager had a Bug.
