### ISSUE TITLE
Playing Content Uri in Exoplayer 2.8.2, works only first time 

### ISSUE THREAD

**Issue by bbincybbaby** [google/ExoPlayer#5188]
Am trimming a video using FFMPEG library, and playing the video using exoplayer. The trimmed video Uri is a content Uri. When i tried to play the video it works perfectly on first time. After first play and clicking on play button after first button am getting this error below.

Am using Exoplayer 2.8.2

```
MediaSource mediaSource = new ExtractorMediaSource.Factory(new DefaultDataSourceFactory(CreatePostActivity.this, "AppName", new DefaultBandwidthMeter())).
                            createMediaSource(filePath);
                    if (exoPlayer != null) {
                        exoPlayer.prepare(mediaSource);
                        exoPlayer.setPlayWhenReady(true);
                        exoPlayer.setRepeatMode(Player.REPEAT_MODE_OFF);
                    }
```

```
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.ContentDataSource$ContentDataSourceException: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.ContentDataSource.open(ContentDataSource.java:101)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:844)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
        at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:313)
        at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:211)
        at android.support.v4.content.FileProvider.openFile(FileProvider.java:566)
        at android.content.ContentProvider.openAssetFile(ContentProvider.java:1543)
        at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1723)
        at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1789)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:423)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1412)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1249)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1172)
        at com.google.android.exoplayer2.upstream.ContentDataSource.open(ContentDataSource.java:74)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:844) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
1543894185.725 2872-2872/com.SocialMob W/System.err: com.google.android.exoplayer2.ExoPlaybackException
1543894185.727 2872-2872/com.SocialMob W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:349)
1543894185.727 2872-2872/com.SocialMob W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
1543894185.727 2872-2872/com.SocialMob W/System.err:     at android.os.Looper.loop(Looper.java:172)
1543894185.727 2872-2872/com.SocialMob W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)
1543894185.727 2872-2872/com.SocialMob W/System.err: Caused by: com.google.android.exoplayer2.upstream.ContentDataSource$ContentDataSourceException: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
1543894185.727 2872-2872/com.SocialMob W/System.err:     at com.google.android.exoplayer2.upstream.ContentDataSource.open(ContentDataSource.java:101)
1543894185.727 2872-2872/com.SocialMob W/System.err:     at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
1543894185.728 2872-2872/com.SocialMob W/System.err:     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:844)
1543894185.728 2872-2872/com.SocialMob W/System.err:     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
1543894185.728 2872-2872/com.SocialMob W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
1543894185.728 2872-2872/com.SocialMob W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
1543894185.728 2872-2872/com.SocialMob W/System.err:     at java.lang.Thread.run(Thread.java:764)
1543894185.728 2872-2872/com.SocialMob W/System.err: Caused by: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
1543894185.728 2872-2872/com.SocialMob W/System.err:     at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:313)
1543894185.728 2872-2872/com.SocialMob W/System.err:     at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:211)
1543894185.728 2872-2872/com.SocialMob W/System.err:     at android.support.v4.content.FileProvider.openFile(FileProvider.java:566)
1543894185.728 2872-2872/com.SocialMob W/System.err:     at android.content.ContentProvider.openAssetFile(ContentProvider.java:1543)
1543894185.728 2872-2872/com.SocialMob W/System.err:     at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1723)
1543894185.729 2872-2872/com.SocialMob W/System.err:     at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1789)
1543894185.729 2872-2872/com.SocialMob W/System.err:     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:423)
1543894185.729 2872-2872/com.SocialMob W/System.err:     at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1412)
1543894185.729 2872-2872/com.SocialMob W/System.err:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1249)
1543894185.729 2872-2872/com.SocialMob W/System.err:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1172)
1543894185.729 2872-2872/com.SocialMob W/System.err:     at com.google.android.exoplayer2.upstream.ContentDataSource.open(ContentDataSource.java:74)
1543894185.729 2872-2872/com.SocialMob W/System.err: 	... 6 more
```

**Comment by bbincybbaby** [comment]
@ojw28 please can you help me out ?

**Comment by erdemguven** [comment]
Please share a sample video.

Does the error occur when you play the video using ExoPlayer Demo app?
