### ISSUE TITLE
android.media.MediaDrmResetException: mediaserver died Motorola Moto G5 Plus

### ISSUE THREAD

**Issue by brunoluizcs** [google/ExoPlayer#5217]
### Issue description
When I try reproduce Dash Protected content in Device Moto G(5) Plus with Android 8.1.0, I get the follow Exception 

```
12-07 14:43:54.238 1642-1642/com.google.android.exoplayer2.demo E/EventLogger: internalError [2.22, 0.00, window=0, period=0, drmSessionManagerError]
    android.media.MediaDrmResetException: mediaserver died
        at android.media.MediaDrm.provideKeyResponse(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(FrameworkMediaDrm.java:157)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:413)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:44)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$PostResponseHandler.handleMessage(DefaultDrmSession.java:473)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

### Reproduction steps
We reproduce the problem in the demo application, I sent the bug report and instructions on how to play our content to dev.exoplayer@gmail.com
just play the content for the problem to happen

### Version of ExoPlayer being used
I notice in Version 2.8.1 and Version 2.9.2
 

### Device(s) and version(s) of Android being used
This issue only happens on Motorola Devices, especially in models Moto G (5), Moto G (5S), Moto G (5S) Plus, Moto G (5) Plus  
we also notice that it happens with less incidence in the models Samsung SM-J701MT, Samsung Galaxy J5. 

### A full bug report captured from the device
I sent the bug report and instructions on how to play our content to dev.exoplayer@gmail.com

**Comment by ojw28** [comment]
@paf-wv - Please take a look.

**Comment by brunoluizcs** [comment]
Guys, do you suggest some workaround for this problem ?

**Comment by rrfrias** [comment]
We are following up with the SoC to root cause the issue.

**Comment by ojw28** [comment]
@rrfrias - Did you hear back from the SoC? Thanks.

**Comment by rrfrias** [comment]
@brunoluizcs is it possible to share the modified apk with dev.exoplayer@gmail.com? We do not have one of the devices mentioned, and so will not be able to confirm that an exoplayer demo apk modified by us reproduces the problem before sharing it with the SoC.
