### ISSUE TITLE
HLS Streaming Format/Encoding/Errors

### ISSUE THREAD

**Issue by gte619n** [google/ExoPlayer#523]
I am writing an Android application that plays a large MP3 file over the web. These files are usually about an hour or so and I've been getting some really inconsistent behavior with the stream cutting off in the middle in some cases.

To fix this, I decided to move to ExoPlayer and utilize an HLS implementation. While I am able to play the Apple test files (the beep boop) without issue, I can't seem to get any of my own streams to work. I've used the Sample project as my base.

Whenever I try to access my own stream, the player errors out and I get the following stack trace:
```java
06-05 18:15:22.898  29566-29566/com.application E/EventLogger﹕ internalError [0.66, loadError]
    java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:73)
            at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:102)
            at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:214)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:110)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:242)
```

What is the correct way to create an HLS Stream for the ExoPlayer stuff? For testing, I have tried a number of ffmpeg exports and am using S3 to serve the files, but I have been unsuccessful. Is the error produced by incorrect headers or malformed files? Is the encoding I'm using just not supported?

One of the samples can be found here: https://s3.amazonaws.com/gte619n/test_stream/output_test.m3u8

Thank you for all your help and suggestions.

**Comment by ojw28** [comment]
Why don't you try using ExoPlayer to play your MP3 files directly? I can't think of any reason why HLS would be any better for this use case. Any benefit you get from moving to ExoPlayer is more likely to be from moving to ExoPlayer than from moving from one format to another.

To answer your question about HLS specifically, we currently only support AAC audio for the HLS case, and not MP3. We do support playing MP3 files directly, as noted above.

**Comment by gte619n** [comment]
Hello, thank you very much for your response. Initially, we attempted to use ExoPlayer to play the long MP3 files, but we are still receiving reports of the stream mysteriously stopping after about 30-40 minutes on some devices (Nexus 5 and Galaxy Note 3 in testing). 

I have been unable to duplicate the issue on my development environment or any of my devices, so I thought that trying HLS might fix the issue, especially if it was related to caching or releasing memory within the device itself. I would appreciate any ideas about testing or theories as to why this would happen, as I've been completely unable to duplicate, but the issue is widely reported enough (7-10% of users) that I believe something is amiss.

Thanks again!

**Comment by ojw28** [comment]
I'm not sure. Depending on the user scenarios, it doesn't seem completely implausible that that kind of percentage of users could be affected (e.g. If users typically consume from your application whilst they're moving around and connected to mobile networks rather than WiFi). You'd probably have to get some more detailed debug information to investigate further, unfortunately.

**Comment by gte619n** [comment]
ojw28,

Thanks again for your input. I've actually begun testing the HLS streams and it appears that the problem is solved. I don't know if there's some sort of memory issue with the Very Large (tm) MP3s or what, but the HLS handling seems to have solved it.

Thank you for your help!
