### ISSUE TITLE
Video can't play in some phone,use exoplayer 2.8.1

### ISSUE THREAD

**Issue by gejiashu** [google/ExoPlayer#5230]
```
2018-12-10 15:59:59.422 800-3549/? E/OMX-VDEC-1080P: Enable/Disable allocate-native-handle allowed only on input port!
2018-12-10 15:59:59.422 800-3549/? E/OMX-VDEC-1080P: set_parameter: Error: 0x80001019, setting param 0x7f00005b
2018-12-10 15:59:59.422 800-3549/? E/OMXNodeInstance: setParameter(0xe86cee84:qcom.decoder.mpeg4, OMX.google.android.index.allocateNativeHandle(0x7f00005b): Output:1 en=0) ERROR: UnsupportedSetting(0x80001019)
2018-12-10 15:59:59.422 800-3549/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
2018-12-10 15:59:59.436 800-1484/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
2018-12-10 15:59:59.436 800-1484/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.configureVideoTunnelMode not implemented
2018-12-10 15:59:59.436 800-1484/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.useAndroidNativeBuffer is supported
2018-12-10 15:59:59.437 800-3549/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.describeHDRStaticInfo not implemented
2018-12-10 15:59:59.440 800-800/? E/OMX-VDEC-1080P: Does not handle dataspace request
2018-12-10 15:59:59.440 800-800/? E/OMXNodeInstance: getConfig(0xe86cee84:qcom.decoder.mpeg4, ??(0x7f00005e)) ERROR: UnsupportedSetting(0x80001019)
2018-12-10 15:59:59.462 800-1484/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.AndroidNativeBufferConsumerUsage not implemented
2018-12-10 15:59:59.482 800-9813/? E/OMX-VDEC-1080P: OMX_COMPONENT_GENERATE_HARDWARE_ERROR
2018-12-10 15:59:59.482 800-9813/? E/OMX-VDEC-1080P: ERROR: Sending OMX_ErrorHardware to Client
2018-12-10 15:59:59.484 800-9812/? E/OMX-VDEC-1080P: Dropping message 13 since client expected to be in error state
2018-12-10 15:59:59.491 8892-9811/com.netease.easybuddy E/ACodec: [OMX.qcom.video.decoder.mpeg4] ERROR(0x80001009)
2018-12-10 15:59:59.491 8892-9811/com.netease.easybuddy E/ACodec: signalError(omxError 0x80001009, internalError -2147483648)
2018-12-10 15:59:59.491 8892-9810/com.netease.easybuddy E/MediaCodec: Codec reported err 0x80001009, actionCode 0, while in state 6
2018-12-10 15:59:59.500 800-1484/? E/OMXNodeInstance: setConfig(0xe96aa140:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
2018-12-10 15:59:59.500 800-1484/? E/OMXNodeInstance: getConfig(0xe96aa140:google.aac.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
2018-12-10 15:59:59.535 8892-9808/com.netease.easybuddy E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1024)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:573)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2018-12-10 15:59:59.552 8892-9811/com.netease.easybuddy E/Surface: getSlotFromBufferLocked: unknown buffer: 0xc86b3600
2018-12-10 15:59:59.553 8892-9811/com.netease.easybuddy E/Surface: getSlotFromBufferLocked: unknown buffer: 0xc86b3680
2018-12-10 15:59:59.553 8892-9811/com.netease.easybuddy E/Surface: getSlotFromBufferLocked: unknown buffer: 0xc86b3700
2018-12-10 15:59:59.554 8892-9811/com.netease.easybuddy E/Surface: getSlotFromBufferLocked: unknown buffer: 0xc86b3780
2018-12-10 15:59:59.566 8892-9808/com.netease.easybuddy E/ExoPlayerImplInternal: Stop failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2084)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:518)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:362)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:153)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:972)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:768)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:731)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:353)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by ojw28** [comment]
Please provide complete information as requested in the issue template. There is nothing we can do with the incomplete information provided here.

**Comment by gejiashu** [comment]
[bugreport-sailfish-PPR1.180610.009-2018-12-11-16-48-25.zip](https://github.com/google/ExoPlayer/files/2666743/bugreport-sailfish-PPR1.180610.009-2018-12-11-16-48-25.zip)
### Issue description

This video (video link: https://g.fp.ps.netease.com/easybuddy/file/5c0dec535e60275d6c8a4fe2Iw86iPiH) can't play on google pixle,But it can be played on the Android P simulator

### Reproduction steps

Play this video (https://g.fp.ps.netease.com/easybuddy/file/5c0dec535e60275d6c8a4fe2Iw86iPiH) using the ExoPlayer demo app.

### Link to test content

video link: https://g.fp.ps.netease.com/easybuddy/file/5c0dec535e60275d6c8a4fe2Iw86iPiH

### Version of ExoPlayer being used

exoplayer 2.8.1

### Device(s) and version(s) of Android being used

Device: google pixel 
Version: 9.0

**Comment by gejiashu** [comment]
@ojw28 The log information has been provided. Can you help me? Thank you.

**Comment by ojw28** [comment]
This line in the bug report indicates that the video stream exceeds what the device decoder for `video/mp4v-es` is capable of decoding:
```
[X] Track:0, id=1, mimeType=video/mp4v-es, res=992x2096, supported=NO_EXCEEDS_CAPABILITIES
```
So I'm afraid this is working as intended.

It's quite unusual for the video stream to be `video/mp4v-es` (as is the case here). It looks like Chrome on desktop doesn't support playback of the video part at all (it just plays the audio for me). On Android, I suspect most devices are far more capable decoding more popular stream types (e.g. `video/avc`, `video/x-vnd.on2.vp9`,  `video/hevc`) than `video/mp4v-es`. I'm not sure whether Android devices are even required to provide a decoder for `video/mp4v-es`.
