### ISSUE TITLE
88200 Hz is not a supported sample rate.

### ISSUE THREAD

**Issue by ArvinChu** [google/ExoPlayer#5248]
Using ExoPlayer-release-v2 on Android 4.4.2 , looks Exoplayer get failed:
```
12-12 17:03:17.525: I/MediaCodecList(9912): register mediacode *****************
12-12 17:03:17.525: I/OMXClient(9912): Using client-side OMX mux.
12-12 17:03:17.545: I/dalvikvm(9912): Could not find method android.media.MediaCodecInfo$VideoCapabilities.isSizeSupported, referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecInfo.areSizeAndRateSupportedV21
12-12 17:03:17.545: W/dalvikvm(9912): VFY: unable to resolve virtual method 721: Landroid/media/MediaCodecInfo$VideoCapabilities;.isSizeSupported (II)Z
12-12 17:03:17.545: D/dalvikvm(9912): VFY: replacing opcode 0x6e at 0x000c
12-12 17:03:17.545: I/dalvikvm(9912): Could not find method android.media.MediaCodecInfo$VideoCapabilities.areSizeAndRateSupported, referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecInfo.areSizeAndRateSupportedV21
12-12 17:03:17.555: W/dalvikvm(9912): VFY: unable to resolve virtual method 718: Landroid/media/MediaCodecInfo$VideoCapabilities;.areSizeAndRateSupported (IID)Z
12-12 17:03:17.555: D/dalvikvm(9912): VFY: replacing opcode 0x6e at 0x0011
12-12 17:03:17.555: I/dalvikvm(9912): Could not find method android.media.MediaCodecInfo$CodecCapabilities.getMaxSupportedInstances, referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecInfo.getMaxSupportedInstancesV23
12-12 17:03:17.555: W/dalvikvm(9912): VFY: unable to resolve virtual method 715: Landroid/media/MediaCodecInfo$CodecCapabilities;.getMaxSupportedInstances ()I
12-12 17:03:17.555: D/dalvikvm(9912): VFY: replacing opcode 0x6e at 0x0000
12-12 17:03:17.555: I/dalvikvm(9912): Could not find method android.media.MediaCodecInfo$CodecCapabilities.getVideoCapabilities, referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecInfo.alignVideoSizeV21
12-12 17:03:17.555: W/dalvikvm(9912): VFY: unable to resolve virtual method 716: Landroid/media/MediaCodecInfo$CodecCapabilities;.getVideoCapabilities ()Landroid/media/MediaCodecInfo$VideoCapabilities;
12-12 17:03:17.555: D/dalvikvm(9912): VFY: replacing opcode 0x6e at 0x000d
12-12 17:03:17.555: I/dalvikvm(9912): Could not find method android.media.MediaCodecInfo$CodecCapabilities.getAudioCapabilities, referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecInfo.isAudioChannelCountSupportedV21
12-12 17:03:17.555: W/dalvikvm(9912): VFY: unable to resolve virtual method 714: Landroid/media/MediaCodecInfo$CodecCapabilities;.getAudioCapabilities ()Landroid/media/MediaCodecInfo$AudioCapabilities;
12-12 17:03:17.555: D/dalvikvm(9912): VFY: replacing opcode 0x6e at 0x000d
12-12 17:03:17.555: I/dalvikvm(9912): Could not find method android.media.MediaCodecInfo$CodecCapabilities.getAudioCapabilities, referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecInfo.isAudioSampleRateSupportedV21
12-12 17:03:17.555: W/dalvikvm(9912): VFY: unable to resolve virtual method 714: Landroid/media/MediaCodecInfo$CodecCapabilities;.getAudioCapabilities ()Landroid/media/MediaCodecInfo$AudioCapabilities;
12-12 17:03:17.555: D/dalvikvm(9912): VFY: replacing opcode 0x6e at 0x000d
12-12 17:03:17.555: I/dalvikvm(9912): Could not find method android.media.MediaCodecInfo$CodecCapabilities.getVideoCapabilities, referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecInfo.isVideoSizeAndRateSupportedV21
12-12 17:03:17.555: W/dalvikvm(9912): VFY: unable to resolve virtual method 716: Landroid/media/MediaCodecInfo$CodecCapabilities;.getVideoCapabilities ()Landroid/media/MediaCodecInfo$VideoCapabilities;
12-12 17:03:17.555: D/dalvikvm(9912): VFY: replacing opcode 0x6e at 0x000d
12-12 17:03:17.565: I/OMXClient(9912): Using client-side OMX mux.
12-12 17:03:17.565: I/(9912): new RKOMXPlugin
12-12 17:03:17.575: I/OMXClient(9912): Using client-side OMX mux.
12-12 17:03:17.575: I/OMXClient(9912): Using client-side OMX mux.
12-12 17:03:17.575: D/EventLogger(9912): decoderEnabled [0.26, 0.00, window=0, period=0, video]
12-12 17:03:17.585: D/EventLogger(9912): decoderEnabled [0.26, 0.00, window=0, period=0, audio]
12-12 17:03:17.585: D/EventLogger(9912): tracksChanged [0.27, 0.00, window=0, period=0, 
12-12 17:03:17.585: D/EventLogger(9912):   Renderer:0 [
12-12 17:03:17.585: I/OMXClient(9912): Using client-side OMX mux.
12-12 17:03:17.585: D/EventLogger(9912):     Group:0, adaptive_supported=N/A [
12-12 17:03:17.585: D/EventLogger(9912):       [X] Track:0, id=1, mimeType=video/avc, res=1280x720, supported=YES
12-12 17:03:17.585: D/EventLogger(9912):     ]
12-12 17:03:17.585: D/EventLogger(9912):   ]
12-12 17:03:17.585: D/EventLogger(9912):   Renderer:1 [
12-12 17:03:17.585: D/EventLogger(9912):     Group:0, adaptive_supported=N/A [
12-12 17:03:17.585: D/EventLogger(9912):       [X] Track:0, id=2, mimeType=audio/mp4a-latm, channels=2, sample_rate=44100, language=und, supported=YES
12-12 17:03:17.595: D/EventLogger(9912):     ]
12-12 17:03:17.595: D/EventLogger(9912):     Metadata [
12-12 17:03:17.595: D/EventLogger(9912):       TSSE: value=Lavf56.25.101
12-12 17:03:17.595: E/ACodec(9912): [OMX.rk.video_decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
12-12 17:03:17.595: D/EventLogger(9912):     ]
12-12 17:03:17.595: W/ACodec(9912): [OMX.rk.video_decoder.avc] prepareForAdaptivePlayback failed w/ err -2147483648
12-12 17:03:17.595: D/EventLogger(9912):   ]
12-12 17:03:17.595: D/EventLogger(9912): ]
12-12 17:03:17.645: I/OMXClient(9912): Using client-side OMX mux.
12-12 17:03:17.645: I/(9912): new RKOMXPlugin
12-12 17:03:17.675: D/dalvikvm(9912): GC_FOR_ALLOC freed 211K, 8% free 3955K/4260K, paused 28ms, total 28ms
12-12 17:03:17.685: D/ACodec(9912): MEDIA_MIMETYPE_AUDIO_AAC sampleRate 44100 wifidisplay_flag 0 info 7363dd20
12-12 17:03:17.685: D/EventLogger(9912): timelineChanged [0.37, 0.00, window=0, period=0, periodCount=3, windowCount=3, reason=DYNAMIC
12-12 17:03:17.685: D/EventLogger(9912):   period [93.93]
12-12 17:03:17.685: D/EventLogger(9912):   period [?]
12-12 17:03:17.685: D/EventLogger(9912):   period [?]
12-12 17:03:17.685: D/EventLogger(9912):   window [93.93, true, false]
12-12 17:03:17.685: D/EventLogger(9912):   window [?, false, false]
12-12 17:03:17.685: D/EventLogger(9912):   window [?, false, false]
12-12 17:03:17.685: D/EventLogger(9912): ]
12-12 17:03:17.695: D/EventLogger(9912): mediaPeriodReadingStarted [0.37, 0.00, window=0, period=0]
12-12 17:03:17.695: D/EventLogger(9912): downstreamFormatChanged [0.38, 0.00, window=0, period=0, id=1, mimeType=video/avc, res=1280x720]
**12-12 17:03:17.725: I/SoftAAC2(9912): Reconfiguring decoder: 0->88200 Hz, 0->2 channels
12-12 17:03:17.745: E/android.media.AudioTrack(9912): getMinBufferSize(): 88200 Hz is not a supported sample rate.
12-12 17:03:17.745: E/ExoPlayerImplInternal(9912): Internal runtime error.
12-12 17:03:17.745: E/ExoPlayerImplInternal(9912): java.lang.IllegalStateException
12-12 17:03:17.745: E/ExoPlayerImplInternal(9912): 	at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:80)
12-12 17:03:17.745: E/ExoPlayerImplInternal(9912): 	at com.google.android.exoplayer2.audio.DefaultAudioSink.getDefaultBufferSize(DefaultAudioSink.java:482)
12-12 17:03:17.745: E/ExoPlayerImplInternal(9912): 	at com.google.android.exoplayer2.audio.DefaultAudioSink.configure(DefaultAudioSink.java:475)
12-12 17:03:17.745: E/ExoPlayerImplInternal(9912): 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onOutputFormatChanged(MediaCodecAudioRenderer.java:445)
12-12 17:03:17.745: E/ExoPlayerImplInternal(9912): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.processOutputFormat(MediaCodecRenderer.java:1395)
12-12 17:03:17.745: E/ExoPlayerImplInternal(9912): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1292)
12-12 17:03:17.745: E/ExoPlayerImplInternal(9912): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
12-12 17:03:17.745: E/ExoPlayerImplInternal(9912): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
12-12 17:03:17.745: E/ExoPlayerImplInternal(9912): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
12-12 17:03:17.745: E/ExoPlayerImplInternal(9912): 	at android.os.Handler.dispatchMessage(Handler.java:98)
12-12 17:03:17.745: E/ExoPlayerImplInternal(9912): 	at android.os.Looper.loop(Looper.java:136)
12-12 17:03:17.745: E/ExoPlayerImplInternal(9912): 	at android.os.HandlerThread.run(HandlerThread.java:61)**
12-12 17:03:17.765: D/dalvikvm(9912): GC_FOR_ALLOC freed 39K, 6% free 4286K/4532K, paused 15ms, total 16ms
12-12 17:03:17.765: D/EventLogger(9912): decoderInitialized [0.45, 0.00, window=0, period=0, video, OMX.rk.video_decoder.avc]
12-12 17:03:17.775: D/EventLogger(9912): decoderInputFormatChanged [0.45, 0.00, window=0, period=0, video, id=1, mimeType=video/avc, res=1280x720]
12-12 17:03:17.775: D/EventLogger(9912): downstreamFormatChanged [0.46, 0.00, window=0, period=0, id=2, mimeType=audio/mp4a-latm, channels=2, sample_rate=44100, language=und]
12-12 17:03:17.775: D/EventLogger(9912): decoderInitialized [0.46, 0.00, window=0, period=0, audio, OMX.google.aac.decoder]
12-12 17:03:17.775: D/EventLogger(9912): decoderInputFormatChanged [0.46, 0.00, window=0, period=0, audio, id=2, mimeType=audio/mp4a-latm, channels=2, sample_rate=44100, language=und]
12-12 17:03:17.775: D/EventLogger(9912): videoSizeChanged [0.46, 0.00, window=0, period=0, 1280, 720]
12-12 17:03:17.775: D/EventLogger(9912): renderedFirstFrame [0.46, 0.00, window=0, period=0, Surface(name=android.graphics.SurfaceTexture@423b5fe8)/@0x42356170]
12-12 17:03:17.775: D/EventLogger(9912): surfaceSizeChanged [0.46, 0.00, window=0, period=0, 1280, 720]
12-12 17:03:17.785: D/EventLogger(9912): state [0.47, 0.00, window=0, period=0, true, READY]
12-12 17:03:17.805: D/EventLogger(9912): decoderDisabled [0.49, 0.00, window=0, period=0, video]
12-12 17:03:17.805: D/EventLogger(9912): decoderDisabled [0.49, 0.00, window=0, period=0, audio]
12-12 17:03:17.805: D/EventLogger(9912): mediaPeriodReleased [0.49, 0.00, window=0, period=0]
12-12 17:03:17.805: E/EventLogger(9912): playerFailed [0.49, 0.00, window=0]
**12-12 17:03:17.805: E/EventLogger(9912): com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
12-12 17:03:17.805: E/EventLogger(9912): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:359)
12-12 17:03:17.805: E/EventLogger(9912): 	at android.os.Handler.dispatchMessage(Handler.java:98)
12-12 17:03:17.805: E/EventLogger(9912): 	at android.os.Looper.loop(Looper.java:136)
12-12 17:03:17.805: E/EventLogger(9912): 	at android.os.HandlerThread.run(HandlerThread.java:61)
12-12 17:03:17.805: E/EventLogger(9912): Caused by: java.lang.IllegalStateException
12-12 17:03:17.805: E/EventLogger(9912): 	at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:80)
12-12 17:03:17.805: E/EventLogger(9912): 	at com.google.android.exoplayer2.audio.DefaultAudioSink.getDefaultBufferSize(DefaultAudioSink.java:482)
12-12 17:03:17.805: E/EventLogger(9912): 	at com.google.android.exoplayer2.audio.DefaultAudioSink.configure(DefaultAudioSink.java:475)
12-12 17:03:17.805: E/EventLogger(9912): 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onOutputFormatChanged(MediaCodecAudioRenderer.java:445)
12-12 17:03:17.805: E/EventLogger(9912): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.processOutputFormat(MediaCodecRenderer.java:1395)
12-12 17:03:17.805: E/EventLogger(9912): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1292)
12-12 17:03:17.805: E/EventLogger(9912): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
12-12 17:03:17.805: E/EventLogger(9912): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
12-12 17:03:17.805: E/EventLogger(9912): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
12-12 17:03:17.805: E/EventLogger(9912): 	... 3 more**
12-12 17:03:17.805: D/EventLogger(9912): loading [0.49, 0.00, window=0, false]
12-12 17:03:17.805: D/EventLogger(9912): state [0.49, 0.00, window=0, true, IDLE]
```

**Comment by andrewlewis** [comment]
@ArvinChu Sorry for the delay. Please could you provide the media used to reproduce this, and also let us know the device/build (output by `adb shell getprop ro.build.fingerprint`)?
