### ISSUE TITLE
How can i play a list of tracks cached offline using exoplayer?

### ISSUE THREAD

**Issue by HardikChauhanSA** [google/ExoPlayer#5257]
Hello,

I got a question.
I am creating an android music player app.
My need is to download or cache, user selected tracks offline and play them through my app. I have successfully cached the songs in the phone's internal storage.

Now the issue I am facing is that I can play an only a single cached song. For example, If I have downloaded 5 songs and I try to play those songs offline only 1 can play and for others, I got an error like, 
`com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
`
We have used **SimpleCache** to cache songs and **HLSDataSource** for playing offline cache as a taken reference from the demo itself.

And also I want to play offline songs in sequence and in a loop.

Can you please help me with?
Thanks in advance.

**Comment by ojw28** [comment]
Please provide complete information about the error, as is requested in the issue template.

**Comment by hardikchauhan8** [comment]
Actually this was a question I want some guidance to achieve the same. But getting the above error. Can you please guide me?

**Comment by HardikChauhanSA** [comment]
Hello @ojw28 ,

Here is the full error log we are getting,

```
12-17 13:23:27.845 2556-2691/com.gtbank.habari.dev E/LoadTask: Unexpected exception loading stream
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.getContentMetadata(SimpleCache.java:355)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.getRedirectedUriOrDefault(CacheDataSource.java:509)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:286)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
12-17 13:23:27.858 2556-2669/com.gtbank.habari.dev E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:403)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.getContentMetadata(SimpleCache.java:355)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.getRedirectedUriOrDefault(CacheDataSource.java:509)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:286)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761)
```

Please check and let me know for anything we might missing or so.

**Comment by HardikChauhanSA** [comment]
Hello

Anyone can please check this and let me know??

**Comment by HardikChauhanSA** [comment]
Anyone to reply on this???

**Comment by ojw28** [comment]
It seems you're trying to make use of a `SimpleCache` that you've already called `release()` on. For future reference, it's pretty easy to answer this kind of thing just by [looking at the source code where the exception is thrown](https://github.com/google/ExoPlayer/blob/r2.9.3/library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/SimpleCache.java#L358), to see what assertion is failing ;).

So this is an issue with your application code. Normally you should have one `SimpleCache` instance that lives for the whole duration of your process, that you don't need to ever call `release()` on, just like in the [demo app](https://github.com/google/ExoPlayer/blob/r2.9.3/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoApplication.java#L103).
