### ISSUE TITLE
Launcher activity cannot start when Exoplayer version is switched from 2.8.4 to 2.9.2

### ISSUE THREAD

**Issue by tkbdragin** [google/ExoPlayer#5277]
### Issue description
I was using Exoplayer version 2.8.4 without any problems. I decided to change to 2.9.2.
The problem I have now is failure to start launcher activity (without any code changes, same code as was on 2.8.4).

The problem is FATAL EXCEPTION: main
...
`Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.constraint.ConstraintLayout" on path: DexPathList[[zip file "/data/app/com.example.alur.androidtv81-b3ibnunCTd_qpIieCATgUg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.alur.androidtv81-b3ibnunCTd_qpIieCATgUg==/lib/arm, /system/lib, /vendor/lib]]`

### Reproduction steps
Change version in gradle from 2.8.4 to 2.9.2

### Version of ExoPlayer being used
2.8.4 switching to 2.9.2

### Device(s) and version(s) of Android being used
Tested on two devices, one Mibox and some custom device (not branded yet), same issues.
Android version 8.0

```
2018-12-18 23:10:24.397 2389-2389/com.android.tv.settings W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:950 android.content.ContextWrapper.sendBroadcast:431 android.app.ActivityThread.performPauseActivityIfNeeded:3998 android.app.ActivityThread.performPauseActivity:3952 android.app.ActivityThread.performPauseActivity:3926 
2018-12-18 23:10:24.399 2168-2192/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.ActivityState.CHANGE flg=0x30 (has extras) } to com.hisilicon.android.hiRMService/.ActivityStateReceiver
2018-12-18 23:10:24.400 2644-2644/com.hisilicon.android.hiRMService I/HiRMService: ActivityStateReceiver currentProcess:com.android.tv.settings state:pause
2018-12-18 23:10:24.439 2667-2667/com.google.android.tvrecommendations D/NotifInteractonRcvr: Show unseen default level notification toasts
2018-12-18 23:10:24.444 2644-2644/com.hisilicon.android.hiRMService I/HiRMService: ActivityStateReceiver currentProcess:com.google.android.tvlauncher state:resume
2018-12-18 23:10:24.455 2168-9828/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.ActivityState.CHANGE flg=0x30 (has extras) } to com.hisilicon.android.hiRMService/.ActivityStateReceiver
2018-12-18 23:10:25.076 2168-9828/system_process D/WificondControl: Scan result ready event
2018-12-18 23:10:25.080 1990-2020/? I/AOService: hdmi_observer  change@/devices/virtual/xt_idletimer/timers
2018-12-18 23:10:25.089 2168-9828/system_process D/WifiPermissionsUtil: Denied: no location permission
2018-12-18 23:10:25.214 2168-2178/system_process I/zygote: Background concurrent copying GC freed 74840(3MB) AllocSpace objects, 9(180KB) LOS objects, 41% free, 8MB/14MB, paused 787us total 130.240ms
2018-12-18 23:10:25.652 10096-10096/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
2018-12-18 23:10:25.837 10102-10102/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
2018-12-18 23:10:25.867 10096-10096/? W/app_process: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
2018-12-18 23:10:25.920 10096-10096/? I/EthernetJNI: Loading ethernet jni class
2018-12-18 23:10:25.935 10096-10096/? D/AndroidRuntime: Calling main entry com.android.commands.wm.Wm
2018-12-18 23:10:25.938 10096-10096/? D/AndroidRuntime: Shutting down VM
2018-12-18 23:10:26.051 10102-10102/? W/app_process: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
2018-12-18 23:10:26.103 10102-10102/? I/EthernetJNI: Loading ethernet jni class
2018-12-18 23:10:26.118 10102-10102/? D/AndroidRuntime: Calling main entry com.android.commands.pm.Pm
2018-12-18 23:10:26.465 3358-3358/com.android.vending I/Finsky: [2] com.google.android.finsky.verifier.impl.PackageVerificationReceiver.onReceive(6): Verification requested, id = 27
2018-12-18 23:10:26.476 3358-10124/com.android.vending I/Finsky: [248] com.google.android.finsky.verifier.impl.dn.a(80): Skipping verification. Disabled by user setting
2018-12-18 23:10:26.476 3358-10124/com.android.vending I/Finsky: [248] com.google.android.finsky.verifier.impl.dn.a(43): Skipping anti malware verification due to pre-check failure
2018-12-18 23:10:26.477 3358-3358/com.android.vending I/Finsky: [2] com.google.android.finsky.verifier.impl.ff.c(157): Verifying id=27, result=1
2018-12-18 23:10:26.480 3358-3358/com.android.vending I/Finsky: [2] com.google.android.finsky.verifier.impl.ff.c(170): Verification complete: id=27, package_name=com.example.alur.androidtv81
2018-12-18 23:10:26.490 2168-2204/system_process I/PackageManager.DexOptimizer: Running dexopt (dexoptNeeded=1) on: /data/app/vmdl1573929986.tmp/base.apk pkg=com.example.alur.androidtv81 isa=arm dexoptFlags=boot_complete,debuggable,public target-filter=quicken oatDir=/data/app/vmdl1573929986.tmp/oat sharedLibraries=null
2018-12-18 23:10:26.540 10125-10125/? W/dex2oat: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
2018-12-18 23:10:26.542 10125-10125/? I/dex2oat: /system/bin/dex2oat --input-vdex-fd=-1 --output-vdex-fd=13 --compiler-filter=quicken --debuggable --classpath-dir=/data/app/vmdl1573929986.tmp
2018-12-18 23:10:27.162 1982-1982/? E/WifiHAL: radio: = 1
2018-12-18 23:10:27.162 1982-1982/? E/WifiHAL: on_time: = 10386823 ms
2018-12-18 23:10:27.162 1982-1982/? E/WifiHAL: tx_time: = 172432 ms
2018-12-18 23:10:27.162 1982-1982/? E/WifiHAL: num_tx_levels: = 1
2018-12-18 23:10:27.162 1982-1982/? E/WifiHAL: tx_time_per_levels: = 99 ms
2018-12-18 23:10:27.162 1982-1982/? E/WifiHAL: rx_time: = 10213911 ms
2018-12-18 23:10:27.162 1982-1982/? E/WifiHAL: on_time_scan: = 0 ms
2018-12-18 23:10:27.162 1982-1982/? E/WifiHAL: on_time_nbd: = 0 ms
2018-12-18 23:10:27.162 1982-1982/? E/WifiHAL: on_time_gscan: = 0 ms
2018-12-18 23:10:27.162 1982-1982/? E/WifiHAL: on_time_pno_scan: = 0 ms
2018-12-18 23:10:27.162 1982-1982/? E/WifiHAL: on_time_hs20: = 0 ms
2018-12-18 23:10:27.303 10125-10125/? E/dex2oat: Failed to open dex file from oat file. File: base.apk:classes2.dex Error: Failure to verify dex file 'base.apk:classes2.dex': Bad method handle type 7
2018-12-18 23:10:27.312 10125-10125/? I/dex2oat: dex2oat took 773.548ms (673.500ms cpu) (threads: 4) 
2018-12-18 23:10:27.320 2004-2027/? E/installed: DexInv: --- END '/data/app/vmdl1573929986.tmp/base.apk' --- status=0x0100, process failed
2018-12-18 23:10:27.320 2004-2027/? E/installd: Failed to dexopt (256)
2018-12-18 23:10:27.321 2168-2204/system_process W/PackageManager.DexOptimizer: Failed to dexopt
    com.android.server.pm.Installer$InstallerException: android.os.ServiceSpecificException: Failed to dexopt (code 256)
        at com.android.server.pm.Installer.dexopt(Installer.java:290)
        at com.android.server.pm.PackageDexOptimizer.dexOptPath(PackageDexOptimizer.java:220)
        at com.android.server.pm.PackageDexOptimizer.performDexOptLI(PackageDexOptimizer.java:175)
        at com.android.server.pm.PackageDexOptimizer.performDexOpt(PackageDexOptimizer.java:123)
        at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:18287)
        at com.android.server.pm.PackageManagerService.installPackageTracedLI(PackageManagerService.java:17882)
        at com.android.server.pm.PackageManagerService.-wrap33(Unknown Source:0)
        at com.android.server.pm.PackageManagerService$7.run(PackageManagerService.java:15353)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)
2018-12-18 23:10:27.324 2168-2192/system_process I/ActivityManager: Force stopping com.example.alur.androidtv81 appid=10061 user=-1: installPackageLI
2018-12-18 23:10:27.403 2168-2204/system_process I/PackageManager: Package com.example.alur.androidtv81 codePath changed from /data/app/com.example.alur.androidtv81-xRaAwYrnJFplA5Ggp1tGiw== to /data/app/com.example.alur.androidtv81-AD428lxNqNmYLU6a3h-kxw==; Retaining data and using new
2018-12-18 23:10:27.403 2168-2204/system_process W/PackageManager: Code path for com.example.alur.androidtv81 changing from /data/app/com.example.alur.androidtv81-xRaAwYrnJFplA5Ggp1tGiw== to /data/app/com.example.alur.androidtv81-AD428lxNqNmYLU6a3h-kxw==
2018-12-18 23:10:27.403 2168-2204/system_process W/PackageManager: Resource path for com.example.alur.androidtv81 changing from /data/app/com.example.alur.androidtv81-xRaAwYrnJFplA5Ggp1tGiw== to /data/app/com.example.alur.androidtv81-AD428lxNqNmYLU6a3h-kxw==
2018-12-18 23:10:27.726 2168-2204/system_process I/zygote: Explicit concurrent copying GC freed 46194(2MB) AllocSpace objects, 12(240KB) LOS objects, 42% free, 8MB/14MB, paused 343us total 173.439ms
2018-12-18 23:10:27.729 2004-2027/? E/installd: Failed to delete /data/app/vmdl1573929986.tmp: No such file or directory
2018-12-18 23:10:27.730 2168-2204/system_process I/ActivityManager: Force stopping com.example.alur.androidtv81 appid=10061 user=0: pkg removed
2018-12-18 23:10:27.731 10102-10102/? I/Pm: Package com.example.alur.androidtv81 installed in 1610 ms
2018-12-18 23:10:27.739 2282-2282/com.android.bluetooth D/Avrcp: AvrcpServiceBroadcastReceiver-> Action: android.intent.action.PACKAGE_REMOVED
2018-12-18 23:10:27.742 2667-2942/com.google.android.tvrecommendations D/PackageUpdatesReceiver: onReceive: android.intent.action.PACKAGE_REMOVED
2018-12-18 23:10:27.742 2667-2942/com.google.android.tvrecommendations D/PackageUpdatesReceiver: Unknown action android.intent.action.PACKAGE_REMOVED
2018-12-18 23:10:27.754 3358-3358/com.android.vending I/Finsky: [2] com.google.android.finsky.p2p.c.b(20): Frosting ID looked up on UI thread. Caller should move to a background thread.
2018-12-18 23:10:27.764 2282-2282/com.android.bluetooth D/Avrcp: AvrcpServiceBroadcastReceiver-> Action: android.intent.action.PACKAGE_ADDED
2018-12-18 23:10:27.764 2282-2282/com.android.bluetooth D/Avrcp: AvrcpServiceBroadcastReceiver-> packageName: com.example.alur.androidtv81
2018-12-18 23:10:27.764 2282-2282/com.android.bluetooth D/Avrcp: packageName: com.example.alur.androidtv81 removed: false
2018-12-18 23:10:27.765 2282-2282/com.android.bluetooth D/Avrcp: isBrowsableListUpdated: false
2018-12-18 23:10:27.767 2667-2942/com.google.android.tvrecommendations D/PackageUpdatesReceiver: onReceive: android.intent.action.PACKAGE_ADDED
2018-12-18 23:10:27.767 2667-2942/com.google.android.tvrecommendations D/TVNotifService.RecMgr: Skipped update channel for package: com.example.alur.androidtv81
2018-12-18 23:10:27.769 2667-2942/com.google.android.tvrecommendations D/PackageUpdatesReceiver: onReceive: android.intent.action.PACKAGE_REPLACED
2018-12-18 23:10:27.776 2667-2942/com.google.android.tvrecommendations D/TVNotifService.RecMgr: Skipped update channel for package: com.example.alur.androidtv81
2018-12-18 23:10:27.779 10102-10102/? I/app_process: System.exit called, status: 0
2018-12-18 23:10:27.780 10102-10102/? I/AndroidRuntime: VM exiting with result code 0.
2018-12-18 23:10:27.782 3358-3358/com.android.vending I/Finsky: [2] com.google.android.finsky.p2p.d.run(3): Wrote row to frosting DB: 224
2018-12-18 23:10:27.784 3358-4070/com.android.vending W/Finsky: [170] com.google.android.finsky.installqueue.impl.p.b(281): Cannot find install request for com.example.alur.androidtv81
2018-12-18 23:10:27.795 3358-3358/com.android.vending I/Finsky: [2] com.google.android.finsky.scheduler.bf.a(65): Jobs in database: 1-1337 12-1 
2018-12-18 23:10:27.796 2168-2240/system_process I/InputReader: Reconfiguring input devices.  changes=0x00000010
2018-12-18 23:10:27.797 2168-5304/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:com.example.alur.androidtv81 flg=0x4000010 (has extras) } to com.google.android.gms/.games.chimera.GamesSystemBroadcastReceiverProxy
2018-12-18 23:10:27.798 2168-2192/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:com.example.alur.androidtv81 flg=0x4000010 (has extras) } to com.google.android.gms/.photos.autobackup.PhotosAppUninstalledReceiver
2018-12-18 23:10:27.800 2168-2192/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:com.example.alur.androidtv81 flg=0x4000010 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2018-12-18 23:10:27.799 2168-2240/system_process I/chatty: uid=1000(system) InputReader identical 1 line
2018-12-18 23:10:27.802 2168-2240/system_process I/InputReader: Reconfiguring input devices.  changes=0x00000010
2018-12-18 23:10:27.802 3358-3358/com.android.vending I/Finsky: [2] com.google.android.finsky.scheduler.g.a(68): ConstraintMapping: 1-1337, 12-1,  -> L: 14969ms, D: 74173539ms, C: false, I: false, N: 1
2018-12-18 23:10:27.802 2168-2192/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:com.example.alur.androidtv81 flg=0x4000010 (has extras) } to com.google.android.tv/com.android.tv.receiver.PackageIntentsReceiver
2018-12-18 23:10:27.805 3358-3358/com.android.vending I/Finsky: [2] com.google.android.finsky.scheduler.JobSchedulerEngine.a(103): Cancelling existing job with id: 9001
2018-12-18 23:10:27.809 3358-3358/com.android.vending I/Finsky: [2] com.google.android.finsky.scheduler.JobSchedulerEngine.a(93): Scheduling job Id: 9000, L: 14969, D: 74173539, C: false, I: false, N: 1
2018-12-18 23:10:27.866 3358-3358/com.android.vending I/Finsky: [2] com.google.android.finsky.p2p.c.b(20): Frosting ID looked up on UI thread. Caller should move to a background thread.
2018-12-18 23:10:27.878 2168-5304/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.example.alur.androidtv81 flg=0x4000010 (has extras) } to com.google.android.gms/.games.chimera.GamesSystemBroadcastReceiverProxy
2018-12-18 23:10:27.878 3358-3358/com.android.vending I/Finsky: [2] com.google.android.finsky.p2p.d.run(3): Wrote row to frosting DB: 225
2018-12-18 23:10:27.879 2168-2192/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.example.alur.androidtv81 flg=0x4000010 (has extras) } to com.google.android.gms/.gass.chimera.PackageChangeBroadcastReceiver
2018-12-18 23:10:27.879 2168-2192/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.example.alur.androidtv81 flg=0x4000010 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2018-12-18 23:10:27.879 2168-2192/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.example.alur.androidtv81 flg=0x4000010 (has extras) } to com.google.android.tv/com.android.tv.receiver.PackageIntentsReceiver
2018-12-18 23:10:27.879 2168-2192/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.example.alur.androidtv81 flg=0x4000010 (has extras) } to com.google.android.gms/.gass.chimera.PackageChangeBroadcastReceiver
2018-12-18 23:10:27.880 2168-2192/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.example.alur.androidtv81 flg=0x4000010 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2018-12-18 23:10:28.003 2925-10136/com.google.android.gms I/Auth: [SupervisedAccountIntentOperation] onHandleIntent(): android.intent.action.PACKAGE_ADDED
2018-12-18 23:10:28.003 2925-10136/com.google.android.gms I/Auth: [SupervisedAccountIntentOperation] This operation is disabled
2018-12-18 23:10:28.007 2925-10136/com.google.android.gms I/ChromeSync: [Sync,SyncIntentOperation] Handling the intent: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.example.alur.androidtv81 flg=0x4000010 cmp=com.google.android.gms/.chimera.GmsIntentOperationService (has extras) }.
2018-12-18 23:10:28.054 2659-2698/com.google.android.tvlauncher I/zygote: Background concurrent copying GC freed 74430(1583KB) AllocSpace objects, 10(908KB) LOS objects, 49% free, 4MB/9MB, paused 403us total 321.566ms
2018-12-18 23:10:28.054 2925-10145/com.google.android.gms I/FontsPackageChangeOp: Package com.example.alur.androidtv81 has no metadata
2018-12-18 23:10:28.085 2168-2191/system_process W/Searchables: No web search activity found
2018-12-18 23:10:28.097 2168-2191/system_process W/Searchables: No web search activity found
2018-12-18 23:10:28.137 2925-3169/com.google.android.gms I/Icing: IndexChimeraService.getServiceInterface callingPackage=com.google.android.gms componentName=AppsCorpus serviceId=36
2018-12-18 23:10:28.149 2925-4288/com.google.android.gms I/Icing: IndexChimeraService.getServiceInterface callingPackage=com.google.android.gms componentName=AppsCorpus serviceId=32
2018-12-18 23:10:28.186 2168-6299/system_process I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.example.alur.androidtv81/.SplashScreen} from uid 0
2018-12-18 23:10:28.195 1980-1980/? E/IPower: Unknown power hint 8
2018-12-18 23:10:28.203 2925-2938/com.google.android.gms I/zygote: Background concurrent copying GC freed 79231(4MB) AllocSpace objects, 30(540KB) LOS objects, 41% free, 8MB/14MB, paused 358us total 457.179ms
2018-12-18 23:10:28.215 2168-2192/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.ActivityState.CHANGE flg=0x30 (has extras) } to com.hisilicon.android.hiRMService/.ActivityStateReceiver
2018-12-18 23:10:28.216 2644-2644/com.hisilicon.android.hiRMService I/HiRMService: ActivityStateReceiver currentProcess:com.google.android.tvlauncher state:pause
2018-12-18 23:10:28.236 1978-1978/? E/Gralloc1Allocator: Hisilicon: Allocator1 alloc 2867483184
2018-12-18 23:10:28.242 2168-2179/system_process I/ActivityManager: Start proc 10159:com.example.alur.androidtv81/u0a61 for activity com.example.alur.androidtv81/.SplashScreen
2018-12-18 23:10:28.258 2925-10051/com.google.android.gms I/Icing: Usage reports ok 1, Failed Usage reports 0, indexed 0, rejected 0, imm upload false
2018-12-18 23:10:28.267 10159-10159/? I/zygote: Late-enabling -Xcheck:jni
2018-12-18 23:10:28.281 2925-10051/com.google.android.gms I/Icing: Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0, imm upload false
2018-12-18 23:10:28.322 2925-3169/com.google.android.gms I/Icing: IndexChimeraService.getServiceInterface callingPackage=com.google.android.gms componentName=AppsCorpus serviceId=36
2018-12-18 23:10:28.325 2925-4288/com.google.android.gms I/Icing: IndexChimeraService.getServiceInterface callingPackage=com.google.android.gms componentName=AppsCorpus serviceId=32
2018-12-18 23:10:28.331 10159-10159/? W/zygote: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
2018-12-18 23:10:28.347 2925-10051/com.google.android.gms I/Icing: Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0, imm upload false
2018-12-18 23:10:28.364 2925-10051/com.google.android.gms I/Icing: Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0, imm upload false
2018-12-18 23:10:28.375 2013-2013/? I/android_ir_user: type=1400 audit(0.0:572): avc: denied { ioctl } for path="/dev/hi_gpio" dev="tmpfs" ino=7635 ioctlcmd=0x580a scontext=u:r:android_ir_user:s0 tcontext=u:object_r:hi_gpio_device:s0 tclass=chr_file permissive=1
2018-12-18 23:10:28.889 10159-10159/com.example.alur.androidtv81 W/zygote: Zip open failed: Failure to verify dex file '/data/app/com.example.alur.androidtv81-AD428lxNqNmYLU6a3h-kxw==/base.apk:classes2.dex': Bad method handle type 7
2018-12-18 23:10:28.978 10159-10159/com.example.alur.androidtv81 D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2018-12-18 23:10:28.992 10159-10159/com.example.alur.androidtv81 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.alur.androidtv81, PID: 10159
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.alur.androidtv81/com.example.alur.androidtv81.SplashScreen}: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class android.support.constraint.ConstraintLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6561)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class android.support.constraint.ConstraintLayout
     Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.constraint.ConstraintLayout
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.constraint.ConstraintLayout" on path: DexPathList[[zip file "/data/app/com.example.alur.androidtv81-AD428lxNqNmYLU6a3h-kxw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.alur.androidtv81-AD428lxNqNmYLU6a3h-kxw==/lib/arm, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:606)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:418)
        at android.app.Activity.setContentView(Activity.java:2654)
        at com.example.alur.androidtv81.SplashScreen.onCreate(SplashScreen.java:13)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6561)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
2018-12-18 23:10:29.008 2168-2408/system_process W/ActivityManager:   Force finishing activity com.example.alur.androidtv81/.SplashScreen
```

Layout file:
```
<?xml version="1.0" encoding="utf-8"?>
    <android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white"
        tools:context=".SplashScreen">

        <ImageView
            android:id="@+id/imageView"
            android:layout_width="wrap_content"
            android:layout_height="273dp"
            android:adjustViewBounds="false"
            android:cropToPadding="false"
            android:scaleType="fitCenter"
            android:src="@drawable/logo"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
    </android.support.constraint.ConstraintLayout>
```

I have completely no idea what is causing this (well, for me this kind of problem showing when switching version of Exoplayer is really missleading, I don't even know where to search)

**Comment by ojw28** [comment]
I don't think this is an ExoPlayer issue. It seems you're using `ConstraintLayout` in your own layout file, but the class cannot be found at runtime. A few suggestions:

* Try "File -> Invalidate Caches / Restart" in Android Studio.
* Check your `build.gradle` to make sure your dependency on `constraint-layout` looks right. It should look something like `implementation 'com.android.support.constraint:constraint-layout:1.1.2'` as per [this page](https://developer.android.com/training/constraint-layout/).

**Comment by tkbdragin** [comment]
I have already tried invalidating caches - didn't help.
When I change Exoplayer version in gradle, nothing else changes thus constraint-layout should be (and is) present all the time.

**Comment by ojw28** [comment]
I'm not sure, in that case. I still don't think this is an ExoPlayer issue. We've not had any other reports of this problem either, which very much suggest that it's something specific to your app or development setup. I don't think there's anything we can really do to help, unless you're able to provide us with complete reproduction steps.

**Comment by droidwave** [comment]
The complete tutorials ExoPlayer
https://androidwave.com/video-streaming-exoplayer-in-android/

**Comment by ojw28** [comment]
@droidwave - Please refrain from spamming our issue tracker with unrelated content. Thanks.

**Comment by AllanWang** [comment]
I appear to be having this error as well:

```
2018-12-18 23:10:27.754 3358-3358/com.android.vending I/Finsky: [2] com.google.android.finsky.p2p.c.b(20): Frosting ID looked up on UI thread. Caller should move to a background thread.
```

However, the media player is working fine. I've migrated my project to androidx, and it has constraintlayout.

If you did an androidx migration as well, note that a lot of the xml tags don't end up being changed automatically

**Comment by ojw28** [comment]
Looking at this again, I think you need to enable Java 8 features in your `build.gradle` file, as per our [developer guide](https://google.github.io/ExoPlayer/guide.html#adding-exoplayer-as-a-dependency). This is a requirement as of 2.9.0, so is consistent with you seeing the problem after upgrading.

**Comment by ojw28** [comment]
Example: https://github.com/google/ExoPlayer/blob/r2.9.3/demos/main/build.gradle#L23
