### ISSUE TITLE
ExoPlaybackException, codec init failure

### ISSUE THREAD

**Issue by sssprog** [google/ExoPlayer#5312]
### Issue description
ExoPlaybackException. Issue happens on Huawei P10 lite with android 8.0. Device name HWWAS-H. Model name WAS-LX1. Code name passed to `codecNeedsSetOutputSurfaceWorkaround` is OMX.IMG.MSVDX.Decoder.AVC

When we return `true` in `codecNeedsSetOutputSurfaceWorkaround` for this device no exception happens.

I guess this device needs the workaround.

### Reproduction steps
We have `SimpleExoPlayer` and `PlayerView` in an activity. On first activity launch video is played normally. If activity is paused, than resumed we get exception. In `onPause` we release player and in `onResume` create new instance of `SimpleExoPlayer`.

### Link to test content
We tested on real project, don't have test project.

### Version of ExoPlayer being used
2.9.2

### Device(s) and version(s) of Android being used
Huawei P10 lite with android 8.0.

### A full bug report captured from the device
```
com.google.android.exoplayer2.ExoPlaybackException
   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:354)
   at android.os.Handler.dispatchMessage(Handler.java:104)
   at android.os.Looper.loop(Looper.java:166)
   at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: java.lang.IllegalArgumentException
   at android.media.MediaCodec.native_setSurface(Native Method)
   at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1967)
   at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(SourceFile:918)
   at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(SourceFile:408)
   at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(SourceFile:375)
   at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(SourceFile:861)
   at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(SourceFile:829)
   at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(SourceFile:811)
   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:328)
   at android.os.Handler.dispatchMessage(Handler.java:104) 
   at android.os.Looper.loop(Looper.java:166) 
   at android.os.HandlerThread.run(HandlerThread.java:65) 
```

**Comment by AquilesCanta** [comment]
Please provide a full bugreport. You can obtain it by running `adb bugreport` after reproducing the issue. Thanks!

**Comment by tonihei** [comment]
Thanks for reporting. We'll add the device to the workaround list soon.
