### ISSUE TITLE
Hls adaptive streaming not working for audio only

### ISSUE THREAD

**Issue by dmytro-ostapovets** [google/ExoPlayer#5313]
### Issue description
Hls adaptive streaming not working with our Audio tracks (Hls file doesn't contain Video track)
We tested Exoplayer demo app, just replaced Hls source by our link.
Player always selects default stream with BANDWIDTH=140800, and never switches to BANDWIDTH=281600, tested on wifi connection.

### Reproduction steps
Just replace HlsSource link in demo app:
`      case C.TYPE_HLS:
        return new HlsMediaSource.Factory(dataSourceFactory)
//            .setPlaylistParserFactory(
//                new DefaultHlsPlaylistParserFactory(getOfflineStreamKeys(uri)))
            .createMediaSource(Uri.parse("our hls url here"));
`

### Link to test content
Link will be provided by email

### Version of ExoPlayer being used
Exoplayer 2.9.3, branch release-v2

### Device(s) and version(s) of Android being used
Google Pixel, Android 9.0

### A full bug report captured from the device
Bug report will be provided by email

**Comment by ojw28** [comment]
We come up with a pretty weird set of tracks for this content (looking at the master playlist, I think the correct result would be if we ended up with just Group 0):
```
EventLogger:   Renderer:1 [
EventLogger:     Group:0, adaptive_supported=YES_NOT_SEAMLESS [
EventLogger:       [ ] Track:0, id=0, mimeType=audio/mp4a-latm, bitrate=140800, codecs=mp4a.40.2, channels=2, sample_rate=44100, supported=YES
EventLogger:       [ ] Track:1, id=1, mimeType=audio/mp4a-latm, bitrate=281600, codecs=mp4a.40.2, channels=2, sample_rate=44100, supported=YES
EventLogger:     ]
EventLogger:     Group:1, adaptive_supported=N/A [
EventLogger:       [X] Track:0, id=group_128k:audio_0, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=44100, label=audio_0, supported=YES
EventLogger:     ]
EventLogger:     Group:2, adaptive_supported=N/A [
EventLogger:       [ ] Track:0, id=group_256k:audio_0, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=44100, label=audio_0, supported=YES
EventLogger:     ]
EventLogger:   ]
```

**Comment by ojw28** [comment]
Reopening this because the issue will be reintroduced in 2.10 (the original fix caused another issue that was worse than the one that it fixed).

**Comment by jakoss** [comment]
I think i have similar issue with strange set of tracks for my content here: https://github.com/google/ExoPlayer/issues/6006

Not sure if the issue have the same cause

**Comment by jofth** [comment]
Is #5313 still an open bug in release 2.10.3?

**Comment by AquilesCanta** [comment]
@jofth, the answer is yes.

For internal reference, IIRC [Internal ref: cr/252046149] fixes this issue and #6006.

**Comment by jofth** [comment]
Thanks @AquilesCanta - as we currently use audio only HLS adaptive streaming is there a planned release that will resolve this, and until then a suggested work around?

@AquilesCanta Our team's observation is that when using an HLS adaptive playlist that is audio only, if the default stream fails (404s for example) then ExoPlayer does not try the next stream in the playlist.

**Comment by verinder84** [comment]
**m3u8 audio streaming not working**
it working with exoplayer: r2.4.1' 
but not working after ugrading to exoplayer 2.11.4

```
 DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(context,userAgent);
  HlsMediaSource mediaSource = new  HlsMediaSource.Factory(dataSourceFactory).createMediaSource(uri); 
  player.prepare(mediaSource, true, false);
```
steaming uri is  http://airodiya-lh.akamaihd.net/i/airodiya_1@528056/master.m3u8

```
/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1090)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:969)
```

**Comment by palvaibhav89** [comment]
Hi i am getting Same issue. [
<img width="865" alt="Screenshot 2020-11-11 at 1 17 40 PM" src="https://user-images.githubusercontent.com/20883663/98896492-0ffcfb80-24cf-11eb-8a48-b1ba96c53183.png">
](url)

@ojw28 PLease give us a solution. @jofth is their any solution you got?
Currently i am using 2.12.1 version.

**Comment by jofth** [comment]
@palvaibhav89 nope, our solution was to stop using hls for audio only streams and use streaming mp3 instead.

**Comment by palvaibhav89** [comment]
@ojw28 is this issue still open? Is there any fix for this on the way?

**Comment by palvaibhav89** [comment]
@AquilesCanta Is there any hope to get this fixed?

**Comment by AquilesCanta** [comment]
Christos, from my comment above:

> For internal reference, IIRC [Internal ref: cr/252046149] fixes this issue and https://github.com/google/ExoPlayer/issues/6006.

**Comment by palvaibhav89** [comment]
@christosts Hi, Do you need any info or data?

**Comment by kmrinmoy07** [comment]
We are still facing this issue in 2023
