### ISSUE TITLE
Decoder mp3 failed with Error 0x80001001

### ISSUE THREAD

**Issue by ghost0906** [google/ExoPlayer#5314]
### Issue description
Use exoplayer play a video with audio format "mp3". The error logsas belows:

```
01-02 09:48:14.580 V/ACodec  (13293): omx_message::EVENT 0 0 2
01-02 09:48:14.580 D/EventLogger(13293): audioDecoderInitialized [0.16, OMX.google.mp3.decoder]
01-02 09:48:14.580 V/ACodec  (13293): [OMX.google.mp3.decoder] Now Idle->Executing
01-02 09:48:14.580 V/ACodec  (13293): omx_message::EVENT 0 0 3
01-02 09:48:14.580 V/ACodec  (13293): ExecutingState::resume
01-02 09:48:14.580 V/ACodec  (13293): submitRegularOutputBuffers
01-02 09:48:14.580 V/ACodec  (13293): submitRegularOutputBuffers [OMX.google.mp3.decoder] calling fillBuffer 0xab968160
01-02 09:48:14.580 V/ACodec  (13293): submitRegularOutputBuffers [OMX.google.mp3.decoder] calling fillBuffer 0xaba316f0
01-02 09:48:14.580 V/ACodec  (13293): submitRegularOutputBuffers [OMX.google.mp3.decoder] calling fillBuffer 0xabc655f0
01-02 09:48:14.580 D/EventLogger(13293): audioFormatChanged [0.16, id=2, mimeType=audio/mpeg, channels=3, sample_rate=44100]
01-02 09:48:14.580 V/ACodec  (13293): submitRegularOutputBuffers [OMX.google.mp3.decoder] calling fillBuffer 0xaba313a0
01-02 09:48:14.580 V/ACodec  (13293): Post the first input buffer
01-02 09:48:14.580 V/ACodec  (13293): [OMX.google.mp3.decoder] Now Executing
01-02 09:48:14.580 E/SoftMP3 (13293): mp3 decoder returned error 1
01-02 09:48:14.580 V/ACodec  (13293): omx_message::EVENT 1 -2147479551 1
01-02 09:48:14.580 E/ACodec  (13293): [OMX.google.mp3.decoder] ERROR(0x80001001)
01-02 09:48:14.580 E/MediaCodec(13293): Codec reported an error. (omx error 0x80001001, internalError -2147483648)
01-02 09:48:14.590 W/Kernel  ( 2507): <4>[ 6498.876426] vde: dev opened
01-02 09:48:14.590 D/Kernel  ( 2507): <6>[ 6498.876464] normal poweron vde_domain 
01-02 09:48:14.590 W/Kernel  ( 2507): <4>[ 6498.876501] vde: the get value rate is different of set, ret is 528000000
01-02 09:48:14.590 D/Kernel  ( 2507): <6>[ 6498.876506] vde: vde_runtime_resume!
01-02 09:48:14.590 E/ExoPlayerImplInternal(13293): Internal runtime error.
01-02 09:48:14.590 E/ExoPlayerImplInternal(13293): java.lang.IllegalStateException
01-02 09:48:14.590 E/ExoPlayerImplInternal(13293): 	at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
01-02 09:48:14.590 E/ExoPlayerImplInternal(13293): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:942)
01-02 09:48:14.590 E/ExoPlayerImplInternal(13293): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:552)
01-02 09:48:14.590 E/ExoPlayerImplInternal(13293): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:582)
01-02 09:48:14.590 E/ExoPlayerImplInternal(13293): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:323)
01-02 09:48:14.590 E/ExoPlayerImplInternal(13293): 	at android.os.Handler.dispatchMessage(Handler.java:98)
01-02 09:48:14.590 E/ExoPlayerImplInternal(13293): 	at android.os.Looper.loop(Looper.java:136)
01-02 09:48:14.590 E/ExoPlayerImplInternal(13293): 	at android.os.HandlerThread.run(HandlerThread.java:61)
01-02 09:48:14.590 D/ExoPlayerImplInternal(13293):  L[886] [Dash_ExoPlayer] [disableRenderer]     czz disableRenderer
01-02 09:48:14.590 V/MediaCodec(13293): stop
01-02 09:48:14.590 V/MediaCodec(13293): Stop /Release
```

### Reproduction steps
Just play the video.

### Version of ExoPlayer being used
Ver. 2.6.0
### Device(s) and version(s) of Android being used
Android ver: 4.4.2

### A full bug report captured from the device
[testav02.log](https://github.com/google/ExoPlayer/files/2709381/testav02.log)

**Comment by AquilesCanta** [comment]
Please provide the missing items (sample media and full bugreport, as obtained from `adb bugreport` after reproducing the issue) and we will reopen.

**Comment by ojw28** [comment]
We'd also need sample content and proper details about the device. Please fully complete the issue template whenever filing issues.
