### ISSUE TITLE
When i add dependecies get an error

### ISSUE THREAD

**Issue by khahani** [google/ExoPlayer#5315]
This is my build.gradle file:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.khahani.app.audioandvideosample"
        minSdkVersion 26
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'com.google.android.exoplayer:exoplayer-core:2.9.3'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.9.3'
}
```

And this is the error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.khahani.app.audioandvideosample, PID: 11951
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.khahani.app.audioandvideosample/com.khahani.app.audioandvideosample.SurfaceViewVideoViewActivity}: java.lang.ClassNotFoundException: Didn't find class "com.khahani.app.audioandvideosample.SurfaceViewVideoViewActivity" on path: DexPathList[[zip file "/data/app/com.khahani.app.audioandvideosample-_Poy_twPj1eK6wroFWOedw==/base.apk"],nativeLibraryDirectories=[/data/app/com.khahani.app.audioandvideosample-_Poy_twPj1eK6wroFWOedw==/lib/x86, /system/lib, /system/vendor/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2718)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6540)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.khahani.app.audioandvideosample.SurfaceViewVideoViewActivity" on path: DexPathList[[zip file "/data/app/com.khahani.app.audioandvideosample-_Poy_twPj1eK6wroFWOedw==/base.apk"],nativeLibraryDirectories=[/data/app/com.khahani.app.audioandvideosample-_Poy_twPj1eK6wroFWOedw==/lib/x86, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1173)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6540) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.khahani.app.audioandvideosample-_Poy_twPj1eK6wroFWOedw==/base.apk because: Failure to verify dex file '/data/app/com.khahani.app.audioandvideosample-_Poy_twPj1eK6wroFWOedw==/base.apk': Bad method handle type 7
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:653)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:686)
        at android.app.LoadedApk.getResources(LoadedApk.java:913)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2226)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5671)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
```

When i remove ExoPlayer dependencies it's perfectly work.

Help please.

**Comment by ojw28** [comment]
You probably need to enable Java 8 features by adding the following inside the `android { ... }` section of your `build.gradle` file:
```
compileOptions {
    targetCompatibility JavaVersion.VERSION_1_8
}
```
The need to do this is documented in our [developer guide](https://google.github.io/ExoPlayer/guide.html).

Closing this on the assumption that the above will fix your issue, but if it doesn't please feel free to respond here and we'll take another look. Thanks!
