### ISSUE TITLE
Unable to play m3u8 Video and Ads

### ISSUE THREAD

**Issue by Maneesh528** [google/ExoPlayer#5346]
I am using Exoplayer 2.7.3.

I able to play the m3u8 video with  
HlsMediaSource.Factory(dataSourceFactory).createMediaSource("My URL");

How can I play ads with in this? If it is not a good approach please help me with the better approach.

**Comment by tonihei** [comment]
The provided information is not enough for us to help you with this issue. 
Please add all the information requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE), including example media, reproduction steps, device information and bugreports.

**Comment by Maneesh528** [comment]
Thanks for your response, I am using below code to play m3u8 format url and Ads, can you please have a look and confirm me where I am going wrong

AdsMediaSource adsMediaSource = new AdsMediaSource(
                    buildMediaSource(Uri.parse(getString(R.string.media_url_m3u8))),
                    manifestDataSourceFactory,
                    imaAdsLoader,
                    playerView.getOverlayFrameLayout(),
                    null, null
            );
player.prepare(adsMediaSource);

But I am facing this Issue: 

com.google.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT #EXTM3U
    
    #EXT-X-...@32:1 in java.io.InputStreamReader@19bc0b4) 
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:105)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:58)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:130)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
     Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT #EXTM3U
    
    #EXT-X-...@32:1 in java.io.InputStreamReader@19bc0b4) 
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:432)
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:98)

**Comment by Maneesh528** [comment]
Thanks for your response, I am using below code to play m3u8 format url and
Ads, can you please have a look and confirm me where I am going wrong

AdsMediaSource adsMediaSource = new AdsMediaSource(
buildMediaSource(Uri.parse(getString(R.string.media_url_m3u8))),
manifestDataSourceFactory,
imaAdsLoader,
playerView.getOverlayFrameLayout(),
null, null
);
player.prepare(adsMediaSource);

But I am facing this Issue:

com.google.android.exoplayer2.ParserException:
org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT
#EXTM3U

#EXT-X-...@32:1 in java.io.InputStreamReader@19bc0b4)
    at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:105)
    at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:58)
    at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:130)
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:776)
 Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token
(position:TEXT #EXTM3U

#EXT-X-...@32:1 in java.io.InputStreamReader@19bc0b4)
    at org.kxml2.io.KXmlParser.next(KXmlParser.java:432)
    at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
    at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:98)

**Comment by tonihei** [comment]
As you may be able to see from the stack trace, you use a DashMediaSource to play the HLS m3u8 playlist. Please use a HLSMediaSource instead.

**Comment by Maneesh528** [comment]
I have used:

MediaSource videoSource = new
HlsMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(getString(R.string.media_url_m3u8)));


But I not getting how to include ads in to it, Can you please help me
to solve this problem?

**Comment by tonihei** [comment]
Whatever you did in `buildMediaSource` is not building a HlsMediaSource but a DashMediaSource.

**Comment by Maneesh528** [comment]
What method will help me to play m3u8 and Ads ? It helps me a lot if you share the sample code

**Comment by Maneesh528** [comment]
What method will help me to play m3u8 and Ads ? It helps me a lot if you
share the sample code.

**Comment by tonihei** [comment]
You already posted the correct code above. Create a new `AdsMediaSource` and provide a `HlsMediaSource` as first argument. 

Generally, we don't have the time to debug your app code and it would be great if you can look through the developer guide and read the class docs first to find out what to do.

**Comment by Maneesh528** [comment]
It's working great, Thanks for your help.

**Comment by Maneesh528** [comment]
This Code works great to play HLS Video and Ads


MediaSource mediaSourceWithAds =
                    new AdsMediaSource(
                            new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(getString(R.string.yupp_video))),
                            manifestDataSourceFactory,
                            imaAdsLoader,
                            playerView.getOverlayFrameLayout());
