### ISSUE TITLE
Cannot open flv rtmp streams

### ISSUE THREAD

**Issue by kaiv2000** [google/ExoPlayer#5364]
Exoplayer cannot open some rtmp streams:
for example: rtmp://online.sokal.lviv.ua/rtplive/cam27-1-1.stream

```
E/LoadTask: Unexpected exception loading stream
            java.lang.IllegalArgumentException
                at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
                at com.google.android.exoplayer2.util.ParsableByteArray.setPosition(ParsableByteArray.java:155)
                at com.google.android.exoplayer2.util.ParsableByteArray.skipBytes(ParsableByteArray.java:167)
                at com.google.android.exoplayer2.video.AvcConfig.buildNalUnitForChild(AvcConfig.java:93)
                at com.google.android.exoplayer2.video.AvcConfig.parse(AvcConfig.java:60)
                at com.google.android.exoplayer2.extractor.flv.VideoTagPayloadReader.parsePayload(VideoTagPayloadReader.java:89)
                at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:65)
                at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:261)
                at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:163)
                at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:898)
                at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                at java.lang.Thread.run(Thread.java:764)
```

**Comment by ojw28** [comment]
The stream works fine for me using `2.9.3`. Closing based on this, and because you haven't filled in the issue template with the information we'd need to investigate further.
