### ISSUE TITLE
Player Crash in 2.9.1

### ISSUE THREAD

**Issue by HiteshDevganiya** [google/ExoPlayer#5366]
I have used version 2.9.0. Its working fine without having issue. After updated to 2.9.1 getting below crash with player.

Android OS : 9.0.0
Exo player version : 2.9.1 

`FATAL EXCEPTION: ExoPlayerHandlerThread
    Process: xxx.xxx.dev, PID: 16508
    java.lang.NoSuchFieldError: No field periodIndex of type I in class Lcom/google/android/exoplayer2/source/MediaSource$MediaPeriodId; or its superclasses (declaration of 'com.google.android.exoplayer2.source.MediaSource$MediaPeriodId' appears in /data/app/xxx.xxx.dev-yjAwVJPbRNtpPwWZ1UEPFQ==/split_lib_dependencies_apk.apk)
        at tv.ustream.player.android.internal.mediaplayer.exo.ExoLoggingUtil.logMediaPeriodId(SourceFile:27)
        at tv.ustream.player.android.internal.mediaplayer.exo.AndroidExoMediaPlayer.onMediaPeriodCreated(SourceFile:540)
        at com.google.android.exoplayer2.source.MediaSourceEventListener$EventDispatcher.lambda$mediaPeriodCreated$0(MediaSourceEventListener.java:371)
        at com.google.android.exoplayer2.source.-$$Lambda$MediaSourceEventListener$EventDispatcher$N-EOPAK5UK0--YMNjezq7UM3UNI.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:898)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by andrewlewis** [comment]
See d51b98dd1f6290504b4be9d86d71e70ebe217513. Looks like you need to update `ExoLoggingUtil` to take into account that API change.
