### ISSUE TITLE
Sending non-protected broadcast com.google.android.exoplayer.stop throwable exception?

### ISSUE THREAD

**Issue by v1sd3v** [google/ExoPlayer#5386]
When I try to stop the audio playback from the notification control I get a Throwable exception. 

Stacktrace: 

```
E/ActivityManager: Sending non-protected broadcast com.google.android.exoplayer.stop from system 4132:com.android.systemui/u0a5 pkg com.example.example
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:21257)
        at com.android.server.am.ActivityManagerService.broadcastIntentInPackage(ActivityManagerService.java:21890)
        at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:357)
        at com.android.server.am.ActivityManagerService.startActivityIntentSender(ActivityManagerService.java:5900)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:298)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3538)
        at android.os.Binder.execTransact(Binder.java:573)
```

**Comment by marcbaechinger** [comment]
Thanks for reporting. 

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

I'm sending this stop intent all the time and haven't seen that issue, so I guess I need some further info to be able to reproduce this. Specifically what OS, Android version and the like. Best to just go along the issue template.

many thanks!

**Comment by v1sd3v** [comment]
I think It had to do with the way I was calling `stopSelf()` in a bounded service without first unbinding that service.
