### ISSUE TITLE
com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError

### ISSUE THREAD

**Issue by jqacn3000** [google/ExoPlayer#5396]
My app crashes after 3 hours of playing Live in Exoplayer (v. r2.9.0)
this is the log:

2019-01-16 08:48:53.755 5318-5545/com.xxx.app E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 65552 byte allocation with 2792 free bytes and 2792B until OOM, max allowed footprint 402653184, growth limit 402653184
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 2792 free bytes and 2792B until OOM, max allowed footprint 402653184, growth limit 402653184
        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
        at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:626)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:546)
        at com.google.android.exoplayer2.source.chunk.ChunkExtractorWrapper$BindingTrackOutput.sampleData(ChunkExtractorWrapper.java:201)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1260)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:319)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:135)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2019-01-16 08:48:53.763 5318-5329/com.xxx.app I/com.xxx.app: Clamp target GC heap from 407MB to 384MB
2019-01-16 08:48:53.801 5318-5559/com.xxx.app D/SurfaceUtils: disconnecting from surface 0xc6864008, reason pushBlankBuffersToNativeWindow
2019-01-16 08:48:53.803 5318-5559/com.xxx.app D/SurfaceUtils: set up nativeWindow 0xc6864008 for 1x1, color 0x2, rotation 0, usage 0x930
2019-01-16 08:48:53.845 5318-5329/com.xxx.app I/com.xxx.app: Clamp target GC heap from 407MB to 384MB
2019-01-16 08:48:53.859 5318-5559/com.xxx.app D/SurfaceUtils: connecting to surface 0xc6864008, reason pushBlankBuffersToNativeWindow(err2)
2019-01-16 08:48:53.860 5318-5558/com.xxx.app D/SurfaceUtils: disconnecting from surface 0xc6864008, reason disconnectFromSurface
2019-01-16 08:48:53.873 5318-5545/com.xxx.app E/libc: Access denied finding property "media.metrics.enabled"
2019-01-16 08:48:53.884 5318-5318/com.xxx.app D/EventLogger: decoderDisabled [2582.55, 239.95, window=0, period=0, video]
2019-01-16 08:48:53.887 5318-5929/com.xxx.app E/libc: Access denied finding property "media.metrics.enabled"
2019-01-16 08:48:53.894 5318-5554/com.xxx.app E/libc: Access denied finding property "media.metrics.enabled"
2019-01-16 08:48:53.918 5318-5318/com.xxx.app D/EventLogger: drmSessionReleased [2582.58, 239.95, window=0, period=0]
2019-01-16 08:48:53.919 5318-5318/com.xxx.app D/EventLogger: decoderDisabled [2582.58, 239.95, window=0, period=0, audio]
2019-01-16 08:48:53.927 5318-5329/com.xxx.app I/com.xxx.app: Clamp target GC heap from 407MB to 384MB
2019-01-16 08:48:53.933 5318-5318/com.xxx.app D/EventLogger: mediaPeriodReleased [2582.60, 239.95, window=0, period=0]
2019-01-16 08:48:53.934 5318-5545/com.xxx.app I/com.xxx.app: Waiting for a blocking GC Alloc
2019-01-16 08:48:53.934 5318-5546/com.xxx.app I/com.xxx.app: Waiting for a blocking GC Alloc
2019-01-16 08:48:54.291 5318-5329/com.xxx.app I/com.xxx.app: Background concurrent copying GC freed 135(27KB) AllocSpace objects, 5715(379MB) LOS objects, 50% free, 4MB/8MB, paused 232us total 363.036ms
2019-01-16 08:48:54.291 5318-5545/com.xxx.app I/com.xxx.app: WaitForGcToComplete blocked Alloc on HeapTrim for 357.652ms
2019-01-16 08:48:54.291 5318-5545/com.xxx.app I/com.xxx.app: Starting a blocking GC Alloc
2019-01-16 08:48:54.292 5318-5546/com.xxx.app I/com.xxx.app: WaitForGcToComplete blocked Alloc on HeapTrim for 357.925ms
2019-01-16 08:48:54.292 5318-5546/com.xxx.app I/com.xxx.app: Starting a blocking GC Alloc
2019-01-16 08:48:54.294 5318-5318/com.xxx.app E/EventLogger: playerFailed [2582.96, 239.95, window=0]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 65552 byte allocation with 2792 free bytes and 2792B until OOM, max allowed footprint 402653184, growth limit 402653184
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:354)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 65552 byte allocation with 2792 free bytes and 2792B until OOM, max allowed footprint 402653184, growth limit 402653184
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 2792 free bytes and 2792B until OOM, max allowed footprint 402653184, growth limit 402653184
        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
        at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:626)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:546)
        at com.google.android.exoplayer2.source.chunk.ChunkExtractorWrapper$BindingTrackOutput.sampleData(ChunkExtractorWrapper.java:201)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1260)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:319)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:135)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by xiaoxixi615** [comment]
I got the same problem when playing a local mkv/mp4 file,  exoplayer(v. r2.9.0)

2019-01-22 11:44:00.635 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: Waiting for a blocking GC Alloc
2019-01-22 11:44:00.652 16320-16331/com.ximoxi.kiwiexoplayerdemo I/zygote: Clamp target GC heap from 215MB to 192MB
2019-01-22 11:44:00.652 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: WaitForGcToComplete blocked Alloc on ProfileSaver for 16.713ms
2019-01-22 11:44:00.652 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: Starting a blocking GC Alloc
2019-01-22 11:44:00.652 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: Starting a blocking GC Alloc
2019-01-22 11:44:00.670 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: Clamp target GC heap from 215MB to 192MB
2019-01-22 11:44:00.670 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: Alloc concurrent copying GC freed 4(80B) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 50us total 17.973ms
2019-01-22 11:44:00.670 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: Starting a blocking GC Alloc
2019-01-22 11:44:00.687 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: Clamp target GC heap from 215MB to 192MB
2019-01-22 11:44:00.687 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: Alloc concurrent copying GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 48us total 16.671ms
2019-01-22 11:44:00.687 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: Forcing collection of SoftReferences for 64KB allocation
2019-01-22 11:44:00.687 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: Starting a blocking GC Alloc
2019-01-22 11:44:00.710 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: Clamp target GC heap from 215MB to 192MB
2019-01-22 11:44:00.711 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: Alloc concurrent copying GC freed 8(208B) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 48us total 23.355ms
2019-01-22 11:44:00.711 16320-22140/com.ximoxi.kiwiexoplayerdemo W/zygote: Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 13456 free bytes and 13KB until OOM, max allowed footprint 201326592, growth limit 201326592"
2019-01-22 11:44:00.711 16320-16331/com.ximoxi.kiwiexoplayerdemo I/zygote: WaitForGcToComplete blocked Background on ProfileSaver for 58.769ms
2019-01-22 11:44:00.711 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: Waiting for a blocking GC Alloc
2019-01-22 11:44:00.721 16320-16363/com.ximoxi.kiwiexoplayerdemo I/zygote: Waiting for a blocking GC Alloc
2019-01-22 11:44:00.741 16320-16331/com.ximoxi.kiwiexoplayerdemo I/zygote: Clamp target GC heap from 215MB to 192MB
2019-01-22 11:44:00.741 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: WaitForGcToComplete blocked Alloc on ProfileSaver for 29.829ms
2019-01-22 11:44:00.741 16320-22140/com.ximoxi.kiwiexoplayerdemo I/zygote: Starting a blocking GC Alloc
2019-01-22 11:44:00.741 16320-16363/com.ximoxi.kiwiexoplayerdemo I/zygote: WaitForGcToComplete blocked Alloc on ProfileSaver for 19.770ms
2019-01-22 11:44:00.741 16320-16363/com.ximoxi.kiwiexoplayerdemo I/zygote: Starting a blocking GC Alloc
2019-01-22 11:44:00.741 16320-22140/com.ximoxi.kiwiexoplayerdemo E/LoadTask: OutOfMemory error loading stream
    java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 13456 free bytes and 13KB until OOM, max allowed footprint 201326592, growth limit 201326592
        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
        at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:633)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:553)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1262)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:321)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:899)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-01-22 11:44:00.759 16320-16331/com.ximoxi.kiwiexoplayerdemo I/zygote: Clamp target GC heap from 215MB to 192MB
2019-01-22 11:44:00.762 16320-16320/com.ximoxi.kiwiexoplayerdemo E/EventLogger: internalError [1732.84, 3.67, window=0, period=0, loadError]
    com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 65552 byte allocation with 13456 free bytes and 13KB until OOM, max allowed footprint 201326592, growth limit 201326592
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:411)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 13456 free bytes and 13KB until OOM, max allowed footprint 201326592, growth limit 201326592
        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
        at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:633)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:553)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1262)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:321)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:899)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2019-01-22 11:44:00.763 16320-16320/com.ximoxi.kiwiexoplayerdemo E/KiwiListener: internalError [1732.84, 3.67, window=0, period=0, loadError]
    com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 65552 byte allocation with 13456 free bytes and 13KB until OOM, max allowed footprint 201326592, growth limit 201326592
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:411)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 13456 free bytes and 13KB until OOM, max allowed footprint 201326592, growth limit 201326592
        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
        at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:633)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:553)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1262)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:321)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:899)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2019-01-22 11:44:00.764 16320-16320/com.ximoxi.kiwiexoplayerdemo D/MainActivity: onError:LOAD_ERROR  msg:Unexpected OutOfMemoryError: Failed to allocate a 65552 byte allocation with 13456 free bytes and 13KB until OOM, max allowed footprint 201326592, growth limit 201326592
2019-01-22 11:44:00.777 16320-16331/com.ximoxi.kiwiexoplayerdemo I/zygote: Clamp target GC heap from 215MB to 192MB
2019-01-22 11:44:01.861 16320-16331/com.ximoxi.kiwiexoplayerdemo I/chatty: uid=10272(com.ximoxi.kiwiexoplayerdemo) HeapTaskDaem

**Comment by xiaoxixi615** [comment]
@erdemguven 
I find the reason is that the allocating process is faster than the releasing process in DefaultAllocator,  availableCount for re-use is not enough,  so new allaction(64*1024) is always created, after a long time, memory is used up, and oom occurs.
```
  @Override
  public synchronized Allocation allocate() {
    allocatedCount++;
    Allocation allocation;
    if (availableCount > 0) {
      allocation = availableAllocations[--availableCount];
      availableAllocations[availableCount] = null;
    } else {
      allocation = new Allocation(new byte[individualAllocationSize], 0); //this executed too many times
    }
    return allocation;
  }
```
can you help to give some advice on how to fix this issue? thanks a lot.

**Comment by erdemguven** [comment]
@jqacn3000 @xiaoxixi615  Have you tried ExoPlayer demo app, does the same thing happen?

**Comment by xiaoxixi615** [comment]
@erdemguven 
ExoPlayer demo doesn't have the same problem,  I find that after adding the [android:largeHeap="true"] property in AndriodManifest.xml, the OOM gone. Thank you very much
