### ISSUE TITLE
Several Players problem

### ISSUE THREAD

**Issue by Zo2m4bie** [google/ExoPlayer#540]
Hi. I tried to use ExoPlayer in my app. In my app I want to show 4 video streams. I created screen with 4 surfaceviews and 4 players.  I tested it on samsung tab 2 7`(Android 4.4), it's work fine(On samsung S3, it's work fine too ). But when I tried it on Nexus 7(2 gen,  Android 5.1.1,  and the same happens on Nexus 6 too), I didn't see any of streams.  After that I tried to show only one stream and I couldn't. Also I figured out that I can show one stream After rebooting. After playing one stream, I tried to play 2 streams. But I received same error as before and after that I couldn't play one stream, even if app was deleted, only reboot can help. Also after that error demo doesn't work too. 

I used DemoPlayer from sample and HlsRendererBuilder

Error trace:

```
06-12 00:19:20.374      185-590/? E/OMX-VDEC-1080P﹕ Extension: OMX.google.android.index.storeMetaDataInBuffers not implemented
06-12 00:19:20.374      185-590/? E/OMXNodeInstance﹕ getExtensionIndex(d7:qcom.decoder.avc, OMX.google.android.index.storeMetaDataInBuffers) ERROR: NotImplemented(0x80001006)
06-12 00:19:20.374  11150-11194/? E/ACodec﹕ [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
06-12 00:19:20.375     185-8931/? E/OMX-VDEC-1080P﹕ Enabling Adaptive playback for 1920 x 1080
06-12 00:19:20.376      185-590/? E/OMX-VDEC-1080P﹕ No color conversion required
06-12 00:19:20.395      185-590/? E/OMX-VDEC-1080P﹕ GET_MV_BUFFER_SIZE returned: Size: 557056 and alignment: 8192
06-12 00:19:20.404      185-590/? E/OMX-VDEC-1080P﹕ Set output buffer failed
06-12 00:19:20.404      185-590/? E/OMXNodeInstance﹕ useBuffer(d7:qcom.decoder.avc, Output:1 3137536@0xb3ffe970) ERROR: InsufficientResources(0x80001000)
06-12 00:19:20.406  11150-11194/? E/ACodec﹕ registering GraphicBuffer 0 with OMX IL component failed: -2147483648
06-12 00:19:20.406  11150-11194/? E/ACodec﹕ Failed to allocate buffers after transitioning to IDLE state (error 0x80000000)
06-12 00:19:20.406  11150-11194/? E/ACodec﹕ signalError(omxError 0x80001001, internalError -2147483648)
06-12 00:19:20.406  11150-11193/? E/MediaCodec﹕ Codec reported err 0x80001001, actionCode 0, while in state 5
06-12 00:19:20.409  11150-11174/? E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 1920, 1080, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:387)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 1920, 1080, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: android.media.MediaCodec$CodecException: start failed
            at android.media.MediaCodec.native_start(Native Method)
            at android.media.MediaCodec.start(MediaCodec.java:612)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:367)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
06-12 00:19:20.419    185-11195/? E/OMX-VDEC-1080P﹕ ERROR: read from pipe failed, ret -1 errno 9
06-12 00:19:20.434    185-11196/? E/OMX-VDEC-1080P﹕ Error in ioctl read next msg
06-12 00:19:20.434     185-3210/? E/﹕ Destroy C2D instance
06-12 00:19:20.434     185-3210/? E/﹕ Destroy C2D instance
06-12 00:19:20.437  11150-11174/? E/ExoPlayerImplInternal﹕ Stop failed.
    java.lang.IllegalStateException
            at android.media.MediaCodec.native_stop(Native Method)
            at android.media.MediaCodec.stop(MediaCodec.java:628)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.releaseCodec(MediaCodecTrackRenderer.java:436)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onDisabled(MediaCodecTrackRenderer.java:407)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onDisabled(MediaCodecVideoTrackRenderer.java:325)
            at com.google.android.exoplayer.TrackRenderer.disable(TrackRenderer.java:214)
            at com.google.android.exoplayer.ExoPlayerImplInternal.stopAndDisable(ExoPlayerImplInternal.java:513)
            at com.google.android.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:501)
            at com.google.android.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:478)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:232)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by Arqu** [comment]
I haven't played with multiple streams on ExoPlayer, however as far as I know, pre Lolipop devices and Lolipop devices support significantly different MediaCodec API and functionality. I think that the app cannot directly access the decode buffer with more than one reader at a time (you can only initialise 1 hardware codec), I think you should take a look at http://developer.android.com/reference/android/media/MediaCodec.html
And also take a look at this paragraph
```
Once the client has an input buffer available it can fill it with data and submit it it to the codec via a call to queueInputBuffer(int, int, int, long, int). Do not submit multiple input buffers with the same timestamp (unless it is codec-specific data marked as such using the flag BUFFER_FLAG_CODEC_CONFIG).
```

**Comment by Ood-Tsen** [comment]
@Zo2m4bie ,  not many devices support multiple hardware decoders simultaneously.
You may consider software decoder.

From your description, 'TI OMAP 4430' and 'Exynos 4412 Quad' do, but others not.

| device | chipset         |  work |
|-----------------|-----------------|-------|
|Samsung tab 2 7  |TI OMAP 4430     |o      |
|Samsung S3       |Exynos 4412 Quad |o      |
|Nexus 7 2nd      |Qualcomm S4Pro   |x      |
|Nexus 6          |Qualcomm 805     |x      |

**Comment by Zo2m4bie** [comment]
@Ood-Tsen As I understand from your answer, it's no matter what kind of android sdk was installed on device. Maybe you know. Is there some method to know that device supports multiple hardware decoders simultaneously? 
And also maybe someone know how to reset Codec. Because for now user has to reboot device after getting this error.

**Comment by Ood-Tsen** [comment]
No, [CodecCapabilities](http://developer.android.com/reference/android/media/MediaCodecInfo.CodecCapabilities.html) does not have this feature.

I think MediaCodec should be released gracefully. If not , it should be an issue.

**Comment by ojw28** [comment]
Whilst there are now more devices supporting multiple decoder instances, there are still no guarantees that multiple instances will be available (since it would prevent shipping of low end Android devices). It seems quite "noisy" to be needing to play 4 video streams at once, however if you do want to do this it might be a matter of white-listing only devices that are known to work for this use case.
