### ISSUE TITLE
HLS Streaming - Input does not start with the #EXTM3U header

### ISSUE THREAD

**Issue by shgrg1712** [google/ExoPlayer#5424]
Seached Issues - #4141 , #4150 ,#4066

I am using HLS encrypted Stream for exoplayer. 

URL - https://mediadev.camtrack.com/dev/temp/bunny.m3u8?Expires=2072197799&Signature=PqNjmCoIRo~lSurGLVtY6FLBNGQRPVC-5JmD8Iq2BQJOopbnBlYNTlN8RBpPrdDELSK618rkIpsh18feUNpx4OjPUn6zc6IRePf20~CVnltW1IVlSf-uV3PLpK9Zjdjm82j12HEgD8m3mff5ihN4ReCzweOIxT41t~SQ95S319CvmuV-8LB4nNiZ2i~7K2MMYIzMOd~ZRrV~0VtFbSRDmb9kTu0ft~DysJb1~JIXqtF2xCH6a5rOAcw2He6PR8wVjQ5rNc4T14UHd2JIIixTJY4~I~P5M3-DcOIfoC15P8bpakaTyxvzDtZbT3Ff~l8ZmbQd9hG4PD5AnUcOEtHtOw__&Key-Pair-Id=APKAJRTX764SKK6DHAOA

I have changed content_url in strings.xml in Exoplayer Demo App and trying to play demo-ima app. 

This is the error I am getting.

```
2019-01-22 17:24:41.368 24136-24231/com.google.android.exoplayer2.imademo E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:184)
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:53)
        at com.google.android.exoplayer2.offline.FilteringManifestParser.parse(FilteringManifestParser.java:41)
        at com.google.android.exoplayer2.offline.FilteringManifestParser.parse(FilteringManifestParser.java:25)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:158)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

I am creating m3u8 content from mp4 file using Pavtube Video Converter tool. Then I have uploaded the video Amazon s3 . Above mentioned URL is cloud front URL .

May be content I have converted from Mp4 is not valid content for this purpose. 

Please help.

**Comment by shgrg1712** [comment]
More Information 

This is locally made URL so this is not georestricted URL.

**Comment by shgrg1712** [comment]
Here I am attaching  encrypted version of file 

Cipher - AES/CBC/PKCS7Padding
Key Size - 16 
IV Size - 16
[encrypted.zip](https://github.com/google/ExoPlayer/files/2782787/encrypted.zip)

This is only m3u8 file. May be I need to upload .ts file also. I am new in this field . Please help If I am uploading incorrect or Incomplete media on url.


[bunny.zip](https://github.com/google/ExoPlayer/files/2782799/bunny.zip)

bunny.zip - This is original file.

**Comment by ojw28** [comment]
None of the standard ways of providing encryption in HLS involve encrypting the playlist, which appears to be what you're doing here. They involve encrypting the individual media segments. So it's unclear what you're doing, and perhaps more importantly, why.

**Comment by shgrg1712** [comment]
Hello Oliver, 
                   May be HLS media I was creating with Pavtube Video Converter is not proper. So I have tried to create HLS media using ffmpeg command. Following is the command I have used.

ffmpeg -i bunny.mp4 -b:v 1M -g 60 -hls_time 2 -hls_list_size 0 -hls_segment_size 500000 output.m3u8

Now After the creation of m3u8 and ts file , I have uploaded the content on amazon server. Then we got cloudfront URL.

That URL I have added to content_url in strings.xml of demo-ima app in Demo exoplayer app. After launching the player it is playing first ts file but then it is getting stuck. Following is the error.

2019-01-23 09:46:15.857 12113-12206/com.google.android.exoplayer2.imademo E/ExoPlayerImplInternal: Source error.
    **com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416**
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:265)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:246)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:195)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.exoplayer2.upstream.DataSourceException
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:303)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:265) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:246) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:195) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 

For your reference , I am attaching media files in the attachment.
[ffmpegHLS.zip](https://github.com/google/ExoPlayer/files/2785815/ffmpegHLS.zip)

**Comment by ojw28** [comment]
[Http 416 is Range Not Satisfiable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/416). Which indicates there's still something wrong with the media. Please could you ensure your media plays correctly in at least one other player first, since that will provide at least some level of validation that the media itself is correct.

**Comment by shgrg1712** [comment]
Hello Oliver ,
                    Can you suggest me good player which plays m3u8 and ts media locally. I will test the media.

Thanks

**Comment by shgrg1712** [comment]
Hello Oliver, 
                   I have made the improvements in my media. Now I am getting another error.

2019-01-23 17:21:25.881 31120-31200/com.google.android.exoplayer2.imademo 
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.findEndOfFirstTsPacketInBuffer(TsExtractor.java:410)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:278)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:253)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:195)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)


Thanks 
Sheetal Garg

**Comment by ojw28** [comment]
That still suggests the media is invalid. I suggest you verify that the media plays correctly with VLC and popular web players, such as [HLS.js](https://hls-js.netlify.com/demo/) before reporting issues here. Closing for now, because the media appears to be invalid.
