### ISSUE TITLE
TextTrackRenderer: InvalidResponseCodeException (404) while file exists

### ISSUE THREAD

**Issue by dophlin** [google/ExoPlayer#543]
I am working on Exoplayer Demo to use it in my application. Everything works well except subtitles. I use Expression Encoder 4 pro to encode movies to II Smooth Streaming format. When I add English subtitle to the movie, Exoplayer shows eng-subtitles correctly but when I add Persian subtitle to the movie, Exoplayer throw an InvalidResponseCodeException. I am sure that the url is correct since I can download it by the browser.

http://www.test.com/XXX/QualityLevels(546)/Fragments(textstream_fas=0)
```
com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:204)
        at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:87)
        at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:146)
        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:242)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
```
When I open the Fragments(textstream_fas=0).* in notepad++, it shows the file is encoded in ANSI.
Is there something special that I should know about it? Let me know if you need additional information.

http://stackoverflow.com/questions/30762529/exoplayer-invalidresponsecodeexception-404-while-file-exists

Thanks

**Comment by ojw28** [comment]
That's definitely a HTTP 404 (i.e. not found), not anything to do with encoding or anything like that. Perhaps the player is requesting a url that's different to the one you're looking at in your browser. Can you provide a link to your SmoothStreaming manifest?

**Comment by dophlin** [comment]
Thank you for your reply, here is a sample SmoothStreaming manifest:

http://stream.goodluckapps.ir/StreamBox/SSData/ted_talks/RomanMars_2015-1500k.ism/QualityLevels%28608%29/Fragments%28textstream_fas=0%29

**Comment by ojw28** [comment]
- You initially pasted a link containing "StreamBox" that has fas subtitles. I don't see a 404 on those, but it does appear they're not packaged correctly within the FMP4 container, and so playback fails.
- The current link above contains english subtitles, but requesting them returns 415 (media unsupported).
- The link the fast subtitles above gives a 404 in my browser.

Which link am I supposed to be looking at, exactly?

**Comment by dophlin** [comment]
Actually, the link which contains "StreamBox" is a sample test for myself, so I provided another link for you to check it. Anyway, in the following there are another links, the first one contains eng subtitle and can be played correctly, the second one is the same video which is encoded with a Persian subtitle.

Eng:
http://stream.goodluckapps.ir/eng/RomanMars_2015-1500k.ism
Persian:
http://stream.goodluckapps.ir/fas/RomanMars_2015-1500k.ism

Last night, I used the pure Demo Project and replaced a sample url with myself and I've figured it out the problem is not about **InvalidResponseCodeException**. I faced to an **EOFException**:
```
    com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.io.EOFException
            at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:254)
            at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:92)
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:95)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:214)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:157)
            at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
            at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:155)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:242)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
```
The exception throws from DefaultHttpDataSource.skipInternal()
```
  private void skipInternal() throws IOException {
    if (bytesSkipped == bytesToSkip) {
      return;
    }

    // Acquire the shared skip buffer.
    byte[] skipBuffer = skipBufferReference.getAndSet(null);
    if (skipBuffer == null) {
      skipBuffer = new byte[4096];
    }

    while (bytesSkipped != bytesToSkip) {
      int readLength = (int) Math.min(bytesToSkip - bytesSkipped, skipBuffer.length);
      int read = inputStream.read(skipBuffer, 0, readLength);
      if (Thread.interrupted()) {
        throw new InterruptedIOException();
      }
      if (read == -1) {
        throw new EOFException(); // Here is the point!!!
      }
      bytesSkipped += read;
      if (listener != null) {
        listener.onBytesTransferred(read);
      }
    }

    // Release the shared skip buffer.
    skipBufferReference.set(skipBuffer);
  }
```

I think reading UTF-8 files with normal inputstream.read is the problem. I usually use BufferedReader to read an UTF-8 stream correctly. What's your opinion?
Thank you for your attention.

**Comment by ojw28** [comment]
That suggests your subtitle data isn't correctly packaged in the FMP4 container. At the point where the error is thrown the data is still being treated as binary sample data contained within FMP4, and it hasn't got to the point where it tries to read/parse the subtitle sample. You should look at your packaging.
