### ISSUE TITLE
Cannot play Smoothstream + DRM on TCL AndroidTV

### ISSUE THREAD

**Issue by gkovacs87** [google/ExoPlayer#5453]
### Issue description

Some of the TCL AndroidTV devices cannot play SmoothStream videos with Playready DRM protection.
We can reproduce the issue in our applications and also in the ExoPlayer demo application.

We receive the following error:
 ```
Playback error.
 com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to open session: Session not opened
         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.shouldWaitForKeys(MediaCodecRenderer.java:1036)
         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:989)
         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664)
         at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
         at android.os.Handler.dispatchMessage(Handler.java:98)
         at android.os.Looper.loop(Looper.java:148)
         at android.os.HandlerThread.run(HandlerThread.java:61)
 Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to open session: Session not opened
         at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:443)
         at com.google.android.exoplayer2.drm.DefaultDrmSession.openInternal(DefaultDrmSession.java:294)
         at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:163)
         at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:559)
         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1075)
         at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
         ... 5 more
 Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to open session: Session not opened
         at android.media.MediaDrm.openSession(Native Method)
         at com.google.android.exoplayer2.drm.FrameworkMediaDrm.openSession(FrameworkMediaDrm.java:112)
         at com.google.android.exoplayer2.drm.DefaultDrmSession.openInternal(DefaultDrmSession.java:282)
         ... 10 more
```

### Reproduction steps
1) Launch ExoPlayer demo application
2) Select Smootstreaming > Super Speed (Playready) content
3) Notice the "Playback failed" message on the device

### Link to test content
https://playready.directtaps.net/smoothstreaming/SSWSS720H264PR/SuperSpeedway_720.ism

We reproduced the issue with other contents as well in our applications, when we are using SmoothStream + Playready. Further samples are sent via mail.

### Version of ExoPlayer being used
2.9.4
2.8.1
1.5.6
(all version we tested)

### Device(s) and version(s) of Android being used
It happens only on TCL devices.
Sample device: TCL U43P6046

### A full bug report captured from the device
Full bugreport sent via mail to dev.exoplayer@gmail.com.

**Comment by AquilesCanta** [comment]
Hi @gkovacs87, sorry for the delay. You should try and contact the device manufacturer; it looks like a device specific issue. I tried to find a direct communication path myself, but did not succeed. Do let me know if we can help.
