### ISSUE TITLE
IMA Demo Crash on Open

### ISSUE THREAD

**Issue by KellzCodes** [google/ExoPlayer#5476]
### Issue description
The Exo IMA Demo crashes on open

### Reproduction steps
1. Upgrade build tools to 3.3.0
2. Sync
3. Run the demo on your phone
### Link to test content
not available

### Version of ExoPlayer being used
Branch dev-v2

### Device(s) and version(s) of Android being used
Motorola Moto Z Play Droid - Motorola XT1635-01(Android 8.0.0, API 26)
com.android.tools.build:gradle:3.3.0

### A full bug report captured from the device
02/05 11:09:57: Launching demo-ima
$ adb shell am start -n "com.google.android.exoplayer2.imademo/com.google.android.exoplayer2.imademo.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Waiting for process to come online
Waiting for process to come online
Connected to process 5487 on device motorola-xt1635_01-ZY223JV2SG
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
    Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
    Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
    Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
I/ExoPlayerImpl: Init 796963d [ExoPlayerLib/2.9.5] [addison, XT1635-01, motorola, 26]
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
D/OpenGLRenderer: HWUI GL Pipeline
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.exoplayer2.imademo, PID: 5487
    java.lang.NullPointerException: Set player using adsLoader.setPlayer before preparing the player.
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:130)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.start(ImaAdsLoader.java:568)
        at com.google.android.exoplayer2.source.ads.AdsMediaSource.lambda$prepareSourceInternal$0(AdsMediaSource.java:333)
        at com.google.android.exoplayer2.source.ads.-$$Lambda$AdsMediaSource$zcXBZahV9F-k_KJACPO-bl_WWX0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6695)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
I/zygote: Do partial code cache collection, code=19KB, data=30KB
I/zygote: After code cache collection, code=19KB, data=30KB
    Increasing code cache capacity to 128KB
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
Application terminated.

**Comment by andrewlewis** [comment]
Thanks for reporting this! Fix on the way soon.
