### ISSUE TITLE
Bug on 2.9.2: "ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#5480]
### Issue description
On some videos, for some reason it doesn't let play them, having this in the log:

```
E: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(44100, 4, 22050)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:646)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1355)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(44100, 4, 22050)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:1128)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:532)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:593)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:640)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1355) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

### Reproduction steps
Run the attached project. It has a file "test.mp4" that doesn't play properly (shows either black screen or just the first frame), and a file "test2.mkv" that plays fine, to show that the app is ok.

### Link to test content
Here:
[ExoPlayerTest.zip](https://github.com/google/ExoPlayer/files/2840846/ExoPlayerTest.zip)

### Version of ExoPlayer being used
2.9.2 :

    implementation 'com.google.android.exoplayer:exoplayer-core:2.9.2'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.9.2'

### Device(s) and version(s) of Android being used
Pixel with Android 9 PQ2A.190205.003  .
Seems like it sometimes works fine on other devices though. Not sure when.

### A full bug report captured from the device
Attached here:
[bugreport-sailfish-PQ2A.190205.003-2019-02-07-14-45-00.zip](https://github.com/google/ExoPlayer/files/2840864/bugreport-sailfish-PQ2A.190205.003-2019-02-07-14-45-00.zip)

This is what I see when I open the app:

![image](https://user-images.githubusercontent.com/5357526/52412409-5d249000-2ae7-11e9-9e28-53124834773c.png)

There is no point in showing you a video, because it stays on this frame. Sometimes instead of the first frame, it just shows black.

I've noticed a similar issue was reported, but it was closed. Seeing that 2.9.2 is the latest official version, I hope there is a way to overcome this.
If you know what I should do, please let me know.

Weird thing is that I see on the release page newer versions : https://github.com/google/ExoPlayer/releases , and on maven too: https://mvnrepository.com/artifact/com.google.android.exoplayer/exoplayer?repo=springio-plugins-release , but all of those can't be used by setting them on the gradle file...

In fact, even on Google Photos it can't play this video right, but only on Google Pixel ...
Here's how it looks like on Google Photos:

[device-2019-02-07-144914.zip](https://github.com/google/ExoPlayer/files/2840870/device-2019-02-07-144914.zip)

Since it seems to occur only on Google Pixel, I've reported about it here too:
https://issuetracker.google.com/issues/123935010

**Comment by AndroidDeveloperLB** [comment]
In fact, even on Google Photos it can't play this video right, but only on Google Pixel ...

**Comment by AndroidDeveloperLB** [comment]
Seems it could be a hardware issue...

**Comment by andrewlewis** [comment]
@AndroidDeveloperLB That's right. The kernel log errors like `<3>[   13.468106] c1    295 wcd9xxx_slim_probe: failed to get slimbus tasha-slim-pgd logical address: -6` are a symptom of a solder crack failure on sailfish, which is a hardware failure and the device would need to be replaced. [Internal reference: b/124077173]

**Comment by AndroidDeveloperLB** [comment]
@andrewlewis What is exactly "solder crack failure" ? Is it repairable, or is it so bad that it requires a full replacement?

**Comment by andrewlewis** [comment]
@AndroidDeveloperLB That's straying too far off topic for this issue tracker but I expect you'll need a replacement device. Hope this limited information is of some use anyway.

**Comment by AndroidDeveloperLB** [comment]
@andrewlewis Sorry. It's just that for this kind of thing it's very hard to find who to ask, that will actually provide a professional and reliable answer... :(
It's not even my device... It's of the office, and I'm just a developer...
