### ISSUE TITLE
Demo crash on open

### ISSUE THREAD

**Issue by KellzCodes** [google/ExoPlayer#5492]
### Issue description
Process: com.google.android.exoplayer2.demo crashes on open

### Reproduction steps
1. Upgrade build tools to 3.3.1
2. Sync
3. Run the demo on your phone

### Link to test content
Not available

### Version of ExoPlayer being used
Branch dev-v2

### Device(s) and version(s) of Android being used
Motorola Moto Z Play Droid - Motorola XT1635-01(Android 8.0.0, API 26)
com.android.tools.build:gradle:3.3.1

### A full bug report captured from the device
`2019-02-10 00:20:44.578 19903-19903/? I/zygote: Late-enabling -Xcheck:jni
2019-02-10 00:20:44.864 19903-19903/com.google.android.exoplayer2.demo I/InstantRun: starting instant run server: is main process
2019-02-10 00:20:45.051 19903-19903/com.google.android.exoplayer2.demo E/SQLiteLog: (1) no such column: manual_stop_reason
2019-02-10 00:20:45.052 19903-19903/com.google.android.exoplayer2.demo D/AndroidRuntime: Shutting down VM
2019-02-10 00:20:45.060 19903-19903/com.google.android.exoplayer2.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.exoplayer2.demo, PID: 19903
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.SampleChooserActivity}: android.database.sqlite.SQLiteException: no such column: manual_stop_reason (code 1): , while compiling: SELECT id, title, subtitle, cache_key, state, download_percentage, downloaded_bytes, total_bytes, failure_reason, stop_flags, not_met_requirements, manual_stop_reason, start_time_ms, update_time_ms, stream_keys, custom_metadata FROM ExoPlayerDownloads ORDER BY start_time_ms ASC
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2895)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2974)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6695)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
     Caused by: android.database.sqlite.SQLiteException: no such column: manual_stop_reason (code 1): , while compiling: SELECT id, title, subtitle, cache_key, state, download_percentage, downloaded_bytes, total_bytes, failure_reason, stop_flags, not_met_requirements, manual_stop_reason, start_time_ms, update_time_ms, stream_keys, custom_metadata FROM ExoPlayerDownloads ORDER BY start_time_ms ASC
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
        at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1165)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1036)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1204)
        at com.google.android.exoplayer2.offline.DefaultDownloadIndex.getCursor(DefaultDownloadIndex.java:246)
        at com.google.android.exoplayer2.offline.DefaultDownloadIndex.getDownloadStates(DefaultDownloadIndex.java:182)
        at com.google.android.exoplayer2.demo.DownloadTracker.loadTrackedActions(DownloadTracker.java:173)
        at com.google.android.exoplayer2.demo.DownloadTracker.<init>(DownloadTracker.java:100)
        at com.google.android.exoplayer2.demo.DemoApplication.initDownloadManager(DemoApplication.java:128)
        at com.google.android.exoplayer2.demo.DemoApplication.getDownloadTracker(DemoApplication.java:101)
        at com.google.android.exoplayer2.demo.SampleChooserActivity.onCreate(SampleChooserActivity.java:103)
        at android.app.Activity.performCreate(Activity.java:6989)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1235)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2848)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2974) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164)`

**Comment by andrewlewis** [comment]
Please could you try uninstalling the demo app (`adb uninstall com.google.android.exoplayer2.demo`) then re-installing it?
