### ISSUE TITLE
ConcatenatingMediaSource + ImaAdsLoader = java.lang.IllegalStateException

### ISSUE THREAD

**Issue by ridvanzoro** [google/ExoPlayer#5493]
Hi,
When I use ImaAdsLoader with ConcatenatingMediaSource, I get java.lang.IllegalStateException error. Could you please help me?

```
ConcatenatingMediaSource concatenatingMediaSource = new ConcatenatingMediaSource();
concatenatingMediaSource.addMediaSource(buildMediaSource(Uri.parse(url));
concatenatingMediaSource.addMediaSource(buildMediaSource(Uri.parse(url2)); 
MediaSource mediaSourceWithAds = new AdsMediaSource(
                concatenatingMediaSource,
                dataSourceFactory,
                imaAdsLoader,
                playerView.getOverlayFrameLayout());
player.prepare(mediaSourceWithAds, !haveStartPosition, false);
```

Error:
```
2019-02-09 21:57:35.728 28236-28320/clk.com.test E/AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
    Process: clk.com.test, PID: 28236
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.source.ads.SinglePeriodAdTimeline.<init>(SinglePeriodAdTimeline.java:39)
        at com.google.android.exoplayer2.source.ads.AdsMediaSource.maybeUpdateSourceInfo(AdsMediaSource.java:457)
        at com.google.android.exoplayer2.source.ads.AdsMediaSource.onAdPlaybackState(AdsMediaSource.java:431)
        at com.google.android.exoplayer2.source.ads.AdsMediaSource.access$300(AdsMediaSource.java:50)
        at com.google.android.exoplayer2.source.ads.AdsMediaSource$ComponentListener$1.run(AdsMediaSource.java:497)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by andrewlewis** [comment]
Please see #3750.
