### ISSUE TITLE
Playing a 360 mp4 video 

### ISSUE THREAD

**Issue by sergexte** [google/ExoPlayer#5517]
I have a question, I tried getting a 360 (mp4) video to play with Exoplayer (v2.9.0) and I couldn’t get it to work. 

The sample in the sample app works great. If I use that file it plays nicely. I noticed it is a .ts file which I tried converting my own .mp4 to .ts but it still failed.

Where could I find some information on how to make the setup for this to work? Or is this not meant to be supported yet? 

The error I'm getting is : 

```
02-14 10:42:52.018 20838-20838 I/art: Late-enabling -Xcheck:jni
02-14 10:42:52.074 20838-20838 W/System: ClassLoader referenced unknown path: /data/app/com.srkt.exoplayerbeta-2/lib/arm
02-14 10:42:52.079 20838-20844 I/art: Debugger is no longer active
02-14 10:42:52.113 20838-20838 W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-14 10:42:52.140 20838-20838 I/art: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
02-14 10:42:52.140 20838-20838 I/art: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
02-14 10:42:52.204 20838-20851 D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
02-14 10:42:52.262 20838-20851 I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
02-14 10:42:52.265 20838-20851 I/OpenGLRenderer: Initialized EGL, version 1.4
02-14 10:42:56.576 20838-20838 I/ExoPlayerImpl: Init 6799f0e [ExoPlayerLib/2.9.0] [hammerhead, Nexus 5, LGE, 23]
02-14 10:42:56.638 20838-20865 W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
02-14 10:42:56.661 20838-20865 I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
02-14 10:42:56.666 20838-20865 D/MediaCodecInfo: NoSupport [sizeAndRate.support, 5760x2880x-1.0] [OMX.qcom.video.decoder.avc, video/avc] [hammerhead, Nexus 5, LGE, 23]
02-14 10:42:56.666 20838-20865 D/MediaCodecInfo: NoSupport [sizeAndRate.support, 5760x2880x-1.0] [OMX.qcom.video.decoder.avc, video/avc] [hammerhead, Nexus 5, LGE, 23]
02-14 10:42:56.702 20838-20874 I/OMXClient: Using client-side OMX mux.
02-14 10:42:56.844 20838-20873 I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 21338113
02-14 10:42:56.846 20838-20874 E/ACodec: [OMX.qcom.video.decoder.avc] configureCodec returning error -1010
02-14 10:42:56.846 20838-20874 E/ACodec: signalError(omxError 0x80001001, internalError -1010)
02-14 10:42:56.846 20838-20873 E/MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3
02-14 10:42:56.847 20838-20865 E/MediaCodec: configure failed with err 0xfffffc0e, resetting...
02-14 10:42:56.853 20838-20874 I/OMXClient: Using client-side OMX mux.
02-14 10:42:56.926 20838-20865 W/MediaCodecRenderer: Failed to initialize decoder: OMX.qcom.video.decoder.avc
    android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1778)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:791)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:731)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:460)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1247)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1097)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:633)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:530)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
02-14 10:42:56.928 20838-20865 E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [5760, 2880, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:465)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1247)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1097)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:633)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:530)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [5760, 2880, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:739)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:460)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1247) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1097) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:633) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:530) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1778)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:791)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:731)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:460) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1247) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1097) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:633) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:530) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
02-14 10:56:54.490 20838-20838 I/ExoPlayerImpl: Release 6799f0e [ExoPlayerLib/2.9.0] [hammerhead, Nexus 5, LGE, 23] [goog.exo.core, goog.exo.ui]
02-14 10:56:54.839 20838-20838 W/ExoPlayerImplInternal: Ignoring messages sent after release.
```

**Comment by andrewlewis** [comment]
`D/MediaCodecInfo: NoSupport [sizeAndRate.support, 5760x2880x-1.0] [OMX.qcom.video.decoder.avc, video/avc] [hammerhead, Nexus 5, LGE, 23]` suggests that the video is too big to be decoded on this device. You could try producing a lower resolution video and see if that is playable.
