### ISSUE TITLE
Getting crash when starting Exoplayer DownloadService

### ISSUE THREAD

**Issue by KinjalDhamat312** [google/ExoPlayer#5539]
Hello, I am getting a crash from exoplayer when I am trying to start downloading cache from the exoplayer download service, Please take a look at below logs and let me know what can be the issue.

```
Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.exoplayer.downloadService.action.ADD cmp=com.example.cachemusic/com.example.cachemusic.base.musicdownloadhelper.DemoDownloadService (has extras) }: app is in background uid UidRecord{3d3c66e u0a130 LAST bg:+2m6s975ms idle change:cached procs:1 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1522)
at android.app.ContextImpl.startService(ContextImpl.java:1478)
at android.content.ContextWrapper.startService(ContextWrapper.java:650)
at com.google.android.exoplayer2.offline.DownloadService.startWithAction$255528a9(DownloadService.java:194)
at com.example.cachemusic.base.musicdownloadhelper.DownloadTracker.startServiceWithAction(DownloadTracker.kt:59)
at com.example.cachemusic.base.musicdownloadhelper.DownloadTracker$StartDownloadDialogHelper.onPrepared(DownloadTracker.kt:265)
at com.google.android.exoplayer2.offline.DownloadHelper$1$$Lambda$0.run(Unknown Source:1062)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6609)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:445)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:906)
```

This crash only seems to come in Android 8.0.
Can anyone please help and let me know the solution?

**Comment by andrewlewis** [comment]
If your app is in the background there needs to be a notification associated with the service due to [background execution limits](https://developer.android.com/about/versions/oreo/android-8.0-changes#back-all).

Have you made modifications to the Download tracker in your app? I'm a bit confused about why a download is being initiated from `StartDownloadDialogHelper.onPrepared`, and why the app is not in the foreground at this point.

**Comment by ojw28** [comment]
Closing due to lack of further information (and because the question may have been answered).
