### ISSUE TITLE
Playing HTTPS streams

### ISSUE THREAD

**Issue by satyres** [google/ExoPlayer#5552]
Hi, 
Exoplayer can't play HTTPS stream and here is an example of a stream.
https://rcn.radioonlinehd.net:8010/masradio
please is there a way to solve this issue.
regards

**Comment by marcbaechinger** [comment]
I think ExoPlayer can access streams with https. I'm fairly sure I've seen this working.
When playing the url you provided, it works as well: mimeType=application/x-icy, supported=YES

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE). Best is trying with the demo app, and then provide the information requested in the template from there.

**Comment by satyres** [comment]
Hi , @marcbaechinger Thanks for your quick reply.
ok i'll provide more information
did you try the stream url using Exoplayer ?
regards

**Comment by satyres** [comment]
Here is the log on Android studio : 
i'm using V 2.9.2

E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://rcn.radioonlinehd.net:8010/masradio
        at com.MSoft.cloudradioPro.players.exoplayer.IcyDataSource.connect(IcyDataSource.java:140)
        at com.MSoft.cloudradioPro.players.exoplayer.IcyDataSource.open(IcyDataSource.java:132)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.io.IOException: unexpected end of stream on Connection{rcn.radioonlinehd.net:8010, proxy=DIRECT@ hostAddress=rcn.radioonlinehd.net/67.212.186.202:8010 cipherSuite=none protocol=http/1.1}
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:208)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)

Regards

**Comment by marcbaechinger** [comment]
Many thanks! Yes, I'm testing with ExoPlayer. 

In the stack trace you sent, it appears that you are trying an http stream. At least the url which shows there is http only: http://rcn.radioonlinehd.net:8010/masradio

When I try with curl it tells me only the https url delivers some data (see below). May I kindly ask you to check whether it is intended to use the http url?

$ curl http://rcn.radioonlinehd.net:8010/masradio
curl: (52) Empty reply from server

$ curl https://rcn.radioonlinehd.net:8010/masradio
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.

**Comment by satyres** [comment]
Hi, Thanks for your time
the problem is that i was removing the "s" automatically because some url won"t play when it's HTTPS
this one have worked now ! strange
i've updated to 2.9.5 and it's working now.
Thanks so much for your time
i'll try on other HTTPS streams and tell you 
Best regards

**Comment by marcbaechinger** [comment]
Great! Many thanks!
