### ISSUE TITLE
Play 2-hour movie. M3u8 format error log 301 test Android 8.0

### ISSUE THREAD

**Issue by Crz-GitHub** [google/ExoPlayer#5555]
com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 301
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)

**Comment by Crz-GitHub** [comment]
Video Test Url:http://sohu.zuida-163sina.com/ppvod/937EABA891674B232D226C159D7CACFC.m3u8

**Comment by mattermon** [comment]
may a server error [301](https://en.wikipedia.org/wiki/HTTP_301)

**Comment by Crz-GitHub** [comment]
Android 6.0 There is no error 8.0 There is no error   I've already called DefaultHttpDataSourceFactory()

**Comment by Crz-GitHub** [comment]
The error is caused by - and _ not finding a solution for the time being

**Comment by andrewlewis** [comment]
This looks like a content or server-side issue rather than a problem with ExoPlayer. You need to figure out why the server is returning status code 301. I'll close the issue for now, but if you find evidence that this is an ExoPlayer issue please reply here and I'll reopen the issue.
