### ISSUE TITLE
Throwing OutOfMemoryError

### ISSUE THREAD

**Issue by star-andy** [google/ExoPlayer#5564]
exoplaer version  2.9.3

android 5.1.1

````
02-25 14:46:57.266 3101-5096/? E/art: Throwing OutOfMemoryError "Failed to allocate a 28 byte allocation with 0 free bytes and 3GB until OOM" (recursive case)
02-25 14:46:57.266 3101-5143/? I/art: WaitForGcToComplete blocked for 106.160ms for cause Alloc
02-25 14:46:57.267 3101-5096/? E/art: "ExoPlayerImplInternal:Handler" prio=5 tid=48 Runnable
02-25 14:46:57.267 3101-5096/? E/art:   | group="main" sCount=0 dsCount=0 obj=0x13084f90 self=0xb9338240
02-25 14:46:57.267 3101-5096/? E/art:   | sysTid=5096 nice=-16 cgrp=default sched=0/0 handle=0xb94d8c68
02-25 14:46:57.267 3101-5096/? E/art:   | state=R schedstat=( 223438971 588924 108 ) utm=21 stm=1 core=3 HZ=100
02-25 14:46:57.267 3101-5096/? E/art:   | stack=0x9b430000-0x9b432000 stackSize=1036KB
02-25 14:46:57.267 3101-5096/? E/art:   | held mutexes= "mutator lock"(shared held)
02-25 14:46:57.267 3101-5096/? E/art:     at android.util.Pair.create(Pair.java:75)
02-25 14:46:57.267 3101-5096/? E/art:     at com.google.android.exoplayer2.source.AbstractConcatenatedTimeline.getConcatenatedUid(AbstractConcatenatedTimeline.java:60)
02-25 14:46:57.267 3101-5096/? E/art:     at com.google.android.exoplayer2.source.AbstractConcatenatedTimeline.getPeriod(AbstractConcatenatedTimeline.java:223)
02-25 14:46:57.267 3101-5096/? E/art:     at com.google.android.exoplayer2.MediaPeriodQueue.getFollowingMediaPeriodInfo(MediaPeriodQueue.java:552)
02-25 14:46:57.267 3101-5096/? E/art:     at com.google.android.exoplayer2.MediaPeriodQueue.getNextMediaPeriodInfo(MediaPeriodQueue.java:126)
02-25 14:46:57.267 3101-5096/? E/art:     at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod(ExoPlayerImplInternal.java:1525)
02-25 14:46:57.267 3101-5096/? E/art:     at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1399)
02-25 14:46:57.267 3101-5096/? E/art:     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:513)
02-25 14:46:57.267 3101-5096/? E/art:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
02-25 14:46:57.267 3101-5096/? E/art:     at android.os.Handler.dispatchMessage(Handler.java:98)
02-25 14:46:57.267 3101-5096/? E/art:     at android.os.Looper.loop(Looper.java:135)
02-25 14:46:57.267 3101-5096/? E/art:     at android.os.HandlerThread.run(HandlerThread.java:61)
`````
My native language is Chinese, please forgive me if my English is not good
I suspect it's a matter of switching mediasource frequently. I wonder if I can switch frequently
````
   /**
     * 切换mediaSource
     */
    public void next(int nextWindowIndex) {
        if (mInternalPlayer == null) {
            return;
        }
        Timeline timeline = mInternalPlayer.getCurrentTimeline();
        if (timeline.isEmpty()) {
            return;
        }
        int windowIndex = mInternalPlayer.getCurrentWindowIndex();
        if (nextWindowIndex != C.INDEX_UNSET) {
            mInternalPlayer.seekTo(nextWindowIndex, C.TIME_UNSET);
        } else if (timeline.getWindow(windowIndex, window, false).isDynamic) {
            mInternalPlayer.seekTo(windowIndex, C.TIME_UNSET);
        }
    }
````

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

I'll need to reproduce the issue somehow to help with this. I am not sure I understand what switching media source means. If you mean either seeking to a different window or repreparing the player, then those actions shouldn't be an issue.

Can you provide steps to reproduce the issue in the demo app? If it requires some minor changes in the code you may point me to a github fork for me to look at.

**Comment by star-andy** [comment]
I'm really sorry that I can't demo this problem again, it just happened by accident

**Comment by AquilesCanta** [comment]
I'll close for now. Make sure you fill the issue template if you have to create a new issue. It's also extremely helpful if you can reproduce in the demo app.

**Comment by star-andy** [comment]
![image](https://user-images.githubusercontent.com/15726024/54094867-c6493d00-43de-11e9-8a16-e46e9519c437.png)
I wonder if this information is useful

**Comment by AquilesCanta** [comment]
The only way for us to debug this is that we are able to reproduce ourselves. An out of memory error doesn't necessarily mean there is a bug in the library. I'm sorry I cannot help more with the given information.
