### ISSUE TITLE
Playback failed after new key request with Multi Key and Key rotation server setting

### ISSUE THREAD

**Issue by rajeshghosh1978** [google/ExoPlayer#5576]
We use Widevine DRM together with ExoPlayer. Our DRM policy support multi key with key rotation. Based on the documentation (https://google.github.io/ExoPlayer/drm.html) we have to pass multiSession true while constructing DefaultDrmSessionManager, since we are supporting Key Rotation . But using that we are getting a black screen in every 3 seconds in LTE mode (Not happening with Wifi). 

Then in the same documentation, we have found that in case of "License server responds with all keys for the content" (which is also supported by our server) we should not pass multisession as true. So we started passing multisession as false. This solved our flickering problem. 

But when our key rotates, we are getting playback failure with the below exception

2019-02-26 20:05:12.413 677-3978/? E/WVCdm: [policy_engine.cpp(55):CanDecryptContent] PolicyEngine::CanDecryptContent Key 'E6E1C48970A047D09D31212ED8AC3EBA' not in license.
2019-02-26 20:05:12.413 677-3978/? E/WVCdm: Decrypt error result in session sid1592 during encrypted block: 5
2019-02-26 20:05:12.419 8496-8724/com.verizon.fios.tv.dev E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Crypto key not available
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1025)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.media.MediaCodec$CryptoException: Crypto key not available
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2608)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1016)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 

### Reproduction steps
DRM policy must support Multi Key with Key Rotation and while DefaultDrmSessionManager , pass multisession false.
### Version of ExoPlayer being used
2.9.3 and 2.9.6 (Tried with both)

### Device(s) and version(s) of Android being used
Pixel XL, Galaxy S8

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
