### ISSUE TITLE
ExoPlayer doesn't play MP4 videos on certain devices

### ISSUE THREAD

**Issue by janegrytsenko** [google/ExoPlayer#561]
Hi everyone! 
I try to run demo app for playing mp4 videos on different devices. The first one uses  OMX.qcom.video.decoder.avc and playing my file without troubles. The second one uses OMX.amlogic.avc.decoder.awesome and doesn't play video, playback state always buffering, the logcat always says:
Warning message AMessage(what = 'omx ', target = 5) = {
    int32_t type = 0
    void *node = 0xf
    int32_t event = 2130706433
    int32_t data1 = 0
    int32_t data2 = 0
    } unhandled in root state.

during I've canceled playback. 
I tried to use software decoder - OMX.google.h264.decoder, then playback status at once idle and logcat says:
06-18 18:13:28.099  18290-18592/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.google.h264.decoder] ERROR(0x80001001)
06-18 18:13:28.099  18290-18592/com.google.android.exoplayer.demo E/MediaCodec﹕ Codec reported an error. (omx error 0x80001001, internalError -2147483648)
06-18 18:13:28.109  18290-18583/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal runtime error.
    java.lang.IllegalStateException
            at android.media.MediaCodec.dequeueInputBuffer(Native Method)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:582)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

The second device has Android 4.2.2 and kernel version 3.0.50 (if it is useful information).
So, is it device trouble? Why video doesn't play with these codecs?

**Comment by janegrytsenko** [comment]
The same situation with .mkv files, using TYPE_WEBM.

**Comment by janegrytsenko** [comment]
I've found, that codec.dequeueOutputBuffer with OMX.amlogic.avc.decoder.awesome and TYPE_MP4 always returns -1.

**Comment by ojw28** [comment]
Please provide additional information as described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html). Thanks.
