### ISSUE TITLE
Problem with smooth streams protected using playready drm

### ISSUE THREAD

**Issue by ThorAsgardDev** [google/ExoPlayer#5614]
Hello,

I'm trying to play a smooth stream protected using playready drm.
I'm using exoplayer 2.9.4 on Android TV with min Android SDK 26
The smooth file is correctly downloaded and parsed, then the mediaDrm session is opened and then at the first call to com.google.android.exoplayer2.drm.FrameworkMediaDrm#getKeyRequest I get the error:

```
E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.shouldWaitForKeys(MediaCodecRenderer.java:1036)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:989)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:443)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:438)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:391)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:327)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:164)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:559)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1075)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:412)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request
        at android.media.MediaDrm.getKeyRequest(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:136)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:388)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:327) 
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:164) 
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:559) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1075) 
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:412) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

The call to mediaDrm.getKeyRequest(scope, initData, mimeType, keyType, optionalParameters); throws the exception.
After some debugging I can say that:
scope is the sessionId
initData seems to be a value extracted from the smooth file
mimeType is "video/mp4"
keyType is 1 (that is corresponding to KEY_TYPE_STREAMING)
optionalParameters is null

About the initData, when I transform the byte[] into a String I can read some characters like "pssh" lost inside binary data.

Could you please help me to understand why I get this exception ?

Additional information.
This stream is correctly played on device which doesn't support playready drm like this:
https://docs.microsoft.com/en-us/playready/images/client_level_app.png
while I'm trying to play this stream on device which support playready drm like this:
https://docs.microsoft.com/en-us/playready/images/client_level_os_soc.png
I don't know if this can be a problem.

Thanks for your help.

**Comment by AquilesCanta** [comment]
Please don't ignore the [template contents](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md). Provide the missing items and I will reopen. Specially important: sample content and bugreport.

**Comment by ThorAsgardDev** [comment]
### [REQUIRED] Content description
I'm trying to play a smooth stream protected using playready drm.
The smooth file is correctly downloaded and parsed, then the mediaDrm session is opened and then at the first call to com.google.android.exoplayer2.drm.FrameworkMediaDrm#getKeyRequest I get the error:

```
E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.shouldWaitForKeys(MediaCodecRenderer.java:1036)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:989)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:443)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:438)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:391)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:327)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:164)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:559)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1075)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:412)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request
        at android.media.MediaDrm.getKeyRequest(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:136)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:388)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:327) 
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:164) 
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:559) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1075) 
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:412) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```		
		
The call to mediaDrm.getKeyRequest(scope, initData, mimeType, keyType, optionalParameters); throws the exception.
After some debugging I can say that:
scope is the sessionId
initData seems to be a value extracted from the smooth file
mimeType is "video/mp4"
keyType is 1 (that is corresponding to KEY_TYPE_STREAMING)
optionalParameters is null

About the initData, when I transform the byte[] into a String I can read some characters like "pssh" lost inside binary data.

Could you please help me to understand why I get this exception ?

Additional information.
This stream is correctly played on device which doesn't support playready drm like this:
https://docs.microsoft.com/en-us/playready/images/client_level_app.png
while I'm trying to play this stream on device which support playready drm like this:
https://docs.microsoft.com/en-us/playready/images/client_level_os_soc.png
I don't know if this can be a problem.


### [REQUIRED] Link to test content
The stream url is only available in France using a private login/password so I can't give you access :(

### [REQUIRED] Version of ExoPlayer being used
Exoplayer 2.9.4

### [REQUIRED] Device(s) and version(s) of Android being used
NVIDIA Shield, Android TV with min Android SDK 26

**Comment by johnsim** [comment]
I am not the PlayReady expert (I will get one engaged), nor Exoplayer expert, but the fact that you see "pssh" inside the init data may be at the heart of the problem. The PlayReady component might be expecting the payload of the pssh box, not the box itself nor the full init segment.

**Comment by ThorAsgardDev** [comment]
hi johnsim,
Thanks for the info, I will investigate this point.

**Comment by AquilesCanta** [comment]
Without access to the stream there is nothing I can do to help. Plus, I don't think you've provided a bugreport.

> but the fact that you see "pssh" inside the init data may be at the heart of the problem

I seem to remember PlayReady CDM implementations that expect a pssh as init data, so I wouldn't count on this.

**Comment by ThorAsgardDev** [comment]
They are a lot of private information in a bugreport. Could you please tell me what file/info you need so that I can reduce the private data.
