### ISSUE TITLE
UDP stream audio discontinuity making screen freeze

### ISSUE THREAD

**Issue by kaemanspk** [google/ExoPlayer#5638]
### [REQUIRED] Content description
Head end UDP stream playback audio discontinuity making video freeze;

2019-03-15 18:09:43.605 13089-13189/com.google.android.exoplayer2.demolatest E/AudioTrack: Discontinuity detected [expected 3551951767, got 3552239767]
2019-03-15 18:10:17.919 13089-13189/com.google.android.exoplayer2.demolatest E/AudioTrack: Discontinuity detected [expected 3586543767, got 3586799767]
2019-03-15 18:11:04.952 13089-13189/com.google.android.exoplayer2.demolatest E/AudioTrack: Discontinuity detected [expected 3633711767, got 3633999767]

### [REQUIRED] Link to test content
video sent to dev.exoplayer@gmail.com

### [REQUIRED] Version of ExoPlayer being used
Exoplayer 2.9.4

### [REQUIRED] Device(s) and version(s) of Android being used
Amlogic 905X2 devices
Android 9 (pie) API 28

**Comment by kaemanspk** [comment]
overall can you please suggest how to handle sudden fall of stream Discontinuity detected [expected 3633711767, got 3633999767] gracefully.

**Comment by tonihei** [comment]
The stream looks broken and the reported audio discontinuities likely happen because the audio timestamps don't match their declared duration. 

When I try to play the stream on another device with the ffmpeg extension, I also get decoding problems like "Error in avcodec_send_packet: Invalid data found when processing input" which let playback fail completely.

**Comment by kaemanspk** [comment]
We are playing live stream from head end and some time getting error like following; my expectation is Exoplayer is handling some malfunction of the stream loading OOM error with retry count.
Is this possible to handle audio related error in the same way. Also we suspect it related to including FFMPEG extension for AC3 audio handling. I just shared other stream over mail to your perusal.

1) Observation while streaming (UDP) through tsplay in loop then we found Exoplayer playback get struck on every tsplay loop.

Playeractivity onPlayerError com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.ext.ffmpeg.FfmpegDecoderException: Error decoding (see logcat). Code: -1094995529
	at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.render(SimpleDecoderAudioRenderer.java:302)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:537)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: com.google.android.exoplayer2.ext.ffmpeg.FfmpegDecoderException: Error decoding (see logcat). Code: -1094995529
	at com.google.android.exoplayer2.ext.ffmpeg.FfmpegDecoder.decode(FfmpegDecoder.java:110)
	at com.google.android.exoplayer2.ext.ffmpeg.FfmpegDecoder.decode(FfmpegDecoder.java:33)
	at com.google.android.exoplayer2.decoder.SimpleDecoder.decode(SimpleDecoder.java:224)
	at com.google.android.exoplayer2.decoder.SimpleDecoder.run(SimpleDecoder.java:189)
	at com.google.android.exoplayer2.decoder.SimpleDecoder.access$000(SimpleDecoder.java:25)
	at com.google.android.exoplayer2.decoder.SimpleDecoder$1.run(SimpleDecoder.java:67)

**Comment by kaemanspk** [comment]
we compared stream playback with other player build on webOS next to each; played same stream noted webOS player played smooth over coming all the issues. just sharing the observation;

**Comment by tonihei** [comment]
The second stream indicates for some of its audio samples that these should not be decoded. ExoPlayer does not currently handle this flag correctly. After adding support for this, the track plays fine with the platform decoders. 

However, I have the impression that was not even intended and the streams are still somewhat broken.

**Comment by kaemanspk** [comment]
Thank you. Please share what is the support/fix that you have added and how we can use it. This is a broadcast stream from Direct TV headend so we really need the fix.

**Comment by kaemanspk** [comment]
hello team, keenly awaiting your response.

**Comment by tonihei** [comment]
Please see the commit linked above for the fix. Closing the issue.
