### ISSUE TITLE
Playing playist from provided position

### ISSUE THREAD

**Issue by dennykurniawan48** [google/ExoPlayer#5646]
### [REQUIRED] Searched documentation and issues
I have same problem with this issue, when try to playing from playlist: [https://github.com/google/ExoPlayer/issues/4375](https://github.com/google/ExoPlayer/issues/4375 )

### [REQUIRED] Question
when I want to play from spesific position that I deliver from intent, but position 0 always playing for some seconds, and then jump to provided position.
Exoplayer version : 2.9.6
This is my code :
```
        ArrayList<FilesResult> result = intent.getParcelableArrayListExtra("send");
        data = new ArrayList<>(result.size());
        data.addAll(result);
        position = intent.getIntExtra("pos", 0);
        DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, "MyApp"));
        ConcatenatingMediaSource mediaSource = new ConcatenatingMediaSource();
        for(FileResult res : data){
            MediaSource source = new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(res.getUrl()));
            mediaSource.addMediaSource(source);
        }
        player.prepare(mediaSource);
        player.seekTo(position, C.TIME_UNSET);
        player.setPlayWhenReady(true);
```
Thanks in advance.

**Comment by tonihei** [comment]
Did you try to do the `seekTo` first and then prepare with `resetPosition=false`?

**Comment by dennykurniawan48** [comment]
Thanks for your reply, I try to change `resetPosition `to false and put `seekto `above it, but I got `IndexOutOfBound exception`:
```
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
        at com.google.android.exoplayer2.source.ConcatenatingMediaSource$ConcatenatedTimeline.getFirstWindowIndexByChildIndex(ConcatenatingMediaSource.java:1011)
        at com.google.android.exoplayer2.source.AbstractConcatenatedTimeline.getPeriodByUid(AbstractConcatenatedTimeline.java:207)
        at com.google.android.exoplayer2.ExoPlayerImpl.getCurrentWindowIndex(ExoPlayerImpl.java:468)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:635)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.generatePlayingMediaPeriodEventTime(AnalyticsCollector.java:653)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.onTimelineChanged(AnalyticsCollector.java:442)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners(ExoPlayerImpl.java:779)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:716)
        at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:647)
        at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:592)
        at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:125)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5293)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by dennykurniawan48** [comment]
I try to implement solution from @ojw28 and modified my code to : 
```
player.setPlayWhenReady(false);
ArrayList<FilesResult> result = intent.getParcelableArrayListExtra("send");
        data = new ArrayList<>(result.size());
        data.addAll(result);
        position = intent.getIntExtra("pos", 0);
        DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, "MyApp"));
        ConcatenatingMediaSource mediaSource = new ConcatenatingMediaSource();
        for(FileResult res : data){
            MediaSource source = new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(res.getUrl()));
            mediaSource.addMediaSource(source);
        }
        player.prepare(mediaSource);
        player.seekTo(position, C.TIME_UNSET);
        player.setPlayWhenReady(true);
```

and then update my UI from `onTracksChanged` to `onPositionDiscontinuity`. Now it's works, thank you.

**Comment by ojw28** [comment]
The new [playlist API](https://medium.com/google-exoplayer/a-top-level-playlist-api-for-exoplayer-abe0a24edb55) handles this in a much more intuitive way (i.e., what you would expect to work, should now just work!). So I don't think we need special documentation for this any more.
