### ISSUE TITLE
Can't resolve method getCurrentMappedTrackInfo()

### ISSUE THREAD

**Issue by namespace7** [google/ExoPlayer#5654]
I'm getting Error here ..
**MappingTrackSelector.MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();**
saying **cannot resolve method getCurrentMappedtrackInfo**
can somebody help me with this?
![image](https://user-images.githubusercontent.com/29954682/54661464-52a2e080-4b00-11e9-8671-48b9ac172de5.png)

**Comment by namespace7** [comment]
I'm using exoplayer:2.8.4

**Comment by tonihei** [comment]
Please try to clean Android Studio caches and rebuild the project. Sometimes the Android Studio cache doesn't pick up changes very well.

**Comment by namespace7** [comment]
The error doesn't go ,even after cleaning the project caches! is that a syntax error ?

**Comment by tonihei** [comment]
That's not possible to say based on a screenshot. And generally, we can't help you debug issues with your app. Android Studio should give you enough information to check if it's a syntax error or not.

**Comment by namespace7** [comment]
here are some Errors
    --------- beginning of crash
2019-03-20 16:23:41.139 28421-28421/com.placidvision.streamtest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.placidvision.streamtest, PID: 28421
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.exoplayer2.trackselection.MappingTrackSelector$MappedTrackInfo com.google.android.exoplayer2.trackselection.MappingTrackSelector.getCurrentMappedTrackInfo()' on a null object reference
        at com.placidvision.streamtest.VideoStream.change_Quality(VideoStream.java:165)
        at com.placidvision.streamtest.VideoStream.access$300(VideoStream.java:50)
        at com.placidvision.streamtest.VideoStream$2.onClick(VideoStream.java:156)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24701)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
