### ISSUE TITLE
Decoder init failed: OMX.hisi.video.decoder.hevc

### ISSUE THREAD

**Issue by GavinQin** [google/ExoPlayer#5672]
com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.hisi.video.decoder.hevc, Format(0, null, null, video/hevc, null, -1, null, [7680, 4320, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:207)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.hisi.video.decoder.hevc, Format(0, null, null, video/hevc, null, -1, null, [7680, 4320, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1967)
        at android.media.MediaCodec.configure(MediaCodec.java:1896)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 

### [REQUIRED] Content description
![image](https://user-images.githubusercontent.com/724320/54895416-7009ed00-4efa-11e9-91a3-875055ab9285.png)

 

### [REQUIRED] Version of ExoPlayer being used
2.8.1 and 2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
Huawei Mate20 Pro
android 9.0

**Comment by marcbaechinger** [comment]
Given the stack trace this may be a codec issue or an issue with how the codec is configured. We would like to investigate but we need a stream url for this. 

Can you provide us with a bug report and a stream url so we can try to reproduce this?

**Comment by GavinQin** [comment]
The stream url is http://182.138.27.252/8k/zstq/playlist.m3u8

**Comment by GavinQin** [comment]
> Given the stack trace this may be a codec issue or an issue with how the codec is configured. We would like to investigate but we need a stream url for this.
> 
> Can you provide us with a bug report and a stream url so we can try to reproduce this?

the stream url is http://182.138.27.252/8k/zstq/playlist.m3u8.

**Comment by marcbaechinger** [comment]
Thanks!

The playlist has a single video track only which is 8k. If this was an adaptive stream with different resolutions available, the adaptive track selection would just not use that track. The device actually does not support that stream but ExoPlayer tries to play it regardless because it is the only stream in the playlist. 

If you play the stream with the demo app you see that the track selection dialog has grayed out the video track with the resolution of 7680x4320. The EventLogger which the demo app uses, logs the following to the debug console:

```
2019-03-26 15:27:33.950 16284-16284/? D/EventLogger: tracksChanged [8.55, 0.00, window=0, period=0, 
2019-03-26 15:27:33.950 16284-16284/? D/EventLogger:   Renderer:0 [
2019-03-26 15:27:33.950 16284-16284/? D/EventLogger:     Group:0, adaptive_supported=N/A [
2019-03-26 15:27:33.950 16284-16284/? D/EventLogger:       [X] Track:0, id=0, mimeType=video/hevc, res=7680x4320, supported=NO_EXCEEDS_CAPABILITIES
2019-03-26 15:27:33.950 16284-16284/? D/EventLogger:     ]
2019-03-26 15:27:33.950 16284-16284/? D/EventLogger:   ]
2019-03-26 15:27:33.950 16284-16284/? D/EventLogger:   Renderer:1 [
2019-03-26 15:27:33.950 16284-16284/? D/EventLogger:     Group:0, adaptive_supported=N/A [
2019-03-26 15:27:33.950 16284-16284/? D/EventLogger:       [X] Track:0, id=1/15, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, language=und, supported=YES
2019-03-26 15:27:33.950 16284-16284/? D/EventLogger:     ]
2019-03-26 15:27:33.950 16284-16284/? D/EventLogger:   ]
2019-03-26 15:27:33.950 16284-16284/? D/EventLogger:   Renderer:2 [
2019-03-26 15:27:33.950 16284-16284/? D/EventLogger:     Group:0, adaptive_supported=N/A [
2019-03-26 15:27:33.951 16284-16284/? D/EventLogger:       [ ] Track:0, id=1/8228, mimeType=application/cea-608, supported=YES
2019-03-26 15:27:33.951 16284-16284/? D/EventLogger:     ]
2019-03-26 15:27:33.951 16284-16284/? D/EventLogger:   ]
2019-03-26 15:27:33.951 16284-16284/? D/EventLogger:   Renderer:3 [
2019-03-26 15:27:33.951 16284-16284/? D/EventLogger:     Group:0, adaptive_supported=N/A [
2019-03-26 15:27:33.951 16284-16284/? D/EventLogger:       [X] Track:0, id=1/21, mimeType=application/id3, supported=YES
2019-03-26 15:27:33.951 16284-16284/? D/EventLogger:     ]
2019-03-26 15:27:33.951 16284-16284/? D/EventLogger:   ]
2019-03-26 15:27:33.951 16284-16284/? D/EventLogger: ]
```
It marks the track with supported=NO_EXCEEDS_CAPABILITIES.

**Comment by GavinQin** [comment]
how can i solve it?
does exoplayer support 8k h265 video?

**Comment by GavinQin** [comment]
the vlc player on tv can play this stearm url.
how can i solve it?
does exoplayer can support 8k h265 video?

**Comment by marcbaechinger** [comment]
ExoPlayer would support this if the underlaying hardware is capable of decoding and rendering such a stream.

I think it's not the software but the device which is not capable. I would guess that VLC can't play this on the same device on which it fails with ExoPlayer. On an Android device VLC is either using the same hardware decoder as ExoPlayer or does decode/render in software. It would, in the hardware decoder case, run into the same issue as ExoPlayer on that very device. If VLC is using a software decoder I would still think it would not have a good outcome for a 8K stream to be rendered in software.

Have you tried VLC running that stream on that device? 

Aside: is it worth checking whether a given device has a 8K display to display the stream in 8K? If not, it could make sense to scale down the stream before sending it over the network to expensively decode and scale it down for a display which shows 4K or Full HD?
