### ISSUE TITLE
Huawei M3: MP4 can't play

### ISSUE THREAD

**Issue by surcreak** [google/ExoPlayer#5676]
This the log：
```
2019-03-25 16:59:56.709 1559-1693/? I/ActivityManager: Displayed com.zhangmen.kids.apad/.guidein.ui.activity.GuidanceActivity: +777ms
2019-03-25 16:59:56.712 681-681/? I/OMX-VDEC-1080P: component_init: OMX.qcom.video.decoder.avc : fd=19
2019-03-25 16:59:56.718 681-681/? I/OMX-VDEC-1080P: omx_vdec::component_init() success : fd=19
2019-03-25 16:59:56.718 14054-14169/com.zhangmen.kids.apad I/ACodec: In onAllocateComponent create compenent, codec name: OMX.qcom.video.decoder.avc
2019-03-25 16:59:56.721 14054-14168/com.zhangmen.kids.apad I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 14391297
2019-03-25 16:59:56.722 681-2275/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
2019-03-25 16:59:56.722 14054-14169/com.zhangmen.kids.apad I/HwExtendedCodec: mime is [video/avc] at setVideoFormat
2019-03-25 16:59:56.726 681-2275/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
2019-03-25 16:59:56.726 681-2275/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.configureVideoTunnelMode not implemented
2019-03-25 16:59:56.726 681-2275/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.useAndroidNativeBuffer is supported
2019-03-25 16:59:56.727 681-2277/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.describeHDRStaticInfo not implemented
2019-03-25 16:59:56.729 681-2277/? E/OMX-VDEC-1080P: Does not handle dataspace request
2019-03-25 16:59:56.729 681-2277/? E/OMXNodeInstance: getConfig(2a902f4:qcom.decoder.avc, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
2019-03-25 16:59:56.730 1559-19538/? W/System.err: java.lang.SecurityException: uid 10190 does not have android.permission.UPDATE_DEVICE_STATS.
2019-03-25 16:59:56.730 1559-19538/? W/System.err:     at android.app.ContextImpl.enforce(ContextImpl.java:1760)
2019-03-25 16:59:56.730 1559-19538/? W/System.err:     at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
2019-03-25 16:59:56.730 1559-19538/? W/System.err:     at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1204)
2019-03-25 16:59:56.730 1559-19538/? W/System.err:     at com.android.server.am.BatteryStatsService.noteStartVideo(BatteryStatsService.java:760)
2019-03-25 16:59:56.730 1559-19538/? W/System.err:     at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:72)
2019-03-25 16:59:56.731 1559-19538/? W/System.err:     at android.os.Binder.execTransact(Binder.java:565)
2019-03-25 16:59:56.740 681-2275/? E/OMX-VDEC-1080P: Extension: OMX.img.index.scalingdown not implemented
2019-03-25 16:59:56.752 681-31517/? I/MediaPlayerService: MediaPlayerService::getOMX
2019-03-25 16:59:56.752 681-14184/? E/OMX-VDEC-1080P: OMX_COMPONENT_GENERATE_HARDWARE_ERROR
2019-03-25 16:59:56.752 681-14184/? E/OMX-VDEC-1080P: ERROR: Sending OMX_ErrorHardware to Client
2019-03-25 16:59:56.753 14054-14186/com.zhangmen.kids.apad I/OMXClient: MuxOMX ctor
2019-03-25 16:59:56.754 14054-14169/com.zhangmen.kids.apad E/ACodec: [OMX.qcom.video.decoder.avc] ERROR(0x80001009)
2019-03-25 16:59:56.754 14054-14169/com.zhangmen.kids.apad E/ACodec: signalError(omxError 0x80001009, internalError -2147483648)
2019-03-25 16:59:56.755 14054-14168/com.zhangmen.kids.apad E/MediaCodec: Codec reported err 0x80001009, actionCode 0, while in state 6
2019-03-25 16:59:56.756 681-14183/? E/OMX-VDEC-1080P: Dropping message 11 since client expected to be in error state
2019-03-25 16:59:56.756 1559-9365/? W/System.err: java.lang.SecurityException: uid 10190 does not have android.permission.UPDATE_DEVICE_STATS.
2019-03-25 16:59:56.756 1559-9365/? W/System.err:     at android.app.ContextImpl.enforce(ContextImpl.java:1760)
2019-03-25 16:59:56.756 1559-9365/? W/System.err:     at android.app.ContextImpl.enforcePermission(ContextImpl.java:1773)
2019-03-25 16:59:56.757 1559-9365/? W/System.err:     at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1204)
2019-03-25 16:59:56.757 1559-9365/? W/System.err:     at com.android.server.am.BatteryStatsService.noteStopVideo(BatteryStatsService.java:771)
2019-03-25 16:59:56.757 1559-9365/? W/System.err:     at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:81)
2019-03-25 16:59:56.757 1559-9365/? W/System.err:     at android.os.Binder.execTransact(Binder.java:565)
2019-03-25 16:59:56.758 14054-14186/com.zhangmen.kids.apad I/OMXMaster: makeComponentInstance(OMX.google.aac.decoder) in ngmen.kids.apad process
2019-03-25 16:59:56.767 14054-14186/com.zhangmen.kids.apad I/ACodec: In onAllocateComponent create compenent, codec name: OMX.google.aac.decoder
2019-03-25 16:59:56.768 14054-14186/com.zhangmen.kids.apad E/OMXNodeInstance: setConfig(36e60001:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
2019-03-25 16:59:56.768 14054-14186/com.zhangmen.kids.apad I/ACodec: codec does not support config priority (err -2147483648)
2019-03-25 16:59:56.768 14054-14186/com.zhangmen.kids.apad E/OMXNodeInstance: setConfig(36e60001:google.aac.decoder, ConfigOperatingRate(0x6f800003)) ERROR: Undefined(0x80001001)
2019-03-25 16:59:56.768 14054-14186/com.zhangmen.kids.apad I/ACodec: codec does not support config operating rate (err -2147483648)
2019-03-25 16:59:56.768 14054-14187/com.zhangmen.kids.apad W/SimpleSoftOMXComponent: checkTransitions port is not populate
2019-03-25 16:59:56.768 14054-14186/com.zhangmen.kids.apad W/SimpleSoftOMXComponent: checkTransitions port is not populate
2019-03-25 16:59:56.770 14054-14187/com.zhangmen.kids.apad I/SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->1 channels
2019-03-25 16:59:56.772 14054-14165/com.zhangmen.kids.apad E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2595)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1287)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2019-03-25 16:59:56.776 14054-14169/com.zhangmen.kids.apad E/Surface: getSlotFromBufferLocked: unknown buffer: 0xc50a10c0
2019-03-25 16:59:56.776 14054-14169/com.zhangmen.kids.apad W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 14 to native window
2019-03-25 16:59:56.777 14054-14169/com.zhangmen.kids.apad E/Surface: getSlotFromBufferLocked: unknown buffer: 0xc50a1180
2019-03-25 16:59:56.777 14054-14169/com.zhangmen.kids.apad W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 13 to native window
2019-03-25 16:59:56.777 14054-14169/com.zhangmen.kids.apad E/Surface: getSlotFromBufferLocked: unknown buffer: 0xc50a11e0
2019-03-25 16:59:56.777 14054-14169/com.zhangmen.kids.apad W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 12 to native window
2019-03-25 16:59:56.777 14054-14108/com.zhangmen.kids.apad I/CrashReport: rom:HuaWei/EMOTION/EmotionUI_5.1.3
2019-03-25 16:59:56.778 14054-14169/com.zhangmen.kids.apad E/Surface: getSlotFromBufferLocked: unknown buffer: 0xc50a12a0
2019-03-25 16:59:56.778 14054-14169/com.zhangmen.kids.apad W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 11 to native window
2019-03-25 16:59:56.781 681-2275/? I/OMX-VDEC-1080P: omx_vdec::component_deinit() complete
2019-03-25 16:59:56.784 681-2275/? I/OMX-VDEC-1080P: Exit OMX vdec Destructor: fd=19
2019-03-25 16:59:56.784 681-2275/? I/OMX-VDEC-1080P: Video slvp perflock released
2019-03-25 16:59:56.787 14054-14165/com.zhangmen.kids.apad E/ExoPlayerImplInternal: Stop failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2032)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:608)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:508)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:562)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:377)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:153)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:976)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:764)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:735)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:355)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```
Help me plase.

**Comment by marcbaechinger** [comment]
Can you please provide the information request by the issue template? We can't help you without the information asked for in the issue template.

You can find the issue template here: https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md

**Comment by surcreak** [comment]
[REQUIRED] Content description
Play sound, but no video.

[REQUIRED] Link to test content
Send email to dev.exoplayer@gmail.com.

[REQUIRED] Version of ExoPlayer being used
Version is 2.9.6.

[REQUIRED] Device(s) and version(s) of Android being used
Huawei M3青春版. android version 7.0.
 
thank you.

**Comment by marcbaechinger** [comment]
The video you sent plays fine on two different devices I tested with, one with Lollipop and on with Pie. So this seems to be a device specific codec issue. 

In the stack trace I find 

OMX_COMPONENT_GENERATE_HARDWARE_ERROR or 
"codec does not support config operating rate (err -2147483648)"

which seems to come from the codec implementation provided by the device.

**Comment by surcreak** [comment]
"Huawei M3青春版" don't support hard decodeing, can set to soft decode?
Thank you very much!

**Comment by marcbaechinger** [comment]
You can use a custom [MediaCodecSelector](https://github.com/google/ExoPlayer/blob/afba6386d333b993777ba74a81d7d8c9d2f808f7/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecSelector.java) and set it when you create the DefaultRenderersFactory:

```
DefaultRenderersFactory defaultRenderersFactory  = new DefaultRenderersFactory(
  /* context= */ this);
if (deviceNeedsSoftwareDecoderWorkaround()) {
  defaultRenderersFactory.setMediaCodecSelector(new CustomMediaCodecSelector());
}
player =
  ExoPlayerFactory.newSimpleInstance(
    /* context= */ this, defaultRenderersFactory, trackSelector, drmSessionManager);
```

So for your case the `CustomMediaCodecSelector` has to then select a software decoder if on the device in question. You could inspect `etc/media_codecs.xml` of the device and look which codecs are available and let the `CustomMediaCodecSelector.getDecoderInfos(String mimeType, boolean requiresSecureDecoder)` return a filtered list with only a subset of all decoders for the mimeType you want. Make sure to always return all decoders as a fallback in case your filtering for decoders of media_codecs.xml does not find what it expects.

**Comment by ojw28** [comment]
Can you reproduce this playing the same content in the ExoPlayer demo app? If not, is it possible you're passing an invalid `Surface` to the player?

**Comment by marcbaechinger** [comment]
Closing due to inactivity. Please reopen if you provide more into.
