### ISSUE TITLE
 Problem with DASH + WV - Error decrypting data: requested key has not been loaded

### ISSUE THREAD

**Issue by laurafuente** [google/ExoPlayer#5679]
Hi,

### [REQUIRED] Issue description
I'm seeing problems trying to play a DASH + WV stream at exoplayer 
When it plays the content during 3-5 minutes I get the following exception:
```
com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1025)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```
I have observed that at the same moment the exception is launched, a log trace is sent notifying that the decoder input format has been changed but the audio format that it's notified it's the same that the current audio track played.

At shaka player every 5 minutes there is a similar behaviour that notifies that the tracks has been changed but not track it's currently changed. But at shakaplayer the video is played correctly without showing any exception.

### [REQUIRED] Reproduction steps
I'm able to reproduce this issue at exoplayer 2.4.4 demo app and also at exoplayer 2.9.6 demo app playing the content during 3-6 minutes

### [REQUIRED] Link to test content
I've sent an e-mail to exoplayer team with the url of the content

### [REQUIRED] A full bug report captured from the device
Here there are some logs when this problem takes place:
```
2019-03-25 16:59:57.814 7231-7332/com.google.android.exoplayer2.demo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-03-25 16:59:57.814 7231-7332/com.google.android.exoplayer2.demo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-03-25 16:59:57.815 7231-7231/com.google.android.exoplayer2.demo D/EventLogger: timelineChanged [165.39, 29.00, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
2019-03-25 16:59:57.815 7231-7231/com.google.android.exoplayer2.demo D/EventLogger:   period [?]
2019-03-25 16:59:57.815 7231-7231/com.google.android.exoplayer2.demo D/EventLogger:   window [60.04, true, true]
2019-03-25 16:59:57.815 7231-7231/com.google.android.exoplayer2.demo D/EventLogger: ]
2019-03-25 16:59:57.817 7231-7333/com.google.android.exoplayer2.demo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-03-25 16:59:57.818 7231-7333/com.google.android.exoplayer2.demo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-03-25 16:59:58.119 7231-7231/com.google.android.exoplayer2.demo D/EventLogger: decoderInputFormatChanged [165.68, 29.28, window=0, period=0, audio, id=7, mimeType=audio/mp4a-latm, bitrate=48740, codecs=mp4a.40.5, channels=2, sample_rate=24000, language=und]
2019-03-25 16:59:58.440 7231-7348/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Executing->Idle
2019-03-25 16:59:58.454 7231-7348/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Idle->Loaded
2019-03-25 16:59:58.454 7231-7348/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Loaded
2019-03-25 16:59:58.454 7231-7348/com.google.android.exoplayer2.demo I/ACodec:  [OMX.google.aac.decoder] Now kWhatShutdownCompleted event : 8362
2019-03-25 16:59:58.454 7231-7348/com.google.android.exoplayer2.demo I/MediaCodec: Codec shutdown complete
2019-03-25 16:59:58.460 7231-7348/com.google.android.exoplayer2.demo I/ACodec:  [OMX.google.aac.decoder] Now uninitialized
2019-03-25 16:59:58.460 7231-7348/com.google.android.exoplayer2.demo I/ACodec:  [] Now kWhatShutdownCompleted event : 8362
2019-03-25 16:59:58.460 7231-7348/com.google.android.exoplayer2.demo I/MediaCodec: Codec shutdown complete
2019-03-25 16:59:58.471 7231-7327/com.google.android.exoplayer2.demo I/ACodec:  [] Now uninitialized
2019-03-25 16:59:58.475 7231-7392/com.google.android.exoplayer2.demo I/ACodec: [] onAllocateComponent
2019-03-25 16:59:58.480 7231-7392/com.google.android.exoplayer2.demo I/OMXClient: MuxOMX ctor
2019-03-25 16:59:58.489 7231-7392/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Loaded
2019-03-25 16:59:58.501 7231-7392/com.google.android.exoplayer2.demo I/ACodec: codec does not support config priority (err -2147483648)
2019-03-25 16:59:58.501 7231-7392/com.google.android.exoplayer2.demo I/ACodec: codec does not support config operating rate (err -2147483648)
2019-03-25 16:59:58.507 7231-7392/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Loaded->Idle
2019-03-25 16:59:58.515 7231-7392/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Idle->Executing
2019-03-25 16:59:58.517 7231-7231/com.google.android.exoplayer2.demo D/EventLogger: decoderInitialized [166.09, 29.63, window=0, period=0, audio, OMX.google.aac.decoder]
2019-03-25 16:59:58.519 7231-7392/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Executing
2019-03-25 16:59:58.560 7231-7327/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1025)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2478)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1016)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
2019-03-25 16:59:58.561 7231-7231/com.google.android.exoplayer2.demo D/EventLogger: droppedFrames [166.13, 29.71, window=0, period=0, 33]
2019-03-25 16:59:58.587 7231-7340/com.google.android.exoplayer2.demo I/ACodec: [OMX.Exynos.avc.dec.secure] Now Executing->Idle
2019-03-25 16:59:58.646 7231-7340/com.google.android.exoplayer2.demo D/SurfaceUtils: set up nativeWindow 0x752c3f8a10 for 1x1, color 0x2, rotation 0, usage 0x930
2019-03-25 16:59:58.666 7231-7340/com.google.android.exoplayer2.demo I/ACodec: [OMX.Exynos.avc.dec.secure] Now Idle->Loaded
2019-03-25 16:59:58.666 7231-7340/com.google.android.exoplayer2.demo I/ACodec: [OMX.Exynos.avc.dec.secure] Now Loaded
2019-03-25 16:59:58.666 7231-7340/com.google.android.exoplayer2.demo I/ACodec: SECURE PLAYBACK STOP / send intent to dvfshelper
2019-03-25 16:59:58.668 7231-7340/com.google.android.exoplayer2.demo I/ACodec:  [OMX.Exynos.avc.dec.secure] Now kWhatShutdownCompleted event : 8362
2019-03-25 16:59:58.671 7231-7339/com.google.android.exoplayer2.demo I/MediaCodec: Codec shutdown complete
2019-03-25 16:59:58.679 7231-7340/com.google.android.exoplayer2.demo I/ACodec:  [OMX.Exynos.avc.dec.secure] Now uninitialized
2019-03-25 16:59:58.679 7231-7340/com.google.android.exoplayer2.demo I/ACodec:  [] Now kWhatShutdownCompleted event : 8362
2019-03-25 16:59:58.680 7231-7339/com.google.android.exoplayer2.demo I/MediaCodec: Codec shutdown complete
2019-03-25 16:59:58.736 7231-7231/com.google.android.exoplayer2.demo D/EventLogger: decoderDisabled [166.31, 29.71, window=0, period=0, video]
2019-03-25 16:59:58.738 7231-7392/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Executing->Idle
2019-03-25 16:59:58.743 7231-7392/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Idle->Loaded
2019-03-25 16:59:58.743 7231-7392/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Loaded
2019-03-25 16:59:58.743 7231-7392/com.google.android.exoplayer2.demo I/ACodec:  [OMX.google.aac.decoder] Now kWhatShutdownCompleted event : 8362
2019-03-25 16:59:58.743 7231-7392/com.google.android.exoplayer2.demo I/MediaCodec: Codec shutdown complete
2019-03-25 16:59:58.745 7231-7392/com.google.android.exoplayer2.demo I/ACodec:  [OMX.google.aac.decoder] Now uninitialized
2019-03-25 16:59:58.746 7231-7392/com.google.android.exoplayer2.demo I/ACodec:  [] Now kWhatShutdownCompleted event : 8362
2019-03-25 16:59:58.746 7231-7392/com.google.android.exoplayer2.demo I/MediaCodec: Codec shutdown complete
2019-03-25 16:59:58.757 7231-7231/com.google.android.exoplayer2.demo D/EventLogger: drmSessionReleased [166.33, 29.71, window=0, period=0]
2019-03-25 16:59:58.757 7231-7231/com.google.android.exoplayer2.demo D/EventLogger: decoderDisabled [166.33, 29.71, window=0, period=0, audio]
2019-03-25 16:59:58.758 7231-7231/com.google.android.exoplayer2.demo D/EventLogger: mediaPeriodReleased [166.33, 29.71, window=0, period=0]
2019-03-25 16:59:58.759 7231-7231/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [166.33, 29.71, window=0]
    com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1025)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2478)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1016)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```
### [REQUIRED] Version of ExoPlayer being used
I'm able to reproduce this problem with exoplayer 2.4.4 and also at exoplayer 2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
I'm testing this with a mobile phone: Samsung SM-G930F with android version: 7.0

**Comment by laurafuente** [comment]
Issue edited

**Comment by marcbaechinger** [comment]
Thanks @laurafuente ! We are looking into this. Many thanks for your patience.

**Comment by marcbaechinger** [comment]
Thanks for your patience, @laurafuente! I looked into the stream you sent us by email. 

It appears to me that this is a live stream which required key rotation. So the error message you've seen complaining about the key not having been loaded may happen at the moment key rotation is requested.

I then added the drm_multi_session attribute. With this it apparently loads the keys which were missing without multi session enabled. This is an excerpt from the log which shows that new keys have been loaded after 166.45, 425.79 and 685.10 seconds of playback (about every 300 secs). 

```
2019-03-28 16:11:41.525 29122-29122/com.google.android.exoplayer2.demo D/EventLogger: drmSessionAcquired [1.88, 29.99, window=0, period=0]
2019-03-28 16:11:43.038 29122-29122/com.google.android.exoplayer2.demo D/EventLogger: drmKeysLoaded [3.39, 29.99, window=0, period=0]
2019-03-28 16:14:24.757 29122-29122/com.google.android.exoplayer2.demo D/EventLogger: drmSessionAcquired [165.11, 41.26, window=0, period=0]
2019-03-28 16:14:26.094 29122-29122/com.google.android.exoplayer2.demo D/EventLogger: drmKeysLoaded [166.45, 23.94, window=0, period=0]
2019-03-28 16:14:26.134 29122-29122/com.google.android.exoplayer2.demo D/EventLogger: drmSessionReleased [166.49, 23.94, window=0, period=0]
2019-03-28 16:18:43.879 29122-29122/com.google.android.exoplayer2.demo D/EventLogger: drmSessionAcquired [424.23, 29.30, window=0, period=0]
2019-03-28 16:18:44.522 29122-29122/com.google.android.exoplayer2.demo D/EventLogger: drmSessionReleased [424.88, 29.95, window=0, period=0]
2019-03-28 16:18:45.435 29122-29122/com.google.android.exoplayer2.demo D/EventLogger: drmKeysLoaded [425.79, 29.97, window=0, period=0]
2019-03-28 16:23:03.204 29122-29122/com.google.android.exoplayer2.demo D/EventLogger: drmSessionAcquired [683.56, 29.30, window=0, period=0]
2019-03-28 16:23:03.835 29122-29122/com.google.android.exoplayer2.demo D/EventLogger: drmSessionReleased [684.19, 29.95, window=0, period=0]
2019-03-28 16:23:04.747 29122-29122/com.google.android.exoplayer2.demo D/EventLogger: drmKeysLoaded [685.10, 29.97, window=0, period=0]
```

With this the streams seems to work as expected:

```
{
   "name": "#5679",
   "uri": "https://your_server/index.mpd",
   "drm_scheme": "widevine",
   "drm_license_url": "https://your_licence_url",
   "drm_multi_session": true
},
```

The demo app then passes `true` to the constructor of the constructor of the `DefaultDrmManager`:

```
new DefaultDrmSessionManager<>(uuid, mediaDrm, drmCallback, null, multiSession /* =true */);
```

You'll notice an audio glitch though, when the new key is loaded. This is a known limitation of the current key rotation implementation because loading the new keys is blocking for a short amount of time. We are currently working on improving this behavior.

**Comment by laurafuente** [comment]
Thanks for the answer
