### ISSUE TITLE
NoSuchElementExceptionat java.util.ArrayDeque.removeFirst

### ISSUE THREAD

**Issue by theboubougne** [google/ExoPlayer#5680]
Just released exoplayer in my app after 2 weeks of beta and I'm starting to see the following stack on Crahlytics
```
Fatal Exception: java.util.NoSuchElementException
       at java.util.ArrayDeque.removeFirst(ArrayDeque.java:264)
       at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:717)
       at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:647)
       at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:592)
       at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:125)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6863)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
I have no idea how to reproduce it as users haven't contacted me yet 
For now, only devices running Android 8 & 9  seems to be impacted

I'm using the latest version of ExoPlayer v2.9.6

**Comment by theboubougne** [comment]
As explained in the description this is all the information I have.
I'm getting this crash stacks from Crashlytics

**Comment by marcbaechinger** [comment]
When looking at the [line of code where the issue happens](https://github.com/google/ExoPlayer/blob/8ec4aad001667674da679f37136bf986ab0e8493/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImpl.java#L717) it appears that this should not happen if access to the list of pending updates is thread-safe.

I actually assume that access is thread-safe in case that ExoPlayer is accessed from the same thread only. There is an [FAQ item](https://google.github.io/ExoPlayer/faqs.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean) around this.

May I ask you to please check whether your app is following that rule of accessing ExoPlayer from a single thread only and let me know the findings?

**Comment by ojw28** [comment]
Closing on the assumption this is an application code thread safety issue.
