### ISSUE TITLE
DASH video resource 404 error

### ISSUE THREAD

**Issue by SumukhaK** [google/ExoPlayer#5688]
Hi, I have a playlist of 7 dash(.mpd) videos. I'm using Exoplayer version 2.8.4. Exoplayer is stuck in loading for the last two of them and I'm getting the following error in my logs. Other 5 videos plays seamlessly. What could be the reason. Thanks in advance.

```
11:41:39.322 31189-31221/com.example.exoplayercodelab E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:137)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

In my eventListner's  onPlayerError, this is the stackTrace of the error : 

 ```
com.google.android.exoplayer2.ExoPlaybackException
     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:349)
    at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:193)
     at android.os.HandlerThread.run(HandlerThread.java:65)
 Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
     at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
     at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
     at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:137)
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by AquilesCanta** [comment]
Hi @SumukhaK, the stack trace states it's a [404](https://en.wikipedia.org/wiki/HTTP_404) from the server. You should make sure that the URL you are providing to the player actually has a backing resource. If that's the case, then you should provide all elements required by the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md).

**Comment by SumukhaK** [comment]
Yes, you are right, it was mistake from one of my team member and since I don't have the access to verify, I jumped to the wrong conclusion. Thank you.
