### ISSUE TITLE
I m getting this exception   com.google.android.exoplayer2.util.Assertions.checkNotEmpty       

### ISSUE THREAD

**Issue by imvikasrai** [google/ExoPlayer#5706]
### [REQUIRED] Link to test content

https://drive.google.com/file/d/17cWyHBC2erYdgUXtLIF4S7yKi7Z3Bc1X/view?usp=sharing

### [REQUIRED] Issue description
I m getting  Internal runtime error.
    java.lang.IllegalArgumentException
        at com.google.android.exoplayer2.util.Assertions.checkNotEmpty in one project and in other version its working fine while the code and library version is same.

### [REQUIRED] Reproduction steps
Just play the video logcat shows me this exception

### [REQUIRED] A full bug report captured from the device
```
ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalArgumentException
        at com.google.android.exoplayer2.util.Assertions.checkNotEmpty(Assertions.java:138)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.<init>(DefaultHttpDataSource.java:148)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSourceFactory.createDataSourceInternal(DefaultHttpDataSourceFactory.java:81)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSourceFactory.createDataSourceInternal(DefaultHttpDataSourceFactory.java:22)
        at com.google.android.exoplayer2.upstream.HttpDataSource$BaseFactory.createDataSource(HttpDataSource.java:176)
        at com.google.android.exoplayer2.upstream.HttpDataSource$BaseFactory.createDataSource(HttpDataSource.java:166)
        at com.google.android.exoplayer2.upstream.DefaultDataSourceFactory.createDataSource(DefaultDataSourceFactory.java:65)
        at com.google.android.exoplayer2.upstream.DefaultDataSourceFactory.createDataSource(DefaultDataSourceFactory.java:25)
        at com.google.android.exoplayer2.source.ExtractorMediaSource.createPeriod(ExtractorMediaSource.java:342)
        at com.google.android.exoplayer2.MediaPeriodHolder.<init>(MediaPeriodHolder.java:82)
        at com.google.android.exoplayer2.MediaPeriodQueue.enqueueNextMediaPeriod(MediaPeriodQueue.java:152)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod(ExoPlayerImplInternal.java:1486)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1365)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:499)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:179)
        at android.os.HandlerThread.run(HandlerThread.java:61)
03-30 09:50:24.636 23832-23832/com.virinchi.mychat.staging E/EventLogger: playerFailed [0.01]
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:358)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:179)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalArgumentException
        at com.google.android.exoplayer2.util.Assertions.checkNotEmpty(Assertions.java:138)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.<init>(DefaultHttpDataSource.java:148)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSourceFactory.createDataSourceInternal(DefaultHttpDataSourceFactory.java:81)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSourceFactory.createDataSourceInternal(DefaultHttpDataSourceFactory.java:22)
        at com.google.android.exoplayer2.upstream.HttpDataSource$BaseFactory.createDataSource(HttpDataSource.java:176)
        at com.google.android.exoplayer2.upstream.HttpDataSource$BaseFactory.createDataSource(HttpDataSource.java:166)
        at com.google.android.exoplayer2.upstream.DefaultDataSourceFactory.createDataSource(DefaultDataSourceFactory.java:65)
        at com.google.android.exoplayer2.upstream.DefaultDataSourceFactory.createDataSource(DefaultDataSourceFactory.java:25)
        at com.google.android.exoplayer2.source.ExtractorMediaSource.createPeriod(ExtractorMediaSource.java:342)
        at com.google.android.exoplayer2.MediaPeriodHolder.<init>(MediaPeriodHolder.java:82)
        at com.google.android.exoplayer2.MediaPeriodQueue.enqueueNextMediaPeriod(MediaPeriodQueue.java:152)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod(ExoPlayerImplInternal.java:1486)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1365)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:499)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:179) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```
### [REQUIRED] Version of ExoPlayer being used
2.7.3

### [REQUIRED] Device(s) and version(s) of Android being used
Oppo f1 plus 
os version-marshmallow

**Comment by imvikasrai** [comment]
One thing is missing the ### [REQUIRED] Link to test content .I m not able to attach the video here. This issue happens with every video

**Comment by imvikasrai** [comment]
I added the  video link for testing below  ### [REQUIRED] Link to test content

**Comment by marcbaechinger** [comment]
There is an assertion which triggered an` java.lang.IllegalArgumentException` in the constructor of DefaultHttpDataSource on line 148. Have you checked why the assertion is throwing on that line?

```
at com.google.android.exoplayer2.util.Assertions.checkNotEmpty(Assertions.java:138)
at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.(DefaultHttpDataSource.java:148)
```

In case you find that there is an illegal argument passed to the constructor, check what you pass to the constructor. You could set a break point to this line in your IDE and then see whats coming as this argument. It may be you are passing something as the userAgent argument which the Assertion does not like.

It often worth looking into what is causing an exception to resolve them. Can you confirm you pass a valid userAgent to the constructor of DefaultHttpDataSource in all of your projects?

**Comment by ojw28** [comment]
Agreed this is highly likely to be an application code issue where an invalid (i.e. empty or null) `userAgent` is being passed to the `DefaultHttpDataSource` constructor or (more likely) the `DefaultHttpDataSourceFactory` constructor. @imvikasrai - Please check this and fix your code.

@marcbaechinger - We should probably add a `checkNotEmpty` assertion in the `DefaultHttpDataSourceFactory` constructor, so that when a developer does this, the failure occurs at the point where the application code does something wrong, rather than later on inside the player when the factory is actually used. Once that's done I think we can close this.
