### ISSUE TITLE
File name is too long to play

### ISSUE THREAD

**Issue by kouxinhong** [google/ExoPlayer#5713]
```
2019-04-02 10:52:55.234 8562-8671/{packagename} E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /data/user/0/{packagename}/cache/splash/YWRtaW5fYWRfc3BsYXNoXzFjNjAyODhjYjhjNDExZTE5Yzc2ZDRkZmJjMjJhNGMwLm1wNF8xNTU0MTEwMzQxM3.mp4: open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:73)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.FileNotFoundException: /data/user/0/{packagename}/cache/splash/YWRtaW5fYWRfc3BsYXNoXzFjNjAyODhjYjhjNDExZTE5Yzc2ZDRkZmJjMjJhNGMwLm1wNF8xNTU0MTEwMzQxM3.mp4: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:485)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:288)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:151)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:65)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:210)
        at libcore.io.IoBridge.open(IoBridge.java:471)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:288) 
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:151) 
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:65) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

```
 `YWRtaW5fYWRfc3BsYXNoXzFjNjAyODhjYjhjNDExZTE5Yzc2ZDRkZmJjMjJhNGMwLm1wNF8xNTU0MTEwMzQxM3.mp4` 
Rename
` 1234.mp4` 

everything is normal

filename No change sometimes success.

please help me，Thank you！

**Comment by ojw28** [comment]
Is the `{packagename}` part of the file path a result of you manually censoring the logcat, or was that actually part of the path the file that was trying to be read?

If it's actually part of the path then that looks like a problem with the file path that your code is providing to ExoPlayer. If it's manual censoring then that's not the problem, however in this case I doubt it's an ExoPlayer issue. It's more likely to be a limitation of the underlying file system, or else the file really isn't there.

It should also be noted that I think the Android platform is allowed to delete files from your cache directory, so I'm not sure that the file not being found is necessarily unexpected. If you want a guarantee that it wont be deleted, then shouldn't you be putting the file somewhere else?

**Comment by ojw28** [comment]
Closing due to lack of response.
