### ISSUE TITLE
Player is getting crashed when the content contains subtitles

### ISSUE THREAD

**Issue by himaswetha** [google/ExoPlayer#5717]
Getting below error and player is getting crased when selecting the DVB subtitle.

```
04-02 12:43:45.020 5457-6329/com.ericsson.MediaFirstUC.tv E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:79)
        at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.updatePeriodTrackSelection(ExoPlayerImplInternal.java:1656)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.reselectTracksInternal(ExoPlayerImplInternal.java:917)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:384)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
04-02 12:43:45.020 5457-5887/com.ericsson.MediaFirstUC.tv E/UCExoEventHandler: onPlayerError
04-02 12:43:45.020 5457-5487/com.ericsson.MediaFirstUC.tv D/NativeLog: Sending broadcast event 'DidSetVideoPlayerTextTrack' from 'WebVideoPlayer.AMC07947' async = true
04-02 12:43:45.021 5457-5887/com.ericsson.MediaFirstUC.tv E/UCExoPlayer: handlePlayerError
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:406)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:79)
        at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.updatePeriodTrackSelection(ExoPlayerImplInternal.java:1656)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.reselectTracksInternal(ExoPlayerImplInternal.java:917)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:384)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by andrewlewis** [comment]
Please provide the information requested in the issue template [here](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=).

**Comment by andrewlewis** [comment]
You may also want to try upgrading to a more recent version of the library.

**Comment by ojw28** [comment]
Closing due to lack of information.
