### ISSUE TITLE
Exoplayer error 

### ISSUE THREAD

**Issue by sophia-podo** [google/ExoPlayer#5720]
Hello, I have some questions.
When does the following error occur?
How can I fix it?
Is this a problem with device? or OS? or Firmware?
(using exoplayer version 2.9.2, supported widevine drm)

1.Operation not supported in this configuration.
```
android.media.MediaCodec$CryptoException: Operation not supported in this configuration
	at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
	at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2532)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(SourceFile:1016)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:664)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:4536)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:4536)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

2.Error decrypting data: unspecified error
```
android.media.MediaCodec$CryptoException: Error decrypting data: unspecified error
	at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
	at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2493)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(SourceFile:1016)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:664)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:4536)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:4536)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

3.Error decrypting data
```
android.media.MediaCodec$CryptoException: Error decrypting data.
	at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
	at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:956)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(SourceFile:1016)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:664)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:4536)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:4536)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

4.
```
android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
	at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
	at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2478)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(SourceFile:1016)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:664)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:4536)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:4536)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

5.This error occur when the security level of the device is L1, but operated L3.
if force down security level L1 to L3, this error not occur.

```
com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
	at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(SourceFile:443)
	at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(SourceFile:438)
	at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(SourceFile:2423)
	at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(SourceFile:2423)
	at com.google.android.exoplayer2.drm.DefaultDrmSession$PostResponseHandler.handleMessage(SourceFile:473)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
	at android.media.MediaDrm.provideKeyResponse(Native Method)
	at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(SourceFile:157)
	at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(SourceFile:2413)
	at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(SourceFile:2413)
	... 4 more
android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
	at android.media.MediaDrm.provideKeyResponse(Native Method)
	at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(SourceFile:157)
	at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(SourceFile:2413)
	at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(SourceFile:2413)
	at com.google.android.exoplayer2.drm.DefaultDrmSession$PostResponseHandler.handleMessage(SourceFile:473)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

6.
```
com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: General DRM error
    at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(SourceFile:443)
    at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(SourceFile:438)
    at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(SourceFile:2423)
    at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(SourceFile:2423)
    at com.google.android.exoplayer2.drm.DefaultDrmSession$PostResponseHandler.handleMessage(SourceFile:473)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: General DRM error
    at android.media.MediaDrm.provideKeyResponse(Native Method)
    at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(SourceFile:157)
    at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(SourceFile:2413)
    at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(SourceFile:2413)
    ... 4 more
android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: General DRM error
    at android.media.MediaDrm.provideKeyResponse(Native Method)
    at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(SourceFile:157)
    at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(SourceFile:2413)
    at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(SourceFile:2413)
    at com.google.android.exoplayer2.drm.DefaultDrmSession$PostResponseHandler.handleMessage(SourceFile:473)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.os.HandlerThread.run(HandlerThread.java:65)
```

7.
```
com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to restore keys: General DRM error
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(SourceFile:443)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.restoreKeys(SourceFile:371)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(SourceFile:328)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(SourceFile:164)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(SourceFile:559)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(SourceFile:1075)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(SourceFile:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:4536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:4536)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to restore keys: General DRM error
        at android.media.MediaDrm.restoreKeys(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.restoreKeys(SourceFile:183)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.restoreKeys(SourceFile:367)
        ... 10 more
android.media.MediaDrm$MediaDrmStateException: Failed to restore keys: General DRM error
        at android.media.MediaDrm.restoreKeys(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.restoreKeys(SourceFile:183)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.restoreKeys(SourceFile:367)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(SourceFile:328)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(SourceFile:164)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(SourceFile:559)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(SourceFile:1075)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(SourceFile:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:4536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:4536)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

too many devices, os and error..
I have not experienced this error, and it is an error from users.
Plz help me.

**Comment by andrewlewis** [comment]
To start investigating this we need more information. Are you able to get full bug reports from these error cases? If that's not possible, could you share some information about the content you are trying to play and what devices seem to be affected?

**Comment by andrewlewis** [comment]
Closing due to lack of activity.

**Comment by eyalpartner** [comment]
_**I can also reproduce:**_
**Log:**
 E MediaDrm-JNI: Illegal state exception: Failed to handle key response: DRM vendor-defined error: -2965 (-2965)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: Renderer error.
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.shouldWaitForKeys(MediaCodecRenderer.java:775)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:716)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:551)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:578)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:154)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2965
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onError(DefaultDrmSessionManager.java:610)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onKeysError(DefaultDrmSessionManager.java:605)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onKeyResponse(DefaultDrmSessionManager.java:597)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.access$900(DefaultDrmSessionManager.java:51)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSessionManager$PostResponseHandler.handleMessage(DefaultDrmSessionManager.java:685)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	... 2 more
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2965
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at android.media.MediaDrm.provideKeyResponse(Native Method)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(FrameworkMediaDrm.java:106)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onKeyResponse(DefaultDrmSessionManager.java:581)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: 	... 5 more
05-06 15:09:32.677   208  5936 D BerlinOmxComponentImpl: setState() line 903: OMX.Marvell.video_decoder.hevc.secure, state change, OMX_StateExecuting(3) -> OMX_StateIdle(2)
05-06 15:09:32.677   208  5936 D BerlinOmxAmpVideoDecoder: Function stop(), Line 1742, Function Enter
05-06 15:09:32.678 20625 20625 D MetricManager: Destroying player state manager
05-06 15:09:32.679 20625 20625 D MetricManager: Player is stopped
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: [0;34m[[0;34m(main)IFSExoPlayer2Pipe.java:2129->onPlayerError][0;32m[android][0;0m [1;31mIFS_ERROR: onPlayerError rendererIndex:0 type: 1 log:com.google.android.exoplayer2.ExoPlaybackException
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: IFSExoPlayer2Pipe.java:2129->onPlayerError
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: ExoPlayerImpl.java:504->handleEvent
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: ExoPlayerImpl.java:103->handleMessage
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: Handler.java:102->dispatchMessage
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: Looper.java:154->loop
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: ActivityThread.java:6077->main
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: Method.java:-2->invoke
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: ZygoteInit.java:865->run
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: ZygoteInit.java:755->main
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: [0;0m
05-06 15:09:32.680 20625 20625 W IFSExoPlayer2Pipe: [0;34m[[0;34m(main)IFSExoPlayer2Pipe.java:2162->onPlayerError][0;32m[android][0;0m [1;33munknown error exception[0;0m

**Details:**
This error occur when the security level of the device is L1 with exoplayer ver 2.8.4 
Content: HEVC +DASH
Android 7
If full adb logcat is needed please tell me, I have it

**Comment by andrewlewis** [comment]
@eyalpartner Please file a new issue and include all the information requested in the new issue template, especially a full bug report captured with `adb bugreport`.

**Comment by eyalpartner** [comment]
Thanks, I have created #5845
