### ISSUE TITLE
Can't play local m3u8 file in version of 2.9.2,but It is ok in version of 2.0.2

### ISSUE THREAD

**Issue by aaironman** [google/ExoPlayer#5721]
ExoPlayerImplInternal: Source error.
                                                                          com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
                                                                              at com.google.android.exoplayer2.extractor.ts.TsExtractor.findEndOfFirstTsPacketInBuffer(SourceFile:402)
                                                                              at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(SourceFile:278)
                                                                              at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(SourceFile:255)
                                                                              at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(SourceFile:197)
                                                                              at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(SourceFile:383)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                              at java.lang.Thread.run(Thread.java:784)

<details><summary>local m3u8 file:</summary>
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=187000, RESOLUTION=768x480, AUDIO="audio"
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-VERSION:3
#EXT-X-KEY:METHOD=AES-128
#EXTINF:10.000
loco_video_187000_0.ts
#EXTINF:10.000
loco_video_187000_1.ts
#EXTINF:10.000
loco_video_187000_2.ts
#EXTINF:10.000
loco_video_187000_3.ts
#EXTINF:10.000
loco_video_187000_4.ts
#EXTINF:10.000
loco_video_187000_5.ts
#EXTINF:10.000
loco_video_187000_6.ts
#EXTINF:10.000
loco_video_187000_7.ts
#EXTINF:10.000
loco_video_187000_8.ts
#EXTINF:10.000
loco_video_187000_9.ts
#EXTINF:10.000
loco_video_187000_10.ts
#EXTINF:10.000
loco_video_187000_11.ts
#EXTINF:10.000
loco_video_187000_12.ts
#EXTINF:10.000
loco_video_187000_13.ts
#EXTINF:10.000
loco_video_187000_14.ts
#EXTINF:10.000
loco_video_187000_15.ts
#EXTINF:10.000
loco_video_187000_16.ts
#EXTINF:10.000
loco_video_187000_17.ts
#EXTINF:10.000
loco_video_187000_18.ts
#EXTINF:10.000
loco_video_187000_19.ts
#EXTINF:10.000
loco_video_187000_20.ts
#EXTINF:10.000
loco_video_187000_21.ts
#EXTINF:10.000
loco_video_187000_22.ts
#EXTINF:10.000
loco_video_187000_23.ts
#EXTINF:10.000
loco_video_187000_24.ts
#EXTINF:10.000
loco_video_187000_25.ts
#EXTINF:10.000
loco_video_187000_26.ts
#EXTINF:10.000
loco_video_187000_27.ts
#EXTINF:10.000
loco_video_187000_28.ts
#EXTINF:10.000
loco_video_187000_29.ts
#EXTINF:10.000
loco_video_187000_30.ts
#EXTINF:10.000
loco_video_187000_31.ts
#EXTINF:10.000
loco_video_187000_32.ts
#EXTINF:10.000
loco_video_187000_33.ts
#EXTINF:10.000
loco_video_187000_34.ts
#EXTINF:10.000
loco_video_187000_35.ts
#EXTINF:10.000
loco_video_187000_36.ts
#EXTINF:10.000
loco_video_187000_37.ts
#EXTINF:10.000
loco_video_187000_38.ts
#EXTINF:10.000
loco_video_187000_39.ts
#EXTINF:10.000
loco_video_187000_40.ts
#EXTINF:10.000
loco_video_187000_41.ts
#EXTINF:10.000
loco_video_187000_42.ts
#EXTINF:10.000
loco_video_187000_43.ts
#EXTINF:10.000
loco_video_187000_44.ts
#EXTINF:10.000
loco_video_187000_45.ts
#EXTINF:10.000
loco_video_187000_46.ts
#EXTINF:10.000
loco_video_187000_47.ts
#EXTINF:10.000
loco_video_187000_48.ts
#EXTINF:1.200
loco_video_187000_49.ts
#EXT-X-ENDLIST
```
</details>

**Comment by andrewlewis** [comment]
Please provide the information requested in the [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=content+not+playing%2C+needs+triage&template=content_not_playing.md&title=). We can't investigate this kind of issue properly without access to the sample media so that we can reproduce the problem.

**Comment by andrewlewis** [comment]
Closing due to lack of activity.
