### ISSUE TITLE
Out of memory crash 

### ISSUE THREAD

**Issue by Rupeshc91** [google/ExoPlayer#5729]
```
 java.lang.OutOfMemoryError: Failed to allocate a 1886547827 byte allocation with 4182256 free bytes and 279MB until OOM
        at com.google.android.exoplayer2.offline.ProgressiveDownloadAction$1.readFromStream(ProgressiveDownloadAction.java:40)
        at com.google.android.exoplayer2.offline.ProgressiveDownloadAction$1.readFromStream(ProgressiveDownloadAction.java:33)
        at com.google.android.exoplayer2.offline.DownloadAction.deserializeFromStream(DownloadAction.java:74)
        at com.google.android.exoplayer2.offline.ActionFile.load(ActionFile.java:67)
        at com.spoyl.videoca.DownloadListener.loadTrackedActions(DownloadListener.kt:43)
        at com.spoyl.videoca.DownloadListener.<init>(DownloadListener.kt:36)
        at com.spoyl.videocache.VideoDownloadHelper.initDownloadTracker(VideoDownloadHelper.kt:64)
        at com.spoyl.videocache.VideoDownloadHelper.init(VideoDownloadHelper.kt:50)
        at com.spoyl.android.uiTypes.ecommFeedTypes.ecommPostVideo.EcommPostVideoHolder.initialize(EcommPostVideoHolder.java:165)
        at com.spoyl.android.posts.videodetails.view.PlayerManager.initialize(PlayerManager.java:70)
        at com.spoyl.android.posts.videodetails.view.Container.onScrollStateChanged(Container.java:332)
        at com.spoyl.android.posts.videodetails.view.Container$AnimatorHelper.handleMessage(Container.java:843)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5740)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
```

**Comment by andrewlewis** [comment]
It looks like we are trying to deserialize about 2 GB of custom data for the download action. Could you provide some more information about how you triggered this behavior? Are you passing custom data? If you step through the code in `ProgressiveDownloadAction`'s `readFromStream` before the error do you see a valid URL?

Assigning to @erdemguven for further investigation. Thanks.

**Comment by Rupeshc91** [comment]
Yes for .mov video URL was empty still it was showing length =1886547827 .If URL is null or empty than what is use of getting length and read data?

**Comment by andrewlewis** [comment]
Is it expected that the URL is empty? That sounds wrong. The length here relates to the size of custom data associated with the action, in bytes. I wonder if we are parsing garbage data as a download action.

**Comment by Rupeshc91** [comment]
Url is not empty but inside ProgressiveDownloadAction readFromStream this method ( Uri uri = Uri.parse(input.readUTF());) returning empty.

**Comment by Rupeshc91** [comment]
Url was not empty but inside progressiveaction class readstream was giving
empty uri

**Comment by erdemguven** [comment]
@Rupeshc91 sorry for late response, do you still see the issue? It sounds like the action file is corrupted. In the latest version of ExoPlayer, we did major changes on how we store download requests. Upgrading your ExoPlayer library may help to see what is wrong.

**Comment by Rupeshc9** [comment]
Hi @erdemguven @andrewlewis  thanks for reply but i already fixed this issue.

**Comment by potatoker** [comment]
@Rupeshc9 hi, could you please tell me how you fixed it?

**Comment by Rupeshc9** [comment]
I added array of deserialiser and it fixed.Earlier i was using deserialiser depend on media type.
