### ISSUE TITLE
When button is clicked on notification, exception occurs intermittently

### ISSUE THREAD

**Issue by pistolcaffe** [google/ExoPlayer#5734]
### Issue description
I implemented the music controller using the `PlayerNotificationManager` (https://medium.com/google-exoplayer/playback-notifications-with-exoplayer-a2f1a18cf93b). However, when I click on the Notification button, the exception occurs intermittently and does not work.

### Reproduction steps
When i click the button on the notification (intermittently)

### Link to test content
N/A

### A full bug report captured from the device
```
E/RemoteViews: Cannot send pending intent: 
    android.content.IntentSender$SendIntentException
        at android.app.ContextImpl.startIntentSender(ContextImpl.java:946)
        at android.content.ContextWrapper.startIntentSender(ContextWrapper.java:436)
        at android.content.ContextWrapper.startIntentSender(ContextWrapper.java:436)
        at android.widget.RemoteViews$OnClickHandler.onClickHandler(RemoteViews.java:299)
        at com.android.systemui.statusbar.phone.StatusBar$28.superOnClickHandler(StatusBar.java:9072)
        at com.android.systemui.statusbar.phone.StatusBar$28.onClickHandler(StatusBar.java:9035)
        at android.widget.RemoteViews$SetOnClickPendingIntent$1.onClick(RemoteViews.java:919)
        at android.view.View.performClick(View.java:6891)
        at android.view.View$PerformClick.run(View.java:26083)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
### Version of ExoPlayer being used
2.8.0

### Device(s) and version(s) of Android being used
Samsung GalaxyS8 (SM-G950N) 
android 8.0

**Comment by andrewlewis** [comment]
Please could you supply a full bug report captured with `adb bugreport` here, or via email to `dev.exoplayer@gmail.com` with subject 'Issue #5734'?

**Comment by pistolcaffe** [comment]
@andrewlewis I just sent an email to `dev.exoplayer@gmail.com.`

**Comment by marcbaechinger** [comment]
When the user taps on a notification with a `PendingIntent` attached, the system attempts to start the activity defined by the PendingIntent. It seems that the `ActivityTaskManager ` fails to start that activity and returns `ActivityManager.START_CANCELED` [which results in the android.content.IntentSender$SendIntentException](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/app/ContextImpl.java#1015).

For creating the notification a `PendingIntent` is used which you provide by `MediaDescriptionAdapter.createCurrentContentIntent(Player player)`  Can you please provide us with the code which creates this `PendingIntent`?

**Comment by pistolcaffe** [comment]
The above exception has occurred for the playback action. The `PendingIntent` for the playback action is generated from `PlayerNotificationManager.createPlaybackActions(Context context)`

**Comment by ojw28** [comment]
@marcbaechinger - Could this be caused by our use of `FLAG_CANCEL_CURRENT` in `PendingNotificationManager.createBroadcastIntent`? I wonder if there's a race condition where the an attempt is made to use the (now canceled) previous intent. Should we be using `FLAG_UPDATE_CURRENT` instead?

**Comment by pistolcaffe** [comment]
is there a solution to the issue?

**Comment by marcbaechinger** [comment]
We changed the flag set to the PendingIntent to FLAG_UPDATE_CURRENT. The fix will be synced to Github asap.
