### ISSUE TITLE
HLS VERSION 3  CONTENT NOT DOWNLOADING ON DEMO APP

### ISSUE THREAD

**Issue by mathemandy** [google/ExoPlayer#5757]
###  Issue description
HLS file from the Music app is not downloading on the demo app.
when i observed the HLS file from the demo content. it was version 6 and mine is version 3. 

###  Reproduction steps
1. Replace the HLS link with the one  sent via email in the HLS section of the Json File. 
2. Run app and select  the download Link for the selcted one you replaced.
3. you would notice no variations are shown and the Dialog just shows CANCEL and OK.
4. Selct OK, App crashes.

Log Below  

###  Link to test content
Link Emailed with issue #1234, resent with issue #5757

### A full bug report captured from the device
```
2019-04-11 15:45:46.783 14430-14430/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.exoplayer2.demo, PID: 14430
    java.lang.NullPointerException
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:110)
        at com.google.android.exoplayer2.source.hls.offline.HlsDownloadHelper.getDownloadAction(HlsDownloadHelper.java:100)
        at com.google.android.exoplayer2.source.hls.offline.HlsDownloadHelper.getDownloadAction(HlsDownloadHelper.java:41)
        at com.google.android.exoplayer2.demo.DownloadTracker$StartDownloadDialogHelper.onClick(DownloadTracker.java:296)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:180)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1073)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
```

###  Version of ExoPlayer being used
    releaseVersion = '2.8.1'

###  Device(s) and version(s) of Android being used
No Specific Device

**Comment by mathemandy** [comment]
Updated to 
`releaseVersion = '2.9.6'`

i was able to download the content. I am going to close this issue as resolved.
Thanks
