### ISSUE TITLE
OutOfMemoryError -ExoPlayer2.9.6

### ISSUE THREAD

**Issue by W2L** [google/ExoPlayer#5775]
in case of HLS stream:
device: PAR-AL00（HUAWEI）, android8.1.0

BOARD=PAR
CPU_ABI2=armeabi
HOST=lf068887b251534238872632-265638860-1p28c
versionName=14.0
IS_TREBLE_ENABLED=true
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@8615d1d
CPU_ABI=armeabi-v7a
PERMISSIONS_REVIEW_REQUIRED=false
IS_USERDEBUG=false
DISPLAY=PAR-AL00 8.2.0.132(C00)
SUPPORTED_ABIS=[Ljava.lang.String;@d41ab92
FINGERPRINT=HUAWEI/PAR-AL00/HWPAR:8.1.0/HUAWEIPAR-AL00/132(C00):user/release-keys
PRODUCT=PAR-AL00
HIDE_PRODUCT_INFO=false
ID=HUAWEIPAR-AL00
IS_CONTAINER=false
IS_ENG=false
DEVICE=HWPAR
TIME=1534240140000
MODEL=PAR-AL00
MANUFACTURER=HUAWEI
USER=test
versionCode=231
BRAND=HUAWEI
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@b5001f4
matchers=[Ljava.lang.String;@c28b963
HARDWARE=kirin970

```
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Out of memory
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:753)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1377)
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:620)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.execute(TbsSdkJava:482)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.start(TbsSdkJava:343)
	at com.google.android.exoplayer2.upstream.Loader.startLoading(TbsSdkJava:236)
	at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker.start(TbsSdkJava:123)
	at com.google.android.exoplayer2.source.hls.HlsMediaSource.prepareSourceInternal(TbsSdkJava:402)
	at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(TbsSdkJava:140)
	at com.google.android.exoplayer2.source.CompositeMediaSource.prepareChildSource(TbsSdkJava:101)
	at com.google.android.exoplayer2.source.ConcatenatingMediaSource.addMediaSourceInternal(TbsSdkJava:756)
	at com.google.android.exoplayer2.source.ConcatenatingMediaSource.addMediaSourcesInternal(TbsSdkJava:732)
	at com.google.android.exoplayer2.source.ConcatenatingMediaSource.prepareSourceInternal(TbsSdkJava:437)
	at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(TbsSdkJava:140)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.prepareInternal(TbsSdkJava:398)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(TbsSdkJava:285)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:166)
	at android.os.HandlerThread.run(HandlerThread.java:65)`
```

**Comment by ojw28** [comment]
Please properly fill in the issue template. There's nothing we can do unless you provide complete information.

**Comment by W2L** [comment]
i resolved this issue by using ConcatenatingMediaSource's lazy mode. ^V^
