### ISSUE TITLE
H.264 codec with SurfaceView vs TextureView on certain KitKat devices

### ISSUE THREAD

**Issue by petertran858** [google/ExoPlayer#58]
On certain KitKat devices I am seeing weird video artifacts when using ExoPlayer to render H.264 with a `TextureView`.

I have a previous implementation of my rendering pipeline that used `MediaCodec` directly and it does not exhibit this issue. Also using ExoPlayer with `SurfaceView` does not exhibit this issue.
Also, I've only observed this on certain KitKat devices (see table below).

Screenshot of ExoPlayer with `TextureView` showing issue:
![exoplayer-textureview](https://cloud.githubusercontent.com/assets/1665632/4462255/0a18e508-48c1-11e4-8bd7-60b9abd17232.png)

Screenshot of expected good video:
![mediacodec-textureview](https://cloud.githubusercontent.com/assets/1665632/4462270/1b326d1e-48c1-11e4-8b32-f97f36af8b35.png)

Here's a test matrix showing when issue occurs. FAIL means the video artifacts are seen.

| Device | Android Ver. | ExoPlayer or MediaCodec | View Type | PASS/FAIL |
| --- | --- | --- | --- | --- |
| Samsung S4 | 4.4.2 | ExoPlayer | TextureView | **FAIL** |
| Samsung S3 | 4.4.2 | ExoPlayer | TextureView | **FAIL** |
| Samsung S4 | 4.4.2 | ExoPlayer | SurfaceView | Pass |
| Samsung S3 | 4.4.2 | ExoPlayer | SurfaceView | Pass |
| Samsung S4 | 4.4.2 | MediaCodec | TextureView | Pass |
| Samsung S3 | 4.4.2 | MediaCodec | TextureView | Pass |
| Nexus 5 | 4.4.4 | ExoPlayer | SurfaceView | Pass |
| Nexus 5 | 4.4.4 | ExoPlayer | TextureView | Pass |
| Nexus 5 | 4.4.4 | MediaCodec | SurfaceView | Pass |
| Nexus 5 | 4.4.4 | MediaCodec | TextureView | Pass |

**Comment by edikfuks** [comment]
Is there any way for ExoPlayer to detect the black/white issue, so could be handled in the code?
Thanks in advance!

**Comment by schwiz** [comment]
There doesn't seem to be a good way to handle this. Right now I just detect known chipsets that have the issue. 

    private boolean shouldUseWorkaround(){
        final String board = Build.BOARD;
        if("APQ8064".equals(board) || "MSM8960".equals(board) || "MSM8930".equals(board)){
            Log.w(TAG, "Defective board detected only using one stream.");
            return true;
        } else {
            return false;
        }
    }

This sort of works but isn't really ideal as these boards could actually have the patch and work correctly, also there are probably others that need to be added to the list.

**Comment by edikfuks** [comment]
@schwiz Thank you!
@ojw28 on October 27th you mentioned couple boards as the defected ones. Would it be possible to list more affected boards? Thank you!

**Comment by ojw28** [comment]
I don't have a more exhaustive list, I'm afraid. It might be that those three are the only ones affected; I'm not sure. If anyone else knows of any additional affected boards, I'd encourage them to post details here!

**Comment by osemen-remit** [comment]
Hi guys,
I'm getting the same behavior on my SGS4 4.4.2
But here what i'm getting in my LogCat:

`com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 640, 360, 1.0, -1, -1, -1, 1920, 1080)`

here is full log:
```
06-23 19:25:54.986    5666-5666/se.memry.android.stage E/EventLogger﹕ internalError [0.33, decoderInitializationError]
    com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 640, 360, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:157)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.lang.IllegalStateException
            at android.media.MediaCodec.native_configure(Native Method)
            at android.media.MediaCodec.configure(MediaCodec.java:262)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:363)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:366)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:157)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
06-23 19:25:54.996    5666-7314/se.memry.android.stage E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 640, 360, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:387)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:157)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 640, 360, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:157)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.lang.IllegalStateException
            at android.media.MediaCodec.native_configure(Native Method)
            at android.media.MediaCodec.configure(MediaCodec.java:262)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:363)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:366)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:157)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
06-23 19:25:55.006    5666-5666/se.memry.android.stage E/EventLogger﹕ playerFailed [0.34]
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 640, 360, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:387)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:157)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 640, 360, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:157)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.lang.IllegalStateException
            at android.media.MediaCodec.native_configure(Native Method)
            at android.media.MediaCodec.configure(MediaCodec.java:262)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:363)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:366)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:157)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by jasells** [comment]
@trandroid  You mentioned you are handling TS over UDP data source (H.264).  i am trying the same using MediaCodec, and having issues.  I was wondering if you had any tips?  I can the H.264 ES, but it only shows a grey screen with a few pixelated artifacts using my own extractor.  Any help or tips greatly appreciated!

**Comment by sungerk** [comment]
i used textureView instead of surfaceview in the demo module ,but it's not play .and without error log.
 
@trandroid Would you like to share me the demo of textureView play online video,my email is kcjsunger@gmail.com

**Comment by trandroid** [comment]
@sungerk Do you have proper set up for `TextureView.SurfaceTextureListener`?
I don't have my source readily available but I essentially do that same as [this call to textureView.setSurfaceTextureListener](https://github.com/satorufujiwara/exoplayer-textureview/blob/master/player/src/main/java/jp/satorufujiwara/player/VideoTexturePresenter.java#L30).

**Comment by sungerk** [comment]
@trandroid   i had run the project,but it's not play video yet, i add a issue in the project

**Comment by jasells** [comment]
@trandroid Thanks for the reply.  I figured out my issue.  It was a combination of :

1) clearing MediaCodec's input buffers before writing to them
2) properly extracting the data from all the Mpeg TS headers.

**Comment by jasells** [comment]
@schwiz 

I know you are using the standard Java Android API, but, just fyi, I am able to resize using a surface view no problem using Xamarin forms as my UI.  The back end is a standard Android surface view, but the way that Xamarin binds to the platform view (surfaceView) means that it doesn't detach from the screen when resizing.  I don't know if that might give you some insight.  It is just a little demo app, so it is not polished, but it does work.

[My project DroidVid using Xamarin](https://github.com/jasells/Droid-Vid/blob/master/Droid/CustomRenderer.cs)

Summary, it has a video view and a button.  Clicking the button will swap the size/possiton of the button and the video view.  The video view could be made full screen by getting the parent page size and resizing to those values.
