### ISSUE TITLE
MPEG-DASH - Unexpected exception loading stream FragmentedMp4Extractor (ArrayIndexOutOfBoundsException) 

### ISSUE THREAD

**Issue by lucalooz** [google/ExoPlayer#5814]
### [REQUIRED] Content description
MPEG-DASH live stream on Akamai CDN without DRM but with token authentication through Cookies (hdnts and hdntl).

```
2019-04-29 14:36:40.980 16576-19923/com.google.android.exoplayer2.demo E/LoadTask: Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=-1
        at com.google.android.exoplayer2.extractor.mp4.Track.getSampleDescriptionEncryptionBox(Track.java:128)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.parseTraf(FragmentedMp4Extractor.java:686)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.parseMoof(FragmentedMp4Extractor.java:658)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onMoofContainerAtomRead(FragmentedMp4Extractor.java:531)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onContainerAtomRead(FragmentedMp4Extractor.java:456)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.processAtomEnded(FragmentedMp4Extractor.java:434)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:429)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:315)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:135)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

### [REQUIRED] Link to test content
Content link and bugreport will be sent to dev.exoplayer@gmail.com

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
OnePlus 6 API 28 Android 9.0.4
Emulator Pixel 2 API 28 Android 9

**Comment by tonihei** [comment]
I'm getting 403 response codes when I try to play the provided example streams. Can you check that I have access to the streams?

**Comment by lucalooz** [comment]
@tonihei i've ensured that it works also from other countries by doing some tests with VPNs
Are you using the default http source? 
The stream requires cookies to be enabled and passed back in subsequent requests

**Comment by tonihei** [comment]
Thanks, I can access the stream now.

Looking at what happens, I would conclude that the stream is malformed. The tfhd box has tf_flags with 0x00002 set, which indicates the presence of the sample description index in the box. However, the index returned when trying to read it is 0 which is not allowed because the index should be 1-based.
