### ISSUE TITLE
E MediaDrm-JNI: Illegal state exception: Failed to handle key response: DRM vendor-defined error: -2965 (-2965)

### ISSUE THREAD

**Issue by eyalpartner** [google/ExoPlayer#5845]
**Details:**
This error occur when the security level of the device is L1 with exoplayer ver 2.8.4
Content: HEVC +DASH
Android 7
If full adb logcat is needed:
https://drive.google.com/open?id=1QG4d6VOr_UPCoYLojjJJkTmmqRWlc2Dp

I am using our tv app that using the exoplayer 2.8.4 implemented so I can't use the
special log request, I attached above the full log in a link.

Happens when zapping to others channels, I can get handreds of this error that also effect the video that doesn't work from time to time.
***********************************************************************************************************

Log:
```
E MediaDrm-JNI: Illegal state exception: Failed to handle key response: DRM vendor-defined error: -2965 (-2965)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: Renderer error.
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.shouldWaitForKeys(MediaCodecRenderer.java:775)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:716)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:551)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:578)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at android.os.Handler.dispatchMessage(Handler.java:98)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at android.os.Looper.loop(Looper.java:154)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at android.os.HandlerThread.run(HandlerThread.java:61)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2965
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onError(DefaultDrmSessionManager.java:610)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onKeysError(DefaultDrmSessionManager.java:605)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onKeyResponse(DefaultDrmSessionManager.java:597)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.access$900(DefaultDrmSessionManager.java:51)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at com.google.android.exoplayer2.drm.DefaultDrmSessionManager$PostResponseHandler.handleMessage(DefaultDrmSessionManager.java:685)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at android.os.Handler.dispatchMessage(Handler.java:102)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: ... 2 more
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2965
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at android.media.MediaDrm.provideKeyResponse(Native Method)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(FrameworkMediaDrm.java:106)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onKeyResponse(DefaultDrmSessionManager.java:581)
05-06 15:09:32.675 20625 10275 E ExoPlayerImplInternal: ... 5 more
05-06 15:09:32.677 208 5936 D BerlinOmxComponentImpl: setState() line 903: OMX.Marvell.video_decoder.hevc.secure, state change, OMX_StateExecuting(3) -> OMX_StateIdle(2)
05-06 15:09:32.677 208 5936 D BerlinOmxAmpVideoDecoder: Function stop(), Line 1742, Function Enter
05-06 15:09:32.678 20625 20625 D MetricManager: Destroying player state manager
05-06 15:09:32.679 20625 20625 D MetricManager: Player is stopped
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: �[0;34m[�[0;34m(main)IFSExoPlayer2Pipe.java:2129->onPlayerError]�[0;32m[android]�[0;0m �[1;31mIFS_ERROR: onPlayerError rendererIndex:0 type: 1 log:com.google.android.exoplayer2.ExoPlaybackException
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: IFSExoPlayer2Pipe.java:2129->onPlayerError
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: ExoPlayerImpl.java:504->handleEvent
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: ExoPlayerImpl.java:103->handleMessage
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: Handler.java:102->dispatchMessage
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: Looper.java:154->loop
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: ActivityThread.java:6077->main
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: Method.java:-2->invoke
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: ZygoteInit.java:865->run
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: ZygoteInit.java:755->main
05-06 15:09:32.679 20625 20625 E IFSExoPlayer2Pipe: �[0;0m
05-06 15:09:32.680 20625 20625 W IFSExoPlayer2Pipe: �[0;34m[�[0;34m(main)IFSExoPlayer2Pipe.java:2162->onPlayerError]�[0;32m[android]�[0;0m �[1;33munknown error exception�[0;0m
```

**Comment by marcbaechinger** [comment]
Did you manage to make this work on any devices or is this happening on a specific device only?

**Comment by ojw28** [comment]
Closing due to lack of follow up. To investigate further, I think we'd also need a full bug report captured shortly after experiencing the problem (captured with `adb bugreport`). Logcat output is not sufficient. You can email a bug report to `dev.exoplayer@gmail.com` if you'd rather not post it publicly.

If you're able to provide the required information, please do so and then respond here, and we'll reopen the issue.
