### ISSUE TITLE
DecoderInitializationException when playing DRM content

### ISSUE THREAD

**Issue by albinalias10** [google/ExoPlayer#5889]
**Issue description**
On certain devices that use OMX.qcom.video.decoder.avc decoder, on DRM content ONLY we receive the below error.

 **Reproduction steps**

- Initialise SimpleExoPlayer

- Prepare MediaSource with drm.

- Note, that in prepare step, we are NOT attaching SimpleExoplayerView to view hierarchy, and only doing so, after player state READY received.

- Get the crash, immediately after prepare() called.

**Link to test Content**
we use the .mpd format files by upload using aws drm encryption.

 **A full bug report captured from the device**

```
E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc.secure, Format(1, null, null, video/avc, avc1.4d401f, 400000, null, [480, 270, 14.985015], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc.secure, Format(1, null, null, video/avc, avc1.4d401f, 400000, null, [480, 270, 14.985015], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:1885)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:814)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Version of ExoPlayer being used**
Exoplayer version 2.9.3

**Code**
```
    private void createMediaSource(Uri mDataUri) {
        String userAgent = Util.getUserAgent(VideoDetailsActivity.this,
                getApplicationContext().getApplicationInfo().packageName);

        // media factory
        RenderersFactory renderersFactory = new DefaultRenderersFactory(this);





       // DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory trackSelectionFactory =
                new AdaptiveTrackSelection.Factory(bandwidthMeter);
        mTrackSelector = new DefaultTrackSelector(trackSelectionFactory);

        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this, userAgent, bandwidthMeter);
        //Handler mainHandler = new Handler();
        mainHandler = new Handler();

        mTrackSelector = new DefaultTrackSelector(trackSelectionFactory);
        mTrackSelectionHelper = new TrackSelectionHelper(mTrackSelector, trackSelectionFactory);

        if(DrmManager.isEncryptedContent(mDataUri)){ // TODO : TO Check if the content is encrypted or normal content
            UUID drmSchemeUuid = DrmManager.getDrmUuid(AppConstants.WIDEVINE);
            DrmSessionManager<FrameworkMediaCrypto> drmSessionManager = null;
            if (drmSchemeUuid != null) {
                try {
                    boolean isOffline = true; // TODO : Check if the content is online/offline
                    if (isOffline) { // for testing keep offline. Download License should start with
                        try {
                            drmSessionManager = buildOfflineDrmSessionManager(LICENSE_URL,mDataUri);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    } else {
                        drmSessionManager = buildDrmSessionManager(drmSchemeUuid, LICENSE_URL,null);
                    }
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
            mVideoSource = buildMediaSource(mDataUri);
            Log.d("videoData", String.valueOf(mDataUri));
            mExoPlayer = ExoPlayerFactory.newSimpleInstance(this,renderersFactory, mTrackSelector, new DefaultLoadControl(),
                    drmSessionManager);
        }else{
            mVideoSource = new HlsMediaSource(mDataUri, dataSourceFactory, 1,
                    mainHandler, this);
            mExoPlayer = ExoPlayerFactory.newSimpleInstance(this,renderersFactory, mTrackSelector, new DefaultLoadControl());
        }

        if (mExoPlayerView != null)
            mExoPlayerView.setPlayer(mExoPlayer);

        // Resume to Previous State
        boolean haveResumePosition = mResumeWindow != C.INDEX_UNSET;
        if (mExoPlayerView != null && mExoPlayer != null) {
            mExoPlayer.prepare(mVideoSource);
            mExoPlayer.addListener(this);
            mExoPlayer.setPlayWhenReady(mExoPlayerStatePlayed);
            if (haveResumePosition) {
                mExoPlayer.seekTo(mResumeWindow, mResumePosition);
            }
            setWifiOnly();
            mExoPlayerView.setControllerVisibilityListener(mPlaybackControllerListener);
            mHandler = new Handler();
            mHandler.post(mUpdateProgressAction);
        }
        if (!mIsFromDownloaded) {
            setStreamingQuality();
        }
    }
```

 **Device(s) and version(s) of Android being used**
Android version - 6.0
Android version-6.0.1
Pie Version phones
Nexus
Samsung phones have Oreo Os
@andrewlewis @xian @canatella @talklittle @kiall 
**-Have you ever seen this error ?
-Do you have an explanation about what is actually happening?**

Any help/fix would be appreciated,
Thanks.

**Comment by andrewlewis** [comment]
Please provide a full bugreport captured using "adb bugreport". Output from "adb logcat" or a log snippet is NOT sufficient. Please attach the captured bug report as a file. If you don't wish to post it publicly, please submit the issue, then email the bug report to dev.exoplayer@gmail.com using a subject in the format "Issue #5889".

**Comment by andrewlewis** [comment]
Also, does the issue go away if you show the player view before preparing the player?

**Comment by westlakestudent** [comment]
is this solved？why are u so caring template， is it important？ the bug is exist，can u help？？？？？

**Comment by andrewlewis** [comment]
Closing due to lack of required information.
