### ISSUE TITLE
Issues playing MKV test content

### ISSUE THREAD

**Issue by ened** [google/ExoPlayer#589]
Previously, I tried loading some Videos through `FrameworkSampleSource`. This worked well:

``` java
final Uri uri = ContentUris.withAppendedId(MediaStore.Video.Media.EXTERNAL_CONTENT_URI, videoId);
final FrameworkSampleSource sampleSource = new FrameworkSampleSource(this, uri, null);
```

Now I switched it over to `ExtractorSampleSource`:

``` java
final Uri uri = ContentUris.withAppendedId(MediaStore.Video.Media.EXTERNAL_CONTENT_URI, videoId);
final ExtractorSampleSource sampleSource = new ExtractorSampleSource(uri, new ContentDataSource(this), new WebmExtractor(), 20480);
```

This results in a "black screen". Nothing will be loaded or played back, and no error messages are present in the logs.

My offline test files might not be compatible with the WebmExtractor (they are MKV files). Which way do we have to detail-test the extractor?

**Comment by ojw28** [comment]
I think your buffer is too small. 20KB isn't going to be big enough to a useful amount of video. For comparison, the demo app uses 10485760 bytes (~10MB).

**Comment by ojw28** [comment]
Please re-open if you still have problems after adjusting the buffer.

**Comment by ened** [comment]
After adjusting the buffer size, I get exceptions like this when trying the MKV test suite files (http://www.matroska.org/downloads/test_w1.html).

**test3.mkv**:
```
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.ParserException: Multiple Segment elements not supported
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:254)
            at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:113)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:271)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:197)
            at android.os.Handler.dispatchMessage(Handler.java:106)
            at android.os.Looper.loop(Looper.java:193)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**test7.mkv**:
Loads a still frame, hangs and then shows error message:
```
    com.google.android.exoplayer.ExoPlaybackException: java.io.EOFException
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:510)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:415)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:106)
            at android.os.Looper.loop(Looper.java:193)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:97)
            at com.google.android.exoplayer.extractor.webm.DefaultEbmlReader.read(DefaultEbmlReader.java:121)
            at com.google.android.exoplayer.extractor.webm.WebmExtractor.read(WebmExtractor.java:228)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:612)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:848)
```

When playing another ~4GB MKV file, the black screen is back.

(sorry, the "reopen" button is not available for me).

**Comment by ened** [comment]
@ojw28 On that note - the MKV test suite at http://www.matroska.org/downloads/test_w1.html is 185MB and highly recommended for testing MKV compatibility. Do you think this would be worth putting into the repository for automated testing? Or let the gradle script download & cache the files..

**Comment by andrewlewis** [comment]
test3.mkv can't be played because we don't support sample header stripping yet. Should be fixed soon.

test7.mkv contains some invalid data that is incorrectly handled.

**Comment by ened** [comment]
@andrewlewis Thanks for taking care of this! If you have a minute left, please also check the other files in the MKV test suite. Many thanks!
