### ISSUE TITLE
sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by osemen-remit** [google/ExoPlayer#590]
Hi,
I'm playing videos on `TextureView`s that are placed in `RecyclerView` so they are often started and stopped and I often see this error

```
W/MessageQueue﹕ Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {42b67fe0} sending message to a Handler on a dead thread
    java.lang.RuntimeException: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {42b67fe0} sending message to a Handler on a dead thread
            at android.os.MessageQueue.enqueueMessage(MessageQueue.java:320)
            at android.os.Handler.enqueueMessage(Handler.java:626)
            at android.os.Handler.sendMessageAtTime(Handler.java:595)
            at android.os.Handler.sendMessageDelayed(Handler.java:566)
            at android.os.Handler.sendEmptyMessageDelayed(Handler.java:530)
            at android.os.Handler.sendEmptyMessage(Handler.java:515)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:244)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
```

Video does not play when I see this.

**Comment by ojw28** [comment]
This only happens if you've called release() on the player (the warning in the logs is expected to occur sometimes when you do this).

**Comment by PhatJo** [comment]
I experience this too. My videos are in an autoplaying list of cards (a "carousel") that are created if the current card is selected, and stopped otherwise. Video playback doesn't work after the 5th or 6th video. What is the recommended fix?

**Comment by PhatJo** [comment]
Hi @ojw28, I'm using the ExoMedia wrapper for my demo project at https://github.com/PhatJo/androidtvdemo where I see the above described problem. Playback stops completely when the warning is thrown
