### ISSUE TITLE
Playback with Security level 1 & HDCP

### ISSUE THREAD

**Issue by Jason239** [google/ExoPlayer#5903]
I tried to play content with security level 1 and HDCP V1, but it does not work on some devices like Samsung S9+, Nexus 5.
Nexus 5 could not play at all.
But especially on S9+, it works well if the audio track was not encrypted and only the video track was encrypted. 
Are these device-dependent issues?

The exoplayer version is 2.9.3
And the error log like below.
```
com.pallycon.exoplayersample.simple E/ExoPlayerImplInternal: Playback error. 
com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Operation not supported in this configuration 
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1110) 
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:653) 
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575) 
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:214) 
at android.os.HandlerThread.run(HandlerThread.java:65) 
Caused by: android.media.MediaCodec$CryptoException: Operation not supported in this configuration 
at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method) 
at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2608) 
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1101) 
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:653) 
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575) 
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:214) 
at android.os.HandlerThread.run(HandlerThread.java:65) 
2019-05-10 16:30:15.297 22132-22132/com.pallycon.exoplayersample.simple E/@@# error: 1 
2019-05-10 16:30:15.297 22132-22132/com.pallycon.exoplayersample.simple E/@@# errorString =: android.media.MediaCodec$CryptoException: Operation not supported in this configuration
```

**Comment by andrewlewis** [comment]
> Nexus 5 could not play at all.
> But especially on S9+, it works well if the audio track was not encrypted and only the video track was encrypted.

To clarify, is it the case that on both Nexus 5 and Samsung Galaxy S9+ you find that L1 DRM playback fails if the audio track is encrypted but succeeds if the audio track is not encrypted? I'm not sure about the level of support for audio encryption but perhaps @ojw28 can comment on this.

There may be more relevant logging before the snippet you provided, so please attach a full bug report. Capture a full bug report using "adb bugreport". Output from "adb logcat" or a log snippet is NOT sufficient. Please attach the captured bug report as a file. If you don't wish to post it publicly, please submit the issue, then email the bug report to dev.exoplayer@gmail.com using a subject in the format "Issue #5903".

**Comment by ojw28** [comment]
Are you using separate keys for audio and video? I don't think you should be configuring the license for audio to be L1 and to require HDCP, because there's no such thing as an L1 audio output path. If you're doing that, you most likely need to use a separate key for audio that only requires L3.
