### ISSUE TITLE
Decoder init failed with Nexus 7

### ISSUE THREAD

**Issue by fengtaoft** [google/ExoPlayer#591]
I have encountered similar problem as described in #370 when I ran the demo project from the master branch (commit acee566)  and selected the HLS test urls. The device I used is Nexus 7 of Android 4.4.4. 

This problem can be reproduced with the "Apple master playlist" video in the demo project on Nexus 7 (Android 4.4.4).

The error log is as follows:
```
I/ExoPlayerImpl( 6944): Init 1.3.3
D/ConnectivityService(  573): handleInetConditionHoldEnd: net=1, condition=100, published condition=100
I/OMXClient( 6944): Using client-side OMX mux.
E/OMX-VDEC-1080P(  181): Extension: OMX.google.android.index.storeMetaDataInBuffers not implemented
E/OMXNodeInstance(  181): OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
E/ACodec  ( 6944): [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
E/OMX-VDEC-1080P(  181): Enabling Adaptive playback for 1920 x 1080
E/OMX-VDEC-1080P(  181): 
E/OMX-VDEC-1080P(  181):  No color conversion required
E/OMX-VDEC-1080P(  181): 
E/OMX-VDEC-1080P(  181):  No color conversion required
E/OMX-VDEC-1080P(  181): 
E/OMX-VDEC-1080P(  181):  No color conversion required
E/OMX-VDEC-1080P(  181): 
E/OMX-VDEC-1080P(  181):  No color conversion required
E/OMX-VDEC-1080P(  181): 
E/OMX-VDEC-1080P(  181):  No color conversion required
E/OMX-VDEC-1080P(  181): 
E/OMX-VDEC-1080P(  181):  No color conversion required
E/OMX-VDEC-1080P(  181): 
E/OMX-VDEC-1080P(  181):  No color conversion required
E/OMX-VDEC-1080P(  181): 
E/OMX-VDEC-1080P(  181):  No color conversion required
E/OMX-VDEC-1080P(  181): GET_MV_BUFFER_SIZE returned: Size: 557056 and alignment: 8192
E/OMX-VDEC-1080P(  181): Failed to set the H264_mv_buffers
E/OMX-VDEC-1080P(  181): ERROR in allocating MV buffers
E/OMXNodeInstance(  181): OMX_UseBuffer failed with error -2147479552 (0x80001000)
E/ACodec  ( 6944): registering GraphicBuffer 0 with OMX IL component failed: -2147483648
E/ACodec  ( 6944): Failed to allocate buffers after transitioning to IDLE state (error 0x80000000)
E/MediaCodec( 6944): Codec reported an error. (omx error 0x80001001, internalError -2147483648)
E/ExoPlayerImplInternal( 6944): Internal track renderer error.
E/ExoPlayerImplInternal( 6944): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 1280, 720, 1.0, -1, -1, -1, 1920, 1080)
E/ExoPlayerImplInternal( 6944):     at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:387)
E/ExoPlayerImplInternal( 6944):     at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
E/ExoPlayerImplInternal( 6944):     at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
E/ExoPlayerImplInternal( 6944):     at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
E/ExoPlayerImplInternal( 6944):     at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
E/ExoPlayerImplInternal( 6944):     at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
E/ExoPlayerImplInternal( 6944):     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
E/ExoPlayerImplInternal( 6944):     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
E/ExoPlayerImplInternal( 6944):     at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 6944):     at android.os.Looper.loop(Looper.java:136)
E/ExoPlayerImplInternal( 6944):     at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 6944):     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/ExoPlayerImplInternal( 6944): Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 1280, 720, 1.0, -1, -1, -1, 1920, 1080)
E/ExoPlayerImplInternal( 6944):     ... 11 more
E/ExoPlayerImplInternal( 6944): Caused by: java.lang.IllegalStateException: start failed
E/ExoPlayerImplInternal( 6944):     at android.media.MediaCodec.start(Native Method)
E/ExoPlayerImplInternal( 6944):     at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:367)
E/ExoPlayerImplInternal( 6944):     ... 10 more
I/ActivityManager(  573): Process com.lofter.android (pid 11010) has died.
I/fflog   ( 6944): ______HLSPlayer2 exception com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 1280, 720, 1.0, -1, -1, -1, 1920, 1080)
E/OMX-VDEC-1080P(  181): 
E/OMX-VDEC-1080P(  181):  Error in ioctl read next msg
E/        (  181): 
E/        (  181):  Destroy C2D instance
E/        (  181): 
E/        (  181):  Destroy C2D instance
```
Any suggestions to solve this problem? Thanks in advance.

**Comment by s3xy4ngyc** [comment]
I can Confirm the Problem is the Same for MPEG/DASH content with Widevine Protection.

Same Logs. Video is starting, but every x seconds a green frame appears and those log messages appear.

**Comment by Jthomas54** [comment]
I can confirm this issue occurs on Nexus 7 running android 5.0 with r1.4.1.

```
07-24 10:21:34.439  20594-20616/? E/OMX-VDEC-1080P﹕ Extension: OMX.google.android.index.storeMetaDataInBuffers not implemented
07-24 10:21:34.439  20594-20616/? E/OMXNodeInstance﹕ OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
07-24 10:21:34.441  25288-25736/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
07-24 10:21:34.443  20594-20617/? E/OMX-VDEC-1080P﹕ Enabling Adaptive playback for 1920 x 1080
07-24 10:21:34.444  20594-30820/? E/OMX-VDEC-1080P﹕ No color conversion required
07-24 10:21:34.445  20594-20617/? E/OMX-VDEC-1080P﹕ No color conversion required
07-24 10:21:34.446  20594-32489/? E/OMX-VDEC-1080P﹕ No color conversion required
07-24 10:21:34.446  20594-32489/? E/OMX-VDEC-1080P﹕ No color conversion required
07-24 10:21:34.446  20594-20611/? E/OMX-VDEC-1080P﹕ No color conversion required
07-24 10:21:34.450  20594-30820/? E/OMX-VDEC-1080P﹕ Extension: OMX.google.android.index.describeColorFormat not implemented
07-24 10:21:34.464  20594-30820/? E/OMX-VDEC-1080P﹕ No color conversion required
07-24 10:21:34.469  20594-20616/? E/OMX-VDEC-1080P﹕ No color conversion required
07-24 10:21:34.469  20594-20616/? E/OMX-VDEC-1080P﹕ No color conversion required
07-24 10:21:34.483  20594-20617/? E/OMX-VDEC-1080P﹕ No color conversion required
07-24 10:21:34.483  20594-20617/? E/OMX-VDEC-1080P﹕ GET_MV_BUFFER_SIZE returned: Size: 557056 and alignment: 8192
07-24 10:21:34.495  20594-20617/? E/OMX-VDEC-1080P﹕ Set output buffer failed
07-24 10:21:34.495  20594-20617/? E/OMXNodeInstance﹕ OMX_UseBuffer failed with error -2147479552 (0x80001000)
07-24 10:21:34.496  25288-25736/com.google.android.exoplayer.demo E/ACodec﹕ registering GraphicBuffer 0 with OMX IL component failed: -2147483648
07-24 10:21:34.496  25288-25736/com.google.android.exoplayer.demo E/ACodec﹕ Failed to allocate buffers after transitioning to IDLE state (error 0x80000000)
07-24 10:21:34.496  25288-25736/com.google.android.exoplayer.demo E/ACodec﹕ signalError(omxError 0x80001001, internalError -2147483648)
07-24 10:21:34.496  25288-25735/com.google.android.exoplayer.demo E/MediaCodec﹕ Codec reported err 0x80001001, actionCode 0, while in state 5
07-24 10:21:34.499  25288-25727/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 400, 300, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:392)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:379)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:750)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:372)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:520)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:498)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:415)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 400, 300, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:379)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:750)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:372)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:520)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:498)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:415)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: android.media.MediaCodec$CodecException: start failed
            at android.media.MediaCodec.native_start(Native Method)
            at android.media.MediaCodec.start(MediaCodec.java:612)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:371)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:750)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:372)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:520)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:498)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:415)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
07-24 10:21:34.508  25288-25727/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Stop failed.
    java.lang.IllegalStateException
            at android.media.MediaCodec.native_stop(Native Method)
            at android.media.MediaCodec.stop(MediaCodec.java:628)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.releaseCodec(MediaCodecTrackRenderer.java:442)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onDisabled(MediaCodecTrackRenderer.java:412)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onDisabled(MediaCodecVideoTrackRenderer.java:328)
            at com.google.android.exoplayer.TrackRenderer.disable(TrackRenderer.java:211)
            at com.google.android.exoplayer.ExoPlayerImplInternal.stopAndDisable(ExoPlayerImplInternal.java:529)
            at com.google.android.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:516)
            at com.google.android.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:493)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:234)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
07-24 10:21:34.508  25288-25288/com.google.android.exoplayer.demo E/EventLogger﹕ internalError [0.44, decoderInitializationError]
    com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 400, 300, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:379)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:750)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:372)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:520)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:498)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:415)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: android.media.MediaCodec$CodecException: start failed
            at android.media.MediaCodec.native_start(Native Method)
            at android.media.MediaCodec.start(MediaCodec.java:612)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:371)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:750)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:372)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:520)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:498)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:415)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
07-24 10:21:34.519  25288-25288/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [0.45]
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 400, 300, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:392)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:379)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:750)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:372)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:520)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:498)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:415)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 400, 300, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:379)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:750)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:372)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:520)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:498)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:415)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: android.media.MediaCodec$CodecException: start failed
            at android.media.MediaCodec.native_start(Native Method)
            at android.media.MediaCodec.start(MediaCodec.java:612)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:371)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:750)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:372)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:520)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:498)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:415)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
07-24 10:22:47.250  11933-11933/? E/﹕ invalid crash request of size 4 (from pid=25179 uid=0)
07-24 10:22:47.487  27402-27402/? E/Diag_Lib﹕ Diag_LSM_Init: Failed to open handle to diag driver, error = 13
07-24 10:22:47.487  27402-27402/? E/Sensors﹕ sns_fsa_la.c(386):fsa: fflush failed, 9
07-24 10:22:47.487  27402-27402/? E/Sensors﹕ sns_fsa_la.c(386):fsa: fflush failed, 9
07-24 10:22:47.548  27402-27411/? E/Sensors﹕ sns_debug_main.c(565):Debug Config File missing in EFS!
```

It does work on my Droid Turbo running android 4.4.4 though.

The demo for r1.3.1 **does** work on the exact same Nexus 7 though.  Hoping to use 1.4+ of ExoPlayer because of breaking changes.

**Comment by ojw28** [comment]
We've never been able to reproduce this issue. It's most likely something has put the device into a bad state, and the mediaserver isn't robust enough to recover.

If you're able to provide reliable reproduction steps using the ExoPlayer demo app then please update this issue, including a full bug report (captured with `adb bugreport`, *not* just `adb logcat` log output). Else I think we'll have to put this down to a sporadic device specific issue.
