### ISSUE TITLE
Asus Zenfone: Audio playback stopped abruptly

### ISSUE THREAD

**Issue by vkgyl2432** [google/ExoPlayer#5923]
Issue description
Player stops playing media at offset - 1:57 for file - (https://d1l07mcd18xic4.cloudfront.net/audio/ef3edb4a-9f65-4ddf-80b8-d33773f0f7a3.m3u8)

Exoplayer version - 2.7.3 (using exoplayer-hls:2.7.3 for hls)
 Below is the stacktrace for the same.
```
E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.releaseOutputBuffer(Native Method)
        at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:2743)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:462)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1068)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:567)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:198)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-05-21 16:50:03.604 9515-9766/com.vlv.aravali.preprod E/ExoPlayerImplInternal: Stop failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2084)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:512)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:468)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onDisabled(MediaCodecAudioRenderer.java:394)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:150)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:972)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:772)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:735)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:198)
        at android.os.HandlerThread.run(HandlerThread.java:65)```


Content url - https://kukufm.com/api/v1.0/episodes/109447/
device - Asus Zenfone 
Adding file after `adb bugreport` for bug report.
[bugreport-WW_Z01RD-PPR1.180610.009-2019-05-21-16-55-12.zip](https://github.com/google/ExoPlayer/files/3202308/bugreport-WW_Z01RD-PPR1.180610.009-2019-05-21-16-55-12.zip)

**Comment by erdemguven** [comment]
I can't reproduce this on Nexus 6. Have you tried another device or a newer version of ExoPlayer?

**Comment by tonihei** [comment]
Just re-asking the question above: Were you able to reproduce on a newer version of ExoPlayer? And is it always reproducible?
