### ISSUE TITLE
java.lang.NoSuchMethodError: No direct method <init>(...) in HlsMediaSource

### ISSUE THREAD

**Issue by praneethkumar16** [google/ExoPlayer#5964]
I'm getting following error when ever I try to play the video using exoplayer in android device. I have updated the exoplayer to latest version 2.9.6 but still I'm getting following error. 

java.lang.NoSuchMethodError: No direct method <init>(Landroid/net/Uri;Lcom/google/android/exoplayer2/upstream/DataSource$Factory;Landroid/os/Handler;Lcom/google/android/exoplayer2/source/AdaptiveMediaSourceEventListener;)V in class Lcom/google/android/exoplayer2/source/hls/HlsMediaSource; or its super classes (declaration of 'com.google.android.exoplayer2.source.hls.HlsMediaSource' appears in /data/app/com.roh.rohmobile-2/base.apk:classes2.dex)

I'm unable to resolve it please help me.

**Comment by ojw28** [comment]
Please properly fill out the issue template (including attaching a full bug report - there is possibly useful information either side of the small log snippet you've included here).

**Comment by praneethkumar16** [comment]
> Please properly fill out the issue template (including attaching a full bug report - there is possibly useful information either side of the small log snippet you've included here).

**Here is the full stack trace:**

  --------- beginning of crash
```
 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.roh.rohmobile, PID: 22703
    java.lang.NoSuchMethodError: No direct method <init>(Landroid/net/Uri;Lcom/google/android/exoplayer2/upstream/DataSource$Factory;Landroid/os/Handler;Lcom/google/android/exoplayer2/source/AdaptiveMediaSourceEventListener;)V in class Lcom/google/android/exoplayer2/source/hls/HlsMediaSource; or its super classes (declaration of 'com.google.android.exoplayer2.source.hls.HlsMediaSource' appears in base.apk!classes2.dex)
        at com.ooyala.android.player.exoplayer.BaseExoPlayer.buildMediaSource(BaseExoPlayer.java:203)
        at com.ooyala.android.player.exoplayer.ExoStreamPlayer.preparePlayer(ExoStreamPlayer.java:280)
        at com.ooyala.android.player.exoplayer.ExoStreamPlayer.initializePlayer(ExoStreamPlayer.java:170)
        at com.ooyala.android.player.exoplayer.ExoStreamPlayer.init(ExoStreamPlayer.java:122)
        at com.ooyala.android.player.MoviePlayer.init(MoviePlayer.java:53)
        at com.ooyala.android.OoyalaPlayerContextSwitcher.createAndInitPlayer(OoyalaPlayerContextSwitcher.java:107)
        at com.ooyala.android.OoyalaPlayer.prepareContent(OoyalaPlayer.java:1650)
        at com.ooyala.android.OoyalaPlayerContextSwitcher.processExitAdModes(OoyalaPlayerContextSwitcher.java:182)
        at com.ooyala.android.OoyalaPlayerContextSwitcher.processAdModes(OoyalaPlayerContextSwitcher.java:162)
        at com.ooyala.android.OoyalaPlayerContextSwitcher.startVideoWorkflow(OoyalaPlayerContextSwitcher.java:61)
        at com.ooyala.android.OoyalaPlayer.onCurrentItemChangeComplete(OoyalaPlayer.java:845)
        at com.ooyala.android.OoyalaPlayer.access$200(OoyalaPlayer.java:83)
        at com.ooyala.android.OoyalaPlayer$1$1.run(OoyalaPlayer.java:556)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6923)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```
I'm using this way to initialise the media source 
`MediaSource videoSource = new HlsMediaSource(mp4VideoUri, dataSourceFactory, 1, null, null);`

**Comment by ojw28** [comment]
`com.ooyala.android.player.exoplayer` is a fork of ExoPlayer. You need to report your issue to Ooyala.

**Comment by praneethkumar16** [comment]
> I'm getting following error when ever I try to play the video using exoplayer in android device. I have updated the exoplayer to latest version 2.9.6 but still I'm getting following error.
> 
> java.lang.NoSuchMethodError: No direct method (Landroid/net/Uri;Lcom/google/android/exoplayer2/upstream/DataSource$Factory;Landroid/os/Handler;Lcom/google/android/exoplayer2/source/AdaptiveMediaSourceEventListener;)V in class Lcom/google/android/exoplayer2/source/hls/HlsMediaSource; or its super classes (declaration of 'com.google.android.exoplayer2.source.hls.HlsMediaSource' appears in /data/app/com.roh.rohmobile-2/base.apk:classes2.dex)
> 
> I'm unable to resolve it please help me.

Why did you close the issue with out solving it?

**Comment by ojw28** [comment]
It's not an ExoPlayer issue. It's an issue in Ooyala's fork of ExoPlayer, as per my response above.
