### ISSUE TITLE
can't play live video with huawei mate 10 lite

### ISSUE THREAD

**Issue by ShahoBashoki** [google/ExoPlayer#5984]
> 2019-06-02 16:45:30.281 414-414/? E/SELinux: avc:  denied  { find } for interface=vendor.huawei.hardware.hwsched::ISched sid=u:r:untrusted_app:s0:c512,c768 pid=31933 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:hwsched_hwservice:s0 tclass=hwservice_manager
2019-06-02 16:45:30.281 31933-31933/land.pod.play E/BufferQueueProducer: [] Can not get hwsched service
2019-06-02 16:45:30.290 759-759/? E/Thermal-daemon: [battery] temp_new :33  temp_old :32
2019-06-02 16:45:30.291 2041-31132/? I/ThermalService: Receive temperature change, type: 9, temp: 33 from thermald
2019-06-02 16:45:30.291 2041-31132/? I/ThermalTrace_ThermalRaise: Battery:33
2019-06-02 16:45:30.291 2041-3161/? W/HwThermalStateManager: warning: no config thermal type:9 temperature:33
2019-06-02 16:45:30.291 759-759/? E/Thermal-daemon: Report temperature: [battery] temp :33  report_threshold:1
2019-06-02 16:45:30.293 759-759/? E/Thermal-daemon: [ap] temp_new :39  temp_old :38
2019-06-02 16:45:30.293 2041-31132/? I/ThermalService: Receive temperature change, type: 0, temp: 39 from thermald
2019-06-02 16:45:30.293 2041-3161/? D/HwThermalStateManager: Thermal type: 0 cur_temperature:39
2019-06-02 16:45:30.293 759-759/? E/Thermal-daemon: Report temperature: [ap] temp :39  report_threshold:1
2019-06-02 16:45:31.258 414-414/? W//system/bin/hwservicemanager: Cannot open /odm/manifest.xml
2019-06-02 16:45:31.259 31933-32222/land.pod.play I/OMXClient: Treble IOmx obtained
2019-06-02 16:45:31.261 762-20434/? I/OMXMaster: makeComponentInstance(OMX.IMG.MSVDX.Decoder.AVC) in omx@1.0-service process
2019-06-02 16:45:31.261 762-20434/? I/imgvideo-omx: Created VdecTask f29d5ea0
2019-06-02 16:45:31.261 762-20434/? I/imgvideo-omx: IMG_OMD_ComponentInit Done.
2019-06-02 16:45:31.261 762-20434/? D/IMG-OMX: Loaded OMX.IMG.MSVDX.Decoder.AVC (0xf29a4c40) from libomx_vxd.so
2019-06-02 16:45:31.262 31933-32222/land.pod.play I/ACodec: In onAllocateComponent create compenent, codec name: OMX.IMG.MSVDX.Decoder.AVC
2019-06-02 16:45:31.266 31933-32221/land.pod.play D/SurfaceUtils: connecting to surface 0xb5c09808, reason connectToSurface
2019-06-02 16:45:31.267 31933-32221/land.pod.play I/MediaCodec: [OMX.IMG.MSVDX.Decoder.AVC] setting surface generation to 32699393
2019-06-02 16:45:31.267 31933-32221/land.pod.play D/SurfaceUtils: disconnecting from surface 0xb5c09808, reason connectToSurface(reconnect)
2019-06-02 16:45:31.267 31933-32221/land.pod.play D/SurfaceUtils: connecting to surface 0xb5c09808, reason connectToSurface(reconnect)
2019-06-02 16:45:31.267 762-6314/? W/imgvideo-omx: Extension index OMX.google.android.index.storeMetaDataInBuffers not found
2019-06-02 16:45:31.267 762-6314/? E/imgvideo-omx: IMG_OMD_GetExtensionIndex FAILED: Index Not Found.
2019-06-02 16:45:31.267 762-6314/? W/imgvideo-omx: Extension index OMX.google.android.index.storeANWBufferInMetadata not found
2019-06-02 16:45:31.267 762-6314/? E/imgvideo-omx: IMG_OMD_GetExtensionIndex FAILED: Index Not Found.
2019-06-02 16:45:31.267 762-6314/? W/imgvideo-omx: Extension index OMX.google.android.index.configureVideoTunnelMode not found
2019-06-02 16:45:31.267 762-6314/? E/imgvideo-omx: IMG_OMD_GetExtensionIndex FAILED: Index Not Found.
2019-06-02 16:45:31.267 762-6314/? W/imgvideo-omx: Extension index OMX.google.android.index.allocateNativeHandle not found
2019-06-02 16:45:31.267 762-6314/? E/imgvideo-omx: IMG_OMD_GetExtensionIndex FAILED: Index Not Found.
2019-06-02 16:45:31.268 762-6314/? E/imgvideo-omx: IMG_OMD_SetConfig FAILED: Unsupported paramter structure.
2019-06-02 16:45:31.268 762-6314/? E/OMXNodeInstance: setConfig(0xf29a4c40:IMG.MSVDX.Decoder.AVC, ??(0x6f700006)) ERROR: UnsupportedIndex(0x8000101a)
2019-06-02 16:45:31.268 31933-32222/land.pod.play W/HwExtendedUtils: hw configLocalPlayBack err = -1010
2019-06-02 16:45:31.268 762-6314/? W/imgvideo-omx: Extension index OMX.google.android.index.allocateNativeHandle not found
2019-06-02 16:45:31.268 762-6314/? E/imgvideo-omx: IMG_OMD_GetExtensionIndex FAILED: Index Not Found.
2019-06-02 16:45:31.268 762-6314/? W/imgvideo-omx: Extension index OMX.google.android.index.storeANWBufferInMetadata not found
2019-06-02 16:45:31.268 762-6314/? E/imgvideo-omx: IMG_OMD_GetExtensionIndex FAILED: Index Not Found.
2019-06-02 16:45:31.268 762-6314/? W/imgvideo-omx: Extension index OMX.google.android.index.storeMetaDataInBuffers not found
2019-06-02 16:45:31.268 762-6314/? E/imgvideo-omx: IMG_OMD_GetExtensionIndex FAILED: Index Not Found.
2019-06-02 16:45:31.268 762-6314/? W/OMXNodeInstance: [0xf29a4c40:IMG.MSVDX.Decoder.AVC] component does not support metadata mode; using fallback
2019-06-02 16:45:31.268 31933-32222/land.pod.play E/ACodec: [OMX.IMG.MSVDX.Decoder.AVC] setPortMode on output to DynamicANWBuffer failed w/ err -1010
2019-06-02 16:45:31.268 762-6314/? E/OMXNodeInstance: setParameter(0xf29a4c40:IMG.MSVDX.Decoder.AVC, OMX.google.android.index.prepareForAdaptivePlayback(0x7f000007): Output:1 en=1 max=1280x720) ERROR: UnsupportedIndex(0x8000101a)
2019-06-02 16:45:31.268 31933-32222/land.pod.play W/ACodec: [OMX.IMG.MSVDX.Decoder.AVC] prepareForAdaptivePlayback failed w/ err -1010
2019-06-02 16:45:31.268 762-6314/? W/imgvideo-omx: Extension index OMX.google.android.index.allocateNativeHandle not found
2019-06-02 16:45:31.268 762-6314/? E/imgvideo-omx: IMG_OMD_GetExtensionIndex FAILED: Index Not Found.
2019-06-02 16:45:31.268 762-6314/? W/imgvideo-omx: Extension index OMX.google.android.index.storeANWBufferInMetadata not found
2019-06-02 16:45:31.268 762-6314/? E/imgvideo-omx: IMG_OMD_GetExtensionIndex FAILED: Index Not Found.
2019-06-02 16:45:31.268 762-6314/? W/imgvideo-omx: Extension index OMX.google.android.index.storeMetaDataInBuffers not found
2019-06-02 16:45:31.268 762-6314/? E/imgvideo-omx: IMG_OMD_GetExtensionIndex FAILED: Index Not Found.
2019-06-02 16:45:31.268 762-6314/? W/OMXNodeInstance: [0xf29a4c40:IMG.MSVDX.Decoder.AVC] component does not support metadata mode; using fallback
2019-06-02 16:45:31.269 762-6314/? I/imgvideo-omx: ProcessName is (land.pod.play�	�)
2019-06-02 16:45:31.269 31933-32222/land.pod.play I/HwExtendedCodec: mime is [video/avc] at setVideoFormat
2019-06-02 16:45:31.269 762-6314/? I/img_omd_vdec_task: >>>>>>>psPortDef->nPortIndex = 0 xFramerate = 25
2019-06-02 16:45:31.269 762-6314/? I/img_omd_vdec_task: mFrameRate = 25
2019-06-02 16:45:31.270 762-6314/? W/imgvideo-omx: Extension index OMX.google.android.index.describeColorAspects not found
2019-06-02 16:45:31.270 762-6314/? E/imgvideo-omx: IMG_OMD_GetExtensionIndex FAILED: Index Not Found.
2019-06-02 16:45:31.270 762-6314/? W/imgvideo-omx: Extension index OMX.google.android.index.describeHDRStaticInfo not found
2019-06-02 16:45:31.270 762-6314/? E/imgvideo-omx: IMG_OMD_GetExtensionIndex FAILED: Index Not Found.
2019-06-02 16:45:31.270 762-6314/? E/imgvideo-omx: IMG_OMD_SetConfig FAILED: Unsupported paramter structure.
2019-06-02 16:45:31.270 762-6314/? E/OMXNodeInstance: setConfig(0xf29a4c40:IMG.MSVDX.Decoder.AVC, ConfigPriority(0x6f800002)) ERROR: UnsupportedIndex(0x8000101a)
2019-06-02 16:45:31.270 31933-32222/land.pod.play I/ACodec: codec does not support config priority (err -1010)
2019-06-02 16:45:31.270 762-6314/? E/imgvideo-omx: IMG_OMD_GetConfig FAILED: Unsupported paramter structure.
2019-06-02 16:45:31.270 762-6314/? E/OMXNodeInstance: getConfig(0xf29a4c40:IMG.MSVDX.Decoder.AVC, ConfigAndroidVendorExtension(0x6f100004)) ERROR: UnsupportedIndex(0x8000101a)
2019-06-02 16:45:31.277 1172-1942/? W/System.err: java.lang.SecurityException: uid 10319 does not have android.permission.UPDATE_DEVICE_STATS.
2019-06-02 16:45:31.277 1172-1942/? W/System.err:     at android.app.ContextImpl.enforce(ContextImpl.java:1932)
2019-06-02 16:45:31.277 1172-1942/? W/System.err:     at android.app.ContextImpl.enforcePermission(ContextImpl.java:1945)
2019-06-02 16:45:31.277 1172-1942/? W/System.err:     at com.android.server.am.BatteryStatsService.enforceCallingPermission(BatteryStatsService.java:1292)
2019-06-02 16:45:31.277 1172-1942/? W/System.err:     at com.android.server.am.BatteryStatsService.noteStartVideo(BatteryStatsService.java:846)
2019-06-02 16:45:31.277 1172-1942/? W/System.err:     at com.android.internal.app.IBatteryStats$Stub.onTransact(IBatteryStats.java:72)
2019-06-02 16:45:31.277 1172-1942/? W/System.err:     at android.os.Binder.execTransact(Binder.java:675)
2019-06-02 16:45:31.280 31933-32222/land.pod.play I/ACodec: onStart

> 

please help me

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md).
