### ISSUE TITLE
Cannot play incomplete mp4 files : not robust

### ISSUE THREAD

**Issue by KnIfER** [google/ExoPlayer#5988]
# Content description
video apps can produce incomplete mp4 file caches, and they can be palyed by ffplayer, MediaPlayer, mxplayer and libvlc player and potplayer. They are seekable and have complete metadata, but their timelines are incomplete.  
```
2019-06-04 01:35:28.473 8204-8204/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [0.09, 0.00, window=0, period=0]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:386)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:207)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1059)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:947)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
```
the app won't crash, but displays no image.
# Link to test content
[incomplete mp4 file sample (4/15 sec).zip](https://github.com/google/ExoPlayer/files/3257251/0C667465ADA31BA1BD5A5FC082D21E5F.zip)
( fome tiktok )
# Version of ExoPlayer being used
Versions: 
exoplayer-core:2.10.0

 Device(s) and version(s) of Android being used:
huawei p10 android 9
samsung s7 android 8

**Comment by arcgate-git** [comment]
I am also facing same issue when I am trimming video using mp4 parser. Trimmed video is not played by exoplayer giving above exception. Please let me know if you find any solution.

**Comment by arcgate-git** [comment]
Trimmed video gets played on device using ES media player. And works well on desktop and IOS devices

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md).

**Comment by ojw28** [comment]
The case of having an incomplete MP4 seems very niche. I don't think it's worth spending time on, sorry.

**Comment by dingbinacm** [comment]
Hi, I find I can't play a exo file, which is only cached partially.When offline, I play it in version2.10.5,it fails to recognize the format.
