### ISSUE TITLE
EOFException in the last part of the data

### ISSUE THREAD

**Issue by rodrigoolr** [google/ExoPlayer#599]
I'm using ExoPlayer in an application and received some user feedback about this issue. I was able to reproduce in two samsung devices (Galaxy A5 and Galaxy S3) with some specific files, but there are some user reports that it happens with all musics in their devices.

While reproducing MP3 files from a HTTP source it tries to read the last part of the data and fails because it reaches the end of file. But it actually is the end of file, so it doesn't really make any sense. When it tries to read the data the synchronizedHeaderData field from MP3Extractor isn't 0 yet, I couldn't tell exactly why or if it should at all...

```
32101-302/? E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: java.io.EOFException
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:509)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:176)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:73)
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:85)
            at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:386)
            at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:241)
            at com.google.android.exoplayer.extractor.mp3.Mp3Extractor.readSample(Mp3Extractor.java:129)
            at com.google.android.exoplayer.extractor.mp3.Mp3Extractor.read(Mp3Extractor.java:106)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:615)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:242)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
```

**Comment by andrewlewis** [comment]
@rodrigoolr, please could you email/share one of the problematic streams with andrewlewis.exoplayer [at] gmail.com? Does this happen every time the player reaches the end of the stream?

**Comment by rodrigoolr** [comment]
@andrewlewis I sent you the stream I used to reproduce the problem by e-mail

**Comment by dnuriel** [comment]
Encountering the Same issue. Though it might be some how related to ID3 in the file?

**Comment by dnuriel** [comment]
Seems my issue is irrelevant. I fixed it. Thanks!

I inject ID3 tags on the fly to files with missing tags which causes the content length to change.

This means that in load in ExtractorSampleSource ~ 612. The length returned is mismatched with the actual file/datasource length which causes the exception.

**Comment by rodrigoolr** [comment]
Do you have any idea on which could be the cause or a temporary workaround that could be used for a while?

**Comment by andrewlewis** [comment]
@rodrigoolr Sorry for taking so long to reply. It looks like the last sample in the file is truncated by three bytes, so an exception is thrown because it can't be read in full. We will implement a fix to handle this case as if the last sample were not there, so the player will transition to the ENDED state as expected.

**Comment by ojw28** [comment]
This is fixed in dev.
