### ISSUE TITLE
Internal track renderer error.

### ISSUE THREAD

**Issue by sabinsathian** [google/ExoPlayer#6004]
### [REQUIRED] Issue description
Exoplayer crashes when playing audio content not supported by TV
### [REQUIRED] Reproduction steps
Though the issue has been reported they have not been specific to Android version and hence opening a new issue to provide more insight to the issue.  Can Exoplayer gracefully handle this error irrespective of the cause?

Install Exoplayer in Android N device and play AC3 (Dolby Digital) Content on a TV which does not support Dolby Digital (eg Sony KLV32V300A or most of the older TVs)

Android N AudioPolicyManager filterSurroundFormats() has alwaysForceAC3 set to 'true' with the comment :
// Most TVs support AC3 even if they do not report it in the EDID.
Because of this, eventhough TV doesnt support DD, the player would choose the format and try to play and causes the issue. 

### [REQUIRED] A full bug report captured from the device
Sending to dev.exoplayer@gmail.com
Adding relevant portion below:
```
06-06 10:39:48.177   182   580 W APM_AudioPolicyManager: getOutput() could not find output for stream 3, samplingRate 48000,format 150994944, channels 3f, flags 1
06-06 10:39:48.178  1970  2060 E AudioTrack: Could not get audio output for session 17, stream type -1, usage 1, sample rate 48000, format 0x9000000, channel mask 0x3f, flags 0x1
06-06 10:39:48.178  1970  2060 E AudioTrack-JNI: Error -22 initializing AudioTrack
06-06 10:39:48.178  1970  2060 E android.media.AudioTrack: Error code -20 when initializing AudioTrack.
06-06 10:39:48.181  1970  1970 E EventLogger: internalError [0.33, audioTrackInitializationError]
06-06 10:39:48.181  1970  1970 E EventLogger: com.google.android.exoplayer.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 144000)
06-06 10:39:48.181  1970  1970 E EventLogger: 	at com.google.android.exoplayer.audio.AudioTrack.checkAudioTrackInitialized(AudioTrack.java:810)
06-06 10:39:48.181  1970  1970 E EventLogger: 	at com.google.android.exoplayer.audio.AudioTrack.initialize(AudioTrack.java:349)
06-06 10:39:48.181  1970  1970 E EventLogger: 	at com.google.android.exoplayer.audio.AudioTrack.initialize(AudioTrack.java:323)
06-06 10:39:48.181  1970  1970 E EventLogger: 	at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:332)
06-06 10:39:48.181  1970  1970 E EventLogger: 	at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:828)
06-06 10:39:48.181  1970  1970 E EventLogger: 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:458)
06-06 10:39:48.181  1970  1970 E EventLogger: 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
06-06 10:39:48.181  1970  1970 E EventLogger: 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
06-06 10:39:48.181  1970  1970 E EventLogger: 	at android.os.Handler.dispatchMessage(Handler.java:98)
06-06 10:39:48.181  1970  1970 E EventLogger: 	at android.os.Looper.loop(Looper.java:154)
06-06 10:39:48.181  1970  1970 E EventLogger: 	at android.os.HandlerThread.run(HandlerThread.java:61)
06-06 10:39:48.181  1970  1970 E EventLogger: 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: Internal track renderer error.
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 144000)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:337)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:828)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:458)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:154)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: Caused by: com.google.android.exoplayer.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 144000)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.audio.AudioTrack.checkAudioTrackInitialized(AudioTrack.java:810)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.audio.AudioTrack.initialize(AudioTrack.java:349)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.audio.AudioTrack.initialize(AudioTrack.java:323)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: 	at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:332)
06-06 10:39:48.182  1970  2060 E ExoPlayerImplInternal: 	... 8 more
```

### [REQUIRED] Version of ExoPlayer being used
2.6.1
### [REQUIRED] Device(s) and version(s) of Android being used
Can be reproduced 100% by playing AC3 content on Android N with TV not supporting AC3.

**Comment by AquilesCanta** [comment]
> Though the issue has been reported they have not been specific to Android version and hence opening a new issue to provide more insight to the issue

Which is the issue number?
