### ISSUE TITLE
DASH Widevine CBCS encrypted content not playing on Android 8

### ISSUE THREAD

**Issue by Hemube** [google/ExoPlayer#6017]
### [REQUIRED] Issue description
DASH stream with Widevine CBCS encryption is not playing on a device with Android 8

### [REQUIRED] Reproduction steps
try to play the CMAF CBC encrypted Dash stream

### [REQUIRED] Link to test content
URL and DRM info will be sent to dev.exoplayer@gmail.com

### [REQUIRED] A full bug report captured from the device
```
06-10 07:24:39.386  2592 18036 E WVCdm   : Decrypt error result in session sid20 during encrypted block: 176
06-10 07:24:39.386  2592 18036 W         : Unable to convert legacy status: -2998, defaulting to UNKNOWN
06-10 07:24:39.387 18697   338 E ExoPlayerImplInternal: Internal runtime error.
06-10 07:24:39.387 18697   338 E ExoPlayerImplInternal: android.media.MediaCodec$CodecException: Error 0x80000000
06-10 07:24:39.387 18697   338 E ExoPlayerImplInternal:         at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
06-10 07:24:39.387 18697   338 E ExoPlayerImplInternal:         at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2532)
06-10 07:24:39.387 18697   338 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:771)
06-10 07:24:39.387 18697   338 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:583)
06-10 07:24:39.387 18697   338 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:519)
06-10 07:24:39.387 18697   338 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
06-10 07:24:39.387 18697   338 E ExoPlayerImplInternal:         at android.os.Handler.dispatchMessage(Handler.java:101)
06-10 07:24:39.387 18697   338 E ExoPlayerImplInternal:         at android.os.Looper.loop(Looper.java:164)
06-10 07:24:39.387 18697   338 E ExoPlayerImplInternal:         at android.os.HandlerThread.run(HandlerThread.java:65)
```

### [REQUIRED] Version of ExoPlayer being used
ExoPlayer 2.8.4

### [REQUIRED] Device(s) and version(s) of Android being used
Samsung J5, Android 8.0.0

**Comment by ojw28** [comment]
@fredgc - Please take a look; thanks.

**Comment by Hemube** [comment]
Found the problem. Problem with pssh data, it was not having the information about "protection scheme". Created the pssh data using the tool then passed that while packaging. 

I assume it was working on android-9 because it can read the pssh data and "protection scheme" from the mpd.

./pssh-box.py --widevine-system-id --protection-scheme cbcs --content-id value --key-id value --hex
