### ISSUE TITLE
HLSSampleSource - getNextLoadPositionus

### ISSUE THREAD

**Issue by iNdieboyjeff** [google/ExoPlayer#602]
Just wanting to report an exception that I've seen cropping up:

```
java.lang.NullPointerException
       at com.google.android.exoplayer.hls.HlsSampleSource.getNextLoadPositionUs(HlsSampleSource.java:537)
       at com.google.android.exoplayer.hls.HlsSampleSource.maybeStartLoading(HlsSampleSource.java:480)
       at com.google.android.exoplayer.hls.HlsSampleSource.onLoadError(HlsSampleSource.java:399)
       at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:248)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
       at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

seems to be an issue with

```
private long getNextLoadPositionUs() {
    if (isPendingReset()) {
      return pendingResetPositionUs;
    } else {
THIS LINE ---->      return currentTsLoadable != null
          ? (currentTsLoadable.isLastChunk ? -1 : currentTsLoadable.endTimeUs)
          : (previousTsLoadable.isLastChunk ? -1 : previousTsLoadable.endTimeUs);
    }
  }
```

**Comment by ojw28** [comment]
Does this happen on the *latest* dev branch? If so, how do you reproduce the issue?

**Comment by ojw28** [comment]
Closing due to inactivity.

**Comment by itaykinnrot** [comment]
https://github.com/google/ExoPlayer/pull/1561 should solve this issue
