### ISSUE TITLE
can not play audio hls 

### ISSUE THREAD

**Issue by ArtisanM** [google/ExoPlayer#6043]
### [REQUIRED] Content description
I have an audio hls(with 16*16 h264 stream which no need to play). But exoplayer can not play this hls correctly unless I disable the video renderer.
I try to play it in exoplayer demo, it can not play too.When I select video track to none, it will play

### [REQUIRED] Link to test content
[https://pili-live-hls-staging.zhibo.qingting.fm/qingting-zhibo-staging/dev_100001232_696aff00-5cd5-11e9-b56f-45ffc5be3b6f.m3u8](url)

### [REQUIRED] Version of ExoPlayer being used
2.9.0

### [REQUIRED] Device(s) and version(s) of Android being used
Android 9, Huawei Mate 20 pro

**Comment by marcbaechinger** [comment]
Can you please check whether that URL works when accessing the stream? I wasn't able to get some data back from the server.

When trying to play that stream with the demo app I get a network timeout.

```
2019-06-17 15:28:48.029 29385-29385/com.google.android.exoplayer2.demo E/EventLogger: internalError [9.16, 0.00, window=0, loadError]
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://3237895721.cloudvdn.com/a.m3u8?domain=pili-live-hls-staging.zhibo.qingting.fm&player=NjEAADTmvua0AqkV&secondToken=secondToken%3ATaT5D4IwgapCZ3SEbI4510mzlh8&streamid=qingting-zhibo-staging%3Aqingting-zhibo-staging%2Fdev_100001232_696aff00-5cd5-11e9-b56f-45ffc5be3b6f&v3=1
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:280)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:178)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:459)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:286)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:170)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.net.SocketTimeoutException: timeout
```

When I do it with curl I get:

```
curl -v "https://2147608939.cloudvdn.com/a.m3u8?domain=pili-live-hls-staging.zhibo.qingting.fm&player=3CcAACB-xu--AqkV&secondToken=secondToken%3AQiBAqO9l1RRVDxL88Lp5WB8buuU&streamid=qingting-zhibo-staging%3Aqingting-zhibo-staging%2Fdev_100001232_696aff00-5cd5-11e9-b56f-45ffc5be3b6f&v3=1"


* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 404 
< server: nginx
< date: Mon, 17 Jun 2019 14:30:20 GMT
< content-type: text/plain; charset=utf-8
< content-length: 11
< x-content-type-options: nosniff
< access-control-allow-origin: *
< 
ConnClosed

```

**Comment by ArtisanM** [comment]
Sorry, something went wrong yesterday, you can try again now.

**Comment by ArtisanM** [comment]
I found that if I change the video width & height from 16 * 16 to 20*20 (or bigger than 20) then exoplayer can play correctly...that's weird

**Comment by marcbaechinger** [comment]
When adding the uri to the demo app of ExoPlayer, the audio plays well while there is no video as you report.

I think that's a restriction coming from the framework media codec on top of which ExoPlayer is running. In the logs I find the following line:

```
com.google.android.exoplayer2.demo D/MediaCodecInfo: NoSupport [sizeAndRate.support, 16x16x-1.0] [OMX.qcom.video.decoder.avc, video/avc] [sailfish, Pixel, Google, 28]
```
Together with what you report in your last comment I guess the easiest fix would be to increase the resolution accordingly.

**Comment by ArtisanM** [comment]
Thanks:)
