### ISSUE TITLE
i got this error when merge video source and subtitle

### ISSUE THREAD

**Issue by ardinh** [google/ExoPlayer#6044]
```
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:924)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:846)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by ardinh** [comment]
```
private void buildMediaSource(Uri mUri, Uri srtUri) {
        // Measures bandwidth during playback. Can be null if not required.
        DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        // Produces DataSource instances through which media data is loaded.
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this,
                Util.getUserAgent(this, getString(R.string.app_name)), bandwidthMeter);
        // This is the MediaSource representing the media to be played.
        MediaSource videoSource = new ExtractorMediaSource.Factory(dataSourceFactory)
                .createMediaSource(mUri);

        //prepare subtitle
        Format subtitleFormat = Format.createTextSampleFormat(null, MimeTypes.TEXT_VTT, null, Format.NO_VALUE, Format.NO_VALUE, "en", null, Format.OFFSET_SAMPLE_RELATIVE);

        MediaSource subtitleSource =new SingleSampleMediaSource(srtUri, dataSourceFactory, subtitleFormat, C.TIME_UNSET);

        MergingMediaSource mergedSource = new MergingMediaSource(videoSource, subtitleSource);
        // Prepare the player with the source.
        player.prepare(mergedSource);
        player.setPlayWhenReady(true);
        player.addListener(this);
    }
```
and here the code

**Comment by marcbaechinger** [comment]
Your code looks ok at a first sight. Seems like the `ProgressiveMediaSource` does not find an extractor for the given media file though. 

Can you provide uris to the media and subtitle files? If you don't wish to post it publicly, please submit the issue, then email the the uris to dev.exoplayer@gmail.com using a subject in the format "Issue #6044".

**Comment by ardinh** [comment]
ok thanks

**Comment by ardinh** [comment]
but now i have new error when read the subtitle file

 com.google.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT 
    
    00:00:00.020 -...@4783:28 in java.io.InputStreamReader@4c109b6) 
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:105)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:58)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:158)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT 
    
    00:00:00.020 -...@4783:28 in java.io.InputStreamReader@4c109b6) 
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:440)
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:321)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:98)

**Comment by marcbaechinger** [comment]
Seems like the XML parser does not like your XML of the DASH manifest. Are you sure it's DASH and that the manifest is valid and well-formed XML?

As mentioned above you can send me uris to the media/subtitle in case you want me to look into this more closely.

**Comment by ojw28** [comment]
Note: It's unclear how or why `DashManifestParser` is involved, because the code snippet above isn't using `DashMediaSource`.
