### ISSUE TITLE
How do I pass License Url using MediaDrmCallback?

### ISSUE THREAD

**Issue by bhaskarraj** [google/ExoPlayer#6062]
I am using DefaultDrmSessionManager and passing a MediaDrmCallback to its parameter. The problem that I am facing is that I am not being able to pass the license URL using MediaDrmCallback. 

My MedaiDrmCallback is: 

```
MediaDrmCallback mediaDrmCallback = new MediaDrmCallback() {
  @Override
  public byte[] executeProvisionRequest(UUID uuid, ExoMediaDrm.ProvisionRequest request) 
       throws Exception {
            String url = request.getDefaultUrl() + "&signedRequest=" + new String(request.getData());
            return executePost(dataSourceFactory, url, null, null);
  }

  @Override
  public byte[] executeKeyRequest(UUID uuid, ExoMediaDrm.KeyRequest request) throws Exception {
    try {
      flag = false;
      String payload = Base64.encodeToString(request.getData(), Base64.DEFAULT);

      LogCS.e("payload", payload.trim().replaceAll("\n", ""));

      DRMLicensePresenterImpl drmLicensePresenter = 
           new DRMLicensePresenterImpl(
                  ExoplayerActivity.this, ExoplayerActivity.this, payload.trim().replaceAll("\n", ""), ticketToStream);
      drmLicensePresenter.getDRMLicenseDetail(
          UrlUtil.getAltBalajiUrl(ExoplayerActivity.this, UrlUtil.DRM_LICENSE));

    } catch (Exception e) {
      e.printStackTrace();
    }
    LogCS.e("license is" + count++ + "----", license);
    // get license
    return Base64.decode(license, Base64.DEFAULT);

   }
};
```

My DefaultDrmSeesionManager is:
```
private DefaultDrmSessionManager getDrmSessionManager() {
  DefaultDrmSessionManager drmSessionManager = null;

  try {
    drmSessionManager = new DefaultDrmSessionManager<>(
        C.WIDEVINE_UUID, 
        FrameworkMediaDrm.newInstance(C.WIDEVINE_UUID), 
        mediaDrmCallback, null, false);    
  } catch (UnsupportedDrmException e) {
            e.printStackTrace();
  }
  return drmSessionManager;
}
```

In MediaDrmCallback override method executeKeyRequest() I am returning Base64.decode(license, Base64.DEFAULT);.

The problem that I am facing is the video only plays for 9 seconds. So I am assuming it because I am unable to bind my license_url to DefaultDrmSessionManager. How can it be solved? I have spent a week searching for any solutions but couldn't find any.

**Comment by marcbaechinger** [comment]
Can you please take a bug report right after you tried to play a protected video?

**Comment by bhaskarraj** [comment]
This is the error log that I am getting:

```
E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:771)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2292)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:762)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by ojw28** [comment]
`Error decrypting data: requested key has not been loaded` means that the key required for decryption was not included in the license response. If you're playing multi-key content then please see [this documentation](https://exoplayer.dev/drm.html#multi-key-content). In particular, if your license server falls under Case 2 rather than Case 1, you will need to change the license server to behave as in Case 1 (recommended), or enable `multiSession` as documented on that page.

If you're not playing multi-key content then it seems likely that you license server just isn't returning the correct keys for decryption.

**Comment by bhaskarraj** [comment]
Does that mean the code in the app side is fine? I also tried by enabling `multisession` to true but I get the following bug:

```
E/MediaDrm-JNI: Illegal state exception: Failed to handle key response: DRM vendor-defined error: -2902 (-2902)
2019-06-20 09:44:20.900 26091-26946/com.osolutions.otv E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.shouldWaitForKeys(MediaCodecRenderer.java:842)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:739)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:165)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:422)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:417)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:402)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:41)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$PostResponseHandler.handleMessage(DefaultDrmSession.java:472)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
        at android.media.MediaDrm.provideKeyResponse(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(FrameworkMediaDrm.java:127)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:392)
```
And the video now doesn't even play for 9 secs. By evaluating two bugs what do you think might be the problem? Can it be server side or app side problem?

**Comment by ojw28** [comment]
I think there's probably something wrong with either the content or the license server response. Have you managed to successfully play this content in any other player or environment?

**Comment by bhaskarraj** [comment]
I do not have much knowledge on the server end. I want to explain you the process of how we are doing the work. The steps are:
1. App gets the streaming link along with License Url
2. App makes another request to the server to get the license key for playing the content.
3. In the above code if you see inside executeKeyRequest I am returning `Base64.decode(license, Base64.DEFAULT);` in which the license is received from the server.

While doing this it plays for 9 seconds and stops playing. While doing some research I have found some examples where for streaming such contents only streaming link and License Url is required and while trying to test those link in my code its working fine but for that, I am using the following callback:

```
private HttpMediaDrmCallback drmCallBack() {
        return new HttpMediaDrmCallback(DRM_LICENSE_URL,
                new DefaultHttpDataSourceFactory(userAgent));
    } 
```

Using the callback in my first comment I am unable to pass the License URL so I think that's creating the problem. I am not able to pass the License URL in that case.  Is there a way to pass License Url in `MediaDrmCallback` of my first comment? I have searched a lot about it but couldn't find much thread about it on the internet and have been stuck for weeks in this part.

**Comment by ojw28** [comment]
> Using the callback in my first comment I am unable to pass the License URL so I think that's creating the problem. I am not able to pass the License URL in that case. Is there a way to pass License Url in MediaDrmCallback of my first comment? I have searched a lot about it but couldn't find much thread about it on the internet and have been stuck for weeks in this part.

It's unclear where you want to pass it to. Nothing other than the `MediaDrmCallback` needs it. Please could you clarify what you think the problem is, exactly?

That aside, I still think the problem is with either the content or the license server response, and would again ask whether you've managed to successfully play this content in any other player or environment?

**Comment by bhaskarraj** [comment]
Thanks @ojw28 like you said earlier the problem was in the server section. Now it's working fine.
