### ISSUE TITLE
Video isn't playing (black screen) on Xiaomi mi A2

### ISSUE THREAD

**Issue by CreeschYT** [google/ExoPlayer#6066]
### Issue description
I'm developing an m3u player which asks the user to choose an m3u file. The m3u urls are put in a ConcatenatingMediaSource the urls work fine on my Samsung S6 (Android 7.0, API 24) and I get no errors and on other Smartphones like (Samsung S4 mini and S6 edge) everything works fine. BUT on my Xiaomi Mi A2 when I choose an m3u file there is nothing, but a black screen. Nothing is played. And I get an Error. 

### Reproduction steps
So you can get a phone with android 9.0 and try the m3u file in the demo. But I think it's not a good idea.

### Link to test content
I can give you the m3u files I used. And the error log of course.
[File I used.zip](https://github.com/google/ExoPlayer/files/3307492/File.I.used.zip)

### A full bug report captured from the device
```
2019-06-19 20:15:01.597 11441-11479/com.example.basiciptv E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://foviptv.shop:8080/WJILAyPvOz/ueYmlOtJQC/2380
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: Cleartext HTTP traffic to foviptv.shop not permitted
        at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:528)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:436)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

### Version of ExoPlayer being used
I'm using exoplayer version 2.9.6 on all of my projects.

### [REQUIRED] Device(s) and version(s) of Android being used
Samsung S6 (Android 7.0) works
Samsung S6 edge (Android 7.0) works
Samsung s4 mini (Android 6.0) works
Xiaomi mi A2 (Android 9.0) doesn't work

Note: This is not my issue, because everything was fine on my older phone. So please don't just reject the issue and atleast give me options.

**Comment by marcbaechinger** [comment]
> Caused by: java.io.IOException: Cleartext HTTP traffic to foviptv.shop not permitted

When targeting Android 9 (API 28 and higher) apps are not allowed to connect to clear text connections (non-https) anymore by default. So if you have your targetSdk set to 28, the `usesCleartextTraffic` attribute in your manifest defaults to true.

Please refer to this documentation:

https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic

"Indicates whether the app intends to use cleartext network traffic, such as cleartext HTTP. The default value for apps that target API level 27 or lower is "true". Apps that target API level 28 or higher default to "false"."

Can you please check if this applies to your case?

**Comment by CreeschYT** [comment]
Ok I added `android:usesCleartextTraffic="true"` to the manifest and it's working now.
