### ISSUE TITLE
EXO报错

### ISSUE THREAD

**Issue by hu374307261** [google/ExoPlayer#6085]
Before filing a bug:
-----------------------
06-24 15:57:41.677 1686-1686/com.diandong.android.app W/SimpleExoPlayer: Player is accessed on the wrong thread. See https://google.github.io/ExoPlayer/faqs.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1190)
        at com.google.android.exoplayer2.SimpleExoPlayer.getBufferedPosition(SimpleExoPlayer.java:1077)
        at com.google.android.exoplayer2.BasePlayer.getBufferedPercentage(BasePlayer.java:106)
        at com.diandong.cn.jzvd.JZMediaExo$onBufferingUpdate.run(JZMediaExo.java:306)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6814)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
### [REQUIRED] A full bug report captured from the device
Capture a full bug report using "adb bugreport". Output from "adb logcat" or a
log snippet is NOT sufficient. Please attach the captured bug report as a file.
If you don't wish to post it publicly, please submit the issue, then email the
bug report to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234", where "#1234" should be replaced with your issue number.

### [REQUIRED] Version of ExoPlayer being used
Specify the absolute version number. Avoid using terms such as "latest".

### [REQUIRED] Device(s) and version(s) of Android being used
Specify the devices and versions of Android on which the issue can be
reproduced, and how easily it reproduces. If possible, please test on multiple
devices and Android versions.

**Comment by andrewlewis** [comment]
Please see https://exoplayer.dev/troubleshooting.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean. (Unfortunately the URL changed but the correct URL is now used on the release branch.)
