### ISSUE TITLE
Decoder init failed in viewpager

### ISSUE THREAD

**Issue by wellbranding** [google/ExoPlayer#6107]
We are receiving a bug, where Exoplayer does not load our MP4 files in the ViewPager after 5th attempt(it is predictable and occurs always). Here is crash log from ExoPlayer:

```
2019-06-28 14:11:03.758 30021-31428/com.idenfy.app.new E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:450)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:437)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:929)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:506)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:566)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [500, 500, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:437) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:929) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:506) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:566) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

**Comment by marcbaechinger** [comment]
How many ExoPlayer instances are hold by the view pager code after the 5th attempt? 

Background of that queston is that, the app code needs to make sure that you don't have more ExoPlayer instances than instances of media codecs a device provides. 

Can you please take a [bug report](https://developer.android.com/studio/debug/bug-report) right after the crash and upload it? You can also send it to dev.exoplayer@gmail.com if you don't want to upload here in public.

You can also look into the logs yoursefl and watch out for [the log statements indicating initialization and release of instances](https://exoplayer.dev/listening-to-player-events.html#player-information).  There are statements similar to these:

```
ExoPlayerImpl: Init 2e5194c [ExoPlayerLib/2.9.6] [marlin, Pixel XL, Google, 26]
...
ExoPlayerImpl: Release 2cd6e65 [ExoPlayerLib/2.9.6] [marlin, Pixel XL, Google, 26] [goog.exo.core, goog.exo.ui, goog.exo.dash]
```

If you find 5 init statements not resolved by a release statement, I'd interpret that that your device is running out of mp4 decoders which produces the exception you are reporting. It happens when no more codecs can be instantiated because all codecs in use.

**Comment by manishPatwari** [comment]
@marcbaechinger Is there any way in Exoplayer 2.9.6, to reuse the allocated decoder or maintain some kind of codec pool which will take care of max limit in the device?
We need multiple codec initialization because of fast switching between videos.
