### ISSUE TITLE
How To Handler Player On Incoming Call (Android Marshmallow)

### ISSUE THREAD

**Issue by Navidhp** [google/ExoPlayer#6113]
player (pause or play) is oky in onPause or onResume lifecycle activity but phone incoming call , answer and end call back to player i have this error , on another android version like oreo everything is oky but in android 
Marshmallow have this problem
error : 
```06-30 12:37:59.915 12957-13081/com.novincinema.cinemamarket E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1287)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
06-30 12:37:59.919 12957-13081/com.novincinema.cinemamarket E/ExoPlayerImplInternal: Stop failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:1901)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:608)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:508)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:562)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:377)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:153)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:976)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:764)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:735)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:355)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)

   /// onPause Activity
   playerView.onPause();
  playerView.getPlayer().setPlayWhenReady(true);

  /// onResume Activity 
  playerView.onResume();
  playerView.getPlayer().setPlayWhenReady(true);

**Comment by andrewlewis** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

In particular, it would be useful to have a full bug report captured using "adb bugreport" after reproducing the error. You can attach it here or email it to dev.exoplayer@gmail.com with subject "Issue #6113".

**Comment by richanshah** [comment]
yes i am also facing this kind of issue,When call is coming video is not recording

**Comment by Navidhp** [comment]
@richanshah are you application has been crash ?

**Comment by richanshah** [comment]
No it's not crashing but I don't get video recording when phone has came
