### ISSUE TITLE
Using Android keystore with Widevine DRM

### ISSUE THREAD

**Issue by JJSarrasin** [google/ExoPlayer#6135]
### Searched documentation and issues
I've searched in the closed issues, documentation and in the source code / Google / Stackoverflow..

### Question
Our backend must use mutual authentication through a PKCS12 certificate. I'm doing this with the following lines of code. It's working great for all OkHttp requests (through retrofit)
`val isP12 = context.resources.openRawResource(R.raw.my_cert)
  keystore = KeyStore.getInstance("PKCS12")
  keystore!!.load(isP12, a())
  isP12.close()`
Everything is working fine with Exoplayer (logic as our stream url aren't protected with mutual auth), but with Widevine auth, it's proxied through our backend server with mutual auth and I've the error reported in the below section. Is it possible to configure the HttpMediaDrmCallback to use the keystore ? As the stacktrace seems to mention, it uses okhttp. Why should we have a specific configuration ? I've tested to disable the mutual auth and it works fine in this case.

### A full bug report captured from the device
2019-07-05 09:09:41.675 23401-23401/com.mypackage E/EventLogger: playerFailed [5.45, 0.00, window=0, period=0]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://host:9443/xxx/xxx/token/
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.shouldWaitForKeys(MediaCodecRenderer.java:1118)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1071)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:650)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://host:9443/xxx/xxx/token/
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:446)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:441)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:406)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:49)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$PostResponseHandler.handleMessage(DefaultDrmSession.java:479)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://host:9443/xxx/xxx/token/
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:287)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)
        at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:152)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:165)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:136)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$PostRequestHandler.handleMessage(DefaultDrmSession.java:513)
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:286)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
2019-07-05 09:09:41.677 23401-23401/com.mypackage E/EventLogger:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
        at com.google.firebase.perf.network.zzd.connect(com.google.firebase:firebase-perf@@18.0.1:13)
        at com.google.firebase.perf.network.zze.connect(com.google.firebase:firebase-perf@@18.0.1:5)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:551)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:443)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:285)
        	... 10 more
     Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xa8a66f48: Failure in SSL library, usually a protocol error
    error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (external/boringssl/src/ssl/tls_record.cc:592 0xa02e1008:0x00000001)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
        	... 27 more

### Link to test content
Tell me if you need access to our stream and DRM as it can be time consuming to prepare the environment for you.

**Comment by tonihei** [comment]
You can specify a `MediaDrmCallback` when creating your `DefaultDrmSessionManager`. This callback allows you to execute the request however you want. You should probably use a `HttpMediaDrmCallback` and use your customized `DataSource` in there. That is assuming your special authentication is handled in a `DataSource`.

**Comment by JJSarrasin** [comment]
Thanks tonihei for pointing the direction. I could use the OkHttpDataSourceFactory instead of the default one. Here is a quick example of DrmSessionManager generation for people who might be interested :

`private fun buildDrmSessionManagerV18(uuid: UUID, licenseUrl: String, multiSession: Boolean): DefaultDrmSessionManager<FrameworkMediaCrypto> {
        val licenseDataSourceFactory = OkHttpDataSourceFactory(myHttpClient, myUserAgent, null)
        val drmCallback = HttpMediaDrmCallback(licenseUrl, licenseDataSourceFactory)
        releaseMediaDrm()
        mediaDrm = FrameworkMediaDrm.newInstance(uuid)
        return DefaultDrmSessionManager(uuid, mediaDrm!!, drmCallback, null, multiSession)
    }`

implementation 'com.google.android.exoplayer:extension-okhttp:r2.0.2'
