### ISSUE TITLE
Exception playing secure DASH/Widevine stream on Samsung Galaxy S4

### ISSUE THREAD

**Issue by makos88** [google/ExoPlayer#614]
Hi
After few seconds of playback i have exception. This same stream works on others devices (for example: Nexus 7, Samsung Galaxy S3, Samsung Tab, Samsung Galaxy S6). Someone had a similar problem and help me.

```
07-09 14:24:15.295: E/WVCdm(305): Decrypt error result in session sid2 during unencrypted block: 1
07-09 14:24:15.295: E/ExoPlayerImplInternal(11393): Internal track renderer error.
07-09 14:24:15.295: E/ExoPlayerImplInternal(11393): com.app.exoplayer.k: android.media.MediaCodec$CryptoException: Error decrypting data.
07-09 14:24:15.295: E/ExoPlayerImplInternal(11393): 	at com.app.exoplayer.A.a(Unknown Source)
07-09 14:24:15.295: E/ExoPlayerImplInternal(11393): 	at com.app.exoplayer.A.a(Unknown Source)
07-09 14:24:15.295: E/ExoPlayerImplInternal(11393): 	at com.app.exoplayer.r.handleMessage(Unknown Source)
07-09 14:24:15.295: E/ExoPlayerImplInternal(11393): 	at android.os.Handler.dispatchMessage(Handler.java:98)
07-09 14:24:15.295: E/ExoPlayerImplInternal(11393): 	at android.os.Looper.loop(Looper.java:145)
07-09 14:24:15.295: E/ExoPlayerImplInternal(11393): 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-09 14:24:15.295: E/ExoPlayerImplInternal(11393): 	at com.app.exoplayer.util.PriorityHandlerThread.run(Unknown Source)
07-09 14:24:15.295: E/ExoPlayerImplInternal(11393): Caused by: android.media.MediaCodec$CryptoException: Error decrypting data.
07-09 14:24:15.295: E/ExoPlayerImplInternal(11393): 	at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
07-09 14:24:15.295: E/ExoPlayerImplInternal(11393): 	at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:956)
07-09 14:24:15.295: E/ExoPlayerImplInternal(11393): 	... 7 more
07-09 14:24:15.295: E/EventLogger(11393): internalError [38.61, cryptoError]
07-09 14:24:15.295: E/EventLogger(11393): android.media.MediaCodec$CryptoException: Error decrypting data.
07-09 14:24:15.295: E/EventLogger(11393): 	at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
07-09 14:24:15.295: E/EventLogger(11393): 	at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:956)
07-09 14:24:15.295: E/EventLogger(11393): 	at com.app.exoplayer.A.a(Unknown Source)
07-09 14:24:15.295: E/EventLogger(11393): 	at com.app.exoplayer.A.a(Unknown Source)
07-09 14:24:15.295: E/EventLogger(11393): 	at com.app.exoplayer.r.handleMessage(Unknown Source)
07-09 14:24:15.295: E/EventLogger(11393): 	at android.os.Handler.dispatchMessage(Handler.java:98)
07-09 14:24:15.295: E/EventLogger(11393): 	at android.os.Looper.loop(Looper.java:145)
07-09 14:24:15.295: E/EventLogger(11393): 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-09 14:24:15.295: E/EventLogger(11393): 	at com.app.exoplayer.util.PriorityHandlerThread.run(Unknown Source)
```

**Comment by DavidMihola** [comment]
Since you don't mention the Android version (and since the S4 used to ship with Android 4.2 IIRC) let me remark that ExoPlayer supports DRM only from Android 4.3/API 18.

http://google.github.io/ExoPlayer/guide.html#digital-rights-management

**Comment by makos88** [comment]
I have installed Android version: 5.0.1

**Comment by ojw28** [comment]
Is this one of the DRM streams in the demo app, or one of your own? Do the ones in the demo app work correctly (if not - exactly which ones fail)? Thanks.

**Comment by makos88** [comment]
This is my own video stream. Streams in demo app work correctly.

**Comment by ojw28** [comment]
How sure are you that the content is packaged correctly? If it's just your stream that reproduces the problem, my guess would be that it's most likely one of two things (a) a packaging issue, or (b) you're setting something in your key response that the S4 has problems handling, and which isn't set in the test streams.

Without a working stream / license server, it's not going to be possible for us to debug any further.
