### ISSUE TITLE
Error code in android.media.MediaCodec$CodecException

### ISSUE THREAD

**Issue by surajsau** [google/ExoPlayer#6141]
### [REQUIRED] Searched documentation and issues
I've tried figuring out the error code received from the native code :
[dequeueOutputBuffer](https://android.googlesource.com/platform/frameworks/av/+/jb-mr0-release/media/libstagefright/MediaCodec.cpp#261) which then calls [postAndAwaitResponse](https://android.googlesource.com/platform/frameworks/av/+/master/media/libstagefright/foundation/AMessage.cpp#417). `ENOENT` and `ENOMEM` when converted to Hexadecimal doesn't seem to match the one we get in the logs.

### [REQUIRED] Question
This is the exception I recieve sometimes in my Crashlytics
```
android.media.MediaCodec$CodecException: Error 0x80000000
at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2752)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1427)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:654)
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:209)
at android.os.HandlerThread.run(HandlerThread.java:67)
```
Can anyone explain what the Hexadecimal code `0x80000000` actually stands for? I've also seen another error code like `0xfffffffed`. Is there any documentation of such error codes available? Would greatly appreciate if anyone provides more insight to this.

Thank you

**Comment by andrewlewis** [comment]
I could be wrong but I think the place to look for these error codes is [MediaErrors.h](https://android.googlesource.com/platform/frameworks/av/+/refs/heads/master/media/libstagefright/include/media/stagefright/MediaErrors.h) and the files it refers to. Unfortunately this looks like a generic unknown error. When seeing a codec exception, there is often some logging earlier in logcat that provides more diagnostic information about what went wrong, but I doubt Crashlytics includes a full logcat, so your best bet may be to see what devices/builds are affected and try to reproduce the issue yourself.
