### ISSUE TITLE
Is it possible to convert TS files to MP3 using Exoplayer ?

### ISSUE THREAD

**Issue by satyres** [google/ExoPlayer#6142]
Hi 
i've been looking for a solution to play local TS files but it seems not possible.
is there a way to convert an Audio TS file to MP3 using Exoplayer or any external library ?
Regards

**Comment by ojw28** [comment]
* ExoPlayer doesn't support transcoding from one format to another.
* ExoPlayer does support playback of TS files, although it's also necessary for the contained sample formats to be supported. Please see the [supported formats page](https://exoplayer.dev/supported-formats.html) for more information.

**Comment by satyres** [comment]
Thanks so much for your answer @ojw28 
i have a TS file and i've tried to make play using Exoplayer but it doesn't work 
but it works on VLC.
is there any way  FLAG or something i need to do to make it work ?
this is the logcat :

 com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:185)
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:53)
        at com.google.android.exoplayer2.offline.FilteringManifestParser.parse(FilteringManifestParser.java:41)
        at com.google.android.exoplayer2.offline.FilteringManifestParser.parse(FilteringManifestParser.java:25)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:158)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)



Regards

**Comment by ojw28** [comment]
You need to use `ProgressiveMediaSource` to play a TS stream, not `HlsMediaSource`. Please note that you can simply add your TS stream to the demo app as per [these instructions](https://exoplayer.dev/demo-application.html), and then take a look at the code to see how it's done.

**Comment by satyres** [comment]
Thanks @ojw28 .
it's not an online stream ,it's  local file that i want to play using Exoplayer.
do i need to use ProgressiveMediaSource ?
Regards

**Comment by ojw28** [comment]
Yes

**Comment by satyres** [comment]
Excellent i' ve been able to play it using the 2.9.6 using ExtractorMediaSource 
and it's working but i cannot jump from time to time and the total play time showing 00:00
but it's working fine
do i need to upgrade to 2.10.2 ?
Any way thanks so much.
Regards

**Comment by ojw28** [comment]
You should try 2.10.2. If it's still not working, you should track https://github.com/google/ExoPlayer/issues/5097 for further improvements.
