### ISSUE TITLE
DownloadHelperTest Failed

### ISSUE THREAD

**Issue by drayan85** [google/ExoPlayer#6146]
### [REQUIRED] Issue description
When I try to run ExoPlayer library core test cases keep failing

### [REQUIRED] Reproduction steps
When try to Run `DownloadHelperTest.java` is keep failing 

### [REQUIRED] Link to test content
N/A

### [REQUIRED] A full bug report captured from the device
```
[Robolectric] com.google.android.exoplayer2.offline.DownloadHelperTest.getTrackSelections_afterReplaceTrackSelections_returnsNewSelections: sdk=28; resources=BINARY
Exception in thread "DownloadHelper" java.lang.NullPointerException
	at com.google.android.exoplayer2.offline.DownloadHelper$MediaPreparer.onSourceInfoRefreshed(DownloadHelper.java:918)
	at com.google.android.exoplayer2.source.BaseMediaSource.refreshSourceInfo(BaseMediaSource.java:74)
	at com.google.android.exoplayer2.testutil.FakeMediaSource.finishSourcePreparation(FakeMediaSource.java:215)
	at com.google.android.exoplayer2.testutil.FakeMediaSource.prepareSourceInternal(FakeMediaSource.java:105)
	at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:140)
	at com.google.android.exoplayer2.offline.DownloadHelper$MediaPreparer.handleMessage(DownloadHelper.java:858)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at com.google.android.exoplayer2.testutil.RobolectricUtil$CustomLooper.doLoop(RobolectricUtil.java:129)
	at com.google.android.exoplayer2.testutil.RobolectricUtil$CustomLooper.loop(RobolectricUtil.java:67)
	at android.os.Looper.loop(Looper.java)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

### [REQUIRED] Device(s) and version(s) of Android being used
N/A

**Comment by ojw28** [comment]
It passes for me. We also run these tests on every commit and as part of our release process. Could you share a bit more detail about how you're able to reproduce this?

Also, it looks impossible to me that [this line would throw a NPE](https://github.com/google/ExoPlayer/blob/r2.10.2/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadHelper.java#L918). I think that would mean `mediaPeriods` is null, but it's assigned right above. Can you see any way that a NPE can happen?

```
[Robolectric] com.google.android.exoplayer2.offline.DownloadHelperTest.getTrackSelections_afterAddAudioLanguagesToSelection_returnsCombinedSelections: sdk=28; resources=BINARY
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28
[Robolectric] com.google.android.exoplayer2.offline.DownloadHelperTest.getTrackSelections_afterReplaceTrackSelections_returnsNewSelections: sdk=28; resources=BINARY
[Robolectric] com.google.android.exoplayer2.offline.DownloadHelperTest.getTrackGroups_returnsTrackGroups: sdk=28; resources=BINARY
[Robolectric] com.google.android.exoplayer2.offline.DownloadHelperTest.getMappedTrackInfo_returnsMappedTrackInfo: sdk=28; resources=BINARY
[Robolectric] com.google.android.exoplayer2.offline.DownloadHelperTest.getDownloadRequest_createsDownloadRequest_withAllSelectedTracks: sdk=28; resources=BINARY
[Robolectric] com.google.android.exoplayer2.offline.DownloadHelperTest.getTrackSelections_afterAddTrackSelections_returnsCombinedSelections: sdk=28; resources=BINARY
[Robolectric] com.google.android.exoplayer2.offline.DownloadHelperTest.getTrackSelections_afterClearTrackSelections_isEmpty: sdk=28; resources=BINARY
[Robolectric] com.google.android.exoplayer2.offline.DownloadHelperTest.getPeriodCount_returnsPeriodCount: sdk=28; resources=BINARY
[Robolectric] com.google.android.exoplayer2.offline.DownloadHelperTest.getManifest_returnsManifest: sdk=28; resources=BINARY
[Robolectric] com.google.android.exoplayer2.offline.DownloadHelperTest.getTrackSelections_returnsInitialSelection: sdk=28; resources=BINARY
[Robolectric] com.google.android.exoplayer2.offline.DownloadHelperTest.getTrackSelections_afterAddTextLanguagesToSelection_returnsCombinedSelections: sdk=28; resources=BINARY

Process finished with exit code 0
```

**Comment by tonihei** [comment]
Please also note though that we changed the Robolectric threading system substantially in our dev branch tests, so the tests running for every commit don't actually guarantee that they run in the release version as well.

**Comment by drayan85** [comment]
It actually in the code base locally NPE is in the next line of code `pendingMediaPeriods.add(mediaPeriod);`


1) If I run the test cases one by one, all the test cases are passing successfully.

2) If I put `TimeUnit.SECONDS.sleep(5);` after the `prepareDownloadHelper(downloadHelper);` in each test suit, all test cases passes successfully.

**Comment by ojw28** [comment]
Thanks! I think I see the problem now (the `MediaPreparer` constructor should initialize `pendingMediaPeriods` before it starts `mediaSourceThread`).

**Comment by drayan85** [comment]
Thanks, @ojw28. I have shifted the `pendingMediaPeriods = new ArrayList<>()` initialization above the `mediaSourceThread.start()` in the `DownloadHelper.java` as below.

```
    public MediaPreparer(MediaSource mediaSource, DownloadHelper downloadHelper) {
      this.mediaSource = mediaSource;
      this.downloadHelper = downloadHelper;
      allocator = new DefaultAllocator(true, C.DEFAULT_BUFFER_SEGMENT_SIZE);
      @SuppressWarnings("methodref.receiver.bound.invalid")
      Handler downloadThreadHandler = Util.createHandler(this::handleDownloadHelperCallbackMessage);
      this.downloadHelperHandler = downloadThreadHandler;
      mediaSourceThread = new HandlerThread("DownloadHelper");
      pendingMediaPeriods = new ArrayList<>();
      mediaSourceThread.start();
      mediaSourceHandler = Util.createHandler(mediaSourceThread.getLooper(), /* callback= */ this);
      mediaSourceHandler.sendEmptyMessage(MESSAGE_PREPARE_SOURCE);
    }
```

No all the test suits pass successfully.

**Comment by ojw28** [comment]
Yes, we'll push a fix for this shortly. Thanks for the bug report!
