### ISSUE TITLE
Switching between encrypted and unencrypted content in the same stream - currently supported?

### ISSUE THREAD

**Issue by jrw95** [google/ExoPlayer#6154]
### [REQUIRED] Searched documentation and issues
- Searched through the issues with `is:issue encrypted unencrypted` (to produce the broadest result)
- Looked through the [Developer Guide, Media Sources](https://exoplayer.dev/media-sources.html) - focused on Advanced Composition, but nothing discussed concatenating encrypted and unencrypted segments, just URIs.
- Google search of `ExoPlayer switch encrypted to unencrypted` did not return anything helpful.

### [REQUIRED] Question
We are attempting to play Widevine HLS live streams containing unencrypted server-side ads, using ExoPlayer 2.10.2, and are encountering a failure when the player tries to play the unencrypted ad content. We can reproduce this in the ExoPlayer 2.10.2 NoExtension demo app, and have done so on a Samsung S7 running Android 6.0.1 and a Google Pixel running Android 9.0.

The use case that we want to support here is a Widevine Modular protected live stream with a large inventory of ad content, where it would be more performant to serve the ad content unencrypted, rather than encrypt the entire ad inventory at every ad break.

Is a use case like this currently supported in ExoPlayer?
Note that our use case is currently focused on Widevine Modular HLS with unencrypted ad content, but we will also need to support Widevine Modular DASH with unencrypted ad content as well.

### A full bug report captured from the device
adb bugreport for the Pixel (Android 9.0) attached.
[bugreport-sailfish-PQ3A.190605.003-2019-07-09-10-56-53.zip](https://github.com/google/ExoPlayer/files/3373612/bugreport-sailfish-PQ3A.190605.003-2019-07-09-10-56-53.zip)

### Link to test content
Test content links have been emailed.

Behavior observed:
- If you open the stream, and an ad is playing, the ad seems to play OK, and then seems to transition to the content (Big Buck Bunny) without apparent issues.
- If instead you open the stream and the content is playing, stream does not transition to the unencrypted ad content. Instead, an exception is thrown and playback fails:
```
2019-07-09 11:02:32.037 4035-4035/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [123.83, 9.65, window=0, period=0]
    com.google.android.exoplayer2.ExoPlaybackException: java.io.EOFException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:386)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.io.EOFException
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:265)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:102)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:110)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:430)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:318)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:357)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:325)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:301)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by ojw28** [comment]
I don't think HLS is designed for mixing FMP4 and TS segments into a single media playlist, as is the case here. The failure point happens when the player refreshes the media playlist and gets one that looks like this:

```
EXT-X-MAP=mp4-init-segment
EXT-X-KEY=drm-stuff
mp4-segment-url
...
EXT-X-DISCONTINUITY
...
EXT-X-KEY:METHOD=NONE
ts-segment-url
```

As per the HLS RFC, the `EXT-X-MAP` initialization data applies to every segment until the next `EXT-X-MAP`. So this media playlist is incorrectly attaching MP4 initialization data onto TS segments, which ultimately causes the playback failure.

It's notable that your playlist will explicitly clear `EXT-X-KEY`, and that the HLS RFC doesn't define an equivalent for `EXT-X-MAP` (i.e. there's no way to specify `EXT-X-MAP=NONE`). Which is why I conclude that HLS is not really designed to handle what you're trying to do.

**Comment by ojw28** [comment]
A few additional points:

1. You could probably come up with suitable initialization data for the TS segments, and add an `EXT-X-MAP` to point to that initialization data after the discontinuity. The spec defines TS initialization data to consist of a PAT followed by a PMT. I'm not actually certain whether we handle this, since I've never seen initialization data provided out-of-segment for TS, but it would at least make your content (possibly?) spec compliant. It doesn't seem ideal to have to do this though.
1. Turns out we asked someone involved in writing the HLS RFC about mixing TS and FMP4 segments in media playlists a while back. The response was (paraphrasing): Don't make this kind of content; you're not helping anyone. Make of that what you will :).

**Comment by sergiomartinez4** [comment]
@ojw28 a follow-up question on this. Taking the TS and FMP4 mixing out of the equation, is switching between encrypted and un-encrypted segments (both ways) a valid scenario?

**Comment by ojw28** [comment]
Yes.
