### ISSUE TITLE
Multi-Period DASH WV on Nexus 6P

### ISSUE THREAD

**Issue by ssenanayake** [google/ExoPlayer#6255]
### [REQUIRED] Issue description
Playback of Multi-Period DASH (No DRM for Ad periods, WV DRM for Content periods), freezes when transitioning from Ad Period to Content Period on Nexus 6P in Landscape mode. Works ok on Portrait mode.

### [REQUIRED] Reproduction steps
1) Use the latest Exoplayer Demo app code, "demo" module.
2) The media.exolist.json file is indicated below.
3) Try playback in Landscape mode on a Nexus 6P

### [REQUIRED] Link to test content
Here's the media.exolist.json file content
```
[
  {
    "name": "Widevine MultiPeriod DASH Test",
    "samples": [
      {
        "name": "BBB WV: Test",
        "uri": "https://dai.google.com/ondemand/dash/content/2497752/vid/19A7D434-8AC8-3835-5681-54E32CBA735B/DLS/streams/4cc557f8-b7d0-49e2-9fef-10150bc9fd1e/manifest.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://cbsi.live.ott.irdeto.com/widevine/getlicense?CrmId=cbsi&AccountId=cbsi&SubContentType=Default&ContentId=19A7D434-8AC8-3835-5681-54E32CBA735B"
      }
    ]
  }
]
```

### [REQUIRED] A full bug report captured from the device
Error indicated in the logcat:

```
2019-08-01 14:06:58.641 4288-4288/com.cbs.ott E/com.cbsi.android.uvp.player.core.VideoPlayer: Playback Errorandroid.media.MediaCodec$CryptoException: Operation not supported in this configuration @access$3200:138,onPlayerError:3053,handleEvent:611,handleMessage:125,dispatchMessage:105
2019-08-01 14:07:01.229 4288-5710/com.cbs.ott E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Operation not supported in this configuration
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1063)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:680)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.media.MediaCodec$CryptoException: Operation not supported in this configuration
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2532)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1049)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:680) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

### [REQUIRED] Version of ExoPlayer being used
2.10.4

### [REQUIRED] Device(s) and version(s) of Android being used
Nexus 6P on Android 7.1.2

**Comment by ojw28** [comment]
The provided link 404s for me:

``` 
> wget https://dai.google.com/ondemand/dash/content/2497752/vid/19A7D434-8AC8-3835-5681-54E32CBA735B/DLS/streams/4cc557f8-b7d0-49e2-9fef-10150bc9fd1e/manifest.mpd
--2019-08-05 19:23:52--  https://dai.google.com/ondemand/dash/content/2497752/vid/19A7D434-8AC8-3835-5681-54E32CBA735B/DLS/streams/4cc557f8-b7d0-49e2-9fef-10150bc9fd1e/manifest.mpd
Resolving dai.google.com (dai.google.com)... 2a00:1450:4009:817::200e, 172.217.169.78
Connecting to dai.google.com (dai.google.com)|2a00:1450:4009:817::200e|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-08-05 19:23:53 ERROR 404: Not Found
```

Please could you check the link?

**Comment by ssenanayake** [comment]
Updated URL: https://dai.google.com/ondemand/dash/content/2497752/vid/19A7D434-8AC8-3835-5681-54E32CBA735B/DLS/streams/224a0c1d-1982-466a-a305-4875c5323135/manifest.mpd

The Google DAI URLs do expire. But you can run the following curl and the "stream_manifest" field of the JSON contains a new time tokenized manifest url:

curl -X POST --data '' 'https://dai.google.com/ondemand/dash/content/2497752/vid/19A7D434-8AC8-3835-5681-54E32CBA735B/streams' | python -mjson.tool

**Comment by ojw28** [comment]
Hmm, now I'm getting 403s for content starting at ~15 seconds. I tried generating my own URL using the command above and with that I got 403s starting at 0 seconds. Is it possible some of the ads (or the content itself) are geo-restricted?

**Comment by ojw28** [comment]
It works using a US proxy, so I guess I can do that. I'll need to dig out a Nexus 6P for testing. Just to confirm: Am I right in thinking you haven't seen this on any other devices? Playback seems to work without failure on a Galaxy S8.

Thanks!

**Comment by ssenanayake** [comment]
Checked with our QA team....So far our QA has only reproduced this behavior on a Nexus 6 and Nexus 6P. We dont have an exhaustive list of devices, but the Nexus 6 & 6P are two of our test devices. Samsung devices have been fine for us too.

**Comment by ojw28** [comment]
I was able to reproduce this. It seems like something is going badly wrong at quite a low level in the platform, since the entire device locks up. Eventually the system UI process hangs, and sometimes the device reboots. The problem also reproduces with Android 8.1.0, which is the last major platform update that Nexus 6P received. 

Given Nexus 6P is no longer receiving major platform updates, it's unclear whether we'll be able to fix this. I'll spend a bit of time seeing if it's possible to work around the problem in ExoPlayer, but realistically we can't justify sinking a lot of time into this.

**Comment by ssenanayake** [comment]
Quick update: Setting L3 seems to work on the Nexus 6P.

frameworkMediaDrm.setPropertyString("securityLevel", "L3")

will update after our QA team does more thorough testing.

**Comment by ojw28** [comment]
Yes, I observe this too.

**Comment by ojw28** [comment]
I don't think there's anything we can do about this at the ExoPlayer level. Workaround around the issue by forcing L3 Widevine seems like the best solution.
