### ISSUE TITLE
Media decode issue

### ISSUE THREAD

**Issue by chiragpindianic** [google/ExoPlayer#6264]
I am implementing Exoplayer in view pager, but there is some time occurs error with media codec.

When view pager resume first release simple player and then after intilize player, but some time thorw execption below: 

com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc,android

Please request you to give a solution to that error.

Thanks

**Comment by ojw28** [comment]
Most likely you haven't released the previous player(s), and the underlying platform has run out of resources to allocate a new decoder.

The description doesn't provide sufficient information for us to help or diagnose further. Please properly fill in the [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=) if you require further assistance (copy and paste it here, rather than filing a new issue).

**Comment by chiragpindianic** [comment]
### [REQUIRED] Issue description
I am trying to implementing exoplayer in my app, I have added exoplayer in viewpager with FragmentStatePagerAdapter. There are five pages in viewpager with the same fragment with a new instance, particular fragment to implement exoplayer with a different video. Exoplayer initilize in fragment onResume method, before intilize exoplayer release previous exoplayer.
But some time error ocure with media decore failed.

### [REQUIRED] Reproduction steps
When view pager page chnage than mostly 3 page to throw exception with MediaCodecRenderer$DecoderInitializationException.

### [REQUIRED] Link to test content
```
  @Override
    public void onResume() {
        super.onResume();
          releasePlayer();
          initializeVideoPlayer(playerView, Player.REPEAT_MODE_ONE, videoPath, null);
    }
// Initialize Video Player
public void initializeVideoPlayer(final PlayerView playerView, final int repeatMode, final String videoPath, final MediaEndListener mediaEndListener) {
        try {
            if (simpleExoVideoPlayer == null) {
                simpleExoVideoPlayer = ExoPlayerFactory.newSimpleInstance(getActivity(), new DefaultRenderersFactory(context), new DefaultTrackSelector());
            }

            if (playerView != null) {
                this.playerView = playerView;
                if (mediaEndListener != null) {
                    this.mediaEndListener = mediaEndListener;
                    mediaPlayEventListener = new MediaPlayEventListener();
                }
                playerView.setPlayer(simpleExoVideoPlayer);
                final MediaSource mediaSource = initVideoMediaSource(videoPath);
                simpleExoVideoPlayer.prepare(mediaSource);
                simpleExoVideoPlayer.setPlayWhenReady(true);
                simpleExoVideoPlayer.setRepeatMode(repeatMode);
                simpleExoVideoPlayer.addListener(new Player.DefaultEventListener() {

                    @Override
                    public void onPlayerError(ExoPlaybackException error) {
                        super.onPlayerError(error);
                        error.printStackTrace();
                    }
                });

                if (mediaPlayEventListener != null) {
                    simpleExoVideoPlayer.addListener(mediaPlayEventListener);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
}

// Release player
 public void releasePlayer() {
        if (simpleExoVideoPlayer != null) {
            simpleExoVideoPlayer.release();
            simpleExoVideoPlayer = null;
        }

        if (playerView != null) {
            playerView.setPlayer(null);
}
```

### [REQUIRED] A full bug report captured from the device
```
E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1000, 1778, 30.000002], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:512)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1186)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:634)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:733)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:644)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1000, 1778, 30.000002], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:786)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:510)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1186) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:634) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:733) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:644) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1960)
        at android.media.MediaCodec.configure(MediaCodec.java:1889)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:569)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:847)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:779)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:510) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1186) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:634) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:733) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:644) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```
### [REQUIRED] Version of ExoPlayer being used
```
configuration.implementation 'com.google.android.exoplayer:exoplayer-core:2.10.3'
configuration.implementation 'com.google.android.exoplayer:exoplayer-dash:2.10.3'
configuration.implementation 'com.google.android.exoplayer:exoplayer-ui:2.9.2'
```
### [REQUIRED] Device(s) and version(s) of Android being used
Device: Mi A1 Andoird Version: 9  
Device: Mi A2 Andoird Version: 9

**Comment by chiragpindianic** [comment]
@ojw28 Can you please look at this and lead me in the right direction? I'll really appreciate if you can guide me forward on this.

**Comment by ojw28** [comment]
I can't see anything particularly wrong with the code snippet above. Given the lack of an obvious issue, I think we'd most likely require concrete reproduction steps to provide further guidance. E.g., you could create a sample project that reproduces the problem and put it on GitHub, so that we can try and reproduce the problem ourselves.
