### ISSUE TITLE
can't stream rtmpt link

### ISSUE THREAD

**Issue by bboykemo** [google/ExoPlayer#6275]
Hi ,
i tried often to play radio stream start with rtmpt but it show as :
```
2019-08-09 02:25:12.387 12287-12327/com.fmegy.myapplication E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to rtmpt://livestreaming5.onlinehorizons.net/pernamegaam/livestream
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:137)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
     Caused by: java.net.MalformedURLException: unknown protocol: rtmpt
        at java.net.URL.<init>(URL.java:596)
        at java.net.URL.<init>(URL.java:486)
        at java.net.URL.<init>(URL.java:435)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:341)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:137) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:776) 
```
it's working with vlc lib but takes long time to start and the lib is 50Mb which is so big to use .

**Comment by umangsaini** [comment]
Exoplayer doesn't support RTMPT (tunneled) URLs. 
If you play the same using RTMP with below URL, it will play 

> rtmp://livestreaming5.onlinehorizons.net/pernamegaam/livestream

Are you looking for RTMP-Tunneled support?

**Comment by bboykemo** [comment]
i tried this link also not working maybe my code missing something , can you share your test code so that i can understand where's my bug !
and one more question if i use RTMP-Tunneled it will handle rtmp , m3u8 and mp3 or only rtmpt ?
thank you

**Comment by umangsaini** [comment]
You need to enable Extensions for the Demo application to play RTMP links.
The instructions for the same is given in the documentation - [Link](https://exoplayer.dev/demo-application.html).
I was not able to play RTMP-Tunneled link, but RTMP link works.

**Comment by bboykemo** [comment]
Still i couldn't play it also after enable Extensions i don't know exactly where's the problem even i downloaded many git demo app to stream rtmp also not working also when i write code to stream not working

**Comment by umangsaini** [comment]
You will need to submit a bug report with all the details. The template for the same is at this [link](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md).

**Comment by AquilesCanta** [comment]
As stated by @umangsaini, please provide all information required by the [template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md).
