### ISSUE TITLE
playback issue with the content intermittently . Throws Crypto Error

### ISSUE THREAD

**Issue by nikhilkawatra** [google/ExoPlayer#6277]
playback issue is coming with the content intermittently . Throws Crypto Error.

Checked the mpd file for Working and Non Working cases and saw some difference .. Want to know if its really affecting the playback ?

Following is the error 

 com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Crypto key not available
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1122)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:654)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)

What should be the expected behaviour ?
[working.txt](https://github.com/google/ExoPlayer/files/3486521/working.txt)
[non_working.txt](https://github.com/google/ExoPlayer/files/3486522/non_working.txt)

Thanks.

**Comment by AquilesCanta** [comment]
Crypto key not available usually means that the server is not returning the required key, which may be a server issue. We need the full [template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md) information to assist further. Also worth checking [this documentation](https://exoplayer.dev/drm.html#multi-key-content), just in case.

**Comment by nikhilkawatra** [comment]
Thanks for the response. We are getting this error on random assets .

Below are some of the additional logs from yesterday's instance 

policy_engine.cpp(55):CanDecryptContent] PolicyEngine::CanDecryptContent Key '0FD1700388A24C55B48EBC269C37FA24' not in license.
2019-08-28 00:13:16.988 3056-7904/? E/WVCdm: Decrypt error result in session sid137 during encrypted block: 5
2019-08-28 00:13:16.990 4233-15209/? E/ExoPlayerImplInternal: Playback error.

Another Error from the logs that I can see related to Widewine are below

2019-08-28 00:23:22.867 3056-13093/? E/WVCdm: [initialization_data.cpp(129):SelectWidevinePssh] InitializationData::SelectWidevinePssh: The concatenated PSSH boxes could be parsed, but no Widevine PSSH was found.
2019-08-28 00:23:22.867 3056-13093/? E/WVCdm: [initialization_data.cpp(75):InitializationData] InitializationData: Unable to select a supported Widevine PSSH from the init data.

Issue gets resolved after few hours typically 24 hours time.

Do you see any issue with the mpd or drm licensing ?

**Comment by AquilesCanta** [comment]
If you have any evidence pointing at this being an ExoPlayer issue, please file a new issue including all the information requested in the issue template (link in the comment above).

> Issue gets resolved after few hours typically 24 hours time.

This suggests this is not an ExoPlayer issue. Plus, if the content is not changing in this 24 hours, it means the license server is changing its behavior. Sounds like a delay in the server when publishing the licenses required by the protected content.
