### ISSUE TITLE
ExoPlayer PlayerView not initializing when starting activity second time

### ISSUE THREAD

**Issue by rakeshostwal** [google/ExoPlayer#6278]
I have a onboarding activity where i have a view pager which loads 3 videos. Videos are loaded from assets only. When app is launched, it loads correctly, but when user logs out and come back to this screen again it shows blanck player view.

**NOTE:** This happens on Samsung device only

###  Reproduction steps

1. Launch App, observe Onboarding screen with player view pager
2.  Login to the app
3.  Logout and come back to Onboarding screen and observe player view pager

### A full bug report captured from the device
```
2019-08-09 17:11:44.898 8191-8191/com.sample.android D/ViewRootImpl@47b5abe[WelcomeActivity]: Relayout returned: old=[0,0][0,0] new=[0,0][1080,1920] result=0x7 surface={valid=true 3089391616} changed=true
2019-08-09 17:11:44.899 8191-9197/com.sample.android I/BufferQueue: [unnamed-8191-8](this:0xb5c2f000,id:8,api:0,p:-1,c:-1) BufferQueue core=(8191:com.sample.android)
2019-08-09 17:11:44.899 8191-9184/com.sample.android I/BufferQueueConsumer: [SurfaceTexture-1-8191-7](this:0xb74fd000,id:7,api:3,p:-1,c:-1) disconnect(C)
2019-08-09 17:11:44.899 8191-9197/com.sample.android W/GuiExt: Cannot find GuiExtService
2019-08-09 17:11:44.899 8191-8494/com.sample.android D/Surface: Surface::connect(this=0xb8246000,api=1)
2019-08-09 17:11:44.900 8191-9197/com.sample.android I/BufferQueueConsumer: [unnamed-8191-8](this:0xb5c2f000,id:8,api:0,p:-1,c:8191) connect(C): consumer=(8191:com.sample.android) controlledByApp=true
2019-08-09 17:11:44.900 8191-9197/com.sample.android I/BufferQueueConsumer: [unnamed-8191-8](this:0xb5c2f000,id:8,api:0,p:-1,c:8191) setConsumerName: unnamed-8191-8
2019-08-09 17:11:44.900 8191-9197/com.sample.android I/BufferQueueConsumer: [SurfaceTexture-1-8191-8](this:0xb5c2f000,id:8,api:0,p:-1,c:8191) setConsumerName: SurfaceTexture-1-8191-8
2019-08-09 17:11:44.901 8191-8494/com.sample.android D/OpenGLRenderer: eglCreateWindowSurface = 0xb1620760, 0xb8246008
2019-08-09 17:11:44.903 8191-9191/com.sample.android D/SurfaceUtils: connecting to surface 0xca8f6808, reason connectToSurface
2019-08-09 17:11:44.903 8191-9191/com.sample.android D/Surface: Surface::connect(this=0xca8f6800,api=3)
2019-08-09 17:11:44.903 8191-9191/com.sample.android I/BufferQueueProducer: [SurfaceTexture-1-8191-8](this:0xb5c2f000,id:8,api:3,p:8191,c:8191) connect(P): api=3 producer=(8191:com.sample.android) producerControlledByApp=true
2019-08-09 17:11:44.903 8191-9191/com.sample.android I/MediaCodec: [OMX.MTK.VIDEO.DECODER.AVC] setting surface generation to 8387608
2019-08-09 17:11:44.903 8191-9191/com.sample.android D/SurfaceUtils: disconnecting from surface 0xca8f6808, reason connectToSurface(reconnect)
2019-08-09 17:11:44.903 8191-9191/com.sample.android D/Surface: Surface::disconnect(this=0xca8f6800,api=3)
2019-08-09 17:11:44.903 8191-9191/com.sample.android I/BufferQueueProducer: [SurfaceTexture-1-8191-8](this:0xb5c2f000,id:8,api:3,p:8191,c:8191) disconnect(P): api 3
2019-08-09 17:11:44.903 8191-9191/com.sample.android I/BufferQueueConsumer: [SurfaceTexture-1-8191-8](this:0xb5c2f000,id:8,api:3,p:-1,c:8191) getReleasedBuffers: returning mask 0xffffffffffffffff
2019-08-09 17:11:44.903 8191-9191/com.sample.android D/SurfaceUtils: connecting to surface 0xca8f6808, reason connectToSurface(reconnect)
2019-08-09 17:11:44.903 8191-9191/com.sample.android D/Surface: Surface::connect(this=0xca8f6800,api=3)
2019-08-09 17:11:44.903 8191-9191/com.sample.android I/BufferQueueProducer: [SurfaceTexture-1-8191-8](this:0xb5c2f000,id:8,api:3,p:8191,c:8191) connect(P): api=3 producer=(8191:com.sample.android) producerControlledByApp=true
2019-08-09 17:11:44.905 8191-9191/com.sample.android I/MediaCodec: failed to configure codec bacause of codec capacity
2019-08-09 17:11:44.905 8191-9191/com.sample.android E/MediaCodec: Codec reported err 0xffffec77, actionCode 0, while in state 3
2019-08-09 17:11:44.908 8191-9191/com.sample.android D/SurfaceUtils: disconnecting from surface 0xca8f6808, reason disconnectFromSurface
2019-08-09 17:11:44.908 8191-9191/com.sample.android D/Surface: Surface::disconnect(this=0xca8f6800,api=3)
2019-08-09 17:11:44.908 8191-9191/com.sample.android I/BufferQueueProducer: [SurfaceTexture-1-8191-8](this:0xb5c2f000,id:8,api:3,p:8191,c:8191) disconnect(P): api 3
2019-08-09 17:11:44.908 8191-9191/com.sample.android I/BufferQueueConsumer: [SurfaceTexture-1-8191-8](this:0xb5c2f000,id:8,api:3,p:-1,c:8191) getReleasedBuffers: returning mask 0xffffffffffffffff
2019-08-09 17:11:44.908 8191-9179/com.sample.android E/MediaCodec: configure failed with err 0xffffec77, resetting...
2019-08-09 17:11:44.920 8191-9192/com.sample.android I/ACodec:  [OMX.MTK.VIDEO.DECODER.AVC] Now uninitialized
2019-08-09 17:11:44.920 8191-9192/com.sample.android I/ACodec:  [] Now kWhatShutdownCompleted event : 8532
2019-08-09 17:11:44.920 8191-9191/com.sample.android I/MediaCodec: Codec shutdown complete
2019-08-09 17:11:44.921 8191-9179/com.sample.android I/ACodec:  [] Now uninitialized
2019-08-09 17:11:44.922 8191-9192/com.sample.android I/ACodec: [] onAllocateComponent
2019-08-09 17:11:44.923 8191-8191/com.sample.android D/SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.sample.android/com.sample.android.ui.activity.foodprofile.WelcomeActivity@f747e46@0) android.view.SurfaceView{f747e46 V.E...... ......ID 0,0-1080,919}
2019-08-09 17:11:44.924 8191-9192/com.sample.android I/OMXClient: Treble IOmx obtained
2019-08-09 17:11:44.927 8191-9192/com.sample.android I/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Now Loaded
2019-08-09 17:11:44.932 8191-8191/com.sample.android D/SurfaceView: surfaceCreated 1 #8 android.view.SurfaceView{f747e46 V.E...... ......ID 0,0-1080,919}
2019-08-09 17:11:44.932 8191-8191/com.sample.android D/SurfaceView: surfaceChanged (1080,919) 1 #8 android.view.SurfaceView{f747e46 V.E...... ......ID 0,0-1080,919}
2019-08-09 17:11:44.939 8191-8191/com.sample.android D/SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.sample.android/com.sample.android.ui.activity.foodprofile.WelcomeActivity@fa69515@0) android.view.SurfaceView{fa69515 V.E...... ......ID 0,0-1080,919}
2019-08-09 17:11:44.939 8191-9192/com.sample.android I/ACodec:  [OMX.MTK.VIDEO.DECODER.AVC] Now uninitialized
2019-08-09 17:11:44.940 8191-9192/com.sample.android I/ACodec:  [] Now kWhatShutdownCompleted event : 8532
2019-08-09 17:11:44.940 8191-9191/com.sample.android I/MediaCodec: Codec shutdown complete
2019-08-09 17:11:44.943 8191-9179/com.sample.android W/MediaCodecRenderer: Failed to initialize decoder: OMX.MTK.VIDEO.DECODER.AVC
    android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1943)
        at android.media.MediaCodec.configure(MediaCodec.java:1872)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-08-09 17:11:44.945 8191-9179/com.sample.android E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.AVC, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.AVC, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1943)
        at android.media.MediaCodec.configure(MediaCodec.java:1872)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 

```

###  Version of ExoPlayer being used

v2.9.0

### Device(s) and version(s) of Android being used

Samsung J7 Prime - v8.1

**Comment by AquilesCanta** [comment]
If this is a device specific issue, I'd suggest contacting the device manufacturer to report the issue. 

Being device specific, I am tempted to rule out the possibility of app-code bad resource management, since it should eventually fail in other devices too. 

There is not much I can do with the provided information, and we don't have the resources to investigate a device+app specific issue. If you have any evidence of this issue being and ExoPlayer issue, please complete the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) information and post below, or file a new issue.
