### ISSUE TITLE
Getting sometimes an ExoPlayerImplInternal: IllegalArgumentException

### ISSUE THREAD

**Issue by perracodex** [google/ExoPlayer#6346]
### Issue description
Getting a playback error randomly and in very rare occasions. It happens right after our app finishes encoding a new video, and a new ExoPlayer instance is created to play it. There are no problem with the videos themselves, as trying a playback again will not produce any error.

In our flow we encode a video using the MediaCodec API. Then ensure the video is fully saved to file. Release the MediaCodec and MediaMuxer resources. And finally open a new ExoPlayer instance to play it.

The only thing I can think of, and I’m only guessing, is that maybe there is some type of OS lock when the system is in the process of releasing the MediaCodec used for encoding, making ExoPlayer to fail. Although, besides the fact that I don’t know how long does the OS take to release the codec resources, I don’t see why ExoPlayer would need a video codec which was used only for encoding, and not decoding.

### Reproduction steps
To play a video right after has been created/encoded. The problem happens in very rare occasions.

### A full bug report captured from the device

```
019-08-27 15:31:01.807 789-3756/? E/VDEC: [set_parameter] : [5399] Allocate native buffer failed, invalid port index 1
2019-08-27 15:31:01.807 789-3756/? E/OMXNodeInstance: setParameter(0xead79de0:hisi.decoder.avc, OMX.google.android.index.allocateNativeHandle(0x7f000008): Output:1 en=0) ERROR: BadPortIndex(0x8000101b)
2019-08-27 15:31:01.807 789-3756/? E/OMXNodeInstance: getExtensionIndex(0xead79de0:hisi.decoder.avc, OMX.google.android.index.storeMetaDataInBuffers) ERROR: NotImplemented(0x80001006)
2019-08-27 15:31:01.807 25784-27450/com.production.test E/ACodec: [OMX.hisi.video.decoder.avc] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
2019-08-27 15:31:01.807 789-3756/? E/VDEC: [set_parameter] : [5399] Allocate native buffer failed, invalid port index 1
2019-08-27 15:31:01.807 789-3756/? E/OMXNodeInstance: setParameter(0xead79de0:hisi.decoder.avc, OMX.google.android.index.allocateNativeHandle(0x7f000008): Output:1 en=0) ERROR: BadPortIndex(0x8000101b)
2019-08-27 15:31:01.807 789-3756/? E/OMXNodeInstance: getExtensionIndex(0xead79de0:hisi.decoder.avc, OMX.google.android.index.storeMetaDataInBuffers) ERROR: NotImplemented(0x80001006)
2019-08-27 15:31:01.809 25784-27450/com.production.test E/HwExtendedCodec: mime: video/avc matching compontent failed!
2019-08-27 15:31:01.813 789-3756/? E/OMXNodeInstance: setConfig(0xead79de0:hisi.decoder.avc, ConfigPriority(0x6f800002)) ERROR: BadParameter(0x80001005)
2019-08-27 15:31:01.828 3406-27458/? E/NfcNci:HwCustNfcService: applyRouting -1.1
2019-08-27 15:31:01.904 636-1184/? E/BufferQueueProducer: [SurfaceView - com.production.test/app.application.activities.PlayerVideoActivity$Internal#0] setMaxDequeuedBufferCount: requested buffer count 1 is less than minimum 2
2019-08-27 15:31:01.904 25784-27450/com.production.test E/Surface: IGraphicBufferProducer::setBufferCount(1) returned Invalid argument
2019-08-27 15:31:01.904 25784-27450/com.production.test E/ACodec: native_window_set_buffer_count failed: Invalid argument (22)
2019-08-27 15:31:01.906 25784-27446/com.production.test E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1986)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1103)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:509)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:475)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:973)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:944)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:926)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:363)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-08-27 15:31:01.910 789-789/? E/VDEC: [check_port_param] : [5001] set_parameter: invalid buffer count 15, should not be bigger than max count 14
2019-08-27 15:31:01.910 789-789/? E/OMXNodeInstance: setParameter(0xead79de0:hisi.decoder.avc, ParamPortDefinition(0x2000001)) ERROR: Undefined(0x80001001)
2019-08-27 15:31:01.932 787-1260/? E/IppAlgoSmartAE: [b378326_64E] onUnloadLibrary() mSmartAESoState is unloaded ,so we not Uninit it!
2019-08-27 15:31:01.943 25784-25784/com.production.test E/main#1.VideoPlayerModule.onPlayerError: Unexpected video player error.content://media/external/video/media/37281
    com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalArgumentException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:397)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1986)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1103)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:509)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:475)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:973)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:944)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:926)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:363)
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

### Version of ExoPlayer being used
 2.10.4

### Device(s) and version(s) of Android being used
Android PIE. 
Huawei P20Lite

**Comment by marcbaechinger** [comment]
I think you are probably right that this is a problem of using a codec simultaneously. Does this happen on any device or did you observer this only on the device you stated above?

Can you please create a full bug report so we can look into this?

**Comment by perracodex** [comment]
I've sent a full bug report to dev.exoplayer@gmail.com
I could also see the issue in a Nexus 6 with 7.1, but only once, haven't been able to reproduce it anymore in such device.
In a Huawei P20-Lite with Pie seems to be more common.

Doing some test, if I delay the video playback to start around a couple of seconds after releasing the codec, then the problem doesn't seem to occur anymore. But, I can't confirm at all if placing such delay may be related or just pure chance, since the issue happens rarely and I need to perform several times the video encoding followed by the ExoPlayer playback before the error happens again.

**Comment by marcbaechinger** [comment]
Thanks! Can you check whether the exception is in the bug report you sent? If I search for IllegalArgumentException or native_setSurface I can't find an exception. 

Is this taken on the Huawei device?

Bug Date: 2019-08-28 10:52:05
Device: <unknown>
Build: <unknown>
Build Date:
Uptime: 10:53:04 up 1 day, 20:51, 0 users, load average: 46.79, 46.95, 45.48

**Comment by marcbaechinger** [comment]
Oh, yes it's taken on a Huawei. Seems my tool is broken :)

Build: SNE-LX1 9.1.0.215(C432E4R1P1)
Build fingerprint: 'HUAWEI/SNE-LX1/HWSNE:9/HUAWEISNE-L21/215C432:user/release-keys'

**Comment by perracodex** [comment]
What would be the correct steps to ensure the exception gets included in
the report?
To generate the one l sent what l did is:  1) Encode video 2) release codec 3) ExoPlayer playback. Repeating this cycle till finally got the error again, which besides appearing in the Android Studio logcat, is also reported through the ExoPlayer.onPlayerError callback.
After the error, l used the adb tool to generate the report.

**Comment by marcbaechinger** [comment]
Hmmmm, that sounds about right and should work like this. Here's a doc about different ways, just for reference: https://developer.android.com/studio/debug/bug-report

The log which is included in your report starts only from 08-28 10:51:51.270 and goes to 08-28 10:53:17.392. Dumpstate says that the device is up since a day though: up 0 weeks, 1 day, 20 hours, 50 minutes. Not sure what is happening here.

When I search all the logs I can't find the word 'ExoPlayer'. which I would expect given the stack trace above.  I'd also expect to find 'com.production.test' in the logs somewhere and the list of processes when looking at DUMPSYS - procstats.

**Comment by perracodex** [comment]
Sent a new bug report to dev.exoplayer@gmail.com

**Comment by marcbaechinger** [comment]
Thanks for sending again!

I can't find much more information though. However, it seems to be an issue with the device specific media codec when setting the surface by MediaCodec.setOutputSurface.

You can try the [setOutputSurface workaround ](https://github.com/google/ExoPlayer/blob/85c10b02567b66ecfaaaacfd0ba9389b41bf919e/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java#L1484)which is in place for other Huwaei. You can test this by adding the device token to that list and see whether this helps. 

You can find the device token if you grep you logcat and search for the line which is logged when ExoPlayer starts. This example is from another device (unfortunately I could not find it in you bugreport)

`ExoPlayerImpl: Init eac897f [ExoPlayerLib/2.10.4] [HWCOL, COL-L29, HUAWEI, 27]`

It's the first token in the device specific part (HWCOL in this case).

**Comment by ojw28** [comment]
Note that #6331 is also proposing adding this device to the `setOutputSurface` workaround.

**Comment by perracodex** [comment]
The only concern is that the setOutputSurface workaround seems to be for devices with API < 27, and the Huawei P20 Lite test device were we can see this issue is running API 28. 
On the other hand the issue happens rarely, sometimes not seen for hours even through constant testing to try to reproduce it, so making it more strange due to its lack of consistency.

**Comment by perracodex** [comment]
We are narrowing the cause of the issue. The latest findings:

When we are encoding a video we use a TextureView as a camera preview surface, which is the source of the frames being encoded. 

In our flow, once the encoding ends, we stop the camera preview “**asynchronously**”, and at the same time we open a new Activity for the new encoded video playback.

It seems that if before opening the video playback, we ensure to **synchronously** wait till the camera preview has fully released the allocated surface preview resources, then so far the issue can’t be longer reproduced.

**Comment by marcbaechinger** [comment]
Closing due to  lack of activity. Please reopen if needed.
