### ISSUE TITLE
OutOfMemoryError: Failed to allocate ... until OOM

### ISSUE THREAD

**Issue by haikelei** [google/ExoPlayer#6424]
```
java.lang.OutOfMemoryError: Failed to allocate a 65548 byte allocation with 11488 free bytes and 11KB until OOM
        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
        at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:633)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:553)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:533)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:187)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:898)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
```

lately i am developing an app like tiotok,but when i switch the video fast,about 150 times later,throw this error

**Comment by ojw28** [comment]
Are you forgetting to release previous player instances (by calling `Player.release`)? Please provide all of the information requested in the [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=).
