### ISSUE TITLE
Exoplayer was not playing the video sometimes

### ISSUE THREAD

**Issue by newandroidboy88** [google/ExoPlayer#6435]
### [REQUIRED] Content description
Sometimes Exoplayer was not playing the 4k video

### [REQUIRED] Link to test content
Use any 4K Video by own.
Take any 4K Video to play in the exoplayer along with Webview to be loaded with  HTML content with 4k video in the same screen

### [REQUIRED] Version of ExoPlayer being used
2.9.4

### [REQUIRED] Device(s) and version(s) of Android being used
Android 6 +

### [REQUIRED] A full bug report captured from the device
```
09-16 16:10:32.131 13244 13604 E         : Mali Debug: color_buffer is 0x0
09-16 16:10:32.231 13244 13604 E         : Mali Debug: color_buffer is 0x0
09-16 16:10:33.031 13244 13604 E         : Mali Debug: color_buffer is 0x0
09-16 16:10:33.045 13244 13604 I chatty  : uid=10059(bizcastz.business) Chrome_InProcGp identical 1 line
09-16 16:10:33.060 13244 13604 E         : Mali Debug: color_buffer is 0x0
09-16 16:10:33.078 13244 13244 I STORS   : Image playing remaining seconds=118
09-16 16:10:33.185 13244 13604 E         : Mali Debug: color_buffer is 0x0
09-16 16:10:33.308 13244 13604 I chatty  : uid=10059(bizcastz.business) Chrome_InProcGp identical 5 lines
09-16 16:10:33.322 13244 13604 E         : Mali Debug: color_buffer is 0x0
09-16 16:10:33.413 13244 13553 D         : PlayerBase::PlayerBase()
09-16 16:10:33.414 13244 13553 D         : TrackPlayerBase::TrackPlayerBase()
09-16 16:10:33.414 13244 13553 I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
09-16 16:10:33.423 13244 13553 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 4100 -> 4100
09-16 16:10:33.424 13244 13553 D AudioTrack: Client defaulted notificationFrames to 2050 for frameCount 4100
09-16 16:10:33.464 13244  1429 I OMXClient: Treble IOmx obtained
09-16 16:10:33.498 13244  1428 D SurfaceUtils: connecting to surface 0xbdff4808, reason connectToSurface
09-16 16:10:33.499 13244  1428 I MediaCodec: [OMX.amlogic.avc.decoder.awesome] setting surface generation to 13562014
09-16 16:10:33.499 13244  1428 D SurfaceUtils: disconnecting from surface 0xbdff4808, reason connectToSurface(reconnect)
09-16 16:10:33.499 13244  1428 D SurfaceUtils: connecting to surface 0xbdff4808, reason connectToSurface(reconnect)
09-16 16:10:33.501 13244  1429 E ACodec  : [OMX.amlogic.avc.decoder.awesome] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
09-16 16:10:33.508 13244  1429 I AmAVUtils: AmAVUtils::isAudioExtendFormat input = video/avc
09-16 16:10:33.530 13244  1429 D SurfaceUtils: disconnecting from surface 0xbdff4808, reason setNativeWindowSizeFormatAndUsage
09-16 16:10:33.530 13244  1429 D SurfaceUtils: connecting to surface 0xbdff4808, reason setNativeWindowSizeFormatAndUsage
09-16 16:10:33.530 13244  1429 D SurfaceUtils: set up nativeWindow 0xbdff4808 for 3840x2160, color 0x11, rotation 0, usage 0x402b00
09-16 16:10:33.531 13244  1429 W ACodec  : [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 9 failed: -1010
09-16 16:10:33.531 13244  1429 W ACodec  : [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
09-16 16:10:33.531 13244  1429 W ACodec  : [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
09-16 16:10:33.532 13244  1429 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-16 16:10:33.551 13244  1429 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-16 16:10:33.578 13244  1429 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-16 16:10:33.604 13244  1429 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-16 16:10:33.632 13244  1429 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-16 16:10:33.648 13244  1429 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-16 16:10:33.697 13244  1435 I OMXClient: Treble IOmx obtained
09-16 16:10:33.774 13244  1434 D SurfaceUtils: connecting to surface 0xbdff5008, reason connectToSurface
09-16 16:10:33.774 13244  1434 I MediaCodec: [OMX.amlogic.avc.decoder.awesome] setting surface generation to 13562015
09-16 16:10:33.774 13244  1434 D SurfaceUtils: disconnecting from surface 0xbdff5008, reason connectToSurface(reconnect)
09-16 16:10:33.775 13244  1434 D SurfaceUtils: connecting to surface 0xbdff5008, reason connectToSurface(reconnect)
09-16 16:10:33.776 13244  1435 E ACodec  : [OMX.amlogic.avc.decoder.awesome] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
09-16 16:10:33.778 13244  1435 I AmAVUtils: AmAVUtils::isAudioExtendFormat input = video/avc
09-16 16:10:33.785 13244  1435 D SurfaceUtils: disconnecting from surface 0xbdff5008, reason setNativeWindowSizeFormatAndUsage
09-16 16:10:33.785 13244  1435 D SurfaceUtils: connecting to surface 0xbdff5008, reason setNativeWindowSizeFormatAndUsage
09-16 16:10:33.785 13244  1435 D SurfaceUtils: set up nativeWindow 0xbdff5008 for 3840x2160, color 0x11, rotation 0, usage 0x402b00
09-16 16:10:33.785 13244  1435 W ACodec  : [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 9 failed: -1010
09-16 16:10:33.785 13244  1435 W ACodec  : [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
09-16 16:10:33.786 13244  1435 W ACodec  : [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
09-16 16:10:33.786 13244  1435 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-16 16:10:33.796 13244  1435 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-16 16:10:33.807 13244  1435 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-16 16:10:33.817 13244  1435 E GraphicBufferAllocator: Failed to allocate (3840 x 2160) layerCount 1 format 17 usage 402b00: 5
09-16 16:10:33.817 13244  1435 E BufferQueueProducer: [SurfaceTexture-70-13244-21] dequeueBuffer: createGraphicBuffer failed
09-16 16:10:33.817 13244  1435 E ACodec  : dequeueBuffer failed: Out of memory (12)
09-16 16:10:33.817 13244  1435 E ACodec  : Failed to allocate buffers after transitioning to IDLE state (error 0xfffffff4)
09-16 16:10:33.817 13244  1435 E ACodec  : signalError(omxError 0x80001001, internalError -12)
09-16 16:10:33.817 13244  1434 E MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 5
09-16 16:10:33.818 13244  1434 D SurfaceUtils: disconnecting from surface 0xbdff5008, reason disconnectFromSurface
09-16 16:10:33.820 13244  1435 W AHierarchicalStateMachine: Warning message AMessage(what = 'omxI') = {
09-16 16:10:33.820 13244  1435 W AHierarchicalStateMachine:   int32_t type = 0
09-16 16:10:33.820 13244  1435 W AHierarchicalStateMachine:   int32_t event = 0
09-16 16:10:33.820 13244  1435 W AHierarchicalStateMachine:   int32_t data1 = 0
09-16 16:10:33.820 13244  1435 W AHierarchicalStateMachine:   int32_t data2 = 1
09-16 16:10:33.820 13244  1435 W AHierarchicalStateMachine: } unhandled in root state.
09-16 16:10:33.891 13244  1425 E cr_MediaCodecBridge: Cannot start the media codec
09-16 16:10:33.891 13244  1425 E cr_MediaCodecBridge: android.media.MediaCodec$CodecException: start failed
09-16 16:10:33.891 13244  1425 E cr_MediaCodecBridge: 	at android.media.MediaCodec.native_start(Native Method)
09-16 16:10:33.891 13244  1425 E cr_MediaCodecBridge: 	at android.media.MediaCodec.start(MediaCodec.java:2051)
09-16 16:10:33.891 13244  1425 E cr_MediaCodecBridge: 	at org.chromium.media.MediaCodecBridge.start(MediaCodecBridge.java:31)
09-16 16:10:33.892 13244  1425 W cr_MediaCodecBridge: Releasing: OMX.amlogic.avc.decoder.awesome
09-16 16:10:33.895 13244  1425 W cr_MediaCodecBridge: Codec released
09-16 16:10:33.898 13244  1425 W cr_MediaCodecBridge: Releasing: OMX.amlogic.avc.decoder.awesome
09-16 16:10:34.020 13244 13553 D         : PlayerBase::stop() from IPlayer
09-16 16:10:34.020 13244 13553 D AudioTrack: stop() called with 28676 frames delivered
09-16 16:10:34.022 13244  1428 D SurfaceUtils: disconnecting from surface 0xbdff4808, reason disconnectFromSurface
09-16 16:10:34.027 13244  1425 W cr_MediaCodecBridge: Codec released
```

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md).

**Comment by newandroidboy88** [comment]
What field do you require from the issue.

**Comment by AquilesCanta** [comment]
All of them. 

Mainly important: sample media and bugreport.
