### ISSUE TITLE
ArrayIndexOutOfBoundsException when reading a segment: possible root causes?

### ISSUE THREAD

**Issue by SemihGk** [google/ExoPlayer#6450]
### [REQUIRED] 
My question is about how to investigate an exception which is thrown in Exoplayer and I searched similar exceptions that are reported before. However, I could not find a quite similar one. 

### [REQUIRED] Question
I see some crash reports on production and we are not able to reproduce the issue. Also, the crash rate is quite low. This is the stack trace:

```
Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: src.length=2880 srcPos=2880 dst.length=65536 dstPos=36079 length=8
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:403)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=2880 srcPos=2880 dst.length=65536 dstPos=36079 length=8
	at java.lang.System.arraycopy(Native Method)
	at com.google.android.exoplayer2.util.ParsableByteArray.readBytes(ParsableByteArray.java:191)
	at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:570)
	at com.google.android.exoplayer2.source.chunk.ChunkExtractorWrapper$BindingTrackOutput.sampleData(ChunkExtractorWrapper.java:206)
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor$TrackBundle.outputSampleEncryptionData(FragmentedMp4Extractor.java:1517)
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1211)
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:321)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:135)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)

```

It looks like Exoplayer crashes when it is reading the segment. As my understanding, this seems like a malformed segment. However, I downloaded the segments that caused this exception and I am able to play these (audio) segments without any issue. So, could you give us some insights in order to understand the root causes? Exoplayer version => 2.9.4

### A full bug report captured from the device
We cannot reproduce the issue in our devices. All we have the stack trace that is reported.

### Link to test content
I attached the segment that caused this exception. Also, attached the init segment( and the other ones until the failed one) and merged all segments. Just in case you may need.

[segments.zip](https://github.com/google/ExoPlayer/files/3636557/segments.zip)

**Comment by icbaker** [comment]
I'm unable to repro either with the content provided.

However it seems like the control flow using the sample content doesn't go through the lines in the stack trace. Specifically, `outputSampleEncryptionData()` returns early on the sample content because `encryptionBox == null`. Whereas the stack trace seems to come from this line further down in `outputSampleEncryptionData()`:

```java
output.sampleData(subsampleEncryptionData, subsampleDataLength);
```

So it might be worth you trying reproducing with encrypted content? Without a clear way to reproduce I'm afraid there's not much we can do to help.

Assigning to @AquilesCanta in case it turns out to be DRM related.

**Comment by SemihGk** [comment]
First of all, thank you very much for your time and I really appreciate your comment. 

As for the content, please accept my apologies. I should have elaborated more about the content. At this case, failed segments are clear. Basically, we have an encrypted stream and the stream switches to a clear content when an ad break starts. It looks like this specific exception is only thrown for the clear segments. We do not see any exception for the encrypted ones. Whenever this exception is thrown, the failed segment URL is clear. Again, we are not able to reproduce the issue. This exception is only reported in the production. So, I do not have much information as well. 

It is totally understandable that there is not much info in order to do further investigation on this issue. However, are you able to give us an idea/guess about what it might be causing this exception?

**Comment by ojw28** [comment]
It would be much more helpful to have the original content (presumably this was an HLS or DASH playback originally). Are the init segments for the clear and encrypted parts of the stream different?
