### ISSUE TITLE
HLS Caching with CacheUtil

### ISSUE THREAD

**Issue by bdanddm503** [google/ExoPlayer#6469]
### Searched documentation and issues
I was looking through documentation and issues related to caching and offline support, but there is no proper answers.

### Question
We are using Exoplayer 2.9.4 and HLS video format.
When trying manually cache next video with CacheUtil's _cache_ method, EOFException occurs, but it is working great with mp4. Probably it happens because of caching playlist file instead of video files. The question is if it is possible to use CacheUtil to cache HLS format? If no, what should we use?

### A full bug report captured from the device
```
com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.io.EOFException
     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:362)
     at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(CacheDataSource.java:304)
     at com.google.android.exoplayer2.upstream.TeeDataSource.read(TeeDataSource.java:71)
     at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(CacheDataSource.java:304)
     at com.google.android.exoplayer2.upstream.cache.CacheUtil.readAndDiscard(CacheUtil.java:307)
     at com.google.android.exoplayer2.upstream.cache.CacheUtil.cache(CacheUtil.java:203)
     at com.google.android.exoplayer2.upstream.cache.CacheUtil.cache(CacheUtil.java:124)
     at com.example.hlscachesample.SimpleVideoPreCacher$cache$1.run(SimpleVideoPreCacher.kt:42)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
     at java.lang.Thread.run(Thread.java:760)
 Caused by: java.io.EOFException
     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:700)
     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:360)
   ... 10 more
```
### Link to test content
Here is a test project: https://github.com/Ortyom/ProblemHlsCacheExample/tree/master/app/src/main/java/com/example/hlscachesample

**Comment by tonihei** [comment]
We updated our downloading support in 2.10 and I would strongly encourage you to update if you want to download HLS streams. Please have a look at our [downloading guide](https://exoplayer.dev/downloading-media.html) and specifically at the last section explaining the use of `DownloadHelper` for adaptive streams like HLS.
