### ISSUE TITLE
Cannot play local files with hash character ('#') in filename

### ISSUE THREAD

**Issue by bueeler** [google/ExoPlayer#6470]
When a media source is created with a file containing hash character ('#') in filename, this file cannot be played back by ExoPlayer, as the URI Object will not provide full path in the function "uri.getPath()" used by FileDataSource.

Media source is created as follows:
`MediaSource videoSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse("/storage/emulated/0/Movies/Movie#01.mp4"));`

then exception is thrown as follows:
```
2019-09-25 11:04:51.325 5322-5322/com.anonymous E/EventLogger: internalError [1.04, 0.00, window=0, period=0, loadError]
    com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /storage/emulated/0/Movies/Movie : open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:73)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:257)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:938)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:394)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.FileNotFoundException: /storage/emulated/0/Movies/Movie : open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:485)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:288)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:151)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:65)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:257) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:938) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:394) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:210)
        at libcore.io.IoBridge.open(IoBridge.java:471)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:288) 
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:151) 
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:65) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:257) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:938) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:394) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```
Can this be fixed by ExoPlayer or should I avoid filenames having "# character?

**Comment by icbaker** [comment]
Looks like the '#' is being interpreted as the start of the fragment of the Uri, so when we call getPath [here](https://github.com/google/ExoPlayer/blob/bef130ad17f11ab3997548653f2466e50bd6eb27/library/core/src/main/java/com/google/android/exoplayer2/upstream/FileDataSource.java#L65) we only get everything before the #.

I've reproduced this. I'm not sure exactly the best way to fix it, but I've got some ideas. In the mean-time, I found that [percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding) the '#' worked. So in your case you could do:

```
Uri.parse("/storage/emulated/0/Movies/Movie%2301.mp4")
```

And I think you can automate this with [URLEncoder](https://developer.android.com/reference/java/net/URLEncoder) (not tested):

```
Uri.parse(URLEncoder.encode(
    "/storage/emulated/0/Movies/Movie#01.mp4"), 
    StandardCharsets.UTF_8.name())
```

**Comment by icbaker** [comment]
Actually I think either of these are better (though neither are tested):

```
createMediaSource(
    (new Uri.Builder()).path("/storage/emulated/0/Movies/Movie#01.mp4").build());
```

Or:

```
createMediaSource(Uri.fromFile(new File("/storage/emulated/0/Movies/Movie#01.mp4")));
```

I'll look into:

* Making the error message clearer in this case ("can't use a local-file Uri with a fragment") 
* Documenting more clearly how to open local files more safely using Uri.Builder or File as above

**Comment by bueeler** [comment]
Thanks a lot for having a look at this issue.
Both proposed solutions work for me. So improved error message and/or updated documentation would help others not running into this issue.

**Comment by ojw28** [comment]
@icbaker - WDYT about having `FileDataSource` reconstruct the correct file path from the `Uri` (by looking at the fragment) to handle this case?

I don't think documenting something that's come up once in the project's existence (and is a general Android question rather than anything specific to ExoPlayer) is ideal. If we documented all such questions, our documentation would probably be a mess and it would be hard to find the actual useful bits anyway. Throwing an improved error message seems preferable, but if we can detect the case accurately enough to do that, can we not just transparently "fix" it?
