### ISSUE TITLE
DRM content is not working on few PIXEL devices (Android Q)

### ISSUE THREAD

**Issue by sravan1213** [google/ExoPlayer#6489]
Our app users have reported DRM content is not working on their Pixel devices. Even the sample drm content in demo app is not working for them. Attached stack trace from our logs.

We couldn't debug much from the below logs. Also attaching device build info screenshot for debugging. Please let me know if more details are required. The number of user's complaining about this is increasing day by day. Please help in resolving this.

```
Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(:9)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(:13)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(:12)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(:16)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

![image-20190930-112200](https://user-images.githubusercontent.com/3246494/65880108-e4907d80-e3ae-11e9-89ad-8ac9a99a152a.png)

**Comment by kim-vde** [comment]
Please provide complete information as requested in the issue template (particularly for the test content and the bug report sections). The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

**Comment by sravan1213** [comment]
Thanks for the reply. @kim-vde we are not able to reproduce on the devices we have. I'll try to get a complete log from one of our customers.

**Comment by sravan1213** [comment]
Customer reported content starting working after updating his OS. We couldn't get the logs when this issue happening. Will open If I get logs.
Thanks for the help.
