### ISSUE TITLE
Hls MediaCodec Error in Android 6 API23

### ISSUE THREAD

**Issue by Navidhp** [google/ExoPlayer#6512]
hi , we have this error while running HLS on android api 23 , is this error because of HLS format or exoplayer ? how can we fix it ? 
thanks!
```
10-06 10:44:28.876 4495-4611/co.ayeneh.filmgardi W/OMXNodeInstance: [1:google.h264.decoder] component does not support metadata mode; using fallback
10-06 10:44:28.876 4495-4611/co.ayeneh.filmgardi E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
10-06 10:44:28.876 4495-4611/co.ayeneh.filmgardi D/SoftAVCDec: Number of CPU cores: 2
10-06 10:44:28.876 4495-4611/co.ayeneh.filmgardi E/OMXNodeInstance: setConfig(1:google.h264.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
10-06 10:44:28.876 4495-4611/co.ayeneh.filmgardi I/ACodec: codec does not support config priority (err -2147483648)
10-06 10:44:28.881 4495-4495/co.ayeneh.filmgardi I/System.out: Wo
10-06 10:44:28.882 4495-4614/co.ayeneh.filmgardi I/OMXClient: Using client-side OMX mux.
10-06 10:44:28.888 4495-4614/co.ayeneh.filmgardi E/OMXNodeInstance: setConfig(1:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
10-06 10:44:28.888 4495-4614/co.ayeneh.filmgardi I/ACodec: codec does not support config priority (err -2147483648)
10-06 10:44:28.888 4495-4614/co.ayeneh.filmgardi E/OMXNodeInstance: setConfig(1:google.aac.decoder, ConfigOperatingRate(0x6f800003)) ERROR: Undefined(0x80001001)
10-06 10:44:28.888 4495-4614/co.ayeneh.filmgardi I/ACodec: codec does not support config operating rate (err -2147483648)
10-06 10:44:28.890 4495-4617/co.ayeneh.filmgardi I/SoftAAC2: limiting to stereo output
10-06 10:44:28.922 4495-4617/co.ayeneh.filmgardi I/SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
10-06 10:44:29.105 4495-4611/co.ayeneh.filmgardi E/MemoryHeapBase: mmap(fd=120, size=3649691648) failed (Out of memory)
10-06 10:44:29.105 4495-4611/co.ayeneh.filmgardi W/MemoryDealer: madvise(0xffffffff, 1529950208, MADV_REMOVE) returned Invalid argument
10-06 10:44:29.105 4495-4611/co.ayeneh.filmgardi E/ACodec: Failed to allocate output port buffers after port reconfiguration: (-12)
10-06 10:44:29.105 4495-4611/co.ayeneh.filmgardi E/ACodec: signalError(omxError 0x80001001, internalError -12)
10-06 10:44:29.105 4495-4610/co.ayeneh.filmgardi E/MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 6
10-06 10:44:29.108 4495-4602/co.ayeneh.filmgardi E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1437)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:653)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
10-06 10:44:29.109 4495-4602/co.ayeneh.filmgardi E/ExoPlayerImplInternal: Disable failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:1948)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:702)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.flushOrReleaseCodec(MediaCodecVideoRenderer.java:604)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:580)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:451)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:158)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1088)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:851)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:399)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
10-06 10:44:29.211 4495-4602/co.ayeneh.filmgardi E/ExoPlayerImplInternal: Reset failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:1901)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:609)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:594)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onReset(MediaCodecRenderer.java:587)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onReset(MediaCodecVideoRenderer.java:460)
        at com.google.android.exoplayer2.BaseRenderer.reset(BaseRenderer.java:164)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:860)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:399)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by ojw28** [comment]
Please provide [complete information as requested in the issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=) (please post it here, rather than filing a new issue). Thanks!

**Comment by Navidhp** [comment]
@ojw28 this is my misteak because stream provider generate disposable link and exoplayer could not get next chunk and this error occurs ! thanks
