### ISSUE TITLE
DASH: Support http-head:2014 UTCTiming scheme

### ISSUE THREAD

**Issue by muganda** [google/ExoPlayer#6524]
### [REQUIRED] Searched documentation and issues
I have looked at the previously reported issues on ExoPlayer and on stackoverflow as well.

### [REQUIRED] Question
I am working with live streams from a streaming provider in DASH format. The manifest file includes UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-head:2014".

### A full bug report captured from the device
```
E/DashMediaSource: Failed to resolve UtcTiming element.
    java.io.IOException: Unsupported UTC timing scheme
        at com.google.android.exoplayer2.source.dash.DashMediaSource.resolveUtcTimingElement(DashMediaSource.java:896)
        at com.google.android.exoplayer2.source.dash.DashMediaSource.onManifestLoadCompleted(DashMediaSource.java:801)
        at com.google.android.exoplayer2.source.dash.DashMediaSource$ManifestCallback.onLoadCompleted(DashMediaSource.java:1290)
        at com.google.android.exoplayer2.source.dash.DashMediaSource$ManifestCallback.onLoadCompleted(DashMediaSource.java:1285)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:450)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by ojw28** [comment]
We don't currently support this type of `UTCTiming` element (why there needs to be 4 different ways of doing this is really beyond me!).

In order for us to test any support we do add for it, could you please provide a test stream as requested in the issue template? Thanks!

**Comment by muganda** [comment]
In the end I asked my streaming service provider to change something about the format. All is well now.

**Comment by ojw28** [comment]
Thanks for the update! I will mark this a low priority enhancement. In practice this means we'll probably ignore it until at least the point when someone else asks for it and is able to provide test content.

**Comment by ppodgorski** [comment]
@ojw28 We would be grateful if you could add support for `urn:mpeg:dash:utc:http-head:2014`.
We have prepared a test content: http://r.dcs.redcdn.pl/livedash/o2/atendesoftware/live/live.livx/live.mpd?indexMode&dummyfile

**Comment by 07steven01** [comment]
Hi @tonihei, I'd appreciate an update on the current status of this issue

**Comment by tonihei** [comment]
No update I'm afraid. Feel free to look into DashMediaSource to see how other timing schemes are handled and maybe you can provide a pull request to add support for this scheme if it's more urgent?
