### ISSUE TITLE
HLS with huge mediaSequence doesn't work.

### ISSUE THREAD

**Issue by bsysop** [google/ExoPlayer#653]
I doing several tests in HLS, and don't know why, when i tried to open a m3u8 online content, this do this fail! I just save this for put here and then restart my ffmpeg command who generate m3u8 and then play perfect. (I try this m3u8 with VLC and playback perfect)

```
07-24 01:45:48.054: E/LoadTask(10905): Unexpected exception loading stream
07-24 01:45:48.054: E/LoadTask(10905): java.lang.NumberFormatException: Invalid int: "2858726044"
07-24 01:45:48.054: E/LoadTask(10905): 	at java.lang.Integer.invalidInt(Integer.java:137)
07-24 01:45:48.054: E/LoadTask(10905): 	at java.lang.Integer.parse(Integer.java:377)
07-24 01:45:48.054: E/LoadTask(10905): 	at java.lang.Integer.parseInt(Integer.java:365)
07-24 01:45:48.054: E/LoadTask(10905): 	at java.lang.Integer.parseInt(Integer.java:331)
07-24 01:45:48.054: E/LoadTask(10905): 	at com.google.android.exoplayer.hls.HlsParserUtil.parseIntAttr(HlsParserUtil.java:44)
07-24 01:45:48.054: E/LoadTask(10905): 	at com.google.android.exoplayer.hls.HlsPlaylistParser.parseMediaPlaylist(HlsPlaylistParser.java:225)
07-24 01:45:48.054: E/LoadTask(10905): 	at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:127)
07-24 01:45:48.054: E/LoadTask(10905): 	at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:1)
07-24 01:45:48.054: E/LoadTask(10905): 	at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93)
07-24 01:45:48.054: E/LoadTask(10905): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
07-24 01:45:48.054: E/LoadTask(10905): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
07-24 01:45:48.054: E/LoadTask(10905): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-24 01:45:48.054: E/LoadTask(10905): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-24 01:45:48.054: E/LoadTask(10905): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-24 01:45:48.054: E/LoadTask(10905): 	at java.lang.Thread.run(Thread.java:841)
07-24 01:45:48.054: E/DemoPlayer(10905): onRenderersError: Unexpected NumberFormatException: Invalid int: "2858726044"
07-24 01:45:48.054: E/EventLogger(10905): internalError [6.20, rendererInitError]
07-24 01:45:48.054: E/EventLogger(10905): com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected NumberFormatException: Invalid int: "2858726044"
07-24 01:45:48.054: E/EventLogger(10905): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
07-24 01:45:48.054: E/EventLogger(10905): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
07-24 01:45:48.054: E/EventLogger(10905): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-24 01:45:48.054: E/EventLogger(10905): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-24 01:45:48.054: E/EventLogger(10905): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-24 01:45:48.054: E/EventLogger(10905): 	at java.lang.Thread.run(Thread.java:841)
07-24 01:45:48.054: E/EventLogger(10905): Caused by: java.lang.NumberFormatException: Invalid int: "2858726044"
07-24 01:45:48.054: E/EventLogger(10905): 	at java.lang.Integer.invalidInt(Integer.java:137)
07-24 01:45:48.054: E/EventLogger(10905): 	at java.lang.Integer.parse(Integer.java:377)
07-24 01:45:48.054: E/EventLogger(10905): 	at java.lang.Integer.parseInt(Integer.java:365)
07-24 01:45:48.054: E/EventLogger(10905): 	at java.lang.Integer.parseInt(Integer.java:331)
07-24 01:45:48.054: E/EventLogger(10905): 	at com.google.android.exoplayer.hls.HlsParserUtil.parseIntAttr(HlsParserUtil.java:44)
07-24 01:45:48.054: E/EventLogger(10905): 	at com.google.android.exoplayer.hls.HlsPlaylistParser.parseMediaPlaylist(HlsPlaylistParser.java:225)
07-24 01:45:48.054: E/EventLogger(10905): 	at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:127)
07-24 01:45:48.054: E/EventLogger(10905): 	at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:1)
07-24 01:45:48.054: E/EventLogger(10905): 	at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93)
07-24 01:45:48.054: E/EventLogger(10905): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
07-24 01:45:48.054: E/EventLogger(10905): 	... 5 more
07-24 01:45:48.064: E/EventLogger(10905): playerFailed [6.20]
07-24 01:45:48.064: E/EventLogger(10905): com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected NumberFormatException: Invalid int: "2858726044"
07-24 01:45:48.064: E/EventLogger(10905): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
07-24 01:45:48.064: E/EventLogger(10905): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
07-24 01:45:48.064: E/EventLogger(10905): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-24 01:45:48.064: E/EventLogger(10905): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-24 01:45:48.064: E/EventLogger(10905): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-24 01:45:48.064: E/EventLogger(10905): 	at java.lang.Thread.run(Thread.java:841)
07-24 01:45:48.064: E/EventLogger(10905): Caused by: java.lang.NumberFormatException: Invalid int: "2858726044"
07-24 01:45:48.064: E/EventLogger(10905): 	at java.lang.Integer.invalidInt(Integer.java:137)
07-24 01:45:48.064: E/EventLogger(10905): 	at java.lang.Integer.parse(Integer.java:377)
07-24 01:45:48.064: E/EventLogger(10905): 	at java.lang.Integer.parseInt(Integer.java:365)
07-24 01:45:48.064: E/EventLogger(10905): 	at java.lang.Integer.parseInt(Integer.java:331)
07-24 01:45:48.064: E/EventLogger(10905): 	at com.google.android.exoplayer.hls.HlsParserUtil.parseIntAttr(HlsParserUtil.java:44)
07-24 01:45:48.064: E/EventLogger(10905): 	at com.google.android.exoplayer.hls.HlsPlaylistParser.parseMediaPlaylist(HlsPlaylistParser.java:225)
07-24 01:45:48.064: E/EventLogger(10905): 	at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:127)
07-24 01:45:48.064: E/EventLogger(10905): 	at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:1)
07-24 01:45:48.064: E/EventLogger(10905): 	at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93)
07-24 01:45:48.064: E/EventLogger(10905): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
07-24 01:45:48.064: E/EventLogger(10905): 	... 5 more
07-24 01:45:48.064: E/PlayerActivity(10905): playbackState: idle
```

The m3u8 manifest.
![captura de tela 2015-07-24 as 01 46 38](https://cloud.githubusercontent.com/assets/9998303/8867878/05913dc2-31a6-11e5-833e-1ac78ce0db4a.png)

**Comment by Arqu** [comment]
Your media sequence number is way too high - that is you exceeded the max value of a 32 bit signed integer. The max media sequence number shouldn't be higher than 2147483647. VLC probably passes because they use a 64 bit integer.

**Comment by bsysop** [comment]
I see, i think this should have a fix.

**Comment by ojw28** [comment]
I agree the content should use a more sensible value for the media sequence number. I can't think of a legitimate reason they need to use numbers that big. The normal 2^31 range is sufficient for 228 years with your segment duration.

**Comment by ojw28** [comment]
Note - We would fix this if it were trivial, but it requires changing DASH/SmoothStreaming code to use longs too due to the pieces of code that they share, and I think we'd then end up having to hackily convert longs back to integers in a bunch of places. Hence marking wontfix for now.

**Comment by bsysop** [comment]
You right, if sequence begins from 0 (0,1,2,3....) its not a problem, but when we think the server got a CDN implementation (Many .ts files is cached in CDN), always need change the file name of the new execution of HLS (Sometimes LiveStreaming go down and when restarts need different .TS filename). For that on ffmpeg we do it like this:

> -start_number $(date +"%d%m%y")$(( ( RANDOM % 100 )

It will give us a sequence like that:
> 020715991
> 020715992
> 020715993

Its looking good for ExoPlayer, perhaps if put just a $(( ( RANDOM % 100000000 ) sometimes got this Player fails.

I understand my solution are medieval, but helps with CDN implementation!

**Comment by ojw28** [comment]
You definitely shouldn't do that. It doesn't guarantee unique values when the server restarts anyway (if you use %100, then it's almost certain to not do this).

I'm not sure what ffmpeg ends up doing with the start_number, but the fact the numbers in the filenames are either negative or decreasing suggests to me that ffmpeg doesn't particularly like it either. You'll have to figure this out mostly by yourself, but a few random thoughts:

- The -i option for ffmpeg looks useful. You could have start_number increment from 0 each time and use -i to bake something unique into the fixed part of the file-name for each run.
- You shouldn't need to use random numbers. Just take the current time since epoch in milliseconds, or something like that, and bake it into the file-names.

**Comment by bsysop** [comment]
You right, that i doing with 
> $(date +"%d%m%y")
Before $RANDOM, this give me Day/Month/Year, and later 100 random int!

It solve my problem actually DayMonthYearRandom!

Thank you very much!.
