### ISSUE TITLE
Error: ExoPlaybackException OutOfMemoryError when play .mkv local file.

### ISSUE THREAD

**Issue by BuiVanNam** [google/ExoPlayer#6580]
- ExoPlayer version: 2.10.6
- OS: android 9.0

Hi Dev team, I play file mkv from local (size 3840*2160 - 30s - 679MB), when play to 10s -> OutOfMemoryError

```
Log: 019-10-25 16:11:57.109 9875-10049/net.vsmart.vphotos E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 65552 byte allocation with 58232 free bytes and 56KB until OOM, max allowed footprint 268435456, growth limit 268435456
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:424)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 58232 free bytes and 56KB until OOM, max allowed footprint 268435456, growth limit 268435456
        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
        at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:641)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:561)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.readToOutput(MatroskaExtractor.java:1461)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.writeSampleData(MatroskaExtractor.java:1363)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.binaryElement(MatroskaExtractor.java:1161)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$InnerEbmlProcessor.binaryElement(MatroskaExtractor.java:1628)
        at com.google.android.exoplayer2.extractor.mkv.DefaultEbmlReader.read(DefaultEbmlReader.java:138)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.read(MatroskaExtractor.java:440)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:965)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:394)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
```

Please help me re-check and resolve this issue. Thanks so much!

**Comment by tonihei** [comment]
> 30s - 679MB

That's 181 Mbps :)

ExoPlayer buffers up to a certain minimum buffer length by default irrespective of the memory usage. If you want ExoPlayer to stop buffering at the target memory usage, you can try to set `DefaultLoadControl.Builder.setPrioritizeTimeOverSizeThresholds(false)`.

**Comment by BuiVanNam** [comment]
Thanks so much!
