### ISSUE TITLE
player local video failed!

### ISSUE THREAD

**Issue by luning-l** [google/ExoPlayer#6590]
hi , we have this error while running local video  on android api 17,but on another android api 17 no problem. how can we fix it ?
thanks!

MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -2147483648)
01-01 02:11:31.868 1494-1632/com.hdl.m3u8demo E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.queueInputBuffer(Native Method)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:773)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:583)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:138)
        at android.os.HandlerThread.run(HandlerThread.java:60)
[video.txt](https://github.com/google/ExoPlayer/files/3777989/video.txt)

**Comment by tonihei** [comment]
Please provide the full list of requested information when submitting bug reports.

From what you posted, it looks like a problem with the MediaCodec implementation on this device. Does it happen on a specific device only, or also on other devices running API 17?
