### ISSUE TITLE
After 3 Buffers exoplayer stopping to retry?

### ISSUE THREAD

**Issue by chavabobby** [google/ExoPlayer#6615]
When my exoplayer gets 3 buffers it's not retrying instead stopping the player, I need to re-launch the activity again. Please help to fix this

**Comment by andrewlewis** [comment]
There isn't enough information here for us to help. Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by chavabobby** [comment]
When the connection is low, it starts buffering and plays when gets connected, after three consecutive buffers it's throwing the below error and stopping with the play button on the screen and the source is up all the time, issue is when network is low it starts buffering and it's not continuously trying or buffering. Please tell me a solution.

`E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.BehindLiveWindowException
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:292)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:609)
        at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:78)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading(HlsMediaPeriod.java:349)
        at com.google.android.exoplayer2.MediaPeriodHolder.continueLoading(MediaPeriodHolder.java:201)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1699)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1671)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:354)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
D/SurfaceUtils: disconnecting from surface 0xbfc54808, reason disconnectFromSurface`

**Comment by andrewlewis** [comment]
Please see this [blog post about load error handling](https://medium.com/google-exoplayer/load-error-handling-in-exoplayer-488ab6908137). It sounds like you want to use a custom load error handling policy where you keep retrying indefinitely (the current default behavior propagates a player error after retrying three times).
