### ISSUE TITLE
How to force retry load chunk when server response is 415?

### ISSUE THREAD

**Issue by luna-vulpo** [google/ExoPlayer#6659]
From time to time I get 415 error on live stream. Like below. I want to retry load chunk till end of buffer or even delay playback.
How to achieve that? 

```
ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 415
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:311)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:257)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:118)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:394)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by marcbaechinger** [comment]
Can you check whether [LoadErrorHandlingPolicy](https://github.com/google/ExoPlayer/blob/bef130ad17f11ab3997548653f2466e50bd6eb27/library/core/src/main/java/com/google/android/exoplayer2/upstream/LoadErrorHandlingPolicy.java) or it's default implementation [DefaultLoadErrorHandlingPolicy](https://github.com/google/ExoPlayer/blob/44293e8f45fc62ff918001b4425c44d0ded5ffc9/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultLoadErrorHandlingPolicy.java) works for you?

I'm not sure, but does it stop playback without playing out the buffer? I think that should be already the case. Do you see another behaviour?

**Comment by ojw28** [comment]
I agree with @marcbaechinger - It looks like the behavior you're asking for is already what ExoPlayer does. If the playback actually fails then it's because the minimum number of retries (3 by default) have been attempted, and the buffer has been exhausted.

**Comment by luna-vulpo** [comment]
thanks, it helps a lot.
