### ISSUE TITLE
How to play second video of my own file?

### ISSUE THREAD

**Issue by imbichitra** [google/ExoPlayer#6723]
Hi all ,
I have a file xxx.ulx which contain 2 mp4 video and when i play the video using `new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(uri);` it alway play the first video not the second video , so how to play the second video direct form xxx.ulx file.

**Comment by kim-vde** [comment]
If possible, you should split the ulx file into 2 mp4 files and use a `ConcateningMediaSource` to play those files one after the other.

If not, an alternative would be to get the index where the second mp4 is starting and use a resolving datasource as in #6720.

**Comment by imbichitra** [comment]
Hi developer,
i currently using first method which work fine form me but i want to implement the alternative  method and i implement as it is given in the link but it not working it shows following error **UnrecognizedInputFormatException: None of the available extractors**
i override method and give offset as 1.
```
@Override
    public DataSpec resolveDataSpec(DataSpec dataSpec) throws IOException {
      long offset = 1;
      return new DataSpec(
          dataSpec.uri,
          dataSpec.httpMethod,
          dataSpec.httpBody,
          dataSpec.absoluteStreamPosition + offset,
          dataSpec.position + offset,
          dataSpec.length,
          dataSpec.key,
          dataSpec.flags);
    }
```
in my video file if i use **ffprobe -i xxx.ulx-v quiet -print_format json -show_format -show_streams -hide_banner** this command gives following information as below.
```
{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "Main",
            "codec_type": "video",
            "width": 1920,
            "height": 1080,
            "coded_width": 1920,
            "coded_height": 1088,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "30/1",
            "avg_frame_rate": "30/1",
            "time_base": "1/15360",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 235008,
            "duration": "15.300000",
            "bit_rate": "18312080",
            "bits_per_raw_sample": "8",
            "nb_frames": "459",
        },
        {
            "index": 1,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "Main",
            "codec_type": "video",
            "codec_time_base": "1/60",
            "codec_tag_string": "avc1",
            "width": 1920,
            "height": 1080,
            "coded_width": 1920,
            "coded_height": 1088,
            "has_b_frames": 2,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "30/1",
            "avg_frame_rate": "30/1",
            "time_base": "1/15360",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 235008,
            "duration": "15.300000",
            "bit_rate": "4019583",
            "bits_per_raw_sample": "8",
            "nb_frames": "459",
        }
    ],
    "format": {
        "filename": "1DigitalSignage_Ultra-D_Logo-1.ultrax",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
        "format_long_name": "QuickTime / MOV",
        "start_time": "0.000000",
        "duration": "15.300000",
        "size": "42725495",
        "bit_rate": "22340128",
        "probe_score": 100,
        "tags": {
            "major_brand": "isom",
            "minor_version": "512",
            "compatible_brands": "isomiso2avc1mp41",
            "encoder": "Lavf58.35.100"
        }
    }
}
```
as it contains 2 video it gives two object inside streams, index = 0 is a one video and index = 1 is another video so in my override method i gave **offset = 1** but it not work and give error as  **UnrecognizedInputFormatException: None of the available extractors** but if use **offset =0** then first video play. please correct me if i am wrong.

**Comment by kim-vde** [comment]
The index returned by the `ffprobe` command has a different meaning than the offset in the resolving data source.
- In the result returned by `ffprobe`, the index indicates the index of a stream in the array containing all the streams. Those indexes will therefore always be consecutive numbers.
- In the resolving media source, the offset indicates the byte offset in the file at which the media starts. Setting this offset to 1 would indicate that the first mp4 file contains only 1 byte, which is not correct.

**Comment by imbichitra** [comment]
But when i set offset= 0 it play the first video , please correct me what to pass as an offset so that it play the second video.

**Comment by imbichitra** [comment]
How to play the second video?

**Comment by kim-vde** [comment]
You need to pass the **byte offset** of the second mp4 inside your file.

**Comment by imbichitra** [comment]
How to get the byte offset, as ffmpeg is not give any byte offset please help me to solve this problem.

**Comment by kim-vde** [comment]
Is it acceptable to hard-code the byte offset? If yes, you can obtain this value by
- retrieving the number of bytes in the first mp4 file obtained by splitting the ulx files into 2 mp4 files (option 1 of [this](https://github.com/google/ExoPlayer/issues/6723#issuecomment-561671619) comment), or by
- adding a break point on the line where the `mp4Extractor` returns `RESULT_END_OF_INPUT`, play the first content and get `input.position()` when hitting the break point.

**Comment by imbichitra** [comment]
Still i am unable to play the second video, i got 3 scenario which describe below.

> scenario-1
I extract the video from ulx and right click on the first video and go to property and get the no of byte as 927889 and i set  **long offset =927889**  but it not work.

>  scenario-2
I simple play the first video and set a break point in **mp4Extracter** and get the position as  7777993 by using **input.position()** but when i set **long offset =7777993 ** this also not work.

>  scenario-3
I simple play the ulx video which contain 2 video by passing **long offset =0**  which play the first video and set a break point in **mp4Extracter** and get the position as  10181090 by using **input.position()** but when i set **long offset =10181090 ** this also not work.
In all the 3 case i got following error
```
UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, 
FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, 
FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor)
 could read the stream. 
```

**Comment by kim-vde** [comment]
This probably means that the offset is wrong.
Can you send the ulx file, together with the 2 files obtained using option 1 of [this](https://github.com/google/ExoPlayer/issues/6723#issuecomment-561671619)  comment, following [these](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md#link-to-test-content) instructions?

**Comment by imbichitra** [comment]
Hi i send an e-mail to dev.exoplayer@gmail.com regarding ulx video file

**Comment by kim-vde** [comment]
I don't have sufficient permissions to access the file you sent. Can you send the file instead of a link to Google Drive?

**Comment by imbichitra** [comment]
this file is almost 42MB i can't attach and send over gmail,the only thing i send drive link.
i again send a drive link with editable permission.

**Comment by kim-vde** [comment]
I had a look at the file. The first mp4 file is valid and ends at offset 44 822 039. This offset corresponds indeed to the start of an mp4 moov box but, if I remove the first 44 822 039 bytes of the file, the resulting mp4 file is invalid.
You said that you managed to split the file in 2 and have 2 valid mp4 files. Can you explain how you did that and send the resulting files?

**Comment by ojw28** [comment]
To clarify, the `.ulx` file doesn't contain two pieces of media concatenated one after the other. It's one piece of media with two video tracks that exist alongside one another. The way ExoPlayer plays the file is identical to what VLC does. If you play the video in the ExoPlayer demo app, you'll see that you're able to select the other video track using "Select Tracks". You should be able to take a look at the demo app source code to figure out how to select the track in your own app.

> but i want to implement the alternative method

Why? The way you're doing it currently is much simpler and already works.

Since you have a working solution, and since you can take a look at the demo app to figure out how to select the alternative video track, I think you already have everything that you need here.

**Comment by imbichitra** [comment]
But my requirement is to play both the video side by side at same time so i have to give index position so that it play both the video.

**Comment by imbichitra** [comment]
As per your opinion the .ulx file contain one piece of media with two video track that exist alongside one another ,but is there any way i can merge both the video so it can contain two piece of media.

**Comment by imbichitra** [comment]
But my question is how to play the second video by passing an offset that mentioned in https://github.com/google/ExoPlayer/issues/6723#issuecomment-562918603 and is there any way to merge two video with two media in one file.

**Comment by ojw28** [comment]
Let's use https://github.com/google/ExoPlayer/issues/6800 to track this, since this issue doesn't provide a good description of what your actual question is.

**Comment by imbichitra** [comment]
Hi i follow the setup to play 2 track simultaneously which is mention in [#6589](https://github.com/google/ExoPlayer/issues/6589#issuecomment-549864783) and below is my custom `TrackSelector `  and `RenderersFactory ` for select video track

```
private void initPlayer() {
    RenderersFactory renderersFactory = new DefaultRenderersFactory(this){
      @Override
      protected void buildVideoRenderers(Context context, int extensionRendererMode,
          MediaCodecSelector mediaCodecSelector,
          @Nullable DrmSessionManager<FrameworkMediaCrypto> drmSessionManager,
          boolean playClearSamplesWithoutKeys, boolean enableDecoderFallback, Handler eventHandler,
          VideoRendererEventListener eventListener, long allowedVideoJoiningTimeMs,
          ArrayList<Renderer> out) {

        super.buildVideoRenderers(context, extensionRendererMode, mediaCodecSelector,
            drmSessionManager, playClearSamplesWithoutKeys, enableDecoderFallback, eventHandler,
            eventListener, allowedVideoJoiningTimeMs, out);
        out.add(new VideoRendererWithoutClock(context,mediaCodecSelector));
        out.add(new VideoRendererWithoutClock(context,mediaCodecSelector));
   
      }
    };

    TrackSelector trackSelector = new TrackSelector() {
      @Override
      public TrackSelectorResult selectTracks(RendererCapabilities[] rendererCapabilities,
          TrackGroupArray trackGroups, MediaSource.MediaPeriodId periodId, Timeline timeline)
          throws ExoPlaybackException {
        Queue<Integer> videoRenderers = new ArrayDeque<>();
        RendererConfiguration[] configs = new RendererConfiguration[rendererCapabilities.length];
        TrackSelection[] selections = new TrackSelection[rendererCapabilities.length];
        for (int i = 0; i < rendererCapabilities.length; i++) {
          if(rendererCapabilities[i].getTrackType() == C.TRACK_TYPE_VIDEO) {
            videoRenderers.add(i);
            configs[i] = RendererConfiguration.DEFAULT;
          }
        }

        for (int i = 0; i < trackGroups.length; i++) {
          if (MimeTypes.isVideo(trackGroups.get(i).getFormat(0).sampleMimeType)) {
            Integer index = videoRenderers.poll();
            Log.d(TAG, "selectTracks: "+index);
            if (index != null) {
              selections[index] = new FixedTrackSelection(trackGroups.get(i), 0);
            }
          }
        }
        return new TrackSelectorResult(configs, selections, new Object());
      }

      @Override
      public void onSelectionActivated(Object info) {

      }
    };
    String Original = Environment.getExternalStorageDirectory() + File.separator + "Video" + File.separator+"1vid.mp4";
    String Original1 = Environment.getExternalStorageDirectory() + File.separator + "Video" + File.separator+"video1.mp4";

    MediaSource contentMediaSource = buildMediaSource(Uri.parse(Original));
    MediaSource contentMediaSource1 = buildMediaSource(Uri.parse(Original1));
    MergingMediaSource mergingMediaSource = new MergingMediaSource(contentMediaSource,contentMediaSource1);
    player = ExoPlayerFactory.newSimpleInstance(this,renderersFactory,trackSelector);
    playerView.setPlayer(player);
    player.prepare(mergingMediaSource);
  }
```
and here is my `VideoRendererWithoutClock` whichi extends `VideoRendererWithoutClock`
```
public class VideoRendererWithoutClock extends MediaCodecVideoRenderer {

  public VideoRendererWithoutClock(Context context,
      MediaCodecSelector mediaCodecSelector) {
    super(context, mediaCodecSelector);
  }

  @Override
  public MediaClock getMediaClock() {
    return super.getMediaClock();
  }
}
```
if i use above code then following error is coming out 
```
Failed to initialize decoder: OMX.qcom.video.decoder.avc
    java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1884)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:571)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:847)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:779)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:510)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1186)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:636)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:733)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:644)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:163)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2020-01-06 10:59:46.535 18307-18330/com.google.android.exoplayer2.imademo E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 29.977732], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:512)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1186)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:636)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:733)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:644)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:163)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 29.977732], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:786)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:510)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1186) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:636) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:733) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:644) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1884)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:571)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:847)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:779)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:510) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1186) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:636) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:733) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:644) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 

```
`Please help me to play 2 track Synchronously at time`

**Comment by imbichitra** [comment]
if i remove `out.add(new VideoRendererWithoutClock(context,mediaCodecSelector));`  from my `RenderersFactory ` which override `buildVideoRenderers` of `DefaultRenderersFactory` then it only play the track one.

**Comment by imbichitra** [comment]
Actually i want to implement below scenario  
![IMG_20200106_130245](https://user-images.githubusercontent.com/23660842/71803114-e0e35580-3085-11ea-8aac-d77efb1b6a1b.jpg)

In the above image 2 video is playing one is left and another is right here i play two separate video using two instance of exoplayer  but how can i play 2 tack just like image one is on left and another is on right with synchronization.

**Comment by kim-vde** [comment]
Are you able to play the second track only as in #6800?
Are you able to play two separate medias at the same time as in #6589?

You should try to solve these simpler problems separately before merging them.

**Comment by imbichitra** [comment]
> Are you able to play the second track only as in #6800?

Yes i play the second track directly by changing the track as below
```
private void changeTrack(){
        MappingTrackSelector.MappedTrackInfo mappedTrackInfo;
        List<DefaultTrackSelector.SelectionOverride> overrides;
        mappedTrackInfo = Assertions.checkNotNull(trackSelector.getCurrentMappedTrackInfo());
        //this.rendererIndex = rendererIndex;
        int rendererIndex = 0;
        TrackGroupArray rendererTrackGroups = mappedTrackInfo.getTrackGroups(rendererIndex);
        DefaultTrackSelector.Parameters selectionParameters = trackSelector.getParameters();

        DefaultTrackSelector.SelectionOverride override =
                selectionParameters.getSelectionOverride(rendererIndex, rendererTrackGroups);
        overrides = override == null ? Collections.emptyList() : Collections.singletonList(override);

        overrides1 = new SparseArray<>();
        int maxOverrides = true ? overrides.size() : Math.min(overrides.size(), 1);
        //Log.d(TAG, "init: maxOverrides "+rendererIndex);
        for (int i = 0; i < maxOverrides; i++) {
            DefaultTrackSelector.SelectionOverride override12 = overrides.get(i);
            overrides1.put(override12.groupIndex, override12);
        }
        int groupIndex = 1;
        int trackIndex = 0;

        DefaultTrackSelector.SelectionOverride override1 = overrides1.get(groupIndex);

        Assertions.checkNotNull(mappedTrackInfo);

        if (override1 == null) {
            //Log.d(TAG, "onTrackViewClicked f: ");
            if (overrides1.size() > 0) {
                // Removed other overrides if we don't allow multiple overrides.
                overrides1.clear();
            }
            overrides1.put(groupIndex, new DefaultTrackSelector.SelectionOverride(groupIndex, trackIndex));
        }
        trackSelector.setParameters(
                TrackSelectionUtil.updateParametersWithOverride(
                        selectionParameters,
                        rendererIndex,
                        rendererTrackGroups,
                        false,
                        getOverrides().get(0)
                ));
    }
```

> Are you able to play two separate medias at the same time as in #6589?

Yes i am able to play two separate medias at the same time but using two instance of exoplayer whi is not synchronized.
but when i want to play two video as mentioned in [#6723](https://github.com/google/ExoPlayer/issues/6723#issuecomment-571010107)  then `Failed to initialize decoder: OMX.qcom.video.decoder.avc` error is occur.

**Comment by kim-vde** [comment]
I did the exercise and managed to play 2 synchronized videos using the following code.

```
  private void initializePlayer() {
    List<Renderer> renderers = new ArrayList<>();
    RenderersFactory renderersFactory = new MyRendererFactory(/* context= */ this, renderers);

    TrackSelector trackSelector = new MyTrackSelector();

    player =
        new SimpleExoPlayer.Builder(/* context= */ this, renderersFactory)
            .setTrackSelector(trackSelector)
            .build();
    player.setPlayWhenReady(true);

    SurfaceView surfaceView1 = findViewById(R.id.surface_view_1);
    surfaceView1.getHolder().addCallback(new MySurfaceHolderCallback(player, renderers.get(0)));
    SurfaceView surfaceView2 = findViewById(R.id.surface_view_2);
    surfaceView2.getHolder().addCallback(new MySurfaceHolderCallback(player, renderers.get(1)));

    MediaSource videoSource1 =
        new ProgressiveMediaSource.Factory(dataSourceFactory)
            .createMediaSource(Uri.parse("https://html5demos.com/assets/dizzy.mp4"));
    MediaSource videoSource2 =
        new ProgressiveMediaSource.Factory(dataSourceFactory)
            .createMediaSource(
                Uri.parse(
                    "https://storage.googleapis.com/exoplayer-test-media-1/gen-3/screens/dash-vod-single-segment/video-avc-baseline-480.mp4"));
    MediaSource mergingSource = new MergingMediaSource(videoSource1, videoSource2);
    player.setMediaSource(mergingSource);

    player.prepare();
  }

  private static final class MyRendererFactory extends DefaultRenderersFactory {

    private final List<Renderer> renderers;

    public MyRendererFactory(Context context, List<Renderer> renderers) {
      super(context);
      this.renderers = renderers;
    }

    @Override
    protected void buildVideoRenderers(
        Context context,
        int extensionRendererMode,
        MediaCodecSelector mediaCodecSelector,
        @Nullable DrmSessionManager<FrameworkMediaCrypto> drmSessionManager,
        boolean playClearSamplesWithoutKeys,
        boolean enableDecoderFallback,
        Handler eventHandler,
        VideoRendererEventListener eventListener,
        long allowedVideoJoiningTimeMs,
        ArrayList<Renderer> out) {
      addVideoRenderer(
          context,
          mediaCodecSelector,
          drmSessionManager,
          playClearSamplesWithoutKeys,
          enableDecoderFallback,
          eventHandler,
          eventListener,
          allowedVideoJoiningTimeMs,
          out);
      addVideoRenderer(
          context,
          mediaCodecSelector,
          drmSessionManager,
          playClearSamplesWithoutKeys,
          enableDecoderFallback,
          eventHandler,
          eventListener,
          allowedVideoJoiningTimeMs,
          out);
    }

    private void addVideoRenderer(
        Context context,
        MediaCodecSelector mediaCodecSelector,
        @Nullable DrmSessionManager<FrameworkMediaCrypto> drmSessionManager,
        boolean playClearSamplesWithoutKeys,
        boolean enableDecoderFallback,
        Handler eventHandler,
        VideoRendererEventListener eventListener,
        long allowedVideoJoiningTimeMs,
        ArrayList<Renderer> out) {
      MediaCodecVideoRenderer videoRenderer =
          new MediaCodecVideoRenderer(
              context,
              mediaCodecSelector,
              allowedVideoJoiningTimeMs,
              drmSessionManager,
              playClearSamplesWithoutKeys,
              enableDecoderFallback,
              eventHandler,
              eventListener,
              MAX_DROPPED_VIDEO_FRAME_COUNT_TO_NOTIFY);
      out.add(videoRenderer);
      renderers.add(videoRenderer);
    }
  }

  private static final class MyTrackSelector extends TrackSelector {
    @Override
    public TrackSelectorResult selectTracks(
        RendererCapabilities[] rendererCapabilities,
        TrackGroupArray trackGroups,
        MediaPeriodId periodId,
        Timeline timeline) {
      Queue<Integer> videoRenderers = new ArrayDeque<>();
      RendererConfiguration[] configs = new RendererConfiguration[rendererCapabilities.length];
      TrackSelection[] selections = new TrackSelection[rendererCapabilities.length];
      for (int i = 0; i < rendererCapabilities.length; i++) {
        if (rendererCapabilities[i].getTrackType() == C.TRACK_TYPE_VIDEO) {
          videoRenderers.add(i);
          configs[i] = RendererConfiguration.DEFAULT;
        }
      }
      for (int i = 0; i < trackGroups.length; i++) {
        if (MimeTypes.isVideo(trackGroups.get(i).getFormat(0).sampleMimeType)) {
          Integer index = videoRenderers.poll();
          if (index != null) {
            selections[index] = new FixedTrackSelection(trackGroups.get(i), 0);
          }
        }
      }
      return new TrackSelectorResult(configs, selections, new Object());
    }

    @Override
    public void onSelectionActivated(Object info) {}
  }

  private static final class MySurfaceHolderCallback implements SurfaceHolder.Callback {

    private final SimpleExoPlayer player;
    private final Renderer renderer;

    public MySurfaceHolderCallback(SimpleExoPlayer player, Renderer renderer) {
      this.player = player;
      this.renderer = renderer;
    }

    @Override
    public void surfaceCreated(SurfaceHolder holder) {
      player
          .createMessage(renderer)
          .setType(C.MSG_SET_SURFACE)
          .setPayload(holder.getSurface())
          .send();
    }

    @Override
    public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {}

    @Override
    public void surfaceDestroyed(SurfaceHolder holder) {}
  }
```

**Comment by imbichitra** [comment]
If i use PlayerView as below 
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  android:orientation="horizontal"
  tools:context=".DemoMainActivity">
  <com.google.android.exoplayer2.ui.PlayerView
    android:id="@+id/surface_view_1"
    app:surface_type="surface_view"
    android:layout_weight="1"
    android:layout_width="0dp"
    android:layout_height="match_parent"/>
  <com.google.android.exoplayer2.ui.PlayerView
    android:id="@+id/surface_view_2"
    app:surface_type="surface_view"
    android:layout_weight="1"
    android:layout_width="0dp"
    android:layout_height="match_parent"/>
</LinearLayout>
```
Following error is shown 
```
Caused by: java.lang.ClassCastException: com.google.android.exoplayer2.ui.PlayerView cannot be cast to android.view.SurfaceView
        at com.google.android.exoplayer2.imademo.DemoMainActivity.initializePlayer(DemoMainActivity.java:147)
        at com.google.android.exoplayer2.imademo.DemoMainActivity.onCreate(DemoMainActivity.java:70)
        at android.app.Activity.performCreate(Activity.java:6858)
```
when get findViewById
```
SurfaceView surfaceView1 = findViewById(R.id.surface_view_1);
SurfaceView surfaceView2 = findViewById(R.id.surface_view_2);
```

**How can i use SurfaceView in my xml file**.

**Comment by imbichitra** [comment]
Thanks, finally i did this.
