### ISSUE TITLE
Getting java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.analytics.AnalyticsListener.onLoadStarted

### ISSUE THREAD

**Issue by ranjan000** [google/ExoPlayer#6738]
I am using exoplayer version 2.10.4 with androidX and gradle version 3.5.3.

I am getting runtime crash

java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.analytics.AnalyticsListener.onLoadStarted(com.google.android.exoplayer2.analytics.AnalyticsListener$EventTime, com.google.android.exoplayer2.source.MediaSourceEventListener$LoadEventInfo, com.google.android.exoplayer2.source.MediaSourceEventListener$MediaLoadData)"
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.onLoadStarted(AnalyticsCollector.java:364)
        at com.google.android.exoplayer2.source.MediaSourceEventListener$EventDispatcher.lambda$loadStarted$2$MediaSourceEventListener$EventDispatcher(MediaSourceEventListener.java:435)
        at com.google.android.exoplayer2.source.-$$Lambda$MediaSourceEventListener$EventDispatcher$WQKVpIh5ilpOizOGmbnyUThugMU.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

The crash appears after updating the gradle version to 3.5+

The flag 
android.enableDexingArtifactTransform=false
works very well and no runtime error. But without this flag, the app crashes.

As I observed, the gradle code shrinking tool doesn't work well if the interface has any optional method.

The proguard as follows
-keep class com.google.android.exoplayer2.** { *; }
-keep class androidx.core.app.CoreComponentFactory { *; }

Dependencies as follows.
implementation "com.google.android.exoplayer:exoplayer-core:$rootProject.exoVersion"
    implementation "com.google.android.exoplayer:exoplayer-hls:$rootProject.exoVersion"
    implementation "com.google.android.exoplayer:exoplayer-dash:$rootProject.exoVersion"
    implementation "com.google.android.exoplayer:extension-okhttp:$rootProject.exoOkhttpVersion"
    compileOnly 'org.checkerframework:checker-qual:2.5.3'
    implementation "com.google.android.exoplayer:extension-ima:$rootProject.exoOkhttpVersion"
    implementation 'androidx.work:work-runtime:2.2.0'
    implementation "androidx.concurrent:concurrent-futures:$rootProject.concurrentVersion"
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'
    implementation 'androidx.media:media:1.1.0'

**Comment by ranjan000** [comment]
Got it.
-keep class com.google.android.exoplayer2.analytics.AnalyticsListener$EventTime { *; }
-keepclassmembers class com.google.android.exoplayer2.analytics.AnalyticsListener$EventTime { *; }
-keepnames class com.google.android.exoplayer2.analytics.AnalyticsListener$EventTime { *; }
-keepclassmembernames class com.google.android.exoplayer2.analytics.AnalyticsListener$EventTime { *; }

Issue solved.
