### ISSUE TITLE
The problem with playing FLAC file

### ISSUE THREAD

**Issue by ChinhQT** [google/ExoPlayer#6739]
I've just updated the lastest Exo and extension/flac libs. But I met the problem with Android 5.1. Sometimes, Player can't play the flac file. Sometimes, noise when playing FLAC content. 

Do you any suggestion to fix these issues ? Thank you so much.

**Comment by christosts** [comment]
Can you please share your content so that we can test locally? You can send it via email to dev.exoplayer@gmail.com with subject "Issue #6739". Also, is this happening on a specific device?

**Comment by ChinhQT** [comment]
Issue #6739 <https://github.com/google/ExoPlayer/issues/6739>

 TuTam-NguyenTranTrungQuan-6131334.flac
<https://drive.google.com/file/d/101DXS8GNQzx2VO5Kk20H-95OwjzeYM8q/view?usp=drive_web>
 XieuLong-PhamQuynhAnh-6132140.flac
<https://drive.google.com/file/d/1W6CfPFj-Bvih1CedM3nVJ6ueIbDDE4Aw/view?usp=drive_web>

**Comment by christosts** [comment]
Hi @ChinhQT ,

I tried the test files on a Nexus 5 (Android 4.4) and a Sony Xperia (Android 5.1.1) with the release-v2 branch and the files played fine.

To further assist you with this issue, can you please clarify:
- You mentioned  you just updated the lastest Exo. Which exactly version do you use? Just to make sure, are you including ExoPlayer as a dependency or are you building from sources (and if yes, which branch)?
- You mentioned `Sometimes, Player can't play the flac file`. Can you provide logs or even a bugreport when this happens?
- What is the device you are experiencing the problems with?

Thanks

**Comment by ChinhQT** [comment]
Hi Exo,

I used release-V2 lib. I used the Oppo phone ( Model : A33w, Android
version 5.1, Oppo Neo 7 A33W )

Thank you for your help.

**Comment by ChinhQT** [comment]
The error log : 
12-10 11:24:07.429 E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IndexOutOfBoundsException: index=17920, limit=17920
        at java.nio.Buffer.checkIndex(Buffer.java:150)
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:171)
        at com.google.android.exoplayer2.audio.ResamplingAudioProcessor.queueInput(:88)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.processBuffers(:707)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(:678)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(:756)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(:1511)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(:657)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(:326)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:218)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by andrewlewis** [comment]
@ChinhQT Can you reproduce this error on the `dev-v2-r2.11.0` branch? It may be the same as #6601.
