### ISSUE TITLE
Can't play video from Dash source on device SamSung SM-J601F/DS

### ISSUE THREAD

**Issue by PhanSon95** [google/ExoPlayer#6740]
I faced error when play drm video on Samsung device with model number SM-J601F/DS
However, on other device player still play video perfect
```
E/MediaDrm-JNI: Illegal state exception: Failed to get provision request: General DRM error (-2000)
E/ExoPlayerImplInternal: Internal runtime error.
    android.media.MediaDrm$MediaDrmStateException: Failed to get provision request: General DRM error
        at android.media.MediaDrm.getProvisionRequestNative(Native Method)
        at android.media.MediaDrm.getProvisionRequest(MediaDrm.java:892)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getProvisionRequest(FrameworkMediaDrm.java:174)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.provision(DefaultDrmSession.java:223)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.provisionRequired(DefaultDrmSessionManager.java:471)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.openInternal(DefaultDrmSession.java:289)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:175)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:437)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1177)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:636)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:737)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:648)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by giladna** [comment]
@PhanSon95 did you try restart the device?

**Comment by christosts** [comment]
Hi,

We would need more information for this crash. There is an issue template you can follow [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) on what is needed. 

For this problem specifically, it'd be essential to have a link to the DASH content and a bugreport from the device when the crash occurs. If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com with the subject  "Issue #6740".

Thanks
