### ISSUE TITLE
ExoPlayerImplInternal: Internal runtime error

### ISSUE THREAD

**Issue by LinTaoAndroid** [google/ExoPlayer#6750]
Playing video with exoplayer(exoplayer:2.9.2) has a high probability of black screen. How can I crack it?Thank you very much

```
ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1986)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1014)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:422)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:387)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:871)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:842)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:824)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:333)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by christosts** [comment]
This is an error from MediaCodec.setOutputSurface; we need more information to assist on an issue like this. Please take a look at the [bug template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

For such an error it would be best to grab a bug-report. If you can't share bug reports publicly, please send them to dev.exoplayer@gmail.com with subject "Issue #6750".

Also, we've seen errors on MdiaCodec.setOutputSurface being device-specific. Have you searched for similar the issues? For example #6346 and #6331.

**Comment by perracolabs** [comment]
Getting a similar exception, from time to time. It happens when rotating the device orientation and the player gets recreated.
The player uses the surface from an external TextureView in order to use shaders, and is assigned via the setVideoSurface method.
I can only reproduce it if I rotate the device to change between portrait-landscape, but takes a while (several rotations none stop) as it happens rarely.
I made sure that the player is released when changing the device orientation. 
Maybe it has something to do (just guessing) if ExoPlayer releases its resources in a separate thread, and when rotating and recreating the player is still in the process of releasing, making the MediaCodecs not to be ready yet, just a guess.

`
2020-01-14 19:12:27.311 26754-30948/com.perracolabs.pixtica W/ACodec: [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 15 failed: -2147483648
2020-01-14 19:12:27.313 26754-30948/com.perracolabs.pixtica W/MapperHal: buffer descriptor with invalid usage bits 0x2000
2020-01-14 19:12:27.315 26754-30948/com.perracolabs.pixtica W/MapperHal: buffer descriptor with invalid usage bits 0x2000
2020-01-14 19:12:27.317 26754-30948/com.perracolabs.pixtica W/MapperHal: buffer descriptor with invalid usage bits 0x2000
2020-01-14 19:12:27.319 26754-30948/com.perracolabs.pixtica W/MapperHal: buffer descriptor with invalid usage bits 0x2000
2020-01-14 19:12:27.320 26754-30943/com.perracolabs.pixtica E/ExoPlayerImplInternal: Internal runtime error.
	java.lang.IllegalArgumentException
		at android.media.MediaCodec.native_setSurface(Native Method)
		at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1986)
		at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1300)
		at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:626)
		at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:592)
		at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1018)
		at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:984)
		at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:966)
		at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:367)
		at android.os.Handler.dispatchMessage(Handler.java:108)
		at android.os.Looper.loop(Looper.java:216)
		at android.os.HandlerThread.run(HandlerThread.java:65)
2020-01-14 19:12:27.321 26754-30948/com.perracolabs.pixtica W/MapperHal: buffer descriptor with invalid usage bits 0x2000
2020-01-14 19:12:27.323 26754-30948/com.perracolabs.pixtica W/MapperHal: buffer descriptor with invalid usage bits 0x2000
2020-01-14 19:12:27.325 26754-30948/com.perracolabs.pixtica W/MapperHal: buffer descriptor with invalid usage bits 0x2000
2020-01-14 19:12:27.327 26754-30948/com.perracolabs.pixtica W/MapperHal: buffer descriptor with invalid usage bits 0x2000
2020-01-14 19:12:27.329 26754-30948/com.perracolabs.pixtica W/MapperHal: buffer descriptor with invalid usage bits 0x2000
2020-01-14 19:12:27.330 26754-30948/com.perracolabs.pixtica W/MapperHal: buffer descriptor with invalid usage bits 0x2000
2020-01-14 19:12:27.332 26754-30948/com.perracolabs.pixtica W/MapperHal: buffer descriptor with invalid usage bits 0x2000
2020-01-14 19:12:27.335 26754-30948/com.perracolabs.pixtica W/MapperHal: buffer descriptor with invalid usage bits 0x2000
2020-01-14 19:12:27.337 26754-30948/com.perracolabs.pixtica W/MapperHal: buffer descriptor with invalid usage bits 0x2000
2020-01-14 19:12:27.339 26754-30948/com.perracolabs.pixtica W/MapperHal: buffer descriptor with invalid usage bits 0x2000
2020-01-14 19:12:27.349 26754-30948/com.perracolabs.pixtica W/ACodec: forcing OMX state to Idle when received shutdown in ExecutingState
2020-01-14 19:12:27.378 26754-30947/com.perracolabs.pixtica D/SurfaceUtils: disconnecting from surface 0x7c92c26010, reason disconnectFromSurface
2020-01-14 19:12:27.395 26754-30963/com.perracolabs.pixtica W/ACodec: forcing OMX state to Idle when received shutdown in ExecutingState
2020-01-14 19:12:27.415 26754-26754/com.perracolabs.pixtica I/ExoPlayerImpl: Release fdd54ac [ExoPlayerLib/2.11.1] [HWSNE, SNE-LX1, HUAWEI, 28] [goog.exo.core, goog.exo.ui]
2020-01-14 19:12:29.353 26754-30961/com.perracolabs.pixtica I/RendererManager#21080.RendererManager.run: Terminated render loop.
2020-01-14 19:12:29.423 26754-26859/com.perracolabs.pixtica W/libEGL: EGLNativeWindowType 0x7cabee8010 disconnect failed
2020-01-14 19:12:29.424 26754-26859/com.perracolabs.pixtica D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2020-01-14 19:12:29.447 26754-26754/com.perracolabs.pixtica I/main#1.FilterRender.onRendererEnd: Filter renderer stopped.
2020-01-14 19:12:29.470 26754-26754/com.perracolabs.pixtica I/ExoPlayerImpl: Init 36f9df [ExoPlayerLib/2.11.1] [HWSNE, SNE-LX1, HUAWEI, 28]
2020-01-14 19:12:29.497 26754-26754/com.perracolabs.pixtica I/main#1.RendererManager.RendererManager: Renderer manager instantiated.
2020-01-14 19:12:29.501 26754-30976/com.perracolabs.pixtica I/RendererManager#21089.EglCore.EglCore: EGLContext created with client version: 3
2020-01-14 19:12:29.503 26754-30976/com.perracolabs.pixtica D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2020-01-14 19:12:29.505 26754-30978/com.perracolabs.pixtica I/OMXClient: IOmx service obtained
`
