### ISSUE TITLE
Exoplayer IllegalStateException On TV Sony

### ISSUE THREAD

**Issue by EddieMeng** [google/ExoPlayer#6754]
### Issue Description
 Hello, i have an issue with exoplayer when playing video in Sony tv. I will descripbe the reproduce procudure and the softaware and hardware condition below, can you guys help me to solve this issue or  give me some clues about it, Thanks a lot.

          12-10 15:13:15.722: E/ExoPlayerImplInternal(9505): Internal runtime error.
          12-10 15:13:15.722: E/ExoPlayerImplInternal(9505): android.media.MediaCodec$CodecException: 
          Error 0xffffffe0
          12-10 15:13:15.722: E/ExoPlayerImplInternal(9505): 	at 
          android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
          12-10 15:13:15.722: E/ExoPlayerImplInternal(9505): 	at 
          android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2635)
          12-10 15:13:15.722: E/ExoPlayerImplInternal(9505): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRendere r.java:3)
          12-10 15:13:15.722: E/ExoPlayerImplInternal(9505): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:9)
          12-10 15:13:15.722: E/ExoPlayerImplInternal(9505): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:12)
          12-10 15:13:15.722: E/ExoPlayerImplInternal(9505): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:17)
          12-10 15:13:15.722: E/ExoPlayerImplInternal(9505): 	at android.os.Handler.dispatchMessage(Handler.java:102)
          12-10 15:13:15.722: E/ExoPlayerImplInternal(9505): 	at android.os.Looper.loop(Looper.java:193)
          12-10 15:13:15.722: E/ExoPlayerImplInternal(9505): 	at android.os.HandlerThread.run(HandlerThread.java:65)

          12-10 15:13:15.905: E/ExoPlayerImplInternal(9505): Reset failed.
          12-10 15:13:15.905: E/ExoPlayerImplInternal(9505): java.lang.IllegalStateException
          12-10 15:13:15.905: E/ExoPlayerImplInternal(9505): 	at android.media.MediaCodec.native_stop(Native Method)
          12-10 15:13:15.905: E/ExoPlayerImplInternal(9505): 	at android.media.MediaCodec.stop(MediaCodec.java:2084)
          12-10 15:13:15.905: E/ExoPlayerImplInternal(9505): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:14)
          12-10 15:13:15.905: E/ExoPlayerImplInternal(9505): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:1)
          12-10 15:13:15.905: E/ExoPlayerImplInternal(9505): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onReset(MediaCodecRenderer.java:1)
          12-10 15:13:15.905: E/ExoPlayerImplInternal(9505): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onReset(MediaCodecVideoRenderer.java:1)
          12-10 15:13:15.905: E/ExoPlayerImplInternal(9505): 	at com.google.android.exoplayer2.BaseRenderer.reset(BaseRenderer.java:2)
          12-10 15:13:15.905: E/ExoPlayerImplInternal(9505): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:9)
          12-10 15:13:15.905: E/ExoPlayerImplInternal(9505): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1)
          12-10 15:13:15.905: E/ExoPlayerImplInternal(9505): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:26)
          12-10 15:13:15.905: E/ExoPlayerImplInternal(9505): 	at android.os.Handler.dispatchMessage(Handler.java:102)
          12-10 15:13:15.905: E/ExoPlayerImplInternal(9505): 	at android.os.Looper.loop(Looper.java:193)
          12-10 15:13:15.905: E/ExoPlayerImplInternal(9505): 	at android.os.HandlerThread.run(HandlerThread.java:65)

### Reproduction steps
On the Sony TV, When User play video on youtube, and then switch to our  app play some video content, and switch back to youtube again, youtube will keep loading thus fail to play any video content. We check the error log, and found the exoplayer's internal error might cause this issue.

### Hardware Info
Sony TV

### Software Info
Android O & P
ExoPlayer Version : 2.10.4

### Complete bug log info
[logcat_switch to youtube error.txt](https://github.com/google/ExoPlayer/files/3954915/logcat_switch.to.youtube.error.txt)

**Comment by christosts** [comment]
Is it possible to verify you are releasing the player correctly when you app goes to background? Please check the [demo app](https://github.com/google/ExoPlayer/blob/r2.11.0/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java) on how to release the player properly.

**Comment by EddieMeng** [comment]
> Hey @EddieMeng. We need more information to resolve this issue but there hasn't been an update in 14 days. I'm marking the issue as stale and if there are no new updates in the next 7 days I will close it automatically.

Hello, Sorry for the late reply, I was busy doing some other things recently, so i didn't reply it on time.

**Comment by EddieMeng** [comment]
> Is it possible to verify you are releasing the player correctly when you app goes to background? Please check the [demo app](https://github.com/google/ExoPlayer/blob/r2.11.0/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java) on how to release the player properly.

Hello, Sorry for the late reply, I was busy doing some other things recently, so i didn't reply it on time.
After i check the release logic of my app, we didn't release the codec when we run in the background. The reason for this is when the app go into foreground, the video should resume  play, if we release the codec, we need to recreate it and prepare the url again, that costs a lot of time.  But even i didn't release it , it should not affect other apps, right?

**Comment by marcbaechinger** [comment]
> we didn't release the codec when we run in the background

Then the crashed you are reporting is likely to be caused by your app which holds a codec instance YouTube wants to acquire too.

> it should not affect other apps, right?

It does. You need to release the codec when the app goes in background. Codecs are shared resources with other apps, so if you do not release codecs, other apps can fail if no other codec instances are available. 

Please see the demo app which does release properly on given life cycle methods of the activity.

> we need to recreate it and prepare the url again, that costs a lot of time

If you are concerned about the startup time for when you app comes into foreground again you can apply a CacheDataSource which makes sure that the app has the data available when the player is recreated.

**Comment by EddieMeng** [comment]
> > we didn't release the codec when we run in the background
> 
> Then the crashed you are reporting is likely to be caused by your app which holds a codec instance YouTube wants to acquire too.
> 
> > it should not affect other apps, right?
> 
> It does. You need to release the codec when the app goes in background. Codecs are shared resources with other apps, so if you do not release codecs, other apps can fail if no other codec instances are available.
> Okay, I used to think the Codec is app's specific resources, living in the app's own memory. After listening to you, i will try to release the codec, and see if the problem will be solved.
> Please see the demo app which does release properly on given life cycle methods of the activity.
> 
> > we need to recreate it and prepare the url again, that costs a lot of time
> 
> If you are concerned about the startup time for when you app comes into foreground again you can apply a CacheDataSource which makes sure that the app has the data available when the player is recreated.
thank you for tell me that, i wanna ask by using exoplayer's CacheDataSource, is it possible to resume all the data the same as before release it, such as the video progress, video player state.

**Comment by marcbaechinger** [comment]
>  is it possible to resume all the data the same as before release it, 
> such as the video progress, video player state.

The demo app does this. Have a look into the PlayerActivity:

https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L205

**Comment by EddieMeng** [comment]
> > is it possible to resume all the data the same as before release it,
> > such as the video progress, video player state.
> 
> The demo app does this. Have a look into the PlayerActivity:
> 
> https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L205

okay, thanks for you reply. I will check the demo to see how it implement.

**Comment by marcbaechinger** [comment]
Closing due to inactivity. Please reopen if required.
