### ISSUE TITLE
当我使用extension-opus运行时发生crash

### ISSUE THREAD

**Issue by rd-wang** [google/ExoPlayer#6769]
When reporting a bug:
-----------------------
```
2019-12-16 19:23:55.629 31401-31530/com.roobo.pudding E/CrashHandler: Crash Log BEGIN
2019-12-16 19:23:55.630 31401-31530/com.roobo.pudding E/CrashHandler: STACK_TRACE=java.lang.NoSuchMethodError: No static method $$triggerInterfaceInit()V in class Lcom/google/android/exoplayer2/Renderer$$CC; or its super classes (declaration of 'com.google.android.exoplayer2.Renderer$$CC' appears in base.apk!classes7.dex)
        at com.google.android.exoplayer2.BaseRenderer.<clinit>(Unknown Source:0)
        at com.roobo.puddingplus_v1.util.MediaMgr.setUrlPlay(MediaMgr.java:70)
        at com.roobo.puddingplus_v1.ui.activity.YEBPlayActivity$DataAdapter.onPageSelected(YEBPlayActivity.java:305)
        at com.roobo.puddingplus_v1.ui.activity.YEBPlayActivity$1.onStoreChangeEvent(YEBPlayActivity.java:191)
        at com.roobo.puddingplus_v1.flux.Store.onStoreChangeEvent(Store.java:47)
        at com.roobo.puddingplus_v1.ui.control.YEBStore.access$800(YEBStore.java:64)
        at com.roobo.puddingplus_v1.ui.control.YEBStore$11.onResponse(YEBStore.java:633)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6867)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
2019-12-16 19:23:55.640 31401-31530/com.roobo.pudding I/CrashHandler: Crash Log END
```
### [REQUIRED] Issue description
按照opus的文档 ，本地引入exoplayer 编译opus 并且仿照TestPlaybackRunnable中的
```
LibopusAudioRenderer audioRenderer = new LibopusAudioRenderer();
      player = new ExoPlayer.Builder(context, audioRenderer).build();
      player.addListener(this);
      MediaSource mediaSource =
          new ProgressiveMediaSource.Factory(
                  new DefaultDataSourceFactory(context, "ExoPlayerExtOpusTest"),
                  MatroskaExtractor.FACTORY)
              .createMediaSource(uri);
      player.prepare(mediaSource);
      player.setPlayWhenReady(true);
```

### [REQUIRED] Version of ExoPlayer being used
latest

### [REQUIRED] Device(s) and version(s) of Android being used
android 9.0 小米MIX2

**Comment by Samrobbo** [comment]
Hi, 

I could not replicate this, please can I get some more information, such as: 

- The exact version of ExoPlayer used, is it 2.11.0? is it 2.10.7?
- A full bug report. You can capture a full bug report using "adb bugreport". Output from "adb logcat" or a log snippet is NOT sufficient.
- A link or copy of the media you used. 

If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by rd-wang** [comment]
使用的是release-v2的最新的提交r2.11.0

```
commit 76962d50f1d80941d6768e4e765fa4ff010705e7 (HEAD -> release-v2, tag: r2.11.0, origin/release-v2, origin/HEAD)
Merge: 33938c05b 4a4aa16d4
Author: Oliver Woodman <olly@google.com>
Date:   Wed Dec 11 16:11:21 2019 +0000

    Merge pull request #6752 from google/dev-v2-r2.11.0

    r2.11.0
```
测试工程已经上传   https://github.com/rd-wang/testOpus

按照如下方式导入
```
    implementation project(path: ':exoplayer-library-core')
    implementation project(path: ':exoplayer-library-dash')
    implementation project(path: ':exoplayer-extension-opus')
```
如下方式调用
```
String url = "http://media.roobo.net/res/20191212/1ed6d607e7105de7d2933f545e28ec40.opus";
                try {
                    if (mPlayer == null) {
                        LibopusAudioRenderer audioRenderer = new LibopusAudioRenderer();
                        mPlayer = new ExoPlayer.Builder(MainActivity.this, audioRenderer).build();
                    }
                    MediaSource mediaSource =
                            new ProgressiveMediaSource.Factory(
                                    new DefaultDataSourceFactory(MainActivity.this, "ExoPlayerExtOpusTest"),
                                    MatroskaExtractor.FACTORY)
                                    .createMediaSource(Uri.parse(url));
                    mPlayer.addListener(
                            new Player.EventListener() {
                                @Override
                                public void onPlayerError(ExoPlaybackException error) {
                                    error.printStackTrace();
                                }
                                @Override
                                public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                                    if (playbackState == Player.STATE_ENDED) {
                                    }
                                }
                            }
                    );
                    mPlayer.prepare(mediaSource);
                    mPlayer.setPlayWhenReady(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
```
捕获到的错误如下
```
W/System.err: java.io.FileNotFoundException: /jacoco.exec (Read-only file system)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:308)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
        at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.openFile(FileOutput.java:67)
        at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.startup(FileOutput.java:49)
        at org.jacoco.agent.rt.internal_8ff85ea.Agent.startup(Agent.java:122)
W/System.err:     at org.jacoco.agent.rt.internal_8ff85ea.Agent.getInstance(Agent.java:50)
        at org.jacoco.agent.rt.internal_8ff85ea.Offline.<clinit>(Offline.java:31)
        at org.jacoco.agent.rt.internal_8ff85ea.Offline.getProbes(Offline.java:51)
        at com.google.android.exoplayer2.Renderer.<clinit>(Unknown Source:8)
        at com.roobo.teacher.testopus.MainActivity$1.onClick(MainActivity.java:40)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25921)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6867)
        at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
W/eacher.testopu: Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (light greylist, reflection)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.roobo.teacher.testopus, PID: 15210
    java.lang.BootstrapMethodError: Exception from call site #93 bootstrap method
        at com.google.android.exoplayer2.util.SlidingPercentile.<clinit>(SlidingPercentile.java:38)
        at com.google.android.exoplayer2.upstream.DefaultBandwidthMeter.<init>(DefaultBandwidthMeter.java:274)
        at com.google.android.exoplayer2.upstream.DefaultBandwidthMeter.<init>(DefaultBandwidthMeter.java:48)
        at com.google.android.exoplayer2.upstream.DefaultBandwidthMeter$Builder.build(DefaultBandwidthMeter.java:190)
        at com.google.android.exoplayer2.upstream.DefaultBandwidthMeter.getSingletonInstance(DefaultBandwidthMeter.java:227)
        at com.google.android.exoplayer2.ExoPlayer$Builder.<init>(ExoPlayer.java:171)
        at com.roobo.teacher.testopus.MainActivity$1.onClick(MainActivity.java:41)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25921)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6867)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.google.android.exoplayer2.util.SlidingPercentile.<clinit>(SlidingPercentile.java:38) 
        at com.google.android.exoplayer2.upstream.DefaultBandwidthMeter.<init>(DefaultBandwidthMeter.java:274) 
        at com.google.android.exoplayer2.upstream.DefaultBandwidthMeter.<init>(DefaultBandwidthMeter.java:48) 
        at com.google.android.exoplayer2.upstream.DefaultBandwidthMeter$Builder.build(DefaultBandwidthMeter.java:190) 
        at com.google.android.exoplayer2.upstream.DefaultBandwidthMeter.getSingletonInstance(DefaultBandwidthMeter.java:227) 
        at com.google.android.exoplayer2.ExoPlayer$Builder.<init>(ExoPlayer.java:171) 
        at com.roobo.teacher.testopus.MainActivity$1.onClick(MainActivity.java:41) 
        at android.view.View.performClick(View.java:6608) 
        at android.view.View.performClickInternal(View.java:6585) 
        at android.view.View.access$3100(View.java:785) 
        at android.view.View$PerformClick.run(View.java:25921) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:6867) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876) 
I/Process: Sending signal. PID: 15210 SIG: 9
Process 15210 terminated.
```
但是这个错误和上面的好像不是一个

**Comment by rd-wang** [comment]
当我使用r2.10.7
```
                String url = "http://media.roobo.net/res/20191212/1ed6d607e7105de7d2933f545e28ec40.opus";
                LibopusAudioRenderer audioRenderer = new LibopusAudioRenderer();
                DefaultTrackSelector trackSelector = new DefaultTrackSelector();
                mPlayer = ExoPlayerFactory.newInstance(MainActivity.this, new Renderer[] {audioRenderer}, trackSelector);
                MediaSource mediaSource =
                        new ProgressiveMediaSource.Factory(
                                new DefaultDataSourceFactory(MainActivity.this, "ExoPlayerExtOpusTest"),
                                MatroskaExtractor.FACTORY)
                                .createMediaSource(Uri.parse(url));
                mPlayer.prepare(mediaSource);
                mPlayer.setPlayWhenReady(true);
```
我获得如下错误
```

12/17 12:06:19: Launching 'app' on Xiaomi MIX 2.
$ adb shell am start -n "com.roobo.teacher.testopus/com.roobo.teacher.testopus.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Waiting for process to come online...
Connected to process 18397 on device 'xiaomi-mix_2-e5e20c22'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/eacher.testopu: Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (light greylist, reflection)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.roobo.teacher.testopus, PID: 18397
    java.lang.BootstrapMethodError: Exception from call site #78 bootstrap method
        at com.google.android.exoplayer2.trackselection.TrackBitrateEstimator.<clinit>(TrackBitrateEstimator.java:31)
        at com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection$Factory.<init>(AdaptiveTrackSelection.java:206)
        at com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection$Factory.<init>(AdaptiveTrackSelection.java:172)
        at com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection$Factory.<init>(AdaptiveTrackSelection.java:56)
        at com.google.android.exoplayer2.trackselection.DefaultTrackSelector.<init>(DefaultTrackSelector.java:1386)
        at com.roobo.teacher.testopus.MainActivity$1.onClick(MainActivity.java:72)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25921)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6867)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.google.android.exoplayer2.trackselection.TrackBitrateEstimator.<clinit>(TrackBitrateEstimator.java:31) 
        at com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection$Factory.<init>(AdaptiveTrackSelection.java:206) 
        at com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection$Factory.<init>(AdaptiveTrackSelection.java:172) 
        at com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection$Factory.<init>(AdaptiveTrackSelection.java:56) 
        at com.google.android.exoplayer2.trackselection.DefaultTrackSelector.<init>(DefaultTrackSelector.java:1386) 
        at com.roobo.teacher.testopus.MainActivity$1.onClick(MainActivity.java:72) 
        at android.view.View.performClick(View.java:6608) 
        at android.view.View.performClickInternal(View.java:6585) 
        at android.view.View.access$3100(View.java:785) 
        at android.view.View$PerformClick.run(View.java:25921) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:6867) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876) 
Process 18397 terminated.

```

**Comment by ojw28** [comment]
I think you need to enable Java 8 support, as documented in our developer guide:

https://exoplayer.dev/hello-world.html#turn-on-java-8-support

You need to do this in the `build.gradle` for the `app` module.
