### ISSUE TITLE
HLS playback fails if chunk requests returns HTTP 416 status code

### ISSUE THREAD

**Issue by ArtYemelianov** [google/ExoPlayer#6775]
### Issue description

Exoplayer is crashed and doesn't switch to another stream (variant) if the new position in the stream is out-of-range.
```
Caused by: com.google.android.exoplayer2.upstream.DataSourceException
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:314)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:257) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:369) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:350) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:325) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:301) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:394) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 

```
### Reproduction steps

1. Provide a playlist with several streams (*.ts extension)
    For example in my case, there are streams: 
            _- stream/song_name_high_quality.ts_  (some chunks in the stream are broken)
            _- stream/song_name_low_quality.ts_  (works propertly)

2. Play the playlist

For example, playback starts from  _- stream/song_name_low_quality.ts_ and after a period of time, the current stream will be switched to more high-quality video which is broken since some chunks are not accessible.

#### Actual behavior
Exoplayer crashes with error `DataSourceException.POSITION_OUT_OF_RANGE`

#### Excepted behaviour
Current stream should be change to proper stream. In above case the current stream should be changed to _- stream/song_name_low_quality.ts_

### Exoplayer Version
https://github.com/google/ExoPlayer/commits/r2.10.8

**Comment by Samrobbo** [comment]
Hi, if possible, can you share your test content with us, so that I can reproduce this. If you do not wish to share it publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by ArtYemelianov** [comment]
Hi @Samrobbo ,
yes, I don't want to share a link publicity, therefore I sent in your email  dev.exoplayer@gmail.com 
Thanks.

**Comment by Samrobbo** [comment]
We'll look into this in the new year, as the team are almost all taking time off for the holiday period.

**Comment by ojw28** [comment]
It should be noted that VLC fails in exactly the same way:
```
[00007f663c306490] adaptive stream error: Failed reading <url-to-one-of-the-chunks-was-here>: HTTP/1.1 416 Requested Range Not Satisfiable
```

We currently have logic to blacklist the variant (temporarily) and switch to another one if the server returns a 404 or a 410, but not a 416. We can probably add 416 to the list as well. In the meantime, you can do this yourself when creating the `HlsMediaSource`:

```
return new HlsMediaSource.Factory(dataSourceFactory)
    .......
    .setLoadErrorHandlingPolicy(new DefaultLoadErrorHandlingPolicy() {
      @Override
      public long getBlacklistDurationMsFor(
          int dataType, long loadDurationMs, IOException exception, int errorCount) {
       if (exception instanceof HttpDataSource.InvalidResponseCodeException) {
          int responseCode =
            ((HttpDataSource.InvalidResponseCodeException) exception).responseCode;
          return responseCode == 416 // HTTP 416
              ? DEFAULT_TRACK_BLACKLIST_MS
              : C.TIME_UNSET;
        }
        // Otherwise use the default policy logic.
        return super.getBlacklistDurationMsFor(
           dataType, loadDurationMs, exception, errorCount);
      }
    })
    .createMediaSource(uri);
```
