### ISSUE TITLE
Play local m3u8 with local media content

### ISSUE THREAD

**Issue by andrea157** [google/ExoPlayer#6791]
Hi, I want to play a local .m3u8 files that have a link to a local video file. The local video file is saved in asset folder.

This is my m3u8:
```
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
asset:///android_asset/content_1.mp4
#EXT-X-ENDLIST
```
When i try to play the content I have the error:

E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.metadata.Metadata.length()' on a null object reference

What is my mistake?
Thanks!

**Comment by ojw28** [comment]
Please can you provide at least a complete stack trace, rather than just the top line? More generally, why are you trying to do this? Just play the MP4 file directly and keep things simple.

Thanks.

**Comment by andrea157** [comment]
Yes sorry,

I would like to use the m3u8 to manage the selection of multi bitrate, multi track audio and multi track subtitles in a single file as I already do for online content. Do you think it's not possible and is it better to use MergingMediaSource and create a mediasource with all my tracks?

here it is:

```
2019-12-19 17:39:48.838 10356-10407/com.xxx.yyyy E/LoadTask: Unexpected exception loading stream
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.metadata.Metadata.length()' on a null object reference
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.createFragmentedMp4Extractor(DefaultHlsExtractorFactory.java:276)
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.createExtractorByFileExtension(DefaultHlsExtractorFactory.java:212)
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.createExtractor(DefaultHlsExtractorFactory.java:114)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:379)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:350)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:325)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:301)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:394)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-12-19 17:39:48.844 10356-10405/com.xxx.yyyy E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.metadata.Metadata.length()' on a null object reference
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:416)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.metadata.Metadata.length()' on a null object reference
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.createFragmentedMp4Extractor(DefaultHlsExtractorFactory.java:276)
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.createExtractorByFileExtension(DefaultHlsExtractorFactory.java:212)
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.createExtractor(DefaultHlsExtractorFactory.java:114)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:379)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:350)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:325)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:301)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:394)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by ojw28** [comment]
The specific `NullPointerException` wont occur in 2.11.0 because there's now a check for it. I doubt that's sufficient to make your approach work though.

> I would like to use the m3u8 to manage the selection of multi bitrate, multi track audio and multi track subtitles in a single file as I already do for online content.

I assume you're using HLS for streamed content. Is that correct? It should be possible for you to play HLS content locally in the same way, so there's nothing particularly wrong with the principle of what you're trying to do. I would question whether the HLS playlist you've provided is actually a valid HLS playlist though. It looks a bit like an invalid HLS playlist created by editing a valid one, putting a link to a single (non-fragmented?) MP4 into it, and hoping that works. If you want to play HLS content then you need to ensure that the content you've created complies with the HLS spec.

**Comment by andrea157** [comment]
Hi, thanks for your support, I understand my mistake.
Now I have rewrite my m3u8: 

> #EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=852000,RESOLUTION=854x480
480_out.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=852000,RESOLUTION=1280x720
720_out.m3u8

and 480_out.m3u8 (720_out is similar) is:

> #EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:9
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:9.080000,
480_out0.ts
#EXTINF:2.120000,
480_out1.ts
...
#EXTINF:1.440000,
480_out13.ts
#EXT-X-ENDLIST

Now the content is correctly played and I can select the quality track but I have another issue, when I do a seek back I have this error:

```
2019-12-22 22:26:12.233 4422-4914/com.xxx.yyyE/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:197)
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:60)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:172)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:394)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

Can you help me?
Thanks

**Comment by ojw28** [comment]
The error is:
```
Input does not start with the #EXTM3U header.
```
One of your playlist files doesn't start with the `#EXTM3U` line, so the media is still not correctly formatted.
