### ISSUE TITLE
High FPS videos problem

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#6808]
I have a playback problem. When I try playing video with more than 25FPS, video is lags, it is not smooth. I have a test video with 50FPS, video plays good, but with horrible lags.As if omitting frames. When I try playing 25FPS video, everything is alright. Videos is in local folder, not stream. Does anyone have an idea?. Is it my nightmare :)

**Comment by marcbaechinger** [comment]
Can you please provide some more information? Please add some url to the streams you are trying to play. Also if you take a bug report right after the observed behaviour we can easily see what device, OS version and ExoPlayer version you are using. We need this information and the test streams to accurately look into your issue. 

If you do not want to send this information in public, you can send an email to dev.exoplayer@gmail.com instead.

**Comment by ghost** [comment]
Thank you for responding.

The video is not a stream but a local video stored in the download folder. 
```
private MediaSource buildMediaSource(Uri uri) {
        return new ExtractorMediaSource(uri,
                new DefaultDataSourceFactory(this,"ua"),
                new DefaultExtractorsFactory(), null, null);
    }
```

Upload video - 
([https://drive.google.com/file/d/1Ijtm0aB4dXNKoqCVcN_FHuWZtL6FhRkG/view?usp=sharing](url).
ExoPlayer version 'com.google.android.exoplayer:exoplayer-core:2.11.1'
OS Version Android 4.4 (Philips pro digital signage).
 
I've found a new problem, I'm trying to play a 500 MB video. It gets stuck somewhere in the middle.
```
E/LoadTask: OutOfMemory error loading stream
    java.lang.OutOfMemoryError
        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
        at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:703)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:623)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:553)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:192)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:987)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: null
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:421)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.OutOfMemoryError
        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
        at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:703)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:623)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:553)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:192)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:987)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
```
thank you for answer

**Comment by marcbaechinger** [comment]
Can you please provide a bug report right after you played the video with 50fps?

And can you please open another issue for the OutOfMemory problem? Pretty much the same information needed for the new issue: url to the file, bug report.

**Comment by ghost** [comment]
From 50FPS 

D/Playing :: /storage/emulated/0/Download/test1.mp4
I/ExoPlayerImpl: Release 41eadfe0 [ExoPlayerLib/2.11.1] [DL, 32BDL4050D, TPV, 19] [goog.exo.core, goog.exo.ui]
D/Constraints: Player Is Null Setting Up Player
I/ExoPlayerImpl: Init 41f632d0 [ExoPlayerLib/2.11.1] [DL, 32BDL4050D, TPV, 19]
D/exoPlayer :: Buffering
I/OMXClient: Using client-side OMX mux.
E/ACodec: [OMX.rk.video_decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
W/ACodec: [OMX.rk.video_decoder.avc] prepareForAdaptivePlayback failed w/ err -2147483648
I/OMXClient: Using client-side OMX mux.
I/: new RKOMXPlugin
D/ACodec: MEDIA_MIMETYPE_AUDIO_AAC sampleRate 48000 wifidisplay_flag 0 info 683db0a8
I/SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
D/dalvikvm: GC_FOR_ALLOC freed 25530K, 67% free 10516K/31668K, paused 23ms, total 23ms
D/dalvikvm: GC_FOR_ALLOC freed 2K, 59% free 13077K/31668K, paused 15ms, total 15ms
D/dalvikvm: GC_FOR_ALLOC freed <1K, 48% free 16474K/31668K, paused 18ms, total 18ms
D/dalvikvm: GC_FOR_ALLOC freed <1K, 34% free 21025K/31668K, paused 15ms, total 15ms
D/dalvikvm: GC_FOR_ALLOC freed <1K, 15% free 27114K/31668K, paused 14ms, total 14ms
D/exoPlayer :: Buffering
D/exoPlayer :: Ended

Url for large file 
https://drive.google.com/open?id=1gLUOXiQMsHF09xk_As2Jy5ac2TdgEizM <https://drive.google.com/open?id=1gLUOXiQMsHF09xk_As2Jy5ac2TdgEizM>

D/Playing :: /storage/emulated/0/Download/Aragma_foto.mp4
D/Constraints: Player Is Null Setting Up Player
I/ExoPlayerImpl: Init 41f776c0 [ExoPlayerLib/2.11.1] [DL, 32BDL4050D, TPV, 19]
D/exoPlayer :: Buffering
I/OMXClient: Using client-side OMX mux.
E/ACodec: [OMX.rk.video_decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
W/ACodec: [OMX.rk.video_decoder.avc] prepareForAdaptivePlayback failed w/ err -2147483648
D/dalvikvm: GC_FOR_ALLOC freed 1127K, 85% free 9910K/65524K, paused 26ms, total 28ms
I/OMXClient: Using client-side OMX mux.
I/: new RKOMXPlugin
D/ACodec: MEDIA_MIMETYPE_AUDIO_AAC sampleRate 48000 wifidisplay_flag 0 info 40038080
I/SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
D/dalvikvm: GC_FOR_ALLOC freed 394K, 7% free 11853K/12648K, paused 56ms, total 56ms
D/dalvikvm: GC_FOR_ALLOC freed 2K, 6% free 14160K/14960K, paused 18ms, total 24ms
D/dalvikvm: GC_FOR_ALLOC freed 1K, 5% free 17172K/18020K, paused 35ms, total 36ms
D/dalvikvm: GC_FOR_ALLOC freed 1K, 4% free 21210K/22032K, paused 31ms, total 34ms
D/dalvikvm: GC_FOR_ALLOC freed 1K, 3% free 26593K/27404K, paused 18ms, total 18ms
D/dalvikvm: GC_FOR_ALLOC freed 1K, 3% free 33835K/34612K, paused 21ms, total 21ms
D/dalvikvm: GC_FOR_ALLOC freed 1K, 2% free 41270K/42092K, paused 31ms, total 31ms
D/dalvikvm: GC_FOR_ALLOC freed 1K, 2% free 48704K/49504K, paused 23ms, total 23ms
D/dalvikvm: GC_FOR_ALLOC freed 1K, 2% free 56138K/56916K, paused 23ms, total 23ms
I/dalvikvm-heap: Clamp target GC heap from 70.246MB to 64.000MB
D/dalvikvm: GC_FOR_ALLOC freed 36K, 2% free 63672K/64396K, paused 33ms, total 33ms
I/dalvikvm-heap: Clamp target GC heap from 71.309MB to 64.000MB
D/dalvikvm: GC_FOR_ALLOC freed <1K, 2% free 64761K/65484K, paused 35ms, total 35ms
I/dalvikvm-heap: Forcing collection of SoftReferences for 65552-byte allocation
I/dalvikvm-heap: Clamp target GC heap from 71.309MB to 64.000MB
D/dalvikvm: GC_BEFORE_OOM freed <1K, 2% free 64761K/65484K, paused 39ms, total 39ms
E/dalvikvm-heap: Out of memory on a 65552-byte allocation.
I/dalvikvm: "Loader:ProgressiveMediaPeriod" prio=5 tid=15 RUNNABLE
      | group="main" sCount=0 dsCount=0 obj=0x41fa62c8 self=0x684867a0
      | sysTid=6833 nice=0 sched=0/0 cgrp=apps handle=1749572496
      | state=R schedstat=( 1712444250 710014125 3425 ) utm=71 stm=100 core=3
I/dalvikvm:     at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:~102)
        at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:703)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:623)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:553)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:192)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:987)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
E/LoadTask: OutOfMemory error loading stream
    java.lang.OutOfMemoryError
        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
        at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:703)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:623)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:553)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:192)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:987)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: null
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:421)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.OutOfMemoryError
        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
        at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:703)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:623)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:553)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:192)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:987)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
D/exoPlayer :: IDLE

**Comment by marcbaechinger** [comment]
Can you please create another issue for the OutOfMemory case?

**Comment by ghost** [comment]
Sorry, but I have no choice. I had to get out of the office. Do you have any ideas with FPS problems? Aragmas video, which i was share for you. had problem too. When i convert via ffmpeg (macOS) to 25fps, video is smooth.. :)

**Comment by marcbaechinger** [comment]
Closed due to lack of information (bug report) and activity.
