### ISSUE TITLE
Exoplayer HLS returning 403 forbidden

### ISSUE THREAD

**Issue by alanperius** [google/ExoPlayer#6812]
Hi guys, I have a android radio App and i'm trying to play an online radio without success. Recently this radio station changed his url and i can't play with exoplayer. 

the Url is: https://e.mm.uol.com.br/band/radiobandeirantes_poa/playlist.m3u8

sending this request using chrome postman, this return with successful but when I play on exoplayer Return 403 

```
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
    (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

```

I'm using explayer 2.9.1. 
I tried lot of solutions founded here and other sites but without success..

code:

```
    private void preparePlayerBand() throws IOException {
        bandwidthMeter = new DefaultBandwidthMeter();
        extractorsFactory = new DefaultExtractorsFactory();

        String userAgent = Util.getUserAgent(this, "RS Rádio Futebol");
        DefaultHttpDataSourceFactory httpDataSourceFactory = new DefaultHttpDataSourceFactory(
                userAgent,
                null /* listener */,
                DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
                DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS,
                true /* allowCrossProtocolRedirects */
        );

        trackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        trackSelector = new DefaultTrackSelector(trackSelectionFactory);
        defaultBandwidthMeter = new DefaultBandwidthMeter();

        dataSourceFactory = new DefaultDataSourceFactory(
                this,
                null /* listener */,
                httpDataSourceFactory
        );

        final MediaSource mediaSource = buildMediaSource(Uri.parse("https://e.mm.uol.com.br/band/radiobandeirantes_poa/playlist.m3u8"),
                Uri.parse("https://e.mm.uol.com.br/band/radiobandeirantes_poa/playlist.m3u8").getPath().substring(Uri.parse("https://e.mm.uol.com.br/band/radiobandeirantes_poa/playlist.m3u8").getPath().lastIndexOf(".") + 1),
                dataSourceFactory);

        //mediaSourceBand = new HlsMediaSource.Factory(dataSourceFactory).setExtractorFactory(defaultHlsExtractorFactory).createMediaSource(Uri.parse(urlBand));

        mediaPlayerBand = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
        mediaPlayerBand.prepare(mediaSource);
        mediaPlayerBand.setVolume(1);

        mediaPlayerBand.setPlayWhenReady(true);

    }
```

```
private MediaSource buildMediaSource(final Uri uri, final String overrideExtension, DataSource.Factory dataSourceFactory)
    {
        int type = TextUtils.isEmpty(overrideExtension) ? Util.inferContentType(uri)
                : Util.inferContentType("." + overrideExtension);
        switch (type)
        {
            case C.TYPE_SS:
                return new SsMediaSource(uri, buildDataSourceFactory(false),
                        new DefaultSsChunkSource.Factory(dataSourceFactory), mainHandler, (MediaSourceEventListener) eventLogger);
            case C.TYPE_DASH:
                return new DashMediaSource(uri, buildDataSourceFactory(false),
                        new DefaultDashChunkSource.Factory(dataSourceFactory), mainHandler, (MediaSourceEventListener) eventLogger);
            case C.TYPE_HLS:
                return new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(uri);
            case C.TYPE_OTHER:
                return new ExtractorMediaSource(uri, dataSourceFactory, new DefaultExtractorsFactory(),
                        mainHandler, (ExtractorMediaSource.EventListener) eventLogger);
            default:
            {
                throw new IllegalStateException("Unsupported type: " + type);
            }
        }
    }

    private DataSource.Factory buildDataSourceFactory(final boolean useBandwithMeter)
    {
        String userAgent = Util.getUserAgent(this, "RS Rádio Futebol");
        return new DefaultDataSourceFactory(this, useBandwithMeter ? BANDWIDTH_METER : null,
                new DefaultHttpDataSourceFactory(userAgent, useBandwithMeter ? BANDWIDTH_METER : null));
    }

``` 

I tried to add a cookies on OnCreate:

```
    static
    {
        DEFAULT_COOKIE_MANAGER = new CookieManager();
        DEFAULT_COOKIE_MANAGER.setCookiePolicy(CookiePolicy.ACCEPT_ALL);
    }

if (CookieHandler.getDefault() != DEFAULT_COOKIE_MANAGER)
        {
            CookieHandler.setDefault(DEFAULT_COOKIE_MANAGER);
        }
```

But keep not working... any idea ? thanks

**Comment by marcbaechinger** [comment]
The server returns a HTTP 403 which means that the server has decided that the user is not authorised to get this resource. 

The server seems to discriminate against different user agents. There is not much you can do about it. You could try to use a user agent which is accepted by the server, but that's probably a bad advise because the server configuration can change again. 

I think you need another url or the server operator needs to allow requests from any client to access the resource. 

When using curl I get the same as what ExoPlayer is reporting:

```
curl --verbose https://e.mm.uol.com.br/band/radiobandeirantes_poa/playlist.m3u8
*   Trying 186.234.127.82...
* TCP_NODELAY set
* Connected to e.mm.uol.com.br (186.234.127.82) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.mm.uol.com.br
*  start date: Dec  5 00:00:00 2018 GMT
*  expire date: Feb  3 12:00:00 2020 GMT
*  subjectAltName: host "e.mm.uol.com.br" matched cert's "*.mm.uol.com.br"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=RapidSSL RSA CA 2018
*  SSL certificate verify ok.
> GET /band/radiobandeirantes_poa/playlist.m3u8 HTTP/1.1
> Host: e.mm.uol.com.br
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Server: nginx
< Date: Mon, 30 Dec 2019 11:58:58 GMT
< Content-Type: text/html
< Content-Length: 162
< Connection: keep-alive
```

When faking the user agent it works:

```
curl --verbose -A "Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1" https://e.mm.uol.com.br/band/radiobandeirantes_poa/playlist.m3u8
```

**Comment by alanperius** [comment]
Hi @marcbaechinger,
thanks for your answer! 

They changed recently his URL, so I don't have any other to use.  

I tried to simulate with your fake UserAgent and worked.. haha 
Stupid workaround.. but.. =)


Thanks
