### ISSUE TITLE
IncompatibleClassChangeError on AnalyticsCollector after SimpleExoPlayer.prepare

### ISSUE THREAD

**Issue by Mercandj** [google/ExoPlayer#6813]
Hello,

### Issue description

Crash on `SimpleExoPlayer.prepare(MediaSource)`

### Full bug report captured from the device

Crash on device :

```
2019-12-28 23:06:11.322 1342-1342/com.mercandalli.android.apps.audio_player_exo_sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mercandalli.android.apps.audio_player_exo_sample, PID: 1342
    java.lang.IncompatibleClassChangeError
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.onAudioSessionId(Unknown Source:2)
        at com.google.android.exoplayer2.SimpleExoPlayer$ComponentListener.onAudioSessionId(SimpleExoPlayer.java:1647)
        at com.google.android.exoplayer2.audio.AudioRendererEventListener$EventDispatcher.lambda$audioSessionId$5$AudioRendererEventListener$EventDispatcher(AudioRendererEventListener.java:170)
        at com.google.android.exoplayer2.audio.-$$Lambda$AudioRendererEventListener$EventDispatcher$a1B1YBHhPRCtc1MQAc2fSVEo22I.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

### Reproduction steps

- minSdkVersion to 19 (no crash with minSdkVersion 24)
- Java 8
- `SimpleExoPlayer.prepare(MediaSource)` (reproductible every time)

### Version of ExoPlayer being used

Crash since the version `2.11`:
- No crash on `2.10.8`
- Crash on `2.11`
- Crash on `2.11.1`

### Device(s) and version(s) of Android being used

Crash on API 29 stock Pixel 3 (not tested more configs).

### Code used

```groovy
android {

    // ...

    buildTypes {
        getByName("debug") {
            isMinifyEnabled = false
            isShrinkResources = false
        }
    }

    // https://developer.android.com/studio/write/java8-support
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
```

```kotlin
private val player: SimpleExoPlayer
private val dataSourceFactory: DefaultDataSourceFactory

init {
    // Measures bandwidth during playback. Can be null if not required.
    val bandwidthMeterA = DefaultBandwidthMeter.Builder(context).build()
    // Produces DataSource instances through which media data is loaded.
    dataSourceFactory = DefaultDataSourceFactory(
        context,
        Util.getUserAgent(context, "music"),
        bandwidthMeterA
    )

    val renderersFactory = DefaultRenderersFactory(context)
    player = SimpleExoPlayer.Builder(
        context,
        renderersFactory
    ).build()
    player.addListener(object : Player.EventListener {
        override fun onLoadingChanged(isLoading: Boolean) { }
        override fun onIsPlayingChanged(isPlaying: Boolean) { }
        override fun onPlayerStateChanged(
            playWhenReady: Boolean,
            playbackState: Int
        ) { }
    })
}

fun start(url: String) {

    // Produces Extractor instances for parsing the media data.
    val extractorsFactory = DefaultExtractorsFactory()

    // This is the MediaSource representing the media to be played:
    val mediaSource = ProgressiveMediaSource.Factory(
        dataSourceFactory,
        extractorsFactory
    ).createMediaSource(Uri.parse(url))

    // Prepare the player with the source.
    player.prepare(mediaSource) // /!\/!\/!\/!\ CRASH FROM HERE /!\/!\/!\/!\/!\
    player.playWhenReady = true
}
```

### Possible reasons:

- 1/ The use of lambda syntax `handler.post(() -> method());` [here](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/audio/AudioRendererEventListener.java#L170). Java8 seems to be [the reason](https://developer.android.com/studio/write/java8-support) as Java 8 Language API seems to be supported only on `API level 24 or higher`.
- 2/ I may be missing new proguard rule...
- 3/ Missing clean... or conflict with R8 or Jetifier... that may explain `IncompatibleClassChangeError` (I'm not doing any binary changes manually)
- ...

----

I may be missing something in my code... as it seems that I'm the only one to have this crash... 
I hope this issue is well formatted and not already known.

Thanks a lot for your great library 💪 !!!

----

Edited:
- Maybe related to https://github.com/google/ExoPlayer/issues/6807
- I'm using Android Studio 4.0 preview 06

**Comment by tonihei** [comment]
According to #6807, this problem only occurred in Android Studio 4.0 canary 6, and was fixed in canary 7. Can you confirm this is the case?

**Comment by Mercandj** [comment]
Indeed, no more crash on Android Studio 4.0 canary 7 with minSdk 19.
Thks!
(Sorry for the issue duplication, closing this MR)
