### ISSUE TITLE
Gradle build error when update from 1.3.3 to 1.4.1

### ISSUE THREAD

**Issue by ericcbm** [google/ExoPlayer#684]
Hello,

I'm having a gradle error when update exoplayer from 1.3.3 to 1.4.1.
I changed the dependencie from:
**compile 'com.google.android.exoplayer:exoplayer:r1.3.3'**
to:
**compile 'com.google.android.exoplayer:exoplayer:r1.4.1'**

Then, project sync works, but when I Run 'app', gradle shows this error:
```javascript
UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
        at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
        at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)
        at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)
    Error:Execution failed for task ':app:dexDebug'.
    > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_79\bin\java.exe'' finished with non-zero exit value 2
```
I already try Clean Project, Rebuild Project and Make Project, but no success. :(

Thanks.

**Comment by ojw28** [comment]
If you Google "DexIndexOverflowException" then you'll find a lot of information about this. It's not a problem specifically related to ExoPlayer. See: https://developer.android.com/tools/building/multidex.html

**Comment by ericcbm** [comment]
Thanks a lot!!
Sorry, next time i will search more hardly. ;) Thanks again!
