### ISSUE TITLE
Issue when streaming mkv

### ISSUE THREAD

**Issue by johangiroux** [google/ExoPlayer#687]
I have trouble playing mkv files, using ExoPlayer v1.4.2.
It's big distant mkv files I'm trying to open (avg 4gb).

It seems to be an issue on the AudioTrack.

Video Codec : V_MPEG4/ISO/AVC
Audio : A_AC3

Here is the stacktrace from the demo :

<pre><code>
08-04 15:26:35.307  17735-20305/com.google.android.exoplayer.demo E/AudioTrack﹕ Could not get audio output for stream type 3, usage 1, sample rate 48000, format 0x9000000, channel mask 0x3f, flags 0x1

08-04 15:26:35.311  17735-20305/com.google.android.exoplayer.demo E/AudioTrack-JNI﹕ Error -22 initializing AudioTrack
08-04 15:26:35.311  17735-20305/com.google.android.exoplayer.demo E/android.media.AudioTrack﹕ Error code -20 when initializing AudioTrack.
08-04 15:26:35.313  17735-17735/com.google.android.exoplayer.demo E/EventLogger﹕ internalError [7.29, audioTrackInitializationError]
    com.google.android.exoplayer.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 144000)
            at com.google.android.exoplayer.audio.AudioTrack.checkAudioTrackInitialized(AudioTrack.java:753)
            at com.google.android.exoplayer.audio.AudioTrack.initialize(AudioTrack.java:311)
            at com.google.android.exoplayer.audio.AudioTrack.initialize(AudioTrack.java:285)
            at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:273)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:858)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:499)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
08-04 15:26:35.313  17735-20305/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 144000)
            at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:278)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:858)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:499)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 144000)
            at com.google.android.exoplayer.audio.AudioTrack.checkAudioTrackInitialized(AudioTrack.java:753)
            at com.google.android.exoplayer.audio.AudioTrack.initialize(AudioTrack.java:311)
            at com.google.android.exoplayer.audio.AudioTrack.initialize(AudioTrack.java:285)
            at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:273)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:858)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:499)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
08-04 15:26:35.329  17735-17735/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [7.31]
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 144000)
            at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:278)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:858)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:499)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 144000)
            at com.google.android.exoplayer.audio.AudioTrack.checkAudioTrackInitialized(AudioTrack.java:753)
            at com.google.android.exoplayer.audio.AudioTrack.initialize(AudioTrack.java:311)
            at com.google.android.exoplayer.audio.AudioTrack.initialize(AudioTrack.java:285)
            at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:273)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:858)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:499)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
</code></pre>

ffmpeg -i on the file :

<pre><code>
built with llvm-gcc 4.2.1 (LLVM build 2336.11.00)
  configuration: --prefix=/Volumes/Ramdisk/sw --enable-gpl --enable-pthreads --enable-version3 --enable-libspeex --enable-libvpx --disable-decoder=libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libgsm --enable-libvidstab --enable-libx265 --disable-doc --arch=x86_64 --enable-runtime-cpudetect
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, matroska,webm, from 'Mad.Max.Fury.Road.2015.1080p.WEB-DL.DD5.1.H264-RARBG.mkv':
  Metadata:
    title           : Mad.Max.Fury.Road.2015.1080p.WEB-DL.DD5.1.H264-RARBG
    encoder         : libebml v1.3.1 + libmatroska v1.4.2
    creation_time   : 2015-06-22 10:40:17
  Duration: 02:00:21.18, start: 0.000000, bitrate: 4830 kb/s
    Chapter #0:0: start 0.000000, end 642.000000
    Metadata:
      title           : 1
    Chapter #0:1: start 642.000000, end 1146.000000
    Metadata:
      title           : 2
    Chapter #0:2: start 1146.000000, end 1813.000000
    Metadata:
      title           : 3
    Chapter #0:3: start 1813.000000, end 2575.000000
    Metadata:
      title           : 4
    Chapter #0:4: start 2575.000000, end 2973.000000
    Metadata:
      title           : 5
    Chapter #0:5: start 2973.000000, end 3595.000000
    Metadata:
      title           : 6
    Chapter #0:6: start 3595.000000, end 4382.000000
    Metadata:
      title           : 7
    Chapter #0:7: start 4382.000000, end 4928.000000
    Metadata:
      title           : 8
    Chapter #0:8: start 4928.000000, end 5402.000000
    Metadata:
      title           : 9
    Chapter #0:9: start 5402.000000, end 6039.000000
    Metadata:
      title           : 10
    Chapter #0:10: start 6039.000000, end 6552.000000
    Metadata:
      title           : 11
    Chapter #0:11: start 6552.000000, end 6785.000000
    Metadata:
      title           : 12
    Chapter #0:12: start 6785.000000, end 7221.184000
    Metadata:
      title           : 13
    Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709), 1912x792 [SAR 1:1 DAR 239:99], 23.98 fps, 23.98 tbr, 1k tbn, 2k tbc (default)
    Metadata:
      title           : Mad.Max.Fury.Road.2015.1080p.WEB-DL.DD5.1.H264-RARBG
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Metadata:
      title           : Mad.Max.Fury.Road.2015.1080p.WEB-DL.DD5.1.H264-RARBG
    Stream #0:2(eng): Subtitle: subrip (default)
    Stream #0:3: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 120x176, 90k tbr, 90k tbn, 90k tbc
    Metadata:
      filename        : small_cover.jpg
      mimetype        : image/jpeg
    Stream #0:4: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 213x120, 90k tbr, 90k tbn, 90k tbc
    Metadata:
      filename        : small_cover_land.jpg
      mimetype        : image/jpeg
    Stream #0:5: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 600x882, 90k tbr, 90k tbn, 90k tbc
    Metadata:
      filename        : cover.jpg
      mimetype        : image/jpeg
    Stream #0:6: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 1067x600, 90k tbr, 90k tbn, 90k tbc
    Metadata:
      filename        : cover_land.jpg
      mimetype        : image/jpeg
</code></pre>

**Comment by ojw28** [comment]
Most Android devices don't support AC3. What device are you attempting playback on?

@andrewlewis - Should we be failing in this way? I would have thought we should just be ignoring the track?

**Comment by andrewlewis** [comment]
For ExtractorSampleSource we don't currently filter out AC-3 tracks based on AudioCapabilities, so this is failing when it tries to set up the AudioTrack for encoded audio passthrough.

After the planned change to check AudioCapabilities in the track renderer, this will either work correctly (if the device has an AC-3 codec) or fail with a decoder query exception (if it doesn't).

**Comment by johangiroux** [comment]
Thank you for your answer, I tried to play on ADT-1, and indeed it's not supported.

**Comment by andrewlewis** [comment]
AC-3 in matroska files should work correctly since b2206866f0eecc52af53681ec340f61ba7d38d2a. Playback is either via HDMI passthrough (if a receiver is connected; note that this feature is buggy on the ADT-1 development device) or with decoding on the device (if the required codec is present). In other cases, playback will fail when trying to create a decoder.
