### ISSUE TITLE
Player throws exception while playing invalid last segment of a HLS file

### ISSUE THREAD

**Issue by shubhamvashisht** [google/ExoPlayer#6895]
### [REQUIRED] Issue description 
Player throws Exception while playing last segment of a hls file when the last segment is of less than 1 second duration.

### [REQUIRED] Reproduction steps
Play the below files and it should throw exception in the last segment

### [REQUIRED] Link to test content
master playlist : https://dbj64m8271a9g.cloudfront.net/60bdc7bf12206fa133e2e65099e9bec611cada30.m3u8

playlist : 
https://dbj64m8271a9g.cloudfront.net/60bdc7bf12206fa133e2e65099e9bec611cada30-variant.m3u8

### [REQUIRED] A full bug report captured from the device
```
2020-01-20 20:04:37.916 24513-25224 E/ ACodec: [OMX.google.mp3.decoder] ERROR(0x80001001)
2020-01-20 20:04:37.916 24513-25224/  E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
2020-01-20 20:04:37.917 24513-25224/ E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
2020-01-20 20:04:37.932 24513-24886/ E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1437)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:653)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2020-01-20 20:04:37.941 24513-24886/ E/ExoPlayerImplInternal: Disable failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2131)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:702)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:580)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onDisabled(MediaCodecAudioRenderer.java:625)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:158)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1088)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:851)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:399)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2020-01-20 20:04:37.957 24513-24886/ E/ExoPlayerImplInternal: Reset failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2084)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:609)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onReset(MediaCodecRenderer.java:587)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onReset(MediaCodecAudioRenderer.java:635)
        at com.google.android.exoplayer2.BaseRenderer.reset(BaseRenderer.java:164)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:860)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:399)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2020-01-20 20:04:37.964 24513-24513/ E/9ba90f2a42daf1ac719cf0c7dea8a8beaa9e1ecf: unexpected type error exoplayer
2020-01-20 20:05:05.703 24513-24886/ E/AudioTrack: Discontinuity detected [expected 294005718, got 300013876]
2020-01-20 20:05:06.022 24513-25236/ E/ACodec: [OMX.google.mp3.decoder] ERROR(0x80001001)
2020-01-20 20:05:06.022 24513-25236/ E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
2020-01-20 20:05:06.022 24513-25236/ E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
2020-01-20 20:05:06.063 24513-24886/ E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.releaseOutputBuffer(Native Method)
        at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:2743)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:733)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1507)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:653)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2020-01-20 20:05:06.069 24513-24886/ E/ExoPlayerImplInternal: Disable failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2131)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:702)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:580)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onDisabled(MediaCodecAudioRenderer.java:625)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:158)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1088)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:851)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:399)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2020-01-20 20:05:06.073 24513-24513/ E/9ba90f2a42daf1ac719cf0c7dea8a8beaa9e1ecf: unexpected type error exoplayer
2020-01-20 20:05:06.085 24513-24886/ E/ExoPlayerImplInternal: Reset failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2084)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:609)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onReset(MediaCodecRenderer.java:587)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onReset(MediaCodecAudioRenderer.java:635)
        at com.google.android.exoplayer2.BaseRenderer.reset(BaseRenderer.java:164)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:860)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:399)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

### [REQUIRED] Version of ExoPlayer being used
2.10.4

### [REQUIRED] Device(s) and version(s) of Android being used
Specify the devices and versions of Android on which the issue can be
reproduced, and how easily it reproduces. If possible, please test on multiple
devices and Android versions.

Devices :  Redmi 7A, OnePlus 6

**Comment by icbaker** [comment]
I can repro with your provided HLS stream in the demo app.

I can also repro with just the final chunk:

```shell
$ adb shell am start -a com.google.android.exoplayer.demo.action.VIEW \
   -d https://dbj64m8271a9g.cloudfront.net/60bdc7bf12206fa133e2e65099e9bec611cada30/60bdc7bf12206fa133e2e65099e9bec611cada30-0049.ts
```

How was this final chunk generated? It seems to be broken in various ways - Both ExoPlayer and VLC think it has 00:00 duration (whereas they both understand that the penultimate chunk has duration 00:05). ExoPlayer produces some audio before crashing when playing it back, while VLC doesn't play it back at all (both happily play back the penultimate chunk).

I don't think this is related to HLS, but is something wrong with this piece of media.

**Comment by shubhamvashisht** [comment]
@icbaker Thank you for your response. I created the chunks using FFMPEG
part of python script used to create playlist
``` result = subprocess.Popen(['ffmpeg -y -i {} -map 0:a -codec copy -hls_time {}  -hls_allow_cache 1 -start_number 0 -master_pl_name {}.m3u8 -hls_list_size 0 -hls_base_url {} -hls_segment_filename {}-%04d.ts {}-variant.m3u8'.format(pathToDownloadedMediaFile, 6, mediaFileName, mediaFileName+"/", mediaFileName, mediaFileName)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True)```

6 seconds segments

**Comment by icbaker** [comment]
I think your final segment (49) is not a valid MPEG-TS file.

When I convert it to MP3 with ffmpeg it complains that there's a header missing (segment 48 does not complain):

```
$ ffmpeg -i ~/Downloads/segment-49.ts ~/Downloads/segment-49.mp3
...
[mp3float @ 0x55d728532b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 0x55d728532b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
``` 

Additionally when viewing the last segment in a hex viewer[1], there seems to be a LAME header in the middle of the byte stream towards the end which is unexpected, as well as a significant amount of repeated data. These bytes appear twice:
`24 64 6C BF 26 89 68 98 93 86 18 C4 D5 49 25 F1 CC 4D 18 52 54 C8 7B 2D 6C A5 3F E5 27 24 4F
1C 1E C7 FF FF 3A 30 A5 88 12 46 6E 88 FD FF FF A2 91 D4 A3 B9 16 26 99 25 FF FF F9 92 28 98 A4 91 92 28 97 52 48 92 05 7F FF 84 81 A1 28 48 1A 12 9D 4C 41 4D 45 33 2E 31 30 30`

And the second occurrence of these is preceded by some `FF` padding, which if you ignore you get more duplication:
`C5 24 8C 91 44 C5 24 8C 91 47 FF FF FF F3 14 92 32 45 13 14 92 32 45 13 15 C0 E1 60 A8 70 38 1C 11 0A 06 02 80 C0 4A A2 43 80 68 25 AF F3 00 DE 10 22 C0 13 FF 01 05 7E A5 03 CD FE 1B 40 51 86 30 F2 C4 A8 40 41 5D 31 31 35 E3 02 3B 84 68 79`

The stack trace in your original post shows that MediaCodec is upset about something, and when I play back segment 49 directly in ExoPlayer demo app there's a log line higher up that suggests it's crashing while decoding the MP3:
```
E/C2SoftMp3Dec: mp3 decoder returned error 13
```

So the stack trace you've included is just a symptom of an earlier MediaCodec crash, probably caused by the invalid media.

It seems like either:
1. The media you're inputting to the ffmpeg HLS segmenting command is invalid (where did it come from?)
2. Something's wrong with your ffmpeg HLS segmenting command
3. There's a bug in your ffmpeg's version of HLS segmenting 

You might like to try playing the original media in ExoPlayer and confirming there are no issues (to investigate (1)).

You could also try updating your ffmpeg version and re-running the segmenting to see if something has changed in their HLS implementation. 


[1]
```
$ hexdump -C ~/Downloads/last-segment.ts 
...
000023b0  f6 5f ff 09 30 17 c6 46  d8 4e 84 d4 16 95 ad 1e  |._..0..F.N......|
000023c0  26 27 06 18 4c 94 a4 97  e3 e8 8c 8e 53 21 ec b4  |&'..L.......S!..|
000023d0  54 a7 f8 e6 31 1c 24 aa  8b df fe 6e 74 61 4a 2a  |T...1.$....ntaJ*|
000023e0  24 8f ff fe 74 7a 9a 28  bc 56 ec 49 7f ff e8 c9  |$...tz.(.V.I....|
000023f0  a9 49 c8 ac 91 49 2f ff  ff cc 91 44 47 01 00 11  |.I...I/....DG...|
00002400  c5 24 8c 91 44 c5 24 8c  91 47 ff ff ff f3 14 92  |.$..D.$..G......|
00002410  32 45 13 14 92 32 45 13  15 c0 e1 60 a8 70 38 1c  |2E...2E....`.p8.|
00002420  11 0a 06 02 80 c0 4a a2  43 80 68 25 af f3 00 de  |......J.C.h%....|
00002430  10 22 c0 13 ff 01 05 7e  a5 03 cd fe 1b 40 51 86  |.".....~.....@Q.|
00002440  30 f2 c4 a8 40 41 5d 31  31 35 e3 02 3b 84 68 79  |0...@A]115..;.hy|
00002450  24 64 6c bf 26 89 68 98  93 86 18 c4 d5 49 25 f1  |$dl.&.h......I%.|
00002460  cc 4d 18 52 54 c8 7b 2d  6c a5 3f e5 27 24 4f 1c  |.M.RT.{-l.?.'$O.|
00002470  1e c7 ff ff 3a 30 a5 88  12 46 6e 88 fd ff ff a2  |....:0...Fn.....|
00002480  91 d4 a3 b9 16 26 99 25  ff ff f9 92 28 98 a4 91  |.....&.%....(...|
00002490  92 28 97 52 48 92 05 7f  ff 84 81 a1 28 48 1a 12  |.(.RH.......(H..|
000024a0  9d 4c 41 4d 45 33 2e 31  30 30 55 55 55 55 55 55  |.LAME3.100UUUUUU|
000024b0  55 55 55 55 55 55 55 55  47 01 00 12 55 55 55 55  |UUUUUUUUG...UUUU|
000024c0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
*
00002570  55 55 55 55 47 01 00 13  55 55 55 55 55 55 55 55  |UUUUG...UUUUUUUU|
00002580  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
*
000025f0  55 8e db a9 a3 10 75 14  dd 87 ff f7 ff ff ff ff  |U.....u.........|
00002600  ff ff f9 ff ff ff ff ff  ff ef db 5c 6b 91 46 be  |...........\k.F.|
00002610  e5 c5 da e3 91 14 72 dd  f8 bb 90 ee 7f ff ff ff  |......r.........|
00002620  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00002630  47 01 00 14 ff ff ff ff  ff ff ff ff d8 a7 a7 b7  |G...............|
00002640  49 49 62 9e 9f 3a 4a 4e  00 00 05 48 92 4e c9 74  |IIb..:JN...H.N.t|
00002650  91 ef 6e 6d b0 21 b3 8a  8f 07 18 58 a1 b5 12 9b  |..nm.!.....X....|
00002660  b1 91 a1 98 9e c1 a2 b2  98 2b 49 8d 08 19 a3 71  |.........+I....q|
00002670  a2 94 82 9c 4c 44 40 c4  85 01 a3 83 55 46 1a 30  |....LD@.....UF.0|
00002680  12 01 40 25 6d 24 b8 1e  c5 20 ac 69 a6 fd a6 b2  |..@%m$... .i....|
00002690  c2 3a c6 30 40 37 c2 e0  eb 05 d8 b8 52 f1 c8 64  |.:.0@7......R..d|
000026a0  c5 bb 0c 4c e4 00 c8 00  00 22 c2 5a 7c a2 91 54  |...L.....".Z|..T|
000026b0  d2 86 ff fb d0 44 d0 00  09 b1 88 ce fe 6f 60 01  |.....D.......o`.|
000026c0  31 b1 19 ed cd e4 00 10  d9 b3 3b f9 86 82 02 22  |1.........;...."|
000026d0  2b 28 b7 30 d0 80 d9 b3  b2 d0 cd 31 4d 31 42 07  |+(.0.......1M1B.|
000026e0  01 38 08 21 f0 b5 48 f5  ea 3a dc 5f 47 01 00 15  |.8.!..H..:._G...|
000026f0  9a 19 a7 ba 32 a6 85 a3  48 75 07 2e c2 60 3a 11  |....2...Hu...`:.|
00002700  c7 c6 95 e1 bf 1d 76 9f  a7 f9 f9 7f 9e 47 d4 68  |......v......G.h|
00002710  00 11 e6 48 a5 db 32 84  2c 82 14 4b f2 fe c3 38  |...H..2.,..K...8|
00002720  d7 bd 7a 7a 3b 0f c6 ec  44 21 ba de 8f ea 0e d3  |..zz;...D!......|
00002730  d4 11 62 34 c5 07 61 ee  3f e1 dd 7e b0 e7 77 bc  |..b4..a.?..~..w.|
00002740  3b 7f fb f6 b1 e7 ed 52  2c 47 11 75 b1 37 5d 62  |;......R,G.u.7]b|
00002750  2e c7 11 89 b3 bf fe ff  ff ff ff ff ff ff 3f ff  |..............?.|
00002760  ff ff ff ff fd b7 4c 05  48 d3 14 1d 63 ba ea 08  |......L.H...c...|
00002770  bb 1d 45 4e bb dd 75 88  bb 3f ff ff ff ff ff ff  |..EN..u..?......|
00002780  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00002790  ff ff ff ff ff ec 4b e9  ed d2 52 58 a7 a7 b7 49  |......K...RX...I|
000027a0  49 78 a4 02 00 18 05 80  47 01 00 16 94 05 41 50  |Ix......G.....AP|
000027b0  80 80 40 18 04 00 a9 85  56 63 d1 45 ff cb 5a 82  |..@.....Vc.E..Z.|
000027c0  14 55 0b 07 fc 04 96 4a  f6 5f ff 09 30 17 c6 46  |.U.....J._..0..F|
000027d0  d8 4e 84 d4 16 95 ad 1e  26 27 06 18 4c 94 a4 97  |.N......&'..L...|
000027e0  e3 e8 8c 8e 53 21 ec b4  54 a7 f8 e6 31 1c 24 aa  |....S!..T...1.$.|
000027f0  8b df fe 6e 74 61 4a 2a  24 8f ff fe 74 7a 9a 28  |...ntaJ*$...tz.(|
00002800  bc 56 ec 49 7f ff e8 c9  a9 49 c8 ac 91 49 2f ff  |.V.I.....I...I/.|
00002810  ff cc 91 44 c5 24 8c 91  44 c5 24 8c 91 47 ff ff  |...D.$..D.$..G..|
00002820  ff f3 14 92 32 45 13 14  92 32 45 13 15 c0 e1 60  |....2E...2E....`|
00002830  a8 70 38 1c 11 0a 06 02  80 c0 4a a2 43 80 68 25  |.p8.......J.C.h%|
00002840  af f3 00 de 10 22 c0 13  ff 01 05 7e a5 03 cd fe  |.....".....~....|
00002850  1b 40 51 86 30 f2 c4 a8  40 41 5d 31 31 35 e3 02  |.@Q.0...@A]115..|
00002860  3b 84 68 79 47 01 00 37  1e 00 ff ff ff ff ff ff  |;.hyG..7........|
00002870  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00002880  ff ff ff ff ff ff ff 24  64 6c bf 26 89 68 98 93  |.......$dl.&.h..|
00002890  86 18 c4 d5 49 25 f1 cc  4d 18 52 54 c8 7b 2d 6c  |....I%..M.RT.{-l|
000028a0  a5 3f e5 27 24 4f 1c 1e  c7 ff ff 3a 30 a5 88 12  |.?.'$O.....:0...|
000028b0  46 6e 88 fd ff ff a2 91  d4 a3 b9 16 26 99 25 ff  |Fn..........&.%.|
000028c0  ff f9 92 28 98 a4 91 92  28 97 52 48 92 05 7f ff  |...(....(.RH....|
000028d0  84 81 a1 28 48 1a 12 9d  4c 41 4d 45 33 2e 31 30  |...(H...LAME3.10|
000028e0  30 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |0UUUUUUUUUUUUUUU|
000028f0  55 55 55 55 55 55 55 55  55 55 55 55 55 55 55 55  |UUUUUUUUUUUUUUUU|
```

**Comment by shubhamvashisht** [comment]
Hi @icbaker, Thank you for the detailed breakdown of the problem. You are right about the corrupted media source file (.mp3). I tried converting it to some other format and ffmpeg also had problem reading some bytes at the end of file. However VLC and Exoplayer both are able to playing the source file (mp3) just fine.
