### ISSUE TITLE
IllegalStateException for MPEG-TS when FLAG_DETECT_ACCESS_UNITS is used

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#6910]
### [REQUIRED] Issue description

Playback of MPEG-TS fails with assertion when `FLAG_DETECT_ACCESS_UNITS` is used.
Video plays well in vlc/mplayer.

### [REQUIRED] Reproduction steps
Start demo app with provided asset and `FLAG_DETECT_ACCESS_UNITS` enabled.
* https://github.com/stari4ek/ExoPlayer/tree/tvirl/issues/1785

```
2020-01-25 11:55:17.189 29823-29823/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=0.46, mediaPos=0.00, window=0, period=0]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:463)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:413)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkStateNotNull(Assertions.java:111)
        at com.google.android.exoplayer2.extractor.ts.H264Reader$SampleReader$SliceHeaderData.isFirstVclNalUnitOfPicture(H264Reader.java:570)
        at com.google.android.exoplayer2.extractor.ts.H264Reader$SampleReader$SliceHeaderData.access$100(H264Reader.java:492)
        at com.google.android.exoplayer2.extractor.ts.H264Reader$SampleReader.endNalUnit(H264Reader.java:467)
        at com.google.android.exoplayer2.extractor.ts.H264Reader.endNalUnit(H264Reader.java:244)
        at com.google.android.exoplayer2.extractor.ts.H264Reader.consume(H264Reader.java:158)
        at com.google.android.exoplayer2.extractor.ts.PesReader.consume(PesReader.java:142)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:339)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:982)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

Removing `FLAG_DETECT_ACCESS_UNITS` solves the issue.
Replacing asserts with:
```java
private boolean isFirstVclNalUnitOfPicture(SliceHeaderData other) {
  if (this.spsData == null || other.spsData == null) {
    return true; 
    // return false;
  }
  // See ISO 14496-10 subsection 7.4.1.2.4.
  // SpsData spsData = Assertions.checkStateNotNull(this.spsData);
  // SpsData otherSpsData = Assertions.checkStateNotNull(other.spsData);
```
workarounds the issue. Video plays well with both (true/false) variants.

### [REQUIRED] Link to test content
* https://drive.google.com/file/d/1p5p7AdQcovzjLyGY4YEvG3kmeBJ_cGH0/view?usp=sharing
* https://github.com/stari4ek/ExoPlayer/blob/tvirl/issues/1785/demos/main/src/main/assets/raw.ts

### [REQUIRED] A full bug report captured from the device
this issue is not device-specific.

### [REQUIRED] Version of ExoPlayer being used
* `Init de34133 [ExoPlayerLib/2.11.2] [foster, SHIELD Android TV, NVIDIA, 28]`
* 9a9ef4397697f52f4262a60d02132814187cdd55

### [REQUIRED] Device(s) and version(s) of Android being used
* reproduced 100% of the time
* Tested on nvidia shield, API 28

**Comment by ojw28** [comment]
Thanks for reporting this! The issue is not present in any release, but is present in `dev-v2` and `dev-v2-r2.11.2`. We'll submit a fix before 2.11.2 is released.

**Comment by ojw28** [comment]
Actually, the issue is not present in `dev-v2-r2.11.2` either. It looks like you were using `dev-v2`. The change above should fix it there.

**Comment by stari4ek** [comment]
Yes, I was using dev-v2 on 9a9ef4397697f52f4262a60d02132814187cdd55

Thank you
