### ISSUE TITLE
App crashes when trying to play an AAC stream

### ISSUE THREAD

**Issue by dreich** [google/ExoPlayer#6927]
To be fast I'm starting from a question. If it'll be needed I'd provide more information for a bug report.
I'm not sure if ExoPlayer should play this AAC stream: http://stream.grad-petrov.ru:8093/aac.m3u.

It's bad that my app crashes at starting playing the stream and I can't catch it.
Version of ExoPlayer is 2.11.1.
If it's something wrong with the stream, then it's ok.

```
2020-01-29 12:38:38.780 5459-5527/ru.pravradost.andrey E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1095)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:974)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-01-29 12:38:42.587 5459-5527/ru.pravradost.andrey E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:961)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-01-29 12:38:42.600 5459-5459/ru.pravradost.andrey E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.pravradost.andrey, PID: 5459
    java.lang.NullPointerException: Attempt to read from field 'java.lang.Object android.util.Pair.first' on a null object reference
        at com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector.invalidateMediaSessionPlaybackState(MediaSessionConnector.java:779)
        at com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector$ComponentListener.onPlayerStateChanged(MediaSessionConnector.java:1132)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$5$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:828)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$AYkTJomZb3BnUDA59u8cvRVoKcM.invokeListener(Unknown Source:2)
        at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
        at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
        at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:826)
        at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
        at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
        at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
        at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by ojw28** [comment]
> I'm not sure if ExoPlayer should play this AAC stream: http://stream.grad-petrov.ru:8093/aac.m3u.

It's not an AAC stream. It's an M3U file that contains a single link `http://stream.grad-petrov.ru:8093/aac`. You can download the file and open it in a text editor to see this. Note that Chrome will also just download the file, rather than play it.

We don't yet support parsing M3U files (it's tracked by https://github.com/google/ExoPlayer/issues/4066), so you'll need to do this yourself and give ExoPlayer the real stream link that it contains. `http://stream.grad-petrov.ru:8093/aac` plays fine in the ExoPlayer demo app.

Note that the playback failure does not result in your app crashing. Your app is crashing due to:

```
2020-01-29 12:38:42.600 5459-5459/ru.pravradost.andrey E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.pravradost.andrey, PID: 5459
    java.lang.NullPointerException: Attempt to read from field 'java.lang.Object android.util.Pair.first' on a null object reference
        at com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector.invalidateMediaSessionPlaybackState(MediaSessionConnector.java:779)
 ```

It's fairly easy for you to work this our yourself by [looking at the line of code](https://github.com/google/ExoPlayer/blob/r2.11.1/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L779). You must be passing an `ErrorMessageProvider` implementation to the `MediaSessionConnector` that's returning `null` from `getErrorMessage`. This is not a valid implementation; you always need to return a `Pair`. You need to fix your `ErrorMessageProvider` to be a valid implementation.

**Comment by dreich** [comment]
Thank you very much!
