### ISSUE TITLE
Is there an example of adding local subtitles?

### ISSUE THREAD

**Issue by sigusigu** [google/ExoPlayer#6940]
### [REQUIRED] Question
Is there an example of loading a local subtitle file stored on a device rather than a web address?
I added a subtitle file via url.
But it doesn't load subtitle files that are local to the device.
I would appreciate a hint.

### A full bug report captured from the device
I tried but not working
```
var srtFile = File("local file path")
var subtitleSource = SingleSampleMediaSource.Factory(manifestDataSourceFactory)
                .createMediaSource(Uri.fromFile(srtFile),
                        Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP, Format.NO_VALUE, "en", null), C.TIME_UNSET)
return MergingMediaSource(ExtractorMediaSource.Factory(manifestDataSourceFactory).createMediaSource(uri), subtitleSource)
```
=================================================================

Unexpected exception loading stream
```
    java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:496)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:436)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SourceLoadable.load(SingleSampleMediaPeriod.java:389)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```
### Link to test content

**Comment by ojw28** [comment]
Please take a look at [the documentation](https://exoplayer.dev/media-sources.html#side-loading-a-subtitle-file), which provides an example.

Given the `ClassCastException` that you're seeing, I think it's likely that `manifestDataSourceFactory` in your code is an instance of `DefaultHttpDataSourceFactory`. If you need to load media from other (non-http) locations as well, you should be using a `DefaultDataSourceFactory` instead. I suspect making this change will fix your problem. As an aside, you should probably rename your variable to just `dataSourceFactory`, since you're not loading any manifests.

**Comment by sigusigu** [comment]
Thank you for your advice And I succeeded
