### ISSUE TITLE
PsExtractor - Private streams shouldn't be assumed to be AC3

### ISSUE THREAD

**Issue by master255** [google/ExoPlayer#6956]
I'll use Exoplayer 2.11.1 and it:
```
@Override
            public void onPlayerError(ExoPlaybackException error) {
            }
```
But the event is not triggered when the next track is called:
mMediaPlayer.prepare(progressiveSource.createMediaSource("http://master255.org/res/%d0%9a%d0%bb%d0%b8%d0%bf%d1%8b/B/Billy%20Mack/Billy%20Mack%20-%20Christmas%20Is%20All%20Around.mpg"));
Track: http://master255.org/res/%d0%9a%d0%bb%d0%b8%d0%bf%d1%8b/B/Billy%20Mack/Billy%20Mack%20-%20Christmas%20Is%20All%20Around.mpg

**Comment by AquilesCanta** [comment]
It's possible the device doesn't offer support to decode the content. Look for something like this in the logcat.

```
tracks [eventTime=2.15, mediaPos=0.00, window=0, period=0, 
  Renderer:0 [
    Group:0, adaptive_supported=N/A [
      [ ] Track:0, id=224, mimeType=video/mpeg2, res=720x576, supported=NO_UNSUPPORTED_TYPE
    ]
  ]
  Renderer:3 [
    Group:0, adaptive_supported=N/A [
      [ ] Track:0, id=189, mimeType=audio/eac3, channels=4, sample_rate=48000, supported=NO_UNSUPPORTED_TYPE
    ]
  ]
]
```

If you can find it, that means the device does not support the stream's compression formats. In order to play the audio, you can use the ffmpeg extension. I can't provide further assistance regarding the video, unfortunately. Please see #2069 for more info.

If you don't think this is the issue you are hitting, please provide a bugreport, which you can obtain by running `adb bugreport` shortly after attempting playback.

**Comment by master255** [comment]
@AquilesCanta 
My device: Samsung Galaxy S8+
Whole LogCat on start this track:
```
2020-02-11 01:28:48.432 24177-25493/com.media.library I/ACodec: [OMX.google.raw.decoder] signalFlush
2020-02-11 01:28:48.432 24177-25493/com.media.library I/ACodec: [OMX.google.raw.decoder] ExecutingState flushing now (codec owns 4/4 input, 0/4 output).
2020-02-11 01:28:48.433 24177-25504/com.media.library D/AudioTrack: stop() called with 0 frames delivered
2020-02-11 01:28:48.433 24177-25493/com.media.library I/ACodec: [OMX.google.raw.decoder] Now Flushing
2020-02-11 01:28:48.434 24177-25493/com.media.library I/ACodec: [OMX.google.raw.decoder] FlushingState onOMXEvent(0,1,0)
2020-02-11 01:28:48.434 24177-25493/com.media.library I/ACodec: [OMX.google.raw.decoder] FlushingState onOMXEvent(0,1,1)
2020-02-11 01:28:48.434 24177-25493/com.media.library I/ACodec: [OMX.google.raw.decoder] Now Executing
2020-02-11 01:28:48.446 24177-25505/com.media.library I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2020-02-11 01:28:48.446 24177-25505/com.media.library I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2020-02-11 01:28:48.481 24177-25490/com.media.library V/FLACParser: FLACParser::~FLACParser
2020-02-11 01:28:48.740 24177-25503/com.media.library W/System.err: java.net.SocketException: Connection reset
2020-02-11 01:28:48.740 24177-25503/com.media.library W/System.err:     at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
2020-02-11 01:28:48.740 24177-25503/com.media.library W/System.err:     at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
2020-02-11 01:28:48.740 24177-25503/com.media.library W/System.err:     at com.media.library.proxy.PlayerThread.run(PlayerThread.java:359)
2020-02-11 01:28:48.743 24177-25505/com.media.library I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2020-02-11 01:28:48.743 24177-25505/com.media.library I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2020-02-11 01:28:48.767 24177-25505/com.media.library I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2020-02-11 01:28:48.769 24177-25505/com.media.library I/chatty: uid=10596(u0_a596) Loader:Progress identical 2 lines
2020-02-11 01:28:48.769 24177-25505/com.media.library I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
```

**Comment by master255** [comment]
@AquilesCanta , And open the bug! It is, and it is not fixed.

**Comment by AquilesCanta** [comment]
I need a whole bugreport.

**Comment by master255** [comment]
@AquilesCanta it's a whole bugreport. Adb doesn't return anything else.

**Comment by AquilesCanta** [comment]
What adb command are you running?

**Comment by master255** [comment]
@AquilesCanta
init:
`public void initPlayer() {
        if (mMediaPlayer == null) {
            TrackSelection.Factory trackSelectionFactory = new AdaptiveTrackSelection.Factory();
            renderersFactory = new DefaultRenderersFactory(ctx).setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON);
            DefaultLoadControl defaultLoadControl = new DefaultLoadControl.Builder()
                    .setPrioritizeTimeOverSizeThresholds(false)
                    .createDefaultLoadControl();
            trackSelector = new DefaultTrackSelector(ctx, trackSelectionFactory);
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP)
                audioSessionId = ((AudioManager) ctx.getSystemService(Context.AUDIO_SERVICE)).generateAudioSessionId();
            else audioSessionId = new android.media.MediaPlayer().getAudioSessionId();
            DefaultTrackSelector.ParametersBuilder builder = new DefaultTrackSelector.ParametersBuilder(ctx);
            builder.setTunnelingAudioSessionId(audioSessionId);
            trackSelector.setParameters(builder);
            mMediaPlayer = new SimpleExoPlayer.Builder(ctx, renderersFactory, trackSelector, defaultLoadControl, DefaultBandwidthMeter.getSingletonInstance(ctx), Util.getLooper(), new AnalyticsCollector(Clock.DEFAULT), true, Clock.DEFAULT).build();
            dataSourceFactory = new DefaultDataSourceFactory(ctx, "MediaLibrary");
            progressiveSource = new ProgressiveMediaSource.Factory(dataSourceFactory);
            hlsSource = new HlsMediaSource.Factory(dataSourceFactory);
            hlsSource.setAllowChunklessPreparation(true);
            mMediaPlayer.getVideoComponent().clearVideoSurfaceView(this);
            mMediaPlayer.getVideoComponent().setVideoSurfaceView(this);
            mMediaPlayer.setForegroundMode(true);
            setListeners();
        }`

after:
 mMediaPlayer.prepare(progressiveSource.createMediaSource(Uri.parse(path)));

**Comment by AquilesCanta** [comment]
Deleted comment as off-topic. I don't need the code, I need the adb command you are running, please.

**Comment by master255** [comment]
@AquilesCanta  command for what? 
I'm using a logcat in the android studio.
I don't use logcat commands.

**Comment by master255** [comment]
@AquilesCanta 
Maybe I got you wrong. Or did you misunderstand me?
Let's take it in order.
ExoPlayer doesn't support the [file ](http://master255.org/res/%d0%9a%d0%bb%d0%b8%d0%bf%d1%8b/B/Billy%20Mack/Billy%20Mack%20-%20Christmas%20Is%20All%20Around.mpg)codec.
However, it must produce an error on this line:
```
            @Override
            public void onPlayerError(ExoPlaybackException error) {
                mErrorListener.onError(error.getCause());
            }
```

But the error does not appear.
What does logcat have to do with it? If there was something in it, I could use it somehow, but it's clean! That's the problem. No errors, no logs, just eternal progress, and endlessly.

**Comment by master255** [comment]
And there is no code formatting in GitHub comments.

**Comment by AquilesCanta** [comment]
Please provide a bugreport by running `adb bugreport` shortly after playing the stream.

**Comment by master255** [comment]
@AquilesCanta 
[bugreport-2020-02-11-22-40-48.zip](https://github.com/google/ExoPlayer/files/4187941/bugreport-2020-02-11-22-40-48.zip)

**Comment by master255** [comment]
@AquilesCanta what next?

**Comment by AquilesCanta** [comment]
Please capture the bug report after playing the content in the demo app.

**Comment by master255** [comment]
@AquilesCanta Google has no money to buy a Galaxy S8+ for its programmers?
Okay. I have such errors in my demo application:
```

2020-02-11 23:45:53.180 15855-16461/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Renderer error: index=6, type=audio, format=Format(189, null, null, audio/ac3, null, -1, null, [-1, -1, -1.0], [3, 48000]), rendererSupport=YES
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$ConfigurationException: Unsupported channel count: 0
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.render(SimpleDecoderAudioRenderer.java:304)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Unknown Source:14)
        at android.os.Looper.loop(Unknown Source:139)
        at android.os.HandlerThread.run(Unknown Source:28)
     Caused by: com.google.android.exoplayer2.audio.AudioSink$ConfigurationException: Unsupported channel count: 0
        at com.google.android.exoplayer2.audio.DefaultAudioSink.configure(DefaultAudioSink.java:459)
        at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.drainOutputBuffer(SimpleDecoderAudioRenderer.java:406)
        at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.render(SimpleDecoderAudioRenderer.java:299)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Unknown Source:14) 
        at android.os.Looper.loop(Unknown Source:139) 
        at android.os.HandlerThread.run(Unknown Source:28) 

2020-02-11 23:45:53.197 15855-15855/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=0.79, mediaPos=2.41, window=0, period=0]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$ConfigurationException: Unsupported channel count: 0
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.render(SimpleDecoderAudioRenderer.java:304)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Unknown Source:14)
        at android.os.Looper.loop(Unknown Source:139)
        at android.os.HandlerThread.run(Unknown Source:28)
     Caused by: com.google.android.exoplayer2.audio.AudioSink$ConfigurationException: Unsupported channel count: 0
        at com.google.android.exoplayer2.audio.DefaultAudioSink.configure(DefaultAudioSink.java:459)
        at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.drainOutputBuffer(SimpleDecoderAudioRenderer.java:406)
        at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.render(SimpleDecoderAudioRenderer.java:299)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Unknown Source:14) 
        at android.os.Looper.loop(Unknown Source:139) 
        at android.os.HandlerThread.run(Unknown Source:28) 

```
[bugreport-2020-02-11-23-48-10.zip](https://github.com/google/ExoPlayer/files/4188255/bugreport-2020-02-11-23-48-10.zip)

**Comment by AquilesCanta** [comment]
Seems to me the provided stack trace is unrelated to the original report, since you are using the ffmpeg extension in the demo app, which you are not using in your own app.

I'll have a look when I have the time. Thanks for the report.

**Comment by master255** [comment]
Dear @AquilesCanta , of course i'm use ffmpeg in my project. I understand the error occurs in a place where it is not foreseen. Fix it, please.

**Comment by ojw28** [comment]
I took a quick look at this as I was touching the FFmpeg extension. It looks like `PsExtractor` assumes `streamId == PRIVATE_STREAM_1` means the stream is AC3, however according to VLC the audio track is LPCM. There's already a comment in `PsExtractor` saying that the stream could also be DTS, so it looks like we need to add some disambiguation to figure out the stream type for `PRIVATE_STREAM_1` streams.

**Comment by master255** [comment]
Now I have this error. For me it is enough.

E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: FfmpegAudioRenderer error, index=5, format=Format(189, null, null, audio/ac3, null, -1, null, [-1, -1, -1.0], [2, 48000]), format_supported=YES
        at f.b.a.b.k0.handleMessage(ExoPlayerImplInternal.java:542)
        at android.os.Handler.dispatchMessage(Unknown Source:14)
        at android.os.Looper.loop(Unknown Source:139)
        at android.os.HandlerThread.run(Unknown Source:28)
     Caused by: com.google.android.exoplayer2.audio.AudioSink$ConfigurationException: Invalid output channel config (mode=0) for: Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [0, 0])
        at com.google.android.exoplayer2.audio.DefaultAudioSink.t(DefaultAudioSink.java:575)
        at f.b.a.b.o1.x.S(DecoderAudioRenderer.java:399)
        at f.b.a.b.o1.x.n(DecoderAudioRenderer.java:296)
        at f.b.a.b.k0.f(ExoPlayerImplInternal.java:892)
        at f.b.a.b.k0.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Unknown Source:14) 
        at android.os.Looper.loop(Unknown Source:139) 
        at android.os.HandlerThread.run(Unknown Source:28)
