### ISSUE TITLE
[Flutter/video_player] AudioFlinger could not create track, status: -12

### ISSUE THREAD

**Issue by Hassan-Fa** [google/ExoPlayer#6962]
### Issue description
i'm using video_player package in flutter which uses ExoPlayer
and each time you want to do seekTo any moment before the current position(moment) video gets loaded again from local file (obviously in this case the video is loaded from a local file)

everything works fine but sometimes after like 15 20 times doing seekTo() , the video won't load again, and the widget is invisible completely (no blank screen I mean)

(the app is being tested on an emulator , so the other issues that tracked this bug maybe different from this one) (i.e. #5480)

### Reproduction steps
is explained above.

### Link to test content
will create a sample app for this if required.

### A full bug report captured from the device
Emailed.

### Version of ExoPlayer being used
Since this video_player package is using the ExoPlayer I'm not sure how I could find the ExoPlayer version.

###  Device(s) and version(s) of Android being used
Api 22
Android-Emulator

### What Console Printed Out
<details>

 <summary>Console</summary>

```
[   +4 ms] I/ExoPlayerImpl( 9752): Init 971115b [ExoPlayerLib/2.9.6] [generic_x86_64, Android SDK built for x86_64, unknown, 22]
[  +47 ms] I/OMXClient( 9752): Using client-side OMX mux.
[  +12 ms] E/ACodec  ( 9752): [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
[  +50 ms] I/OMXClient( 9752): Using client-side OMX mux.
[ +240 ms] E/AudioTrack( 9752): AudioFlinger could not create track, status: -12
[   +3 ms] E/AudioTrack-JNI( 9752): Error -12 initializing AudioTrack
[   +1 ms] E/android.media.AudioTrack( 9752): Error code -20 when initializing AudioTrack.
[   +1 ms] E/ExoPlayerImplInternal( 9752): Playback error.
[   +1 ms] E/ExoPlayerImplInternal( 9752): com.google.android.exoplayer2.ExoPlaybackException:
com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 12, 48000)
[   +1 ms] E/ExoPlayerImplInternal( 9752):      at
com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:646)
[   +3 ms] E/ExoPlayerImplInternal( 9752):      at
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1355)
[   +2 ms] E/ExoPlayerImplInternal( 9752):      at
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
[   +2 ms] E/ExoPlayerImplInternal( 9752):      at
com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
[   +1 ms] E/ExoPlayerImplInternal( 9752):      at
com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
[   +1 ms] E/ExoPlayerImplInternal( 9752):      at android.os.Handler.dispatchMessage(Handler.java:98)
[   +2 ms] E/ExoPlayerImplInternal( 9752):      at android.os.Looper.loop(Looper.java:135)
[   +1 ms] E/ExoPlayerImplInternal( 9752):      at android.os.HandlerThread.run(HandlerThread.java:61)
[   +1 ms] E/ExoPlayerImplInternal( 9752): Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack
init failed: 0, Config(48000, 12, 48000)
[   +1 ms] E/ExoPlayerImplInternal( 9752):      at
com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:1128)
[   +1 ms] E/ExoPlayerImplInternal( 9752):      at
com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:532)
[   +1 ms] E/ExoPlayerImplInternal( 9752):      at
com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:593)
[   +3 ms] E/ExoPlayerImplInternal( 9752):      at
com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:640)
[   +1 ms] E/ExoPlayerImplInternal( 9752):      ... 7 more
```

</details>

**Comment by andrewlewis** [comment]
The cause seems to be "02-10 22:46:58.227  1174  6088 E AudioFlinger: not enough memory for AudioTrack size=65600".

Can you reproduce this on a real device? If not, it may be an emulator bug. If yes, please provide a bug report taken from the device. Thanks.

**Comment by ptvandi** [comment]
I had this issue when running the Android Studio emulator. To resolve my problem, I bumped the RAM in the AVD manager (just guessed the amount, went from about 1.5GB to 3GB).
