### ISSUE TITLE
smoothstreaming failed with 2.11.2

### ISSUE THREAD

**Issue by DarkAnakin** [google/ExoPlayer#6981]
### [REQUIRED] Issue description
smoothstreaming videos failed to play with the version 2.11.2

### [REQUIRED] Reproduction steps
play Super speed demo
```
Caused by: java.lang.NullPointerException
        at java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1068)
        at java.util.Collections$UnmodifiableList.<init>(Collections.java:1344)
        at java.util.Collections.unmodifiableList(Collections.java:1331)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.<init>(FragmentedMp4Extractor.java:251)
at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.<init>(FragmentedMp4Extractor.java:223)
        at com.google.android.exoplayer2.source.smoothstreaming.DefaultSsChunkSource.<init>(DefaultSsChunkSource.java:116)
        at com.google.android.exoplayer2.source.smoothstreaming.DefaultSsChunkSource$Factory.createChunkSource(DefaultSsChunkSource.java:69)
```

**Comment by ojw28** [comment]
Thanks for the report. SmoothStreaming isn't as widely used as the other streaming standards we support (i.e., DASH and HLS), and we need to put some better testing in place for it.

We will create a 2.11.3 release shortly that includes the fix. We've also added `DefaultSsChunkSouce` to the nullness tests that we run internally, which would have caught this, and will be working on putting some better playback tests in place for SmoothStreaming going forward.
