### ISSUE TITLE
I got [com.google.android.exoplayer2.ParserException: Invalid NAL length]

### ISSUE THREAD

**Issue by tuxxon** [google/ExoPlayer#6987]
### [REQUIRED] Issue description
When playing  https://www.youtube.com/watch?v=JN4RMvH72Uo with ExoPlayer
I got [com.google.android.exoplayer2.ParserException: Invalid NAL length]
the details error message I got is 
```
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.ParserException: Invalid NAL length
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:544)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:193)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:965)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:394)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

###[REQUIRED] Reproducing errors.
I think if you use `NewPipe` app which is using Exoplayer, then you can reproduce this error.

### [REQUIRED] Version of ExoPlayer being used
v 2.10.8

### [REQUIRED] Device(s) and version(s) of Android being used
Android Emulator on AdroidStudio.

Anyone can help me?

Thank you.

**Comment by christosts** [comment]
The [YouTube Android Player API](https://developers.google.com/youtube/android/player/) is the official way to play YouTube videos on Android. It's not possible to obtain direct links to YouTube videos for playback by ExoPlayer.
