### ISSUE TITLE
HEVC DASH + PlayReady in ExoPlayer: android.media.MediaCodec$CryptoException 

### ISSUE THREAD

**Issue by willzhan** [google/ExoPlayer#7003]
### [REQUIRED] Issue description
APK used: https://drive.google.com/file/d/1MTAi7y80Njjqz_gH5zo5SQa7shAYYxB8/view?usp=sharing
APK based on: https://github.com/google/ExoPlayer 
Live HEVC DASH + CENC (PlayReady/Widevine) stream URL: •	https://hkms-aaea.streaming.media.azure.net/7f000d39-7421-470f-9ba6-9cb855addc82/manifest.ism/manifest(format=mpd-time-csf,encryption=cenc,filter=uhd) 

Player throws error after playing for underterministic amount of time: 3 min, 5 min or 10 min.

### [REQUIRED] Reproduction steps
The above HEVC DASH + PlayReady live stream has only 4K bitrate/layer. Every player can get PlayReady license from the default license delivery URL.

Set up ExoPlayer test app and play for a while, see error thrown.

### [REQUIRED] Link to test content
See above.
If you test the same live stream but without DRM protection: https://hkms-aaea.streaming.media.azure.net/e8ca1fe2-d0ed-4cd1-880a-bcc2e8216d9d/4dc8ba561e.ism/manifest(format=mpd-time-csf,filter=uhd) , there is no such issue.

### [REQUIRED] A full bug report captured from the device

```
2020-02-19 14:12:24.065 9002-9071/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(1_V_video_track_516467159851116480, null, null, video/hevc, hev1.1.6.L150.90, 14000000, null, [3840, 2160, -1.0], [-1, -1]), rendererSupport=NO_UNSUPPORTED_DRM
    com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Unknown Error
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1197)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:719)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.media.MediaCodec$CryptoException: Unknown Error
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2532)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1188)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:719)?
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)?
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)?
        at android.os.Handler.dispatchMessage(Handler.java:101)?
        at android.os.Looper.loop(Looper.java:164)?
        at android.os.HandlerThread.run(HandlerThread.java:65)?
```

### [REQUIRED] Version of ExoPlayer being used
TBD

### [REQUIRED] Device(s) and version(s) of Android being used
Mi Box International Version

**Comment by christosts** [comment]
I have been able to play the PlayReady stream without errors with the demo app on versions 2.10.8 and 2.11.2 on a Sony Bravia Android TV.

May I ask what version of the player you are using? Is it also possible to grab a bug report from the device when the issue happens (if you don't want to post it here you can email it at dev.exoplayer@gmail.com with subject #7003).

Thanks

**Comment by willzhan** [comment]
Thanks a lot, christosts! Great to see the positive test on Sony Android TV. I will follow up with the rest of the info via email. Thanks again!

**Comment by willeamlee** [comment]
releaseVersion = '2.11.2'
releaseVersionCode = 2011002
[DRMerror.log](https://github.com/google/ExoPlayer/files/4253094/DRMerror.log)

**Comment by christosts** [comment]
Update: I managed to get a repro on a Xiaomi MiBox 3. Will post again once I have a better understanding of this.

**Comment by christosts** [comment]
Hi,

as far as I can tell, the issue is coming from the device's PlayReady module with UHD content. The maintainer of module has been notified of this issue. You will need to contact the device manufacturer for a fix.

**Comment by willzhan** [comment]
Awesome investigation, chrisosts! We will follow up with the device manufacturer. Thanks a lot!
