### ISSUE TITLE
Not working playing Unicast (http)

### ISSUE THREAD

**Issue by SteinerOkay** [google/ExoPlayer#701]
I tried to play multicast stream (example: http://176.51.2.230:1234/udp/233.7.70.205:5000) with this ExtractorRendererBuilder:
but no playing anything and "playbackState=idle", in log:

```
08-10 01:48:29.453    4440-4440/com.google.android.exoplayer.demo I/ExoPlayerImpl﹕ Init 1.4.2
08-10 01:48:29.454    4440-4440/com.google.android.exoplayer.demo D/EventLogger﹕ start [0]
08-10 01:48:29.455    4440-4440/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, false, P]
08-10 01:48:29.460    4440-4440/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.01, true, P]
08-10 01:48:29.632    4440-4464/com.google.android.exoplayer.demo D/OpenGLRenderer﹕ endAllStagingAnimators on 0xaf13bc00 (ListView) with handle 0xa2f57270
08-10 01:48:34.188    4440-4440/com.google.android.exoplayer.demo D/EventLogger﹕ state [4.73, true, B]
08-10 01:48:34.229    4440-9821/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
08-10 01:48:34.265    4440-9821/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
08-10 01:48:34.269    4440-9821/com.google.android.exoplayer.demo W/ACodec﹕ do not know color format 0x7fa30c03 = 2141391875
08-10 01:48:34.411    4440-4440/com.google.android.exoplayer.demo D/EventLogger﹕ decoderInitialized [4.96, OMX.qcom.video.decoder.avc]
08-10 01:48:34.415    4440-9827/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
08-10 01:48:34.422    4440-9827/com.google.android.exoplayer.demo E/OMXMaster﹕ A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
08-10 01:48:34.437    4440-4440/com.google.android.exoplayer.demo D/EventLogger﹕ decoderInitialized [4.98, OMX.google.aac.decoder]
08-10 01:48:34.454    4440-9828/com.google.android.exoplayer.demo I/SoftAAC2﹕ Reconfiguring decoder: 0->48000 Hz, 0->2 channels
08-10 01:48:34.613    4440-9821/com.google.android.exoplayer.demo W/AHierarchicalStateMachine﹕ Warning message AMessage(what = 'omx ', target = 1) = {
    int32_t type = 0
    int32_t node = 1708
    int32_t event = 2130706432
    int32_t data1 = 1
    int32_t data2 = 0
    } unhandled in root state.
08-10 01:48:34.642    4440-9821/com.google.android.exoplayer.demo E/ACodec﹕ registering GraphicBuffer 0 with OMX IL component failed: -2147483648
08-10 01:48:34.642    4440-9821/com.google.android.exoplayer.demo E/ACodec﹕ Failed to allocate output port buffers after port reconfiguration (error 0x80000000)
08-10 01:48:34.642    4440-9821/com.google.android.exoplayer.demo E/ACodec﹕ signalError(omxError 0x80001001, internalError -2147483648)
08-10 01:48:34.642    4440-9820/com.google.android.exoplayer.demo E/MediaCodec﹕ Codec reported err 0x80001001, actionCode 0, while in state 6
08-10 01:48:34.649    4440-9681/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal runtime error.
    java.lang.IllegalStateException
            at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
            at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:832)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:499)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
08-10 01:48:34.655    4440-4440/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [5.20]
    com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:238)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.lang.IllegalStateException
            at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
            at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:832)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:499)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
08-10 01:48:34.760    4440-9821/com.google.android.exoplayer.demo W/ACodec﹕ cannot keep component allocated on shutdown in Uninitialized state
08-10 01:48:34.768    4440-4440/com.google.android.exoplayer.demo D/EventLogger﹕ state [5.31, true, I]
08-10 01:48:59.926    4440-4440/com.google.android.exoplayer.demo W/InputEventReceiver﹕ Attempted to finish an input event but the input event receiver has already been disposed.
08-10 01:49:02.050    4440-4440/com.google.android.exoplayer.demo W/InputEventReceiver﹕ Attempted to finish an input event but the input event receiver has already been disposed.

```

Anybody have idea whats wrong?

**Comment by ojw28** [comment]
Nope. This is by no means a primary use case; we're more invested in streaming over TCP/HTTP. So you'll likely need to debug the issue yourself.

**Comment by spark85** [comment]
I've had this issue streaming .aac w/ a .m3u8 wrapper

**Comment by ojw28** [comment]
Closing as obsolete. If the issue still occurs in version 2.0.4 then please file a new issue containing all of the information requested in our new issue template; thanks!
