### ISSUE TITLE
Player gets stuck when entering mid-roll after empty pre-roll

### ISSUE THREAD

**Issue by TakuSemba** [google/ExoPlayer#7015]
### [REQUIRED] Issue description

When a vast has empty pre-roll and non-empty mid-roll, ExoPlayer gets stuck right before entering the mid-roll and keeps buffering.

This suddenly started happening today which is when js version inside IMA SDK changed from 3.196.2 to 3.199.0. 

I replaced 3.199.0 with 3.196.2 locally with proxy and it worked well.

https://imasdk.googleapis.com/native/core/3.199.0/native_bridge_debug__ja.js
↓
https://imasdk.googleapis.com/native/core/3.196.2/native_bridge_debug__ja.js

A similar situation happened a few months ago.
https://github.com/google/ExoPlayer/issues/6728

### [REQUIRED] Reproduction steps

I prepared a vast with empty pre-roll and non-empty mid-roll, so you can reproduce from this link just by playing a media with this vast.

### [REQUIRED] Link to test content

I will send you a link file to dev.exoplayer@gmail.com

### [REQUIRED] A full bug report captured from the device

I will send you a zip to dev.exoplayer@gmail.com

### [REQUIRED] Version of ExoPlayer being used
2.10.4

### [REQUIRED] Device(s) and version(s) of Android being used
The device that I used: Pixel 3 (OS 10)

**Comment by raunakyadav** [comment]
Hello, 
Facing the same issue since today. If the vmap does not have a preroll node, it does not play any midrolls too.
Getting the following logs :
```
 D/ImaAdsLoader: onAdEvent: LOADED
 D/ImaAdsLoader: Loaded ad 1 of 1 in group -1
 E/ImaAdsLoader: Internal error in onAdEvent
    java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
        at com.raunak.exodemo.ImaAdsLoader.handleAdEvent(ImaAdsLoader.java:1067)
        at com.raunak.exodemo.ImaAdsLoader.onAdEvent(ImaAdsLoader.java:663)
        at com.google.ads.interactivemedia.v3.internal.iq.a(IMASDK:76)
        at com.google.ads.interactivemedia.v3.internal.iq.a(IMASDK:72)
        at com.google.ads.interactivemedia.v3.internal.iq.a(IMASDK:115)
        at com.google.ads.interactivemedia.v3.internal.ij.a(IMASDK:59)
        at com.google.ads.interactivemedia.v3.internal.jc.f(IMASDK:169)
        at com.google.ads.interactivemedia.v3.internal.jc.a(IMASDK:43)
        at com.google.ads.interactivemedia.v3.internal.jd.b(IMASDK:43)
        at com.google.ads.interactivemedia.v3.internal.jd$1.shouldOverrideUrlLoading(IMASDK:4)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:16)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
 D/ImaAdsLoader: loadAd in ad group -1
 W/ImaAdsLoader: Unexpected loadAd without LOADED event; assuming ad group index is actually 0
 W/ImaAdsLoader: Unexpected loadAd in an ad group with no remaining unavailable ads
 D/ImaAdsLoader: onAdEvent: CONTENT_PAUSE_REQUESTED
 D/ImaAdsLoader: playAd
 D/ImaAdsLoader: VideoAdPlayerCallback.onEnded in onTimelineChanged/onPositionDiscontinuity
 D/ImaAdsLoader: onAdEvent: LOG
 I/ImaAdsLoader: AdEvent: {type=adPlayError, errorCode=402, errorMessage=VAST media file loading reached a timeout of 8 seconds.}
 D/ImaAdsLoader: onAdEvent: CONTENT_RESUME_REQUESTED
```

**Comment by donato** [comment]
Thank you for the detailed reproduction steps! I have verified the problem and will roll out a patch within the hour.

**Comment by TakuSemba** [comment]
@donato 
Hi, 3.199.2 is released but the issue is still happening.
Did you already release the patch version? and what version would it be?

**Comment by donato** [comment]
Thank you for following up @TakuSemba , I had misdiagnosed the earlier problem. I'd thought the issue was with podIndex, but it looks like it was related to preloading the first video after an empty adbreak. I'm working on another hotfix, 3.199.3 which should be live shortly.

**Comment by TakuSemba** [comment]
Thanks, I confirmed that 3.199.3 was released and the issue was solved.
