### ISSUE TITLE
Android 4.x.x - E/ExoPlayerImplInternal: Source error.

### ISSUE THREAD

**Issue by inat-tv** [google/ExoPlayer#7028]
Logcat:

```
02-28 15:33:45.463 8100-8441/com.renklab.inatpro E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:170)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
02-28 15:33:45.603 8100-8100/com.renklab.inatpro D/StreamPlayerActivity: onTimelineChanged: 
02-28 15:33:45.603 8100-8100/com.renklab.inatpro E/StreamPlayerActivity: onPlayerError: 
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:394)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:170)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
```

Minimum sdk 17, target sdk 29

I created 2 players both as fragment and activity but it doesn't work on android 4 versions. No problem at 5 and above.
<a href="https://hizliresim.com/VByd6B"><img src="https://i.hizliresim.com/VByd6B.png"></a>

**Comment by inat-tv** [comment]
There are other errors too. The image is of poor quality in multiple qualities. It doesn't open on Android 4 at all.
```
02-28 15:43:58.353 8100-8739/com.renklab.inatpro E/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
02-28 15:43:58.353 8100-8739/com.renklab.inatpro E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -2147483648
02-28 15:43:58.353 8100-8739/com.renklab.inatpro W/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed
02-28 15:43:58.353 8100-8739/com.renklab.inatpro W/ACodec: [OMX.google.h264.decoder] prepareForAdaptivePlayback failed w/ err -2147483648
02-28 15:43:58.373 8100-8742/com.renklab.inatpro I/OMXClient: Using client-side OMX mux.
02-28 15:43:58.473 8100-8737/com.renklab.inatpro D/dalvikvm: GC_FOR_ALLOC freed 1352K, 7% free 74282K/79180K, paused 98ms, total 98ms
02-28 15:43:58.513 8100-8740/com.renklab.inatpro E/SoftAVC: Decoder failed: -2
02-28 15:43:58.513 8100-8739/com.renklab.inatpro E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
02-28 15:43:58.513 8100-8738/com.renklab.inatpro E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -2147483648)
02-28 15:43:58.513 8100-8654/com.renklab.inatpro D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.4D401E, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, Android SDK built for x86, unknown, 19]
02-28 15:43:58.513 8100-8654/com.renklab.inatpro E/ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(0, null, null, video/avc, avc1.4D401E, 564000, null, [640, 360, -1.0], [-1, -1]), rendererSupport=NO_EXCEEDS_CAPABILITIES
    com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:732)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.queueInputBuffer(Native Method)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1190)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:719)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
02-28 15:43:58.523 8100-8654/com.renklab.inatpro E/ExoPlayerImplInternal: Disable failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.flush(Native Method)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:773)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.flushOrReleaseCodec(MediaCodecVideoRenderer.java:724)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:634)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:569)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:168)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1136)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:891)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:382)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
02-28 15:43:58.583 8100-8100/com.renklab.inatpro D/StreamPlayerActivity: onTracksChanged: 4
02-28 15:43:58.713 8100-8100/com.renklab.inatpro E/StreamPlayerActivity: onPlayerError: 
    com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:732)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.queueInputBuffer(Native Method)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1190)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:719)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
02-28 15:43:58.713 8100-8100/com.renklab.inatpro D/StreamPlayerActivity: onLoadingChanged: false
02-28 15:43:58.733 8100-8100/com.renklab.inatpro D/StreamPlayerActivity: onPlayerStateChanged: true
02-28 15:44:44.743 1888-1888/com.android.phone D/dalvikvm: GC_FOR_ALLOC freed 591K, 18% free 3584K/4364K, paused 25ms, total 26ms
02-28 15:44:55.013 8100-8100/com.renklab.inatpro I/Ads: This request is sent from a test device.
02-28 15:44:55.053 8100-8746/com.renklab.inatpro E/DynamiteModule: Failed to load IDynamiteLoader from GmsCore: Application package com.google.android.gms not found

```

**Comment by inat-tv** [comment]
Don't have a simple example for Exoplayer? For example, can not you make a sample through a single m3u8 link? It is very complicated. It makes a lot of effort for beginners.

**Comment by inat-tv** [comment]
We make many settings wrong. A good example though. We can learn through the example.

**Comment by andrewlewis** [comment]
For the first error (HTTP status 400) this is likely to be a server issue. See also #4537.

Regarding the exceptions from `MediaCodec`: it looks like you are testing on the emulator, which has limited support for decoding video formats (especially before API 23). See also [supported devices](https://exoplayer.dev/supported-devices.html).

Regarding sample code, please have a look at the documentation at https://exoplayer.dev and the ExoPlayer demo application. It is not really a simple example but hopefully you can pick out the relevant things you need from there.

**Comment by inat-tv** [comment]
> İlk hata (HTTP durumu 400) için bu bir sunucu sorunu olabilir. Ayrıca bkz . [# 4537](https://github.com/google/ExoPlayer/issues/4537) .
> 
> Aşağıdaki istisnalar göz önüne alındığında `MediaCodec`: video formatlarının kodunun çözülmesi için sınırlı desteği olan (özellikle API 23'ten önce) emülatör üzerinde test ediyor gibi görünüyorsunuz. Ayrıca bkz . [Desteklenen cihazlar](https://exoplayer.dev/supported-devices.html) .
> 
> Örnek kodla ilgili olarak, lütfen [https://exoplayer.dev adresindeki](https://exoplayer.dev) belgelere ve ExoPlayer demo uygulamasına bir göz atın . Gerçekten basit bir örnek değil ama umarım ihtiyacınız olan ilgili şeyleri oradan seçebilirsiniz.



> For the first error (HTTP status 400) this is likely to be a server issue. See also #4537.
> 
> Regarding the exceptions from `MediaCodec`: it looks like you are testing on the emulator, which has limited support for decoding video formats (especially before API 23). See also [supported devices](https://exoplayer.dev/supported-devices.html).
> 
> Regarding sample code, please have a look at the documentation at https://exoplayer.dev and the ExoPlayer demo application. It is not really a simple example but hopefully you can pick out the relevant things you need from there.

I read this topic. But there are many channels. Not all of them have server problems. All posts have the same problem. https://github.com/google/ExoPlayer/issues/4537 There may be an exoplayer issue for Android 4. Or I may be making some settings wrong. But I couldn't figure it out.

**Comment by inat-tv** [comment]
> For the first error (HTTP status 400) this is likely to be a server issue. See also #4537.
> 
> Regarding the exceptions from `MediaCodec`: it looks like you are testing on the emulator, which has limited support for decoding video formats (especially before API 23). See also [supported devices](https://exoplayer.dev/supported-devices.html).
> 
> Regarding sample code, please have a look at the documentation at https://exoplayer.dev and the ExoPlayer demo application. It is not really a simple example but hopefully you can pick out the relevant things you need from there.

I read this topic. But there are many channels. Not all of them have server problems. All posts have the same problem. https://github.com/google/ExoPlayer/issues/4537 There may be an exoplayer issue for Android 4. Or I may be making some settings wrong. But I couldn't figure it out.
