### ISSUE TITLE
Audio and Video HLS Stream is not playing in Nexus 5 (5.1.1 Android Version)

### ISSUE THREAD

**Issue by sachinbhanot** [google/ExoPlayer#703]
I am trying to play hls video in exoplayer demo. but is showing the exception. Its working yesterday but not today ? can you please help me out ? where is the issues?

 com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 640, 272, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:387)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.setSurface(MediaCodecVideoTrackRenderer.java:350)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.handleMessage(MediaCodecVideoTrackRenderer.java:331)
            at com.google.android.exoplayer.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:541)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:219)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 640, 272, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.setSurface(MediaCodecVideoTrackRenderer.java:350)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.handleMessage(MediaCodecVideoTrackRenderer.java:331)
            at com.google.android.exoplayer.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:541)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:219)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: android.media.MediaCodec$CodecException: Error 0xffffffed
            at android.media.MediaCodec.native_configure(Native Method)
            at android.media.MediaCodec.configure(MediaCodec.java:577)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:363)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:366)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.setSurface(MediaCodecVideoTrackRenderer.java:350)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.handleMessage(MediaCodecVideoTrackRenderer.java:331)
            at com.google.android.exoplayer.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:541)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:219)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
08-10 13:42:23.322  21345-21607/? E/chromium﹕ [ERROR:get_updates_processor.cc(243)] PostClientToServerMessage() failed during GetUpdates
08-10 13:42:30.395      187-745/? E/audio_hw_primary﹕ out_write: error -1 - cannot write stream data: I/O error
08-10 13:42:30.453     746-1371/? E/WifiHAL﹕ Error polling socket
08-10 13:42:33.719  21345-21419/? E/chromium﹕ [ERROR:simple_index_file.cc(223)] Failed to write the temporary index file
08-10 13:42:34.669      746-842/? E/WifiStateMachine﹕ WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=0.00 targetRoamBSSID=18:9c:5d:96:8f:df RSSI=-53
08-10 13:42:37.392      746-815/? E/ActivityManager﹕ ANR in com.jio.media.mobile.apps.jioondemand
    PID: 20784

**Comment by ojw28** [comment]
This may well have been a temporary, device specific issue. There's insufficient information to investigate though. If this is still a problem on 1.5.8, please file a fresh issue containing all of the information requested in the issue template.
