### ISSUE TITLE
No virtual method addVideoListener

### ISSUE THREAD

**Issue by wahdatjan** [google/ExoPlayer#7033]
```
java.lang.NoSuchMethodError: No virtual method addVideoListener(Lcom/google/android/exoplayer2/SimpleExoPlayer$VideoListener;)V in class Lcom/google/android/exoplayer2/SimpleExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.SimpleExoPlayer' appears in /data/app/com.example.android.tvleanback-FYnVvEo0bdLBpYBsK86nkw==/base.apk)
        at com.google.android.exoplayer2.ext.leanback.LeanbackPlayerAdapter.onAttachedToHost(LeanbackPlayerAdapter.java:117)
        at androidx.leanback.media.PlaybackBaseControlGlue.onAttachedToHost(PlaybackBaseControlGlue.java:234)
        at androidx.leanback.media.PlaybackTransportControlGlue.onAttachedToHost(PlaybackTransportControlGlue.java:169)
        at androidx.leanback.media.PlaybackGlueHost.attachToGlue(PlaybackGlueHost.java:220)
        at androidx.leanback.media.PlaybackGlue.setHost(PlaybackGlue.java:196)
        at com.example.android.tvleanback.ui.PlaybackFragment.initializePlayer(PlaybackFragment.java:161)
        at com.example.android.tvleanback.ui.PlaybackFragment.onStart(PlaybackFragment.java:117)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2477)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1494)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3235)
        at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:212)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:628)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by krocard** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by ojw28** [comment]
It seems possible you are mixing multiple different versions of ExoPlayer together. All ExoPlayer modules used by your app should have the same version. So you might also want to check whether this is the case.
