### ISSUE TITLE
DRM Widevine L1 HDCP - Offline 

### ISSUE THREAD

**Issue by andrea157** [google/ExoPlayer#7048]
Hi, I'm trying to implement the download of DRM-protected content on the demo app.
Downloading and playing a Widevine L3 content works correctly while for the same content but with Widevine L1 HDCP protection I can download it but when I try to play it I have the following exception:

```
2020-03-05 09:15:48.599 26489-27082/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.drm.KeysExpiredException
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:486)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:379)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:271)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:536)
        at com.google.android.exoplayer2.source.SampleQueue.onFormatResult(SampleQueue.java:795)
        at com.google.android.exoplayer2.source.SampleQueue.readSampleMetadata(SampleQueue.java:563)
        at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:327)
        at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.readData(ChunkSampleStream.java:372)
        at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:379)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:808)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:709)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.drm.KeysExpiredException
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:379) 
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:271) 
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:536) 
        at com.google.android.exoplayer2.source.SampleQueue.onFormatResult(SampleQueue.java:795) 
        at com.google.android.exoplayer2.source.SampleQueue.readSampleMetadata(SampleQueue.java:563) 
        at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:327) 
        at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.readData(ChunkSampleStream.java:372) 
        at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:379) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:808) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:709) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

So I wanted to know if theoretically a content with Widevine L1 HDCP is downloadable and playable offline as for a Widevine L3 or if there are different limitations. If it is possible, what can this error depend on?

**Comment by seventhmoon** [comment]
No. You cannot play L1 protected content on L3 devices.

**Comment by andrea157** [comment]
Sorry I'm not explained well.

The device I'm using supports the L1 DRM.

I have the same content in two versions: one with DRM HDCP L1 and the other with DRM L3. 

The online reproduction of these 2 contents works correctly on my device instead by downloading them the version with DRM L3 works correctly offline while the HDCP L1 DRM version (which works online) does not work offline; I have no error while downloading the license and the content but when I play it I have the error above

**Comment by andrea157** [comment]
Sorry, I solved this problem but now I have a new problem.

When I call `offlineLicenseHelper.renewLicense(offlineLicenseKeySetId)`

I have this error:

```
Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:446)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:441)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:394)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:350)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:176)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:437)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.openBlockingKeyRequest(OfflineLicenseHelper.java:273)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.blockingKeyRequest(OfflineLicenseHelper.java:258)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.renewLicense(OfflineLicenseHelper.java:205)
        at it.rainet.download.drm.exo.ExoDrmRenewLicenseAsync.doInBackground(ExoDrmRenewLicenseAsync.kt:55)
        at it.rainet.download.drm.exo.ExoDrmRenewLicenseAsync.doInBackground(ExoDrmRenewLicenseAsync.kt:21)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request
        at android.media.MediaDrm.getKeyRequest(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:144)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:391)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:350) 
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:176) 
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:437) 
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.openBlockingKeyRequest(OfflineLicenseHelper.java:273) 
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.blockingKeyRequest(OfflineLicenseHelper.java:258) 
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.renewLicense(OfflineLicenseHelper.java:205) 
        at it.rainet.download.drm.exo.ExoDrmRenewLicenseAsync.doInBackground(ExoDrmRenewLicenseAsync.kt:55) 
        at it.rainet.download.drm.exo.ExoDrmRenewLicenseAsync.doInBackground(ExoDrmRenewLicenseAsync.kt:21) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by ojw28** [comment]
There isn't enough information here for us to help you. Please provide a full bug report as requested in the issue template, and also a more detailed description of exactly what you're doing.

**Comment by andrea157** [comment]
I solved. This ticket can be closed. Thanks

**Comment by mseroczynski** [comment]
@andrea157 Could you please provide any tip on how to solve mentioned issue?

**Comment by andrea157** [comment]
It was a server configuration issue
