### ISSUE TITLE
App crashes on recent versions FATAL EXCEPTION: ExoPlayerImplInternal:Handler

### ISSUE THREAD

**Issue by haihack** [google/ExoPlayer#7060]
### [REQUIRED] Issue description
The crashing happened right after I played a streaming audio. I had been reporting this issue in [earlier version 2.9.6](https://github.com/google/ExoPlayer/issues/5600) but it has still existed until now. So I decided to reproduce it in a small project.

### [REQUIRED] Link to test content
[Click here!](https://drive.google.com/open?id=1nC0zp9MfEt9veClpyPu5wSHz7dScdaUp)

### [REQUIRED] A full bug report captured from the device
```
    --------- beginning of crash
2020-03-08 14:35:02.774 28626-28730/com.bug.exoplayer E/AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
    Process: com.bug.exoplayer, PID: 28626
    java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.upstream.DataSource.addTransferListener(com.google.android.exoplayer2.upstream.TransferListener)"
        at com.google.android.exoplayer2.source.ProgressiveMediaSource.createPeriod(ProgressiveMediaSource.java:270)
        at com.google.android.exoplayer2.source.ExtractorMediaSource.createPeriod(ExtractorMediaSource.java:366)
        at com.google.android.exoplayer2.MediaPeriodHolder.createMediaPeriod(MediaPeriodHolder.java:409)
        at com.google.android.exoplayer2.MediaPeriodHolder.<init>(MediaPeriodHolder.java:97)
        at com.google.android.exoplayer2.MediaPeriodQueue.enqueueNextMediaPeriodHolder(MediaPeriodQueue.java:155)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod(ExoPlayerImplInternal.java:1541)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1528)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:565)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

### [REQUIRED] Version of ExoPlayer being used
2.11.3

### [REQUIRED] Device(s) and version(s) of Android being used
Samsung Galaxy A50 - Android version 9

**Comment by ojw28** [comment]
The issue is that `implementation 'com.github.mattias-karlsson:exoplayer-shoutcast:1.0.0'` is incompatible with the version of ExoPlayer that you're trying to use. It looks like that library hasn't been updated for ~3 years.

Note that ExoPlayer supports Shoutcast metadata directly from 2.10 (see [this blog post](https://medium.com/google-exoplayer/exoplayer-2-10-whats-new-15d344eaa8b9)). So your best option is to upgrade to the latest version of ExoPlayer, remove your dependency on 'com.github.mattias-karlsson:exoplayer-shoutcast`, and use ExoPlayer's built in support for Shoutcast metadata.
