### ISSUE TITLE
Unable to stream HLS on Lenovo devices

### ISSUE THREAD

**Issue by Ltty** [google/ExoPlayer#709]
Hi,
I am unable to decoder TS segments on Lenovo devices. Here's the exception. Any clue on how to solve this? This occurs when streaming HLS. I don't have any issues on other devices such as Galaxy, Nexus or HTC One.
    
    08-13 11:45:20.424  12343-17268/at.fhooe.mc.gopro.free D/ACodec﹕ BaseState::onOMXMessage type 0
    08-13 11:45:20.424  12343-17268/at.fhooe.mc.gopro.free E/ACodec﹕ [OMX.MTK.VIDEO.DECODER.AVC] ERROR(0x80001005)
    08-13 11:45:20.424  12343-17268/at.fhooe.mc.gopro.free W/ACodec﹕ OMXCodec::onEvent--OMX Bad Parameter!!
    08-13 11:45:20.424  12343-17268/at.fhooe.mc.gopro.free D/ACodec﹕ BaseState::onOMXMessage type 1
    08-13 11:45:20.424  12343-17268/at.fhooe.mc.gopro.free D/ACodec﹕ [OMX.MTK.VIDEO.DECODER.AVC] onOMXEmptyBufferDone 0xb8a17ff8
    08-13 11:45:20.424  12343-17268/at.fhooe.mc.gopro.free D/ACodec﹕ ACodec::BaseState::postFillThisBuffer mPortEOS 0
    08-13 11:45:20.424  12343-17266/at.fhooe.mc.gopro.free E/MediaCodec﹕ Codec reported an error. (omx error 0x80001005, internalError -1103)
    08-13 11:45:20.425  12343-17268/at.fhooe.mc.gopro.free D/ACodec﹕ BaseState::onOMXMessage type 2
    08-13 11:45:20.425  12343-17268/at.fhooe.mc.gopro.free D/ACodec﹕ [OMX.MTK.VIDEO.DECODER.AVC] onOMXFillBufferDone 0xb8a10a08 time 0 us, flags = 0x00000000, rangeLength 0, platformPrivate 0x0
    08-13 11:45:20.425  12343-17268/at.fhooe.mc.gopro.free D/ACodec﹕ [OMX.MTK.VIDEO.DECODER.AVC] calling fillBuffer 0xb8a10a08
    08-13 11:45:20.426  12343-12343/at.fhooe.mc.gopro.free D/OpenGLRenderer﹕ drawRect multiDraw Toolbar @41ebf508 paint 0x64a25138 id 5 style 0 AA 0 color 0xff333333
    08-13 11:45:20.426  12343-17257/at.fhooe.mc.gopro.free I/MediaCodec﹕ [flush] :IN
    08-13 11:45:20.430  12343-17257/at.fhooe.mc.gopro.free E/ExoPlayerImplInternal﹕ Internal   runtime error.
    java.lang.IllegalStateException
            at android.media.MediaCodec.flush(Native Method)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.flushCodec(MediaCodecTrackRenderer.java:540)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.checkForDiscontinuity(MediaCodecTrackRenderer.java:526)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:494)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:106)
            at android.os.Looper.loop(Looper.java:193)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at     com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
    08-13 11:45:20.430  12343-17256/at.fhooe.mc.gopro.free I/System.out﹕ >doSendRequest
    08-13 11:45:20.434  12343-12343/at.fhooe.mc.gopro.free I/SurfaceView﹕ updateWindow --   OnPreDrawListener, mHaveFrame = true

**Comment by ojw28** [comment]
I suggest you report the issue to Lenovo, if it's only occurring on Lenovo devices.

**Comment by balazslapis** [comment]
I got the same exception crash in my Samsung Galaxy Note 3
