### ISSUE TITLE
crash when I switch between WIFI and 4G when playing dash video, how to resolve this?

### ISSUE THREAD

**Issue by ynheng** [google/ExoPlayer#7108]
```
com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=8.11, mediaPos=7.01, window=0, period=0, loadError]
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:359)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:182)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(CacheDataSource.java:308)
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:91)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:287)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:62)
        at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:183)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:471)
        at com.google.android.exoplayer2.source.chunk.ChunkExtractorWrapper$BindingTrackOutput.sampleData(ChunkExtractorWrapper.java:201)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1323)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:321)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:135)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
        at java.lang.Thread.run(Thread.java)
     Caused by: java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
        at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java)
        at libcore.io.IoBridge.recvfrom(IoBridge.java)
        at java.net.PlainSocketImpl.read(PlainSocketImpl.java)
        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java)
        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java)
        at com.android.okhttp.okio.Okio$2.read(Okio.java:135)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
        at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:418)
        at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:696)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:357)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:182) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(CacheDataSource.java:308) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:91) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:287) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:62) 
        at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:183) 
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:471) 
        at com.google.android.exoplayer2.source.chunk.ChunkExtractorWrapper$BindingTrackOutput.sampleData(ChunkExtractorWrapper.java:201) 
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1323) 
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:321) 
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:135) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java) 
        at java.lang.Thread.run(Thread.java) 
     Caused by: android.system.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
        at libcore.io.Posix.recvfromBytes(Native Method)
        at libcore.io.Posix.recvfrom(Posix.java)
        at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java)
        at libcore.io.IoBridge.recvfrom(IoBridge.java) 
        at java.net.PlainSocketImpl.read(PlainSocketImpl.java) 
        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java) 
        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java) 
        at com.android.okhttp.okio.Okio$2.read(Okio.java:135) 
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211) 
        at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50) 
        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:418) 
        at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:696) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:357) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:182) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(CacheDataSource.java:308) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:91) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:287) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:62) 
        at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:183) 
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:471) 
        at com.google.android.exoplayer2.source.chunk.ChunkExtractorWrapper$BindingTrackOutput.sampleData(ChunkExtractorWrapper.java:201) 
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1323) 
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:321) 
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:135) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java) 
        at java.lang.Thread.run(Thread.java) 
03-18 15:11:14.435 31264-31264/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=8.14, mediaPos=7.04, window=0, period=0, loadError]
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://117.131.18.30:8080/depository_yqv/asset/zhengshi/test2/1080p/seg_v_1_00004.m4s
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:292)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:487)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:288)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:129)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
        at java.lang.Thread.run(Thread.java)
     Caused by: java.net.ConnectException: failed to connect to /117.131.18.30 (port 8080) after 8000ms: connect failed: ENETUNREACH (Network is unreachable)
        at libcore.io.IoBridge.connect(IoBridge.java)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java)
        at java.net.Socket.connect(Socket.java)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
        at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
        at com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
        at com.android.okhttp.Connection.connect(Connection.java:152)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
        at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:342)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:331)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:249)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:288)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:487) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:288) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:129) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java) 
        at java.lang.Thread.run(Thread.java) 
     Caused by: android.system.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
        at libcore.io.Posix.connect(Native Method)
        at libcore.io.BlockGuardOs.connect(BlockGuardOs.java)
        at libcore.io.IoBridge.connectErrno(IoBridge.java)
        at libcore.io.IoBridge.connect(IoBridge.java) 
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java) 
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java) 
        at java.net.Socket.connect(Socket.java) 
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117) 
        at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160) 
        at com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67) 
        at com.android.okhttp.Connection.connect(Connection.java:152) 
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185) 
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128) 
        at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:342) 
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:331) 
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:249) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:288) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:487) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:288) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:129) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java) 
        at java.lang.Thread.run(Thread.java) 
```

**Comment by seyinator** [comment]
Can you show us Activity, please? Like source code.

**Comment by ynheng** [comment]
please see ExoPlayer/demos/main/src/main/java/com/google/android/exoplayer2/demo/....
I just replace the url as my video address.

**Comment by ynheng** [comment]
I think the problem is happened in blow code:

```
// OkHttpDataSource.java
 @Override
  public long open(DataSpec dataSpec) throws HttpDataSourceException {
    // ...
    Request request = makeRequest(dataSpec);
    Response response;
    ResponseBody responseBody;
    try {
      this.response = callFactory.newCall(request).execute();
      response = this.response;
      responseBody = Assertions.checkNotNull(response.body());
      responseByteStream = responseBody.byteStream();
    } catch (IOException e) {
      throw new HttpDataSourceException(
          "Unable to connect to " + dataSpec.uri, e, dataSpec, HttpDataSourceException.TYPE_OPEN);
    }
}
```

and this is the okhttpClient I added:

```
// DemoApplication.java
 public HttpDataSource.Factory buildHttpDataSourceFactory() {
    OkHttpClient client = new OkHttpClient.Builder()
        .connectTimeout(8, TimeUnit.SECONDS)
        .readTimeout(8, TimeUnit.SECONDS)
        .writeTimeout(8, TimeUnit.SECONDS)
        .callTimeout(8, TimeUnit.SECONDS)
        .retryOnConnectionFailure(true)
        .build();

    return new OkHttpDataSourceFactory(client, userAgent);
  }
```

**Comment by ynheng** [comment]
The env is WIFI & 4G opening at the same time , When I close the WIFI , it throws IOException, then crash;
But if I just open one network, then I close it when playing, it won't crash...

**Comment by ynheng** [comment]
resolved, the exception throwed here does't lead to crash, because the exception is catch in LoadTask;  
the crash is truely caused by an error that didn't logged in logcat....

```
//Loader.LoadTask.java
public void run() {
      try {
        executorThread = Thread.currentThread();
        if (!canceled) {
          TraceUtil.beginSection("load:" + loadable.getClass().getSimpleName());
          try {
            loadable.load();
          } finally {
            TraceUtil.endSection();
          }
        }
```
