### ISSUE TITLE
NoClassDefFoundError at 4.0.4 and 4.0.3

### ISSUE THREAD

**Issue by ppamorim** [google/ExoPlayer#711]
I'm using the last version of ExoPlayer, but...
Bugsnag reported:

    java.lang.NoClassDefFoundError: android.media.MediaCodecList
        at com.google.android.exoplayer.MediaCodecUtil$MediaCodecListCompatV16.getCodecCount(MediaCodecUtil.java:383)
        at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfoInternal(MediaCodecUtil.java:133)
        at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(MediaCodecUtil.java:122)
        at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(MediaCodecUtil.java:105)
        at com.google.android.exoplayer.MediaCodecUtil.maxH264DecodableFrameSize(MediaCodecUtil.java:266)
        at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.selectVideoFormats(VideoFormatSelectorUtil.java:98)
        at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.selectVideoFormatsForDefaultDisplay(VideoFormatSelectorUtil.java:61)
        at com.paidefamilia.domain.interactors.loader.HlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(HlsRendererBuilder.java:120)
        at com.paidefamilia.domain.interactors.loader.HlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(HlsRendererBuilder.java:65)
        at com.google.android.exoplayer.util.ManifestFetcher$SingleFetchHelper.onLoadCompleted(ManifestFetcher.java:369)
        at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4446)
        at java.lang.reflect.Method.invokeNative(Method.java:-2)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
        at dalvik.system.NativeStart.main(NativeStart.java:-2)

Any idea about it?

@ojw28 Samsung GT-P3100(Galaxy Tab 2), Samsung GT-P7510(Galaxy Tab 10') and LGE LG-E612f(Optimus L5). Android 4.0.4 and 4.0.3.

**Comment by ojw28** [comment]
It looks like the platform is missing some functionality that should be present. What device / OS level is this?

**Comment by ppamorim** [comment]
@ojw28 Samsung GT-P3100, Samsung GT-P7510 and LGE LG-E612f. Android 4.0.4 and 4.0.3.

**Comment by ojw28** [comment]
ExoPlayer doesn't support most uses cases prior to API level 16 (Jellybean).

**Comment by ppamorim** [comment]
@ojw28 Why this NoClassDefFoundError isn't handled? This crashes the app and needs a better handle. :(

**Comment by ojw28** [comment]
Unless you have a very specific use case, you shouldn't be using ExoPlayer at all on API levels under 16. There's no sensible way to handle the underlying platform not supporting the player (whatever we do, it'll be equivalent to you just not trying to use ExoPlayer on these platform levels).

**Comment by ppamorim** [comment]
@ojw28 Only HLS.

**Comment by ojw28** [comment]
Isn't supported below API level 16. This is documented in the [cons section](https://google.github.io/ExoPlayer/guide.html#pros-and-cons) of the developer guide, and also in the [manifest](https://github.com/google/ExoPlayer/blob/master/library/src/main/AndroidManifest.xml#L28) and [gradle](https://github.com/google/ExoPlayer/blob/master/library/build.gradle#L22) file.

**Comment by ppamorim** [comment]
@ojw28, It's only supported because MediaCodec was implemented in API 16, I know. Can be solved with #710.
