### ISSUE TITLE
I got "adsLoader.setPlayer before preparing the player. " error with implementing ima ads 

### ISSUE THREAD

**Issue by newtestpage** [google/ExoPlayer#7116]
I got this error when I want to implement ima ads with video . Could you help me to solve this problem ? Thanks 
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.exoplayercodelab, PID: 14703
    java.lang.IllegalStateException: Set player using adsLoader.setPlayer before preparing the player.
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:95)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.start(ImaAdsLoader.java:592)
        at com.google.android.exoplayer2.source.ads.AdsMediaSource.lambda$prepareSourceInternal$0$AdsMediaSource(AdsMediaSource.java:220)
        at com.google.android.exoplayer2.source.ads.-$$Lambda$AdsMediaSource$zcXBZahV9F-k_KJACPO-bl_WWX0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
`

complete playerActivity code is as below :
`public DefaultBandwidthMeter BANDWIDTH_METER ;

    private SimpleExoPlayer player;
    private PlayerView mPlayerView;
    private DefaultTrackSelector trackSelector;

    private long playbackPosition;
    private int currentWindow;
    private boolean playWhenReady = true;

    // Ads
    private ImaAdsLoader imaAdsLoader;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_test);

        BANDWIDTH_METER = new DefaultBandwidthMeter.Builder(Test.this).build();
        mPlayerView = findViewById(R.id.simple_exoplayer_view);
        imaAdsLoader = new ImaAdsLoader(Test.this, getAdTagUri());

    }

    @Override
    protected void onStart() {
        super.onStart();
        if (Util.SDK_INT > 23) {
            initializePlayer();
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
        if (Util.SDK_INT <= 23 || player == null) {
            initializePlayer();
        }
    }

    @Override
    protected void onPause() {
        super.onPause();
        if (Util.SDK_INT <= 23) {
            releasePlayer();
        }
    }

    @Override
    protected void onStop() {
        super.onStop();
        if (Util.SDK_INT > 23) {
            releasePlayer();
        }
    }

    @Override
    protected void onDestroy() {
        imaAdsLoader.release();
        super.onDestroy();
    }

    private void initializePlayer() {

        TrackSelection.Factory trackSelectionFactory = new AdaptiveTrackSelection.Factory();
        trackSelector = new DefaultTrackSelector(trackSelectionFactory);
        player = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
        mPlayerView.setPlayer(player);
        MediaSource mediaSourceWithAds = buildMediaSourceWithAds(Uri.parse("http://clips.vorwaerts-gmbh.de/VfE_html5.mp4"));
        player.setPlayWhenReady(playWhenReady);
        player.seekTo(currentWindow, playbackPosition);
        player.prepare(mediaSourceWithAds, false, true);

    }

    private void releasePlayer() {
        if (player != null) {
            playbackPosition = player.getCurrentPosition();
            playWhenReady = player.getPlayWhenReady();
            currentWindow = player.getCurrentWindowIndex();
            player.release();
            player = null;
            trackSelector = null;
        }
    }

    private MediaSource buildMediaSourceWithAds(Uri uri) {

        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this,getString(R.string.app_name));
        MediaSource videoSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(uri);

        return new AdsMediaSource(
                videoSource,
                dataSourceFactory,
                imaAdsLoader,
                mPlayerView);
    }

    private Uri getAdTagUri() {
        return Uri.parse("https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=");
    }
`

**Comment by newtestpage** [comment]
I found solution on this post .
https://github.com/google/ExoPlayer/issues/6639
