### ISSUE TITLE
Clear Key Encryption - Renderer Error - Crypto not found

### ISSUE THREAD

**Issue by soumyadeep-ghosh** [google/ExoPlayer#7120]
I looked at Issue #3138 and #3201, searched the documentation, but it seems like the functions has been deprecated.

So my objective is to play a ClearKey DRM MP4 Dash File over on ExoPlayer.

And I am using the following code:

```
DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "eTuitionPro"));
        Uri uri = Uri.parse(Tools.baseAddress+"VIDEO/"+i.getStringExtra("ModuleID")+"/index.php").buildUpon().appendQueryParameter("token", Tools.token).build();

        String keyString = "{\"keys\":[{\"kty\":\"oct\",\"k\":\"76a6c65c5ea762046bd749a2e632ccbb\",\"kid\":\"a7e61c373e219033c21091fa607bf3b8\"}],'type':\"temporary\"}";

        MediaDrmCallback drmCallback = new LocalMediaDrmCallback(keyString.getBytes());
        DrmSessionManager manager=null;
        manager = new DefaultDrmSessionManager.Builder()
                .setPlayClearSamplesWithoutKeys(true)
                .setMultiSession(false)
                .setKeyRequestParameters(new HashMap<String,String>())
                .setUuidAndExoMediaDrmProvider(C.CLEARKEY_UUID, FrameworkMediaDrm.DEFAULT_PROVIDER)
                .build(drmCallback);

        MediaSource dashMediaSource = new DashMediaSource.Factory(dataSourceFactory).setDrmSessionManager(manager).createMediaSource(uri);

        player = new SimpleExoPlayer.Builder(this).build();

        ep.setPlayer(player);
        player.prepare(dashMediaSource);
```

But when I am trying to play the video, the Clear Lead plays absolutely fine, but it shows the following Error after the Clear Lead :
```
2020-03-21 19:00:56.779 6734-7351/com.noidea.collegetools.etutionpro E/ExoPlayerImplInternal: Renderer error: index=1, type=audio, format=Format(1, null, null, audio/mp4a-latm, mp4a.40.2, 100245, und, [-1, -1, -1.0], [2, 44100]), rendererSupport=NO_UNSUPPORTED_DRM
    com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Crypto key not available
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1197)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:719)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.media.MediaCodec$CryptoException: Crypto key not available
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2699)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1188)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:719) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

The Keys are already in Base64URL Format and has been packaged using Shaka Packager. The Video works absolutely fine over at Shaka Player.

Using ExoPlayer 2.11.3

Files for Testing : https://1drv.ms/u/s!AlU1XgbOYXJfgb8SXm952hfFGToh-Q?e=sw3R8Q

I am not sure if my approach is correct.

Thank You in advance for any help.

**Comment by ojw28** [comment]
`k` and `kid` in the license response are supposed to be base64url encoded, [as per the spec](https://w3c.github.io/encrypted-media/#clear-key-license-format). If you fix your license response string to use the correct encoding, playback works correctly:
```
String keyString = "{\"keys\":[{\"kty\":\"oct\",\"k\":\"dqbGXF6nYgRr10mi5jLMuw\",\"kid\":\"p+YcNz4hkDPCEJH6YHvzuA\"}],'type':\"temporary\"}";
```
In case it's useful, I used [this website](https://base64.guru/converter/encode/hex) to encode them (and then stripped off the trailing `==` in the result).

**Comment by soumyadeep-ghosh** [comment]
Thank You @ojw28 , it worked like a charm !!
