### ISSUE TITLE
Player UI Library causes crashes making it unable to run instrumental tests consistently

### ISSUE THREAD

**Issue by shidobecker** [google/ExoPlayer#7130]
###  Issue description
When I try to run any instrumental tests in a module that contains (or a module that depends on another module that contains) the player ui library  `com.google.android.exoplayer:exoplayer-ui` I end up with this following crash:
```

2020-03-23 10:50:22.148 32552-32552/br.com.ampli.lesson.test E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/br.com.ampli.lesson.test-n5lQnrhOgpZ_ffhdwP1FgQ==/base.apk"],nativeLibraryDirectories=[/data/app/br.com.ampli.lesson.test-n5lQnrhOgpZ_ffhdwP1FgQ==/lib/x86_64, /data/app/br.com.ampli.lesson.test-n5lQnrhOgpZ_ffhdwP1FgQ==/base.apk!/lib/x86_64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:226)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:731)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at android.app.LoadedApk.getResources(LoadedApk.java:1032)

```

### [REQUIRED] Reproduction steps
Just adding the playerUi dependency and try to run an instrumentation test with it results on Process Crashed with the log above.

### [REQUIRED] Link to test content
Since it's not a problem reproducing media, no test content

### [REQUIRED] A full bug report captured from the device
```
2020-03-23 10:50:22.148 32552-32552/br.com.ampli.lesson.test E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/br.com.ampli.lesson.test-n5lQnrhOgpZ_ffhdwP1FgQ==/base.apk"],nativeLibraryDirectories=[/data/app/br.com.ampli.lesson.test-n5lQnrhOgpZ_ffhdwP1FgQ==/lib/x86_64, /data/app/br.com.ampli.lesson.test-n5lQnrhOgpZ_ffhdwP1FgQ==/base.apk!/lib/x86_64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:226)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:731)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at android.app.LoadedApk.getResources(LoadedApk.java:1032)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5749)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/br.com.ampli.lesson.test-n5lQnrhOgpZ_ffhdwP1FgQ==/base.apk because: Bad encoded_array value: Failure to verify dex file '/data/app/br.com.ampli.lesson.test-n5lQnrhOgpZ_ffhdwP1FgQ==/base.apk': Bad encoded_value method type size 7
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:727)
```

This is the only library that causes this issue, all playCore, dash, hls and smoothStreaming are fine

I'm able to resolve this by downgrading the version of playerUI to any other one, sync, build, run tests (crashes) then upgrading again to the latest version, then sync, build, run tests and works as expected

And 
 ```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
Was always added, on module that uses exoPlayer and others that depends on it as well (I trying adding and removing it just to be sure), but they all import from a gradle file that already has it in first place.

### [REQUIRED] Version of ExoPlayer being used
Happens on versions: 2.10.7 up to 2.11.3

### Device(s) and version(s) of Android being used
Any device or emulator

**Comment by ojw28** [comment]
I don't see anything in this issue report to suggest it's an ExoPlayer problem, as opposed to something wrong with your project configuration. If you're sure it's an ExoPlayer issue, please could you provide a small Android Studio demo project that we could use to efficiently reproduce the problem?

**Comment by shidobecker** [comment]
@ojw28 Well I think it's related, if I change the playerUI version or remove completed, all tests start working again.
As soon as I can I'll try to create another project so you guys can reproduce it

**Comment by ojw28** [comment]
> As soon as I can I'll try to create another project so you guys can reproduce it

Please do, thank you. One other thing to check is that you're using the same version for all ExoPlayer modules that you're using.
