### ISSUE TITLE
DASH download fails if last segment request throws a 404

### ISSUE THREAD

**Issue by Rana-Adeel-Ahmad** [google/ExoPlayer#7142]
Issue description:
-----------------------
I am trying to download DRM protected video and play offline. 
I Download the demo app from (https://github.com/google/ExoPlayer.git) and run the app. its seems secure widevine cannot be downloaded, then l found out that there is check in #getDownloadUnsupportedStringId() in #SampleChooserActivity.java which is preventing to download the media. After updating I am able to download.
- ### Issue:
i update the media.exolist.json file as follow

````
    {
        "name": "WV: Secure SD (cenc,MP4,H264)",
        "uri": "https://test-encoding-bucket.s3-us-west-1.amazonaws.com/offline-playback/test3/manifests/sd/stream.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=BQASiLwdKdYAJDQ4OTA2MmYxLTEyNDItNDA4NS04NjM1LTA3ODg3MmExZjcwMAAAAGDdO5QYUXr_lh5BdTBUQ5FYieOdpIZcxkg9MunapzD9hrYSJQzCZ6w7KbCdqIzUIrEKiOn1ouWk1neCAC9PS0l7l6lwaNtf75pMB1pvAtvxUX1pVlWtGZWp23GhLagj3L_LULZRg3-ImRnCKEv1Lk_5_TwJ6Q"
      },
````
Then play the app and click on download icon of  (#WV: Secure SD (cenc, MP4,H264)). There is selection dialog and then Downloading start. At the end when downloading is about to complete its throws an error 
 
````
2020-03-25 17:14:31.813 3604-3734/com.google.android.exoplayer2.demo E/DownloadManager: Task failed: dash:https://test-encoding-bucket.s3-us-west-1.amazonaws.com/offline-playback/test3/manifests/sd/stream.mpd, false
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:53)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:487)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:288)
        at com.google.android.exoplayer2.upstream.cache.CacheUtil.readAndDiscard(CacheUtil.java:306)
        at com.google.android.exoplayer2.upstream.cache.CacheUtil.cache(CacheUtil.java:210)
        at com.google.android.exoplayer2.offline.SegmentDownloader.download(SegmentDownloader.java:152)
        at com.google.android.exoplayer2.offline.DownloadManager$Task.run(DownloadManager.java:1290)


````

I cannot figuring out whats going wrong . other google secure .mpd streams downloaded successfully but my file did not. 

### Second
if possible Please write an demo app where the secure stream downloaded and playback.

**Comment by ojw28** [comment]
The second request is tracked by https://github.com/google/ExoPlayer/issues/7347.

I don't think the 404 error you're seeing has anything to do with whether the content is DRM protected. I think the problem is that [this workaround for playback](https://github.com/google/ExoPlayer/blob/r2.11.5/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/DefaultDashChunkSource.java#L427) also needs implementing in the downloader as well.

**Comment by ojw28** [comment]
Note: It's not as simple as just treating the 404 as a successful segment download in the downloader, since at playback time the player will still attempt to request the segment from upstream.

If the device has a network connection and there's an upstream `HttpDataSource`, this will result in a 404 at playback. Playback will end successfully, however the player shouldn't need to make a network request in this case because the content has been downloaded. Furthermore, if there is no network connection or no upstream `HttpDataSource`, playback will fail because the error wont be one for which the workaround is applied.

To fix this properly, I think we'd need a way of caching the 404 error in `SimpleCache`, whereas currently `SimpleCache` can only cache successful responses.

Marking as a bug, but also as low priority because the DASH manifest is referencing a segment that doesn't exist on the server, which is a violation of the DASH timing model.

**Comment by Rana-Adeel-Ahmad** [comment]
Yups you are right. we found that problem is with last segment of DASH manifest that does not exists. for the moment we replace the manifest file and issue was gone, but for the proper solution we should need a way of caching the 404 error.
