### ISSUE TITLE
 java.lang.UnsupportedOperationException in maybeUpdateMediaTimeHistory method

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#7160]
### [REQUIRED] Issue description

I am playing around with the new PlaybackStatsListener

When setting the keepHistory boolean to false the exception will be fired and app will crash
When setting the keepHistory boolean to true the exception will be fired and app will `not` crash

seems like that keepHistory should be conditioned before calling the add method in`maybeUpdateMediaTimeHistory` since the operation cannot be done on the `Collections.emptyList()`

```
   private void maybeUpdateMediaTimeHistory(long realtimeMs, long mediaTimeMs) {
      if (currentPlaybackState != PlaybackStats.PLAYBACK_STATE_PLAYING) {
        if (mediaTimeMs == C.TIME_UNSET) {
          return;
        }
        if (!mediaTimeHistory.isEmpty()) {
          long previousMediaTimeMs = mediaTimeHistory.get(mediaTimeHistory.size() - 1)[1];
          if (previousMediaTimeMs != mediaTimeMs) {
            mediaTimeHistory.add(new long[] {realtimeMs, previousMediaTimeMs});
          }
        }
      }
      
      mediaTimeHistory.add(
          mediaTimeMs == C.TIME_UNSET
              ? guessMediaTimeBasedOnElapsedRealtime(realtimeMs)
              : new long[] {realtimeMs, mediaTimeMs});
    }
```

##### My Code
```
 player =
          new SimpleExoPlayer.Builder(/* context= */ this, renderersFactory)
              .setTrackSelector(trackSelector)
              .build();

      PlaybackStatsListener playbackStatsListener = new PlaybackStatsListener(false,
          (eventTime, playbackStats) -> {

          });

      player.addAnalyticsListener(playbackStatsListener);

      player.addListener(new PlayerEventListener());
```

2020-03-29 18:08:44.834 2810-2810/com.google.android.exoplayer2.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.exoplayer2.demo, PID: 2810
    java.lang.UnsupportedOperationException
        at java.util.AbstractList.add(AbstractList.java:148)
        at java.util.AbstractList.add(AbstractList.java:108)
        at com.google.android.exoplayer2.analytics.PlaybackStatsListener$PlaybackStatsTracker.maybeUpdateMediaTimeHistory(PlaybackStatsListener.java:945)
        at com.google.android.exoplayer2.analytics.PlaybackStatsListener$PlaybackStatsTracker.onPlaybackSpeedChanged(PlaybackStatsListener.java:706)
        at com.google.android.exoplayer2.analytics.PlaybackStatsListener.onSessionCreated(PlaybackStatsListener.java:174)
        at com.google.android.exoplayer2.analytics.DefaultPlaybackSessionManager.updateSessions(DefaultPlaybackSessionManager.java:96)
        at com.google.android.exoplayer2.analytics.PlaybackStatsListener.onPlayerStateChanged(PlaybackStatsListener.java:242)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.onPlayerStateChanged(AnalyticsCollector.java:447)
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$setPlayWhenReady$0(ExoPlayerImpl.java:277)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$fmq0mZ64J-x_eCNhM7DubT3eF70.invokeListener(Unknown Source:15)
        at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
        at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$notifyListeners$6(ExoPlayerImpl.java:726)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$DrcaME6RvvSdC72wmoYPUB4uP5w.run(Unknown Source:4)
        at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
        at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:726)
        at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:274)
        at com.google.android.exoplayer2.SimpleExoPlayer.updatePlayWhenReady(SimpleExoPlayer.java:1526)
        at com.google.android.exoplayer2.SimpleExoPlayer.setPlayWhenReady(SimpleExoPlayer.java:1201)
        at com.google.android.exoplayer2.demo.PlayerActivity.initializePlayer(PlayerActivity.java:398)
        at com.google.android.exoplayer2.demo.PlayerActivity.onStart(PlayerActivity.java:238)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7348)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3137)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7037)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

### [REQUIRED] Reproduction steps
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app
or a small sample app that you’re able to share as source code on GitHub.

### [REQUIRED] Link to test content
Provide a JSON snippet for the demo app’s media.exolist.json file, or a link to
media that reproduces the issue. If you don't wish to post it publicly, please
submit the issue, then email the link to dev.exoplayer@gmail.com using a subject
in the format "Issue #1234", where "#1234" should be replaced with your issue
number. Provide all the metadata we'd need to play the content like drm license
urls or similar. If the content is accessible only in certain countries or
regions, please say so.

### [REQUIRED] Version of ExoPlayer being used

2.11.3

### [REQUIRED] Device(s) and version(s) of Android being used
Galaxy s10e Android 9

**Comment by andrewlewis** [comment]
Thanks for reporting this. We will push a fix soon.
