### ISSUE TITLE
4K(2160 resolution) video is not playing 

### ISSUE THREAD

**Issue by pprateek786** [google/ExoPlayer#717]
Hello,
I am trying to play 4k or Ultrahd video but it is not playing in DemoPlayer.The error log 

```
01-01 11:15:01.141  17143-17143/ com.test E/EventLogger﹕ internalError [0.08, rendererInitError]
    java.lang.IllegalStateException: No variants selected.
            at  com.test.media.player.support.exoplayer.HlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(HlsRendererBuilder.java:146)
            at  com.test.media.player.support.exoplayer.HlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(HlsRendererBuilder.java:85)
            at com.google.android.exoplayer.util.ManifestFetcher$SingleFetchHelper.onLoadCompleted(ManifestFetcher.java:369)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
01-01 11:15:01.143  17143-17143/ com.test D/EventLogger﹕ end [0.08]
01-01 11:15:01.165  17143-17143/ com.test E/EventLogger﹕ playerFailed [0.10]
    java.lang.IllegalStateException: No variants selected.
            at  com.test.media.player.support.exoplayer.HlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(HlsRendererBuilder.java:146)
            at  com.test.media.player.support.exoplayer.HlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(HlsRendererBuilder.java:85)
            at com.google.android.exoplayer.util.ManifestFetcher$SingleFetchHelper.onLoadCompleted(ManifestFetcher.java:369)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Arqu** [comment]
Take a look at HlsChunkSource constructor. There you will find:
```
this.maxWidth = maxWidth > 0 ? maxWidth : 1920;
this.maxHeight = maxHeight > 0 ? maxHeight : 1080;
```

Which limits the variants to that resolution. Probably since your resolution is too high it is never counted as a variant and playback fails.

**Comment by IanDBird** [comment]
I was going to suggest that the playlist variants are being filtered here: https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/HlsRendererBuilder.java#L141

This then internally calls this: https://github.com/google/ExoPlayer/blob/b3bf8fea20c1e82abef9a9a2699b3d7147672dd3/library/src/main/java/com/google/android/exoplayer/chunk/VideoFormatSelectorUtil.java#L98.

My guess is that you're trying to play a 4K video via HLS on a device which reports a lower H264 supported level and therefore that single 4K resolution variant is being filtered out.

**Comment by ojw28** [comment]
Probably working as intended due to the reasons above.

**Comment by pprateek786** [comment]
So, It is not possible to play 4k video in Exoplayer

**Comment by IanDBird** [comment]
I can play 4K video using ExoPlayer, but only on devices which actually support decoding 4K video (e.g. the Nvidia Shield, Sony's new 4K Android TVs, etc). What specific device are you testing on?

**Comment by pprateek786** [comment]
I am playing single bitrate HLS Video.

While I am playing on Exoplayer 1.2.3. its working fine but When i try to play on Exoplayer 1.3.3. I got Array out of bound exception but in Exoplayer 1.4.2 that expcetion is handled on HLS RenderBuilder Class.

 if (manifest instanceof HlsMasterPlaylist) {
HlsMasterPlaylist masterPlaylist = (HlsMasterPlaylist) manifest;
try {
variantIndices = VideoFormatSelectorUtil.selectVideoFormatsForDefaultDisplay(
context, masterPlaylist.variants, null, false);
} catch (DecoderQueryException e) {
player.onRenderersError(e);
return;
}
if (variantIndices.length == 0) {
player.onRenderersError(new IllegalStateException("No variants selected."));
return;
}
This time variantIndices Length is zero  and it go to OnError. ? May be new exoplayer not support single bitrate HLS Video Streaming but How its playing  in previous 1.2.2 version . I am little bit confused ? can you please help e out

**Comment by pprateek786** [comment]
Any update regarding the issue?

**Comment by ojw28** [comment]
What device are you attempting playback on? Please provide detailed information as listed [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html).

**Comment by pprateek786** [comment]
The 4k content is playing fine with the latest Exo Player 1.5.3 .I have tested 4K video on Shield TV.
