### ISSUE TITLE
MP4 will not start playback from URL stream on Fire TV OS 5.2.7.3

### ISSUE THREAD

**Issue by avstreamdevpro** [google/ExoPlayer#7172]
### [REQUIRED] Issue description

MP4 will not start playback from URL stream.

It plays on mobile and Fire TV OS 6+. But not working on Fire TV OS 5.2

I think exoplayer can support Android 4.1+.

https://exoplayer.dev/supported-devices.html

### [REQUIRED] Reproduction steps

Attempt playing mp4 on Fire TV OS 5.2.7.3 using Exoplayer or Amazon Port Exoplayer.
Not playing and get an error message.

### [REQUIRED] Link to test content

Will post mp4 url to email listed.

### [REQUIRED] A full bug report captured from the device

```
04-01 11:19:54.647 13190-13405/org.test.testtv E/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] configureCodec returning error -2147483648
04-01 11:19:54.647 13190-13405/org.test.testtv E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
04-01 11:19:54.647 13190-13404/org.test.testtv E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 3
04-01 11:19:54.650 13190-13220/org.test.testtv E/MediaCodec: configure failed with err 0x80001001, resetting...
04-01 11:19:54.686 13190-13220/org.test.testtv E/ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(1, null, null, video/avc, null, -1, null, [3840, 1608, 23.97602], [-1, -1]), rendererSupport=NO_EXCEEDS_CAPABILITIES
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.AVC, Format(1, null, null, video/avc, null, -1, null, [3840, 1608, 23.97602], [-1, -1])
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:561)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1249)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:756)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:810)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:709)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.AVC, Format(1, null, null, video/avc, null, -1, null, [3840, 1608, 23.97602], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:863)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:559)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1249) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:756) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:810) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:709) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: android.media.MediaCodec$CodecException: Error 0x80001001
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:599)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:689)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:924)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:856)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:559) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1249) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:756) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:810) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:709) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

### [REQUIRED] Version of ExoPlayer being used
2.11.3

### [REQUIRED] Device(s) and version(s) of Android being used
Fire TV OS 5.2.7.3 - Android API 22

**Comment by andrewlewis** [comment]
It looks like the device just doesn't support decoding this 4k stream (`Renderer error: index=0, type=video, format=Format(1, null, null, video/avc, null, -1, null, [3840, 1608, 23.97602], [-1, -1]), rendererSupport=NO_EXCEEDS_CAPABILITIES`). As this is a FireTV device, Amazon may be able to comment further on what level of support for decoding this format can be expected, to determine whether this is working as intended.

**Comment by hears** [comment]
before when I input a wrong URL. have get same error... maybe you try

**Comment by avstreamdevpro** [comment]
It seems the device just doesn't support decoding 4k stream.
And it also doesn't support 1080p videos.
So I changed into lower resolution videos, and then it works.
