### ISSUE TITLE
IndexOutOfBoundsException - while checking if media isLive

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#7175]
Hi,

While checking the isLive new API  
in the Demo app in v2.11.3 version I get this exception after executing the below code.
running this on Pixel 3 android 10

No sure what is the best approach here but I was expecting to get false
unless it should be called only after player is READY

is there a way to add api that checks is there is a window  before calling get, so this  case can be checked before accessing the window?

do you think I should stick to our current logic that uses -  `player.isCurrentWindowDynamic()`
```
     player.prepare(mediaSource, !haveStartPosition, false);
    boolean isLive = false;
    
    if (player.getCurrentTimeline() != null) {
      isLive = player.getCurrentTimeline().getWindow(player.getCurrentWindowIndex(), new Timeline.Window()).isLive;
    }
```

10x
Gilad.

2020-04-02 18:02:19.419 13123-13123/com.google.android.exoplayer2.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.exoplayer2.demo, PID: 13123
    java.lang.IndexOutOfBoundsException
        at com.google.android.exoplayer2.Timeline$1.getWindow(Timeline.java:550)
        at com.google.android.exoplayer2.Timeline.getWindow(Timeline.java:668)
        at com.google.android.exoplayer2.demo.PlayerActivity.initializePlayer(PlayerActivity.java:412)
        at com.google.android.exoplayer2.demo.PlayerActivity.onStart(PlayerActivity.java:240)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
        at android.app.Activity.performStart(Activity.java:7848)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by andrewlewis** [comment]
You can check `timeline.getWindowCount()` or `timeline.isEmpty()`.

**Comment by tonihei** [comment]
Actually, the preferred way to check if media is live is to use `player.isCurrentWindowLive()`.  This already includes the check Andrew mentioned above.

**Comment by giladna** [comment]
thanks!
