### ISSUE TITLE
HttpDataSource$HttpDataSourceException over local network

### ISSUE THREAD

**Issue by phanirithvij** [google/ExoPlayer#7246]
### [REQUIRED] Searched documentation and issues
None. This seems like a bug to me but I'm not sure.

### [REQUIRED] Question
My setup is a PC that is connected to my android device's mobile hotspot.
I'm serving a sample video file from a python flask server on my pc.
I'm trying to play it in my flutter app using the `video_player` plugin and the app is the example app provided here [in the official page](https://pub.dev/packages/video_player#-readme-tab-).
I get an error `com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException`.
So it must be an issue with exoplayer but not the flutter plugin.

**I tried to play the video `http://192.168.43.159:3000/files/solo.mp4` on my android device on the browser and it PLAYED the video successfully** [Screenshot](https://res.cloudinary.com/rootworld/image/upload/v1587047474/screenshot.jpg)

But from the app, it does not.

I have `<uses-permission android:name="android.permission.INTERNET" />` on my manifest.

I'm attaching this in the hope it can be reproduced.

```shell
pip install flask
```

```python
import os
from flask import Flask, send_from_directory, send_file

app = Flask(__name__)

@app.route('/files/<path:filename>')
def download_file(filename):
    return send_from_directory(app.config['UPLOAD_FOLDER'], filename)

if __name__ == '__main__':
    upload_folder = os.path.join(os.getcwd(), 'files')
    print("Place your files here", upload_folder)
    app.config['UPLOAD_FOLDER'] = upload_folder
    try:
        os.makedirs(app.config['UPLOAD_FOLDER'])
    except Exception as e:
        print(e)
    app.run(host='0.0.0.0', port=3000, debug=True)
```

On my windows machine the third IP is the wifi address that I can access from my mobile.
```
λ ipconfig.exe | grep IPv4
   IPv4 Address. . . . . . . . . . . : 192.168.56.1
   IPv4 Address. . . . . . . . . . . : 192.168.99.1
   IPv4 Address. . . . . . . . . . . : 192.168.43.159
   IPv4 Address. . . . . . . . . . . : 192.168.137.1
```

And there is no issue with the flask server as

```shell
λ curl -i http://192.168.43.159:3000/files/solo.mp4
HTTP/1.0 200 OK
Content-Length: 7260663
Content-Type: video/mp4
Last-Modified: Tue, 14 Jan 2020 18:56:44 GMT
Cache-Control: public, max-age=43200
Expires: Fri, 17 Apr 2020 02:18:29 GMT
ETag: "1579028204.3614361-7260663-1450905606"
Date: Thu, 16 Apr 2020 14:18:29 GMT
Accept-Ranges: bytes
Server: Werkzeug/0.16.0 Python/3.8.0

Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
```

### A full bug report captured from the device
```java
Restarted application in 2,088ms.
I/ExoPlayerImpl(20949): Release 8286f5b [ExoPlayerLib/2.9.6] [RMX1971, RMX1971, realme, 29] [goog.exo.core]
E/libc    (20949): Access denied finding property "persist.report.tid"
I/ExoPlayerImpl(20949): Init cec51d4 [ExoPlayerLib/2.9.6] [RMX1971, RMX1971, realme, 29]
E/AccessibilityBridge(20949): VirtualView node must not be the root node.
E/ExoPlayerImplInternal(20949): Source error.
E/ExoPlayerImplInternal(20949): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://192.168.43.159:3000/files/solo.mp4
E/ExoPlayerImplInternal(20949): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
E/ExoPlayerImplInternal(20949): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(20949): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal(20949): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(20949): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(20949): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(20949): 	at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal(20949): Caused by: java.io.IOException: Cleartext HTTP traffic to 192.168.43.159 not permitted
E/ExoPlayerImplInternal(20949): 	at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:124)
E/ExoPlayerImplInternal(20949): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
E/ExoPlayerImplInternal(20949): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/ExoPlayerImplInternal(20949): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:528)
E/ExoPlayerImplInternal(20949): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:444)
E/ExoPlayerImplInternal(20949): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
E/ExoPlayerImplInternal(20949): 	... 6 more
E/flutter (20949): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://192.168.43.159:3000/files/solo.mp4, null)
E/flutter (20949): null
```

### Link to test content

[solo.mp4](https://res.cloudinary.com/rootworld/video/upload/v1587047471/solo.mp4) 6.92MB

**Comment by phanirithvij** [comment]
The weird behavior is I can access the video URL from the browser, vlc, and all the other apps except the flutter app that I'm building.

**Comment by icbaker** [comment]
I think this is relevant: `Cleartext HTTP traffic to 192.168.43.159 not permitted`

There's some info about that here: https://exoplayer.dev/troubleshooting.html#fixing-cleartext-http-traffic-not-permitted-errors
