### ISSUE TITLE
AudioSink$InitializationException on Sony TV for AAC/5.1/48kHz with tunneling enabled

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#7274]
### [REQUIRED] Searched documentation and issues
`DefaultAudioSink` source code.

### [REQUIRED] Question
According to crashlytics I'm getting some `AudioSink$InitializationException`. Usually on Sony TVs (60%, while it's 10% from all devices).
One specific report is:

```
timeline [eventTime=0.13, mediaPos=48.72, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
  period [?]
  window [78.00, true, true]
]
decoderEnabled [eventTime=0.22, mediaPos=48.72, window=0, period=0, video]
decoderEnabled [eventTime=0.24, mediaPos=48.72, window=0, period=0, audio]
tracks [eventTime=0.24, mediaPos=48.72, window=0, period=0
  MediaCodecVideoRenderer [
    Group:0, adaptive_supported=N/A [
      [X] Track:0, id=0, mimeType=video/avc, codecs=avc1.640028, res=1920x1080, supported=YES
    ]
  ]
  FfmpegAudioRenderer []
  MediaCodecAudioRenderer [
    Group:0, adaptive_supported=N/A [
      [X] Track:0, id=1/257, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=6, sample_rate=48000, supported=YES
    ]
  ]
  FfmpegAudioRenderer []
  TextRenderer [
    Group:0, adaptive_supported=N/A [
      [ ] Track:0, id=1/8448, mimeType=application/cea-608, supported=YES
    ]
  ]
  MetadataRenderer [
    Group:0, adaptive_supported=N/A [
      [X] Track:0, id=null, mimeType=application/id3, supported=YES
    ]
  ]
  CameraMotionRenderer []
]
downstreamFormat [eventTime=0.29, mediaPos=48.72, window=0, period=0, id=0, mimeType=null]
decoderInitialized [eventTime=0.51, mediaPos=48.72, window=0, period=0, video, OMX.MTK.VIDEO.DECODER.AVC]
decoderInputFormat [eventTime=0.51, mediaPos=48.72, window=0, period=0, video, id=0, mimeType=video/avc, codecs=avc1.640028, res=1920x1080]
decoderInitialized [eventTime=0.64, mediaPos=48.72, window=0, period=0, audio, OMX.google.aac.decoder]
decoderInputFormat [eventTime=0.64, mediaPos=48.72, window=0, period=0, audio, id=1/257, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=6, sample_rate=48000]
playerFailed [eventTime=0.78, mediaPos=48.72, window=0, period=0
  com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=2, format=Format(1/257, null, null, audio/mp4a-latm, mp4a.40.2, -1, null, [-1, -1, -1.0], [6, 48000]), format_supported=YES
      at e.e.a.b.v.a(BaseRenderer.java:30)
      at e.e.a.b.d1.y.a(MediaCodecAudioRenderer.java:134)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.b(MediaCodecRenderer.java:56)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.a(MediaCodecRenderer.java:35)
      at e.e.a.b.c0.a(ExoPlayerImplInternal.java:219)
      at e.e.a.b.c0.handleMessage(ExoPlayerImplInternal.java:24)
      at android.os.Handler.dispatchMessage(Handler.java:101)
      at android.os.Looper.loop(Looper.java:164)
      at android.os.HandlerThread.run(HandlerThread.java:65)
  Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 196992)
      at com.google.android.exoplayer2.audio.DefaultAudioSink.a(DefaultAudioSink.java:191)
      at e.e.a.b.d1.y.a(MediaCodecAudioRenderer.java:131)
      ... 7 more
```
This one was produced for 5.1 48kHz AAC track, when tunneling was enabled.
Disabling tunneling - fixes the issue.

**Q:** So, what is designed way to handle this kind of behavior from perspective of player->exoplayer?

It looks like, player should retry, with no-tunneling fallback option. Is it correct?
Or maybe with different decoder priority - sony has 2 codecs for `audio/mp4a-latm`:  `OMX.google.aac.decoder`, `OMX.MTK.AUDIO.DECODER.DSPAAC`?

**Q:** Are there any other reasons when track initialization can fail?

As commented in chromium (https://chromium.googlesource.com/chromium/src/media/+/95cd25a8fa3397d4d84232ebdc8fbb554f14afec/base/android/java/src/org/chromium/media/AudioTrackOutputStream.java#183), track won't be initialized, if connected audio does not support it (AC3 for ex.). 

Is it covered by `RendererCapabilities.FormatSupport`? Or player should retry with ffmpeg fallback (for ac3/aac/dts/...)?

### A full bug report captured from the device
Do not own a device. Reported by user.

### Link to test content
* https://drive.google.com/open?id=1TRdi02m_S9wUlt9AZCe5U2zaV2XxwV1I (dumped HLS with chunks/manifest)

**Comment by kim-vde** [comment]
We should first try to understand why the audio track is not initialized. Tunneling should be automatically disabled if it is not supported and the audio track shouldn’t be created if the format is not supported. I suspect it is due to another reason.

What version of ExoPlayer are you using? Do you know what is the SDK version of the device? Does the device support tunneling?
How do you enable tunneling? More particularly, how do you generate the audio session ID?

**Comment by stari4ek** [comment]
Device:
```
System: 3.10.79 (665451)
Sdk: 26
Device: BRAVIA_ATV3_4K
Product: BRAVIA_ATV3_4K_EU
Manufacturer: Sony
Model: BRAVIA 4K GB ATV3
```

List of codecs:
```
  video/3gpp [OMX.MTK.VIDEO.DECODER.H263, OMX.google.h263.decoder (adaptive)]
  video/avc [OMX.MTK.VIDEO.DECODER.AVC (adaptive) (tunneling), OMX.google.h264.decoder (adaptive)]
  video/hevc [OMX.MTK.VIDEO.DECODER.HEVC (adaptive) (tunneling), OMX.google.hevc.decoder (adaptive)]
  video/x-vnd.on2.vp8 [OMX.MTK.VIDEO.DECODER.VP8 (adaptive), OMX.google.vp8.decoder (adaptive)]
  video/x-vnd.on2.vp9 [OMX.MTK.VIDEO.DECODER.VP9 (adaptive) (tunneling), OMX.google.vp9.decoder (adaptive)]
  video/mp4v-es [OMX.MTK.VIDEO.DECODER.MPEG4, OMX.google.mpeg4.decoder (adaptive)]
  video/mpeg2 [OMX.MTK.VIDEO.DECODER.MPEG2, OMX.google.mpeg2.decoder (adaptive)]
  video/dolby-vision [OMX.dolby.vision.dvhe.stn.decoder (adaptive) (tunneling)]
  audio/mp4a-latm [OMX.google.aac.decoder, OMX.MTK.AUDIO.DECODER.DSPAAC]
  audio/mpeg [OMX.google.mp3.decoder]
  audio/mpeg-L1 [OMX.MTK.AUDIO.DECODER.DSPMP1]
  audio/mpeg-L2 [OMX.MTK.AUDIO.DECODER.DSPMP2]
  audio/raw [OMX.google.raw.decoder]
  audio/g711-alaw [OMX.google.g711.alaw.decoder, OMX.MTK.AUDIO.DECODER.DSPLPCMALAW]
  audio/g711-mlaw [OMX.google.g711.mlaw.decoder, OMX.MTK.AUDIO.DECODER.DSPLPCMMLAW]
  audio/ac3 [OMX.MTK.AUDIO.DECODER.DSPAC3]
  audio/eac3 [OMX.MTK.AUDIO.DECODER.DSPEAC3]
  audio/vnd.dts [OMX.MTK.AUDIO.DECODER.DSPDTS]
  audio/vorbis [OMX.google.vorbis.decoder]
  audio/opus [OMX.google.opus.decoder]
  audio/3gpp [OMX.google.amrnb.decoder]
  audio/amr-wb [OMX.google.amrwb.decoder]
```

ExoPlayer: 7214ad2d6f9d1e1c13649f2fb4b085ef746f0c3e (it's nearly HEAD from dev-v2)

Tunneling is supported, since there're codecs with tunneling, including `OMX.MTK.VIDEO.DECODER.AVC` used in the example.

```java

DefaultTrackSelector trackSelector = new DefaultTrackSelector(context);

DefaultTrackSelector.ParametersBuilder paramsBuilder =
    new DefaultTrackSelector.ParametersBuilder(context);

if (tunneling) {
    int tunnelingAudioSessionId = C.generateAudioSessionIdV21(context);
    paramsBuilder.setTunnelingAudioSessionId(tunnelingAudioSessionId);
}

trackSelector.setParameters(paramsBuilder.build());
```

According to the log, for same user/device/settings, there is no issues for same type of stream, but with AAC 2.0, 44.1kHz:

```
110 21:02:25.347|main|D] EventLogger: decoderInitialized [eventTime=0.56, mediaPos=51.96, window=0, period=0, video, OMX.MTK.VIDEO.DECODER.AVC]
110 21:02:25.350|main|D] EventLogger: decoderInputFormat [eventTime=0.56, mediaPos=51.96, window=0, period=0, video, id=0, mimeType=video/avc, codecs=avc1.640028, res=1920x1080]
110 21:02:25.409|main|D] EventLogger: decoderInitialized [eventTime=0.62, mediaPos=51.96, window=0, period=0, audio, OMX.google.aac.decoder]
110 21:02:25.414|main|D] EventLogger: decoderInputFormat [eventTime=0.63, mediaPos=51.96, window=0, period=0, audio, id=1/257, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=44100]
```

**Comment by andrewlewis** [comment]
Sorry for the delay.

It should be possible for you to implement retrying at the application level in case you want to disable tunneling and/or switch to on-device decoding.

On `dev-v2` we now retry audio track initialization (see #7042) which may help with this. Without a bug report I don't think we will be able to make more progress diagnosing this.
