### ISSUE TITLE
Play M3U8 File Error

### ISSUE THREAD

**Issue by 951AB159BA** [google/ExoPlayer#7310]
```
2020-04-29 19:02:32.656 7771-8367/com.umeye.demo E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.ParserException: Loading finished before preparation is complete.
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.maybeThrowPrepareError(HlsSampleStreamWrapper.java:259)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.maybeThrowPrepareError(HlsMediaPeriod.java:164)
        at com.google.android.exoplayer2.source.MaskingMediaPeriod.maybeThrowPrepareError(MaskingMediaPeriod.java:139)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:619)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by christosts** [comment]
Please consider providing more information as requested in the issue template which can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md), in this case we'd need the exoplayer version and a sample m3u8 file.

If you're unable to share content publicly please send an email to dev.exoplayer@gmail.com with the subject "Issue #7310".

**Comment by 951AB159BA** [comment]
> 
> 
> Please consider providing more information as requested in the issue template which can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md), in this case we'd need the exoplayer version and a sample m3u8 file.
> 
> If you're unable to share content publicly please send an email to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with the subject "Issue #7310".

Hello,
the file's link is here.
[playlist(2).zip](https://github.com/google/ExoPlayer/files/4585195/playlist.2.zip)
Its version is '2.11.3'

**Comment by christosts** [comment]
The playlist data are currently returning an HTTP 403, can you please check if the stream is still available?

**Comment by 951AB159BA** [comment]
> 
> 
> Since there haven't been any recent updates here, I am going to close this issue.
> 
> @951AB159BA if you're still experiencing this problem and want to continue the discussion just leave a comment here and we are happy to re-open this.

Ok. Thank you.

**Comment by dryganets** [comment]
My 5 cents:
`Loading finished before preparation is complete` usually happens for the cases when track atom hasn't been found in the MP4.

ExoPlayer has a very strict media parsing state machine as it is implemented according to the Apple's quicktime specification. If atom size is set to 0 it is treated as it lasts till the end of the file, so every atom after this one will be ignored.

If such an atom exists in the MP4 this file will be playable by the mplayer and vlc but not by QuickTime or ExoPlayer.

I've seen some of those issues in the past as we have a custom MP4 muxer to don't depend on the android platform quirks.

FIY: @ojw28.
