### ISSUE TITLE
Livestream black screen for new android versions (android 10, android 9)

### ISSUE THREAD

**Issue by r1n1os** [google/ExoPlayer#7348]
For some devices I have issue to play livestream. It just showing black screen without sound. 
I debug the code and i have seen that the **avcLevel** is equal to **65536** which is **not included** in the switch statement of **avcLevelToMaxFrameSize()**. 
At the end I am seeing the following error:
**internalError [1.02, rendererInitError]
    java.lang.IllegalStateException: No variants selected.** 

Also, I am using old version of the library version -> 1.5.2
This is an issue that is fixed in the latest versions? 

Full log: 

```
 E/EventLogger: internalError [1.02, rendererInitError]
    java.lang.IllegalStateException: No variants selected.
        at packagename.myplayer.HlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(HlsRendererBuilder.java:142)
        at packagename.myplayer.HlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(HlsRendererBuilder.java:84)
        at com.google.android.exoplayer.util.ManifestFetcher$SingleFetchHelper.onLoadCompleted(ManifestFetcher.java:369)
        at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by ojw28** [comment]
The version you're using is so old that I don't think we can spend time looking at this issue. The easiest way to check is to give your content a try in a recent version of the [demo app](https://exoplayer.dev/demo-application.html).
