### ISSUE TITLE
No stable streaming and "java.net.SocketTimeoutException: timeout"

### ISSUE THREAD

**Issue by Abu-Abdullah** [google/ExoPlayer#7353]
Hi,

I'm facing issues with stability. the below code works for me to stream 3-5 clips, then it hangs and throws:

```
E/MediaService: TYPE_SOURCE: Unable to connect
E/MediaService: httpError.dataSpec: DataSpec[GET http://www.maknoon.com/audios.m4a/alalbani/alnoor/005b.m4a, null, 0, 0, -1, null, 6]
E/MediaService: httpError.getCause(): java.net.SocketTimeoutException: timeout
```

certainly there is no issue with the network or the streaming server. the behavior is exactly the same every time. it works for 5 clips and then it hangs for few minutes and then it works for few clips again. if i destroy the app and restart it again, it will work immediately. i do not recall such behavior when i was using native MediaPlayer without Exoplayer and its classes e.g. PlayerNotificationManager / MediaSessionConnector

any hints is appreciated.

```
public class MediaService extends MediaBrowserServiceCompat implements Player.EventListener
{
	private static final String TAG = "MediaService";

	private static final String MY_MEDIA_ROOT_ID = "media_root_id";
	private static final String MY_EMPTY_MEDIA_ROOT_ID = "empty_root_id";

	private MediaSessionCompat mediaSession;

	static final String Broadcast_saveFavorite = "com.myapp.audiocataloger.saveFavorite";

	@Override
	public void onCreate()
	{
		super.onCreate();

		mediaSession = new MediaSessionCompat(this, TAG);
		mediaSession.setFlags(MediaSessionCompat.FLAG_HANDLES_MEDIA_BUTTONS | MediaSessionCompat.FLAG_HANDLES_TRANSPORT_CONTROLS);

		final PlaybackStateCompat.Builder stateBuilder = new PlaybackStateCompat.Builder().setActions(PlaybackStateCompat.ACTION_PLAY | PlaybackStateCompat.ACTION_PLAY_PAUSE | PlaybackStateCompat.ACTION_STOP);
		mediaSession.setPlaybackState(stateBuilder.build());

		setSessionToken(mediaSession.getSessionToken());
		setUpPlayer();
	}

	static SimpleExoPlayer mediaPlayer;
	PlayerNotificationManager playerNotificationManager;
	static boolean serviceStarted = false;
	MediaSessionConnector mediaSessionConnector;

	final AudioAttributes attr = new AudioAttributes.Builder()
			.setUsage(C.USAGE_MEDIA)
			.setContentType(C.CONTENT_TYPE_SPEECH)
			.build();

	private void setUpPlayer()
	{
		mediaPlayer = new SimpleExoPlayer.Builder(this).build();
		mediaPlayer.addListener(this);
		mediaPlayer.setWakeMode(C.WAKE_MODE_LOCAL);
		mediaPlayer.setVolume(1.0f);
		mediaPlayer.setAudioAttributes(attr, true); // In 2.9.X you don't need to manually handle audio focus (onAudioFocusChange)

		mediaSessionConnector = new MediaSessionConnector(mediaSession);
		mediaSessionConnector.setPlayer(mediaPlayer);
		mediaSessionConnector.setPlaybackPreparer(new MediaSessionConnectorCallback());
		mediaSessionConnector.setControlDispatcher(new MediaControlDispatcher());

		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O)
		{
			final NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
			if (notificationManager != null)
			{
				final NotificationChannelGroup group = new NotificationChannelGroup(getString(R.string.default_notification_group_id), getString(R.string.default_notification_group_name));
				notificationManager.createNotificationChannelGroup(group);
				if (notificationManager.getNotificationChannel(getString(R.string.default_notification_channel_id)) == null)
				{
					final NotificationChannel channel = new NotificationChannel(getString(R.string.default_notification_channel_id), getString(R.string.default_notification_channel_name), NotificationManager.IMPORTANCE_DEFAULT);
					channel.setSound(null, null);
					channel.setGroup(getString(R.string.default_notification_group_id));
					notificationManager.createNotificationChannel(channel);
				}
			}
		}

		playerNotificationManager = new PlayerNotificationManager(
				this,
				getString(R.string.default_notification_channel_id),
				1,
				new DescriptionAdapter(),
				new PlayerNotificationManager.NotificationListener()
				{
					@Override
					public void onNotificationPosted(int notificationId, Notification notification, boolean ongoing)
					{
						if(ongoing) // play
						{
							// Avoid starting service many times
							if(!serviceStarted)
							{
								serviceStarted = true;
								if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O)
									startForegroundService(new Intent(MediaService.this, MediaService.class));
								else
									startService(new Intent(MediaService.this, MediaService.class));
							}

							startForeground(notificationId, notification);
							LocalBroadcastManager.getInstance(MediaService.this).registerReceiver(noisyReceiver, intentFilter);
						}
						else // pause
						{
							stopForeground(false); // It works here only
							try { LocalBroadcastManager.getInstance(MediaService.this).unregisterReceiver(noisyReceiver); }
							catch (IllegalArgumentException e) { e.printStackTrace(); }
						}
					}

					@Override
					public void onNotificationCancelled(int notificationId, boolean dismissedByUser)
					{
						serviceStarted = false;

						mediaPlayer.stop(true);

						stopForeground(true); // Take the service out of the foreground
						stopSelf();

						if(dismissedByUser)
							Log.v(TAG, "User swipe the notification");

						try { LocalBroadcastManager.getInstance(MediaService.this).unregisterReceiver(noisyReceiver); }
						catch (IllegalArgumentException e) { e.printStackTrace(); }
					}
				});

		playerNotificationManager.setMediaSessionToken(mediaSession.getSessionToken());
		playerNotificationManager.setPlayer(mediaPlayer);
	}

	private class DescriptionAdapter implements PlayerNotificationManager.MediaDescriptionAdapter
	{
		@NonNull @Override
		public String getCurrentContentTitle(@NonNull Player player)
		{
			//final MediaControllerCompat controller = mediaSession.getController();
			//final MediaMetadataCompat mediaMetadata = controller.getMetadata();
			//final MediaDescriptionCompat description = mediaMetadata.getDescription(); // TODO: description = null all the time except the very first time it is triggered
			//Log.v(TAG, "description " + description);
			return title;
		}

		@Nullable @Override
		public String getCurrentContentText(@NonNull Player player)
		{
			return subTitle;
		}

		@Nullable @Override
		public Bitmap getCurrentLargeIcon(@NonNull Player player, @NonNull PlayerNotificationManager.BitmapCallback callback)
		{
			return BitmapFactory.decodeResource(getApplicationContext().getResources(), R.mipmap.ic_launcher);
		}

		@Nullable @Override
		public PendingIntent createCurrentContentIntent(@NonNull Player player)
		{
			final Intent intent = new Intent(MediaService.this, MainActivity.class);
			final PendingIntent contentIntent = PendingIntent.getActivity(MediaService.this, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);
			return contentIntent;
		}
	}
	
	public static class MediaControlDispatcher implements ControlDispatcher
	{
		@Override
		public boolean dispatchSetPlayWhenReady(@NonNull Player player, boolean playWhenReady)
		{
			player.setPlayWhenReady(playWhenReady);
			return true;
		}

		@Override
		public boolean dispatchSeekTo(Player player, int windowIndex, long positionMs)
		{
			player.seekTo(windowIndex, positionMs);
			return true;
		}

		@Override
		public boolean dispatchSetRepeatMode(Player player, @Player.RepeatMode int repeatMode)
		{
			player.setRepeatMode(repeatMode);
			return true;
		}

		@Override
		public boolean dispatchSetShuffleModeEnabled(Player player, boolean shuffleModeEnabled)
		{
			player.setShuffleModeEnabled(shuffleModeEnabled);
			return true;
		}

		@Override
		public boolean dispatchStop(@NonNull Player player, boolean reset)
		{
			player.stop(reset);
			return true;
		}
	}

	@Override
	public BrowserRoot onGetRoot(@NonNull String clientPackageName, int clientUid, Bundle rootHints)
	{
		if (TextUtils.equals(clientPackageName, getPackageName()))
			return new BrowserRoot(MY_MEDIA_ROOT_ID, null);
		else
			return new BrowserRoot(MY_EMPTY_MEDIA_ROOT_ID, null);
	}

	@Override
	public void onLoadChildren(@NonNull final String parentMediaId, @NonNull final Result<List<MediaItem>> result)
	{
		if (TextUtils.equals(MY_EMPTY_MEDIA_ROOT_ID, parentMediaId))
		{
			result.sendResult(null);
			return;
		}

		final List<MediaItem> mediaItems = new ArrayList<>();
		result.sendResult(mediaItems);
	}

	private static final IntentFilter intentFilter = new IntentFilter(AudioManager.ACTION_AUDIO_BECOMING_NOISY);
	class MediaSessionConnectorCallback implements MediaSessionConnector.PlaybackPreparer
	{
		@Override
		public void onPrepare(boolean playWhenReady)
		{
		}

		@Override
		public void onPrepareFromMediaId(@NonNull String mediaId, boolean playWhenReady, @NonNull Bundle extras)
		{
		}

		@Override
		public void onPrepareFromSearch(@NonNull String query, boolean playWhenReady, @NonNull Bundle extras)
		{
		}

		@Override
		public void onPrepareFromUri(@NonNull Uri uri, boolean playWhenReady, @NonNull Bundle extras)
		{
		}

		@Override
		public long getSupportedPrepareActions()
		{
			long actions = PlaybackStateCompat.ACTION_PLAY
					| PlaybackStateCompat.ACTION_PLAY_PAUSE
					| PlaybackStateCompat.ACTION_STOP;
			if (mediaPlayer.getPlayWhenReady())
				actions |= PlaybackStateCompat.ACTION_PAUSE;
			return actions;
		}

		@Override
		public boolean onCommand(@NonNull Player player, @NonNull ControlDispatcher controlDispatcher, @NonNull String command, @Nullable Bundle extras, @Nullable ResultReceiver cb)
		{
			command(command, extras);
			return true;
		}
	}

	String title, subTitle;
	void command(String command, Bundle extras)
	{
		if (command.equals("play"))
		{
			title = "\u200e" + extras.getString("title"); // we put LTR mark since subTitle cannot be changed to RTL using Mark '\u200f'
			subTitle = "\u200e" + extras.getString("subTitle");
			final String url = extras.getString("url");
			final int offset = extras.getInt("offset");
			exo_play(url, offset);
		}
	}

	void exo_play(String url, int offset)
	{
		playerNotificationManager.setPlayer(null);

		final DataSource.Factory dataSourceFactory = new DefaultHttpDataSourceFactory(
				Util.getUserAgent(this, getString(R.string.app_name)),
				DEFAULT_CONNECT_TIMEOUT_MILLIS, DEFAULT_READ_TIMEOUT_MILLIS, true); // Both timeout is 8000

		final MediaSource videoSource = new ProgressiveMediaSource.Factory(dataSourceFactory)
				/* Useless, no value, still getting java.net.SocketTimeoutException: timeout
				.setLoadErrorHandlingPolicy(new DefaultLoadErrorHandlingPolicy()
				{
					@Override
					public int getMinimumLoadableRetryCount(int dataType)
					{
						return 0;
						/*
						if(dataType == C.DATA_TYPE_MEDIA_PROGRESSIVE_LIVE)
							return DEFAULT_MIN_LOADABLE_RETRY_COUNT_PROGRESSIVE_LIVE; // 6
						else
							return DEFAULT_MIN_LOADABLE_RETRY_COUNT; // 3
						*
					}
				})
				*/
				.createMediaSource(Uri.parse(url));

		mediaPlayer.setPlayWhenReady(true);

		if (offset != 0)
		{
			mediaPlayer.seekTo(offset);
			mediaPlayer.prepare(videoSource, false, true);
		}
		else
			// Prepare the player with the source
			mediaPlayer.prepare(videoSource, true, true);

		playerNotificationManager.setPlayer(mediaPlayer);
	}

	private final BroadcastReceiver noisyReceiver = new BroadcastReceiver()
	{
		@Override
		public void onReceive(Context context, Intent intent)
		{
			mediaSession.getController().getTransportControls().pause();
		}
	};

	@Override
	public void onPlayerError(ExoPlaybackException error)
	{
		switch (error.type)
		{
			case ExoPlaybackException.TYPE_SOURCE:
			{
				final IOException cause = error.getSourceException();
				Log.e(TAG, "TYPE_SOURCE: " + cause.getMessage());
				if (cause instanceof HttpDataSourceException)
				{
					final HttpDataSourceException httpError = (HttpDataSourceException) cause;

					Log.e(TAG, "httpError.dataSpec: " + httpError.dataSpec);

					if (httpError instanceof HttpDataSource.InvalidResponseCodeException)
					{
						final HttpDataSource.InvalidResponseCodeException ex = (HttpDataSource.InvalidResponseCodeException) httpError;
						Log.e(TAG, "Http error during playback: " + ex.responseCode);

						final Throwable innerCause = httpError.getCause();
						if (innerCause != null)
							Log.e(TAG, "innerCause.getMessage(): " + innerCause.getMessage());
					}
					else
						Log.e(TAG, "httpError.getCause(): " + httpError.getCause());
				}
				else
					Log.e(TAG, "Error: " + error.toString());
			}
			break;
			case ExoPlaybackException.TYPE_RENDERER:
				Log.e(TAG, "TYPE_RENDERER: " + error.getRendererException().getMessage());
				break;
			case ExoPlaybackException.TYPE_UNEXPECTED:
				Log.e(TAG, "TYPE_UNEXPECTED: " + error.getUnexpectedException().getMessage());
				break;
			case ExoPlaybackException.TYPE_OUT_OF_MEMORY:
				Log.e(TAG, "TYPE_OUT_OF_MEMORY: " + error.getUnexpectedException().getMessage());
				break;
			case ExoPlaybackException.TYPE_REMOTE:
				Log.e(TAG, "TYPE_REMOTE: " + error.getUnexpectedException().getMessage());
				break;
		}

		playerNotificationManager.setPlayer(null);
	}

	@Override
	public int onStartCommand(Intent intent, int flags, int startId)
	{
		if(intent != null)
			MediaButtonReceiver.handleIntent(mediaSession, intent);
		return START_NOT_STICKY;
	}

	@Override
	public void onDestroy()
	{
		if (mediaPlayer != null)
		{
			playerNotificationManager.setPlayer(null);
			mediaPlayer.release();
			mediaPlayer = null;
		}

		mediaSession.release();
		super.onDestroy();
	}
}
```

**Comment by Abu-Abdullah** [comment]
it seems that it stuck in ExoPlayer.STATE_BUFFERING for some time. after that it returns to work normal.

the console output has more details:
```
05-11 09:49:37.530 23036-23128/com.myapp.audiocataloger E/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:282)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:956)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.SocketTimeoutException
        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
        at com.android.okhttp.okio.Okio$2.read(Okio.java:140)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310)
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206)
        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:239)
        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:104)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:1120)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:951)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:482)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:540)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:463)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:280)
```

**Comment by Abu-Abdullah** [comment]
Just to eliminate any issue with the native android okhttp, i have used exoplayer:extension-okhttp, the result is the same:
```
05-11 10:41:46.520 28174-28256/com.myapp.audiocataloger E/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:225)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:956)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.SocketTimeoutException
        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:354)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:226)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:220)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:956) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by Abu-Abdullah** [comment]
i have tried many things and read dozens of tracker issues but no clue how to solve this.
i have tried:
- implementing LoadControl/buffers
- playing with OkHttpClient timeout (read/write/protocols ....)
- releasing the player for every clip and all other resources and setup the player for every clip again and again
- monitor the app performance (nothing strange here).

nothing works. i do not know how to release OkHttpClient resource but tried:
- httpClient.dispatcher().executorService().shutdown();
- httpClient.connectionPool().evictAll();
- httpClient.cache().close();

the behavior is the same. i can play 6 clips before it freeze (in buffer state) and throws the above exception.

**Comment by Abu-Abdullah** [comment]
Another output from the console that might be related to this issue:
```
W/AudioTrack: StreamType not music do not upload bigdata
W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 9838
W/AudioFlinger: createTrack_l(): mismatch between requested flags (00000004) and output flags (00000002)
APM_AudioPolicyManager: mIsNewHalPolicy = 1, persist.kirin.media.lowlatency.enable = 0, *flags & AUDIO_OUTPUT_FLAG_FAST = 4
```

**Comment by Abu-Abdullah** [comment]
i tried to use CronetDataSource and i got the same results:
```
2020-05-13 19:51:29.113 15057-15273/com.myapp.audiocataloger E/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: java.net.SocketTimeoutException
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:439)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:956)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.net.SocketTimeoutException
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:439) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:956) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391) 
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 
```
i tried as well the recommendation found [here ](https://medium.com/@leandromazzuquini/if-you-are-using-okhttp-you-should-know-this-61d68e065a2b)of using only one okhttpclient and i made it even static to make sure no leak is happening. again the same result

it seems i run out of options. any hint or support is appreciated

**Comment by ojw28** [comment]
What you're seeing is a socket timeout from the underlying network stack when ExoPlayer makes a request, which mostly rules out this being bug in ExoPlayer. Furthermore, you see the same behaviour with three different underlying network stack implementations, which mostly rules out a bug in any one of the network stacks as well.

Given this, it seems highly like that the issue is with the network connection or the server. I don't really see how the issue could lie anywhere else in this case. Note that debugging such issues is not always that straightforward. For example, your network provider or the server that you're requesting media from may choose to throttle/block some traffic based on its characteristics. Unfortunately, detailed debugging of this kind of thing falls outside the scope of this issue tracker.

If you're able to, I'd suggest you try combinations of requesting media from a different server, using a different network, and possibly using a different type of device. This may help you narrow down the root cause relatively quickly.

**Comment by Abu-Abdullah** [comment]
i tried to sniff the packets (using Packet capture from google store) from 2 versions of my app where i used exoplayer (having this issue) in one of them and the other one with native mediaplayer (which does not have this issue as it seems to me).
the difference between them is mainly:
- exoplayer has additional "Icy-MetaData: 1"
- exoplayer has "Accepted-Encoding: gzip, deflate" where mediaplayer has "Accepted-Encoding: gzip"

**Comment by Abu-Abdullah** [comment]
can i replicate the same packet structure in exoplayer to match the other one. just to see if this will help or not.

after reading your comment, i guess it is the server now who is rejecting the request after 6 times of requesting 6 files (same file of different). the pattern is exactly the same every time. i guess it is a security mechanism that identified my request based on some criteria and reject it after 6 times. after 5 minutes it allows again the same request for another 6 times.

i tried to request the files from a web browser which does not have this as well. you can just listen to as many as you want from different files.

**Comment by Abu-Abdullah** [comment]
i was looking for a way to remove header property with no success. such code didn't work for me:
```
HttpDataSource.RequestProperties s = dataSourceFactory.getDefaultRequestProperties();
s.remove("Icy-MetaData");
```

**Comment by ojw28** [comment]
Sorry, but unless you can demonstrate that there's an issue with ExoPlayer, debugging this is outside the scope of this issue tracker.
