### ISSUE TITLE
Crypto key not available occurs when playing Widevine DASH on a specific device

### ISSUE THREAD

**Issue by ogawa-ma** [google/ExoPlayer#7356]
### Searched documentation and issues
・ExoPlayer Javadoc
・ExoPlayerの問題

### Question
CryptoException occurs when playing Widevine DASH on Android OS8.
Why does it happen?

```
com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Crypto key not available
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1126)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:658)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:251)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.media.MediaCodec$CryptoException: Crypto key not available
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2547)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1117)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:658) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:251) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

使用されているExoPlayerのバージョン：2.10.6

発生したデバイス情報
デバイス名：Xperia XZ 
モデル番号：SOV34
Androidバージョン：8.0.0

### A full bug report captured from the device
I have sent the bugreport to dev.exoplayer@gmail.com.

### Link to test content
I have sent the media file URL and the license server URL to dev.exoplayer@gmail.com.

**Comment by krocard** [comment]
@AquilesCanta Can you help understand why the crypto key is not available?

**Comment by AquilesCanta** [comment]
Hi, is this still an issue? Is it possible that it was fixed server-side?

I was just now able to correctly play the stream locally.

**Comment by ogawa-ma** [comment]
@AquilesCanta 
Hello, I haven't made any server-side fixes.
ExoPlaybackException occurs when trying to play in Xperia XZ(OS:8.0.0) still confirmed.
Did you find out from the bug report why the crypto key is not available?
Also, if you do not know the cause, is there any information that can be provided from here for cause investigation?

**Comment by AquilesCanta** [comment]
- Can you please confirm whether this is a device-specific issue? 
- Are you able to play the stream on any other device?
- Are there any special reproduction steps I should be aware of?

I didn't have any issues to play on a pixel 3a, using the demo app.

**Comment by ogawa-ma** [comment]
@AquilesCanta
>Can you please confirm whether this is a device-specific issue?

This occurs only on this device.


>Are you able to play the stream on any other device?

You can play it normally on other devices(Pixel3,Pixel4).


>Are there any special reproduction steps I should be aware of?

There is no special way to play it. Just need to play on the Xperia XZ(OS:8.0.0) to reproduce this phenomenon.

**Comment by AquilesCanta** [comment]
In that case, I doubt this is an ExoPlayer issue. I think one of two things may be going on:

- The content decryption module on your device is generating a key request that the license server doesn't like. Maybe it's something related to this specific device (maybe try another phone with the same model?), or the device model. If this is the situation, I'd try to see what's going on on the server side. I'd find it strange that the server is not returning HTTP 403 or similar.
- The key request and response are working as expected, but the device is someway failing to use the keys for decryption. In this case the best option is contacting the device manufacturer, they may be able to help.

I've just noticed there's no bugreport attached to the e-mail you sent. I don't think i'll be able to find much in it, but you are welcome to try sending one.

**Comment by ogawa-ma** [comment]
@AquilesCanta
I'm sorry. I forgot to attach a bug report. I have now sent a bug report to dev.exoplayer@gmail.com.

**Comment by rrfrias** [comment]
@ogawa-ma We would like to get Sony involved. Do i have your permission to share the bugreport and repro steps that you mentioned in the email with Sony? Also the license expiration date is 2020-06-18. Is it possible to extend it or share different content so that we/Sony can repro?
