### ISSUE TITLE
Video not playing 

### ISSUE THREAD

**Issue by deepakrokz** [google/ExoPlayer#7358]
Getting Playback error in some devices especially Honor and Samsung running KitKat and Nougat, while playing video from a URL while audio is functioning fine. It has been a long time struggling with this issue.

Please help me out of this problem, I looked all over the issue list but couldn't found any solution.
This is one of the log:

```
ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.ffmpeg.hevc.decoder, Format(1, null, null, video/hevc, null, -1, null, [480, 480, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.ffmpeg.hevc.decoder, Format(1, null, null, video/hevc, null, -1, null, [480, 480, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:262)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by deepakrokz** [comment]
Can I have someone's input on this.
I will be very thankful for your time if it's getting resolved ASAP.

Thanks in advance.

**Comment by deepakrokz** [comment]
Hi @willnorris, @xian, @canatella, @kiall, @icbaker,
Guys help me please, I will be very thankful to you.

**Comment by kiall** [comment]
I have nothing to do with ExoPlayer - haven't used it in years. Can you please stop mentioning random people.

I get tagged every month or two in ExoPlayer issues - I don't have the slightest clue why.

**Comment by krocard** [comment]
`MediaCodec.native_configure(Native Method)` throwing `java.lang.IllegalStateException` during `MediaCodecRenderer.initCodec`

@ojw28 Is this a known issue for the software decoder OMX.ffmpeg.hevc.decoder or can you understand the issue from just the stacktrace?

@deepakrokz it would be great if you can post the logcat when the error occurs, or even better, the full bug report. Thanks!

**Comment by icbaker** [comment]
> I have nothing to do with ExoPlayer - haven't used it in years. Can you please stop mentioning random people.
> 
> I get tagged every month or two in ExoPlayer issues - I don't have the slightest clue why.

+1 to this, please don't tag random people (even random members of ExoPlayer team) or ping issues with no additional info just to try and get attention. Someone from the team will look at every issue. We can usually resolve your problem faster if you provide the information requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

**Comment by deepakrokz** [comment]
@krocard, sorry for the delay.

Here it is:

```
05-18 09:03:20.033 2344-2544/com.test D/dalvikvm: VFY: replacing opcode 0x6e at 0x000c
05-18 09:03:20.033 2344-2544/com.test I/OMXClient: Using client-side OMX mux.
05-18 09:03:20.037 2344-2544/com.test E/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
05-18 09:03:20.037 2344-2544/com.test W/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed
05-18 09:03:20.037 2344-2544/com.test D/MediaCodecInfo: NoSupport [legacyFrameSize, 480x480] [OMX.ffmpeg.hevc.decoder, video/hevc] [vbox86p, Google Nexus 7_1, Genymotion, 19]
05-18 09:03:20.037 2344-2544/com.test D/MediaCodecInfo: NoSupport [legacyFrameSize, 480x480] [OMX.ffmpeg.hevc.decoder, video/hevc] [vbox86p, Google Nexus 7_1, Genymotion, 19]
05-18 09:03:20.037 2344-2544/com.test I/OMXClient: Using client-side OMX mux.
05-18 09:03:20.041 2344-2544/com.test D/SoftFFmpegAudio: SoftFFmpegAudio component: OMX.ffmpeg.aac.decoder mMode: 1
05-18 09:03:20.041 2344-2544/com.test V/SoftFFmpegAudio: ~SoftFFmpegAudio
05-18 09:03:20.041 2344-2544/com.test I/OMXClient: Using client-side OMX mux.
05-18 09:03:20.049 2344-2561/com.test I/OMXClient: Using client-side OMX mux.
05-18 09:03:20.049 2344-2561/com.test D/SoftFFmpegVideo: SoftFFmpegVideo component: OMX.ffmpeg.hevc.decoder mMode: 0 appData: 0xb810c298
05-18 09:03:20.053 2344-2561/com.test E/ACodec: [OMX.ffmpeg.hevc.decoder] configureCodec returning error -1010
05-18 09:03:20.053 2344-2560/com.test E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -1010)
05-18 09:03:20.053 2344-2561/com.test V/SoftFFmpegVideo: ~SoftFFmpegVideo
05-18 09:03:20.053 2344-2544/com.test W/MediaCodecRenderer: Failed to initialize decoder: OMX.ffmpeg.hevc.decoder
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:262)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
05-18 09:03:20.053 2344-2544/com.test E/dalvikvm: Could not find class 'android.media.MediaCodec$CodecException', referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException.getDiagnosticInfoV21
05-18 09:03:20.053 2344-2544/com.test W/dalvikvm: VFY: unable to resolve instanceof 204 (Landroid/media/MediaCodec$CodecException;) in Lcom/google/android/exoplayer2/mediacodec/MediaCodecRenderer$DecoderInitializationException;
05-18 09:03:20.053 2344-2544/com.test D/dalvikvm: VFY: replacing opcode 0x20 at 0x0000
05-18 09:03:20.061 2344-2544/com.test E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.ffmpeg.hevc.decoder, Format(1, null, null, video/hevc, null, -1, null, [480, 480, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.ffmpeg.hevc.decoder, Format(1, null, null, video/hevc, null, -1, null, [480, 480, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:262)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
05-18 09:03:21.697 2344-2407/com.test D/MuzibeesApp: drawUpEachThreadInfoDiff: Thread count = 47. Thread differ : -1. unknown: -1 [(-)Loader:ExtractorMediaPeriod]
```

**Comment by ojw28** [comment]
The logs above seem to have been captured on a cloud based emulator running API level 19. Please see our [supported devices page](https://exoplayer.dev/supported-devices.html) for some information about emulators. We only support Android's official emulator, from API level 23. Please provide logs captured from a real device that experiences this issue.

Please also see the [supported formats page](https://exoplayer.dev/supported-formats.html). If you read it, and also follow the link to the [Android page for sample formats](https://developer.android.com/guide/topics/media/media-formats#core), you'll see that HEVC is only supported from API level 21.

**Comment by deepakrokz** [comment]
In terms of real device thing, we are facing issues in Samsung tab running **Kitkat,** Honor 5A running API level **23 i.e. Marshmallow** as reported by some of the users. We don't have these devices stack trace. So I tried to generate this case in Genymotion device **Galaxy Nexus 7 running Kitkat** that's stack track I shared with you in the above comments. 

Please help us.

**Comment by ojw28** [comment]
As per my comment above, HEVC is unlikely to be supported on KitKat devices. For devices that we do expect to support HEVC, you'll need to provide proper logs captured from those devices in order for us to help, I'm afraid.

**Comment by deepakrokz** [comment]
Hi @ojw28 ,
What about this LOG:

```
05-20 02:32:38.886 16946-17354/com.test D/dalvikvm: GC_FOR_ALLOC freed 1346K, 17% free 34803K/41528K, paused 167ms, total 168ms
05-20 02:32:39.566 16946-16946/com.test D/EGL_emulation: eglMakeCurrent: 0xb79eae30: ver 2 0
05-20 02:32:39.746 16946-17345/com.test I/OMXClient: Using client-side OMX mux.
05-20 02:32:39.786 16946-17345/com.test I/dalvikvm: Could not find method android.media.MediaCodecInfo$VideoCapabilities.isSizeSupported, referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecInfo.areSizeAndRateSupportedV21
05-20 02:32:39.786 16946-17345/com.test W/dalvikvm: VFY: unable to resolve virtual method 996: Landroid/media/MediaCodecInfo$VideoCapabilities;.isSizeSupported (II)Z
05-20 02:32:39.786 16946-17345/com.test D/dalvikvm: VFY: replacing opcode 0x6e at 0x0012
05-20 02:32:39.786 16946-17345/com.test I/dalvikvm: Could not find method android.media.MediaCodecInfo$VideoCapabilities.areSizeAndRateSupported, referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecInfo.areSizeAndRateSupportedV21
05-20 02:32:39.796 16946-17345/com.test W/dalvikvm: VFY: unable to resolve virtual method 993: Landroid/media/MediaCodecInfo$VideoCapabilities;.areSizeAndRateSupported (IID)Z
05-20 02:32:39.796 16946-17345/com.test D/dalvikvm: VFY: replacing opcode 0x6e at 0x000d
05-20 02:32:39.796 16946-17345/com.test I/dalvikvm: Could not find method android.media.MediaCodecInfo$CodecCapabilities.getMaxSupportedInstances, referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecInfo.getMaxSupportedInstancesV23
05-20 02:32:39.796 16946-17345/com.test W/dalvikvm: VFY: unable to resolve virtual method 990: Landroid/media/MediaCodecInfo$CodecCapabilities;.getMaxSupportedInstances ()I
05-20 02:32:39.796 16946-17345/com.test D/dalvikvm: VFY: replacing opcode 0x6e at 0x0000
05-20 02:32:39.806 16946-17345/com.test I/dalvikvm: Could not find method android.media.MediaCodecInfo$CodecCapabilities.getVideoCapabilities, referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecInfo.alignVideoSizeV21
05-20 02:32:39.806 16946-17345/com.test W/dalvikvm: VFY: unable to resolve virtual method 991: Landroid/media/MediaCodecInfo$CodecCapabilities;.getVideoCapabilities ()Landroid/media/MediaCodecInfo$VideoCapabilities;
05-20 02:32:39.806 16946-17345/com.test D/dalvikvm: VFY: replacing opcode 0x6e at 0x000b
05-20 02:32:39.806 16946-17345/com.test I/dalvikvm: Could not find method android.media.MediaCodecInfo$CodecCapabilities.getAudioCapabilities, referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecInfo.isAudioChannelCountSupportedV21
05-20 02:32:39.806 16946-17345/com.test W/dalvikvm: VFY: unable to resolve virtual method 989: Landroid/media/MediaCodecInfo$CodecCapabilities;.getAudioCapabilities ()Landroid/media/MediaCodecInfo$AudioCapabilities;
05-20 02:32:39.816 16946-17345/com.test D/dalvikvm: VFY: replacing opcode 0x6e at 0x000b
05-20 02:32:39.816 16946-17345/com.test I/dalvikvm: Could not find method android.media.MediaCodecInfo$CodecCapabilities.getAudioCapabilities, referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecInfo.isAudioSampleRateSupportedV21
05-20 02:32:39.816 16946-17345/com.test W/dalvikvm: VFY: unable to resolve virtual method 989: Landroid/media/MediaCodecInfo$CodecCapabilities;.getAudioCapabilities ()Landroid/media/MediaCodecInfo$AudioCapabilities;
05-20 02:32:39.816 16946-17345/com.test D/dalvikvm: VFY: replacing opcode 0x6e at 0x000b
05-20 02:32:39.826 16946-17345/com.test I/dalvikvm: Could not find method android.media.MediaCodecInfo$CodecCapabilities.getVideoCapabilities, referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecInfo.isVideoSizeAndRateSupportedV21
05-20 02:32:39.826 16946-17345/com.test W/dalvikvm: VFY: unable to resolve virtual method 991: Landroid/media/MediaCodecInfo$CodecCapabilities;.getVideoCapabilities ()Landroid/media/MediaCodecInfo$VideoCapabilities;
05-20 02:32:39.826 16946-17345/com.test D/dalvikvm: VFY: replacing opcode 0x6e at 0x000b
05-20 02:32:39.856 16946-17363/com.test I/OMXClient: Using client-side OMX mux.
05-20 02:32:40.156 16946-16946/com.test I/Choreographer: Skipped 110 frames!  The application may be doing too much work on its main thread.
05-20 02:32:40.526 16946-17364/com.test I/SoftAAC2: Reconfiguring decoder: 0->44100 Hz, 0->2 channels
05-20 02:32:40.596 16946-17345/com.test E/android.media.AudioTrack: getMinBufferSize(): error querying hardware
05-20 02:32:40.606 16946-17345/com.test E/AudioTrack-JNI: Error creating AudioTrack: Could not get AudioSystem frame count.
05-20 02:32:40.606 16946-17345/com.test E/android.media.AudioTrack: Error code -16 when initializing AudioTrack.
05-20 02:32:40.616 16946-17345/com.test E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 44100)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(SourceFile:646)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(SourceFile:1355)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:663)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 44100)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(SourceFile:1128)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(SourceFile:532)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(SourceFile:593)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(SourceFile:640)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(SourceFile:1355) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:663) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
05-20 02:32:40.966 16946-16946/com.test D/EGL_emulation: eglMakeCurrent: 0xb79eae30: ver 2 0
```


This time I have used Android's Official Simulator Pixel running Kitkat and getting above issue as stack track.

**Comment by ojw28** [comment]
As per my previous response:

> We only support Android's official emulator, **from API level 23**.
