### ISSUE TITLE
XmlPullParserException reading DASH manifest from Amazon S3

### ISSUE THREAD

**Issue by rishabhshah09** [google/ExoPlayer#7362]
```
ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ������ ftypmp42������...@1:894 in java.io.InputStreamReader@d28535b) 
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:105)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:58)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:158)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ������ ftypmp42������...@1:894 in java.io.InputStreamReader@d28535b) 
        at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:447)
        at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:321)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:98)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:58) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:158) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by krocard** [comment]
Seems like you are hitting an invalid token in the XML stream. I'm not sure we can help you on what exactly is wrong in your media without access to the dash manifest itself. Maybe you could attach it to this issue?

@ojw28 is our DASH expert, and might be able to help further.

**Comment by ojw28** [comment]
It looks like the DASH manifest is malformed. You'll have to provide it to us if you'd like us to check, however. Marking as "needs more info" for this reason.

**Comment by krocard** [comment]
> Unexpected token (position:TEXT ������ ftypmp42�������...@1:894 in java.io.InputStreamReader@d28535b) 

Actually, `������ ftypmp42�������` corresponds to the first bytes of a h.264 encoded MP4.

It seems like ExoPlayer it trying to play an  mp4 (a binary file) as a dash XML manifest.

How did you configure Exoplayer MediaSource?
