### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#7377]
App Crash with the following error:

E/AndroidRuntime: FATAL EXCEPTION: main

```
 java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.exoplayer2.metadata.MetadataOutput.onMetadata(com.google.android.exoplayer2.metadata.Metadata)' on a null object reference
        at com.google.android.exoplayer2.SimpleExoPlayer$ComponentListener.onMetadata(SimpleExoPlayer.java:1400)
        at com.google.android.exoplayer2.metadata.MetadataRenderer.invokeRendererInternal(MetadataRenderer.java:194)
        at com.google.android.exoplayer2.metadata.MetadataRenderer.handleMessage(MetadataRenderer.java:185)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

    implementation 'com.google.android.exoplayer:exoplayer-core:2.10.4'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.10.4'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.10.4'

**Comment by krocard** [comment]
Thanks @icbaker for the analysis.

`ComponentListener.onMetadata` calls `MetadataOutput.onMetadata` on all the MetadataOutput receivers your app registered with `SimpleExoPlayer.addMetadataOutput`.

Thus it seems your app added a `null` `MetadataOutput`. Search for your app calls to `SimpleExoPlayer.addMetadataOutput` a check that null is never passed.

Note that if you enable the Java nullness checker or use Kotllin, those bugs could be caught at build time.
