### ISSUE TITLE
Resources$NotFoundException (exo_controls_repeat_off)

### ISSUE THREAD

**Issue by Discovery-Prachi** [google/ExoPlayer#7380]
### [REQUIRED] Issue description
We are observing following crash on Crashlytics multiple times on Device : HMD Global, Nokia 5.1 plus, Android OS 9.

We are not using or overriding this drawable - "drawable/exo_controls_repeat_off"  in our app. Could you help us solve this. 

### [REQUIRED] Reproduction steps
We could not reproduce, but observing on Crashlytics multiple times for mentioned devices only.

### [REQUIRED] A full bug report captured from the device
Logs for the crash : 
```
Caused by android.content.res.Resources$NotFoundException: Resource "com.discoveryplus.mobile.android:drawable/exo_controls_repeat_off" (7f0800fd) is not a Drawable (color or path): TypedValue{t=0x12/d=0x0 a=7 r=0x7f0800fd}
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:808)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:648)
       at android.content.res.Resources.getDrawableForDensity(Resources.java:888)
       at android.content.res.Resources.getDrawable(Resources.java:827)
       at android.content.res.Resources.getDrawable(Resources.java:802)
       at com.google.android.exoplayer2.ui.PlayerControlView.<init>(PlayerControlView.java:338)
       at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:452)
```

### [REQUIRED] Version of ExoPlayer being used
```
"com.google.android.exoplayer:exoplayer-core:2.11.0"
"com.google.android.exoplayer:exoplayer-dash:2.11.0"
"com.google.android.exoplayer:exoplayer-hls:2.11.0"
"com.google.android.exoplayer:exoplayer-ui:2.11.0"
```

### [REQUIRED] Device(s) and version(s) of Android being used
Crash is seen on following device : 
Device : HMD Global, Nokia 5.1 plus, Android OS 9.

**Comment by ojw28** [comment]
How many unique devices are the reports coming from? If it's a very small number, then it's most likely that these devices are running a custom Android build, which is broken. Possibly a build of Lineage OS (I'm not sure, but you can probably see exactly what build they're running somewhere in Crashlytics).
