### ISSUE TITLE
android.media.MediaCodec$CryptoException: Error decrypting data: unspecified error

### ISSUE THREAD

**Issue by gokulkalagara** [google/ExoPlayer#7393]
**Exoplayer Version**
ExoPlayerLib/2.11.4

**Device details**

Manufacturer: samsung
Model: SM-G935W8

**Error**
```
playerFailed [eventTime=5.77, mediaPos=0.00, window=0, period=0
com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Error decrypting data: unspecified error
    at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1202)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:722)
      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
    at android.os.Handler.dispatchMessage(Handler.java:98)
     at android.os.Looper.loop(Looper.java:154)
     at android.os.HandlerThread.run(HandlerThread.java:61)\
 Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: unspecified error
      at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
      at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2478)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1193)\n      ... 6 more\n]
```

[error-log.txt](https://github.com/google/ExoPlayer/files/4648308/error-log.txt)
Please check the log files

![drm-info](https://user-images.githubusercontent.com/13214923/82287239-6294a980-99bd-11ea-8149-540a943bbdd6.jpeg)

**Comment by ojw28** [comment]
@jt64 - Please take a look.

**Comment by gokulkalagara** [comment]
@ojw28 Please check this.

**Device Bug Report**
[bugreport-2020-05-29-12-40-38.zip](https://github.com/google/ExoPlayer/files/4700223/bugreport-2020-05-29-12-40-38.zip)

**Comment by gokulkalagara** [comment]
@marcbaechinger please check this

**Comment by jt64** [comment]
Thank you for providing the bugreport. The bugreport shows that this particular device is in a non-secure or unstable state:

<6>[171815.796932]  [3:    kworker/3:0:21075] Trustonic TEE: 601|Err tima  measure_verify_kernel: TIMA_PKM_HASH_DB: KERNEL VERIFICATION FAILED

05-29 12:40:14.288 18098 25598 E wv_dash : Trustlet did not send a valid return code: 0x6000
05-29 12:40:14.288 18098 25598 E wv_dash : tee_send_msg_general_cmd is failed.
05-29 12:40:14.288 18098 25598 E wv_dash : process drm decrypt CENC failed


Samsung's analysis of devices in this state is this:
----------------------------------------------------
"According to above log, system tried to verify kernel but it failed.
This log is from Samsung Mobile's solution, but It seems that kernel is modified.

The Widevine TA checks system's reliability before decryption.
Samsung Mobile provides one API and Widevine TA checks system's status by using this API.
If this API returns failure, Widevine TA doesn't execute decryption and just returns "0x6000" error.
This is Samsung Mobile's requirement.

[...] I can say that current decryption failure happens due to reliability of device.
I don't know the current status of this device exactly and why it decides that kernel is modified, but I think Widevine TA is working as intended."
