### ISSUE TITLE
"*mp4?type=m3u8" cause error media source

### ISSUE THREAD

**Issue by VeiZhang** [google/ExoPlayer#7426]
### [REQUIRED] Question
The movie link end with **"mp4?type=m3u8"**, use exo player with `TYPE_OTHER` to watch the movie, and then it caused `UnrecognizedInputFormatException`. But my android platform support the video format, I try again with `TYPE_HLS`, it works well. 
**Is there any good ways to solve it?**

### A full bug report captured from the device
```
ExoPlayer: mExoEventListener - onPlayerStateChanged: playWhenReady = true, playbackState = 2
ExoPlayer: mExoEventListener: playbackState = STATE_BUFFERING 0 - 0
EventLogger: timeline [eventTime=0.01, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
EventLogger:   period [?]
EventLogger:   window [?, false, false]
EventLogger: ]
ExoPlayer: mExoEventListener: onTimelineChanged-----timeline com.google.android.exoplayer2.source.SinglePeriodTimeline@214da72
EventLogger: mediaPeriodCreated [eventTime=0.02, mediaPos=0.00, window=0, period=0]
EventLogger: loading [eventTime=0.02, mediaPos=0.00, window=0, period=0, true]
ExoPlayer: mExoEventListener: onLoadingChanged-----isLoading true
UsbService.NetworkService: usbFile.exists() =false
EventLogger: internalError [eventTime=2.09, mediaPos=0.00, window=0, period=0, loadError
EventLogger:   com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
EventLogger:       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1090)
EventLogger:       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:969)
EventLogger:       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
EventLogger:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
EventLogger:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
EventLogger:       at java.lang.Thread.run(Thread.java:761)
EventLogger: ]
ExoPlayerImplInternal: Source error
ExoPlayerImplInternal:   com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1090)
ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:969)
ExoPlayerImplInternal:       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:761)
EventLogger: mediaPeriodReleased [eventTime=2.09, mediaPos=0.00, window=0, period=0]
EventLogger: playerFailed [eventTime=2.09, mediaPos=0.00, window=0, period=0
EventLogger:   com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
EventLogger:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:394)
EventLogger:       at android.os.Handler.dispatchMessage(Handler.java:98)
EventLogger:       at android.os.Looper.loop(Looper.java:154)
EventLogger:       at android.os.HandlerThread.run(HandlerThread.java:61)
EventLogger:   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
EventLogger:       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1090)
EventLogger:       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:969)
EventLogger:       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
EventLogger:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
EventLogger:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
EventLogger:       at java.lang.Thread.run(Thread.java:761)
EventLogger: ]
ExoPlayer: onPlayerError: error type : TYPE_SOURCE, com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
ExoPlayer: onPlayerError: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
BaseVideoView: [ciel_debug][onError]: what: -10001,extra: 0
```

### Link to test content
Sorry, the test link is private.

**Comment by marcbaechinger** [comment]
If you want to play an HLS stream, then you need to use a `HlsMediaSource`. So you need to use `TYPE_HLS`. An HLS stream provides a playlist which is a text file this needs to be interpreted by the player to then download the adaptive media. The error you are seeing and posted above occurs because the `ProgressiveMediaSource` is used and it tries to interpret the text playlist as a media file. This fails with the error message above because the extractors expect a media container rather than a playlist.

So you need to do something like this:

```
HlsMediaSource hlsMediaSource = new HlsMediaSource.Factory(dataSourceFactory)
    .createMediaSource(uri);
player.setMediaSource(hlsMediaSource);
```

**Comment by VeiZhang** [comment]
@marcbaechinger Thanks for your reply. But the situation is different, I don't know which stream will be played, so I used `ProgressiveMediaSource`, then the `mp4?type=m3u8` come error. I mean how to recognize and use the true media soure.

**Comment by marcbaechinger** [comment]
If you are using an adaptive stream like HLS, DASH or SmoothStreaming you can not use `ProgressiveMediaSource`. Instead you need to use the adaptive media source according to the type of the stream. In you case of an HLS stream yoy would need to create a `HlsMediaSource` as shown below. 

It's up to the app to choose the correct media source.
(This is a duplicate of #7389)

**Comment by VeiZhang** [comment]
@marcbaechinger Thanks a lot
