### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by vy12021** [google/ExoPlayer#7433]
# stacks

```
java.lang.IndexOutOfBoundsException
com.google.android.exoplayer2.Timeline$1.getPeriod(Timeline.java:560)
--
2 com.google.android.exoplayer2.Timeline.getPeriodByUid(Timeline.java:794)
3 com.google.android.exoplayer2.ExoPlayerImpl.getCurrentWindowIndex(ExoPlayerImpl.java:474)
4 com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:627)
5 com.google.android.exoplayer2.analytics.AnalyticsCollector.generatePlayingMediaPeriodEventTime(AnalyticsCollector.java:645)
6 com.google.android.exoplayer2.analytics.AnalyticsCollector.onTimelineChanged(AnalyticsCollector.java:420)
7 com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$0$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:804)
8 com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$N_S5kRfhaRTAkH28P5luFgKnFjQ.invokeListener(Unknown Source:2)
9 com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
10 com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
11 com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
12 com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:802)
13 com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
14 com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
15 com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
16 com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
17 com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
18 android.os.Handler.dispatchMessage(Handler.java:106)
19 android.os.Looper.loop(Looper.java:227)
```
### Note:
This error is an accidental problem and comes from the online problem collection.
Only happens when upgrading to 2.11.3.

**Comment by vy12021** [comment]
### Add one more situation.
```
java.lang.IndexOutOfBoundsException
1 com.google.android.exoplayer2.Timeline$1.getPeriod(Timeline.java:560)
--
2 com.google.android.exoplayer2.Timeline.getPeriodByUid(Timeline.java:794)
3 com.google.android.exoplayer2.ExoPlayerImpl.periodPositionUsToWindowPositionMs(ExoPlayerImpl.java:743)
4 com.google.android.exoplayer2.ExoPlayerImpl.getCurrentPosition(ExoPlayerImpl.java:497)
5 com.google.android.exoplayer2.ExoPlayerImpl.getContentPosition(ExoPlayerImpl.java:539)
6 com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:607)
7 com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:636)
8 com.google.android.exoplayer2.analytics.AnalyticsCollector.generateMediaPeriodEventTime(AnalyticsCollector.java:662)
9 com.google.android.exoplayer2.analytics.AnalyticsCollector.onLoadStarted(AnalyticsCollector.java:340)
10 com.google.android.exoplayer2.source.MediaSourceEventListener$EventDispatcher.lambda$loadStarted$2$MediaSourceEventListener$EventDispatcher(MediaSourceEventListener.java:435)
11 com.google.android.exoplayer2.source.-$$Lambda$MediaSourceEventListener$EventDispatcher$WQKVpIh5ilpOizOGmbnyUThugMU.run(Unknown Source:8)
12 android.os.Handler.handleCallback(Handler.java:790)
13 android.os.Handler.dispatchMessage(Handler.java:99)
14 android.os.Looper.loop(Looper.java:197)
```

**Comment by marcbaechinger** [comment]
The `IndexOutOfBoundsException` which is shown in the logs above is thrown by `Timeline.EMPTY`. The player tries to get a period from the empty timeline in `getCurrentPosition`. 

This actually should not happen with an empty timeline, because there is the check in [`shouldMaskPosition`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImpl.java#L748) in ExoPlayerImpl:

```
private boolean shouldMaskPosition() {
    return playbackInfo.timeline.isEmpty() || pendingOperationAcks > 0;
  }
```
Accordingly this seems to be a threading issue, because the above check would not allow `getCurrentPosition` to access the timeline when empty, but instead just return `maskingWindowPositionMs`.

```
@Override
  public long getCurrentPosition() {
    if (shouldMaskPosition()) {
      return maskingWindowPositionMs;
    } else if (playbackInfo.periodId.isAd()) {
      return C.usToMs(playbackInfo.positionUs);
    } else {
      return periodPositionUsToWindowPositionMs(playbackInfo.periodId, playbackInfo.positionUs);
    }
  }
```
For further investigation it would be very helpful for me to get some more information:

Can you let me know from what release you've upgraded to 2.11.3?
Can you create a bug report when running your app on any device? Regardless whether the problem exists or not, I want to look into the logs if that is possible.  If you don't wish to post it publicly, then please email the bug report to dev.exoplayer@gmail.com using a subject in the format "Issue #7433".

**Comment by saschpe** [comment]
I can confirm the crash with version 2.11.4

```
Fatal Exception: java.lang.IndexOutOfBoundsException
       at com.google.android.exoplayer2.Timeline$1.getPeriod(Timeline.java:560)
       at com.google.android.exoplayer2.Timeline.getPeriod(Timeline.java:806)
       at com.google.android.exoplayer2.analytics.AnalyticsCollector$MediaPeriodQueueTracker.onMediaPeriodCreated(AnalyticsCollector.java:813)
       at com.google.android.exoplayer2.analytics.AnalyticsCollector.onMediaPeriodCreated(AnalyticsCollector.java:317)
       at com.google.android.exoplayer2.source.MediaSourceEventListener$EventDispatcher.lambda$mediaPeriodCreated$0(MediaSourceEventListener.java:371)
       at com.google.android.exoplayer2.source.-$$Lambda$MediaSourceEventListener$EventDispatcher$N-EOPAK5UK0--YMNjezq7UM3UNI.run(-.java:6)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by marcbaechinger** [comment]
@saschpe Do you have a full bug report for this?

**Comment by saschpe** [comment]
Apart from the trace? Not yet. I grabbed it straight from my crash reporting tool.
