### ISSUE TITLE
How to remove ICY header request

### ISSUE THREAD

**Issue by Abu-Abdullah** [google/ExoPlayer#7450]
Hi,

I was trying to find a way on how to remove the ICY header from the header request. I'm expecting it is causing some issues with certein hosting server.

i have been trying many things without success e.g. 

```
final HttpDataSource.RequestProperties s = dataSourceFactory.getDefaultRequestProperties();
s.remove(IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_NAME);
```

OR 

```
final ProgressiveMediaSource audioSource2 =
new ProgressiveMediaSource.Factory(() -> {
	final HttpDataSource dataSource = new DefaultHttpDataSource(Util.getUserAgent(this, getString(R.string.app_name)))
	{
		@Override
		public long open(DataSpec dataSpec) throws HttpDataSourceException
		{
			dataSpec.httpRequestHeaders.remove(IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_NAME);
			return super.open(dataSpec);
		}
	};
	//dataSource.clearRequestProperty(IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_NAME);
	return dataSource;
}).createMediaSource(Uri.parse(url));
```

the last one throws:
```
2020-05-31 17:45:56.863 9747-10339/com.myapp.audiocataloger E/LoadTask: Unexpected exception loading stream
      java.lang.UnsupportedOperationException
        at java.util.Collections$UnmodifiableMap.remove(Collections.java:1502)
        at com.myapp.audiocataloger.MediaService$4.open(MediaService.java:813)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:956)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
```

I tried as well to override it in TransferListener without success as well

```
final TransferListener transferListener = new TransferListener()
{
	@Override
	public void onTransferInitializing(DataSource dataSource, DataSpec dataSpec, boolean isNetwork)
	{
		// Override it here
	}

	@Override
	public void onTransferStart(DataSource dataSource, DataSpec dataSpec, boolean b){}

	@Override
	public void onBytesTransferred(DataSource dataSource, DataSpec dataSpec, boolean b, int i){}

	@Override
	public void onTransferEnd(DataSource dataSource, DataSpec dataSpec, boolean b){}
};
```

Please advise the proper way to do this.

**Comment by andrewlewis** [comment]
In the option where you override `open`, could you try instantiating a new `DataSpec` based on values from the old one but without the ICY header?

**Comment by Abu-Abdullah** [comment]
thank you @andrewlewis for the hint. it is working as you suggest:
```
@Override
public long open(DataSpec dataSpec) throws HttpDataSourceException
{
	final Map<String, String> m1 = dataSpec.httpRequestHeaders;
	final Map<String, String> m2 = new HashMap<>();
	for (Map.Entry<String, String> entry : m1.entrySet())
		if(!entry.getKey().equals(IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_NAME))
			m2.put(entry.getKey(), entry.getValue());
	
	return super.open(dataSpec.withRequestHeaders(m2));
}
```
And thankfully the web server behavior is correct now. I'm not facing the same issues that i faced in #7353 which indicates that setting ICY_Metadata in the header by default is not the correct way. Many web servers might be affected by this (at least in my case which i have it on bluehost, one of the leaders in this market).

I think we should have an easy way to configure the dataspec.httpRequestHeaders

thank you again
