### ISSUE TITLE
Can't catch BehindLiveWindowException long time

### ISSUE THREAD

**Issue by VeiZhang** [google/ExoPlayer#7481]
### [REQUIRED] Question
Sometimes I found `BehindLiveWindowException`, exo player always show loading, it's hard to catch because it need long time to reproduct.
I try to init player like ExoPlayer sample when `BehindLiveWindowException`, but it didn't work.

**I use android media player and it works well, is there any ways to solve or present?**

### A full bug report captured from the device
```
2020-06-09 15:28:07.423 E/EventLogger: playerFailed [eventTime=1420.38, mediaPos=-27.84, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.BehindLiveWindowException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:394)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.source.BehindLiveWindowException
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:300)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:645)
        at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:78)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading(HlsMediaPeriod.java:363)
        at com.google.android.exoplayer2.MediaPeriodHolder.continueLoading(MediaPeriodHolder.java:205)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1760)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1739)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
    ]
2020-06-09 15:28:07.424 E/ExoPlayer: onPlayerError: error type : TYPE_SOURCE, com.google.android.exoplayer2.source.BehindLiveWindowException
2020-06-09 15:28:07.424 E/ExoPlayer: onPlayerError retry - isBehindLiveWindow: 
    com.google.android.exoplayer2.source.BehindLiveWindowException
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:300)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:645)
        at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:78)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading(HlsMediaPeriod.java:363)
        at com.google.android.exoplayer2.MediaPeriodHolder.continueLoading(MediaPeriodHolder.java:205)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1760)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1739)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2020-06-09 15:28:07.424 I/ExoPlayer: onPlayerError retry: isBehindLiveWindow
```

### Link to test content
Sorry, the play link is dynamic, I can't provide.

**Comment by ojw28** [comment]
I'm not sure I understand what the issue is. I think you're saying that you're trying to catch `BehindLiveWindowException` and retry in this case, and that it's not working, however:

1. It's unclear why the logging you've provided indicates that it's not working. `onPlayerError retry - isBehindLiveWindow` to me suggests that it is working and that your code will go on to retry.
1. I think you'll need to provide a small sample app that demonstrates exactly the problem you're seeing, since it's not clear there's anything actionable we can do with the information provided.

**Comment by VeiZhang** [comment]
@ojw28 Yes, u are right. But when I catch the exception, I try to prepare again, it still show loading and balck screen. Actually I wait about 1 - 2 min to catch it, too long.

I can't provide a sample, because play link will time out in seconds.

**Comment by ojw28** [comment]
> Actually I wait about 1 - 2 min to catch it, too long.

I don't really understand what this means. I also don't think we can help without clearer reproduction steps. It's possible that the media itself is causing the problem.

**Comment by VeiZhang** [comment]
@ojw28 OK. Thanks for your help. I will give a sample if I can get the link.
