### ISSUE TITLE
Http 302 redirect doesn't work although i set up allowCrossProtocolRedirects to true

### ISSUE THREAD

**Issue by pooyair** [google/ExoPlayer#7486]
hi i use demo application whitin the project. please test following url that work fine with vlc and safari web browser but not working with Exoplayer:
```

```
```
2020-06-10 03:50:49.093 24246-24246/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=1.83, mediaPos=0.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:394)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1096)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:975)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
    ]
2020-06-10 03:50:49.922 2198-2252/? E/ContactsProvider_EventLog: Flush buffer to file cnt : 1 size : 0Kb duration : 2ms lastUpdatedAfter : 12614 ms mFlush_time_threasold : 2000 mCurrentSize : 338
```

Thanks

**Comment by ojw28** [comment]
The URL does not do a 302 redirect for me:
```
curl -v "http://tokenbaba.tvcdn.online/tokenx/loadch.php?c=6293&checkedby:iptvcat.com"
*   Trying 217.182.198.2...
* TCP_NODELAY set
* Connected to tokenbaba.tvcdn.online (217.182.198.2) port 80 (#0)
> GET /tokenx/loadch.php?c=6293&checkedby:iptvcat.com HTTP/1.1
> Host: tokenbaba.tvcdn.online
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 10 Jun 2020 09:38:00 GMT
< Server: Apache/2.4.29 (Ubuntu)
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< 
* Connection #0 to host tokenbaba.tvcdn.online left intact
* Closing connection 0
```
I can't make it play anything in Safari or VLC, either. Marking as "needs more info" because we currently don't have working reproduction steps.

**Comment by pooyair** [comment]
sorry , you are right , seems the server provider change the url. i would close it until i can reporduce it again
