### ISSUE TITLE
ExoPlayer bulid a release version which minifyEnabled is true

### ISSUE THREAD

**Issue by VicJcc** [google/ExoPlayer#749]
buildTypes {
        release {
            minifyEnabled true
            signingConfig signingConfigs.adhoc
            proguardFiles getDefaultProguardFile('proguard-android.txt')
        }
    }

when I build like above ,it dose not work well on the phone called OnePlus 1,and android version is 4.3.
the url is http://s.5dktv.com/hls/f4/30100127_72_1.m3u8.

**Comment by ojw28** [comment]
What does "not work well" actually mean? This isn't sufficient information to debug the issue.

**Comment by VicJcc** [comment]
It means the url can only play 3-7 seconds,then it return buffering and idle,but actually it should play more        then one minute.

**Comment by ojw28** [comment]
What error occurs in logcat when it transitions to idle? There's probably a stack trace when the error occurs.

**Comment by VicJcc** [comment]
09-01 10:25:07.705  30160-30335/? E/OMXMaster﹕ A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
09-01 10:25:07.705  30160-30378/? E/OMXMaster﹕ A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
09-01 10:25:07.755      350-890/? E/ALSAStreamOps﹕ setParameters(): keyRouting with device2 0x2
09-01 10:25:07.805      350-890/? E/ACDB-LOADER﹕ Error: ACDB AudProc vol returned = -19
09-01 10:25:07.855  30160-30352/? E/LoadTask﹕ Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.j.s.c(Unknown Source)
            at com.google.android.exoplayer.e.c.o.b(Unknown Source)
            at com.google.android.exoplayer.e.c.o.a(Unknown Source)
            at com.google.android.exoplayer.e.c.l.a(Unknown Source)
            at com.google.android.exoplayer.f.f.a(Unknown Source)
            at com.google.android.exoplayer.f.v.h(Unknown Source)
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
09-01 10:25:07.855  30160-30160/? E/EventLogger﹕ internalError [0.50, loadError]
    com.google.android.exoplayer.i.ab: Unexpected ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.j.s.c(Unknown Source)
            at com.google.android.exoplayer.e.c.o.b(Unknown Source)
            at com.google.android.exoplayer.e.c.o.a(Unknown Source)
            at com.google.android.exoplayer.e.c.l.a(Unknown Source)
            at com.google.android.exoplayer.f.f.a(Unknown Source)
            at com.google.android.exoplayer.f.v.h(Unknown Source)
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
09-01 10:25:07.955  30160-30352/? E/LoadTask﹕ Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.j.s.c(Unknown Source)
            at com.google.android.exoplayer.e.c.o.b(Unknown Source)
            at com.google.android.exoplayer.e.c.o.a(Unknown Source)
            at com.google.android.exoplayer.e.c.l.a(Unknown Source)
            at com.google.android.exoplayer.f.f.a(Unknown Source)
            at com.google.android.exoplayer.f.v.h(Unknown Source)
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
09-01 10:25:07.965  30160-30160/? E/EventLogger﹕ internalError [0.61, loadError]
    com.google.android.exoplayer.i.ab: Unexpected ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.j.s.c(Unknown Source)
            at com.google.android.exoplayer.e.c.o.b(Unknown Source)
            at com.google.android.exoplayer.e.c.o.a(Unknown Source)
            at com.google.android.exoplayer.e.c.l.a(Unknown Source)
            at com.google.android.exoplayer.f.f.a(Unknown Source)
            at com.google.android.exoplayer.f.v.h(Unknown Source)
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
09-01 10:25:08.995  30160-30352/? E/LoadTask﹕ Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.j.s.c(Unknown Source)
            at com.google.android.exoplayer.e.c.o.b(Unknown Source)
            at com.google.android.exoplayer.e.c.o.a(Unknown Source)
            at com.google.android.exoplayer.e.c.l.a(Unknown Source)
            at com.google.android.exoplayer.f.f.a(Unknown Source)
            at com.google.android.exoplayer.f.v.h(Unknown Source)
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
09-01 10:25:08.995  30160-30160/? E/EventLogger﹕ internalError [1.64, loadError]
    com.google.android.exoplayer.i.ab: Unexpected ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.j.s.c(Unknown Source)
            at com.google.android.exoplayer.e.c.o.b(Unknown Source)
            at com.google.android.exoplayer.e.c.o.a(Unknown Source)
            at com.google.android.exoplayer.e.c.l.a(Unknown Source)
            at com.google.android.exoplayer.f.f.a(Unknown Source)
            at com.google.android.exoplayer.f.v.h(Unknown Source)
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
09-01 10:25:11.085  30160-30352/? E/LoadTask﹕ Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.j.s.c(Unknown Source)
            at com.google.android.exoplayer.e.c.o.b(Unknown Source)
            at com.google.android.exoplayer.e.c.o.a(Unknown Source)
            at com.google.android.exoplayer.e.c.l.a(Unknown Source)
            at com.google.android.exoplayer.f.f.a(Unknown Source)
            at com.google.android.exoplayer.f.v.h(Unknown Source)
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
09-01 10:25:11.095  30160-30160/? E/EventLogger﹕ internalError [3.74, loadError]
    com.google.android.exoplayer.i.ab: Unexpected ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.j.s.c(Unknown Source)
            at com.google.android.exoplayer.e.c.o.b(Unknown Source)
            at com.google.android.exoplayer.e.c.o.a(Unknown Source)
            at com.google.android.exoplayer.e.c.l.a(Unknown Source)
            at com.google.android.exoplayer.f.f.a(Unknown Source)
            at com.google.android.exoplayer.f.v.h(Unknown Source)
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
09-01 10:25:11.385  30160-30335/? E/AudioTrack﹕ Discontinuity detected [expected 4430301, got 260658]
09-01 10:25:11.515  30160-30335/? E/AudioTrack﹕ Discontinuity detected [expected 399977, got 4572781]
09-01 10:25:12.075  30160-30335/? E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.j: com.google.android.exoplayer.i.ab: Unexpected ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.x.a_(Unknown Source)
            at com.google.android.exoplayer.q.k(Unknown Source)
            at com.google.android.exoplayer.q.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.j.w.run(Unknown Source)
     Caused by: com.google.android.exoplayer.i.ab: Unexpected ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.j.s.c(Unknown Source)
            at com.google.android.exoplayer.e.c.o.b(Unknown Source)
            at com.google.android.exoplayer.e.c.o.a(Unknown Source)
            at com.google.android.exoplayer.e.c.l.a(Unknown Source)
            at com.google.android.exoplayer.f.f.a(Unknown Source)
            at com.google.android.exoplayer.f.v.h(Unknown Source)
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
09-01 10:25:12.115  30160-30160/? E/EventLogger﹕ playerFailed [4.76]
    com.google.android.exoplayer.j: com.google.android.exoplayer.i.ab: Unexpected ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.x.a_(Unknown Source)
            at com.google.android.exoplayer.q.k(Unknown Source)
            at com.google.android.exoplayer.q.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.j.w.run(Unknown Source)
     Caused by: com.google.android.exoplayer.i.ab: Unexpected ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.j.s.c(Unknown Source)
            at com.google.android.exoplayer.e.c.o.b(Unknown Source)
            at com.google.android.exoplayer.e.c.o.a(Unknown Source)
            at com.google.android.exoplayer.e.c.l.a(Unknown Source)
            at com.google.android.exoplayer.f.f.a(Unknown Source)
            at com.google.android.exoplayer.f.v.h(Unknown Source)
            at com.google.android.exoplayer.i.z.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
09-01 10:25:12.155  30160-30160/? E/Parcel﹕ Reading a NULL string not supported here.
09-01 10:25:12.155     350-4928/? E/﹕ Destroy C2D instance
09-01 10:25:12.155     350-4928/? E/﹕ Destroy C2D instance
09-01 10:25:24.435      403-403/? E/Parcel﹕ Reading a NULL string not supported here.
09-01 10:25:24.435      403-403/? E/Parcel﹕ Reading a NULL string not supported here.

**Comment by ojw28** [comment]
Same as #748 in that case. Let's use that issue to track.
