### ISSUE TITLE
 Some questions about encryption and decryption

### ISSUE THREAD

**Issue by NerdAnonymous** [google/ExoPlayer#7509]
This is the m3u8 file returned by the server：
```
#EXTM3U
#EXT-X-TARGETDURATION:17
#EXT-X-ALLOW-CACHE:YES
#EXT-SECRET-KEY-INDEX:28
#EXT-SECRET-KEY:kUBz388WOmIz3pUpRf/zG7tYW1lIG9lEnZ3UTLZjqxzLDzM72vUgb/cxr0a3qsyaFvtrJt1L+zrWaPuPWkb6tWWZKPsPYi9da1ODnFi8oCyjf8DSPvlIxPOZRcbWdsfnaSmy6H5qKuJ8h0sk5PV+6NIcbFxCMyXKvWFcVqcyjaw=
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
http:\/\/xxx.com\/xxx\/xxx\/xxx\/xxx\/seg-1-v1-a1.ts
#EXTINF:16.667,
seg-1-v1-a1.ts
#EXTINF:8.333,
seg-2-v1-a1.ts
#EXTINF:8.333,
seg-3-v1-a1.ts
#EXTINF:8.333,
seg-4-v1-a1.ts
#EXTINF:8.333,
```

note: #EXT-SECRET-KEY-INDEX and #EXT-SECRET-KEY are server-defined decryption fields used to decrypt the encrypted ts file stream of the server，I tried to modify HlsPlaylistParser to get the correct key and customize the datasource to decrypt, but it got an error

```
     Caused by: com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.findEndOfFirstTsPacketInBuffer(TsExtractor.java:392)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:260)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:268)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:212)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:389)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

This is my custom decrypted file：

```
public class SecretDataSource implements DataSource {

  private final DataSource upstream;
  private final long secretCipher;

  public SecretDataSource(DataSource upstream, long secretCipher) {
    this.upstream = upstream;
    this.secretCipher = secretCipher;
  }

  @Override
  public void addTransferListener(TransferListener transferListener) {
    upstream.addTransferListener(transferListener);
  }

  @Override
  public long open(DataSpec dataSpec) throws IOException {
    long open = upstream.open(dataSpec);
    return open;
  }

  @Override
  public int read(byte[] buffer, int offset, int readLength) throws IOException {
    int deBufLen = BCrypto.decodeVideoBuf2(buffer, readLength, secretCipher, offset);
    return deBufLen;
  }

  @Nullable
  @Override
  public Uri getUri() {
    return upstream.getUri();
  }

  @Override
  public void close() throws IOException {
    upstream.close();
  }
}
```

**Comment by icbaker** [comment]
Drive by comment: Your `read()` method doesn't seem to actually do any reading? `buffer` is an output parameter you're expected to fill with data.
"buffer - The buffer into which the read data should be stored."
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DataSource.html#read-byte:A-int-int-

Should there be another line in there to call `upstream.read()` to actually read the data before you try and decrypt it?

```java
@Override
public int read(byte[] buffer, int offset, int readLength) throws IOException {
  int bytesRead = upstream.read(buffer, offset, readLength);
  int deBufLen = BCrypto.decodeVideoBuf2(buffer, bytesRead, secretCipher, offset);
  return deBufLen;
}
```

(I don't know the contract of `BCrypto.decodeVideoBuf2` so it's difficult to know if that call is correct. I'm assuming it does the decryption in-place on `buffer`, or at least that that's both an in & out parameter)
