### ISSUE TITLE
IllegalStateException at LoadTask

### ISSUE THREAD

**Issue by ppamorim** [google/ExoPlayer#751]
Hi friends.
Sometimes the loader of ExoPlayer throws this exception and the video returns an black screen, the complete log:

    08-31 08:49:07.870   4977-14714/com.happyApp W/MessageQueue﹕ Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {2ead6980} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {2ead6980} sending message to a Handler on a dead thread
            at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
            at android.os.Handler.enqueueMessage(Handler.java:631)
            at android.os.Handler.sendMessageAtTime(Handler.java:600)
            at android.os.Handler.sendMessageDelayed(Handler.java:570)
            at android.os.Handler.sendEmptyMessageDelayed(Handler.java:534)
            at android.os.Handler.sendEmptyMessage(Handler.java:519)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:212)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

Happens on the source of master branch, at LG G2 with Android 5.1.1.
This issue is destroying my app, a lot of user are saying the same problem and my rating was lowered a lot :(

**Comment by ojw28** [comment]
That error message is harmless. It occasionally happens when the player is released, and can be safely ignored. See #426. Whatever your issue is, it's something else. In general posting a full bug report captured from a device is more helpful for debugging an issue. Please open a separate issue if you're able to provide more detailed information.
