### ISSUE TITLE
com.google.android.exoplayer2.source.BehindLiveWindowException

### ISSUE THREAD

**Issue by niteshfel** [google/ExoPlayer#7524]
when i have stream HLS video then this error came and onPlayerError ExoPlaybackException i found this error so what is the solution of this error why this error came any reason ?

**Comment by brookmg** [comment]
I am currently experiencing this error. Happens after playing one minute or less from the stream. A similar issue to this was locked to the contributors only since 2017.
```
E/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.source.BehindLiveWindowException
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:300)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:645)
        at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:78)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading(HlsMediaPeriod.java:363)
        at com.google.android.exoplayer2.MediaPeriodHolder.continueLoading(MediaPeriodHolder.java:205)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1760)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1739)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by AquilesCanta** [comment]
Please search in the issue tracker before reporting. There's is [plenty of material](https://github.com/google/ExoPlayer/issues?q=is%3Aissue+behindlivewindowexception) about BehindLiveWindowException. For example in #4723 you'll find an explanation of what it is and the issue has a contribution from a user who proposes a way of preventing BLWE from happening. Ultimately, you'll need to place a safety net in case BLWE happens. The demo app re-prepares the media source when a BLWE occurs. [See here](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L677).

**Comment by brookmg** [comment]
Thanks, @AquilesCanta. I missed those.

**Comment by AquilesCanta** [comment]
No problem. Good luck.

**Comment by niteshfel** [comment]
Thanks
