### ISSUE TITLE
Switch audio tracks before playback on ProgressiveMediaSource?

### ISSUE THREAD

**Issue by phharley17** [google/ExoPlayer#7529]
### [REQUIRED] Searched documentation and issues:
Hi, this question is in regard of ProgressiveMediaSource/local media (ie. MKV with H264 video, AAC and AC3 audio) not for DASH/HLS/SS . Thanks to the documentation here: [Track Selection](https://exoplayer.dev/track-selection.html), I am able to chance the desired track before playback, by changing the language code using `setPreferredAudioLanguage(...)` the problem is when the audio tracks are from different audio codec this seem to be ignored and it plays the first one anyway. If they are on the same codec, switching audio tracks works fine.

Then I have tried with the documentation here: [DefaultTrackSelector, Selecting specific tracks](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html). Using `setSelectionOverride(rendererIndex, rendererTrackGroups, selectionOverride)` I have managed to switch the the audio track regardless of the audio codec the problem I face is, that it seems to be allowing to do it once `MappedTrackInfo` is loaded to the player and while playing? With a player event like `onIsPlayingChanged()` I am able switch the audio track. But I can still hear a little of the initial audio track being played then is when it switch to the selected track. Obviously not a pretty approach. Happens more often if I am using ClippingMediaSource.

The [sample code here](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/TrackSelectionDialog.java). Seem to be doing something similar but I think it also does it after the playback has been started/loaded too. Or else I am not understanding it correctly.

### [REQUIRED] Question:
Is there any way to switch the audio track like above but before the player starts playing? Perhaps any other particular player event I should be using? Forgive my ignorance with the library.

**Comment by AquilesCanta** [comment]
I think we just need to debug why the `DefaultTrackSelector` is selecting something different than what you want to select. You always have the option of implementing your own `TrackSelector` which does exactly what you want (probably extending the Default one), but this is a use case that should be normally handled using built-in components.

Can you provide the problematic piece of media and precisely describe required steps, expected and observed behavior? A full bug report would also help.

**Comment by ojw28** [comment]
It would also be helpful if you could try playing the file in our demo app, after modifying it just to make your desired constraint based track selection (i.e., add selection code using `setPreferredAudioLanguage`). Then, capture and provide the logcat output during playback. It's quite useful for debugging (e.g., it will indicate to what extent the device supports each of the available tracks).

**Comment by phharley17** [comment]
> I think we just need to debug why the `DefaultTrackSelector` is selecting something different than what you want to select. You always have the option of implementing your own `TrackSelector` which does exactly what you want (probably extending the Default one), but this is a use case that should be normally handled using built-in components.
> 
> Can you provide the problematic piece of media and precisely describe required steps, expected and observed behavior? A full bug report would also help.

Hi, It is indeed selecting the track that I want to select. but it seems to be switching it after a few milliseconds later. I am guessing is the way I am doing it or because of the player event I am relying on. The media has h264 video, AAC audio and FLAC audio. I can get it to switch to the FLAC audio, it just plays a few milliseconds of the AAC audio and then switch to the FLAC audio. Very minimal but still can be heard, specially when using ClippingMediaSource. Is less noticeable if I use the ProgressiveMediaSource without clipping. If I use the playback control to go back to the beginning it is not apparent. I suppose is because the desired audio track is still loaded into the player.

This is how it kinda how is currently being executed.
```
@Override
public void onIsPlayingChanged(boolean isPlaying) 
{  
      //track_selector is an instance of DefaultTrackSelector
      if (isPlaying) {
          MappedTrackInfo mapInfo = track_selector.getCurrentMappedTrackInfo();
          tgArray = mapInfo.getTrackGroups(1); //Index for AUDIOS
          so = new DefaultTrackSelector.SelectionOverride(1, 0); //1 = Index for FLAC audio track
          track_selector.setParameters(
          track_selector.buildUponParameters().setSelectionOverride(1, tgArray, so)); } else { }
}
```
I suppose I can look into extending the TrackSelector. Sorry for the question, but will it help on selecting the desired track before playback?

I am afraid the media file may have copyrighted material. But I can try to replicate this on another file.

The following is the log, I am not sure if it can be useful. Please ignore the renderer error NO_UNSUPPORTED_TYPE, this was tested on the android emulator for some reason the FfmpegAudioRenderer extension is not loading on it. But is still being tested on a Mi Box S, which has a built-in FLAC decoder.

@ojw28 , I can definitelly give that a try too.

```
2020-06-19 08:00:15.441 32497-32497/com.example.atvdemo_v2 I/zygote: Not late-enabling -Xcheck:jni (already on)
2020-06-19 08:00:15.454 32497-32497/com.example.atvdemo_v2 W/zygote: Unexpected CPU variant for X86 using defaults: x86
2020-06-19 08:00:15.798 32497-32508/com.example.atvdemo_v2 I/zygote: Background concurrent copying GC freed 3934(1229KB) AllocSpace objects, 0(0B) LOS objects, 67% free, 738KB/2MB, paused 4.427ms total 157.212ms
2020-06-19 08:00:15.885 32497-32497/com.example.atvdemo_v2 I/DefaultRenderersFactory: Loaded FfmpegAudioRenderer.
2020-06-19 08:00:15.892 32497-32497/com.example.atvdemo_v2 I/ExoPlayerImpl: Init f959557 [ExoPlayerLib/2.11.5] [generic_x86, sdk_google_atv_x86, unknown, 26]
2020-06-19 08:00:16.063 32497-32536/com.example.atvdemo_v2 D/OpenGLRenderer: HWUI GL Pipeline
2020-06-19 08:00:16.141 32497-32536/com.example.atvdemo_v2 I/OpenGLRenderer: Initialized EGL, version 1.4
2020-06-19 08:00:16.141 32497-32536/com.example.atvdemo_v2 D/OpenGLRenderer: Swap behavior 1
2020-06-19 08:00:16.141 32497-32536/com.example.atvdemo_v2 W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
2020-06-19 08:00:16.141 32497-32536/com.example.atvdemo_v2 D/OpenGLRenderer: Swap behavior 0
2020-06-19 08:00:16.172 32497-32502/com.example.atvdemo_v2 I/zygote: Do partial code cache collection, code=30KB, data=19KB
2020-06-19 08:00:16.174 32497-32502/com.example.atvdemo_v2 I/zygote: After code cache collection, code=26KB, data=18KB
2020-06-19 08:00:16.174 32497-32502/com.example.atvdemo_v2 I/zygote: Increasing code cache capacity to 128KB
2020-06-19 08:00:16.204 32497-32536/com.example.atvdemo_v2 D/EGL_emulation: eglCreateContext: 0xae6b2820: maj 3 min 1 rcv 4
2020-06-19 08:00:16.258 32497-32536/com.example.atvdemo_v2 D/EGL_emulation: eglMakeCurrent: 0xae6b2820: ver 3 1 (tinfo 0xa26bfa70)
2020-06-19 08:00:16.270 32497-32532/com.example.atvdemo_v2 I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
2020-06-19 08:00:16.285 32497-32536/com.example.atvdemo_v2 E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
2020-06-19 08:00:16.285 32497-32536/com.example.atvdemo_v2 E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
2020-06-19 08:00:16.288 32497-32532/com.example.atvdemo_v2 W/LibraryLoader: Failed to load [avutil, swresample, avcodec, ffmpeg]
2020-06-19 08:00:16.343 32497-32551/com.example.atvdemo_v2 I/OMXClient: Treble IOmx obtained
2020-06-19 08:00:16.425 32497-32536/com.example.atvdemo_v2 D/EGL_emulation: eglMakeCurrent: 0xae6b2820: ver 3 1 (tinfo 0xa26bfa70)
2020-06-19 08:00:16.441 32497-32508/com.example.atvdemo_v2 I/zygote: Background concurrent copying GC freed 7076(495KB) AllocSpace objects, 2(136KB) LOS objects, 50% free, 2MB/4MB, paused 5.928ms total 121.394ms
2020-06-19 08:00:16.537 32497-32555/com.example.atvdemo_v2 D/EGL_emulation: eglCreateContext: 0xa5285060: maj 3 min 1 rcv 4
2020-06-19 08:00:16.575 32497-32555/com.example.atvdemo_v2 D/EGL_emulation: eglMakeCurrent: 0xa5285060: ver 3 1 (tinfo 0xa52834e0)
2020-06-19 08:00:16.597 32497-32555/com.example.atvdemo_v2 E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
2020-06-19 08:00:16.597 32497-32555/com.example.atvdemo_v2 E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
2020-06-19 08:00:16.604 32497-32555/com.example.atvdemo_v2 E/EGL_emulation: eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
2020-06-19 08:00:16.604 32497-32555/com.example.atvdemo_v2 E/EGL_emulation: tid 32555: eglQueryContext(1873): error 0x3004 (EGL_BAD_ATTRIBUTE)
2020-06-19 08:00:16.606 32497-32549/com.example.atvdemo_v2 D/SurfaceUtils: connecting to surface 0x9437f008, reason connectToSurface
2020-06-19 08:00:16.606 32497-32549/com.example.atvdemo_v2 I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 33276929
2020-06-19 08:00:16.606 32497-32549/com.example.atvdemo_v2 D/SurfaceUtils: disconnecting from surface 0x9437f008, reason connectToSurface(reconnect)
2020-06-19 08:00:16.606 32497-32549/com.example.atvdemo_v2 D/SurfaceUtils: connecting to surface 0x9437f008, reason connectToSurface(reconnect)
2020-06-19 08:00:16.609 32497-32551/com.example.atvdemo_v2 E/ACodec: [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
2020-06-19 08:00:16.619 32497-32551/com.example.atvdemo_v2 I/ACodec: codec does not support config priority (err -1010)
2020-06-19 08:00:16.747 32497-32561/com.example.atvdemo_v2 I/OMXClient: Treble IOmx obtained
2020-06-19 08:00:16.763 32497-32561/com.example.atvdemo_v2 I/ACodec: codec does not support config priority (err -2147483648)
2020-06-19 08:00:16.764 32497-32561/com.example.atvdemo_v2 I/ACodec: codec does not support config operating rate (err -2147483648)
2020-06-19 08:00:16.829 32497-32549/com.example.atvdemo_v2 D/MediaCodec: [OMX.google.h264.decoder] setting dataspace on output surface to #104
2020-06-19 08:00:16.905 32497-32549/com.example.atvdemo_v2 D/SurfaceUtils: connecting to surface 0x9181f008, reason connectToSurface
2020-06-19 08:00:16.908 32497-32549/com.example.atvdemo_v2 I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 33276930
2020-06-19 08:00:16.908 32497-32549/com.example.atvdemo_v2 D/SurfaceUtils: disconnecting from surface 0x9181f008, reason connectToSurface(reconnect)
2020-06-19 08:00:16.908 32497-32549/com.example.atvdemo_v2 D/SurfaceUtils: connecting to surface 0x9181f008, reason connectToSurface(reconnect)
2020-06-19 08:00:16.908 32497-32549/com.example.atvdemo_v2 D/SurfaceUtils: disconnecting from surface 0x9437f008, reason disconnectFromSurface
2020-06-19 08:00:17.006 32497-32549/com.example.atvdemo_v2 D/SoftwareRenderer: setting dataspace on output surface to #104
2020-06-19 08:00:17.050 32497-32532/com.example.atvdemo_v2 D/AudioTrack: Client defaulted notificationFrames to 4000 for frameCount 12000
2020-06-19 08:00:17.331 32497-32532/com.example.atvdemo_v2 E/ExoPlayerImplInternal: Renderer error: index=1, type=audio, format=Format(3, null, null, audio/flac, null, -1, und, [-1, -1, -1.0], [2, 48000]), rendererSupport=NO_UNSUPPORTED_TYPE
      com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: [-49999], Format(3, null, null, audio/flac, null, -1, und, [-1, -1, -1.0], [2, 48000])
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:563)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1731)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainAndReinitializeCodec(MediaCodecRenderer.java:1494)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1276)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:556)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:814)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:712)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: [-49999], Format(3, null, null, audio/flac, null, -1, und, [-1, -1, -1.0], [2, 48000])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:847)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:561)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1731) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainAndReinitializeCodec(MediaCodecRenderer.java:1494) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1276) 
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:556) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:814) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:712) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
2020-06-19 08:00:17.351 32497-32549/com.example.atvdemo_v2 D/SurfaceUtils: disconnecting from surface 0x9181f008, reason disconnectFromSurface
```

**Comment by phharley17** [comment]
I was able to get it resolved by kind-of extending `TrackSelector`. The track switching via `SelectionOverride` always work wonderfully. My specific case, and very specific I must say, desired random and programatically audio track selection before the player start rendering/playing and regardless of the audio codec. Currently it only seem to allow once `MappedTrackInfo` is not null or when the player is already playing the content, thus creating the behavior described above. But was able to get a solution by extending `TrackSelector`
