### ISSUE TITLE
Assertion crashes app for HLS from SampleQueue.discardUpstreamSampleMetadata

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#7549]
### [REQUIRED] Issue description
I'm seeing uncaught exceptions in Crashlytics coming from ExoPlayer:
```
Fatal Exception: java.lang.IllegalArgumentException
       at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
       at com.google.android.exoplayer2.source.SampleQueue.discardUpstreamSampleMetadata(SampleQueue.java:770)
       at com.google.android.exoplayer2.source.SampleQueue.discardUpstreamSamples(SampleQueue.java:195)
       at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.discardUpstreamMediaChunksFromIndex(HlsSampleStreamWrapper.java:1134)
       at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.discardUpstream(HlsSampleStreamWrapper.java:910)
       at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.onLoadCanceled(HlsSampleStreamWrapper.java:786)
       at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.onLoadCanceled(HlsSampleStreamWrapper.java:88)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:473)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

### [REQUIRED] Reproduction steps
Issue is observed via crashlytics on users devices. App does not request player to stop/cancel playback. Here are last messages right before assertion fails:
```
13:18:08 main|D] EventLogger: timeline [eventTime=1072.81, mediaPos=23.46, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
13:18:08 main|D] EventLogger:   period [?]
13:18:08 main|D] EventLogger:   window [60.00, true, true]
13:18:08 main|D] EventLogger: ]
13:18:19 main|D] EventLogger: timeline [eventTime=1084.01, mediaPos=24.66, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
13:18:19 main|D] EventLogger:   period [?]
13:18:19 main|D] EventLogger:   window [60.00, true, true]
13:18:19 main|D] EventLogger: ]
13:18:31 main|D] EventLogger: timeline [eventTime=1095.17, mediaPos=15.81, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
13:18:31 main|D] EventLogger:   period [?]
13:18:31 main|D] EventLogger:   window [60.00, true, true]
13:18:31 main|D] EventLogger: ]
13:18:34 main|E] EventLogger: audioTrackUnderrun [eventTime=1099.00, mediaPos=19.28, window=0, period=0, 65600, 341, 666]]
13:18:35 main|E] EventLogger: audioTrackUnderrun [eventTime=1099.38, mediaPos=19.54, window=0, period=0, 65600, 341, 117]]
13:18:35 main|D] EventLogger: timeline [eventTime=1099.48, mediaPos=9.92, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
13:18:35 main|D] EventLogger:   period [?]
13:18:35 main|D] EventLogger:   window [60.00, true, true]
13:18:35 main|D] EventLogger: ]
13:18:36 main|E] EventLogger: audioTrackUnderrun [eventTime=1100.51, mediaPos=10.26, window=0, period=0, 65600, 341, 335]]
13:18:38 main|D] EventLogger: droppedFrames [eventTime=1102.34, mediaPos=11.07, window=0, period=0, 50]
13:18:46 main|D] EventLogger: timeline [eventTime=1110.65, mediaPos=9.38, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
13:18:46 main|D] EventLogger:   period [?]
13:18:46 main|D] EventLogger:   window [60.00, true, true]
13:18:46 main|D] EventLogger: ]
13:18:50 main|E] EventLogger: audioTrackUnderrun [eventTime=1114.70, mediaPos=13.02, window=0, period=0, 65600, 341, 740]]
13:18:51 main|D] EventLogger: droppedFrames [eventTime=1115.17, mediaPos=13.62, window=0, period=0, 50]
13:18:54 main|E] EventLogger: audioTrackUnderrun [eventTime=1119.14, mediaPos=17.20, window=0, period=0, 65600, 341, 217]]
13:18:55 main|E] EventLogger: audioTrackUnderrun [eventTime=1119.56, mediaPos=17.58, window=0, period=0, 65600, 341, 219]]
13:18:55 main|D] EventLogger: timeline [eventTime=1119.69, mediaPos=17.67, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
13:18:55 main|D] EventLogger:   period [?]
13:18:55 main|D] EventLogger:   window [60.00, true, true]
13:18:55 main|D] EventLogger: ]
13:18:55 main|E] EventLogger: audioTrackUnderrun [eventTime=1119.86, mediaPos=17.67, window=0, period=0, 65600, 341, 291]]
13:18:56 main|E] EventLogger: audioTrackUnderrun [eventTime=1121.12, mediaPos=18.78, window=0, period=0, 65600, 341, 333]]
13:18:57 main|D] EventLogger: droppedFrames [eventTime=1121.91, mediaPos=19.80, window=0, period=0, 50]
13:19:00 r:Playback|E] UncaughtExceptionHandler: Uncaught exception java.lang.IllegalArgumentException: null
```

### [REQUIRED] Link to test content
not applicable

### [REQUIRED] A full bug report captured from the device
not applicable

### [REQUIRED] Version of ExoPlayer being used
* dev-v2 2.11.4 (dac3dde7bb8d79e785f65b0c0c7b7425f41dffa6)

Version which was used before this one and did not have such issue: dfec0338c59e6e651a7b1acadd9687c682f6de6c

### [REQUIRED] Device(s) and version(s) of Android being used
* Xiaomi mibox, mibox s,
* BRAVIA 4K GB ATV3, BRAVIA 4K GB
* TCL Beyond TV
* Android 9, 8 (60%/40%)

**Comment by tonihei** [comment]
This was a bug in the code after merging a PR and has been fixed since (I think by https://github.com/google/ExoPlayer/commit/7bc5fa855f774ce198e23a455fec751b7743486f).
