### ISSUE TITLE
Content Uris

### ISSUE THREAD

**Issue by liadpaz** [google/ExoPlayer#7620]
How to correctly use content Uris as a source? Currently I am using the DefaultDataSourceFactory as a source, but after some time of playing it starts buffering and interrupting playback (I can't hear any buffering at any other local songs music player).

I've been searching for it all over the internet (Stackoverflow, GitHub and random sites).

**Comment by tonihei** [comment]
If it starts playing, I'd assume your content Uri is working correctly? If the Uri were wrong, it couldn't find the file and playback would never start. 

If playback of local files starts buffering and stopping during playback, there may be problems in the media. Please provide an example file if you want us to have a look.

**Comment by liadpaz** [comment]
@tonihei Thanks for the reply, it took me a bit to reply because I thought it didn't do it now.
But it still happens, I'm using the `MediaSessionConnector` and I'm preparing the `ExoPlayer` in the `MediaSessionConnector.PlaybackPreparer`. 
My code looks like this:

```
for (song in songs) {
 mediaSource.addMediaSource(ProgressiveMediaSource.Factory(dataSourceFactory).setTag(song.mediaDescription).createMediaSource(song.songUri))
}
        exoPlayer.seekTo(index, 0)
```

The `dataSourceFactory` is the same instance always (it comes from the service that holds the player).

Also I think that every time that I encountered this 'bug' it's when the app is on background.

*I'm also using a `MediaSessionConnector.QueueEditor` so I'm using only one media source and it's already prepared in the `ExoPlayer`, I just adding/removing/moving media sources within it

**Comment by tonihei** [comment]
> Also I think that every time that I encountered this 'bug' it's when the app is on background.

If you app goes into background with ExoPlayer still running, you need to use a foreground service. See [this StackOverflow post ](https://stackoverflow.com/questions/58657511/exoplayer-audio-not-playing-in-background-service)for an example and further explanations. Could this be the reason for your playback problems while in background?

**Comment by liadpaz** [comment]
I'm promoting the service to be on foreground (plus I'm using the `PlayerNotificationManager` as in the uamp app).
When in background it's not that I can't hear any playback, it's just that sometimes it's starts buffering and resumes playback soon after but sometimes it's buffering and resuming multiple times in a short time period.

**Comment by tonihei** [comment]
@marcbaechinger Is there anything else that needs to be taken care of when using ExoPlayer in a service?

**Comment by marcbaechinger** [comment]
I'm not aware of something special to take care when in a foreground service actually. If there was a problem with the service not being in foreground, the service is usually just killed by the system, which results in ExoPlayer being destroyed. 

I'm not aware of such buffering problems in a foreground service.

I'd be probably be interesting to see the logs. Can you create a bug report and upload here?

**Comment by liadpaz** [comment]
@marcbaechinger I'd be happy to send you the logs, just can you tell me how to get them?

**Comment by marcbaechinger** [comment]
Best is [to capture a full bugreport](https://developer.android.com/studio/debug/bug-report) just after the problem occured. You can then upload the bug report here.

**Comment by liadpaz** [comment]
@marcbaechinger I could finally get the report, I hope its enough for you to help me.

[link](https://drive.google.com/file/d/14xL1wjhuSXABEh5ygSITjHmOX-GKvhuD/view?usp=sharing)

(I couldn't upload it to here for some reason)

**Comment by raghavtilak** [comment]
> How to correctly use content Uris as a source? Currently I am using the DefaultDataSourceFactory as a source, but after some time of playing it starts buffering and interrupting playback (I can't hear any buffering at any other local songs music player).
> 
> I've been searching for it all over the internet (Stackoverflow, GitHub and random sites).

@liadpaz hey, i am facing the same issue. Not able to load content uri. Did you find any solution?

**LOGS**
2021-06-14 20:03:53.742 16955-17316/com.raghav.videomerger E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.ContentDataSource$ContentDataSourceException: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.ContentDataSource.open(ContentDataSource.java:110)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1702)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1518)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1435)
        at com.google.android.exoplayer2.upstream.ContentDataSource.open(ContentDataSource.java:70)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

Please help.

**Comment by marcbaechinger** [comment]
@raghavtilak Can you please open a new issue? I don't think its related because your stack trace shows a `FileNotFoundException`. If you file a new issue, please also add the URI that you tried to load and that produced the stack trace. 

It seems to be a missing asset that you want to play and that is not found, so it's worth double checking the asset URI you are using and then mention it in the new issue.

**Comment by marcbaechinger** [comment]
Closing due to inactivity.
