### ISSUE TITLE
Unable to play redirect URL

### ISSUE THREAD

**Issue by wishy-viewlift** [google/ExoPlayer#7621]
Checked in the demo application for the url

[Redirect URL](https://justice-avod.amagi.tv/vod?c=justiceAA-justiceonoavod&a=BM1145&redirect_path=https%3A%2F%2Fjustice-avod.amagi.tv%2FjusticeAA-justiceonoavod%2FBM1145%2Fplaylist.m3u8)

Used for redirection

   ` public HttpDataSource.Factory buildHttpDataSourceFactory() {
    return new DefaultHttpDataSourceFactory(userAgent, DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
            DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS, true);
     }`

Gives the exception

  `None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1090)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:969)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)`

While the same URL is able to play in ios and safari.

**Comment by wishy-viewlift** [comment]
After further debugging I found when the URL is converted to URI and we call getPath() method it returns `/vod` which is causing the issue. Now if we add a or condition in inferContentType on HLS case the video plays but that is a wrong approach.

So just wanted to know what change can I make to have this working?

**Comment by wishy-viewlift** [comment]
was able to fix by overriding the extension
