### ISSUE TITLE
Playback Failed due to OMX/mediaserver died, signalling error!

### ISSUE THREAD

**Issue by SharanKumarReddyKambham** [google/ExoPlayer#7626]
Hello ,

I 've been working with demo exoplayer  of version 2.11 and playing Mpeg dash stream on the long run ,it plays fine till approximately 20 hours and after that the playback fails wit the following :

```07-11 10:03:48.171 27604 18163 E ACodec  : OMX/mediaserver died, signalling error!
07-11 10:03:48.171 27604 18163 E ACodec  : signalError(omxError 0x8000100d, internalError -32)
07-11 10:03:48.171 27604 18163 E MediaCodec: Codec reported err 0xffffffe0, actionCode 0, while in state 6
07-11 10:03:48.171 27604 18160 W ACodec  : not dequeuing from native window due to fatal error
07-11 10:03:48.171 27604 18159 E MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
07-11 10:03:48.171 27604 18160 W ACodec  : not dequeuing from native window due to fatal error
07-11 10:03:48.171 27604 18160 E ACodec  : OMX/mediaserver died, signalling error!
07-11 10:03:48.171 27604 18160 E ACodec  : signalError(omxError 0x8000100d, internalError -32)
07-11 10:03:48.175 27604 18159 D SurfaceUtils: disconnecting from surface 0x8d7cc008, reason disconnectFromSurface
07-11 10:03:48.175 27604 18160 E ACodec  : signalError(omxError 0x80001001, internalError -2147483648)
07-11 10:03:48.176 27604 18159 E MediaCodec: Codec reported err 0xffffffe0, actionCode 0, while in state 0
07-11 10:03:48.176 27604 18159 E MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 0
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(1, null, null, video/avc, avc1.4d4028, 5000000, null, [1920, 1080, 25.0], [-1, -1]), rendererSupport=YES
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:735)
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:193)
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:65)
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:   Caused by: java.lang.IllegalStateException
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:       at android.media.MediaCodec.releaseOutputBuffer(Native Method)
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:       at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:2804)
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.renderOutputBufferV21(MediaCodecVideoRenderer.java:1203)
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.processOutputBuffer(MediaCodecVideoRenderer.java:929)
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1590)
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:721)
07-11 10:03:48.185 27604 27689 E ExoPlayerImplInternal:       ... 5 more
07-11 10:03:48.185 27604 27604 D EventLogger: droppedFrames [eventTime=73796.35, mediaPos=-1.43, window=0, period=0, 2]
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal: Disable failed.
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal:   java.lang.IllegalStateException
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_flush(Native Method)
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal:       at android.media.MediaCodec.flush(MediaCodec.java:2131)
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:777)
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.flushOrReleaseCodec(MediaCodecVideoRenderer.java:724)
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:636)
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:569)
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:168)
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1136)
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:891)
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:382)
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:193)
07-11 10:03:48.188 27604 27689 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:65)
07-11 10:03:48.190 27604 27604 D EventLogger: decoderDisabled [eventTime=73796.36, mediaPos=-1.43, window=0, period=0, video]
07-11 10:03:48.192  3708  3941 E bt_btif : register_notification_rsp: Avrcp device is not connected, handle: 0x0
07-11 10:03:48.192  3708  3941 I chatty  : uid=1002(bluetooth) BluetoothAvrcpH identical 4 lines
07-11 10:03:48.192  3708  3941 E bt_btif : register_notification_rsp: Avrcp device is not connected, handle: 0x0
07-11 10:03:48.193 27604 27604 D EventLogger: decoderDisabled [eventTime=73796.36, mediaPos=-1.43, window=0, period=0, audio]
07-11 10:03:48.195 27604 27689 E ExoPlayerImplInternal: Disable failed.
```

**Existing issues**: https://github.com/google/ExoPlayer/issues/7520

### Issue description
Exoplayer demo player plays the MPEG dash stream for approximately 21 hours, and after that playback fails stating the above-mentioned exception

###  Reproduction steps
Play any live MPEG dash stream for continuous 21 hours in AMLogic boxes

### [REQUIRED] Link to test content
As the stream is a proprietary am unable to give access to it here are the stream properties

videoProperties: codec :avc1.4d4028
audioproperties: codec :mp4a.40.2

### [REQUIRED] A full bug report captured from the device
[playbackfail.log](https://github.com/google/ExoPlayer/files/4923353/playbackfail.log)

### [REQUIRED] Version of ExoPlayer being used
Exoplayer 2.11

### [REQUIRED] Device(s) and version(s) of Android being used
TX3 Android 9

**Comment by Samrobbo** [comment]
Hi, 

Please can you capture a full bug report using "adb bugreport". Please attach the captured bug report as a file. If you don't wish to post it publicly, please submit the issue, then email the bug report to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number.

You also mentioned this works with any live MPEG dash stream, in which case can you verify it works with a public stream and then provide that stream link. 

Thanks.

**Comment by Samrobbo** [comment]
Alternatively, if you're unable to share test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by Samrobbo** [comment]
There was also an issue with Android Marshmallow and earlier, where a release build of the apk would perform much better than a debug build, which may not make a difference but it's worth checking.

**Comment by SharanKumarReddyKambham** [comment]
Hi team shared the content to the dev.exoplayer@gmail.com, please check and update.

_There was also an issue with Android Marshmallow and earlier, where a release build of the app would perform much better than a debug build, which may not make a difference but it's worth checking._

I think the above statement doesn't make any point as we are checking in Android 9 (PIE) OS.

**Comment by Samrobbo** [comment]
Hi, Can we please get a bug report, as I described above?

Thanks.

**Comment by SharanKumarReddyKambham** [comment]
Hi Please find the full log attached.
[full_log_report.log](https://github.com/google/ExoPlayer/files/5015068/full_log_report.log)

**Comment by ggnull35** [comment]
Is there any update for this case ? We are facing a similar issue (just duration is shorter) on OMX for AAC HE v2 decoding.

**Comment by andrewlewis** [comment]
There seems to be a native crash from the software AAC decoder:

```
07-11 10:03:47.967  3444  3444 I /system/bin/tombstoned: received crash request for pid 3438
07-11 10:03:47.986  3438 18164 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-11 10:03:47.986  3438 18164 F DEBUG   : Build fingerprint: 'Amlogic/u211/u211:9/PPR1.180610.011/20191021:userdebug/test-keys'
07-11 10:03:47.986  3438 18164 F DEBUG   : Revision: '0'
07-11 10:03:47.986  3438 18164 F DEBUG   : ABI: 'arm'
07-11 10:03:47.986  3438 18164 F DEBUG   : pid: 3438, tid: 18164, name: omx@1.0-service  >>> media.codec <<<
07-11 10:03:47.986  3438 18164 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-11 10:03:47.986  3438 18164 F DEBUG   : Abort message: 'ubsan: add-overflow'
07-11 10:03:47.986  3438 18164 F DEBUG   :     r0  00000000  r1  000046f4  r2  00000006  r3  b2922918
07-11 10:03:47.987  3438 18164 F DEBUG   :     r4  00000d6e  r5  000046f4  r6  ae982edc  r7  0000010c
07-11 10:03:47.987  3438 18164 F DEBUG   :     r8  00000002  r9  b1014044  r10 b0fdfad2  r11 b101403c
07-11 10:03:47.987  3438 18164 F DEBUG   :     ip  00000007  sp  ae982ec8  lr  b28b10e5  pc  b28a8e72
07-11 10:03:48.010  3438 18164 F DEBUG   : 
07-11 10:03:48.010  3438 18164 F DEBUG   : backtrace:
07-11 10:03:48.010  3438 18164 F DEBUG   :     #00 pc 0001ce72  /system/lib/libc.so (abort+62)
07-11 10:03:48.010  3438 18164 F DEBUG   :     #01 pc 00005a58  /system/lib/vndk-28/libstagefright_soft_aacdec.so (abort_with_message(char const*)+24)
07-11 10:03:48.010  3438 18164 F DEBUG   :     #02 pc 00005ab4  /system/lib/vndk-28/libstagefright_soft_aacdec.so (__ubsan_handle_add_overflow_minimal_abort+24)
07-11 10:03:48.010  3438 18164 F DEBUG   :     #03 pc 00011735  /system/lib/vndk-28/libstagefright_soft_aacdec.so (FDK_get32+242)
07-11 10:03:48.010  3438 18164 F DEBUG   :     #04 pc 0003160d  /system/lib/vndk-28/libstagefright_soft_aacdec.so (_Z26CBlock_DecodeHuffmanWordCBP13FDK_BITSTREAMPA4_Kt+36)
07-11 10:03:48.010  3438 18164 F DEBUG   :     #05 pc 000321d5  /system/lib/vndk-28/libstagefright_soft_aacdec.so (CBlock_ReadSpectralData(FDK_BITSTREAM*, CAacDecoderChannelInfo*, SamplingRateInfo const*, unsigned int)+512)
07-11 10:03:48.010  3438 18164 F DEBUG   :     #06 pc 00033c1b  /system/lib/vndk-28/libstagefright_soft_aacdec.so (CChannelElement_Read(FDK_BITSTREAM*, CAacDecoderChannelInfo**, CAacDecoderStaticChannelInfo**, AUDIO_OBJECT_TYPE, SamplingRateInfo*, unsigned int, unsigned int, unsigned int, unsigned char, signed char, TRANSPORTDEC*)+2238)
07-11 10:03:48.011  3438 18164 F DEBUG   :     #07 pc 0002ecaf  /system/lib/vndk-28/libstagefright_soft_aacdec.so (CAacDecoder_DecodeFrame(AAC_DECODER_INSTANCE*, unsigned int, short*, int, int)+2242)
07-11 10:03:48.011  3438 18164 F DEBUG   :     #08 pc 00006eed  /system/lib/vndk-28/libstagefright_soft_aacdec.so (aacDecoder_DecodeFrame+1020)
07-11 10:03:48.011  3438 18164 F DEBUG   :     #09 pc 000041df  /system/lib/vndk-28/libstagefright_soft_aacdec.so (android::SoftAAC2::onQueueFilled(unsigned int)+1226)
07-11 10:03:48.011  3438 18164 F DEBUG   :     #10 pc 0002a03d  /system/lib/vndk-28/libstagefright_omx.so (android::SimpleSoftOMXComponent::onMessageReceived(android::sp<android::AMessage> const&)+324)
07-11 10:03:48.011  3438 18164 F DEBUG   :     #11 pc 0002b1ed  /system/lib/vndk-28/libstagefright_omx.so (android::AHandlerReflector<android::SimpleSoftOMXComponent>::onMessageReceived(android::sp<android::AMessage> const&)+48)
07-11 10:03:48.011  3438 18164 F DEBUG   :     #12 pc 0000d2c9  /system/lib/vndk-28/libstagefright_foundation.so (android::AHandler::deliverMessage(android::sp<android::AMessage> const&)+24)
07-11 10:03:48.011  3438 18164 F DEBUG   :     #13 pc 0000fbb9  /system/lib/vndk-28/libstagefright_foundation.so (android::AMessage::deliver()+60)
07-11 10:03:48.011  3438 18164 F DEBUG   :     #14 pc 0000dfa1  /system/lib/vndk-28/libstagefright_foundation.so (android::ALooper::loop()+476)
07-11 10:03:48.011  3438 18164 F DEBUG   :     #15 pc 0000c0cb  /system/lib/vndk-sp-28/libutils.so (android::Thread::_threadLoop(void*)+286)
07-11 10:03:48.011  3438 18164 F DEBUG   :     #16 pc 00063c15  /system/lib/libc.so (__pthread_start(void*)+22)
07-11 10:03:48.011  3438 18164 F DEBUG   :     #17 pc 0001e065  /system/lib/libc.so (__start_thread+22)
```

**Comment by andrewlewis** [comment]
> As the stream is a proprietary am unable to give access to it here are the stream properties

Given that the error appears to come from code handling the AAC bitstream, I think we'll need at least a minimal part of the bitstream that reproduces the error to make progress. Is it possible to trim out the part of the audio stream that is passed to the decoder just before the error and attach that or email it to dev.exoplayer@gmail.com with subject "Issue #7626"?

Edit: actually we received the link but a media chunk is returning an HTTP 404 status code, so we can't play it. It would be helpful if you could just get the small piece of the AAC stream that triggers the error at 21 hours and share that.
