### ISSUE TITLE
DRM renew license Failed to handle key response: General DRM error (-2000)

### ISSUE THREAD

**Issue by shasapo** [google/ExoPlayer#7648]
### [REQUIRED] Searched documentation and issues
I have looked for same issues but still can't find an answer.

### [REQUIRED] Question
Using device Samsung S9
With the help of `OfflineLicenseHelper`, I have download the license, store it, then do checking for the license duration.
But when I am trying to **renew the license**, it got me this error below taken from adb bugreport :
```
I WVCdm   : [cdm_engine.cpp(529):QueryStatus] CdmEngine::QueryStatus
I WVCdm   : [cdm_engine.cpp(240):GenerateKeyRequest] CdmEngine::GenerateKeyRequest: sid14
D WVCdm   : [license.cpp(480):PrepareKeyUpdateRequest] PrepareKeyUpdateRequest: nonce=3698112418
I System.out: (HTTPLog)-Static: isSBSettingEnabled false
I System.out: (HTTPLog)-Static: isSBSettingEnabled false
I WVCdm   : [cdm_engine.cpp(326):AddKey] CdmEngine::AddKey: sid14
E WVCdm   : [license.cpp(673):HandleKeyUpdateResponse] CdmLicense::HandleKeyUpdateResponse: Unable to parse signed message
I WVCdm   : [cdm_engine.cpp(386):AddKey] CdmEngine::AddKey: key set ID: ksid1CCA21E0
E WVCdm   : [cdm_engine.cpp(399):AddKey] CdmEngine::AddKey: keys not added, result = 97
W WVCdm   : Returns UNKNOWN error for legacy status: 97
W WVCdm   : Returns UNKNOWN error for legacy status: 97
E MediaDrm-JNI: Illegal state exception: Failed to handle key response: General DRM error (-2000)
I WVCdm   : [cdm_engine.cpp(196):CloseSession] CdmEngine::CloseSession: sid14
I WVCdm   : [(0):] L3 Terminate.
I TeeSysClient: driver closed [hardware/samsung_slsi/exynos9810/mobicore/ClientLib/src/driver.cpp:120]
W System.err: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: General DRM error
W System.err: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:486)
W System.err: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:481)
W System.err: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:466)
W System.err: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:50)
W System.err: 	at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:519)
W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:107)
W System.err: 	at android.os.Looper.loop(Looper.java:237)
W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:67)
W System.err: Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: General DRM error
W System.err: 	at android.media.MediaDrm.provideKeyResponse(Native Method)
W System.err: 	at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(FrameworkMediaDrm.java:190)
W System.err: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:454)
W System.err: 	... 5 more
```
Question :
1. When renew the license, do we need to make a network call ?
2. Can you help check the reason why it failed ?

### A full bug report captured from the device
[adbFullReportLog.txt.zip](https://github.com/google/ExoPlayer/files/4951008/adbFullReportLog.txt.zip)

### Link to test content
Will be provided if needed.

**Comment by ojw28** [comment]
@shasapo - Is the same code working correctly on other devices? This will help to disambiguate between an issue with the code itself, and an issue with the underlying device.

> When renew the license, do we need to make a network call ?

Yes. A network request is required to renew the license.

> Can you help check the reason why it failed ?

This looks suspicious to me:

```
E WVCdm   : [license.cpp(673):HandleKeyUpdateResponse] CdmLicense::HandleKeyUpdateResponse: Unable to parse signed message
```

@jt64 - Please could you take a look at the bug report?

**Comment by jt64** [comment]
Based on the log message, the license response looks invalid. A network request is required to renew the license. Can you describe the steps your app is taking to do the license renewal? Also can you verify on the server that a valid renewal message was returned?
