### ISSUE TITLE
one of the my hls url is not working on exoplayer

### ISSUE THREAD

**Issue by newtestpage** [google/ExoPlayer#7651]
Hello
I faced a problem on my project . I have many hls url on my project and all of them playing on exoplayer properly . But one of the links not working . How ever it's work on google chrome,vlc etc. Any Idea how should I play this url ?
`https://dcunilive208-lh.akamaihd.net/i/dclive_1@112780/index_150.m3u8?`

I got this error :
`E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:170)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
D/EGL_emulation: eglMakeCurrent: 0xa4a08fa0: ver 2 0 (tinfo 0xa4a09970)
W/OkHttpClient: A connection to https://dcunilive208-lh.akamaihd.net/ was leaked. Did you forget to close a response body?
I/chatty: uid=10093(app.salintv.com) OkHttp Connecti identical 1 line
W/OkHttpClient: A connection to https://dcunilive208-lh.akamaihd.net/ was leaked. Did you forget to close a response body?`

**Comment by AquilesCanta** [comment]
This is an [HTTP 403](https://en.wikipedia.org/wiki/HTTP_403#:~:text=HTTP%20403%20is%20a%20HTTP,with%20the%20403%20status%20code.). This is the server telling ExoPlayer / your app that it is not authorized to access the resource it's trying to access. If I run

`curl -I https://dcunilive208-lh.akamaihd.net/i/dclive_1@112780/index_150.m3u8`

locally, I get:

`HTTP/1.1 405 Method Not Allowed`

With ffplay I also get a 403. 

I suggest you check out why the server is not allowing access. If you are right in saying it works with other players, you should compare how the server is making the distinction between them and see if you can either make changes in your app's request parameters to enable access, or make changes in the server to allow you app to access the resource.

**Comment by shayegan1988** [comment]
https://dcunilive208-lh.akamaihd.net/i/dclive_1@112780/index_150_av-p.m3u8?
sd=10&rebase=on&hdntl=exp=1595415624~acl=%2fi%2fdclive_1%40112780*~data=hdntl~hmac=0ae177b1efc06bf76e2fb46889b102b9d8896f0c9829d1e90d4b2afad4cd96bf
