### ISSUE TITLE
I can't play files from google drive on Exoplayer

### ISSUE THREAD

**Issue by trmvenus** [google/ExoPlayer#7662]
Hello.
I tried to play the video file from google drive on Exoplayer
I just changed the url on demo Exoplayer project.

But I got the error like below:

Please help me and fix it.

    E/EventLogger: internalError [eventTime=1.77, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1096)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:975)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
    ]

    E/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1096)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:975)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

    D/EventLogger: mediaPeriodReleased [eventTime=1.77, mediaPos=0.00, window=0, period=0]
    E/EventLogger: playerFailed [eventTime=1.77, mediaPos=0.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:394)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1096)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:975)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
    ]

**Comment by ojw28** [comment]
Most likely you're providing the player with a link to a web page, rather than a direct link to an actual media file, which is what ExoPlayer needs. Does the same link play correctly in another player such as VLC?

If the same link does play correctly in another player, you'll need to provide us with a link that reproduces the problem for us to investigate further.

**Comment by trmvenus** [comment]
Thanks, ojw28.

I can play this video using VLC.

This video is a TS file with Australian TV Subtitles.

https://drive.google.com/open?id=1eTFX0KpQUog9bI5LQOe23K6B_FkgpErr

**Comment by ojw28** [comment]
Trying to open that link directly in VLC does not work for me. As explained above, it's not a direct link to an actual media file. It's a link to a web page from which you can download a media file. I managed to get a direct link, which is (this might expire, I'm not sure how Google Drive links work):

https://drive.google.com/u/1/uc?id=1eTFX0KpQUog9bI5LQOe23K6B_FkgpErr&export=download

This link does play in VLC. It doesn't play on a Pixel device using ExoPlayer because it's using `audio/mpeg-L2` and `video/mpeg2` sample formats, neither of which Android is guaranteed to support. You can read about supported formats [here](https://exoplayer.dev/supported-formats.html). It's possible (although not guaranteed) that a subset of Android devices might support playback if they ship with the corresponding optional decoders.

The logging you'll see in the ExoPlayer demo app to indicate that the formats are not supported looks like:

```
MediaCodecVideoRenderer [
  Group:0, adaptive_supported=N/A [
    [ ] Track:0, id=544/2314, mimeType=video/mpeg2, res=720x576, supported=NO_UNSUPPORTED_TYPE
  ]
]
MediaCodecAudioRenderer [
  Group:0, adaptive_supported=N/A [
    [ ] Track:0, id=544/2315, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, language=en, supported=NO_UNSUPPORTED_TYPE
  ]
]
```

where `NO_UNSUPPORTED_TYPE` indicates that the format is not supported by the device
