### ISSUE TITLE
Invalid pssh atom in cenc:pssh element

### ISSUE THREAD

**Issue by miquelbeltran** [google/ExoPlayer#767]
Hello, I'm having trouble playing my encrypted DASH streams.

The error I get is the following `com.google.android.exoplayer.ParserException: Invalid pssh atom in cenc:pssh element`

The content protection tag from my dash manifest is the following:

```
      <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
        <cenc:pssh>CAESEE4uoWHwHCJz4aUJpec1eqMaCGNhc3RsYWJzIhBOLqFh8Bwic+GlCaXnNXqj</cenc:pssh>
      </ContentProtection>
```

The full exception trace:
```
 com.google.android.exoplayer.ParserException: Invalid pssh atom in cenc:pssh element
            at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseContentProtection(MediaPresentationDescriptionParser.java:317)
            at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseAdaptationSet(MediaPresentationDescriptionParser.java:231)
            at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parsePeriod(MediaPresentationDescriptionParser.java:191)
            at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseMediaPresentationDescription(MediaPresentationDescriptionParser.java:129)
            at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:96)
            at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:54)
            at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

The content used is available here: http://castlabs-dl.s3.amazonaws.com/public/Client/Movies/Dash/blood1_enc/Manifest.mpd

I can provide the keys if required as well.

**Comment by ojw28** [comment]
That normally indicates that the content of the cenc:pssh element isn't valid.

**Comment by ojw28** [comment]
Confirmed that the contents of the element doesn't seem to be a valid pssh atom, as is required. You'll need to fix the manifest to get this content to work.

**Comment by miquelbeltran** [comment]
Thanks for your reply, I'll report back to the content creator.
