### ISSUE TITLE
MediaCodec$CodecException: Error 0x80000000 

### ISSUE THREAD

**Issue by Taranlayal10** [google/ExoPlayer#7671]
### [REQUIRED] Searched documentation and issues
I did found a blog of the similar [issue](https://gitmemory.com/issue/google/ExoPlayer/7440/655219045) but there is no resolution provided for it

### [REQUIRED] Question
I am playing DASH Widevine content in my application. It plays without any issue for like three times but when I try to play different contents again and again it gives me an error. I am releasing player every time before creating the player also.

Below is the error every time I try to play any content.

```
E: Renderer error: index=0, type=video, format=Format(1, null, null, video/avc, avc1.42E00C, 179992, null, [320, 180, 25.0], [-1, -1]), rendererSupport=NO_UNSUPPORTED_DRM
      d.e.b.a.a0: android.media.MediaCodec$CodecException: Error 0x80000000
        at d.e.b.a.t.a(Unknown Source:32)
        at d.e.b.a.l1.f.a(Unknown Source:99)
        at d.e.b.a.d0.d(Unknown Source:91)
        at d.e.b.a.d0.handleMessage(Unknown Source:147)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
        at d.e.b.a.l1.f.b(Unknown Source:51)
        at d.e.b.a.l1.f.a(Unknown Source:46)
        at d.e.b.a.d0.d(Unknown Source:91) 
        at d.e.b.a.d0.handleMessage(Unknown Source:147) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
E: Could not fetch mapper for  shared memory
E: mapMemory returns nullptr
E: Disable failed.
      android.media.MediaCodec$CodecException: Error 0x80000000
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2147)
        at d.e.b.a.l1.f.E(Unknown Source:55)
        at com.google.android.exoplayer2.video.m.E(Unknown Source:1)
        at d.e.b.a.l1.f.u(Unknown Source:1)
        at com.google.android.exoplayer2.video.m.u(Unknown Source:1)
        at d.e.b.a.l1.f.t(Unknown Source:16)
        at com.google.android.exoplayer2.video.m.t(Unknown Source:28)
        at d.e.b.a.t.disable(Unknown Source:25)
        at d.e.b.a.d0.a(Unknown Source:8)
        at d.e.b.a.d0.a(Unknown Source:30)
        at d.e.b.a.d0.a(Unknown Source:17)
        at d.e.b.a.d0.handleMessage(Unknown Source:237)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
E: Renderer Exception: Error 0x80000000
```

### A full bug report captured from the device
Sent the bug report to dev.exoplayer@gmail.com  

### Link to test content
This is not content specific as the same content plays one time and does not play other time.

**Comment by tonihei** [comment]
From what I can see in the bugreport, the DRM encryption of the media is not supported by the device (look for the `rendererSupport=NO_UNSUPPORTED_DRM` string the logcat). ExoPlayer still attempts to play the stream just in case it happens to work anyway. So my best guess is that the platform code generates this error due to the unsupported DRM protection. Another indication for this are log lines like: `DrmWidevineDash: Error: OEMCrypto_CopyBuffer failed and return = 10026`.
