### ISSUE TITLE
getting "playback failed" error at random time during playback

### ISSUE THREAD

**Issue by swifityG** [google/ExoPlayer#7713]
### [REQUIRED] Issue description
I get "playback failed" error at random time during playback

### [REQUIRED] Reproduction steps
I don't know exactly how to reproduce, usually its happening few min or secs after playback start 

### [REQUIRED] Link to test content
its can happen in every m3u8 in my experience .. 

### [REQUIRED] A full bug report captured from the device
```
08-05 04:53:16.761  2035  2035 E EventLogger:       at com.google.android.exoplayer2.ext.cronet.CronetDataSource.readInternal(CronetDataSource.java:806)
08-05 04:53:16.761  2035  2035 E EventLogger:       at com.google.android.exoplayer2.ext.cronet.CronetDataSource.read(CronetDataSource.java:529)
08-05 04:53:16.761  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:183)
08-05 04:53:16.761  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(CacheDataSource.java:599)
08-05 04:53:16.761  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:92)
08-05 04:53:16.761  2035  2035 E EventLogger:       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:282)
08-05 04:53:16.761  2035  2035 E EventLogger:       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61)
08-05 04:53:16.761  2035  2035 E EventLogger:       at com.google.android.exoplayer2.extractor.ts.TsExtractor.fillBufferWithAtLeastOnePacket(TsExtractor.java:389)
08-05 04:53:16.761  2035  2035 E EventLogger:       at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:280)
08-05 04:53:16.761  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:67)
08-05 04:53:16.761  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:398)
08-05 04:53:16.761  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:368)
08-05 04:53:16.761  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:335)
08-05 04:53:16.761  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:413)
08-05 04:54:53.767  2035  2035 E EventLogger:   com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: java.net.SocketTimeoutException
08-05 04:54:53.767  2035  2035 E EventLogger:       at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:441)
08-05 04:54:53.767  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:178)
08-05 04:54:53.767  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:763)
08-05 04:54:53.767  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:578)
08-05 04:54:53.767  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
08-05 04:54:53.767  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:411)
08-05 04:54:53.767  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:393)
08-05 04:54:53.767  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:368)
08-05 04:54:53.767  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:335)
08-05 04:54:53.767  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:413)
08-05 04:55:06.824  3266  3266 D SurfaceFlinger:        HWC | 77f4628b00 | 0000 | 0020 | 04 | 0100 | ? 00000121  |    0.0,    0.0,  768.0,  432.0 |    0,    0, 1080, 1920 | SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@3fcf600@0#0
08-05 04:55:06.824  3266  3266 D SurfaceFlinger:        HWC | 77f05d1740 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0, 1080.0, 1920.0 |    0,    0, 1080, 1920 | com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity#0
08-05 04:55:21.576  2035  2035 E EventLogger:   com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: er: Exception in CronetUrlRequest: net::ERR_CONNECTION_ABORTED, ErrorCode=11, InternalErrorCode=-103, Retryable=false
08-05 04:55:21.576  2035  2035 E EventLogger:       at com.google.android.exoplayer2.ext.cronet.CronetDataSource.readInternal(CronetDataSource.java:806)
08-05 04:55:21.576  2035  2035 E EventLogger:       at com.google.android.exoplayer2.ext.cronet.CronetDataSource.read(CronetDataSource.java:529)
08-05 04:55:21.576  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:183)
08-05 04:55:21.576  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(CacheDataSource.java:599)
08-05 04:55:21.576  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:92)
08-05 04:55:21.576  2035  2035 E EventLogger:       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:282)
08-05 04:55:21.576  2035  2035 E EventLogger:       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61)
08-05 04:55:21.576  2035  2035 E EventLogger:       at com.google.android.exoplayer2.extractor.ts.TsExtractor.fillBufferWithAtLeastOnePacket(TsExtractor.java:389)
08-05 04:55:21.576  2035  2035 E EventLogger:       at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:280)
08-05 04:55:21.576  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:67)
08-05 04:55:21.576  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:398)
08-05 04:55:21.576  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:368)
08-05 04:55:21.576  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:335)
08-05 04:55:21.576  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:413)
08-05 04:55:21.731  2035  2035 E EventLogger:   com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: er: Exception in CronetUrlRequest: net::ERR_ADDRESS_UNREACHABLE, ErrorCode=9, InternalErrorCode=-109, Retryable=false
08-05 04:55:21.731  2035  2035 E EventLogger:       at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:438)
08-05 04:55:21.731  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:178)
08-05 04:55:21.731  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:763)
08-05 04:55:21.731  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:578)
08-05 04:55:21.731  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
08-05 04:55:21.731  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:411)
08-05 04:55:21.731  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:393)
08-05 04:55:21.731  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:368)
08-05 04:55:21.731  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:335)
08-05 04:55:21.731  2035  2035 E EventLogger:       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:413)
08-05 04:55:25.417  3266  3266 D SurfaceFlinger:        HWC | 77f4628ec0 | 0000 | 0020 | 04 | 0100 | ? 00000121  |    0.0,    0.0,  768.0,  432.0 |    0,    0, 1080, 1920 | SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@3fcf600@0#0
08-05 04:55:25.417  3266  3266 D SurfaceFlinger:        HWC | 77f46279c0 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0, 1080.0, 1920.0 |    0,    0, 1080, 1920 | com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity#0
08-05 04:55:57.863  2035  3457 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
08-05 04:55:57.863  2035  3457 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:556)
08-05 04:55:57.863  2035  3457 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.SampleDataQueue.readData(SampleDataQueue.java:309)
08-05 04:55:57.863  2035  3457 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.SampleDataQueue.readToBuffer(SampleDataQueue.java:147)
08-05 04:55:57.863  2035  3457 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:359)
08-05 04:55:57.863  2035  3457 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.readData(HlsSampleStreamWrapper.java:571)
08-05 04:55:57.863  2035  3457 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.hls.HlsSampleStream.readData(HlsSampleStream.java:79)
08-05 04:55:57.863  2035  3457 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:377)
08-05 04:55:57.863  2035  3457 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1247)
08-05 04:55:57.863  2035  3457 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:809)
08-05 04:55:57.863  2035  3457 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:869)
08-05 04:55:57.863  2035  3457 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:463)
08-05 04:55:57.963  2035  2035 E EventLogger:   com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
08-05 04:55:57.963  2035  2035 E EventLogger:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:556)
08-05 04:55:57.963  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.SampleDataQueue.readData(SampleDataQueue.java:309)
08-05 04:55:57.963  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.SampleDataQueue.readToBuffer(SampleDataQueue.java:147)
08-05 04:55:57.963  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:359)
08-05 04:55:57.963  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.readData(HlsSampleStreamWrapper.java:571)
08-05 04:55:57.963  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsSampleStream.readData(HlsSampleStream.java:79)
08-05 04:55:57.963  2035  2035 E EventLogger:       at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:377)
08-05 04:55:57.963  2035  2035 E EventLogger:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1247)
08-05 04:55:57.963  2035  2035 E EventLogger:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:809)
08-05 04:55:57.963  2035  2035 E EventLogger:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:869)
08-05 04:55:57.963  2035  2035 E EventLogger:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:463)
08-05 04:55:57.986  3736  6057 I MediaFocusControl:  AudioFocus  abandonAudioFocus() from uid/pid 10746/2035 clientId=android.media.AudioManager$61cca10com.google.android.exoplayer2.AudioFocusManager$AudioFocusListener$7d7cb7a
08-05 04:55:57.992  2035  2035 D SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@3fcf600@0) android.view.SurfaceView{3fcf600 V.E...... ........ 0,0-1920,1080}
08-05 04:55:57.993  3266  3340 I SurfaceFlinger: id=4225 Removed SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@3fcf600@0#0 (1/6)
08-05 04:55:57.994  3266  3340 I SurfaceFlinger: id=4225 Removed SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@3fcf600@0#0 (-2/6)
08-05 04:55:57.994  2035  2035 D SurfaceView: BG destroy() Surface(name=Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@3fcf600@0) android.view.SurfaceView{3fcf600 V.E...... ........ 0,0-1920,1080}
08-05 04:55:57.994  3266  4284 I SurfaceFlinger: id=4226 Removed Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@3fcf600@0#0 (0/6)
08-05 04:55:57.994  3266  4284 I SurfaceFlinger: id=4226 Removed Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@3fcf600@0#0 (-2/6)
08-05 04:55:57.996  3266  3266 I Layer   : id=4226 onRemoved Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@3fcf600@0#0
08-05 04:55:57.997  3266  3266 I Layer   : id=4225 onRemoved SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@3fcf600@0#0
08-05 04:55:57.999  3266  3266 D SurfaceFlinger:        HWC | 77f04bcf40 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0, 1080.0, 1920.0 |    0,    0, 1080, 1920 | com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity#0
08-05 04:55:58.097  3736  5710 I MediaFocusControl:  AudioFocus  requestAudioFocus() from uid/pid 10746/2035 clientId=android.media.AudioManager$61cca10com.google.android.exoplayer2.AudioFocusManager$AudioFocusListener$30ba4e8 req=1 flags=0x0
08-05 04:55:58.106  3736  6057 V WindowManager: Relayout Window{a91a9c1 u0 com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity}: viewVisibility=0 req=1920x1080 WM.LayoutParams{(0,0)(fillxfill) sim=#20 ty=1 fl=#80810580 pfl=0x20000 fmt=-3 wanim=0x10302fd vsysui=0x1706 needsMenuKey=2 colorMode=0 naviIconColor=0}
08-05 04:55:58.112  3266  3266 I SurfaceFlinger: id=4231 createSurf (1920x1080),4 flag=404, SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@261fd8a@0#0
08-05 04:55:58.113  3266  3266 I SurfaceFlinger: id=4232 createSurf (1920x1080),-1 flag=20404, Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@261fd8a@0#0
08-05 04:55:58.113  2035  2035 D SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@261fd8a@0) android.view.SurfaceView{261fd8a V.E...... ......ID 0,0-1920,1080}
08-05 04:55:58.138  3266  3266 D SurfaceFlinger:       GLES | 00000000 | 0000 | 0220 | 04 | 0105 | ? ffffffff  |    0.0,    0.0,   -1.0,   -1.0 |    0,    0, 1080, 1920 | Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@261fd8a@0#0
08-05 04:55:58.138  3266  3266 D SurfaceFlinger:        HWC | 77f04bcf40 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0, 1080.0, 1920.0 |    0,    0, 1080, 1920 | com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity#0
08-05 04:55:58.140  3736  5710 V WindowManager: Relayout Window{a91a9c1 u0 com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity}: viewVisibility=0 req=1920x1080 WM.LayoutParams{(0,0)(fillxfill) sim=#20 ty=1 fl=#80810580 pfl=0x20000 fmt=-3 wanim=0x10302fd vsysui=0x1706 needsMenuKey=2 colorMode=0 naviIconColor=0}
08-05 04:56:02.339  3266  3266 D SurfaceFlinger:        HWC | 77f4627240 | 0000 | 0020 | 04 | 0100 | ? 00000121  |    0.0,    0.0, 1024.0,  576.0 |    0,    0, 1080, 1920 | SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@261fd8a@0#0
08-05 04:56:02.339  3266  3266 D SurfaceFlinger:        HWC | 77f05d1740 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0, 1080.0, 1920.0 |    0,    0, 1080, 1920 | com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity#0
08-05 04:57:09.435  2035  5590 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
08-05 04:57:09.435  2035  5590 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:556)
08-05 04:57:09.435  2035  5590 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.SampleDataQueue.readData(SampleDataQueue.java:309)
08-05 04:57:09.435  2035  5590 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.SampleDataQueue.readToBuffer(SampleDataQueue.java:147)
08-05 04:57:09.435  2035  5590 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:359)
08-05 04:57:09.435  2035  5590 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.readData(HlsSampleStreamWrapper.java:571)
08-05 04:57:09.435  2035  5590 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.hls.HlsSampleStream.readData(HlsSampleStream.java:79)
08-05 04:57:09.435  2035  5590 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:377)
08-05 04:57:09.435  2035  5590 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1247)
08-05 04:57:09.435  2035  5590 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:809)
08-05 04:57:09.435  2035  5590 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:869)
08-05 04:57:09.435  2035  5590 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:463)
08-05 04:57:09.548  2035  2035 E EventLogger:   com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
08-05 04:57:09.548  2035  2035 E EventLogger:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:556)
08-05 04:57:09.548  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.SampleDataQueue.readData(SampleDataQueue.java:309)
08-05 04:57:09.548  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.SampleDataQueue.readToBuffer(SampleDataQueue.java:147)
08-05 04:57:09.548  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:359)
08-05 04:57:09.548  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.readData(HlsSampleStreamWrapper.java:571)
08-05 04:57:09.548  2035  2035 E EventLogger:       at com.google.android.exoplayer2.source.hls.HlsSampleStream.readData(HlsSampleStream.java:79)
08-05 04:57:09.548  2035  2035 E EventLogger:       at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:377)
08-05 04:57:09.548  2035  2035 E EventLogger:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1247)
08-05 04:57:09.548  2035  2035 E EventLogger:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:809)
08-05 04:57:09.548  2035  2035 E EventLogger:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:869)
08-05 04:57:09.548  2035  2035 E EventLogger:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:463)
08-05 04:57:09.572  3736  4955 I MediaFocusControl:  AudioFocus  abandonAudioFocus() from uid/pid 10746/2035 clientId=android.media.AudioManager$61cca10com.google.android.exoplayer2.AudioFocusManager$AudioFocusListener$30ba4e8
08-05 04:57:09.578  2035  2035 D SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@261fd8a@0) android.view.SurfaceView{261fd8a V.E...... ........ 0,0-1920,1080}
08-05 04:57:09.579  3266  3340 I SurfaceFlinger: id=4231 Removed SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@261fd8a@0#0 (1/6)
08-05 04:57:09.579  3266  3340 I SurfaceFlinger: id=4231 Removed SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@261fd8a@0#0 (-2/6)
08-05 04:57:09.579  2035  2035 D SurfaceView: BG destroy() Surface(name=Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@261fd8a@0) android.view.SurfaceView{261fd8a V.E...... ........ 0,0-1920,1080}
08-05 04:57:09.579  3266  5463 I SurfaceFlinger: id=4232 Removed Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@261fd8a@0#0 (0/6)
08-05 04:57:09.579  3266  4284 I SurfaceFlinger: id=4232 Removed Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@261fd8a@0#0 (-2/6)
08-05 04:57:09.581  3266  3266 I Layer   : id=4232 onRemoved Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@261fd8a@0#0
08-05 04:57:09.581  3266  3266 I Layer   : id=4231 onRemoved SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@261fd8a@0#0
08-05 04:57:09.586  3266  3266 D SurfaceFlinger:        HWC | 77f05d1740 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0, 1080.0, 1920.0 |    0,    0, 1080, 1920 | com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity#0
08-05 04:57:09.684  3736  4955 I MediaFocusControl:  AudioFocus  requestAudioFocus() from uid/pid 10746/2035 clientId=android.media.AudioManager$61cca10com.google.android.exoplayer2.AudioFocusManager$AudioFocusListener$f8a89d4 req=1 flags=0x0
08-05 04:57:09.694  3736  4955 V WindowManager: Relayout Window{a91a9c1 u0 com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity}: viewVisibility=0 req=1920x1080 WM.LayoutParams{(0,0)(fillxfill) sim=#20 ty=1 fl=#80810580 pfl=0x20000 fmt=-3 wanim=0x10302fd vsysui=0x1706 needsMenuKey=2 colorMode=0 naviIconColor=0}
08-05 04:57:09.700  3266  3266 I SurfaceFlinger: id=4233 createSurf (1920x1080),4 flag=404, SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@3dba417@0#0
08-05 04:57:09.701  3266  3266 I SurfaceFlinger: id=4234 createSurf (1920x1080),-1 flag=20404, Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@3dba417@0#0
08-05 04:57:09.702  2035  2035 D SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@3dba417@0) android.view.SurfaceView{3dba417 V.E...... ......ID 0,0-1920,1080}
08-05 04:57:09.723  3266  3266 D SurfaceFlinger:       GLES | 00000000 | 0000 | 0220 | 04 | 0105 | ? ffffffff  |    0.0,    0.0,   -1.0,   -1.0 |    0,    0, 1080, 1920 | Background for - SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@3dba417@0#0
08-05 04:57:09.723  3266  3266 D SurfaceFlinger:        HWC | 77f05d1740 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0, 1080.0, 1920.0 |    0,    0, 1080, 1920 | com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity#0
08-05 04:57:15.212  3266  3266 D SurfaceFlinger:        HWC | 77f46270c0 | 0000 | 0020 | 04 | 0100 | ? 00000121  |    0.0,    0.0, 1024.0,  576.0 |    0,    0, 1080, 1920 | SurfaceView - com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity@3dba417@0#0
08-05 04:57:15.212  3266  3266 D SurfaceFlinger:        HWC | 77f05d1740 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0, 1080.0, 1920.0 |    0,    0, 1080, 1920 | com.RGDev.Live/com.google.android.exoplayer2.demo.PlayerActivity#0
```
### [REQUIRED] Version of ExoPlayer being used
last dev

### [REQUIRED] Device(s) and version(s) of Android being used
android 8 oreo

I think the cornet errors not relevant because its can happen sometimes without any cronet errors

**Comment by swifityG** [comment]
its doesnt happen with okhttp so mabye it its some problem with cronet

**Comment by ojw28** [comment]
Does this reproduce in the ExoPlayer demo app, or is this with your own project? If the latter, could you try in the ExoPlayer demo app and see if it reproduces there as well.

**Comment by ojw28** [comment]
The error you're seeing is [documented here](https://chromium.googlesource.com/chromium/src/+/master/net/base/net_error_list.h#141):

> A connection timed out as a result of not receiving an ACK for data sent. This can include a FIN packet that did not get ACK'd.

**Comment by swifityG** [comment]
I used exoplayer demo app and didnt change any core stuffs, the issue mainly occurs when switching between networks but can happen randomly too.. since I switched to okhttp i dont get it

**Comment by ojw28** [comment]
Did it occur with the HLS samples in the demo app, or only ones that you added yourself? I've tried repeatedly switching network during playback of the included HLS samples, and am unable to reproduce this problem.
