### ISSUE TITLE
The HLS only-audio steam can't play

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#7722]
### [REQUIRED] Issue description
The stream [http://newcntv.qcloudcdn.com/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8](http://newcntv.qcloudcdn.com/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8) can't be played. and throw the exception.

I have set the payload reader flag `FLAG_IGNORE_H264_STREAM`. 

```
2020-08-07 09:25:49.224 30061-30061/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=0.45, mediaPos=0.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:487)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:167)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:434)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException
        at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
        at com.google.android.exoplayer2.util.ParsableByteArray.setPosition(ParsableByteArray.java:158)
        at com.google.android.exoplayer2.util.ParsableByteArray.skipBytes(ParsableByteArray.java:173)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor$PmtReader.readEsInfo(TsExtractor.java:709)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor$PmtReader.consume(TsExtractor.java:594)
        at com.google.android.exoplayer2.extractor.ts.SectionReader.consume(SectionReader.java:127)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:342)
        at com.google.android.exoplayer2.source.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:67)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:409)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:379)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:346)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:413)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
    ]
```
I also test the stream with Android MediaPlayer, Safari and VLC. All the player could play well. So there may less robust for the ts format parser. Hope to spend time investigating though. 

And I also use the `Apple's mediastreamvalidator` to test, there is not indicates issues with the stream. 

```
➜  Downloads git:(master) ✗ mediastreamvalidator -O example/ http://newcntv.qcloudcdn.com/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8
mediastreamvalidator: Version 1.4 (417.2-190530)
[/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8] Started root playlist download
[/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8] Started media playlist download
[/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8] parsed media segment count: 29, duration: 300.480
[/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8] parsed media segment count: 60, duration: 610.840
[/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8] parsed media segment count: 91, duration: 920.280
[/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8] parsed media segment count: 121, duration: 1221.960
[/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8] parsed media segment count: 152, duration: 1531.680
[/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8] parsed media segment count: 183, duration: 1841.240
[/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8] parsed media segment count: 214, duration: 2150.160
[/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8] parsed media segment count: 244, duration: 2451.840
[/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8] parsed media segment count: 274, duration: 2751.920
[/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8] All media files delivered and have end tag, stopping

--------------------------------------------------------------------------------
http://newcntv.qcloudcdn.com/asp/hlsaudio/hls/450/0303000a/3/default/77cf0d02a1bf4e998ab88a3a3dd903f6/450.m3u8
--------------------------------------------------------------------------------
Processed 291 out of 291 segments
Average segment duration: 9.981306
Total segment bitrates (all discontinuities): average: 73.65 kb/s, max: 74.74 kb/s


Discontinuity: sequence: 0, parsed segment count: 291 of 291, duration: 2904.560 sec, average: 73.65 kb/s, max: 74.74 kb/s
Track ID: 1
Audio Codec: AAC-LC
Audio sample rate: 48000 Hz
Audio channels: 2
Audio channel layout: Stereo (L R)
```
I'm not familiar with TS format. I just modify the position of the exception throws. The stream could play well.  Like this:
`ParsableByteArray.java`
```
public void setPosition(int position) {
    // It is fine for position to be at the end of the array.
    // Log.e("TsExtractor","position = [" + position + "], limit = [" + limit + "]");
    // Assertions.checkArgument(position >= 0 && position <= limit);
    if (position >= limit){
      position = limit;
    }
    this.position = position;
  }
```
Hope you give some information which the stream has error, and give the correct workaroud. Thanks!

**Comment by Romantic-LiXuefeng** [comment]
I used the StreamAnalyzer to analyze the first segment(0.ts) in the HlS playlist. The `PMT` parser error ,because of  the  param `ES_info_length  =  11` set incorrectly. 
![image](https://user-images.githubusercontent.com/9837705/89601724-ca111580-d897-11ea-9a12-407b41ab8406.png)

**Comment by Romantic-LiXuefeng** [comment]
@ojw28 Do you think whether need to add a workaroud to support this particular stream?

**Comment by ojw28** [comment]
As you've observed, the media is broken. We may consider adding robustness for this case, but ultimately the media provider should fix their content.

**Comment by Romantic-LiXuefeng** [comment]
@ojw28  Thanks! It works.
