### ISSUE TITLE
DownloadHelper MediaSource throws IllegalArgumentException while playing

### ISSUE THREAD

**Issue by BharathMG-ShareChat** [google/ExoPlayer#7731]
### Issue description
When using DownloadHelper to prepare MediaSource, sometimes we are getting IllegalArgumentException. Have attached trace below.

### Reproduction steps
Unfortunately, it is not always reproducible.

### A full bug report captured from the device
Caused by java.lang.IllegalArgumentException
       at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
       at com.google.android.exoplayer2.upstream.DataSpec.<init>(DataSpec.java:309)
       at com.google.android.exoplayer2.upstream.DataSpec.subrange(DataSpec.java:398)
       at com.google.android.exoplayer2.upstream.DataSpec.subrange(DataSpec.java:384)
       at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:126)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

### [REQUIRED] Version of ExoPlayer being used
2.11.7

**Comment by andrewlewis** [comment]
It seems that we are trying to load an invalid offset in the stream (probably out of bounds). Without more information I don't think we'll be able to provide any further help. Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

In particular, steps to reproduce the issue, including a link to the stream you are trying to play would be useful.
