### ISSUE TITLE
[OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -1010

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#7741]
I encountered an error while using [react-native-video](https://github.com/react-native-community/react-native-video), some videos can be played normally, some videos have errors

Is there any solution?

error message:

```
08-12 15:56:28.047 16969-20943/***.*** E/ACodec: [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -1010
08-12 15:56:28.059 16969-20943/***.*** E/ACodec: [OMX.qcom.video.decoder.avc] ERROR(0x80001019)
08-12 15:56:28.059 16969-20943/***.*** E/ACodec: signalError(omxError 0x80001019, internalError -2147483648)
08-12 15:56:28.059 16969-20942/***.*** E/MediaCodec: Codec reported err 0x80001019, actionCode 0, while in state 6
08-12 15:56:28.086 16969-20937/***.*** E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1287)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
08-12 15:56:28.094 16969-20937/***.*** E/ExoPlayerImplInternal: Stop failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:628)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:608)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:508)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:562)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:377)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:153)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:983)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:771)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:742)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:358)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by andrewlewis** [comment]
This is a generic exception from the media framework. To be able to help we need more information, like a bug report captured via `adb bugreport` just after seeing the error. Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
