### ISSUE TITLE
IMA Ad getting skipped on Pause the Ad 

### ISSUE THREAD

**Issue by ursurya** [google/ExoPlayer#7774]
While Playing Midroll ads Using Exoplayer  IMA Extension in  Amazon FireTV App Using VMAP, Issue we face is,  when i tried to pause the Ad by calling "player.setPlayWhenReady(false)" the Ad got skipped . I am Using Midroll Optimized pod with 5 Ads. While first ad playing pause and play worked but when i press pause while second ad is playing it got skipped (i got AdEnded callback) and third ad start playing. When i pause the Fourth Ad , complete Ad got skipped and content started playing. I tried calling pause Method of adManager and ImaAdloader but didn't worked . Faced same issue with below IMA Sample tag as well  [https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostoptimizedpod&cmsid=496&vid=short_onecue&correlator=](url)

Exoplayer Version : 2.11.3
Device : Amazon AFTT (5.1.1)

**Comment by andrewlewis** [comment]
Please could you check if this is reproducible on the most recent release 2.11.7? Quite a few IMA extension bugs were fixed after the release you're using.

**Comment by ursurya** [comment]
Thanks @andrewlewis  for your quick response. As mentioned above i am trying it on amazon fire tv and Latest  amazon custom Exoplayer Version is 2.11.3 (com.amazon.android:exoplayer:2.11.3). I will check with Exoplayer Version 2.11.7 and will update

**Comment by ursurya** [comment]
Hi @andrewlewis , I tested with Exoplayer Version 2.11.7 in Android Mobile app and got different issue. Now,When "paused" on the first ad itself all the ads got skipped and showed content. I observed the below exception logged during  Ad Pause. Tested with the same Ad tag mentioned above

```
E/ImaAdsLoader: Internal error in pauseAd
      java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader$ComponentListener.pauseAd(ImaAdsLoader.java:1645)
        at com.google.ads.interactivemedia.v3.internal.akf.a(IMASDK:18)
        at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:177)
        at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:48)
        at com.google.ads.interactivemedia.v3.internal.ake.b(IMASDK:28)
        at com.google.ads.interactivemedia.v3.internal.akc.shouldOverrideUrlLoading(IMASDK:6)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-414712570:16)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
E/EventLogger: internalError [eventTime=32.26, mediaPos=3.02, window=0, loadError
      com.google.android.exoplayer2.source.ads.AdsMediaSource$AdLoadException: java.lang.RuntimeException: Internal error in pauseAd
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.maybeNotifyInternalError(ImaAdsLoader.java:1253)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.access$1000(ImaAdsLoader.java:89)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader$ComponentListener.pauseAd(ImaAdsLoader.java:1651)
        at com.google.ads.interactivemedia.v3.internal.akf.a(IMASDK:18)
        at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:177)
        at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:48)
        at com.google.ads.interactivemedia.v3.internal.ake.b(IMASDK:28)
        at com.google.ads.interactivemedia.v3.internal.akc.shouldOverrideUrlLoading(IMASDK:6)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-414712570:16)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: java.lang.RuntimeException: Internal error in pauseAd
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.maybeNotifyInternalError(ImaAdsLoader.java:1252)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.access$1000(ImaAdsLoader.java:89) 
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader$ComponentListener.pauseAd(ImaAdsLoader.java:1651) 
        at com.google.ads.interactivemedia.v3.internal.akf.a(IMASDK:18) 
        at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:177) 
        at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:48) 
        at com.google.ads.interactivemedia.v3.internal.ake.b(IMASDK:28) 
        at com.google.ads.interactivemedia.v3.internal.akc.shouldOverrideUrlLoading(IMASDK:6) 
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73) 
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-414712570:16) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:323) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
     Caused by: java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader$ComponentListener.pauseAd(ImaAdsLoader.java:1645)
        at com.google.ads.interactivemedia.v3.internal.akf.a(IMASDK:18) 
        at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:177) 
        at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:48) 
        at com.google.ads.interactivemedia.v3.internal.ake.b(IMASDK:28) 
        at com.google.ads.interactivemedia.v3.internal.akc.shouldOverrideUrlLoading(IMASDK:6) 
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73) 
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-414712570:16) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:323) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
    ]
E/ImaAdsLoader: Internal error in pauseAd
      java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader$ComponentListener.pauseAd(ImaAdsLoader.java:1645)
        at com.google.ads.interactivemedia.v3.internal.akf.a(IMASDK:18)
        at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:177)
        at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:48)
        at com.google.ads.interactivemedia.v3.internal.ake.b(IMASDK:28)
        at com.google.ads.interactivemedia.v3.internal.akc.shouldOverrideUrlLoading(IMASDK:6)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-414712570:16)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by ursurya** [comment]
Hi @andrewlewis  , Did you get a chance to look into the Exception Log shared above

**Comment by andrewlewis** [comment]
Based on the exception, the ad the IMA extension thinks is currently playing is different to the one the IMA SDK passes to `pauseAd`, which is unexpected.

I tried to reproduce this using the sample ad tag linked above on 2.11.7 but wasn't able to (I tried pausing and resuming several times during the preroll and also during the first and second ads in the midroll pod, but playback worked as expected). Without being able to reproduce this it's going to be quite difficult to fix. I thought about just removing this assertion but I'm concerned we will get the wrong ad media info passed to `playAd` on resuming which will just move the problem later. Are you able to reproduce this in the ExoPlayer demo app? Does it reproduce with other ad tags? Can you think of anything else I might be doing differently?

**Comment by ursurya** [comment]
Thanks @andrewlewis . I debugged further based on your comment and exception and observed we are getting different AdMediaInfo object to pauseAd Method  When paused Ad.  When i Paused  the First position Ad of Midroll , received second Ad position related object to pauseAd Method and "imaAdMediaInfo" instance is holding current playing First Ad info. Why  are we getting AdMediaInfo object of Next Ad instead of Current playing one ? 
I tried checking with Exoplayer demo app but pause/play controls are not visible while playing ad. How did you Checked  ?

**Comment by ursurya** [comment]
Hi @andrewlewis  Can you please help us on why are we getting different AdMediaInfo Object when pause ad. Pause and Play worked fine with Preroll ads .

**Comment by andrewlewis** [comment]
> I tried checking with Exoplayer demo app but pause/play controls are not visible while playing ad. How did you Checked ?

In `PlayerView` I hardcoded `controllerHideDuringAds = false` and set `DEFAULT_SHOW_TIMEOUT_MS = 0` so that the controller doesn't auto-hide once shown. Then I tried playing the ad tag 'VMAP pre-roll single ad, mid-roll optimized pod with 3 ads, post-roll single ad' and paused/resumed during ads but didn't see an exception.

It does sound plausible that there could be a bug where preloading causes the wrong ad media info to be passed, but I am not able to reproduce it. The only thing I can think of is that we may be getting different versions of the IMA SDK JavaScript component. Assuming you can reproduce this in the demo app having done the steps above, please could you also hardcode `ImaAdsLoader.DEBUG` to true, reproduce the issue in the demo app then attach the logcat output? I expect that will include enough information to tell whether we are getting the same version of the IMA SDK JavaScript component. Thanks.

**Comment by ursurya** [comment]
I will update in a day. Please don't close this issue
