### ISSUE TITLE
[Android-9 TV]Failed to initialize OMX.broadcom.video_decoder.secure 

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#7778]
Before filing a bug:
-----------------------
There are a lot of issue like this but we are facing this issue on a specific h/w.

### [REQUIRED] Question description
Decoder is not being acquired when the application comes to foreground even though we release the player in onPause()

### [REQUIRED] Reproduction steps

1. This issue on TV.
2. There is no recent apps button in TV so once if I press HOME button on TV, in order to go back to app, i need to press application's logo. There we can see the following exception,
```
android.media.MediaCodec$CodecException: Failed to initialize OMX.broadcom.video_decoder.secure, error 0xfffffff4
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1811)
        at android.media.MediaCodec.createByCodecName(MediaCodec.java:1792)
        at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:925)
        at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:860)
        at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:561)
        at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1254)
        at com.kaltura.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:756)
        at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:814)
        at com.kaltura.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:712)
        at com.kaltura.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.kaltura.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
We are unable to test this issue on ExoPlayer demo app because if i go back and press the app icon once again. It does not start from the player on TV.

### [REQUIRED] Link to test content
NA

### [REQUIRED] A full bug report captured from the device
I am sharing the application's log on dev.exoplayer@gmail.com <dev.exoplayer@gmail.com>
You can focus on RED highlighted text. You can see lifecycle, of onPause and onResume.

### [REQUIRED] Version of ExoPlayer being used
2.11.7

### [REQUIRED] Device(s) and version(s) of Android being used
This issue is happening only on a specific h/w. This is Android 9 TV. The same codebase works fine on different h/w with same testing steps.

**Comment by GouravSna** [comment]
I have shared the adb logs over email. You can also see the no of decoders available in device. It is marked in RED text.

We have tried `renderersFactory.setEnableDecoderFallback` which allows the device to choose s/w decoders in case h/w decoder limit is reached then also, this h/w is not able to acquire the s/w decoder. 
Why we thought to use this because if you see the list in adb logs, `OMX.broadcom.video_decoder.secure` this decoder has 1 instance only.

**Comment by marcbaechinger** [comment]
The logs show that ExoPlayer is initialized twice. The first time the codec can be initialized, the second time it fails. The logs confirm that, the player is released in between. 

`setEnableDecoderFallback` probably does not help if no software decoder is available for the secured content you want to play. So if that does not help it would not be a big surprise.

You said you are on TV and you are releasing in `onPause`. Can you please double check that you [release according to the API level like the demo app does](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L266)? I suspect you are above API 23 and then you should release in `onStop` and initialize in 'onStart' to make sure the life cycle methods do not overlap with other apps. I would make sure that is the case before doing further investigation. 

The codec could be acquired by another app so having the life cycle method properly could make a difference.

**Comment by GouravSna** [comment]
Hi @marcbaechinger , I guess from `ExoPlayerImpl: Init 8280c78 [ExoPlayerLib/2.11.7]` this you are telling that player is initialized twice. Correct me if I am wrong.

This you are seeing because in onPause, we are releasing the player in onPause [onApplicationPaused](https://github.com/kaltura/playkit-android/blob/b369acb2776d7b081768def942d0765e21018524/playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerWrapper.java#L940) and we prepare the player in onResume [onApplicationResumed](https://github.com/kaltura/playkit-android/blob/b369acb2776d7b081768def942d0765e21018524/playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerWrapper.java#L763) Both the flows are attached to the Application's `onPause()` and `onResume()` activity lifecycle.

**Comment by marcbaechinger** [comment]
Can you try the same with `onStart` and `onStop` like the demo app does?

**Comment by GouravSna** [comment]
Hi @marcbaechinger , Shared the logs over email where we called the methods in `onStart` and `onStop`

**Comment by marcbaechinger** [comment]
Yes, same thing.  Hard to say something besides that it seems that the decoder is not available. 
I can only guess. If you force stop your app and then start the app again, does this make a difference over backgrounding/foregrounding?

**Comment by GouravSna** [comment]
@marcbaechinger , will the system's bug report be helpful for you to see if the decoder was being released by the underlying framework or not in case when we go to background. 
OR we need to ask the vendor to check it.

**Comment by marcbaechinger** [comment]
Closing due to inactivity.
