### ISSUE TITLE
OutOfMemory with local audio MP4 file

### ISSUE THREAD

**Issue by abouda** [google/ExoPlayer#7779]
### [REQUIRED] Issue description
OutOfMemory when trying to open a local audio-only file.
Streaming the same file over HLS works fine.
Using `setPrioritizeTimeOverSizeThresholds(false)` in the `DefaultLoadControl.Builder()` does not help. Doesn't seem to be buffering related.

```
 com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 99301752 byte allocation with 16777216 free bytes and 70MB until OOM
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:394)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 99301752 byte allocation with 16777216 free bytes and 70MB until OOM
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:450)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 99301752 byte allocation with 16777216 free bytes and 70MB until OOM
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:239)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.getTrackSampleTables(Mp4Extractor.java:471)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:406)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:368)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:359)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:187)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:988)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
```

### [REQUIRED] Reproduction steps
Issue also happens in ExoPlayer Demo app using `adb shell am start -a com.google.android.exoplayer.demo.action.VIEW` to open the file.

### [REQUIRED] Link to test content
Audio file sent to dev.exoplayer@gmail.com

### [REQUIRED] A full bug report captured from the device
Bugreport sent to dev.exoplayer@gmail.com

### [REQUIRED] Version of ExoPlayer being used
2.11.7

### [REQUIRED] Device(s) and version(s) of Android being used
Issue happens on:
Sony Xperia tablet Android 6.0.1
Lenovo yoga 2 Android 5.0.1
Lenovo yoga 3 Android 6.0.1
Galaxy S5 mini Android 6.0.1

Issue does not happen on newer phones. Pixel 3 Android 10, Galaxy s10 Android 10

**Comment by marcbaechinger** [comment]
I can't file the email you sent I'm afraid. Can you please check whether this went to dev.exoplayer@gmail.com?

**Comment by ojw28** [comment]
The file you've provided is an 80 hour long, 2GB MP4 file that contains 12,412,717 audio samples. The sample table needs 24 bytes per sample, so to represent it in memory requires ~297MB. ExoPlayer is failing to allocate sufficient memory, and is therefore failing as a result. Even on devices where this "works", the memory allocation will be excessive.

I don't think an 80 hour long MP4 file is really an appropriate way to distribute this content. You should look at splitting it into smaller pieces, or using FMP4 so that the sample table is fragmented throughout the file rather than being placed entirely at the start.

Technically the file is valid, but I'll close this as `bad media` because whilst it may be valid, it's not really a sensible way to distribute such a long piece of content.
