### ISSUE TITLE
Caused by android.content.res.Resources$NotFoundException Resource ID #0x7f08015c

### ISSUE THREAD

**Issue by chhatrasal09** [google/ExoPlayer#7793]
I am getting a fatal crash on Crashlytics. The crashes are around 300-400 on every build.

I am using these dependencies in my project :
```
implementation "com.google.android.exoplayer:exoplayer-core:2.11.1"
implementation "com.google.android.exoplayer:exoplayer-dash:2.11.1"
implementation "com.google.android.exoplayer:exoplayer-hls:2.11.1"
implementation "com.google.android.exoplayer:exoplayer-ui:2.11.1"
```

The crash logged on Crashlytics says **"Caused by android.content.res.Resources$NotFoundException Resource ID #0x7f08015c"**. When I tried to find out to the resource id I found out that the mentioned id is of @drawable/exo_controls_repeat_all and this file is in drawable-v-21 directory.

Here are the steps I followed the resource id of the mentioned drawable : 
1. APK Analyzer -> classesXXX.dex
2. In this dex file I opened the directory of my apps package name and went to R$drawable file
3. R$drawable -> Show as byte code.

```.field public static final exo_controls_repeat_all:I = 0x7f08015c```
Here is the crash log from Crashlytics :
```
Caused by android.content.res.Resources$NotFoundException: Resource ID #0x7f08015c
       at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:288)
       at android.content.res.Resources.getDrawableForDensity(Resources.java:1026)
       at android.content.res.Resources.getDrawable(Resources.java:969)
       at android.content.res.Resources.getDrawable(Resources.java:944)
       at com.google.android.exoplayer2.ui.PlayerControlView.<init>(SourceFile:83)
       at com.google.android.exoplayer2.ui.PlayerView.<init>(SourceFile:77)
       at com.github.vkay94.dtpv.DoubleTapPlayerView.<init>(SourceFile:3)
       at com.github.vkay94.dtpv.DoubleTapPlayerView.<init>(SourceFile:2)
       at app package name.streamPlayer.StreamTapPlayerView.<init>(SourceFile:9)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at android.view.LayoutInflater.createView(LayoutInflater.java:658)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at androidx.databinding.DataBindingUtil.inflate(SourceFile:3)
       at androidx.databinding.DataBindingUtil.inflate(SourceFile:1)
       at app package name.Fragment.onCreateView(SourceFile:1)
       at androidx.fragment.app.Fragment.performCreateView(SourceFile:4)
       at androidx.fragment.app.FragmentStateManager.e(SourceFile:13)
       at androidx.fragment.app.FragmentManager.X(SourceFile:25)
       at androidx.fragment.app.FragmentManager.W(SourceFile:1)
       at androidx.fragment.app.FragmentManager.U(SourceFile:4)
       at androidx.fragment.app.BackStackRecord.f(SourceFile:26)
       at androidx.fragment.app.FragmentManager.executeOps(SourceFile:6)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:14)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:10)
       at androidx.fragment.app.FragmentManager.E(SourceFile:5)
       at androidx.fragment.app.BackStackRecord.commitNow(SourceFile:2)
       at androidx.viewpager2.adapter.FragmentStateAdapter.c(SourceFile:18)
       at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(SourceFile:2)
       at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(SourceFile:1)
       at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(SourceFile:4)
       at androidx.recyclerview.widget.RecyclerView$5.addView(SourceFile:2)
       at androidx.recyclerview.widget.ChildHelper.a(SourceFile:5)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(SourceFile:13)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(SourceFile:2)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(SourceFile:1)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:6)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:9)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:64)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:8)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:9)
       at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
       at android.view.View.layout(View.java:19781)
       at android.view.ViewGroup.layout(ViewGroup.java:6144)
       at androidx.viewpager2.widget.ViewPager2.onLayout(SourceFile:8)
       at android.view.View.layout(View.java:19781)
       at android.view.ViewGroup.layout(ViewGroup.java:6144)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19781)
       at android.view.ViewGroup.layout(ViewGroup.java:6144)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19781)
       at android.view.ViewGroup.layout(ViewGroup.java:6144)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1816)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1660)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1569)
       at android.view.View.layout(View.java:19781)
       at android.view.ViewGroup.layout(ViewGroup.java:6144)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19781)
       at android.view.ViewGroup.layout(ViewGroup.java:6144)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1816)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1660)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1569)
       at android.view.View.layout(View.java:19781)
       at android.view.ViewGroup.layout(ViewGroup.java:6144)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:888)
       at android.view.View.layout(View.java:19781)
       at android.view.ViewGroup.layout(ViewGroup.java:6144)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2674)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2377)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1515)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7266)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
       at android.view.Choreographer.doCallbacks(Choreographer.java:790)
       at android.view.Choreographer.doFrame(Choreographer.java:721)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by AquilesCanta** [comment]
> The crashes are around 300-400 on every build

By build do you mean Android build? Is this device specific or it happens across all devices?

**Comment by chhatrasal09** [comment]
> > The crashes are around 300-400 on every build
> 
> By build do you mean Android build? Is this device specific or it happens across all devices?

- Yes build means each app version eg-1.0.0.
- some of the androids versions - 
   22% - Android 9
   21% - Android 8
   18% - Android 10
   12% - Android 5
   20% - Android 6
- some of the devices
  - 28% - Xioami
      - 4% Redmi Note 4
      - 3% Redmi 7
      - 3% Redmi Note 5 Pro
      - 18% Other
  - 28% - Samsung
      - 6% Galaxy J2
      - 4% Galaxy J7
      - 2% Galaxy J8
      - 16% Other
  - 12% HUAWEi
  - 6% - VIVO
  - 4% - OnePlus
  - 4% - OPPO
  - 3% - Google
  - 15% - Other Devices

These are the data available from Crashlytics. Please let me know if you need more info.

**Comment by AquilesCanta** [comment]
The only similar issue (#7380) report we have had in the past was from a device probably running a customized version of android. In this case, we have a widespread issue, which is new for us. Unfortunately I don't know we can assist with this. I think that we would have more similar reports if this was an ExoPlayer issue.

> When I tried to find out to the resource id I found out that the...

Did you manage te reproduce the issue on the APK that you used for the analysis? Because if not, this line could be a red herring.

I'm inclined to think this may be an issue in the APK's build process but I don't have evidence to support that:
- Is there any evidence pointing at this being an ExoPlayer issue?
- Is there any way to reproduce this issue?

**Comment by ojw28** [comment]
It could also be that all of these crashes are coming from a customized version of Android, the same as in the other issue. Custom ROMs such as Lineage OS support [quite a lot](https://wiki.lineageos.org/devices/) of devices. Looking at the specific build fingerprints of the devices reporting these crashes should allow you to identify with some degree of accuracy whether they're running customized versions of Android.

**Comment by chhatrasal09** [comment]
> The only similar issue (#7380) report we have had in the past was from a device probably running a customized version of android. In this case, we have a widespread issue, which is new for us. Unfortunately I don't know we can assist with this. I think that we would have more similar reports if this was an ExoPlayer issue.
> 
> > When I tried to find out to the resource id I found out that the...
> 
> Did you manage te reproduce the issue on the APK that you used for the analysis? Because if not, this line could be a red herring.
> 
> I'm inclined to think this may be an issue in the APK's build process but I don't have evidence to support that:
> 
> * Is there any evidence pointing at this being an ExoPlayer issue?
> * Is there any way to reproduce this issue?

- If there is an issue with the build then it should not run on my devices as well? But fortunately it works well on my device and on some devices that we use to test every build before release. So, I don't think this is an issue of build process.
- The resource id that I found from apk points to exo_controls_repeat_all.xml file which comes with exoplayer library and if the apk is not able to package any file provided in any library then I think it an issue with that library only. 
I am getting this crash even if I am not using that particular image. 
If its not an issue of the library then can you point me to any documents/blogss/SO questions where I can find how to remove the read only file of a library to avoid this crash?
- This is resource not found exception, so I. guess I can reproduce it only if I have any one of the above mentioned devices.



> It could also be that all of these crashes are coming from a customized version of Android, the same as in the other issue. Custom ROMs such as Lineage OS support [quite a lot](https://wiki.lineageos.org/devices/) of devices. Looking at the specific build fingerprints of the devices reporting these crashes should allow you to identify with some degree of accuracy whether they're running customized versions of Android.

- Within 2 weeks I got 3k crashes for around 1.3K unique users. Is it possible that all 1.3K devices are custom ROMs?
 The product that we are building is an entertainment app, So I don't think all 1.3K users are using custom ROMs.
- I have checked the list referred by you. For SAMSUNG LineageOS has given support only to J7 of J series devices but there are crashes on other Galaxy J series devices as well. Which supports my previous point.

**Comment by ojw28** [comment]
> Is it possible that all 1.3K devices are custom ROMs?

It's impossible to say without knowing how many users you have in total. In any case, I'm pretty sure Crashlytics should give you more information than just "Android 10". It probably gives you the name of the specific OS build running on the device, or the whole device fingerprint that includes this information. You can look at this information to confirm whether the devices are running custom ROMs or not.

**Comment by chhatrasal09** [comment]
@ojw28 
Here are the screenshots of all the possible places where we can get info about crashes.
<img width="417" alt="Screenshot 2020-08-29 at 5 24 04 AM" src="https://user-images.githubusercontent.com/21989289/92036921-9807ac00-ed8e-11ea-9298-5ea1cfa2af14.png">
<img width="417" alt="Screenshot 2020-08-29 at 5 23 42 AM" src="https://user-images.githubusercontent.com/21989289/92036943-a1911400-ed8e-11ea-9fb3-e16fe236a795.png">
<img width="423" alt="Screenshot 2020-08-29 at 5 23 32 AM" src="https://user-images.githubusercontent.com/21989289/92036950-a655c800-ed8e-11ea-8442-3033c8737fb1.png">
<img width="1255" alt="Screenshot 2020-08-29 at 5 23 22 AM" src="https://user-images.githubusercontent.com/21989289/92036966-ace43f80-ed8e-11ea-90fb-c41c0383ac86.png">

These are the possible places on Crashlytics that I found where we can see the crashes info. But I haven't found any place where the Crashlytics mentioned name of any OS. They just mentioned the android version like **"Android 10, 9"**. There is only thing which can be used to find whether the device has custom ROM or not i.e. **"Rooted"** under Operating System, which I checked for several users for the above crash and for those users the **Rooted** state is **No*.

**Comment by ojw28** [comment]
It's hard to be certain, but in that case I would guess that this is most likely not related to custom ROMs.

**Comment by tonihei** [comment]
Other ideas for things you could check:
 - Is Java 8 enabled on all libraries / modules directly or indirectly depending on ExoPlayer?
 - Do you use multidex? And if so, is it enabled for all relevant app variants? 
 - Do you depend on ExoPlayer in gradle using `implementation`? 

None of this may be related, but it's probably good to verify the build setup with regards to how resources are found and packaged. Also note that resource ids change for each build. So please check that you don't accidentally persists them somehow (see for example https://stackoverflow.com/questions/48015442/how-to-fix-android-content-res-resourcesnotfoundexception-error).

**Comment by AquilesCanta** [comment]
Hi @chhatrasal09, can you think of any way we can follow up on this? I think you are in a better position than we are to diagnose this issue, but if you have any line of work we may follow on our side, we are happy to assist.
