### ISSUE TITLE
"Error decrypting data" when playing Widevine protected content on Nexus 4

### ISSUE THREAD

**Issue by educobuci** [google/ExoPlayer#783]
I'm experiencing consistently a problem when playing Widevine protected content on some devices, specially on Nexus 4, it works for 2 or 3 minutes then I get the following exception:

    09-10 11:48:20.498    4452-4760/com.google.android.exoplayer.demo E/OMXMaster﹕ A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
    09-10 11:48:23.012    4452-4785/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.qcom.video.decoder.avc.secure] storeMetaDataInBuffers failed w/ err -2147483648
    09-10 11:50:22.810    4452-4724/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal track renderer error.
        com.google.android.exoplayer.ExoPlaybackException: android.media.MediaCodec$CryptoException: Error decrypting data.
                at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:683)
                at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:500)
                at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                at android.os.Handler.dispatchMessage(Handler.java:98)
                at android.os.Looper.loop(Looper.java:135)
                at android.os.HandlerThread.run(HandlerThread.java:61)
                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
         Caused by: android.media.MediaCodec$CryptoException: Error decrypting data.
                at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:956)
                at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:674)
                at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:500)
                at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                at android.os.Handler.dispatchMessage(Handler.java:98)
                at android.os.Looper.loop(Looper.java:135)
                at android.os.HandlerThread.run(HandlerThread.java:61)
                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
    09-10 11:50:22.810    4452-4452/com.google.android.exoplayer.demo E/EventLogger﹕ internalError [125.67, cryptoError]
        android.media.MediaCodec$CryptoException: Error decrypting data.
                at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:956)
                at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:674)
                at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:500)
                at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                at android.os.Handler.dispatchMessage(Handler.java:98)
                at android.os.Looper.loop(Looper.java:135)
                at android.os.HandlerThread.run(HandlerThread.java:61)
                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
    09-10 11:50:22.827    4452-4452/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [125.75]
        com.google.android.exoplayer.ExoPlaybackException: android.media.MediaCodec$CryptoException: Error decrypting data.
                at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:683)
                at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:500)
                at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                at android.os.Handler.dispatchMessage(Handler.java:98)
                at android.os.Looper.loop(Looper.java:135)
                at android.os.HandlerThread.run(HandlerThread.java:61)
                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
         Caused by: android.media.MediaCodec$CryptoException: Error decrypting data.
                at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:956)
                at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:674)
                at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:500)
                at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                at android.os.Handler.dispatchMessage(Handler.java:98)
                at android.os.Looper.loop(Looper.java:135)
                at android.os.HandlerThread.run(HandlerThread.java:61)
                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
    

The problem doesn't occur when I use the sample medias included in the ExoPlayer demo, protected or not.
I've also tested the same content on other devices like Motorola Moto E and also on Shaka Player for web and it works normally.

**Comment by ojw28** [comment]
Are you using key rotation? If so, try turning it off and see if that allows you to play successfully.

**Comment by educobuci** [comment]
Hi, no I'm not using key rotation as I forgot to mention, I am able to play the same content on Moto E and using the Shaka web player.

**Comment by ojw28** [comment]
Hm. It sounds a bit like a license configuration issue, although this doesn't really explain why it works on a Moto E.

I'm not sure exactly what your setup is, but one way of setting this up is to have each license response provide keys that are valid for X minutes (possibly 2 or 3 in your case), and be configured to invoke another request after some period shorter than X minutes (e.g. 1 minute). Hence the player should always have valid keys. Have you checked that all of this is configured correctly in your case?

If it continues to be an issue, you're probably best off asking Widevine for help, since the failure is probably in the Widevine CDM underneath ExoPlayer.

**Comment by educobuci** [comment]
Yes the license has not any time limit. It looks like something wrong with the CDM I guess. Is there any way to recovery from this error state? I mean the exception will raise but if I could at least retry automatically that will be a little better. I'm trying the "Retry" button on the demo player but it doesn't recover once the error occur, is there a way to force the license request happen again?

Thanks.

**Comment by ojw28** [comment]
If the problem doesn't occur with the Widevine test content in the demo app, it remains more likely that the root cause of the failure is either the way your content is encoded or the way the licenses are being configured (or at least that it's possible to avoid the failure by encoding or configuring in a different way). There are services that have been widely deployed on Nexus 4 (from KitKat) that use Widevine's CDM without this issue.

I think the retry button does (or should) trigger a fresh license request.
