### ISSUE TITLE
What is possible cause of this Crash ?

### ISSUE THREAD

**Issue by amankr** [google/ExoPlayer#7839]
###  Question
I have an application where a list of infinite short videos are played in a list ( similar to TikTok ).
To improve next video loading, I am using downloadManger with LRU cache. 
The Exoplayer always plays video from this cache and downloadManager prefills it.
Videos are never removed by application code and depends on LRU cache to control unbounded increase in disk size.
skipped videos are put in STATE_STOPPED.

The following crash is observed for some cases in production. ~1 percent of daily users are facing this.

```
Fatal Exception: java.lang.IllegalStateException
       at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
       at com.google.android.exoplayer2.offline.DownloadManager$InternalHandler.putDownloadWithState(DownloadManager.java:1159)
       at com.google.android.exoplayer2.offline.DownloadManager$InternalHandler.onRemoveTaskStopped(DownloadManager.java:1117)
       at com.google.android.exoplayer2.offline.DownloadManager$InternalHandler.onTaskStopped(DownloadManager.java:1078)
       at com.google.android.exoplayer2.offline.DownloadManager$InternalHandler.handleMessage(DownloadManager.java:728)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

I have gone though the code of `DownloadManager.java`. From my understanding it looks like the crash is because the video is going through following states in some cases

Video is in `STATE_STOPPED` -> Somehow goes into `STATE_REMOVING`  -> new request for same video puts it into `STATE_RESTARTING` -> Fails Assertion Check

As this is not always reproduce-able, I am not able to figure out how this crash is happening. Please help me understand this

**Comment by christosts** [comment]
@marcbaechinger can you take a look?

**Comment by marcbaechinger** [comment]
Sorry for my late reply!

> To improve next video loading, I am using downloadManger with LRU cache.

If you only want to download data temporarily it's probably easier to do this directly without using download manager. Using a `DownloadManager` with a LRU cache sounds like difficult to me. 

We have a [blog post about how to pre-cache progressive streams](https://medium.com/google-exoplayer/pre-caching-downloading-progressive-streams-in-exoplayer-3a816c75e8f6). So if you are using progressive media, please take a look whether this blog post can help by using `CacheUtil` directly.  That sounds like a better combination to the LRU eviction strategy. Please let me know whether that's an option.

**Comment by ojw28** [comment]
The root cause of the crash reported here has also been reported in https://github.com/google/ExoPlayer/issues/8419. Please follow that issue for a fix.
