### ISSUE TITLE
java.nio.BufferOverflowException during MP4 playback

### ISSUE THREAD

**Issue by ened** [google/ExoPlayer#787]
Playing a huge (433354867 bytes) MP4 file will work well for around 10 seconds and is then followed by a stop of playback and the following error stack trace:

```
com.google.android.exoplayer.ExoPlaybackException: java.nio.BufferOverflowException
        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:240)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
 Caused by: java.nio.BufferOverflowException
        at java.nio.Buffer.checkPutBounds(Buffer.java:183)
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:355)
        at com.google.android.exoplayer.extractor.RollingSampleBuffer.readData(RollingSampleBuffer.java:287)
        at com.google.android.exoplayer.extractor.RollingSampleBuffer.readSample(RollingSampleBuffer.java:193)
        at com.google.android.exoplayer.extractor.DefaultTrackOutput.getSample(DefaultTrackOutput.java:142)
        at com.google.android.exoplayer.extractor.ExtractorSampleSource.readData(ExtractorSampleSource.java:393)
        at com.google.android.exoplayer.SampleSourceTrackRenderer.readSource(SampleSourceTrackRenderer.java:170)
        at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:562)
        at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:456)
        at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:425)
        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:207)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

ExoPlayer setup is like this:

```
int numRenderers = 2;

final ExtractorSampleSource sampleSource = new ExtractorSampleSource(getIntent().getData(),
        new DefaultUriDataSource(this, "Brand/Product"), new DefaultAllocator(65534), 10485760);

final TrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(sampleSource, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT);
final TrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource);

exoPlayer = ExoPlayer.Factory.newInstance(numRenderers);

exoPlayer.addListener(new ExoPlayer.Listener() {
    @Override
    public void onPlayerStateChanged(final boolean playWhenReady, final int playbackState) {
        Log.d(TAG, "state: " + playbackState);
        if (playbackState == ExoPlayer.STATE_READY) {
            for (int i = 0; i < sampleSource.getTrackCount(); i++) {
                addTrackInfo(sampleSource.getFormat(i));
            }
        }
    }

    @Override
    public void onPlayWhenReadyCommitted() {
    }

    @Override
    public void onPlayerError(final ExoPlaybackException e) {
        addErrors("Error in ExoPlayer", e);
    }
});
exoPlayer.sendMessage(videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, new Surface(surface));
exoPlayer.prepare(videoRenderer, audioRenderer);
exoPlayer.setPlayWhenReady(true);
```

Test file was submitted to @ojw28 - gmail.

**Comment by ojw28** [comment]
On what device do you see this? Thanks.

**Comment by ened** [comment]
Custom device, not released yet, MTK (MT8127)-based. However, we passed CTS completely, so there should not be any system issues.

I can provide you the detail `adb logcat` output.

**Comment by ojw28** [comment]
As an aside, CTS can't test literally everything. Passing CTS isn't a complete guarantee that the device doesn't have any issues.

**Comment by ened** [comment]
Got. After retesting this on a HTC One M8 I definitely see the issue with the particular device I'm using. 

Too bad it's ExoPlayer that actually triggers it. Will find a way to reproduce the problem.  
Thanks!

**Comment by ened** [comment]
One way to reproduce it is by changing the playback position immediately after the video has started (e.g. drag slider half way), then the error will appear later.

**Comment by ened** [comment]
When adding some logging to RollingSampleBuffer.readData:

```
private void readData(long absolutePosition, ByteBuffer target, int length) {
  Log.d("Exo.readData", "capacity: " + target.capacity());
  // ...
}
```

I noticed that a phone like HTC One M8 has a alternating buffer size of **2097088** and **8192** where as my failing device alternates between **65536** and **8192**.

**Comment by ened** [comment]
And this `ByteBuffer` is initially retrieved via `MediaCodecTrackRenderer`, where it is being read from Androids `MediaCodec` class, which returns with a default capacity of 65536. This size is then re-used for any future buffer allocations.

**Comment by ojw28** [comment]
They're not alternating. One size is the input buffers of the video decoder, and the other size is the input buffers of the audio decoder.

Seems your custom device has a video decoder that provides 65K input buffers by default, which is why they then overflow. They're not big enough. The HTC M8's video decoder is providing 2MB buffers.

If you have a contact in MTK, please suggest they look at the default size of the input buffers that their video decoder is exposing.

**Comment by ened** [comment]
You are suggesting a single video frame (or a single sample) as retrieved using MediaCodec is bigger than the buffer available in the video decoder?

Then the question is why it is playing in the first place (for ~ 10 seconds).

**Comment by ojw28** [comment]
It's the MediaCodec's input buffers that are too small (i.e. the ones that the extracted puts the compressed samples in to feed them to the decoder). The compressed video frames are obviously not all the same size; it's likely that it's playing up to a keyframe, which is larger than 65K, and then failing at that point. The keyframe right at the start of the file must be smaller than 65K.
