### ISSUE TITLE
SimpleExoPlayer don't run prepare with HlsMediaSource

### ISSUE THREAD

**Issue by trantrongkim98** [google/ExoPlayer#7872]
### [DESCRIPTION] Issue description

i can start a MediaSource with .mp4 but i can't start with resource is m3u8

### [LOG] A full bug report captured from the device
```bash
E/AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
    Process: com.example.vPlayer, PID: 25608
    java.lang.LinkageError: Method void com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper$FormatAdjustingSampleQueue.format(com.google.android.exoplayer2.Format) overrides final method in class Lcom/google/android/exoplayer2/source/SampleQueue; (declaration of 'com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper$FormatAdjustingSampleQueue' appears in /data/app/com.example.vPlayer-bpUFedlpsM5BKlqrtVuBkQ==/base.apk)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.buildSampleStreamWrapper(HlsMediaPeriod.java:753)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.buildAndPrepareMainSampleStreamWrapper(HlsMediaPeriod.java:609)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.buildAndPrepareSampleStreamWrappers(HlsMediaPeriod.java:481)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.prepare(HlsMediaPeriod.java:158)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod(ExoPlayerImplInternal.java:1554)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1534)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:565)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
E/AndroidRuntime: FATAL EXCEPTION: Loader:HlsSampleStreamWrapper
    Process: com.example.vPlayer, PID: 25608
    java.lang.LinkageError: Method void com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper$FormatAdjustingSampleQueue.format(com.google.android.exoplayer2.Format) overrides final method in class Lcom/google/android/exoplayer2/source/SampleQueue; (declaration of 'com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper$FormatAdjustingSampleQueue' appears in /data/app/com.example.vPlayer-bpUFedlpsM5BKlqrtVuBkQ==/base.apk)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.buildSampleStreamWrapper(HlsMediaPeriod.java:753)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.buildAndPrepareMainSampleStreamWrapper(HlsMediaPeriod.java:609)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.buildAndPrepareSampleStreamWrappers(HlsMediaPeriod.java:481)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.prepare(HlsMediaPeriod.java:158)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod(ExoPlayerImplInternal.java:1554)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1534)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:565)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

### [version] :
- implementation 'com.google.android.exoplayer:exoplayer-core:2.11.5'
- implementation 'com.google.android.exoplayer:exoplayer-dash:2.11.5'
- implementation 'com.google.android.exoplayer:exoplayer-ui:2.11.5'
- implementation 'com.google.android.exoplayer:exoplayer-hls:2.11.1'
- implementation 'com.google.android.exoplayer:exoplayer-smoothstreaming:2.11.1'

### [DEVICE]:
 - Vsmart Live Android 10

**Comment by trantrongkim98** [comment]
i fixed it, my version 1.11.5 was wrong and i use 2.11.1 and `implementation fileTree(dir: "libs", include: ["*.jar"])`
