### ISSUE TITLE
why implementation with link don't work in when inplementation work with project

### ISSUE THREAD

**Issue by trantrongkim98** [google/ExoPlayer#7874]
### [REQUIRED] Searched documentation and issues
```bash
  implementation project(modulePrefix + 'library-core')
    implementation project(modulePrefix + 'library-dash')
    implementation project(modulePrefix + 'library-hls')
    implementation project(modulePrefix + 'library-smoothstreaming')
    implementation project(modulePrefix + 'library-ui')
//    implementation 'com.google.android.exoplayer:exoplayer-core:2.11.5'
//    implementation 'com.google.android.exoplayer:exoplayer-dash:2.11.5'
//    implementation 'com.google.android.exoplayer:exoplayer-ui:2.11.5'
//    implementation 'com.google.android.exoplayer:exoplayer-hls:2.11.1'
//    implementation 'com.google.android.exoplayer:exoplayer-smoothstreaming:2.11.1'
```

### [REQUIRED] Question
i don't start a video hls when i use link from repository github

### A full bug report captured from the device
- when i implemention with link
```bash
AndroidRuntime: FATAL EXCEPTION: Loader:HlsSampleStreamWrapper
    Process: com.example.vPlayer, PID: 11664
    java.lang.LinkageError: Method void com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper$FormatAdjustingSampleQueue.format(com.google.android.exoplayer2.Format) overrides final method in class Lcom/google/android/exoplayer2/source/SampleQueue; (declaration of 'com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper$FormatAdjustingSampleQueue' appears in /data/app/com.example.vPlayer-9eL6EaYwcF4FI5TIjAKDVA==/base.apk)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.buildSampleStreamWrapper(HlsMediaPeriod.java:753)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.buildAndPrepareMainSampleStreamWrapper(HlsMediaPeriod.java:609)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.buildAndPrepareSampleStreamWrappers(HlsMediaPeriod.java:481)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.prepare(HlsMediaPeriod.java:158)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod(ExoPlayerImplInternal.java:1554)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1534)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:565)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by trantrongkim98** [comment]
I fixed it, i was use version 2.11.5 and it's wrong then i use version 2.11.1 and it work for me
and i was add `implementation fileTree(dir: "libs", include: ["*.jar"])`
