### ISSUE TITLE
AudioSink$InitializationException after fast seeking in tunneling mode

### ISSUE THREAD

**Issue by AGasztold** [google/ExoPlayer#7879]
**Issue description**
This issue was detected in our app (during random seeking/track changing), but also reproduced in Exoplayer Demo (playback was freezed after rapid seeking at the end of the stream).

**Reproduction steps**
1. Start tunneling mode
2. Open VOD - DASH/Widevine video
3. Seek to the end of the stream -> and continue seeking for a while (playback state is changing through ENDED->BUFFERING->READY)
4. Exit PlayerActivity and start playback once again -> first chunks are buffered, playback state is READY, but there is no video/audio playing
5. Exit PlayerActivity and start playback again -> no playback again and we can see following exception:

_ExoPlayerImplInternal: Renderer error: index=3, type=audio, format=Format(8, null, null, audio/mp4a-latm, mp4a.40.2, 128000, pl, [-1, -1, -1.0], [2, 48000]), rendererSupport=NO_UNSUPPORTED_DRM
      com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 12, 48000)
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:831)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1590)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:721)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 12, 48000)
        at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:1428)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:527)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:608)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:824)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1590) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:721) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164)_ 

Please find the video of reproduction (but recorded in different time than log provided):
https://drive.google.com/file/d/1WdH7MTepAvUyaYMOpe72X6SFHBIkNFoR/view?usp=sharing

**Link to test content**
These tests were performed on video content from our CDN. I will provide more details if needed.

**Log file**
https://drive.google.com/file/d/1-vGXjuDiBk3BjwuJY0j49vUeaF-dyLcd/view?usp=sharing
Please let me know if bugreport is needed as well.

**Version of ExoPlayer being used**
2.11.8

**Device(s) and version(s) of Android being used**
Sagemcom STB - Android 8.0

**Comment by kim-vde** [comment]
It could be the same problem as in #4448. They both happen when recreating the AudioTrack, they both have error message "E/AudioTrack: Could not get audio output for session..." and they both happen on Android 8.

**Comment by AGasztold** [comment]
Hello, I am not 100% sure if both issues are the same. Issue #4448 occurred on Exoplayer 2.8.1. I have noticed this situation on 2.11.8 (only on Android 8, in tunneling mode), but I could not reproduce it on 2.9.3. Anyway, is it possible to make a workaround for that?

**Comment by krocard** [comment]
It might not be the same root cause, but it is the same symptom of an AudioTrack init failing because an AudioTrack using the same resources was release recently (and it's resources probably not available yet).
There are two workarounds that ExoPlayer will soon support that should avoid this issue:
 - avoiding to release the AudioTrack on seek (this is currently experimental)
 - retrying to create the AudioTrack after a short delay (like 100ms). This should be implemented soon and is tracked by #4448.

As this is the same workarounds as #4448, I will mark this as its duplicate.

**Comment by AGasztold** [comment]
Ok, I see. Thank you for your answer!
