### ISSUE TITLE
Something happend at 13f4a3e

### ISSUE THREAD

**Issue by tai2** [google/ExoPlayer#788]
By bisect I've found that commit 13f4a3e broke streams that could be properly played just before applying it.

* device: Nexus5 Android 5.1.1
* branch: dev 5050913
* app: ExoPlayer demo

I'm sorry I cannot share the media file publicly so media url is hidden. This stream is dynamically transmitted and stream session depends on a cookie, although I'm not certain that it has something to do with it or not.

```
09-11 18:23:27.738  23000-23000/? I/art﹕ Late-enabling -Xcheck:jni
09-11 18:23:27.846  23000-23000/com.google.android.exoplayer.demo W/VideoCapabilities﹕ Unrecognized profile 2130706433 for video/avc
09-11 18:23:27.869  23000-23000/com.google.android.exoplayer.demo I/VideoCapabilities﹕ Unsupported profile 4 for video/mp4v-es
09-11 18:23:27.878  23000-23042/com.google.android.exoplayer.demo D/OpenGLRenderer﹕ Use EGL_SWAP_BEHAVIOR_PRESERVED: true
09-11 18:23:27.883  23000-23000/com.google.android.exoplayer.demo D/Atlas﹕ Validating map...
09-11 18:23:27.910  23000-23042/com.google.android.exoplayer.demo I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 01/14/15, ab0075f, Id3510ff6dc
09-11 18:23:27.910  23000-23042/com.google.android.exoplayer.demo I/OpenGLRenderer﹕ Initialized EGL, version 1.4
09-11 18:23:27.924  23000-23042/com.google.android.exoplayer.demo D/OpenGLRenderer﹕ Enabling debug mode 0
09-11 18:23:32.902  23000-23000/com.google.android.exoplayer.demo I/ExoPlayerImpl﹕ Init 1.4.2
09-11 18:23:32.913  23000-23000/com.google.android.exoplayer.demo D/EventLogger﹕ start [0]
09-11 18:23:32.919  23000-23000/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.01, false, P]
09-11 18:23:32.928  23000-23000/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.01, true, P]
09-11 18:23:33.038  23000-23042/com.google.android.exoplayer.demo D/OpenGLRenderer﹕ endAllStagingAnimators on 0xb49a0300 (ListView) with handle 0xa2024f10
09-11 18:23:34.170  23000-23000/com.google.android.exoplayer.demo D/EventLogger﹕ state [1.26, true, B]
09-11 18:23:34.270  23000-23098/com.google.android.exoplayer.demo W/HlsChunkSource﹕ Final variant not blacklisted (404): https://XXXXXXXX
09-11 18:23:34.271  23000-23000/com.google.android.exoplayer.demo E/EventLogger﹕ internalError [1.36, loadError]
    com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
            at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
            at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:136)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:101)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
09-11 18:23:34.294  23000-23098/com.google.android.exoplayer.demo W/HlsChunkSource﹕ Final variant not blacklisted (404): https://XXXXXXXX
09-11 18:23:34.295  23000-23000/com.google.android.exoplayer.demo E/EventLogger﹕ internalError [1.38, loadError]
    com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
            at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
            at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:136)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:101)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
09-11 18:23:35.327  23000-23098/com.google.android.exoplayer.demo W/HlsChunkSource﹕ Final variant not blacklisted (404): https://XXXXXXXX
09-11 18:23:35.328  23000-23000/com.google.android.exoplayer.demo E/EventLogger﹕ internalError [2.41, loadError]
    com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
            at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
            at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:136)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:101)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
09-11 18:23:37.410  23000-23098/com.google.android.exoplayer.demo W/HlsChunkSource﹕ Final variant not blacklisted (404): https://XXXXXXXX
09-11 18:23:37.420  23000-23000/com.google.android.exoplayer.demo E/EventLogger﹕ internalError [4.51, loadError]
    com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
            at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
            at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:136)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:101)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
09-11 18:23:37.424  23000-23098/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:146)
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:133)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:207)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
            at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
            at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:136)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:101)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
09-11 18:23:37.442  23000-23000/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [4.53]
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:146)
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:133)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:207)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
            at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
            at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:136)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:101)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
09-11 18:23:37.443  23000-23000/com.google.android.exoplayer.demo D/EventLogger﹕ state [4.53, true, I]
```

**Comment by ojw28** [comment]
It's difficult to see how that change could have broken playback in this way.

These are 404 responses from the server, so I think the only thing on the client that could cause this is if the URLs actually incorrect. You've disguised the URLs in your log. Are the original undisguised URLs that are 404ing actually valid, and is there definitely content at them?

**Comment by tai2** [comment]
I added the same URLs between the commits when I tried.
I agree this is very odd behaviour because HTTP parameters isn't explicitly changed in the change set.
But URL is the same then, the change might influenced HTTP headers implicitly.
I will investigate this some more.

**Comment by tai2** [comment]
Can I dump all HTTP headers to logs? It need a hassle to capture the packets because It's HTTPS session.

**Comment by tai2** [comment]
Now logs added and seeing more details.

**Comment by tai2** [comment]
I've got why this error occurred (But I don't understand which code lines made this result yet).

Our server is a bit special. If one stream is consumed, it is disappeared immediately and cannot be used forever. If a client accesses the consumed stream, the server returns 404 response.

For example, a client request a m3u8 file and server generate a file list dynamically.

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:11
#EXTINF:10.110100,
stream_0.ts
#EXTINF:9.943267,
stream_1.ts
#EXTINF:9.943267,
stream_2.ts
```

Once stream_0.ts is consumed, the client must request stream_1.ts and the next is stream_2.ts and so on.

But the commit 13f4a3e changed access pattern. Once a client request stream_0.ts and retrieve 200 response, it request straem_0.ts again and retrieve 404 error. That's what happened and this don't occur before 13f4a3e. Do you have any ideas about which changes can make this? @ojw28

**Comment by ojw28** [comment]
It's the change in HlsSampleSource.enable that's causing the problem. Fetching the first chunk twice isn't ideal, but our previous attempts to optimise that have proven quite problematic. I'll take another look.

That side, your server just shouldn't do that. Why is that a sensible way for the server to behave (consider other cases, for example if the client hits an error and needs to fetch the chunk again)?

**Comment by mkazuma29** [comment]
Thanks all.

I agree your opinion.
Currently the server's response is starting with the chunk that the client previously got. This is the workaround for JWPlayer, and it never get that one again, so the server doesn't deliver the one previously got from the client.

If the server can deliver the chunk even if that is got from the client previously, is this issue fixed???
I'll take a investigation on the server implementation!!

**Comment by ojw28** [comment]
According to the HLS spec:

```Any Media Segment that is specified in a Playlist loaded by a client
   MUST be available for immediate download within at least the segment
   duration, or playback errors can occur.```

So when the client loads a playlist containing a list of segments, all of the listed segments must be available for the client to download for at least the duration of the last segment in the list. If the server wishes to make segments so they're no longer available, the server is required to remove them from the playlist so that the client doesn't see them in the list when it next refreshes the playlist.

I have a feeling that all segments in the playlist should remain available if the playlist has an EXT-X-ENDLIST, although the spec is unclear (and slightly contradictory) on this point, so I'm unsure.

**Comment by ojw28** [comment]
Note - We will be fixing the specific issue of downloading the first segment twice with a new (and hopefully correct this time around) optimisation. We'll push the fix shortly. This will remove the most obvious failure you've noticed, however it's likely you'll experience other more subtle failures until you fix your server to be compliant. There are no hard guarantees that ExoPlayer will not download the same segments more than once.

**Comment by mkazuma29** [comment]
Thanks for your quick fix!!   I'm modifying the server to keep all of the segment data listed on playlist available.
In our case, all of the streaming is  delivered without EXT-X-ENDLIST on the playlist, so the modification should be enough for the spec.

**Comment by tai2** [comment]
Thank you for advice. We've fixed the problem by server modification.
