### ISSUE TITLE
I want play video with subtitle offline, but i can not run

### ISSUE THREAD

**Issue by longquangpham90** [google/ExoPlayer#7885]
### [REQUIRED] Question
We can not play subtitle offline local device Sony XZ Premium
Application is run file video offline, but can not run with subtitle 
Can you support
This is logcat report 
### A full bug report captured from the device

> Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: 
```
java.io.FileNotFoundException: /storage/emulated/0/Download/136614.vie.vtt: open failed: ENOENT (No such file or directory)
>         at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:119)
>         at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:88)
>         at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177) 
>         at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:487) 
>         at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:288) 
>         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
>         at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SourceLoadable.load(SingleSampleMediaPeriod.java:404) 
>         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
>         at java.lang.Thread.run(Thread.java:764) 
>      Caused by: java.io.FileNotFoundException: /storage/emulated/0/Download/136614.vie.vtt: open failed: ENOENT (No such file or directory)
>         at libcore.io.IoBridge.open(IoBridge.java:485)
>         at java.io.RandomAccessFile.<init>(RandomAccessFile.java:288)
>         at java.io.RandomAccessFile.<init>(RandomAccessFile.java:151)
>         at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:108)
>         at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:88) 
>         at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177) 
>         at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:487) 
>         at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:288) 
>         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
>         at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SourceLoadable.load(SingleSampleMediaPeriod.java:404) 
>         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
>         at java.lang.Thread.run(Thread.java:764) 
>      Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
>         at libcore.io.Linux.open(Native Method)
>         at libcore.io.BlockGuardOs.open(BlockGuardOs.java:210)
>         at libcore.io.IoBridge.open(IoBridge.java:471)
>         at java.io.RandomAccessFile.<init>(RandomAccessFile.java:288) 
>         at java.io.RandomAccessFile.<init>(RandomAccessFile.java:151) 
>         at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:108) 
>         at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:88) 
>         at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177) 
>         at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:487) 
>         at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:288) 
>         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
>         at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SourceLoadable.load(SingleSampleMediaPeriod.java:404) 
>         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
>         at java.lang.Thread.run(Thread.java:764) 
>     ]
```

**Comment by kim-vde** [comment]
The `FileDataSource` does not find the file `/storage/emulated/0/Download/136614.vie.vtt`.

What happens if you execute `adb ls /storage/emulated/0/Download`? Does the file exist?

**Comment by longquangpham90** [comment]
yes file is exist
we can read and open with File Manager, but EXOPlayer can not run

**Comment by kim-vde** [comment]
`FileDataSource` uses a `RandomAccessFile` to read the file (at least in the latest version of ExoPlayer). Can you debug and check what are the parameters passed to the constructor of `RandomAccessFile`? What version of ExoPlayer are you using?
