### ISSUE TITLE
Unable to play midrolls

### ISSUE THREAD

**Issue by chladto1** [google/ExoPlayer#7889]
### [REQUIRED] Issue description
When _timeOffset_ atribute in VMAP has non zero milliseconds and ads server does not return ad, next ads will not be played any more.

### [REQUIRED] Reproduction steps
Use VMAP below and seek between two midrolls.

### [REQUIRED] Link to test content
[https://devs.origin.cdn.cra.cz/ima/zenexoupdate.xml](https://devs.origin.cdn.cra.cz/ima/zenexoupdate.xml)

### [REQUIRED] A full bug report captured from the device
`2020-09-11 11:58:41.380 31430-31430/com.google.android.exoplayer2.demo E/ImaAdsLoader: Internal error in onAdEvent
      java.lang.NumberFormatException: For input string: "20.5"
        at java.lang.Integer.parseInt(Integer.java:615)
        at java.lang.Integer.parseInt(Integer.java:650)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.handleAdEvent(ImaAdsLoader.java:891)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.access$1100(ImaAdsLoader.java:89)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader$ComponentListener.onAdEvent(ImaAdsLoader.java:1416)
        at com.google.ads.interactivemedia.v3.internal.ajo.a(IMASDK:50)
        at com.google.ads.interactivemedia.v3.internal.ajd.a(IMASDK:32)
        at com.google.ads.interactivemedia.v3.internal.akl.a(IMASDK:47)
        at com.google.ads.interactivemedia.v3.internal.ako.b(IMASDK:20)
        at com.google.ads.interactivemedia.v3.internal.akm.shouldOverrideUrlLoading(IMASDK:6)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle.aab-stable-1:16)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:197)
        at android.app.ActivityThread.main(ActivityThread.java:8125)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2020-09-11 11:58:41.381 31430-31430/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=11.37, mediaPos=15.15, window=0, loadError
      com.google.android.exoplayer2.source.ads.AdsMediaSource$AdLoadException: java.lang.RuntimeException: Internal error in onAdEvent
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.maybeNotifyInternalError(ImaAdsLoader.java:1253)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.access$1000(ImaAdsLoader.java:89)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader$ComponentListener.onAdEvent(ImaAdsLoader.java:1418)
        at com.google.ads.interactivemedia.v3.internal.ajo.a(IMASDK:50)
        at com.google.ads.interactivemedia.v3.internal.ajd.a(IMASDK:32)
        at com.google.ads.interactivemedia.v3.internal.akl.a(IMASDK:47)
        at com.google.ads.interactivemedia.v3.internal.ako.b(IMASDK:20)
        at com.google.ads.interactivemedia.v3.internal.akm.shouldOverrideUrlLoading(IMASDK:6)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle.aab-stable-1:16)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:197)
        at android.app.ActivityThread.main(ActivityThread.java:8125)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)`

### [REQUIRED] Version of ExoPlayer being used
2.11.8

### [REQUIRED] Device(s) and version(s) of Android being used
Any

**Comment by andrewlewis** [comment]
Thanks for the report. There is a fix in review.
