### ISSUE TITLE
onNotificationPosted startForeground - Null pointer exception class name is null

### ISSUE THREAD

**Issue by hobsRKM** [google/ExoPlayer#7893]
I have created a player service and started it in MainActivity.
When i play an audio and in onNotificationPosted when i try to startForground the application crashes with error

```
 java.lang.NullPointerException: class name is null
        at android.content.ComponentName.<init>(ComponentName.java:116)
        at android.app.Service.startForeground(Service.java:695)
        at com.test.myapplication.ui.player.MusicPlayerInitExo$3.onNotificationPosted(MusicPlayerInitExo.java:526)
```
**Here is my setup**

```
public class MainActivity  extends AppCompatActivity  {
    MusicPlayerInitExo musicPlayerObj;
 .....................................
    private NotificationManager mNotificationManager;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        ...................................................
        Intent intent = new Intent(this,MusicPlayerInitExo.class);
        Util.startForegroundService(this,intent);
```

**Service**
```
public class MusicPlayerInitExo extends Service {
..................................
.............
  new PlayerNotificationManager.NotificationListener() {
                    @Override
                    public void onNotificationPosted(int notificationId, Notification notification, boolean ongoing) {
                         startForeground(notificationId, notification) ;

                    }
                    @Override
                    public void onNotificationCancelled(int notificationId, boolean dismissedByUser) {
                        if (dismissedByUser) {
                            // Do what the app wants to do when dismissed by the user.
                            player.release();
                            playerNotificationManager.setPlayer(null);
                            stopSelf();
                            System.exit(0);
                        }
                    }
                });
```

**Comment by hobsRKM** [comment]
Had to start it on Oncreate
