### ISSUE TITLE
Shoutcast v1 Error

### ISSUE THREAD

**Issue by kayabuyukcelen** [google/ExoPlayer#791]
Hello,

Exoplayer works well with Shoutcast v2 servers with aac+ streaming. But in shoutcast v1 I get this error.

How can I handle this?

E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeThrowError(MediaCodecTrackRenderer.java:782)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:274)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:197)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:806)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:737)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by ojw28** [comment]
The player isn't recognising the format of the stream. Could you provide a link to it?

**Comment by kayabuyukcelen** [comment]
Of course,

http://sonic.medyainternet.com:9632/;stream.nsv
http://radyodejavu.canliyayinda.com:8054/;stream.nsv

These are standart shoutcast v1.9.x

Same code works on shoutcast 2.x servers.
Example; http://stream.radyovaveyla.com/;stream.nsv
http://radyobozcaada.canliyayinda.com:4000/;1

Thanks a lot.

**Comment by ojw28** [comment]
The AdtsExtractor's sniff method returns false for the affected streams, but if you force it to return true then they play just fine. It looks like the server doesn't bother to make sure that it starts sending data from the beginning of an ADTS frame; the data just starts from an arbitrary point in the stream.

To correctly sniff these streams, I think we'd need to locate the first sync word (after any ID3 headers have been skipped). This could be anywhere in the first 8K of data, since that's the maximum ADTS frame size. We would then need to either verify the ADTS frame header, and/or possibly read its length and check that there's another sync word immediately following it.

@andrewlewis Thoughts?

**Comment by andrewlewis** [comment]
Sounds good. The platform extractor checks for a frame at the start of the stream, but I can't see a reason not to search as we do for MP3.

**Comment by kayabuyukcelen** [comment]
Thanks @ojw28 . Just made it work with modifying sniff method.

**Comment by ojw28** [comment]
Sniffing should now correctly detect these streams.
