### ISSUE TITLE
Not able to play some DRM/Non-DRM content, while others play just fine -> 2.12.0

### ISSUE THREAD

**Issue by nishantkp** [google/ExoPlayer#7919]
### [REQUIRED] Issue description
I am having trouble playing some videos. Some VOD/Live DRM+Non-DRM works just fine, but some are not playing and throwing following error. Not sure whats wrong with it.

I have tried non-DRM with Demo app, but it is working there but the same piece of content is not playing on my end. I am not able to figure out issue. Can you please help me narrow it down?

### [REQUIRED] Reproduction steps
Not necessary at the moment

### [REQUIRED] Link to test content
Works just fine on sample app, so its not going to help

### [REQUIRED] A full bug report captured from the device
```
com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: : open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:97)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:193)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SourceLoadable.load(SingleSampleMediaPeriod.java:428)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: : open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:166)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:89)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:193) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SourceLoadable.load(SingleSampleMediaPeriod.java:428) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.io.FileNotFoundException: : open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
        at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:155)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:89) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:193) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SourceLoadable.load(SingleSampleMediaPeriod.java:428) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289) 
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152) 
        at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:155) 
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:89) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:193) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SourceLoadable.load(SingleSampleMediaPeriod.java:428) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

### [REQUIRED] Version of ExoPlayer being used
it started appearing after I have updated it to 2.12.0 from 2.11.8

### [REQUIRED] Device(s) and version(s) of Android being used
Any device

**Comment by icbaker** [comment]
From the stack trace it looks like you're trying to open an empty file path.

FileNotFoundException generally includes the path in the message (like this example from #7885):
`java.io.FileNotFoundException: /storage/emulated/0/Download/136614.vie.vtt: open failed: ENOENT (No such file or directory)`

But in your log, there's nothing between those two colons before `open failed` (suggesting the path is `""`):
`Caused by: java.io.FileNotFoundException: : open failed: ENOENT (No such file or directory)`

If the problem only reproduces in your app, and not in the demo app, then it seems likely it's related to the way you pass the file path to ExoPlayer. Can you run through with a debugger/logging and see if you can work out why the file path is ending up as an empty string?

We can't really provide more help than that without more info. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com (with subject "Issue #1234").

**Comment by nishantkp** [comment]
Hi @icbaker,

Figured out what was wrong, I was creating a `MediaItem.Subtitle` with empty subtitle url and passing it to `MediaItem`. Now I have just added a sanity check before creating a `List<MediaItem.Subtitle>` for subtitle url and it works just fine.

In previous version (2.11.8) I was creating a subtitle source with, 

```java
SingleSampleMediaSource subTitleSource =
                new SingleSampleMediaSource.Factory(mediaDataSourceFactory)
                        .createMediaSource(
                                subTitleUri,
                                Format.createTextSampleFormat(null, MimeTypes.TEXT_VTT,
                                        Format.NO_VALUE, "en", null),
                                C.TIME_UNSET);
```

and was using `MergingMediaSource` to combine both the media and subtitle. In that was not checking for empty subtitle url so I have just omitted that part when I have updated to 2.12.0 .
