### ISSUE TITLE
AbstractMethodError crash exception

### ISSUE THREAD

**Issue by VeiZhang** [google/ExoPlayer#7927]
### [REQUIRED] Issue description
Update Exo Player from v2.11.4 to v2.12.0, it crashed every time when playing a movie.

### [REQUIRED] Reproduction steps
Playing a movie.

### [REQUIRED] Link to test content
No special play link.

### [REQUIRED] A full bug report captured from the device
```
E/AndroidRuntime: FATAL EXCEPTION: ExoPlayer:Playback
    Process: com.excellence.tv, PID: 28558
    java.lang.AbstractMethodError: abstract method "java.lang.String com.google.android.exoplayer2.RendererCapabilities.getName()"
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:410)
        at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:235)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:183)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1969)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```
### [REQUIRED] Version of ExoPlayer being used
The latest.

### [REQUIRED] Device(s) and version(s) of Android being used
Amlogic 905x, Android 7.1

**Comment by VeiZhang** [comment]
I also try in exo player sample with use **mave library**, it also show these logs:
```
2020-09-16 15:56:30.108 E: FATAL EXCEPTION: ExoPlayer:Playback
    Process: com.google.android.exoplayer2.demo, PID: 2512
    java.lang.AbstractMethodError: abstract method "java.lang.String com.google.android.exoplayer2.RendererCapabilities.getName()"
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:410)
        at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:235)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:183)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1969)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by icbaker** [comment]
[Previous issues](https://github.com/google/ExoPlayer/issues?q=abstractmethoderror+) have various suggestions to tweak your gradle config:

https://github.com/google/ExoPlayer/issues/7349#issuecomment-626103954:
```
android.enableDexingArtifactTransform=false
```

https://github.com/google/ExoPlayer/issues/6801#issuecomment-569933539:
```
compileOptions {
  targetCompatibility JavaVersion.VERSION_1_8
}
```

There are probably more ideas if you dig through the other issues in that search.

**Comment by VeiZhang** [comment]
@icbaker Thnaks. It is so strange.
