### ISSUE TITLE
How to use ExoPlayer IMA Extension to display Ads only without content video?

### ISSUE THREAD

**Issue by colorhaake** [google/ExoPlayer#7929]
Hi there,

My requirement is we only want to display VAST ads on our android app but without content video.

I follow the [guide](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side) on the Google IMA SDK to use the ExoPlayer IMA extension

Without content video, so I tried to put an empty string in MediaSource

```
val mediaSourceWithAds = AdsMediaSource(
        // We only want to play ads video and we don't have any content video
        // Pass empty url here and it would raise MalformedURLException exception but we  ignore it
        buildMediaSource(Uri.parse("")),
        DefaultDataSourceFactory(requireContext(), userAgent),
        imaAdsLoader,
        videoPlayerView
)
```

It will get the `MalformedURLException` exception. Butt ads can still be played except we cannot receive the ads event `COMPLETED` or `ALL_ADS_COMPLETED`.
```
 com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:309)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.MalformedURLException: no protocol: 
        at java.net.URL.<init>(URL.java:601)
```

I thought the exception is only related to the content video. It should not affect the ads event.
It's important for us to get the correct event. 
How can I play the ads only without content video and get the correct event?
I am using the latest ExoPlayer IMA SDK
`com.google.android.exoplayer:extension-ima:2.12.0 `

BTW, I have seen the thread https://github.com/google/ExoPlayer/issues/3774. They recommend using AdMob. But using AdMob is not our expectation. We just want to play VAST ads on the video player.

Thanks
Joseph

**Comment by andrewlewis** [comment]
Using AdMob is the right way to do this, per #3774, which you've already seen.

It might work to do a hack where you use a valid piece of content that's very short (perhaps `SilenceMediaSource`) but that is not recommended/supported. Creating a `ProgressiveMediaSource` with an empty URL doesn't have that behavior.

**Comment by colorhaake** [comment]
`SilenceMediaSource` is a quick solution for what I want. Thanks for your advice
