### ISSUE TITLE
Unable to add VideoAdPlayerCallback to ImaAdsLoader in latest version 2.12.0

### ISSUE THREAD

**Issue by Manvendra-Jadon** [google/ExoPlayer#7944]
I am getting an error, where video force closes before playing mid-roll ad. Here is the stack trace for the same:
```
E/ImaAdsLoader: Internal error in loadAd
java.lang.IllegalStateException: Failed to find cue point
at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.getAdGroupIndexForAdPod(ImaAdsLoader.java:1457)
at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.loadAd(ImaAdsLoader.java:845)
at com.google.ads.interactivemedia.v3.internal.akf.a(IMASDK:23)
at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:177)
at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:44)
at com.google.ads.interactivemedia.v3.internal.ake.b(IMASDK:28)
at com.google.ads.interactivemedia.v3.internal.akc.shouldOverrideUrlLoading(IMASDK:6)
at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:17)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:143)
at android.os.Looper.loop(Looper.java:122)
at android.app.ActivityThread.main(ActivityThread.java:5597)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```
I tried upgrading ima extension to latest version, but i am unable to add callback, which is required on my end.

**Comment by andrewlewis** [comment]
Please could you share the ad tag here or email it to `dev.exoplayer@gmail.com` with subject "#7944"? Thanks.

**Comment by Manvendra-Jadon** [comment]
@andrewlewis Details sent through email(dev.exoplayer@gmail.com).

**Comment by andrewlewis** [comment]
> I tried upgrading ima extension to latest version, but i am unable to add callback, which is required on my end.

On the latest version I can't reproduce the problem (the ad tag has two empty ads with cue points "0" and "-1" (postroll) but both are located correctly).

Could you give some more details about what information you need from `VideoAdPlayerCallback`? The same information should be available via player listeners, so there may be an alternative way to implement what you're trying to do.

**Comment by Manvendra-Jadon** [comment]
<img width="537" alt="Screenshot 2020-09-28 at 4 46 13 PM" src="https://user-images.githubusercontent.com/70095620/94425857-3d554a80-01aa-11eb-926a-00cd89bad15c.png">

@andrewlewis If you see screenshot, when i am upgrading from 2.11.5 to 2.12.0, i am not able to add this callback showing in red. Because of this i am unable to check anything on latest version.

Also, stack-trace mentioned in the bug: https://github.com/google/ExoPlayer/issues/7322
is the same i get when video force closes before playing mid-roll.

**Comment by andrewlewis** [comment]
What events to do you handle in your `VideoAdPlayerCallback`? I am wondering if you can replace those with listening to events on the player to avoid needing to add a callback. See also #6249.

**Comment by Manvendra-Jadon** [comment]
@andrewlewis We handle onPlay(), onEnded(), onError(). Is there no way to add this callback on latest version? As this is lot of effort on my end to change this and will surely break few things.

Also, what about this:
Stack-trace mentioned in the bug: #7322
is the same i get when video force closes before playing mid-roll.
