### ISSUE TITLE
Exoplayer streaming issue in android 11

### ISSUE THREAD

**Issue by nareshsvn** [google/ExoPlayer#8022]
In our project, we are using exo-player for playing the streamed audio tracks. Our app is audiobook reader. App downloads encrypted audio book from server. After decryption, the content is available on the local server from where we fetch each track and play that in exo player. Up until now the app was working fine.
After migration app to android 11, When we try to play audio in exo-player we are getting the following error- **"connection timed out and socket got closed. source internal error"** .
Before android 11 migration, exo-player was working fine. After migration, we are finding this issue.
We tested with Media player and found that streaming data is playing fine even in android 11 device.
Could you please advice on what is causing this issue in exo-player.

**below are the ex-player dependencies used in the app**

    implementation 'com.google.android.exoplayer:exoplayer-core:2.12.0'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.12.0'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.12.0'

**Code used in the project:**

SimpleExoPlayer exoPlayer = new SimpleExoPlayer.Builder(this)
                        .setTrackSelector( new DefaultTrackSelector(this))
                        .build();
						
 Uri uri = Uri.parse("http://127.0.0.1:8080/9780230490864_010_MP3.mp3");
 MediaSource mediaSource =
         new ExtractorMediaSource.Factory(
                new DefaultHttpDataSourceFactory("exoplayer-codelab")).
                createMediaSource(uri);					
						
player.setMediaSource(mediaSource);
player.prepare();
player.setPlayWhenReady(true);

**Error message:**

2020-09-30 19:57:31.211 7098-7313/uk.co.firstygroup.glassboxx E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://127.0.0.1:8080/9780230490864_010_MP3.mp3
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:203)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:841)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.net.SocketTimeoutException: timeout
        at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:200)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:841)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

Thanks

**Comment by krocard** [comment]
From the stack trace, it seems like the TCP connection was successfully established, the request send, but the server did not answer.
This seems like this is an issue with the server but without more information like an analysis from the [network profiler](https://developer.android.com/studio/profile/network-profiler) or a way to reproduce, I'm afraid we can not help you further.

**Comment by nareshsvn** [comment]
Hi,

I have modified my local server settings. now the exo-player is working.

Thanks for your timely support.
