### ISSUE TITLE
EOF Exception when trying to play HLS file

### ISSUE THREAD

**Issue by pernilla** [google/ExoPlayer#804]
We're trying to play an HLS file and get an EOFException (see added exception below). I have looked in the response and request and nothing looks weird, we also provided Accept-Encoding: identity. The same file plays well in other players such as Safari's built in player, NexPlayer for Android, and, VLC for example. Can anyone give us an idea why Exoplayer thinks this file is not playable? 

Unfortunately I can't add the stream here publicly, but I'm happy to provide it by email if someone wants to take a look. 

```java
09-17 13:30:02.397  23430-23430/? E/EventLogger﹕ internalError [2.28, loadError]
    java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:87)
            at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114)
            at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
09-17 13:30:02.469  23430-23430/? E/EventLogger﹕ internalError [2.36, loadError]
    java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:87)
            at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114)
            at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
09-17 13:30:03.254     356-1006/? D/audio_hw_primary﹕ disable_audio_route: reset and update mixer path: low-latency-playback
09-17 13:30:03.260     356-1006/? D/audio_hw_primary﹕ disable_snd_device: snd_device(5: headphones)
09-17 13:30:03.628  23430-23430/? E/EventLogger﹕ internalError [3.51, loadError]
    java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:87)
            at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114)
            at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
09-17 13:30:03.828  16746-17331/? W/ctxmgr﹕ [PowerConnectionState]Got same value as before for power connection (Plug state: 2 BatteryLevel: 0.54)
09-17 13:30:05.779  23430-23430/? E/EventLogger﹕ internalError [5.66, loadError]
    java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:87)
            at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114)
            at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
09-17 13:30:05.785   23430-3896/? E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: java.io.EOFException
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:146)
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:137)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:277)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:199)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:87)
            at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114)
            at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
09-17 13:30:05.797     810-1447/? V/WindowManager﹕ Adding window Window{29a10123 u0 Panel:com.google.android.exoplayer.demo/com.google.android.exoplayer.demo.PlayerActivity} at 17 of 23 (after Window{3d1e5fa u0 com.google.android.exoplayer.demo/com.google.android.exoplayer.demo.PlayerActivity})
09-17 13:30:05.810  23430-23430/? E/EventLogger﹕ playerFailed [5.70]
    com.google.android.exoplayer.ExoPlaybackException: java.io.EOFException
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:146)
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:137)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:277)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:199)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:87)
            at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114)
            at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by ojw28** [comment]
The end of the chunk is probably not clipped correctly to a chunk boundary. Can you send a link to olly.exoplayer@gmail.com? Thanks.

**Comment by pernilla** [comment]
I've sent the link to you. Thanks.

**Comment by ojw28** [comment]
Right. As you noted via email, this is because we don't support mp3 media segments in HLS at the moment (although we do support mp3 tracks within MPEG-2 TS media segments).

Fortunately, it looks easy to add support by simply hooking into the existing Mp3Extractor. I'll push a change this week.

**Comment by pernilla** [comment]
Awesome! As soon as you do we'll have a look at it! Thanks.

/Pernilla

**Comment by ojw28** [comment]
Now supported on dev.
