### ISSUE TITLE
Unable to play Ads at 35 minutes and 47 seconds and above

### ISSUE THREAD

**Issue by chladto1** [google/ExoPlayer#8067]
### Issue description
Problem is in _ImaAdsLoader_ at line 1541. When play an Ad at 35 minutes and 47 seconds and above, value _adPodTimeUs_ is always 2147483647 (int max).

### Reproduction steps
Play an Ad at 40 or 50 minutes.

### Link to test content
Sorry, I do not have any public video content longer that 36 minutes. VMAP is below.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<vmap:VMAP xmlns:vmap="http://www.iab.net/videosuite/vmap" version="1.0">
    <vmap:AdBreak breakId="preroll" breakType="linear" timeOffset="start">
        <vmap:AdSource allowMultipleAds="false" followRedirects="true" id="preroll-ad-1">
            <vmap:AdTagURI templateType="vast3"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpodbumper&url=&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=preroll&pod=1&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&vrid=6496&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]></vmap:AdTagURI>
        </vmap:AdSource>
    </vmap:AdBreak>
    <vmap:AdBreak breakId="midroll-1" breakType="linear" timeOffset="00:10:00.000">
        <vmap:AdSource allowMultipleAds="false" followRedirects="true" id="midroll-1-pre-bumper">
            <vmap:AdTagURI templateType="vast3"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpodbumper&url=&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&cue=15000&vad_type=linear&vpos=midroll&pod=2&mridx=1&rmridx=1&bumper=before&min_ad_duration=0&max_ad_duration=10000&vrid=6496&sb=1&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]></vmap:AdTagURI>
        </vmap:AdSource>
    </vmap:AdBreak>
    <vmap:AdBreak breakId="midroll-2" breakType="linear" timeOffset="00:20:00.000">
        <vmap:AdSource allowMultipleAds="false" followRedirects="true" id="midroll-1-ad-1">
            <vmap:AdTagURI templateType="vast3"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpodbumper&url=&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&cue=15000&vad_type=linear&vpos=midroll&pod=2&mridx=1&rmridx=1&ppos=1&min_ad_duration=0&max_ad_duration=30000&vrid=6496&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]></vmap:AdTagURI>
        </vmap:AdSource>
    </vmap:AdBreak>
    <vmap:AdBreak breakId="midroll-3" breakType="linear" timeOffset="00:30:00.000">
        <vmap:AdSource allowMultipleAds="false" followRedirects="true" id="midroll-1-ad-2">
            <vmap:AdTagURI templateType="vast3"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpodbumper&url=&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&cue=15000&vad_type=linear&vpos=midroll&pod=2&mridx=1&rmridx=1&ppos=2&min_ad_duration=0&max_ad_duration=30000&vrid=6496&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]></vmap:AdTagURI>
        </vmap:AdSource>
    </vmap:AdBreak>
    <vmap:AdBreak breakId="midroll-4" breakType="linear" timeOffset="00:40:00.000">
        <vmap:AdSource allowMultipleAds="false" followRedirects="true" id="midroll-1-ad-3">
            <vmap:AdTagURI templateType="vast3"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpodbumper&url=&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&cue=15000&vad_type=linear&vpos=midroll&pod=2&mridx=1&rmridx=1&ppos=3&lip=true&min_ad_duration=0&max_ad_duration=30000&vrid=6496&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]></vmap:AdTagURI>
        </vmap:AdSource>
    </vmap:AdBreak>
    <vmap:AdBreak breakId="midroll-5" breakType="linear" timeOffset="00:50:00.000">
        <vmap:AdSource allowMultipleAds="false" followRedirects="true" id="midroll-1-post-bumper">
            <vmap:AdTagURI templateType="vast3"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpodbumper&url=&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&cue=15000&vad_type=linear&vpos=midroll&pod=2&mridx=1&rmridx=1&bumper=after&min_ad_duration=0&max_ad_duration=10000&vrid=6496&sb=1&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]></vmap:AdTagURI>
        </vmap:AdSource>
    </vmap:AdBreak>
    <vmap:AdBreak breakId="postroll" breakType="linear" timeOffset="end">
        <vmap:AdSource allowMultipleAds="false" followRedirects="true" id="postroll-pre-bumper">
            <vmap:AdTagURI templateType="vast3"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpodbumper&url=&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=postroll&pod=3&bumper=before&min_ad_duration=0&max_ad_duration=10000&vrid=6496&sb=1&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]></vmap:AdTagURI>
        </vmap:AdSource>
    </vmap:AdBreak>
</vmap:VMAP>
```

### A full bug report captured from the device
```
2020-10-12 13:14:36.868 4073-4073/com.google.android.exoplayer2.demo E/ImaAdsLoader: Internal error in loadAd
      java.lang.IllegalStateException: Failed to find cue point
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.getAdGroupIndexForCuePointTimeSeconds(ImaAdsLoader.java:1549)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.getAdGroupIndexForAdPod(ImaAdsLoader.java:1517)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.loadAdInternal(ImaAdsLoader.java:1229)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.access$2100(ImaAdsLoader.java:103)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader$ComponentListener.loadAd(ImaAdsLoader.java:1794)
        at com.google.ads.interactivemedia.v3.internal.akp.a(IMASDK:25)
        at com.google.ads.interactivemedia.v3.internal.akl.a(IMASDK:167)
        at com.google.ads.interactivemedia.v3.internal.akl.a(IMASDK:159)
        at com.google.ads.interactivemedia.v3.internal.ako.b(IMASDK:20)
        at com.google.ads.interactivemedia.v3.internal.akm.shouldOverrideUrlLoading(IMASDK:6)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle.aab-stable-1:16)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:197)
        at android.app.ActivityThread.main(ActivityThread.java:8125)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

### Version of ExoPlayer being used
2.12.0

### Device(s) and version(s) of Android being used
Device independent.

**Comment by marcbaechinger** [comment]
Thanks for reporting. We look into this.
