### ISSUE TITLE
NullPointerException in ExoPlayer

### ISSUE THREAD

**Issue by sapanda** [google/ExoPlayer#810]
Hi All,

I keep getting the following NullPointer exception with a 5mbps 1080p HLS stream from a live encoder. I'm on the latest version too (r1.4.2). Any idea what might be going wrong? Any additional data I can provide you guys to investigate the issue? (I can provide a stream URL privately - it's from our client so I can't share publicly)

```
com.google.android.exoplayer.ExoPlaybackException: java.lang.NullPointerException
  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:238)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at android.os.Looper.loop(Looper.java:146)
  at android.os.HandlerThread.run(HandlerThread.java:61)
  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
Caused by: java.lang.NullPointerException
  at com.google.android.exoplayer.extractor.DefaultTrackOutput.configureSpliceTo(DefaultTrackOutput.java:189)
  at com.google.android.exoplayer.hls.HlsExtractorWrapper.configureSpliceTo(HlsExtractorWrapper.java:144)
  at com.google.android.exoplayer.hls.HlsSampleSource.readData(HlsSampleSource.java:277)
  at com.google.android.exoplayer.metadata.MetadataTrackRenderer.doSomeWork(MetadataTrackRenderer.java:131)
  at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
```

**Comment by ojw28** [comment]
It looks most likely that some of the variants are defining a different number of media tracks than other variants. ExoPlayer doesn't handle this case. If you provide the URL to olly.exoplayer@gmail.com we can confirm.

**Comment by sapanda** [comment]
Sorry, unfortunately we only had the encoder for a few hours. But we'll be getting it again in two weeks. Will provide you with the stream when we do.
