### ISSUE TITLE
SampleQueueMappingException for specific hls videos

### ISSUE THREAD

**Issue by FortunaRegem** [google/ExoPlayer#8101]
I'm having a problem with playing some of my hls videos with the exo player.
Im getting the following error:

```
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1095)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:974)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

Video url for example: https://cdn.jwplayer.com/manifests/wyhexK3K.m3u8

What i am doing is: creating first a cache for that video and than getting it with the following functions:
```
    fun createVideoCache(videoUrl: String) {
        val videoUri = Uri.parse(videoUrl)
        val dataSpec = DataSpec(videoUri)
        val defaultCacheKeyFactory = CacheUtil.DEFAULT_CACHE_KEY_FACTORY
        val progressListener = CacheUtil.ProgressListener { requestLength, bytesCached, newBytesCached ->
                val downloadPercentage: Double = (bytesCached * 100.0 / requestLength)
            }
        val dataSource: DataSource = HlsDataSourceFactory {
            DefaultDataSourceFactory(
                context,
                Util.getUserAgent(context, "Sportyn")
            ).createDataSource()
        }.createDataSource(C.DATA_TYPE_MANIFEST)
        try {
            cacheVideo(dataSpec, defaultCacheKeyFactory, dataSource, progressListener)
        } catch(e: Exception) {}
    }

    fun getVideo(videoUrl: String): HlsMediaSource {
        val videoUri = Uri.parse(videoUrl)
        return HlsMediaSource.Factory(cacheDataSourceFactory!!).setAllowChunklessPreparation(true).createMediaSource(videoUri)
    }
```

Where cacheDataSourceFactory is : 
```
cacheDataSourceFactory = CacheDataSourceFactory(
                simpleCache,
                DefaultHttpDataSourceFactory(context.let {
                    Util.getUserAgent(it, "String")
                }),
                CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR
            )
```

The player init looks like this:
```
    selectedPlayer = context.let {
        SimpleExoPlayer.Builder(it).setTrackSelector(trackSelector).build()
      }
    selectedPlayer?.repeatMode = Player.REPEAT_MODE_ONE
    selectedPlayer?.addListener(this)
    selectedPlayer?.addVideoListener(this)
    exoPlayerView.player = selectedPlayer
```

Am I missing something?

Thank you in advance

**Comment by andrewlewis** [comment]
The stack trace refers to `ProgressiveMediaPeriod` but the code is using `HlsMediaSource`, which looks wrong. Could you double check what the stack trace is?

The provided example URL plays fine for me in the ExoPlayer demo app.

**Comment by FortunaRegem** [comment]
Sorry, thats my fault, I was out of ideas so I tried with this:
```
ProgressiveMediaSource.Factory(VideoCacheStore.cacheDataSourceFactory).createMediaSource(videoUri)
```

But same error happens with both

**Comment by AquilesCanta** [comment]
The media you are trying to play is HLS. But the error you show is from ProgressiveMediaSource (as @andrewlewis points out). You just need to use HlsMediaSource instead. You **cannot** get the posted stacktrace if you are using HlsMediaSource.

**Comment by FortunaRegem** [comment]
I get the same error either way
Here is the stack trace with HlsMediaSource
```
com.google.android.exoplayer2.source.hls.SampleQueueMappingException: Unable to bind a sample queue to TrackGroup with mime type audio/mp4a-latm.
        at com.google.android.exoplayer2.source.hls.HlsSampleStream.maybeThrowError(HlsSampleStream.java:64)
        at com.google.android.exoplayer2.BaseRenderer.maybeThrowStreamError(BaseRenderer.java:143)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:615)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by AquilesCanta** [comment]
I had a quick look at the issue: The problem is that the master playlist says that your stream contains audio (see `CODECS="mp4a.40.2,avc1.77.30"` but the transport stream files don't contain audio:

```
General
ID                                       : 1 (0x1)
Complete name                            : wyhexK3K-33111895.mp4-2.ts
Format                                   : MPEG-TS
File size                                : 174 KiB
Duration                                 : 2 s 233 ms
Overall bit rate                         : 637 kb/s

Video
ID                                       : 256 (0x100)
...
```

So when ExoPlayer tries to map the audio renderer to the track, it fails. I can think of two ways for you to fix this:
- Remove the audio codecs from the master playlist.
- Use traditional preparation instead of chunkless. That is, remove `setAllowChunklessPreparation(true)`. Note that this will mean that playback will be a bit slower to start.
