### ISSUE TITLE
Crash while playing HLS live content (probably a playlist update retry process)

### ISSUE THREAD

**Issue by Our-colibri** [google/ExoPlayer#8117]
In exoplayer 2.10.6

I am having trouble with a crashing phenomenon while playing live content on HLS.

It was crashing in the part of the playlist where I was getting an I/O (HTTP) error and retrying to get the playlist update.

I suspect the crash is caused by the fact that the process of updating currentTask is not thread-safe.

I think that if <Loader#startLoading> is called between <Loader.LoadTask#finish> and <Loader.LoadTask#start> in <Loader.LoadTask#handleMessage>, it will be like this.

Is this working as designed?

Logging of crashes:
```
Fatal Exception: java.lang.IllegalStateException
       at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.start(Loader.java:351)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:481)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6758)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ojw28** [comment]
For that stack trace to happen, I think `Loader.startLoading` must have been called on the application's main thread. This should never happen, since loads are only expected to be started by the player's own internal thread(s).

This suggests to me that your application code might be calling something directly that it shouldn't be calling. Perhaps your application code is calling `prepareSource` on a `MediaSource` instance, for example. Could you take a look? If that's not the case, I think you'll need to figure out how `Laoder.startLoading` ends up being called on the application's main thread. If you can point to where this happens in the ExoPlayer library, then that would be something we could investigate and fix.

**Comment by Our-colibri** [comment]
Thanks for the reply.

I was creating a separate thread in MyMediaSource#prepareSource to call the actual MediaSource#prepare as you wrote.
(The reason was to recreate and replace the MediaSource as needed in the Prepare phase.)

I didn't understand it well enough, so your reply was a great help.
Thanks so much.
