### ISSUE TITLE
exoplayer 2.12.1  Unexpected error loading stream

### ISSUE THREAD

**Issue by emadPirayesh** [google/ExoPlayer#8128]
when set minifyEnabled=true in gradle this crash occur in play mp4 stream
info
used exoplayer 2.12.1
android 9 
device redmi note 8

```
1603879301.094 16034-16221/pr.x.xE/LoadTask: Unexpected error loading stream
      java.lang.AbstractMethodError: abstract method "java.lang.Object com.google.a.a.e.a(java.lang.Object)"
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:120)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:419)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:381)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:372)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:195)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
1603879301.096 16034-16207/pr.gahvare.gahvare E/AndroidRuntime: FATAL EXCEPTION: ExoPlayer:Playback
    Process: pr.gahvare.gahvare, PID: 16034
    java.lang.AbstractMethodError: abstract method "java.lang.Object com.google.a.a.e.a(java.lang.Object)"
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:120)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:419)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:381)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:372)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:195)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
1603879301.097 16034-16221/pr.gahvare.gahvare E/AndroidRuntime: FATAL EXCEPTION: Loader:ProgressiveMediaPeriod
    Process: pr.gahvare.gahvare, PID: 16034
    java.lang.AbstractMethodError: abstract method "java.lang.Object com.google.a.a.e.a(java.lang.Object)"
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:120)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:419)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:381)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:372)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:195)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by icbaker** [comment]
I'm not able to reproduce this problem.

I used the demo app and set `minifiyEnabled true` in its [build.gradle](https://github.com/google/ExoPlayer/blob/r2.12.1/demos/main/build.gradle), then played Misc > Dizzy (MP4). It played fine.

Can you reproduce in the demo app using your media? If so, we'll likely need access to the media to investigate further. Please either upload it here or send to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" (where "#1234" should be replaced with this issue number). Please also update this issue to indicate you’ve done this.

If the issue doesn't reproduce in the demo app then please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com (same subject as above). Please also update this issue to indicate you’ve done this.

**Comment by emadPirayesh** [comment]
below link is demo source code  for reproduce problem.
https://mega.nz/file/nJkARAgQ#XRdtQkc50p_byde8K_KjmxrztXkjHnaTmICjajQOck8

**Comment by emadPirayesh** [comment]
after update classpath com.android.tools.build:gradle:3.2.1  to  classpath 'com.android.tools.build:gradle:3.5.4'  this issue solve

**Comment by icbaker** [comment]
Glad you managed to fix the problem!

The stack trace you provided suggests the redacted method causing the AbstractMethodError (`com.google.a.a.e.a(java.lang.Object)`) is Guava's `com.google.common.base.Function.apply(Object)`:
https://github.com/google/ExoPlayer/blob/be13805ce4e22231ae728d2710a2b8751ee5ad7c/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mp4/AtomParsers.java#L120

(mainly including this info so if anyone else is searching through the issues they can see that upgrading Gradle might help for this problem)

**Comment by hejianboo** [comment]
I fixed this problem from this https://github.com/google/guava/issues/3227. 
Add this line in proguard config file
`-keepnames class com.google.common.** { *; }`
