### ISSUE TITLE
Exoplayer Builder gives error when open a video again. 

### ISSUE THREAD

**Issue by CanerGures** [google/ExoPlayer#8129]
I have implemented the exoplayer builder according to documents. But when I play the video and back press and open again it gives the following error.

```
2020-10-28 13:21:17.618 1347-1347/com.example.exoplayer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.exoplayer, PID: 1347
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/source/ads/AdsMediaSource$MediaSourceFactory;
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at com.google.android.exoplayer2.source.DefaultMediaSourceFactory.loadDelegates(DefaultMediaSourceFactory.java:321)
        at com.google.android.exoplayer2.source.DefaultMediaSourceFactory.<init>(DefaultMediaSourceFactory.java:152)
        at com.google.android.exoplayer2.source.DefaultMediaSourceFactory.<init>(DefaultMediaSourceFactory.java:127)
        at com.google.android.exoplayer2.SimpleExoPlayer$Builder.<init>(SimpleExoPlayer.java:195)
        at com.google.android.exoplayer2.SimpleExoPlayer$Builder.<init>(SimpleExoPlayer.java:153)
        at com.example.exoplayer.MainActivity.initializePlayer(MainActivity.kt:277)
        at com.example.exoplayer.MainActivity.onStart(MainActivity.kt:73)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333)
        at android.app.Activity.performStart(Activity.java:6992)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.source.ads.AdsMediaSource$MediaSourceFactory" on path: DexPathList[[zip file "/data/app/com.example.exoplayer-gwKmVAVWr-XjBupFUIJMdw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.exoplayer-gwKmVAVWr-XjBupFUIJMdw==/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
```

my code can be seen at [question](https://stackoverflow.com/questions/64569123/exoplayer-builder-gives-error-when-back-pressed-and-open-video-again)

Let me explain the problem again. I have recyclerview and items in it. When the user clicks one item it leads to an another activity to open the player. When the user clicks back button and open a video(same or different), it gives the error above.

also the project is [here](https://github.com/CanerGures/ExoPlayer-Application) for who wants to check whole project.
 
I want to be clear on that again I followed the instructions on the document and several website. What is the problem here I really couldn't figure it out.

**Comment by ojw28** [comment]
One thing I noticed is that you're pulling in ExoPlayer modules that use different versions.
```
    implementation 'com.google.android.exoplayer:exoplayer:2.10.1'
    implementation 'com.google.android.exoplayer:exoplayer-core:2.12.0'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.12.0'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.12.0'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.10.1'
```
Failure to find the class may be caused by mixing the versions, so as a first attempt at fixing this I'd suggest you switch all of these dependencies to using a single, consistent version (probably `2.12.1`). If that doesn't work, it would be helpful if you could provide clear reproduction steps for us to try. I did try running your project, but the app just shows me a single "API POST" button that doesn't appear to do anything when I press it.

As an aside, it's also strange that you're depending on both the full library dependency and the individual modular dependencies. You should only need to use one or the other; not both. See the [getting started](https://exoplayer.dev/hello-world.html) page for more detail.

**Comment by CanerGures** [comment]
Hey, I have just tried the version that you mentioned on all dependencies and it worked. Also, there should be a recycler view with items on the main screen, I don't know why you can't see them. This is the picture of the app [here](https://imgur.com/gallery/9AMT0AR).Thanks for the reply and solution. It helped so much. Thank you again.
