### ISSUE TITLE
How to support L1 widevine drm using exoplayer

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#8151]
### [REQUIRED] How to play L1 widevine drm using Exoplayer
We are seeing lot of drm playback failures on devices where L1 Widevine is supported.

On such devices, we see DRM session throwing below error. We are using Exoplayer v2.11.8

```
 22174 22867 E ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(3, null, null, video/avc, avc1.64001f, 1200000, null, [1280, 720, 25.0], [-1, -1]), rendererSupport=YES
10-29 13:48:30.182 22174 22867 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
10-29 13:48:30.182 22174 22867 E ExoPlayerImplInternal:       at c.j.b.c.s.a(BaseRenderer.java:15)
10-29 13:48:30.182 22174 22867 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.r(MediaCodecRenderer.java:60)
10-29 13:48:30.182 22174 22867 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.a(MediaCodecRenderer.java:27)
10-29 13:48:30.182 22174 22867 E ExoPlayerImplInternal:       at c.j.b.c.c0.b(ExoPlayerImplInternal.java:138)
10-29 13:48:30.182 22174 22867 E ExoPlayerImplInternal:       at c.j.b.c.c0.handleMessage(ExoPlayerImplInternal.java:18)
10-29 13:48:30.182 22174 22867 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:103)
10-29 13:48:30.182 22174 22867 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:224)
10-29 13:48:30.182 22174 22867 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
10-29 13:48:30.182 22174 22867 E ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
10-29 13:48:30.182 22174 22867 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.DefaultDrmSession.a(DefaultDrmSession.java:31)
```

Please let us know the following

1. is this a device specific issue?
2. How to handle Widevine L1 Drm playback? Right now we are just calling the below code to pass drm license

_setDrmSessionManager(license_url, "widevine");_

Do we need to detect L1 device and so something extra?

Thanks in advance.

**Comment by krackjack234** [comment]
More logs if it helps

```
11-03 20:01:38.748  3709  3709 E EventLogger: internalError [eventTime=9.04, mediaPos=0.00, window=0, period=0, drmSessionManagerError
11-03 20:01:38.748  3709  3709 E EventLogger:   com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
11-03 20:01:38.748  3709  3709 E EventLogger:       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
11-03 20:01:38.748  3709  3709 E EventLogger:       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
11-03 20:01:38.748  3709  3709 E EventLogger:       at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)
11-03 20:01:38.748  3709  3709 E EventLogger:       at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)
11-03 20:01:38.748  3709  3709 E EventLogger:       at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:160)
11-03 20:01:38.748  3709  3709 E EventLogger:       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:166)
11-03 20:01:38.748  3709  3709 E EventLogger:       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:136)
11-03 20:01:38.748  3709  3709 E EventLogger:       at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:551)
11-03 20:01:38.748  3709  3709 E EventLogger:       at android.os.Handler.dispatchMessage(Handler.java:107)
11-03 20:01:38.748  3709  3709 E EventLogger:       at android.os.Looper.loop(Looper.java:224)
11-03 20:01:38.748  3709  3709 E EventLogger:       at android.os.HandlerThread.run(HandlerThread.java:67)
11-03 20:01:38.748  3709  3709 E EventLogger: ]
11-03 20:01:38.751  1167  2417 I MiuiNetworkPolicy: updateUidState uid = 99366, uidState = 16
11-03 20:01:38.751  1167  2417 I MiuiNetworkPolicy: updateUidState uid = 9801, uidState = 16
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(3, null, null, video/avc, avc1.64001f, 1200000, null, [1280, 720, 25.0], [-1, -1]), rendererSupport=YES
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.shouldWaitForKeys(MediaCodecRenderer.java:1215)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1161)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:722)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:103)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:224)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:486)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:481)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:444)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:50)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:519)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:107)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       ... 2 more
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:160)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:166)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:136)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:551)
11-03 20:01:38.757  3709  4484 E ExoPlayerImplInternal:       ... 3 more
```

**Comment by lcf87** [comment]
Could you check the log from you licensing server? The server is returning 403 on your connection, it's unclear from the Exoplayer side as to why.

**Comment by krackjack234** [comment]
Ok strange thing is this is working on all phones which has widevine L3 and some phones which has widevine L1.
But we will again check from license server side.
