### ISSUE TITLE
Playback stuck buffering and not loading

### ISSUE THREAD

**Issue by idokit365** [google/ExoPlayer#8166]
Reproduct steps:
1. load a large file (more or less 6GB).
2. this error will producting after seeking several times.

The error log:

2020-11-05 19:52:33.283 21455-26731/? W/DefaultLoadControl: Target buffer size reached with less than 500ms of buffered media data.
2020-11-05 19:52:33.287 21455-26731/? W/DefaultLoadControl: Target buffer size reached with less than 500ms of buffered media data.
2020-11-05 19:52:33.288 21455-26731/? E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.beef.mediakit.v1.o0.handleMessage(ExoPlayerImplInternal.java:31)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:230)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException: Playback stuck buffering and not loading
        at com.beef.mediakit.v1.o0.a(ExoPlayerImplInternal.java:259)
        at com.beef.mediakit.v1.o0.handleMessage(ExoPlayerImplInternal.java:25)
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:230) 
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by idokit365** [comment]
I use exoplayer demo to play large video, the same issue happened.

**Comment by lcf87** [comment]
Could you fill out the issue template and provide us with the media that triggered this problem to help us help you better, thanks!
