### ISSUE TITLE
Failed to allocate output port buffers after port reconfiguration

### ISSUE THREAD

**Issue by i-nasser** [google/ExoPlayer#8204]
### [REQUIRED] Issue description
I created exoplayer one time by invoking this method getSourceMediaPlayerInternal()  when ended video I need to go to next random video. When ended video into exoplayer I have Invoked playVideoFromMediaSource()
The video works for a time and after that this error appears and  the screen exoplayer becomes black and the video stops working.

Code:
-----------------------

    public static SimpleExoPlayer getSourceMediaPlayerInternal(String url, Context context, long seekTime) {

        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

        SimpleExoPlayer PlayerInternal = ExoPlayerFactory.newSimpleInstance(context, trackSelector);
        MediaSource audioSource = new ExtractorMediaSource(Uri.parse(url), new CacheDataSourceFactory(context, 100 * 1024 * 1024, 5 * 1024 * 1024), new DefaultExtractorsFactory(), null, null);
        PlayerInternal.prepare(audioSource);
        PlayerInternal.seekTo(seekTime);
        PlayerInternal.setPlayWhenReady(true);

        return PlayerInternal;
    }

----------------------------------------------------------------------

    static MediaSource audioSource = null;
    public static void playVideoFromMediaSource(SimpleExoPlayer PlayerInternal, PlayerView smallVideoView, long seekTime, Context context) {

        audioSource = new ExtractorMediaSource(Uri.parse(Helper.BASE_MEDIA_URL + SharedHelper.getArrayListSponsorAds(context).get(MainActivity.countSponsorAds).getVideoLink()), new CacheDataSourceFactory(context, 100 * 1024 * 1024, 5 * 1024 * 1024), new DefaultExtractorsFactory(), null, null);

        PlayerInternal.prepare(audioSource);
        PlayerInternal.seekTo(seekTime);
        PlayerInternal.setPlayWhenReady(true);
        smallVideoView.setPlayer(PlayerInternal);

    }

When reporting a bug:
-----------------------
```
E/ACodec: Failed to allocate output port buffers after port reconfiguration: (-12)
    signalError(omxError 0x80001001, internalError -12)
E/MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 6
E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1437)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:653)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal: Disable failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:1948)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:702)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.flushOrReleaseCodec(MediaCodecVideoRenderer.java:606)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:580)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:451)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:158)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1088)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:851)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:399)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal: Reset failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:1901)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:609)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:596)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onReset(MediaCodecRenderer.java:587)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onReset(MediaCodecVideoRenderer.java:460)
        at com.google.android.exoplayer2.BaseRenderer.reset(BaseRenderer.java:164)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:860)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:399)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```
I have tryed to chnage the code to this shape And have the same issue.

```
static MediaSource audioSource = null;
    public static void playVideoFromMediaSource(SimpleExoPlayer PlayerInternal, PlayerView smallVideoView, long seekTime, Context context) {
        
        if (audioSource != null) {
            ((ExtractorMediaSource) audioSource).releaseSourceInternal();
            audioSource = new ExtractorMediaSource(Uri.parse(Helper.BASE_MEDIA_URL + SharedHelper.getArrayListSponsorAds(context).get(MainActivity.countSponsorAds).getVideoLink()), new CacheDataSourceFactory(context, 100 * 1024 * 1024, 5 * 1024 * 1024), new DefaultExtractorsFactory(), null, null);
        } else {
            audioSource = new ExtractorMediaSource(Uri.parse(Helper.BASE_MEDIA_URL + SharedHelper.getArrayListSponsorAds(context).get(MainActivity.countSponsorAds).getVideoLink()), new CacheDataSourceFactory(context, 100 * 1024 * 1024, 5 * 1024 * 1024), new DefaultExtractorsFactory(), null, null);
        }

        PlayerInternal.prepare(audioSource);
        PlayerInternal.seekTo(seekTime);
        PlayerInternal.setPlayWhenReady(true);
        smallVideoView.setPlayer(PlayerInternal);
    }

```

### [REQUIRED] Version of ExoPlayer being used
v2.10.4

**Comment by marcbaechinger** [comment]
The exception is raised by the Android media framework that uses devices specific codecs. It's strange that you are saying it works once but not several times. Are you seeing this problems on different devices/emulators or just on a specific device?

Difficult to say something with the information available. You are saying it works fine at the first try and then fails. The code also uses a `CacheDataSourceFactory` with a constructor I can't find. Can you make sure the caching works (or better, can you try without caching to make sure that the player gets the same data the first and the second time)?

If you can't figure something out, can you please create a bug report `adb bugreport` and upload it here?
