### ISSUE TITLE
AnalyticsListener crashes

### ISSUE THREAD

**Issue by assaadroid** [google/ExoPlayer#8224]
### [REQUIRED] Issue description
java.lang.AbstractMethodError

### [REQUIRED] Reproduction steps

this issue happens only if I create a build with minifyEnabled false, otherwise if I set to true it works normally.

android gradle plugin Version : 4.1.1
gradle version: 6.5

### [REQUIRED] A full bug report captured from the device
Caused by: java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.analytics.AnalyticsListener.onMediaItemTransition(com.google.android.exoplayer2.analytics.AnalyticsListener$EventTime, com.google.android.exoplayer2.MediaItem, int)"
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.onMediaItemTransition(AnalyticsCollector.java:452)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$2$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:1420)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$06WAXA7vL-SBfQvmAx45uxQjmso.invokeListener(Unknown Source:2)
        at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:279)
        at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:1496)
        at com.google.android.exoplayer2.ExoPlayerImpl.access$100(ExoPlayerImpl.java:56)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:1418)
        at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1326)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:954)
        at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSourcesInternal(ExoPlayerImpl.java:1062)
        at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSources(ExoPlayerImpl.java:384)
        at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSources(ExoPlayerImpl.java:379)
        at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSource(ExoPlayerImpl.java:363)
        at com.google.android.exoplayer2.SimpleExoPlayer.setMediaSource(SimpleExoPlayer.java:1499)

### [REQUIRED] Version of ExoPlayer being used
version 2.12.1

### [REQUIRED] Device(s) and version(s) of Android being used
all devices

**Comment by icbaker** [comment]
Errors like this are generally related to Java 8 support (the method it's complaining about is marked `default` on the `AnalyticsListener` interface, which is a language feature added in Java 8).

[Previous issues](https://github.com/google/ExoPlayer/issues?q=abstractmethoderror+) have various suggestions to tweak your gradle config:

https://github.com/google/ExoPlayer/issues/7349#issuecomment-626103954:
```
android.enableDexingArtifactTransform=false
```

https://github.com/google/ExoPlayer/issues/6801#issuecomment-569933539:
```
compileOptions {
  targetCompatibility JavaVersion.VERSION_1_8
}
```

There are probably more ideas if you dig through the other issues in that search.

**Comment by assaadroid** [comment]
10x, it was fixed by adding android.enableDexingArtifactTransform=false
