### ISSUE TITLE
Certain devices crash with an SQLiteException when attempting to create cache 

### ISSUE THREAD

**Issue by frushlabo** [google/ExoPlayer#8251]
### [REQUIRED] Issue description
Certain devices crash with an SQLiteException when attempting to create cache 

### [REQUIRED] Reproduction steps
Create a media source with cache using CacheDataSourceFactory()

### [REQUIRED] Link to test content
Any content 

### [REQUIRED] A full bug report captured from the device
Currently attempting to acquire bug report however do you not have a physical device available currently - apologies, will update when this is available 

```
Fatal Exception: android.database.sqlite.SQLiteException: not an error (Sqlite code 0 SQLITE_OK), (OS error - 2:No such file or directory)
       at android.database.sqlite.SQLiteConnection.nativeRegisterLocalizedCollators(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:461)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:241)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:211)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:559)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:222)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:211)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:947)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:926)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:790)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:779)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:403)
       at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:356)
       at com.google.android.exoplayer2.upstream.cache.CachedContentIndex$DatabaseStorage.exists(CachedContentIndex.java:776)
       at com.google.android.exoplayer2.upstream.cache.CachedContentIndex.initialize(CachedContentIndex.java:192)
       at com.google.android.exoplayer2.upstream.cache.SimpleCache.initialize(SimpleCache.java:548)
       at com.google.android.exoplayer2.upstream.cache.SimpleCache.access$000(SimpleCache.java:50)
       at com.google.android.exoplayer2.upstream.cache.SimpleCache$1.run(SimpleCache.java:268)

```
### [REQUIRED] Version of ExoPlayer being used
2.11.5

### [REQUIRED] Device(s) and version(s) of Android being used
Reported on Android versions 7 - 10
Huawei: nova 5T / p30 / p30 lite
Samsung: Galaxy A7
LGE: Stylo 5 / K51

**Comment by marcbaechinger** [comment]
Yes, please upload a bug report if you have one. The stack trace shows the failure happens in `setLocaleFromConfiguration` and `nativeRegisterLocalizedCollators`. Not sure if this is really something to cause problems, but it may be dependent with some locales or changes of that. So when you are seeing the error on a device it would be interesting if it is really 'device specific' as opposed to 'locale specific'. I think it would not surprise me if you find it is working on some of the devices you mention above as well. A bug report would probably help us seeing what localizations the problematic devices have.

Besides: Are you using a specific DatabaseProvider that you pass to the constructor of the `SimpleCache`?

**Comment by marcbaechinger** [comment]
I think I was able to reproduce this. As I was guessing it has to do with a locale that is set wrongly manually by my code.

I flashed a Pixel device with Android Oreo and added the following in the 'Application' class that is executed right at the start of the ExoPlayer demo application:

```
Locale locale = new Locale("русский");
Locale.setDefault(locale);
Configuration config = new Configuration();
config.locale = locale;
getBaseContext().getResources().updateConfiguration(config, null);
```

When I then try to install the app it fails with the following exception that is exactly what you reported:

```
2020-11-24 23:12:57.075 16425-16460/com.google.android.exoplayer2.demo E/SQLiteDatabase: Failed to open database '/data/user/0/com.google.android.exoplayer2.demo/databases/exoplayer_internal.db'.
    android.database.sqlite.SQLiteException: not an error (code 0)
        at android.database.sqlite.SQLiteConnection.nativeRegisterLocalizedCollators(Native Method)
        at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:362)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:219)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:493)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:200)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:192)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:864)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:849)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:724)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:295)
        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:262)
        at com.google.android.exoplayer2.upstream.cache.CachedContentIndex$DatabaseStorage.exists(CachedContentIndex.java:799)
        at com.google.android.exoplayer2.upstream.cache.CachedContentIndex.initialize(CachedContentIndex.java:201)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.initialize(SimpleCache.java:580)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.access$000(SimpleCache.java:49)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache$1.run(SimpleCache.java:268)
```

This does not happen without the code that programmatically set the locale with the cyrillic letters for 'Russian' (русский). It also does not happen when I switch the device to the Russian language in the Android settings only. When I do the same on Android 10/11 it works fine. I see a stack trace there as well but it does not crash.

From this I actually think this is an app problem rather than a problem with the ExoPlayer library or the SQLite version on an OS version.

I wonder whether your app has some functionality to change the language and does something similar like the code snippet I use above. Probably constructing a Locale with a language that is not ASCII or the like. Can you check whether this is the case? I see the same when I run it on an emulator with API 25. Can I ask you to run your app on the emulator with API 25 for testing?

**Comment by marcbaechinger** [comment]
Closing due to inactivity.
