### ISSUE TITLE
ExoPlayerImplInternal: Playback error

### ISSUE THREAD

**Issue by sandarshnaroju** [google/ExoPlayer#8264]
### [REQUIRED] Searched documentation and issues
Searched here and in Stackoverflow

### [REQUIRED] Question
In my project I am using Exoplayer to play DRM protected channel streams, I am facing problems in playing video. Here is the error:

```
2020-11-22 21:26:17.258 26378-26429/com.example.videoplayer E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:336)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:193)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:126)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

```

### A full bug report captured from the device

```
2020-11-22 21:25:50.027 26378-26378/? I/ple.videoplaye: Late-enabling -Xcheck:jni
2020-11-22 21:25:50.064 26378-26378/? W/ple.videoplaye: miui_dex2oat: DeoptimizeBootImage: patch entry points of methods in boot image to interpreter bridge
2020-11-22 21:25:50.293 26378-26378/com.example.videoplayer I/ple.videoplaye: The ClassLoaderContext is a special shared library.
2020-11-22 21:25:50.293 26378-26378/com.example.videoplayer W/ple.videoplaye: miui_dex2oat:　OatFile: /system/framework/oat/arm64/org.apache.http.legacy.boot.odex Compiler-Filter = speed-profile
2020-11-22 21:25:50.295 26378-26378/com.example.videoplayer W/ple.videoplaye: miui_dex2oat: oat file of /data/app/com.example.videoplayer-ooaf9Gh9rBIYaBhcLBDCgA==/base.apk is not exists
2020-11-22 21:25:50.557 26378-26378/com.example.videoplayer W/ple.videoplaye: miui_dex2oat: /data/app/com.example.videoplayer-ooaf9Gh9rBIYaBhcLBDCgA==/base.apk: Fall back to running out of the original dex file.
2020-11-22 21:25:50.572 26378-26378/com.example.videoplayer I/Perf: Connecting to perf service.
2020-11-22 21:25:50.650 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden method Landroid/graphics/drawable/Drawable;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, linking)
2020-11-22 21:25:50.651 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)
2020-11-22 21:25:50.651 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)
2020-11-22 21:25:50.651 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
2020-11-22 21:25:50.651 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
2020-11-22 21:25:50.738 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
2020-11-22 21:25:50.740 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
2020-11-22 21:25:50.747 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden method Landroid/widget/TextView;->getTextDirectionHeuristic()Landroid/text/TextDirectionHeuristic; (light greylist, linking)
2020-11-22 21:25:50.789 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden method Landroid/text/SpannableStringInternal;->length()I (light greylist, linking)
2020-11-22 21:25:50.860 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden method Landroid/graphics/FontFamily;-><init>()V (light greylist, reflection)
2020-11-22 21:25:50.860 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden method Landroid/graphics/FontFamily;->addFontFromAssetManager(Landroid/content/res/AssetManager;Ljava/lang/String;IZIII[Landroid/graphics/fonts/FontVariationAxis;)Z (light greylist, reflection)
2020-11-22 21:25:50.860 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden method Landroid/graphics/FontFamily;->addFontFromBuffer(Ljava/nio/ByteBuffer;I[Landroid/graphics/fonts/FontVariationAxis;II)Z (light greylist, reflection)
2020-11-22 21:25:50.860 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden method Landroid/graphics/FontFamily;->freeze()Z (light greylist, reflection)
2020-11-22 21:25:50.860 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden method Landroid/graphics/FontFamily;->abortCreation()V (light greylist, reflection)
2020-11-22 21:25:50.861 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden method Landroid/graphics/Typeface;->createFromFamiliesWithDefault([Landroid/graphics/FontFamily;Ljava/lang/String;II)Landroid/graphics/Typeface; (light greylist, reflection)
2020-11-22 21:25:50.959 26378-26378/com.example.videoplayer W/ple.videoplaye: Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (light greylist, reflection)
2020-11-22 21:25:50.967 26378-26378/com.example.videoplayer I/ExoPlayerImpl: Init e8e523a [ExoPlayerLib/2.12.0] [violet, Redmi Note 7 Pro, Xiaomi, 28]
2020-11-22 21:25:50.981 26378-26378/com.example.videoplayer D/AudioManager: getStreamVolume isRestricted mode = 0
2020-11-22 21:25:51.047 26378-26431/com.example.videoplayer I/DpmTcmClient: RegisterTcmMonitor from: $Proxy0
2020-11-22 21:25:51.058 26378-26431/com.example.videoplayer D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-11-22 21:25:51.078 26378-26378/com.example.videoplayer W/Looper: Slow Looper main: Activity com.example.videoplayer/.MainActivity is 466ms late (wall=486ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.LaunchActivityItem] lifecycleRequest=android.app.servertransaction.ResumeActivityItem }) because of 1 msg, msg 1 took 467ms (late=1ms h=android.app.ActivityThread$H w=110)
2020-11-22 21:25:51.114 26378-26432/com.example.videoplayer I/Adreno: QUALCOMM build                   : 89f10b9, I3d0e3ac366
    Build Date                       : 12/25/18
    OpenGL ES Shader Compiler Version: EV031.25.14.03
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2020-11-22 21:25:51.114 26378-26432/com.example.videoplayer I/Adreno: Build Config                     : S P 6.0.9 AArch64
2020-11-22 21:25:51.117 26378-26432/com.example.videoplayer I/Adreno: PFP: 0x016ee177, ME: 0x00000000
2020-11-22 21:25:51.122 26378-26432/com.example.videoplayer I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2020-11-22 21:25:51.122 26378-26432/com.example.videoplayer I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-11-22 21:25:51.123 26378-26432/com.example.videoplayer I/OpenGLRenderer: Initialized EGL, version 1.4
2020-11-22 21:25:51.123 26378-26432/com.example.videoplayer D/OpenGLRenderer: Swap behavior 2
2020-11-22 21:25:51.216 26378-26432/com.example.videoplayer E/LB: fail to open file: No such file or directory
2020-11-22 21:25:51.358 26378-26429/com.example.videoplayer W/Utils: could not parse long range '427-372'
2020-11-22 21:25:51.360 26378-26429/com.example.videoplayer W/VideoCapabilities: Unsupported mime video/divx
2020-11-22 21:25:51.362 26378-26429/com.example.videoplayer W/VideoCapabilities: Unsupported mime video/divx4
2020-11-22 21:25:51.373 26378-26429/com.example.videoplayer W/VideoCapabilities: Unrecognized profile 4 for video/hevc
2020-11-22 21:25:51.373 26378-26429/com.example.videoplayer W/Utils: could not parse long range '310-287'
2020-11-22 21:25:51.373 26378-26429/com.example.videoplayer W/Utils: could not parse long range '320-220'
2020-11-22 21:25:51.375 26378-26429/com.example.videoplayer W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2020-11-22 21:25:51.377 26378-26429/com.example.videoplayer W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2020-11-22 21:25:51.391 26378-26429/com.example.videoplayer W/Utils: could not parse long range '322-206'
2020-11-22 21:25:51.403 26378-26429/com.example.videoplayer I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
2020-11-22 21:25:51.412 26378-26429/com.example.videoplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.1.4.L153, video/hevc] [OMX.qcom.video.decoder.hevc.secure, video/hevc] [violet, Redmi Note 7 Pro, Xiaomi, 28]
2020-11-22 21:25:51.412 26378-26429/com.example.videoplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.1.4.L153, video/hevc] [OMX.qcom.video.decoder.hevc.secure, video/hevc] [violet, Redmi Note 7 Pro, Xiaomi, 28]
2020-11-22 21:25:58.604 26378-26426/com.example.videoplayer I/ple.videoplaye: ProcessProfilingInfo new_methods=3558 is saved saved_to_disk=1 resolve_classes_delay=8000
2020-11-22 21:26:13.748 26378-26439/com.example.videoplayer W/ple.videoplaye: Long monitor contention with owner ExoPlayer:Playback (26429) at byte[] android.media.MediaDrm.openSession(int)(MediaDrm.java:-2) waiters=0 in boolean com.google.android.exoplayer2.source.SampleQueue.setUpstreamFormat(com.google.android.exoplayer2.Format) for 22.102s
2020-11-22 21:26:13.748 26378-26439/com.example.videoplayer W/ple.videoplaye: Current owner stack:
2020-11-22 21:26:13.748 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.drm.DrmSession$-CC.replaceSession(DrmSession.java:40)
2020-11-22 21:26:13.748 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.setSourceDrmSession(MediaCodecRenderer.java:1220)
2020-11-22 21:26:13.748 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1436)
2020-11-22 21:26:13.748 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:394)
2020-11-22 21:26:13.748 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:977)
2020-11-22 21:26:13.748 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:829)
2020-11-22 21:26:13.748 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at android.os.Handler.dispatchMessage(Handler.java:102)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at android.os.Looper.loop(Looper.java:201)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at android.os.HandlerThread.run(HandlerThread.java:65)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye: Contender stack:
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.source.SampleQueue.setUpstreamFormat(SampleQueue.java:-1)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.source.SampleQueue.format(SampleQueue.java:520)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.source.chunk.BundledChunkExtractor$BindingTrackOutput.format(BundledChunkExtractor.java:186)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor$TrackBundle.updateDrmInitData(FragmentedMp4Extractor.java:1611)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onMoofContainerAtomRead(FragmentedMp4Extractor.java:572)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onContainerAtomRead(FragmentedMp4Extractor.java:486)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.processAtomEnded(FragmentedMp4Extractor.java:464)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:459)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:340)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.source.chunk.BundledChunkExtractor.read(BundledChunkExtractor.java:114)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:129)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-11-22 21:26:13.749 26378-26439/com.example.videoplayer W/ple.videoplaye:     at java.lang.Thread.run(Thread.java:764)
2020-11-22 21:26:13.789 26378-26632/com.example.videoplayer I/OMXClient: IOmx service obtained
2020-11-22 21:26:13.797 26378-26632/com.example.videoplayer I/ACodec: codec does not support config priority (err -2147483648)
2020-11-22 21:26:13.799 26378-26632/com.example.videoplayer I/ACodec: codec does not support config priority (err -2147483648)
2020-11-22 21:26:13.800 26378-26632/com.example.videoplayer W/ExtendedACodec: Failed to get extension for extradata parameter
2020-11-22 21:26:13.859 26378-26429/com.example.videoplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.1.4.L153, video/hevc] [OMX.qcom.video.decoder.hevc, video/hevc] [violet, Redmi Note 7 Pro, Xiaomi, 28]
2020-11-22 21:26:13.867 26378-26637/com.example.videoplayer I/OMXClient: IOmx service obtained
2020-11-22 21:26:13.884 26378-26636/com.example.videoplayer D/SurfaceUtils: connecting to surface 0x7781cca010, reason connectToSurface
2020-11-22 21:26:13.885 26378-26636/com.example.videoplayer I/MediaCodec: [OMX.google.hevc.decoder] setting surface generation to 27011073
2020-11-22 21:26:13.885 26378-26636/com.example.videoplayer D/SurfaceUtils: disconnecting from surface 0x7781cca010, reason connectToSurface(reconnect)
2020-11-22 21:26:13.885 26378-26636/com.example.videoplayer D/SurfaceUtils: connecting to surface 0x7781cca010, reason connectToSurface(reconnect)
2020-11-22 21:26:13.886 26378-26637/com.example.videoplayer I/ACodec: codec does not support config priority (err -1010)
2020-11-22 21:26:13.887 26378-26637/com.example.videoplayer E/ACodec: [OMX.google.hevc.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
2020-11-22 21:26:13.887 26378-26637/com.example.videoplayer I/ExtendedACodec: setupVideoDecoder()
2020-11-22 21:26:13.890 26378-26637/com.example.videoplayer I/ACodec: codec does not support config priority (err -1010)
2020-11-22 21:26:13.892 26378-26637/com.example.videoplayer W/ExtendedACodec: Failed to get extension for extradata parameter
2020-11-22 21:26:14.450 26378-26429/com.example.videoplayer W/ple.videoplaye: Accessing hidden method Landroid/media/AudioTrack$Builder;->setOffloadedPlayback(Z)Landroid/media/AudioTrack$Builder; (dark greylist, linking)
2020-11-22 21:26:14.451 26378-26429/com.example.videoplayer W/ple.videoplaye: Accessing hidden method Landroid/media/AudioTrack$Builder;->setOffloadedPlayback(Z)Landroid/media/AudioTrack$Builder; (dark greylist, linking)
2020-11-22 21:26:14.473 26378-26429/com.example.videoplayer D/AudioTrack: get packages (com.example.videoplayer) for calling UID 10719
2020-11-22 21:26:14.473 26378-26429/com.example.videoplayer D/AudioTrack: set(): Force removing AUDIO_OUTPUT_FLAG_RAW
2020-11-22 21:26:17.258 26378-26429/com.example.videoplayer E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:336)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:193)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:126)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-11-22 21:26:17.277 26378-26636/com.example.videoplayer D/SurfaceUtils: disconnecting from surface 0x7781cca010, reason disconnectFromSurface
2020-11-22 21:26:17.374 26378-26378/com.example.videoplayer W/System.err: com.google.android.exoplayer2.ExoPlaybackException: Source error
2020-11-22 21:26:17.374 26378-26378/com.example.videoplayer W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
2020-11-22 21:26:17.374 26378-26378/com.example.videoplayer W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
2020-11-22 21:26:17.375 26378-26378/com.example.videoplayer W/System.err:     at android.os.Looper.loop(Looper.java:201)
2020-11-22 21:26:17.375 26378-26378/com.example.videoplayer W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)
2020-11-22 21:26:17.375 26378-26378/com.example.videoplayer W/System.err: Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
2020-11-22 21:26:17.375 26378-26378/com.example.videoplayer W/System.err:     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:336)
2020-11-22 21:26:17.375 26378-26378/com.example.videoplayer W/System.err:     at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:193)
2020-11-22 21:26:17.376 26378-26378/com.example.videoplayer W/System.err:     at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
2020-11-22 21:26:17.376 26378-26378/com.example.videoplayer W/System.err:     at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:126)
2020-11-22 21:26:17.376 26378-26378/com.example.videoplayer W/System.err:     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
2020-11-22 21:26:17.376 26378-26378/com.example.videoplayer W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-11-22 21:26:17.376 26378-26378/com.example.videoplayer W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-11-22 21:26:17.376 26378-26378/com.example.videoplayer W/System.err:     at java.lang.Thread.run(Thread.java:764)

```

### Link to test content
```
package com.example.videoplayer;

import android.net.Uri;
import android.os.Bundle;

import androidx.appcompat.app.AppCompatActivity;

import com.google.android.exoplayer2.C;
import com.google.android.exoplayer2.DefaultRenderersFactory;
import com.google.android.exoplayer2.ExoPlaybackException;
import com.google.android.exoplayer2.ExoPlayer;
import com.google.android.exoplayer2.ExoPlayerFactory;
import com.google.android.exoplayer2.MediaItem;
import com.google.android.exoplayer2.SimpleExoPlayer;
import com.google.android.exoplayer2.drm.DrmSessionManager;
import com.google.android.exoplayer2.drm.FrameworkMediaCrypto;
import com.google.android.exoplayer2.extractor.DefaultExtractorsFactory;
import com.google.android.exoplayer2.extractor.mp3.Mp3Extractor;
import com.google.android.exoplayer2.extractor.ts.DefaultTsPayloadReaderFactory;
import com.google.android.exoplayer2.source.ConcatenatingMediaSource;
import com.google.android.exoplayer2.source.DefaultMediaSourceFactory;
import com.google.android.exoplayer2.source.MediaSource;
import com.google.android.exoplayer2.source.ProgressiveMediaSource;
import com.google.android.exoplayer2.source.dash.DashChunkSource;
import com.google.android.exoplayer2.source.dash.DashMediaSource;
import com.google.android.exoplayer2.source.dash.DefaultDashChunkSource;
import com.google.android.exoplayer2.trackselection.DefaultTrackSelector;
import com.google.android.exoplayer2.ui.PlayerView;
import com.google.android.exoplayer2.upstream.DataSource;
import com.google.android.exoplayer2.upstream.DefaultBandwidthMeter;
import com.google.android.exoplayer2.upstream.DefaultHttpDataSource;
import com.google.android.exoplayer2.upstream.DefaultHttpDataSourceFactory;
import com.google.android.exoplayer2.util.Util;
import com.pallycon.widevinelibrary.PallyconDrmException;
import com.pallycon.widevinelibrary.PallyconEventListener;
import com.pallycon.widevinelibrary.PallyconWVMSDK;
import com.pallycon.widevinelibrary.PallyconWVMSDKFactory;
import com.pallycon.widevinelibrary.UnAuthorizedDeviceException;

import java.util.EventListener;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;

import com.pallycon.widevinelibrary.PallyconDrmException;
import com.pallycon.widevinelibrary.PallyconEventListener;
import com.pallycon.widevinelibrary.PallyconWVMSDK;
import com.pallycon.widevinelibrary.PallyconWVMSDKFactory;
import com.pallycon.widevinelibrary.UnAuthorizedDeviceException;

public class MainActivity extends AppCompatActivity {


    private class ExoplayerEventListener implements ExoPlayer.EventListener {
        @Override
        public void onPlayerError(ExoPlaybackException error) {
            error.printStackTrace();
        }
    }


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        PlayerView playerView = findViewById(R.id.player_view);

        // TODO : 2.set content information

        DefaultExtractorsFactory extractorsFactory =
                new DefaultExtractorsFactory()
                        .setTsExtractorFlags(DefaultTsPayloadReaderFactory.FLAG_DETECT_ACCESS_UNITS | DefaultTsPayloadReaderFactory.FLAG_ALLOW_NON_IDR_KEYFRAMES);

        SimpleExoPlayer exoPlayer = new SimpleExoPlayer.Builder(this, new DefaultRenderersFactory(this)).setTrackSelector(new DefaultTrackSelector(this)).setMediaSourceFactory(
                new DefaultMediaSourceFactory(this, extractorsFactory)).build();
        HashMap<String, String> map = new HashMap<>();
        map.put("pallycon-customdata-v2", "xxxxxx==");


        exoPlayer.addListener(new ExoplayerEventListener());

        MediaItem mediaItem = new MediaItem.Builder()
                .setUri("http://xxxxxx/index.mpd")
                .setDrmUuid(C.WIDEVINE_UUID)
                .setDrmLicenseUri("http://license.pallycon.com/ri/licenseManager.do")
                .setDrmLicenseRequestHeaders(map)
                .setDrmMultiSession(true)
                .build();

        exoPlayer.setMediaItem(mediaItem);
        playerView.setPlayer(exoPlayer);
        exoPlayer.prepare();
        exoPlayer.setPlayWhenReady(true);
    }
}


```

**Comment by AquilesCanta** [comment]
> Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404

This means the server is returning a 404 at some point and playback cannot continue. Please check your links and server to see why a 404 is being returned.

Aside, next time you file an issue, please read the issue template and follow the instructions. Under "Link to test content" you pasted the code to reproduce and redacted the link. Under "A full bug report captured from the device", you pasted a piece of logcat. This makes the communication inefficient.
