### ISSUE TITLE
Crash - Unable to start activity ComponentInfo (attempt to read from field 'long com.google.android.exoplayer2.offline.a0.a')

### ISSUE THREAD

**Issue by Proxwian** [google/ExoPlayer#8274]
### [REQUIRED] Issue description
App crashing when trying to launch with having downloaded video via ExoPlayer:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.tv1.kino, PID: 6871
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.tv1.kino/ru.********.android.ui.activity.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'long com.google.android.exoplayer2.offline.a0.a' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3895)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4074)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'long com.google.android.exoplayer2.offline.a0.a' on a null object reference
        at com.google.android.exoplayer2.offline.s.a(Download.java:1)
        at ru.********.android.dao.model.kino.DownloadFile.getSize(DownloadFile.kt:1)
        at ru.********.android.i.f.o(DownloadTracker.kt:1)
        at ru.********.android.i.f.y(DownloadTracker.kt:3)
        at ru.********.android.i.f.z(DownloadTracker.kt:1)
        at ru.********.android.i.f.D(DownloadTracker.kt:5)
        at ru.********.android.i.f.q(DownloadTracker.kt:4)
        at ru.********.android.i.f.<init>(DownloadTracker.kt:12)
        at ru.********.android.i.d.m(AppManager.kt:11)
        at ru.********.android.i.d.k(AppManager.kt:1)
        at ru.********.android.App$a.c(App.kt:1)
        at ru.********.android.ui.activity.MainActivity.onCreate(MainActivity.kt:28)
        at android.app.Activity.performCreate(Activity.java:8085)
        at android.app.Activity.performCreate(Activity.java:8073)
```

### [REQUIRED] Version of ExoPlayer being used
2.12.1

### [REQUIRED] Device(s) and version(s) of Android being used
Huawei Mate 30

**Comment by AquilesCanta** [comment]
We cannot assist by looking at a snippet of an obfuscated+minified logcat. Please provide us with a way of reproducing or, at least, a non obfuscated logcat.
