### ISSUE TITLE
FireOS5 - ExoPlayerImplInternal: Renderer error

### ISSUE THREAD

**Issue by ryxryx** [google/ExoPlayer#8281]
### [REQUIRED] Issue description
Describe the issue in detail, including observed and expected behavior.
We are using official ExoPlayer (2.11.3) in our video player apps. The player works fine on Android 5.1.1 to up to the latest Android OS, and works fine on FireOS6 and above. But on FireOS 5, the playback stops during playing, especially when the player finishes playing an ad (DAI IMA), right after pre-roll, and starts on the video content. 

We see on the ExoPlayer website: "Device specific issues encountered on FireOS are normally caused by incompatibilities in the support that FireOS provides for running Android applications. Such issues should be reported to Amazon in the first instance. We are aware of issues affecting FireOS version 4 and earlier. We believe FireOS version 5 resolved these issues." Hence, we would like to bring up the issue to you.

Reproducible on:
- Amazon Fire 7 (2017) Fire OS 5.6.4.0
- Amazon Fire 6 Fire OS 5.6.0.0

### [REQUIRED] Reproduction steps
Issue only reproduciable on FireOS 5.6 for now. To reproduce, suggest using a Fire 7 or 6 with FireOS 5.6. Play with video content from Google IMA DAI, see if the player can go through all ads and contents.

### [REQUIRED] Link to test content

Accessible only in the USA

url 1: https://7883af314d2849b68749725ce5fdfe2b.dlvr1.net/nosec/The_CW/14/797/91282501920/Devils-101-EpisodeOne-CW.m3u8?originpath=/ondemand/hls/content/2478072/vid/693ccdf0-8772-4e16-9546-4074f0f1318f/DLS/streams/731b1982-bac3-40f1-935a-135e57705cf2/master.m3u8

url 2: https://7883af314d2849b68749725ce5fdfe2b.dlvr1.net/nosec/The_CW/638/840/70462021580/Batwoman-101-Pilot-T1510154-CW.m3u8?originpath=/ondemand/hls/content/2478072/vid/b570a6c4-8097-44bf-80df-e27eef815c15/DLS/streams/67902bc0-feb5-42dc-8dbf-76bc74a4171a/master.m3u8

### [REQUIRED] A full bug report captured from the device

Bug report attached. Please let us know if it is sufficient.

[app_logs_1.txt](https://github.com/google/ExoPlayer/files/5599694/app_logs_1.txt)
[app_logs_2.txt](https://github.com/google/ExoPlayer/files/5599695/app_logs_2.txt)

Some logs below:
```
11-24 18:17:32.547 10512-10797/? E/ExoPlayerImplInternal: Renderer error: index=1, type=audio, format=Format(1/15, null, null, audio/mp4a-latm, null, -1, null, [-1, -1, -1.0], [2, 64000]), rendererSupport=YES
    com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:732)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_queueInputBuffer(Native Method)
        at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:853)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1190)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:719)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

### [REQUIRED] Version of ExoPlayer being used
2.11.3

### [REQUIRED] Device(s) and version(s) of Android being used
Reproducible on below, and issue happens everytime.
- Amazon Fire 7 (2017) Fire OS 5.6.4.0
- Amazon Fire 6 Fire OS 5.6.0.0

Issues not happen on: Android 5.1.1 and above; or FireOS6, FireOS7

--

Thank you and let us know if you need information.

**Comment by AquilesCanta** [comment]
Hi @ryxryx, thank you very much for the high quality report. This doesn't seem to be an ExoPlayer issue, but rather an issue specific to FireOS 5.6 (and fixed later?). Unfortunately, we only provide best effort support for FireOS (as stated in https://exoplayer.dev/supported-devices.html), and any device specific issues should be directed to Amazon. I think we would be willing to accept high quality pull requests including non-disruptive changes to support FireOS devices, but we cannot commit to debug and fix this ourselves. I'm sincerely sorry we cannot be of assistance in this scenario.

**Comment by ghost** [comment]
@AquilesCanta Hi! I catch this bug on emulator with Android 5.1. All times when I start start player.


> 11-26 15:59:35.679 4372-4406/com.umbrellait.interactive_informant E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
11-26 15:59:35.691 4372-4409/com.umbrellait.interactive_informant E/SoftAVC: Decoder failed: -2
11-26 15:59:35.697 4372-4406/com.umbrellait.interactive_informant E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
11-26 15:59:35.698 4372-4406/com.umbrellait.interactive_informant E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
11-26 15:59:35.699 4372-4405/com.umbrellait.interactive_informant E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
11-26 15:59:35.703 4372-4396/com.umbrellait.interactive_informant E/ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(2, null, null, video/avc, null, -1, null, [1280, 720, 24.0], [-1, -1]), rendererSupport=YES
      com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:735)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_queueInputBuffer(Native Method)
        at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:831)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1195)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:722)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
11-26 15:59:35.705 4372-4396/com.umbrellait.interactive_informant E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:662)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:777)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.flushOrReleaseCodec(MediaCodecVideoRenderer.java:724)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:636)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:569)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:168)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1136)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:891)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:382)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
11-26 15:59:35.728 4372-4396/com.umbrellait.interactive_informant E/ExoPlayerImplInternal: Reset failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:628)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:671)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:714)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onReset(MediaCodecRenderer.java:643)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onReset(MediaCodecVideoRenderer.java:578)
        at com.google.android.exoplayer2.BaseRenderer.reset(BaseRenderer.java:175)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:900)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:382)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by AquilesCanta** [comment]
@umbrellait-daniil-shtainmets What you are seeing is the same stacktrace, not the same bug. Please file a fresh issue including all information requested in the issue template.

EDIT: Also, make sure you read https://exoplayer.dev/supported-devices.html for info on emulators.
