### ISSUE TITLE
Video can't play on some devices

### ISSUE THREAD

**Issue by kyymeade** [google/ExoPlayer#8282]
[2020-11-26 12:14:40.427] [28176] [5120] [4] [MediaCodec] : [OMX.qcom.video.decoder.avc] setting surface generation to 28852225
[2020-11-26 12:14:40.427] [28176] [5121] [4] [ExtendedACodec] : [OMX.qcom.video.decoder.avc]configureCodec AMessage(what = 'conf', target = 1) = {
  Buffer csd-1 = {
    00000000:  00 00 00 01 68 e9 09 35  20                       ....h..5 
  }
  string mime = "video/avc"
  float frame-rate = 25.000000
  int32_t rotation-degrees = 0
  int32_t max-height = 1902
  int32_t height = 1902
  int32_t width = 3732
  int32_t max-input-size = 458800
  int32_t priority = 0
  Buffer csd-0 = {
    00000000:  00 00 00 01 67 4d 40 33  96 52 80 75 01 df cf 53  ....gM@3.R.u...S
    00000010:  50 10 10 14 00 00 03 00  04 00 00 03 00 ca 10     P..............
  }
  int32_t max-width = 3732
  RefBase *native-window = 0x813d6040
}
[2020-11-26 12:14:40.427] [28176] [5121] [4] [ExtendedACodec] : This platform is qcom_8937
[2020-11-26 12:14:40.427] [28176] [5121] [6] [ExtendedACodec] : This video(3732 X 1902) is larger than 1920X1080 qcom decoder not support
[2020-11-26 12:14:40.427] [28176] [5121] [6] [ACodec] : [OMX.qcom.video.decoder.avc] configureCodec returning error -1010
[2020-11-26 12:14:40.427] [28176] [5121] [6] [ACodec] : signalError(omxError 0x80001001, internalError -1010)
[2020-11-26 12:14:40.427] [28176] [5120] [6] [MediaCodec] : Codec reported err 0xfffffc0e, actionCode 0, while in state 3
[2020-11-26 12:14:40.437] [28176] [4999] [6] [MediaCodec] : configure failed with err 0xfffffc0e, resetting...
[2020-11-26 12:14:40.437] [28176] [5120] [4] [ACodec] : initiateShutdown
[2020-11-26 12:14:40.437] [28176] [5120] [4] [ACodec] : initiateShutdown kWhatReleaseCodecInstance modify to 3s
[2020-11-26 12:14:40.437] [662] [1774] [4] [OMX-VDEC-1080P] : omx_vdec::component_deinit() complete
[2020-11-26 12:14:40.437] [662] [1774] [4] [OMX-VDEC-1080P] : Exit OMX vdec Destructor: fd=50
[2020-11-26 12:14:40.437] [662] [1774] [4] [OMX-VDEC-1080P] : Video slvp perflock released
[2020-11-26 12:14:40.437] [28176] [5121] [4] [OMXClient] : Using client-side OMX mux.
[2020-11-26 12:14:40.447] [662] [15469] [6] [] : Service not available yet
[2020-11-26 12:14:40.457] [3473] [3479] [6] [ANDR-PERF-MPCTL] : Invalid profile no. 0, total profiles 0 only
[2020-11-26 12:14:40.457] [662] [15469] [4] [OMX-VDEC-1080P] : Video slvp perflock acquired
[2020-11-26 12:14:40.457] [662] [15469] [4] [OMX-VDEC-1080P] : component_init: OMX.qcom.video.decoder.avc : fd=50
[2020-11-26 12:14:40.467] [662] [15469] [4] [OMX-VDEC-1080P] : omx_vdec::component_init() success : fd=50
[2020-11-26 12:14:40.467] [28176] [5120] [4] [ACodec] : initiateShutdown
[2020-11-26 12:14:40.467] [28176] [5120] [4] [ACodec] : initiateShutdown kWhatReleaseCodecInstance modify to 3s
[2020-11-26 12:14:40.467] [662] [1584] [4] [OMX-VDEC-1080P] : omx_vdec::component_deinit() complete
[2020-11-26 12:14:40.477] [662] [1584] [4] [OMX-VDEC-1080P] : Exit OMX vdec Destructor: fd=50
[2020-11-26 12:14:40.477] [662] [1584] [4] [OMX-VDEC-1080P] : Video slvp perflock released
[2020-11-26 12:14:40.477] [28176] [4999] [5] [MediaCodecRenderer] : Failed to initialize decoder: OMX.qcom.video.decoder.avc
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1778)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:571)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:847)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:779)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:510)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1186)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:636)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:733)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
[2020-11-26 12:14:40.477] [28176] [4999] [6] [ExoPlayerImplInternal] : Playback error.
com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [3732, 1902, 25.0], [-1, -1])
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:512)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1186)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:636)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:733)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [3732, 1902, 25.0], [-1, -1])
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:786)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:510)
	... 9 more
Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1778)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:571)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:847)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:779)
	... 10 more
[2020-11-26 12:14:40.477] [28176] [28176] [6] [kyy] : com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [3732, 1902, 25.0], [-1, -1])

[REQUIRED] Content description
videourl:https://media.changchangenglish.com/course/8d432e2554bb854cea889db32611e8b9_720.mp4
I see the err:This video(3732 X 1902) is larger than 1920X1080 qcom decoder not support
but the video is 1280x720 
[REQUIRED] Version of ExoPlayer being used
2.10.5

[REQUIRED] Device(s) and version(s) of Android being used
Vivo Y66
android 6.0.1

**Comment by AquilesCanta** [comment]
Agreed the line:
`OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [3732, 1902, 25.0], [-1, -1])`
looks very weird. And that's definitely on the ExoPlayer side, so that's good news. I have checked whether ExoPlayer tries to configure the decoder with the wrong size (3732, 1902) before attempting the right size, but it doesn't seem to be the case, and the right size is being used from the start.

I think the best path forward is that you try to play https://media.changchangenglish.com/course/8d432e2554bb854cea889db32611e8b9_720.mp4 on the ExoPlayer demo app, using the latest release, on Vivo Y66, android 6.0.1. ExoPlayer 2.10.5 is a pretty old version, plus it's not clear whether you tested this in the demo app.

So please checkout the latest ExoPlayer version's demo app and play the problematic file, and reach back if you are having any issues. If you do this, please don't forget to provide us with the output of `adb bugreport` shortly after reproducing the issue. On the other hand, if you are not having any issues, then we need to figure out whether a bug has been fixed since 2.10.5, or you app somehow introduces the issue.
