### ISSUE TITLE
Crash with Chromecast

### ISSUE THREAD

**Issue by chladto1** [google/ExoPlayer#8291]
### Issue description
Could you please take a look at this log? This is crash from Firebase, we do not have any context but hopefully you will found some issue to fix.

### Reproduction steps
Unknown

### Link to test content
Unknown

### A full bug report captured from the device
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'e0.t.l.c e0.t.l.f$g.a()' on a null object reference
       at androidx.mediarouter.media.MediaRouter$GlobalMediaRouter.setSelectedRouteInternal(MediaRouter.java:2616)
       at androidx.mediarouter.media.MediaRouter$GlobalMediaRouter.updateSelectedRouteIfNeeded(MediaRouter.java:2502)
       at androidx.mediarouter.media.MediaRouter$GlobalMediaRouter.updateProviderContents(MediaRouter.java:2376)
       at androidx.mediarouter.media.MediaRouter$GlobalMediaRouter.updateProviderDescriptor(MediaRouter.java:2260)
       at androidx.mediarouter.media.MediaRouter$GlobalMediaRouter$ProviderCallback.onDescriptorChanged(MediaRouter.java:2768)
       at androidx.mediarouter.media.MediaRouteProvider.deliverDescriptorChanged(MediaRouteProvider.java:241)
       at androidx.mediarouter.media.MediaRouteProvider$ProviderHandler.handleMessage(MediaRouteProvider.java:442)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

### Version of ExoPlayer being used
2.11.8

### Device(s) and version(s) of Android being used
Honor 9 Lite, Android 9

**Comment by AquilesCanta** [comment]
I don't think we will be able to assist much with this amount of info. I've contacted a team that may be able to shed some light but I cannot make any promises.

**Comment by AquilesCanta** [comment]
Hi, the team in charge of MediaRouter was able to narrow down the possible causes of the issue, but mentioned that there is not much which is actionable on our side. Is it possible that the media router version that you are using is old? If so, they advised you try updating the library version.

Other than that, the ExoPlayer team is not able to help much here, since the issue is not even occurring in our stacktrace. Please let me know if you manage to reproduce the issue, or if you are able to mitigate it by updating the mediarouter library version, so as to favor future readers.
