### ISSUE TITLE
IllegalArgumentException from AacUtil.getSamplingFrequency

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#8295]
Issue split from #8283

### [REQUIRED] Issue description
I'm getting this error reported to crashlytics:

```
Non-fatal Exception: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:436)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
Caused by java.lang.IllegalArgumentException
       at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
       at com.google.android.exoplayer2.audio.AacUtil.getSamplingFrequency(AacUtil.java:346)
       at com.google.android.exoplayer2.audio.AacUtil.parseAudioSpecificConfig(AacUtil.java:196)
       at com.google.android.exoplayer2.audio.AacUtil.parseAudioSpecificConfig(AacUtil.java:179)
       at com.google.android.exoplayer2.extractor.ts.AdtsReader.parseAdtsHeader(AdtsReader.java:504)
       at com.google.android.exoplayer2.extractor.ts.AdtsReader.consume(AdtsReader.java:178)
       at com.google.android.exoplayer2.extractor.ts.PesReader.consume(PesReader.java:144)
       at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:383)
       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

```
EventLogger: mediaItem [eventTime=10191.79, mediaPos=0.00, window=0, reason=PLAYLIST_CHANGED]
EventLogger: state [eventTime=10191.79, mediaPos=0.00, window=0, BUFFERING]
EventLogger: loading [eventTime=10191.80, mediaPos=0.00, window=0, period=0, true]
EventLogger: timeline [eventTime=10191.80, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
EventLogger:   period [?]
EventLogger:   window [?, false, false]
EventLogger: ]
EventLogger: timeline [eventTime=10192.38, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
EventLogger:   period [?]
EventLogger:   window [?, false, false]
EventLogger: ]
```

### [REQUIRED] Reproduction steps
Callstacks are from automatic error reports and I can not reproduce them locally

### [REQUIRED] Link to test content
Errors are from automatic error reports and I do not own media

### [REQUIRED] A full bug report captured from the device
n/a

### [REQUIRED] Version of ExoPlayer being used
r2.12.1

### [REQUIRED] Device(s) and version(s) of Android being used
BRAVIA 4K GB ATV3, Xiaomi MiBox S, NVidia Shield TV

**Comment by christosts** [comment]
@krocard  can you take a look?

**Comment by krocard** [comment]
From the stack trace, the AAC packet has an invalid frequency index:
https://github.com/google/ExoPlayer/blob/83477497c19959f4b33c3af57cc1e646fcc3848a/library/common/src/main/java/com/google/android/exoplayer2/audio/AacUtil.java#L333-L350

The 4 bit frequency index should either be 15 (arbitrary, specified in the next 24 bits) or < 13 and correspond to the predefined frequency table.

A frequency index of 13 and 14 will result in this assertion failing. I do think that a `ParserException` should be thrown though.

This might be because those value now correspond to a frequency, and the code should be updated. Otherwise this is a bad media.

Assigning to @kim-vde as this is an extractor issue.

**Comment by kim-vde** [comment]
The frequency index is indeed invalid (see ISO 14496-3:2009 tables 1.13 and 1.18). I will change the exception thrown to a ParserException.
