### ISSUE TITLE
Error inflating class on PlayerView

### ISSUE THREAD

**Issue by mazWaz** [google/ExoPlayer#8309]
### Issue description
Error inflating class on com.google.android.exoplayer2.ui.PlayerView

### [REQUIRED] Reproduction steps
Error layout viewdatabinding xml on playerview

### Link to test content
val decodedString: ByteArray = Base64.decode(it.data.substringAfter("base64,"), Base64.DEFAULT)
 val byteArrayDataSource = ByteArrayDataSource(decodedString)
val factory =DataSource.Factory { byteArrayDataSource }
val mediaSource: MediaSource = ExtractorMediaSource.Factory(factory)
         .setExtractorsFactory(DefaultExtractorsFactory())
          .createMediaSource(Uri.EMPTY)

exoPlayer = SimpleExoPlayer.Builder(requireContext()).build().apply{
    playWhenReady = isPlayerPlaying
    seekTo(currentWindow, playbackPosition)
    setMediaSource(mediaSource)
     prepare()
 }

### A full bug report captured from the device
 android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class com.google.android.exoplayer2.ui.PlayerView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
        at web.id.pbrx.lss.ui.base.BaseFragment.onCreateView(BaseFragment.kt:19)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

### [REQUIRED] Version of ExoPlayer being used
 exoPlayer V2.12.1

### [REQUIRED] Device(s) and version(s) of Android being used
Android Sdk Version 23
All devices running on Android X

**Comment by mazWaz** [comment]
SOLVED
https://github.com/google/ExoPlayer/issues/5138#issuecomment-450807968
