### ISSUE TITLE
Play mp4 video get "Skipping atom with length > 2147483647" error.

### ISSUE THREAD

**Issue by Daktm** [google/ExoPlayer#8310]
```
12-02 18:57:24.453  3218  4413 E ExoPlayerImplInternal: Playback error
12-02 18:57:24.453  3218  4413 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: Source error
12-02 18:57:24.453  3218  4413 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
12-02 18:57:24.453  3218  4413 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:98)
12-02 18:57:24.453  3218  4413 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:154)
12-02 18:57:24.453  3218  4413 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:61)
12-02 18:57:24.453  3218  4413 E ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.ParserException: Skipping atom with length > 2147483647 (unsupported).
12-02 18:57:24.453  3218  4413 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomHeader(FragmentedMp4Extractor.java:455)
12-02 18:57:24.453  3218  4413 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:349)
12-02 18:57:24.453  3218  4413 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
12-02 18:57:24.453  3218  4413 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)
12-02 18:57:24.453  3218  4413 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
12-02 18:57:24.453  3218  4413 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-02 18:57:24.453  3218  4413 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-02 18:57:24.453  3218  4413 E ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:761)
12-02 18:57:24.454  2205  4421 W libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)
12-02 18:57:24.455  2205  4420 W libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)
12-02 18:57:24.468  2205  4417 I EXYNOS_BASE_COMP: [0xf4d53700][Exynos_OMX_ComponentStateSet] current:(OMX_StateExecuting) dest:(OMX_StateIdle)
12-02 18:57:24.469  2205  4421 W libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)
12-02 18:57:24.470  2205  4420 W libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)
12-02 18:57:24.471  2205  4417 I EXYNOS_BASE_COMP: [0xf4d53700][Exynos_OMX_ComponentStateSet] OMX_EventCmdComplete
12-02 18:57:24.471  2205  4417 I EXYNOS_BASE_COMP: [0xf4d53700][Exynos_OMX_ComponentStateSet] current:(OMX_StateIdle) dest:(OMX_StateLoaded)
12-02 18:57:24.472  2205  4421 W libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)
12-02 18:57:24.480  2205  4417 I EXYNOS_BASE_COMP: [0xf4d53700][Exynos_OMX_ComponentStateSet] OMX_EventCmdComplete
```

**Comment by Daktm** [comment]
Exoplayer 2.12.1

**Comment by christosts** [comment]
Please provide complete information as requested in the issue template, specifically the information around test content. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

Thanks.
