### ISSUE TITLE
exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error (bug)

### ISSUE THREAD

**Issue by newtestpage** [google/ExoPlayer#8355]
Hi I tried to play an hls url with demo app . it works fine on high android version . but when I tested it with lower android version I got error . 

android version 5 - 5.1
samsung galaxy core prime
exoplayer ver:2.12.0

tested link :"https://nrpus.bozztv.com/36bay2/gin/giniko_manoto1_700kb_36bay2/index.m3u8"

here is complete log :
```
12/16 13:38:01: Launching 'demo' on samsung SM-G361F.
$ adb shell am start -n "com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.SampleChooserActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 13645 on device 'samsung-sm_g361f-4200f9c99b0e8200'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/ContextImpl: ContextImpl running for user UserHandle{0} 0
D/ContextImpl: ContextImpl running for user UserHandle{0} 0
W/ResourcesManager: getTopLevelResources: null for user  0
D/ContextImpl: ContextImpl running for user UserHandle{0} 0
I/MultiDex: VM with version 2.1.0 has multidex support
    Installing application
    VM has multidex support, MultiDex support library is disabled.
D/ContextImpl: ContextImpl running for user UserHandle{0} 0
W/ResourcesManager: getTopLevelResources: null for user  0
W/ResourcesManager: getTopLevelResources: null for user  0
D/ContextImpl: ContextImpl running for user UserHandle{0} 0
W/ResourcesManager: getTopLevelResources: null for user  0
D/DisplayManager: DisplayManager()
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
D/PhoneWindow: *FMB* installDecor mIsFloating : false
    *FMB* installDecor flags : -2139029248
I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
    Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
W/art: Suspending all threads took: 7.659ms
I/art: Background sticky concurrent mark sweep GC freed 11033(667KB) AllocSpace objects, 1(16KB) LOS objects, 12% free, 5MB/6MB, paused 10.032ms total 45.277ms
W/: Unable to open '/system/framework/fipstimakeystore.jar': No such file or directory
W/art: Failed to open zip archive '/system/framework/fipstimakeystore.jar': I/O Error
W/System.err: java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
        at libcore.io.IoBridge.open(IoBridge.java:456)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
        at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.openFile(FileOutput.java:67)
        at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.startup(FileOutput.java:49)
        at org.jacoco.agent.rt.internal_8ff85ea.Agent.startup(Agent.java:122)
        at org.jacoco.agent.rt.internal_8ff85ea.Agent.getInstance(Agent.java:50)
        at org.jacoco.agent.rt.internal_8ff85ea.Offline.<clinit>(Offline.java:31)
        at com.google.android.exoplayer2.offline.DefaultDownloadIndex.$jacocoInit(DefaultDownloadIndex.java)
        at com.google.android.exoplayer2.offline.DefaultDownloadIndex.<clinit>(DefaultDownloadIndex.java)
        at com.google.android.exoplayer2.demo.DemoUtil.ensureDownloadManagerInitialized(DemoUtil.java:132)
        at com.google.android.exoplayer2.demo.DemoUtil.getDownloadTracker(DemoUtil.java:115)
        at com.google.android.exoplayer2.demo.SampleChooserActivity.onCreate(SampleChooserActivity.java:117)
        at android.app.Activity.performCreate(Activity.java:6178)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)
        at android.app.ActivityThread.access$900(ActivityThread.java:177)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5910)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
    Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
W/System.err:     at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at libcore.io.IoBridge.open(IoBridge.java:442)
    	... 24 more
W/ContextImpl: Failed to ensure directory: /storage/extSdCard/Android/data/com.google.android.exoplayer2.demo/files
E/SQLiteLog: (283) recovered 22 frames from WAL file /data/data/com.google.android.exoplayer2.demo/databases/exoplayer_internal.db-wal
I/DynamiteModule: Considering local module com.google.android.gms.cronet_dynamite:0 and remote module com.google.android.gms.cronet_dynamite:1311
    Selected remote version of com.google.android.gms.cronet_dynamite, version >= 1311
V/DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
D/ContextImpl: ContextImpl running for user UserHandle{0} 0
W/ResourcesManager: getTopLevelResources: null for user  0
W/ResourcesManager: Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
    Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
W/ResourcesManager: getTopLevelResources: null for user  0
W/ResourcesManager: getTopLevelResources: null for user  0
W/linker: libcronet.83.0.4103.106.so: unused DT entry: type 0x6ffffef5 arg 0x29f4
    libcronet.83.0.4103.106.so: unused DT entry: type 0x6ffffffe arg 0x2994
    libcronet.83.0.4103.106.so: unused DT entry: type 0x6fffffff arg 0x3
I/cr_CronetLibraryLoader: Cronet version: 83.0.4103.106, arch: armv7l
D/CronetEngineWrapper: CronetEngine built using Google-Play-Services-Cronet-Provider
D/ConnectivityManager: CallingUid : 10144, CallingPid : 13645
D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/ContextImpl: ContextImpl running for user UserHandle{0} 0
D/PhoneWindow: *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
D/PhoneWindow: *FMB* isFloatingMenuEnabled return false
I/OpenGLRenderer: Initialized EGL, version 1.4
D/GC: <tid=13714> OES20 ===> GC Version   : GC version rls_5011p6_GC5.5.14 
D/OpenGLRenderer: Enabling debug mode 0
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@22d910d6 time:1743668
D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
D/ListView: change accessibility focus position = 9
I/Timeline: Timeline: Activity_launch_request id:com.google.android.exoplayer2.demo time:1748108
D/ContextImpl: ContextImpl running for user UserHandle{0} 0
W/ResourcesManager: getTopLevelResources: null for user  0
D/PhoneWindow: *FMB* installDecor mIsFloating : false
    *FMB* installDecor flags : -2139029248
I/art: Background sticky concurrent mark sweep GC freed 8239(707KB) AllocSpace objects, 2(32KB) LOS objects, 12% free, 6MB/7MB, paused 6.733ms total 28.351ms
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
    Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
    Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
D/DisplayManager: DisplayManager()
I/ExoPlayerImpl: Init 1a4de1e2 [ExoPlayerLib/2.12.1] [coreprimevelte, SM-G361F, samsung, 22]
D/EventLogger: playWhenReady [eventTime=0.00, mediaPos=0.00, window=0, true, USER_REQUEST]
D/EventLogger: timeline [eventTime=0.01, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
      period [?]
      window [?, false, true]
    ]
    mediaItem [eventTime=0.01, mediaPos=0.00, window=0, reason=PLAYLIST_CHANGED]
D/EventLogger: state [eventTime=0.01, mediaPos=0.00, window=0, BUFFERING]
D/DisplayManager: DisplayManager()
D/PhoneWindow: *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
    *FMB* isFloatingMenuEnabled return false
D/EventLogger: surfaceSize [eventTime=0.06, mediaPos=0.00, window=0, 480, 764]
D/EventLogger: loading [eventTime=0.10, mediaPos=0.00, window=0, period=0, true]
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@30069bc4 time:1748644
D/EventLogger: timeline [eventTime=1.00, mediaPos=129.36, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
      period [?]
      window [184.80, true, true]
    ]
W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
W/AudioCapabilities: Unsupported mime audio/mpeg-L1
    Unsupported mime audio/mpeg-L2
W/AudioCapabilities: Unsupported mime audio/x-ima
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.64081F, video/avc] [OMX.google.h264.decoder, video/avc] [coreprimevelte, SM-G361F, samsung, 22]
    NoSupport [codec.profileLevel, avc1.64081F, video/avc] [OMX.google.h264.decoder, video/avc] [coreprimevelte, SM-G361F, samsung, 22]
D/EventLogger: videoEnabled [eventTime=1.58, mediaPos=129.36, window=0, period=0]
    audioEnabled [eventTime=1.58, mediaPos=129.36, window=0, period=0]
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.64081F, video/avc] [OMX.google.h264.decoder, video/avc] [coreprimevelte, SM-G361F, samsung, 22]
D/EventLogger: tracks [eventTime=1.58, mediaPos=129.36, window=0, period=0
      MediaCodecVideoRenderer [
        Group:0, adaptive_supported=N/A [
I/ACodec:  [] Now uninitialized
D/EventLogger:       [X] Track:0, id=0, mimeType=video/avc, bitrate=1182506, codecs=avc1.64081F, res=848x480, fps=25.0, supported=YES
        ]
        Metadata [
          HlsTrackMetadataEntry
        ]
      ]
      MediaCodecAudioRenderer [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=1/15, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=44100, supported=YES
        ]
      ]
      TextRenderer []
      MetadataRenderer [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=null, mimeType=application/id3, supported=YES
        ]
      ]
      CameraMotionRenderer []
    ]
I/OMXClient: Using client-side OMX mux.
D/EventLogger: downstreamFormat [eventTime=1.58, mediaPos=129.36, window=0, period=0, id=0, mimeType=null, bitrate=1182506, codecs=avc1.64081f,mp4a.40.2, res=854x480, fps=25.0]
I/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] Now Loaded
E/ACodec: onConfigureComponent mime.c_str() = video/avc
E/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] storeMetaDataInBuffers failed w/ err -2147483648
I/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] remove quirk kRequiresAllocateBufferOnInputPorts/OutputPorts to avoid memcpy.
    [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] add quirk kRequiresBufferPhysicalContinuousOnOutputPorts.
I/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] Now Loaded->Idle
    [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] INPUT: def.nBufferCountActual is increased to 4 
    Native Window Buffer Geometry 848.480 - OMX_COLOR_FormatYUV420SemiPlanar
I/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] configureOutputBuffersFromNativeWindow setBufferCount : 9, minUndequeuedBuffers : 4
    [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] Allocating 9 buffers from a native window of size 610560 on output port
D/EventLogger: videoDecoderInitialized [eventTime=1.68, mediaPos=129.36, window=0, period=0, OMX.MARVELL.VIDEO.HW.CODA7542DECODER]
    videoInputFormat [eventTime=1.68, mediaPos=129.36, window=0, period=0, id=0, mimeType=video/avc, bitrate=1182506, codecs=avc1.64081F, res=848x480, fps=25.0]
I/ACodec:  [] Now uninitialized
I/OMXClient: Using client-side OMX mux.
I/ACodec: [OMX.SEC.aac.dec] Now Loaded
E/ACodec: onConfigureComponent mime.c_str() = audio/mp4a-latm
I/ACodec: [OMX.SEC.aac.dec] Now Loaded->Idle
D/EventLogger: audioDecoderInitialized [eventTime=1.70, mediaPos=129.36, window=0, period=0, OMX.SEC.aac.dec]
    audioInputFormat [eventTime=1.70, mediaPos=129.36, window=0, period=0, id=1/15, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=44100]
I/ACodec: [OMX.SEC.aac.dec] Now Idle->Executing
I/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] Now Idle->Executing
D/EventLogger: audioSessionId [eventTime=1.73, mediaPos=129.36, window=0, period=0, 129]
E/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] ERROR(0x80001000)
    signalError(omxError 0x80001000, internalError -2147483648)
E/MediaCodec: Codec reported err 0x80001000, actionCode 0, while in state 6
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.64081F, video/avc] [OMX.google.h264.decoder, video/avc] [coreprimevelte, SM-G361F, samsung, 22]
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/avc, avc1.64081F, 1182506, null, [848, 480, 25.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MARVELL.VIDEO.HW.CODA7542DECODER
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1377)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:872)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:58)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1774)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:857)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
    Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:662)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:81)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:914)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:773)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:454)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:175)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1507)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1254)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1218)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:546)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
D/EventLogger: videoDisabled [eventTime=1.87, mediaPos=129.36, window=0, period=0]
I/ACodec: [OMX.SEC.aac.dec] Now Flushing
I/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] Now Executing->Idle
D/EventLogger: audioDisabled [eventTime=1.87, mediaPos=129.36, window=0, period=0]
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xab447d30
W/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] can not return buffer 2879054216 to native window
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xab448840
W/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] can not return buffer 2879061000 to native window
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xab4482e8
W/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] can not return buffer 2878005752 to native window
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xab448088
W/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] can not return buffer 2878255304 to native window
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xab41be18
W/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] can not return buffer 2878255184 to native window
I/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] Now Idle->Loaded
    [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] Now Loaded
I/ACodec:  [OMX.MARVELL.VIDEO.HW.CODA7542DECODER] Now uninitialized
I/ACodec: [OMX.SEC.aac.dec] Now Executing->Idle
I/ACodec: [OMX.SEC.aac.dec] Now Idle->Loaded
I/ACodec: [OMX.SEC.aac.dec] Now Loaded
     [OMX.SEC.aac.dec] Now uninitialized
E/EventLogger: playerFailed [eventTime=1.91, mediaPos=129.36, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/avc, avc1.64081F, 1182506, null, [848, 480, 25.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MARVELL.VIDEO.HW.CODA7542DECODER
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1377)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:872)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:58)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1774)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:857)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
    ]
D/EventLogger: loading [eventTime=1.92, mediaPos=129.36, window=0, period=0, false]
    state [eventTime=1.92, mediaPos=129.36, window=0, period=0, IDLE]
I/ExoPlayerImpl: Release 1a4de1e2 [ExoPlayerLib/2.12.1] [coreprimevelte, SM-G361F, samsung, 22] [goog.exo.core, goog.exo.cronet, goog.exo.ui, goog.exo.hls]
```

**Comment by tonihei** [comment]
This issue sounds similar to a problem with another older Samsung device that was previously reported internally and solved by a workaround (internal ref: b/114764047).

Could you try adding your device (`SM-G361F`) to the workaround method [here](
https://github.com/google/ExoPlayer/blob/be13805ce4e22231ae728d2710a2b8751ee5ad7c/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L2310)? This requires that you check out and build the code locally (see https://github.com/google/ExoPlayer#locally for instructions). It would be great if you can try that and in case it helps, we can add this device to the list in our code.

**Comment by newtestpage** [comment]
Hi . Thanks for your answer . But I am not sure is about just my device . I checked with android studio emulator also with android api 21 and it has the same problem . 

```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/avc, avc1.64081F, 1181197, null, [848, 480, 25.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.google.h264.decoder
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1377)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:855)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:58)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1752)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:841)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:662)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:81)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:897)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:758)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:454)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:175)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1510)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1257)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1221)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:546)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by ojw28** [comment]
The emulator is known to be broken prior to API level 23, as per our [supported devices page](https://exoplayer.dev/supported-devices.html).

**Comment by ojw28** [comment]
Marking as needs more info again, since Toni's question above still needs answering.
