### ISSUE TITLE
Exoplayer app doesn´t reproduce VoD with tunneling

### ISSUE THREAD

**Issue by masensio** [google/ExoPlayer#8366]
I´m trying to reproduce with the exoplayer library (2.11.8 version) a 4K VoD content with the properties:
- Video Format: video/hevc - Decoder OMX.MTK.VIDEO.DECODER.HEVC.secure
- Audio Format: audio/mp4a-latm - Decoder OMX.google.aac.decoder
- widevine

- ExoPlayer version number: 2.11.8
- Android version: Android 9
- Android device: Sony Bravia 4K UR3

If Tunneling is disabled the video is correctly reproduced. But if Tunneling is enabled I have the exception.

```
2020-12-17 18:00:48.407 5829-5829/beta.paytvapp.mca.go E/EventLogger: playerFailed [eventTime=1.33, mediaPos=0.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 196992)
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:834)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1590)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:721)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 196992)
        at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:1434)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:530)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:611)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:827)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1590) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:721) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
    ]
```

What I need to do to reproduce that content using tunneling?

**Comment by tonihei** [comment]
This sounds like a device specific problem, but with the given information it's hard to tell what the cause of this problem is and whether there is something we can do about this. Could you provide us with an example stream and a full bugreport (taken with `adb bugreport`)? If you don't want to post this publicly, please send an email to exoplayer.dev@gmail.com with "Issue #8366" in the subject line and then report back here that you've send the email.

**Comment by masensio** [comment]
Hi @tonihei,

Sorry for the delay. 
I´ll send you the media.exolist.json and the bug report to the email you provide me.

**Comment by tonihei** [comment]
I can't see the email unfortunately. Did you include "Issue #8366" in the subject line?

**Comment by masensio** [comment]
Hi @tonihei,
The Subject mail is: Issue #8366
I hope you can see that. 🙏

**Comment by tonihei** [comment]
Sorry for delay in checking for the email, but I'm still unable to find it.
