### ISSUE TITLE
IllegalStateException: Call to playAd without appropriate call to loadAd first.

### ISSUE THREAD

**Issue by nbasbous** [google/ExoPlayer#8377]
I got the following IllegalStateException 
```
java.lang.IllegalStateException: Call to playAd without appropriate call to loadAd first.
        at com.google.ads.interactivemedia.v3.internal.aoh.playAd(aoh:2)
        at com.google.ads.interactivemedia.v3.internal.ank.d(ank:6)
        at com.google.ads.interactivemedia.v3.internal.ane.r(ane:3)
        at com.google.ads.interactivemedia.v3.internal.ane.d(ane:125)
        at com.google.ads.interactivemedia.v3.internal.anj.d(anj:5)
        at com.google.ads.interactivemedia.v3.internal.ang.shouldOverrideUrlLoading(ang:2)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:77)
        at xS.g(chromium-SystemWebViewGoogle.aab-stable-428010100:1)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-SystemWebViewGoogle.aab-stable-428010100:16)
        at android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:7091)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```
ExoPlayer version: 2.12.1
IMA SDK version: 3.21.0

**Comment by andrewlewis** [comment]
Please could you provide some steps to reproduce the issue (including the ad tag you are using)? If you don't want to share it here you can email the information to `dev.exoplayer@gmail.com` with subject "Issue #8377". Thanks.

**Comment by nbasbous** [comment]
I sent needed info to dev.exoplayer@gmail.com with subject "Issue #8377"

**Comment by andrewlewis** [comment]
@nbasbous Based on the error message, it looks like you are actually using IMA SDK-owned ad playback, as defined at the start of [this page](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/custom_ad_playback). The implementation is outside the ExoPlayer codebase, so we can't provide support, but I filed an internal bug to ask the IMA SDK team for help anyway [internal: b/177221707] and will plan to update this issue if more information becomes available. For future reference, here is the [forum for IMA SDK support](https://groups.google.com/g/ima-sdk), and you may wish to post an issue there and reference that bug number.

**Comment by andrewlewis** [comment]
@nbasbous The ad tag provided via email seems not to be returning any valid ads. Could you provide a new ad tag? Also, have you seen any changes of behavior with the latest (or recent) versions of the IMA SDK?
