### ISSUE TITLE
Api 19 (Android 4) Binary XML file Error ?

### ISSUE THREAD

**Issue by inat-tv** [google/ExoPlayer#8421]
**Hello to everyone. It gave the following error on Android 4. I just couldn't figure it out. Has Android 4 support been lost?**

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{***.PlayerActivity}: android.view.InflateException: Binary XML file line #10: Error inflating class com.google.android.exoplayer2.ui.PlayerView
     FATAL EXCEPTION: Thread-312
Process: com.***.***, PID: 7777
java.lang.RuntimeException: Unable to start activity ComponentInfo{***.PlayerActivity}: android.view.InflateException: Binary XML file line #10: Error inflating class com.google.android.exoplayer2.ui.PlayerView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
	at android.app.ActivityThread.access$800(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:11)
	at androidx.test.espresso.base.UiControllerImpl.n(UiControllerImpl.java:6)
	at androidx.test.espresso.base.UiControllerImpl.m(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:6)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:15)
	at androidx.test.espresso.action.Tap.b(Tap.java)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5001)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class com.google.android.exoplayer2.ui.PlayerView
	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at androidx.appcompat.app.AppCompatDelegateImpl.B()
	at androidx.appcompat.app.e.setContentView()
	at ***.PlayerActivity.onCreate()
	at android.app.Activity.performCreate(Activity.java:5231)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:2)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
	... 25 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	... 37 more
Caused by: android.view.InflateException: Binary XML file line #128: Error inflating class TextView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at com.google.android.exoplayer2.ui.g.<init>()
	at com.google.android.exoplayer2.ui.PlayerView.<init>()
	at com.google.android.exoplayer2.ui.PlayerView.<init>()
	... 40 more
Caused by: android.content.res.Res
```

**Comment by ojw28** [comment]
We still support API level 19. I tried modifying the demo app to use `PlayerView` rather than `StyledPlayerView`, and it worked fine for me on an API level 19 device. Without complete information as requested in the issue template, it's not possible for us to assist further.

**Comment by inat-tv** [comment]
I am using PlayerView. I made a special design. Could it be due to drawable resource?

**Comment by ojw28** [comment]
Yes, it's almost certainly due to your customisation. Note that the stack trace tells you the exact line in the layout file being inflated that causes the problem:
```
Binary XML file line #128
```
If you turned obfuscation off, the stack trace would also tell you the exact line in code where the layout file is inflated, which would allow you to know which layout file to look at. This, together with some investigation, should allow you to work out what's wrong.

Closing, since customised UI components are not part of ExoPlayer and debugging them falls outside the scope of this issue tracker.

**Comment by inat-tv** [comment]
The problem was fixed when I removed the items I marked as "android:visibility="gone"" in the image below :)

![Adsız](https://user-images.githubusercontent.com/31779629/104787113-cc10c600-579f-11eb-9b76-ca78071f0f85.png)
