### ISSUE TITLE
HttpDataSourceException:SocketTimeoutException

### ISSUE THREAD

**Issue by fonebinary** [google/ExoPlayer#8449]
Hi, 
I am getting SocketTimeoutException on a very good network. I am not able to understand this is an exoplayer/okhttp issue or issue with my network.

**Error**
```
"error_msg":"com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect<->
--> GET http://XYZ\/279\/ac760f157a9cf82a96ac1440b01bdf18_160.mp4 Icy-MetaData: 1 User-Agent: com.media/7.7 (Linux;Android 9) ExoPlayerLib/2.11.4 Accept-Encoding: identity --> END GET 
<-- HTTP FAILED: java.net.SocketTimeoutException: failed to connect to ABC.com/ip (port 80) from /192.168.1.102 (port 40058) after 10000ms 
<-- HTTP FAILED: java.net.SocketTimeoutException: failed to connect to ABC.com/ip (port 80) from /192.168.1.102 (port 40072) after 10000ms 
--> GET http://XYZ/279/ac760f157a9cf82a96ac1440b01bdf18_160.mp4 Icy-MetaData: 1 User-Agent: com.media/7.7 (Linux;Android 9) ExoPlayerLib/2.11.4 Accept-Encoding: identity 
--> END GET 
<-- HTTP FAILED: java.net.SocketTimeoutException: failed to connect to ABC.com/ip (port 80) from /192.168.1.102 (port 40082) after 10000ms 
--> GET http://XYZ/279/ac760f157a9cf82a96ac1440b01bdf18_160.mp4 Icy-MetaData: 1 User-Agent: com.media/7.7 (Linux;Android 9) ExoPlayerLib/2.11.4 Accept-Encoding: identity 
--> END GET 
<-- HTTP FAILED: java.net.SocketTimeoutException: failed to connect to ABC.com/ip (port 80) from /192.168.1.102 (port 40098) after 10000ms "
```

**Comment by lcf87** [comment]
It's a bit surprising this happens, could you try playing the media using another player (vlc) or if you could provide a link to the media?

**Comment by ujjwalagrawal17** [comment]
Hi, 

Multiple users in our production app were facing the same issue. 


**Crash Logs:**

```
Fatal Exception: com.google.android.exoplayer2.upstream.y$b: java.net.SocketTimeoutException: timeout
       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:14)
       at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:7)
       at com.google.android.exoplayer2.upstream.TeeDataSource.read(TeeDataSource.java:12)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(CacheDataSource.java:28)
       at com.google.android.exoplayer2.upstream.cache.CacheUtil.readAndDiscard(CacheUtil.java:111)
       at com.google.android.exoplayer2.upstream.cache.CacheUtil.cache(CacheUtil.java:157)
       at com.google.android.exoplayer2.upstream.cache.CacheUtil.cache(CacheUtil.java:17)
       at com.codenicely.shaadicardmaker.services.video.VideoPreLoadingService.cacheVideo(VideoPreLoadingService.java:14)
       at com.codenicely.shaadicardmaker.services.video.VideoPreLoadingService.access$cacheVideo(VideoPreLoadingService.java) at com.codenicely.shaadicardmaker.services.video.VideoPreLoadingService$preCacheVideo$1.invokeSuspend(VideoPreLoadingService.java:20)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:9)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:116)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:14)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:28)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java)
       
```
       
Link to relevant stackoverflow answer: https://stackoverflow.com/a/58693882/5627216


**Relevant Code:** 

```
import android.app.IntentService
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.util.Log
import com.codenicely.shaadicardmaker.R
import com.codenicely.shaadicardmaker.application.BaseApplication
import com.codenicely.shaadicardmaker.common.Constants
import com.google.android.exoplayer2.upstream.DataSource
import com.google.android.exoplayer2.upstream.DataSpec
import com.google.android.exoplayer2.upstream.DefaultDataSourceFactory
import com.google.android.exoplayer2.upstream.cache.CacheKeyFactory
import com.google.android.exoplayer2.upstream.cache.CacheUtil
import com.google.android.exoplayer2.upstream.cache.SimpleCache
import com.google.android.exoplayer2.util.Util
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.Job
import kotlinx.coroutines.launch

class VideoPreLoadingService :
        IntentService(VideoPreLoadingService::class.java.simpleName) {
    private lateinit var mContext: Context
    private var simpleCache: SimpleCache? = null
    private var cachingJob: Job? = null
    private var videosList: ArrayList<String>? = null

    override fun onHandleIntent(intent: Intent?) {
        mContext = applicationContext
        simpleCache = BaseApplication.simpleCache

        if (intent != null) {
            val extras = intent.extras
            videosList = extras?.getStringArrayList(Constants.VIDEO_LIST)

            if (!videosList.isNullOrEmpty()) {
                preCacheVideo(videosList)
            }
        }
    }

    private fun preCacheVideo(videosList: ArrayList<String>?) {
        var videoUrl: String? = null
        if (!videosList.isNullOrEmpty()) {
            videoUrl = videosList[0]
            videosList.removeAt(0)
        } else {
            stopSelf()
        }
        if (!videoUrl.isNullOrBlank()) {
            Log.d("Home_Adapter", "inside Service")
            val videoUri = Uri.parse(videoUrl)
            //,0, 200 * 1024, null
            val dataSpec = DataSpec(videoUri,0,2 * 1024 * 1024,null)
            val defaultCacheKeyFactory = CacheUtil.DEFAULT_CACHE_KEY_FACTORY
            val progressListener =
                    CacheUtil.ProgressListener { requestLength, bytesCached, newBytesCached ->
                        val downloadPercentage: Double = (bytesCached * 100.0
                                / requestLength)
                    }
            val dataSource: DataSource =
                    DefaultDataSourceFactory(
                            mContext,
                            Util.getUserAgent(this, getString(R.string.app_name))).createDataSource()

            cachingJob = GlobalScope.launch(Dispatchers.IO) {
                cacheVideo(dataSpec, defaultCacheKeyFactory, dataSource, progressListener)
                preCacheVideo(videosList)
            }
        }
    }

    private fun cacheVideo(
            dataSpec: DataSpec,
            defaultCacheKeyFactory: CacheKeyFactory?,
            dataSource: DataSource,
            progressListener: CacheUtil.ProgressListener
    ) {
        Log.d("Home_Adapter", "insidestartPreLoadingService_cache")
        CacheUtil.cache(
                dataSpec,
                simpleCache,
                defaultCacheKeyFactory,
                dataSource,
                progressListener,
                null
        )
    }

    override fun onDestroy() {
        super.onDestroy()
        Log.d("Home_Adapter", "Destroy")
        cachingJob?.cancel()
    }
}
```

**Comment by ujjwalagrawal17** [comment]
@lcf87 can you reopen this issue ?
