### ISSUE TITLE
HLS Live stream not opening in ExoPlayer

### ISSUE THREAD

**Issue by needz** [google/ExoPlayer#8493]
Stream not opening on any device in ExoPlayer, not tracks detected, hard to track issue, while works in VLC.

http://18.194.188.118/haramain3/haramain.smil/master.m3u8

- ExoPlayer 2.12.2
- Android 11
- Android ADT-3

Any possible workarounds?

```
2021-01-23 13:49:47.030 27726-27905/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException: Playback stuck buffering and not loading
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:956)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2021-01-23 13:49:47.038 27726-27726/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=44.40, mediaPos=-40.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException: Playback stuck buffering and not loading
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:956)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    ]
```

**Comment by ojw28** [comment]
This is a problem with the stream, where it declares an audio track that it does not actually contain. The media should be fixed to not declare this track.

Please see https://github.com/google/ExoPlayer/issues/6112 for an identical case, and for a workaround that allows this stream type to be played.
