### ISSUE TITLE
Specific mkv video fails with "ParserException: Error parsing vorbis codec private"

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#8496]
Trying to play this video http://streams.videolan.org/samples/Matroska/haruhi.mkv with ExoPlayer, it fails with following exception:

```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.ParserException: Error parsing vorbis codec private
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$Track.parseVorbisCodecPrivate(MatroskaExtractor.java:2422)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$Track.initializeOutput(MatroskaExtractor.java:2051)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.endMasterElement(MatroskaExtractor.java:760)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$InnerEbmlProcessor.endMasterElement(MatroskaExtractor.java:1833)
        at com.google.android.exoplayer2.extractor.mkv.DefaultEbmlReader.read(DefaultEbmlReader.java:87)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.read(MatroskaExtractor.java:490)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1050)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

The same video plays just fine (both picture and sound) in system `VideoView`.

- ExoPlayer version number: 2.12.3 
- Android version: 10
- Android device: OnePlus 7

**Comment by kim-vde** [comment]
This is indeed a bug. I will implement a fix.

**Comment by kim-vde** [comment]
I added the fix to the [dev-v2](https://github.com/google/ExoPlayer/tree/dev-v2) branch. It will be added to the [release-v2](https://github.com/google/ExoPlayer/tree/release-v2)  branch in a few weeks, when ExoPlayer 2.13 is released.
