### ISSUE TITLE
Player fails to resume playing the content after turning back the mobile data.

### ISSUE THREAD

**Issue by shiv-u** [google/ExoPlayer#8513]
- URI to test content for reproduction - This issue is observed irrespective of the content.

- ExoPlayer version number - 2.12.1.

-  Steps to reproduce - 
 1) Click on a video to play
 2) Turn off the mobile data
 3) The player will continue playing until it has finished playing the buffered content.
 4) Turn on the mobile data and clicking on the resume button fails to continue playing the video.
 
- Device info - This issue is observed on multiple android devices.
   
 -  Exception encountered - 
```
  2021-01-27 16:09:34.262 12023-12023/? E/EventLogger: internalError [eventTime=0.07, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: ep: Exception in CronetUrlRequest: net::ERR_INTERNET_DISCONNECTED, ErrorCode=2, InternalErrorCode=-106, Retryable=false
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:447)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:764)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:579)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: ep: Exception in CronetUrlRequest: net::ERR_INTERNET_DISCONNECTED, ErrorCode=2, InternalErrorCode=-106, Retryable=false
        at org.chromium.net.impl.CronetUrlRequest.onError(:com.google.android.gms.dynamite_cronetdynamite@204714065@20.47.14 (100400-0):4)
    ]
```

**Comment by marcbaechinger** [comment]
I tried to repro this but I can't. It works as expected for me. I have the ExoPlayer demo app and the settings app in split screen side by side. Then I play a video in the demo app and in the network settings I disable 'Mobile data'. The mobile network icon in the status bar of the phone gets the cross added to indicate that the mobile network access is disabled. I see several stack traces like what you see and finally ExoPlayer gives up and after the buffer is depleted, the player fails and transitions to 'STATE_IDLE'.

Then I enable mobile data again and I wait until the cross in the status bar is removed from the icon, indicating that the mobile network is connected again. I resume playback and the player goes to STATE_BUFFERING and finally STATE_READY without any further exceptions. The demo app is [using the `EventLogger`](https://exoplayer.dev/listening-to-player-events.html#using-eventlogger) which nicely logs that behaviour as you can see below.

When doing this several times I had some cases where enabling mobile data took a while and the icon was still having the error cross in the status bar. So if I was too quick with pressing resume it resulted in another network error, but this is expected as the player needs to wait until the OS has the mobile connections again. Please make sure that's the mobile network is ready as well when you resume. 

I see that your exception stack trace is timestamped at `eventTime=0.07, mediaPos=0.00`, so I don't think that is from when you resume playback in your step 4) of the repro steps. I'd expect that eventTime and mediaPos is higher when resuming:

Your error:
```
2021-01-27 16:09:34.262 12023-12023/? E/EventLogger: internalError [eventTime=0.07, mediaPos=0.00, window=0, period=0, loadError
```

How do you disable/enable the mobile data? Please note that if you put the app with the player in the background, the player is recreated when coming to the foreground again. It then tries to restart and it possible that the OS does not have mobile network at this moment. 

I'd suggest that you add the EventLogger to your app if you haven't already. Then go through your repro steps again so you can observe all player state changes in the log. If you still think that the exception is thrown with the mobile network correctly working, please create a bug report right after this happens. Then upload it here. With this we can trace quite nicely what is going on, just like my example below.

```
E/EventLogger: playerFailed [eventTime=187.85, mediaPos=139.98, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:585)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: et: Exception in CronetUrlRequest: net::ERR_INTERNET_DISCONNECTED, ErrorCode=2, InternalErrorCode=-106, Retryable=false
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:453)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:764)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:579)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:126)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: et: Exception in CronetUrlRequest: net::ERR_INTERNET_DISCONNECTED, ErrorCode=2, InternalErrorCode=-106, Retryable=false
        at org.chromium.net.impl.CronetUrlRequest.onError(:com.google.android.gms.dynamite_cronetdynamite@210312097@21.03.12 (150400-0):4)
    ]
D/EventLogger: loading [eventTime=187.86, mediaPos=139.98, window=0, period=0, false]
D/EventLogger: state [eventTime=187.86, mediaPos=139.98, window=0, period=0, IDLE]
D/EventLogger: isPlaying [eventTime=187.88, mediaPos=139.98, window=0, period=0, false]
D/EventLogger: state [eventTime=383.93, mediaPos=139.98, window=0, period=0, BUFFERING]
D/EventLogger: loading [eventTime=383.95, mediaPos=139.98, window=0, period=0, true]
D/EventLogger: timeline [eventTime=384.98, mediaPos=139.98, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
D/EventLogger:   period [734.00]
D/EventLogger:   window [734.00, true, false]
D/EventLogger: ]
D/EventLogger: videoEnabled [eventTime=385.00, mediaPos=139.98, window=0, period=0]
D/EventLogger: audioEnabled [eventTime=385.00, mediaPos=139.98, window=0, period=0]
D/EventLogger: tracks [eventTime=385.00, mediaPos=139.98, window=0, period=0
D/EventLogger:   MediaCodecVideoRenderer [
D/EventLogger:     Group:0, adaptive_supported=YES [
D/EventLogger:       [X] Track:0, id=1, mimeType=video/avc, bitrate=769255, codecs=avc1.42c01e, res=320x142, fps=24.0, supported=YES
D/EventLogger:       [X] Track:1, id=2, mimeType=video/avc, bitrate=1774254, codecs=avc1.4d401f, res=854x380, fps=24.0, supported=YES
D/EventLogger:       [X] Track:2, id=3, mimeType=video/avc, bitrate=7203938, codecs=avc1.4d4028, res=1280x570, fps=24.0, supported=YES
D/EventLogger:       [X] Track:3, id=4, mimeType=video/avc, bitrate=18316946, codecs=avc1.64002a, res=1920x856, fps=24.0, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger:   MediaCodecAudioRenderer [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=0, mimeType=audio/mp4a-latm, bitrate=131596, codecs=mp4a.40.2, channels=2, sample_rate=44100, language=en, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger:   TextRenderer []
D/EventLogger:   MetadataRenderer []
D/EventLogger:   CameraMotionRenderer []
D/EventLogger: ]
D/EventLogger: downstreamFormat [eventTime=385.32, mediaPos=139.98, window=0, period=0, id=0, mimeType=audio/mp4a-latm, bitrate=131596, codecs=mp4a.40.2, channels=2, sample_rate=44100, language=en]
D/EventLogger: audioDecoderInitialized [eventTime=385.53, mediaPos=139.98, window=0, period=0, c2.android.aac.decoder]
D/EventLogger: audioInputFormat [eventTime=385.53, mediaPos=139.98, window=0, period=0, id=0, mimeType=audio/mp4a-latm, bitrate=131596, codecs=mp4a.40.2, channels=2, sample_rate=44100, language=en]
D/EventLogger: downstreamFormat [eventTime=385.54, mediaPos=139.98, window=0, period=0, id=1, mimeType=video/avc, bitrate=769255, codecs=avc1.42c01e, res=320x142, fps=24.0]
D/EventLogger: videoDecoderInitialized [eventTime=385.66, mediaPos=139.98, window=0, period=0, c2.qti.avc.decoder]
D/EventLogger: videoInputFormat [eventTime=385.66, mediaPos=139.98, window=0, period=0, id=1, mimeType=video/avc, bitrate=769255, codecs=avc1.42c01e, res=320x142, fps=24.0]
D/EventLogger: audioSessionId [eventTime=386.19, mediaPos=139.98, window=0, period=0, 193]
D/EventLogger: videoSize [eventTime=388.05, mediaPos=139.98, window=0, period=0, 320, 142]
D/EventLogger: renderedFirstFrame [eventTime=388.05, mediaPos=139.98, window=0, period=0, Surface(name=null)/@0xef499a6]
D/EventLogger: state [eventTime=388.66, mediaPos=139.99, window=0, period=0, READY]
```

**Comment by shiv-u** [comment]
@marcbaechinger In my phone (Redmi K20 Pro) I can disable mobile data by swiping down tool bar, if you switch between settings app and demo while turning on the data the player is able to resume back but if you're able to turn of the network without switching to another activity the issue still persists.

**Comment by marcbaechinger** [comment]
Thanks! I think you are resuming before mobile data actually is available as I described above. You need to wait a bit longer in this case. ExoPlayer can not connect before the OS has mobile data again. 

I still think this is working correctly if mobile data is available. You need to wait a bit longer probably as explained above. 

Please provide me with a bug report with the EventLoggeradded to you app if you want me to look into this some further.

**Comment by shiv-u** [comment]
@marcbaechinger I've resolved the issue, I was missing  `playerView.setPlaybackPreparer(this);` in playeractivity. I should have looked into my code in depth before raising this issue, sorry for this inconvenience .
