### ISSUE TITLE
Specific mkv video fails with EOFException from SampleDataQueue.sampleData()

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#8516]
Trying to play this short sample video https://samples.ffmpeg.org/Matroska/compressed/atlantis405-test.mkv with ExoPlayer, it fails with following:

```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.io.EOFException
        at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:193)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:530)
        at com.google.android.exoplayer2.extractor.TrackOutput.sampleData(TrackOutput.java:161)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.writeToOutput(MatroskaExtractor.java:1672)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.writeSampleData(MatroskaExtractor.java:1519)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.binaryElement(MatroskaExtractor.java:1240)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$InnerEbmlProcessor.binaryElement(MatroskaExtractor.java:1853)
        at com.google.android.exoplayer2.extractor.mkv.DefaultEbmlReader.read(DefaultEbmlReader.java:141)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.read(MatroskaExtractor.java:490)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1050)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

```
Video: MPEG4 Video (H264) 1280x720 25fps [V: Stargate Atlantis S04E05 720p x264-V [eng] (h264 high L5.1, yuv420p, 1280x720) [default]]
Audio: Dolby AC3 48000Hz 6ch 384kbps [A: AC3 5.1 PAL [eng] (ac3, 48000 Hz, 5.1, 384 kb/s) [default]]
```

The same video plays just fine in system `VideoView` (picture plays always, AC3 audio plays if there's platform decoder). I got same results on two different devices I have tested.

- ExoPlayer version number: 2.12.3
- Android version: 10
- Android device: OnePlus 7

**Comment by marcbaechinger** [comment]
I can repro this. There is a HTTP/416 just before the EOF. Seems like the range request can't be served. This needs some investigation.

**Comment by moneytoo** [comment]
My report is based on testing the file locally. This sample is just a 10 MB head cut. I'm going through some possibly obscure videos and reporting what videos are playable in VideoView but are failing in ExoPlayer.

**Comment by marcbaechinger** [comment]
ok, thanks for clarification. I think it's likely that the reason for why we try to do a range request that is exceeding the file size is related to the same root cause.

**Comment by ojw28** [comment]
Clipping the end off an MKV file does not generally result in a valid MKV file. So yes, that's the root cause.
