### ISSUE TITLE
OutOfMemory errors on some device

### ISSUE THREAD

**Issue by miniesahni1** [google/ExoPlayer#8518]
**Observed Behaviour**
We are experiencing fatal crashes due to OutOfMemory errors. Able to replicate issue on Samsung S20 Plus and OnePlus 6T. 
On Samsung S20 Plus - Application crash
OnePlus 6T - Playback pause in between

**Reproduction steps**
We are trying to play two video tracks using MergingMediaSource
Steps: 
1.Create MediaSource using MergingMediaSource(with two media).
2. Create two Video renderers  in overriden method “buildVideoRenderers” of DefaultRenderersFactory.
3. Create custom track selection to assign tracks to these renderer.
When playback start, we get OutOfMemory errors.

**Detail of media used:**
Resolution : 3840*2160
Duration of media: more than 1min

**Report captured from the device** 
/com.sample.exoplayer E/LoadTask: OutOfMemory error loading stream
      java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 1048 free bytes and 1048B until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 524288 bytes)
        at com.google.android.exoplayer2.source.SampleDataQueue.preAppend(SampleDataQueue.java:394)
        at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:183)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:530)
        at com.google.android.exoplayer2.extractor.TrackOutput.sampleData(TrackOutput.java:161)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:541)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:200)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1050)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
 
 
FATAL EXCEPTION: Loader:ProgressiveMediaPeriod
    java.lang.OutOfMemoryError: Failed to allocate a 2736 byte allocation with 33536 free bytes and 32KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 1310720 bytes)
        at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
        at java.lang.StringBuilder.<init>(StringBuilder.java:102)
        at java.lang.String.replace(String.java:2372)
        at com.google.android.exoplayer2.util.Log.appendThrowableString(Log.java:163)
        at com.google.android.exoplayer2.util.Log.e(Log.java:127)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:442)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

- ExoPlayer version number - 2.12.2
- Android version - Android 10

**Comment by marcbaechinger** [comment]
The OOM happens when the player tries to allocate more memory in `SampleDataQueue.preAppend`. I think that is just when the player increases the size of the data buffer to buffer downloaded data for playback.

I see that the resolution of the video is pretty high and I don't know how you configured the buffering behavior of the player. So it may certainly be that loading two videos in parallel my exceed the memory available to your app. The amount of available memory is not static and [depends on what is going on in the system](https://developer.android.com/topic/performance/memory) and likely on how much memory a given device has in total. So this may explain why this happens on some devices and not on others.

So this does not look like a bug of the player to me, but rather like a question of configuration or whats actually possible on a given device with the available memory and other apps in the background.

What happens if you do the same with a significantly lower-res video? If that works you may be able to reconfigure the player (see `DefaultLoadControl`) and decrease the buffer sizes so you can keep the memory consumption of your app below the critical threshold on these devices.
