### ISSUE TITLE
DataSourceException.POSITION_OUT_OF_RANGE

### ISSUE THREAD

**Issue by vhow** [google/ExoPlayer#8521]
- issue
```java
E/ExoPlayerImplInternal: Source error
E/ExoPlayerImplInternal:   com.google.android.exoplayer2.upstream.DataSourceException
E/ExoPlayerImplInternal:       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:284)
E/ExoPlayerImplInternal:       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:962)
E/ExoPlayerImplInternal:       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:764)
```
p.s. 

1. The audio has been cached, `isCached` returns `true`

```java
    boolean isCached(final String key) {
        Log.d(TAG, "isCached() called with: key = [" + key + "]");
        final Set<String> keys = mCache.getKeys();
        if (!keys.contains(key)) {
            Log.v(TAG, "isCached: does not contain this key.");
            return false;
        }
        final NavigableSet<CacheSpan> spans = mCache.getCachedSpans(key);
        if (spans.isEmpty()) {
            Log.v(TAG, "isCached: spans is empty.");
            return false;
        }
        for (CacheSpan span : spans) {
            final boolean cached = mCache.isCached(key, span.position, span.length);
            if (!cached) {
                Log.v(TAG, "isCached: is not fully cached.");
                return false;
            }
        }
        Log.d(TAG, "isCached: is fully cached.");
        return true;
    }
```

2. The `Cache` is created in this way 

```java
    mCache = new SimpleCache(
            new File(context.getCacheDir(), "offline"),
            new LeastRecentlyUsedCacheEvictor(maxCacheBytes),
            databaseProvider);
```
 
- ExoPlayer 2.11.7
- Android 8.0

**Comment by icbaker** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.
