### ISSUE TITLE
MediaCodecVideoRenderer on playing ClearKey DRM video

### ISSUE THREAD

**Issue by ruthwikkk** [google/ExoPlayer#8524]
I have implemented video playback using ClearKey DRM in my app. In most of the devices the video is playing smoothly but in some specific devices I'm getting `MediaCodecVideoRenderer` exception. On further investigation we found that in these devices the PlayerView uses `TextureView` for rendering rather than `SurfaceView`. I have read `TextureView` doesn't support playback for secure content [here](https://github.com/google/ExoPlayer/issues/370). I have tried forcefully enabling `SurfaceView` but still no luck. 
How can I resolve this ?

Exception log
```
ExoPlayerImplInternal E Playback error
                         E   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(3, nul
                            l, null, video/avc, avc1.640028, 1120439, null, [852, 480, 24.0], [-1, -1]), format_supported=YES
                         E       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
                         E       at android.os.Handler.dispatchMessage(Handler.java:107)
                         E       at android.os.Looper.loop(Looper.java:238)
                         E       at android.os.HandlerThread.run(HandlerThread.java:61)
                         E   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder i
                            nit failed: OMX.MTK.VIDEO.DECODER.AVC, Format(3, null, null, video/avc, avc1.640028, 1120439, null, [852, 480, 24.
                            0], [-1, -1])
                         E       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer
                            .java:1047)
                         E       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.jav
                            a:604)
                         E       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:
                            1470)
                         E       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.
                            java:640)
                         E       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java
                            :994)
                         E       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
                         E       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
                         E       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
                         E       ... 3 more
                         E   Caused by: android.media.MediaCodec$CodecException: start failed
                         E       at android.media.MediaCodec.native_start(Native Method)
                         E       at android.media.MediaCodec.start(MediaCodec.java:1898)
                         E       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.start(SynchronousMediaCodecAdapter.
                            java:48)
                         E       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1146)
                         E       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer
                            .java:1040)
```

Device Details where issue is recreated
Samsung J6+
SM-J610F - j6primelte
OS: Android 28 Pie

ExoPlayer Version: 2.12.2

**Comment by andrewlewis** [comment]
> On further investigation we found that in these devices the PlayerView uses `TextureView` for rendering rather than `SurfaceView`.

Just to clarify, I don't think we ever pick `TextureView` automatically -- it should be up to app code what kind of view to use. Generally I think we recommend using `SurfaceView` from Android N for all use cases.

> I have tried forcefully enabling `SurfaceView` but still no luck.

As in, you see the exact same error with clearkey DRM content (and not with non-DRM content) even with `SurfaceView`? If so I think we need to triage this as a general DRM issue (not to do with `TextureView`).

There may be some more descriptive error logging in logcat just before the stack trace. Could you attach a bug report taken just after reproducing the error, as that may help track down the root cause?

**Comment by ruthwikkk** [comment]
The log I provided is from user's side so I think its not possible to collect the logs you requested. 

I used the following code to check view type 
`playerView.videoSurfaceView !is TextureView`
and result was `false` for devices facing playback issue.

One more information is to add is we requested the user to install [DRMInfo](https://play.google.com/store/apps/details?id=com.androidfung.drminfo&hl=en_IN&gl=US) app to collect DRM support related data and I'm attaching the screenshot.

![sc_1](https://user-images.githubusercontent.com/25474982/106589289-dd185000-6571-11eb-96b5-326d4ccddb91.jpeg)

Seems the ClearKey version the user has is 1.1. 
Does this issue has any relation with ClearKey version ?

**Comment by andrewlewis** [comment]
I think you need to use `SurfaceView` for playback to work with DRM. Can you reproduce this error when using `SurfaceView`?

**Comment by ruthwikkk** [comment]
Yes the issue is reproduced in `SurfaceView` also.  
I tried to set the surface type as SurfaceView by
`app:surface_type="surface_view" `
and still the playback showed error.

**Comment by andrewlewis** [comment]
It sounds like you can reproduce this locally, so can you provide a bug report taken right after doing that?

Does the layout inspector show that a `SurfaceView` is really being used (not overridden elsewhere)?

**Comment by ruthwikkk** [comment]
Actually I don't have physical access to the device. 
The error log we collected was by giving custom log build to user. 
Is there any method to check the SurfaceView override programmatically so I can pull that data from user ?

**Comment by andrewlewis** [comment]
You could add code to log the type of the output view (just reusing the getter you called before `playerView.videoSurfaceView`).

If the user is able to provide the stack trace, can you ask them to run `adb logcat` and provide the logging for a few seconds just before the stack trace is logged too?

**Comment by ruthwikkk** [comment]
Okey I'll try, just give 24h to collect the details requested.

**Comment by ruthwikkk** [comment]
```
I ACodec  :  [] Now uninitialized
I ACodec  : [] onAllocateComponent
W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
I OMXClient: IOmx service obtained
I ACodec  : [OMX.Exynos.avc.dec] Now Loaded
D SurfaceUtils: connecting to surface 0xbd12a808, reason connectToSurface
I MediaCodec: [OMX.Exynos.avc.dec] setting surface generation to 3638275
D SurfaceUtils: connecting to surface 0xbd12a808, reason connectToSurface(reconnect)
D SurfaceUtils: disconnecting from surface 0xbd12a808, reason connectToSurface(reconnect)
W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
I ACodec  : codec does not support config priority (err -1010)
I ACodec  : app-pid(3553)
I ACodec  : can't find wfdsink-exynos-enable
I ACodec  : [OMX.Exynos.avc.dec] Now Loaded->Idle
I ACodec  : [OMX.Exynos.avc.dec] configureOutputBuffersFromNativeWindow setBufferCount : 8, minUndequeuedBuffers : 4
D SurfaceUtils: set up nativeWindow 0xbd12a808 for 1920x1080, color 0x121, rotation 0, usage 0x2900
I MediaCodec: setCodecState state : 0
I ACodec  : [OMX.Exynos.avc.dec] Now Idle->Executing
I ACodec  : [OMX.Exynos.avc.dec] Now Executing
I ACodec  : [OMX.Exynos.avc.dec] calling emptyBuffer 1 w/ codec specific data, size : 29
I ACodec  : [OMX.Exynos.avc.dec] calling emptyBuffer 2 w/ codec specific data, size : 8
I ACodec  :  [] Now uninitialized
I ACodec  : [] onAllocateComponent
I OMXClient: IOmx service obtained
I ACodec  : [OMX.Exynos.avc.dec] Now handling output port settings change
W AHierarchicalStateMachine: Warning message AMessage(what = 'omxI') = {
W AHierarchicalStateMachine:   int32_t type = 0
W AHierarchicalStateMachine:   int32_t event = 3
W AHierarchicalStateMachine:   int32_t data1 = 1
W AHierarchicalStateMachine:   int32_t data2 = 117440527
W AHierarchicalStateMachine: } unhandled in root state.
D SurfaceUtils: set up nativeWindow 0xbd12a808 for 1920x1088, color 0x121, rotation 0, usage 0x2900
I ACodec  : codec does not support config operating rate (err -2147483648)
I ACodec  : [OMX.Exynos.avc.dec] Now Executing
I ACodec  : [OMX.Exynos.avc.dec] configureOutputBuffersFromNativeWindow setBufferCount : 15, minUndequeuedBuffers : 4
I ACodec  : codec does not support config priority (err -2147483648)
I ACodec  : [OMX.google.aac.decoder] Now Loaded->Idle
I ACodec  : [OMX.google.aac.decoder] Now Loaded
I ACodec  : app-pid(3553)
I ACodec  : [OMX.google.aac.decoder] Now Idle->Executing
I ACodec  : [OMX.google.aac.decoder] Now Executing
I ACodec  : [OMX.google.aac.decoder] calling emptyBuffer 1 w/ codec specific data, size : 5
I MediaCodec: setCodecState state : 1
I ACodec  : [OMX.google.aac.decoder] Now handling output port settings change
I ACodec  : [OMX.google.aac.decoder] Now Executing
D AudioTrack: setVolume(1.000000, 1.000000) pid : 3553
W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
W FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_session_max_duration_min'.
W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
I AudioTrack: updateAudioTranstionLength FadeIn[0] FadeOut[0] FadeInRing[0]
W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
I ACodec  : [OMX.Exynos.avc.dec] signalFlush
I ACodec  : [OMX.Exynos.avc.dec] ExecutingState flushing now (codec owns 4/5 input, 2/15 output).
I ACodec  : [OMX.Exynos.avc.dec] Now Flushing
I ACodec  : [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,0)
I ACodec  : [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,1)
I ACodec  : [OMX.Exynos.avc.dec] Now Executing
I ACodec  : [OMX.Exynos.avc.dec] signalFlush
I ACodec  : [OMX.Exynos.avc.dec] ExecutingState flushing now (codec owns 0/5 input, 11/15 output).
I ACodec  : [OMX.Exynos.avc.dec] Now Flushing
I ACodec  : [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,0)
D ConnectivityManager: requestNetwork; CallingUid : 10259, CallingPid : 3553, PackageName : me.entri.entrime
I ACodec  : [OMX.Exynos.avc.dec] Now Executing
I ACodec  : [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,1)
W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
D ViewRootImpl@7c28aa5[VideoActivityV3]: Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x1 surface={true 3028525056} changed=false
D SurfaceView: show() Surface(name=SurfaceView - me.entri.entrime/me.entri.entrime.activities.VideoActivityV3@3f25a88@0[3553])/@0x212fdbd android.view.SurfaceView{3f25a88 V.E...... ......ID 0,0-711,400}
D SurfaceView: surfaceChanged (711,400) 1 #5 android.view.SurfaceView{3f25a88 V.E...... ......ID 0,0-711,400}

W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
I ACodec  : [OMX.Exynos.avc.dec] Now handling output port settings change
I ACodec  : [OMX.Exynos.avc.dec] configureOutputBuffersFromNativeWindow setBufferCount : 15, minUndequeuedBuffers : 4
I ACodec  : [OMX.Exynos.avc.dec] Now Executing
W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
D ViewRootImpl@7c28aa5[VideoActivityV3]: ViewPostIme pointer 1
:20953}
I ACodec  : [OMX.Exynos.avc.dec] Now Flushing
D ViewRootImpl@7c28aa5[VideoActivityV3]: ViewPostIme pointer 1
I ACodec  : [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,0)
I ACodec  : [OMX.Exynos.avc.dec] signalFlush
I ACodec  : [OMX.Exynos.avc.dec] ExecutingState flushing now (codec owns 4/5 input, 2/15 output).
I ACodec  : [OMX.google.aac.decoder] signalFlush
I ACodec  : [OMX.google.aac.decoder] Now Executing
D AudioTrack: setVolume(1.000000, 1.000000) pid : 3553
I ACodec  : [OMX.google.aac.decoder] FlushingState onOMXEvent(0,1,0)
I ACodec  : [OMX.google.aac.decoder] Now Flushing
W FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_session_max_duration_min'.
I ACodec  : [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,1)
I ACodec  : [OMX.Exynos.avc.dec] Now Executing

```

log pulled from users device just before the exception. Please check @andrewlewis

**Comment by andrewlewis** [comment]
I didn't notice any useful diagnostic info there (although I don't think there's any sign of unexpected codec error logging at all among the logging so possibly it wasn't taken right after seeing the error).

There isn't much else we can do to help I'm afraid. As mentioned above I'd recommend only using `SurfaceView`.

**Comment by ruthwikkk** [comment]
As I mentioned earlier I'm using `SurfaceView` for playback. I haven't applied any settings on that side but in some particular devices, somehow its falling back to `TextureView`, which causing the exception.

**Comment by andrewlewis** [comment]
I think any fallback to `TextureView` must be functionality that's in the app (as mentioned in my first comment).
