### ISSUE TITLE
OfflineLicenseHelper.renewLicense() throw android.media.MediaDrm$MediaDrmStateException: Failed to get key request

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#8554]
Hi, I'm currently trying to use the ExoPlayer offline feature into my app and I encounter an issue with License renewal.

ExoPlayer : 2.12.3

Android Version : 
- Android 10
- Android 11

Android Device :
- OnePlus Nord (AC2003)
- OnePlus 5 (A5000)
- Huawei P30 Lite (MAR-LX1A)
- Emulator

DRM : Widevine L3

I use OfflineLicenseHelper to get the DRM License and it works fine. I'm able to successfully get the license and I can play the video offline.

But when I try to renew the license I got the following error : 

```
com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:518)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:513)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:464)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:420)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:288)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:686)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:626)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:513)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.openBlockingKeyRequest(OfflineLicenseHelper.java:286)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.blockingKeyRequest(OfflineLicenseHelper.java:269)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.renewLicense(OfflineLicenseHelper.java:207)
        at com.google.android.exoplayer2.demo.DownloadTracker$WidevineOfflineLicenseFetchTask.doInBackground(DownloadTracker.java:409)
        at com.google.android.exoplayer2.demo.DownloadTracker$WidevineOfflineLicenseFetchTask.doInBackground(DownloadTracker.java:372)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error
        at android.media.MediaDrm.getKeyRequest(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:199)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:460)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:420) 
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:288) 
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:686) 
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:626) 
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:513) 
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.openBlockingKeyRequest(OfflineLicenseHelper.java:286) 
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.blockingKeyRequest(OfflineLicenseHelper.java:269) 
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.renewLicense(OfflineLicenseHelper.java:207) 
        at com.google.android.exoplayer2.demo.DownloadTracker$WidevineOfflineLicenseFetchTask.doInBackground(DownloadTracker.java:409) 
        at com.google.android.exoplayer2.demo.DownloadTracker$WidevineOfflineLicenseFetchTask.doInBackground(DownloadTracker.java:372) 
        at android.os.AsyncTask$3.call(AsyncTask.java:394) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923)
```
I successfully reproduced the issue with the ExoPlayer sample app. 
In WidevineOfflineLicenseFetchTask I try to renew the license just after getting it like that : 

```
try {
  keySetId = offlineLicenseHelper.downloadLicense(format);
  offlineLicenseHelper.renewLicense(keySetId)
} catch (DrmSession.DrmSessionException e) {
  drmSessionException = e;
} finally {
  offlineLicenseHelper.release();
}
```

When the application tries to download the video, it will get the license and try to renew it immediately.

All videos in "Widevine DASH (policy test)" section of the sample app fail, but videos in section "Widevine DASH (MP4, H264)" work fine.

Maybe this issue depends of the type of DRM used. I don't know if they are any difference between this two videos.

**Comment by icbaker** [comment]
The DRM license policy determines whether an offline license can be renewed or not.

In this case, the policies governing the samples in the "Widevine DASH (policy test)" don't allow renewal, hence the failures. Meanwhile the policy governing the samples in "Widevine DASH (MP4, H264)" does allow renewal.

In general it doesn't really make sense to try and perform DRM operations like renewal on content where you don't control/know the license policy (like the samples in the demo app).

If you're a Widevine partner you should reach out to them for support regarding testing different license policies.
