### ISSUE TITLE
With exoplayer demo app v2.13.1 tunneling mode enabled, playback fails if unplug the HDMI

### ISSUE THREAD

**Issue by Sasikumartech** [google/ExoPlayer#8599]
In exoplayer demo app v2.13.1, we enabled video tunneling feature.
While playing the  video, if we unplug the HDMI then the playback get failed and it throws the below error and exception.

```
02-16 14:26:47.275 12748 12889 E AudioTrack-JNI: Error -32 during AudioTrack native read
02-16 14:26:47.278  3608 12920 W AudioFlinger: An invalidated track shouldn't be in active list
02-16 14:26:47.280  3608  4220 W APM::AudioOutputDescriptor: close client with port ID 90 still active on output 89
02-16 14:26:47.288 12748 12889 E android.media.AudioTrack: AudioTrack.write() could not write timestamp header!
...
02-16 14:26:47.314  3608  3675 W APM_AudioPolicyManager: stopOutput() no output for client 90
...
02-16 14:26:47.316  3394  3394 W NEXUS   : nexus_playpump: NEXUS_Playpump_Stop: 0000000058ca6d16 playpump already stopped
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal: Recoverable playback error
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(0, null, null, audio/mp4a-latm, mp4a.40.2, 134359, en, [-1, -1, -1.0], [2, 44100]), format_supported=YES
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:103)
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:214)
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.audio.AudioSink$WriteException: AudioTrack write failed: -6
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.DefaultAudioSink.writeBuffer(DefaultAudioSink.java:928)
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.DefaultAudioSink.processBuffers(DefaultAudioSink.java:852)
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:805)
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:630)
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1854)
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:824)
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:947)
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:477)
02-16 14:26:47.318 12748 12889 W ExoPlayerImplInternal:       ... 3 more
```

Is there any issue with tunneling mode?

**Comment by krocard** [comment]
From the log, the issue comes from audio passthrough, not video tunneling.
Audio passthrough is invalidated on HDMI disconnection, this is a known limitation of ExoPlayer. The capability of the device are determined at construction and are not updated on external events (such as HDMI disconnection).

If an app wants to support this use-case, it should make use of [AudioCapabilitiesReceiver](https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/audio/AudioCapabilitiesReceiver.java).
When the audio capability changes, release and recreate the player.
