### ISSUE TITLE
Hello Guys,  I'm getting this error in exoplayer while playing videos. Please help me out if anybody has faced this issue or has an idea about this.  Thank you.

### ISSUE THREAD

**Issue by yijiaren1217** [google/ExoPlayer#8601]
ExoPlayerImplInternal: Renderer error: index=1, type=audio, format=Format(2, null, null, audio/mpeg, null, -1, ```, [-1, -1, -1.0], [1, 32000]), rendererSupport=YES
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.ext.ffmpeg.FfmpegDecoderException: Unexpected decode error
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.render(SimpleDecoderAudioRenderer.java:305)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.ext.ffmpeg.FfmpegDecoderException: Unexpected decode error
        at com.google.android.exoplayer2.ext.ffmpeg.FfmpegDecoder.createUnexpectedDecodeException(FfmpegDecoder.java:107)
        at com.google.android.exoplayer2.ext.ffmpeg.FfmpegDecoder.createUnexpectedDecodeException(FfmpegDecoder.java:38)
        at com.google.android.exoplayer2.decoder.SimpleDecoder.decode(SimpleDecoder.java:233)
        at com.google.android.exoplayer2.decoder.SimpleDecoder.run(SimpleDecoder.java:194)
        at com.google.android.exoplayer2.decoder.SimpleDecoder.access$000(SimpleDecoder.java:26)
        at com.google.android.exoplayer2.decoder.SimpleDecoder$1.run(SimpleDecoder.java:68)
     Caused by: java.lang.IllegalArgumentException
        at java.nio.Buffer.limit(Buffer.java:290)
        at java.nio.ByteBuffer.limit(ByteBuffer.java:818)
        at com.google.android.exoplayer2.ext.ffmpeg.FfmpegDecoder.decode(FfmpegDecoder.java:147)
        at com.google.android.exoplayer2.ext.ffmpeg.FfmpegDecoder.decode(FfmpegDecoder.java:38)
        at com.google.android.exoplayer2.decoder.SimpleDecoder.decode(SimpleDecoder.java:229)
        at com.google.android.exoplayer2.decoder.SimpleDecoder.run(SimpleDecoder.java:194) 
        at com.google.android.exoplayer2.decoder.SimpleDecoder.access$000(SimpleDecoder.java:26) 
        at com.google.android.exoplayer2.decoder.SimpleDecoder$1.run(SimpleDecoder.java:68)

**Comment by christosts** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can
be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.
