### ISSUE TITLE
Codec error in mp4 video playing

### ISSUE THREAD

**Issue by AlinaRakhimova** [google/ExoPlayer#8609]
I got an exception when I try to play mp4 video 

**Version of ExoPlayer being used**
Version:2.11.4 (checked also on the last version)

**Device(s) and version(s) of Android being used**
Android_1080p_API_24 (Emulator)
Android_1080p_API_26 (Emulator)
Redmi 4X (Android 7.1.2)

**A full bug report captured from the device**
D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1170x2532x30.0] [OMX.google.h264.decoder, video/avc] [generic_x86, Android SDK built for x86, Google, 24]
D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1170x2532x30.0] [OMX.google.h264.decoder, video/avc] [generic_x86, Android SDK built for x86, Google, 24]
I/OMXClient: MuxOMX ctor
I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 7472137
E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
I/ACodec: codec does not support config priority (err -2147483648)
E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001019)
    signalError(omxError 0x80001019, internalError -2147483648)
E/MediaCodec: Codec reported err 0x80001019, actionCode 0, while in state 6
I/OMXClient: MuxOMX ctor
I/ACodec: codec does not support config priority (err -2147483648)
I/ACodec: codec does not support config operating rate (err -2147483648)
D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1170x2532x30.0] [OMX.google.h264.decoder, video/avc] [generic_x86, Android SDK built for x86, Google, 24]
E/ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(1, null, null, video/avc, null, -1, null, [1170, 2532, 30.0], [-1, -1]), rendererSupport=NO_EXCEEDS_CAPABILITIES
      com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:735)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2568)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1520)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:721)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2052)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:777)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.flushOrReleaseCodec(MediaCodecVideoRenderer.java:724)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:636)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:569)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:168)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1136)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:891)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:382)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal: Reset failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2005)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:671)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:714)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onReset(MediaCodecRenderer.java:643)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onReset(MediaCodecVideoRenderer.java:578)
        at com.google.android.exoplayer2.BaseRenderer.reset(BaseRenderer.java:175)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:900)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:382)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by christosts** [comment]
The logs show the video is beyond the device's decoder capabilities

```
E/ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(1, null, null, video/avc, null, -1, null, [1170, 2532, 30.0], [-1, -1]), rendererSupport=NO_EXCEEDS_CAPABILITIES
```

I can see the video is enoded with H264 with resolution 1170x2532 at 30.0 fps. The logs show that the software decoder (OMX.google.h264.decoder) definitely cannot decode this video.

```
D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1170x2532x30.0] [OMX.google.h264.decoder, video/avc] [generic_x86, Android SDK built for x86, Google, 24]
```

I don't expect this video to play on the Android emulator since it has only the software decoder.

For the Redmi 4X, I cannot see in the logs which decoder was picked up, although the player would normally pick up the hardware decoder, which however still cannot play the video , indicated by `rendererSupport=NO_EXCEEDS_CAPABILITIES`. In cases where the device's decoders report that cannot handle a video, the player would still attempt playback on a best effort basis. 

I would recommend to use a lower resolution video in all cases.

**Comment by AlinaRakhimova** [comment]
@christosts Look at this please.
Logs for Redmi:

```
17:30:20.362 Surface (  914): getSlotFromBufferLocked: unknown buffer: 0x7f498f41a0
W/ 02-19 17:30:20.362 ACodec  (  914): [OMX.qcom.video.decoder.avc] can not return buffer 13 to native window
E/ 02-19 17:30:20.363 Surface (  914): getSlotFromBufferLocked: unknown buffer: 0x7f498f3fc0
W/ 02-19 17:30:20.363 ACodec  (  914): [OMX.qcom.video.decoder.avc] can not return buffer 12 to native window
E/ 02-19 17:30:20.377 ExoPlayerImplInternal(  914): Reset failed.
E/ 02-19 17:30:20.377 ExoPlayerImplInternal(  914):   java.lang.IllegalStateException
E/ 02-19 17:30:20.377 ExoPlayerImplInternal(  914):       at android.media.MediaCodec.native_stop(Native Method)
E/ 02-19 17:30:20.377 ExoPlayerImplInternal(  914):       at android.media.MediaCodec.stop(MediaCodec.java:2007)
E/ 02-19 17:30:20.377 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:671)
E/ 02-19 17:30:20.377 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:714)
E/ 02-19 17:30:20.377 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onReset(MediaCodecRenderer.java:643)
E/ 02-19 17:30:20.377 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onReset(MediaCodecVideoRenderer.java:578)
E/ 02-19 17:30:20.377 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.BaseRenderer.reset(BaseRenderer.java:175)
E/ 02-19 17:30:20.377 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:900)
E/ 02-19 17:30:20.377 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
E/ 02-19 17:30:20.377 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:382)
E/ 02-19 17:30:20.377 ExoPlayerImplInternal(  914):       at android.os.Handler.dispatchMessage(Handler.java:98)
E/ 02-19 17:30:20.377 ExoPlayerImplInternal(  914):       at android.os.Looper.loop(Looper.java:163)
E/ 02-19 17:30:20.377 ExoPlayerImplInternal(  914):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/ 02-19 17:30:20.389 chromium(  914): [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
E/ 02-19 17:30:20.389 OnboardingFragment$PlayerEventListener(  914): java.lang.IllegalStateException: There is an error while video preparing: com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
E/ 02-19 17:30:20.391 chromium(  914): [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
E/ 02-19 17:30:20.584 chromium(  914): [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
E/ 02-19 17:30:20.589 chromium(  914): [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
D/ 02-19 17:30:20.749 MediaCodecInfo(  914): NoSupport [sizeAndRate.support, 1170x2532x29.998811721801758] [OMX.qcom.video.decoder.avc, video/avc] [santoni, Redmi 4X, Xiaomi, 25]
D/ 02-19 17:30:20.749 MediaCodecInfo(  914): NoSupport [sizeAndRate.support, 1170x2532x29.998811721801758] [OMX.google.h264.decoder, video/avc] [santoni, Redmi 4X, Xiaomi, 25]
D/ 02-19 17:30:20.750 MediaCodecInfo(  914): NoSupport [sizeAndRate.support, 1170x2532x29.998811721801758] [OMX.qcom.video.decoder.avc, video/avc] [santoni, Redmi 4X, Xiaomi, 25]
D/ 02-19 17:30:20.750 MediaCodecInfo(  914): NoSupport [sizeAndRate.support, 1170x2532x29.998811721801758] [OMX.qcom.video.decoder.avc, video/avc] [santoni, Redmi 4X, Xiaomi, 25]
D/ 02-19 17:30:20.751 MediaCodecInfo(  914): NoSupport [sizeAndRate.support, 1170x2532x29.998811721801758] [OMX.google.h264.decoder, video/avc] [santoni, Redmi 4X, Xiaomi, 25]
D/ 02-19 17:30:20.751 MediaCodecInfo(  914): NoSupport [sizeAndRate.support, 1170x2532x29.998811721801758] [OMX.qcom.video.decoder.avc, video/avc] [santoni, Redmi 4X, Xiaomi, 25]
D/ 02-19 17:30:20.757 MediaCodecInfo(  914): NoSupport [sizeAndRate.support, 1170x2532x29.998811721801758] [OMX.qcom.video.decoder.avc, video/avc] [santoni, Redmi 4X, Xiaomi, 25]
D/ 02-19 17:30:20.757 MediaCodecInfo(  914): NoSupport [sizeAndRate.support, 1170x2532x29.998811721801758] [OMX.google.h264.decoder, video/avc] [santoni, Redmi 4X, Xiaomi, 25]
I/ 02-19 17:30:20.785 OMXClient(  914): MuxOMX ctor
E/ 02-19 17:30:20.805 chromium(  914): [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
E/ 02-19 17:30:20.806 chromium(  914): [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
I/ 02-19 17:30:20.820 MediaCodec(  914): [OMX.qcom.video.decoder.avc] setting surface generation to 935939
I/ 02-19 17:30:20.822 ExtendedACodec(  914): setupVideoDecoder()
I/ 02-19 17:30:20.822 ExtendedACodec(  914): vpp-enable search is 0 and value is 0
I/ 02-19 17:30:20.843 ExtendedACodec(  914): Decoder will be in frame by frame mode
D/ 02-19 17:30:20.889 SurfaceUtils(  914): set up nativeWindow 0x7f4f3bbe10 for 1170x2532, color 0x7fa30c04, rotation 0, usage 0x2002900
E/ 02-19 17:30:20.894 chromium(  914): [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
E/ 02-19 17:30:20.903 chromium(  914): [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
I/ 02-19 17:30:20.952 OMXClient(  914): MuxOMX ctor
I/ 02-19 17:30:20.960 ACodec  (  914): codec does not support config priority (err -2147483648)
I/ 02-19 17:30:20.964 ACodec  (  914): codec does not support config priority (err -2147483648)
I/ 02-19 17:30:20.965 ACodec  (  914): codec does not support config operating rate (err -2147483648)
E/ 02-19 17:30:21.028 chromium(  914): [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
E/ 02-19 17:30:21.030 chromium(  914): [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
E/ 02-19 17:30:21.049 chromium(  914): [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
E/ 02-19 17:30:21.056 chromium(  914): [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
E/ 02-19 17:30:21.070 ACodec  (  914): [OMX.qcom.video.decoder.avc] ERROR(0x80001009)
E/ 02-19 17:30:21.070 ACodec  (  914): signalError(omxError 0x80001009, internalError -2147483648)
E/ 02-19 17:30:21.070 MediaCodec(  914): Codec reported err 0x80001009, actionCode 0, while in state 6
D/ 02-19 17:30:21.134 AudioTrack(  914): Client defaulted notificationFrames to 7688 for frameCount 15376
D/ 02-19 17:30:21.184 MediaCodecInfo(  914): NoSupport [sizeAndRate.support, 1170x2532x29.998811721801758] [OMX.qcom.video.decoder.avc, video/avc] [santoni, Redmi 4X, Xiaomi, 25]
D/ 02-19 17:30:21.185 MediaCodecInfo(  914): NoSupport [sizeAndRate.support, 1170x2532x29.998811721801758] [OMX.google.h264.decoder, video/avc] [santoni, Redmi 4X, Xiaomi, 25]
D/ 02-19 17:30:21.185 MediaCodecInfo(  914): NoSupport [sizeAndRate.support, 1170x2532x29.998811721801758] [OMX.qcom.video.decoder.avc, video/avc] [santoni, Redmi 4X, Xiaomi, 25]
E/ 02-19 17:30:21.186 ExoPlayerImplInternal(  914): Renderer error: index=0, type=video, format=Format(1, null, null, video/avc, null, -1, null, [1170, 2532, 29.998812], [-1, -1]), rendererSupport=NO_EXCEEDS_CAPABILITIES
E/ 02-19 17:30:21.186 ExoPlayerImplInternal(  914):   com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
E/ 02-19 17:30:21.186 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
E/ 02-19 17:30:21.186 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:735)
E/ 02-19 17:30:21.186 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
E/ 02-19 17:30:21.186 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
E/ 02-19 17:30:21.186 ExoPlayerImplInternal(  914):       at android.os.Handler.dispatchMessage(Handler.java:98)
E/ 02-19 17:30:21.186 ExoPlayerImplInternal(  914):       at android.os.Looper.loop(Looper.java:163)
E/ 02-19 17:30:21.186 ExoPlayerImplInternal(  914):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/ 02-19 17:30:21.186 ExoPlayerImplInternal(  914):   Caused by: java.lang.IllegalStateException
E/ 02-19 17:30:21.186 ExoPlayerImplInternal(  914):       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/ 02-19 17:30:21.186 ExoPlayerImplInternal(  914):       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2570)
E/ 02-19 17:30:21.186 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1520)
E/ 02-19 17:30:21.186 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:721)
E/ 02-19 17:30:21.186 ExoPlayerImplInternal(  914):       ... 5 more
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914): Disable failed.
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914):   java.lang.IllegalStateException
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914):       at android.media.MediaCodec.native_flush(Native Method)
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914):       at android.media.MediaCodec.flush(MediaCodec.java:2054)
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:777)
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.flushOrReleaseCodec(MediaCodecVideoRenderer.java:724)
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:636)
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:569)
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:168)
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1136)
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:891)
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:382)
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914):       at android.os.Handler.dispatchMessage(Handler.java:98)
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914):       at android.os.Looper.loop(Looper.java:163)
E/ 02-19 17:30:21.189 ExoPlayerImplInternal(  914):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/ 02-19 17:30:21.229 Surface (  914): getSlotFromBufferLocked: unknown buffer: 0x7f498f4a40
W/ 02-19 17:30:21.229 ACodec  (  914): [OMX.qcom.video.decoder.avc] can not return buffer 15 to native window
E/ 02-19 17:30:21.230 Surface (  914): getSlotFromBufferLocked: unknown buffer: 0x7f49904ae0
W/ 02-19 17:30:21.230 ACodec  (  914): [OMX.qcom.video.decoder.avc] can not return buffer 14 to native window
E/ 02-19 17:30:21.232 Surface (  914): getSlotFromBufferLocked: unknown buffer: 0x7f49830740
W/ 02-19 17:30:21.232 ACodec  (  914): [OMX.qcom.video.decoder.avc] can not return buffer 13 to native window
E/ 02-19 17:30:21.234 Surface (  914): getSlotFromBufferLocked: unknown buffer: 0x7f49830680
W/ 02-19 17:30:21.234 ACodec  (  914): [OMX.qcom.video.decoder.avc] can not return buffer 12 to native window
E/ 02-19 17:30:21.235 Surface (  914): getSlotFromBufferLocked: unknown buffer: 0x7f498306e0
W/ 02-19 17:30:21.235 ACodec  (  914)
```: [OMX.qcom.video.decoder.avc] can not return buffer 11 to native

**Comment by christosts** [comment]
The logs show the same, both H264 decoders in the device cannot decode this stream

```
D/ 02-19 17:30:21.184 MediaCodecInfo(  914): NoSupport [sizeAndRate.support, 1170x2532x29.998811721801758] [OMX.qcom.video.decoder.avc, video/avc] [santoni, Redmi 4X, Xiaomi, 25]
D/ 02-19 17:30:21.185 MediaCodecInfo(  914): NoSupport [sizeAndRate.support, 1170x2532x29.998811721801758] [OMX.google.h264.decoder, video/avc] [santoni, Redmi 4X, Xiaomi, 25]
```

ExoPlayer picks the `OMX.qcom.video.decoder.avc` which is the hardware decoder, as a best effort but it fails to decode the video. The video resolution for H264 is beyond the device's capabilities. Please try a lower resolution, or perhaps explore encoding with a different codec in case the device has better support for other codecs.
