### ISSUE TITLE
Sometimes play local mp4 file with unexpected runtime error

### ISSUE THREAD

**Issue by hsicen** [google/ExoPlayer#8612]
Below is the logcat:
```
102-06 10:38:26.511 14670 16351 D CCodecConfig: c2::u32 coded.pl.profile = 8192
202-06 10:38:26.511 14670 16351 D CCodecConfig: c2::float coding.drc.attenuation-factor.value = 1
302-06 10:38:26.511 14670 16351 D CCodecConfig: c2::float coding.drc.boost-factor.value = 1
402-06 10:38:26.511 14670 16351 D CCodecConfig: c2::i32 coding.drc.compression-mode.value = 3
502-06 10:38:26.511 14670 16351 D CCodecConfig: c2::i32 coding.drc.effect-type.value = 3
602-06 10:38:26.511 14670 16351 D CCodecConfig: c2::float coding.drc.encoded-level.value = 0.25
702-06 10:38:26.511 14670 16351 D CCodecConfig: c2::float coding.drc.reference-level.value = -16
802-06 10:38:26.511 14670 16351 D CCodecConfig: c2::u32 input.buffers.max-size.value = 8192
902-06 10:38:26.511 14670 16351 D CCodecConfig: c2::u32 input.delay.value = 0
1002-06 10:38:26.511 14670 16351 D CCodecConfig: string input.media-type.value = "audio/mp4a-latm"
1102-06 10:38:26.511 14670 16351 D CCodecConfig: c2::u32 output.delay.value = 2
1202-06 10:38:26.511 14670 16351 D CCodecConfig: string output.media-type.value = "audio/raw"
1302-06 10:38:26.511 14670 16351 D CCodecConfig: c2::u32 raw.channel-count.value = 1
1402-06 10:38:26.511 14670 16351 D CCodecConfig: c2::u32 raw.sample-rate.value = 44100
1502-06 10:38:26.511 14670 16351 D CCodecConfig: }
1602-06 10:38:26.513 14670 16351 D CCodecConfig: config failed => CORRUPTED
1702-06 10:38:26.513 14670 16351 D CCodecConfig: c2 config is Dict {
1802-06 10:38:26.513 14670 16351 D CCodecConfig: c2::u32 coded.aac-packaging.value = 0
1902-06 10:38:26.513 14670 16351 D CCodecConfig: c2::u32 coded.bitrate.value = 64000
2002-06 10:38:26.513 14670 16351 D CCodecConfig: c2::u32 coded.pl.level = 0
2102-06 10:38:26.513 14670 16351 D CCodecConfig: c2::u32 coded.pl.profile = 8192
2202-06 10:38:26.513 14670 16351 D CCodecConfig: c2::float coding.drc.attenuation-factor.value = 1
2302-06 10:38:26.513 14670 16351 D CCodecConfig: c2::float coding.drc.boost-factor.value = 1
2402-06 10:38:26.513 14670 16351 D CCodecConfig: c2::i32 coding.drc.compression-mode.value = 3
2502-06 10:38:26.513 14670 16351 D CCodecConfig: c2::i32 coding.drc.effect-type.value = 3
2602-06 10:38:26.513 14670 16351 D CCodecConfig: c2::float coding.drc.encoded-level.value = 0.25
2702-06 10:38:26.513 14670 16351 D CCodecConfig: c2::float coding.drc.reference-level.value = -16
2802-06 10:38:26.513 14670 16351 D CCodecConfig: c2::u32 input.buffers.max-size.value = 8192
2902-06 10:38:26.513 14670 16351 D CCodecConfig: c2::u32 input.delay.value = 0
3002-06 10:38:26.513 14670 16351 D CCodecConfig: string input.media-type.value = "audio/mp4a-latm"
3102-06 10:38:26.513 14670 16351 D CCodecConfig: c2::u32 output.delay.value = 2
3202-06 10:38:26.513 14670 16351 D CCodecConfig: string output.media-type.value = "audio/raw"
3302-06 10:38:26.513 14670 16351 D CCodecConfig: c2::u32 raw.channel-count.value = 2
3402-06 10:38:26.513 14670 16351 D CCodecConfig: c2::u32 raw.sample-rate.value = 44100
3502-06 10:38:26.513 14670 16351 D CCodecConfig: }
3602-06 10:38:26.513 14670 16351 W Codec2Client: query -- param skipped: index = 1107298332.
3702-06 10:38:26.513 14670 16351 D CCodec : client requested max input size 810, which is smaller than what component recommended (8192); overriding with component recommendation.
3802-06 10:38:26.513 14670 16351 W CCodec : This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
3902-06 10:38:26.513 14670 16351 D CCodec : setup formats input: AMessage(what = 0x00000000) = {
4002-06 10:38:26.513 14670 16351 D CCodec : int32_t channel-count = 2
4102-06 10:38:26.513 14670 16351 D CCodec : int32_t level = 0
4202-06 10:38:26.513 14670 16351 D CCodec : int32_t max-input-size = 8192
4302-06 10:38:26.513 14670 16351 D CCodec : string mime = "audio/mp4a-latm"
4402-06 10:38:26.513 14670 16351 D CCodec : int32_t profile = 2
4502-06 10:38:26.513 14670 16351 D CCodec : int32_t sample-rate = 44100
4602-06 10:38:26.513 14670 16351 D CCodec : } and output: AMessage(what = 0x00000000) = {
4702-06 10:38:26.513 14670 16351 D CCodec : int32_t channel-count = 2
4802-06 10:38:26.513 14670 16351 D CCodec : string mime = "audio/raw"
4902-06 10:38:26.513 14670 16351 D CCodec : int32_t sample-rate = 44100
5002-06 10:38:26.513 14670 16351 D CCodec : }
5102-06 10:38:26.514 14670 16351 W Codec2Client: query -- param skipped: index = 1342179345.
5202-06 10:38:26.514 14670 16351 W Codec2Client: query -- param skipped: index = 2415921170.
5302-06 10:38:26.514 14670 16351 W Codec2Client: query -- param skipped: index = 1610614798.
5402-06 10:38:26.515 14670 16351 D BufferPoolManager: # of cleaned connections: 2
5502-06 10:38:26.515 14670 16351 D BufferPoolManager: create new connection 63008782811286
5602-06 10:38:26.515 14670 16351 D CCodecBufferChannel: [c2.android.aac.decoder#112] Created input block pool with allocatorID 16 => poolID 19 - OK (0)
5702-06 10:38:26.516 14670 16351 I CCodecBufferChannel: [c2.android.aac.decoder#112] Created output block pool with allocatorID 16 => poolID 345 - OK
5802-06 10:38:26.517 14670 16351 D CCodecBufferChannel: [c2.android.aac.decoder#112] Configured output block pool ids 345 => OK
5902-06 10:38:26.518 14670 16351 D BufferPoolManager: client death recipient registered 63008782811287
6002-06 10:38:26.518 14670 15435 D BufferPoolManager: register existing connection 63008782811286
6102-06 10:38:26.524 14670 16338 I ACodec : [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) err=0(NO_ERROR)
6202-06 10:38:26.525 14670 16338 I ACodec : [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) err=0(NO_ERROR)
6302-06 10:38:26.525 14670 16338 I ACodec : [OMX.hisi.video.decoder.avc] using color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) and dataspace 0x104
6402-06 10:38:26.525 14670 15435 D BufferPoolManager: register new connection 3562138389164
6502-06 10:38:26.528 14670 14670 D LeakCanary: Watching instance of androidx.fragment.app.FragmentManagerViewModel (androidx.fragment.app.FragmentManagerViewModel received ViewModel#onCleared() callback) with key 9ef0d206-69c8-4528-9d03-a011639152e2
6602-06 10:38:26.528 14670 14670 D LeakCanary: Watching instance of com.camera360.salad.editor.album.AlbumSelectManagerViewModel (com.camera360.salad.editor.album.AlbumSelectManagerViewModel received ViewModel#onCleared() callback) with key a1cd7d28-cf4a-4da5-a8da-cece5af65af6
6702-06 10:38:26.528 14670 14670 D LeakCanary: Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key ded75b98-25a3-4adf-9840-8a02f0e7dfcb
6802-06 10:38:26.528 14670 14670 D LeakCanary: Watching instance of com.camera360.salad.editor.album.LoadAlbumMediasViewModel (com.camera360.salad.editor.album.LoadAlbumMediasViewModel received ViewModel#onCleared() callback) with key 9af4b56c-9d72-4cee-9e73-c10c065e161a
6902-06 10:38:26.529 14670 14670 D LeakCanary: Watching instance of androidx.lifecycle.ReportFragment (androidx.lifecycle.ReportFragment received Fragment#onDestroy() callback) with key 6ddcb85d-d017-41b0-b33c-1314e4de6541
7002-06 10:38:26.529 14670 14670 D AlbumContainerActivity: onDestroy
7102-06 10:38:26.529 14670 14670 D LeakCanary: Watching instance of com.camera360.salad.editor.album.AlbumContainerActivity (com.camera360.salad.editor.album.AlbumContainerActivity received Activity#onDestroy() callback) with key a9aa427e-b766-42f1-9f56-7d08cf975788
7202-06 10:38:26.529 14670 14670 D CrashReport: >>> com.camera360.salad.editor.album.AlbumContainerActivity onDestroyed <<<
7302-06 10:38:26.530 14670 14670 D GIO.AppState: onActivityDestroyed com.camera360.salad.editor.album.AlbumContainerActivity@e2d62f5
7402-06 10:38:26.530 14670 14670 D GIO.AutoAppState: onActivityDestroyed com.camera360.salad.editor.album.AlbumContainerActivity@e2d62f5
7502-06 10:38:26.531 14670 16338 I ACodec : [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) err=0(NO_ERROR)
7602-06 10:38:26.531 14670 16338 I ACodec : [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) err=0(NO_ERROR)
7702-06 10:38:26.531 14670 16338 I ACodec : [OMX.hisi.video.decoder.avc] using color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) and dataspace 0x104
7802-06 10:38:26.531 14670 14670 D LeakCanary: Watching instance of androidx.loader.app.LoaderManagerImpl$LoaderViewModel (androidx.loader.app.LoaderManagerImpl$LoaderViewModel received ViewModel#onCleared() callback) with key a5a36065-c239-4126-9424-83a7d09e53e8
7902-06 10:38:26.531 14670 14670 D LeakCanary: Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key 90429ee1-911e-479f-ae57-633ae62d58d6
8002-06 10:38:26.531 14670 16337 D SurfaceUtils: connecting to surface 0x98d05808, reason connectToSurface
8102-06 10:38:26.532 14670 16337 I MediaCodec: [OMX.hisi.video.decoder.avc] setting surface generation to 15022142
8202-06 10:38:26.532 14670 16337 D SurfaceUtils: disconnecting from surface 0x98d05808, reason connectToSurface(reconnect)
8302-06 10:38:26.532 14670 16337 D SurfaceUtils: connecting to surface 0x98d05808, reason connectToSurface(reconnect)
8402-06 10:38:26.534 14670 16338 D SurfaceUtils: disconnecting from surface 0x98d05808, reason setNativeWindowSizeFormatAndUsage
8502-06 10:38:26.534 14670 16338 D SurfaceUtils: connecting to surface 0x98d05808, reason setNativeWindowSizeFormatAndUsage
8602-06 10:38:26.534 14670 16338 D SurfaceUtils: set up nativeWindow 0x98d05808 for 1088x1920, color 0x30d, rotation 0, usage 0x20002900
8702-06 10:38:26.534 14670 16338 E BufferQueueProducer: [SurfaceTexture-0-14670-32]:139: setMaxDequeuedBufferCount: the requested maxDequeuedBuffercount (-1) exceeds the current dequeued buffer count (0)
8802-06 10:38:26.534 14670 16338 E Surface : IGraphicBufferProducer::setBufferCount(1) returned Invalid argument
8902-06 10:38:26.534 14670 16338 E ACodec : native_window_set_buffer_count failed: Invalid argument (22)
9002-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: Playback error
9102-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
9202-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
9302-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: at android.os.Handler.dispatchMessage(Handler.java:103)
9402-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: at android.os.Looper.loop(Looper.java:213)
9502-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: at android.os.HandlerThread.run(HandlerThread.java:67)
9602-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: Caused by: java.lang.IllegalArgumentException
9702-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: at android.media.MediaCodec.native_setSurface(Native Method)
9802-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: at android.media.MediaCodec.setOutputSurface(MediaCodec.java:2042)
9902-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1242)
10002-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:516)
10102-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:478)
10202-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1402)
10302-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1368)
10402-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1343)
10502-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
10602-06 10:38:26.536 14670 16333 E ExoPlayerImplInternal: ... 3 more
10702-06 10:38:26.536 14670 16338 D SurfaceUtils: disconnecting from surface 0x98d05008, reason setNativeWindowSizeFormatAndUsage
10802-06 10:38:26.538 14670 16338 D SurfaceUtils: connecting to surface 0x98d05008, reason setNativeWindowSizeFormatAndUsage
10902-06 10:38:26.538 14670 14670 D LeakCanary: Watching instance of com.bumptech.glide.manager.SupportRequestManagerFragment (com.bumptech.glide.manager.SupportRequestManagerFragment received Fragment#onDestroy() callback) with key 307643bb-c631-437f-ac50-5958e1202ebd
11002-06 10:38:26.538 14670 16338 D SurfaceUtils: set up nativeWindow 0x98d05008 for 1088x1920, color 0x30d, rotation 0, usage 0x20002900
11102-06 10:38:26.538 14670 16338 W ACodec : [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 11 failed: -2147483648
11202-06 10:38:26.542 14670 14670 D LeakCanary: Watching instance of androidx.constraintlayout.widget.ConstraintLayout (com.camera360.salad.editor.album.MediaListFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks)) with key 7393ef2f-3f31-4414-9d71-6095c28dd0bb
11302-06 10:38:26.543 14670 14670 D LeakCanary: Watching instance of androidx.constraintlayout.widget.ConstraintLayout (com.camera360.salad.editor.album.AlbumFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks)) with key 825a87a9-0015-480a-92bf-06ef0f1a857d
11402-06 10:38:26.543 14670 14670 D LeakCanary: Watching instance of androidx.loader.app.LoaderManagerImpl$LoaderViewModel (androidx.loader.app.LoaderManagerImpl$LoaderViewModel received ViewModel#onCleared() callback) with key 0f6e7d6f-a898-4bb0-95f7-563429741c80
11502-06 10:38:26.543 14670 14670 D LeakCanary: Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key 229a49ab-96f7-48dc-86f5-54f8b88a263c
11602-06 10:38:26.543 14670 14670 D LeakCanary: Watching instance of androidx.loader.app.LoaderManagerImpl$LoaderViewModel (androidx.loader.app.LoaderManagerImpl$LoaderViewModel received ViewModel#onCleared() callback) with key 70655ec1-fa36-4d45-8faa-91ce02fcbb27
11702-06 10:38:26.543 14670 14670 D LeakCanary: Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key f228d115-87dc-402d-817a-4c5f535c2e9f
11802-06 10:38:26.543 14670 14670 D LeakCanary: Watching instance of androidx.loader.app.LoaderManagerImpl$LoaderViewModel (androidx.loader.app.LoaderManagerImpl$LoaderViewModel received ViewModel#onCleared() callback) with key 49a4cf9a-8c3e-431c-8b6f-1a83ff8a86f0
11902-06 10:38:26.543 14670 14670 D LeakCanary: Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key a5aa6f60-ba1d-4c27-b3aa-96e4310b67bb
12002-06 10:38:26.544 14670 14670 D LeakCanary: Watching instance of com.bumptech.glide.manager.SupportRequestManagerFragment (com.bumptech.glide.manager.SupportRequestManagerFragment received Fragment#onDestroy() callback) with key 2e6992f7-46c2-49df-9270-bf3d7c3eaf07
12102-06 10:38:26.544 14670 14670 D LeakCanary: Watching instance of com.camera360.salad.editor.album.MediaListFragment (com.camera360.salad.editor.album.MediaListFragment received Fragment#onDestroy() callback) with key 7332390d-9f6c-454d-864a-5127283d29e6
12202-06 10:38:26.544 14670 14670 D LeakCanary: Watching instance of com.camera360.salad.editor.album.AlbumFragment (com.camera360.salad.editor.album.AlbumFragment received Fragment#onDestroy() callback) with key 706b4280-5388-423d-86b4-f738f24638ec
12302-06 10:38:26.545 14670 14670 D ActivityThread: Remove activity client record, r= ActivityRecord{7890616 token=android.os.BinderProxy@9fbd283 {com.camera360.salad/com.camera360.salad.editor.album.AlbumContainerActivity}} token= android.os.BinderProxy@9fbd283
12402-06 10:38:26.565 14670 16333 D BufferPoolAccessor: buffer invalidation added bp:2 1
12502-06 10:38:26.565 14670 15458 D BufferPoolAccessor: buffer invalidation deleted bp:2
12602-06 10:38:26.566 14670 16338 W ACodec : forcing OMX state to Idle when received shutdown in ExecutingState
12702-06 10:38:26.597 14670 16337 D SurfaceUtils: disconnecting from surface 0x98d05008, reason disconnectFromSurface
12802-06 10:38:26.603 14670 14670 W BundlePool: <create new bundle object>
12902-06 10:38:26.603 14670 14670 D frameEvent_play: PLAYER_EVENT_ON_STATUS_CHANGE
13002-06 10:38:26.603 14670 14670 E ExoMediaPlayer: Unexpected runtime error, causeMessage = null
13102-06 10:38:26.603 14670 14670 W BundlePool: <create new bundle object>
13202-06 10:38:26.604 14670 14670 E frameEvent_error: ERROR_EVENT_UNKNOWN,Bundle[{causeMessage=null, errorMessage=Unexpected runtime error}]
13302-06 10:38:26.604 14670 14670 E BaseVideoView: onError : code = -88012, Message = Bundle[{causeMessage=null, errorMessage=Unexpected runtime error}]
13402-06 10:38:26.604 14670 14670 D hsc : 播放出错： code->-88012 bundle->Bundle[{causeMessage=null, errorMessage=Unexpected runtime error}]
13502-06 10:38:26.605 14670 14670 D CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.crashreport.crash.c$1
13602-06 10:38:26.605 14670 14770 D CrashReport: post a throwable false
13702-06 10:38:26.605 14670 14770 E CrashReport: Java Catch Happen
13802-06 10:38:26.606 14670 14670 D ExoMediaPlayer: onLoadingChanged : false, bufferPercentage = 0
13902-06 10:38:26.606 14670 14670 D ExoMediaPlayer: onPlayerStateChanged : playbackState = 1
14002-06 10:38:26.621 14670 14670 D GIO.PageObserver: last callback time over three seconds, and force refresh page
14102-06 10:38:26.644 14670 14805 W GIO.HttpService: performRequest: code 200 url:https://api.growingio.com/v3/835c0c2f633e0d20/android/cstm?stm=1612579106437, error: null ,response:
14202-06 10:38:26.647 14670 14823 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
14302-06 10:38:26.652 14670 14823 D OpenGLRenderer: disableOutlineDraw is true
```

**Comment by Samrobbo** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

In particular, having access to the mp4 file that is causing the problem would help greatly.

**Comment by hsicen** [comment]
Sorry so long to back you，I get stacktrace with product environment and it from our user,no more infomation about it.

**Comment by hsicen** [comment]
I had send bugreport and mp4 file to the email.
