### ISSUE TITLE
NumberFormatException when parsing mpd file with image/jpeg content type and SegmentTemplate duration is not Long

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#8614]
Hi,

I got a url to explore dash thumbnails
Once I tried running it via the demo app of r2.13.1 I got the NumberFormatException during manifest parsing.
I am using Galaxy s10e with Android10

In order to run it  I had to support http playback in the demo app
so I updated the Manifest.xml under application section I have added :     
`android:networkSecurityConfig="@xml/network_security_config"`

and also added under res folder xml folder with network_security_config.xml

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config xmlns:tools="http://schemas.android.com/tools"
    tools:ignore="UnusedResources">
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
    <debug-overrides>
        <trust-anchors>
            <certificates src="user" />
        </trust-anchors>
    </debug-overrides>
</network-security-config>
```

I am using the following mpd URL 

```  
{
        "name": "Multi Image Tracks",
        "uri": "http://dash.edgesuite.net/akamai/bbb_30fps/bbb_with_multiple_tiled_thumbnails.mpd"
 }
```

The exception occurs due to the fact that the DashManifestparser does not assume that the duration can be float string 
```
2021-02-21 16:05:49.541 5687-5713/? E/libprocessgroup: Error encountered killing process cgroup uid 99153 pid 21062: No such file or directory
2021-02-21 16:06:01.891 21657-21657/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=0.19, mediaPos=0.00, window=0, loadError
      com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NumberFormatException: For input string: "634.566"
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:436)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NumberFormatException: For input string: "634.566"
        at java.lang.Long.parseLong(Long.java:594)
        at java.lang.Long.parseLong(Long.java:636)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseLong(DashManifestParser.java:1743)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseSegmentTemplate(DashManifestParser.java:958)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseAdaptationSet(DashManifestParser.java:469)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parsePeriod(DashManifestParser.java:302)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseMediaPresentationDescription(DashManifestParser.java:154)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:105)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:62)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:179)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
    ]
```

PS.
The same issue can also show up for parseInt where the integer number is not set there so there is no validation.

Example for what I think can be a solution

```

  protected static long parseLong(XmlPullParser xpp, String name, long defaultValue) {
    String value = xpp.getAttributeValue(null, name);
    boolean isFloat = false;
    if (value !=null && value.contains(".")) {
      value = value.split("\\.")[0];
      isFloat = true;
    }
    long longValue = (value == null) ? defaultValue : Long.parseLong(value);
    if (isFloat) {
      return ++longValue;
    }
    return longValue;
  }

protected static int parseInt(XmlPullParser xpp, String name, int defaultValue) {
    String value = xpp.getAttributeValue(null, name);
    if (value == null || !TextUtils.isDigitsOnly(value)) {
      return defaultValue;
    }
    return Integer.parseInt(value);
  }


```

**Comment by ojw28** [comment]
Specifying duration as a floating point value is against the specification, which defines it to be an unsigned integer:
```
<xs:attribute name="duration" type="xs:unsignedInt"/>
```
You should request that the content owner fix their content to be compliant to the specification. Since we have not seen other reports of this issue, it seems likely to be an isolated case, and therefore there isn't a strong argument for a client side workaround. Closing on this basis.

**Comment by giladna** [comment]
@ojw28 maybe this has to be re considered 

since I can see it is working on DASH-IF player

10x
Gilad.

http://reference.dashif.org/dash.js/v2.9.3/samples/dash-if-reference-player/index.html

with this url and float duration  duration="634.566"

`http://dash.edgesuite.net/akamai/bbb_30fps/bbb_with_multiple_tiled_thumbnails.mpd`


```
<MPD mediaPresentationDuration="PT634.566S" minBufferTime="PT2.00S" profiles="urn:hbbtv:dash:profile:isoff-live:2012,urn:mpeg:dash:profile:isoff-live:2011" type="static" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd">
    <BaseURL>./</BaseURL>
    <Period>
        <AdaptationSet id="1" mimeType="video/mp4" contentType="video" subsegmentAlignment="true" subsegmentStartsWithSAP="1" par="16:9">
            <SegmentTemplate duration="120" timescale="30" media="$RepresentationID$/$RepresentationID$_$Number$.m4v" startNumber="1" initialization="$RepresentationID$/$RepresentationID$_0.m4v"/>
            <Representation id="bbb_30fps_1024x576_2500k" codecs="avc1.64001f" bandwidth="3134488" width="1024" height="576" frameRate="30" sar="1:1" scanType="progressive"/>
            <Representation id="bbb_30fps_1280x720_4000k" codecs="avc1.64001f" bandwidth="4952892" width="1280" height="720" frameRate="30" sar="1:1" scanType="progressive"/>
            <Representation id="bbb_30fps_1920x1080_8000k" codecs="avc1.640028" bandwidth="9914554" width="1920" height="1080" frameRate="30" sar="1:1" scanType="progressive"/>
            <Representation id="bbb_30fps_320x180_200k" codecs="avc1.64000d" bandwidth="254320" width="320" height="180" frameRate="30" sar="1:1" scanType="progressive"/>
            <Representation id="bbb_30fps_320x180_400k" codecs="avc1.64000d" bandwidth="507246" width="320" height="180" frameRate="30" sar="1:1" scanType="progressive"/>
            <Representation id="bbb_30fps_480x270_600k" codecs="avc1.640015" bandwidth="759798" width="480" height="270" frameRate="30" sar="1:1" scanType="progressive"/>
            <Representation id="bbb_30fps_640x360_1000k" codecs="avc1.64001e" bandwidth="1254758" width="640" height="360" frameRate="30" sar="1:1" scanType="progressive"/>
            <Representation id="bbb_30fps_640x360_800k" codecs="avc1.64001e" bandwidth="1013310" width="640" height="360" frameRate="30" sar="1:1" scanType="progressive"/>
            <Representation id="bbb_30fps_768x432_1500k" codecs="avc1.64001e" bandwidth="1883700" width="768" height="432" frameRate="30" sar="1:1" scanType="progressive"/>
            <Representation id="bbb_30fps_3840x2160_12000k" codecs="avc1.640033" bandwidth="14931538" width="3840" height="2160" frameRate="30" sar="1:1" scanType="progressive"/>
        </AdaptationSet>
        <AdaptationSet id="2" mimeType="audio/mp4" contentType="audio" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
            <Accessibility schemeIdUri="urn:tva:metadata:cs:AudioPurposeCS:2007" value="6"/>
            <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
            <SegmentTemplate duration="192512" timescale="48000" media="$RepresentationID$/$RepresentationID$_$Number$.m4a" startNumber="1" initialization="$RepresentationID$/$RepresentationID$_0.m4a"/>
            <Representation id="bbb_a64k" codecs="mp4a.40.5" bandwidth="67071" audioSamplingRate="48000">
                <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
            </Representation>
        </AdaptationSet>
        <AdaptationSet id="3" mimeType="image/jpeg" contentType="image">
            <SegmentTemplate media="$RepresentationID$/tile_$Number$.jpg" duration="634.566" startNumber="1"/>
            <Representation bandwidth="12000" id="thumbnails_102x58" width="1024" height="1152">
                <EssentialProperty schemeIdUri="http://dashif.org/thumbnail_tile" value="10x20"/>
            </Representation>
            <Representation bandwidth="24000" id="thumbnails_256x144" width="2048" height="1152">
                <EssentialProperty schemeIdUri="http://dashif.org/thumbnail_tile" value="8x8"/>
            </Representation>
        </AdaptationSet>
    </Period>
</MPD>
```

**Comment by ojw28** [comment]
A single example of an MPD that violates the DASH specification doesn't warrant adding workarounds into clients. The owner of the content should fix it to be specification compliant.

Another player being able to play the content isn't a strong argument either. By that argument, every player would be expected to handle every type of invalid content that every other player handles. If that were the case, what specification would players actually be implementing, and how would it be feasible to ever write a new one?
