### ISSUE TITLE
got CodecException when playing mp4 file

### ISSUE THREAD

**Issue by kingfisherphuoc** [google/ExoPlayer#8643]
- ExoPlayer version number: 2.12.1
- Android version: 9.0
- Android device: Android TV Box X96Max_Plus2

It was good with `MediaPlayer`. However, I wanted some more advantages features of ExoPlayer, I switched to ExoPlayer. After playing a list of items for awhile, I got this exception:

```
prepareVideo id = 1614290482543, url = file:///storage/emulated/0/Android/data/com.mydomain.player/files/Download/videoT02-23-02-59-18.177ONsource.mp4,
2021-02-26 00:01:22.550 W/MediaCodecRenderer: Failed to initialize decoder: OMX.amlogic.avc.decoder.awesome
      android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2068)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.start(SynchronousMediaCodecAdapter.java:48)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1146)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1040)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2021-02-26 00:01:22.553 E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 29.97003], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 29.97003], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1047)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2068)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.start(SynchronousMediaCodecAdapter.java:48)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1146)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1040)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```
What's the issue? Is there any workaround for it?

**Comment by krocard** [comment]
Unfortunately, the posted exception carried very little information regarding the codec state.
I'm afraid we cannot understand the issue without more context in the form of a bug report.
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) publicly on this issue, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.

**Comment by kingfisherphuoc** [comment]
@krocard I am afraid that I cannot share the code. Let me explain it again.
I tried to play a playlist of videos from sdcard. After playing for a period of time, I got this issue. Here's how I do it:

```
 public MediaItem prepareVideo(String url) {
        final String id = String.valueOf(System.currentTimeMillis());
        final MediaItem mediaItem = new MediaItem.Builder().setUri(url).setMediaId(id).build();
        try {
            if (currentPlayer.getMediaItemCount() == 0) { // no media is playing atm
                currentPlayer.setMediaItem(mediaItem);
                currentPlayer.setPlayWhenReady(false);
            } else { // player is playing now
                currentPlayer.addMediaItem(mediaItem);
            }
            showLog("prepareVideo id = " + id + ", url = " + url + ", item count = "
                    + currentPlayer.getMediaItemCount());
        } catch (Exception e) {
        }
        return mediaItem;
    }
```
I am using a single exoplayer instance, `TextTureView` and those flags:

```
currentPlayer = new SimpleExoPlayer.Builder(getContext()).build();
currentPlayer.addListener(eventListener);
currentPlayer.addVideoListener(videoListener);
currentPlayer.prepare();
playerView.setPlayer(currentPlayer);
playerView.setKeepContentOnPlayerReset(true);
playerView.setClipToOutline(true);
View videoSurfaceView = playerView.getVideoSurfaceView();
if (videoSurfaceView != null) {
            videoSurfaceView.setScaleX(1.00001f);
}
```

Do you have any idea how to fix it?

**Comment by krocard** [comment]
A [bug report](https://developer.android.com/studio/debug/bug-report) does not contain the code of your application. It is a zip file containing the divers logs of the device as well as as the service states.

Alternatively reproducing using our [demo application](https://exoplayer.dev/demo-application.html) and sharing a bug report would be of great help.

Please see our [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) for more information in how you can help us resolve your issue.

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by kingfisherphuoc** [comment]
@krocard I cannot share my bug reports, so I sent them to your email. Please take a look at it.

This is my updated log:
```
2021-03-09 11:35:53.653 I/OMXClient: IOmx service obtained
2021-03-09 11:35:53.685 D/SurfaceUtils: connecting to surface 0x8e2d9808, reason connectToSurface
2021-03-09 11:35:53.685 I/MediaCodec: [OMX.amlogic.avc.decoder.awesome] setting surface generation to 32888837
2021-03-09 11:35:53.685 D/SurfaceUtils: disconnecting from surface 0x8e2d9808, reason connectToSurface(reconnect)
2021-03-09 11:35:53.685 D/SurfaceUtils: connecting to surface 0x8e2d9808, reason connectToSurface(reconnect)
2021-03-09 11:35:53.686 I/AmAVUtils: AmAVUtils::getComponentRole isEncoder :0 mime:video/avc 
2021-03-09 11:35:53.686 V/AVUtils: AVUtils::getComponentRole
2021-03-09 11:35:53.687 E/ACodec: [OMX.amlogic.avc.decoder.awesome] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
2021-03-09 11:35:53.692 I/AmAVUtils: AmAVUtils::isAudioExtendFormat input = video/avc
2021-03-09 11:35:53.692 I/ACodec: codec does not support config priority (err -1010)
2021-03-09 11:35:53.724 D/SurfaceUtils: disconnecting from surface 0x8e2d9808, reason setNativeWindowSizeFormatAndUsage
2021-03-09 11:35:53.724 D/SurfaceUtils: connecting to surface 0x8e2d9808, reason setNativeWindowSizeFormatAndUsage
2021-03-09 11:35:53.724 D/SurfaceUtils: set up nativeWindow 0x8e2d9808 for 720x1280, color 0x11, rotation 0, usage 0x402b00
2021-03-09 11:35:53.724 W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 9 failed: -1010
2021-03-09 11:35:53.725 W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
2021-03-09 11:35:53.726 W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
2021-03-09 11:35:53.736 E/GraphicBufferAllocator: Failed to allocate (720 x 1280) layerCount 1 format 17 usage 402b00: 5
2021-03-09 11:35:53.736 E/BufferQueueProducer: [SurfaceTexture-1-32118-4] dequeueBuffer: createGraphicBuffer failed
2021-03-09 11:35:53.736 E/ACodec: dequeueBuffer failed: Out of memory (12)
2021-03-09 11:35:53.736 E/ACodec: Failed to allocate buffers after transitioning to IDLE state (error 0xfffffff4)
2021-03-09 11:35:53.736 E/ACodec: signalError(omxError 0x80001001, internalError -12)
2021-03-09 11:35:53.736 E/MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 5
2021-03-09 11:35:53.742 W/AHierarchicalStateMachine: Warning message AMessage(what = 'omxI') = {
      int32_t type = 0
      int32_t event = 0
      int32_t data1 = 0
      int32_t data2 = 1
    } unhandled in root state.
2021-03-09 11:35:53.742 D/SurfaceUtils: disconnecting from surface 0x8e2d9808, reason disconnectFromSurface
2021-03-09 11:35:53.764 W/MediaCodecRenderer: Failed to initialize decoder: OMX.amlogic.avc.decoder.awesome
      android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2068)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.start(SynchronousMediaCodecAdapter.java:48)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1146)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1040)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2021-03-09 11:35:53.780 E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [720, 1280, 25.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, Format(1, null, null, video/avc, null, -1, null, [720, 1280, 25.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1047)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2068)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.start(SynchronousMediaCodecAdapter.java:48)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1146)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1040)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

**Comment by krocard** [comment]
```
03-09 11:22:23.029  1000  3253 24120 E gralloc : ioctl c0144900 failed with code -1: Out of memory
03-09 11:22:23.029  1000  3253 24120 E gralloc : ION_HEAP_TYPE_CUSTOM alloc failed!
03-09 11:22:23.029  1000  3253 24120 E [Gralloc-ERROR]: mali_gralloc_ion_allocate:486 ion_alloc failed from client ( 6 )
03-09 11:22:23.029  1000  3253 24120 E gralloc : mali_gralloc_ion_allocate return error
03-09 11:22:23.029  1000  3253 24120 E gralloc : Failed to allocate buffer.
03-09 11:22:23.030 10126 24506 29534 E GraphicBufferAllocator: Failed to allocate (720 x 1280) layerCount 1 format 17 usage 402b00: 5
03-09 11:22:23.030 10126 24506 29534 E BufferQueueProducer: [SurfaceTexture-1-24506-12] dequeueBuffer: createGraphicBuffer failed
03-09 11:22:23.030 10126 24506 29534 E ACodec  : dequeueBuffer failed: Out of memory (12)
03-09 11:22:23.030 10126 24506 29534 E ACodec  : Failed to allocate buffers after transitioning to IDLE state (error 0xfffffff4)
03-09 11:22:23.030 10126 24506 29534 E ACodec  : signalError(omxError 0x80001001, internalError -12)
03-09 11:22:23.031 10126 24506 29533 E MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 5
```
in the kernel buffer log:
` <3>[164646.576991@0] ion_codec_mm_allocate failed out size 1433600,alloced -1728512`


This suggests that the codec allocation failed due to ION memory allocation failure.
This is usually caused by having too many codec allocated at the same time.

> After playing a list of items for awhile, I got this exception

Could it be that your code is allocating a new player for each items and not calling `release()` on them? If so, you application is leaking codec holding ION memory.

It doesn't look like it from the code snippets, but could you please double check your code?

**Comment by kingfisherphuoc** [comment]
@krocard I used a single exoplayer instance in my activity. I released the player on `onDestroy` of activity. It will happen more frequently if I restart the activity (by closing and reopening it).
-  is there any case that the release function takes some time to be finished? can we have any method to check or release all created exoplayer?
I am using some native c library in my app, could it be the reason of `ION memory allocation failure`?

**Comment by krocard** [comment]
Digging a bit more in the bug report the `media.resource_manager service` shows that your application created and destroyed media codecs 10 times during the last 2 seconds.
I believe that each of those codec creation fails and for some reason ExoPlayer retries to create the codec.
This ExoPlayer retry is not intended, ExoPlayer should fail on error and not retry to create the codec.

<details>
<summary>
dumpsys media.resource_manager
</summary>

```
    03-09 11:22:23 removeResource(pid 24506, clientId 2167027328)
    03-09 11:22:23 removeResource(pid 24506, clientId 2167027328)
    03-09 11:22:23 reclaimResource(callingPid 24506, resources non-secure-codec/video-codec:1 graphic-memory/unspecified:1 )
    03-09 11:22:23 addResource(pid 24506, clientId 2167027328, resources non-secure-codec/video-codec:1 )
    03-09 11:22:23 removeResource(pid 24506, clientId 2158247936)
    03-09 11:22:23 removeResource(pid 24506, clientId 2158247936)
    03-09 11:22:23 reclaimResource(callingPid 24506, resources non-secure-codec/video-codec:1 graphic-memory/unspecified:1 )
    03-09 11:22:22 addResource(pid 24506, clientId 2158247936, resources non-secure-codec/video-codec:1 )
    03-09 11:22:22 removeResource(pid 24506, clientId 2166688192)
    03-09 11:22:22 removeResource(pid 24506, clientId 2166688192)
    03-09 11:22:22 reclaimResource(callingPid 24506, resources non-secure-codec/video-codec:1 graphic-memory/unspecified:1 )
    03-09 11:22:22 addResource(pid 24506, clientId 2166688192, resources non-secure-codec/video-codec:1 )
    03-09 11:22:22 removeResource(pid 24506, clientId 2172742848)
    03-09 11:22:22 removeResource(pid 24506, clientId 2172742848)
    03-09 11:22:22 reclaimResource(callingPid 24506, resources non-secure-codec/video-codec:1 graphic-memory/unspecified:1 )
    03-09 11:22:22 addResource(pid 24506, clientId 2172742848, resources non-secure-codec/video-codec:1 )
    03-09 11:22:22 removeResource(pid 24506, clientId 2382547776)
    03-09 11:22:22 removeResource(pid 24506, clientId 2382547776)
    03-09 11:22:22 reclaimResource(callingPid 24506, resources non-secure-codec/video-codec:1 graphic-memory/unspecified:1 )
    03-09 11:22:22 addResource(pid 24506, clientId 2382547776, resources non-secure-codec/video-codec:1 )
    03-09 11:22:22 removeResource(pid 24506, clientId 2108885728)
    03-09 11:22:22 removeResource(pid 24506, clientId 2108885728)
    03-09 11:22:22 reclaimResource(callingPid 24506, resources non-secure-codec/video-codec:1 graphic-memory/unspecified:1 )
    03-09 11:22:22 addResource(pid 24506, clientId 2108885728, resources non-secure-codec/video-codec:1 )
    03-09 11:22:22 removeResource(pid 24506, clientId 2108883968)
    03-09 11:22:22 removeResource(pid 24506, clientId 2108883968)
    03-09 11:22:22 reclaimResource(callingPid 24506, resources non-secure-codec/video-codec:1 graphic-memory/unspecified:1 )
    03-09 11:22:21 addResource(pid 24506, clientId 2108883968, resources non-secure-codec/video-codec:1 )
    03-09 11:22:21 removeResource(pid 24506, clientId 2108882368)
    03-09 11:22:21 removeResource(pid 24506, clientId 2108882368)
    03-09 11:22:21 reclaimResource(callingPid 24506, resources non-secure-codec/video-codec:1 graphic-memory/unspecified:1 )
    03-09 11:22:21 addResource(pid 24506, clientId 2108882368, resources non-secure-codec/video-codec:1 )
    03-09 11:22:21 removeResource(pid 24506, clientId 2108881792)
    03-09 11:22:21 removeResource(pid 24506, clientId 2108881792)
    03-09 11:22:21 reclaimResource(callingPid 24506, resources non-secure-codec/video-codec:1 graphic-memory/unspecified:1 )
    03-09 11:22:21 addResource(pid 24506, clientId 2108881792, resources non-secure-codec/video-codec:1 )
    03-09 11:22:21 removeResource(pid 24506, clientId 2108880992)
    03-09 11:22:21 removeResource(pid 24506, clientId 2108880992)
    03-09 11:22:21 reclaimResource(callingPid 24506, resources non-secure-codec/video-codec:1 graphic-memory/unspecified:1 )
    03-09 11:22:21 addResource(pid 24506, clientId 2108880992, resources non-secure-codec/video-codec:1 )
    03-09 11:19:32 removeResource(pid 24506, clientId 2383052064)
    03-09 11:19:32 removeResource(pid 24506, clientId 2383052064)
    03-09 11:19:12 addResource(pid 24506, clientId 2383052064, resources graphic-memory/unspecified:0 )
    03-09 11:19:11 addResource(pid 24506, clientId 2383052064, resources non-secure-codec/video-codec:1 )
    03-09 11:19:11 removeResource(pid 24506, clientId 2383051168)
    03-09 11:19:11 removeResource(pid 24506, clientId 2383051168)
    03-09 11:19:01 addResource(pid 24506, clientId 2383051168, resources graphic-memory/unspecified:0 )
    03-09 11:19:01 addResource(pid 24506, clientId 2383051168, resources non-secure-codec/video-codec:1 )
```

</details>

From that log, the first codec failure seems to have occur at `11:22:21` unfortunately due to the retries logs, the logcat buffer has evicted those original error logs from it's buffer.
Thus I can't tell why the first codec creation failed.

Given the surprising behaviour of ExoPlayer codec realocation, could you try to reproduce the issue with [our demo app](https://exoplayer.dev/demo-application.html)? It would help to know if the issue comes from how your app is using ExoPlayer or from ExoPlayer itself.

**Comment by kingfisherphuoc** [comment]
@krocard 
I was trying to reuse the `exoPlayer` instance if it's error:

```
       @Override
        public void onPlayerError(final ExoPlaybackException error) {
            showLog("onPlayerError: " + error.getLocalizedMessage());
            onMediaItemError(error);
            currentPlayer.prepare();
        }
```

Perhaps I should create a new `exoplayer` instance instead of reusing the error one, right?

**Comment by krocard** [comment]
You can try that. Additionally, are you forcing the player to resume playback after an error? For example with player.play or player. setPlayWhenReady.

Another way to solve the issue might be to switch to a SurfaceView instead of a TextureView. This should allow to offload more resources to the GPU. It should require less ION memory.

I don't think we can help you further without a minimal reproduction setup. Either with our demo application or a sample app of your own.
