### ISSUE TITLE
must use surfaceView to play widevine sample via exoplayer?

### ISSUE THREAD

**Issue by dendrocyte** [google/ExoPlayer#8668]
I am new to integrate Drm sample to exoplayer.
I search from stackOverFlow about this error msg. But mentioned solution from stackOverFlow is to use surfaceView for playing Widevine test sample via exoplayer. 

Error msg:
```
native window cannot handle protected buffers: the consumer should either be a hardware composer or support hardware protection
```
How to fix this error? does it lack the video codec?  

even I play widevine sample via exoplayer + surfaceView, it is only able to play once. there is the related error msg below. 
```
2021-02-26 19:54:22.726 10902-12069/org.noovo.vlc D/SurfaceUtils: connecting to surface 0x71cc1f3010, reason connectToSurface
2021-02-26 19:54:22.726 10902-12069/org.noovo.vlc I/MediaCodec: [OMX.qcom.video.decoder.avc.secure] setting surface generation to 11163653
2021-02-26 19:54:22.726 10902-12069/org.noovo.vlc D/SurfaceUtils: disconnecting from surface 0x71cc1f3010, reason connectToSurface(reconnect)
2021-02-26 19:54:22.726 10902-12069/org.noovo.vlc D/SurfaceUtils: connecting to surface 0x71cc1f3010, reason connectToSurface(reconnect)
2021-02-26 19:54:22.730 10902-12070/org.noovo.vlc E/SurfaceUtils: native window cannot handle protected buffers: the consumer should either be a hardware composer or support hardware protection
2021-02-26 19:54:22.732 836-2253/? D/BufferQueueProducer: About to force-disconnect API_MEDIA, mode=1
2021-02-26 19:54:22.736 836-2253/? E/SurfaceFlinger: Failed to find layer (SurfaceView - org.noovo.vlc/com.example.noovo_gsyplayer.noovo_v2.ui.DrmTestPlayerActivity#0) in layer parent (no-parent).
2021-02-26 19:54:22.738 836-2390/? E/SurfaceFlinger: Failed to find layer (Background for - SurfaceView - org.noovo.vlc/com.example.noovo_gsyplayer.noovo_v2.ui.DrmTestPlayerActivity#0) in layer parent (no-parent).
2021-02-26 19:54:22.738 1719-8091/? I/MediaFocusControl:  AudioFocus  abandonAudioFocus() from uid/pid 10171/10902 clientId=android.media.AudioManager@9aa2d89com.shuyu.gsyvideoplayer.video.base.GSYVideoView$1@4deb903
2021-02-26 19:54:22.739 10902-12056/org.noovo.vlc E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.media.MediaCodec$CodecException: Error 0xffffffff
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1954)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1242)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:516)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:478)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1402)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1368)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1343)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 

``` 

I reference the widevine sample from https://integration.widevine.com/player

test sample:
https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd
license url:
https://proxy.staging.widevine.com/proxy

```
drmSessionManager =
                    DefaultDrmSessionManager.Builder()
                        //keyRequest 很重要
                        .setKeyRequestParameters(mapOf(
                            "MDAwMDAwMDAwMDAwMDAwMQ==" to "eKHcBkYRlwfpA1FNigBzXw==",
                            "MDAwMDAwMDAwMDAwMDAwMw==" to "QkZshCrBxUObHgwJ+7Th0g==",
                            "MDAwMDAwMDAwMDAwMDAwMg==" to "Hzeeo4xw5Af3ayPsZAHK7w==",
                            "MDAwMDAwMDAwMDAwMDAwMA==" to "Pwoz80CYueIrwHjgobXoVA==",
                            "MDAwMDAwMDAwMDAwMDAwNA==" to "IvCfhLVopdAH5LHRFpQ1gQ==",
                            "MDAwMDAwMDAwMDAwMDAwNQ==" to "msMDbgSsnSvpRu1iQFFJvA==",
                            "MDAwMDAwMDAwMDAwMDAwNg==" to "MUWYWCQzTsTLSsS9w+K+7w==",
                            "MDAwMDAwMDAwMDAwMDAwNw==" to "ebhzT7mNJ1qQempaFQEouw=="
                        ))
                        .build(HttpMediaDrmCallback("https://proxy.staging.widevine.com/proxy", DefaultHttpDataSourceFactory("user-agent")))
```

**Comment by krocard** [comment]
@AquilesCanta can you take a look? I think bare Surface are not suitable for DRM and a SurfaceView is needed.

**Comment by icbaker** [comment]
> Error msg:
> 
> ```
> native window cannot handle protected buffers: the consumer should either be a hardware composer or support hardware protection
> ```
> 
> How to fix this error? does it lack the video codec?

This error is from the Android framework, not ExoPlayer. The causes likely depend on the Widevine licence policy and device being used. We may be able to help if you can provide the info necessary to reproduce it. 

Please either provide instructions for us to reproduce the problem with the [demo app](https://exoplayer.dev/demo-application.html) or provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

-----


> even I play widevine sample via exoplayer + surfaceView, it is only able to play once. there is the related error msg below.

There isn't enough information here to help you with this part. As above, please provide enough info for us to reproduce the problem with the demo app or in a minimal reproducible example Android Studio project.

----

>```
> drmSessionManager =
>                     DefaultDrmSessionManager.Builder()
>                         //keyRequest 很重要
>                         .setKeyRequestParameters(mapOf(
>                             "MDAwMDAwMDAwMDAwMDAwMQ==" to "eKHcBkYRlwfpA1FNigBzXw==",
>                             "MDAwMDAwMDAwMDAwMDAwMw==" to "QkZshCrBxUObHgwJ+7Th0g==",
>                             "MDAwMDAwMDAwMDAwMDAwMg==" to "Hzeeo4xw5Af3ayPsZAHK7w==",
>                             "MDAwMDAwMDAwMDAwMDAwMA==" to "Pwoz80CYueIrwHjgobXoVA==",
>                             "MDAwMDAwMDAwMDAwMDAwNA==" to "IvCfhLVopdAH5LHRFpQ1gQ==",
>                             "MDAwMDAwMDAwMDAwMDAwNQ==" to "msMDbgSsnSvpRu1iQFFJvA==",
>                             "MDAwMDAwMDAwMDAwMDAwNg==" to "MUWYWCQzTsTLSsS9w+K+7w==",
>                             "MDAwMDAwMDAwMDAwMDAwNw==" to "ebhzT7mNJ1qQempaFQEouw=="
>                         ))
>                         .build(HttpMediaDrmCallback("https://proxy.staging.widevine.com/proxy", DefaultHttpDataSourceFactory("user-agent")))
>```

This looks like you might be sending (sample) Widevine key IDs and key values in the HTTP headers of every license request you make. This seems strange - I suspect you don't mean to be doing this. In a production app you wouldn't want to build your content keys into the code...

**Comment by dendrocyte** [comment]
I report the issue#8668 via mail and provide a minimal reproducible example to my github.
sorry for the late reply.

**Comment by icbaker** [comment]
> I report the issue#8668 via mail

I can't find this email. Can you double check you sent it to "dev.exoplayer@gmail.com" with the subject "Issue #8668"?

----

I'm unable to reproduce the error seen in this case:
> even I play widevine sample via exoplayer + surfaceView, it is only able to play once. there is the related error msg below.

To try and repro this I:
* Cloned https://github.com/dendrocyte/WidevineTest at https://github.com/dendrocyte/WidevineTest/commit/51fc41a62c888900b940063214ce8e349abad83b
* Ran the app on a Pixel 3a XL
* The video started playing automatically
* I seeked to near the end using the UI seek bar
* At the end of the video it paused
* I pressed play again, and it played again.

Aside:
This project seems to use an intermediary library: 
```
implementation 'com.shuyu:gsyVideoPlayer-java:8.1.0' //v7.1.8支援exoplayer 1.12.1
//是否需要ExoPlayer模式
implementation 'com.shuyu:GSYVideoPlayer-exo2:8.1.0' //v7.1.8支援exoplayer 1.12.1
```

We don't know what this library is doing in between your code and ExoPlayer so we can't really offer any support with it.

An ideal minimal repro would only use the ExoPlayer libraries directly. In fact, it seems like you should be able to use the demo app directly with the following JSON:

```
{
  "name": "Issue #8668",
  "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd",
  "drm_scheme": "widevine",
  "drm_license_uri": "https://proxy.staging.widevine.com/proxy"
},
```

I suggest you try that in the ExoPlayer demo app on the devices you're seeing problems on. If you still see problems then please reply here with a bug report (produced by `adb bugreport`) and details of the device used. If it works with the ExoPlayer demo app then it's an issue either in your app code or the intermediary library, and you're likely best off following up with them directly.

**Comment by dendrocyte** [comment]
The demo app and your advise help me a lot!
I fix the bug in my app after comparing from demo app:
'even I play widevine sample via exoplayer + surfaceView, it is only able to play once' 
-> does not re-build drmSessionManager
'native window cannot handle protected buffers: the consumer should either be a hardware composer or support hardware protection'
-> does not stopPlayback when remove the surface

You can close the issue.

**Comment by icbaker** [comment]
Glad you got it sorted! :)
