### ISSUE TITLE
UnrecognizedInputFormatException

### ISSUE THREAD

**Issue by davidohne** [google/ExoPlayer#8672]
I'm using a media player which uses Exoplayer to watch live tv with a m3u file (example sent to you by mail).

The playlist can be opened in VLC and Perfect Player but when I try to use it with exoplayer FireTv 4k stick logs say this:

```
03-03 21:11:05.160 31270  2517 E ExoPlayerImplInternal: Source error.
03-03 21:11:05.160 31270  2517 E ExoPlayerImplInternal: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (e, g, j, e, j, f, g0, c, d, z, b, b, h) could read the stream.
03-03 21:11:05.160 31270  2517 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.v$b.b(ProgressiveMediaPeriod.java:14)
03-03 21:11:05.160 31270  2517 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.v$a.a(ProgressiveMediaPeriod.java:14)
03-03 21:11:05.160 31270  2517 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.Loader$d.run(Loader.java:4)
03-03 21:11:05.160 31270  2517 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-03 21:11:05.160 31270  2517 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-03 21:11:05.160 31270  2517 E ExoPlayerImplInternal: 	at java.lang.Thread.run(Thread.java:761)
03-03 21:11:05.997 31270  2517 E ExoPlayerImplInternal: Source error.
03-03 21:11:05.997 31270  2517 E ExoPlayerImplInternal: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (e, g, j, e, j, f, g0, c, d, z, b, b, h) could read the stream.
03-03 21:11:05.997 31270  2517 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.v$b.b(ProgressiveMediaPeriod.java:14)
03-03 21:11:05.997 31270  2517 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.v$a.a(ProgressiveMediaPeriod.java:14)
03-03 21:11:05.997 31270  2517 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.Loader$d.run(Loader.java:4)
03-03 21:11:05.997 31270  2517 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-03 21:11:05.997 31270  2517 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-03 21:11:05.997 31270  2517 E ExoPlayerImplInternal: 	at java.lang.Thread.run(Thread.java:761)
03-03 21:11:07.066 31270  2517 E ExoPlayerImplInternal: Source error.
03-03 21:11:07.066 31270  2517 E ExoPlayerImplInternal: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (e, g, j, e, j, f, g0, c, d, z, b, b, h) could read the stream.
03-03 21:11:07.066 31270  2517 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.v$b.b(ProgressiveMediaPeriod.java:14)
03-03 21:11:07.066 31270  2517 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.v$a.a(ProgressiveMediaPeriod.java:14)
03-03 21:11:07.066 31270  2517 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.Loader$d.run(Loader.java:4)
03-03 21:11:07.066 31270  2517 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-03 21:11:07.066 31270  2517 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-03 21:11:07.066 31270  2517 E ExoPlayerImplInternal: 	at java.lang.Thread.run(Thread.java:761)
```

Device: Amazon Fire TV 4k Stick
Content: Sent to you by mail

**Comment by krocard** [comment]
From the exception, ExoPlayer choose to use a `ProgressiveMediaSource` for the media instead of the correct `HlsMediaSource`. This is because, from https://exoplayer.dev/hls.html:
> If your URI doesn’t end with .m3u8, you can pass MimeTypes.APPLICATION_M3U8 to setMimeType of MediaItem.Builder to explicitly indicate the type of the content.

Either rename your file to the standard extension `m3u8` or explicitly pass to ExoPlayer that the MimeType is `APPLICATION_M3U8`.

**Comment by icbaker** [comment]
The file provided looks like it might be an [m3u playlist](https://en.wikipedia.org/wiki/M3U), not an HLS playlist (m3u8). These are not supported by ExoPlayer: https://github.com/google/ExoPlayer/issues/4066 If this is the case then setting the MIME type as suggested by @krocard won't work (you'll just get a different exception from `HlsMediaSource`).
