### ISSUE TITLE
Apple LL HLS occasionally hangs

### ISSUE THREAD

**Issue by natario1** [google/ExoPlayer#8679]
I'm trying to play an Apple LL HLS stream with 2.13.2 and having several issues. This is one of them which might be actionable, as at least I have a stack trace. It happens occasionally, both when joining the stream or during playback, likely when refreshing the playlist. Note that this is only logged, it does not generate a player exception and the app does not crash.

```
2021-03-05 19:29:33.656 19692-22935/io.video.videokit.demo E/LoadTask: Unexpected exception handling load completed
      java.lang.IndexOutOfBoundsException: index (0) must be less than size (0)
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1402)
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1384)
        at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77)
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextMediaSequenceAndPartIndex(HlsChunkSource.java:713)
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.createMediaChunkIterators(HlsChunkSource.java:577)
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:341)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:708)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continuePreparing(HlsSampleStreamWrapper.java:249)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.buildAndPrepareSampleStreamWrappers(HlsMediaPeriod.java:524)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.prepare(HlsMediaPeriod.java:160)
        at com.google.android.exoplayer2.source.MaskingMediaPeriod.createPeriod(MaskingMediaPeriod.java:130)
        at com.google.android.exoplayer2.source.MaskingMediaSource.onChildSourceInfoRefreshed(MaskingMediaSource.java:209)
        at com.google.android.exoplayer2.source.MaskingMediaSource.onChildSourceInfoRefreshed(MaskingMediaSource.java:37)
        at com.google.android.exoplayer2.source.CompositeMediaSource.lambda$prepareChildSource$0$CompositeMediaSource(CompositeMediaSource.java:113)
        at com.google.android.exoplayer2.source.-$$Lambda$CompositeMediaSource$lU5TDdLYJk4FzgCLkUChati_nlA.onSourceInfoRefreshed(Unknown Source:4)
        at com.google.android.exoplayer2.source.BaseMediaSource.refreshSourceInfo(BaseMediaSource.java:84)
        at com.google.android.exoplayer2.source.hls.HlsMediaSource.onPrimaryPlaylistRefreshed(HlsMediaSource.java:586)
        at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker.onPlaylistUpdated(DefaultHlsPlaylistTracker.java:401)
        at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker.access$1200(DefaultHlsPlaylistTracker.java:52)
        at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.processLoadedPlaylist(DefaultHlsPlaylistTracker.java:705)
        at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:560)
        at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:488)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:481)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

On top of this, I'm also experiencing other freezing issues but with no logs. Just stuck in `Player.STATE_BUFFERING`, though still receiving `onTimelineChanged` for example. I'd appreciate any hints as to how to investigate these issues deeper, e.g. enable extra logging, give you more information, provide you with a stream url (you'd have to look at it while it's active, I don't have a permanent url, so we need some kind of coordination in this case). We're using Wowza streaming engine.

Rarely (like twice) I also got onPlayerError() callback mentioning a 404 error. This would hint at a server issue, but given that Apple LL HLS implementation is so new in exoplayer, I figured I would let you know, just in case it triggers something in your head.

**Comment by marcbaechinger** [comment]
Yeah, best would be if we can test with a sample stream. If you can't share test content publicly, please send the uri to dev.exoplayer@gmail.com using a subject in the format "Issue #8679". Please also update this issue to indicate you’ve done this.

The error message of the stack trace says the playlist has an empty list of segments. So it would be helpful to see the playlist to evaluate whether the playlist is invalid, or something went wrong with merging in case you are using skipped segments. So to have a look it would be really helpful to be able to test with the infrastructure on which you are seeing these issues.

**Comment by stari4ek** [comment]
I am getting it also after updating to r2.13.2 (from v2.12.3)

```
Non-fatal Exception: java.lang.IndexOutOfBoundsException: index (38) must be less than size (22)
       at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1402)
       at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1384)
       at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77)
       at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextSegmentHolder(HlsChunkSource.java:470)
       at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:402)
       at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:717)
       at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:80)
       at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading(HlsMediaPeriod.java:365)
       at com.google.android.exoplayer2.source.MaskingMediaPeriod.continueLoading(MaskingMediaPeriod.java:226)
       at com.google.android.exoplayer2.MediaPeriodHolder.continueLoading(MediaPeriodHolder.java:217)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:2180)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:2143)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

All logs I checked in Crashlytics which has this exception are the same and does not have any other oddities except shorter window. Obfuscated callstrack in the log is the same as above:
```
16:56:49 EventLogger: timeline [eventTime=93.69, mediaPos=144.49, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
16:56:49 EventLogger:   period [?]
16:56:49 EventLogger:   window [160.16, seekable=true, dynamic=true]
16:56:49 EventLogger: ]
16:56:54 EventLogger: timeline [eventTime=98.72, mediaPos=145.50, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
16:56:54 EventLogger:   period [?]
16:56:54 EventLogger:   window [160.16, seekable=true, dynamic=true]
16:56:54 EventLogger: ]
16:56:59 EventLogger: timeline [eventTime=103.76, mediaPos=146.55, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
16:56:59 EventLogger:   period [?]
16:56:59 EventLogger:   window [160.16, seekable=true, dynamic=true]
16:56:59 EventLogger: ]
16:57:04 EventLogger: timeline [eventTime=108.79, mediaPos=143.57, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
16:57:04 EventLogger:   period [?]
16:57:04 EventLogger:   window [160.16, seekable=true, dynamic=true]
16:57:04 EventLogger: ]
16:57:09 EventLogger: timeline [eventTime=113.85, mediaPos=144.62, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
16:57:09 EventLogger:   period [?]
16:57:09 EventLogger:   window [68.07, seekable=true, dynamic=true]
16:57:09 EventLogger: ]
16:57:09 EventLogger: videoDisabled [eventTime=113.89, mediaPos=144.62, window=0, period=0]
16:57:09 EventLogger: audioDisabled [eventTime=113.89, mediaPos=144.62, window=0, period=0]
16:57:09 EventLogger: videoDecoderReleased [eventTime=113.94, mediaPos=144.62, window=0, period=0, OMX.amlogic.avc.decoder.awesome]
16:57:09 EventLogger: audioDecoderReleased [eventTime=113.95, mediaPos=144.62, window=0, period=0, OMX.google.aac.decoder]
16:57:09 EventLogger: playerFailed [eventTime=113.95, mediaPos=144.62, window=0, period=0   com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error       at a.e.a.b.n0.handleMessage(ExoPlayerImplInternal.java:33)       at android.os.Handler.dispatchMessage(Handler.java:102)       at android.os.Looper.loop(Looper.java:193)       at android.os.HandlerThread.run(HandlerThread.java:65)   Caused by: java.lang.IndexOutOfBoundsException: index (39) must be less than size (17)       at a.e.a.c.c.a.w(Unknown Source:5)       at a.e.b.b.e2.get(RegularImmutableList.java:1)       at a.e.a.b.b2.t0.q.g(HlsSampleStreamWrapper.java:61)       at a.e.a.b.b2.o.g(CompositeSequenceableLoader.java:4)       at a.e.a.b.b2.t0.o.g(HlsMediaPeriod.java:5)       at a.e.a.b.b2.v.g(MaskingMediaPeriod.java:1)       at a.e.a.b.n0.y(ExoPlayerImplInternal.java:22)       at a.e.a.b.n0.p(ExoPlayerImplInternal.java:4)       at a.e.a.b.n0.handleMessage(ExoPlayerImplInternal.java:21)       ... 3 more ]
```

it looks like it tries to use chunk index based on old (larger) window.

**Comment by marcbaechinger** [comment]
Do you have a URI for which this exception is thrown?

**Comment by stari4ek** [comment]
Sorry. Just observing automatically uploaded crashlytics logs. So, no media info.
