### ISSUE TITLE
General Drm error while attempt to play DASH + Widevine

### ISSUE THREAD

**Issue by aSLmolly** [google/ExoPlayer#8695]
I am experiencing the following issue when trying to play content with Dash and Widevine.
The exception it is raised in this line of code:

```
  mediaDrm.provideKeyResponse(sessionId, (byte[]) response);
```

```
E/MediaDrm-JNI: Illegal state exception: Failed to handle key response: General DRM error (-2000)
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:579)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: General DRM error
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:524)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:519)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:504)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:58)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:563)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: General DRM error
        at android.media.MediaDrm.provideKeyResponse(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(FrameworkMediaDrm.java:228)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:492)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:58) 
        at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:563) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

 The license seems to be acquired correctly but for some reason the MediaDrm is failing to process it.
 
Already visited and investigated all similar issues.

More information dropped to dev.exoplayer@gmail.com.

**Comment by icbaker** [comment]
@rrfrias Can you take a look? It looks like the Widevine CDM didn't like the provided response:

```
I WVCdm   : [cdm_engine.cpp(327):AddKey] CdmEngine::AddKey: sid3
E WVCdm   : [license.cpp(934):ExtractProviderSessionToken] CdmLicense::ExtractProviderSessionToken: unable to parse signed license response
E WVCdm   : [license.cpp(529):HandleKeyResponse] CdmLicense::HandleKeyResponse: unable to parse signed license response
E WVCdm   : [cdm_engine.cpp(400):AddKey] CdmEngine::AddKey: keys not added, result = 70
W WVCdm   : Returns UNKNOWN error for legacy status: 70
W WVCdm   : Returns UNKNOWN error for legacy status: 70
```

**Comment by AbdoulMDiscovery** [comment]
@aSLmolly were you able to solve this issue? I am currently facing the same issue.

**Comment by rrfrias** [comment]
@AbdoulMDiscovery you can send a bugreport to dev.exoplayer@gmail.com to have us investigate. It might be better to create a separate issue.
