### ISSUE TITLE
2.13.2 Source error on m4a files in release mode

### ISSUE THREAD

**Issue by krottv** [google/ExoPlayer#8709]
ExoPlayer version 2.13.2 (on 2.12.3 everything is fine)
Android - any version

In release mode I have minify enabled = true. And mp4, m4a files cannot be played - Source error.
Link for test - https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview124/v4/ab/15/31/ab1531f7-be5a-4be1-a007-113e6f87f235/mzaf_16276103177644625463.plus.aac.p.m4a

If I make apk in debug mode then everything works fine.

How I create exoPlayer instance - SimpleExoPlayer.Builder(context)

Seems like exoPlayer lacks some proguard rules.

Error message
```
2021-03-12 11:02:03.597 18731-31574/? E/LoadTask: Unexpected exception loading stream
      java.lang.ClassCastException: e.j.a.c.z1.f cannot be cast to e.j.a.c.z1.d0.c
        at e.j.a.c.z1.g0.j.i(Mp4Extractor.java:144)
        at e.j.a.c.c2.a0$a.b(ProgressiveMediaPeriod.java:44)
        at com.google.android.exoplayer2.upstream.Loader$d.run(Loader.java:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2021-03-12 11:02:03.607 18731-31471/? E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at e.j.a.c.n0.handleMessage(ExoPlayerImplInternal.java:41)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ClassCastException: e.j.a.c.z1.f cannot be cast to e.j.a.c.z1.d0.c
        at com.google.android.exoplayer2.upstream.Loader$d.run(Loader.java:26)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.ClassCastException: e.j.a.c.z1.f cannot be cast to e.j.a.c.z1.d0.c
        at e.j.a.c.z1.g0.j.i(Mp4Extractor.java:144)
        at e.j.a.c.c2.a0$a.b(ProgressiveMediaPeriod.java:44)
        at com.google.android.exoplayer2.upstream.Loader$d.run(Loader.java:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2021-03-12 11:02:03.613 18731-18731/? E/exo-player: Source error
    com.google.android.exoplayer2.ExoPlaybackException: Source error
        at e.j.a.c.n0.handleMessage(ExoPlayerImplInternal.java:41)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ClassCastException: e.j.a.c.z1.f cannot be cast to e.j.a.c.z1.d0.c
        at com.google.android.exoplayer2.upstream.Loader$d.run(Loader.java:26)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.ClassCastException: e.j.a.c.z1.f cannot be cast to e.j.a.c.z1.d0.c
        at e.j.a.c.z1.g0.j.i(Mp4Extractor.java:144)
        at e.j.a.c.c2.a0$a.b(ProgressiveMediaPeriod.java:44)
        at com.google.android.exoplayer2.upstream.Loader$d.run(Loader.java:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by tonihei** [comment]
I can't reproduce this in the ExoPlayer demo app even when enabling R8 full mode. 

Code shrinking issues depend a lot on which methods are used exactly by your app, so it would be helpful if you could upload a small example project that reproduces the issue. 

Alternatively, it would also be helpful to see the `mapping.txt` file for your release build as it allows to resolve `e.j.a.c.z1.f` back to its original class name and could give some indication which cast went wrong exactly.
