### ISSUE TITLE
com.google.android.exoplayer2.ParserException: Loading finished before preparation is complete.

### ISSUE THREAD

**Issue by arlimm318** [google/ExoPlayer#8716]
I encountered an exception while playing a TS segment.  But  VLC plays normally.
Why does the EXOPlayer exception occur?The ts  doesn't look wrong.

[cctv13.zip](https://github.com/google/ExoPlayer/files/6139909/cctv13.zip)

playerFailed [eventTime=0.85, mediaPos=0.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:488)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.ParserException: Loading finished before preparation is complete.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.maybeThrowPrepareError(ProgressiveMediaPeriod.java:239)
        at com.google.android.exoplayer2.source.MaskingMediaPeriod.maybeThrowPrepareError(MaskingMediaPeriod.java:144)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:839)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:411)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by AquilesCanta** [comment]
The stream declares a track on PID 0x81 which is not present in the file: 

```
 Stream_type loop: 

            Stream_type: 3 (0x03)  [= ISO/IEC 11172 Audio]
            reserved_1: 7 (0x07)
            Elementary_PID: 256 (0x0100)
            reserved_2: 15 (0x0f)
            ES_info_length: 0 (0x0000)


            Stream_type: 27 (0x1b)  [= AVC video stream as defined in ITU-T Rec. H.264 | ISO/IEC 14496-10 Video]
            reserved_1: 7 (0x07)
            Elementary_PID: 257 (0x0101)
            reserved_2: 15 (0x0f)
            ES_info_length: 0 (0x0000)


            Stream_type: 129 (0x81)  [= User private]
            reserved_1: 7 (0x07)
            Elementary_PID: 258 (0x0102)
            reserved_2: 15 (0x0f)
            ES_info_length: 0 (0x0000)
```

There are no packets with PID 259. As a workaround you could implement a [TsPayloadReaderFactory](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/extractor/ts/TsPayloadReader.html) which is a thin wrapper around the [DefaultTsPayloadReaderFactory](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/extractor/ts/DefaultTsPayloadReaderFactory.html) but returns null for stream type 129. This is similar to #7873, so you should track that for library improvements around TS robustness.
