### ISSUE TITLE
IllegalArgumentException when switching the target PlayerView on Xiaomi MIBOX3 devices. Works when codecNeedsSetOutputSurfaceWorkaround set to true

### ISSUE THREAD

**Issue by szymonsc** [google/ExoPlayer#8718]
Issue description
-------------------------
When switching the target PlayerView the player stops playing with an IllegalArgumentException (similar to #4468/#6899/#8014/#8030). 

**We applied the output surface workaround for this device and confirmed the issue has gone.
Please include a new device model for the output surface workaround.**

```
diff --git a/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java b/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java
index 5908c6ff8f..996437d553 100644
--- a/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java
+++ b/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java
@@ -1604,6 +1604,7 @@ public class MediaCodecVideoRenderer extends MediaCodecRenderer {
         case "magnolia":
         case "machuca":
         case "oneday":
+        case "once":
           return true;
         default:
           break; // Do nothing.
```

Reproduction steps
-------------------------
- Create a layout with 2 player views
- Instantiate a simple ExoPlayer app and have it run a video on one of them
- Switch between the two views

Device info
-------------------------
- MANUFACTURER: Xiaomi
- MODEL: MIBOX3
- DEVICE: once
- SDK_INT: 28

ExoPlayer version
-------------------------
2.12.3

A full bug report captured from the device
-------------------------
It's not possible to collect bug reports using adb, because it was reported on the user device, but we have error stacktrace collected from logs

```
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal: Playback error
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:   d.d.b.c.m0: Unexpected runtime error
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:       at d.d.b.c.o0.handleMessage(Unknown Source:250)
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:193)
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:65)
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:   Caused by: java.lang.IllegalArgumentException
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_setSurface(Native Method)
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:       at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1979)
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.video.o.V1(Unknown Source:0)
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.video.o.W1(Unknown Source:68)
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.video.o.g(Unknown Source:5)
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:       at d.d.b.c.o0.l(Unknown Source:20)
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:       at d.d.b.c.o0.w0(Unknown Source:12)
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:       at d.d.b.c.o0.v0(Unknown Source:13)
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:       at d.d.b.c.o0.handleMessage(Unknown Source:121)
02-17 09:15:57.363  6367  8484 E ExoPlayerImplInternal:       ... 3 more
```

**Comment by AquilesCanta** [comment]
Can you please provide a bugreport shortly after reproducing the issue, as required by the issue template. You can capture a bugreport by running `adb bugreport`. [Internal ref: cl/363152330].
