### ISSUE TITLE
using `Surface` mode with `ImageReader` returns dequeueBuffer: BufferQueue has been abandoned

### ISSUE THREAD

**Issue by manjusha221** [google/ExoPlayer#8725]
Hi Team,
I want to get frames from video while playing, As mentioned in issue 
https://github.com/google/ExoPlayer/issues/7167

I tried with imagereader.getsurface() set to  player.setVideoSurface(mReaderSurface), video is not rendering and I see the error

" E/BufferQueueProducer: [ImageReader-1x1f23m1-8731-1] queueBuffer: BufferQueue(0x7f774a0b00) has been abandoned"

Can you please look into it, Is there anything Iam missing.

**Comment by AquilesCanta** [comment]
I don't think there's evidence enough to assume the pasted line has anything to do with the issue you are observing. 

Please provide complete information as requested in the issue template. The issue template can
be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.

In this specific case you should look into providing us with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by manjusha221** [comment]
Hi @AquilesCanta ,
Im attaching the surface of imagereader to exoplayer surface as follows

```
 ImageReader mReader = ImageReader.newInstance(1,1,ImageFormat.YUV_420_888,1);
    Surface mReaderSurface = mReader.getSurface();
    HandlerThread mHandlerThread = new HandlerThread("hh");
    mHandlerThread.start();
    Handler mHandler = new Handler(mHandlerThread.getLooper());
    mReader.setOnImageAvailableListener(this, mHandler);

    player.setVideoSurface(mReaderSurface);
```

when I tried to play the video, Im getting following error.

```
2021-03-19 11:59:21.256 6184-11784/com.google.android.exoplayer2.demo W/OpenGLRenderer: Surface doesn't have any previously queued frames, nothing to readback from
2021-03-19 11:59:21.274 6184-11784/com.google.android.exoplayer2.demo I/chatty: uid=10468(com.google.android.exoplayer2.demo) RenderThread identical 2 lines
2021-03-19 11:59:21.284 6184-11784/com.google.android.exoplayer2.demo W/OpenGLRenderer: Surface doesn't have any previously queued frames, nothing to readback from
2021-03-19 11:59:21.284 6184-12557/com.google.android.exoplayer2.demo E/BufferQueueProducer: [ImageReader-1x1f23m1-6184-1] queueBuffer: BufferQueue(0x7e87bdd080) has been abandoned
2021-03-19 11:59:21.284 6184-12557/com.google.android.exoplayer2.demo E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
2021-03-19 11:59:21.284 6184-12557/com.google.android.exoplayer2.demo E/ACodec: [OMX.qcom.video.decoder.avc] BaseState::onOutputBufferDrained returning error -19
2021-03-19 11:59:21.284 6184-12557/com.google.android.exoplayer2.demo E/ACodec: signalError(omxError 0x80001001, internalError -19)
2021-03-19 11:59:21.284 6184-12556/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported err 0xffffffed, actionCode 0, while in state 6
2021-03-19 11:59:21.286 6184-12556/com.google.android.exoplayer2.demo D/SurfaceUtils: disconnecting from surface 0x7ed5b39010, reason disconnectFromSurface
2021-03-19 11:59:21.288 6184-12553/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1/256, null, null, video/avc, avc1.4D401E, -1, null, [640, 360, -1.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1414)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:839)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:947)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:477)
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:82)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1779)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:824)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:947) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:477) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2021-03-19 11:59:21.289 6184-12553/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Disable failed.
```

**Comment by AquilesCanta** [comment]
The size of the image reader (1,1) looks suspicious for starters. 

However, debugging this is not something we have bandwidth for. If you have any evidence pointing at this being an ExoPlayer issue, or you are able to narrow down what the issue in your app is, we may be able to help. It may also make sense to post your question in a general Q&A site like StackOverflow.
