### ISSUE TITLE
DRM screen capture blocking not working on Android 7.0

### ISSUE THREAD

**Issue by vfutia** [google/ExoPlayer#8741]
Our team has setup DRM protection for videos and playback in ExoPlayer.  Everything works as expected in our tests with the exception of Android 7.0 (and possibly below but can't verify).  We observe that while DRM playback and license key download works as expected, users are able to capture the screen both through the default OS screen capture as well as through third party video capture apps.  

Everything, DRM video playback and screen capture blocking, worked as expected when we tried the following versions of Android:
- Android 11
- Android 10 (multiple devices)
- Android 9
- Android 7.1.1

Setup
- ExoPlayer 2.12.1
- Android 7.0
- Lenovo TB-8304F1, Galaxy S8
- DRM scheme : DASH Widevine cenc

**Comment by icbaker** [comment]
Does the license you're using require Widevine L1 or also allow L3?

Does this reproduce with the Widevine samples in the [demo app](https://exoplayer.dev/demo-application.html) (e.g. [`Widevine GTS policy tests > HW secure all (L1)`](https://github.com/google/ExoPlayer/blob/r2.12.1/demos/main/src/main/assets/media.exolist.json#L55)? If so, can you please provide a bug report taken after screen-capturing the recording from the demo app?

**Comment by vfutia** [comment]
We are only using Widevine L3

Installing the app on our 7.0 device consistently results in crash on startup.

```
    --------- beginning of crash
2021-03-23 03:42:06.416 8240-8240/com.google.android.exoplayer2.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.exoplayer2.demo, PID: 8240
    java.lang.RuntimeException: Unable to instantiate application androidx.multidex.MultiDexApplication: java.lang.ClassNotFoundException: Didn't find class "androidx.multidex.MultiDexApplication" on path: DexPathList[[zip file "/data/app/com.google.android.exoplayer2.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.exoplayer2.demo-1/lib/arm64, /data/app/com.google.android.exoplayer2.demo-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:807)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5477)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.multidex.MultiDexApplication" on path: DexPathList[[zip file "/data/app/com.google.android.exoplayer2.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.exoplayer2.demo-1/lib/arm64, /data/app/com.google.android.exoplayer2.demo-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newApplication(Instrumentation.java:992)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:801)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5477) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:203) 
        at android.app.ActivityThread.main(ActivityThread.java:6251) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.google.android.exoplayer2.demo-1/base.apk because: Failed to open dex file '/data/app/com.google.android.exoplayer2.demo-1/base.apk' from memory: Unrecognized version number in /data/app/com.google.android.exoplayer2.demo-1/base.apk: 0 3 9 
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:373)
        at dalvik.system.DexFile.<init>(DexFile.java:113)
        at dalvik.system.DexFile.<init>(DexFile.java:78)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:359)
        at dalvik.system.DexPathList.makeElements(DexPathList.java:323)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:263)
        at dalvik.system.DexPathList.<init>(DexPathList.java:126)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:525)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:558)
        at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1921)
        at android.app.LoadedApk.getResources(LoadedApk.java:771)
        at android.app.ContextImpl.<init>(ContextImpl.java:2055)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2000)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5394)
        		... 8 more
```

**Comment by vfutia** [comment]
Ok I was finally able to get the demo app to work.  We tried the demo app and were able to reproduce this issue on the device specified in the original post.  We tried both the L3 and L1 demo videos and in both cases, we were able to do a screen capture as well as a third party video capture of the DRM protected file.  

Below are the logs taken and their associated activities:

[L1 Screen Capture](https://drive.google.com/file/d/1XKU92LvvE3MrpSG3nhlREwh3MseRK-Tw/view?usp=sharing)
[L1 Video Capture](https://drive.google.com/file/d/1WShXWWSka5sO_LwLgzFJGMC0zs5UVpOY/view?usp=sharing)
[L3 Screen Capture](https://drive.google.com/file/d/1-2qKEMbKYVqs6JsRRnCu3bjxvhe2jkVQ/view?usp=sharing)
[L3 Video Capture](https://drive.google.com/file/d/150cDH64UzlvAByNggu4_UqWFOpcIJuQp/view?usp=sharing)

Additionally, here's a [DRM Info capture](https://drive.google.com/file/d/1C_x2R0PHgfbtMuAAg9bgg4XrKGLKWv4i/view?usp=sharing) from the device in question.

**Comment by icbaker** [comment]
The logcat snippets you've provided aren't [bug reports](https://developer.android.com/studio/debug/bug-report) which contain much more useful info. If you're able to provide full bug reports that would be more helpful.

I'm confused by some things in the log snippets you've provided though:
* The DRM Info screenshot shows the device only supports up to L3, so it shouldn't be able to play the L1 content at all. At the bottom of the L1 logcats I see a playback error at `mediaPos=11.04` - is it possible you're just playing (and screenshotting) the clear-lead? The content I suggested you try in the demo app has an initial 10s of unencrypted content.
* In all the logs the device doesn't seem to be using a secure video decoder. The decoder name is `OMX.MTK.VIDEO.DECODER.AVC` while [`MediaCodec` javadoc](https://developer.android.com/reference/android/media/MediaCodec) says "the name of all secure codecs must end in ".secure".". I also don't see any of the logging that I'd expect from the Widevine CDM - though this may be only present in a full bug report.

Please can you reproduce again with the demo app playing the widevine L3 and L1 samples, ensure you play each for at least 15s without seeing an error and make your screenshot/recording after the 10s point in the content - then take bug reports (`adb bugreport`) and provide them here.

Thanks!

**Comment by vfutia** [comment]
Apologize for the confusion about the bug report.

We tried this again with L1 and the video stopped playing at around 11 secs so that appears to be working as expected.

For L3, we ran it again and around 20 secs in we captured the screen and the video was plainly visible in the screenshot.

[Bug report post screenshot](https://drive.google.com/file/d/1jEbBM_-7ua8BTa5bArDWOvfYN4XswiuX/view?usp=sharing)

**Comment by icbaker** [comment]
Thanks for the BR - it doesn't include any of the additional logging I'd expect from the Widevine CDM and the decoder name is the same (i.e. doesn't seem to be picking a 'secure' decoder).

Having done a bit more research, I've realised the fact the decoder isn't 'secure' indicates this device doesn't have a secure output path.  This results in screenshots/capturing being permitted by default. You can block screenshots by calling `SurfaceView#setSecure()` on the surface you attach to the player, but note that a determined attacker can still likely get hold of the video/image bytes (WV L1 + secure output path is designed to prevent this).

I managed to reproduce the behaviour on my Pixel 3a XL by 'disabling' the secure decoders by adding this to the top of `MediaCodecUtil#isCodecUsableDecoder`:
```
if (name.endsWith(".secure")) {
  return false;
}
```

That resulted in it using a normal decoder for L3 playback, which allowed screenshots. And calling `SurfaceView#setSecure(true)` inside `(Styled)PlayerView` resulted in screenshots being blocked completely.
