### ISSUE TITLE
UUID Smooth Streaming exception UnsupportedSchemeException

### ISSUE THREAD

**Issue by funsecurity** [google/ExoPlayer#875]
Hi,

I'm trying to play protected with "Smooth Streaming " content, but to try to parse the ProtectionHeader and get the UUID , an exception of "schema not supported" . Do not try to connect to the license server or anything.

UUID is "9a04f079-9840-4286-ab92-e65be0885f95"

Thank you.

Exception:

    com.google.android.exoplayer.drm.UnsupportedDrmException: android.media.UnsupportedSchemeException: Failed to instantiate drm object.
            at com.google.android.exoplayer.drm.StreamingDrmSessionManager.<init>(StreamingDrmSessionManager.java:182)
            at com.google.android.exoplayer.demo.player.SmoothStreamingRendererBuilder$AsyncRendererBuilder.onSingleManifest(SmoothStreamingRendererBuilder.java:154)
            at com.google.android.exoplayer.demo.player.SmoothStreamingRendererBuilder$AsyncRendererBuilder.onSingleManifest(SmoothStreamingRendererBuilder.java:93)

**Comment by ojw28** [comment]
Aside from AndroidTV devices, most Android devices don't provide platform support for PlayReady DRM (which is what this UUID corresponds to).

**Comment by objectiveCarlo** [comment]
This sucks because our DRMs are in classic widevine (using widevine://) and PlayReady (UUID = 9a04f079-9840-4286-ab92-e65be0885f95) both are not working on exoplayer. 

Do you guys have any suggestions on how to do DRM support that will cover almost all android devices? 
Thanks

**Comment by ojw28** [comment]
If you want to cover almost all Android devices, you should use Widevine Classic (for older devices) and Widevine Modular (for newer ones). PlayReady is normally only supported on AndroidTV devices, as far as I know.
