### ISSUE TITLE
find OutOfMemoryError in com.google.android.exoplayer2.util.Log.getThrowableString

### ISSUE THREAD

**Issue by huozhezhazha** [google/ExoPlayer#8771]
**Whether you can solve this problem** 

java.lang.OutOfMemoryError
Failed to allocate a 512 byte allocation with 128 free bytes and 128B until OOM, target footprint 536870912, growth limit 536870912
at java.util.Arrays.copyOf(Arrays.java:3257)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
at java.lang.StringBuffer.append(StringBuffer.java:367)
at java.io.StringWriter.write(StringWriter.java:94)
at com.android.internal.util.FastPrintWriter.flushLocked(FastPrintWriter.java:382)
at com.android.internal.util.FastPrintWriter.appendLocked(FastPrintWriter.java:322)
at com.android.internal.util.FastPrintWriter.print(FastPrintWriter.java:499)
at java.io.PrintWriter.println(PrintWriter.java:756)
at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:778)
at java.lang.Throwable.printStackTrace(Throwable.java:670)
at java.lang.Throwable.printStackTrace(Throwable.java:735)
at android.util.Log.getStackTraceString(Log.java:378)
at com.google.android.exoplayer2.util.Log.getThrowableString(Log.java:156)
at com.google.android.exoplayer2.util.Log.appendThrowableString(Log.java:161)
at com.google.android.exoplayer2.util.Log.e(Log.java:127)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:448)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:929)

**Comment by lcf87** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can
be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.
