### ISSUE TITLE
DownloadTracker: Failed to fetch offline DRM license

### ISSUE THREAD

**Issue by ChetanPatelSS** [google/ExoPlayer#8794]
I need to play DRM-protected content offline.

However, after building the DRM session, the following error is thrown:

```
DownloadTracker: Failed to fetch offline DRM license
      com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:524)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:519)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:482)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:58)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:563)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:194)
```

**Comment by ojw28** [comment]
The server is responding with an [HTTP 403](https://en.wikipedia.org/wiki/HTTP_403). It's not possible for us to assist you further unless you properly fill out the issue template. Note also that this may well be a server-side issue.

**Comment by ChetanPatelSS** [comment]
@ojw28 @google-oss-bot thanks for help, yes issues is resolved.
