### ISSUE TITLE
Error when attempting to resume after activity has resumed

### ISSUE THREAD

**Issue by darussian** [google/ExoPlayer#881]
We are working with ad partners that run their ads using a VideoView in a separate activity causing the video activity to call onStop. When returning back to the activity where Exoplayer is I receive the following error  when i attempt to resume the video

```
10-19 13:08:16.218    9022-9241/com.dramafever.large E/Surface﹕ queueBuffer: error queuing buffer to SurfaceTexture, -19
10-19 13:08:16.218    9022-9241/com.dramafever.large E/ACodec﹕ signalError(omxError 0x80001001, internalError -19)
10-19 13:08:16.219    9022-9240/com.dramafever.large E/MediaCodec﹕ Codec reported err 0xffffffed, actionCode 0, while in state 6
10-19 13:08:16.221    9022-9195/com.dramafever.large E/ExoPlayerImplInternal﹕ Internal runtime error.
    java.lang.IllegalStateException
            at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
            at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:802)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:458)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```
I make sure that the Surface is sent to the video renderer when it is recreated
```
player.blockingSendMessage(currentSource.renderers[TRACK_INDEX_TYPE_VIDEO], MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, holder.getSurface());
```

Is it viable to resume playing the video using the Same ExoPlayer instance or do I have to release the previous one and create a new one?

This is using exoplayer r1.5.0

**Comment by ojw28** [comment]
My understanding is this was resolved by properly clearing the surface when it became invalid.
