### ISSUE TITLE
IMA NullPointerException when invoking android.graphics.Bitmap.getWidth()

### ISSUE THREAD

**Issue by gilbertdigio** [google/ExoPlayer#8819]
Issue:
-------------------------
We are detecting suddenly a lot of NullPointerException's in Firebase coming from IMA since April 8th. It's happening in several versions, not specefic one. We are using ExoPlayer 2.12.3.

Someone mentions the same issue in a comment to this post: https://github.com/google/ExoPlayer/issues/8447#issuecomment-802407326

Stacktrace:
-------------------------
`Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:355)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
       at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:784)`

`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at com.google.ads.interactivemedia.v3.internal.amt.a(amt.java:3)
       at com.google.ads.interactivemedia.v3.internal.amr.doInBackground(amr.java:12)
       at android.os.AsyncTask$2.call(AsyncTask.java:334)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
       at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:784)`

REPRODUCTION STEPS:
-------------------------
No reproduction steps.

Exoplayer version:
-------------------------
ExoPlayer 2.12.3.

Device(s) and version(s) of Android being used
-------------------------
Device and OS independent

**Comment by andrewlewis** [comment]
This should be fixed in IMA SDK 3.23.0 which is [used by ExoPlayer 2.13.3](https://github.com/google/ExoPlayer/blob/r2.13.3/extensions/ima/build.gradle#L28). Please reply here if you can still reproduce on that version.
