### ISSUE TITLE
Exoplayer v2.13.3 can't play  60 fps media

### ISSUE THREAD

**Issue by ag2s20150909** [google/ExoPlayer#8873]
#5921
- ExoPlayer version number 2.13.3
- Android version 7.1.2
- Android device vivo x9

```    
E/ExoPlayerImplInternal: Playback error
          com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640034, -1, null, [3840, 2024, 59.999996], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:154)
            at android.os.HandlerThread.run(HandlerThread.java:61)
         Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.640034, -1, null, [3840, 2024, 59.999996], [-1, -1])
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1018)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:578)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1420)
            at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:694)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:965)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:811)
            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:948)
            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
            at android.os.Handler.dispatchMessage(Handler.java:98) 
            at android.os.Looper.loop(Looper.java:154) 
            at android.os.HandlerThread.run(HandlerThread.java:61) 
         Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
            at android.media.MediaCodec.native_configure(Native Method)
            at android.media.MediaCodec.configure(MediaCodec.java:1884)
            at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.configure(SynchronousMediaCodecAdapter.java:61)
            at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:620)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1110)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1011)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:578) 
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1420) 
            at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:694) 
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:965) 
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:811) 
            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:948) 
            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478) 
            at android.os.Handler.dispatchMessage(Handler.java:98) 
            at android.os.Looper.loop(Looper.java:154) 
            at android.os.HandlerThread.run(HandlerThread.java:61) 
    D/EventLogger: videoDisabled [eventTime=33.18, mediaPos=0.00, window=0, period=0]
    D/EventLogger: audioDisabled [eventTime=33.18, mediaPos=0.00, window=0, period=0]
    E/EventLogger: playerFailed [eventTime=33.18, mediaPos=0.00, window=0, period=0
          com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640034, -1, null, [3840, 2024, 59.999996], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:154)
            at android.os.HandlerThread.run(HandlerThread.java:61)
         Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.640034, -1, null, [3840, 2024, 59.999996], [-1, -1])
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1018)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:578)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1420)
            at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:694)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:965)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:811)
            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:948)
            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
            at android.os.Handler.dispatchMessage(Handler.java:98) 
            at android.os.Looper.loop(Looper.java:154) 
            at android.os.HandlerThread.run(HandlerThread.java:61) 
         Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
            at android.media.MediaCodec.native_configure(Native Method)
            at android.media.MediaCodec.configure(MediaCodec.java:1884)
            at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.configure(SynchronousMediaCodecAdapter.java:61)
            at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:620)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1110)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1011)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:578) 
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1420) 
            at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:694) 
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:965) 
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:811) 
            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:948) 
            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478) 
            at android.os.Handler.dispatchMessage(Handler.java:98) 
            at android.os.Looper.loop(Looper.java:154) 
            at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by kim-vde** [comment]
I suspect that the renderer is not capable of handling the video, which wouldn't be surprising as the resolution seems to be 4K. Indeed, the format printed in the logs (`format=Format(1, null, null, video/avc, avc1.640034, -1, null, [3840, 2024, 59.999996], [-1, -1])`) indicates that the video width is 3840 pixels and that its height is 2024 pixels.

- Was it working with a previous version of ExoPlayer?
- Does it play with MediaPlayer?
- Could you send us a test content that reproduces the issue? If you're unable to share it publicly, please send it to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.

**Comment by ag2s20150909** [comment]
> I suspect that the renderer is not capable of handling the video, which wouldn't be surprising as the resolution seems to be 4K. Indeed, the format printed in the logs (`format=Format(1, null, null, video/avc, avc1.640034, -1, null, [3840, 2024, 59.999996], [-1, -1])`) indicates that the video width is 3840 pixels and that its height is 2024 pixels.
> 
> * Was it working with a previous version of ExoPlayer?
> * Does it play with MediaPlayer?
> * Could you send us a test content that reproduces the issue? If you're unable to share it publicly, please send it to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using a subject in the format
>   "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
>   indicate you've done this.

I test on my new Android 10 devices,it work.Maybe  the cpu is too old.

**Comment by icbaker** [comment]
Content for this issue has been provided over email.

**Comment by kim-vde** [comment]
Thanks @icbaker.

The content provided also plays on my Pixel test device. The AVC decoders on your vivo device are probably unable to decode such a resolution.

If you want to be sure, you can debug and check what happens in `MediaCodecVideoRenderer.supportsFormat()` or in `MediaCodecRenderer.maybeInitCodecWithFallback()`.
