### ISSUE TITLE
Android Tv app crashes with BehindLiveWindowException at getNextChunk when release the network from throttled low bandwidth

### ISSUE THREAD

**Issue by toseefawan** [google/ExoPlayer#8907]
### Description: 
Android Tv app crashes with `BehindLiveWindowException` at `getNextChunk` when release the network from throttled low bandwidth like 200Kbps, 400Kbps. Also when we throttle the network during playback and release throttle we get the same crash.

### Steps to reproduce:
Use a tool (like Charles proxy) to throttle the CDN to a low bandwidth setting (eg: 200Kbps).
Start playback linear channel (Live stream)
Wait for video to load (buffer) for 10 seconds, then release the throttle.
### Expected behaviour:
Linear stream should start playing.

### Actual behaviour:
App crashes

### version info:

- ExoPlayer 2.11.7
- Android version: Based on Android 9
- Android device: 
- Fire OS Version: Fire OS 7
- Android Tv Devices: Most devices with Fire OS 7 e.g. Fire TV Stick - 3rd Gen (2020) sofware version: 7.2.2.8, Fire TV Stick Lite – 1st Gen (2020) and Fire TV Edition - JVC Smart HD/FHD (2020)

### Logs:

Here is the logcat - an exoplayer exception is causing the crash - particularly interested in BehindLiveWindowException at getNextChunk.

 ```
   com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.BehindLiveWindowException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.source.BehindLiveWindowException
        at com.google.android.exoplayer2.source.smoothstreaming.DefaultSsChunkSource.getNextChunk(DefaultSsChunkSource.java:210)
        at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.continueLoading(ChunkSampleStream.java:531)
        at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:78)
        at com.google.android.exoplayer2.source.smoothstreaming.SsMediaPeriod.continueLoading(SsMediaPeriod.java:184)
        at com.google.android.exoplayer2.MediaPeriodHolder.continueLoading(MediaPeriodHolder.java:205)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1905)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1884)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:368)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
2021-04-29 12:41:54.676 12278-12278/de.sky.online D/AndroidRuntime: Shutting down VM
    --------- beginning of crash
2021-04-29 12:41:54.677 12278-12278/de.sky.online E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.sky.online, PID: 12278
    java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter data
        at sky.wrapper.tv.EventEmitter.emitEvent(Unknown Source:7)
        at sky.wrapper.tv.player.exoplayer.PlayerEventListener.onPlayerError(PlayerEventListener.java:69)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$2$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:812)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$06WAXA7vL-SBfQvmAx45uxQjmso.invokeListener(Unknown Source:2)
        at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
        at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
        at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:812)
        at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
        at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
        at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
        at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6740)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2021-04-29 12:41:54.757 12278-12278/de.sky.online I/Process: Sending signal. PID: 12278 SIG: 9
```

**Comment by christosts** [comment]
Can you please take a look at this piece of [documentation on BehindLiveWindowException](https://exoplayer.dev/live-streaming.html#behindlivewindowexception) and let me know if it covers what you see?

The exception should be propagated to the app through the `onPlayerError` callback, and the app can decide what to do next. Are observing something different?
