### ISSUE TITLE
ExoPlaybackException required for desugaring of try-with-resources is not found.

### ISSUE THREAD

**Issue by manwinder123** [google/ExoPlayer#8916]
Attempting to build an android project using Buck and I've added the exoplayer dependencies, exoplayer-core, exoplayer-hls, exoplayer-ui, exoplayer-common, AND exoplayer-extractor.

- ExoPlayer version number : **2.13.3**

I get the following issue building the debug version of the app:

```
Error: Class or interface com.google.android.exoplayer2.ExoPlaybackException required for desugaring of try-with-resources is not found.
com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:72)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
	at com.android.tools.r8.D8.run(D8.java:73)
	at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:361)
	at com.facebook.buck.android.DxStep.execute(DxStep.java:309)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:46)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.executeCommands(CachingBuildRuleBuilder.java:1470)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.runWithDefaultExecutor(CachingBuildRuleBuilder.java:1432)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$2.runWithDefaultBehavior(CachingBuildRuleBuilder.java:866)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:162)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:145)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$2(WeightedListeningExecutorService.java:100)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$0(WeightedListeningExecutorService.java:74)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.android.tools.r8.utils.AbortException: Error: Class or interface com.google.android.exoplayer2.ExoPlaybackException required for desugaring of try-with-resources is not found.
	at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:101)
	at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:72)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:64)
	... 21 more
Command failed with exit code 1.
    When running <d8>.
    When building rule //third_party/com.google.android.exoplayer:exoplayer-core#aar_prebuilt_jar,d8.
```

**Comment by ojw28** [comment]
If this only occurs with Buck, then it feels like it's a Buck issue rather than an ExoPlayer issue. You should report your issue to the Buck maintainers if this is the case. If you can reproduce the same issue using Google provided tools, please provide reproduction steps and we'll take a look.
