### ISSUE TITLE
MediaCodec error

### ISSUE THREAD

**Issue by ddicaro** [google/ExoPlayer#8929]
I have already opened a similar [issue](https://github.com/google/ExoPlayer/issues/6503) where I described the problem #6503

On many mid-range devices using OMX.MTK.VIDEO.DECODER.AVC decoder(or similar ones) when try to play a MPEG-DASH stream on Akamai CDN with DRM we receive this error:

```
com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.AVC, Format(1_0, null, null, video/avc, avc1.640028, 511750, null, [512, 288, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:207)
```
We encounter the same error on many devices of our users (see attachment  [Report-codec_error_with_device.pdf](https://github.com/google/ExoPlayer/files/6460006/Report-codec_error_with_device.pdf)), which we clearly have no chance to test.
We wanted to know if you could test them and / or add them inside the switch of method: `protected boolean codecNeedsSetOutputSurfaceWorkaround(String name)` of class `MediaCodecVideoRenderer.class`, in fact, as mentioned [here](https://github.com/google/ExoPlayer/issues/6503#issuecomment-542183772), it would be possible as long as the conditions are met

Version of ExoPlayer being used

2.11.7

Device(s) and version(s) of Android being used

HUAWEI P30 lite - HWMAR - Android 10 and many others

**Comment by Samrobbo** [comment]
@kim-vde are you okay to look at this? You addressed the same thing when it last arose.

**Comment by kim-vde** [comment]
Could you explain why you think adding the devices to `codecNeedsSetOutputSurfaceWorkaround(String name)` is the solution and how you generated this list of devices?

The error message is quite generic and I am worried that the workaround might not be the correct solution. The cause of the issue could for example be:
* That the format is not supported. Indeed, many formats in the list you provided have AVC `profile_idc` 0x64=100, which is not guaranteed to be supported on all Android devices (see [Android supported media formats](https://developer.android.com/guide/topics/media/media-formats)).
* That the app creates too many decoders for some reason.
