### ISSUE TITLE
ExoPlayerImplInternal: Renderer error: index=1, type=audio, format=Format(program_audio_ddp:dolby_audio, dolby_audio, null, audio/eac3, ec-3, -1, en, [-1, -1, -1.0], [6, 48000]), rendererSupport=NO_UNSUPPORTED_TYPE

### ISSUE THREAD

**Issue by NG-Gaurav** [google/ExoPlayer#8936]
```
2021-05-13 12:21:04.714 11768-12171/com.viewlift.hoichoi E/ExoPlayerImplInternal: Renderer error: index=1, type=audio, format=Format(program_audio_ddp:dolby_audio, dolby_audio, null, audio/eac3, ec-3, -1, en, [-1, -1, -1.0], [6, 48000]), rendererSupport=NO_UNSUPPORTED_TYPE
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: [-49999], Format(program_audio_ddp:dolby_audio, dolby_audio, null, audio/eac3, ec-3, -1, en, [-1, -1, -1.0], [6, 48000])
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:561)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1725)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainAndReinitializeCodec(MediaCodecRenderer.java:1489)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1271)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:556)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:810)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:709)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: [-49999], Format(program_audio_ddp:dolby_audio, dolby_audio, null, audio/eac3, ec-3, -1, en, [-1, -1, -1.0], [6, 48000])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:843)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:559)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1725) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainAndReinitializeCodec(MediaCodecRenderer.java:1489) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1271) 
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:556) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:810) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:709) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

the issue only in android tv working fine on mobile device

**Comment by Samrobbo** [comment]
It looks like there's a problem when trying to initialise a decoder for dolby_audio. 

Can you give us some more information please? In particular, a full bug report (not just a stack trace) when the issue occurs, as well as a link to the media that you are trying to play.

The best way to give us all the information we need is to fill in all the fields in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by NG-Gaurav** [comment]
any. update on it.

**Comment by Samrobbo** [comment]
As I said above, I need a full bug report, as well as reproduction steps.

- Clear reproduction steps including observed and expected behavior
- Output of running "adb bugreport" in the console shortly after encountering the issue

**The best way to give us all the information we need is to fill in all the fields in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).**

If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by Samrobbo** [comment]
I've tried playing the media on the exoplayer demo app on an android mobile device, and it looks like we choose the mp4a audio track because there is no eac3 decoder on the device. 

```
MediaCodecAudioRenderer [
2021-05-19 14:48:00.788 10072-10072/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
2021-05-19 14:48:00.788 10072-10072/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:0, id=program_audio_ddp:dolby_audio, mimeType=audio/eac3, codecs=ec-3, channels=6, sample_rate=48000, language=en, label=dolby_audio, supported=NO_UNSUPPORTED_TYPE
2021-05-19 14:48:00.788 10072-10072/com.google.android.exoplayer2.demo D/EventLogger:     ]
2021-05-19 14:48:00.789 10072-10072/com.google.android.exoplayer2.demo D/EventLogger:     Group:1, adaptive_supported=N/A [
2021-05-19 14:48:00.789 10072-10072/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=program_audio_aac:stereo, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000, language=en, label=stereo, supported=YES
2021-05-19 14:48:00.790 10072-10072/com.google.android.exoplayer2.demo D/EventLogger:     ]
```

Can you try to reproduce with the demo application on the android TV and show what happens in that scenario?

**Comment by ojw28** [comment]
I think application code must be explicitly selecting the EAC3 track, even though it's not supported. If that's the case then this is likely an issue with the application code, rather than with ExoPlayer itself.
