### ISSUE TITLE
IllegalArgumentException maybe thrown when calling setVideoTextureView

### ISSUE THREAD

**Issue by GavinChu** [google/ExoPlayer#8951]
**Issue description**
In some extreme cases, when calling setVideoTextureView, the internal thread of ExoPlayer will call MediaCodec#setOuputSurface, which may throw an IllegalArgumentException. What can be confirmed is that my device supports the setOuputSurface capability.

I tried to analyze this problem. If the internal thread of ExoPlayer is calling MediaCodec#setOuputSurface within 50ms after MediaCodec#start is called, there is a high probability that an exception will be thrown. MediaCodec#start seems to trigger some messages to release the old buffer. In the process of releasing the buffer, calling setOuputSurface may throw an exception.

**Reproduction steps**
1. Play local video.
2. Remove all Audio renderers.
3. StyledPlayerView uses TextureView (TextureView is easier to reproduce the problem)
4. StyledPlayerView delays 30ms to set the surface (let setOutputSurface be executed after the codec is initialized).

Then play video and exit, I reproduced 3 times in 100 steps.

**Searched documentation and issues**
[native_window_set_buffer_count failed: Invalid argument](https://github.com/google/ExoPlayer/issues/6930)
[Getting sometimes an ExoPlayerImplInternal: IllegalArgumentException](https://github.com/google/ExoPlayer/issues/6346)

**A full bug report captured from the device**
```
2021-05-17 19:30:28.074 12535-12535/com.google.android.exoplayer2.demo D/SimpleExoPlayer: setVideoOutputInternal: Surface(name=android.graphics.SurfaceTexture@386968e)/@0x2018eaf
2021-05-17 19:30:28.092 12535-12535/com.google.android.exoplayer2.demo D/EventLogger: videoDecoderInitialized [eventTime=0.06, mediaPos=0.00, window=0, period=0, OMX.qcom.video.decoder.avc]
2021-05-17 19:30:28.104 12535-15577/com.google.android.exoplayer2.demo W/MediaCodecVideoRenderer: setOutputSurface: Surface(name=android.graphics.SurfaceTexture@386968e)/@0x2018eaf
2021-05-17 19:30:28.106 12535-15581/com.google.android.exoplayer2.demo **E/BufferQueueProducer: [SurfaceTexture-0-12535-94](id:30f70000008d,api:3,p:12535,c:12535) setMaxDequeuedBufferCount: requested buffer count 2 is less than minimum 3**
2021-05-17 19:30:28.106 12535-15581/com.google.android.exoplayer2.demo **E/Surface: IGraphicBufferProducer::setBufferCount(2) returned Invalid argument**
2021-05-17 19:30:28.108 12535-15577/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:588)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:254)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:2145)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.setOutputSurface(SynchronousMediaCodecAdapter.java:183)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1265)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:562)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:508)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1505)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1469)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1444)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:510)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:254) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Version of ExoPlayer being used**
2.14.0

**Comment by christosts** [comment]
Hi,

As you may have noticed from your search on past issues, these problems tend to be codec and/or device specific. Are you seeing this problem on a specific device only?

As a first action, if the issue is specific to device, have you tried enabling the codecNeedsSetOutputSurfaceWorkaround?  If you're using ExoPlayer from sources,  you can directly modify MediacodecVideoRenderer. Otherwise, you'd need to use a custom Renderer that extends MediaCodecVideoRenderer and return true in codecNeedsSetOutputSurfaceWorkaround.

**Comment by GavinChu** [comment]
Sorry for the delayed response.

I suspect that this problem may be a bug in the Android platform, and I have reproduced it on many phones.

Enabling codecNeedsSetOutputSurfaceWorkaround means that I need more time to reinitialize the decoder, but most of the time, it can work without enabling codecNeedsSetOutputSurfaceWorkaround. If the internal thread of ExoPlayer is calling MediaCodec#setOuputSurface within 50ms after MediaCodec#start is called, there is a high probability that an exception will be thrown.

**Comment by ahhsfj1991** [comment]
> 

do you have demo code for use custom MediaCodecVideoRenderer?

**Comment by ahhsfj1991** [comment]
> Hi,
> 
> As you may have noticed from your search on past issues, these problems tend to be codec and/or device specific. Are you seeing this problem on a specific device only?
> 
> As a first action, if the issue is specific to device, have you tried enabling the codecNeedsSetOutputSurfaceWorkaround? If you're using ExoPlayer from sources, you can directly modify MediacodecVideoRenderer. Otherwise, you'd need to use a custom Renderer that extends MediaCodecVideoRenderer and return true in codecNeedsSetOutputSurfaceWorkaround.

do you have demo code for use custom MediaCodecVideoRenderer?

**Comment by christosts** [comment]
If you are **not** using any extensions for video decoding, then try this
```java
RenderersFactory renderersFactory = new DefaultRenderersFactory(context){
      @Override
      protected void buildVideoRenderers(Context context, int extensionRendererMode,
          MediaCodecSelector mediaCodecSelector, boolean enableDecoderFallback,
          Handler eventHandler, VideoRendererEventListener eventListener,
          long allowedVideoJoiningTimeMs, ArrayList<Renderer> out) {
        MediaCodecVideoRenderer videoRenderer =
            new MediaCodecVideoRenderer(
                context,
                getCodecAdapterFactory(),
                mediaCodecSelector,
                allowedVideoJoiningTimeMs,
                enableDecoderFallback,
                eventHandler,
                eventListener,
                MAX_DROPPED_VIDEO_FRAME_COUNT_TO_NOTIFY){
              @Override
              protected boolean codecNeedsSetOutputSurfaceWorkaround(String name) {
                return {yourLogic} || super.codecNeedsSetOutputSurfaceWorkaround(name);
              }
            };
        out.add(videoRenderer);
      }
    };
    ExoPlayer exoPlayer = new ExoPlayer.Builder(context, renderersFactory).build();
```
