### ISSUE TITLE
How to download a simple m3u8 file with ts chunks

### ISSUE THREAD

**Issue by darwin-morocho** [google/ExoPlayer#8976]
Hi I'm trying to download a simple m3u8 video from a given URL, I was searching on the official demo but it doesn't have any example about this.

the URL returns a 
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:16
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:13.733333,
q1080_0.ts
#EXTINF:8.333333,
q1080_1.ts
#EXTINF:8.333333,
q1080_2.ts
#EXTINF:15.533333,
q1080_3.ts
#EXT-X-ENDLIST
```

I tried using `DownloadHelper` like this
```kotlin
val downloadHelper: DownloadHelper = DownloadHelper.forMediaItem(
                        activity,
                        MediaItem.fromUri(Uri.parse(url)),
                        DefaultRenderersFactory(activity),
                        DefaultHttpDataSourceFactory())

 downloadHelper.prepare(object : DownloadHelper.Callback {
      override fun onPrepared(helper: DownloadHelper) { }
     override fun onPrepareError(helper: DownloadHelper, e: IOException) { }
 })

val buffer = ByteArray(1204)
val request = downloadHelper.getDownloadRequest(buffer) // <--- CRASH HERE
DownloadService.sendAddDownload(activity, HLSDownloaderService::class.java, request, false)
```

but it doesn't work. I'm getting the next error
```
2021-05-22 18:50:37.816 28929-28929/app.meedu.app E/MethodChannel#app.meedu.app/video-downloader: Failed to handle method call
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:84)
        at com.google.android.exoplayer2.offline.DownloadHelper.assertPreparedWithMedia(DownloadHelper.java:827)
        at com.google.android.exoplayer2.offline.DownloadHelper.getDownloadRequest(DownloadHelper.java:753)
        at app.meedu.app.platform_channels.VideoDownloader.onMethodCall(VideoDownloader.kt:53)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-05-22 18:50:41.570 28929-29125/app.meedu.app E/VideoFrameReleaseHelper: Failed to call Surface.setFrameRate
      java.lang.IllegalStateException: Surface has already been released.
        at android.view.Surface.checkNotReleasedLocked(Surface.java:696)
        at android.view.Surface.setFrameRate(Surface.java:905)
        at com.google.android.exoplayer2.video.VideoFrameReleaseHelper.setSurfaceFrameRateV30(VideoFrameReleaseHelper.java:389)
        at com.google.android.exoplayer2.video.VideoFrameReleaseHelper.clearSurfaceFrameRate(VideoFrameReleaseHelper.java:379)
        at com.google.android.exoplayer2.video.VideoFrameReleaseHelper.onStopped(VideoFrameReleaseHelper.java:232)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onStopped(MediaCodecVideoRenderer.java:471)
        at com.google.android.exoplayer2.BaseRenderer.stop(BaseRenderer.java:165)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.ensureStopped(ExoPlayerImplInternal.java:1599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1608)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1351)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1314)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:494)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by marcbaechinger** [comment]
There is a page about downloading media on our DevGuide: https://exoplayer.dev/downloading-media.html
It explains how to subclass a `DownloadService` and how to add a download and play downloaded content. 

Looking at this doc, adding a download involves building a `DownloadRequest` with something like this

```
DownloadRequest downloadRequest =
    new DownloadRequest.Builder(contentId, contentUri).setData(buffer).build();
```

At the very end is a section about downloading adaptive media like HLS.

Can you check whether this works for you in a similar way? If this is not helpful, can you let me know why you are pursuing another approach to create a `DownloadRequest`?

**Comment by darwin-morocho** [comment]
> https://exoplayer.dev/downloading-media.html

I've followed that page before but it doesn't have one demo about how to use the DownloadHelper class for HLS videos only have a little snippet but that snippet is incomplete.


```
DownloadRequest downloadRequest =
    new DownloadRequest.Builder(contentId, contentUri).setData(buffer).build();
```
The code above works but download the chunks as exo files I want to download the video as a m3u8 file with their ts files to play the video in a flutter video player.

**Comment by marcbaechinger** [comment]
Ah, ok I see. You want to use the download facilities of ExoPlayer to create a spec compliant local version that can be read by arbitrary players supporting HLS.

I'm not sure if using a subclass of `DownloadService` is the right option then. I even think that you probably won't find any out-of-the-box solution with ExoPlayer download components I'm afraid. These are very much focused on caching network requests and transparently delivering either cached data (if available) or upstream data downloaded from the network. The data is internally stored in .exo files like you noticed. 

What you want to do is creating a local manifest that is pointing to local ts files.  Like I said there is no out-of-the-box solution for this available on ExoPlayer side. You can probably use the `HlsPlaylistParser` for parsing the playlist to get the segments and then use  a `DataSource` for downloading. I don't think we can give you much support here for this as this is quite a specific use case which we do not explicitly support besides what's there in by the existing Cache/Download support.

**Comment by marcbaechinger** [comment]
Closing due to inactivity.
