### ISSUE TITLE
ExoPlaybackException. "setOutputSurface" on this devices needs the workaround

### ISSUE THREAD

**Issue by freedom0622** [google/ExoPlayer#8981]
ExoPlaybackException.  
Issue happens on Huawei P40 Pro with android 10.0. Device name **HWELS**. Model name ELS-AN00. Code name passed to codecNeedsSetOutputSurfaceWorkaround is OMX.hisi.video.decoder.avc  

We create a custom Renderer extend **MediaCodecVideoRenderer**, and return true in **codecNeedsSetOutputSurfaceWorkaround**. Then no exception happens.  

I guess quite a few "OMX.hisi.video.decoder.avc" chips have this problem.

Reproduction steps  
We have a SimpleExoPlayer instance in an activity created by "SimpleExoPlayer.Builder(context).build()". Repeatedly enter this activity up to 30 times, the problem occured.

Link to test content  
We tested on real project, don't have test project.  

Version of ExoPlayer being used  
2.12.3  

Device(s) and version(s) of Android being used  
Huawei P40 Pro with android 10.0.  

A full bug report captured from the device  

```
> com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error  
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)  
        at android.os.Handler.dispatchMessage(Handler.java:106)  
        at android.os.Looper.loop(Looper.java:219)  
        at android.os.HandlerThread.run(HandlerThread.java:67)  
     Caused by: java.lang.IllegalArgumentException  
        at android.media.MediaCodec.native_setSurface(Native Method)  
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:2042)  
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1242)  
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:516)  
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:478)  
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1402)  
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1368)  
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1343)  
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)  
        at android.os.Handler.dispatchMessage(Handler.java:106)  
        at android.os.Looper.loop(Looper.java:219)  
        at android.os.HandlerThread.run(HandlerThread.java:67)  
```

**Comment by marcbaechinger** [comment]
Thanks for reporting this! We are looking into this and check whether we want to add the device to the list of devices needing the workaround. The device is quite new and uses API 29 since release. We have the P20 on the list already for API levels 27 and below.

My I ask you as a first step to create a [full bug report](https://developer.android.com/studio/debug/bug-report) from that device and upload it here? This will include all the device information we need for evaluation in more detail.
