### ISSUE TITLE
IllegalStateException caused by android.media.MediaCodec.native_dequeueXXX

### ISSUE THREAD

**Issue by jruesga** [google/ExoPlayer#8990]
We are observing several IllegalStateException caused by `android.media.MediaCodec.native_dequeueOutputBuffer` and `android.media.MediaCodec.native_dequeueInputBuffer` in several different devices/manufacturers (mainly Samsung, LG and Motorola), but they are all present in mostly each devices/manufacturers). We have been observed them in VOD and Live content, as VSF and VPF and with ExoPlayer 2.10.8 and 2.11.7.

The stacktrace looks like

```
com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:717)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:610)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2726)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1040)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:704)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:610) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

Is there advice we can do to mitigate these errors? We have collected bugreports for some of these devices (I've sent them to the Exo mailing list).

Thanks in advance.

**Comment by andrewlewis** [comment]
If you can reproduce some of these exceptions reliably, please share a minimal reproducible sample and then we can share it with the relevant device OEMs so they can figure out what's going on.

I had a look through the provide logcat/bug reports. Unfortunately the error logging is not very helpful but a few things stood out:
- In all cases the codecs string is for H.264/AVC High profile (`avc1.64...`). This may not be supported everywhere based on the Android CDD (here is the [latest version](https://source.android.com/compatibility/android-cdd#5_3_4_h_264)).
- In all cases the video renderer format support is `rendererSupport=NO_UNSUPPORTED_DRM`. Looking at the code, I guess it may just be the case that the player is customizing the media crypto type (not using `FrameworkMediaCrypto`) so this might not be an issue, but I am not certain.
- It looks like there may be use of multiple codecs at the same time, probably for ad playback. Using multiple codecs concurrently may not be supported in some cases and can cause errors:
```
03-03 15:42:22.775 media  3654  1395 I ResourceManagerService: writeResourceInfo (PID : 5969, clientID : 3091056608, secure-codec/video-codec:1, 1280x720 (fps:30) - sw codec : no, encoder : no)
03-03 15:42:22.775 media  3654  1395 I ResourceManagerService: writeResourceInfo (PID : 5969, clientID : 2907079840, non-secure-codec/video-codec:1, 1280x720 (fps:29) - sw codec : no, encoder : no)
```

Here is an example format support log line for reference:
```
2020-10-23 17:58:14.268 19571-21007/com.nexstreaming.app.nexplayersample E/ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(720p-30fps-4830k, null, null, video/avc, avc1.64001f, 4830000, null, [1280, 720, 30.0], [-1, -1]), rendererSupport=NO_UNSUPPORTED_DRM
```

Can you find correlations in your error reporting between specific conditions (like using H.264 high profile or transitioning between ads and content) that cause a high volume of exceptions? If so that may help point to a cause.

**Comment by jruesga** [comment]
Sorry for the delayed response.

Unfortunately, we can only reproduce this error sporadically. We need to spent several hours or even days playing an asset to get into this error and there is no a common pattern of reproduction of the issue.


> In all cases the codecs string is for H.264/AVC High profile (avc1.64...). This may not be supported everywhere based on the Android CDD (here is the latest version).

That could be the case in some devices (maybe the Shield Pro), but we were not able to reproduce it consistently in devices that have this issue. We are able to force the max bitrate and playback successfully in a device that later on it will fail with these kind of issues.


> In all cases the video renderer format support is rendererSupport=NO_UNSUPPORTED_DRM. Looking at the code, I guess it may just be the case that the player is customizing the media crypto type (not using FrameworkMediaCrypto) so this might not be an issue, but I am not certain.

iirc, Ollie said that this `NO_UNSUPPORTED_DRM` status can be displayed after an error in a DRM protected stream
(https://github.com/google/ExoPlayer/issues/7794#issuecomment-679246975). The logs are from 2.11.7, so I was always under the impression that that was the case. We are still migrating to 2.13.3, so we don't have any data to share about this issue yet.


> It looks like there may be use of multiple codecs at the same time, probably for ad playback. Using multiple codecs concurrently may not be supported in some cases and can cause errors:

That could be the case, for ad playaback for live assets when we try CSAI, in which we have a dual player approach (we start loading the ad player while main content is playing). But it is not the case for VOD or live with SSAI, in that case we have a single player and a single timeline.


> Can you find correlations in your error reporting between specific conditions (like using H.264 high profile or transitioning between ads and content) that cause a high volume of exceptions? If so that may help point to a cause.

We were unable to determine this, as I was able to reproduce this error in the middle of a main content, without any other player or ad involved. From the logs, we've observed that just some seconds before the errors, there is a bitrate transition, sometimes from HD to SD or the other way around, so it could be the H.264 profile switching what causes the problem, but it doesn't happen always, as we can transition from bitrates (to even max bitrate) without getting the error though. In addition, if H.264 high profile is not supported, shouldn't Exo's ABR discard that track?
