### ISSUE TITLE
ExoPlayerImplInternal: Renderer error

### ISSUE THREAD

**Issue by youi-support-team** [google/ExoPlayer#8991]
This issue seems to be specific to Android Samsung A10 mobile phones. This occurs on an app that has ExoPlayer integrated but I have found the same crash to occur in the ExoPlayer Demo App whenever I try to play UHD content. Originally found in version 2.11.7 but reproduced in 2.14.0. Whenever the player is supposed to be instantiated it will crash with this message in the logs:

```
E/ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(720p-30fps-3500k, null, null, video/avc, avc1.64001f, 3605193, null, [1280, 720, 29.97], [-1, -1]), rendererSupport=NO_UNSUPPORTED_DRM
com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:723)
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:237)
at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.IllegalStateException
at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1504)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:709)
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
at android.os.Handler.dispatchMessage(Handler.java:103) 
at android.os.Looper.loop(Looper.java:237) 
at android.os.HandlerThread.run(HandlerThread.java:67) 
```

I know that the resolution of UHD content is likely outside the capabilities of this device to render, but I've also seen this issue for 720p content which should be fine. Another noteworthy part is that `E/ACodec: dequeueBuffer failed: NO_MEMORY(-12)`
is printed to the logs just a bit before this. I wonder if the underlying hardware decoder used by ExoPlayer by default has run out of memory. In which case I would believe this to be a limitation on the Android platform level. 

Another issue which I believe to be related but haven't been able to reproduce on the ExoPlayer Demo App is that sometimes video content will only play audio and no video will render. Only a black screen appears. There is nothing noteworthy in the logs regarding this occurrence other than: `E/ACodec: dequeueBuffer failed: NO_MEMORY(-12)` 
Which is spammed throughout the logs during the beginning of the stream.

- ExoPlayer Version 2.11.7, 2.14.0
- Android Version: 10
- Android Device: Android Samsung A10

**Comment by marcbaechinger** [comment]
Can you provide us with a sample uri to the content so we can look into this?

**Comment by youi-support-team** [comment]
It should happen for any kind of content but I can look into getting a uri where this happens.

**Comment by stevemayhew** [comment]
@marcbaechinger  I think you'll find many issues like this with the same signature, however, since the cause for the IllegalStateException is the handler thread died or some other reason the codec is not Executing state down in AV framework, there may be **many** causes.

1. Issue #7520 - @icbaker  was looking at this, they did not specify the device 
2. Issue #4136 - again, not specific device so difficult to diagnose
3. Issue #6189 - On this, they did not reproduce on Pixel, only on Moto G5
4. Issue #8134 - this is the issue we commented on, it is on Samsung, but we have reproduced it on Pixel.

We'll focus on getting as much data as we can on our reproducing this on Pixel, since that should be easy for your team to get devices and logging A/V Framework and platform level code for this device.  Logging framework code would help to see if some case in [MediaCodec Native](http://androidxref.com/9.0.0_r3/xref/frameworks/base/media/jni/android_media_MediaCodec.cpp#794) (e.g. JNI failing to creat a Java object) is causing it.

We sent content to dev.exoplayer@gmail.com your welcome to use, We can focus our input on this bug or create another, your choice.

**Comment by ghost** [comment]
I would think this is reproducible by leaving content streaming for an extended period of time. I usually get a timeout in the Exoplayer Demo App, but if the stream can continue playing for several hours it should crash with this renderer error on this device. I have found this exception occurs on a TCL Android TV as well. It happens regardless of the type of content. Please let me know if there are any updates on this issue.

**Comment by ghost** [comment]
This is reproducible in the Exoplayer Demo App using a Samsung Galaxy A30 after a software update to version A305FDDS6BUD3. I ran an HLS stream for an extended period of time, but seems independent of the type of stream.
