### ISSUE TITLE
HttpDataSource$InvalidResponseCodeException: Response code: 403

### ISSUE THREAD

**Issue by mmk909** [google/ExoPlayer#8999]
```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:230)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:383)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:774)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:587)
        at com.google.android.exoplayer2.upstream.ResolvingDataSource.open(ResolvingDataSource.java:108)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:451)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:425)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:400)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:356)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by marcbaechinger** [comment]
Please refer to other sites on the net to find out what HTTP 403 is: https://en.wikipedia.org/wiki/HTTP_403

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by Michael-Lee-CN** [comment]
After some study, I found it was caused by using out-dated cached content for m3u8 content is Simple Cache, ie the playlist with access control params for each url, in a scenario that if all medias within m3u8 list is not totally cached, then next time will reuse url in the cached m3u8 file, which could be out-dated and cause 403 error, so is there a way to not caching .m3u8 list but still caching other .ts urls for Exoplayer?

**Comment by mmk909** [comment]
solved by customizing source code

**Comment by ivanzhang2** [comment]
> solved by customizing source code

how to customize? 
server side response code or   exo source code ?
