### ISSUE TITLE
H.264/MP2T over HTTP 

### ISSUE THREAD

**Issue by juanpef** [google/ExoPlayer#90]
I have the next code:

        Uri uri = Uri.parse("http://192.166.103.140:8000/udp/239.192.0.49:2121");
		SampleSource sampleSource = new FrameworkSampleSource(mContext, uri, /* headers */ null , RENDERER_COUNT);
		MediaCodecVideoTrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(sampleSource,
     		        MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT, 0, mainHandler,
     		        null, 50); 
		MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource);
    		ExoPlayer exoPlayer = ExoPlayer.Factory.newInstance(RENDERER_COUNT);
    		exoPlayer.prepare(videoRenderer, audioRenderer);
    		exoPlayer.sendMessage(videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, surface);
    		exoPlayer.setPlayWhenReady(true);

It works with a closed file like http://html5demos.com/assets/dizzy.mp4 but it does not work with a live streaming. What is the problem???

**Comment by Schizo** [comment]
This should be an out of the box feature.

**Comment by ojw28** [comment]
- We're working on a new extractor model that should make this easier to support (ETA 1-2 weeks).
- Is anyone able to provide a working test stream to help us validate support?
- Your evaluation of what should and should not be an out of the box feature is dubious. On what basis did you reach your conclusion, other than it's a feature you personally want?

**Comment by Schizo** [comment]
@ojw28  wheni was writing my comment, i asked my selfe the same question. But to answer your question, h264 streaming over http/udp is one of the most used cases. Nearly every surveillance system i came across was using h264 over http. 

For the test-case: 
-) What do you need exactly? Can you not test it with an ffmpeg stream easily sending an elementary H264 Stream?

**Comment by ojw28** [comment]
Ideally just a test URL, that works, without us having to spend any time setting one up ourselves.

**Comment by ojw28** [comment]
One other question - Am I correct in thinking that you shouldn't expect seeking to work for this use case (since there's no index, either in the form of an external manifest or in the media stream itself)?

**Comment by ojw28** [comment]
We pushed a bunch of changes that should make this quite straightforward to do. But we're not going to prioritize the work without someone providing a test stream. If no-one is able to do so, then that really indicates that this feature isn't in significant demand.

**Comment by Schizo** [comment]
ojw28 i am ready to setup a wowza test-streaming for 30days, would this be ok?

**Comment by ojw28** [comment]
Just to check: This really is over HTTP and not RTSP right? If so then yes, if you set something up we'll take a look (no promises, since you never know what you'll find when you start trying to build something!).

**Comment by Schizo** [comment]
@ojw28  would it be easier, when i create a plain UDP connection? But then this would be a point-to-point connection and you need to pass me an ip. Where is the depacketization process in exoplayer happening?

**Comment by ojw28** [comment]
We have a UDP data source already as it happens. We'll push it to GitHub in the next week or so. I'm not sure whether it makes this easier or not. I suspect you really want RTSP, which we're not supporting.

**Comment by Schizo** [comment]
UDP is much more important for me then RTSP right now. Any Chance getting the UDP Data source before friday? I can test it as well before it goes to master and give some feedback.

**Comment by ojw28** [comment]
A UdpDataSource is now in dev.

**Comment by Schizo** [comment]
Thank you for the early package!

Somehow i am getting an Exception "Unexpected Exception loading stream"

What i did:

1) **checked out exoplayer-dev**

2) **In demo > PlayerActivity**

````
contentUri = Uri.parse("192.168.1.5:1234");
contentType = TYPE_MP4;
````
````
case TYPE_MP4:
return new ExtractorRendererBuilder(this, userAgent, contentUri);
````

3) **In ExtractorRenderBuilder**
```
DataSource dataSource1 = new UdpDataSource(bandwidthMeter, 2000);
ExtractorSampleSource sampleSource = new ExtractorSampleSource(uri, dataSource1, allocator,
BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);
```


4) **I am Streaming from ffmpeg :**
ffmpeg -f avfoundation -i "1:0" -r 30 -vf scale=1280:720 -vcodec libx264 -crf 12 -preset ultrafast -tune zerolatency -threads 8 -thread_type slice -f  mpegts udp://192.168.1.5:1234

And i can see the stream it in other players like MxPlayer

**Comment by ojw28** [comment]
- We need more information to be able to debug this. Like the stack trace.
- Why does your code reference MP4 anywhere? I don't think what you're streaming is MP4. What does that ffmpeg command actually cause to be streamed (my guess is MPEG-TS, but I'm unsure)?

**Comment by Schizo** [comment]
1) **LogCat:**

````
07-22 09:13:06.481  14155-14155/? I/ExoPlayerImpl﹕ Init 1.4.1
07-22 09:13:06.485  14155-14155/? D/EventLogger﹕ start [0]
07-22 09:13:06.487  14155-14155/? D/EventLogger﹕ state [0.00, false, P]
07-22 09:13:06.503  14155-14155/? D/EventLogger﹕ state [0.02, true, I]
07-22 09:13:06.545  14155-14155/? D/EventLogger﹕ state [0.06, true, P]
07-22 09:13:06.574      451-476/? I/ActivityManager﹕ Displayed com.google.android.exoplayer.demo/.PlayerActivity: +151ms
07-22 09:13:06.575      816-816/? I/Keyboard.Facilitator﹕ onFinishInput()
07-22 09:13:06.842      153-153/? W/SurfaceFlinger﹕ couldn't log to binary event log: overflow.
07-22 09:13:22.157  14155-14191/? E/LoadTask﹕ Unexpected exception loading stream
    java.lang.IllegalArgumentException
            at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
            at com.google.android.exoplayer.util.ParsableByteArray.setPosition(ParsableByteArray.java:116)
            at com.google.android.exoplayer.util.ParsableByteArray.skipBytes(ParsableByteArray.java:127)
            at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:155)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:722)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
07-22 09:13:22.683      451-558/? E/WifiStateMachine﹕ WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.25 rxSuccessRate=145.49 targetRoamBSSID=any RSSI=-57
07-22 09:13:28.433      451-558/? E/WifiStateMachine﹕ WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.31 rxSuccessRate=183.37 targetRoamBSSID=any RSSI=-58
07-22 09:13:30.734  14155-14191/? E/LoadTask﹕ Unexpected exception loading stream
    java.lang.IllegalArgumentException
            at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
            at com.google.android.exoplayer.util.ParsableByteArray.setPosition(ParsableByteArray.java:116)
            at com.google.android.exoplayer.util.ParsableByteArray.skipBytes(ParsableByteArray.java:127)
            at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:155)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:722)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
07-22 09:13:40.981  14155-14191/? E/LoadTask﹕ Unexpected exception loading stream
    java.lang.IllegalArgumentException
            at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
            at com.google.android.exoplayer.util.ParsableByteArray.setPosition(ParsableByteArray.java:116)
            at com.google.android.exoplayer.util.ParsableByteArray.skipBytes(ParsableByteArray.java:127)
            at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:155)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:722)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

2) I am not really referencing mp4, it was just the case statement from my previous code, the dev code furthermore is not passing any specific extractor like mp4Extrator when calling ExtractorRenderBuilder anymore.

**Comment by algrid** [comment]
I'm trying to play an MPEG2TS stream (I added an entry with my video stream to the Demo app and it's played as DefaultUriDataSource). It starts playing but very often gets stuck with the same error:

```
12-18 19:09:07.820 24333-24412/com.google.android.exoplayer.demo E/LoadTask: Unexpected exception loading stream
                                                                             java.lang.IllegalArgumentException
                                                                                 at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                                                                                 at com.google.android.exoplayer.util.ParsableByteArray.setPosition(ParsableByteArray.java:116)
                                                                                 at com.google.android.exoplayer.util.ParsableByteArray.skipBytes(ParsableByteArray.java:127)
                                                                                 at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:146)
                                                                                 at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:753)
                                                                                 at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                 at java.lang.Thread.run(Thread.java:818)
```

**Comment by ernhelm** [comment]
Try buffering for 2 to 3 sec twice before playing and allow the buffer to
jump way ahead of the device that streams

**Comment by algrid** [comment]
Increasing buffer time didn't help.

Investigating further I can see that it looks like TS packets synchronisation problem. For some reason TsExtractor sometimes gets a broken TS packet (with wrong length != 188) and all the following packets are shifted. So it keeps getting packets that aren't starting with SYNC_BYTE (0x47) and ignore them. Sometimes it can by chance receive a packet that's still broken but starting with 0x47 and this can lead to the exception above.

I'm not sure who's to blame, maybe it's even a server side problem, but anyway I'll try to add a resync procedure that will restore normal flow of packets (skipping only 1 or 2 of them).

**Comment by sreenadhkondru** [comment]
On the server side, if FFMPEG is being used to stream TS packets on UDP, add the following parameters:
-flush_packets 0
<UDPDatasource>?pkt_size=1316

This will ensure that a TS packet is not spread across 2 UDP packets and a UDP packet loss doesn't trigger the TSExtractor to get an incomplete TS packet and go out of sync. (note that 1316 is a multiple of the TS packet size-188)

On the client side the fix by algrid works.

**Comment by lcksk** [comment]
@ojw28 Do you have a demo for mpeg2ts over UDP (test case for UdpDataSource)?

**Comment by ojw28** [comment]
Closing due to staleness. We do not have a demo for mpeg2ts over UDP. Our handling of UDP is very much a "best effort", as opposed to being a primary use case that we support.
