### ISSUE TITLE
Question for AsynchronousBufferQueueing 

### ISSUE THREAD

**Issue by HyowonHwang** [google/ExoPlayer#9006]
Hi

I've recently met a log of codec exception like below. 
Firstly, do you have any estimated reasons for this? 

```
Caused by: com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(5, null, null, video/avc, avc1.4D400C, 292000, null, [144, 240, -1.0], [-1, -1]), format_supported=YES
  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:44)
  at android.os.Handler.dispatchMessage(Handler.java:103)
  at android.os.Looper.loop(Looper.java:237)
  at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc
  at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1)
  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:24)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.g(ExoPlayerImplInternal.java:14)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:24)
  ... 3 more
Caused by: java.lang.IllegalStateException
  at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
  at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2726)
  at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:1)
  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.p(MediaCodecRenderer.java:3)
  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:18)
```

Then I've found that `ExoPlayer` supports features of async queueing,  when using `MediaCodecRenderer` like `experimentalSetAsynchronousBufferQueueingEnabled` or `experimentalSetSynchronizeCodecInteractionsWithQueueingEnabled`

I just think that the features could be helpful to avoid codec exception. 
However, I am not sure that it could  works right and stable because of starting with `experimental`.

Please, let me know if async queueing is helpful on my case and verified with most android devices.

**Comment by andrewlewis** [comment]
> Firstly, do you have any estimated reasons for this?

Unfortunately there generally isn't much diagnostic information in the stack trace for exceptions thrown by `MediaCodec`. If you look at the logcat output just before `MediaCodec` throws or check in the kernel logs you can sometimes see a more descriptive error logged by a lower-level component. In the past when we've seen such errors the explanations included things like: the device running out of resources, the bitstream being invalid and bugs in the decoder's handling of adaptive switches.

> Please, let me know if async queueing is helpful on my case and verified with most android devices.

We've been experimenting with it but I think we'd probably still class it as experimental. @christosts is the expert on asynch queueing and can correct me and/or provide further details.

**Comment by christosts** [comment]
As @andrewlewis mentioned, the provided stack trace is not providing enough information and we'd need more information from the logcat output.

Ii is not straightforward that the error you observe is fixed by operating MediaCodec in asynchronous mode. Can you share more information on this? Is this exception raised always when you play video with synchronous mode and does the asynchronous mode fix it? What kind of content are you playing, on what device and Android version?  

The API is still experimental and under evaluation and we cannot provide more information for a stable at the moment. Please follow #6348 where we will post an update when we have concrete next steps for this API.

**Comment by HyowonHwang** [comment]
@andrewlewis 
> output just before MediaCodec throws or check in the kernel logs you can sometimes see a more descriptive error logged by a lower-level component.

As you mentioned, this exception seems not to happen normally and I logged `EventListener.onPlayerError`, found a lot of logs for this. I will try to get the log you said and share it. 

@christosts 
> Is this exception raised always when you play video with synchronous mode and does the asynchronous mode fix it? What kind of content are you playing, on what device and Android version?

I have been only using  synchronous mode using playing video and not tried the asynchronous mode yet. 
So, all exception are with  synchronous mode. 

## Version of ExoPlayer being used
`2.12.3`

## Device(s) and version(s) of Android being used
I found the exception with below devices and Android 10 and 11 are the most.

SM-N960N 
SM-A315N 
SM-G977N 
SM-N976N 
SM-A515F 
SM-N971N 
SM-N981N 
vivo 190 
SM-G965N 
SM-A715F
SM-A505
Redmi Note 8 Pro
SM-A716S 
CPH1823
SM-G973N
SM-A505F
CPH1909
SM-G970N

> The API is still experimental and under evaluation and we cannot provide more information for a stable at the moment. Please follow #6348 where we will post an update when we have concrete next steps for this API.

Thanks, I keep watching on this issue

**Comment by christosts** [comment]
As this was a question for AsynchronousBufferQueueing, the question was answered and I'closing the issue. If you need further assistance, feel free to re-open the issue or open another issue with different question.

Thanks
