### ISSUE TITLE
RTMP playback error connection lost

### ISSUE THREAD

**Issue by kyrylzotov** [google/ExoPlayer#9009]
There is a problem with rtmp stream from mac camera.
During the stream it says error `-14` that is means connection lost.
But the same code is working with mobile stream.

Library version
2.14.0

 internalError [eventTime=105.48, mediaPos=0.00, window=0, period=0, loadError
      net.butterflytv.rtmp_client.RtmpClient$RtmpIOException: RTMP error: -14
        at net.butterflytv.rtmp_client.RtmpClient.read(RtmpClient.java:267)
        at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.read(RtmpDataSource.java:58)
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:92)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:283)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:75)
        at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagHeader(FlvExtractor.java:236)
        at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:165)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1049)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by kyrylzotov** [comment]
And in VLC player that stream is playable

**Comment by andrewlewis** [comment]
I don't think there's enough information here for this to be actionable for us. ExoPlayer is surfacing an error from within librtmp so you could report it at https://github.com/ant-media/LibRtmp-Client-for-Android (and they will probably need some instructions to reproduce the issue).
