### ISSUE TITLE
com.google.android.exoplayer2.ExoPlaybackException Caused by: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by deprecated-fun** [google/ExoPlayer#9017]
ExoPlayer throws ExoPlaybackException when tries to prepare video for playing
Attached an error log
```
E/VideoEditorFragment$onActivityCreated: com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:358)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:2146)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:873)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:384)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:351)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:861)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:832)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:814)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:332)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

The bug is reproducible consistently.

Steps to reproduce:

Shoot a video on camera inside an app
Give created file to fragment with exoplayer

Works fine on android 10 on Samsung Galaxy A51 and Huawei Y8p

ExoPlayer version number: 2.7.3
Android version: 11
Android device: Samsung Galaxy A31

Also it doesn't work on Xiaomi Redmi Note 8 with android 10:

```
E/ExoPlayerImplInternal: Stop failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2147)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:512)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:439)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:468)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:341)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:150)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:972)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:772)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:735)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
E/VideoEditorFragment$onActivityCreated: com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:358)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1005)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:567)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
E/MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer

E/VideoEditorPresenter$onFirstViewAttach: java.lang.IllegalStateException: mediaMetadataRetriever.g…ST_SYNC
                    ) must not be null
        at VideoEditorRepository$getThumbnails$1.call(VideoEditorRepository.kt:48)
        at VideoEditorRepository$getThumbnails$1.call(VideoEditorRepository.kt:23)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
        at io.reactivex.Single.subscribe(Single.java:3400)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by andrewlewis** [comment]
We need more information to investigate this. Please reproduce the issue with the ExoPlayer demo app then capture a full bug report. If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this. If you need to make any changes to reproduce the issue in the demo app please also provide a minimal patch so we can see what changes are required.

Hopefully the bug report will point to the cause of the `MediaCodec` exception. ExoPlayer doesn't use `MediaMetadataRetriever` but the logging from that component may indicate that the media framework is in a bad state, so it could be related.

**Comment by deprecated-fun** [comment]
I could not reproduce the issue with the Exoplayer demo app. If it helps our project creates file and captures video with Camera View. Then the file is passed to Exoplayer to preview the footage.

**Comment by andrewlewis** [comment]
> I could not reproduce the issue with the Exoplayer demo app. If it helps our project creates file and captures video with Camera View. Then the file is passed to Exoplayer to preview the footage.

Just a guess, but if you are using an output view to show media taken from more than one source (camera preview, ExoPlayer) I think there can be errors due to limitations around reusing surfaces. You could try using an output view that is just for ExoPlayer if this is the case.

If you could share a full bug report taken just after seeing the error that may possibly shed some light on the cause.

**Comment by deprecated-fun** [comment]
https://github.com/google/ExoPlayer/issues/3835 could it be related to this issue?

**Comment by andrewlewis** [comment]
> #3835 could it be related to this issue?

We haven't needed to enable the `setOutputSurface` workaround past API level 28 yet but this issue mentions seeing the problem on Android 10/11 (API 29/30). I think Android 10 included new compatibility tests for calling `setOutputSurface`.

Could you provide a full bug report taken just after reproducing the error, as requested above? Preferably one for each affected device. You can email them to `dev.exoplayer@gmail.com` and please put 'Issue #9017' in the subject line.

See also this suggestion I made above:

> Just a guess, but if you are using an output view to show media taken from more than one source (camera preview, ExoPlayer) I think there can be errors due to limitations around reusing surfaces. You could try using an output view that is just for ExoPlayer if this is the case.

**Comment by deprecated-fun** [comment]
I'm not sure if I'm allowed to share full bug report. But if it helps I updated Exoplayer library version to 2.14.1 and error log for Samsung Galaxy A31 changed to:

```
2021-07-14 17:55:35.801 E/MediaCodecVideoRenderer: Video codec error
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:100)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1842)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:843)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        2021-07-14 17:55:35.802 D/MediaCodecInfo: NoSupport [sizeAndRate.support, 640x480x29.79665756225586] [c2.android.h263.decoder, video/3gpp] [a31, SM-A315F, samsung, 30]
2021-07-14 17:55:35.807 E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/3gpp, null, -1, null, [640, 480, 29.796658], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MTK.VIDEO.DECODER.H263
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1410)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:864)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:100)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1842)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:843)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2021-07-14 17:55:35.811 E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2298)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:160)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:912)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:905)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:761)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:483)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:176)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1609)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1351)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1314)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:571)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by deprecated-fun** [comment]
And for Xiaomi Redmi Note 8 Pro:
```
2021-07-14 18:36:17.838 E/MediaCodecVideoRenderer: Video codec error
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:100)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1842)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:843)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-07-14 18:36:17.839 D/MediaCodecInfo: NoSupport [sizeAndRate.support, 640x480x29.53972816467285] [c2.android.h263.decoder, video/3gpp] [begonia, Redmi Note 8 Pro, Xiaomi, 29]
2021-07-14 18:36:17.840 E/ACodec: [OMX.MTK.VIDEO.DECODER.H263] ERROR(0x80001005)
2021-07-14 18:36:17.840 E/ACodec: signalError(omxError 0x80001005, internalError -2147483648)
2021-07-14 18:36:17.840 E/ACodec: Wrong ownership in EBD: UPSTREAM(2) buffer #8
```

**Comment by andrewlewis** [comment]
The latest set of errors suggest the media exceeds capabilities of the bundled software H.263 decoder:

```
2021-07-14 17:55:35.802 D/MediaCodecInfo: NoSupport [sizeAndRate.support, 640x480x29.79665756225586] [c2.android.h263.decoder, video/3gpp] [a31, SM-A315F, samsung, 30]
```

```
2021-07-14 18:36:17.839 D/MediaCodecInfo: NoSupport [sizeAndRate.support, 640x480x29.53972816467285] [c2.android.h263.decoder, video/3gpp] [begonia, Redmi Note 8 Pro, Xiaomi, 29]
```

Without more information I'm not sure there is an efficient way for us to help here. For this latest set of errors I'd suggest switching to a more modern codec like H.264/AVC. For the previous set of errors you could try enabling the output surface workaround just in case it helps. Otherwise, without more information from bug reports I don't think there is anything we can do based on the provided information. Unfortunately the stack traces are not very informative.
