### ISSUE TITLE
2.13.0 possibly broke SimpleExoPlayer that is not running on the main thread. 

### ISSUE THREAD

**Issue by whoozle** [google/ExoPlayer#9051]
It looks like 2.13.0 introduced a regression, if you're using separate HandlerThread for a player and SurfaceView in your app.
Exoplayer versions earlier than 2.13 were running in production on the millions of different devices without any problem like this.
I tested it on Nexus 5(M4B30Z) and Pixel 4(RQ3A.210605.005). 

I'm building player as follows
```java
        player = new SimpleExoPlayer.Builder(context)
                .setTrackSelector(trackSelector)
                .setLoadControl(loadControl)
                .setLooper(handler.getLooper())
                .build();
```

player is using surface view:
```java
            player.setVideoSurfaceView(surfaceView);
```

and the surface view is  just:

```
surfaceView = findViewById(R.id.contextView);
```

Handler created as
```java
        HandlerThread thread = new HandlerThread(this.toString());
        thread.start();
        handler = new Handler(thread.getLooper());
```

The backtrace is 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pureqml.qmlcore.runtime.android, PID: 13674
    java.lang.IllegalStateException: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
        at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1959)
        at com.google.android.exoplayer2.SimpleExoPlayer.getCurrentWindowIndex(SimpleExoPlayer.java:1654)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:858)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateReadingMediaPeriodEventTime(AnalyticsCollector.java:873)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.onSurfaceSizeChanged(AnalyticsCollector.java:471)
        at com.google.android.exoplayer2.SimpleExoPlayer.maybeNotifySurfaceSizeChanged(SimpleExoPlayer.java:1903)
        at com.google.android.exoplayer2.SimpleExoPlayer.access$3700(SimpleExoPlayer.java:79)
        at com.google.android.exoplayer2.SimpleExoPlayer$ComponentListener.surfaceChanged(SimpleExoPlayer.java:2189)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:594)
        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:606)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

No app frame in the backtrace, and it was working for ages (3-4 years, with regular updates to the latest release), until I upgraded to 2.14.0, and then I bisected it to 2.13.0.

The last version that is working is 2.12.4 and it's working absolutely fine (even though it has thread check too).

Thanks!

**Comment by whoozle** [comment]
Apparently the problem is in that `AnalyticsCollector` calls `getCurrentWindowIndex` from arbitrary thread whichever caused an event

**Comment by icbaker** [comment]
2.13.0 strictly enforces (by default) that `SimpleExoPlayer` is always accessed from the same thread - from the [Release Notes](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md):
> * Core library:
>   * Verify correct thread usage in SimpleExoPlayer by default. Opt-out is still possible until the next major release using `setThrowsWhenUsingWrongThread(false)` (#4463).

`SimpleExoPlayer` has never supported being accessed by multiple threads, it just wasn't strictly enforced in the past. This means that before 2.13.0 you won't see these exceptions but instead you probably see all sorts of different undefined behaviours or crashes.

See https://github.com/google/ExoPlayer/issues/9005 for a discussion on how this single-thread requirement relates to the callbacks from `SurfaceView`. If you'd like to return to the pre-2.13.0 undefined behaviour you can use [`SimpleExoPlayer#setThrowsWhenUsingWrongThread`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#setThrowsWhenUsingWrongThread(boolean)), but it will be removed in a future release.
