### ISSUE TITLE
[bug] getCodecCapabilities

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#9065]
Hello, I'm getting error by Crashlytics, I couldn't reproduce this issue myself so I have only the stacktrace I'm getting from Crashlytics.
From my understanding it's trying to read a video mp4a but fails to do so
```
Fatal Exception: java.lang.UnsupportedOperationException: com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=0, format=Format(1/15, null, null, audio/mp4a-latm, mp4a.40.2, -1, null, [-1, -1, -1.0], [2, 44100]), format_supported=YES
       at com.google.android.exoplayer2.offline.DownloadHelper.runTrackSelection(DownloadHelper.java:886)
       at com.google.android.exoplayer2.offline.DownloadHelper.onMediaPrepared(DownloadHelper.java:791)
       at com.google.android.exoplayer2.offline.DownloadHelper.access$200(DownloadHelper.java:91)
       at com.google.android.exoplayer2.offline.DownloadHelper$MediaPreparer.handleDownloadHelperCallbackMessage(DownloadHelper.java:1056)
       at com.google.android.exoplayer2.offline.DownloadHelper$MediaPreparer.lambda$Db71ShN3QybOcTYlOayKmy_uYGE(DownloadHelper.java:28)
       at com.google.android.exoplayer2.offline.-$$Lambda$DownloadHelper$MediaPreparer$Db71ShN3QybOcTYlOayKmy_uYGE.handleMessage(-.java:28)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
```
Caused by com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=0, format=Format(1/15, null, null, audio/mp4a-latm, mp4a.40.2, -1, null, [-1, -1, -1.0], [2, 44100]), format_supported=YES
       at com.google.android.exoplayer2.ExoPlaybackException.createForRenderer(ExoPlaybackException.java:196)
       at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:369)
       at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:344)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.supportsFormat(MediaCodecRenderer.java:507)
       at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:485)
       at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:355)
       at com.google.android.exoplayer2.offline.DownloadHelper.runTrackSelection(DownloadHelper.java:845)
       at com.google.android.exoplayer2.offline.DownloadHelper.onMediaPrepared(DownloadHelper.java:791)
       at com.google.android.exoplayer2.offline.DownloadHelper.access$200(DownloadHelper.java:91)
       at com.google.android.exoplayer2.offline.DownloadHelper$MediaPreparer.handleDownloadHelperCallbackMessage(DownloadHelper.java:1056)
       at com.google.android.exoplayer2.offline.DownloadHelper$MediaPreparer.lambda$Db71ShN3QybOcTYlOayKmy_uYGE(DownloadHelper.java:28)
       at com.google.android.exoplayer2.offline.-$$Lambda$DownloadHelper$MediaPreparer$Db71ShN3QybOcTYlOayKmy_uYGE.handleMessage(-.java:28)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
```
Caused by com.google.android.exoplayer2.mediacodec.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
       at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:369)
       at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java:171)
       at com.google.android.exoplayer2.mediacodec.-$$Lambda$x39zU57LL5hHh1BDD4qtUQaOOjU.getDecoderInfos(-.java)
       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.getDecoderInfos(MediaCodecAudioRenderer.java:330)
       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.supportsFormat(MediaCodecAudioRenderer.java:294)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.supportsFormat(MediaCodecRenderer.java:505)
       at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:485)
       at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:355)
       at com.google.android.exoplayer2.offline.DownloadHelper.runTrackSelection(DownloadHelper.java:845)
       at com.google.android.exoplayer2.offline.DownloadHelper.onMediaPrepared(DownloadHelper.java:791)
       at com.google.android.exoplayer2.offline.DownloadHelper.access$200(DownloadHelper.java:91)
       at com.google.android.exoplayer2.offline.DownloadHelper$MediaPreparer.handleDownloadHelperCallbackMessage(DownloadHelper.java:1056)
       at com.google.android.exoplayer2.offline.DownloadHelper$MediaPreparer.lambda$Db71ShN3QybOcTYlOayKmy_uYGE(DownloadHelper.java:28)
       at com.google.android.exoplayer2.offline.-$$Lambda$DownloadHelper$MediaPreparer$Db71ShN3QybOcTYlOayKmy_uYGE.handleMessage(-.java:28)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
```
Caused by java.lang.IllegalArgumentException
       at android.media.MediaCodecList.getCodecCapabilities(MediaCodecList.java)
       at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:291)
       at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:303)
       at com.google.android.exoplayer2.mediacodec.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java:171)
       at com.google.android.exoplayer2.mediacodec.-$$Lambda$x39zU57LL5hHh1BDD4qtUQaOOjU.getDecoderInfos(-.java)
       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.getDecoderInfos(MediaCodecAudioRenderer.java:330)
       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.supportsFormat(MediaCodecAudioRenderer.java:294)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.supportsFormat(MediaCodecRenderer.java:505)
       at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:485)
       at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:355)
       at com.google.android.exoplayer2.offline.DownloadHelper.runTrackSelection(DownloadHelper.java:845)
       at com.google.android.exoplayer2.offline.DownloadHelper.onMediaPrepared(DownloadHelper.java:791)
       at com.google.android.exoplayer2.offline.DownloadHelper.access$200(DownloadHelper.java:91)
       at com.google.android.exoplayer2.offline.DownloadHelper$MediaPreparer.handleDownloadHelperCallbackMessage(DownloadHelper.java:1056)
       at com.google.android.exoplayer2.offline.DownloadHelper$MediaPreparer.lambda$Db71ShN3QybOcTYlOayKmy_uYGE(DownloadHelper.java:28)
       at com.google.android.exoplayer2.offline.-$$Lambda$DownloadHelper$MediaPreparer$Db71ShN3QybOcTYlOayKmy_uYGE.handleMessage(-.java:28)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

- ExoPlayer version number: 2.14.0
- Android version: 4.4.2
- Android device: alps M

**Comment by ojw28** [comment]
How many occurrences of this crash are you seeing? If you're seeing relatively low volume then I don't think it's worth spending time on this. It looks like the underlying platform is throwing an `IllegalArgumentException`, probably spuriously, but the device you've specified is running an 8 year old version of Android and seems unlikely to be in circulation in high numbers.

**Comment by yoobi** [comment]
Yes you're right only a few users are affected by it and this bug seems to be only on Android 4. So I think we can discard this bug :)
