### ISSUE TITLE
Receiving DESCRIBE 401 when playing password protected RTSP content

### ISSUE THREAD

**Issue by ishaq1994** [google/ExoPlayer#9070]
I am trying to access `rtsp://admin:admin12345@xx.xx.xx.211/Streaming/Channels/101`

I have created mediasource as shown below

```
 SimpleExoPlayer exoPlayer =new SimpleExoPlayer.Builder(context).build();
        exoPlayer.setMediaSource( new RtspMediaSource.Factory().createMediaSource(MediaItem.fromUri(rtspUri)););
        exoPlayer.prepare();
        exoPlayer.setPlayWhenReady(this.playWhenReady);
```

```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.rtsp.RtspMediaSource$RtspPlaybackException: DESCRIBE 401
        at com.google.android.exoplayer2.source.rtsp.RtspMediaSource$SessionInfoListenerImpl.onSessionTimelineRequestFailed(RtspMediaSource.java:219)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.dispatchRtspError(RtspClient.java:529)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.onRtspMessageReceived(RtspClient.java:366)
        at com.google.android.exoplayer2.source.rtsp.RtspMessageChannel$Receiver.lambda$handleRtspMessage$0$RtspMessageChannel$Receiver(RtspMessageChannel.java:291)
        at com.google.android.exoplayer2.source.rtsp.-$$Lambda$RtspMessageChannel$Receiver$HitD0FATwe-gLFkoSjlAUnzETfA.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: com.google.android.exoplayer2.source.rtsp.RtspMediaSource$RtspPlaybackException: DESCRIBE 401
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.onRtspMessageReceived(RtspClient.java:368)
        at com.google.android.exoplayer2.source.rtsp.RtspMessageChannel$Receiver.lambda$handleRtspMessage$0$RtspMessageChannel$Receiver(RtspMessageChannel.java:291) 
        at com.google.android.exoplayer2.source.rtsp.-$$Lambda$RtspMessageChannel$Receiver$HitD0FATwe-gLFkoSjlAUnzETfA.run(Unknown Source:4) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by ojw28** [comment]
I suspect you need to update to version 2.14.1.

* If the issue still occurs with 2.14.1, please provide all of the information requested in the [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=) (please copy/paste it here rather than opening a new issue), including a new stack trace showing the point at which the failure occurs.
* If the stream plays successfully in 2.14.1, please close this issue.

Thanks!

**Comment by ishaq1994** [comment]
I tried after updating to 2.14.1 and received below exception, Please provide a successful example code of creating mediasource

E/AndroidRuntime: FATAL EXCEPTION: ExoPlayer:Playback
    Process: com.example.rtspplayer, PID: 29313
    java.lang.NullPointerException
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:154)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:426)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$RtspClient$MessageListener(RtspClient.java:420)
        at com.google.android.exoplayer2.source.rtsp.-$$Lambda$RtspClient$MessageListener$dJPB0r-FyeWq7xUwLx0FyxTnUk0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by claincly** [comment]
Please add log to display the lines of the exchanged RTSP messages, thanks!

https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/library/rtsp/src/main/java/com/google/android/exoplayer2/source/rtsp/RtspMessageChannel.java#L226

and 

https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/library/rtsp/src/main/java/com/google/android/exoplayer2/source/rtsp/RtspClient.java#L420

**Comment by ishaq1994** [comment]
How can I over ride this methods  Thanks

**Comment by claincly** [comment]
I don't understand you question, but the simplest way is to add a `Log.e("RTSP", message);`  on the lines I mentioned in the previous comment.

The NPE looks like the RTSP response is missing a CSEQ header, which is illegal.

**Comment by ishaq1994** [comment]
How can I add logs in read only file

**Comment by ishaq1994** [comment]
E/RTSP: OPTIONS rtsp://10.10.10.244/Streaming/Channels/101 RTSP/1.0
    cseq: 0
    user-agent: ExoPlayerLib/2.14.1
E/RTSP: RTSP/1.0 200 OK
    Public: OPTIONS, DESCRIBE, PLAY, PAUSE, SETUP, TEARDOWN, SET_PARAMETER, GET_PARAMETER
    Date:  Sun, Jun 20 2021 15:43:53 GMT
E/AndroidRuntime: FATAL EXCEPTION: ExoPlayer:Playback
    Process: com.example.Nucleon, PID: 17181
    java.lang.NullPointerException
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:154)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:436)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$RtspClient$MessageListener(RtspClient.java:426)
        at com.google.android.exoplayer2.source.rtsp.-$$Lambda$RtspClient$MessageListener$dJPB0r-FyeWq7xUwLx0FyxTnUk0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by ishaq1994** [comment]
Hi please find the log attached below

```
E/RTSP: OPTIONS rtsp://10.10.10.244/Streaming/Channels/101 RTSP/1.0
    cseq: 0
    user-agent: ExoPlayerLib/2.14.1
E/RTSP: RTSP/1.0 200 OK
    Public: OPTIONS, DESCRIBE, PLAY, PAUSE, SETUP, TEARDOWN, SET_PARAMETER, GET_PARAMETER
    Date:  Sun, Jun 20 2021 15:59:58 GMT
E/AndroidRuntime: FATAL EXCEPTION: ExoPlayer:Playback
    Process: com.example.Nucleon, PID: 21421
    java.lang.NullPointerException
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:154)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:438)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$RtspClient$MessageListener(RtspClient.java:428)
        at com.google.android.exoplayer2.source.rtsp.-$$Lambda$RtspClient$MessageListener$dJPB0r-FyeWq7xUwLx0FyxTnUk0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by claincly** [comment]
The RTSP response is missing a CSEQ header, which, quoting from the RTSP spec:


> The CSeq field specifies the sequence number for an RTSP request-response pair. **This field MUST be present in all requests and responses.** For every RTSP request containing the given sequence number, there will be a corresponding response having the same number.  Any retransmitted request must contain the same sequence number as the original (i.e. the sequence number is not incremented for retransmissions of the same request).

Your server is not acting correctly.

**Comment by ishaq1994** [comment]
Hi I am able to play same link in  windows VLC medial player , this is for testing purpose ,
is there any way I can bypass it for the time being ?

**Comment by claincly** [comment]
Yes you should be able to.

Long story short, an RTSP request contains a cseq number, and the response carry the same sequence number, that's how the RTSP client knows which request corresponds to the incoming response. 

You could try move the cSeq definition on `RtspClient:L299` to the otter class, and remove the line `RtspClient:L426` that checks for the cseq.
