### ISSUE TITLE
Sending custom message to exoplayer from widevine proxy

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#908]
Hi,

We would like to send custom message to exoplayer from the widevine proxy. How can I do that. 
This requirement is there to restrict license to the suspended users.

I'm sending like this.
```
self.send403("The user is suspended. Please contact Customer Care")

 def send403(self, text):
    """Send 403 Error Response for suspended users"""
    self.response.status = 403
    self.response.write(self.response.write(text))
```

But in the exoplayer, we are not getting the http response code or message.
```
/ExoPlayerImplInternal( 2100): Internal track renderer error.
E/ExoPlayerImplInternal( 2100): com.google.android.exoplayer.ExoPlaybackException: java.io.EOFException
E/ExoPlayerImplInternal( 2100):     at com.google.android.exoplayer.MediaCodecTrackRenderer.shouldWaitForKeys(MediaCodecTrackRenderer.java:636)
E/ExoPlayerImplInternal( 2100):     at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:587)
E/ExoPlayerImplInternal( 2100):     at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:449)
E/ExoPlayerImplInternal( 2100):     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
E/ExoPlayerImplInternal( 2100):     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
E/ExoPlayerImplInternal( 2100):     at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 2100):     at android.os.Looper.loop(Looper.java:136)
E/ExoPlayerImplInternal( 2100):     at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 2100):     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/ExoPlayerImplInternal( 2100): Caused by: java.io.EOFException
E/ExoPlayerImplInternal( 2100):     at com.android.okhttp.internal.Util.readAsciiLine(Util.java:318)
E/ExoPlayerImplInternal( 2100):     at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
E/ExoPlayerImplInternal( 2100):     at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
E/ExoPlayerImplInternal( 2100):     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
E/ExoPlayerImplInternal( 2100):     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
E/ExoPlayerImplInternal( 2100):     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
E/ExoPlayerImplInternal( 2100):     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:499)
E/ExoPlayerImplInternal( 2100):     at com.port.apps.epg.exoplayer.DemoUtil.executePost(DemoUtil.java:93)
E/ExoPlayerImplInternal( 2100):     at com.port.apps.epg.exoplayer.WidevineTestMediaDrmCallback.executeKeyRequest(WidevineTestMediaDrmCallback.java:109)
E/ExoPlayerImplInternal( 2100):     at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostRequestHandler.handleMessage(StreamingDrmSessionManager.java:392)
E/ExoPlayerImplInternal( 2100):     at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 2100):     at android.os.Looper.loop(Looper.java:136)
E/ExoPlayerImplInternal( 2100):     at android.os.HandlerThread.run(HandlerThread.java:61)
```
How we can achieve this?

Regards,
Randeep

**Comment by ojw28** [comment]
The error suggests your server isn't sending a valid HTTP response. How to implement a Widevine proxy is beyond the scope of this issue tracker. I suggest you ask Widevine how this should be done, or consult with their documentation.
