### ISSUE TITLE
Exoplayer crashes when it stream long time (around 4 hours)

### ISSUE THREAD

**Issue by dangphan** [google/ExoPlayer#9112]
I don't know below error when app streaming long time around 4 hours.
Could you tell me how to prevent crashing app?
Besides, I use VLC is working normally.

```
2021-06-24 16:17:21,155 ERROR [
com.google.android.exoplayer2.extractor.flv.TagPayloadReader$UnsupportedFormatException: Video format not supported: 3
	at com.google.android.exoplayer2.extractor.flv.VideoTagPayloadReader.parseHeader(VideoTagPayloadReader.java:74)
	at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:65)
	at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:270)
	at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:172)
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1048)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by kim-vde** [comment]
The error is thrown because the format of a video sample is not supported (see [VideoTagPayloadReader](https://github.com/google/ExoPlayer/blob/r2.14.1/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/flv/VideoTagPayloadReader.java#L74)). ExoPlayer only supports H.264 for FLV files ([corresponding to video encoding ID 7](https://en.wikipedia.org/wiki/Flash_Video)). The sample provided has video encoding “Screen 1” (corresponding to video encoding ID 3), or the encoding ID is incorrect.

**Comment by dangphan** [comment]
> The error is thrown because the format of a video sample is not supported (see [VideoTagPayloadReader](https://github.com/google/ExoPlayer/blob/r2.14.1/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/flv/VideoTagPayloadReader.java#L74)). ExoPlayer only supports H.264 for FLV files ([corresponding to video encoding ID 7](https://en.wikipedia.org/wiki/Flash_Video)). The sample provided has video encoding “Screen 1” (corresponding to video encoding ID 3), or the encoding ID is incorrect.

Thank you kim-vde
