### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by yangcyzhang** [google/ExoPlayer#9130]
Caused by: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
at java.lang.Thread.nativeCreate(Native Method)
at java.lang.Thread.start(Thread.java:893)
at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1382)
at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:630)
at com.google.android.exoplayer2.upstream.Loader.release(Loader.java:4)
at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.release(ProgressiveMediaPeriod.java:4)
at com.google.android.exoplayer2.source.ProgressiveMediaSource.releasePeriod(ProgressiveMediaSource.java:1)
at com.google.android.exoplayer2.source.MaskingMediaPeriod.releasePeriod(MaskingMediaPeriod.java:2)
at com.google.android.exoplayer2.source.MaskingMediaSource.releasePeriod(MaskingMediaSource.java:1)
at com.google.android.exoplayer2.MediaSourceList.releasePeriod(MediaSourceList.java:3)
at com.google.android.exoplayer2.MediaPeriodHolder.releaseMediaPeriod(MediaPeriodHolder.java:2)
at com.google.android.exoplayer2.MediaPeriodHolder.release(MediaPeriodHolder.java:2)
at com.google.android.exoplayer2.MediaPeriodQueue.clear(MediaPeriodQueue.java:5)
at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:23)
at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:32)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:219)
at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by kim-vde** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by yangcyzhang** [comment]
tanks for you help、Maybe it's an internal problem with my app。I'd better close the problem
