### ISSUE TITLE
How to clear the view and the buffer?

### ISSUE THREAD

**Issue by Clement-Jean** [google/ExoPlayer#9148]
My app is focusing on downloading videos and then playing them with Exoplayer. And obviously Downloading comes together with deleting the file.

So the downloading/playing parts work but then I want to be able to clear the player when the user is deleting the video he/she is playing. So I have:

```
videoView.player?.stop()
videoView.player?.release()
```

However, the videoview still shows the image that it was last playing and I'm also guessing that the buffer is still there because when I delete and redownload the same video just after I cannot play it, it gives me this error:

```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (Mp4Extractor, AdtsExtractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1027)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

(i tried to use all the possible exrtractors)

How can I clear view and buffer in this case and then still being able to play the new downloaded video?

**Comment by marcbaechinger** [comment]
Can you give some more details what you do after calling `release`? Because I'd say that after releasing you have to recreate the player to restart playback with a new stream.

I don't think it has something to do with the buffer because data in the buffer isn't read by the extractor. For my understanding the data in the buffer has been extracted by an extractor already and is then buffered before it is sent to the codec.

Can you give some more details in how you release and then recreate the player in your code?

**Comment by Clement-Jean** [comment]
I was not recreating the player but yesterday I saw that the `release` documentation says something like `don't use the player after calling this`.

So I recreated it and it works. However, I wonder if there is a less "heavy" way of doing this because I have a player with a Playlist (ConcatenatingMediaSource) and I need to reinitialize everything each time this event happens.

What do you think ?

**Comment by marcbaechinger** [comment]
I think it should be enough to just remove the `MediaSource` for the given stream to the download that have been removed. Then you can create a new `MediaSource` and add it to the `ConcatentaingMediaSource` again. When the user then seeks to that item in the playlist (or playback transitions to it automatically), the new source will be prepared.

```
concatenatingMediaSource.removeMediaSource(index);
concatenatingMediaSource.addMediaSource(index, newMediaSource);
```

As an aside, we support playlist with a top level API since a while (2.12). So you could move from the concatenating media source to `player.addMediaSource()`. 

```
player.removeMediaSource(index);
player.addMediaSource(index, newMediaSource);
```
