### ISSUE TITLE
audio getting skipped while playing

### ISSUE THREAD

**Issue by maven-y** [google/ExoPlayer#9186]
### Issue description
I am using stream URLs to play in my app, I have checked it keeps skipped after an interval of 5-10 minutes or so. Please check below error log.

### Reproduction steps
Sample app of exoplayer added media source in json file

### Version Exoplayer
2.7.3
OnePlus 6T
android 10

### Url Streaming
https://studio29.radiolize.com/radio/8120/radio.mp3

### Stream details are below :

<img width="504" alt="Screenshot 2021-07-13 at 9 47 04 AM" src="https://user-images.githubusercontent.com/6801363/125389790-648aaa80-e3bf-11eb-8b4a-75e994cd2fa1.png">
<img width="413" alt="Screenshot 2021-07-13 at 9 46 56 AM" src="https://user-images.githubusercontent.com/6801363/125389807-694f5e80-e3bf-11eb-9ab3-06940a7604cf.png">

```
2021-07-13 10:16:07.090 20264-20264/com.appypie.snappy E/icyHttpDataFactory: RadioStatus : PlaybackStatus_LOADING
2021-07-13 10:16:07.209 20264-20264/com.appypie.snappy E/icyHttpDataFactory: RadioStatus : PlaybackStatus_LOADING
2021-07-13 10:16:07.846 20264-20484/com.appypie.snappy E/icyHttpDataFactory: IcyHeaders{bitRate='48', genre='null', name='JTMR Radio', url='null', isPublic=false}
2021-07-13 10:16:08.098 20264-20484/com.appypie.snappy E/icyHttpDataFactory: IcyMetadata{streamTitle='JTMR Radio - The Family Matters Show', streamUrl='JTMR Radio - The Family Matters Show'}
2021-07-13 10:16:08.293 20264-20264/com.appypie.snappy E/icyHttpDataFactory: RadioStatus : PlaybackStatus_PLAYING
2021-07-13 10:16:04.336 20264-20363/com.appypie.snappy W/FlurryAgent: Flurry session paused for context:com.appypie.snappy.HomeActivity@a2dd71f
2021-07-13 10:16:04.710 20264-20483/com.appypie.snappy W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
    java.io.IOException: Invalid byte order: ffff8950
        at android.media.ExifInterface.readByteOrder(ExifInterface.java:3121)
        at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2437)
        at android.media.ExifInterface.getMimeType(ExifInterface.java:2315)
        at android.media.ExifInterface.loadAttributes(ExifInterface.java:1753)
        at android.media.ExifInterface.<init>(ExifInterface.java:1447)
        at com.bumptech.glide.load.resource.bitmap.ExifInterfaceImageHeaderParser.getOrientation(ExifInterfaceImageHeaderParser.java:40)
        at com.bumptech.glide.load.ImageHeaderParserUtils.getOrientation(ImageHeaderParserUtils.java:91)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:236)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:206)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:162)
        at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:33)
        at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:16)
        at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:72)
        at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:55)
        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
        at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
        at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43)
        at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:515)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:480)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:466)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:418)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:387)
        at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
        at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
        at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:74)
        at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
2021-07-13 10:16:04.722 20264-20371/com.appypie.snappy D/EGL_emulation: eglMakeCurrent: 0xd3938780: ver 3 0 (tinfo 0xbf580150)
2021-07-13 10:16:06.781 20264-20264/com.appypie.snappy W/AudioManager: Use of stream types is deprecated for operations other than volume control
2021-07-13 10:16:06.781 20264-20264/com.appypie.snappy W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2021-07-13 10:16:07.082 20264-20264/com.appypie.snappy I/AppCompactView: received color #FFFFFf
2021-07-13 10:16:07.089 20264-20264/com.appypie.snappy E/RadioStatus: RadioStatus : PlaybackStatus_LOADING
2021-07-13 10:16:07.090 20264-20264/com.appypie.snappy E/icyHttpDataFactory: RadioStatus : PlaybackStatus_LOADING
2021-07-13 10:16:07.205 20264-20264/com.appypie.snappy I/AppCompactView: received color #FFFFFf
2021-07-13 10:16:07.209 20264-20264/com.appypie.snappy E/RadioStatus: RadioStatus : PlaybackStatus_LOADING
2021-07-13 10:16:07.209 20264-20264/com.appypie.snappy E/icyHttpDataFactory: RadioStatus : PlaybackStatus_LOADING
2021-07-13 10:16:07.209 20264-20264/com.appypie.snappy D/AudioManager: dispatching onAudioFocusChange(-1) to android.media.AudioManager@fc25eb3com.appypie.snappy.radioStream.AudioPlayerActivity$26@f0c70
2021-07-13 10:16:07.209 20264-20264/com.appypie.snappy I/System.out: ====  cancel is call
2021-07-13 10:16:07.846 20264-20484/com.appypie.snappy D/IcyHttpDataSource: open: responseHeaders={null=[HTTP/1.1 200 OK], Access-Control-Allow-Headers=[Origin, Accept, X-Requested-With, Content-Type, Icy-MetaData], Access-Control-Allow-Methods=[GET, OPTIONS, HEAD], Access-Control-Allow-Origin=[*], Cache-Control=[no-cache, no-store], Connection=[keep-alive], Content-Type=[audio/aac], Date=[Tue, 13 Jul 2021 04:51:51 GMT], Expires=[Mon, 26 Jul 1997 05:00:00 GMT], ice-audio-info=[channels=2;samplerate=44100;bitrate=48], icy-br=[48], icy-metaint=[16000], icy-name=[JTMR Radio], icy-pub=[0], Referrer-Policy=[no-referrer-when-downgrade], Server=[nginx], Transfer-Encoding=[chunked], X-Android-Received-Millis=[1626151567845], X-Android-Response-Source=[NETWORK 200], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1626151567558], X-Content-Type-Options=[nosniff], X-Robots-Tag=[none], X-XSS-Protection=[1]}
2021-07-13 10:16:07.846 20264-20484/com.appypie.snappy E/icyHttpDataFactory: IcyHeaders{bitRate='48', genre='null', name='JTMR Radio', url='null', isPublic=false}
2021-07-13 10:16:08.098 20264-20484/com.appypie.snappy E/icyHttpDataFactory: IcyMetadata{streamTitle='JTMR Radio - The Family Matters Show', streamUrl='JTMR Radio - The Family Matters Show'}
2021-07-13 10:16:08.156 20264-20484/com.appypie.snappy I/AppCompactView: received color #FFFFFf
2021-07-13 10:16:08.162 20264-20264/com.appypie.snappy I/RadioActivity: Audio updateAlbum()
2021-07-13 10:16:08.162 20264-20264/com.appypie.snappy I/System.out: ===== gg artist : JTMR Radio
2021-07-13 10:16:08.162 20264-20264/com.appypie.snappy I/System.out: ===== gg track : The Family Matters Show
2021-07-13 10:16:08.162 20264-20264/com.appypie.snappy I/System.out: ====== gg iTunesUrl : https://itunes.apple.com/search?term=JTMR Radio-The Family Matters Show&entity=album
2021-07-13 10:16:08.172 20264-20491/com.appypie.snappy I/System.out: Track image: The Family Matters Show - JTMR Radio
2021-07-13 10:16:08.185 20264-20264/com.appypie.snappy E/onTracksChanged: onTracksChanged4
2021-07-13 10:16:08.187 20264-20264/com.appypie.snappy I/RadioActivity: Audio updateAlbum()
2021-07-13 10:16:08.187 20264-20264/com.appypie.snappy I/System.out: ===== gg artist : JTMR Radio
2021-07-13 10:16:08.187 20264-20264/com.appypie.snappy I/System.out: ===== gg track : The Family Matters Show
2021-07-13 10:16:08.187 20264-20264/com.appypie.snappy I/System.out: ====== gg iTunesUrl : https://itunes.apple.com/search?term=JTMR Radio-The Family Matters Show&entity=album
2021-07-13 10:16:08.192 20264-20494/com.appypie.snappy I/OMXClient: IOmx service obtained
2021-07-13 10:16:08.197 20264-20491/com.appypie.snappy I/System.out: MemoryCache.contains: a3829e2311d23aaa98ea7152498b10c7 ? false
2021-07-13 10:16:08.197 20264-20491/com.appypie.snappy I/System.out: open: https://ws.audioscrobbler.com/2.0/
2021-07-13 10:16:08.206 20264-20494/com.appypie.snappy I/ACodec: codec does not support config priority (err -2147483648)
2021-07-13 10:16:08.282 20264-20264/com.appypie.snappy I/AppCompactView: received color #FFFFFf
2021-07-13 10:16:08.285 20264-20482/com.appypie.snappy D/AudioTrack: getTimestamp_l(13): device stall time corrected using current time 52064777745321
2021-07-13 10:16:08.291 20264-20264/com.appypie.snappy E/RadioStatus: RadioStatus : PlaybackStatus_PLAYING
2021-07-13 10:16:08.291 20264-20491/com.appypie.snappy I/System.out: body: method=artist.getInfo&track=The+Family+Matters+Show&artist=JTMR+Radio&api_key=bf7d33438293d53de2022e0d2b52063d
2021-07-13 10:16:08.293 20264-20264/com.appypie.snappy E/icyHttpDataFactory: RadioStatus : PlaybackStatus_PLAYING
2021-07-13 10:16:08.534 20264-20264/com.appypie.snappy I/System.out: ==== gg jsonArray : 0
2021-07-13 10:16:08.535 20264-20264/com.appypie.snappy I/System.out: ==== gg gg imageItuneUrl : 
2021-07-13 10:16:08.535 20264-20264/com.appypie.snappy I/System.out: setImageOnBackground ====  gg albumCover updatesnull
2021-07-13 10:16:08.535 20264-20264/com.appypie.snappy I/System.out:  album updateshttps://d2wuvg8krwnvon.cloudfront.net/media/images/noCover.jpg
2021-07-13 10:16:08.535 20264-20264/com.appypie.snappy I/System.out: manoj k disableAutoalbum.equalsIgnoreCase
2021-07-13 10:16:08.535 20264-20264/com.appypie.snappy I/System.out: albumCover == null || (artist.equals
2021-07-13 10:16:08.535 20264-20264/com.appypie.snappy I/System.out: if (imageUrl.length()>5)
2021-07-13 10:16:08.542 20264-20264/com.appypie.snappy I/System.out: ==== gg albumCover without itune
2021-07-13 10:16:08.543 20264-20264/com.appypie.snappy I/System.out: ==== gg jsonArray : 0
2021-07-13 10:16:08.543 20264-20264/com.appypie.snappy I/System.out: ==== gg gg imageItuneUrl : 
2021-07-13 10:16:08.543 20264-20264/com.appypie.snappy I/System.out: setImageOnBackground ====  gg albumCover updatesnull
2021-07-13 10:16:08.543 20264-20264/com.appypie.snappy I/System.out:  album updateshttps://d2wuvg8krwnvon.cloudfront.net/media/images/noCover.jpg
2021-07-13 10:16:08.543 20264-20264/com.appypie.snappy I/System.out: manoj k disableAutoalbum.equalsIgnoreCase
2021-07-13 10:16:08.543 20264-20264/com.appypie.snappy I/System.out: albumCover == null || (artist.equals
2021-07-13 10:16:08.543 20264-20264/com.appypie.snappy I/System.out: if (imageUrl.length()>5)
2021-07-13 10:16:08.543 20264-20264/com.appypie.snappy I/System.out: ==== gg albumCover without itune
2021-07-13 10:16:08.663 20264-20491/com.appypie.snappy I/System.out: MemoryCache.store: a3829e2311d23aaa98ea7152498b10c7 Expires at: Tue Jul 13 11:16:08 GMT+05:30 2021
2021-07-13 10:16:08.664 20264-20491/com.appypie.snappy I/System.out: MemoryCache.load: a3829e2311d23aaa98ea7152498b10c7
2021-07-13 10:16:08.874 20264-20303/com.appypie.snappy V/FA: Inactivity, disconnecting from the service
2021-07-13 10:16:09.410 20264-20491/com.appypie.snappy I/System.out: No Cover Image Found
2021-07-13 10:16:10.282 20264-20264/com.appypie.snappy W/Glide: Load failed for https://d2wuvg8krwnvon.cloudfront.net/media/images/noCover.jpg with size [-2147483648x-2147483648]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.io.FileNotFoundException(https://d2wuvg8krwnvon.cloudfront.net/media/images/noCover.jpg)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.io.FileNotFoundException(https://d2wuvg8krwnvon.cloudfront.net/media/images/noCover.jpg)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.FileNotFoundException(https://d2wuvg8krwnvon.cloudfront.net/media/images/noCover.jpg)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.FileNotFoundException: https://d2wuvg8krwnvon.cloudfront.net/media/images/noCover.jpg
2021-07-13 10:16:10.283 20264-20264/com.appypie.snappy I/Glide: Root cause (1 of 1)
    java.io.FileNotFoundException: https://d2wuvg8krwnvon.cloudfront.net/media/images/noCover.jpg
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:106)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
2021-07-13 10:16:10.284 20264-20264/com.appypie.snappy W/Glide: Load failed for https://d2wuvg8krwnvon.cloudfront.net/media/images/noCover.jpg with size [-2147483648x-2147483648]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.io.FileNotFoundException(https://d2wuvg8krwnvon.cloudfront.net/media/images/noCover.jpg)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.io.FileNotFoundException(https://d2wuvg8krwnvon.cloudfront.net/media/images/noCover.jpg)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.FileNotFoundException(https://d2wuvg8krwnvon.cloudfront.net/media/images/noCover.jpg)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.FileNotFoundException: https://d2wuvg8krwnvon.cloudfront.net/media/images/noCover.jpg
2021-07-13 10:16:10.285 20264-20264/com.appypie.snappy I/Glide: Root cause (1 of 1)
    java.io.FileNotFoundException: https://d2wuvg8krwnvon.cloudfront.net/media/images/noCover.jpg
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:106)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)

```

### Help

Please tell what is wrong with the media, how can I modify it so that it can be playable.
Do I need to add any extension or upgrade the version of exo ?

Any help would be appriciated

**Comment by Samrobbo** [comment]
I'm getting a 502 error when trying to access that URL, is there an issue on the URL side? 

I would strongly recommend trying to update to the most recent version of ExoPlayer, and see if this resolves your issue. Using the latest release provides you with additional useful features, as well as bug fixes and various other improvements.

**Comment by ojw28** [comment]
As an additional point, it appears you're using `IcyHttpDataSource`, which is not a component that we provide and which may be responsible for the problem you're seeing.

More recent versions of ExoPlayer support ICY metadata directly (this has been the case since 2.10, as per this [blog post](https://medium.com/google-exoplayer/exoplayer-2-10-whats-new-15d344eaa8b9)). Moving to the latest version and removing use of `IcyHttpDataSource` may resolve the problem.
