### ISSUE TITLE
ExoPlayer crashing while trying to release `DefaultDrmSession` (`Assertions.checkState`)

### ISSUE THREAD

**Issue by saurabharora90** [google/ExoPlayer#9193]
A small percentage of our users are facing crashes within Exoplayer 2.13.3

Stacktrace:

```
Fatal Exception: java.lang.IllegalStateException
       at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:86)
       at com.google.android.exoplayer2.drm.DefaultDrmSession.release(DefaultDrmSession.java:307)
       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager$ReferenceCountListenerImpl.lambda$onReferenceCountDecremented$0(DefaultDrmSessionManager.java:795)
       at com.google.android.exoplayer2.drm.-$$Lambda$DefaultDrmSessionManager$ReferenceCountListenerImpl$lohQXhovvcCpLXYZ8GSk9gsNCn8.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

I am trying to understand if there is something we aren't handling properly with the DRM Session Manager? 

This is how we create the session manager:

```
DefaultDrmSessionManager.Builder()
        .setUseDrmSessionsForClearContent(C.TRACK_TYPE_AUDIO, C.TRACK_TYPE_VIDEO)
       //additional configuration omitted for brevity 
        .build(
            HttpMediaDrmCallback(
                licenseUrl,
                dataSourceFactory
            )
        )


DashMediaSource.Factory(dataSourceFactory)
        .setDrmSessionManager(drmSessionManager)
        .createMediaSource(mediaItem)
```

**Comment by icbaker** [comment]
Thanks for the report - I think there's a bug in the way `DefaultDrmSessionManager` releases it's internal 'keep-alive' references when it's released.

Specifically if the manager is released while there's still at least one active 'external' session reference the manager will incorrectly release both references (one of the release calls will be delayed by `sessionKeepaliveMs`, defaults to 5mins). If this races against the external reference being explicitly released (which it should be) then you'll see the stack trace you've included because the session sees 'too many' release calls.

I'll send a fix.

---

One question:

> A small percentage of our users are facing crashes within Exoplayer 2.13.3

Is this causing playback problems or app crashes, or is it just visible in the logs?

**Comment by saurabharora90** [comment]
>Is this causing playback problems or app crashes, or is it just visible in the logs?

Sorry missed the question. Guess it was an edit.

It is causing app crashes.

**Comment by fpitters** [comment]
Probably not related. We are seeing a weird crash after bumping to 2.14.2 (from 2.13.2) with a close stacktrace

```
Fatal Exception: java.lang.IllegalStateException
       at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:84)
       at com.google.android.exoplayer2.drm.DefaultDrmSession.release(DefaultDrmSession.java:308)
       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager$PreacquiredSessionReference.lambda$release$1(DefaultDrmSessionManager.java:1015)
       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager$PreacquiredSessionReference.lambda$release$1$DefaultDrmSessionManager$PreacquiredSessionReference(DefaultDrmSessionManager.java:3)
       at com.google.android.exoplayer2.drm.-$$Lambda$DefaultDrmSessionManager$PreacquiredSessionReference$nYc-XCZkgUmlTVMJKF9VQKrj-NU.run(-.java:3)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```
The incidence is low, few ~5 out of 25K a day and not device specific, happening across all brands. Although Huawei devices have 40% of the share.

Let me know if you have any comment or insight.

**Comment by icbaker** [comment]
@fpitters Can you please file a new issue?
