### ISSUE TITLE
Demo app FLV sample is no longer available

### ISSUE THREAD

**Issue by Wiktorl4z** [google/ExoPlayer#9205]
Basicly wanted to check if newest version of ExoPlayer is still supporting FLV files.

Steps to reproduct:
1. Downloaded ExoPlayer sample app
2. Clicked on Misc 
3. Big Buck Bunny video (FLV) download icon
4. Downloading is starting but file can't be downloaded.

Btw would like to ask if newest ExoPlayer is still supporting FLV?

**Comment by icbaker** [comment]
When I try and play the Big Buck Bunny (FLV) sample in the demo app I see the following stack trace in logcat:

```
2021-07-20 14:19:39.550 3284-3284/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=35.08, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:643)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:621)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: java.net.SocketTimeoutException
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:644)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:203)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:778)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:591)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:86)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1014)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:411)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.net.SocketTimeoutException
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:644) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:203) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:778) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:591) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:86) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1014) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:411) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
    ]
```

It looks like the asset is no longer available at the URL used by the demo app:
https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/demos/main/src/main/assets/media.exolist.json#L577-L578

And confirmed with curl - this just hangs too:
```shell
$ curl "https://vod.leasewebcdn.com/bbb.flv?ri=1024&rs=150&start=0" -o bbb.flv
```

So I don't think it indicates anything about ExoPlayer's support for FLV - just that the asset we link to for the demo app is no longer available. I'll send a change to remove it.

**Comment by Wiktorl4z** [comment]
Yeah I agree, but meanwhile wanted to confirm if ExoPlayer is still supporting FLV. 
Thank you @icbaker
