### ISSUE TITLE
Always throws the exception when setting the Surface that has already been released

### ISSUE THREAD

**Issue by ShawnLin013** [google/ExoPlayer#9244]
```
2021-07-31 23:30:25.130 4113-8278/com.ivuu E/VideoFrameReleaseHelper: Failed to call Surface.setFrameRate
      java.lang.IllegalStateException: Surface has already been released.
        at android.view.Surface.checkNotReleasedLocked(Surface.java:696)
        at android.view.Surface.setFrameRate(Surface.java:905)
        at com.google.android.exoplayer2.video.VideoFrameReleaseHelper.setSurfaceFrameRateV30(VideoFrameReleaseHelper.java:389)
        at com.google.android.exoplayer2.video.VideoFrameReleaseHelper.clearSurfaceFrameRate(VideoFrameReleaseHelper.java:379)
        at com.google.android.exoplayer2.video.VideoFrameReleaseHelper.onSurfaceChanged(VideoFrameReleaseHelper.java:182)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:549)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:507)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1503)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1467)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1442)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:509)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

It would be great if check the `surface.isValid()` before the `surface.setFrameRate(frameRate, compatibility);`
```
@RequiresApi(30)
private static void setSurfaceFrameRateV30(Surface surface, float frameRate) {
  int compatibility =
      frameRate == 0
          ? Surface.FRAME_RATE_COMPATIBILITY_DEFAULT
          : Surface.FRAME_RATE_COMPATIBILITY_FIXED_SOURCE;
  try {
    surface.setFrameRate(frameRate, compatibility);
  } catch (IllegalStateException e) {
    Log.e(TAG, "Failed to call Surface.setFrameRate", e);
  }
}
```

ExoPlayer: 2.13.3
Android: 11

**Comment by ojw28** [comment]
I don't understand the request here. The title says "always throw the exception" whereas the body of the issue says "check `surface.isValid()`".

What is it exactly that you're suggesting? Also, how are you providing the surface to the player? If you're doing this manually and if you're seeing this issue, then that may imply that you're incorrectly leaving the player holding a released surface, which isn't something you should be doing.

**Comment by ShawnLin013** [comment]
Hi @ojw28 
We use a singleton ExoPlayer in RecyclerView and manual release the ViewHolder's Surface when surfaceDestroyed() called. As the following code:
```
surface?.release()
surface = null
sendMessage(C.TRACK_TYPE_VIDEO, Renderer.MSG_SET_SURFACE, null)
```
Since the Surface has already been released. The exception always called when manual release the ViewHolder's Surface.
So my suggestion is that surface.isValid() should be called before the surface.setFrameRate(frameRate, compatibility); called.
As the following code:
```
@RequiresApi(30)
private static void setSurfaceFrameRateV30(Surface surface, float frameRate) {
  if (!surface.isValid()) {
    return
  }
  
  int compatibility =
      frameRate == 0
          ? Surface.FRAME_RATE_COMPATIBILITY_DEFAULT
          : Surface.FRAME_RATE_COMPATIBILITY_FIXED_SOURCE;
  try {
    surface.setFrameRate(frameRate, compatibility);
  } catch (IllegalStateException e) {
    Log.e(TAG, "Failed to call Surface.setFrameRate", e);
  }
}
```

**Comment by ojw28** [comment]
I doubt you need to manually release a `Surface` when `surfaceDestroyed` is called. That said, if you really want to do this for some reason, why don't you swap the order of the calls so that you clear the surface from the player first? You shouldn't ever leave the player with an invalid surface, however temporarily, which is what you appear to be doing here.
