### ISSUE TITLE
Video codec error when seeking file with encrypted audio stream

### ISSUE THREAD

**Issue by guymclean** [google/ExoPlayer#9256]
We are encountering issues when trying to seek a video file, which is reproducible using the sample app. The video file in question has the audio stream encrypted (and the sample app doesn't actually recognise an audio stream). We have a use case that allows users to seek paused video frame by frame and so this is issue is critical for our app. 

To reproduce the issue, use the video file supplied (email across), pause playback and repeatedly tap the 'seek back 5 seconds button'. The stack trace is below. It is worth noting that if we select video tracks 'none' the issue no longer appears.

```
E/MediaCodec: Codec reported err 0x80000000, actionCode 0, while in state 6
D/SurfaceUtils: disconnecting from surface 0x7599ff3ab0, reason disconnectFromSurface
D/CCodecBufferChannel: [c2.qti.avc.decoder#422] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel: [c2.qti.avc.decoder#422] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel: [c2.qti.avc.decoder#422] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel: [c2.qti.avc.decoder#422] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel: [c2.qti.avc.decoder#422] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel: [c2.qti.avc.decoder#422] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel: [c2.qti.avc.decoder#422] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel: [c2.qti.avc.decoder#422] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel: [c2.qti.avc.decoder#422] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel: [c2.qti.avc.decoder#422] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel: [c2.qti.avc.decoder#422] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel: [c2.qti.avc.decoder#422] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel: [c2.qti.avc.decoder#422] MediaCodec discarded an unknown buffer
I/hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
D/BufferPoolAccessor2.0: bufferpool2 0x74f9f10478 : 8(5505024 size) total buffers - 8(5505024 size) used buffers - 0/8 (recycle/alloc) - 8/255 (fetch/transfer)
D/EventLogger: positionDiscontinuity [eventTime=14.20, mediaPos=0.00, window=0, period=0, reason=SEEK, PositionInfo:old [window=0, period=0, pos=0], PositionInfo:new [window=0, period=0, pos=0]]
D/EventLogger: state [eventTime=14.20, mediaPos=0.00, window=0, period=0, BUFFERING]
D/EventLogger: state [eventTime=14.21, mediaPos=0.00, window=0, period=0, READY]
D/EventLogger: positionDiscontinuity [eventTime=14.45, mediaPos=0.00, window=0, period=0, reason=SEEK, PositionInfo:old [window=0, period=0, pos=0], PositionInfo:new [window=0, period=0, pos=0]]
D/EventLogger: state [eventTime=14.45, mediaPos=0.00, window=0, period=0, BUFFERING]
D/EventLogger: state [eventTime=14.46, mediaPos=0.00, window=0, period=0, READY]
E/MediaCodecVideoRenderer: Video codec error
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:93)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1209)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:845)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4033, -1, null, [848, 480, 29.970032], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.qti.avc.decoder
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1410)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:864)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:93)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1209)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:845)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2298)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:160)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:912)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:905)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:761)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:483)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:176)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1609)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1351)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1314)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:571)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
D/EventLogger: videoDisabled [eventTime=14.96, mediaPos=0.00, window=0, period=0]
D/EventLogger: videoDecoderReleased [eventTime=14.96, mediaPos=0.00, window=0, period=0, c2.qti.avc.decoder]
E/EventLogger: playerFailed [eventTime=14.96, mediaPos=0.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4033, -1, null, [848, 480, 29.970032], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.qti.avc.decoder
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1410)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:864)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:93)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1209)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:845)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    ]
```

- ExoPlayer version number: 2.14.2
- Android version 11
- Android device: Google Pixel 3a

The video file causing the issue has been emailed to dev.exoplayer@gmail.com
Thanks

**Comment by andrewlewis** [comment]
Thanks for reporting this. I can reproduce it on Pixel 4a running S beta. It seems that just pausing then seeking back and waiting a few seconds is enough to trigger the error.

**Comment by guymclean** [comment]
Okay thanks for letting me know - at least it's easily reproducible. Please let me know if you are able to fix this issue. Cheers, Guy

________________________________

**Comment by guymclean** [comment]
Many thanks Andrew - Please let me know as soon as you are able to resolve this issue as it is currently a critical bug in our production app.

**Comment by andrewlewis** [comment]
Tracking bug [internal: b/173106189]. I'll plan to update this issue when that is updated.

**Comment by ened** [comment]
@andrewlewis did you find out something, yet?

**Comment by CPDdev** [comment]
Hi @andrewlewis is there any additional information that we could provide to help? Do you have any update on this issue please?

**Comment by andrewlewis** [comment]
Reply from codec framework team: "This happens if the app is queueing in incomplete access unit. MediaCodec requires queuing whole access units per buffer (actually, whole frames) - and then pauses."

I haven't had time to look into why there are incomplete frames being queued for this stream yet.

**Comment by andrewlewis** [comment]
From what I can tell, the last buffer queued to the codec before the exception is thrown is actually complete. I've asked for more information on the internal bug and will update here when we learn more.

**Comment by guymclean** [comment]
@andrewlewis has there been any further progress made on this issue? Thanks

**Comment by vishnuchilakala** [comment]
Any updates on this issue @andrewlewis ?

**Comment by andrewlewis** [comment]
I've asked for an update on the internal issue.

**Comment by vishnuchilakala** [comment]
@andrewlewis Can you please provide any updates? We are getting quite a lot of these errors (with the same stack trace) in production for a while now and any fix / workaround would help us a lot. Thanks!

**Comment by sridhard** [comment]
yes. same issue

**Comment by javierjim** [comment]
@andrewlewis , any update so far? Especially with respect to this to make sure videos are encoded properly?
> Reply from codec framework team: "This happens if the app is queueing in incomplete access unit. MediaCodec requires queuing whole access units per buffer (actually, whole frames) - and then pauses."
>
> I haven't had time to look into why there are incomplete frames being queued for this stream yet.

**Comment by andrewlewis** [comment]
I've asked for an update on the internal bug again.

If you can share instructions for reproducing the bug including the specific device/build you saw this on and a stream we can play in the ExoPlayer demo app, that might help push this along. There is some discussion on the bug about not being able to reproduce the issue on various devices.

**Comment by advap** [comment]
@andrewlewis hi, we are facing a similar issue. is there a fix for that?

**Comment by andrewlewis** [comment]
It looks like the issue was addressed in the codec framework in 2023: https://r.android.com/2587766. I suspect this fix made it into Android 14 (Android U, API 34).

If you see this issue in Android 14/15, please could you file a new bug in the Media3 repository at https://github.com/androidx/media/issues, share the information requested there and we can follow up?
