### ISSUE TITLE
RTSP stream fails with onSessionTimelineRequestFailed

### ISSUE THREAD

**Issue by Cilenco** [google/ExoPlayer#9259]
I'm trying to access the following rtsp stream from my FritzBox

    rtsp://192.168.178.1:554/?avm=1&freq=338&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=0&pids=0,16,17,18,20,100,110,120,121,122,125,130,131,950

It plays fine in VLC but ExoPlayer craches with an `IllegalStateException` (stacktrace below). From [this](https://github.com/google/ExoPlayer/issues/9070#issuecomment-863159561) question I got the idea to log the send and receiving rtsp messages which look like this:
```
send: [OPTIONS rtsp://192.168.178.1:554/?avm=1&freq=314&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=0&pids=0,16,17,18,20,100,101,84,102,103,104,105,106,1176,2070,2171 RTSP/1.0, cseq: 0, user-agent: ExoPlayerLib/2.14.2, , ]
onRtspMessageReceived: [RTSP/1.0 200 OK, Public: OPTIONS, DESCRIBE, SETUP, PLAY, TEARDOWN, CSeq: 0, ]
send: [DESCRIBE rtsp://192.168.178.1:554/?avm=1&freq=314&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=0&pids=0,16,17,18,20,100,101,84,102,103,104,105,106,1176,2070,2171 RTSP/1.0, cseq: 1, user-agent: ExoPlayerLib/2.14.2, , ]
onRtspMessageReceived: [RTSP/1.0 200 OK, Content-Base: rtsp://192.168.178.1:554/?avm=1&freq=314&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=0&pids=0,16,17,18,20,100,101,84,102,103,104,105,106,1176,2070,2171, Content-Length: 210, Content-Type: application/sdp, CSeq: 1, , v=0
    o=- 12 1 IN IP4 192.168.178.1
    s=SatIPServer:1 0,0,4
    t=0 0
    m=video 0 RTP/AVP 33
    c=In IP4 0.0.0.0
    a=control:stream=1
    a=fmtp:33 ver=1.2;src=1;tuner=1,240,1,7,112,,dvbc,,,,6900,34;pids=0,16,17,18,20
    a=sendonly]
```

Below is the stacktrace from the ExoPlayer exception stating that it can't request the sessionTimeline

```
com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.io.IOException: com.google.android.exoplayer2.ParserException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.source.rtsp.RtspMediaPeriod$InternalListener.onSessionTimelineRequestFailed(RtspMediaPeriod.java:572)
        at com.google.android.exoplayer2.source.rtsp.RtspClient.dispatchRtspError(RtspClient.java:262)
        at com.google.android.exoplayer2.source.rtsp.RtspClient.access$500(RtspClient.java:67)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:525)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$RtspClient$MessageListener(RtspClient.java:422)
        at com.google.android.exoplayer2.source.rtsp.-$$Lambda$RtspClient$MessageListener$9u5JvYWAdRxaQT3-zaI614vd2Qw.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: com.google.android.exoplayer2.source.rtsp.RtspMediaSource$RtspPlaybackException: com.google.android.exoplayer2.ParserException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:525) 
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$RtspClient$MessageListener(RtspClient.java:422) 
        at com.google.android.exoplayer2.source.rtsp.-$$Lambda$RtspClient$MessageListener$9u5JvYWAdRxaQT3-zaI614vd2Qw.run(lambda) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: com.google.android.exoplayer2.ParserException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.source.rtsp.SessionDescriptionParser.addMediaDescriptionToSession(SessionDescriptionParser.java:201)
        at com.google.android.exoplayer2.source.rtsp.SessionDescriptionParser.parse(SessionDescriptionParser.java:184)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:477)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$RtspClient$MessageListener(RtspClient.java:422) 
        at com.google.android.exoplayer2.source.rtsp.-$$Lambda$RtspClient$MessageListener$9u5JvYWAdRxaQT3-zaI614vd2Qw.run(lambda) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:84)
        at com.google.android.exoplayer2.source.rtsp.MediaDescription$Builder.build(MediaDescription.java:201)
        at com.google.android.exoplayer2.source.rtsp.SessionDescriptionParser.addMediaDescriptionToSession(SessionDescriptionParser.java:199)
        at com.google.android.exoplayer2.source.rtsp.SessionDescriptionParser.parse(SessionDescriptionParser.java:184) 
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:477) 
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$RtspClient$MessageListener(RtspClient.java:422) 
        at com.google.android.exoplayer2.source.rtsp.-$$Lambda$RtspClient$MessageListener$9u5JvYWAdRxaQT3-zaI614vd2Qw.run(lambda) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
2021-08-05 14:57:24.379 6948-6948/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=0.14, mediaPos=0.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.io.IOException: com.google.android.exoplayer2.ParserException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.source.rtsp.RtspMediaPeriod$InternalListener.onSessionTimelineRequestFailed(RtspMediaPeriod.java:572)
        at com.google.android.exoplayer2.source.rtsp.RtspClient.dispatchRtspError(RtspClient.java:262)
        at com.google.android.exoplayer2.source.rtsp.RtspClient.access$500(RtspClient.java:67)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:525)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$RtspClient$MessageListener(RtspClient.java:422)
        at com.google.android.exoplayer2.source.rtsp.-$$Lambda$RtspClient$MessageListener$9u5JvYWAdRxaQT3-zaI614vd2Qw.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: com.google.android.exoplayer2.source.rtsp.RtspMediaSource$RtspPlaybackException: com.google.android.exoplayer2.ParserException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:525) 
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$RtspClient$MessageListener(RtspClient.java:422) 
        at com.google.android.exoplayer2.source.rtsp.-$$Lambda$RtspClient$MessageListener$9u5JvYWAdRxaQT3-zaI614vd2Qw.run(lambda) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: com.google.android.exoplayer2.ParserException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.source.rtsp.SessionDescriptionParser.addMediaDescriptionToSession(SessionDescriptionParser.java:201)
        at com.google.android.exoplayer2.source.rtsp.SessionDescriptionParser.parse(SessionDescriptionParser.java:184)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:477)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$RtspClient$MessageListener(RtspClient.java:422) 
        at com.google.android.exoplayer2.source.rtsp.-$$Lambda$RtspClient$MessageListener$9u5JvYWAdRxaQT3-zaI614vd2Qw.run(lambda) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:84)
        at com.google.android.exoplayer2.source.rtsp.MediaDescription$Builder.build(MediaDescription.java:201)
        at com.google.android.exoplayer2.source.rtsp.SessionDescriptionParser.addMediaDescriptionToSession(SessionDescriptionParser.java:199)
        at com.google.android.exoplayer2.source.rtsp.SessionDescriptionParser.parse(SessionDescriptionParser.java:184) 
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:477) 
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$RtspClient$MessageListener(RtspClient.java:422) 
        at com.google.android.exoplayer2.source.rtsp.-$$Lambda$RtspClient$MessageListener$9u5JvYWAdRxaQT3-zaI614vd2Qw.run(lambda) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

Any help with this is highly appreciated!

**Comment by claincly** [comment]
The fmtp line

```
    a=fmtp:33 ver=1.2;src=1;tuner=1,240,1,7,112,,dvbc,,,,6900,34;pids=0,16,17,18,20
```

indicates the payload type 33, and it's format MP2T that we don't support at the moment. There is no way to solve this easily I'm afraid. 

That aside, you are welcomed to implement RFC2250 as `RtpMp2tReader` to support it and submit to our codebase. For reference, there's a similar implementation [here](https://github.com/tresvecesseis/ExoPlayer/blob/dev-v2-rtsp/library/rtp/src/main/java/com/google/android/exoplayer2/source/rtp/extractor/RtpMp2tExtractor.java).

**Comment by claincly** [comment]
I'm closing this as we don't have work planned for supporting MPEG2-TS atm, please feel free to open again.
