### ISSUE TITLE
Some error with Drm on Samsung S9+

### ISSUE THREAD

**Issue by Kolyall** [google/ExoPlayer#9261]
The erron occurs if I try to play on Samsung SM-G965F, but on other devices all works fine
```
MediaItem.Builder()
            .setMediaId(trackId)
            .setUri(dashManifestFileUrl)
            .setDrmUuid(C.WIDEVINE_UUID)
            .setDrmMultiSession(true)
            .setMimeType(MimeTypes.APPLICATION_MPD)
            .setDrmLicenseUri(licenseUrl)
                        .build()
```
```
2021-08-05 18:03:12.373 20545-13381 E/C2AllocatorIon: >>>SEC mapUsage Mapper1 1
2021-08-05 18:03:12.373 20545-13381 E/C2AllocatorIon: >>>SEC C2AllocatorIon::mapUsage ion_is_legacy++++++++
2021-08-05 18:03:12.373 20545-13381 E/C2AllocatorIon: >>>SEC mapUsage	0, 1
2021-08-05 18:03:12.382 20545-1159 E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:520)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onProvisionError(DefaultDrmSession.java:239)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager$ProvisioningManagerImpl.onProvisionError(DefaultDrmSessionManager.java:869)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onProvisionResponse(DefaultDrmSession.java:382)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$000(DefaultDrmSession.java:58)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:557)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:194)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeProvisionRequest(HttpMediaDrmCallback.java:119)
               at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:596)
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:383)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:81)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:75)
        at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:170)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:177)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeProvisionRequest(HttpMediaDrmCallback.java:119) 
        at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:596) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by andrewlewis** [comment]
It looks like your license server is returning HTTP status 404. Can you check your license server logs to see if there is diagnostic information there?

**Comment by Kolyall** [comment]
Ok, later will inform you, maybe it is server error

**Comment by Kolyall** [comment]
@andrewlewis Why emulator (Android Studio) calls `MediaDrmCallback#executeKeyRequest`, but real device calls method `MediaDrmCallback#executeProvisionRequest`?

**Comment by andrewlewis** [comment]
> @andrewlewis Why emulator (Android Studio) calls MediaDrmCallback#executeKeyRequest, but real device calls method MediaDrmCallback#executeProvisionRequest?

I'd guess it may already be provisioned but I'm not sure (and I wouldn't be surprised if DRM generally doesn't work on the emulator like it does on a real device). It also seems unrelated to the original issue filed here?

Assigning @icbaker in case he has anything to correct or add.

**Comment by icbaker** [comment]
>>@andrewlewis Why emulator (Android Studio) calls MediaDrmCallback#executeKeyRequest, but real device calls method MediaDrmCallback#executeProvisionRequest?
>
> I'd guess it may already be provisioned but I'm not sure (and I wouldn't be surprised if DRM generally doesn't work on the emulator like it does on a real device). It also seems unrelated to the original issue filed here?

I think a) the emulator only supports widevine L3 and b) L3 doesn't require provisioning. But +1 to Andrew's general assumption that the emulator is probably not a good testing ground for DRM.

If you want to force L3 on a device that claims to support L1 (and so avoid the provisioning call) there's some instructions here: https://github.com/google/ExoPlayer/issues/8108#issuecomment-767618167

@rrfrias may be able to shed some light on the 404 response from the provisioning server.

**Comment by Kolyall** [comment]
@andrewlewis I just override `MediaDrmCallback` by this issue https://github.com/google/ExoPlayer/issues/9216 and wrap license request at `executeProvisionRequest` and at `executeKeyRequest`. That's why  404 error occurs . 
So to fix the original issue filed here, I don't overrider `executeProvisionRequest`, but overrride `executeKeyRequest`
So my `WrappedHttpMediaDrmCallback` looks like:
```
class WrappedLicenseHttpMediaDrmCallback constructor(
     private val httpMediaDrmCallback: HttpMediaDrmCallback,
) : MediaDrmCallback {

    override fun executeProvisionRequest(uuid: UUID, request: ExoMediaDrm.ProvisionRequest): ByteArray {
        return httpMediaDrmCallback.executeProvisionRequest(uuid, request)
    }


    override fun executeKeyRequest(uuid: UUID, request: ExoMediaDrm.KeyRequest): ByteArray {
         val requestType = request.requestType
         val data = request.data
         /// wrap here
        ...
        val newRequest = ExoMediaDrm.KeyRequest(data, licenseServerUrl, requestType)
        return httpMediaDrmCallback.executeKeyRequest(uuid, newRequest)
    }

}
```

So  the issue is resolved. You may close it.
