### ISSUE TITLE
CacheException: attempt to write a readonly database (code 1032)

### ISSUE THREAD

**Issue by arvkmr** [google/ExoPlayer#9289]
The issue is very intermittent and cannot be reproduced reliably however when it does start happening it happens until the session is stopped. The player will fail to download all the following files because of this error. 

- ExoPlayer version number : 2.13.1
- Android version: 7.0

Here's the error that I see in the logs.

```
08-10 11:03:56.728 E/SQLiteLog( 1553): (1032) statement aborts at 7: [DELETE FROM ExoPlayerCacheIndex1b49b1cc9ea4edce WHERE id = ?] 
08-10 11:03:56.741 E/EventLogger( 1553): audioTrackUnderrun [eventTime=68.19, mediaPos=34.88, window=0, period=0, 71552, 372, 664]
08-10 11:03:56.762 E/PQ      (  203): [PQ][PQSession] iterator is empty
08-10 11:03:56.788 E/VDO_LOG (  320): DecodeEx return 1
08-10 11:03:56.796 E/PQ      (  203): [PQ][PQSession] iterator is empty
08-10 11:03:56.829 E/VDO_LOG (  320): DecodeEx return 1
08-10 11:03:56.833 E/PQ      (  203): [PQ][PQSession] iterator is empty
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553): Playback error
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):   com.google.android.exoplayer2.ExoPlaybackException: Source error
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at android.os.Handler.dispatchMessage(Handler.java:106)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at android.os.Looper.loop(Looper.java:203)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at android.os.HandlerThread.run(HandlerThread.java:61)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):   Caused by: com.google.android.exoplayer2.upstream.cache.Cache$CacheException: com.google.android.exoplayer2.database.DatabaseIOException: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at com.google.android.exoplayer2.upstream.cache.SimpleCache.applyContentMetadataMutations(SimpleCache.java:540)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:778)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:579)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1015)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at java.lang.Thread.run(Thread.java:761)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):   Caused by: com.google.android.exoplayer2.database.DatabaseIOException: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at com.google.android.exoplayer2.upstream.cache.CachedContentIndex$DatabaseStorage.storeIncremental(CachedContentIndex.java:897)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at com.google.android.exoplayer2.upstream.cache.CachedContentIndex.store(CachedContentIndex.java:225)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at com.google.android.exoplayer2.upstream.cache.SimpleCache.applyContentMetadataMutations(SimpleCache.java:538)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       ... 8 more
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):   Caused by: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:743)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1530)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at com.google.android.exoplayer2.upstream.cache.CachedContentIndex$DatabaseStorage.deleteRow(CachedContentIndex.java:939)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       at com.google.android.exoplayer2.upstream.cache.CachedContentIndex$DatabaseStorage.storeIncremental(CachedContentIndex.java:886)
08-10 11:03:56.842 E/ExoPlayerImplInternal( 1553):       ... 10 more
```

The way I am managing my cache keys is fairly simple, I just use the url as a key, will probably switch to using a hashcode instead. 
```
val factory = CacheKeyFactory {
    getKey(it.uri.toString())
}

fun getKey(url: String): String {
      var key = url
      if (url.contains("?")) {
          key = url.substring(0, url.indexOf("?"))
      }
      return key
}

// Cache is using a simple cache and default exoDatabaseProvider

 val provider = ExoDatabaseProvider(context)
 simpleCache = SimpleCache(cacheDirectory, leastRecentlyUsedCacheEvictor, provider)
                
```

[logcat.log](https://github.com/google/ExoPlayer/files/6975495/logcat.log)

**Comment by arvkmr** [comment]
@ojw28 Is there any additional information needed?

**Comment by ojw28** [comment]
Is this failing on a specific device or set of devices? It feels like the device probably has a broken SQL implementation, in which case I'm not sure there's a whole lot we can do (I would also expect other applications to also be intermittently failing with similar problems).

**Comment by ojw28** [comment]
Note that ExoPlayer's code is clearly obtaining a writable database at the point where this issue occurs, so I think we're doing the right thing (i.e., we would not expect to see `attempt to write a readonly database`):

https://github.com/google/ExoPlayer/blob/r2.15.0/library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CachedContentIndex.java#L880

If you have your own `DatabaseProvider` implementation, you should double check that it's returning a writable database from `getWritableDatabase`.
