### ISSUE TITLE
AAC SBR Source Error 

### ISSUE THREAD

**Issue by orcunkobal** [google/ExoPlayer#9295]
Hi,

I work on this stream link; http://yayin.zazuradio.com:4850/listen.pls?sid=1

I get an error like;
`
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1024)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)`

I checked the media information on VLC and the file is here: https://github.com/orcunkobal/test/blob/master/product.png

Is this error about the AAC extension? Because I try to other stream URL with the same media information without SBR extension and it works.

Here are the works media information image and stream URL ( just an example without SBR);
https://github.com/orcunkobal/test/blob/master/other.png
https://stream.powerapp.com.tr/powerpop/96

Exo version: 2.12.0
Phone: Samsung Note 10+

**Comment by claincly** [comment]
The first link works fine on my side:

I did curl to get the actual link: http://yayin.zazuradio.com:4850/stream

```
      MediaCodecAudioRenderer [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=0, mimeType=audio/mp4a-latm, bitrate=52000, codecs=mp4a.40.2, channels=2, sample_rate=22050, supported=YES
        ]
        Metadata [
          IcyHeaders: name=".", genre=".", bitrate=52000, metadataInterval=32768
        ]
      ]
```

Can you try with the actual streaming link, rather than the link to get the playlist?

**Comment by icbaker** [comment]
ExoPlayer doesn't support `.pls` files:
* https://github.com/google/ExoPlayer/issues/1947
* https://github.com/google/ExoPlayer/issues/2051

Extracting the underlying stream link as @claincly did above is the recommended approach.

**Comment by orcunkobal** [comment]
http://yayin.zazuradio.com:4850/stream : Is it playing the latest exoplayer ?  @claincly

**Comment by claincly** [comment]
The link's down.
