### ISSUE TITLE
OMX.qti.audio.decoder.flac fails to decode some valid FLAC bitstreams

### ISSUE THREAD

**Issue by Empressia** [google/ExoPlayer#9349]
### Summary

When I play some flac files (flac files are converted from wav by flac ver1.3.2).  
The following log will be output and stopped. (not always)  

```
2021-08-28 17:34:49.715 16168-16510/*********package*name********* I/OMXClient: IOmx service obtained
2021-08-28 17:34:49.718 16168-16376/*********package*name********* W/MediaCodec: MediaCodec::configure bitrate not found for mUid 10356
2021-08-28 17:34:49.719 16168-16510/*********package*name********* I/ACodec: codec does not support config priority (err -2147483648)
2021-08-28 17:34:49.719 16168-16510/*********package*name********* I/ExtendedACodec: no bitwidth, setting default bitwidth as 16 bits
2021-08-28 17:34:49.719 16168-16510/*********package*name********* I/ExtendedACodec: no min blksize, setting default block size as 16
2021-08-28 17:34:49.719 16168-16510/*********package*name********* I/ExtendedACodec: no max blksize, setting default block size as 16
2021-08-28 17:34:49.719 16168-16510/*********package*name********* I/ExtendedACodec: no min frame size, setting default frame size as 0
2021-08-28 17:34:49.719 16168-16510/*********package*name********* I/ExtendedACodec: no max frame size, setting default frame size as 0
2021-08-28 17:34:49.720 16168-16510/*********package*name********* I/ACodec: codec does not support config priority (err -2147483648)
2021-08-28 17:34:49.720 16168-16510/*********package*name********* I/ACodec: codec does not support config operating rate (err -2147483648)
2021-08-28 17:34:49.721 16168-16510/*********package*name********* W/ExtendedACodec: Failed to get extension for extradata parameter
2021-08-28 17:34:49.747 16168-16510/*********package*name********* E/ACodec: Wrong ownership in FBD: DOWNSTREAM(3) buffer #12
2021-08-28 17:34:49.747 16168-16510/*********package*name********* I/ACodec: [OMX.qti.audio.decoder.flac] output port has 4 buffers:
2021-08-28 17:34:49.747 16168-16510/*********package*name********* I/ACodec:   slot  0: #       9 0x0/0x0 COMPONENT(1) dequeued:0
2021-08-28 17:34:49.747 16168-16510/*********package*name********* I/ACodec:   slot  1: #      10 0x0/0x0 DOWNSTREAM(3) dequeued:6
2021-08-28 17:34:49.747 16168-16510/*********package*name********* I/ACodec:   slot  2: #      11 0x0/0x0 DOWNSTREAM(3) dequeued:7
2021-08-28 17:34:49.747 16168-16510/*********package*name********* I/ACodec:   slot  3: #      12 0x0/0x0 DOWNSTREAM(3) dequeued:5
2021-08-28 17:34:49.747 16168-16510/*********package*name********* E/ACodec: signalError(omxError 0x80001001, internalError -2147483646)
2021-08-28 17:34:49.747 16168-16510/*********package*name********* E/MediaCodec: Codec reported err 0x80000002, actionCode 0, while in state 6
2021-08-28 17:34:49.751 16168-16376/*********package*name********* E/MediaCodecAudioRenderer: Audio codec error
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:100)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1842)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:843)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:368)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-08-28 17:34:49.753 16168-16376/*********package*name********* E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/flac, null, -1, null, [-1, -1, -1.0], [2, 48000]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:368)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecDecoderException: Decoder failed: OMX.qti.audio.decoder.flac
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.createDecoderException(MediaCodecRenderer.java:980)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:864)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:368) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:100)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1842)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:843)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:368) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2021-08-28 17:34:49.754 16168-16376/*********package*name********* E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2298)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:160)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:912)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:905)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:761)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onDisabled(MediaCodecAudioRenderer.java:537)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:176)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1609)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1351)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1314)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:571)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:368)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-08-28 17:34:52.757 16168-16510/*********package*name********* I/ACodec: [OMX.qti.audio.decoder.flac] forcing the release of codec
2021-08-28 17:34:52.769 16168-16510/*********package*name********* E/ACodec: OMX.qti.audio.decoder.flac
```

* Why do I often get this error? Or why does this error often not occur?
* How can I avoid stopping?
* Could you give me some tips to solve please?

------------

### Similar problem ?
https://github.com/google/ExoPlayer/issues/8261

You will see a similar error log there. However, this log does not come out every time.  

------------

### Environment
* ExoPlayerLib/2.14.1
* Xperia 10 II (SO-41A)
* Android 11

**Comment by Empressia** [comment]
flac file -> 48,000Hz / 24bit / stereo

**Comment by kim-vde** [comment]
The FLAC decoder seems to be missing some information (for example the min and max frame size) for some reason. This could be caused by the [stream info block](https://xiph.org/flac/format.html#metadata_block_streaminfo) being invalid.

Can you provide an example file that produces the issue? If you're unable to share a test content publicly, please send it to dev.exoplayer@gmail.com using subject #9349. Please also update this issue to indicate you've done this.

**Comment by Empressia** [comment]
All the original music files that cause the problem cannot be provided because they are paid music files.  
It has also not been successful in creating other files to reproduce.  

----

### Additional information:

* After this problem occurs, a quick tap on the play/pause button in PlayerControlView 3-5 times seems to play normally.  

* The problem also occurred with exoplayer 2.15.0.

**Comment by kim-vde** [comment]
I am afraid it’s difficult to help you if we don’t have the content. Here are a few things that I would try if I were you:
- As I said in my previous comment, the audio decoder is complaining about some missing information from the FLAC stream info block so I would try to see if this box is present in the file and if it looks valid. You can for example use command `hexdump -C <file> | less` to inspect the file.
- I would try to play the problematic files on our [demo app](https://github.com/google/ExoPlayer/tree/r2.15.0/demos/main), to make sure the problem doesn’t come from your app.
- You can also try to use our [FLAC extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/flac) to see if it provides more information in the logs or if it solves the problem. This extension uses a software decoder to decode the samples.
- I would try to play the file with `ffplay` and see if you see some errors printed out.

You say that this problem does not occur every time. So, for the same content, sometimes your get the error, and sometimes not, right? And when you get the error, pressing the play button a few times solves it?  This sounds strange to me. Is your content a live stream?

**Comment by Empressia** [comment]
Thank you for the comment.  

I'd like to try from what I can do.  

> I would try to play the file with ffplay and see if you see some errors printed out.  

I try this. It played successfully.  
The following is the log.  
("X" is a character for masks.)  

```
>ffplay -i 01_XXXXXXXXXXXX.flac
（～省略～）
Input #0, flac, from '01_XXXXXXXXXXXX.flac':  0KB sq=    0B f=0/0
  Metadata:
    date            : 2020-XX-XX
    year            : 2020
    genre           : XXXXXXXX;XXXXXXXXXXXX
    organization    : XXXXXXXX
    album_artist    : XXXXXXXXXXXX
    artist          : XXXXXXXXXXXX
    track           : 01
    title           : XXXXXXXX
    album           : XXXXXXXXXX
  Duration: 00:10:28.XX, start: 0.000000, bitrate: 441 kb/s
  Stream #0:0: Audio: flac, 48000 Hz, stereo, s32 (24 bit)
  Stream #0:1: Video: png, rgba(pc), 420x420 [SAR 2835:2835 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)
  Stream #0:2: Video: png, rgba(pc), 420x420 [SAR 2835:2835 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)
  XX.XX A-V:    nan fd=   0 aq=   XXKB vq=    0KB sq=    0B f=0/0
```

> You say that this problem does not occur every time. So, for the same content, sometimes your get the error, and sometimes not, right?

I reset the player items and start to play the flac file, the problem probably occur 100%.  
(I think the fact that I thought it wasn't 100% was because the following cases were mixed during the trial.)

> And when you get the error, pressing the play button a few times solves it?

Yes, buffering starts and playback starts as expected.  
Once buffered, the file doesn't stop... maybe.  

> Is your content a live stream?

My content is a file in SD card (access by content scheme).  
I'm making Media Item as follows.  

```java
// uri -> content://～
MediaItem.fromUri(uri)
```

**Comment by Empressia** [comment]
I erased the cover image and made it one, but the problem did not change.

**Comment by Empressia** [comment]
I checked the first bytes of the file (I checked it using a binary editor.).

```
ADDRESS  00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
00000000 -----------------------------------------------
00000010 66 4C 61 43 00 00 00 22 10 00 10 00 00 00 10 00 
00000020 2A 39 0B B8 03 70 01 CC B0 00 62 4E 73 B4 C4 95 
00000030 77 02 47 80 4C 8D 3D 0B 57 9C 03 00 04 6E 00 00 
00000040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 10 00 
00000050 00 00 00 00 00 07 50 00 00 00 00 00 00 04 92 EF
```

I don't know how to use demo apps and extensions, so it may take some time.

**Comment by Empressia** [comment]
how do i play flac file with content scheme on demo app...?

**Comment by kim-vde** [comment]
You can just add the following sample to [media.exolist.json](https://github.com/google/ExoPlayer/blob/r2.15.0/demos/main/src/main/assets/media.exolist.json):
````
{
  "name": "Title",
  "uri": "/sdcard/file.mp4"
},
````

The issue you are having could also been related to a workaround we have in `MediaCodecUtil.java`:
https://github.com/google/ExoPlayer/blob/02f7aafe67b4893134a31ea55a3ba0f0535df145/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecUtil.java#L583-L590

Could you try to bumping "< 30" to "< 31", to see if the workaround should also be applied to Android 11?

**Comment by Empressia** [comment]
i modify

```java
    if (Util.SDK_INT < 30 && decoderInfos.size() > 1) {
```

to

```java
    if (Util.SDK_INT < 31 && decoderInfos.size() > 1) {
```

and apply to my application.  

Then the problem no longer occurs.  

thank you.

**Comment by kim-vde** [comment]
I have added the fix to ExoPlayer. It should be in the next minor release.
