### ISSUE TITLE
Getting 403 response on downloaded media

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#9372]
- ExoPlayer version number: 1.14.2
- Android version: Mostly Android 8, 9, 10 and 11 
- Android device: 54% of samsung,  10% LGE and more

Hello, im my application user can download the media, I'm using DownloadService from your example to download the media (there are hls file) and then I read it though `DownloadHelper.createMediaSource(downloadRequest, dataSourceFactory)` from time to time I get a non-fatal exception that user can't watch the download and I have the following stacktrace:

```
Non-fatal Exception: com.google.android.exoplayer2.ExoPlaybackException: Source error
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:214)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```
```
aused by com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
       at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:324)
       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:774)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:587)
       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:177)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

Unfortunately I couldn't reproduce this issue.
Perhaps you have an idea of what is wrong and how I could fix this

**Comment by ag2s20150909** [comment]
maybe you should set some http headers

**Comment by yoobi** [comment]
Could you develop a bit ?

**Comment by marcbaechinger** [comment]
You are receiving an HTTP 403 which means that the server refused to authorize the request.

You need to provide the authentication credentials that allows to request the resource. That's the same thing you are doing when playing back directly.

It's unclear what authentication the server expects, but it may be some HTTP request headers that you need to set like suggested above.

It's not much what you can do from the client side I'm afraid. You need to figure out why the server is refusing the authentication.

**Comment by yoobi** [comment]
>You are receiving an HTTP 403 which means that the server refused to authorize the request.

Yes but I don't get which parts needs internet since it is a downloaded media and is supposed to be available offline.

Maybe I have not explained clearly, I'm getting HTTP 403 on a downloaded media, I don't understand why internet is needed to view a media that is already on the phone.

**Comment by marcbaechinger** [comment]
The stack trace is coming out of a `ParsingLoadable.load` method.

I assume this is an HLS stream and the player tries to download a media playlist that is not cached. A common case when this can happen is that when the HLS stream has multiple renditions (for instance resolutions) and the adaptive playback chooses a a different rendition for playback than for download (see [DevGuide](https://exoplayer.dev/downloading-media.html#downloading-and-playing-adaptive-streams) also).

Would that be an explanation of what you are seeing? Can you please check whether you have created the download request and set the `StreamKeys` as described in the dev guide?

**Comment by yoobi** [comment]
Ok so here is my code:

```
fun getDownloadedMediaSource(mediaId: String): MediaSource {
    getDownloadRequest(mediaId)?.let { downloadRequest ->
            Log.e("DownloadRequest", "downloadRequest.streamKeys.toString()"
            return DownloadHelper.createMediaSource(downloadRequest, getDataSourceFactory(downloadRequest.id))
                .also { Log.e("DownloadedMediaSource", "${it.mediaItem.playbackProperties?.streamKeys}") }
        }
}

val trackSelector: DefaultTrackSelector = DefaultTrackSelector(context)

return SimpleExoPlayer.Builder(context)
            .setTrackSelector(trackSelector)
            .setLoadControl(loadControl)
            .build()
            .apply {
                addListener(eventListener)
                playWhenReady = isPlayerPlaying
                setMediaSource(getDownloadedMediaSource(mediaItem.mediaId))
                prepare()
                seekTo(currentWindow, playbackPosition)
            }
```

And the Log I get is `E/DownloadRequest: [0.0.1]` `E/DownloadedMediaSource: [0.0.1]` 
Is there something I'm missing? Could it be because of `setTrackSelector` ?

**Comment by yoobi** [comment]
Any idea? or do you need more info ?

**Comment by marcbaechinger** [comment]
Is this still an issue for you?

As mentioned in the comment above, you need to make sure that you use the same streamKeys when doing plackback that you have used for downloading. If this is the case, the player never does hit the network when playing downloaded content.

From the [DevGuide](https://exoplayer.dev/downloading-media.html#downloading-and-playing-adaptive-streams):


_When building the MediaItem, MediaItem.playbackProperties.streamKeys must be set to match those in the DownloadRequest so that the player only tries to play the subset of tracks that have been downloaded. Using Download.request.toMediaItem and DownloadRequest.toMediaItem to build the MediaItem will take care of this for you. If building a MediaSource to pass directly to the player, it is similarly important to configure the stream keys by calling MediaSourceFactory.setStreamKeys._

Please let me know if you have solved this and whether I can close this issue.

**Comment by yoobi** [comment]
Yes I've been using everything from the DevGuide and from the example of Exoplayer, it is exactly this.
I'm fetching my `DownloadRequest` then I'm creating the `mediaSource` using `DownloadHelper.createMediasource`.

Some of my users are still getting this error but it's a really small portions, so I don't really know, I've been testing it intensively recently and everything works, I don't really get it.

**Comment by marcbaechinger** [comment]
Closing due to inactivity. Please reopen if you think it is required.
