### ISSUE TITLE
Debugging ERROR_CODE_IO_UNSPECIFIED

### ISSUE THREAD

**Issue by BrettyWhite** [google/ExoPlayer#9381]
Hello,

I am using version 2.15.0 and getting an `ERROR_CODE_IO_UNSPECIFIED` from a random mix of my users.

The stacktrace is as follows:
```
com.app.android.sound.AppPlayerHolder$playerListener$1.onPlayerError (AppPlayerHolder.java:129)
com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$12 (ExoPlayerImpl.java:1308)
com.google.android.exoplayer2.ExoPlayerImpl$$InternalSyntheticLambda$0$1d3756c78b6d6b7ece141d7c1e9a6465b69ea5798e59ea3803cb705ea4cacb60$10.invoke$bridge (ExoPlayerImpl.java:6)
com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke (ListenerSet.java:261)
com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0 (ListenerSet.java:170)
com.google.android.exoplayer2.drm.DrmSessionEventListener$EventDispatcher$$InternalSyntheticLambda$1$1185696162911533178e4cb4d14cb678a9bc7a7637d5bf4eea67e2d9d449f6b6$0.run$bridge (DrmSessionEventListener.java:10)
com.google.android.exoplayer2.util.ListenerSet.flushEvents (ListenerSet.java:191)
com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo (ExoPlayerImpl.java:1380)
com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo (ExoPlayerImpl.java:1220)
com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1 (ExoPlayerImpl.java:227)
androidx.constraintlayout.motion.widget.ViewTransition$$InternalSyntheticLambda$0$c6479121047b1f8bc12f1f2e0ede63895f3663eff4e9e9fcac2cd5b22c16fea3$0.run$bridge (ViewTransition.java:218)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:6705)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:911) 
```

Some context: I am rotating through 2 instances of `SimpleExoPlayer` in an attempt to make a short sound loop longer. Not sure if that has anything to do with this error. 

The media source is loaded  as follows:

```kotlin
    private fun createMediaSource(): MediaSource? {
        simpleCache = Application.simpleCache
        if (simpleCache != null) {
            if (cacheDataSourceFactory == null) {
                cacheDataSourceFactory =
                    CacheDataSource.Factory()
                        .setCache(simpleCache!!)
                        .setCacheKeyFactory(CacheKeyFactory.DEFAULT)
            }
        }
        val mediaItem = MediaItem.fromUri(sourceUri)
        return cacheDataSourceFactory?.let {
            if (progressiveMediaSource == null) {
                val defaultExtractorsFactory = DefaultExtractorsFactory().setConstantBitrateSeekingEnabled(true)
                progressiveMediaSource = ProgressiveMediaSource.Factory(it, defaultExtractorsFactory)
            }
            progressiveMediaSource?.createMediaSource(mediaItem)
        }
    }
   ```
   
   The players are instantiated like this:
   
   ```kotlin
private fun initPlayer() {
        mCurrentPlayer = mContext?.let { SimpleExoPlayer.Builder(it).build() }
        mCurrentPlayer?.playWhenReady = true
        mCurrentPlayer?.repeatMode = Player.REPEAT_MODE_ALL
        val mediaSource = createMediaSource()
        if (mediaSource != null){
            mCurrentPlayer?.setMediaSource(mediaSource)
        } else {
            // fall back on grabbing from the internet and log error
            mCurrentPlayer?.setMediaItem(MediaItem.fromUri(sourceUri))
        }
        mCurrentPlayer?.addListener(playerListener)
        mCurrentPlayer?.setWakeMode(C.WAKE_MODE_NETWORK)
        mCurrentPlayer?.volume = sound.volume.toFloat()
        mCurrentPlayer?.prepare()
}
```

The `PlaybackException` message is always `null`. There are no DRM protections on the audio being played. I was wondering if anyone with experience in this could either help debug, or provide more context around the error. 

Thanks!

**Comment by kim-vde** [comment]
Can you provide a [bug report]((https://developer.android.com/studio/debug/bug-report)) to see if there is more info in the logs? If you're unable to share bug reports publicly, please send them to dev.exoplayer@gmail.com using subject #9381. Please also update this issue to indicate you've done this.

Ideally you should also provide us with clear reproduction steps. Otherwise it is difficult to debug the issue.

**Comment by BrettyWhite** [comment]
Thanks for responding @kim-vde. I am in the process of trying to collect better logs for this. We had never seen this issue when testing internally, and it's popping up randomly across a small sample of testers in a closed beta. I recently released a small update to collect more logs when this happens and will update this/you as soon as they start rolling in.

As a side note, The only time I ever saw this error in development was when I intentionally set a bad URL for a remote audio file. However I'm quite certain the URLs the users are getting are correct - though I will be able to tell for sure soon. Thanks!

**Comment by BrettyWhite** [comment]
Upon further review it seems to be an issue with the caching:

```
Non-fatal Exception: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: timeout
       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:358)
       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
       at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
       at com.google.android.exoplayer2.upstream.cache.CacheWriter.readBlockToCache(CacheWriter.java:172)
       at com.google.android.exoplayer2.upstream.cache.CacheWriter.cache(CacheWriter.java:134)
       at com.app.android.sound.appPlayerHolder.cacheAudio(appPlayerHolder.java:356)
       at com.app.android.sound.appPlayerHolder.access$cacheAudio(appPlayerHolder.java:50)
       at com.app.android.sound.appPlayerHolder$preCacheAudio$1.invokeSuspend(appPlayerHolder.java:347)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

```
Caused by java.net.SocketTimeoutException: timeout
       at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
       at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
       at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
       at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
       at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
       at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
       at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
       at com.google.firebase.perf.network.InstrURLConnectionBase.getResponseCode(InstrURLConnectionBase.java:185)
       at com.google.firebase.perf.network.InstrHttpsURLConnection.getResponseCode(InstrHttpsURLConnection.java:99)
       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:354)
       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
       at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
       at com.google.android.exoplayer2.upstream.cache.CacheWriter.readBlockToCache(CacheWriter.java:172)
       at com.google.android.exoplayer2.upstream.cache.CacheWriter.cache(CacheWriter.java:134)
       at com.app.android.sound.appPlayerHolder.cacheAudio(appPlayerHolder.java:356)
       at com.app.android.sound.appPlayerHolder.access$cacheAudio(appPlayerHolder.java:50)
       at com.app.android.sound.appPlayerHolder$preCacheAudio$1.invokeSuspend(appPlayerHolder.java:347)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

```
Caused by java.net.SocketException: socket is closed
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:551)
       at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
       at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
       at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
       at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
       at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
       at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
       at com.google.firebase.perf.network.InstrURLConnectionBase.getResponseCode(InstrURLConnectionBase.java:185)
       at com.google.firebase.perf.network.InstrHttpsURLConnection.getResponseCode(InstrHttpsURLConnection.java:99)
       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:354)
       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
       at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
       at com.google.android.exoplayer2.upstream.cache.CacheWriter.readBlockToCache(CacheWriter.java:172)
       at com.google.android.exoplayer2.upstream.cache.CacheWriter.cache(CacheWriter.java:134)
       at com.app.android.sound.appPlayerHolder.cacheAudio(appPlayerHolder.java:356)
       at com.app.android.sound.appPlayerHolder.access$cacheAudio(appPlayerHolder.java:50)
       at com.app.android.sound.appPlayerHolder$preCacheAudio$1.invokeSuspend(appPlayerHolder.java:347)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

**Comment by BrettyWhite** [comment]
Additional context:

I'm trying to pre-cache before instantiating `SimpleExoPlayer` by doing this:

```kotlin
private fun preCacheAudio(audioUrl: String?) {
        if (!audioUrl.isNullOrBlank()) {
            val audioUri = Uri.parse(audioUrl)
            val dataSpec = DataSpec(audioUri)
            val event = DownloadEvent(0)
            var previousPercent = 0
            eventBus.post(event)
            val progressListener =
                CacheWriter.ProgressListener { requestLength, bytesCached, _ ->
                    val downloadPercentage: Int = (bytesCached * 100.0 / requestLength).toInt()
                    if (downloadPercentage != previousPercent && SystemClock.elapsedRealtime() - lastEventTime > debounceTime) {
                        lastEventTime = SystemClock.elapsedRealtime()
                        val complete = DownloadEvent(downloadPercentage)
                        eventBus.post(complete)
                        previousPercent = downloadPercentage
                    }
                }

            launch(Dispatchers.IO) {
                Application.dataSource?.let {
                    cacheAudio(dataSpec, it, progressListener)
                }
            }
        }
    }

    private suspend fun cacheAudio(dataSpec: DataSpec, dataSource: CacheDataSource, progressListener: CacheWriter.ProgressListener) {
        val writer = CacheWriter(dataSource, dataSpec, null, progressListener)
        writer.runCatching {
            this.cache()
        }.onSuccess {
            withContext(Dispatchers.Main){
                initPlayer()
            }
        }.onFailure { cacheError ->
            Timber.e("CACHE Failure: $cacheError")
            cacheError.printStackTrace()
        }.recover {
            withContext(Dispatchers.Main) {
                initPlayer()
            }
        }
    }
```

And then when i create the `SimpleExoPlayer` Instance, i create my media source like this:

```kotlin
    private fun createMediaSource(): MediaSource? {
        simpleCache = Application.simpleCache
        if (simpleCache != null) {
            if (cacheDataSourceFactory == null) {
                cacheDataSourceFactory =
                    CacheDataSource.Factory()
                        .setCache(simpleCache!!)
                        .setCacheKeyFactory(CacheKeyFactory.DEFAULT)
            }
        }
        val mediaItem = MediaItem.fromUri(sourceUri)
        return cacheDataSourceFactory?.let {
            if (progressiveMediaSource == null) {
                val defaultExtractorsFactory = DefaultExtractorsFactory().setConstantBitrateSeekingEnabled(true)
                progressiveMediaSource = ProgressiveMediaSource.Factory(it, defaultExtractorsFactory)
            }
            progressiveMediaSource?.createMediaSource(mediaItem)
        }
    }
```

Edit: Additional Info

It seems the users this happens to have slower internet. It happens across Android versions

**Comment by kim-vde** [comment]
The stack traces suggest that there is a network timeout when trying to get the response code from the server. The error is thrown by the underlying network stack (in this case, OkHttp).

Given this, the issue is probably with the network connection or the server (and therefore not with ExoPlayer). You should try to figure out why the server is slow. You can also try to increase the timeout, but it would be a workaround instead of a proper fix.

More information about the network stack in ExoPlayer can be found [here](https://exoplayer.dev/network-stacks.html).

**Comment by BrettyWhite** [comment]
Thanks @kim-vde. After reviewing that link I will take a look at Cronet and talk with our CDN about QUIC to see if that improves anything at all. Seeing as this does not look to be an ExoPlayer issue I will close it. Thank you again for your help.

**Comment by AquilesCanta** [comment]
I took a quick look at `DefaultHttpDataSource` and I don't see how a java.net.SocketTimeoutException in `DefaulHttpDataSource::open->HttpURLConnection::getResponseCode` can throw a `HttpDataSourceException` with error code IO_UNSPECIFIED. I am assuming that the relevant block of code is the catch that calls `HttpDataSourceException.createForIOException` [here](https://github.com/google/ExoPlayer/blob/02f7aafe67b4893134a31ea55a3ba0f0535df145/library/common/src/main/java/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.java#L358). Can you clarify this?

**Comment by BrettyWhite** [comment]
@AquilesCanta is your question directed towards my implementation, or to someone else? Just trying to clarify

**Comment by AquilesCanta** [comment]
It's directed towards you. ExoPlayer shouldn't use ERROR_CODE_IO_UNSPECIFIED for a SocketTimeoutException, so that's a bug. However, after checking the implementation, I don't see how that's possible. I was hoping you could clarify for me how this is happening. Perhaps I'm misinterpreting the stacktrace, or you depend on ExoPlayer via code and introduced changes to DefaultHttpDataSource, etc.

**Comment by BrettyWhite** [comment]
@AquilesCanta I think its due to the flow. 

Basically what I had was:

1. Sound player is initialized
    1a. if sound is `CacheDataSource` cache, then start the player
    1b. if not, then download the sound first, continue.
2. Cache the audio file. This is done here:

```kotlin
    private suspend fun cacheAudio(dataSpec: DataSpec, dataSource: CacheDataSource, progressListener: CacheWriter.ProgressListener) {
        val writer = CacheWriter(dataSource, dataSpec, null, progressListener)
        writer.runCatching {
            this.cache()
        }.onSuccess {
            Timber.i("CACHE SUCCESS")
            withContext(Dispatchers.Main){
                initPlayer()
            }
        }.onFailure { cacheError ->
            Timber.e("CACHE Failure: $cacheError")
            cacheError.printStackTrace()
        }.recover {
            withContext(Dispatchers.Main) {
                initPlayer()
            }
        }
    }
```

At this point if for some reason this step fails, I believe it was then hitting the `recover` block which tried to init the player anyway.

3. It then hits the `createMediaSource` function:

```kotlin
    private fun createMediaSource(): MediaSource? {
        simpleCache = Application.simpleCache
        if (simpleCache != null) {
            if (cacheDataSourceFactory == null) {
                cacheDataSourceFactory =
                    CacheDataSource.Factory()
                        .setCache(simpleCache!!)
                        .setCacheKeyFactory(CacheKeyFactory.DEFAULT)
            }
        }
        val mediaItem = MediaItem.fromUri(sourceUri)
        return cacheDataSourceFactory?.let {
            if (progressiveMediaSource == null) {
                val defaultExtractorsFactory = DefaultExtractorsFactory().setConstantBitrateSeekingEnabled(true)
                progressiveMediaSource = ProgressiveMediaSource.Factory(it, defaultExtractorsFactory)
            }
            progressiveMediaSource?.createMediaSource(mediaItem)
        }
    }
```

I believe that this is where the `ERROR_CODE_IO_UNSPECIFIED` is happening. Not a direct consequence of the SocketTimeout, but as an indirect consequence

**Comment by AquilesCanta** [comment]
It's not clear to me there's something actionable for us here. I was not able to find either in ExoPlayer code or in the user's description the source of the IO_UNSPECIFIED error code. If you have more precise indication on where the origin of the `ERROR_CODE_IO_UNSPECIFIED` is, please comment below and I'll reopen the issue.
