### ISSUE TITLE
Video can't playback without exception

### ISSUE THREAD

**Issue by VeiZhang** [google/ExoPlayer#9388]
When reporting a bug:
-------------------------
**Video can't playback without error exception, and no picture but sometimes audio can work or not.**

```
com.google.android.exoplayer2.demo I/OpenGLRenderer: Initialized EGL, version 1.4
com.google.android.exoplayer2.demo D/OpenGLRenderer: Swap behavior 1
com.google.android.exoplayer2.demo W/InputMethodManager: Ignoring onBind: cur seq=143, given seq=142
com.google.android.exoplayer2.demo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
com.google.android.exoplayer2.demo W/LibraryLoader: Failed to load [flacJNI]
com.google.android.exoplayer2.demo I/DefaultRenderersFactory: Loaded LibvpxVideoRenderer.
com.google.android.exoplayer2.demo I/DefaultRenderersFactory: Loaded Libgav1VideoRenderer.
com.google.android.exoplayer2.demo I/DefaultRenderersFactory: Loaded LibopusAudioRenderer.
com.google.android.exoplayer2.demo I/DefaultRenderersFactory: Loaded LibflacAudioRenderer.
com.google.android.exoplayer2.demo I/DefaultRenderersFactory: Loaded FfmpegAudioRenderer.
com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init 8af614e [ExoPlayerLib/2.14.0] [p212_1G, Xsarius Q1, Amlogic, 25]
com.google.android.exoplayer2.demo D/EventLogger: playWhenReady [eventTime=0.00, mediaPos=0.00, window=0, true, USER_REQUEST]
com.google.android.exoplayer2.demo D/EventLogger: timeline [eventTime=0.04, mediaPos=0.00, window=0, periodCount=17, windowCount=17, reason=PLAYLIST_CHANGED
com.google.android.exoplayer2.demo D/EventLogger:   period [?]
com.google.android.exoplayer2.demo D/EventLogger:   period [?]
com.google.android.exoplayer2.demo D/EventLogger:   period [?]
com.google.android.exoplayer2.demo D/EventLogger:   ...
com.google.android.exoplayer2.demo D/EventLogger:   window [?, seekable=false, dynamic=true]
com.google.android.exoplayer2.demo D/EventLogger:   window [?, seekable=false, dynamic=true]
com.google.android.exoplayer2.demo D/EventLogger:   window [?, seekable=false, dynamic=true]
com.google.android.exoplayer2.demo D/EventLogger:   ...
com.google.android.exoplayer2.demo D/EventLogger: ]
com.google.android.exoplayer2.demo D/EventLogger: mediaItem [eventTime=0.04, mediaPos=0.00, window=0, reason=PLAYLIST_CHANGED]
com.google.android.exoplayer2.demo D/EventLogger: state [eventTime=0.06, mediaPos=0.00, window=0, BUFFERING]
com.google.android.exoplayer2.demo I/art: Do partial code cache collection, code=28KB, data=29KB
com.google.android.exoplayer2.demo I/art: After code cache collection, code=28KB, data=29KB
com.google.android.exoplayer2.demo I/art: Increasing code cache capacity to 128KB
com.google.android.exoplayer2.demo D/EventLogger: surfaceSize [eventTime=0.19, mediaPos=0.00, window=0, 1280, 720]
com.google.android.exoplayer2.demo D/EventLogger: loading [eventTime=0.21, mediaPos=0.00, window=0, period=0, true]
com.google.android.exoplayer2.demo D/EventLogger: timeline [eventTime=0.22, mediaPos=0.00, window=0, period=0, periodCount=17, windowCount=17, reason=SOURCE_UPDATE
com.google.android.exoplayer2.demo D/EventLogger:   period [?]
com.google.android.exoplayer2.demo D/EventLogger:   period [?]
com.google.android.exoplayer2.demo D/EventLogger:   period [?]
com.google.android.exoplayer2.demo D/EventLogger:   ...
com.google.android.exoplayer2.demo D/EventLogger:   window [?, seekable=false, dynamic=false]
com.google.android.exoplayer2.demo D/EventLogger:   window [?, seekable=false, dynamic=true]
com.google.android.exoplayer2.demo D/EventLogger:   window [?, seekable=false, dynamic=true]
com.google.android.exoplayer2.demo D/EventLogger:   ...
com.google.android.exoplayer2.demo D/EventLogger: ]
com.google.android.exoplayer2.demo D/EventLogger: timeline [eventTime=0.35, mediaPos=0.00, window=0, period=0, periodCount=17, windowCount=17, reason=SOURCE_UPDATE
com.google.android.exoplayer2.demo D/EventLogger:   period [?]
com.google.android.exoplayer2.demo D/EventLogger:   period [?]
com.google.android.exoplayer2.demo D/EventLogger:   period [?]
com.google.android.exoplayer2.demo D/EventLogger:   ...
com.google.android.exoplayer2.demo D/EventLogger:   window [?, seekable=false, dynamic=false]
com.google.android.exoplayer2.demo D/EventLogger:   window [?, seekable=false, dynamic=true]
com.google.android.exoplayer2.demo D/EventLogger:   window [?, seekable=false, dynamic=true]
com.google.android.exoplayer2.demo D/EventLogger:   ...
com.google.android.exoplayer2.demo D/EventLogger: ]
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile/level 1/32 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile/level 0/0 for video/mpeg2
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile/level 0/2 for video/mpeg2
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 2 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 2 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 2 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 2 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 3 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 3 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 3 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 3 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 5 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 5 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 5 for video/mpeg2
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 5 for video/mpeg2
com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/vc1
com.google.android.exoplayer2.demo W/Utils: could not parse long range '1-'
com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/wvc1
com.google.android.exoplayer2.demo W/Utils: could not parse long range '1-'
com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/wmv3
com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/x-ms-wmv
com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/mjpeg
com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/aac-adif
com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/aac-latm
com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/adts
com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/wma
com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/wmapro
com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/truehd
com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/ffmpeg
com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/ac3
com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/eac3
com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/dtshd
com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/mpeg-L2
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized level 16 for video/x-vnd.on2.vp8
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized level 32 for video/x-vnd.on2.vp8
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized level 64 for video/x-vnd.on2.vp8
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized level 128 for video/x-vnd.on2.vp8
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized level 256 for video/x-vnd.on2.vp8
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized level 512 for video/x-vnd.on2.vp8
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized level 1024 for video/x-vnd.on2.vp8
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized level 2048 for video/x-vnd.on2.vp8
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized level 4096 for video/x-vnd.on2.vp8
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized level 8192 for video/x-vnd.on2.vp8
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized level 16384 for video/x-vnd.on2.vp8
com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized level 32768 for video/x-vnd.on2.vp8
com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/x-vnd.on2.vp6
com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/x-vnd.on2.vp6a
com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/x-vnd.on2.vp6f
com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/rm10
com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/rm20
com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/rm40
com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/wmv2
com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/wmv1
com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
com.google.android.exoplayer2.demo W/LibraryLoader: Failed to load [vpx, vpxV2JNI]
com.google.android.exoplayer2.demo W/LibraryLoader: Failed to load [opusV2JNI]
com.google.android.exoplayer2.demo W/LibraryLoader: Failed to load [ffmpegJNI]
com.google.android.exoplayer2.demo D/EventLogger: videoEnabled [eventTime=0.73, mediaPos=0.00, window=0, period=0]
com.google.android.exoplayer2.demo D/EventLogger: audioEnabled [eventTime=0.74, mediaPos=0.00, window=0, period=0]
com.google.android.exoplayer2.demo D/EventLogger: tracks [eventTime=0.74, mediaPos=0.00, window=0, period=0
com.google.android.exoplayer2.demo D/EventLogger:   MediaCodecVideoRenderer [
com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=1/256, mimeType=video/avc, codecs=avc1.4D401F, res=1280x720, supported=YES
com.google.android.exoplayer2.demo D/EventLogger:     ]
com.google.android.exoplayer2.demo D/EventLogger:   ]
com.google.android.exoplayer2.demo D/EventLogger:   LibvpxVideoRenderer []
com.google.android.exoplayer2.demo D/EventLogger:   Libgav1VideoRenderer []
com.google.android.exoplayer2.demo D/EventLogger:   MediaCodecAudioRenderer [
com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=1/257, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000, language=nl, supported=YES
com.google.android.exoplayer2.demo D/EventLogger:     ]
com.google.android.exoplayer2.demo D/EventLogger:   ]
com.google.android.exoplayer2.demo D/EventLogger:   LibopusAudioRenderer []
com.google.android.exoplayer2.demo D/EventLogger:   LibflacAudioRenderer []
com.google.android.exoplayer2.demo D/EventLogger:   FfmpegAudioRenderer []
com.google.android.exoplayer2.demo D/EventLogger:   TextRenderer []
com.google.android.exoplayer2.demo D/EventLogger:   MetadataRenderer []
com.google.android.exoplayer2.demo D/EventLogger:   CameraMotionRenderer []
com.google.android.exoplayer2.demo D/EventLogger: ]
com.google.android.exoplayer2.demo I/OMXClient: MuxOMX ctor
com.google.android.exoplayer2.demo D/EventLogger: downstreamFormat [eventTime=0.75, mediaPos=0.00, window=0, period=0, id=1/256, mimeType=video/avc, codecs=avc1.4D401F, res=1280x720]
com.google.android.exoplayer2.demo I/MediaCodec: [OMX.amlogic.avc.decoder.awesome] setting surface generation to 3303425
com.google.android.exoplayer2.demo D/ACodec_amlogic: query systemComposer 1
com.google.android.exoplayer2.demo E/ACodec: [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
com.google.android.exoplayer2.demo I/ACodec: codec does not support config priority (err -1010)
com.google.android.exoplayer2.demo I/art: Do partial code cache collection, code=61KB, data=61KB
com.google.android.exoplayer2.demo I/art: After code cache collection, code=61KB, data=60KB
com.google.android.exoplayer2.demo I/art: Increasing code cache capacity to 256KB
com.google.android.exoplayer2.demo D/SurfaceUtils: set up nativeWindow 0x764cab8410 for 1280x720, color 0x11, rotation 0, usage 0x2002900
com.google.android.exoplayer2.demo W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
com.google.android.exoplayer2.demo W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
com.google.android.exoplayer2.demo D/EventLogger: videoDecoderInitialized [eventTime=0.86, mediaPos=0.00, window=0, period=0, OMX.amlogic.avc.decoder.awesome]
com.google.android.exoplayer2.demo D/EventLogger: videoInputFormat [eventTime=0.86, mediaPos=0.00, window=0, period=0, id=1/256, mimeType=video/avc, codecs=avc1.4D401F, res=1280x720]
com.google.android.exoplayer2.demo D/EventLogger: downstreamFormat [eventTime=0.86, mediaPos=0.00, window=0, period=0, id=1/257, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000, language=nl]
com.google.android.exoplayer2.demo I/OMXClient: MuxOMX ctor
com.google.android.exoplayer2.demo I/ACodec: codec does not support config priority (err -2147483648)
com.google.android.exoplayer2.demo I/ACodec: codec does not support config operating rate (err -2147483648)
com.google.android.exoplayer2.demo D/EventLogger: audioDecoderInitialized [eventTime=0.92, mediaPos=0.00, window=0, period=0, OMX.google.aac.decoder]
com.google.android.exoplayer2.demo D/EventLogger: audioInputFormat [eventTime=0.93, mediaPos=0.00, window=0, period=0, id=1/257, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000, language=nl]
com.google.android.exoplayer2.demo D/AudioTrack: Client defaulted notificationFrames to 8208 for frameCount 16416
com.google.android.exoplayer2.demo E/DecoderAudioRenderer: Audio sink error
      com.google.android.exoplayer2.audio.AudioSink$UnexpectedDiscontinuityException: Unexpected audio track timestamp discontinuity: expected 0, got -78991767
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:792)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:637)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1922)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:848)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
com.google.android.exoplayer2.demo I/art: Do full code cache collection, code=123KB, data=111KB
com.google.android.exoplayer2.demo I/art: Starting a blocking GC JitCodeCache
com.google.android.exoplayer2.demo I/art: After code cache collection, code=79KB, data=61KB
com.google.android.exoplayer2.demo I/art: Background partial concurrent mark sweep GC freed 57(34KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 13MB/22MB, paused 32.003ms total 63.515ms
com.google.android.exoplayer2.demo I/art: Do partial code cache collection, code=120KB, data=95KB
com.google.android.exoplayer2.demo I/art: After code cache collection, code=120KB, data=95KB
com.google.android.exoplayer2.demo I/art: Increasing code cache capacity to 512KB
com.google.android.exoplayer2.demo D/EventLogger: loading [eventTime=3.66, mediaPos=-78.99, window=0, period=0, false]
```

I send u the test by email `dev.exoplayer@gmail.com`

- ExoPlayer version number
2.14.0

- Android version
Android7.1

- Android device
Amlogic905X

**Comment by VeiZhang** [comment]
In addition, android player works well. I don't know how to check what's the wrong.

**Comment by christosts** [comment]
Can you please share a URL to your content for reproduction? If you cannot share it publicly, please send it to dev.exoplayer@gmail.com with the subject "Issue #9388". I can see from the logs AudioSink is complaining about unexpected pts in the audio samples

> com.google.android.exoplayer2.audio.AudioSink$UnexpectedDiscontinuityException: Unexpected audio track timestamp discontinuity: expected 0, got -78991767

We need the content to debug if this is coming from the content itself or the player.

Thanks.

**Comment by VeiZhang** [comment]
@christosts ok, I send again, please check.

**Comment by bearboob** [comment]
I use exoplayer demos-main to play and meet the same problem. 

* ExoPlayer version number
2.15.1

* Android version
Android 11

* Android device
Amlogic and Realtek

> 10-13 09:51:32.146  5953  5953 D EventLogger: timeline [eventTime=0.57, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
10-13 09:51:32.146  5953  5953 D EventLogger:   period [?]
10-13 09:51:32.146  5953  5953 D EventLogger:   window [?, seekable=false, dynamic=false]
10-13 09:51:32.146  5953  5953 D EventLogger: ]
10-13 09:51:32.155  5953  5953 D EventLogger: videoEnabled [eventTime=0.58, mediaPos=0.00, window=0, period=0]
10-13 09:51:32.156  5953  5953 D EventLogger: audioEnabled [eventTime=0.58, mediaPos=0.00, window=0, period=0]
10-13 09:51:32.157  5953  5953 I JZ      : ExoPlayerImpl  updatePlaybackInfo newPlaybackInfo=PlaybackInfo{ !!!!playbackState=2, bufferedPositionUs=0, totalBufferedDurationUs=0, positionUs=0, isLoading=true, requestedContentPositionUs=-9223372036854775807, playbackError=null}
10-13 09:51:32.160  5953  5953 D EventLogger: tracks [eventTime=0.58, mediaPos=0.00, window=0, period=0
10-13 09:51:32.160  5953  5953 D EventLogger:   MediaCodecVideoRenderer [
10-13 09:51:32.160  5953  5953 D EventLogger:     Group:0, adaptive_supported=N/A [
10-13 09:51:32.160  5953  5953 D EventLogger:       [X] Track:0, id=1/17, mimeType=video/mpeg2, res=1920x1080, supported=YES
10-13 09:51:32.160  5953  5953 D EventLogger:     ]
10-13 09:51:32.160  5953  5953 D EventLogger:   ]
10-13 09:51:32.160  5953  5953 D EventLogger:   MediaCodecAudioRenderer [
10-13 09:51:32.160  5953  5953 D EventLogger:     Group:0, adaptive_supported=N/A [
10-13 09:51:32.161  5953  5953 D EventLogger:       [X] Track:0, id=1/20, mimeType=audio/ac3, channels=2, sample_rate=48000, language=en, supported=YES
10-13 09:51:32.161  5953  5953 D EventLogger:     ]
10-13 09:51:32.161  5953  5953 D EventLogger:   ]
10-13 09:51:32.161  5953  5953 D EventLogger:   TextRenderer []
10-13 09:51:32.161  5953  5953 D EventLogger:   MetadataRenderer []
10-13 09:51:32.161  5953  5953 D EventLogger:   CameraMotionRenderer []
10-13 09:51:32.161  5953  5953 D EventLogger: ]
10-13 09:51:32.294  5953  6927 E MediaCodecAudioRenderer: Audio sink error
10-13 09:51:32.294  5953  6927 E MediaCodecAudioRenderer:   com.google.android.exoplayer2.audio.AudioSink$UnexpectedDiscontinuityException: Unexpected audio track timestamp discontinuity: expected 0, got -767245
10-13 09:51:32.294  5953  6927 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:803)
10-13 09:51:32.294  5953  6927 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:644)
10-13 09:51:32.294  5953  6927 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.bypassRender(MediaCodecRenderer.java:2203)
10-13 09:51:32.294  5953  6927 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:818)
10-13 09:51:32.294  5953  6927 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:988)
10-13 09:51:32.294  5953  6927 E MediaCodecAudioRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:483)
10-13 09:51:32.294  5953  6927 E MediaCodecAudioRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
10-13 09:51:32.294  5953  6927 E MediaCodecAudioRenderer:       at android.os.Looper.loop(Looper.java:223)
10-13 09:51:32.294  5953  6927 E MediaCodecAudioRenderer:       at android.os.HandlerThread.run(HandlerThread.java:67)
10-13 09:51:32.294  5953  6927 I JZ      : MediaCodecAudioRenderer Audio sink error error=Unexpected audio track timestamp discontinuity: expected 0, got -767245


@christosts ts file link is here https://drive.google.com/file/d/14tPeQTnTwtZIZUOTJTeo9zS657rAZKVc/view?usp=sharing
please check,thank you.

**Comment by christosts** [comment]
@VeiZhang: I checked the two files that we received with teh demo app in ExoPlayer 2.15.1:
- The first file contains video with interlaced scan type and an audio track encoded in AC3. It is not guaranteed that decoders in the Android platform will be decode interlaced video (scan type should be progressive). In a few tests on a Sony TV, sound is playing but no video is displaying. Please use videos encoded with progressive scan type. 
- The second file contains video with progressive scan type and an AAC audio track. In the second file, the presentation timestamps for audio and video  start from a different point. Is there a reason why the timestamps don't start at the same offset?

You can inspect the timestamps in the file with ffprobe
- video: `ffprobe -loglevel error -show_entries frame=pkt_pos,pkt_pts_time -select_streams v:0 -pretty {file}`
- audio: `ffprobe -loglevel error -show_entries frame=pkt_pos,pkt_pts_time -select_streams a:0 -pretty {file}`

Also, how did you collect the stacktrace? The stacktrace mentions `DecoderAudioRenderer` and `MediaCodecAudioRenderer`, but only  the `MediaCodecAudioRenderer` should have been involved in this case:
```
com.google.android.exoplayer2.demo E/DecoderAudioRenderer: Audio sink error
      com.google.android.exoplayer2.audio.AudioSink$UnexpectedDiscontinuityException: Unexpected audio track timestamp discontinuity: expected 0, got -78991767
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:792)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:637)
```
