### ISSUE TITLE
Error rendererFormat : Format(1, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, 30.0], [-1, -1])

### ISSUE THREAD

**Issue by Jaydipnathani** [google/ExoPlayer#9396]
> `DefaultRenderersFactory. setEnableDecoderFallback(true)`

After using this my issue was resolve when I test in debug mode. But when I did App release, the issue started coming back to my user so the issue not resolve.

A version of ExoPlayer being used  2.14.1

I have an issue with ...
***Device Name:-*** 

**Samsung** 
  
- Galaxy J1(2016)  -  Android : 5.1.1
- Galaxy A20 - Android : 11
- Galaxy A20e - Android : 11
- Galaxy J6+ - Android : 10
- Galaxy A10 - Android : 10
- Galaxy C7 -  Android : 8.0.0
- Galaxy A2 - Core Android : 8.1.0
- Galaxy J7 - Android : 5.1.1
```
Non-fatal Exception: java.lang.Exception: Title : Videoview Blackscreen issue : Activity
Function : prepareVideo()
Callback : videoview setOnErrorListener()
Error : MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4029, -1, null, [1920, 1080, 29.970028], [-1, -1]), format_supported=YES
Error_code : 1
App_name : 
Message : Video path : file:///data/user/0/packagename/files/app_templates/32717/602d038a0e280_zip_file_1613562762/602d038a0e280_zip_file_1613562762/title_video_mkf16.mp4
 Is Video path exist? : true
 Error rendererName : MediaCodecVideoRenderer
 Error rendererFormat : Format(1, null, null, video/avc, avc1.4D4029, -1, null, [1920, 1080, 29.970028], [-1, -1])
 Error rendererFormatSupport4
 Error LocalizedMessage : Decoder failed: c2.android.avc.decoder
 Error Message : Decoder failed: c2.android.avc.decoder
```
Video :- [title_video_mkf16.mp4](https://drive.google.com/file/d/1YTKz_ILRIswqmgMO-facXknueJPKrH5j/view?usp=sharing)
***HUAWEI***

- HUAWEI Y5 2019 - android : 9
- Huawei MediaPad T5 - android : 8.0.0
- HUAWEI P smart 2019 - android : 10
- Mate 20 Pro - android : 10
- Mate 20 - android : 10
- P20 - android : 10
- 荣耀畅玩7X - android : 9
- HUAWEI P20 Lite - android : 9
```
Non-fatal Exception: java.lang.Exception: Title : Videoview Blackscreen issue : Activity
Function : prepareVideo()
Callback : videoview setOnErrorListener()
Error : MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, 30.0], [-1, -1]), format_supported=YES
Error_code : 1
App_name : 
Message : Video path : file:///data/user/0/packagename/files/app_templates/36028/bd468f5a62b44_zip_file_1625309727657/bd468f5a62b44_zip_file_1625309727657/outro_video_pgg3.mp4
 Is Video path exist? : true
 Error rendererName : MediaCodecVideoRenderer
 Error rendererFormat : Format(1, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, 30.0], [-1, -1])
 Error rendererFormatSupport4
 Error LocalizedMessage : Decoder init failed: OMX.hisi.video.decoder.avc, Format(1, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, 30.0], [-1, -1])
 Error Message : Decoder init failed: OMX.hisi.video.decoder.avc, Format(1, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, 30.0], [-1, -1])
```

Video :- [outro_video_pgg3.mp4](https://drive.google.com/file/d/156RHLpUY2vQQFuKOAmyuF2xih74Hn9ut/view?usp=sharing)

***VIVO***
- V2029 Android : 10
 ```
Non-fatal Exception: java.lang.Exception: Title : Videoview Blackscreen issue : Activity
Function : prepareVideo()
Callback : videoview setOnErrorListener()
Error : MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.42C028, -1, null, [1920, 1080, 30.0], [-1, -1]), format_supported=YES
Error_code : 1
App_name :
Message : Video path : file:///storage/emulated/0/Android/data/packagename/files/Movies/1Intro/bg_video_trim/fcb9c851f0564_trim_video_file_1629262336212.mp4
 Is Video path exist? : true
 Error rendererName : MediaCodecVideoRenderer
 Error rendererFormat : Format(1, null, null, video/avc, avc1.42C028, -1, null, [1920, 1080, 30.0], [-1, -1])
 Error rendererFormatSupport4
 Error LocalizedMessage : Decoder failed: c2.android.avc.decoder
 Error Message : Decoder failed: c2.android.avc.decoder 
```

**Layout:**

``` 
<com.google.android.exoplayer2.ui.PlayerView
                    android:id="@+id/videoView"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_gravity="center"
                    android:gravity="center"
                    app:use_controller="false" />
```

**Java Code.**

```
     private PlayerView playerView ;
     private SimpleExoPlayer simpleExoPlayer;
    private View surfaceView;

  @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
      videoPlayerView = findViewById(R.id.videoView);
      initializePlayer();
}

```

```
 @Override
    protected void onPause() {
        super.onPause();

      onDestroyPlayerView();  
    }

```
```
  @Override
    protected void onResume() {
        super.onResume();

        Log.e(TAG, "onResume: ");
         initializePlayer();
       }

```
```


 public void initializePlayer() {

        Log.i(TAG, "initializePlayer: ");
        Log.e(TAG, "Exoplayer INIT: ");

        DefaultRenderersFactory rf = new DefaultRenderersFactory(context.getApplicationContext()).setEnableDecoderFallback(true);
        simpleExoPlayer = new SimpleExoPlayer.Builder(context, rf).build();

        if (playerView != null) {
            playerView.setPlayer(simpleExoPlayer);
            playerView.setUseController(setController);
            playerView.setResizeMode(RESIZE_MODE);
            surfaceView = playerView.getVideoSurfaceView();
            if (surfaceView != null) {
                Log.i(TAG, "initializePlayer: SURFACE Found!!");
            } else {
                Log.i(TAG, "initializePlayer: SURFACE = NULL ");
            }
           setSurfaceViewToExoPlayer();
        }
    }

```

```
public void setSurfaceViewToExoPlayer() {

        Log.i(TAG, "setSurfaceViewToExoPlayer: ");
        if (surfaceView != null) {
            if (simpleExoPlayer != null) {
                if (surfaceView instanceof SurfaceView) {
                    simpleExoPlayer.setVideoSurfaceView((SurfaceView) surfaceView);
                }
            }
        }
    }

    public void prepareVideo() {
     
        if (simpleExoPlayer != null && videoPath != null && videoPath.length() > 0) {

            MediaItem mediaItem = new MediaItem.Builder()
                    .setUri(Uri.fromFile(FileUtils.getValidFile(videoPath.replace(" ", "%20"))))
                    .setMimeType(MimeTypes.VIDEO_MP4)
                    .build();

            if (simpleExoPlayer.getMediaItemCount() > 0) {
                simpleExoPlayer.clearMediaItems();
            }

            simpleExoPlayer.setMediaItem(mediaItem);
            simpleExoPlayer.setRepeatMode(repeatMode);
            simpleExoPlayer.setPlayWhenReady(isPlayWhenReady);
            simpleExoPlayer.setVolume(1f);
            simpleExoPlayer.seekTo(0, 0);
            simpleExoPlayer.addListener(this);
            simpleExoPlayer.prepare();
        }
    }

```

```
public void onDestroyPlayerView() {

            simpleExoPlayer.pause();
            if (simpleExoPlayer.getMediaItemCount() > 0) {
                simpleExoPlayer.clearMediaItems();
            }
            Log.e(TAG, "Exoplayer RELEASE: ");

            simpleExoPlayer.stop(true);
            simpleExoPlayer.clearVideoSurface();
            simpleExoPlayer.removeListener(this);
            simpleExoPlayer.release();
            simpleExoPlayer = null;
     
    }
```

Please help me with how to fix this issue. @christosts @ojw28 @marcbaechinger @andrewlewis 

Thanks

_Originally posted by @Jaydipnathani in https://github.com/google/ExoPlayer/issues/9230#issuecomment-901661806_

**Comment by 3-BodyCoding** [comment]
This is because the avc1 encoded video of ffmpeg does not start the file header. I hope exoplayer can support it.

**Comment by Jaydipnathani** [comment]
Please help me with how to fix this issue. @christosts @ojw28 @marcbaechinger @andrewlewis

**I think this issue is not a device-specific issue. Many devices have issues.**

**Comment by christosts** [comment]
I tested the files with ExoPlayer 2.16 on a Pixel 4 (with both the hardware and software decoder) and they play fine. Looking at the code snippet, I noticed two things:

1. On your code snippet, you are not overriding the Activity's `onStop()` method and you're releasing the player only when `onPause()` is called. Maybe your app is not releasing the player properly, therefore the player is keeping decoders occupied. Try overriding `onStop()` as demonstrated in [the demo app](https://github.com/google/ExoPlayer/blob/r2.16.0/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L169) (if you're not doing so already).

1. on your `initializePlayer()` you set the `palyerView`'s surface on the player again (`setSurfaceViewToExoPlayer()`) after calling `playerView.setPlayer(simpleExoPlayer)`. You don't need to set the video surface view again. You should not need to call `setSurfaceViewToExoPlayer()`, unless there's something I'm missing. I don't think this is causing the problems you are seeing, but it's not needed either.

**Comment by ojw28** [comment]
> On your code snippet, you are not overriding the Activity's onStop() method and you're releasing the player only when onPause() is called. Maybe your app is not releasing the player properly, therefore the player is keeping decoders occupied. Try overriding onStop() as demonstrated in the demo app (if you're not doing so already).

To clarify, the demo app releases in `onPause()` _or_ `onStop()`, depending on API level. `onPause()` happens first  as described in the [Activity documentation](https://developer.android.com/reference/android/app/Activity#activity-lifecycle). So from a resource management perspective it's fine to release in `onPause()` on all API levels, and to not override `onStop()` when doing this. Hence I don't think there's anything wrong with the code snippet as it is, in this regard.

As context, the reason the demo app releases in `onStop()` on API levels > 23 is that it works better on devices that support multi-window, because it allows playback to proceed whilst another visible application has focus. The application without focus will be paused, but not stopped, when this is the case. The reason the demo app releases in `onPause()` on earlier API levels is because earlier API levels only provided very loose guarantees around when `onStop()` would be called. These guarantees were made a lot tighter for API levels > 23.

**Comment by Jaydipnathani** [comment]
Thank you for answering.

1) I have tried with init and release Exoplayer instance by overriding onStart() and onStop() also as described in the demo, and I was getting the same issue as well.

2) I have noticed that this issue arrives when Video Ads (Interstitial ad, Native video ad, Rewarded video ad) display from Firebase AdMob. so I think AdMob does not release the proper player so that.

So, How can we handle this?

```
2021-11-23 09:30:33.437 30123-554/com.oneintro.intromaker E/ExoPlayerImplInternal: Renderer error.
    com.google.android.gms.ads.exoplayer3.c
        at com.google.android.gms.ads.exoplayer3.mediacodec.c.N(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:16)
        at com.google.android.gms.ads.exoplayer3.mediacodec.c.G(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:4)
        at com.google.android.gms.ads.exoplayer3.video.h.G(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:1)
        at com.google.android.gms.ads.exoplayer3.mediacodec.c.z(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:3)
        at com.google.android.gms.ads.exoplayer3.n.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:41)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.gms.ads.exoplayer3.mediacodec.b: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, video/avc, -1, null, [270, 480, -1.0], [-1, -1])
        at com.google.android.gms.ads.exoplayer3.mediacodec.c.N(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:15)
        at com.google.android.gms.ads.exoplayer3.mediacodec.c.G(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:4) 
        at com.google.android.gms.ads.exoplayer3.video.h.G(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:1) 
        at com.google.android.gms.ads.exoplayer3.mediacodec.c.z(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:3) 
        at com.google.android.gms.ads.exoplayer3.n.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:41) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1935)
        at android.media.MediaCodec.configure(MediaCodec.java:1864)
        at com.google.android.gms.ads.exoplayer3.video.h.J(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:16)
        at com.google.android.gms.ads.exoplayer3.mediacodec.c.N(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:13)
        at com.google.android.gms.ads.exoplayer3.mediacodec.c.G(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:4) 
        at com.google.android.gms.ads.exoplayer3.video.h.G(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:1) 
        at com.google.android.gms.ads.exoplayer3.mediacodec.c.z(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:3) 
        at com.google.android.gms.ads.exoplayer3.n.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:41) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
2021-11-23 09:30:37.351 30123-30123/com.oneintro.intromaker E/ObAdMobNativeAdHandler: UnifiedNativeAdView onNativeAdLoaded()
```

**Comment by wahdatjan** [comment]
The thing is that you are trying to run on surfaceView which i was doing as well , try to remove surface view , run without surfaceview

**Comment by christosts** [comment]
> 2\. I have noticed that this issue arrives when Video Ads (Interstitial ad, Native video ad, Rewarded video ad) display from Firebase AdMob. so I think AdMob does not release the proper player so that.

It sounds like you're using ExoPlayer and Admob in your app, and possibly hit the same error as #5856 and #5582. You need to make sure that you release your ExoPlayer instance before playing an ad and also you might need to do the workaround described in this [comment on #5582](https://github.com/google/ExoPlayer/issues/5582#issuecomment-469331547) when the app is resuming.
