### ISSUE TITLE
How to get companion ads' height and width?

### ISSUE THREAD

**Issue by deeteeh** [google/ExoPlayer#9397]
I want to get height and width of companion ads but every time app crashes. adEvent.getAd() returning ad but it crashes when I start null checking adEvent.getAd().getCompanionAds()

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <package_name>, PID: 3117
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at com.google.ads.interactivemedia.v3.impl.data.c.getCompanionAds(SourceFile:2)
        at <package_name>.activities.PlayerActivity$d.onAdEvent(SourceFile:1077)
        at com.google.ads.interactivemedia.v3.internal.dg.b(SourceFile:10)
        at com.google.ads.interactivemedia.v3.internal.cv.b(SourceFile:15)
        at com.google.ads.interactivemedia.v3.internal.ed.k(SourceFile:47)
        at com.google.ads.interactivemedia.v3.internal.ej.f(SourceFile:5)
        at com.google.ads.interactivemedia.v3.internal.eg.shouldOverrideUrlLoading(SourceFile:2)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:77)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-451515923:14)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

![image](https://user-images.githubusercontent.com/90253338/132332297-860d818b-55e6-4f6c-afce-d6bc5e9fc01e.png)

**Comment by andrewlewis** [comment]
Are you using the ExoPlayer IMA extension? If so, that only supports client-side ad insertion but [`Ad.getCompanionAds()`](https://developers.google.com/interactive-media-ads/docs/sdks/android/dai/api/reference/com/google/ads/interactivemedia/v3/api/Ad.html?hl=el#getCompanionAds()) is documented as only for when using DAI, so I don't think this method will be useful. (It probably shouldn't throw for this case though, so I will see if we can fix that.)

I'm not aware of a way to get the size of companion ads when using client-side ad insertion but instead I think your app should be providing ad slots that are the correct size for the companion ads. See also the [HTML5 IMA demo](https://googleads.github.io/googleads-ima-html5/vsi/) which has a bunch of ad slots in the UI. It may be worth searching/asking for help at at https://groups.google.com/g/ima-sdk if this isn't helpful.

**Comment by deeteeh** [comment]
> Are you using the ExoPlayer IMA extension? If so, that only supports client-side ad insertion but [`Ad.getCompanionAds()`](https://developers.google.com/interactive-media-ads/docs/sdks/android/dai/api/reference/com/google/ads/interactivemedia/v3/api/Ad.html?hl=el#getCompanionAds()) is documented as only for when using DAI, so I don't think this method will be useful. (It probably shouldn't throw for this case though, so I will see if we can fix that.)
> 
> I'm not aware of a way to get the size of companion ads when using client-side ad insertion but instead I think your app should be providing ad slots that are the correct size for the companion ads. See also the [HTML5 IMA demo](https://googleads.github.io/googleads-ima-html5/vsi/) which has a bunch of ad slots in the UI. It may be worth searching/asking for help at at https://groups.google.com/g/ima-sdk if this isn't helpful.

Hi Andrew, thanks for the response.

Yes, I am using Exoplayer Ima extension. Actually our ad server returns different ad with different companion ad size, so I wanted to get the ad size from the current loaded ad and then set the slot's size.
Is there any way to get companion ad data from the loaded ad response?

**Comment by andrewlewis** [comment]
I don't know of a way to do that (as far as I know users of companion ads generally know the sizes up front because they are standardized or they generated the ad tag themselves). Could you ask on the IMA SDK forum I linked to above and reply here with a link so others can benefit from the answer?

**Comment by deeteeh** [comment]
Posted the question on IMA SDK forum.

link-> [https://groups.google.com/g/ima-sdk/c/ccoWV9pDwFQ/m/4AAN39G1BwAJ](https://groups.google.com/g/ima-sdk/c/ccoWV9pDwFQ/m/4AAN39G1BwAJ)

**Comment by andrewlewis** [comment]
Thanks for posting that.

Just for the record, I've also submitted a fix in the IMA SDK for the `NullPointerException` to avoid the crash, but this won't help with what you are trying to do as this method returns an empty list for non-DAI use cases.
