### ISSUE TITLE
Fail to play RTSP stream from live555 with static payload type

### ISSUE THREAD

**Issue by goffioul** [google/ExoPlayer#9400]
Trying to play a RTSP stream from live555 (not recent, I admit) fails with the following exception:
```
[...]
09-07 15:14:31.032 12502 12532 E ExoPlayerImplInternal:   Caused by: java.lang.IllegalStateException
09-07 15:14:31.032 12502 12532 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:84)
09-07 15:14:31.032 12502 12532 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.rtsp.MediaDescription$Builder.build(MediaDescription.java:201)
09-07 15:14:31.032 12502 12532 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.rtsp.SessionDescriptionParser.addMediaDescriptionToSession(SessionDescriptionParser.java:202)
```

The logs of the RTSP dialog is as follows:
```
09-07 15:14:30.975 12502 12532 D RTSP    : OPTIONS rtsp://10.254.253.68/IdentityThief-576i-MPEG2.ts RTSP/1.0
09-07 15:14:30.975 12502 12532 D RTSP    : CSeq: 0
09-07 15:14:30.975 12502 12532 D RTSP    : User-Agent: ExoPlayerLib/2.15.0
09-07 15:14:30.975 12502 12532 D RTSP    : 
09-07 15:14:30.987 12502 12532 D RTSP    : RTSP/1.0 200 OK
09-07 15:14:30.987 12502 12532 D RTSP    : CSeq: 0
09-07 15:14:30.987 12502 12532 D RTSP    : Date: Tue, Sep 07 2021 14:14:30 GMT
09-07 15:14:30.987 12502 12532 D RTSP    : Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER
09-07 15:14:30.992 12502 12532 D RTSP    : DESCRIBE rtsp://10.254.253.68/IdentityThief-576i-MPEG2.ts RTSP/1.0
09-07 15:14:30.992 12502 12532 D RTSP    : CSeq: 1
09-07 15:14:30.992 12502 12532 D RTSP    : User-Agent: ExoPlayerLib/2.15.0
09-07 15:14:30.992 12502 12532 D RTSP    : 
09-07 15:14:31.005 12502 12532 D RTSP    : RTSP/1.0 200 OK
09-07 15:14:31.005 12502 12532 D RTSP    : CSeq: 1
09-07 15:14:31.005 12502 12532 D RTSP    : Date: Tue, Sep 07 2021 14:14:30 GMT
09-07 15:14:31.005 12502 12532 D RTSP    : Content-Base: rtsp://10.254.253.68/IdentityThief-576i-MPEG2.ts/
09-07 15:14:31.005 12502 12532 D RTSP    : Content-Type: application/sdp
09-07 15:14:31.005 12502 12532 D RTSP    : Content-Length: 441
09-07 15:14:31.005 12502 12532 D RTSP    : 
09-07 15:14:31.005 12502 12532 D RTSP    : v=0
09-07 15:14:31.005 12502 12532 D RTSP    : o=- 1628769590593995 1 IN IP4 10.254.253.68
09-07 15:14:31.005 12502 12532 D RTSP    : s=MPEG Transport Stream, streamed by the LIVE555 Media Server
09-07 15:14:31.005 12502 12532 D RTSP    : i=IdentityThief-576i-MPEG2.ts
09-07 15:14:31.005 12502 12532 D RTSP    : t=0 0
09-07 15:14:31.005 12502 12532 D RTSP    : a=tool:LIVE555 Streaming Media v2012.05.17
09-07 15:14:31.005 12502 12532 D RTSP    : a=type:broadcast
09-07 15:14:31.005 12502 12532 D RTSP    : a=control:*
09-07 15:14:31.005 12502 12532 D RTSP    : a=range:npt=0-6448.227
09-07 15:14:31.005 12502 12532 D RTSP    : a=x-qt-text-nam:MPEG Transport Stream, streamed by the LIVE555 Media Server
09-07 15:14:31.005 12502 12532 D RTSP    : a=x-qt-text-inf:IdentityThief-576i-MPEG2.ts
09-07 15:14:31.005 12502 12532 D RTSP    : m=video 0 RTP/AVP 33
09-07 15:14:31.005 12502 12532 D RTSP    : c=IN IP4 0.0.0.0
09-07 15:14:31.005 12502 12532 D RTSP    : b=AS:5915
09-07 15:14:31.005 12502 12532 D RTSP    : a=control:track1
```

The exception is generated here: https://github.com/google/ExoPlayer/blob/release-v2/library/rtsp/src/main/java/com/google/android/exoplayer2/source/rtsp/MediaDescription.java#L200
which refers to RTSP specs: https://datatracker.ietf.org/doc/html/rfc2326#appendix-C.1.3

However, AFAICS the specs only requires rtpmap for dynamic payload type, not static one. And live555 is sending a static payload type (see https://datatracker.ietf.org/doc/html/rfc1890, table 2, page 14).

Is this a limitation in ExoPlayer, or am I missing something?

**Comment by claincly** [comment]
We only support AVC at the moment, and it's not statically assigned.

RTP payload type 33 is assigned to MP2T, which we don't support.

So yes, it is an ExoPlayer limitation.

**Comment by goffioul** [comment]
I found out #9210 afterwards, does it make sense to keep this issue separate?

**Comment by claincly** [comment]
Please close it and use the format tracker, if you don't have further question on this, thanks!

**Comment by goffioul** [comment]
Duplicate of #9210
