### ISSUE TITLE
Crash in Android 7 lenovo devices, while releasing the player

### ISSUE THREAD

**Issue by tasmiya-tabassum** [google/ExoPlayer#9407]
App is crashing while releasing the player,

- Device - Android 7 Lenevo devices
- Version of library consumed in the app - 2.14.1
- Below is the crash report captured by Firebase,

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.Surface.release()' on a null object reference
       at com.google.android.exoplayer2.SimpleExoPlayer.setVideoOutputInternal(SimpleExoPlayer.java:1927)
       at com.google.android.exoplayer2.SimpleExoPlayer.access$4000(SimpleExoPlayer.java:92)
       at com.google.android.exoplayer2.SimpleExoPlayer$ComponentListener.surfaceDestroyed(SimpleExoPlayer.java:2278)
       at android.view.SurfaceView.updateWindow(SurfaceView.java:606)
       at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:255)
       at android.view.View.dispatchWindowVisibilityChanged(View.java:10274)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1566)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1278)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6357)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
       at android.view.Choreographer.doCallbacks(Choreographer.java:683)
       at android.view.Choreographer.doFrame(Choreographer.java:619)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
       
      Thanks!

**Comment by ojw28** [comment]
I think, although am not 100% certain, that this was fixed by https://github.com/google/ExoPlayer/commit/ab416f41ac33339670f412beb442e5a7f14e4063, which is in the 2.15.0 release. Closing on that assumption. Please let us know if you still see a crash of this kind after upgrading to 2.15.0 or later. Thanks!
