### ISSUE TITLE
HLS live stream not work

### ISSUE THREAD

**Issue by trkich** [google/ExoPlayer#942]
I downloaded demo and try one of my HLS live stream (m3u8) but it doesn't work. 
The same live stream work perfectly on iOS, Roku, MAG, JWPlayer, Samsung and LG smart tv, VLC etc..

If you want i can send you stream url on email?
Thanks in advance.

11-09 17:49:10.561  17638-17727/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:807)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:738)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
11-09 17:49:10.599      350-373/system_process I/ActivityManager﹕ Displayed com.google.android.exoplayer.demo/.PlayerActivity: +3s237ms
11-09 17:49:10.816      350-364/system_process V/WindowManager﹕ Adding window Window{2dddeccb u0 Panel:com.google.android.exoplayer.demo/com.google.android.exoplayer.demo.PlayerActivity} at 6 of 12 (after Window{2f402b90 u0 com.google.android.exoplayer.demo/com.google.android.exoplayer.demo.PlayerActivity})
11-09 17:49:10.919  17638-17638/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [1.42]
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:807)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:738)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
11-09 17:49:10.967  17638-17638/com.google.android.exoplayer.demo D/EventLogger﹕ state [1.43, true, I]
11-09 17:49:11.107  17638-17659/com.google.android.exoplayer.demo W/EGL_emulation﹕ eglSurfaceAttrib not implemented
11-09 17:49:11.107  17638-17659/com.google.android.exoplayer.demo W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa60a5840, error=EGL_SUCCESS

**Comment by andrewlewis** [comment]
HLS samples in the demo app require PlayerActivity.TYPE_HLS to be passed as the 'type' argument to the Sample constructor (not PlayerActivity.TYPE_OTHER). Does it play correctly when you do that?

**Comment by trkich** [comment]
Hi, I try also with PlayerActivity.TYPE_HLS and its the same.

**Comment by ojw28** [comment]
At the very least, the logs would look very different to the ones provided above.

**Comment by trkich** [comment]
Hi this is log when i use PlayerActivity.TYPE_HLS:

new Sample("Fanous", "http://url to video", PlayerActivity.TYPE_HLS),

11-10 12:57:48.286    3372-3388/com.google.android.exoplayer.demo I/art﹕ Background sticky concurrent mark sweep GC freed 10497(644KB) AllocSpace objects, 9(432KB) LOS objects, 5% free, 6MB/6MB, paused 1.396ms total 217.962ms
11-10 12:57:48.323    3372-3388/com.google.android.exoplayer.demo W/art﹕ Suspending all threads took: 5.413ms
11-10 12:57:48.550    3372-3381/com.google.android.exoplayer.demo W/art﹕ Suspending all threads took: 59.323ms
11-10 12:57:48.595    3372-3388/com.google.android.exoplayer.demo I/art﹕ Background partial concurrent mark sweep GC freed 706(33KB) AllocSpace objects, 0(0B) LOS objects, 36% free, 6MB/10MB, paused 1.593ms total 152.184ms
11-10 12:57:48.601    3372-3388/com.google.android.exoplayer.demo W/art﹕ Suspending all threads took: 5.706ms
11-10 12:57:48.704    3372-3372/com.google.android.exoplayer.demo I/ExoPlayerImpl﹕ Init 1.5.2
11-10 12:57:48.729    3372-3372/com.google.android.exoplayer.demo D/EventLogger﹕ start [0]
11-10 12:57:48.733    3372-3372/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, false, P]
11-10 12:57:48.756    3372-3372/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.03, true, P]
11-10 12:57:49.104    3372-3409/com.google.android.exoplayer.demo W/EGL_emulation﹕ eglSurfaceAttrib not implemented
11-10 12:57:49.104    3372-3409/com.google.android.exoplayer.demo W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xb4b5a700, error=EGL_SUCCESS
11-10 12:57:49.551    3372-3372/com.google.android.exoplayer.demo I/Choreographer﹕ Skipped 40 frames!  The application may be doing too much work on its main thread.
11-10 12:57:50.045    3372-3381/com.google.android.exoplayer.demo W/art﹕ Suspending all threads took: 50.715ms
11-10 12:57:50.803    3372-3372/com.google.android.exoplayer.demo D/EventLogger﹕ state [2.07, true, B]
11-10 12:57:50.863    3372-3372/com.google.android.exoplayer.demo D/EventLogger﹕ videoFormat [2.13, 0, 0]
11-10 12:57:50.940    3372-5065/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
11-10 12:57:51.044    3372-3381/com.google.android.exoplayer.demo W/art﹕ Suspending all threads took: 9.722ms
11-10 12:57:51.082    3372-5065/com.google.android.exoplayer.demo W/OMXNodeInstance﹕ [1:google.h264.decoder] component does not support metadata mode; using fallback
11-10 12:57:51.082    3372-5065/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
11-10 12:57:51.164    3372-5070/com.google.android.exoplayer.demo E/SoftAVC﹕ Decoder failed: -2
11-10 12:57:51.171    3372-5065/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.google.h264.decoder] ERROR(0x80001001)
11-10 12:57:51.172    3372-5065/com.google.android.exoplayer.demo E/ACodec﹕ signalError(omxError 0x80001001, internalError -2147483648)
11-10 12:57:51.173    3372-5064/com.google.android.exoplayer.demo E/MediaCodec﹕ Codec reported err 0x80001001, actionCode 0, while in state 6
11-10 12:57:51.242    3372-5044/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal runtime error.
    java.lang.IllegalStateException
            at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
            at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:983)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:529)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:460)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
11-10 12:57:51.282    3372-3372/com.google.android.exoplayer.demo D/EventLogger﹕ decoderInitialized [2.55, OMX.google.h264.decoder]
11-10 12:57:51.322    3372-5044/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Stop failed.
    java.lang.IllegalStateException
            at android.media.MediaCodec.native_stop(Native Method)
            at android.media.MediaCodec.stop(MediaCodec.java:628)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.releaseCodec(MediaCodecTrackRenderer.java:411)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onDisabled(MediaCodecTrackRenderer.java:379)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onDisabled(MediaCodecVideoTrackRenderer.java:280)
            at com.google.android.exoplayer.TrackRenderer.disable(TrackRenderer.java:235)
            at com.google.android.exoplayer.ExoPlayerImplInternal.stopAndDisable(ExoPlayerImplInternal.java:561)
            at com.google.android.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:548)
            at com.google.android.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:525)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:247)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
11-10 12:57:51.504    3372-3381/com.google.android.exoplayer.demo W/art﹕ Suspending all threads took: 8.836ms
11-10 12:57:51.538    3372-3372/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [2.74]
    com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.lang.IllegalStateException
            at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
            at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:983)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:529)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:460)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
11-10 12:57:51.784    3372-3409/com.google.android.exoplayer.demo W/EGL_emulation﹕ eglSurfaceAttrib not implemented
11-10 12:57:51.784    3372-3409/com.google.android.exoplayer.demo W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa60a5100, error=EGL_SUCCESS
11-10 12:57:51.816    3372-3372/com.google.android.exoplayer.demo D/EventLogger﹕ state [3.08, true, I]

**Comment by ojw28** [comment]
Please send us the URL of the affected stream. There's an address you can use [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html).

**Comment by trkich** [comment]
I sent you two links on email. Please check...

**Comment by ojw28** [comment]
- The first link works fine on my device. You'd need to provide more details, as described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html), for us to debug further.
- The second link contains H.262 video, which isn't supported by most Android devices (or by ExoPlayer currently, although we'll be adding support where the underlying device does provide support in https://github.com/google/ExoPlayer/pull/915).

**Comment by trkich** [comment]
Video is H.264: http://prntscr.com/917cjy
I downloaded code from master and add my urls to Samples.java in demo app and try to run.

**Comment by ojw28** [comment]
Are you referring specifically to the second link? When I try and play the link (using VLC) I just get a massive warning icon and "warning security issue, app users: please restart your app" message, which is delivered as H262 video. My guess is I'm seeing something different because authentication is failing (i.e. the link you provided is not sufficient for me to successfully authenticate, or else there is some kind of check that fails, for example a geo restriction).
