### ISSUE TITLE
Leak: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

### ISSUE THREAD

**Issue by franciscofranco** [google/ExoPlayer#943]
```javascript
                                                          java.lang.Throwable: Explicit termination method 'dispose' not called
                                                              at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                              at android.view.DisplayEventReceiver.<init>(DisplayEventReceiver.java:65)
                                                              at android.view.Choreographer$FrameDisplayEventReceiver.<init>(Choreographer.java:792)
                                                              at android.view.Choreographer.<init>(Choreographer.java:207)
                                                              at android.view.Choreographer.<init>(Choreographer.java)
                                                              at android.view.Choreographer$1.initialValue(Choreographer.java:104)
                                                              at android.view.Choreographer$1.initialValue(Choreographer.java:99)
                                                              at java.lang.ThreadLocal$Values.getAfterMiss(ThreadLocal.java:430)
                                                              at java.lang.ThreadLocal.get(ThreadLocal.java:65)
                                                              at android.view.Choreographer.getInstance(Choreographer.java:232)
                                                              at com.google.android.exoplayer.VideoFrameReleaseTimeHelper.enable(VideoFrameReleaseTimeHelper.java:89)
                                                              at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onEnabled(MediaCodecVideoTrackRenderer.java:226)
                                                              at com.google.android.exoplayer.TrackRenderer.enable(TrackRenderer.java:162)
                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:322)
                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                              at android.os.Looper.loop(Looper.java:148)
                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                              at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
``

**Comment by ojw28** [comment]
I believe this is a platform bug on some versions of Android (it's fixed in M). It's also essentially harmless, as far as I know.
