### ISSUE TITLE
Exoplayer is unable to load some of HLS urls But Safari on Mac  could load them!

### ISSUE THREAD

**Issue by NimaTajfar** [google/ExoPlayer#9447]
Hi , Please try these 2 url which works with Safari Macos and loaded with Safari but not with Exoplayer ,
 i tried latest version of Exoplayer 2.15.0 and it didn't load the stream. here is the url:

https://ss.90minlive.online/live/tv3-l/playlist.m3u8

just open above HLS url with emulator or tv with demo app.

```
  c 31387-31387/com.google.android.exoplayer2.demo E/EventLogger: internalError [1.66, loadError]om.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to
 https://ss.90minlive.online/live/tv3-l/playlist.m3u8
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:195)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
        at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
        at com.android.okhttp.Connection.connect(Connection.java:143)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
        at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:427)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:351)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318)
        at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
        at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:556)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
        at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103) 
        at com.android.okhttp.Connection.connect(Connection.java:143) 
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185) 
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128) 
        at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341) 
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330) 
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114) 
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89) 
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:427) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:351) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318) 
        at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219) 
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115) 
        at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:556) 
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324) 
        at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103) 
        at com.android.okhttp.Connection.connect(Connection.java:143) 
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185) 
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128) 
        at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341) 
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330) 
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114) 
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89) 
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:427) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:351) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 

```

**Comment by ojw28** [comment]
Please see [this troubleshooting entry](https://exoplayer.dev/troubleshooting.html#fixing-sslhandshakeexception-and-certpathvalidatorexception-errors).
