### ISSUE TITLE
unable to play content

### ISSUE THREAD

**Issue by Zoom-Adr** [google/ExoPlayer#9482]
can someone advise why unable to play?
other clearkey works but not this.

thanks in advanced.

       {
          "name": "test",
          "logo_uri": "https://ignore.me",
          "uri": "https://linear01-playback.sooka.my/CH3/masterCH3.mpd",
          "drm_scheme": "clearkey", 
          "drm_license_url": "https://run.mocky.io/v3/194563d2-e077-4816-9b0a-d2743f76e256"
       },

**Comment by krocard** [comment]
Could you please post the exception thrown or describe what the playback issue is? Reproducing every issue takes a lot of time and we can solve issues faster by looking at error logs, thanks.

**Comment by Zoom-Adr** [comment]
hello, unable to play. it shows "media includes audio tracks, but none are playable by this device"..
it works on shaka and jwplayer though..

**Comment by krocard** [comment]
The media audio codec is HE-AAC according to mediainfo. Which you device should be able to decode. It might be a DRM error.  Let me try to reproduce.

<details>
<summary>
`$ mediainfo https://linear01-playback.sooka.my/CH3/masterCH3.mpd`
</summary>

```
General
Complete name                            : https://linear01-playback.sooka.my/CH3/masterCH3.mpd
Format                                   : DASH MPD
File size                                : 10.6 KiB
Overall bit rate mode                    : Variable

Video #1
ID                                       : 1-1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Baseline@L2.1
Format settings                          : 4 Ref Frames
Format settings, CABAC                   : No
Format settings, Reference frames        : 4 frames
Muxing mode                              : dash
Codec ID                                 : encv / avc1
Codec ID/Info                            : Advanced Video Coding
Bit rate mode                            : Variable
Bit rate                                 : 360 kb/s
Width                                    : 480 pixels
Height                                   : 270 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 12.500 FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.222
Title                                    : Video
Encoded date                             : UTC 2021-09-22 21:18:23
Tagged date                              : UTC 2021-09-22 21:18:23
Encryption                               : Encrypted
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Source                                   : 1632345500953item-01item_init.m4i
mdhd_Duration                            : 1844674494988288
Codec configuration box                  : avcC

Video #2
ID                                       : 2-1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Baseline@L2.2
Format settings                          : 4 Ref Frames
Format settings, CABAC                   : No
Format settings, Reference frames        : 4 frames
Muxing mode                              : dash
Codec ID                                 : encv / avc1
Codec ID/Info                            : Advanced Video Coding
Bit rate mode                            : Variable
Bit rate                                 : 600 kb/s
Width                                    : 480 pixels
Height                                   : 270 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.185
Title                                    : Video
Encoded date                             : UTC 2021-09-22 21:18:23
Tagged date                              : UTC 2021-09-22 21:18:23
Encryption                               : Encrypted
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Source                                   : 1632345500953item-02item_init.m4i
mdhd_Duration                            : 1844674494988288
Codec configuration box                  : avcC

Video #3
ID                                       : 3-1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.2
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Muxing mode                              : dash
Codec ID                                 : encv / avc1
Codec ID/Info                            : Advanced Video Coding
Bit rate mode                            : Variable
Bit rate                                 : 800 kb/s
Width                                    : 640 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.104
Title                                    : Video
Encoded date                             : UTC 2021-09-22 21:18:23
Tagged date                              : UTC 2021-09-22 21:18:23
Encryption                               : Encrypted
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Source                                   : 1632345500953item-03item_init.m4i
mdhd_Duration                            : 1844674494988288
Codec configuration box                  : avcC

Video #4
ID                                       : 4-1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Muxing mode                              : dash
Codec ID                                 : encv / avc1
Codec ID/Info                            : Advanced Video Coding
Bit rate mode                            : Variable
Bit rate                                 : 960 kb/s
Width                                    : 960 pixels
Height                                   : 540 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.074
Title                                    : Video
Encoded date                             : UTC 2021-09-22 21:18:23
Tagged date                              : UTC 2021-09-22 21:18:23
Encryption                               : Encrypted
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Source                                   : 1632345500953item-04item_init.m4i
mdhd_Duration                            : 1844674494988288
Codec configuration box                  : avcC

Video #5
ID                                       : 5-1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Muxing mode                              : dash
Codec ID                                 : encv / avc1
Codec ID/Info                            : Advanced Video Coding
Bit rate mode                            : Variable
Bit rate                                 : 1 500 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.065
Title                                    : Video
Encoded date                             : UTC 2021-09-22 21:18:23
Tagged date                              : UTC 2021-09-22 21:18:23
Encryption                               : Encrypted
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Source                                   : 1632345500953item-05item_init.m4i
mdhd_Duration                            : 1844674494988288
Codec configuration box                  : avcC

Audio #1
ID                                       : 6-1
Format                                   : AAC LC SBR
Format/Info                              : Advanced Audio Codec Low Complexity with Spectral Band Replication
Commercial name                          : HE-AAC
Format settings                          : NBC
Muxing mode                              : dash
Codec ID                                 : enca-40-5
Bit rate mode                            : Constant
Bit rate                                 : 39.0 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 23.438 FPS (2048 SPF)
Compression mode                         : Lossy
Title                                    : Sound
Language                                 : Malay
Encoded date                             : UTC 2021-09-22 21:18:23
Tagged date                              : UTC 2021-09-22 21:18:23
Encryption                               : Encrypted
Source                                   : 1632345500953item-06item_init.m4i
mdhd_Duration                            : 1844674494988288

Audio #2
ID                                       : 7-1
Format                                   : AAC LC SBR
Format/Info                              : Advanced Audio Codec Low Complexity with Spectral Band Replication
Commercial name                          : HE-AAC
Format settings                          : NBC
Muxing mode                              : dash
Codec ID                                 : enca-40-5
Bit rate mode                            : Constant
Bit rate                                 : 39.0 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 23.438 FPS (2048 SPF)
Compression mode                         : Lossy
Title                                    : Sound
Language                                 : Multiple languages
Encoded date                             : UTC 2021-09-22 21:18:23
Tagged date                              : UTC 2021-09-22 21:18:23
Encryption                               : Encrypted
Source                                   : 1632345500953item-07item_init.m4i
mdhd_Duration                            : 1844674494988288

```

</details>

**Comment by Zoom-Adr** [comment]
i'm trying to play in exoplayer demo. let me know if there is another way to play in exoplayer.
thanks for your help

**Comment by krocard** [comment]
Could you post the log of exoplayer demo app? That should tell us why the tracks can't be played.

**Comment by Zoom-Adr** [comment]
how do i get the log from the app?

**Comment by krocard** [comment]
Look at the "Run" tab.
![image](https://user-images.githubusercontent.com/6862950/135309105-2803573f-9fbb-4aa4-aded-36769678dcd5.png)

I just tried and immediately got an error:
~~~
E/DashMediaSource: Failed to resolve time offset.
      androidx.media3.common.upstream.HttpDataSource$CleartextNotPermittedException: Cleartext HTTP traffic not permitted. See https://exoplayer.dev/issues/cleartext-not-permitted
        at androidx.media3.datasource.cronet.CronetDataSource.open(CronetDataSource.java:665)
        at androidx.media3.exoplayer.upstream.DefaultDataSource.open(DefaultDataSource.java:265)
        at androidx.media3.exoplayer.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:778)
        at androidx.media3.exoplayer.upstream.cache.CacheDataSource.open(CacheDataSource.java:591)
        at androidx.media3.exoplayer.upstream.StatsDataSource.open(StatsDataSource.java:89)
        at androidx.media3.exoplayer.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:103)
        at androidx.media3.exoplayer.upstream.DataSourceInputStream.open(DataSourceInputStream.java:66)
        at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:178)
        at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:411)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: es: Exception in CronetUrlRequest: net::ERR_CLEARTEXT_NOT_PERMITTED, ErrorCode=11, InternalErrorCode=-29, Retryable=false
        at org.chromium.net.impl.CronetUrlRequest.onError(:com.google.android.gms.dynamite_cronetdynamite@213614097@21.36.14 (150400-0):4)
~~~

The linked url https://exoplayer.dev/issues/cleartext-not-permitted which explains that http (not https) requests are not allowed for cleartext.
Looking into `https://linear01-playback.sooka.my/CH3/masterCH3.mpd`:
~~~ xml
	<UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-iso:2014" value="http://time.akamai.com/?iso" />
~~~
the url is http, not https.

Replacing http://time.akamai.com by https://time.akamai.com prevents the error, but playback _still_ fail as clearkey still consider the DRM unsupported.

@AquilesCanta could you look into why the clearkey DRM consider the track unsupported?

**Comment by ojw28** [comment]
This is probably something for @icbaker

**Comment by icbaker** [comment]
ExoPlayer doesn't think your stream contains clearkey information (note how the `drm` property only lists `widevine`):

```
tracks [eventTime=1.04, mediaPos=35.98, window=0, period=0
  MediaCodecVideoRenderer [
    Group:0, adaptive_supported=YES [
      [ ] Track:0, id=1632345500953item-01item, mimeType=video/avc, bitrate=360000, codecs=avc1.428015, drm=[widevine], res=480x270, fps=12.5, supported=NO_UNSUPPORTED_DRM
      [ ] Track:1, id=1632345500953item-02item, mimeType=video/avc, bitrate=600000, codecs=avc1.428016, drm=[widevine], res=480x270, fps=25.0, supported=NO_UNSUPPORTED_DRM
      [ ] Track:2, id=1632345500953item-03item, mimeType=video/avc, bitrate=800000, codecs=avc1.4d4020, drm=[widevine], res=640x480, fps=25.0, supported=NO_UNSUPPORTED_DRM
      [ ] Track:3, id=1632345500953item-04item, mimeType=video/avc, bitrate=960000, codecs=avc1.4d4029, drm=[widevine], res=960x540, fps=25.0, supported=NO_UNSUPPORTED_DRM
      [ ] Track:4, id=1632345500953item-05item, mimeType=video/avc, bitrate=1500000, codecs=avc1.640029, drm=[widevine], res=1280x720, fps=25.0, supported=NO_UNSUPPORTED_DRM
    ]
  ]
  MediaCodecAudioRenderer [
    Group:0, adaptive_supported=N/A [
      [ ] Track:0, id=1632345500953item-06item, mimeType=audio/mp4a-latm, bitrate=39000, codecs=mp4a.40.5, drm=[widevine], sample_rate=48000, language=ms, supported=NO_UNSUPPORTED_DRM
    ]
    Group:1, adaptive_supported=N/A [
      [ ] Track:0, id=1632345500953item-07item, mimeType=audio/mp4a-latm, bitrate=39000, codecs=mp4a.40.5, drm=[widevine], sample_rate=48000, language=mul, supported=NO_UNSUPPORTED_DRM
    ]
  ]
  TextRenderer []
  MetadataRenderer []
  CameraMotionRenderer []
]
```

Looking in your DASH manifest this is likely because you only list the widevine UUID (`edef8ba9-79d6-4ace-a3c8-27dcd51d21ed`) in your `ContentProtection` nodes. From the [DASH-IF spec](https://dashif-documents.azurewebsites.net/Guidelines-Security/master/Guidelines-Security.html#CPS-AdditionalConstraints-W3C):
> A DRM system specific ContentProtection descriptor for Clear Key SHALL use the system ID e2719d58-a985-b3c9-781a-b030af78d30e and value="ClearKey1.0".

**Comment by Zoom-Adr** [comment]
Hello,

So do I need to replace the KID in the json with the following?  How do i add the value=ClearKey1. 0" in the json or exolist?


system ID e2719d58-a985-b3c9-781a-b030af78d30e and value="ClearKey1.0"


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by icbaker** [comment]
I'm afraid preparing valid media is out of scope for this issue tracker.
