### ISSUE TITLE
Getting com.google.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException while downloading DRM enabled video url

### ISSUE THREAD

**Issue by neeluagrawal04** [google/ExoPlayer#9491]
Hi I am facing the below exception while download the DRM enabled video url via exoplayer lib
exception:

~~~
com.google.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:134 in java.io.InputStreamReader@9a2c689) 
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:108)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:63)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:179)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:87)
        at com.google.android.exoplayer2.offline.SegmentDownloader$1.doWork(SegmentDownloader.java:313)
        at com.google.android.exoplayer2.offline.SegmentDownloader$1.doWork(SegmentDownloader.java:310)
        at com.google.android.exoplayer2.util.RunnableFutureTask.run(RunnableFutureTask.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:134 in java.io.InputStreamReader@9a2c689) 
        at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1220)
        at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1402)
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:393)
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:101)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:63) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:179) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:87) 
        at com.google.android.exoplayer2.offline.SegmentDownloader$1.doWork(SegmentDownloader.java:313) 
        at com.google.android.exoplayer2.offline.SegmentDownloader$1.doWork(SegmentDownloader.java:310) 
        at com.google.android.exoplayer2.util.RunnableFutureTask.run(RunnableFutureTask.java:125) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 
~~~

Can anyone help me to get out of this issue?

**Comment by krocard** [comment]
The exception points to your dash manifest missing a closing tag (`unterminated entity ref`). Could you please send us the dash manifest that is causing the issue?

If you're unable to share test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by krocard** [comment]
Does this media plays with other dash players?

**Comment by neeluagrawal04** [comment]
Playing is not the issue but during download it will give me this exception. And how to find this dash manifest?

**Comment by krocard** [comment]
You are probably playing the media from an http(s) url. This url points to the dash manifest. Please share this url with us.

**Comment by neeluagrawal04** [comment]
Thanks for your help. Issue is fixed hence closing this issue
