### ISSUE TITLE
DefaultAudioSink exception when playing in tunneling mode

### ISSUE THREAD

**Issue by maciejbarszcz** [google/ExoPlayer#9501]
Use case:
- there is an ongoing playback, with no tunneling for the current MediaSource
- then we ask ExoPlayer to load and play (with no call to pause or stop current playback) new MediaSource which eventually will be played in tunneling mode
- there is an IllegalStateException thrown by DefaultAudioSink

If the second MediaSource is not setup to be played in tunneling mode, no exception is thrown.

```
E/ExoPlayerImplInternal: Playback error
  com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:608)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
 Caused by: java.lang.IllegalStateException
	at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:84)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.writeBuffer(DefaultAudioSink.java:943)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.processBuffers(DefaultAudioSink.java:883)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.drainToEndOfStream(DefaultAudioSink.java:1043)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:787)
	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:639)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1898)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:823)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
	at android.os.Handler.dispatchMessage(Handler.java:103) 
	at android.os.Looper.loop(Looper.java:214) 
	at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by krocard** [comment]
Could you please attach a bug report? Without it it is very hard to know the context of the issue.

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

@tonihei I'm not sure which line failed as the exoplayer version is not prsent in the bug. The following line could have caused the error: `Assertions.checkState(avSyncPresentationTimeUs != C.TIME_UNSET)`.
