### ISSUE TITLE
I am not able to play .mkv url in exoplayer version 2.15.1

### ISSUE THREAD

**Issue by NavdeepParasTech** [google/ExoPlayer#9530]
I tried it in demo APP, I have 2 url with same extensions, 
one is http://iptvfeed.com:80/movie/afXVkRKd8kGL/JpfcgLtZndnW/36169.mkv  which play well but it shows me error "Media includes audio tracks, but none are playable by this device".

Log for 1st url:
-------------------------
2021-10-05 10:57:05.552 24820-3473/com.google.android.exoplayer2.demo E/MediaStatisticsData: not supported vendor: mtk

2nd url is http://iptvfeed.com:80/movie/afXVkRKd8kGL/JpfcgLtZndnW/36176.mkv which is not played.

Log for 2nd url:
-------------------------
2021-10-05 10:59:07.197 24820-3827/com.google.android.exoplayer2.demo E/MediaStatisticsData: not supported vendor: mtk
2021-10-05 10:59:09.372 24820-3828/com.google.android.exoplayer2.demo E/ACodec: [OMX.MTK.VIDEO.DECODER.HEVC] ERROR(0x80001005)
2021-10-05 10:59:09.372 24820-3828/com.google.android.exoplayer2.demo E/ACodec: signalError(omxError 0x80001005, internalError -2147483648)
2021-10-05 10:59:09.372 24820-3827/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported err 0x80001005, actionCode 0, while in state 6
2021-10-05 10:59:09.384 24820-3819/com.google.android.exoplayer2.demo E/MediaCodecVideoRenderer: Video codec error
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:105)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1823)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:823)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-10-05 10:59:09.391 24820-3819/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/hevc, hvc1.2.4.H153.90, -1, en, [3840, 1600, -1.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:558)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MTK.VIDEO.DECODER.HEVC
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1410)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:105)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1823)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:823)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2021-10-05 10:59:09.394 24820-3819/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2298)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:165)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:895)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:888)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:741)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:483)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:178)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1642)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1384)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1347)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:574)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-10-05 10:59:09.405 24820-24820/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=5.85, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_DECODING_FAILED
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/hevc, hvc1.2.4.H153.90, -1, en, [3840, 1600, -1.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:558)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MTK.VIDEO.DECODER.HEVC
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1410)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:105)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1823)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:823)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    ]
2021-10-05 10:59:09.407 24820-3828/com.google.android.exoplayer2.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x79b5c74180
2021-10-05 10:59:09.409 24820-3828/com.google.android.exoplayer2.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x79b5c74260

**Comment by andrewlewis** [comment]
For "Media includes audio tracks, but none are playable by this device", please take a look at the logging output by the demo app, and in particular the part showing tracks and `MediaCodecAudioRenderer` like the logcat snippet [here](https://github.com/google/ExoPlayer/issues/9482#issuecomment-930351714). That should show what codec is needed and not present on the device. The snippet of logging pasted here is not relevant.

For the second error, please capture a bug report via `adb bugreport` just after reproducing the issue. You can attach it here or email it to dev.exoplayer@gmail.com with subject "Issue #9530" (and update this issue to indicate you've done this).

**Comment by arunkumartdr** [comment]
Try settiing Mimetype like this : ```  .setMimeType(MimeTypes.APPLICATION_M3U8)``` to your media item change mime type like m3u8,dash,mp4 etc.......

**Comment by NavdeepParasTech** [comment]
Hii @andrewlewis,

- For "Media includes audio tracks, but none are playable by this device" i have checked the logging output :

2021-10-06 10:50:43.235 4260-19899/com.google.android.exoplayer2.demo D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.640033, video/avc] [OMX.SEC.avc.sw.dec, video/avc] [a12, SM-A125F, samsung, 30]
2021-10-06 10:50:43.236 4260-4260/com.google.android.exoplayer2.demo D/EventLogger: tracks [eventTime=3.42, mediaPos=0.00, window=0, period=0
2021-10-06 10:50:43.236 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:   MediaCodecVideoRenderer [
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=1, mimeType=video/avc, codecs=avc1.640033, res=3840x1632, language=und, supported=NO_EXCEEDS_CAPABILITIES
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:     ]
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:   ]
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:   MediaCodecAudioRenderer [
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:0, id=2, mimeType=audio/true-hd, channels=8, sample_rate=48000, language=hi, supported=NO_UNSUPPORTED_TYPE
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:     ]
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:   ]
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:   TextRenderer [
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=3, mimeType=application/pgs, language=en, supported=YES
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:     ]
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:   ]
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:   MetadataRenderer []
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger:   CameraMotionRenderer []
2021-10-06 10:50:43.237 4260-4260/com.google.android.exoplayer2.demo D/EventLogger: ]
2021-10-06 10:50:43.239 4260-19899/com.google.android.exoplayer2.demo I/ACodec:  [] Now uninitialized
2021-10-06 10:50:43.241 4260-19908/com.google.android.exoplayer2.demo I/ACodec: [] onAllocateComponent
2021-10-06 10:50:43.245 4260-19908/com.google.android.exoplayer2.demo I/OMXClient: IOmx service obtained
2021-10-06 10:50:43.252 4260-19908/com.google.android.exoplayer2.demo I/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Now Loaded

**- For second error I have sent bug report in your email.**

**Comment by andrewlewis** [comment]
For the first issue, there is no renderer that can handle `audio/true-hd`. You could look into the ffmpeg audio renderer extension as an option for this, or connect an A/V receiver.

For the second issue, the situation is similar except that in this case it looks like the H.265/HEVC decoder can't handle the resolution/profile of the media you are passing to it:

```
10-06 10:27:39.146  1046   842 13804 E VDO_LOG : [Err] 3840x1600 isn't in spec
10-06 10:27:39.147  1046   842 13804 E VDO_LOG : [Err, h265_dec_init] Fail to open Vdec Drv H265 instance! -99
10-06 10:27:39.147  1046   842 13804 E VDO_LOG : [Err, h265_dec_init] Resolution over HW SPEC
10-06 10:27:39.147  1046   842 13804 E VDO_LOG : [Err] Error code 4
```

Indeed the device doesn't report support for this format but ExoPlayer tries to use the decoder anyway even though it exceeds capabilities:

```
10-06 10:27:39.033 10327  4260 13789 D MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.H153.90, video/hevc] [OMX.MTK.VIDEO.DECODER.HEVC, video/hevc] [a12, SM-A125F, samsung, 30]
```

The solution to both issues is to prepare the input media in a format that is supported by the device. You can see a summary of supported formats [here](https://developer.android.com/guide/topics/media/media-formats) or [look in the CDD for details](https://source.android.com/compatibility/cdd).
