### ISSUE TITLE
Skipping atom with length > 2147483647 (unsupported).

### ISSUE THREAD

**Issue by lambo81** [google/ExoPlayer#9538]
Using 2.15.1.  I am serving mpd and media files via AWS Cloudfront:

```
<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" type="static" minBufferTime="PT30S" profiles="urn:mpeg:dash:profile:isoff-main:2011" mediaPresentationDuration="PT18M42.721S">
  <Period start="PT0S" duration="PT18M42.721S" id="1">
    <AdaptationSet mimeType="video/mp4" frameRate="30000/1001" segmentAlignment="true" subsegmentAlignment="true" startWithSAP="1" subsegmentStartsWithSAP="1" bitstreamSwitching="false">
      <Representation id="1" width="1920" height="1080" bandwidth="8500000" codecs="avc1.640028">
        <BaseURL>balance-and-strength_1080.mp4</BaseURL>
        <SegmentBase indexRange="759-5286">
          <Initialization range="0-758"/>
        </SegmentBase>
      </Representation>
      <Representation id="2" width="1280" height="720" bandwidth="6500000" codecs="avc1.640028">
        <BaseURL>balance-and-strength_720.mp4</BaseURL>
        <SegmentBase indexRange="757-5284">
          <Initialization range="0-756"/>
        </SegmentBase>
      </Representation>
      <Representation id="3" width="960" height="540" bandwidth="3500000" codecs="avc1.640028">
        <BaseURL>balance-and-strength_540.mp4</BaseURL>
        <SegmentBase indexRange="757-5284">
          <Initialization range="0-756"/>
        </SegmentBase>
      </Representation>
      <Representation id="4" width="640" height="360" bandwidth="1200000" codecs="avc1.4d401f">
        <BaseURL>balance-and-strength_360.mp4</BaseURL>
        <SegmentBase indexRange="751-5278">
          <Initialization range="0-750"/>
        </SegmentBase>
      </Representation>
      <Representation id="5" width="640" height="360" bandwidth="600000" codecs="avc1.4d401f">
        <BaseURL>balance-and-strength_360_low.mp4</BaseURL>
        <SegmentBase indexRange="751-5278">
          <Initialization range="0-750"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
    <AdaptationSet mimeType="audio/mp4" lang="eng" segmentAlignment="0">
      <Representation id="6" bandwidth="96000" audioSamplingRate="48000" codecs="mp4a.40.5">
        <BaseURL>balance-and-strength_96kbps.mp4</BaseURL>
        <SegmentBase indexRange="661-5188">
          <Initialization range="0-660"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
    <AdaptationSet mimeType="audio/mp4" lang="eng" segmentAlignment="0">
      <Representation id="7" bandwidth="64000" audioSamplingRate="48000" codecs="mp4a.40.5">
        <BaseURL>balance-and-strength_64kbps.mp4</BaseURL>
        <SegmentBase indexRange="661-5188">
          <Initialization range="0-660"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

A few seconds into the video, **public void onPlayerError(PlaybackException error)**, is triggered and the player goes to a Player.STATE_IDLE state.  I print out the exception stacktrace:

```
    com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:624)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:594)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     **Caused by: com.google.android.exoplayer2.ParserException: Skipping atom with length > 2147483647 (unsupported).**
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomHeader(FragmentedMp4Extractor.java:437)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:328)
        at com.google.android.exoplayer2.source.chunk.BundledChunkExtractor.read(BundledChunkExtractor.java:153)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:127)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

What does this mean?  What is this talking about?
I could be wrong, but I did some digging--does this have something to do with chunks size?  Is that related to GOP settings?

This is happening with my 1920x1080 video only.  These are my GOP settings set by some defaults in MediaConvert:

GOP size: 90
Unit: FRAMES
B frames between reference frames: 1
Closed GOP Cadence: 1
Number of reference frames: 3
Dynaic sub-GOP: Default?
Repeat PPS: Disabled
GOP reference B-frame: Disabled
Scene change detection: ENABLED
Min I-Interval: 0

**Comment by andrewlewis** [comment]
It looks like the media segment is not valid (or at least, not what `FragmentedMp4Extractor` is expecting to read). Specifically, at the point of reading an MP4 atom length from it read a number that is an excessively large number of bytes, which probably means it's reading garbage data.

I'd first check the code that's producing the media segments is set up correctly and check if there are any known issues with its MP4 output. To dig into the problem further I'd first figure out which media segment is being loaded then log the atom headers as they are being read in the `FragmentedMp4Extractor`. This will let you identify where in the MP4 structure the unexpected value is being read.

**Comment by lambo81** [comment]
The media segments are created by AWS MediaConvert using the built in preset for 1920x1080 dash video.  I didn't find any bugs about their system although their may be.

I don't know how to figure out which media segment is being loaded, I assume there is a way to do this with ExoPlayer?  But even if I found out which segment, the real issue is a problem with conversion, right?
