### ISSUE TITLE
Video playback stops with error with Audio Codec Error after changing Audio track.

### ISSUE THREAD

**Issue by ominfowave** [google/ExoPlayer#9542]
I'm getting the following error log when I change to audio track from default, the other audio plays for 1-2 seconds, and then video and audio both stop. This is specifically happening in Android 11 devices. The same video is working fine in Android 9.

--------------------------
Error log:
2021-10-07 17:20:39.176 6449-7372 E/MediaCodecAudioRenderer: Audio codec error
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_queueInputBuffer(Native Method)
        at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2559)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueInputBuffer(SynchronousMediaCodecAdapter.java:142)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1370)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:825)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:236)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-10-07 17:20:39.179 6449-7372 E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(4, null, null, audio/mpeg, null, -1, ar, [-1, -1, -1.0], [1, 24000]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:558)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:236)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecDecoderException: Decoder failed: c2.android.mp3.decoder
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.createDecoderException(MediaCodecRenderer.java:963)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_queueInputBuffer(Native Method)
        at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2559)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueInputBuffer(SynchronousMediaCodecAdapter.java:142)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1370)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:825)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2021-10-07 17:20:39.190 6449-7372 E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2298)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:165)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:895)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:888)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:741)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onDisabled(MediaCodecAudioRenderer.java:539)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:178)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1635)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1377)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1340)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:574)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:236)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-10-07 17:20:39.217 6449-6449 D/Demo: Exoplayer onPlayerErrorChanged: MediaCodecAudioRenderer error, index=1, format=Format(4, null, null, audio/mpeg, null, -1, ar, [-1, -1, -1.0], [1, 24000]), format_supported=YES :::: com.google.android.exoplayer2.mediacodec.MediaCodecDecoderException: Decoder failed: c2.android.mp3.decoder
2021-10-07 17:20:39.217 6449-6449 W/System.err: com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(4, null, null, audio/mpeg, null, -1, ar, [-1, -1, -1.0], [1, 24000]), format_supported=YES
2021-10-07 17:20:39.217 6449-6449 W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:558)
2021-10-07 17:20:39.217 6449-6449 W/System.err: Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecDecoderException: Decoder failed: c2.android.mp3.decoder
2021-10-07 17:20:39.217 6449-6449 W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.createDecoderException(MediaCodecRenderer.java:963)
2021-10-07 17:20:39.217 6449-6449 W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
2021-10-07 17:20:39.217 6449-6449 W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
2021-10-07 17:20:39.217 6449-6449 W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
2021-10-07 17:20:39.218 6449-6449 W/System.err:     at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueInputBuffer(SynchronousMediaCodecAdapter.java:142)
2021-10-07 17:20:39.218 6449-6449 W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1370)
2021-10-07 17:20:39.218 6449-6449 W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:825)
2021-10-07 17:20:39.219 6449-6449 D/Demo: Exoplayer onPlayerError: MediaCodecAudioRenderer error, index=1, format=Format(4, null, null, audio/mpeg, null, -1, ar, [-1, -1, -1.0], [1, 24000]), format_supported=YES :::: com.google.android.exoplayer2.mediacodec.MediaCodecDecoderException: Decoder failed: c2.android.mp3.decoder
2021-10-07 17:20:39.219 6449-6449 W/System.err: com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(4, null, null, audio/mpeg, null, -1, ar, [-1, -1, -1.0], [1, 24000]), format_supported=YES
2021-10-07 17:20:39.219 6449-6449 W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:558)
2021-10-07 17:20:39.219 6449-6449 W/System.err: Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecDecoderException: Decoder failed: c2.android.mp3.decoder
2021-10-07 17:20:39.219 6449-6449 W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.createDecoderException(MediaCodecRenderer.java:963)
2021-10-07 17:20:39.219 6449-6449 W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
2021-10-07 17:20:39.219 6449-6449 W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
2021-10-07 17:20:39.219 6449-6449 W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
2021-10-07 17:20:39.219 6449-6449 W/System.err:     at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueInputBuffer(SynchronousMediaCodecAdapter.java:142)
2021-10-07 17:20:39.220 6449-6449 W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1370)
2021-10-07 17:20:39.220 6449-6449 W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:825)

-----------------------------------
- ExoPlayer version number:
   implementation 'com.google.android.exoplayer:exoplayer-core:2.15.1'
   implementation 'com.google.android.exoplayer:exoplayer-dash:2.15.1'
   implementation 'com.google.android.exoplayer:exoplayer-ui:2.15.1'

- Android version: 11
- Android device: Redmi Note 9Pro, Vivo

Note: Different audio tracks and subtitles are added in the Video file using FFMPEG, the audio track length might be different thn the Video itself but the playback is stoped and getting errors before completion of audio or video.

**Comment by andrewlewis** [comment]
Please could you provide the output of `adb bugreport` taken just after reproducing the error? You can attach it here or email it to dev.exoplayer@gmail.com with subject "Issue #9530" (and update this issue to indicate you've done this). The MP3 decoder is failing (`Decoder failed: c2.android.mp3.decoder`) and there's likely to be more diagnostic information logged just before the error.

**Comment by wangxuan217** [comment]
From the log, it doesn't seem to be the problem of exo. It seems to be the lack of decoder. Is the media resource played by the developer MPEG2?

**Comment by ominfowave** [comment]
> From the log, it doesn't seem to be the problem of exo. It seems to be the lack of decoder. Is the media resource played by the developer MPEG2?

I think you are right, the problem was with how we were adding audio tracks in video using FFMPEG, we were copying audio codecs of source video files to add new audio tracks that caused the issue somehow.
