### ISSUE TITLE
DRM gives me an exception when I call downloadLicense, how to request keySetId ?

### ISSUE THREAD

**Issue by billyjoker** [google/ExoPlayer#9548]
Hi I was updated to Exoplayer 2.14 recently but I have problems with the update of the downloadLicense request, it throws me an exception:

```
2021-10-08 13:14:28.175 3568-6530/? E/DefaultDrmSession: DRM session error
      com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:194)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:153)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:603)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:383)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:81)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:75)
        at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:170)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:177)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:153) 
        at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:603) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

The problem was obtaining the keySetId, my code:

```
    public void downloadDrmLicense(HttpDataSource.Factory httpDataSourceFactory,
                                   Uri uri,
                                   String licenseUrl,
                                   DrmLicenseListener licenseListener) {
        try {
            DataSource dataSource = httpDataSourceFactory.createDataSource();
            mOfflineLicenseHelper =
                    OfflineLicenseHelper.newWidevineInstance(licenseUrl, true,
                            httpDataSourceFactory, new DrmSessionEventListener.EventDispatcher());
            byte[] keySetId = null;
            try {
                DashManifest dashManifest = DashUtil.loadManifest(dataSource, uri);

                Format formatSimple = DashUtil.loadFormatWithDrmInitData(dataSource, dashManifest.getPeriod(0));

                if (formatSimple != null) {
                    keySetId = mOfflineLicenseHelper.downloadLicense(formatSimple);
                }

            } catch (IllegalArgumentException | IOException e) {
                Log.e(TAG, "DrmInitDataTask Exception");
            } finally {
                if (keySetId == null) {
                    Log.e(TAG, "[LICENSE] Unable to retrieve license");
                    licenseListener.get(null, 0L);
                } else {
                    Log.d(TAG, "[LICENSE] License downloaded successfully");
                    licenseListener.get(keySetId, getLicenseDurationRemainingMillis(keySetId));
                }
                mOfflineLicenseHelper.release();
            }

        } catch (Exception e) {
            Log.e(TAG, e.getMessage(), e);
        }
    }
```

I get the formatSimple properly, but when call `downloadLicense`, if I debug I see a point inside the `blockingKeyRequest` method that does 

`byte[] keySetId = drmSession.getOfflineLicenseKeySetId();`

and it returns a null

With my old code working with exoplayer 2.11 was working fine, but when I did the refactor to this one, it fails.

**Comment by icbaker** [comment]
The HTTP 500 error in the stack trace is coming from your DRM license server - you should look in the server logs to understand the cause of that.

**Comment by billyjoker** [comment]
Finally I have figured out that the problem was a bad international ip detecting from our backservers. Solved
