### ISSUE TITLE
Exoplayer Version 2.15.1 HLS media format.. getting crash with few title. The error log is mentioned below.

### ISSUE THREAD

**Issue by tapow** [google/ExoPlayer#9571]
**When clicking on title it is playing 1-2 second then after getting crash.**

**But, In the same player few titles is playing. It is very hard to Compile and check this particular issue. Also, when I run the App in debug mode some title playing but later some time or singed build is keep getting crash**

Error Log, which may help:
-------------------------

- The main line of error code:
  com.google.android.exoplayer2.MediaMetadata$Builder.populateFromMetadata(MediaMetadata.java:380)

E/libc: Access denied finding property "vendor.display-size" E/AndroidRuntime: FATAL EXCEPTION: main Process: com.poptv.tvapp, PID: 9605 java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.metadata.Metadata$Entry.populateMediaMetadata(com.google.android.exoplayer2.MediaMetadata$Builder)" at com.google.android.exoplayer2.MediaMetadata$Builder.populateFromMetadata(MediaMetadata.java:380) at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1272) at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1220) at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1$ExoPlayerImpl(ExoPlayerImpl.java:227) at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda16.run(Unknown Source:4) at android.os.Handler.handleCallback(Handler.java:883) at android.os.Handler.dispatchMessage(Handler.java:100) at android.os.Looper.loop(Looper.java:214) at android.app.ActivityThread.main(ActivityThread.java:7356) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) E/EGL_emulation: eglQueryContext 32c0 EGL_BAD_ATTRIBUTE E/EGL_emulation: tid 10026: eglQueryContext(1903): error 0x3004 (EGL_BAD_ATTRIBUTE) E/OMXNodeInstance: getExtensionIndex(0xee218f60:google.h264.decoder, OMX.google.android.index.enableAndroidNativeBuffers) ERROR: UnsupportedIndex(0x8000101a) E/ACodec: [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010 E/OMXNodeInstance: getParameter(0xee218f60:google.h264.decoder, ??(0x6f600011)) ERROR: UnsupportedIndex(0x8000101a) W/OMXNodeInstance: [0xee218f60:google.h264.decoder] component does not support metadata mode; using fallback E/OMXNodeInstance: setConfig(0xee218f60:google.h264.decoder, ConfigPriority(0x6f800002)) ERROR: UnsupportedIndex(0x8000101a) E/OMXNodeInstance: getConfig(0xee218f60:google.h264.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: UnsupportedIndex(0x8000101a) E/OMXNodeInstance: getConfig(0xee218f60:google.h264.decoder, ??(0x7f000003)) ERROR: UnsupportedSetting(0x80001019) E/OMXNodeInstance: getConfig(0xee218f60:google.h264.decoder, ??(0x7f000003)) ERROR: UnsupportedSetting(0x80001019) E/OMXNodeInstance: setConfig(0xec13c420:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001) E/OMXNodeInstance: getConfig(0xec13c420:google.aac.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)

**How to reproduce:**

- It is happening in Android TV platform.
- ExoPlayer version number 2.15.1
- Android version 5.0+

**Comment by tapow** [comment]
Is this codec issue or video Size issue.. What should i try to fix this issue for Android TV App..?

**Comment by tonihei** [comment]
The main error you see is the AbstractMethodError for a recently added method. I assume this is some kind of build issue where the build was created with stale information. I would suggest trying a clean build (including Android Studio's "Clean caches  and restart" option). This usually resolves such issues.

**Comment by tapow** [comment]
@tonihei thanks for your reply. But, some movie are playing but some are doesn't. If it is the build issue then none of the movie should play. Also, I noticed some time play in debug mode but when create signed build the same movie url doesn't play.. This is something not able to find the root cause... We check progaurd and all setting but could not find any issue with that.

**Comment by tonihei** [comment]
This could also be related to using two different versions of ExoPlayer dependencies in your gradle setup. You could display the full dependency tree with `gradlew :app:dependencies` (or similar, depending on your setup) and look for ExoPlayer dependencies with different version numbers.

**Comment by tonihei** [comment]
Closing due to inactivity.

**Comment by ajay9889** [comment]
<img width="922" alt="Screenshot 2021-12-03 at 10 49 58 PM" src="https://user-images.githubusercontent.com/9216373/144695301-097ae1ff-acef-4052-abe8-2715cbbf3abb.png">
<img width="857" alt="Screenshot 2021-12-03 at 10 50 32 PM" src="https://user-images.githubusercontent.com/9216373/144695302-986474bc-2238-4777-8fcc-c52b0c86acc4.png">

All version look like the same 2.15.1 there is not conflict in dependencies. Also, it is happening on Android TV Device. What could be the issue. ?

We have tried another format and test sample HLS &  Dash file as well that also some time play and some become blank screen
