### ISSUE TITLE
ClassNotFoundException in some Samsung and Huawei devices

### ISSUE THREAD

**Issue by renanboni** [google/ExoPlayer#9574]
Hey, I have found a few crashes related to the `MediaPlayerController` class, here's the stacktrace:

**Caused by java.lang.ClassNotFoundException
androidx.media2.session.MediaController$PlaybackInfoParcelizer**
```
Caused by java.lang.ClassNotFoundException: androidx.media2.session.MediaController$PlaybackInfoParcelizer
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:454)
       at androidx.versionedparcelable.VersionedParcel.findParcelClass(VersionedParcel.java:1632)
       at androidx.versionedparcelable.VersionedParcel.writeVersionedParcelableCreator(VersionedParcel.java:1042)
       at androidx.versionedparcelable.VersionedParcel.writeVersionedParcelable(VersionedParcel.java:1032)
       at androidx.versionedparcelable.VersionedParcel.writeVersionedParcelable(VersionedParcel.java:1022)
       at androidx.media2.session.ConnectionResultParcelizer.write(ConnectionResultParcelizer.java:74)
       at java.lang.reflect.Method.invoke(Method.java)
       at androidx.versionedparcelable.VersionedParcel.writeToParcel(VersionedParcel.java:1587)
       at androidx.versionedparcelable.VersionedParcel.writeVersionedParcelable(VersionedParcel.java:1035)
       at androidx.versionedparcelable.ParcelImpl.writeToParcel(ParcelImpl.java:57)
       at androidx.media2.session.IMediaController$Stub$Proxy.onConnected(IMediaController.java:921)
       at androidx.media2.session.MediaSessionStub$2.run(MediaSessionStub.java:380)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Fatal Exception: java.lang.RuntimeException
MediaController$PlaybackInfo does not have a Parcelizer**

```
Fatal Exception: java.lang.RuntimeException: MediaController$PlaybackInfo does not have a Parcelizer
       at androidx.versionedparcelable.VersionedParcel.writeVersionedParcelableCreator(VersionedParcel.java:1044)
       at androidx.versionedparcelable.VersionedParcel.writeVersionedParcelable(VersionedParcel.java:1032)
       at androidx.versionedparcelable.VersionedParcel.writeVersionedParcelable(VersionedParcel.java:1022)
       at androidx.media2.session.ConnectionResultParcelizer.write(ConnectionResultParcelizer.java:74)
       at java.lang.reflect.Method.invoke(Method.java)
       at androidx.versionedparcelable.VersionedParcel.writeToParcel(VersionedParcel.java:1587)
       at androidx.versionedparcelable.VersionedParcel.writeVersionedParcelable(VersionedParcel.java:1035)
       at androidx.versionedparcelable.ParcelImpl.writeToParcel(ParcelImpl.java:57)
       at androidx.media2.session.IMediaController$Stub$Proxy.onConnected(IMediaController.java:921)
       at androidx.media2.session.MediaSessionStub$2.run(MediaSessionStub.java:380)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

Seems to be happening only in Samsung and Huawei devices although I couldn't reproduce it. 

<img width="463" alt="Screenshot 2021-10-18 at 12 27 22" src="https://user-images.githubusercontent.com/12984721/137714117-aa3c56ac-5de7-4d03-81a4-81b6e9dfa11a.png">

**Comment by tonihei** [comment]
Closing because this isn't really an ExoPlayer issue as far as I can see.
