### ISSUE TITLE
why i fail to use ClippingMediaSource to handle the audio file in demo

### ISSUE THREAD

**Issue by weizaishouex2010** [google/ExoPlayer#9580]
I test the exoplayer demo  in playlists in the PlayerActivity. I want clip an audio file from 1s to 8s
I just modify code in the initializePlayer()
audio url is [https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/gear0/fileSequence0.aac](url)
MediaSource audioSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(url);
ClippingMediaSource c_audio = new ClippingMediaSource(audioSource,1_000_000,8_000_000);
player.setMediaSource(c_audio);

why i always get the error msg:
2021-10-19 23:46:24.802 12657-12657/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=1.63, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_FAILED_RUNTIME_CHECK
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:608)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:236)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:84)
        at com.google.android.exoplayer2.source.ClippingMediaPeriod.selectTracks(ClippingMediaPeriod.java:119)
        at com.google.android.exoplayer2.source.MaskingMediaPeriod.selectTracks(MaskingMediaPeriod.java:186)
        at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:296)
        at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:259)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:193)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2209)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:501)

but when I use code below, it works fine, what is the difference?
MediaItem audioMediaItem=
        new MediaItem.Builder().setUri(Uri.parse(url))
            .setClipStartPositionMs(1000)
            .setClipEndPositionMs(8000)
            .build();
player.setMediaItem(audioMediaItem);

**Comment by tonihei** [comment]
`ClippingMediaSource` doesn't support clipping unseekable media files to a non-zero start position. If you just play the file without clipping you can observe that `Player.isCurrentWindowSeekable()` is false, meaning the clipping start of 1 second won't work.

The problem is that the nicely readable `IllegalClippingException` isn't thrown, making it hard to understand the error. I'll mark this as a bug to fix this particular problem.

**Comment by weizaishouex2010** [comment]
> `ClippingMediaSource` doesn't support clipping unseekable media files to a non-zero start position. If you just play the file without clipping you can observe that `Player.isCurrentWindowSeekable()` is false, meaning the clipping start of 1 second won't work.
> 
> The problem is that the nicely readable `IllegalClippingException` isn't thrown, making it hard to understand the error. I'll mark this as a bug to fix this particular problem.

but why the second way works fine?

**Comment by tonihei** [comment]
I used the second way (with `MediaItem`) when testing the file and it didn't work. So I think the problem occurs in both cases.
