### ISSUE TITLE
Getting exception as Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.

### ISSUE THREAD

**Issue by neeluagrawal04** [google/ExoPlayer#9602]
On downloading non-drm enabled videos via using the OkHttpDataSourceFactory and playing the video via DefaultHttpDataSourceFactory i am getting the exception as:-

```
 Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:250)
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:70)
        at com.google.android.exoplayer2.offline.FilteringManifestParser.parse(FilteringManifestParser.java:46)
        at com.google.android.exoplayer2.offline.FilteringManifestParser.parse(FilteringManifestParser.java:30)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:179)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
```

Please let me know what would be the root cause of this issue.

Thanks

**Comment by ojw28** [comment]
Please provide a minimal patch for the demo app that reproduces this problem. It's impossible to provide any guidance from the information provided.

**Comment by neeluagrawal04** [comment]
I am playing a non-drm enabled video via mediaItem then i am getting the above exception
Sharing url on dev.exoplayer@gmail.com

**Comment by ojw28** [comment]
The link provided does not work for me. It shows the following error in a web browser:
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Nov 03 12:05:44 UTC 2021
There was an unexpected error (type=Bad Request, status=400).
Missing request attribute 'X-JWT-Token' of type String
```
Please provide the file somewhere where it's accessible without needing some kind of token (alternatively, provide complete details of what we need to do to access the content).

**Comment by neeluagrawal04** [comment]
Issue is resolve, Thanks for your help. 
Hence closing this issue

**Comment by neeluagrawal04** [comment]
Hi, I am getting this exception when I am re-downloading a non-drm enabled videos via drm enabling configuration. And I am getting the below as the exception: 

DownloadManager: Task failed: application/x-mpegURL:hmedia_url, false
      com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:250)
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:70)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:179)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:87)
        at com.google.android.exoplayer2.offline.SegmentDownloader$1.doWork(SegmentDownloader.java:313)
        at com.google.android.exoplayer2.offline.SegmentDownloader$1.doWork(SegmentDownloader.java:310)
        at com.google.android.exoplayer2.util.RunnableFutureTask.run(RunnableFutureTask.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)

Please help me with this issue. I am sharing media link on email

**Comment by ojw28** [comment]
Please provide a minimal patch for the demo app that reproduces this problem. It's impossible to provide any guidance from the information provided. The media links provided are also not accessible; they both return HTTP 503.
