### ISSUE TITLE
Fallback to L3 incase of DRM errors while downloading content.

### ISSUE THREAD

**Issue by SaurabhOfficial** [google/ExoPlayer#9622]
When filing a question:
-------------------------

<b>Describe your question in detail.</b>

1. Similar to the Issue here : https://github.com/google/ExoPlayer/issues/8108#
Is it possible for us to force the device to use L3 security level using some blackList config, by passing a custom `ExoMediaDrm.Provider`? I saw one secondary constructor in the `OfflineLicenseHelper` Class but it has been deprecated.
2. Is there any other work-around to avoid DRM Issues while downloading content on devices which have their L1 security level revoked?

<b>Error</b> 

com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error

**Comment by icbaker** [comment]
> Similar to the Issue here : [Automatically fallback to Widevine L3 in case there is a DRM error #8108](https://github.com/google/ExoPlayer/issues/8108)
>    Is it possible for us to force the device to use L3 security level using some blackList config, by passing a custom `ExoMediaDrm.Provider`? I saw one secondary constructor in the `OfflineLicenseHelper` Class but it has been deprecated.

You can use the non-deprecated `OfflineLicenseHelper` constructor that takes a `DefaultDrmSessionManager` instance and pass your custom `ExoMediaDrm.Provider` to [`DefaultDrmSessionManager.Builder#setUuidAndExoMediaDrmProvider`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.Builder.html#setUuidAndExoMediaDrmProvider(java.util.UUID,com.google.android.exoplayer2.drm.ExoMediaDrm.Provider)).

**Comment by SaurabhOfficial** [comment]
@icbaker just one more question, is it even possible to successfully download content along with the offline keys using `OfflineLicenseHelper` and then get similar DRM-related Issues while playing the content offline, since the device's L1 security level has been revoked?
Shouldn't the device not be allowed to download the offline keys in the first place, since its L1 security level has been revoked? if possible can you just point me towards the code section I should be looking at?

**Comment by icbaker** [comment]
@rrfrias can you please take a look at this question about the specifics of widevine offline licenses on a device with revoked L1.

**Comment by rrfrias** [comment]
A request to download an offline license from a revoked L1 device will fail. Let us know if you are not seeing this.

**Comment by dino-saurabh** [comment]
Sure I will get back with some log captures if possible.

**Comment by dino-saurabh** [comment]
```
E/ExoPlayerErrorDelegate: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: java.lang.IllegalArgumentException: Failed to restore keys
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:520)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.restoreKeys(DefaultDrmSession.java:446)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:407)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:294)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:776)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:685)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:564)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.access$1600(DefaultDrmSessionManager.java:63)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager$PreacquiredSessionReference.lambda$acquire$0$DefaultDrmSessionManager$PreacquiredSessionReference(DefaultDrmSessionManager.java:972)
        at com.google.android.exoplayer2.drm.-$$Lambda$DefaultDrmSessionManager$PreacquiredSessionReference$rqyTSlYT3rRwS_rvp-1F3CN49xI.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalArgumentException: Failed to restore keys
        at android.media.MediaDrm.restoreKeys(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.restoreKeys(FrameworkMediaDrm.java:262)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.restoreKeys(DefaultDrmSession.java:443)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:407) 
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:294) 
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:776) 
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:685) 
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:564) 
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.access$1600(DefaultDrmSessionManager.java:63) 
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager$PreacquiredSessionReference.lambda$acquire$0$DefaultDrmSessionManager$PreacquiredSessionReference(DefaultDrmSessionManager.java:972) 
        at com.google.android.exoplayer2.drm.-$$Lambda$DefaultDrmSessionManager$PreacquiredSessionReference$rqyTSlYT3rRwS_rvp-1F3CN49xI.run(Unknown Source:4) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.os.HandlerThread.run(HandlerThread.java:67) `
```

^^ @rrfrias this is what I could find, let me know if more logs are needed. cc @vinodkputta @mayurk2

**Comment by dino-saurabh** [comment]
while playing the content without downloading, this error comes up.
```
android.media.MediaCodec$CryptoException: Required output protections are not active
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2699)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:143)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1380)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:845)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

but with forcing widevine level L3, on both scenarios playing without downloading and downloading and playing the content works ( it downloads the lower resolution content and successfully able to play it).

**Comment by rrfrias** [comment]
These seem like two separate issues. Can you send a full bugreport to dev.exoplayer@gmail.com? It might shed some light on what is happening.

> while playing the content without downloading, this error comes up.

I assume you are using the default security level (L1) but since it the device is revoked it ends up with higher resolution content and license policies that L3 cannot fulfill. HDCP and output protections are not supported on L3.

In the earlier case, it might be that the license was downloaded as L3 but it is search for an L1 offline license and cannot find it. Maybe you can tell. More logs will be helpful. 

> but with forcing widevine level L3, on both scenarios playing without downloading and downloading and playing the content works ( it downloads the lower resolution content and successfully able to play it).

This is the right way to handle devices for which L1 has been revoked. If you are part of CWIP, you can contact Widevine for support https://widevine.com/contact and a list of revoked devices.

**Comment by SaurabhOfficial** [comment]
@rrfrias I have shared the bug-report to dev.exoplayer@gmail.com along with device widevine info capture please check.

**Comment by rrfrias** [comment]
The debug logs have only one log TAG. May be you filtered out other logs? Can you share another set of logs?

Also the concern seems to be that you were able to download content before the app detected that the security level for that device was revoked. You can either validate that the device has been revoked or try to acquire a license before downloading content.

**Comment by dino-saurabh** [comment]
> The debug logs have only one log TAG. May be you filtered out other logs? Can you share another set of logs?

@rrfrias I can see the shared logs on the email have different tags, I have shared another set of logs after reproducing the Issue 👍🏼
> 
> Also the concern seems to be that you were able to download content before the app detected that the security level for that device was revoked. You can either validate that the device has been revoked or try to acquire a license before downloading content.

How can we detect if the security level for a device was revoked, is there any way other than actively maintaing a List. since in streaming we can simply fallback to security level L3 in case of playback failure with L1. but with downloads this becomes tricky since we are able to download the content in the first place but not able to play it.

**Comment by rrfrias** [comment]
> but with downloads this becomes tricky since we are able to download the content in the first place but not able to play it.

Try requesting the offline license before downloading the asset. That will let you know if the L1 security level for that device has been revoked. If so fallback to L3 and download L3 asset.

> is there any way other than actively maintaing a List. 

A service side verification of revocation status is recommended over any possible client side checks.
