### ISSUE TITLE
Some videos are not working

### ISSUE THREAD

**Issue by majdalden** [google/ExoPlayer#9631]
Why this video is not working on ExoPlayer?

https://drive.google.com/file/d/1hGHRzfKNQlu1WVVVsDeDk8hD4lEnsExn/view?usp=sharing

but this is working

https://drive.google.com/file/d/1YlAc9LJcCR9U0G-gkE33qgoxeI2VbXZd/view?usp=sharing

This problem happened on google pixel or emulator only but work on normally on Samsung, Xiaomi etc

Could there be a difference between them?

Note: I fetch vides from my apis but now upload to drive

**Comment by icbaker** [comment]
Playing the working video in the demo app I see it only contains a video track and no audio track:
```
tracks [eventTime=0.04, mediaPos=0.00, window=0, period=0
  MediaCodecVideoRenderer [
    Group:0, adaptive_supported=N/A [
      [X] Track:0, id=1, mimeType=video/avc, codecs=avc1.640028, res=1920x1080, fps=23.973726, supported=YES
    ]
  ]
  MediaCodecAudioRenderer []
  TextRenderer []
  MetadataRenderer []
  CameraMotionRenderer []
]
```

Playing the non-working file in the demo app shows it includes both audio and video tracks:
```
tracks [eventTime=0.05, mediaPos=0.00, window=0, period=0
  MediaCodecVideoRenderer [
    Group:0, adaptive_supported=N/A [
      [X] Track:0, id=1, mimeType=video/avc, codecs=avc1.640028, res=1920x1080, fps=23.976023, supported=YES
    ]
  ]
  MediaCodecAudioRenderer [
    Group:0, adaptive_supported=N/A [
      [X] Track:0, id=2, mimeType=audio/mpeg, channels=2, sample_rate=48000, language=ar, supported=YES
    ]
    Metadata [
      TSSE: description=null: value=Lavf58.29.100
    ]
  ]
  TextRenderer []
  MetadataRenderer []
  CameraMotionRenderer []
]
```

I see the following error when playing this file in version 2.15.1 of the ExoPlayer demo app on a Pixel 5:

```
2021-11-01 14:44:47.050 1457-21457/? E/C2SoftMp3Dec: mp3 decoder returned error 1
2021-11-01 14:44:47.051 21294-21456/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.android.mp3.decoder#354] work failed to complete: 14
2021-11-01 14:44:47.051 21294-21456/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.android.mp3.decoder#354] work failed to complete: 22
2021-11-01 14:44:47.051 21294-21456/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported err 0xe, actionCode 0, while in state 6/STARTED
2021-11-01 14:44:47.051 21294-21456/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported err 0x16, actionCode 0, while in state 0/UNINITIALIZED
2021-11-01 14:44:47.051 21294-21456/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.android.mp3.decoder#354] work failed to complete: 22
2021-11-01 14:44:47.051 21294-21456/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported err 0x16, actionCode 0, while in state 0/UNINITIALIZED
2021-11-01 14:44:47.053 21294-21444/com.google.android.exoplayer2.demo E/MediaCodecAudioRenderer: Audio codec error
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2937)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:98)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1199)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:825)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

The error indicates that the device's MP3 decoder doesn't think the MP3 content is valid.

I tried 2 things:
1. Disable the audio track in ExoPlayer -> the file plays fine
2. Play the file in VLC on MacOS -> the file plays, but with no audible audio

Given that neither VLC nor the AOSP mp3 decoder can play the audio of this file it seems very likely that the file does not contain valid MP3 data.

The file that does work contains no audio data, and so obviously doesn't trigger any audio-related errors.

I recommend either fixing the audio track encoding, or re-muxing the file to remove the invalid audio track.

**Comment by majdalden** [comment]
But all the videos are without sound
The sound doesn't important too much

how to disable the audio track in ExoPlayer?

**Comment by icbaker** [comment]
You can do so by customising the `TrackSelectionParameters`: https://exoplayer.dev/track-selection.html

Specifically, you can find the index of the audio renderer by looping through calls to [`ExoPlayer#getRendererType`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlayer.html#getRendererType(int)) from 0 to [`ExoPlayer#getRendererCount`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlayer.html#getRendererCount()), looking for one with [`C.TRACK_TYPE_AUDIO`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/C.html#TRACK_TYPE_AUDIO).

Then you can pass that `audioRendererIndex` to [`DefaultTrackSelector#ParametersBuilder#setRendererDisabled`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.ParametersBuilder.html#setRendererDisabled(int,boolean)).

**Comment by icbaker** [comment]
If you don't want sound in any of these videos it seems preferable to re-mux them and remove the invalid audio track completely.
