### ISSUE TITLE
Bug on Fast forward and seeking to the specific position of encrypted video

### ISSUE THREAD

**Issue by MohsenNaderzadeh** [google/ExoPlayer#9633]
Hi guys, I'm using the ExoPlayer library for playing an encrypted video by AES Algorithm and CRT mode.
I Implemented a new custom ExoPlayer DataSource for playing that. Everything is ok, but in some videos when we change the seek bar position very fast, sometimes video playing gets paused and this Exception is thrown but there is no application crash.
Note: when I close the player activity and select that video again for playing, everything is ok most of the time and this exception is not thrown even when I change the seek bar position very fast.

`E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:608)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.media.MediaCodec$CodecException: Error 0x80001009
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2194)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:165)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:895)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:888)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReinitializeCodec(MediaCodecRenderer.java:864)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onPositionReset(MediaCodecRenderer.java:710)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onPositionReset(MediaCodecVideoRenderer.java:419)
        at com.google.android.exoplayer2.BaseRenderer.resetPosition(BaseRenderer.java:160)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetRendererPosition(ExoPlayerImplInternal.java:1303)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.seekToPeriodPosition(ExoPlayerImplInternal.java:1281)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.seekToPeriodPosition(ExoPlayerImplInternal.java:1221)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.seekToInternal(ExoPlayerImplInternal.java:1192)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:485)
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2194)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:165)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:895)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:888)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:741)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:483)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:178)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1635)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1377)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1340)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:610)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
W`

**Comment by icbaker** [comment]
Given you're using a custom `DataSource` implementation, it's possible there's a bug in that. Can you try setting up a subclass of [`DataSourceContractTest`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/testutil/DataSourceContractTest.html) to see if it spots any problems with your implementation (perhaps obvious note: if all these tests pass, it doesn't necessarily guarantee your implementation is free of bugs of course). There's more info in this blog post: https://medium.com/google-exoplayer/standardising-datasource-implementations-through-testing-b7a8ab04f8d1

You could also try doing the same playback with fast seeking **without** using your custom data source (I guess with unencrypted media). If the problem doesn't reproduce in that case, it also suggests there's a problem with your `DataSource` implementation. If it does reproduce then you can probably also reproduce in the [demo app](https://exoplayer.dev/demo-application.html) - if you can provide us instructions and media to reproduce the problem in the demo app it will help us pin-point the cause of the problem.
