### ISSUE TITLE
subtitle segments why not >=0

### ISSUE THREAD

**Issue by zcwfeng** [google/ExoPlayer#9650]
HlsChunckSource.java

717 lines
such as:

```
if (segmentIndexInPlaylist >= 0) {
        // In case we are inside the live window, we try to pick a part if available.
        Segment segment = mediaPlaylist.segments.get(segmentIndexInPlaylist);
        List<HlsMediaPlaylist.Part> parts =
            targetPositionInPlaylistUs < segment.relativeStartTimeUs + segment.durationUs
                ? segment.parts
                : mediaPlaylist.trailingParts;
        for (int i = 0; i < parts.size(); i++) {
          HlsMediaPlaylist.Part part = parts.get(i);
          if (targetPositionInPlaylistUs < part.relativeStartTimeUs + part.durationUs) {
            if (part.isIndependent) {
              partIndex = i;
              // Increase media sequence by one if the part is a trailing part.
              mediaSequence += parts == mediaPlaylist.trailingParts ? 1 : 0;
            }
            break;
          }
        }
      }

```
-------------------

 if (segmentIndexInPlaylist >= 0)

mediaPlaylist.segments == 0  is erro. 
 why not add check and exception

**Comment by icbaker** [comment]
Can you please add some more detail about what you're asking, and a little more context about the general problem you're seeing (if any). Thanks!

**Comment by ojw28** [comment]
Is this about what happens if the media playlist is empty (i.e. `mediaPlaylist.segments.size() == 0`)? I can cause a playback to be stuck buffering if I give ExoPlayer the following empty VOD playlist.

```
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-ENDLIST
```

Inside the player, this is happening:

```
java.lang.IndexOutOfBoundsException: index (0) must be less than size (0)
    at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1402)
    at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1384)
    at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77)
    at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextMediaSequenceAndPartIndex(HlsChunkSource.java:719)
    at com.google.android.exoplayer2.source.hls.HlsChunkSource.createMediaChunkIterators(HlsChunkSource.java:578)
    at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:331)
    at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:740)
    at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continuePreparing(HlsSampleStreamWrapper.java:254)
    at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.buildAndPrepareSampleStreamWrappers(HlsMediaPeriod.java:540)
    at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.prepare(HlsMediaPeriod.java:161)
```
