### ISSUE TITLE
RTSP source error with "SETUP 400"

### ISSUE THREAD

**Issue by yeojoyjob** [google/ExoPlayer#9653]
When I tried to play the RTSP streaming, I got a problem with ExoPlayer 2.16.0.

I set the local camera rtsp url into exoplayer with RtspMediaSource like this
```
val trackSelectionFactory = AdaptiveTrackSelection.Factory()
val trackSelector = DefaultTrackSelector(requireContext(), trackSelectionFactory)
player = ExoPlayer.Builder(requireContext()).build()
player?.addAnalyticsListener(EventLogger(trackSelector))
val uri = Uri.parse("rtsp://AndroidTV:MyPassword@192.168.1.19:554/media2/stream.sdp?profile=Profile201")
val mediaItem = MediaItem.fromUri(uri)
val mediaSource = RtspMediaSource
    .Factory()
    .setForceUseRtpTcp(false)
    .createMediaSource(mediaItem)

player?.setMediaSource(mediaSource)
player?.prepare()
```

the error is
```
11-05 09:40:53.240 D/EventLogger(25306): audioDecoderInitialized [eventTime=428.59, mediaPos=0.00, window=0, period=0, OMX.google.aac.decoder]
11-05 09:40:53.251 E/ExoPlayerImplInternal(25306): Playback error
11-05 09:40:53.251 E/ExoPlayerImplInternal(25306):   com.google.android.exoplayer2.ExoPlaybackException: Source error
11-05 09:40:53.251 E/ExoPlayerImplInternal(25306):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:628)
11-05 09:40:53.251 E/ExoPlayerImplInternal(25306):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:604)
11-05 09:40:53.251 E/ExoPlayerImplInternal(25306):       at android.os.Handler.dispatchMessage(Handler.java:102)
11-05 09:40:53.251 E/ExoPlayerImplInternal(25306):       at android.os.Looper.loop(Looper.java:193)
11-05 09:40:53.251 E/ExoPlayerImplInternal(25306):       at android.os.HandlerThread.run(HandlerThread.java:65)
11-05 09:40:53.251 E/ExoPlayerImplInternal(25306):   Caused by: com.google.android.exoplayer2.source.rtsp.RtspMediaSource$RtspPlaybackException: SETUP 400
11-05 09:40:53.251 E/ExoPlayerImplInternal(25306):       at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspResponse(RtspClient.java:563)
11-05 09:40:53.251 E/ExoPlayerImplInternal(25306):       at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:494)
11-05 09:40:53.251 E/ExoPlayerImplInternal(25306):       at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$RtspClient$MessageListener(RtspClient.java:487)
11-05 09:40:53.251 E/ExoPlayerImplInternal(25306):       at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener$$ExternalSyntheticLambda0.run(Unknown Source:4)
11-05 09:40:53.251 E/ExoPlayerImplInternal(25306):       at android.os.Handler.handleCallback(Handler.java:873)
11-05 09:40:53.251 E/ExoPlayerImplInternal(25306):       at android.os.Handler.dispatchMessage(Handler.java:99)
11-05 09:40:53.251 E/ExoPlayerImplInternal(25306):       ... 2 more
```

And I also cloned your demo and played this stream, it also gave me the same error message.
However I found another exoplayer rtsp example in github, it played well.
that project is in https://github.com/X1opya/Exoplayer-Rtsp-Example, which was released 3 years ago.

and I'm going to send you the "adb bugreport" and details.

**Comment by claincly** [comment]
Please provide a log of RTSP messages.

The easiest way is to use the `RtspMediaSource.Factory` method `setDebugLoggingEnabled()`

That is, set the media source factory when building the ExoPlayer instance, like this:

```
     SimpleExoPlayer player =
          new ExoPlayer.Builder(/* context= */ this)
              .set... // all other customization
              .setMediaSourceFactory(new RtspMediaSource.Factory().setDebugLoggingEnabled(true))
              .build()
```

**Comment by yeojoyjob** [comment]
I was wondering how to get that message... Thank you. and the message is

```
11-05 11:51:34.566 D/RtspClient(29683): OPTIONS rtsp://192.168.1.19:554/media2/stream.sdp?profile=Profile201 RTSP/1.0
11-05 11:51:34.566 D/RtspClient(29683): User-Agent: ExoPlayerLib/2.16.0
11-05 11:51:34.566 D/RtspClient(29683): CSeq: 0
11-05 11:51:34.566 D/RtspClient(29683):
11-05 11:51:34.636 D/RtspClient(29683): RTSP/1.0 200 OK
11-05 11:51:34.636 D/RtspClient(29683): CSeq: 0
11-05 11:51:34.636 D/RtspClient(29683): Date: Fri, 5 Nov 2021 15:51:34 GMT
11-05 11:51:34.636 D/RtspClient(29683): Public: OPTIONS, DESCRIBE, PLAY, SETUP, GET_PARAMETER, SET_PARAMETER, TEARDOWN
11-05 11:51:34.653 D/RtspClient(29683): DESCRIBE rtsp://192.168.1.19:554/media2/stream.sdp?profile=Profile201 RTSP/1.0
11-05 11:51:34.653 D/RtspClient(29683): User-Agent: ExoPlayerLib/2.16.0
11-05 11:51:34.653 D/RtspClient(29683): CSeq: 1
11-05 11:51:34.653 D/RtspClient(29683):
11-05 11:51:34.696 D/RtspClient(29683): RTSP/1.0 401 Unauthorized
11-05 11:51:34.696 D/RtspClient(29683): CSeq: 1
11-05 11:51:34.696 D/RtspClient(29683): WWW-Authenticate: Digest realm="streaming_server", nonce="ba060d398c404c9d25dd7be787fb1d87", algorithm=MD5, qop="auth"
11-05 11:51:34.708 D/RtspClient(29683): DESCRIBE rtsp://192.168.1.19:554/media2/stream.sdp?profile=Profile201 RTSP/1.0
11-05 11:51:34.708 D/RtspClient(29683): User-Agent: ExoPlayerLib/2.16.0
11-05 11:51:34.708 D/RtspClient(29683): CSeq: 2
11-05 11:51:34.708 D/RtspClient(29683): Authorization: Digest username="AndroidTV", realm="streaming_server", nonce="ba060d398c404c9d25dd7be787fb1d87", uri="rtsp://192.168.1.19:554/media2/stream.sdp?profile=Profile201", response="d5ffedeeef126055cebc7f0fcaf775ce"
11-05 11:51:34.708 D/RtspClient(29683):
11-05 11:51:34.859 D/RtspClient(29683): RTSP/1.0 200 OK
11-05 11:51:34.859 D/RtspClient(29683): CSeq: 2
11-05 11:51:34.859 D/RtspClient(29683): Date: Fri, 5 Nov 2021 15:51:34 GMT
11-05 11:51:34.859 D/RtspClient(29683): Content-base: rtsp://192.168.1.19:554/media2/stream.sdp?profile=Profile201/
11-05 11:51:34.859 D/RtspClient(29683): Content-Type: application/sdp
11-05 11:51:34.859 D/RtspClient(29683): Content-Length: 774
11-05 11:51:34.859 D/RtspClient(29683):
11-05 11:51:34.859 D/RtspClient(29683): v=0
11-05 11:51:34.859 D/RtspClient(29683): o=RTSP 1636127494 821 IN IP4 0.0.0.0
11-05 11:51:34.859 D/RtspClient(29683): s=RTSP server
11-05 11:51:34.859 D/RtspClient(29683): c=IN IP4 0.0.0.0
11-05 11:51:34.859 D/RtspClient(29683): t=0 0
11-05 11:51:34.859 D/RtspClient(29683): a=charset:Shift_JIS
11-05 11:51:34.859 D/RtspClient(29683): a=range:npt=0-
11-05 11:51:34.859 D/RtspClient(29683): a=control:*
11-05 11:51:34.859 D/RtspClient(29683): a=etag:1234567890
11-05 11:51:34.859 D/RtspClient(29683): m=video 0 RTP/AVP 98
11-05 11:51:34.859 D/RtspClient(29683): a=rtpmap:98 H264/90000
11-05 11:51:34.859 D/RtspClient(29683): a=control:trackID=2
11-05 11:51:34.859 D/RtspClient(29683): a=x-onvif-track:trackID=2
11-05 11:51:34.859 D/RtspClient(29683): a=fmtp:98 packetization-mode=1; profile-level-id=4d002a; sprop-parameter-sets=Z00AKpY1wPAET8s3AQEBAg==,aO48gA==
11-05 11:51:34.859 D/RtspClient(29683): a=recvonly
11-05 11:51:34.859 D/RtspClient(29683): m=audio 0 RTP/AVP 97
11-05 11:51:34.859 D/RtspClient(29683): a=rtpmap:97 mpeg4-generic/16000/2
11-05 11:51:34.859 D/RtspClient(29683): a=fmtp:97 streamtype=5; profile-level-id=15; mode=AAC-hbr; config=1410; SizeLength=13; IndexLength=3; IndexDeltaLength=3; CTSDeltaLength=0; DTSDeltaLength=0
11-05 11:51:34.859 D/RtspClient(29683): a=control:trackID=0
11-05 11:51:34.859 D/RtspClient(29683): a=x-onvif-track:trackID=0
11-05 11:51:34.859 D/RtspClient(29683): a=recvonly
11-05 11:51:34.859 D/RtspClient(29683): m=application 0 RTP/AVP 107
11-05 11:51:34.859 D/RtspClient(29683): a=control:trackID=1
11-05 11:51:34.859 D/RtspClient(29683): a=x-onvif-track:trackID=1
11-05 11:51:34.859 D/RtspClient(29683): a=rtpmap:107 vnd.onvif.metadata/90000
11-05 11:51:34.859 D/RtspClient(29683): a=recvonly
11-05 11:51:34.921 D/RtspClient(29683): SETUP rtsp://192.168.1.19:554/media2/stream.sdp/trackID=2?profile=Profile201 RTSP/1.0
11-05 11:51:34.921 D/RtspClient(29683): User-Agent: ExoPlayerLib/2.16.0
11-05 11:51:34.921 D/RtspClient(29683): CSeq: 3
11-05 11:51:34.921 D/RtspClient(29683): Authorization: Digest username="AndroidTV", realm="streaming_server", nonce="ba060d398c404c9d25dd7be787fb1d87", uri="rtsp://192.168.1.19:554/media2/stream.sdp/trackID=2?profile=Profile201", response="08791b4170b5e1bb9657c96243bb2d13"
11-05 11:51:34.921 D/RtspClient(29683): Transport: RTP/AVP;unicast;client_port=60764-60765
11-05 11:51:34.921 D/RtspClient(29683):
11-05 11:51:35.131 D/RtspClient(29683): RTSP/1.0 400 Bad Request
11-05 11:51:35.131 D/RtspClient(29683): CSeq: 3
```

**Comment by claincly** [comment]
I suspect the problem is the track URI we send in SETUP:
`rtsp://192.168.1.19:554/media2/stream.sdp/trackID=2?profile=Profile201`
should be 
`rtsp://192.168.1.19:554/media2/stream.sdp?profile=Profile201/trackID=2`

Could you confirm with the log from the other RTSP implementation you tried?

**Comment by yeojoyjob** [comment]
@claincly I see, you're right. I tested it with ExoPlayer 2.9.0 and checked the log

```
11-05 12:48:41.167 V/Sender  (32323): PLAY rtsp://AndroidTV:MyPassword@192.168.1.19:554/media2/stream.sdp?profile=Profile201 RTSP/1.0
11-05 12:48:41.167 V/Sender  (32323): CSeq: 6
11-05 12:48:41.167 V/Sender  (32323): User-Agent: ExoPlayerLib/2.9.0 (Media Player for Android)
11-05 12:48:41.167 V/Sender  (32323): Session: 378190124
11-05 12:48:41.167 V/Sender  (32323): Range: npt=0.000-
11-05 12:48:41.167 V/Sender  (32323): Scale: 1.0
11-05 12:48:41.167 V/Sender  (32323): Authorization: Digest username="AndroidTV", realm="streaming_server", nonce="efaa8e068a7490468955276b41e22250", qop="auth", uri="rtsp://AndroidTV:MyPassword@192.168.1.19:554/media2/stream.sdp?profile=Profile201", nc="00000004", cnonce="7816682defae87d049a54f6fbc7a7102", algorithm="D", response="b12fa23780d0601489dfa54dde8e6fd7"
11-05 12:48:41.167 V/Sender  (32323):
11-05 12:48:41.184 V/Receiver(32323): RTSP/1.0 200 OK
11-05 12:48:41.184 V/Receiver(32323): CSeq: 6
11-05 12:48:41.184 V/Receiver(32323): Date: Fri, 5 Nov 2021 16:48:41 GMT
11-05 12:48:41.184 V/Receiver(32323): Session: 378190124;timeout=70
11-05 12:48:41.184 V/Receiver(32323): RTP-Info: url=rtsp://AndroidTV:MyPassword@192.168.1.19:554/media2/stream.sdp?profile=Profile201/trackID=2;seq=0;rtptime=0,url=rtsp://AndroidTV:MyPassword@192.168.1.19:554/media2/stream.sdp?profile=Profile201/trackID=0;seq=0;rtptime=0
11-05 12:48:41.184 V/Receiver(32323): Range: npt=0-
11-05 12:48:41.184 V/Receiver(32323): RTCP-Interval: 250
```
In the RTP-Info, the URL is that you said.

So what do I do? Are there some options to move "/trackID=2" after the URL's parameter?

**Comment by claincly** [comment]
The dirty fix would be changing this line
https://github.com/google/ExoPlayer/blob/7fe9ecc1c592b758e76f6b458e0dc43cce282e5f/library/rtsp/src/main/java/com/google/android/exoplayer2/source/rtsp/RtspMediaTrack.java#L229
to 
`return Uri.parse(sessionUri.toString() + "/" + controlAttributeString);`

We will release a fix soon.

**Comment by yeojoyjob** [comment]
Got it. Thanks for helping me. I'll wait for your fix.

**Comment by claincly** [comment]
Please make the proposed change as you see fit. 

ExoPlayer will not provide a official "fix" to this issue, as the accepted URI is quite a deviation from the standard URI schema.
