### ISSUE TITLE
Unable to play HLS URL

### ISSUE THREAD

**Issue by liutingdu** [google/ExoPlayer#970]
I  am trying to play my HLS stream in the demo app, the stream was transcoded from an IP camera. 

The code I added:
```java
new Sample("Test", "url" , PlayerActivity.TYPE_HLS)
```
It always shows black screen and the video never shows up. The same URL works with VLC on Android.

The demo app version is: 1.4.2

Tested on Android 6.0 on Nexus 5.

I've sent an Email with the URL and full logs attached, thanks a lot in advance :)

Here are part of the logs: 
```
11-19 15:48:55.775 16784-16784/com.google.android.exoplayer.demo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
11-19 15:48:55.785 16784-16784/com.google.android.exoplayer.demo W/VideoCapabilities: Unrecognized profile/level 0/0 for video/mpeg2
11-19 15:48:55.786 16784-16784/com.google.android.exoplayer.demo W/VideoCapabilities: Unrecognized profile/level 0/2 for video/mpeg2
11-19 15:48:55.786 16784-16784/com.google.android.exoplayer.demo W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
11-19 15:48:55.799 16784-16784/com.google.android.exoplayer.demo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
11-19 15:48:55.809 16784-16812/com.google.android.exoplayer.demo D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
11-19 15:48:55.854 16784-16812/com.google.android.exoplayer.demo I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 09/02/15, 76f806e, Ibddc658e36
11-19 15:48:55.855 16784-16812/com.google.android.exoplayer.demo I/OpenGLRenderer: Initialized EGL, version 1.4
11-19 15:49:33.048 16784-16784/com.google.android.exoplayer.demo I/ExoPlayerImpl: Init 1.4.2
11-19 15:49:33.054 16784-16784/com.google.android.exoplayer.demo D/EventLogger: start [0]
11-19 15:49:33.055 16784-16784/com.google.android.exoplayer.demo D/EventLogger: state [0.00, false, P]
11-19 15:49:33.062 16784-16784/com.google.android.exoplayer.demo D/EventLogger: state [0.01, true, P]
11-19 15:49:33.165 16784-16812/com.google.android.exoplayer.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb3ab58b0
11-19 15:49:33.173 16784-16812/com.google.android.exoplayer.demo D/OpenGLRenderer: endAllStagingAnimators on 0xb4ce2e80 (ListView) with handle 0xb06fe140
11-19 15:49:53.673 16784-16784/com.google.android.exoplayer.demo D/EventLogger: end [20.62]
11-19 15:49:56.022 16784-16845/com.google.android.exoplayer.demo W/MessageQueue: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {6a0ae21} sending message to a Handler on a dead thread
                                                                                 java.lang.IllegalStateException: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {6a0ae21} sending message to a Handler on a dead thread
                                                                                     at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                                     at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                                     at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                                     at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                                     at android.os.Handler.sendEmptyMessageDelayed(Handler.java:534)
                                                                                     at android.os.Handler.sendEmptyMessage(Handler.java:519)
                                                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:212)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
11-19 15:50:09.186 16784-16784/com.google.android.exoplayer.demo I/ExoPlayerImpl: Init 1.4.2
11-19 15:50:09.189 16784-16784/com.google.android.exoplayer.demo D/EventLogger: start [0]
11-19 15:50:09.189 16784-16784/com.google.android.exoplayer.demo D/EventLogger: state [0.00, false, P]
11-19 15:50:09.190 16784-16784/com.google.android.exoplayer.demo D/EventLogger: state [0.00, true, P]
11-19 15:50:09.315 16784-16812/com.google.android.exoplayer.demo D/OpenGLRenderer: endAllStagingAnimators on 0xb4ce2e80 (ListView) with handle 0xb06fe670
11-19 15:50:55.584 16784-16812/com.google.android.exoplayer.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0xaeeaeb50
11-19 15:50:56.463 16784-16784/com.google.android.exoplayer.demo D/EventLogger: state [47.28, false, P]
11-19 15:50:56.935 16784-16784/com.google.android.exoplayer.demo D/EventLogger: state [47.75, true, P]
11-19 15:50:57.204 16784-16784/com.google.android.exoplayer.demo V/EventLogger: loadEnd [48.02, 0, 1808]
11-19 15:50:58.394 16784-16784/com.google.android.exoplayer.demo V/EventLogger: loadStart [49.21, 0, 4, 0, 0]
11-19 15:50:58.460 16784-16784/com.google.android.exoplayer.demo V/EventLogger: loadEnd [49.27, 0, 66]
11-19 15:51:01.461 16784-16784/com.google.android.exoplayer.demo V/EventLogger: loadStart [52.27, 0, 4, 0, 0]
11-19 15:51:01.540 16784-16784/com.google.android.exoplayer.demo V/EventLogger: loadEnd [52.35, 0, 79]
11-19 15:51:01.540 16784-16784/com.google.android.exoplayer.demo V/EventLogger: loadStart [52.35, 0, 1, 66018, 72018]
11-19 15:51:02.994 16784-16784/com.google.android.exoplayer.demo V/EventLogger: loadEnd [53.81, 0, 1454]
11-19 15:51:05.322 16784-16784/com.google.android.exoplayer.demo D/EventLogger: end [56.13]
11-19 15:54:31.355 16784-16784/com.google.android.exoplayer.demo I/ExoPlayerImpl: Init 1.4.2
```

**Comment by ojw28** [comment]
The stream declares an audio track but does not contain any audio. If the stream doesn't contain audio, it shouldn't declare a track. This is the same as #905 (see 5th post in that issue for the bit of code you could manually comment out to allow playback to proceed - although doing this will break audio on any correctly functioning streams).

The correct fix is for whoever is providing this stream to not include an audio track.

**Comment by liutingdu** [comment]
You are right :)  Thanks a lot!
