### ISSUE TITLE
Is it possible to play the RTSP even though it has a video codec error?

### ISSUE THREAD

**Issue by yeojoyjob** [google/ExoPlayer#9703]
Hi, I hope you're doing well.

I'm working on playing RTSP streaming and ExoPlayer works well with most cameras.
However, with some conditions, it gives me the errors about video codec error.

I was trying to play 4k streaming, which has 4512x1728 resolution. 

```
11-17 17:20:44.477 D/RtspClient( 4740): OPTIONS rtsp://192.168.1.43:554/live1s2.sdp RTSP/1.0
11-17 17:20:44.477 D/RtspClient( 4740): User-Agent: ExoPlayerLib/2.16.0
11-17 17:20:44.477 D/RtspClient( 4740): CSeq: 0
11-17 17:20:44.477 D/RtspClient( 4740):
11-17 17:20:44.506 D/RtspClient( 4740): RTSP/1.0 200 OK
11-17 17:20:44.506 D/RtspClient( 4740): CSeq: 0
11-17 17:20:44.506 D/RtspClient( 4740): Date: Wed, 17 Nov 2021 22:20:43 GMT
11-17 17:20:44.506 D/RtspClient( 4740): Public: OPTIONS, DESCRIBE, PLAY, SETUP, GET_PARAMETER, SET_PARAMETER, TEARDOWN
11-17 17:20:44.519 D/RtspClient( 4740): DESCRIBE rtsp://192.168.1.43:554/live1s2.sdp RTSP/1.0
11-17 17:20:44.519 D/RtspClient( 4740): User-Agent: ExoPlayerLib/2.16.0
11-17 17:20:44.519 D/RtspClient( 4740): CSeq: 1
11-17 17:20:44.519 D/RtspClient( 4740):
11-17 17:20:44.570 D/RtspClient( 4740): RTSP/1.0 401 Unauthorized
11-17 17:20:44.570 D/RtspClient( 4740): CSeq: 1
11-17 17:20:44.570 D/RtspClient( 4740): WWW-Authenticate: Digest realm="streaming_server", nonce="bed07d3d474bfc88f3dd9f01d35154c7", algorithm=MD5, qop="auth"
11-17 17:20:44.597 D/RtspClient( 4740): DESCRIBE rtsp://192.168.1.43:554/live1s2.sdp RTSP/1.0
11-17 17:20:44.597 D/RtspClient( 4740): User-Agent: ExoPlayerLib/2.16.0
11-17 17:20:44.597 D/RtspClient( 4740): CSeq: 2
11-17 17:20:44.597 D/RtspClient( 4740): Authorization: Digest username="viewer", realm="streaming_server", nonce="bed07d3d474bfc88f3dd9f01d35154c7", uri="rtsp://192.168.1.43:554/live1s2.sdp", response="d719fa73ebd31dca149df148d72db12e"
11-17 17:20:44.597 D/RtspClient( 4740):
11-17 17:20:44.893 D/RtspClient( 4740): RTSP/1.0 200 OK
11-17 17:20:44.893 D/RtspClient( 4740): CSeq: 2
11-17 17:20:44.893 D/RtspClient( 4740): Date: Wed, 17 Nov 2021 22:20:43 GMT
11-17 17:20:44.893 D/RtspClient( 4740): Content-base: rtsp://192.168.1.43:554/live1s2.sdp/
11-17 17:20:44.893 D/RtspClient( 4740): Content-Type: application/sdp
11-17 17:20:44.893 D/RtspClient( 4740): Content-Length: 774
11-17 17:20:44.893 D/RtspClient( 4740):
11-17 17:20:44.893 D/RtspClient( 4740): v=0
11-17 17:20:44.893 D/RtspClient( 4740): o=RTSP 1637187643 788 IN IP4 0.0.0.0
11-17 17:20:44.893 D/RtspClient( 4740): s=RTSP server
11-17 17:20:44.893 D/RtspClient( 4740): c=IN IP4 0.0.0.0
11-17 17:20:44.893 D/RtspClient( 4740): t=0 0
11-17 17:20:44.893 D/RtspClient( 4740): a=charset:Shift_JIS
11-17 17:20:44.893 D/RtspClient( 4740): a=range:npt=0-
11-17 17:20:44.893 D/RtspClient( 4740): a=control:*
11-17 17:20:44.893 D/RtspClient( 4740): a=etag:1234567890
11-17 17:20:44.893 D/RtspClient( 4740): m=video 0 RTP/AVP 98
11-17 17:20:44.893 D/RtspClient( 4740): a=rtpmap:98 H264/90000
11-17 17:20:44.893 D/RtspClient( 4740): a=control:trackID=3
11-17 17:20:44.893 D/RtspClient( 4740): a=x-onvif-track:trackID=3
11-17 17:20:44.893 D/RtspClient( 4740): a=fmtp:98 packetization-mode=1; profile-level-id=4d0033; sprop-parameter-sets=Z00AM5Y1wCNAbNNwEBAQIA==,aO48gA==
11-17 17:20:44.893 D/RtspClient( 4740): a=recvonly
11-17 17:20:44.893 D/RtspClient( 4740): m=audio 0 RTP/AVP 97
11-17 17:20:44.893 D/RtspClient( 4740): a=rtpmap:97 mpeg4-generic/16000/2
11-17 17:20:44.893 D/RtspClient( 4740): a=fmtp:97 streamtype=5; profile-level-id=15; mode=AAC-hbr; config=1410; SizeLength=13; IndexLength=3; IndexDeltaLength=3; CTSDeltaLength=0; DTSDeltaLength=0
11-17 17:20:44.893 D/RtspClient( 4740): a=control:trackID=0
11-17 17:20:44.893 D/RtspClient( 4740): a=x-onvif-track:trackID=0
11-17 17:20:44.893 D/RtspClient( 4740): a=recvonly
11-17 17:20:44.893 D/RtspClient( 4740): m=application 0 RTP/AVP 107
11-17 17:20:44.893 D/RtspClient( 4740): a=control:trackID=1
11-17 17:20:44.893 D/RtspClient( 4740): a=x-onvif-track:trackID=1
11-17 17:20:44.893 D/RtspClient( 4740): a=rtpmap:107 vnd.onvif.metadata/90000
11-17 17:20:44.893 D/RtspClient( 4740): a=recvonly
```

and
```
11-17 17:20:47.756 E/MediaCodecVideoRenderer( 4740): Video codec error
11-17 17:20:47.756 E/MediaCodecVideoRenderer( 4740):   java.lang.IllegalStateException
11-17 17:20:47.756 E/MediaCodecVideoRenderer( 4740):       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
11-17 17:20:47.756 E/MediaCodecVideoRenderer( 4740):       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
11-17 17:20:47.756 E/MediaCodecVideoRenderer( 4740):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:122)
11-17 17:20:47.756 E/MediaCodecVideoRenderer( 4740):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1764)
11-17 17:20:47.756 E/MediaCodecVideoRenderer( 4740):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:778)
11-17 17:20:47.756 E/MediaCodecVideoRenderer( 4740):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
11-17 17:20:47.756 E/MediaCodecVideoRenderer( 4740):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
11-17 17:20:47.756 E/MediaCodecVideoRenderer( 4740):       at android.os.Handler.dispatchMessage(Handler.java:102)
11-17 17:20:47.756 E/MediaCodecVideoRenderer( 4740):       at android.os.Looper.loop(Looper.java:193)
11-17 17:20:47.756 E/MediaCodecVideoRenderer( 4740):       at android.os.HandlerThread.run(HandlerThread.java:65)
11-17 17:20:47.757 D/MediaCodecInfo( 4740): NoSupport [sizeAndRate.support, 4512x1728x-1.0] [OMX.MS.AVC.Decoder, video/avc] [xinhaoshan, HiSmart 4K ATV4, Hisense, 28]
11-17 17:20:47.758 D/MediaCodecInfo( 4740): NoSupport [sizeAndRate.support, 4512x1728x-1.0] [OMX.google.h264.decoder, video/avc] [xinhaoshan, HiSmart 4K ATV4, Hisense, 28]
11-17 17:20:47.764 D/MediaCodecInfo( 4740): NoSupport [sizeAndRate.support, 4512x1728x-1.0] [OMX.MS.AVC.Decoder, video/avc] [xinhaoshan, HiSmart 4K ATV4, Hisense, 28]
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740): Playback error
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(null, null, null, video/avc, avc1.4d0033, -1, null, [4512, 1728, -1.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):       at android.os.Handler.dispatchMessage(Handler.java:102)
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):       at android.os.Looper.loop(Looper.java:193)
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):       at android.os.HandlerThread.run(HandlerThread.java:65)
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MS.AVC.Decoder
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1470)
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:799)
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):       ... 3 more
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):   Caused by: java.lang.IllegalStateException
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:122)
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1764)
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:778)
11-17 17:20:47.788 E/ExoPlayerImplInternal( 4740):       ... 5 more
11-17 17:20:47.805 D/PlaybackVideoFragment( 4740): onVideoDisabled()
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740): Disable failed.
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):   java.lang.IllegalStateException
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):       at android.media.MediaCodec.native_flush(Native Method)
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):       at android.media.MediaCodec.flush(MediaCodec.java:2131)
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:188)
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:850)
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:843)
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:696)
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:529)
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:178)
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1642)
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1382)
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1345)
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):       at android.os.Handler.dispatchMessage(Handler.java:102)
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):       at android.os.Looper.loop(Looper.java:193)
11-17 17:20:47.806 E/ExoPlayerImplInternal( 4740):       at android.os.HandlerThread.run(HandlerThread.java:65)
```

With the resolution 3840x1536, it plays well, but we need to provide the highest resolution. Because it connects with the other services.

And I tried to use vlc-android-library, yeah it works well with 4512x1728 resolution, it's cool, but its apk file size is about 160 mb. The library has lots of native libraries.

With ExoPlayer, its size is just 6 mb.

So my question is
**1. Do you have something to help me to resolve this?**

**2. If no, do you have a plan to support 4512x1728 resolution to play RTSP streaming?**

**Comment by marcbaechinger** [comment]
This is not RTSP specific I think except that in contrast to a adaptive streaming format with RTSP the is no way to adapt to a  lower quality as far as I can tell.

Like you say and see in the error message the resolution in question gives a `NO_EXCEEDS_CAPABILITIES` for the decoder on the given device that apparently is a `HiSmart 4K ATV4, Hisense, 28`. I don't think there is much you can do against this with the given decoder. I'm not sure what vlc is doing but like you say when referring to native libraries they are probably doing this in software? I can't tell to be honest and I'm not sure whether it is advisable to do so for the highest resolution when lower resolution is decoded in hardware. If you want to try this I think it's about providing a renderer that is using software codecs instead for a device that can not support it in hardware.

**Comment by yeojoyjob** [comment]
Thank you
