### ISSUE TITLE
Getting IllegalArgumentException for XiaomiTV devices

### ISSUE THREAD

**Issue by thaleslima** [google/ExoPlayer#9710]
Issue Description

On Xiaomi devices getting IllegalArgumentException for XiaomiTV devices. Here is the stacktrace

```
2021-11-19 10:23:21.692 21646-22025/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:612)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1979)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.setOutputSurface(SynchronousMediaCodecAdapter.java:220)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1331)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:614)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1537)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1501)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1476)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:517)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

Steps to reproduce

1. Play any video(in Exoplayer demo as well) and do backpress, you will get the exception.

Device Info 

- API LEVEL = 28
- DEVICE = aquaman
- MANUFACTURER = Xiaomi
- MODEL = MiTV-AESP0

Exoplayer Version

- 2.16.1

Here is the bug report.
[bugreport-aquaman-PI-2021-11-19-10-23-22.zip](https://github.com/google/ExoPlayer/files/7570561/bugreport-aquaman-PI-2021-11-19-10-23-22.zip)

**Comment by tonihei** [comment]
The attached bugreport doesn't contain the error, please make sure to capture the bugreport right after the problem occurred.

Besides that, the problem looks similar to the one reported in #6346. In there it was suggested that the source of the error could be an ongoing asynchronous encoding operation (see https://github.com/google/ExoPlayer/issues/6346#issuecomment-526509019). Could something like this be the case here as well?

Alternatively, you could try adding this device to `MediaCodecVideoRenderer.evaluateDeviceNeedsSetOutputSurfaceWorkaround`. You need to build the code locally to do that, as described here: https://github.com/google/ExoPlayer#locally. If this works, we could add the device to our list as well.

**Comment by thaleslima** [comment]
Worked when set the following in `MediaCodecVideoRenderer.evaluateDeviceNeedsSetOutputSurfaceWorkaround:`

```
private static boolean evaluateDeviceNeedsSetOutputSurfaceWorkaround() {
    if (Util.SDK_INT <= 28) {
      switch (Util.DEVICE) {
        case "aquaman": //new device - MiTV-AESP
          return true;
        default:
          break;
      }
    }
}
```

**Comment by tonihei** [comment]
Thanks for testing! We'll add the device to the list.
