### ISSUE TITLE
MediaCodecAudioRenderer: Audio codec error (API 31)

### ISSUE THREAD

**Issue by farzadno** [google/ExoPlayer#9716]
When play mp3 file (im tested various mp3 files, but not fixed):
This error occurred when fast seeking by user : `exoPlayer.seekTo(millis); `

```
targetSdk 31
Device: Android Emulator

implementation 'com.google.android.exoplayer:exoplayer:2.16.0'
implementation 'com.google.android.exoplayer:extension-mediasession:2.16.0'
```

Initilize exoplayer:

```
MediaItem mediaItem = MediaItem.fromUri(mp3Uri);
DefaultExtractorsFactory defaultExtractorsFactory = new DefaultExtractorsFactory();
defaultExtractorsFactory.setMp3ExtractorFlags(FLAG_ENABLE_INDEX_SEEKING);
MediaSourceFactory mediaSourceFactory = new DefaultMediaSourceFactory(this, defaultExtractorsFactory);
mediaSourceFactory.createMediaSource(mediaItem);

exoPlayer = new ExoPlayer.Builder(this).setMediaSourceFactory(mediaSourceFactory).build();
exoPlayer.addListener(eventListener);
exoPlayer.setWakeMode(PowerManager.PARTIAL_WAKE_LOCK);
exoPlayer.setHandleAudioBecomingNoisy(true);

audioAttributes = new AudioAttributes.Builder()
	.setUsage(C.USAGE_MEDIA)
	.setContentType(C.CONTENT_TYPE_MUSIC)
	.setAllowedCapturePolicy(C.ALLOW_CAPTURE_BY_ALL)
	.build();
exoPlayer.setAudioAttributes(audioAttributes, true);

exoPlayer.setMediaItem(mediaItem);
exoPlayer.prepare();
exoPlayer.setPlayWhenReady(false);
```

Logcat:

```
2021-11-23 01:24:26.799 11813-12003/com.xxxxx.android E/MediaCodecAudioRenderer: Audio codec error
java.lang.IllegalStateException: start failed
at android.media.MediaCodec.native_start(Native Method)
at android.media.MediaCodec.start(MediaCodec.java:2284)
at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.$r8$lambda$eDpY_fTfY9aVkUSlR57RZPPXgr0(Unknown Source:0)
at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$$ExternalSyntheticLambda1.run(Unknown Source:2)
at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecCallback.onFlushCompletedSynchronized(AsynchronousMediaCodecCallback.java:265)
at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecCallback.onFlushCompleted(AsynchronousMediaCodecCallback.java:244)
at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecCallback.lambda$flushAsync$0$com-google-android-exoplayer2-mediacodec-AsynchronousMediaCodecCallback(AsynchronousMediaCodecCallback.java:202)
at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecCallback$$ExternalSyntheticLambda0.run(Unknown Source:4)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.os.HandlerThread.run(HandlerThread.java:67)
2021-11-23 01:24:26.805 11813-12003/com.xxxxx.android E/ExoPlayerImplInternal: Playback error
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/mpeg, null, -1, null, [-1, -1, -1.0], [2, 48000]), format_supported=YES
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecDecoderException: Decoder failed: c2.android.mp3.decoder
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.createDecoderException(MediaCodecRenderer.java:918)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:799)
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loopOnce(Looper.java:201) 
at android.os.Looper.loop(Looper.java:288) 
at android.os.HandlerThread.run(HandlerThread.java:67) 
Caused by: java.lang.IllegalStateException: start failed
at android.media.MediaCodec.native_start(Native Method)
at android.media.MediaCodec.start(MediaCodec.java:2284)
at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.$r8$lambda$eDpY_fTfY9aVkUSlR57RZPPXgr0(Unknown Source:0)
at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$$ExternalSyntheticLambda1.run(Unknown Source:2)
at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecCallback.onFlushCompletedSynchronized(AsynchronousMediaCodecCallback.java:265)
at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecCallback.onFlushCompleted(AsynchronousMediaCodecCallback.java:244)
at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecCallback.lambda$flushAsync$0$com-google-android-exoplayer2-mediacodec-AsynchronousMediaCodecCallback(AsynchronousMediaCodecCallback.java:202)
at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecCallback$$ExternalSyntheticLambda0.run(Unknown Source:4)
```

**Comment by farzadno** [comment]
This error has been fixed in version `2.16.1`
Thanks
