### ISSUE TITLE
Trackselection Playback error on onResume

### ISSUE THREAD

**Issue by ponthamaya** [google/ExoPlayer#9718]
- ExoPlayer 2.16.1 Demo project
- Android 10
- Android OnePlus 6T

I got the error when I minimized the app and resumed back.

Reproduce:
Change the audio track from StyledPlayerView control settings below the Playspeed. you will get the playback error when you minimize the app and resume back.

```
> 2021-11-23 11:43:40.411 5723-6639/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
>       com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:612)
>         at android.os.Handler.dispatchMessage(Handler.java:103)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.os.HandlerThread.run(HandlerThread.java:67)
>      Caused by: java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
>         at com.google.android.exoplayer2.source.smoothstreaming.DefaultSsChunkSource.<init>(DefaultSsChunkSource.java:107)
>         at com.google.android.exoplayer2.source.smoothstreaming.DefaultSsChunkSource$Factory.createChunkSource(DefaultSsChunkSource.java:72)
>         at com.google.android.exoplayer2.source.smoothstreaming.SsMediaPeriod.buildSampleStream(SsMediaPeriod.java:239)
>         at com.google.android.exoplayer2.source.smoothstreaming.SsMediaPeriod.selectTracks(SsMediaPeriod.java:145)
>         at com.google.android.exoplayer2.source.MaskingMediaPeriod.selectTracks(MaskingMediaPeriod.java:186)
>         at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:296)
>         at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:259)
>         at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:193)
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2209)
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:505)
>         at android.os.Handler.dispatchMessage(Handler.java:103) 
>         at android.os.Looper.loop(Looper.java:214) 
>         at android.os.HandlerThread.run(HandlerThread.java:67) 
> 2021-11-23 11:43:40.431 5723-5723/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=0.41, mediaPos=5.27, window=0, period=0, errorCode=ERROR_CODE_UNSPECIFIED
>       com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:612)
>         at android.os.Handler.dispatchMessage(Handler.java:103)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.os.HandlerThread.run(HandlerThread.java:67)
>      Caused by: java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
>         at com.google.android.exoplayer2.source.smoothstreaming.DefaultSsChunkSource.<init>(DefaultSsChunkSource.java:107)
>         at com.google.android.exoplayer2.source.smoothstreaming.DefaultSsChunkSource$Factory.createChunkSource(DefaultSsChunkSource.java:72)
>         at com.google.android.exoplayer2.source.smoothstreaming.SsMediaPeriod.buildSampleStream(SsMediaPeriod.java:239)
>         at com.google.android.exoplayer2.source.smoothstreaming.SsMediaPeriod.selectTracks(SsMediaPeriod.java:145)
>         at com.google.android.exoplayer2.source.MaskingMediaPeriod.selectTracks(MaskingMediaPeriod.java:186)
>         at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:296)
>         at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:259)
>         at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:193)
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2209)
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:505)
>         at android.os.Handler.dispatchMessage(Handler.java:103) 
>         at android.os.Looper.loop(Looper.java:214) 
>         at android.os.HandlerThread.run(HandlerThread.java:67) 
>     ]
>   
```

**Comment by tonihei** [comment]
Thanks for reporting, I can reproduce this problem.

**Comment by ponthamaya** [comment]
Please fix it in Demo project. It would be great.
