### ISSUE TITLE
update version 2.16.1 video can not play

### ISSUE THREAD

**Issue by zhouzhengfw** [google/ExoPlayer#9719]
hi after i update my version to 2.16.1 i can not play my video [https://cdn1-staging.fireworktv.com/medias/2021/11/18/1637259506-rwyenuix/transcoded/540/LUDMILLAANTIRRACISTA.mp4](url)
thank you

**Comment by tonihei** [comment]
Yes, I can confirm this file plays fine in 2.15.0 and fails to play in the latest dev version.

The error is:
```
Caused by: java.lang.IllegalStateException
        at androidx.media3.common.util.Assertions.checkState(Assertions.java:85)
        at androidx.media3.extractor.ParsableNalUnitBitArray.assertValidOffset(ParsableNalUnitBitArray.java:212)
        at androidx.media3.extractor.ParsableNalUnitBitArray.skipBit(ParsableNalUnitBitArray.java:68)
        at androidx.media3.extractor.ParsableNalUnitBitArray.readBit(ParsableNalUnitBitArray.java:128)
        at androidx.media3.extractor.ParsableNalUnitBitArray.readExpGolombCodeNum(ParsableNalUnitBitArray.java:196)
        at androidx.media3.extractor.ParsableNalUnitBitArray.readUnsignedExpGolombCodedInt(ParsableNalUnitBitArray.java:181)
        at androidx.media3.extractor.NalUnitUtil.parseH265SpsNalUnitPayload(NalUnitUtil.java:550)
        at androidx.media3.extractor.NalUnitUtil.parseH265SpsNalUnit(NalUnitUtil.java:456)
        at androidx.media3.extractor.HevcConfig.parse(HevcConfig.java:83)
        at androidx.media3.extractor.mp4.AtomParsers.parseVideoSampleEntry(AtomParsers.java:1152)
        at androidx.media3.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:952)
        at androidx.media3.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:311)
        at androidx.media3.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:132)
        at androidx.media3.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:491)
        at androidx.media3.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:450)
        at androidx.media3.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:432)
        at androidx.media3.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:250)
```

@kim-vde Could you take a look?

**Comment by kim-vde** [comment]
Thanks for reporting the issue. This is a regression introduced by #9421. I will merge a fix.

**Comment by kim-vde** [comment]
I just merged the fix to dev-v2. It should be part of the next minor release.

I will close this issue. Please open another one if you still encounter problems.

**Comment by rickzw** [comment]
> I just merged the fix to dev-v2. It should be part of the next minor release.
> 
> I will close this issue. Please open another one if you still encounter problems.

When is the next minor release with this fix?

**Comment by kim-vde** [comment]
The next major release is planned for February or March 2022. We don't know yet if we are going to do a minor release before.
