### ISSUE TITLE
Playback error       com.google.android.exoplayer2.ExoPlaybackException: Source error

### ISSUE THREAD

**Issue by akardas16** [google/ExoPlayer#9747]
When trying to use exoplayer in recyclerview it doesn't work

```
2021-12-01 21:54:38.948 7237-7565/com.akardas.exploremovies E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:628)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:236)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 402
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:396)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-12-01 21:54:38.976 7237-7237/com.akardas.exploremovies E/ResizingSurfaceView: Error clearing surface
    java.lang.IllegalArgumentException: Make sure the SurfaceView or associated SurfaceHolder has a valid Surface
        at com.google.android.gles_jni.EGLImpl._eglCreateWindowSurface(Native Method)
        at com.google.android.gles_jni.EGLImpl.eglCreateWindowSurface(EGLImpl.java:101)
        at com.devbrackets.android.exomedia.core.video.surface.ResizingSurfaceView.clearSurface(ResizingSurfaceView.kt:161)
        at com.devbrackets.android.exomedia.core.ListenerMux.onStateChanged(ListenerMux.kt:127)
        at com.devbrackets.android.exomedia.nmp.ExoMediaPlayerImpl.reportPlayerState(ExoMediaPlayerImpl.kt:414)
        at com.devbrackets.android.exomedia.nmp.ExoMediaPlayerImpl.onPlayerStateChanged(ExoMediaPlayerImpl.kt:165)
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$18(ExoPlayerImpl.java:1329)
        at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda3.invoke(Unknown Source:4)
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:261)
        at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:170)
        at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
        at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:191)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1366)
        at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1202)
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1$com-google-android-exoplayer2-ExoPlayerImpl(ExoPlayerImpl.java:242)
        at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda17.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
```

**Comment by ojw28** [comment]
The first error (`Response code: 402`) is from the server, so that's not something we have any control over. It seems to be a non-standard response code indicating that payment is required (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/402).

I suspect that the error you're more interested in is the second one. "It doesn't work" is not sufficient information for us to help you. Please properly fill out the issue template and provide all of the requested information if you'd like us to help. Thanks!
