### ISSUE TITLE
Playing m4a file stream vs. local on phone

### ISSUE THREAD

**Issue by denite** [google/ExoPlayer#975]
I'm trying to get my app to play both mp3 files and m4a files with exoPlayer. Mp3 files work perfectly, but I'm having a hard time with m4a files.

When using the Demo, if I replace a TYPE_OTHER with "http://deniteappz.com/01.m4a" it works perfectly, but as soon as I change that to a local same m4a file locally on my phone, it crashes. 

Is there something specific I need to do to make local m4a files work? It's odd as mp3 files wrok perfectly locally.

I'm using -> Samsung Note 4 w/ Lollipop / Samsung Tablet Pro w/ Kit Kat .
The error happens every time.

Here is the error log:

11-22 09:44:30.665 10315-10655/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                          com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeThrowError(MediaCodecTrackRenderer.java:782)
                                                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:274)
                                                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:197)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                              at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                           Caused by: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
                                                                                              at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:806)
                                                                                              at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:737)
                                                                                              at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                              at java.lang.Thread.run(Thread.java:818)
11-22 09:44:30.666 10315-10315/com.google.android.exoplayer.demo E/EventLogger: playerFailed [60.31]
                                                                                com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeThrowError(MediaCodecTrackRenderer.java:782)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:274)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:197)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                 Caused by: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
                                                                                    at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:806)
                                                                                    at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:737)
                                                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                    at java.lang.Thread.run(Thread.java:818)
11-22 09:44:30.666 10315-10315/com.google.android.exoplayer.demo D/EventLogger: state [60.31, true, I]
11-22 09:44:33.734 10315-10315/com.google.android.exoplayer.demo D/AbsListView: AbsListView android.widget.ListPopupWindow$DropDownListView{3e5cff6b V.ED.VC. ......I. 0,0-0,0} enabled= true
11-22 09:44:33.734 10315-10315/com.google.android.exoplayer.demo D/AbsListView: AbsListView android.widget.ListPopupWindow$DropDownListView{3e5cff6b V.ED.VC. ......I. 0,0-0,0} enabled= true
11-22 09:44:34.468 10315-10315/com.google.android.exoplayer.demo W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
11-22 09:44:37.883 10315-10315/com.google.android.exoplayer.demo D/EventLogger: end [67.53]
11-22 09:44:37.961 10315-10315/com.google.android.exoplayer.demo I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1cbfd254 time:52708316

**Comment by ojw28** [comment]
There should be no difference between the two cases, and the sample works fine in both cases for me on both the dev and master branches. What kind of URI are you specifying in the disk case? Is it a file:/// uri, or something else? Where abouts on the local file system are you putting the file?

There is a known issue with the demo app where local playback will fail on devices running Marshmallow, which is because the demo app doesn't implement Android's new permissions model yet. Although in this case you'd see a very different error that clearly relates to permissions, like:

```
com.google.android.exoplayer.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /sdcard/01.m4a: open failed: EACCES (Permission denied)
```

**Comment by denite** [comment]
OK, I got it working with the Demo... (I was previously using r1.4.2). I have now updated to the latest version and it works on the Demo...

I've updated my app with all of the Demo files, but I still get the same error... except it plays the file for a bit... then freezes the app and gives that exception I posted above.

Internal track renderer error.                                                          com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)

Is there something I need to do to remove the video stream as my app is just audio?

**Comment by ojw28** [comment]
The selection of the extractor only occurs at the start of playback, so I don't think it's possible that you're seeing that error part way through a playback. You shouldn't need to do anything related to video.

**Comment by denite** [comment]
Hmm... I can't for the life of me get this working with m4a's...

What would be your suggestion for implementing ExoPlayer into an app from scratch if all I need is audio? Maybe I need to import it differently.

I basically just copied all the files in the demo/player folder into my app.... Exported a jar file and use that as my lib.

And I use:
mediaPlayer = new DemoPlayer(new ExtractorRendererBuilder(context, userAgent, contentUri));

(along with its listeners etc)

Thanx for your quick responses btw. it's appreciated.

**Comment by ojw28** [comment]
So if I understand correctly, you're saying that the demo app works fine, but when you copy the same code into your own app that's no longer the case? I don't really know what could cause that. It sounds pretty odd to me. But as above, I don't think it's possible to see the error you're saying occurs part way through a playback.

**Comment by denite** [comment]
My apologies, I just re-tested the Demo and it does not work. (I must have tested wrong previously)

Here is how I tested it:

new Sample("Stream File","http://deniteappz.com/01.mp3", PlayerActivity.TYPE_OTHER),
new Sample("mp3 File","/extSdCard/Beyonce_m4a/BDay/01.mp3", PlayerActivity.TYPE_OTHER),
new Sample("M4a File","/extSdCard/Beyonce_m4a/01.m4a", PlayerActivity.TYPE_OTHER),};

The streamed m4a file works great...
The local mp3 file works great...
but the local m4a file does not work. Just gives that exception.

As for my app: The music plays, but the app freezes right away... (I guess the music is just playing in the bg)... and then after a bit i see the error in my Android Studio log...

**Comment by ojw28** [comment]
I really can't figure out how all of the statements in this issue can be accurate. It's unlikely that the player has anything to do with your app freezing, since it does nearly all of its work on a background thread rather than the main application thread. The error you say you're seeing wouldn't result in that kind of behavior, either.

Focusing on reproducing in the demo app specifically, the only thing I can think of is that the file at `/extSdCard/Beyonce_m4a/01.m4a` isn't actually identical to the one provided at the link.

**Comment by denite** [comment]
OK, so let's disregard my app for the moment... 

Let's focus on just the Demo App.

I can guarantee that ```/extSdCard/Beyonce_m4a/01.m4a``` && http://deniteappz.com/01.m4a are the same file.

I can also guarantee that ```/extSdCard/Beyonce_m4a/BDay/01.mp3``` works great on the demo. (a local file).

I just did two more tests... Uninstall, reinstall... local m4a will not play at all... I tested a couple of other m4a files as well, and no luck.

**Comment by denite** [comment]
Any luck reproducing this on your end? Can you get the demo to play a m4a file from internal storage?

**Comment by ojw28** [comment]
It works fine for me. I can't reproduce the issue you're seeing. Note that the code executed is identical in both cases, except that FileDataSource will be used instead of DefaultHttpDataSource.

**Comment by denite** [comment]
Hmm... that's not good. I guess I have to start from scratch again.

What would you say would be the easiest case to use Exoplayer for just Audio?

The code used in your video doesn't seem to work for me, and FrameworkSampleSoure is now depreciated... so I'm stuck... :-(

**Comment by denite** [comment]
I figured out the problem. All's well :-)
