### ISSUE TITLE
CacheDataSink raise NullPointerException

### ISSUE THREAD

**Issue by nickliwei1624** [google/ExoPlayer#9757]
Hi,

Reproduce Steps:
    a. Android 10 system
    b. Install third party netease apk(such as: https://www.appsdrop.com/netease/)
    c. Play any video in the netease apk. The video will play failed. From the logcat, the exoplayer(2.7.0) raise a NullPointerException like below:
 
```
12-01 17:38:05.271  8891  8891 I ExoPlayerImpl: Init c601e7d [ExoPlayerLib/2.7.0] [tablet, huanglong, HL2.0, 29]
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: Internal runtime error.
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: java.lang.NullPointerException
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.util.Assertions.checkNotNull(SourceFile:107)
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.cache.CacheDataSink.<init>(SourceFile:87)
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.cache.CacheDataSinkFactory.createDataSink(SourceFile:47)
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.cache.CacheDataSourceFactory.createDataSource(SourceFile:79)
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.cache.CacheDataSourceFactory.createDataSource(SourceFile:27)
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.DefaultDataSourceFactory.createDataSource(SourceFile:65)
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.DefaultDataSourceFactory.createDataSource(SourceFile:25)
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.hls.DefaultHlsDataSourceFactory.createDataSource(SourceFile:36)
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistTracker.start(SourceFile:181)
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.hls.HlsMediaSource.prepareSource(SourceFile:330)
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.prepareInternal(SourceFile:396)
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:289)
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:103)
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:214)
12-01 17:38:05.273  8891 16764 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

As I have no source code of netease apk, I just download the source code of exoplayer 2.7.0. After check the source code, I found that only DashDownloadTest will call CacheDataSourceFactory. But DashDownloadTest is in the gts, I don't think the apk will call gts to implement the video play feature. So why it will call into CacheDataSourceFactory? and why the cache is null? Would you please give a help? Thank you.

```
protected void setUp() throws Exception {
    super.setUp();
    testRunner = new DashTestRunner(TAG, getActivity(), getInstrumentation())
        .setManifestUrl(DashTestData.H264_MANIFEST)
        .setFullPlaybackNoSeeking(true)
        .setCanIncludeAdditionalVideoFormats(false)
        .setAudioVideoFormats(DashTestData.AAC_AUDIO_REPRESENTATION_ID,
            DashTestData.H264_CDD_FIXED);
    tempFolder = Util.createTempDirectory(getActivity(), "ExoPlayerTest");
    cache = new SimpleCache(tempFolder, new NoOpCacheEvictor());
  }

private CacheDataSourceFactory newOfflineCacheDataSourceFactory() {
    return new CacheDataSourceFactory(cache, DummyDataSource.FACTORY,
        CacheDataSource.FLAG_BLOCK_ON_CACHE);
  }
```
   I also attached the logcat, please have a check.

BR
[vfmw_logcat.log](https://github.com/google/ExoPlayer/files/7653201/vfmw_logcat.log)
,

**Comment by marcbaechinger** [comment]
The reason why you can find this only in the `DashDownloadTest` is probably because it is the app that sets up caching as part of the app. So this looks like to be an app issue rather than an ExoPlayer issue. Version 2.7.0 is from 2018 so even if that app doesn't seem to be reasonably maintained, the only thing that would help is contacting the people from netease. I can't help you any further I'm afraid.
