### ISSUE TITLE
ExoPlayerImplInternal: Playback error

### ISSUE THREAD

**Issue by mateng3399** [google/ExoPlayer#9758]
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
    
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:383)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)

**Comment by marcbaechinger** [comment]
An HTTP response code 404 indicates that the resource is not found on the server side. ExoPlayer is correctly showing the reason why this URI you want to play is not working. Please  verify whether the URI is correct or contact the server administrator if you think the URI should work. There is nothing we can do about it.
