### ISSUE TITLE
Failed to initialize OMX.MTK.VIDEO.DECODER.AVC, error 0xfffffff4

### ISSUE THREAD

**Issue by AnkitKumarMaurya** [google/ExoPlayer#9791]
```
W/MediaCodecRenderer: Failed to initialize decoder: OMX.MTK.VIDEO.DECODER.AVC
    android.media.MediaCodec$CodecException: Failed to initialize OMX.MTK.VIDEO.DECODER.AVC, error 0xfffffff4
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1864)
        at android.media.MediaCodec.createByCodecName(MediaCodec.java:1842)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:840)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:775)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:511)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1174)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:635)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:729)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:643)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

I am getting this error for some devices only and also for some specific videos . After getting this exception Exo player showing black screen for every. It is working when reopen app. I am using 2.10.0 version

**Comment by christosts** [comment]
From the stack trace, it looks like the AVC decoder instance is leaked; likely it has been acquired and not released properly by another playback attempt. I can't provide more info from this stack trace, it could be that your app is not releasing player instances properly, or some other app is holding the decoders. To better assist we would need more information about your use-case, and ideally bugreports obtained from devices right after the failure occurs.

Some general guidelines that may help:
- is the issue reproducible with the ExoPlayer demo app on the specific device when playing the specific content?
- regarding releasing the player (and any acquired decoder instances): have you followed the [demo app](https://github.com/google/ExoPlayer/blob/r2.10.0/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java) example to ensure the player is released?
