### ISSUE TITLE
Uri FileNotFoundException

### ISSUE THREAD

**Issue by ponthamaya** [google/ExoPlayer#9807]
• ExoPlayer 2.16.1 Demo project
• Android 10
• Android OnePlus 6T

I got this error when I play video from gallery. Even I gave storage permission i it's throwing this. 

```
2021-12-19 18:46:16.664 23569-23569/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=3.07, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /storage/emulated/0/ADM/(2021) mmm (Org Vers) HDRip x264 MP3 700MB ESub.mkv: open failed: EACCES (Permission denied)
        at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:197)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:108)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.FileNotFoundException: /storage/emulated/0/ADM/(2021) mmm (Org Vers) HDRip x264 MP3 700MB ESub.mkv: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
        at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:178)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:108) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7302)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289) 
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152) 
        at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:178) 
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:108) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
    ]
2021-12-19 18:46:16.672 23569-23612/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:628)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /storage/emulated/0/ADM/(2021) mmm (Org Vers) HDRip x264 MP3 700MB ESub.mkv: open failed: EACCES (Permission denied)
        at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:197)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:108)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.FileNotFoundException: /storage/emulated/0/ADM/(2021) mmm (Org Vers) HDRip x264 MP3 700MB ESub.mkv: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
        at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:178)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:108) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7302)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289) 
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152) 
        at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:178) 
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:108) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
  ```

**Comment by marcbaechinger** [comment]
If this is on Android 10 only, then you can try to set

`android:requestLegacyExternalStorage="true"`

in the manifest. Can you try this out and respond here if that works? I see we have set this attribute in the [demo app](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/AndroidManifest.xml#L37), so it is worth trying.

It would be also helpful to know if you see this on other Android versioins as well, so if you can test with API 28 or API 30 as well, this would be great. Permission to accessing general storage files have change from 28 to 30 so if you want to make sure it works for any API levels such a test could be essential for you to know it works, or for us to investigate why it doesn't work. 

It would also informative to see the code you are using, to create the path to the file that fails to be read. So if you could provide this snippet that would be helpful for further investigation on our side.

**Comment by ponthamaya** [comment]
I just added some video receiving intent in AndroidManifast.xml and receive intent Value in Demo PlayActivity. 

Demo app is working fine on API 28, 31, 32 without adding requestLegacyExternalStorage. 


This issue only occurred in API 30. If i added android:requestLegacyExternalStorage="true then there is no issue.

**Comment by marcbaechinger** [comment]
Ok, cool. I'm closing this issue then as I understand this is solved by adding the legacy attribute for API 30.
Please reopen if you think this is needed.
