### ISSUE TITLE
 Internal track renderer error

### ISSUE THREAD

**Issue by figuresk8terkim** [google/ExoPlayer#981]
I am a starter to study about Exoplayer.
I download Zip file and build it. But When I choose mp4 file and select play button, the error is occured.

Could you please check this Error for me? I would like to implemente Exoplayer Demo app. 

Thank you

```
162	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 Internal track renderer error.
163	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor) could read the stream.
164	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
165	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
166	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
167	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
168	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at android.os.Handler.dispatchMessage(Handler.java:98)
169	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at android.os.Looper.loop(Looper.java:148)
170	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at android.os.HandlerThread.run(HandlerThread.java:61)
171	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
172	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 Caused by: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor) could read the stream.
173	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:807)
174	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:738)
175	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
176	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
177	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
178	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
179	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
180	11-24	16:20:31.538	E	21816	21894	ExoPlayerImplInternal:		 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by figuresk8terkim** [comment]
should i modify the source file to implement Demo app? I never modify the source that provided.

**Comment by figuresk8terkim** [comment]
Additionally, I implement WebM ExoPlayerDemo > Local VP Video only

**Comment by ojw28** [comment]
Whatever the media is that you're providing, we're not recognizing it as a valid WebM file. You'd have to provide sample media for us to debug this further.

**Comment by figuresk8terkim** [comment]
I attach the file that i tested in WebM App. Please debug for me
Thank you

**Comment by figuresk8terkim** [comment]
I use the mp4 file to test. Unfortunately, I cannot attach the file because its size is over 10MB and file type is mp4. So Could you please tell me how to attach the file, Or If you have any e-mail address I will send file to you by e-mail. Thank you

**Comment by ojw28** [comment]
You appear to be trying to play an MP4 file using an ExoPlayer instance where you've explicitly set it up to only have a WebmExtractor. That's not going to work. Please try adding your sample directly to the ExoPlayer demo app's `Samples.java`, without making other modifications. I suspect you'll find that playback is successful in that case. If not, please let us know. Thanks!
