### ISSUE TITLE
HSS + Playready + Dolby Bug in Android 10

### ISSUE THREAD

**Issue by stillping** [google/ExoPlayer#9826]
Playback fails in Android TV device due to `NullPointerException` when trying to play `VOD HSS asset` with `Playready` protection that contains an `audio track Dolby Surround 5.1/EAC3.` The issue is reproducible only when the device has `Android 10`

<img width="1000" alt="Screenshot 2021-12-31 at 11 46 59" src="https://user-images.githubusercontent.com/1597488/147821806-c7253d15-97d3-4abe-8532-2ddcc3504630.png">

```
2021-12-31 10:03:33.047 9651-9651/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=0.70, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_UNSPECIFIED
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:612)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.NullPointerException
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:154)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:856)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:662)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:739)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:640)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1842)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:780)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    ]
```
We were able to replicate the issue with following set up

### Environment
We were able to reproduce the issue by using one of these AndroidTV devices connected to one of these TVs
#### AndroidTV devices:

- MagentaTV ONE (G6) with Android 10. We were not able to replicate this issue on Android 9 Magenta TV Stick.
- Chromecast 2020 ’Sabrina’ with Android 10

#### TV:

- Samsung TV - 2018, Model: UE32N5300, LED TV (non 4K model)
- Sony Bravia KD-32W800 ( braviatl.10006 )

### Reproduction Steps
- Compile and open Exoplayer demo app from the provided branch
- Expand _Bug Under Investigation Assets_ section
- Select _Smooth, PlayReady, Dolby 5.1 - not working_ asset

#### Expected behavior
Playback works normally

#### Actual behavior
Playback doesn't start and error is reported 

### Notes
The same content is provided as a VOD DASH with same characteristics ( Playready, containing Dolby Surround 5.1/EAC3 track). This is working fine

After extensive testing, we believe this is an Android 10 + HSS bug only being surfaced on particular TVs. 

We were able to replicate the issue with devices described above using Exoplayer's release V2 (r2.16.1) demo app. A branch is available where new assets URI have been added to the `media.exolist.json` file in order too reproduce the issue.
https://github.com/stillping/ExoPlayer/tree/hss_dolby_issue

### Test Output
- [adb bugreport](https://github.com/google/ExoPlayer/files/7796081/bugreport-HP4409-DT-G-QTT8.201201.004-2021-12-30-17-12-56.zip)
- [logcat.txt](https://github.com/google/ExoPlayer/files/7796082/logcat.txt)

**Comment by ojw28** [comment]
Thanks for the clear reproduction steps. The issue seems to be caused by the existence of `CodecPrivateData` in the EC-3 stream, as declared in the SmoothStreaming manifest:
```
CodecPrivateData="00063F000000AF87FBA7022DFB42A4D405CD93843BDD0600200F00"
```
Ignoring it allows playback to succeed. What I'm unclear on is whether:
1. It's a content issue, because `CodecPrivateData` should not be specified for this track
2. It's an ExoPlayer issue, because ExoPlayer should ignore the `CodecPrivateData`
3. It's an ExoPlayer issue, because ExoPlayer should correctly handle the `CodecPrivateData`

Do you happen to know:

1. Where the correct value of `CodecPrivateData` is defined for EC-3. The SmoothStreaming specification states that for audio streams this should be set to the "extra codec-specific information appended to the end of the WAVEFORMATEX structure", but I can't find where this extra codec-specific information is actually defined for EC-3.
2. If you believe that the `CodecPrivateData` is correct, where is this data contained within the DASH example that's working correctly, if anywhere?

Thanks!

**Comment by stillping** [comment]
Exoplayer have replied with this:

Thanks for the clear reproduction steps. The issue seems to be caused by the existence of CodecPrivateData in the EC-3 stream, as declared in the SmoothStreaming manifest:

```
CodecPrivateData="00063F000000AF87FBA7022DFB42A4D405CD93843BDD0600200F00"
```

Ignoring it allows playback to succeed. What I'm unclear on is whether:

- It's a content issue, because CodecPrivateData should not be specified for this track
- It's an ExoPlayer issue, because ExoPlayer should ignore the CodecPrivateData
- It's an ExoPlayer issue, because ExoPlayer should correctly handle the CodecPrivateData

Do you happen to know:
- Where the correct value of CodecPrivateData is defined for EC-3. The SmoothStreaming specification states that for audio streams this should be set to the "extra codec-specific information appended to the end of the WAVEFORMATEX structure", but I can't find where this extra codec-specific information is actually defined for EC-3.
-  If you believe that the CodecPrivateData is correct, where is this data contained within the DASH example that's working correctly, if anywhere?

Thanks!
