### ISSUE TITLE
Exoplayer error rendering uri local phone

### ISSUE THREAD

**Issue by hafiz013** [google/ExoPlayer#9836]
-why when 1 time load local video work properly but i want to reupload again get this error

```
2022-01-05 15:05:26.257 20703-23129/ E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, null, -1, null, [720, 720, 29.467085], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:226)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(2, null, null, video/avc, null, -1, null, [720, 720, 29.467085], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1052)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:609)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1480)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:999)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:849)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:226) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2024)
        at android.media.MediaCodec.configure(MediaCodec.java:1952)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.configure(SynchronousMediaCodecAdapter.java:43)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:580)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1148)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1045)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:609) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1480) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:999) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:849) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:226) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```
and get this error from rendering : 

```
ErrorVideo: com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, null, -1, null, [720, 720, 29.467085], [-1, -1]), format_supported=YES.rendererException.message
```

So how to solve this rendering error? because sometimes it work and sometime is not work.

Below here sample mycode:

```
import android.content.Context
import android.database.ContentObserver
import android.media.AudioManager
import android.net.Uri
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.ImageView
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import com.google.android.exoplayer2.ExoPlaybackException
import com.google.android.exoplayer2.MediaItem
import com.google.android.exoplayer2.Player
import com.google.android.exoplayer2.SimpleExoPlayer
import com.google.android.exoplayer2.ui.StyledPlayerView
import com.nibmeetings.android.R
import com.nibmeetings.android.ui.postCaption.AddCaptions
import timber.log.Timber

class VideoFragment : Fragment() {
    private lateinit var mContext: Context
    private var uri: Uri? = null
    var imgVolumeController:ImageView? = null
    var videoViewFeed: StyledPlayerView? = null
    var currentVideoVolume = 10f
    var isMuted = true
    var player: SimpleExoPlayer? = null
    var v:View? =  null
    private var layoutVideoViewOnClickContainer:View? = null
    private lateinit var mSettingsContentObserver: SettingsSound

    override fun onAttach(context: Context) {
        super.onAttach(context)

        mContext = context
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        arguments?.let {
            uri = it.getParcelable("uri")
        }
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        v = inflater.inflate(R.layout.fragment_video, container, false)

        videoViewFeed = v?.findViewById(R.id.videoViewFeed)
        layoutVideoViewOnClickContainer = v?.findViewById(R.id.layoutVideoViewOnClickContainer)
        imgVolumeController = v?.findViewById(R.id.imgVolumeController)

        initializePlayer()

        player?.addListener(object:Player.EventListener{
            override fun onPlayerError(error: ExoPlaybackException) {
                when(error.type){
                    ExoPlaybackException.TYPE_SOURCE -> {
                        Toast.makeText(mContext, "source:$error.sourceException.message", Toast.LENGTH_SHORT).show()
                        Timber.d("ErrorVideo: $error.sourceException.message")
                    }
                    ExoPlaybackException.TYPE_RENDERER ->{
                        Toast.makeText(mContext, "render: $error.rendererException.message", Toast.LENGTH_SHORT).show()
                        Timber.d("ErrorVideo: $error.rendererException.message")
                    }
                    ExoPlaybackException.TYPE_UNEXPECTED ->{
                        Toast.makeText(mContext, "unexpected: $error.unexpectedException.message", Toast.LENGTH_SHORT).show()
                        Timber.d("ErrorVideo: $error.unexpectedException.message")
                    }
                }

                videoViewFeed?.player?.stop()
                releasePlayer()
                initializePlayer()

                super.onPlayerError(error)
            }

            override fun onPlayWhenReadyChanged(playWhenReady: Boolean, reason: Int) {
                super.onPlayWhenReadyChanged(playWhenReady, reason)
            }
        })
        imgVolumeController?.setOnClickListener {
            if (isMuted) {
                //Set to Un-mute
                imgVolumeController?.setImageDrawable(ContextCompat.getDrawable(mContext, R.drawable.ic_unmute_feed))
                player?.volume = currentVideoVolume
                isMuted = false
            }
            else {
                //Set to mute
                imgVolumeController?.setImageDrawable(ContextCompat.getDrawable(mContext, R.drawable.ic_mute_feed))
                player?.volume = 0f
                isMuted = true
            }
        }

        layoutVideoViewOnClickContainer?.setOnClickListener{
            if (player?.isPlaying == true) {
                player?.pause()
            }
            else {
                player?.play()
            }
        }

        registerVolume()

        return v
    }

    fun initializePlayer(){
        uri?.let{
            player  = SimpleExoPlayer.Builder(mContext).build().apply {
                setMediaItem(MediaItem.fromUri(it))
                repeatMode = Player.REPEAT_MODE_ONE
                prepare()
                playWhenReady = true
                volume = 0f
            }
            videoViewFeed?.player = player
            videoViewFeed?.hideController()
            videoViewFeed?.controllerAutoShow = false
            videoViewFeed?.useController = false
        }
    }

    override fun onPause() {
        super.onPause()

        if(videoViewFeed?.player?.isPlaying == true){
            Toast.makeText(mContext, "pause play", Toast.LENGTH_SHORT).show()
            videoViewFeed?.player?.pause()
        }
    }

    override fun onResume() {
        super.onResume()

        if(videoViewFeed?.player?.isPlaying != true){
            Toast.makeText(mContext, "resume play", Toast.LENGTH_SHORT).show()
            videoViewFeed?.player?.play()
        }
    }

    override fun onDestroy() {
        removeRegisterVolume()
        releasePlayer()
        super.onDestroy()
    }

    private fun registerVolume(){
        mSettingsContentObserver = SettingsSound(
            mContext,
            Handler(Looper.myLooper()!!), currentVideoVolume
        )
        mContext.contentResolver.registerContentObserver(android.provider.Settings.System.CONTENT_URI, true, mSettingsContentObserver)
    }

    private fun removeRegisterVolume(){
        mContext.contentResolver.unregisterContentObserver(mSettingsContentObserver)
    }

    private fun releasePlayer() {
        if (videoViewFeed?.player != null) {
           /* player?.stop()
            player?.release()
            player = null*/
            videoViewFeed?.player?.release()
            videoViewFeed?.player = null
            videoViewFeed = null
            player = null
            Toast.makeText(mContext, "destroy play", Toast.LENGTH_SHORT).show()
        }
    }

    class SettingsSound(var context: Context, handler: Handler?, var currentV:Float) : ContentObserver(handler) {
        var audioManager: AudioManager = context.getSystemService(AppCompatActivity.AUDIO_SERVICE) as AudioManager

        override fun deliverSelfNotifications(): Boolean {
            return false
        }

        override fun onChange(selfChange: Boolean) {
            super.onChange(selfChange)

            val currentVolume = audioManager.getStreamVolume(AudioManager.STREAM_MUSIC)
            currentV = currentVolume.toFloat()
        }
    }
}
```

i using this player  version 

```
    implementation 'com.google.android.exoplayer:exoplayer:2.12.3'
    implementation 'com.google.android.exoplayer:exoplayer-core:2.12.3'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.12.3'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.12.3'`
```

**Comment by ojw28** [comment]
If you'd like us to spend time investigating your issue, please properly fill out the issue template. Thanks.

**Comment by hafiz013** [comment]
@ojw28 can share the template please

**Comment by hafiz013** [comment]
but i wonder if using videoview (native android) working properly. below here is my code:

`class VideoFragment : Fragment() {
    private lateinit var mContext: Context
    private var uri: Uri? = null
    private var mediaPlayer:MediaPlayer? = null
    var imgVolumeController:ImageView? = null
    var videoView:VideoView? = null
    var currentVideoVolume = 30f
    var v:View? =  null
    var isMuted = true
    private var layoutVideoViewOnClickContainer:View? = null
    private lateinit var mSettingsContentObserver: SettingsSound

    override fun onAttach(context: Context) {
        super.onAttach(context)

        mContext = context
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        arguments?.let {
            uri = it.getParcelable("uri")
        }
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        v = inflater.inflate(R.layout.fragment_video, container, false)

        //videoViewFeed = v?.findViewById(R.id.videoViewFeed)
        videoView = v?.findViewById(R.id.videoView)

        layoutVideoViewOnClickContainer = v?.findViewById(R.id.layoutVideoViewOnClickContainer)
        imgVolumeController = v?.findViewById(R.id.imgVolumeController)

        initializePlayer()

        imgVolumeController?.setOnClickListener {
            try {
                isMuted = if (isMuted) {
                    //Set to Un-mute
                    imgVolumeController?.setImageDrawable(
                        ContextCompat.getDrawable(
                            mContext,
                            R.drawable.ic_unmute_feed
                        )
                    )
                    this.unmute()
                    false
                } else {
                    //Set to mute
                    imgVolumeController?.setImageDrawable(
                        ContextCompat.getDrawable(
                            mContext,
                            R.drawable.ic_mute_feed
                        )
                    )
                    this.mute()
                    true
                }
            }catch (e:Exception){

            }catch (e:IllegalStateException){

            }
        }

        layoutVideoViewOnClickContainer?.setOnClickListener{
            if(videoView?.isPlaying == true){
                videoView?.pause()
            }else{
                videoView?.start()
            }
        }

        registerVolume()

        return v
    }

    fun initializePlayer(){
        uri?.let{
            videoView?.setOnPreparedListener { its->
                this.mediaPlayer = its
                mute()
                its.isLooping = true
            }
            videoView?.setVideoURI(it)
            videoView?.start()
        }
    }

    fun mute(){
        this.setVolume(0)
    }

    fun unmute(){
        setVolume(100)
    }

    fun setVolume(amount:Int){
        val max = 100
        val numerator: Double = if (max - amount > 0) ln((max - amount).toDouble()) else 0.0
        val volume = (1 - numerator / Math.log(max.toDouble())).toFloat()

        try {
            this.mediaPlayer?.setVolume(volume, volume)
        }catch (e:Exception){

        }catch (e:java.lang.IllegalStateException){

        }
    }

    override fun onPause() {
        super.onPause()

        if(videoView?.isPlaying == true){
            videoView?.pause()
        }

    }

    override fun onResume() {
        super.onResume()

        if(videoView?.isPlaying != true){
            if(!isMuted){
                this.unmute()
            }
            videoView?.start()
        }
    }

    override fun onDestroy() {
        removeRegisterVolume()
        releasePlayer()
        super.onDestroy()
    }

    private fun registerVolume(){
        mSettingsContentObserver = SettingsSound(
            mContext,
            Handler(Looper.myLooper()!!), currentVideoVolume
        )
        mContext.contentResolver.registerContentObserver(android.provider.Settings.System.CONTENT_URI, true, mSettingsContentObserver)
    }

    private fun removeRegisterVolume(){
        mContext.contentResolver.unregisterContentObserver(mSettingsContentObserver)
    }

    private fun releasePlayer() {
        if(videoView != null){
            videoView?.stopPlayback()
        }
    }

    class SettingsSound(var context: Context, handler: Handler?, var currentV:Float) : ContentObserver(handler) {
        var audioManager: AudioManager = context.getSystemService(AppCompatActivity.AUDIO_SERVICE) as AudioManager

        override fun deliverSelfNotifications(): Boolean {
            return false
        }

        override fun onChange(selfChange: Boolean) {
            super.onChange(selfChange)

            val currentVolume = audioManager.getStreamVolume(AudioManager.STREAM_MUSIC)
            currentV = currentVolume.toFloat()
        }
    }
}`

**Comment by ojw28** [comment]
Closing because the issue template was not filled out, and because it's beyond the scope of this issue tracker to read through large amounts of your own application code. The issue template can be found here: https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=.
