### ISSUE TITLE
STATE_BUFFERING problem

### ISSUE THREAD

**Issue by don11995** [google/ExoPlayer#984]
Ok, I'm returning to my problem that ExoPlayer freezes on STATE_BUFFERING state. For test I'm using next stream: http://brodilo.tv/channel.php. 
Every 3-5 minutes, there is advertising that redirects us to other stream. I'm not trying to solve the problem with redirection, it was decided to make the following logic: when the stream switches or empty frames appear, start playing stream again. But ExoPlayer at the moment when stream switches on advertising, just switches to the state STATE_BUFFERING, and stays there forever. How do I determine that another stream occurred and re-open it? STATE_ENDED also never occurs, only buffering. Sometimes during the STATE_BUFFERING the following error occurs:
```
Unexpected exception loading stream
                                                                java.lang.IllegalArgumentException
                                                                    at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                                                                    at com.google.android.exoplayer.util.ParsableByteArray.setPosition(ParsableByteArray.java:116)
                                                                    at com.google.android.exoplayer.util.ParsableByteArray.skipBytes(ParsableByteArray.java:127)
                                                                    at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:140)
                                                                    at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:745)
                                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                    at java.lang.Thread.run(Thread.java:818)
```

**Comment by ojw28** [comment]
The Elementary PID of each the individual streams (e.g. audio/video) is changing at the ad insertion points, which we don't handle currently. It's possible to hack around inside ExoPlayer to handle this case (see below), but I'm not sure it's something we want to do, and it may well cause issues with other streams. The best solution would be to have your server ensure that the Elementary PIDs do not change at ad insertion points.

-------------

If you do want to hack around in ExoPlayer, I think the following changes in TsExtractor fix things to work with your stream:

- Change `streamTypes` to be a `SparseArray<TsPayloadReader>`
- Change [this block](https://github.com/google/ExoPlayer/blob/r1.5.2/library/src/main/java/com/google/android/exoplayer/extractor/ts/TsExtractor.java#L290) to perform a mapping from the new Elementary PID to the existing payload reader, like:
```
if (streamTypes.get(streamType) != null) {
  if (tsPayloadReaders.get(elementaryPid) == null) {
    Log.e(TAG, "Remapping\t" + streamType);
    tsPayloadReaders.put(elementaryPid, streamTypes.get(streamType));
  }
  continue;
}
```
- Change [this block](https://github.com/google/ExoPlayer/blob/r1.5.2/library/src/main/java/com/google/android/exoplayer/extractor/ts/TsExtractor.java#L323) to be:
```
if (pesPayloadReader != null) {
  PesReader payloadReader = new PesReader(pesPayloadReader);
  streamTypes.put(streamType, payloadReader);
  tsPayloadReaders.put(elementaryPid, payloadReader);
}
```
