### ISSUE TITLE
Subtitle Track not detected in HLS Manifest

### ISSUE THREAD

**Issue by davepotts** [google/ExoPlayer#9847]
Hello,

Firstly thank you for providing this library. I really appreciate your work

I'm encountering an issue where Exoplayer does not detect the subtitle text track in our streams. using event logger I can see that audio and video are detected correctly however the `TextRenderer [] ` is empty.  The text track is correctly rendered when loading the stream in both VLC and Shaka player.

I will email a stream link to you.

my exoplayer configuration is basic, using only standard apis and im using 2.16.1

```
class VideoPlayer(context: Context, attrs: AttributeSet? = null) : StyledPlayerView(context, attrs){
        useArtwork = false
        useController = true
        setShowBuffering(SHOW_BUFFERING_NEVER)
        resizeMode = RESIZE_MODE_FIT

        val defaultLoadControl = DefaultLoadControl()
        val trackSelector = DefaultTrackSelector(context)
        trackSelector.parameters = trackSelector.buildUponParameters()
            .setPreferredTextLanguage(Locale.getDefault().language)
            .setPreferredAudioLanguage(Locale.getDefault().language)
            .setSelectUndeterminedTextLanguage(true)
            .build()

        player = ExoPlayer.Builder(context).setLoadControl(defaultLoadControl)
            .setTrackSelector(trackSelector).build()
        player.videoScalingMode = C.VIDEO_SCALING_MODE_SCALE_TO_FIT
        player.repeatMode = Player.REPEAT_MODE_OFF
        player.playWhenReady = true
        player.addAnalyticsListener(EventLogger(trackSelector))
        player.addListener(playerListener)
        setPlayer(player)
        player.setMediaItem(MediaItem.Builder()
            .setUri(STREAM_URI)
            .build())
        player.prepare()
}
```

Have I misconfigured the player in any way?

**Comment by icbaker** [comment]
The playlist provided over email does not play on my device - I get HTTP 403 errors and then a `SocketTimeoutException`:
```
E/EventLogger: internalError [eventTime=4.33, mediaPos=0.00, window=0, loadError
      com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:719)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
    ]
E/EventLogger: internalError [eventTime=14.34, mediaPos=0.00, window=0, loadError
      com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: java.net.SocketTimeoutException
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:676)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.net.SocketTimeoutException
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:672)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
    ]
```

Is this content geo-blocked? Please provide media that is globally accessible to allow us to reproduce the problem.

**Comment by davepotts** [comment]
Hi Ian,. Unfortunately our streaming platform provider is having an issue where the stream throws not found for a few seconds while it provisions the chunks to the CDN,


If you run the stream initially for c.10 seconds it will eventually start. Subsequent recurring plays will not experience the issue while the content is accessed. The CDN cache files are cleared after 1 hour of non-vewership

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by icbaker** [comment]
I tried playing the stream 4 times in a row (over a period of a few minutes) and every time playback failed to start due to timeout exceptions.
