### ISSUE TITLE
Unable to play https streams

### ISSUE THREAD

**Issue by colorgold** [google/ExoPlayer#9851]
I tried playing the following stream URL:
`https://centova.hostingtico.com:7006/stream`
I am able to play it on a browser, but I can't play it on Android using ExoPlayer. The error I get is:
`Source error`
and nothing more. There have been other streams that cannot play because they start with `https`, so I would remove the `s` and it would play successfully. However, this one does not exist without the `s`. 
I used the following code:
```
final String streamUrl = "https://centova.hostingtico.com:7006/stream"
ExoPlayer player = new ExoPlayer.Builder(context).build();
        player.addListener(new Player.Listener() {
            @Override
            public void onPlaybackStateChanged(int state) {
                if (state == Player.STATE_ENDED ) {
                    sendBroadcastIntent(STATE_ENDED, id);
                } else if (state == Player.STATE_BUFFERING) {
                    sendBroadcastIntent(STATE_BUFFERING, id);
                }
            }

            @Override
            public void onIsPlayingChanged(boolean isPlaying) {
                if (isPlaying) {
                    sendBroadcastIntent(STATE_PLAYING, id);
                }
                else{
                    sendBroadcastIntent(STATE_ENDED, id);
                }
            }

            @Override
            public void onPlayerError(@NonNull PlaybackException error) {
                Log.d(TAG, "exoplayer onPlayerError: " + error.getMessage());
                sendBroadcastIntent(STATE_ERROR, id);
            }

        });

        MediaItem mediaItem = MediaItem.fromUri(Uri.parse(streamUrl));
        player.setMediaItem(mediaItem);
        player.prepare();
        player.setPlayWhenReady(true);
```

I found a previous report of this problem, but it has been closed and the solution does not apply to my case.

**Comment by icbaker** [comment]
I tried the provided URL in the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html). The stacktrace logged to logcat shows it fails due to a TLS certificate problem:

```
2022-01-11 10:22:16.394 11001-11001/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=4.03, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_IO_NETWORK_CONNECTION_FAILED
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:628)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:245)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: es: Exception in CronetUrlRequest: net::ERR_CERT_AUTHORITY_INVALID, ErrorCode=11, InternalErrorCode=-202, Retryable=false
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:669)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: es: Exception in CronetUrlRequest: net::ERR_CERT_AUTHORITY_INVALID, ErrorCode=11, InternalErrorCode=-202, Retryable=false
        at org.chromium.net.impl.CronetUrlRequest.onError(:com.google.android.gms.dynamite_cronetdynamite@213016097@21.30.16 (150400-0):4)
    ]
2022-01-11 10:22:16.395 11001-11001/com.google.android.exoplayer2.demo D/EventLogger: loading [eventTime=4.04, mediaPos=0.00, window=0, period=0, false]
2022-01-11 10:22:16.397 11001-11001/com.google.android.exoplayer2.demo D/EventLogger: state [eventTime=4.04, mediaPos=0.00, window=0, period=0, IDLE]
```

Switching the demo app to use the built-in network stack instead of Cronet gives a similar stack trace:

```
2022-01-11 10:26:29.778 11004-11004/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=4.03, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_IO_NETWORK_CONNECTION_FAILED
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:628)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:245)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:365)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
        at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
```

You can find more info about this problem here (and the Android docs linked from there): https://exoplayer.dev/troubleshooting.html#fixing-sslhandshakeexception-and-certpathvalidatorexception-errors

----
> The error I get is: `Source error` and nothing more.

This is because here you're logging only the top-level exception message and discarding the stack trace and any cause exceptions:
```
@Override
public void onPlayerError(@NonNull PlaybackException error) {
  Log.d(TAG, "exoplayer onPlayerError: " + error.getMessage());
  sendBroadcastIntent(STATE_ERROR, id);
}
```
---

**Comment by colorgold** [comment]
> I tried the provided URL in the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html). The stacktrace logged to logcat shows it fails due to a TLS certificate problem:
> 
> ```
> 2022-01-11 10:22:16.394 11001-11001/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=4.03, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_IO_NETWORK_CONNECTION_FAILED
>       com.google.android.exoplayer2.ExoPlaybackException: Source error
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:628)
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:245)
>         at android.os.HandlerThread.run(HandlerThread.java:67)
>      Caused by: com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: es: Exception in CronetUrlRequest: net::ERR_CERT_AUTHORITY_INVALID, ErrorCode=11, InternalErrorCode=-202, Retryable=false
>         at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:669)
>         at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
>         at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
>         at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
>         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
>         at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
>         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:923)
>      Caused by: es: Exception in CronetUrlRequest: net::ERR_CERT_AUTHORITY_INVALID, ErrorCode=11, InternalErrorCode=-202, Retryable=false
>         at org.chromium.net.impl.CronetUrlRequest.onError(:com.google.android.gms.dynamite_cronetdynamite@213016097@21.30.16 (150400-0):4)
>     ]
> 2022-01-11 10:22:16.395 11001-11001/com.google.android.exoplayer2.demo D/EventLogger: loading [eventTime=4.04, mediaPos=0.00, window=0, period=0, false]
> 2022-01-11 10:22:16.397 11001-11001/com.google.android.exoplayer2.demo D/EventLogger: state [eventTime=4.04, mediaPos=0.00, window=0, period=0, IDLE]
> ```
> 
> Switching the demo app to use the built-in network stack instead of Cronet gives a similar stack trace:
> 
> ```
> 2022-01-11 10:26:29.778 11004-11004/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=4.03, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_IO_NETWORK_CONNECTION_FAILED
>       com.google.android.exoplayer2.ExoPlaybackException: Source error
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:628)
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:245)
>         at android.os.HandlerThread.run(HandlerThread.java:67)
>      Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
>         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:365)
>         at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
>         at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
>         at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
>         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
>         at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
>         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:923)
>      Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
>         at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
>         at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
> ```
> 
> You can find more info about this problem here (and the Android docs linked from there): https://exoplayer.dev/troubleshooting.html#fixing-sslhandshakeexception-and-certpathvalidatorexception-errors
> 
> > The error I get is: `Source error` and nothing more.
> 
> This is because here you're logging only the top-level exception message and discarding the stack trace and any cause exceptions:
> 
> ```
> @Override
> public void onPlayerError(@NonNull PlaybackException error) {
>   Log.d(TAG, "exoplayer onPlayerError: " + error.getMessage());
>   sendBroadcastIntent(STATE_ERROR, id);
> }
> ```

Thank you for the information! I was able to acquire a different URL that would work because as you mentioned, the TLS certificate was the problem.
