### ISSUE TITLE
MediaDrmStateException throws OfflineLicenseHelper.renewLicense()

### ISSUE THREAD

**Issue by ogawa-ma** [google/ExoPlayer#9852]
■ environment
ExoPlayer : 2.16.1
Device : Pixel3
OS : Android12

I get the following error when trying to renew my Widevine license using OfflineLicenseHelper.renewLicense.

```
2022-01-12 19:06:29.478 13906-13994/com.google.android.exoplayer2.demo E/MediaDrm-JNI: Illegal state exception: Failed to get key request: ERROR_DRM_UNKNOWN
    ============================== Beginning of DRM Plugin Log ==============================
      01-12 19:04:39.826 I found instance=clearkey version=android.hardware.drm@1.4::IDrmFactory
      01-12 19:04:39.826 I found instance=default version=android.hardware.drm@1.0::IDrmFactory
      01-12 19:04:39.826 I found instance=widevine version=android.hardware.drm@1.3::IDrmFactory
      01-12 19:04:41.341 W Cannot cast android.hardware.drm@1.0::IDrmPlugin obj to android.hardware.drm@1.4::IDrmPlugin plugin
      01-12 19:06:29.478 W Cannot cast android.hardware.drm@1.0::IDrmPlugin obj to android.hardware.drm@1.4::IDrmPlugin plugin
    ============================== End of DRM Plugin Log ============================== (-2000)
2022-01-12 19:06:29.479 13906-13994/com.google.android.exoplayer2.demo E/DefaultDrmSession: DRM session error
      android.media.MediaDrm$MediaDrmStateException: Failed to get key request: ERROR_DRM_UNKNOWN
      ============================== Beginning of DRM Plugin Log ==============================
        01-12 19:04:39.826 I found instance=clearkey version=android.hardware.drm@1.4::IDrmFactory
        01-12 19:04:39.826 I found instance=default version=android.hardware.drm@1.0::IDrmFactory
        01-12 19:04:39.826 I found instance=widevine version=android.hardware.drm@1.3::IDrmFactory
        01-12 19:04:41.341 W Cannot cast android.hardware.drm@1.0::IDrmPlugin obj to android.hardware.drm@1.4::IDrmPlugin plugin
        01-12 19:06:29.478 W Cannot cast android.hardware.drm@1.0::IDrmPlugin obj to android.hardware.drm@1.4::IDrmPlugin plugin
      ============================== End of DRM Plugin Log ==============================
        at android.media.MediaDrm.getKeyRequestNative(Native Method)
        at android.media.MediaDrm.getKeyRequest(MediaDrm.java:1580)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:203)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:477)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:442)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:312)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:782)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:683)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:565)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:511)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.openBlockingKeyRequest(OfflineLicenseHelper.java:284)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.blockingKeyRequest(OfflineLicenseHelper.java:267)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.renewLicense(OfflineLicenseHelper.java:207)
        at com.google.android.exoplayer2.demo.DownloadTracker$WidevineOfflineLicenseFetchTask.doInBackground(DownloadTracker.java:405)
        at com.google.android.exoplayer2.demo.DownloadTracker$WidevineOfflineLicenseFetchTask.doInBackground(DownloadTracker.java:369)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
2022-01-12 19:06:29.492 13906-13906/com.google.android.exoplayer2.demo E/DownloadTracker: Failed to fetch offline DRM license
      com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: ERROR_DRM_UNKNOWN
      ============================== Beginning of DRM Plugin Log ==============================
        01-12 19:04:39.826 I found instance=clearkey version=android.hardware.drm@1.4::IDrmFactory
        01-12 19:04:39.826 I found instance=default version=android.hardware.drm@1.0::IDrmFactory
        01-12 19:04:39.826 I found instance=widevine version=android.hardware.drm@1.3::IDrmFactory
        01-12 19:04:41.341 W Cannot cast android.hardware.drm@1.0::IDrmPlugin obj to android.hardware.drm@1.4::IDrmPlugin plugin
        01-12 19:06:29.478 W Cannot cast android.hardware.drm@1.0::IDrmPlugin obj to android.hardware.drm@1.4::IDrmPlugin plugin
      ============================== End of DRM Plugin Log ==============================
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:540)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:530)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:481)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:442)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:312)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:782)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:683)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:565)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:511)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.openBlockingKeyRequest(OfflineLicenseHelper.java:284)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.blockingKeyRequest(OfflineLicenseHelper.java:267)
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.renewLicense(OfflineLicenseHelper.java:207)
        at com.google.android.exoplayer2.demo.DownloadTracker$WidevineOfflineLicenseFetchTask.doInBackground(DownloadTracker.java:405)
        at com.google.android.exoplayer2.demo.DownloadTracker$WidevineOfflineLicenseFetchTask.doInBackground(DownloadTracker.java:369)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: ERROR_DRM_UNKNOWN
      ============================== Beginning of DRM Plugin Log ==============================
        01-12 19:04:39.826 I found instance=clearkey version=android.hardware.drm@1.4::IDrmFactory
        01-12 19:04:39.826 I found instance=default version=android.hardware.drm@1.0::IDrmFactory
        01-12 19:04:39.826 I found instance=widevine version=android.hardware.drm@1.3::IDrmFactory
        01-12 19:04:41.341 W Cannot cast android.hardware.drm@1.0::IDrmPlugin obj to android.hardware.drm@1.4::IDrmPlugin plugin
        01-12 19:06:29.478 W Cannot cast android.hardware.drm@1.0::IDrmPlugin obj to android.hardware.drm@1.4::IDrmPlugin plugin
      ============================== End of DRM Plugin Log ==============================
        at android.media.MediaDrm.getKeyRequestNative(Native Method)
        at android.media.MediaDrm.getKeyRequest(MediaDrm.java:1580)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:203)
2022-01-12 19:06:29.492 13906-13906/com.google.android.exoplayer2.demo E/DownloadTracker:     at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:477)
              ... 17 more
```

To test this, I changed the ExoPlayer sample app to the following and ran it, and it also occurred in the sample app.
```
try {
    keySetId = offlineLicenseHelper.downloadLicense(format);
    offlineLicenseHelper.renewLicense(keySetId);
} catch (DrmSession.DrmSessionException e) {
    drmSessionException = e;
} finally {
    offlineLicenseHelper.release();
}
```

There were similar issues with https://github.com/google/ExoPlayer/issues/8554, but this time the content is different and it also occurs with "Widevine DASH (MP4, H264)".
Did "Widevine DASH (MP4, H264)" policy change and no longer allow offline license updates?

**Comment by ogawa-ma** [comment]
I'm sorry. The first error log I posted was not the log generated by the sample app, so I updated it to the error log generated by the sample app.

**Comment by icbaker** [comment]
I made the same change in the ExoPlayer 2.16.1 demo app, and I also saw failures, but my 'DRM Plugin' log was different to yours and made it clear that the problem is that renewal is not allowed by the license policy [1].

I took another look at #8554 and realised that when answering that and looking at the license policies I was reading the wrong policy for the `media.exolist.json` entries like "Widevine DASH (MP4, H264)". We have some ExoPlayer-specific policies that are accessed by adding URL parameters to the license URL - these are used in [this test suite](https://github.com/google/ExoPlayer/tree/release-v2/playbacktests/src/androidTest/java/com/google/android/exoplayer2/playbacktests/gts) (the URLs are built in [`DashTestData.java`](https://github.com/google/ExoPlayer/blob/release-v2/playbacktests/src/androidTest/java/com/google/android/exoplayer2/playbacktests/gts/DashTestData.java)).

I incorrectly assumed that the same policy was being used when playing the widevine-protected samples in the demo app - but looking more carefully at the `media.exolist.json` file I see that the license URL does not have any `video_id` URL parameter. Checking the default policy used when no `video_id` is specified I see that it does not have the `can_renew` field set (i.e. neither true nor false). It's possible (unverified) that the widevine plugin version used by the reporter in #8554 treats that as 'renewable' while the ones we're using here treat it as non-renewable - which would explain the behaviour we're seeing.

The outcome is basically the same as the #8554 though - quoting from myself there:
> In general it doesn't really make sense to try and perform DRM operations like renewal on content where you don't control/know the license policy (like the samples in the demo app).
>
>If you're a Widevine partner you should reach out to them for support regarding testing different license policies. 

[1]
```
2022-01-13 11:08:32.128 1753-1753/com.google.android.exoplayer2.demo E/DownloadTracker:     at com.google.android.exoplayer2.drm.OfflineLicenseHelper.blockingKeyRequest(OfflineLicenseHelper.java:267)                                                                     
        at com.google.android.exoplayer2.drm.OfflineLicenseHelper.renewLicense(OfflineLicenseHelper.java:207)                                                                                                                                                               
        at com.google.android.exoplayer2.demo.DownloadTracker$WidevineOfflineLicenseFetchTask.doInBackground(DownloadTracker.java:407)                                                                                                                                      
        at com.google.android.exoplayer2.demo.DownloadTracker$WidevineOfflineLicenseFetchTask.doInBackground(DownloadTracker.java:370)                                                                                                                                      
        at android.os.AsyncTask$3.call(AsyncTask.java:394)                                                                                                                                                                                                                  
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                                                                                                                                         
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)                                                                                                                                                                                                    
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)                                                                                                                                                                                  
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)                                                                                                                                                                                  
        at java.lang.Thread.run(Thread.java:920)                                                                                                                                                                                                                            
     Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: ERROR_DRM_LICENSE_POLICY                                                                                                                                                          
      ============================== Beginning of DRM Plugin Log ==============================                                                                                                                                                                             
        01-12 16:43:50.925 I found instance=clearkey version=android.hardware.drm@1.4::IDrmFactory                                                                                                                                                                          
        01-12 16:43:50.925 I found instance=widevine version=android.hardware.drm@1.4::IDrmFactory                                                                                                                                                                          
        01-12 16:43:51.447 I [oemcrypto_adapter_dynamic.cpp(716):Initialize] L3 Initialized. Trying L1.                                                                                                                                                                     
        01-12 16:43:51.558 W [oemcrypto_adapter_dynamic.cpp(885):LoadLevel1] Could not load L1 _oecc109.                                                                                                                                                                    
        01-12 16:43:51.558 W [oemcrypto_adapter_dynamic.cpp(886):LoadLevel1] Could not load L1 _oecc110.                                                                                                                                                                    
        01-12 16:43:51.559 I [oemcrypto_adapter_dynamic.cpp(738):Initialize] Level 1 Build Info (v16): Build Information: API_Version: 16.3 LibOEMCrypto_Version: 1.46 TA_Version: 1.83                                                                                     
        01-12 16:43:51.562 I [usage_table_header.cpp(204):RestoreTable] Found usage table to restore: entry_count = 0                                                                                                                                                       
        01-12 16:43:51.603 I [cdm_engine.cpp(140):OpenSession] New session: session_id = sid12                                                                                                                                                                              
        01-12 16:43:51.603 I [cdm_engine.cpp(871):QueryOemCryptoSessionId] session_id = sid12                                                                                                                                                                               
        01-12 16:43:51.619 I [cdm_engine.cpp(227):GenerateKeyRequest] session_id = sid12, key_set_id = <empty>, license_type = Streaming                                                                                                                                    
        01-12 16:43:51.868 I [cdm_engine.cpp(776):QuerySessionStatus] session_id = sid12                                                                                                                                                                                    
        01-12 16:43:52.205 I [cdm_engine.cpp(306):AddKey] session_id = sid12, key_set_id = <empty>                                                                                                                                                                          
        01-12 16:43:56.757 I [cdm_engine.cpp(185):CloseSession] session_id = sid12                                                                                                                                                                                          
        01-12 16:43:56.772 I [(0):] L3 Terminate.                                                                                                                                                                                                                           
        01-12 16:43:58.188 I [oemcrypto_adapter_dynamic.cpp(702):Initialize] Level 3 Build Info (v16): OEMCrypto Level3 Code 22594 May 28 2021 16:59:07                                                                                                                     
        01-12 16:43:58.188 I [(0):] Level3 Library 22594 May 28 2021 16:59:07                                                                                                                                                                                               
        01-12 16:43:58.205 I [oemcrypto_adapter_dynamic.cpp(716):Initialize] L3 Initialized. Trying L1.                                                                                                                                                                     
        01-12 16:43:58.310 W [oemcrypto_adapter_dynamic.cpp(885):LoadLevel1] Could not load L1 _oecc109.                                                                                                                                                                    
        01-12 16:43:58.311 W [oemcrypto_adapter_dynamic.cpp(886):LoadLevel1] Could not load L1 _oecc110.                                                                                                                                                                    
        01-12 16:43:58.312 I [oemcrypto_adapter_dynamic.cpp(738):Initialize] Level 1 Build Info (v16): Build Information: API_Version: 16.3 LibOEMCrypto_Version: 1.46 TA_Version: 1.83                                                                                     
        01-12 16:43:58.312 I [usage_table_header.cpp(204):RestoreTable] Found usage table to restore: entry_count = 0                                                                                                                                                       
        01-12 16:43:58.356 I [cdm_engine.cpp(140):OpenSession] New session: session_id = sid13                                                                                                                                                                              
        01-12 16:43:58.356 I [cdm_engine.cpp(871):QueryOemCryptoSessionId] session_id = sid13                                                                                                                                                                               
        01-12 16:43:58.363 I [cdm_engine.cpp(227):GenerateKeyRequest] session_id = sid13, key_set_id = <empty>, license_type = Offline                                                                                                                                      
        01-12 16:43:59.004 I [cdm_engine.cpp(306):AddKey] session_id = sid13, key_set_id = <empty>                                                                                                                                                                          
        01-12 16:43:59.174 I [cdm_engine.cpp(365):AddKey] key_set_id = ksidFEEFCBF6                                                                                                                                                                                         
        01-12 16:43:59.176 I [cdm_engine.cpp(185):CloseSession] session_id = sid13                                                                                                                                                                                          
        01-12 16:43:59.190 I [cdm_engine.cpp(140):OpenSession] New session: session_id = sid14                                                                                                                                                                              
2022-01-13 11:08:32.128 1753-1753/com.google.android.exoplayer2.demo E/DownloadTracker:     01-12 16:43:59.191 I [cdm_engine.cpp(871):QueryOemCryptoSessionId] session_id = sid14                                                                                           
        01-12 16:43:59.194 I [cdm_engine.cpp(389):RestoreKey] session_id = sid14, key_set_id = ksidFEEFCBF6                                                                                                                                                                 
        01-12 16:43:59.486 I [cdm_engine.cpp(227):GenerateKeyRequest] session_id = sid14, key_set_id = <empty>, license_type = Offline                                                                                                                                      
        01-12 16:43:59.486 E [license.cpp(399):PrepareKeyUpdateRequest] License renewal prohibited                                                                                                                                                                          
        01-12 16:43:59.486 E [cdm_engine.cpp(287):GenerateKeyRequest] CdmSession::GenerateKeyRequest failed: session_id = sid14, status = 167                                                                                                                               
        01-12 16:43:59.502 I [cdm_engine.cpp(185):CloseSession] session_id = sid14                                                                                                                                                                                          
        01-12 16:59:22.860 I [(0):] L3 Terminate.                                                                                                                                                                                                                           
        01-12 16:59:22.929 I [oemcrypto_adapter_dynamic.cpp(702):Initialize] Level 3 Build Info (v16): OEMCrypto Level3 Code 22594 May 28 2021 16:59:07                                                                                                                     
        01-12 16:59:22.929 I [(0):] Level3 Library 22594 May 28 2021 16:59:07                                                                                                                                                                                               
        01-12 16:59:22.930 I [oemcrypto_adapter_dynamic.cpp(716):Initialize] L3 Initialized. Trying L1.                                                                                                                                                                     
        01-12 16:59:22.997 W [oemcrypto_adapter_dynamic.cpp(885):LoadLevel1] Could not load L1 _oecc109.                                                                                                                                                                    
        01-12 16:59:22.997 W [oemcrypto_adapter_dynamic.cpp(886):LoadLevel1] Could not load L1 _oecc110.                                                                                                                                                                    
        01-12 16:59:22.998 I [oemcrypto_adapter_dynamic.cpp(738):Initialize] Level 1 Build Info (v16): Build Information: API_Version: 16.3 LibOEMCrypto_Version: 1.46 TA_Version: 1.83                                                                                     
        01-12 16:59:22.999 I [usage_table_header.cpp(204):RestoreTable] Found usage table to restore: entry_count = 0                                                                                                                                                       
        01-12 16:59:23.041 I [cdm_engine.cpp(140):OpenSession] New session: session_id = sid15                                                                                                                                                                              
        01-12 16:59:23.041 I [cdm_engine.cpp(871):QueryOemCryptoSessionId] session_id = sid15                                                                                                                                                                               
        01-12 16:59:23.045 I [cdm_engine.cpp(227):GenerateKeyRequest] session_id = sid15, key_set_id = <empty>, license_type = Offline                                                                                                                                      
        01-12 16:59:23.569 I [cdm_engine.cpp(306):AddKey] session_id = sid15, key_set_id = <empty>                                                                                                                                                                          
        01-12 16:59:23.654 I [cdm_engine.cpp(365):AddKey] key_set_id = ksid05B1E572                                                                                                                                                                                         
        01-12 16:59:23.656 I [cdm_engine.cpp(185):CloseSession] session_id = sid15                                                                                                                                                                                          
        01-12 16:59:23.664 I [cdm_engine.cpp(140):OpenSession] New session: session_id = sid16                                                                                                                                                                              
        01-12 16:59:23.664 I [cdm_engine.cpp(871):QueryOemCryptoSessionId] session_id = sid16                                                                                                                                                                               
        01-12 16:59:23.668 I [cdm_engine.cpp(389):RestoreKey] session_id = sid16, key_set_id = ksid05B1E572                                                                                                                                                                 
        01-12 16:59:23.817 I [cdm_engine.cpp(227):GenerateKeyRequest] session_id = sid16, key_set_id = <empty>, license_type = Offline                                                                                                                                      
        01-12 16:59:23.817 E [license.cpp(399):PrepareKeyUpdateRequest] License renewal prohibited                                                                                                                                                                          
        01-12 16:59:23.817 E [cdm_engine.cpp(287):GenerateKeyRequest] CdmSession::GenerateKeyRequest failed: session_id = sid16, status = 167                                                                                                                               
        01-12 16:59:23.820 I [cdm_engine.cpp(185):CloseSession] session_id = sid16                                                                                                                                                                                          
        01-12 17:34:45.154 I [cdm_engine.cpp(140):OpenSession] New session: session_id = sid17                                                                                                                                                                              
        01-12 17:34:45.154 I [cdm_engine.cpp(871):QueryOemCryptoSessionId] session_id = sid17                                                                                                                                                                               
        01-12 17:34:45.161 I [cdm_engine.cpp(227):GenerateKeyRequest] session_id = sid17, key_set_id = <empty>, license_type = Streaming                                                                                                                                    
        01-12 17:34:45.279 I [cdm_engine.cpp(776):QuerySessionStatus] session_id = sid17                                                                                                                                                                                    
        01-12 17:34:45.700 I [cdm_engine.cpp(306):AddKey] session_id = sid17, key_set_id = <empty>                                                                                                                                                                          
        01-12 17:35:52.608 I [cdm_engine.cpp(185):CloseSession] session_id = sid17                                                                                                                                                                                          
        01-13 11:07:48.848 I [(0):] L3 Terminate.                                                                                                                                                                                                                           
        01-13 11:07:49.086 I [oemcrypto_adapter_dynamic.cpp(702):Initialize] Level 3 Build Info (v16): OEMCrypto Level3 Code 22594 May 28 2021 16:59:07                                                                                                                     
        01-13 11:07:49.086 I [(0):] Level3 Library 22594 May 28 2021 16:59:07                                                                                                                                                                                               
        01-13 11:07:49.092 I [oemcrypto_adapter_dynamic.cpp(716):Initialize] L3 Initialized. Trying L1.                                                                                                                                                                     
        01-13 11:07:49.175 W [oemcrypto_adapter_dynamic.cpp(885):LoadLevel1] Could not load L1 _oecc109.                                                                                                                                                                    
        01-13 11:07:49.176 W [oemcrypto_adapter_dynamic.cpp(886):LoadLevel1] Could not load L1 _oecc110.                                                                                                                                                                    
2022-01-13 11:08:32.128 1753-1753/com.google.android.exoplayer2.demo E/DownloadTracker:     01-13 11:07:49.178 I [oemcrypto_adapter_dynamic.cpp(738):Initialize] Level 1 Build Info (v16): Build Information: API_Version: 16.3 LibOEMCrypto_Version: 1.46 TA_Version: 1.83 
        01-13 11:07:49.178 I [usage_table_header.cpp(204):RestoreTable] Found usage table to restore: entry_count = 0                                                                                                                                                       
        01-13 11:07:49.222 I [cdm_engine.cpp(140):OpenSession] New session: session_id = sid18                                                                                                                                                                              
        01-13 11:07:49.222 I [cdm_engine.cpp(871):QueryOemCryptoSessionId] session_id = sid18                                                                                                                                                                               
        01-13 11:07:49.232 I [cdm_engine.cpp(227):GenerateKeyRequest] session_id = sid18, key_set_id = <empty>, license_type = Offline                                                                                                                                      
        01-13 11:07:49.871 I [cdm_engine.cpp(306):AddKey] session_id = sid18, key_set_id = <empty>                                                                                                                                                                          
        01-13 11:07:49.957 I [cdm_engine.cpp(365):AddKey] key_set_id = ksidBE8F0989                                                                                                                                                                                         
        01-13 11:07:49.958 I [cdm_engine.cpp(185):CloseSession] session_id = sid18                                                                                                                                                                                          
        01-13 11:07:49.966 I [cdm_engine.cpp(140):OpenSession] New session: session_id = sid19                                                                                                                                                                              
        01-13 11:07:49.966 I [cdm_engine.cpp(871):QueryOemCryptoSessionId] session_id = sid19                                                                                                                                                                               
        01-13 11:07:49.969 I [cdm_engine.cpp(389):RestoreKey] session_id = sid19, key_set_id = ksidBE8F0989                                                                                                                                                                 
        01-13 11:07:50.118 I [cdm_engine.cpp(227):GenerateKeyRequest] session_id = sid19, key_set_id = <empty>, license_type = Offline                                                                                                                                      
        01-13 11:07:50.118 E [license.cpp(399):PrepareKeyUpdateRequest] License renewal prohibited                                                                                                                                                                          
        01-13 11:07:50.118 E [cdm_engine.cpp(287):GenerateKeyRequest] CdmSession::GenerateKeyRequest failed: session_id = sid19, status = 167                                                                                                                               
        01-13 11:07:50.121 I [cdm_engine.cpp(185):CloseSession] session_id = sid19                                                                                                                                                                                          
        01-13 11:08:30.924 I [(0):] L3 Terminate.                                                                                                                                                                                                                           
        01-13 11:08:31.005 I [oemcrypto_adapter_dynamic.cpp(702):Initialize] Level 3 Build Info (v16): OEMCrypto Level3 Code 22594 May 28 2021 16:59:07                                                                                                                     
        01-13 11:08:31.005 I [(0):] Level3 Library 22594 May 28 2021 16:59:07                                                                                                                                                                                               
        01-13 11:08:31.010 I [oemcrypto_adapter_dynamic.cpp(716):Initialize] L3 Initialized. Trying L1.                                                                                                                                                                     
        01-13 11:08:31.089 W [oemcrypto_adapter_dynamic.cpp(885):LoadLevel1] Could not load L1 _oecc109.                                                                                                                                                                    
        01-13 11:08:31.090 W [oemcrypto_adapter_dynamic.cpp(886):LoadLevel1] Could not load L1 _oecc110.                                                                                                                                                                    
        01-13 11:08:31.091 I [oemcrypto_adapter_dynamic.cpp(738):Initialize] Level 1 Build Info (v16): Build Information: API_Version: 16.3 LibOEMCrypto_Version: 1.46 TA_Version: 1.83                                                                                     
        01-13 11:08:31.092 I [usage_table_header.cpp(204):RestoreTable] Found usage table to restore: entry_count = 0                                                                                                                                                       
        01-13 11:08:31.134 I [cdm_engine.cpp(140):OpenSession] New session: session_id = sid20                                                                                                                                                                              
        01-13 11:08:31.134 I [cdm_engine.cpp(871):QueryOemCryptoSessionId] session_id = sid20                                                                                                                                                                               
        01-13 11:08:31.139 I [cdm_engine.cpp(227):GenerateKeyRequest] session_id = sid20, key_set_id = <empty>, license_type = Offline                                                                                                                                      
        01-13 11:08:31.854 I [cdm_engine.cpp(306):AddKey] session_id = sid20, key_set_id = <empty>                                                                                                                                                                          
        01-13 11:08:31.939 I [cdm_engine.cpp(365):AddKey] key_set_id = ksid12B96064                                                                                                                                                                                         
        01-13 11:08:31.941 I [cdm_engine.cpp(185):CloseSession] session_id = sid20                                                                                                                                                                                          
        01-13 11:08:31.948 I [cdm_engine.cpp(140):OpenSession] New session: session_id = sid21                                                                                                                                                                              
        01-13 11:08:31.948 I [cdm_engine.cpp(871):QueryOemCryptoSessionId] session_id = sid21                                                                                                                                                                               
        01-13 11:08:31.951 I [cdm_engine.cpp(389):RestoreKey] session_id = sid21, key_set_id = ksid12B96064                                                                                                                                                                 
        01-13 11:08:32.102 I [cdm_engine.cpp(227):GenerateKeyRequest] session_id = sid21, key_set_id = <empty>, license_type = Offline                                                                                                                                      
        01-13 11:08:32.102 E [license.cpp(399):PrepareKeyUpdateRequest] License renewal prohibited                                                                                                                                                                          
        01-13 11:08:32.102 E [cdm_engine.cpp(287):GenerateKeyRequest] CdmSession::GenerateKeyRequest failed: session_id = sid21, status = 167                                                                                                                               
      ============================== End of DRM Plugin Log ==============================                                                                                                                                                                                   
        at android.media.MediaDrm.getKeyRequestNative(Native Method)                                                                                                                                                                                                        
        at android.media.MediaDrm.getKeyRequest(MediaDrm.java:1580)
```
