### ISSUE TITLE
MPEG-4 video stream is not opening, while other players can open it without problems.

### ISSUE THREAD

**Issue by menscikov** [google/ExoPlayer#9853]
**Issue description**
ExoPlayer can't open MPEG-4 AVC video stream. No errors, just constant loading.
VLC player opens without problems.

**Link to test content**
Link to the media e-mailed to ExoPlayer development team.

**Version of ExoPlayer being used**
2.16.1

**Device(s) and version(s) of Android being used**
Xiaomi Mi 9T, Android 11

**Comment by icbaker** [comment]
I can reproduce the problem as described. The stream provided over email plays in VLC on MacOS but not in the ExoPlayer demo app (2.16.1).

I see the following in the logs, which indicates the server is returning a HTTP 404 response.  To understand why that's happening I suggest you look in the server logs or talk to the hosting provider - it doesn't seem like an exoplayer problem.

```
2022-01-12 13:58:29.630 11016-11016/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=2.70, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:719)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
    ]
2022-01-12 13:58:34.614 11016-11016/com.google.android.exoplayer2.demo E/exoplayer2.dem: Invalid ID 0x00000000.
2022-01-12 13:58:38.638 11016-11016/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=11.71, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: java.net.SocketTimeoutException
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:676)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.net.SocketTimeoutException
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:672)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
    ]

```

**Comment by menscikov** [comment]
Hello, thank you for testing the video stream. One of my users reported about this issue.
I will send him this information.

**Comment by icbaker** [comment]
Closing due to inactivity
