### ISSUE TITLE
How to use exoplayer:extension-ima:2.16.0 with vmap tags?  

### ISSUE THREAD

**Issue by Stinger2198** [google/ExoPlayer#9860]
I used this library on android app, earlier all working fine, but after update version i cant find how to use vmap with new version. When i tried use like describe on documentation I always get error -  
```
2022-01-13 15:26:36.981 31003-31003/EventLogger: internalError [eventTime=27.96, mediaPos=0.00, window=0, loadError
      com.google.android.exoplayer2.source.ads.AdsMediaSource$AdLoadException: AdError [errorType: LOAD, errorCode: AdErrorCode [name: FAILED_TO_REQUEST_ADS, number: 1005], message: There was a problem requesting ads from the server. Caused by: 6]
        at com.google.android.exoplayer2.ext.ima.AdTagLoader$ComponentListener.onAdError(AdTagLoader.java:1376)
        at com.google.ads.interactivemedia.v3.internal.dn.c(IMASDK:2)
        at com.google.ads.interactivemedia.v3.internal.co.a(IMASDK:6)
        at com.google.ads.interactivemedia.v3.internal.ed.k(IMASDK:66)
        at com.google.ads.interactivemedia.v3.internal.ej.f(IMASDK:5)
        at com.google.ads.interactivemedia.v3.internal.eg.shouldOverrideUrlLoading(IMASDK:2)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-AmazonWebView.apk-stable-60252232:15)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:143)
        at android.os.Looper.loop(Looper.java:122)
        at android.app.ActivityThread.main(ActivityThread.java:5604)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: AdError [errorType: LOAD, errorCode: AdErrorCode [name: FAILED_TO_REQUEST_ADS, number: 1005], message: There was a problem requesting ads from the server. Caused by: 6]
```

**Comment by icbaker** [comment]
This error looks like it's coming from inside the IMA SDK (rather than from ExoPlayer). You might want to try getting help from the IMA folks directly: https://groups.google.com/g/ima-sdk

For us to take a closer look we will need an ad tag URI we can use to reproduce the problem. 
Please either post it here or send it to dev.exoplayer@gmail.com using a subject in the format `Issue #1234` (where `#1234` should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

**Comment by Stinger2198** [comment]
@icbaker I sent mail for address which you give. Thank you a lot for help with figure out this problem.

**Comment by icbaker** [comment]
Thanks for the ad tag provided over email. Since you sent it as an attachment (rather than a link to a hosted tag), I hosted it myself and reproduced the same stack trace you're seeing.

I then enabled additional IMA debugging using [`ImaAdsLoader.Builder#setDebugModeEnabled(boolean)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.Builder.html#setDebugModeEnabled(boolean)), which gave some new lines in logcat before the error. They showed that in my case the problem was due to CORS policies:
```
2022-01-14 09:45:37.215 20104-20104/? I/chromium: [INFO:CONSOLE(1092)] " [  0.043s] [ima.loader.AdsLoaderImpl] Requesting ads using new ads loader. ", source: https://imasdk.googleapis.com/native/core/3.299.2/native_bridge_debug__en.js (1092)
2022-01-14 09:45:37.215 20104-20104/? I/chromium: [INFO:CONSOLE(1092)] " [  0.044s] [ima.loader.AdsLoaderImpl] requestAds, processing external request. ", source: https://imasdk.googleapis.com/native/core/3.299.2/native_bridge_debug__en.js (1092)
2022-01-14 09:45:37.215 20104-20104/? I/chromium: [INFO:CONSOLE(1092)] " [  0.045s] [ima.loader.SequentialAdsLoader] Enqueued new request. ", source: https://imasdk.googleapis.com/native/core/3.299.2/native_bridge_debug__en.js (1092)
2022-01-14 09:45:37.215 20104-20104/? I/chromium: [INFO:CONSOLE(1092)] " [  0.045s] [ima.loader.SequentialAdsLoader] Starting request from queue. ", source: https://imasdk.googleapis.com/native/core/3.299.2/native_bridge_debug__en.js (1092)
2022-01-14 09:45:37.227 20104-20104/? I/chromium: [INFO:CONSOLE(0)] "Access to XMLHttpRequest at 'REDACTED host location of ad tag XML file' from origin 'https://imasdk.googleapis.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: https://imasdk.googleapis.com/native/sdkloader/native_sdk_v3_debug.html?sdk_version=a.3.25.1&hl=en-us&omv=1.3.3-google_20200416&app=com.google.android.exoplayer2.demo (0)
2022-01-14 09:45:37.229 20104-20104/? I/chromium: [INFO:CONSOLE(1092)] " [  0.061s] [UrlLoader] LIMA: Failed! retrying without credentials ", source: https://imasdk.googleapis.com/native/core/3.299.2/native_bridge_debug__en.js (1092)
2022-01-14 09:45:37.248 20104-20104/? I/chromium: [INFO:CONSOLE(0)] "Access to XMLHttpRequest at 'REDACTED host location of ad tag XML file' from origin 'https://imasdk.googleapis.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: https://imasdk.googleapis.com/native/sdkloader/native_sdk_v3_debug.html?sdk_version=a.3.25.1&hl=en-us&omv=1.3.3-google_20200416&app=com.google.android.exoplayer2.demo (0)
2022-01-14 09:45:37.249 20104-20104/? I/chromium: [INFO:CONSOLE(1092)] " [  0.070s] [ima.loader.AdXmlFetcher] Failed to load ad request URL. Error: 6 ", source: https://imasdk.googleapis.com/native/core/3.299.2/native_bridge_debug__en.js (1092)
2022-01-14 09:45:37.249 20104-20104/? I/chromium: [INFO:CONSOLE(1092)] " [  0.070s] [ima.loader.SequentialAdsLoader] Starting request from queue. ", source: https://imasdk.googleapis.com/native/core/3.299.2/native_bridge_debug__en.js (1092)
```

I don't know if this is the same root cause that you're seeing, since obviously you're hosting your ad tag in a different place - but I suggest you try enabling the debug logging and see if you see a similar error. If so, you need to take a look at https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/cors.

If that doesn't help resolve the problem then I think the next step is to give us access to the URI of your hosted ad tag (rather than the content of it).

**Comment by Stinger2198** [comment]
Ok, thank you, I will try to do this and let you know result.

**Comment by Stinger2198** [comment]
@icbaker Which URI you need? I gave you all i have by mail. I create this VMAP in android app and pass it to adsLoader for load ads. Ads provider give ads by url address which contains in vmap tag.

**Comment by icbaker** [comment]
How are you accessing the `VAST_tag_xml.txt` file that you attached to the email? Concretely: What value does the `Uri uriVastData` local variable in your code snippet have at runtime? (you can share this over email if it's hosted in a location you don't want to share publicly - but please also reply here if you send us an email as we don't routinely monitor that inbox)

What additional logs do you see when you enable the IMA debug logging as described above?

**Comment by Stinger2198** [comment]
You can use my vmap in your app with my links? Can you provide right code for use vmap tags in android?

**Comment by Stinger2198** [comment]
I create this vmap in my android app (calling specific method) and create URI from String and pass it to adsLoader (maybe thats wrong?)

**Comment by Stinger2198** [comment]
2022-01-14 13:18:44.406 15306-15306/com.hideouttv D/AdTagLoader: onAdError
      AdError [errorType: LOAD, errorCode: AdErrorCode [name: FAILED_TO_REQUEST_ADS, number: 1005], message: There was a problem requesting ads from the server. Caused by: 6]
        at com.google.ads.interactivemedia.v3.internal.co.a(IMASDK:5)
        at com.google.ads.interactivemedia.v3.internal.ed.k(IMASDK:66)
        at com.google.ads.interactivemedia.v3.internal.ej.f(IMASDK:5)
        at com.google.ads.interactivemedia.v3.internal.eg.shouldOverrideUrlLoading(IMASDK:2)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-AmazonWebView.apk-stable-60252232:15)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:143)
        at android.os.Looper.loop(Looper.java:122)
        at android.app.ActivityThread.main(ActivityThread.java:5604)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
2022-01-14 13:18:44.413 15306-15306/com.hideouttv I/EventLogger_onAdError: AdError [errorType: LOAD, errorCode: AdErrorCode [name: FAILED_TO_REQUEST_ADS, number: 1005], message: There was a problem requesting ads from the server. Caused by: 6]
2022-01-14 13:18:44.465 15306-15306/com.hideouttv E/EventLogger: internalError [eventTime=5.28, mediaPos=0.00, window=0, loadError
      com.google.android.exoplayer2.source.ads.AdsMediaSource$AdLoadException: AdError [errorType: LOAD, errorCode: AdErrorCode [name: FAILED_TO_REQUEST_ADS, number: 1005], message: There was a problem requesting ads from the server. Caused by: 6]
        at com.google.android.exoplayer2.ext.ima.AdTagLoader$ComponentListener.onAdError(AdTagLoader.java:1376)
        at com.google.ads.interactivemedia.v3.internal.dn.c(IMASDK:2)
        at com.google.ads.interactivemedia.v3.internal.co.a(IMASDK:6)
        at com.google.ads.interactivemedia.v3.internal.ed.k(IMASDK:66)
        at com.google.ads.interactivemedia.v3.internal.ej.f(IMASDK:5)
        at com.google.ads.interactivemedia.v3.internal.eg.shouldOverrideUrlLoading(IMASDK:2)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-AmazonWebView.apk-stable-60252232:15)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:143)
        at android.os.Looper.loop(Looper.java:122)
        at android.app.ActivityThread.main(ActivityThread.java:5604)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: AdError [errorType: LOAD, errorCode: AdErrorCode [name: FAILED_TO_REQUEST_ADS, number: 1005], message: There was a problem requesting ads from the server. Caused by: 6]
        at com.google.ads.interactivemedia.v3.internal.co.a(IMASDK:5)
        at com.google.ads.interactivemedia.v3.internal.ed.k(IMASDK:66) 
        at com.google.ads.interactivemedia.v3.internal.ej.f(IMASDK:5) 
        at com.google.ads.interactivemedia.v3.internal.eg.shouldOverrideUrlLoading(IMASDK:2) 
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-AmazonWebView.apk-stable-60252232:15) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:143) 
        at android.os.Looper.loop(Looper.java:122) 
        at android.app.ActivityThread.main(ActivityThread.java:5604) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
    ]
2022-01-14 13:18:44.467 15306-15306/com.hideouttv D/EventLogger: timeline [eventTime=5.29, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
2022-01-14 13:18:44.467 15306-15306/com.hideouttv D/EventLogger:   period [?]
2022-01-14 13:18:44.467 15306-15306/com.hideouttv D/EventLogger:   window [?, seekable=false, dynamic=false]
2022-01-14 13:18:44.467 15306-15306/com.hideouttv D/EventLogger: ]
2022-01-14 13:18:46.960 15306-15306/com.hideouttv D/EventLogger: timeline [eventTime=7.78, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
2022-01-14 13:18:46.960 15306-15306/com.hideouttv D/EventLogger:   period [168.22]
2022-01-14 13:18:46.960 15306-15306/com.hideouttv D/EventLogger:   window [168.22, seekable=true, dynamic=false]
2022-01-14 13:18:46.961 15306-15306/com.hideouttv D/EventLogger: ]
2022-01-14 13:18:47.044 15306-15306/com.hideouttv D/EventLogger: videoEnabled [eventTime=7.86, mediaPos=0.00, window=0, period=0]
2022-01-14 13:18:47.046 15306-15306/com.hideouttv D/EventLogger: audioEnabled [eventTime=7.86, mediaPos=0.00, window=0, period=0]
2022-01-14 13:18:47.050 15306-15306/com.hideouttv D/EventLogger: tracks [eventTime=7.87, mediaPos=0.00, window=0, period=0
2022-01-14 13:18:47.051 15306-15306/com.hideouttv D/EventLogger:   MediaCodecVideoRenderer [
2022-01-14 13:18:47.051 15306-15306/com.hideouttv D/EventLogger:     Group:0, adaptive_supported=N/A [
2022-01-14 13:18:47.051 15306-15306/com.hideouttv D/EventLogger:       [X] Track:0, id=1, mimeType=video/avc, codecs=avc1.42C01F, res=640x360, fps=59.999996, supported=YES
2022-01-14 13:18:47.051 15306-15306/com.hideouttv D/EventLogger:     ]
2022-01-14 13:18:47.051 15306-15306/com.hideouttv D/EventLogger:   ]
2022-01-14 13:18:47.051 15306-15306/com.hideouttv D/EventLogger:   MediaCodecAudioRenderer [
2022-01-14 13:18:47.051 15306-15306/com.hideouttv D/EventLogger:     Group:0, adaptive_supported=N/A [
2022-01-14 13:18:47.051 15306-15306/com.hideouttv D/EventLogger:       [X] Track:0, id=2, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=1, sample_rate=48000, language=en, supported=YES
2022-01-14 13:18:47.051 15306-15306/com.hideouttv D/EventLogger:     ]
2022-01-14 13:18:47.051 15306-15306/com.hideouttv D/EventLogger:   ]
2022-01-14 13:18:47.051 15306-15306/com.hideouttv D/EventLogger:   TextRenderer []
2022-01-14 13:18:47.051 15306-15306/com.hideouttv D/EventLogger:   MetadataRenderer []
2022-01-14 13:18:47.051 15306-15306/com.hideouttv D/EventLogger:   CameraMotionRenderer []
2022-01-14 13:18:47.051 15306-15306/com.hideouttv D/EventLogger: ]

**Comment by Stinger2198** [comment]
Error log

**Comment by Stinger2198** [comment]
@icbaker This VAST_tag_xml create dynamically in code my app with specific url and return like a String after that i create URI from this string. I cant find information how pass vmap tags to adsLoader in programm code. Can you help me or show code how i can do that in android?

**Comment by icbaker** [comment]
> I create this vmap in my android app (calling specific method) and create URI from String and pass it to adsLoader (maybe thats wrong?)

Yes, looking at your code snippet again, it looks like you're passing a `String` containing XML data directly to `Uri.parse`, which doesn't seem correct (and I'm a little surprised that `Uri.parse` doesn't complain). The code snippet is incomplete (missing a definition of `createXMLVastTag(...)`), so it's hard to tell for sure.

To use the IMA SDK and the ExoPlayer IMA extension, you need to host your ad tag XML on a VAST-compliant ad server. From the [Android IMA SDK docs](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side):
> IMA SDKs can request ads from any VAST-compliant ad server and manage ad playback in your apps

**Comment by Stinger2198** [comment]
public static String createXMLVastTag(Context context, HTVVideo selectedVideo) {

    String start = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<vmap:VMAP
xmlns:vmap=\"http://www.iab.net/videosuite/vmap\" version=\"1.0\">";

    String preRoll = "<vmap:AdBreak timeOffset=\"start\"
breakType=\"linear\" breakId=\"preroll\">" +
            "  <vmap:AdSource id=\"preroll-1-ad-1\"
allowMultipleAds=\"true\" followRedirects=\"true\">" +
            "   <vmap:AdTagURI templateType=\"vast3\"><![CDATA[" +
getAdUrl(context, "5f1b098bca2fd62aac59ac58", selectedVideo) +
"]]></vmap:AdTagURI> " +
            "</vmap:AdSource>\n" +
            " </vmap:AdBreak>";

    String preRoll1 = "<vmap:AdBreak timeOffset=\"start\"
breakType=\"linear\" breakId=\"preroll-1\">\n" +
            "  <vmap:AdSource id=\"preroll-2-ad-2\"
allowMultipleAds=\"true\" followRedirects=\"true\">" +
            "   <vmap:AdTagURI templateType=\"vast3\"><![CDATA[" +
getAdUrl(context, "5f1b098bca2fd62aac59ac58", selectedVideo) +
"]]></vmap:AdTagURI> " +

            "</vmap:AdSource>\n" +
            " </vmap:AdBreak>";

    String preRoll2 = "<vmap:AdBreak timeOffset=\"start\"
breakType=\"linear\" breakId=\"preroll-2\">\n" +
            "  <vmap:AdSource id=\"preroll-3-ad-3\"
allowMultipleAds=\"true\" followRedirects=\"true\">" +
            "   <vmap:AdTagURI templateType=\"vast3\"><![CDATA[" +
getAdUrl(context, "5f1b098bca2fd62aac59ac58", selectedVideo) +
"]]></vmap:AdTagURI> " +
            "</vmap:AdSource>\n" +
            " </vmap:AdBreak>";


    String midRoll1 = "<vmap:AdBreak timeOffset=\"00:02:00.000\"
breakType=\"linear\" breakId=\"midroll-1\">\n" +
            "  <vmap:AdSource id=\"midroll-1-ad-1\"
allowMultipleAds=\"true\" followRedirects=\"true\">\n" +
            "   <vmap:AdTagURI templateType=\"vast3\"><![CDATA[" +
getAdUrl(context, "5f1b098bca2fd62aac59ac58", selectedVideo) +
"]]></vmap:AdTagURI>\n" +
            "  </vmap:AdSource>\n" +
            " </vmap:AdBreak>";

    String midRoll2 = "<vmap:AdBreak timeOffset=\"00:02:00.000\"
breakType=\"linear\" breakId=\"midroll-2\">\n" +
            "  <vmap:AdSource id=\"midroll-2-ad-2\"
allowMultipleAds=\"true\" followRedirects=\"true\">\n" +
            "   <vmap:AdTagURI templateType=\"vast3\"><![CDATA[" +
getAdUrl(context, "5f1b098bca2fd62aac59ac58", selectedVideo) +
"]]></vmap:AdTagURI>\n" +
            "  </vmap:AdSource>\n" +
            " </vmap:AdBreak>";

    String midRoll3 = "<vmap:AdBreak timeOffset=\"00:05:00.000\"
breakType=\"linear\" breakId=\"midroll-3\">\n" +
            "  <vmap:AdSource id=\"midroll-3-ad-1\"
allowMultipleAds=\"true\" followRedirects=\"true\">\n" +
            "   <vmap:AdTagURI templateType=\"vast3\"><![CDATA[" +
getAdUrl(context, "5f1b098bca2fd62aac59ac58", selectedVideo) +
"]]></vmap:AdTagURI>\n" +
            "  </vmap:AdSource>\n" +
            " </vmap:AdBreak>";

    String midRoll4 = "<vmap:AdBreak timeOffset=\"00:05:00.000\"
breakType=\"linear\" breakId=\"midroll-4\">\n" +
            "  <vmap:AdSource id=\"midroll-4-ad-1\"
allowMultipleAds=\"true\" followRedirects=\"true\">\n" +
            "   <vmap:AdTagURI templateType=\"vast3\"><![CDATA[" +
getAdUrl(context, "5f1b098bca2fd62aac59ac58", selectedVideo) +
"]]></vmap:AdTagURI>\n" +
            "  </vmap:AdSource>\n" +
            " </vmap:AdBreak>";

    String midRoll5 = "<vmap:AdBreak timeOffset=\"00:09:00.000\"
breakType=\"linear\" breakId=\"midroll-5\">\n" +
            "  <vmap:AdSource id=\"midroll-5-ad-1\"
allowMultipleAds=\"true\" followRedirects=\"true\">\n" +
            "   <vmap:AdTagURI templateType=\"vast3\"><![CDATA[" +
getAdUrl(context, "5f1b098bca2fd62aac59ac58", selectedVideo) +
"]]></vmap:AdTagURI>\n" +
            "  </vmap:AdSource>\n" +
            " </vmap:AdBreak>";

    String midRoll6 = "<vmap:AdBreak timeOffset=\"00:09:00.000\"
breakType=\"linear\" breakId=\"midroll-6\">\n" +
            "  <vmap:AdSource id=\"midroll-6-ad-1\"
allowMultipleAds=\"true\" followRedirects=\"true\">\n" +
            "   <vmap:AdTagURI templateType=\"vast3\"><![CDATA[" +
getAdUrl(context, "5f1b098bca2fd62aac59ac58", selectedVideo) +
"]]></vmap:AdTagURI>\n" +
            "  </vmap:AdSource>\n" +
            " </vmap:AdBreak>";

    String midRoll7 = "<vmap:AdBreak timeOffset=\"00:16:00.000\"
breakType=\"linear\" breakId=\"midroll-7\">\n" +
            "  <vmap:AdSource id=\"midroll-7-ad-1\"
allowMultipleAds=\"true\" followRedirects=\"true\">\n" +
            "   <vmap:AdTagURI templateType=\"vast3\"><![CDATA[" +
getAdUrl(context, "5f1b098bca2fd62aac59ac58", selectedVideo) +
"]]></vmap:AdTagURI>\n" +
            "  </vmap:AdSource>\n" +
            " </vmap:AdBreak>";
    String midRoll8 = "<vmap:AdBreak timeOffset=\"00:16:00.000\"
breakType=\"linear\" breakId=\"midroll-8\">\n" +
            "  <vmap:AdSource id=\"midroll-8-ad-1\"
allowMultipleAds=\"true\" followRedirects=\"true\">\n" +
            "   <vmap:AdTagURI templateType=\"vast3\"><![CDATA[" +
getAdUrl(context, "5f1b098bca2fd62aac59ac58", selectedVideo) +
"]]></vmap:AdTagURI>\n" +
            "  </vmap:AdSource>\n" +
            " </vmap:AdBreak>";

    String end = "</vmap:VMAP>";



    return start + preRoll + preRoll1 + preRoll2 + midRoll1 + midRoll2
+ midRoll3 + midRoll4 + midRoll5 + midRoll6 + midRoll7 + midRoll8 +
end;


}


пт, 14 янв. 2022 г. в 13:36, Ian Baker ***@***.***>:

**Comment by Stinger2198** [comment]
createXMLVastTag(...) this i can show by mail (sended)
Early this method working fine (old version ima sdk exoplayer)

**Comment by Stinger2198** [comment]
@icbaker

**Comment by Stinger2198** [comment]
in explayer 2.11.1 that worked like - 
```
 String vastData = ExoplayerHelper.createXMLVastTag(getActivity(), selectedVideo);
ImaAdsLoader.Builder imaBuilder = new ImaAdsLoader.Builder(getActivity());

mAdsLoader = imaBuilder.buildForAdsResponse(vastData);

MediaSource contentMediaSource = ExoplayerHelper.buildMediaSource(Uri.parse(selectedVideo.getSources().get(ExoplayerHelper.getIndexOfSourceFileFromVideoType(selectedVideo)).getFile()), mediaDataSourceFactory, manifestDataSourceFactory);
MediaSource mediaSourceWithAds = new AdsMediaSource(contentMediaSource, mediaDataSourceFactory, mAdsLoader, playerView);
mAdsLoader.setPlayer(exoPlayer);
exoPlayer.prepare(mediaSourceWithAds);
exoPlayer.setPlayWhenReady(true);
```

**Comment by icbaker** [comment]
[`ImaAdsLoader.buildForAdsResponse`](https://github.com/google/ExoPlayer/blob/r2.11.1/extensions/ima/src/main/java/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.java#L256) (the method you used in your 2.11.1 snippet) expects a `String` containing XML data - which is what you're passing, so it makes sense that it succeeds. [`Uri.parse`](https://developer.android.com/reference/android/net/Uri#parse(java.lang.String)) expects a `String` containing "an RFC 2396-compliant, encoded URI", but you're still passing it XML data directly - which may explain why things aren't working.

You may be able to generate a [`data:` scheme URI](https://en.wikipedia.org/wiki/Data_URI_scheme) from your XML data and pass that in to the constructor of `MediaItem.AdsConfiguration.Builder`. You can use [`Util.getDataUriForString(String, String)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/util/Util.html#getDataUriForString(java.lang.String,java.lang.String)) for this - you probably want `mimeType = application/xml` (based on [these Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types)). This is mentioned in the [`ImaAdsLoader` javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.html):
>Literal ads responses can be encoded as data scheme data specs, for example, by constructing the data spec using a URI generated via `Util.getDataUriForString(String, String)`.

**Comment by Stinger2198** [comment]
Thanks for the tip, I'll try it and let you know @icbaker

**Comment by Stinger2198** [comment]
@icbaker Thank you a LOT!!!!! You really save my life!!! It is WORKING!!! Thank you for help!!! You are very smart!!! Big thank you again!!!

**Comment by Stinger2198** [comment]
Thank you a LOT!!!!! You really save my life!!! It is WORKING!!! Thank you
for help!!! You are very smart!!! Big thank you again!!!

пт, 14 янв. 2022 г. в 14:10, Ian Baker ***@***.***>:
