### ISSUE TITLE
Unable to play streaming on certain devices

### ISSUE THREAD

**Issue by ogawa-ma** [google/ExoPlayer#9868]
## ExoPlayer Version
*  2.16.1

## Device
* HUAWEI P9 lite(Android7.0)
* Pixel3(Android12)

## Bugreport
Attached by email to dev.exoplayer@gmail.com

---

## Question

When I edited assets / media.exolist.json of the demo app and played my content (Widevine H264), some devices can play streaming and some cannot, and ExoPlaybackException and CryptoException occur on the devices that cannot.

■ Terminals that cannot play streaming
HUAWEI P9 lite

■ Terminal that can play streaming
Pixel 3

The demo app "Widevine DASH (MP4, H264)" can be streamed normally on HUAWEI P9 lite.
Is this error occurring due to a problem with the video file?

```
2022-01-18 12:13:38.384 4751-4751/com.google.android.exoplayer2.demo E/HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
2022-01-18 12:13:38.495 4751-4751/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init 8090066 [ExoPlayerLib/2.16.1] [HWVNS-H, HUAWEI VNS-L22, HUAWEI, 24]
2022-01-18 12:13:38.526 4751-4751/com.google.android.exoplayer2.demo I/HwPointEventFilter: do not support AFT because of no config
2022-01-18 12:13:39.071 4751-9449/com.google.android.exoplayer2.demo I/OMXClient: MuxOMX ctor
2022-01-18 12:13:39.075 4751-9449/com.google.android.exoplayer2.demo I/ACodec: In onAllocateComponent create compenent, codec name: OMX.google.aac.decoder
2022-01-18 12:13:39.077 4751-9449/com.google.android.exoplayer2.demo I/ACodec: codec does not support config priority (err -2147483648)
2022-01-18 12:13:39.099 4751-9454/com.google.android.exoplayer2.demo I/OMXClient: MuxOMX ctor
2022-01-18 12:13:39.100 4751-9454/com.google.android.exoplayer2.demo I/ACodec: In onAllocateComponent create compenent, codec name: OMX.IMG.MSVDX.Decoder.AVC
2022-01-18 12:13:39.101 4751-9453/com.google.android.exoplayer2.demo I/MediaCodec: [OMX.IMG.MSVDX.Decoder.AVC] setting surface generation to 4865030
2022-01-18 12:13:39.102 4751-9454/com.google.android.exoplayer2.demo I/HwExtendedCodec: mime is [video/avc] at setVideoFormat
2022-01-18 12:13:39.103 4751-9454/com.google.android.exoplayer2.demo I/ACodec: codec does not support config priority (err -1010)
2022-01-18 12:13:40.567 4751-4756/com.google.android.exoplayer2.demo I/art: Do full code cache collection, code=244KB, data=245KB
2022-01-18 12:13:40.568 4751-4756/com.google.android.exoplayer2.demo I/art: After code cache collection, code=243KB, data=215KB
2022-01-18 12:13:42.978 4751-4756/com.google.android.exoplayer2.demo I/art: Do partial code cache collection, code=251KB, data=220KB
2022-01-18 12:13:42.979 4751-4756/com.google.android.exoplayer2.demo I/art: After code cache collection, code=251KB, data=220KB
2022-01-18 12:13:42.979 4751-4756/com.google.android.exoplayer2.demo I/art: Increasing code cache capacity to 1024KB
2022-01-18 12:13:44.918 4751-9442/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(video-avc1-1, null, null, video/avc, avc1.4D4020, 6000000, null, [1280, 720, 29.970188], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2505)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:171)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1307)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:780)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
2022-01-18 12:13:44.952 4751-9442/com.google.android.exoplayer2.demo W/MediaDrm: MediaDrm went away with unhandled events
2022-01-18 12:13:44.952 4751-9442/com.google.android.exoplayer2.demo W/MediaDrm: MediaDrm went away with unhandled events
2022-01-18 12:13:44.954 4751-4751/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=6.45, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_DRM_SYSTEM_ERROR
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(video-avc1-1, null, null, video/avc, avc1.4D4020, 6000000, null, [1280, 720, 29.970188], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2505)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:171)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1307)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:780)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
    ]
```

**Comment by icbaker** [comment]
The "Widevine DASH (MP4, H264)" sample in the demo app only requires Widevine L3. Is it possible that your content requires Widevine L1 and the Huawei P9 Lite device you're testing with is unable to provide that?

You can test this theory by trying to play the "Widevine DASH (policy tests) > HW secure crypto" sample in the demo app on the P9 Lite because that does require Widevine L1 (i think it has an unencrypted start, so ensure you play it all the way through to verify whether it's working correctly or not).

You can also use the "DRM Info" app to inspect the Widevine level reported by the Widevine CDM on the device.

If the "HW secure crypto" sample works on this device, then we'd need access to your specific media and DRM license server details in order to investigate further. Please either upload it here or send to dev.exoplayer@gmail.com using a subject in the format `Issue #1234` (where `#1234` should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

**Comment by ogawa-ma** [comment]
@icbaker
The security level of the Huawei P9 Lite device was L3.
<img src="https://user-images.githubusercontent.com/54785318/150076372-e2c5c6fe-7424-410f-a2f7-544a6fba4a08.png" width="320px">


I tested the demo app and got the following results.
* "Widevine DASH (MP4, H264)" -> Playable
* "Widevine DASH (policy tests) > HW secure crypto" -> Playable
* "Widevine DASH (policy tests) > HW secure crypto (L3)" -> Playable
* "Widevine DASH (policy tests) > HW secure all (L1)" -> Can't play

sorry. I would like to provide media that cannot be played, but due to video rights issues, I cannot provide it to the outside for free.
Is there anything I can find out from the logs?

I'm sorry to ask such a rudimentary question about DRM, but my understanding of Widevine CDM's Security Level L1~L3 is that L1 is capable of playing HD quality videos, while L3 is not capable of playing HD quality videos.
Therefore, I thought that my content that could not be played could be played on the Huawei P9 Lite device if the image quality was set to 480p, but I could not play it. Is this recognition correct?

Also, as an additional information, my content that can't be played this time was playing fine with the version of Exoplayer (2.11.3).
Since I updated the version of ExoPlayer to 2.16.1, it became impossible to play, so I think that something on the ExoPlayer side may not be able to play due to a problem.

**Comment by icbaker** [comment]
> I tested the demo app and got the following results.
> 
> * "Widevine DASH (MP4, H264)" -> Playable
> * "Widevine DASH (policy tests) > HW secure crypto" -> Playable
> * "Widevine DASH (policy tests) > HW secure crypto (L3)" -> Playable
> * "Widevine DASH (policy tests) > HW secure all (L1)" -> Can't play

Ah my bad - I pointed you at the wrong sample. The "HW secure crypto" samples implies the [`MediaDrm#SECURITY_LEVEL_HW_SECURE_CRYPTO`](https://developer.android.com/reference/android/media/MediaDrm#SECURITY_LEVEL_HW_SECURE_CRYPTO) level, which [can be handled by a Widevine L3 CDM](https://websites.fraunhofer.de/video-dev/enabling-hardware-drm-on-android-chrome-using-the-encrypted-media-extensions/), while [`MediaDrm#SECURITY_LEVEL_HW_SECURE_ALL`](https://developer.android.com/reference/android/media/MediaDrm#SECURITY_LEVEL_HW_SECURE_ALL) requires L1. So what you see is expected and matches the fact that your device only has an L3 CDM.

------

> I'm sorry to ask such a rudimentary question about DRM, but my understanding of Widevine CDM's Security Level L1~L3 is that L1 is capable of playing HD quality videos, while L3 is not capable of playing HD quality videos.
> Therefore, I thought that my content that could not be played could be played on the Huawei P9 Lite device if the image quality was set to 480p, but I could not play it. Is this recognition correct?

The license policy defines what widevine level is required for a given piece of media. A stream with multiple resolution variants (e.g. a DASH or HLS stream) can have different policies for different resolutions - so it's possible for a content provider to only allow HD playback on L1-capable devices - but this is a decision the content provider makes when preparing their license policies and stream definitions, it is not an inherent property of widevine L1. It's true that it's common for streaming providers to implement exactly this rule - so I understand where your impression comes from - but it's not reasonable to assume it's true of all content.

------

> Also, as an additional information, my content that can't be played this time was playing fine with the version of Exoplayer (2.11.3).
> Since I updated the version of ExoPlayer to 2.16.1, it became impossible to play, so I think that something on the ExoPlayer side may not be able to play due to a problem.

That is interesting/surprising - and I agree it suggests there's something more than just L1/L3 compatibility going on. However in order to investigate we will need access to media & a DRM license server that plays successfully on 2.11.3 and fails on 2.16.1 - without that I'm afraid we won't be able to provide detailed support. Does the "Widevine DASH (policy tests) > HW secure all (L1)" sample from the demo app play successfully on this device on 2.11.3? If so we can use that to investigate further.

If you're a widevine partner you can also get support directly from them:  https://www.widevine.com/contact.

**Comment by ogawa-ma** [comment]
@icbaker 
Sorry for the late reply.
The problem of not being able to play has been resolved.

The cause was that the license had been issued with an expiration date of 2052, which caused the playback error.
I changed the license expiration date to 1 week and it played.

Thank you for investigating.
