### ISSUE TITLE
Playback of DASH streams sometimes fails on Xiaomi Mi TV P1

### ISSUE THREAD

**Issue by pwiniars** [google/ExoPlayer#9877]
Hi, 

I've found a problem with playback of some H264 DASH streams on certain new Xiaomi devices with Android 10. For example Xiaomi Mi TV P1 43" (L43M6-6AEU). It's very likely that the whole P1 group behaves this way. Playback immediately fails with exception.

**Steps to reproduce:**
Can be reproduced using any version of ExoPlayer Demo app, for ex. the newest 2.16.1, with following params:

```
{
     "name": "Test Xiaomi",
     "uri": "https://r.dcs.redcdn.pl/dash/o2/portal/prod/vod/big_buck_bunny/trailer/dash/Manifest.ism",
     "extension": "mpd"
} 
```

In this exemple it fails only for the first two tracks, that have resolution 1280x720:

```
<Representation id="1" codecs="avc1.640029" bandwidth="2800000" width="1280" height="720" />
<Representation id="2" codecs="avc1.640028" bandwidth="1800000" width="1280" height="720" />
```
**ADB output**

```
com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=0.58, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_DECODING_FAILED
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640029, 2800000, null, [1280, 720, -1.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MS.AVC.Decoder
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1470)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:799)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_queueInputBuffer(Native Method)
        at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2451)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueInputBuffer(SynchronousMediaCodecAdapter.java:165)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1310)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:780)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    ]
```

Other tracks in this material work just fine. I've no clue what triggers this crash, because I've also tested other materials coded with avc1.640029 and avc1.640028, they play without problems.

**Comment by esiek** [comment]
we have the same problem

**Comment by christosts** [comment]
This is likely a device-specific problem that needs fixing on the vendor side. In case we can assist/debug/understand the error better, can you please grab a [bug-report](https://developer.android.com/studio/debug/bug-report) from the device **after the error occurs** and share it with us? If you cannot share it publicly, send it via email dev.exoplayer@gmail.com with subject "Issue #9877" and update this issue to indicate you've done this.

**Comment by pwiniars** [comment]
@christosts Thank's for the reply. Here's bug report: https://drive.google.com/file/d/1c75NY4b06VdG6FVM7Pwqs0_6CbHrH6Ny/view?usp=sharing

**Comment by pwiniars** [comment]
@christosts Could you provide any new info based on provided bug report?

**Comment by christosts** [comment]
Sorry for the late response. In the bugreport logs, there is an error raised by the device's decoder `MS_OMX_H264DEC`, which is propagated to by platform to the player

```
E MS_OMX_H264DEC: Error Code: 1000001 0 0 0
E ACodec  : [OMX.MS.AVC.Decoder] ERROR(0x90000001)
E ACodec  : signalError(omxError 0x90000001, internalError -2147483648)
E MediaCodec: Codec reported err 0x90000001, actionCode 0, while in state 6
```

I'm afraid I cannot offer better help, I did not find anything specific to this error. Please try reaching out to the device manufacturer.
