### ISSUE TITLE
Cannot play live stream "Unexpected exception loading stream"

### ISSUE THREAD

**Issue by abhiguru** [google/ExoPlayer#988]
Andorid : 5.1
Live Stream URL : http://video.vcu.tv/mpd/stream.mpd

Seems like an error parsing the MPD but cannot really tell what or where it is any help much appreciated. 

? I/OpenGLRenderer: Initialized EGL, version 1.4
? D/OpenGLRenderer: Enabling debug mode 0
com.google.android.exoplayer.demo I/ExoPlayerImpl: Init 1.5.2
com.google.android.exoplayer.demo D/EventLogger: start [0]
com.google.android.exoplayer.demo D/EventLogger: state [0.00, false, P]
com.google.android.exoplayer.demo D/EventLogger: state [0.00, true, P]
com.google.android.exoplayer.demo E/LoadTask: Unexpected exception loading stream
                                              java.lang.NumberFormatException: Invalid int: ""
                                                  at java.lang.Integer.invalidInt(Integer.java:138)
                                                  at java.lang.Integer.parseInt(Integer.java:358)
                                                  at java.lang.Integer.parseInt(Integer.java:334)
                                                  at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseInt(MediaPresentationDescriptionParser.java:704)
                                                  at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseRepresentation(MediaPresentationDescriptionParser.java:369)
                                                  at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseAdaptationSet(MediaPresentationDescriptionParser.java:253)
                                                  at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parsePeriod(MediaPresentationDescriptionParser.java:204)
                                                  at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseMediaPresentationDescription(MediaPresentationDescriptionParser.java:134)
                                                  at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:97)
                                                  at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:55)
                                                  at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93)
                                                  at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                  at java.lang.Thread.run(Thread.java:818)
com.google.android.exoplayer.demo E/EventLogger: internalError [0.27, rendererInitError]
                                                 com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected NumberFormatException: Invalid int: ""
                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.lang.NumberFormatException: Invalid int: ""
                                                     at java.lang.Integer.invalidInt(Integer.java:138)
                                                     at java.lang.Integer.parseInt(Integer.java:358)
                                                     at java.lang.Integer.parseInt(Integer.java:334)
                                                     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseInt(MediaPresentationDescriptionParser.java:704)
                                                     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseRepresentation(MediaPresentationDescriptionParser.java:369)
                                                     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseAdaptationSet(MediaPresentationDescriptionParser.java:253)
                                                     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parsePeriod(MediaPresentationDescriptionParser.java:204)
                                                     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseMediaPresentationDescription(MediaPresentationDescriptionParser.java:134)
                                                     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:97)
                                                     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:55)
                                                     at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93)
                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                     at java.lang.Thread.run(Thread.java:818) 
com.google.android.exoplayer.demo E/EventLogger: playerFailed [0.28]
                                                 com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected NumberFormatException: Invalid int: ""
                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.lang.NumberFormatException: Invalid int: ""
                                                     at java.lang.Integer.invalidInt(Integer.java:138)
                                                     at java.lang.Integer.parseInt(Integer.java:358)
                                                     at java.lang.Integer.parseInt(Integer.java:334)
                                                     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseInt(MediaPresentationDescriptionParser.java:704)
                                                     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseRepresentation(MediaPresentationDescriptionParser.java:369)
                                                     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseAdaptationSet(MediaPresentationDescriptionParser.java:253)
                                                     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parsePeriod(MediaPresentationDescriptionParser.java:204)
                                                     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseMediaPresentationDescription(MediaPresentationDescriptionParser.java:134)
                                                     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:97)
                                                     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:55)
                                                     at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93)
                                                     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                     at java.lang.Thread.run(Thread.java:818) 
com.google.android.exoplayer.demo D/EventLogger: state [0.28, true, I]

**Comment by abhiguru** [comment]
AudioSamplingRate="" in the MPD was throwing an exception

<SegmentTemplate startNumber="0" initialization="../dash/$RepresentationID$/sampletryfive-init.m4a" media="../dash/$RepresentationID$/sampletryfive-$Number$.m4a" duration="4"/>


-<Representation id="2400k" codecs="mp4a.40.2" bandwidth="128000" audioSamplingRate="">

<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>

</Representation>

</AdaptationSet>
