### ISSUE TITLE
Fatal Exception Neither user nor current process has android.permission.WAKE_LOCK

### ISSUE THREAD

**Issue by BrettyWhite** [google/ExoPlayer#9883]
Hello, I am experiencing an odd error with Exoplayer and specifically Galaxy S20 and S21 devices running Android 12. 

I have been getting crashlytics reports that the user / process don't have wake lock permissions:

![Screen Shot 2022-01-21 at 9 10 24 AM](https://user-images.githubusercontent.com/3911458/150541743-c7f163fa-8702-4056-b9f3-8616a22190eb.png)

I have `WAKE_LOCK` in my permissions:

```xml
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
```

And I am using `setWakeMode` to handle the locks and am not handling them myself:

```kotlin
    private fun initPlayer() {
        mCurrentPlayer = mContext?.let { ExoPlayer.Builder(it).build() }
        mCurrentPlayer?.playWhenReady = true
        mCurrentPlayer?.repeatMode = Player.REPEAT_MODE_ALL
        val mediaSource = createMediaSource()
        if (mediaSource != null) {
            mCurrentPlayer?.setMediaSource(mediaSource)
            mCurrentPlayer?.addListener(playerListener)
            mCurrentPlayer?.setWakeMode(C.WAKE_MODE_NETWORK)
            mCurrentPlayer?.volume = sound.volume.toFloat()
            mCurrentPlayer?.prepare()
        }
    }
```

In my specific use cases, there might be multiple instances of players set up in the same manner as the previous example, all running at the same time. The Service is a `MediaBrowserService` and the app is used to play sounds in the background for long periods of time.

I have not experienced this issue personally, and cannot reproduce it on my Pixel 5a running 12, and was curious if anyone had seen this or might know if I'm doing something wrong.

Devices Affected: 
- Samsung S21 5G - Android 12
- Samsung S20 Ultra - Android 12

Exoplayer Version: **2.16.1**
App's Target API: **30**

Thank you!

EDIT:

additional part of trace:

```
Caused by android.os.RemoteException
Remote stack trace: at android.app.ContextImpl.enforce(ContextImpl.java:2273) at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2301) at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:8202) at android.os.IPowerManager$Stub.onTransact(IPowerManager.java:588) at android.os.Binder.execTransactInternal(Binder.java:1215) 
```

**Comment by BrettyWhite** [comment]
I can help debug if needed, just trying to see if there will be any movement on this?

**Comment by marcbaechinger** [comment]
Sorry for my late reply. 

It's currently unclear how this can happen. We checked on a Samsung phone to see whether the user can reject the WAKELOCK permission manually but it doesn't seem to be. So it's unclear how the process or user can not have this granted.

For how many percentage of the user on these devices is such an exception logged?

**Comment by BrettyWhite** [comment]
We had a total of 17 instances of this specific crash - all on Samsung devices on Android 12. I also saw some odd errors regarding Foreground Service exceptions (starting from the background, unrelated to this - even though its not possible in our app). 

We have since set our Target API to 30 from 31 and these errors have stopped. We have chalked them up to API 31 having quite a few unresolved bugs, especially on Samsung's implementation. As of now we will probably stay on 30 until we are forced to upgrade to 31. - just wanted to make you all aware in case others are experiencing the same issue.

**Comment by BrettyWhite** [comment]
Actually just got another instance of this last night, from a version that was targeting API 30, not 31. The device was still a Samsung running Android 12.

![Screen Shot 2022-02-01 at 9 20 28 AM](https://user-images.githubusercontent.com/3911458/151985670-12e7eab8-4ddb-4bea-8b52-6345b3d4191a.png)

![Screen Shot 2022-02-01 at 9 20 52 AM](https://user-images.githubusercontent.com/3911458/151985705-cf1b12e7-459b-462a-89f6-e5e3d9f58280.png)

Edit: Another Image

![Screen Shot 2022-02-01 at 9 23 52 AM](https://user-images.githubusercontent.com/3911458/151986052-741c4038-7909-4831-80f0-33e7e5850700.png)

**Comment by BrettyWhite** [comment]
Still seeing this, now on additional devices like the Samsung Galaxy A42 5G running Android 12. 

Only seems to be Samsung specific

**Comment by shakht** [comment]
hello, so currently i am facing the same issue, and i have's left any check or idea without testing it, and it didn't fix the issue, did you reach a fix?
thanks in advance.

**Comment by zhoujielun111** [comment]
谢谢啦！邮件我已经收到了！！

**Comment by shakht** [comment]
FOUND IT: search for the permission 'android.permission.WAKE_LOCK' through all your project, there must be a library that is using this permission but limits the sdk version like this

`<uses-permission
        android:name="android.permission.WAKE_LOCK"
        android:maxSdkVersion="25" />`

**so the solution is**
in your project manifest just add a node replace like this

`    <uses-permission android:name="android.permission.WAKE_LOCK"
        tools:node="replace" />`

and it will fix the issue
