### ISSUE TITLE
Video Codec Error

### ISSUE THREAD

**Issue by narasimharao11** [google/ExoPlayer#9952]
Hi Team, 
   We have updated exoplayer version from 2.11.2 to 2.16.0 . After updating the player when we try to change the bitrate multiple times, we are facing the Video codec error in android OS 12 (iQOO Z3 5G). 
 We hardcoded the stream url and drm license url in demo app. We reproduced the same issue in exoplayer demo app 2.16.0 and attached the logs and complete bug report.

Adb Logs

```
E/MediaCodecVideoRenderer: Video codec error
      java.lang.IllegalStateException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2284)
        at u1.b.run(Unknown Source:2)
        at u1.h.o(Unknown Source:35)
        at u1.h.n(Unknown Source:3)
        at u1.h.j(Unknown Source:0)
        at u1.h.a(Unknown Source:0)
        at u1.g.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:334)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-02-08 10:59:52.789 6949-6949/? D/EventLogger: downstreamFormat [eventTime=10.07, mediaPos=647.23, window=0, period=0, id=7, mimeType=video/avc, bitrate=300000, codecs=avc1.64000d, drm=[playready,widevine,cenc], res=384x216, fps=25.0]
2022-02-08 10:59:52.790 6949-8103/? E/ExoPlayerImplInternal: Playback error
      w0.p: MediaCodecVideoRenderer error, index=0, format=Format(7, null, null, video/avc, avc1.64000D, 300000, null, [384, 216, 25.0], [-1, -1]), format_supported=YES
        at w0.c1.handleMessage(Unknown Source:350)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:334)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.i: Decoder failed: OMX.qcom.video.decoder.avc.secure
        at com.google.android.exoplayer2.video.j.b0(Unknown Source:4)
        at u1.p.m(Unknown Source:149)
        at w0.c1.q(Unknown Source:91)
        at w0.c1.handleMessage(Unknown Source:220)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loopOnce(Looper.java:233) 
        at android.os.Looper.loop(Looper.java:334) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalStateException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2284)
        at u1.b.run(Unknown Source:2)
        at u1.h.o(Unknown Source:35)
        at u1.h.n(Unknown Source:3)
        at u1.h.j(Unknown Source:0)
        at u1.h.a(Unknown Source:0)
        at u1.g.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233) 
        at android.os.Looper.loop(Looper.java:334) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

- ExoPlayer version number - 2.16.0
- Android version -12 
- Android device - IQOO Z3 5G

Please find the attached bug report
[bugreport-2011i-SP1A.210812.003-2022-02-08-18-58-01.zip](https://github.com/google/ExoPlayer/files/8024303/bugreport-2011i-SP1A.210812.003-2022-02-08-18-58-01.zip)

**Comment by narasimharao11** [comment]
Hi Team,

After updating the player to 2.16.0 from 2.11.2 we are having this issue.We are facing a blocker for this issue please reply back as soon as possible. We reproduced the same issue in exoplayer demo app 2.16.0 and attached the latest complete bug report.


[bugreport-2011i-SP1A.210812.003-2022-03-04-19-57-39.zip](https://github.com/google/ExoPlayer/files/8186587/bugreport-2011i-SP1A.210812.003-2022-03-04-19-57-39.zip)

**Comment by narasimharao11** [comment]
We have sent an email all the details.
