### ISSUE TITLE
DRM Exception in some devices

### ISSUE THREAD

**Issue by giovannyvelezalt** [google/ExoPlayer#9958]
We have been getting this stack trace reported in NewRelic:

```
android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error at google.DefaultDrmSession.onError(DefaultDrmSession.java:1) 
at DefaultDrmSession.onKeysError(DefaultDrmSession.java:3) 
at DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:5) 
at doLicense(DefaultDrmSession.java:11) 
at acquire(DefaultDrmSession.java:8) 
at acquireSession(DefaultDrmSessionManager.java:17) 
at com.google.android.exoplayer2.source.SampleMetadataQueue.onFormatResult(SampleMetadataQueue.java:13) 
at com.google.android.exoplayer2.source.SampleMetadataQueue.read(SampleMetadataQueue.java:22) 
at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:2) 
at ChunkSampleStream.readData(ChunkSampleStream.java:3) 
at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:1) 
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:3) 
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:6) 
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:14) 
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:17) 
at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:223) 
at android.os.HandlerThread.run(HandlerThread.java:67) Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error at android.media.MediaDrm.getKeyRequest(Native Method) 
at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:5) 
at DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:2) ... 15 more android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error 
at android.media.MediaDrm.getKeyRequest(Native Method) 
at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:5) 
at DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:2) 
at DefaultDrmSession.doLicense(DefaultDrmSession.java:11) 
at DefaultDrmSession.acquire(DefaultDrmSession.java:8) 
at .DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:17) 
at com.google.android.exoplayer2.source.SampleMetadataQueue.onFormatResult(SampleMetadataQueue.java:13) 
at com.google.android.exoplayer2.source.SampleMetadataQueue.read(SampleMetadataQueue.java:22) 
at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:2) 
at ChunkSampleStream.readData(ChunkSampleStream.java:3) 
at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:1) 
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:3) 
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:6) 
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:14)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:17)
at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:223) 
at android.os.HandlerThread.run(HandlerThread.java:67)
```

We extracted a list of devices affected by the issue 
[DevicesWithError.xlsx](https://github.com/google/ExoPlayer/files/8032789/DevicesWithError.xlsx)

and we have requested one user with a OnePlus 6T to extract a log report

[bugreport-OnePlus6T-RKQ1.201217.002-2022-02-06-10-20-51.zip](https://github.com/google/ExoPlayer/files/8032799/bugreport-OnePlus6T-RKQ1.201217.002-2022-02-06-10-20-51.zip)

It looks like this issue is related to https://github.com/google/ExoPlayer/issues/9137

**Comment by ojw28** [comment]
@rrfrias - Please take a look. Thanks!

**Comment by rrfrias** [comment]
The stack trace indicates an error when requesting a license, but there is not enough information in this stack trace to tell more. We added more information to stack traces in android 12 devices, so if you have one from those devices, it would help.

A bugreport would be even more helpful. The one attached unfortunately does not contain any errors or Exceptions. 

> It looks like this issue is related to https://github.com/google/ExoPlayer/issues/9137

Why do you think it is related to that issue. You seem to be using the platform DRM. Let me know if i am mistaken.
