### ISSUE TITLE
Can ExoPlayer Transformer handle any audio input format?

### ISSUE THREAD

**Issue by ziad-halabi9** [google/ExoPlayer#9960]
I am testing out the ExoPlayer `Transformer` (2.13.0) and followed the tutorial described here: https://exoplayer.dev/transforming-media.html

When I input an m4a file as an input MediaItem, it works fine. But if I input any mp3 or wav file, the transformer fails with the following stacktrace: 

```
022-02-08 18:17:13.268 6746-6746/com.android.transformertest W/System.err: java.lang.IllegalStateException: The output does not contain any tracks. Check that at least one of the input sample formats is supported.
2022-02-08 18:17:13.268 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.transformer.Transformer$TransformerAnalyticsListener.onTracksChanged(Transformer.java:634)
2022-02-08 18:17:13.268 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.analytics.AnalyticsCollector.lambda$onTracksChanged$35(AnalyticsCollector.java:588)
2022-02-08 18:17:13.268 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.analytics.-$$Lambda$AnalyticsCollector$7tg5KkucYfjKC8XMa7Ki5D-f7tE.invoke(Unknown Source:8)
2022-02-08 18:17:13.268 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:297)
2022-02-08 18:17:13.268 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:184)
2022-02-08 18:17:13.268 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6)
2022-02-08 18:17:13.268 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:205)
2022-02-08 18:17:13.268 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:220)
2022-02-08 18:17:13.268 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.analytics.AnalyticsCollector.sendEvent(AnalyticsCollector.java:797)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.analytics.AnalyticsCollector.onTracksChanged(AnalyticsCollector.java:585)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$10(ExoPlayerImpl.java:1035)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$VXzfUrPSnMl-ySIw0FPLtylNgIY.invoke(Unknown Source:6)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:297)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:184)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:205)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1101)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:965)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1$ExoPlayerImpl(ExoPlayerImpl.java:181)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$nOBJYkeEQ2uz3sBKLToLWmzrgZk.run(Unknown Source:4)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at android.os.Looper.loop(Looper.java:237)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8167)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
2022-02-08 18:17:13.269 6746-6746/com.android.transformertest W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

This is thrown from the `Transformer's` `onTracksChanged` where the `muxerWrapper` has 0 track count. I also noticed that the `TrackSelectionArray` has just one `null` item.

So I am wondering if this is a limitation to the Transformer or if it is possible to support any audio format?

I also asked this question on StackOverflow with a bounty here: https://stackoverflow.com/questions/71004666/write-exoplayer-output-to-a-file

Thank you!

**Comment by kim-vde** [comment]
Hi,

The supported output formats are the same as in [MediaMuxer](https://developer.android.com/reference/android/media/MediaMuxer#addTrack(android.media.MediaFormat)). For MP4, the supported audio formats are AAC, AMR NB and AMR WB. The version of the Transformer in 2.13.0 will output the same sample MIME type as the input. So, if you feed it MP3/WAV, it will try to output MP3/WAV and will fail.

What you could do to overcome this is to use the Transformer in ExoPlayer 2.17 (which should be out very soon), where we have added support for setting the output sample MIME types and for fallbacking to a supported MIME type when the input one is not supported. Note that Transformer is still work in progress. It might not work on some devices and the API is likely to change in the future.

**Comment by ziad-halabi9** [comment]
Thank you @kim-vde for your response. I understand now and I am glad that more work has been done on the Transformer and looking forward to the 2.17 version.

My use case here is that I have a player with some `AudioProcessors` that the user can control. I want a way to output the song along with those changes to a file. I modified the Transformer to include the `AudioProcessors` and it worked out great. Except for the unsupported formats. 

Can you please elaborate a bit more on "it might not work on some devices"? My App is already in production and my only alternative to this is to use `FFmpeg` lib. But I prefer an ExoPlayer solution. Thanks!

**Comment by kim-vde** [comment]
>  I modified the Transformer to include the AudioProcessors and it worked out great.

Note that we plan to integrate the Transformer with AudioProcessors as well so what you want to do should become much easier in the future!

> Can you please elaborate a bit more on "it might not work on some devices"?

If your media file contains video frames and these video frames are not encoded in order, muxing will fail because out-of-order frames are not supported by the [MediaMuxer](https://developer.android.com/reference/android/media/MediaMuxer). We are planning to fix this but it might take a bit of time as this is not an easy task.
