### ISSUE TITLE
ParserException: Searched too many bytes.

### ISSUE THREAD

**Issue by githubashutoshsoni** [google/ExoPlayer#9964]
one of the files is not playing when I play using the below code. The file I'm using is this please download this or upload to some server as [this link]() let me know what to do to fix this? thanks! I have read the guidelines and sent the mail. There's nothing like DRM content protection for the time being. 

```

   fun playAudio(id: Int, url: String) {

        if (currentPlayingId == null || currentPlayingId != id) {

            if (currentPlayingId != null) {
                calculatePlayTimeAndUpdateServer(getCurrentItem()?.id)
            }
            val extractorsFactory = DefaultExtractorsFactory()
                .setMp3ExtractorFlags(Mp3Extractor.FLAG_ENABLE_CONSTANT_BITRATE_SEEKING)



            val mediaSource = ProgressiveMediaSource
                .Factory(
                    DefaultDataSourceFactory(applicationContext, userAgent),
                    DefaultExtractorsFactory()
                ).setCustomCacheKey("InharmonyAudio_$id")
                .createMediaSource(
                    MediaItem.fromUri(Uri.parse(url))

                )


            val attr = AudioAttributes.Builder().setUsage(C.USAGE_MEDIA)
                .setContentType(C.CONTENT_TYPE_MUSIC)
                .build()

            exoPlayer?.setAudioAttributes(attr, true)

            exoPlayer?.setMediaSource(mediaSource)
            exoPlayer?.prepare()
            userSetPlayWhenReadyValue = true
            exoPlayer?.playWhenReady = true
        } else {
            val oppositeValue = !isCurrentlyPlaying()
            userSetPlayWhenReadyValue = oppositeValue
            exoPlayer?.playWhenReady = oppositeValue
        }
        currentPlayingId = id
        currentlyPlayingUrl = url

        bottomListener?.onStatusChanged(exoPlayer?.playWhenReady ?: false)

    }

```

The error logs are as follows: 
```

2022-02-10 15:47:09.583 13720-19030/com.app.app W/AHierarchicalStateMachine: Warning message AMessage(what = 'omxI') = {
      int32_t type = 0
      int32_t event = 3
      int32_t data1 = 1
      int32_t data2 = 0
    } unhandled in root state.
2022-02-10 15:47:09.583 13720-19030/com.app.app W/AHierarchicalStateMachine: Warning message AMessage(what = 'omxI') = {
      int32_t type = 0
      int32_t event = 3
      int32_t data1 = 1
      int32_t data2 = 0
    } unhandled in root state.
2022-02-10 15:47:09.612 13720-18793/com.app.app D/AudioTrack: setVolume(1.000000, 1.000000) pid : 13720
2022-02-10 15:47:09.636 13720-19030/com.app.app I/ACodec: [OMX.SEC.mp3.dec] Now Executing
2022-02-10 15:47:10.499 13720-18793/com.app.app E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:628)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:598)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.ParserException: Searched too many bytes.
        at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.synchronize(Mp3Extractor.java:381)
        at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.readInternal(Mp3Extractor.java:256)
        at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.read(Mp3Extractor.java:229)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2022-02-10 15:47:10.501 13720-19030/com.app.app I/ACodec: [OMX.SEC.mp3.dec] signalFlush
2022-02-10 15:47:10.502 13720-19030/com.app.app I/ACodec: [OMX.SEC.mp3.dec] ExecutingState flushing now (codec owns 0/10 input, 5/5 output).
2022-02-10 15:47:10.503 13720-19030/com.app.app I/ACodec: [OMX.SEC.mp3.dec] Now Flushing
2022-02-10 15:47:10.508 13720-19030/com.app.app I/ACodec: [OMX.SEC.mp3.dec] FlushingState onOMXEvent(0,1,0)

```

The device I have tested is on Samsung M7. Android 11. it happens on most of the Android 11 devices. running fine on Android 10 or Android 12. Exoplayer version 2.16.1

**Comment by ojw28** [comment]
I do not see the same error that you see, using the link you've provided. I'm also using 2.16.1. That said, the file still doesn't play because it's using `audio/mpeg-L1`, which is not supported on all Android devices.
```
Group:0, adaptive_supported=N/A [
    [ ] Track:0, id=null, mimeType=audio/mpeg-L1, channels=1, sample_rate=32000, supported=NO_UNSUPPORTED_TYPE
]
```
As a first step, I suggest you encode your content in a more widely supported format.

**Comment by githubashutoshsoni** [comment]
Okay, so currently the only solution is to change the source audio to raw or other format.
