### ISSUE TITLE
Custom rendered causes playback and performance issue

### ISSUE THREAD

**Issue by GlebPBanuba** [google/ExoPlayer#9966]
Hi,
we found performance and playback issue after adding custom renderer in playback process.

Here is the repo that demonstrates the issue
 https://github.com/ve-sdk-android/ExoPlayer-sample

Our custom renderer is https://github.com/ve-sdk-android/ExoPlayer-sample/blob/master/app/src/main/java/com/banuba/exoplayer/sample/VideoFrameDrawer.kt that should add blur

Please take a look this issue.
Looking forward to seeing your reply

**Comment by ojw28** [comment]
This sounds like a performance problem with the customizations you're adding, in which case this isn't an ExoPlayer issue. If you believe there's an ExoPlayer issue here then please could be more precise about what it is. We're unable to provide assistance on issues relating to your own code. Thanks!

**Comment by GlebPBanuba** [comment]
The repo https://github.com/ve-sdk-android/ExoPlayer-sample is just a sample that should ONLY help you to reproduce the issue.

Our custom Player does not have such performance and playback issues 
but ExoPlayer posts bunch of errors in LogCat.

Below are errors from my Pixel 2 XL

//1
```
2022-02-11 00:45:29.390 27433-27462/com.banuba.exoplayer.sample E/MediaCodecVideoRenderer: Video codec error
      android.media.MediaCodec$CodecException: Error 0xffffffc2
```

// 2
```
2022-02-11 00:45:29.391 27433-27462/com.banuba.exoplayer.sample D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2160x3840x59.99980163574219] [c2.android.hevc.decoder, video/hevc] [taimen, Pixel 2 XL, Google, 30]
2022-02-11 00:45:29.395 27433-27462/com.banuba.exoplayer.sample E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/hevc, hvc1.1.6.L150.B0, -1, null, [2160, 3840, 59.9998], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.hevc
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1470)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:799)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.media.MediaCodec$CodecException: Error 0xffffffc2
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2298)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:188)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:850)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:843)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReinitializeCodec(MediaCodecRenderer.java:819)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.maybeDropBuffersToKeyframe(MediaCodecVideoRenderer.java:1140)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.processOutputBuffer(MediaCodecVideoRenderer.java:961)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1839)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:778)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 

        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2298)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:188)
```

//3
```
2022-02-11 00:45:29.397 27433-27462/com.banuba.exoplayer.sample E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2298)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:188)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:850)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:843)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:696)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:529)
```

//4 
```
2022-02-11 00:45:29.404 27433-27468/com.banuba.exoplayer.sample E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7b5bf77210
2022-02-11 00:45:29.404 27433-27468/com.banuba.exoplayer.sample W/ACodec: [OMX.qcom.video.decoder.hevc] can not return buffer 30 to native window
```

Since our project highly depends on ExoPlayer we really need your assistance in this issue.
Please take a look the repo that reproduces the issue.

What information would be helpful to you to resolve the issue?

**Comment by ojw28** [comment]
It seems relatively likely to me that a 5 year old phone just isn't powerful enough to play 4K 60FPS HEVC content, and also apply custom GL rendering steps to it at the same time. Have you tried using lower resolution content?

**Comment by GlebPBanuba** [comment]
Our custom player based on ffmpeg + Media Codec API does not have such issue on Pixel 2 XL.

**Comment by GlebPBanuba** [comment]
Hi! any updates on this issue?

**Comment by GlebPBanuba** [comment]
Hello!
What updates on this issue?

**Comment by GlebPBanuba** [comment]
@ojw28 Hi! any updates?

**Comment by ojw28** [comment]
This isn't something we have capacity to provide support on, I'm afraid. It seems highly specific to your individual app setup.
