### ISSUE TITLE
This particular stream does not play

### ISSUE THREAD

**Issue by lpv-1902** [google/ExoPlayer#9975]
I keep getting an error on this particular stream but it works on browsers with HLS M3u8 extensions and on Safari on Mac.

Stream: https://d1pdqnzctoj5f8.cloudfront.net/clients_live/tv3/vr-hd1/playlist.m3u8

```
[ExoPlayerImplInternal] Source error
[ExoPlayerImplInternal]   com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: interceptor okhttp3.OkHttpClient$Builder_InterceptorImpl@a323790 returned a response with no body
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:442)
[ExoPlayerImplInternal]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[ExoPlayerImplInternal]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[ExoPlayerImplInternal]       at java.lang.Thread.run(Thread.java:914)
[ExoPlayerImplInternal]   Caused by: java.lang.IllegalStateException: interceptor okhttp3.OkHttpClient$Builder_InterceptorImpl@a323790 returned a response with no body
[ExoPlayerImplInternal]       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:161)
[ExoPlayerImplInternal]       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[ExoPlayerImplInternal]       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
[ExoPlayerImplInternal]       at okhttp3.RealCall.execute(RealCall.java:93)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:220)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:170)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
[ExoPlayerImplInternal]       ... 3 more
```

**Comment by icbaker** [comment]
The provided link works fine for me in the [demo app](https://exoplayer.dev/demo-application.html) at 2.16.1 using `CronetDataSource` (the default), `OkHttpDataSource` and `DefaultHttpDataSource` (I edited [the source](https://github.com/google/ExoPlayer/blob/r2.16.1/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoUtil.java#L94) to use these other two).

From the stack trace, is it possible that a custom OkHttp interceptor that you're providing in your app is misbehaving?

If you can also play this content successfully with the demo app that suggests the problem is likely in your app rather than in the ExoPlayer library.
