### ISSUE TITLE
NPE when download manifest with DashUtil.loadManifest 

### ISSUE THREAD

**Issue by schnaps1981** [google/ExoPlayer#9979]
Hi Team!
i want to download offline license key, ant then save it to local database.
i created such helper-class

```
class LicenseDownloader @Inject constructor(
    private val context: Context
) {

    private val userAgent = Util.getUserAgent(context, "ua")
    private val drmSessionEventListener = object : DrmSessionEventListener.EventDispatcher() {}

    private val httpDataSourceFactory = DefaultHttpDataSource.Factory().setUserAgent(userAgent)
    private val dataSource = httpDataSourceFactory.createDataSource()

    suspend fun downloadLicense(
        manifestUrl: String,
        licenseUrl: String
    ): ByteArray {

        val offlineLicenseHelper = OfflineLicenseHelper
            .newWidevineInstance(licenseUrl, httpDataSourceFactory, drmSessionEventListener)

        return runCatching {
            withContext(Dispatchers.IO) {

                val dashManifest = DashUtil.loadManifest(
                    dataSource,
                    Uri.parse(manifestUrl)
                )

                val drmInitData =
                    DashUtil.loadFormatWithDrmInitData(dataSource, dashManifest.getPeriod(0))
                val license = offlineLicenseHelper.downloadLicense(drmInitData!!)

                license
            }
        }.also {

            offlineLicenseHelper.release()
        }.getOrElse {
            Timber.e(it.localizedMessage)

            ByteArray(0)
        }
    }
}
```

after start application, first call of licenseDownloader.downloadLicense(manifestUrl, licenseUrl) ends success, but second call throws NPE with **message java.lang.NullPointerException: wrapped.getHeaderField(key) must not be null**

```
W/System.err: java.lang.NullPointerException: wrapped.getHeaderField(key) must not be null
2022-02-16 03:41:57.229 14002-14162/com.xxxxxxxx W/System.err:     at com.android.tools.appinspection.network.httpurl.TrackedHttpURLConnection.getHeaderField(TrackedHttpURLConnection.kt:317)
2022-02-16 03:41:57.229 14002-14162/com.xxxxxxxx W/System.err:     at com.android.tools.appinspection.network.httpurl.HttpsURLConnectionWrapper.getHeaderField(HttpsURLConnectionWrapper.kt:182)
2022-02-16 03:41:57.229 14002-14162/com.xxxxxxxx W/System.err:     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.isCompressed(DefaultHttpDataSource.java:774)
2022-02-16 03:41:57.229 14002-14162/com.xxxxxxxx W/System.err:     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:405)
2022-02-16 03:41:57.229 14002-14162/com.xxxxxxxx W/System.err:     at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
2022-02-16 03:41:57.230 14002-14162/com.xxxxxxxx W/System.err:     at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
2022-02-16 03:41:57.230 14002-14162/com.xxxxxxxx W/System.err:     at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
2022-02-16 03:41:57.230 14002-14162/com.xxxxxxxx W/System.err:     at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:177)
2022-02-16 03:41:57.230 14002-14162/com.xxxxxxxx W/System.err:     at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:69)
2022-02-16 03:41:57.230 14002-14162/com.xxxxxxxx W/System.err:     at com.google.android.exoplayer2.source.dash.DashUtil.loadManifest(DashUtil.java:75)
2022-02-16 03:41:57.230 14002-14162/com.xxxxxxxx W/System.err:     at com.xxxxxxxx.player.LicenseDownloader$downloadLicense$2.invokeSuspend(LicenseDownloader.kt:78)
2022-02-16 03:41:57.230 14002-14162/com.xxxxxxxx W/System.err:     at com.xxxxxxxx.player.LicenseDownloader$downloadLicense$2.invoke(Unknown Source:10)
2022-02-16 03:41:57.230 14002-14162/com.xxxxxxxx W/System.err:     at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
2022-02-16 03:41:57.230 14002-14162/com.xxxxxxxx W/System.err:     at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
2022-02-16 03:41:57.230 14002-14162/com.xxxxxxxx W/System.err:     at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
2022-02-16 03:41:57.230 14002-14162/com.xxxxxxxx W/System.err:     at com.xxxxxxxx.player.LicenseDownloader.downloadLicense(LicenseDownloader.kt:74)
2022-02-16 03:41:57.230 14002-14162/com.xxxxxxxx W/System.err:     at com.xxxxxxxx.utils.DownloadHelper$updateAvailabilityStatus$$inlined$forEach$lambda$1$1.invokeSuspend(DownloadHelper.kt:127)
2022-02-16 03:41:57.230 14002-14162/com.xxxxxxxx W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-02-16 03:41:57.230 14002-14162/com.xxxxxxxx W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-02-16 03:41:57.231 14002-14162/com.xxxxxxxx W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2022-02-16 03:41:57.231 14002-14162/com.xxxxxxxx W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-02-16 03:41:57.231 14002-14162/com.xxxxxxxx W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2022-02-16 03:41:57.231 14002-14162/com.xxxxxxxx W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Exception thrown in the line **DashUtil.loadManifest**. 

what is the problem? help me please! i spend about 2 days, but does not find solution (((

Android 10 (Emulator and other devices)
ExoPlayer v2.14.0

**Comment by icbaker** [comment]
This is a bug in Android Studio's implementation of `URLConnection`: https://issuetracker.google.com/219572925

**Comment by Kolyall** [comment]
@icbaker why the issue is closed? It still reproduce. 
ExoPlayer v2.16.1
```
Android Studio Bumblebee | 2021.1.1 Patch 1
Build #AI-211.7628.21.2111.8139111, built on February 1, 2022
Runtime version: 11.0.11+0-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-100-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 12
Registry: external.system.auto.import.disabled=true, debugger.watches.in.variables=false
Non-Bundled Plugins: JUnit4-Parallel-Runner (1.5), com.intellij.javafx (1.0.4), com.intellij.marketplace (211.7628.36), com.atlassian.bitbucket.references (2021.1.195), com.thoughtworks.gauge (211.6693.111), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), com.developerphil.adbidea (1.6.4)
Current Desktop: ubuntu:GNOME
```

**Comment by schnaps1981** [comment]
@Kolyall that is no problem of exoplayer.

you can try to use okhttp datasource

1. you need import dependency 
`"com.google.android.exoplayer:extension-okhttp:**xx.xx.xx (your exoplayer version)**"`

2. then
```
val client = OkHttpClient.Builder().build()

val okhttpDataSourceFactory = OkHttpDataSource.Factory(okHttpClient)

val okHttpDataSource = okhttpDataSourceFactory.createDataSource()`

val drmInitData = DashUtil.loadFormatWithDrmInitData(okHttpDataSource, dashManifest.getPeriod(0))

```
it works fine for me

**Comment by Kolyall** [comment]
"com.google.android.exoplayer:extension-okhttp:2.16.1"

```
val client = OkHttpClient.Builder().build()

val okhttpDataSourceFactory = OkHttpDataSource.Factory(okHttpClient)

val okHttpDataSource = okhttpDataSourceFactory.createDataSource()`

val drmInitData = DashUtil.loadFormatWithDrmInitData(okHttpDataSource, dashManifest.getPeriod(0))//after call the line error
```
Error:
```
java.lang.ArrayIndexOutOfBoundsException: size=16 offset=0 byteCount=-64
        at okio._UtilKt.checkOffsetAndCount(-Util.kt:24)
        at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:155)
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.readInternal(OkHttpDataSource.java:494)
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.read(OkHttpDataSource.java:356)
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:92)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:291)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:80)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomHeader(FragmentedMp4Extractor.java:354)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:328)
        at com.google.android.exoplayer2.source.chunk.BundledChunkExtractor.read(BundledChunkExtractor.java:152)
        at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:102)
        at com.google.android.exoplayer2.source.dash.DashUtil.loadInitializationData(DashUtil.java:303)
        at com.google.android.exoplayer2.source.dash.DashUtil.loadInitializationData(DashUtil.java:257)
        at com.google.android.exoplayer2.source.dash.DashUtil.loadSampleFormat(DashUtil.java:144)
        at com.google.android.exoplayer2.source.dash.DashUtil.loadSampleFormat(DashUtil.java:167)
        at com.google.android.exoplayer2.source.dash.DashUtil.loadFormatWithDrmInitData(DashUtil.java:117)
```

**Comment by icbaker** [comment]
@Kolyall please file a new issue for the `ArrayIndexOutOfBoundsException` problem, with all the info requested in the issue template - in particular a link to a stream we can use to reproduce the issue.
