### ISSUE TITLE
Exception  in  FragmentedMp4Extractor.java when streaming Playready3.0+ HEVC Content ( Video Protected and Audio Clear) 

### ISSUE THREAD

**Issue by santoshray** [google/ExoPlayer#9998]
**Issue Descri[ption**
Hi Exoplayer Team 
The Bug being filed doesn't  seem to be present  in  https://github.com/google/ExoPlayer/issues?q=is%3Aissue
We have consulted  Check the supported formats: https://exoplayer.dev/supported-formats.html . 
It  mentions that Playready SL2000 is supported  in  Android TV . But even if we are testing Playready SL 3000  , the issue is independent of the DRM license  . 

The issue being reported is related to  FragmentedMp4Extractor.java. There is exception  at  https://github.com/google/ExoPlayer/blob/release-v2/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mp4/FragmentedMp4Extractor.java#L1315
when trying to stream  encrypted HEVC Playready3.0+ URL listed in https://testweb.playready.microsoft.com/Content/Content3X
There is no issue when streaming  the corresponding  clear File . 

Below is the Summary of which contents are playable and  which are not

1. None of the Encrypted HEVC file can be streamed . But the same content can be played  on Windows PC  using PlayReadyWWA JS Sample player  present in  Microsoftstore  and installing HEVC decoder extension  .
   Example  Encrypted File   http://profficialsite.origin.mediaservices.windows.net/58505412-db41-447b-8adc-727811182ac3/tearsofsteel_4k_60s_24fps.12000kbps.3840x2160.h265-10b.2ch.128kbps.aac.audioclear.cenc.mp4   under   ( HEVC 10-bit depth 3840x2160 @12Mbps ).

2. Also there is no issue in streaming Clear HEVC file  .
 Example : http://profficialsite.origin.mediaservices.windows.net/3caed20a-04e3-4f7c-9a4b-ff6afcaba2da/tearsofsteel_4k_60s_24fps.12000kbps.3840x2160.h265-10b.2ch.128kbps.aac.mp4 . under ( HEVC 10-bit depth 3840x2160 @12Mbps ).
 
3. There is no issue in streaming  Encrypted or Clear  H.264 URLs . 

**Reproduction Steps** 

1. Provision Android platform with  Playready 3.0+ DRM license  . 
2. Modify the demo App to  support Playready 3.0+ URLs  .
3. Install the APK and Stream the Contents  corresponding to Encrypted  HEVC File .  

Logcat logs :  Logcat logs for good and bad cases are attached  

[logcat_encrypt.txt](https://github.com/google/ExoPlayer/files/8122017/logcat_encrypt.txt)
[logcat_clear.txt](https://github.com/google/ExoPlayer/files/8122018/logcat_clear.txt)

 **URI to test content for reproduction**
 http://profficialsite.origin.mediaservices.windows.net/58505412-db41-447b-8adc-727811182ac3/tearsofsteel_4k_60s_24fps.12000kbps.3840x2160.h265-10b.2ch.128kbps.aac.audioclear.cenc.mp4

- For protected content:
- DRM scheme and license server URL
DRM scheme : Playready  
license server URL  :  https://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(persist:false,sl:150)
- ExoPlayer version number : [r2.16.1](https://github.com/google/ExoPlayer/releases/tag/r2.16.1)
- Android version RQ3A.210705.001
- Android device  : Android automotive based on stock AOS

**Analysis**
Please refer to  EncryptedHEVC+AAC_Plyback_issue.pdf  
[EncryptedHEVC+AAC_Plyback_issue.pdf](https://github.com/google/ExoPlayer/files/8122015/EncryptedHEVC%2BAAC_Plyback_issue.pdf)

Log Snippet for Issue case  
----------------------------------
02-08 19:18:21.008   978  6634 V C2SoftAacDec: AAC decoder using MPEG-D DRC effect type 3
02-08 19:18:21.008   978  6634 V C2SoftAacDec: AAC decoder using MPEG-D DRC album mode 0
02-08 19:18:21.008   978  6634 V C2SoftAacDec: AAC decoder using maximum output channel count 8
02-08 19:18:21.008   978  6634 W C2SoftAacDec: aacDecoder_DecodeFrame decoderErr = 0x0005
02-08 19:18:21.008   978  6634 W C2SoftAacDec: AAC decoder returned error 0x0005, substituting silence
02-08 19:18:21.008   978  6634 D C2SoftAacDec: Invalid AAC stream
02-08 19:18:21.008   978  6634 V C2SoftAacDec: size = 0
02-08 19:18:21.008   978  6634 V C2SoftAacDec: outInfo.frameIndex = 86
02-08 19:18:21.008   978  6634 V C2SoftAacDec: 0 samples available (0), or 1 frames
02-08 19:18:21.008   978  6634 V C2SoftAacDec: getting 0 from ringbuffer
02-08 19:18:21.008   978  6634 V C2SoftAacDec: out timestamp 61987000 / 0
02-08 19:18:21.154  6606  6606 E QTI_SDM_INFO: [qti_rmnet_peripheral.c:768] qti_file_open():Could not open device file. Errno 2 error msg=No such file or directory
02-08 19:18:21.845   778  1651 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
02-08 19:18:22.148  5148  5148 E EventLogger: internalError [3.29, loadError]
02-08 19:18:22.148  5148  5148 E EventLogger: com.google.android.exoplayer2.ParserException: Offset to end of mdat was negative.
02-08 19:18:22.148  5148  5148 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1081)
02-08 19:18:22.148  5148  5148 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:286)
02-08 19:18:22.148  5148  5148 E EventLogger: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:749)
02-08 19:18:22.148  5148  5148 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
02-08 19:18:22.148  5148  5148 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-08 19:18:22.148  5148  5148 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-08 19:18:22.148  5148  5148 E EventLogger: 	at java.lang.Thread.run(Thread.java:923)

**Request**
Can the team please  help check issue  .

**Comment by santoshray** [comment]
Hi christosts , 
Can you please help check the issue  ?
If you need more information then let us know .

**Comment by christosts** [comment]
Apologies for the late response. I can repro with the demo app (r2.17.1) on a TV with Playready support.

@icbaker do you know if there is an issue with decrypting MP4 files directly (the content is not DASH nor HLS)?
@andrewlewis any thoughts on the FragmentedMp4Extractor?

[edit]
Stack trace error with 2.17.1
```
E/EventLogger: internalError [eventTime=1.97, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.ParserException: Offset to end of mdat was negative.
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1326)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:342)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
    ]
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.ParserException: Offset to end of mdat was negative.
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1326)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:342)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by icbaker** [comment]
The stack trace points to a problem with the fMP4 container, which is parsed before anything is passed to the PlayReady CDM for decryption. 

Without analysing the files in detail I would suspect that the reason you only see the problem with the encrypted file is because the preparation process is creating an invalid fMP4 file.

The exception is happening when mdat atoms overlap:
https://github.com/google/ExoPlayer/blob/8129675b065bc98330ec775fb7a538c139793070/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mp4/FragmentedMp4Extractor.java#L1322-L1328

I'm afraid we don't have the resources to analyse every piece of seemingly broken media - but the error you're seeing does look like an invalid MP4 container.

I did try playing the file on a Chromecast with Google TV and it failed with a different error from the DRM layer [1] - possibly because it doesn't support SL3000? Not sure.

<details>
  <summary>DRM error logcat snippet (from 2.17.1)</summary>

```
2022-03-25 18:04:39.923 3577-3619/? V/PlayReadySessionManager: createSession >>
2022-03-25 18:04:39.923 3577-3619/? V/PlayReadyContext: initialize >>
2022-03-25 18:04:39.949 10665-10665/com.google.android.exoplayer2.demo D/EventLogger: downstreamFormat [eventTime=0.75, mediaPos=0.00, window=0, period=0, id=1, mimeType=video/hevc, codecs=hvc1.2.4.L150.90, drm=[playready], res=3840x2160]
2022-03-25 18:04:39.949 3577-3619/? V/PLAYREADYSDK: PLAYREADY version:Version:4.0.0.5102.72da2ae7
2022-03-25 18:04:39.949 3577-3619/? V/PLAYREADYSDK: PLAYREADY git version:72da2ae7078fe8b5ca205ff655a3e2ed28d580e2-with-1-dirty-files
2022-03-25 18:04:39.949 3577-3619/? V/PLAYREADYSDK: PLAYREADY version serial:400000072da2ae7
2022-03-25 18:04:39.949 3577-3619/? V/PLAYREADYSDK: PLAYREADY Last Changed:Date: Tue Sep 10 10:24:09 2019 +0800
2022-03-25 18:04:39.949 3577-3619/? V/PLAYREADYSDK: PLAYREADY Last Build: Sun Jan 19 12:31:22 CST 2020
2022-03-25 18:04:39.949 3577-3619/? V/PLAYREADYSDK: PLAYREADY Builer Name: kai.song
2022-03-25 18:04:39.951 3577-3619/? D/PlayReadySecureOs: PRSecure_set_HWID/244
2022-03-25 18:04:39.951 3577-3619/? D/PlayReadySecureOs: PRSecure_Initialize,41  TDK 
2022-03-25 18:04:39.959 10759-10759/? E/hdcp_tx22: [TX] Authenticating...
2022-03-25 18:04:39.965 10759-10759/? E/hdcp_tx22: FSM STATE_PRE_AUTH
2022-03-25 18:04:39.966 10759-10759/? E/hdcp_tx22: [TX] bypass mode
2022-03-25 18:04:39.966 10759-10759/? E/hdcp_tx22: [TX] Authentication failed.  Retrying...
2022-03-25 18:04:39.971 10759-10759/? E/hdcp_tx22: FSM STATE_CONNECTED
2022-03-25 18:04:39.977 3577-3619/? D/PlayReadySecureOs: TEEC_OpenSession svc_id=9a04f079-9840-4286
2022-03-25 18:04:39.996 3577-3619/? D/PlayReadySecureOs: TEEC_AllocateSharedMemory tee size=0x200000
2022-03-25 18:04:40.109 3577-3619/? V/PlayReadySession: create >>
2022-03-25 18:04:40.109 3577-3619/? V/PlayReadySession: PPlayReadySession >> sessionId = PR0
2022-03-25 18:04:40.109 3577-3619/? V/PlayReadyDrmPlugin: openSession << sessionID = PR0
2022-03-25 18:04:40.112 10665-10665/com.google.android.exoplayer2.demo D/EventLogger: drmSessionAcquired [eventTime=0.92, mediaPos=0.00, window=0, period=0, state=3]
2022-03-25 18:04:40.112 3577-3619/? I/PlayReadyDrmPlugin: getKeyRequest KeyType = 1
2022-03-25 18:04:40.112 3577-3619/? V/PlayReadySessionManager: getSession >>  session id [PR0]
2022-03-25 18:04:40.112 3577-3619/? V/PlayReadyDrmPlugin: getKeyRequest >> init_data_size = 648 
2022-03-25 18:04:40.112 3577-3619/? V/PlayReadyDrmPlugin: getKeyRequest >> Found PSSH from initData: 32, 616
2022-03-25 18:04:40.112 3577-3619/? V/PlayReadySession: generateLicenseChallenge  mSessionId [PR0]
2022-03-25 18:04:40.143 3577-3619/? V/PlayReadyContext: Drm_LicenseAcq_GenerateChallenge1: urlSize 58, challengeSize 6840
2022-03-25 18:04:40.189 3577-3619/? E/PlayReadyUtil: Cannot find <KID>
2022-03-25 18:04:40.189 3577-3619/? E/PlayReadySession: Cannot extract kid
2022-03-25 18:04:40.189 3577-3619/? E/PlayReadySession: registerLicenseChallenge() failed
2022-03-25 18:04:40.189 3577-3619/? E/PlayReadyDrmPlugin: PlayReadySessionManager::generateLicenseChallenge() failed
2022-03-25 18:04:40.195 10665-10767/com.google.android.exoplayer2.demo E/DefaultDrmSession: DRM session error
      java.lang.IllegalArgumentException: Failed to get key request
        at android.media.MediaDrm.getKeyRequest(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:214)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:481)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:425)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:315)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:790)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:690)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:573)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:519)
        at com.google.android.exoplayer2.source.SampleQueue.onFormatResult(SampleQueue.java:926)
        at com.google.android.exoplayer2.source.SampleQueue.peekSampleMetadata(SampleQueue.java:706)
        at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:423)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.readData(ProgressiveMediaPeriod.java:487)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$SampleStreamImpl.readData(ProgressiveMediaPeriod.java:947)
        at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:425)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:948)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-03-25 18:04:40.199 10665-10665/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=1.00, mediaPos=0.00, window=0, period=0, drmSessionManagerError
      java.lang.IllegalArgumentException: Failed to get key request
        at android.media.MediaDrm.getKeyRequest(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:214)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:481)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:425)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:315)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:790)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:690)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:573)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:519)
        at com.google.android.exoplayer2.source.SampleQueue.onFormatResult(SampleQueue.java:926)
        at com.google.android.exoplayer2.source.SampleQueue.peekSampleMetadata(SampleQueue.java:706)
        at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:423)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.readData(ProgressiveMediaPeriod.java:487)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$SampleStreamImpl.readData(ProgressiveMediaPeriod.java:947)
        at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:425)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:948)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
    ]
```

</details>

**Comment by icbaker** [comment]
Closing because the media is likely invalid.
