### ISSUE TITLE
ParserException after loadManifest

### ISSUE THREAD

**Issue by Kolyall** [google/ExoPlayer#9999]
"com.google.android.exoplayer:extension-okhttp:2.16.1"
```
val client = OkHttpClient.Builder().build()

val okhttpDataSourceFactory = OkHttpDataSource.Factory(okHttpClient)

val okHttpDataSource = okhttpDataSourceFactory.createDataSource()`

val dashManifest = DashUtil.loadManifest(
                formatDataSource,
                dashManifestFileUrl
            )//after call the line error

val drmInitData = DashUtil.loadFormatWithDrmInitData(okHttpDataSource, dashManifest.getPeriod(0))
```
Error:
```
com.google.android.exoplayer2.ParserException
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:108)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:62)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:176)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:66)
        at com.google.android.exoplayer2.source.dash.DashUtil.loadManifest(DashUtil.java:92)
  Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT -Generated with ...@2:1 in java.io.InputStreamReader@6edbee2) 
        at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:432)
        at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:100)
```

**Comment by Kolyall** [comment]
Sometimes:
error is 
```
com.google.android.exoplayer2.ParserException
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:108)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:62)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:176)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:66)
        at com.google.android.exoplayer2.source.dash.DashUtil.loadManifest(DashUtil.java:92)
Caused by: org.xmlpull.v1.XmlPullParserException: Dangling < (position:IGNORABLE_WHITESPACE @2:1 in java.io.InputStreamReader@3cf6bad) 
        at com.android.org.kxml2.io.KXmlParser.peekType(KXmlParser.java:1002)
        at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:448)
        at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:100)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:62) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:176) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:66) 
        at com.google.android.exoplayer2.source.dash.DashUtil.loadManifest(DashUtil.java:92) 
```

**Comment by Kolyall** [comment]
Sometimes error is :
```
  com.google.android.exoplayer2.ParserException: inputStream does not contain a valid media presentation description
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:102)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:62)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:176)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:66)
        at com.google.android.exoplayer2.source.dash.DashUtil.loadManifest(DashUtil.java:92)
```

**Comment by icbaker** [comment]
Please provide a link to a stream (`dashManifestFileUrl ` in your example) that we can use to reproduce the issue (as requested in https://github.com/google/ExoPlayer/issues/9979#issuecomment-1048831726).

**Comment by Kolyall** [comment]
Closed issue was that I forgott add custom Interceptors
